// Puzzle data for Hearsay, the daily epistemic deduction game. Imported ONLY
// by the server page (app/hearsay/page.js), which filters live<=today before
// passing boards to the client, so future boards never ship early.
//
// A shortlist of cards is public. Each character is privately told ONE of the
// secret card's attributes (weekdays two characters, Sundays three), then they
// speak in turn. What they say about their own ignorance is the evidence.
//
// Statement schema (who = the attribute key its speaker was told):
//   dontKnow          "I don't know which it is."
//   know              "Now I know which it is."
//   knowOtherDoesnt   "I don't know it, and I know <other> doesn't either."
//     (carries `other`, the attribute key of the character spoken about)
//
// Semantics are public-announcement logic over the live candidate set S:
//   dontKnow(x)          keep cards whose x-value is shared by >= 2 cards in S
//   know(x)              keep cards whose x-value is unique in S
//   knowOtherDoesnt(x,y) keep cards x cannot pin, where every card sharing that
//                        x-value also has a non-unique y-value
//
// LEAK GUARD: the answer is NOT stored. The client replays this same
// simulation to find the single surviving card, exactly as the generator proved
// it unique. Every board is machine-verified (scripts/verify-hearsay.mjs) to
// leave exactly one card, to narrow at every line, to stay ambiguous until the
// final line, and to be unpinnable from any single attribute at the start.
export const PUZZLES = [
  {
    num: 1, quizId: 'hearsay-7-24-26', live: '2026-07-24', dateLabel: 'July 24, 2026', sunday: false,
    noun: 'bottle', listLabel: 'the cellar list',
    attrs: ['region', 'year'],
    who: ['Odette', 'Rufus'],
    cards: [
      { a: 'Mosel', b: '2014' }, { a: 'Mosel', b: '2016' }, { a: 'Barolo', b: '2014' },
      { a: 'Barolo', b: '2019' }, { a: 'Rioja', b: '2019' }, { a: 'Chinon', b: '2019' },
      { a: 'Rioja', b: '2011' }, { a: 'Rioja', b: '2014' }, { a: 'Rioja', b: '2021' },
    ],
    script: [
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'know' },
    ],
  },
  {
    num: 2, quizId: 'hearsay-7-25-26', live: '2026-07-25', dateLabel: 'July 25, 2026', sunday: false,
    noun: 'sailing', listLabel: 'the harbour board',
    attrs: ['port', 'day'],
    who: ['Marisol', 'Ivo'],
    cards: [
      { a: 'Palermo', b: 'Tuesday' }, { a: 'Split', b: 'Saturday' }, { a: 'Bergen', b: 'Monday' },
      { a: 'Bergen', b: 'Thursday' }, { a: 'Bergen', b: 'Friday' }, { a: 'Tangier', b: 'Tuesday' },
      { a: 'Split', b: 'Tuesday' }, { a: 'Split', b: 'Friday' }, { a: 'Split', b: 'Thursday' },
      { a: 'Tangier', b: 'Sunday' }, { a: 'Cadiz', b: 'Tuesday' },
    ],
    script: [
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 3, quizId: 'hearsay-7-26-26', live: '2026-07-26', dateLabel: 'July 26, 2026', sunday: true,
    noun: 'painting', listLabel: 'the auction catalogue',
    attrs: ['gallery', 'year', 'seal'],
    who: ['Hester', 'Cato', 'Ottoline'],
    cards: [
      { a: 'Corvina', b: '1903', c: 'a black seal' }, { a: 'Fairholme', b: '1928', c: 'a black seal' }, { a: 'Everly', b: '1911', c: 'a blue seal' },
      { a: 'Duxley', b: '1928', c: 'a red seal' }, { a: 'Corvina', b: '1947', c: 'a red seal' }, { a: 'Everly', b: '1947', c: 'a blue seal' },
      { a: 'Everly', b: '1903', c: 'a blue seal' }, { a: 'Fairholme', b: '1947', c: 'a black seal' }, { a: 'Duxley', b: '1903', c: 'a blue seal' },
      { a: 'Corvina', b: '1928', c: 'a blue seal' }, { a: 'Corvina', b: '1934', c: 'a red seal' }, { a: 'Ashcroft', b: '1934', c: 'a red seal' },
      { a: 'Corvina', b: '1952', c: 'a blue seal' }, { a: 'Everly', b: '1928', c: 'a black seal' }, { a: 'Duxley', b: '1911', c: 'a blue seal' },
      { a: 'Fairholme', b: '1911', c: 'a blue seal' }, { a: 'Ashcroft', b: '1928', c: 'a black seal' },
    ],
    script: [
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'dontKnow' },
      { who: 'c', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'stillDontKnow' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 4, quizId: 'hearsay-7-27-26', live: '2026-07-27', dateLabel: 'July 27, 2026', sunday: false,
    noun: 'train', listLabel: 'the departure board',
    attrs: ['platform', 'hour'],
    who: ['Nadia', 'Osric'],
    cards: [
      { a: 'Platform 9', b: '9:15' }, { a: 'Platform 11', b: '6:05' }, { a: 'Platform 7', b: '13:55' },
      { a: 'Platform 11', b: '13:55' }, { a: 'Platform 4', b: '9:15' }, { a: 'Platform 7', b: '9:15' },
      { a: 'Platform 14', b: '16:20' }, { a: 'Platform 11', b: '7:40' }, { a: 'Platform 11', b: '16:20' },
      { a: 'Platform 11', b: '11:30' }, { a: 'Platform 14', b: '11:30' }, { a: 'Platform 9', b: '16:20' },
      { a: 'Platform 4', b: '6:05' },
    ],
    script: [
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'stillDontKnow' },
      { who: 'a', type: 'knowNowOtherStill', other: 'b' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 5, quizId: 'hearsay-7-28-26', live: '2026-07-28', dateLabel: 'July 28, 2026', sunday: false,
    noun: 'birthday', listLabel: 'the shortlist',
    attrs: ['month', 'day'],
    who: ['Delphine', 'Bram'],
    cards: [
      { a: 'August', b: '18th' }, { a: 'March', b: '18th' }, { a: 'April', b: '23rd' },
      { a: 'March', b: '4th' }, { a: 'December', b: '4th' }, { a: 'April', b: '27th' },
      { a: 'March', b: '27th' }, { a: 'October', b: '23rd' }, { a: 'April', b: '18th' },
      { a: 'December', b: '14th' }, { a: 'December', b: '9th' },
    ],
    script: [
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 6, quizId: 'hearsay-7-29-26', live: '2026-07-29', dateLabel: 'July 29, 2026', sunday: false,
    noun: 'room', listLabel: 'the register',
    attrs: ['floor', 'suite'],
    who: ['Simone', 'Auberon'],
    cards: [
      { a: '6th floor', b: 'Suite A' }, { a: '6th floor', b: 'Suite F' }, { a: '3rd floor', b: 'Suite R' },
      { a: '9th floor', b: 'Suite M' }, { a: '3rd floor', b: 'Suite A' }, { a: '8th floor', b: 'Suite C' },
      { a: '8th floor', b: 'Suite M' }, { a: '8th floor', b: 'Suite F' }, { a: '3rd floor', b: 'Suite J' },
      { a: '8th floor', b: 'Suite R' }, { a: '6th floor', b: 'Suite R' }, { a: '9th floor', b: 'Suite J' },
    ],
    script: [
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'stillDontKnow' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 7, quizId: 'hearsay-7-30-26', live: '2026-07-30', dateLabel: 'July 30, 2026', sunday: false,
    noun: 'lot', listLabel: 'the sale sheet',
    attrs: ['house', 'lot'],
    who: ['Perpetua', 'Casimir'],
    cards: [
      { a: 'Ashby', b: 'Lot 27' }, { a: 'Grimaldi', b: 'Lot 74' }, { a: 'Grimaldi', b: 'Lot 27' },
      { a: 'Ives', b: 'Lot 12' }, { a: 'Grimaldi', b: 'Lot 68' }, { a: 'Ashby', b: 'Lot 41' },
      { a: 'Halloran', b: 'Lot 74' }, { a: 'Ives', b: 'Lot 41' }, { a: 'Halloran', b: 'Lot 41' },
      { a: 'Fenwick', b: 'Lot 12' }, { a: 'Fenwick', b: 'Lot 68' }, { a: 'Grimaldi', b: 'Lot 55' },
    ],
    script: [
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'stillDontKnow' },
      { who: 'a', type: 'knowNowOtherStill', other: 'b' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 8, quizId: 'hearsay-7-31-26', live: '2026-07-31', dateLabel: 'July 31, 2026', sunday: false,
    noun: 'painting', listLabel: 'the auction catalogue',
    attrs: ['gallery', 'year'],
    who: ['Hester', 'Cato'],
    cards: [
      { a: 'Fairholme', b: '1911' }, { a: 'Corvina', b: '1928' }, { a: 'Fairholme', b: '1934' },
      { a: 'Everly', b: '1903' }, { a: 'Corvina', b: '1947' }, { a: 'Everly', b: '1947' },
      { a: 'Ashcroft', b: '1947' }, { a: 'Fairholme', b: '1928' }, { a: 'Corvina', b: '1911' },
      { a: 'Everly', b: '1952' }, { a: 'Belvoir', b: '1911' },
    ],
    script: [
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'stillDontKnow' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 9, quizId: 'hearsay-8-1-26', live: '2026-08-01', dateLabel: 'August 1, 2026', sunday: false,
    noun: 'room', listLabel: 'the register',
    attrs: ['floor', 'suite'],
    who: ['Simone', 'Auberon'],
    cards: [
      { a: '6th floor', b: 'Suite J' }, { a: '3rd floor', b: 'Suite R' }, { a: '8th floor', b: 'Suite R' },
      { a: '6th floor', b: 'Suite C' }, { a: '6th floor', b: 'Suite F' }, { a: '3rd floor', b: 'Suite C' },
      { a: '9th floor', b: 'Suite A' }, { a: '6th floor', b: 'Suite A' }, { a: '8th floor', b: 'Suite M' },
      { a: '3rd floor', b: 'Suite M' }, { a: '9th floor', b: 'Suite F' }, { a: '8th floor', b: 'Suite F' },
    ],
    script: [
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'stillDontKnow' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 10, quizId: 'hearsay-8-2-26', live: '2026-08-02', dateLabel: 'August 2, 2026', sunday: true,
    noun: 'bottle', listLabel: 'the cellar list',
    attrs: ['region', 'year', 'seal'],
    who: ['Odette', 'Rufus', 'Ottoline'],
    cards: [
      { a: 'Etna', b: '2011', c: 'a blue seal' }, { a: 'Etna', b: '2019', c: 'a green seal' }, { a: 'Douro', b: '2014', c: 'a blue seal' },
      { a: 'Douro', b: '2021', c: 'a green seal' }, { a: 'Barolo', b: '2021', c: 'a blue seal' }, { a: 'Rioja', b: '2019', c: 'a blue seal' },
      { a: 'Mosel', b: '2014', c: 'a green seal' }, { a: 'Barolo', b: '2014', c: 'a blue seal' }, { a: 'Barolo', b: '2023', c: 'a red seal' },
      { a: 'Mosel', b: '2011', c: 'a green seal' }, { a: 'Douro', b: '2016', c: 'a green seal' }, { a: 'Rioja', b: '2023', c: 'a green seal' },
      { a: 'Mosel', b: '2023', c: 'a green seal' }, { a: 'Douro', b: '2019', c: 'a red seal' }, { a: 'Etna', b: '2023', c: 'a blue seal' },
    ],
    script: [
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'dontKnow' },
      { who: 'c', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'stillDontKnow' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 11, quizId: 'hearsay-8-3-26', live: '2026-08-03', dateLabel: 'August 3, 2026', sunday: false,
    noun: 'train', listLabel: 'the departure board',
    attrs: ['platform', 'hour'],
    who: ['Nadia', 'Osric'],
    cards: [
      { a: 'Platform 2', b: '13:55' }, { a: 'Platform 14', b: '9:15' }, { a: 'Platform 4', b: '7:40' },
      { a: 'Platform 11', b: '6:05' }, { a: 'Platform 14', b: '16:20' }, { a: 'Platform 2', b: '16:20' },
      { a: 'Platform 11', b: '11:30' }, { a: 'Platform 4', b: '6:05' }, { a: 'Platform 11', b: '13:55' },
      { a: 'Platform 11', b: '9:15' }, { a: 'Platform 7', b: '16:20' }, { a: 'Platform 7', b: '7:40' },
      { a: 'Platform 11', b: '16:20' },
    ],
    script: [
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'stillDontKnow' },
      { who: 'a', type: 'knowNowOtherStill', other: 'b' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 12, quizId: 'hearsay-8-4-26', live: '2026-08-04', dateLabel: 'August 4, 2026', sunday: false,
    noun: 'lot', listLabel: 'the sale sheet',
    attrs: ['house', 'lot'],
    who: ['Perpetua', 'Casimir'],
    cards: [
      { a: 'Ashby', b: 'Lot 74' }, { a: 'Grimaldi', b: 'Lot 41' }, { a: 'Fenwick', b: 'Lot 41' },
      { a: 'Ashby', b: 'Lot 27' }, { a: 'Halloran', b: 'Lot 12' }, { a: 'Halloran', b: 'Lot 74' },
      { a: 'Fenwick', b: 'Lot 68' }, { a: 'Grimaldi', b: 'Lot 68' }, { a: 'Ashby', b: 'Lot 55' },
      { a: 'Grimaldi', b: 'Lot 12' }, { a: 'Ives', b: 'Lot 41' }, { a: 'Fenwick', b: 'Lot 27' },
    ],
    script: [
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'stillDontKnow' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 13, quizId: 'hearsay-8-5-26', live: '2026-08-05', dateLabel: 'August 5, 2026', sunday: false,
    noun: 'sailing', listLabel: 'the harbour board',
    attrs: ['port', 'day'],
    who: ['Marisol', 'Ivo'],
    cards: [
      { a: 'Cadiz', b: 'Thursday' }, { a: 'Palermo', b: 'Sunday' }, { a: 'Palermo', b: 'Monday' },
      { a: 'Kotor', b: 'Monday' }, { a: 'Bergen', b: 'Sunday' }, { a: 'Bergen', b: 'Friday' },
      { a: 'Tangier', b: 'Tuesday' }, { a: 'Palermo', b: 'Thursday' }, { a: 'Tangier', b: 'Sunday' },
      { a: 'Bergen', b: 'Saturday' }, { a: 'Palermo', b: 'Tuesday' }, { a: 'Cadiz', b: 'Saturday' },
    ],
    script: [
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'stillDontKnow' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 14, quizId: 'hearsay-8-6-26', live: '2026-08-06', dateLabel: 'August 6, 2026', sunday: false,
    noun: 'birthday', listLabel: 'the shortlist',
    attrs: ['month', 'day'],
    who: ['Delphine', 'Bram'],
    cards: [
      { a: 'June', b: '9th' }, { a: 'August', b: '27th' }, { a: 'June', b: '4th' },
      { a: 'April', b: '18th' }, { a: 'June', b: '23rd' }, { a: 'June', b: '27th' },
      { a: 'June', b: '18th' }, { a: 'August', b: '14th' }, { a: 'March', b: '9th' },
      { a: 'April', b: '4th' }, { a: 'March', b: '14th' }, { a: 'October', b: '14th' },
      { a: 'October', b: '4th' },
    ],
    script: [
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'stillDontKnow' },
      { who: 'a', type: 'knowNowOtherStill', other: 'b' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 15, quizId: 'hearsay-8-7-26', live: '2026-08-07', dateLabel: 'August 7, 2026', sunday: false,
    noun: 'crossing', listLabel: 'the ferry timetable',
    attrs: ['island', 'time'],
    who: ['Emeric', 'Marguerite'],
    cards: [
      { a: 'Innismore', b: '19:45' }, { a: 'Doorna', b: '19:45' }, { a: 'Skarva', b: '19:45' },
      { a: 'Doorna', b: '11:05' }, { a: 'Skarva', b: '13:30' }, { a: 'Skarva', b: '11:05' },
      { a: 'Skarva', b: '06:40' }, { a: 'Blaskett', b: '19:45' }, { a: 'Ronaby', b: '08:15' },
      { a: 'Ronaby', b: '06:40' }, { a: 'Innismore', b: '16:20' },
    ],
    script: [
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'stillDontKnow' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 16, quizId: 'hearsay-8-8-26', live: '2026-08-08', dateLabel: 'August 8, 2026', sunday: false,
    noun: 'manuscript', listLabel: 'the reading room slip',
    attrs: ['hand', 'binding'],
    who: ['Lazlo', 'Leopold'],
    cards: [
      { a: 'a court hand', b: 'calf over oak' }, { a: 'a merchant hand', b: 'a green morocco' }, { a: 'a court hand', b: 'a green morocco' },
      { a: 'a secretary hand', b: 'a chained binding' }, { a: 'a chancery hand', b: 'a plain wrapper' }, { a: 'a court hand', b: 'a plain wrapper' },
      { a: 'a merchant hand', b: 'vellum boards' }, { a: 'a chancery hand', b: 'a limp binding' }, { a: 'an italic hand', b: 'calf over oak' },
      { a: 'a monastic hand', b: 'a plain wrapper' }, { a: 'a court hand', b: 'vellum boards' }, { a: 'a secretary hand', b: 'a green morocco' },
    ],
    script: [
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 17, quizId: 'hearsay-8-9-26', live: '2026-08-09', dateLabel: 'August 9, 2026', sunday: true,
    noun: 'timepiece', listLabel: 'the strongroom register',
    attrs: ['maker', 'case', 'dial'],
    who: ['Delphine', 'Osric', 'Ottoline'],
    cards: [
      { a: 'Kestner', b: 'an enamel case', c: 'a champagne dial' }, { a: 'Sallevoy', b: 'a gold case', c: 'a blue dial' }, { a: 'Vaubert', b: 'a steel case', c: 'a champagne dial' },
      { a: 'Sallevoy', b: 'an enamel case', c: 'a white dial' }, { a: 'Ormond', b: 'a gold case', c: 'a black dial' }, { a: 'Ormond', b: 'a steel case', c: 'a champagne dial' },
      { a: 'Sallevoy', b: 'a silver case', c: 'a white dial' }, { a: 'Ormond', b: 'a silver case', c: 'a champagne dial' }, { a: 'Ormond', b: 'a steel case', c: 'a blue dial' },
      { a: 'Kestner', b: 'an enamel case', c: 'a blue dial' }, { a: 'Ormond', b: 'a silver case', c: 'a blue dial' }, { a: 'Sallevoy', b: 'a brass case', c: 'a black dial' },
      { a: 'Ingram', b: 'a steel case', c: 'a blue dial' }, { a: 'Ingram', b: 'a silver case', c: 'a white dial' }, { a: 'Vaubert', b: 'a gold case', c: 'a champagne dial' },
    ],
    script: [
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'c', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'a', type: 'stillDontKnow' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'c' },
      { who: 'a', type: 'know' },
    ],
  },
  {
    num: 18, quizId: 'hearsay-8-10-26', live: '2026-08-10', dateLabel: 'August 10, 2026', sunday: false,
    noun: 'reservation', listLabel: 'the booking sheet',
    attrs: ['room', 'party'],
    who: ['Clemence', 'Ottoline'],
    cards: [
      { a: 'the Cellar', b: 'a party of twelve' }, { a: 'the Long Room', b: 'a party of eight' }, { a: 'the Orangery', b: 'a party of two' },
      { a: 'the Library', b: 'a party of three' }, { a: 'the Orangery', b: 'a party of six' }, { a: 'the Library', b: 'a party of twelve' },
      { a: 'the Library', b: 'a party of eight' }, { a: 'the Long Room', b: 'a party of twelve' }, { a: 'the Long Room', b: 'a party of three' },
      { a: 'the Terrace', b: 'a party of two' }, { a: 'the Long Room', b: 'a party of four' }, { a: 'the Terrace', b: 'a party of six' },
      { a: 'the Long Room', b: 'a party of six' }, { a: 'the Garden Room', b: 'a party of six' }, { a: 'the Orangery', b: 'a party of twelve' },
    ],
    script: [
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'stillDontKnow' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 19, quizId: 'hearsay-8-11-26', live: '2026-08-11', dateLabel: 'August 11, 2026', sunday: false,
    noun: 'watch', listLabel: 'the repair ledger',
    attrs: ['maker', 'case'],
    who: ['Rosalind', 'Merrick'],
    cards: [
      { a: 'Kestner', b: 'a titanium case' }, { a: 'Petrie', b: 'a gold case' }, { a: 'Ormond', b: 'an enamel case' },
      { a: 'Kestner', b: 'a steel case' }, { a: 'Sallevoy', b: 'a gold case' }, { a: 'Ormond', b: 'a brass case' },
      { a: 'Petrie', b: 'an enamel case' }, { a: 'Vaubert', b: 'a titanium case' }, { a: 'Kestner', b: 'a gold case' },
      { a: 'Kestner', b: 'a rose gold case' }, { a: 'Ingram', b: 'a steel case' }, { a: 'Ingram', b: 'a titanium case' },
    ],
    script: [
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'know' },
    ],
  },
  {
    num: 20, quizId: 'hearsay-8-12-26', live: '2026-08-12', dateLabel: 'August 12, 2026', sunday: false,
    noun: 'meteorite', listLabel: 'the specimen drawer',
    attrs: ['fall', 'mass'],
    who: ['Ivo', 'Ottoline'],
    cards: [
      { a: 'Sikhote', b: '480 g' }, { a: 'Kalder', b: '480 g' }, { a: 'Bellamy Flat', b: '1.2 kg' },
      { a: 'Kalder', b: '210 g' }, { a: 'Kalder', b: '1.2 kg' }, { a: 'Bellamy Flat', b: '210 g' },
      { a: 'Sikhote', b: '1.2 kg' }, { a: 'Tanezrouft', b: '40 g' }, { a: 'Ostrava', b: '12 g' },
      { a: 'Bellamy Flat', b: '12 g' }, { a: 'Kalder', b: '96 g' }, { a: 'Cape Ruin', b: '12 g' },
      { a: 'Kalder', b: '40 g' }, { a: 'Cape Ruin', b: '1.2 kg' }, { a: 'Tanezrouft', b: '480 g' },
    ],
    script: [
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'stillDontKnow' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 21, quizId: 'hearsay-8-13-26', live: '2026-08-13', dateLabel: 'August 13, 2026', sunday: false,
    noun: 'racehorse', listLabel: 'the paddock sheet',
    attrs: ['stable', 'colours'],
    who: ['Genevieve', 'Ambrose'],
    cards: [
      { a: 'Ellerslie', b: 'violet hoops' }, { a: 'Ninebarrow', b: 'scarlet' }, { a: 'Ninebarrow', b: 'navy and white' },
      { a: 'Coldstream', b: 'violet hoops' }, { a: 'Prideaux', b: 'green and gold' }, { a: 'Ellerslie', b: 'black and amber' },
      { a: 'Halloway', b: 'violet hoops' }, { a: 'Prideaux', b: 'navy and white' }, { a: 'Thornfell', b: 'green and gold' },
      { a: 'Ninebarrow', b: 'black and amber' }, { a: 'Coldstream', b: 'scarlet' }, { a: 'Prideaux', b: 'grey with a red sash' },
    ],
    script: [
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 22, quizId: 'hearsay-8-14-26', live: '2026-08-14', dateLabel: 'August 14, 2026', sunday: false,
    noun: 'fresco', listLabel: 'the conservation file',
    attrs: ['chapel', 'condition'],
    who: ['Osric', 'Delphine'],
    cards: [
      { a: 'the chapter house', b: 'sound' }, { a: 'the lady chapel', b: 'water damaged' }, { a: 'the north chapel', b: 'water damaged' },
      { a: 'the apse', b: 'water damaged' }, { a: 'the crypt', b: 'sound' }, { a: 'the north chapel', b: 'sound' },
      { a: 'the nave', b: 'sound' }, { a: 'the north chapel', b: 'soot darkened' }, { a: 'the nave', b: 'flaking' },
      { a: 'the chapter house', b: 'flaking' }, { a: 'the crypt', b: 'overpainted' }, { a: 'the lady chapel', b: 'soot darkened' },
      { a: 'the crypt', b: 'partly lost' },
    ],
    script: [
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'stillDontKnow' },
      { who: 'a', type: 'know' },
    ],
  },
  {
    num: 23, quizId: 'hearsay-8-15-26', live: '2026-08-15', dateLabel: 'August 15, 2026', sunday: false,
    noun: 'moth', listLabel: 'the trap record',
    attrs: ['species', 'night'],
    who: ['Marisol', 'Hester'],
    cards: [
      { a: 'the peppered', b: '3 June' }, { a: 'the angle shades', b: '11 June' }, { a: 'the poplar hawk', b: '2 July' },
      { a: 'the poplar hawk', b: '19 June' }, { a: 'the garden tiger', b: '11 June' }, { a: 'the garden tiger', b: '19 June' },
      { a: 'the elephant hawk', b: '3 June' }, { a: 'the poplar hawk', b: '26 July' }, { a: 'the peppered', b: '11 June' },
      { a: 'the angle shades', b: '19 June' }, { a: 'the poplar hawk', b: '14 July' }, { a: 'the angle shades', b: '26 July' },
      { a: 'the buff arches', b: '11 June' },
    ],
    script: [
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'know' },
    ],
  },
  {
    num: 24, quizId: 'hearsay-8-16-26', live: '2026-08-16', dateLabel: 'August 16, 2026', sunday: true,
    noun: 'garden', listLabel: 'the estate survey',
    attrs: ['quarter', 'hedge', 'gate'],
    who: ['Silas', 'Marguerite', 'Clemence'],
    cards: [
      { a: 'the walled quarter', b: 'a yew hedge', c: 'a stone arch' }, { a: 'the east quarter', b: 'a privet hedge', c: 'a wicket gate' }, { a: 'the walled quarter', b: 'a privet hedge', c: 'a stone arch' },
      { a: 'the lower quarter', b: 'a yew hedge', c: 'a stone arch' }, { a: 'the west quarter', b: 'a box hedge', c: 'a stone arch' }, { a: 'the lower quarter', b: 'a beech hedge', c: 'a green gate' },
      { a: 'the lower quarter', b: 'a beech hedge', c: 'a stone arch' }, { a: 'the walled quarter', b: 'a box hedge', c: 'a stone arch' }, { a: 'the east quarter', b: 'a yew hedge', c: 'a stone arch' },
      { a: 'the west quarter', b: 'a box hedge', c: 'a green gate' }, { a: 'the old quarter', b: 'a box hedge', c: 'an iron gate' }, { a: 'the east quarter', b: 'a holly hedge', c: 'a green gate' },
      { a: 'the west quarter', b: 'a yew hedge', c: 'an iron gate' }, { a: 'the lower quarter', b: 'a holly hedge', c: 'a green gate' }, { a: 'the lower quarter', b: 'a yew hedge', c: 'an iron gate' },
      { a: 'the walled quarter', b: 'a box hedge', c: 'a wicket gate' },
    ],
    script: [
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'c' },
      { who: 'c', type: 'dontKnow' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'c', type: 'know' },
    ],
  },
  {
    num: 25, quizId: 'hearsay-8-17-26', live: '2026-08-17', dateLabel: 'August 17, 2026', sunday: false,
    noun: 'lot', listLabel: 'the saleroom list',
    attrs: ['house', 'estimate'],
    who: ['Merrick', 'Beatrix'],
    cards: [
      { a: 'Brightmoor', b: '£2,600' }, { a: 'Cantelow', b: '£900' }, { a: 'Brightmoor', b: '£7,800' },
      { a: 'Marchwood', b: '£400' }, { a: 'Sallow & Kean', b: '£900' }, { a: 'Vendrell', b: '£900' },
      { a: 'Cantelow', b: '£400' }, { a: 'Pike Hall', b: '£4,200' }, { a: 'Vendrell', b: '£400' },
      { a: 'Cantelow', b: '£7,800' }, { a: 'Brightmoor', b: '£4,200' },
    ],
    script: [
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 26, quizId: 'hearsay-8-18-26', live: '2026-08-18', dateLabel: 'August 18, 2026', sunday: false,
    noun: 'bridge', listLabel: 'the works schedule',
    attrs: ['river', 'span'],
    who: ['Delphine', 'Clemence'],
    cards: [
      { a: 'the Ouse', b: '27 metres' }, { a: 'the Ouse', b: '18 metres' }, { a: 'the Torridge', b: '44 metres' },
      { a: 'the Cregan', b: '120 metres' }, { a: 'the Cregan', b: '44 metres' }, { a: 'the Torridge', b: '88 metres' },
      { a: 'the Aln', b: '120 metres' }, { a: 'the Torridge', b: '18 metres' }, { a: 'the Weald', b: '61 metres' },
      { a: 'the Torridge', b: '120 metres' }, { a: 'the Marne', b: '61 metres' }, { a: 'the Marne', b: '88 metres' },
    ],
    script: [
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'stillDontKnow' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 27, quizId: 'hearsay-8-19-26', live: '2026-08-19', dateLabel: 'August 19, 2026', sunday: false,
    noun: 'delivery', listLabel: 'the depot manifest',
    attrs: ['depot', 'crate'],
    who: ['Hollis', 'Thaddeus'],
    cards: [
      { a: 'Hallowfield', b: 'crate 46' }, { a: 'Northgate', b: 'crate 11' }, { a: 'Sarn Cross', b: 'crate 17' },
      { a: 'Hallowfield', b: 'crate 38' }, { a: 'Wexbury', b: 'crate 23' }, { a: 'Wexbury', b: 'crate 38' },
      { a: 'Pennick', b: 'crate 38' }, { a: 'Pennick', b: 'crate 11' }, { a: 'Wexbury', b: 'crate 46' },
      { a: 'Wexbury', b: 'crate 04' }, { a: 'Sarn Cross', b: 'crate 04' },
    ],
    script: [
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'stillDontKnow' },
      { who: 'a', type: 'know' },
    ],
  },
  {
    num: 28, quizId: 'hearsay-8-20-26', live: '2026-08-20', dateLabel: 'August 20, 2026', sunday: false,
    noun: 'flat', listLabel: 'the letting register',
    attrs: ['street', 'floor'],
    who: ['Ottoline', 'Marisol'],
    cards: [
      { a: 'Pell Street', b: 'the third floor' }, { a: 'Marlow Row', b: 'the ground floor' }, { a: 'Pell Street', b: 'the first floor' },
      { a: 'Marlow Row', b: 'the top floor' }, { a: 'Pell Street', b: 'the second floor' }, { a: 'Ashby Lane', b: 'the ground floor' },
      { a: 'Ivy Walk', b: 'the third floor' }, { a: 'Pell Street', b: 'the ground floor' }, { a: 'Ivy Walk', b: 'the fourth floor' },
      { a: 'Quill Court', b: 'the second floor' }, { a: 'Ashby Lane', b: 'the second floor' },
    ],
    script: [
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 29, quizId: 'hearsay-8-21-26', live: '2026-08-21', dateLabel: 'August 21, 2026', sunday: false,
    noun: 'seed lot', listLabel: 'the seed bank card',
    attrs: ['origin', 'store'],
    who: ['Delphine', 'Cressida'],
    cards: [
      { a: 'Anatolia', b: 'vault 17' }, { a: 'Hokkaido', b: 'vault 8' }, { a: 'Hokkaido', b: 'vault 3' },
      { a: 'the Andes', b: 'vault 6' }, { a: 'Yunnan', b: 'vault 1' }, { a: 'Hokkaido', b: 'vault 1' },
      { a: 'Anatolia', b: 'vault 8' }, { a: 'the Andes', b: 'vault 17' }, { a: 'Hokkaido', b: 'vault 12' },
      { a: 'Sardinia', b: 'vault 6' }, { a: 'Hokkaido', b: 'vault 6' }, { a: 'Yunnan', b: 'vault 3' },
      { a: 'the Rift Valley', b: 'vault 1' }, { a: 'the Rift Valley', b: 'vault 17' }, { a: 'the Andes', b: 'vault 8' },
    ],
    script: [
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 30, quizId: 'hearsay-8-22-26', live: '2026-08-22', dateLabel: 'August 22, 2026', sunday: false,
    noun: 'orchid', listLabel: 'the glasshouse log',
    attrs: ['house', 'bloom'],
    who: ['Ambrose', 'Lazlo'],
    cards: [
      { a: 'the Palm House', b: 'pale green' }, { a: 'the Cold House', b: 'speckled yellow' }, { a: 'the Cold House', b: 'crimson' },
      { a: 'the Alpine House', b: 'pale green' }, { a: 'the Water House', b: 'white' }, { a: 'the Palm House', b: 'deep violet' },
      { a: 'the Fern House', b: 'pale green' }, { a: 'the Water House', b: 'crimson' }, { a: 'the Bark House', b: 'white' },
      { a: 'the Cold House', b: 'deep violet' }, { a: 'the Alpine House', b: 'speckled yellow' }, { a: 'the Water House', b: 'copper' },
    ],
    script: [
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 31, quizId: 'hearsay-8-23-26', live: '2026-08-23', dateLabel: 'August 23, 2026', sunday: true,
    noun: 'dispatch', listLabel: 'the signal book',
    attrs: ['station', 'hour', 'cipher'],
    who: ['Barnaby', 'Hollis', 'Hester'],
    cards: [
      { a: 'Amberline', b: '05:00', c: 'the plain cipher' }, { a: 'Greyquay', b: '17:00', c: 'the double cipher' }, { a: 'Torhaven', b: '05:00', c: 'the field cipher' },
      { a: 'Amberline', b: '11:00', c: 'the field cipher' }, { a: 'Amberline', b: '23:00', c: 'the plain cipher' }, { a: 'Norlan', b: '23:00', c: 'the red cipher' },
      { a: 'Amberline', b: '02:00', c: 'the field cipher' }, { a: 'Greyquay', b: '05:00', c: 'the field cipher' }, { a: 'Amberline', b: '05:00', c: 'the red cipher' },
      { a: 'Amberline', b: '17:00', c: 'the plain cipher' }, { a: 'Vesk', b: '02:00', c: 'the plain cipher' }, { a: 'Amberline', b: '02:00', c: 'the double cipher' },
      { a: 'Amberline', b: '05:00', c: 'the double cipher' }, { a: 'Amberline', b: '11:00', c: 'the double cipher' }, { a: 'Greyquay', b: '05:00', c: 'the red cipher' },
      { a: 'Vesk', b: '05:00', c: 'the plain cipher' }, { a: 'Vesk', b: '02:00', c: 'the red cipher' }, { a: 'Greyquay', b: '05:00', c: 'the plain cipher' },
    ],
    script: [
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'dontKnow' },
      { who: 'c', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'c' },
      { who: 'c', type: 'know' },
    ],
  },
  {
    num: 32, quizId: 'hearsay-8-24-26', live: '2026-08-24', dateLabel: 'August 24, 2026', sunday: false,
    noun: 'painting', listLabel: 'the gallery ledger',
    attrs: ['gallery', 'year'],
    who: ['Juno', 'Delphine'],
    cards: [
      { a: 'Corvina', b: '1947' }, { a: 'Duxley', b: '1903' }, { a: 'Corvina', b: '1952' },
      { a: 'Corvina', b: '1934' }, { a: 'Duxley', b: '1934' }, { a: 'Ashcroft', b: '1947' },
      { a: 'Fairholme', b: '1934' }, { a: 'Wrenfield', b: '1928' }, { a: 'Everly', b: '1952' },
      { a: 'Wrenfield', b: '1934' }, { a: 'Ashcroft', b: '1928' }, { a: 'Everly', b: '1903' },
      { a: 'Everly', b: '1947' }, { a: 'Ashcroft', b: '1911' },
    ],
    script: [
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'stillDontKnow' },
      { who: 'a', type: 'know' },
    ],
  },
  {
    num: 33, quizId: 'hearsay-8-25-26', live: '2026-08-25', dateLabel: 'August 25, 2026', sunday: false,
    noun: 'recording', listLabel: 'the tape index',
    attrs: ['studio', 'reel'],
    who: ['Anouk', 'Odette'],
    cards: [
      { a: 'Corris Lane', b: 'reel 8' }, { a: 'Old Foundry', b: 'reel 2' }, { a: 'Kestrel Yard', b: 'reel 5' },
      { a: 'Ashmount', b: 'reel 19' }, { a: 'Kestrel Yard', b: 'reel 27' }, { a: 'Old Foundry', b: 'reel 12' },
      { a: 'Old Foundry', b: 'reel 5' }, { a: 'Ashmount', b: 'reel 2' }, { a: 'Bellwater', b: 'reel 12' },
      { a: 'Ashmount', b: 'reel 8' }, { a: 'Nine Elms', b: 'reel 2' },
    ],
    script: [
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'knowNowOtherStill', other: 'a' },
      { who: 'a', type: 'know' },
    ],
  },
  {
    num: 34, quizId: 'hearsay-8-26-26', live: '2026-08-26', dateLabel: 'August 26, 2026', sunday: false,
    noun: 'application', listLabel: 'the college roll',
    attrs: ['college', 'subject'],
    who: ['Hester', 'Casper'],
    cards: [
      { a: 'Ashgrove', b: 'architecture' }, { a: 'Rookwood', b: 'architecture' }, { a: 'Templeton', b: 'law' },
      { a: 'Templeton', b: 'zoology' }, { a: 'Templeton', b: 'music' }, { a: 'Ashgrove', b: 'classics' },
      { a: 'Fenchurch', b: 'law' }, { a: 'Carrickfell', b: 'architecture' }, { a: 'Carrickfell', b: 'zoology' },
      { a: 'Marlborough', b: 'law' }, { a: 'Marlborough', b: 'zoology' },
    ],
    script: [
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'stillDontKnow' },
      { who: 'a', type: 'know' },
    ],
  },
  {
    num: 35, quizId: 'hearsay-8-27-26', live: '2026-08-27', dateLabel: 'August 27, 2026', sunday: false,
    noun: 'bell', listLabel: 'the tower register',
    attrs: ['foundry', 'weight'],
    who: ['Sabine', 'Delphine'],
    cards: [
      { a: 'Marchmont', b: '16 cwt' }, { a: 'Norton Bell', b: '4 cwt' }, { a: 'Grayling', b: '11 cwt' },
      { a: 'Norton Bell', b: '16 cwt' }, { a: 'Grayling', b: '16 cwt' }, { a: 'Whitcombe', b: '16 cwt' },
      { a: 'Underhill', b: '31 cwt' }, { a: 'Marchmont', b: '31 cwt' }, { a: 'Grayling', b: '7 cwt' },
      { a: 'Ferrers', b: '4 cwt' }, { a: 'Marchmont', b: '7 cwt' }, { a: 'Ferrers', b: '22 cwt' },
    ],
    script: [
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 36, quizId: 'hearsay-8-28-26', live: '2026-08-28', dateLabel: 'August 28, 2026', sunday: false,
    noun: 'expedition', listLabel: 'the base log',
    attrs: ['route', 'depth'],
    who: ['Fenwick', 'Isolde'],
    cards: [
      { a: 'the south spur', b: 'day 9' }, { a: 'the west arete', b: 'day 6' }, { a: 'the ice couloir', b: 'day 3' },
      { a: 'the black gully', b: 'day 3' }, { a: 'the south spur', b: 'day 22' }, { a: 'the ice couloir', b: 'day 6' },
      { a: 'the north col', b: 'day 6' }, { a: 'the north col', b: 'day 18' }, { a: 'the north col', b: 'day 22' },
      { a: 'the black gully', b: 'day 14' }, { a: 'the south spur', b: 'day 18' },
    ],
    script: [
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'know' },
    ],
  },
  {
    num: 37, quizId: 'hearsay-8-29-26', live: '2026-08-29', dateLabel: 'August 29, 2026', sunday: false,
    noun: 'letter', listLabel: 'the archive index',
    attrs: ['city', 'year'],
    who: ['Barnaby', 'Rufus'],
    cards: [
      { a: 'Antwerp', b: '1926' }, { a: 'Odesa', b: '1919' }, { a: 'Tangier', b: '1898' },
      { a: 'Odesa', b: '1926' }, { a: 'Odesa', b: '1903' }, { a: 'Trieste', b: '1898' },
      { a: 'Valparaiso', b: '1911' }, { a: 'Trieste', b: '1931' }, { a: 'Tangier', b: '1931' },
      { a: 'Trieste', b: '1903' }, { a: 'Valparaiso', b: '1919' },
    ],
    script: [
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'stillDontKnow' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 38, quizId: 'hearsay-8-30-26', live: '2026-08-30', dateLabel: 'August 30, 2026', sunday: true,
    noun: 'cabin', listLabel: 'the passenger manifest',
    attrs: ['deck', 'cabin', 'trunk'],
    who: ['Ivo', 'Fenwick', 'Aurelio'],
    cards: [
      { a: 'E deck', b: 'cabin 12', c: 'a tin trunk' }, { a: 'C deck', b: 'cabin 31', c: 'a leather trunk' }, { a: 'D deck', b: 'cabin 24', c: 'a tin trunk' },
      { a: 'C deck', b: 'cabin 58', c: 'a tin trunk' }, { a: 'A deck', b: 'cabin 47', c: 'a painted trunk' }, { a: 'E deck', b: 'cabin 31', c: 'a tin trunk' },
      { a: 'B deck', b: 'cabin 12', c: 'a wicker trunk' }, { a: 'A deck', b: 'cabin 12', c: 'a leather trunk' }, { a: 'E deck', b: 'cabin 24', c: 'a painted trunk' },
      { a: 'C deck', b: 'cabin 12', c: 'a leather trunk' }, { a: 'D deck', b: 'cabin 47', c: 'a wicker trunk' }, { a: 'C deck', b: 'cabin 24', c: 'a wicker trunk' },
      { a: 'D deck', b: 'cabin 12', c: 'a tin trunk' }, { a: 'C deck', b: 'cabin 31', c: 'a painted trunk' }, { a: 'E deck', b: 'cabin 24', c: 'a wicker trunk' },
    ],
    script: [
      { who: 'c', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'c' },
      { who: 'c', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'c' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 39, quizId: 'hearsay-8-31-26', live: '2026-08-31', dateLabel: 'August 31, 2026', sunday: false,
    noun: 'submission', listLabel: 'the reading pile',
    attrs: ['genre', 'length'],
    who: ['Ambrose', 'Clemence'],
    cards: [
      { a: 'a thriller', b: '221 pages' }, { a: 'a ghost story', b: '92 pages' }, { a: 'a verse novel', b: '412 pages' },
      { a: 'a ghost story', b: '305 pages' }, { a: 'a farce', b: '92 pages' }, { a: 'a memoir', b: '305 pages' },
      { a: 'a travelogue', b: '140 pages' }, { a: 'a travelogue', b: '412 pages' }, { a: 'a ghost story', b: '412 pages' },
      { a: 'a thriller', b: '305 pages' }, { a: 'a memoir', b: '188 pages' },
    ],
    script: [
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'knowNowOtherStill', other: 'b' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 40, quizId: 'hearsay-9-1-26', live: '2026-09-01', dateLabel: 'September 1, 2026', sunday: false,
    noun: 'lighthouse', listLabel: 'the coastal survey',
    attrs: ['coast', 'character'],
    who: ['Perpetua', 'Cato'],
    cards: [
      { a: 'the north coast', b: 'a group flash' }, { a: 'the shingle coast', b: 'an occulting light' }, { a: 'the north coast', b: 'one flash' },
      { a: 'the granite coast', b: 'one flash' }, { a: 'the north coast', b: 'a fixed light' }, { a: 'the north coast', b: 'two flashes' },
      { a: 'the estuary', b: 'a group flash' }, { a: 'the estuary', b: 'three flashes' }, { a: 'the estuary', b: 'an occulting light' },
      { a: 'the chalk coast', b: 'a group flash' }, { a: 'the north coast', b: 'an occulting light' }, { a: 'the north coast', b: 'three flashes' },
      { a: 'the estuary', b: 'one flash' }, { a: 'the granite coast', b: 'three flashes' }, { a: 'the shingle coast', b: 'a fixed light' },
    ],
    script: [
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 41, quizId: 'hearsay-9-2-26', live: '2026-09-02', dateLabel: 'September 2, 2026', sunday: false,
    noun: 'tapestry', listLabel: 'the loom register',
    attrs: ['workshop', 'warp'],
    who: ['Wilhelmina', 'Cato'],
    cards: [
      { a: 'Everly Mill', b: 'mixed warp' }, { a: 'Buckthorn', b: 'mixed warp' }, { a: 'Averill', b: 'linen warp' },
      { a: 'Averill', b: 'hemp warp' }, { a: 'Averill', b: 'silk warp' }, { a: 'Buckthorn', b: 'linen warp' },
      { a: 'Buckthorn', b: 'silk warp' }, { a: 'Dunmarch', b: 'cotton warp' }, { a: 'Fernbank', b: 'silk warp' },
      { a: 'Averill', b: 'cotton warp' }, { a: 'Averill', b: 'wool warp' }, { a: 'Cranleigh', b: 'wool warp' },
    ],
    script: [
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'knowNowOtherStill', other: 'a' },
      { who: 'a', type: 'know' },
    ],
  },
  {
    num: 42, quizId: 'hearsay-9-3-26', live: '2026-09-03', dateLabel: 'September 3, 2026', sunday: false,
    noun: 'sighting', listLabel: 'the field notebook',
    attrs: ['hide', 'weather'],
    who: ['Odette', 'Juno'],
    cards: [
      { a: 'the tower hide', b: 'in drizzle' }, { a: 'the marsh hide', b: 'in bright sun' }, { a: 'the dune hide', b: 'in fog' },
      { a: 'the oak hide', b: 'in a stiff wind' }, { a: 'the oak hide', b: 'at first light' }, { a: 'the cliff hide', b: 'under cloud' },
      { a: 'the dune hide', b: 'in bright sun' }, { a: 'the oak hide', b: 'under cloud' }, { a: 'the dune hide', b: 'in a stiff wind' },
      { a: 'the tower hide', b: 'under cloud' }, { a: 'the oak hide', b: 'in fog' },
    ],
    script: [
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'stillDontKnow' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 43, quizId: 'hearsay-9-4-26', live: '2026-09-04', dateLabel: 'September 4, 2026', sunday: false,
    noun: 'kiln firing', listLabel: 'the works diary',
    attrs: ['kiln', 'fuel'],
    who: ['Cato', 'Ottoline'],
    cards: [
      { a: 'the electric kiln', b: 'oak' }, { a: 'the electric kiln', b: 'coal' }, { a: 'the bottle kiln', b: 'ash wood' },
      { a: 'the electric kiln', b: 'gas' }, { a: 'the wood kiln', b: 'ash wood' }, { a: 'the salt kiln', b: 'recycled timber' },
      { a: 'the electric kiln', b: 'recycled timber' }, { a: 'the electric kiln', b: 'pine' }, { a: 'the bottle kiln', b: 'oak' },
      { a: 'the gas kiln', b: 'pine' }, { a: 'the gas kiln', b: 'oak' },
    ],
    script: [
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'know' },
    ],
  },
  {
    num: 44, quizId: 'hearsay-9-5-26', live: '2026-09-05', dateLabel: 'September 5, 2026', sunday: false,
    noun: 'lighthouse keeper', listLabel: 'the roster',
    attrs: ['light', 'watch'],
    who: ['Bram', 'Rufus'],
    cards: [
      { a: 'Fell Ness', b: 'the middle watch' }, { a: 'Longstone', b: 'the afternoon' }, { a: 'Blackrock', b: 'the first watch' },
      { a: 'Longstone', b: 'the forenoon' }, { a: 'Fell Ness', b: 'the afternoon' }, { a: 'Longstone', b: 'the morning watch' },
      { a: 'Gannet Isle', b: 'the middle watch' }, { a: 'Carrick Point', b: 'the forenoon' }, { a: 'Skerry Head', b: 'the forenoon' },
      { a: 'Carrick Point', b: 'the first watch' }, { a: 'Skerry Head', b: 'the first watch' },
    ],
    script: [
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 45, quizId: 'hearsay-9-6-26', live: '2026-09-06', dateLabel: 'September 6, 2026', sunday: true,
    noun: 'racing pigeon', listLabel: 'the loft book',
    attrs: ['loft', 'ring', 'race'],
    who: ['Hester', 'Ambrose', 'Lazlo'],
    cards: [
      { a: 'Eastgate Loft', b: 'a green ring', c: 'the young bird race' }, { a: 'Denby Loft', b: 'a yellow ring', c: 'the young bird race' }, { a: 'Denby Loft', b: 'a blue ring', c: 'the long race' },
      { a: 'Eastgate Loft', b: 'a blue ring', c: 'the young bird race' }, { a: 'Chilton Loft', b: 'a yellow ring', c: 'the young bird race' }, { a: 'Eastgate Loft', b: 'a black ring', c: 'the young bird race' },
      { a: 'Eastgate Loft', b: 'a yellow ring', c: 'the coast race' }, { a: 'Chilton Loft', b: 'a green ring', c: 'the inland race' }, { a: 'Barrow Loft', b: 'a black ring', c: 'the long race' },
      { a: 'Chilton Loft', b: 'a blue ring', c: 'the coast race' }, { a: 'Denby Loft', b: 'a green ring', c: 'the coast race' }, { a: 'Fenwick Loft', b: 'a yellow ring', c: 'the long race' },
      { a: 'Chilton Loft', b: 'a green ring', c: 'the young bird race' }, { a: 'Barrow Loft', b: 'a black ring', c: 'the inland race' },
    ],
    script: [
      { who: 'c', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'dontKnow' },
      { who: 'c', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 46, quizId: 'hearsay-9-7-26', live: '2026-09-07', dateLabel: 'September 7, 2026', sunday: false,
    noun: 'weather station', listLabel: 'the network list',
    attrs: ['site', 'reading'],
    who: ['Aurelio', 'Sabine'],
    cards: [
      { a: 'Sandwath', b: '11C' }, { a: 'Cairn Ross', b: '-4C' }, { a: 'Cairn Ross', b: '6C' },
      { a: 'Pike Fell', b: '17C' }, { a: 'Undercliff', b: '1C' }, { a: 'Wraymoor', b: '11C' },
      { a: 'Cairn Ross', b: '1C' }, { a: 'Pike Fell', b: '23C' }, { a: 'Undercliff', b: '6C' },
      { a: 'Pike Fell', b: '-4C' }, { a: 'Undercliff', b: '-4C' }, { a: 'Sandwath', b: '1C' },
      { a: 'Torrey Point', b: '11C' },
    ],
    script: [
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'know' },
    ],
  },
  {
    num: 47, quizId: 'hearsay-9-8-26', live: '2026-09-08', dateLabel: 'September 8, 2026', sunday: false,
    noun: 'beehive', listLabel: 'the apiary record',
    attrs: ['orchard', 'queen'],
    who: ['Wilhelmina', 'Marguerite'],
    cards: [
      { a: 'Little Ash', b: 'a marked green queen' }, { a: 'Cotterdown', b: 'a marked blue queen' }, { a: 'Mill Hollow', b: 'a marked blue queen' },
      { a: 'Hazelbrook', b: 'an unmarked queen' }, { a: 'Little Ash', b: 'a marked blue queen' }, { a: 'Mill Hollow', b: 'a marked green queen' },
      { a: 'Windlass', b: 'an unmarked queen' }, { a: 'Windlass', b: 'a marked white queen' }, { a: 'Hazelbrook', b: 'a marked yellow queen' },
      { a: 'Sparrow Hill', b: 'a marked yellow queen' }, { a: 'Hazelbrook', b: 'a marked blue queen' }, { a: 'Little Ash', b: 'a new queen' },
    ],
    script: [
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'stillDontKnow' },
      { who: 'a', type: 'know' },
    ],
  },
  {
    num: 48, quizId: 'hearsay-9-9-26', live: '2026-09-09', dateLabel: 'September 9, 2026', sunday: false,
    noun: 'tram', listLabel: 'the depot sheet',
    attrs: ['route', 'livery'],
    who: ['Leopold', 'Wilhelmina'],
    cards: [
      { a: 'the university route', b: 'green and cream' }, { a: 'the circle route', b: 'crimson' }, { a: 'the coast route', b: 'teal' },
      { a: 'the circle route', b: 'blue and white' }, { a: 'the hill route', b: 'crimson' }, { a: 'the coast route', b: 'plain grey' },
      { a: 'the docks route', b: 'crimson' }, { a: 'the market route', b: 'maroon' }, { a: 'the circle route', b: 'maroon' },
      { a: 'the docks route', b: 'maroon' }, { a: 'the university route', b: 'crimson' }, { a: 'the hill route', b: 'green and cream' },
      { a: 'the docks route', b: 'plain grey' },
    ],
    script: [
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'know' },
    ],
  },
  {
    num: 49, quizId: 'hearsay-9-10-26', live: '2026-09-10', dateLabel: 'September 10, 2026', sunday: false,
    noun: 'coin hoard', listLabel: 'the finds list',
    attrs: ['field', 'reign'],
    who: ['Casper', 'Odette'],
    cards: [
      { a: 'Wether Down', b: 'Aethelred' }, { a: 'Long Meadow', b: 'Harold' }, { a: 'Chalk Furlong', b: 'Edward III' },
      { a: 'Cobb’s Piece', b: 'Edward III' }, { a: 'Chalk Furlong', b: 'Aethelred' }, { a: 'Nine Acre', b: 'Aethelred' },
      { a: 'Cobb’s Piece', b: 'John' }, { a: 'Chalk Furlong', b: 'Harold' }, { a: 'Nine Acre', b: 'Harold' },
      { a: 'Nine Acre', b: 'Cnut' }, { a: 'Nine Acre', b: 'Stephen' },
    ],
    script: [
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 50, quizId: 'hearsay-9-11-26', live: '2026-09-11', dateLabel: 'September 11, 2026', sunday: false,
    noun: 'cider', listLabel: 'the press ledger',
    attrs: ['orchard', 'variety'],
    who: ['Sabine', 'Barnaby'],
    cards: [
      { a: 'Ashcott', b: 'Yarlington Mill' }, { a: 'Ellwood', b: 'Browns Apple' }, { a: 'Comber Farm', b: 'Somerset Redstreak' },
      { a: 'Comber Farm', b: 'Kingston Black' }, { a: 'Foxhanger', b: 'Somerset Redstreak' }, { a: 'Ashcott', b: 'Kingston Black' },
      { a: 'Ashcott', b: 'Dabinett' }, { a: 'Dunning', b: 'Dabinett' }, { a: 'Foxhanger', b: 'Harry Masters' },
      { a: 'Comber Farm', b: 'Harry Masters' }, { a: 'Ellwood', b: 'Kingston Black' },
    ],
    script: [
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'stillDontKnow' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 51, quizId: 'hearsay-9-12-26', live: '2026-09-12', dateLabel: 'September 12, 2026', sunday: false,
    noun: 'canoe', listLabel: 'the portage list',
    attrs: ['river', 'put-in'],
    who: ['Solveig', 'Anouk'],
    cards: [
      { a: 'the Kelder', b: 'the lock' }, { a: 'the Shining', b: 'the lock' }, { a: 'the Slate', b: 'the gravel bar' },
      { a: 'the Fenn', b: 'the mill weir' }, { a: 'the Shining', b: 'the old bridge' }, { a: 'the Slate', b: 'the ford' },
      { a: 'the Kelder', b: 'the old bridge' }, { a: 'the Kelder', b: 'the ford' }, { a: 'the Kelder', b: 'the mill weir' },
      { a: 'the Marrow', b: 'the gravel bar' }, { a: 'the Slate', b: 'the boat house' }, { a: 'the Otterburn', b: 'the mill weir' },
      { a: 'the Otterburn', b: 'the lock' },
    ],
    script: [
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'stillDontKnow' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 52, quizId: 'hearsay-9-13-26', live: '2026-09-13', dateLabel: 'September 13, 2026', sunday: true,
    noun: 'costume', listLabel: 'the wardrobe list',
    attrs: ['act', 'fabric', 'trim'],
    who: ['Ottoline', 'Solveig', 'Rosalind'],
    cards: [
      { a: 'act two', b: 'linen', c: 'gold trim' }, { a: 'act two', b: 'brocade', c: 'no trim' }, { a: 'act two', b: 'linen', c: 'no trim' },
      { a: 'act one', b: 'brocade', c: 'silver trim' }, { a: 'act three', b: 'taffeta', c: 'no trim' }, { a: 'act one', b: 'wool', c: 'no trim' },
      { a: 'act one', b: 'linen', c: 'gold trim' }, { a: 'act three', b: 'linen', c: 'no trim' }, { a: 'act one', b: 'wool', c: 'black trim' },
      { a: 'act two', b: 'brocade', c: 'gold trim' }, { a: 'act two', b: 'taffeta', c: 'gold trim' }, { a: 'the finale', b: 'velvet', c: 'gold trim' },
      { a: 'act three', b: 'brocade', c: 'silver trim' }, { a: 'act three', b: 'brocade', c: 'no trim' },
    ],
    script: [
      { who: 'c', type: 'dontKnow' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'c' },
      { who: 'c', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'know' },
    ],
  },
  {
    num: 53, quizId: 'hearsay-9-14-26', live: '2026-09-14', dateLabel: 'September 14, 2026', sunday: false,
    noun: 'lifeboat', listLabel: 'the station board',
    attrs: ['station', 'shout'],
    who: ['Lazlo', 'Verity'],
    cards: [
      { a: 'Kilbrannan', b: 'at 13:15' }, { a: 'Dunmore', b: 'at 02:10' }, { a: 'Kilbrannan', b: 'at 18:30' },
      { a: 'Fairlight', b: 'at 05:45' }, { a: 'Sennen', b: 'at 02:10' }, { a: 'Portreath', b: 'at 23:05' },
      { a: 'Rosslare', b: 'at 23:05' }, { a: 'Sennen', b: 'at 13:15' }, { a: 'Kilbrannan', b: 'at 02:10' },
      { a: 'Portreath', b: 'at 18:30' }, { a: 'Fairlight', b: 'at 09:20' },
    ],
    script: [
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'know' },
    ],
  },
  {
    num: 54, quizId: 'hearsay-9-15-26', live: '2026-09-15', dateLabel: 'September 15, 2026', sunday: false,
    noun: 'quilt', listLabel: 'the collection card',
    attrs: ['pattern', 'county'],
    who: ['Beatrix', 'Ambrose'],
    cards: [
      { a: 'tumbling blocks', b: 'Gwent' }, { a: 'flying geese', b: 'Fife' }, { a: 'log cabin', b: 'Angus' },
      { a: 'mariner’s compass', b: 'Gwent' }, { a: 'log cabin', b: 'Powys' }, { a: 'bear paw', b: 'Gwent' },
      { a: 'tumbling blocks', b: 'Fife' }, { a: 'wedding ring', b: 'Antrim' }, { a: 'mariner’s compass', b: 'Kerry' },
      { a: 'tumbling blocks', b: 'Kerry' }, { a: 'flying geese', b: 'Angus' },
    ],
    script: [
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'know' },
    ],
  },
  {
    num: 55, quizId: 'hearsay-9-16-26', live: '2026-09-16', dateLabel: 'September 16, 2026', sunday: false,
    noun: 'kite', listLabel: 'the flying-field log',
    attrs: ['design', 'line'],
    who: ['Ottoline', 'Genevieve'],
    cards: [
      { a: 'a rokkaku', b: '120 metres' }, { a: 'a sled kite', b: '200 metres' }, { a: 'a parafoil', b: '200 metres' },
      { a: 'a diamond', b: '90 metres' }, { a: 'a sled kite', b: '120 metres' }, { a: 'a diamond', b: '60 metres' },
      { a: 'a box kite', b: '90 metres' }, { a: 'a box kite', b: '30 metres' }, { a: 'a delta', b: '150 metres' },
      { a: 'a diamond', b: '30 metres' }, { a: 'a rokkaku', b: '90 metres' }, { a: 'a delta', b: '120 metres' },
      { a: 'a diamond', b: '200 metres' },
    ],
    script: [
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'know' },
    ],
  },
  {
    num: 56, quizId: 'hearsay-9-17-26', live: '2026-09-17', dateLabel: 'September 17, 2026', sunday: false,
    noun: 'cheese', listLabel: 'the counter card',
    attrs: ['dairy', 'age'],
    who: ['Fenwick', 'Ambrose'],
    cards: [
      { a: 'Pilcher', b: '6 months' }, { a: 'Stane End', b: '3 months' }, { a: 'Pilcher', b: '9 months' },
      { a: 'Stane End', b: '18 months' }, { a: 'Longmere', b: '9 months' }, { a: 'Wintersett', b: '18 months' },
      { a: 'Havercroft', b: '3 months' }, { a: 'Redbourne', b: '3 months' }, { a: 'Havercroft', b: '24 months' },
      { a: 'Stane End', b: '24 months' }, { a: 'Pilcher', b: '14 months' }, { a: 'Redbourne', b: '6 months' },
    ],
    script: [
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 57, quizId: 'hearsay-9-18-26', live: '2026-09-18', dateLabel: 'September 18, 2026', sunday: false,
    noun: 'observation', listLabel: 'the night log',
    attrs: ['telescope', 'object'],
    who: ['Emeric', 'Lazlo'],
    cards: [
      { a: 'the 8-inch reflector', b: 'a nebula' }, { a: 'the club scope', b: 'a variable star' }, { a: 'the 12-inch reflector', b: 'a comet' },
      { a: 'the club scope', b: 'a planetary moon' }, { a: 'the astrograph', b: 'a nebula' }, { a: 'the 12-inch reflector', b: 'a double star' },
      { a: 'the refractor', b: 'a variable star' }, { a: 'the survey scope', b: 'a nebula' }, { a: 'the club scope', b: 'a double star' },
      { a: 'the refractor', b: 'a double star' }, { a: 'the survey scope', b: 'a double star' },
    ],
    script: [
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'know' },
    ],
  },
  {
    num: 58, quizId: 'hearsay-9-19-26', live: '2026-09-19', dateLabel: 'September 19, 2026', sunday: false,
    noun: 'loaf', listLabel: 'the bakery docket',
    attrs: ['flour', 'proof'],
    who: ['Genevieve', 'Delphine'],
    cards: [
      { a: 'stoneground wheat', b: 'a 4 hour proof' }, { a: 'stoneground wheat', b: 'an 18 hour proof' }, { a: 'barley', b: 'a 12 hour proof' },
      { a: 'einkorn', b: 'an 18 hour proof' }, { a: 'stoneground wheat', b: 'a 12 hour proof' }, { a: 'rye', b: 'a 4 hour proof' },
      { a: 'rye', b: 'a 24 hour proof' }, { a: 'emmer', b: 'a 12 hour proof' }, { a: 'spelt', b: 'an 8 hour proof' },
      { a: 'stoneground wheat', b: 'an 8 hour proof' }, { a: 'emmer', b: 'an 18 hour proof' },
    ],
    script: [
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 59, quizId: 'hearsay-9-20-26', live: '2026-09-20', dateLabel: 'September 20, 2026', sunday: true,
    noun: 'core sample', listLabel: 'the drill log',
    attrs: ['site', 'depth', 'cap'],
    who: ['Wilhelmina', 'Rufus', 'Hester'],
    cards: [
      { a: 'site epsilon', b: '30 metres', c: 'a red cap' }, { a: 'site alpha', b: '96 metres', c: 'a yellow cap' }, { a: 'site epsilon', b: '58 metres', c: 'a yellow cap' },
      { a: 'site delta', b: '96 metres', c: 'a red cap' }, { a: 'site alpha', b: '30 metres', c: 'a red cap' }, { a: 'site epsilon', b: '12 metres', c: 'a black cap' },
      { a: 'site delta', b: '58 metres', c: 'a red cap' }, { a: 'site beta', b: '58 metres', c: 'a red cap' }, { a: 'site epsilon', b: '140 metres', c: 'a red cap' },
      { a: 'site gamma', b: '12 metres', c: 'a black cap' }, { a: 'site epsilon', b: '58 metres', c: 'a red cap' }, { a: 'site alpha', b: '140 metres', c: 'a black cap' },
      { a: 'site beta', b: '96 metres', c: 'a white cap' }, { a: 'site beta', b: '30 metres', c: 'a black cap' }, { a: 'site beta', b: '140 metres', c: 'a yellow cap' },
      { a: 'site gamma', b: '96 metres', c: 'a black cap' },
    ],
    script: [
      { who: 'b', type: 'knowOtherDoesnt', other: 'c' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'c', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'a', type: 'stillDontKnow' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 60, quizId: 'hearsay-9-21-26', live: '2026-09-21', dateLabel: 'September 21, 2026', sunday: false,
    noun: 'kiln', listLabel: 'the pottery ledger',
    attrs: ['glaze', 'firing'],
    who: ['Sabine', 'Rosalind'],
    cards: [
      { a: 'celadon', b: 'firing 41' }, { a: 'oxblood', b: 'firing 15' }, { a: 'tenmoku', b: 'firing 9' },
      { a: 'salt', b: 'firing 30' }, { a: 'ash', b: 'firing 30' }, { a: 'salt', b: 'firing 4' },
      { a: 'oxblood', b: 'firing 30' }, { a: 'salt', b: 'firing 9' }, { a: 'oxblood', b: 'firing 22' },
      { a: 'oxblood', b: 'firing 9' }, { a: 'ash', b: 'firing 41' }, { a: 'copper red', b: 'firing 22' },
      { a: 'salt', b: 'firing 15' },
    ],
    script: [
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'know' },
    ],
  },
  {
    num: 61, quizId: 'hearsay-9-22-26', live: '2026-09-22', dateLabel: 'September 22, 2026', sunday: false,
    noun: 'recording', listLabel: 'the tape index',
    attrs: ['studio', 'reel'],
    who: ['Rosalind', 'Barnaby'],
    cards: [
      { a: 'Old Foundry', b: 'reel 12' }, { a: 'Ashmount', b: 'reel 8' }, { a: 'Ashmount', b: 'reel 5' },
      { a: 'Old Foundry', b: 'reel 5' }, { a: 'Bellwater', b: 'reel 27' }, { a: 'Nine Elms', b: 'reel 12' },
      { a: 'Old Foundry', b: 'reel 2' }, { a: 'Old Foundry', b: 'reel 8' }, { a: 'Ashmount', b: 'reel 27' },
      { a: 'Corris Lane', b: 'reel 12' }, { a: 'Corris Lane', b: 'reel 19' },
    ],
    script: [
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 62, quizId: 'hearsay-9-23-26', live: '2026-09-23', dateLabel: 'September 23, 2026', sunday: false,
    noun: 'kiln', listLabel: 'the pottery ledger',
    attrs: ['glaze', 'firing'],
    who: ['Marisol', 'Sabine'],
    cards: [
      { a: 'oxblood', b: 'firing 41' }, { a: 'salt', b: 'firing 4' }, { a: 'oxblood', b: 'firing 15' },
      { a: 'ash', b: 'firing 30' }, { a: 'tenmoku', b: 'firing 30' }, { a: 'celadon', b: 'firing 41' },
      { a: 'oxblood', b: 'firing 22' }, { a: 'copper red', b: 'firing 22' }, { a: 'salt', b: 'firing 9' },
      { a: 'tenmoku', b: 'firing 4' }, { a: 'tenmoku', b: 'firing 41' }, { a: 'ash', b: 'firing 4' },
    ],
    script: [
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'stillDontKnow' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 63, quizId: 'hearsay-9-24-26', live: '2026-09-24', dateLabel: 'September 24, 2026', sunday: false,
    noun: 'expedition', listLabel: 'the base log',
    attrs: ['route', 'depth'],
    who: ['Genevieve', 'Cato'],
    cards: [
      { a: 'the north col', b: 'day 18' }, { a: 'the south spur', b: 'day 18' }, { a: 'the ice couloir', b: 'day 3' },
      { a: 'the south spur', b: 'day 14' }, { a: 'the south spur', b: 'day 3' }, { a: 'the south spur', b: 'day 9' },
      { a: 'the long traverse', b: 'day 14' }, { a: 'the west arete', b: 'day 18' }, { a: 'the west arete', b: 'day 9' },
      { a: 'the ice couloir', b: 'day 6' }, { a: 'the ice couloir', b: 'day 22' },
    ],
    script: [
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 64, quizId: 'hearsay-9-25-26', live: '2026-09-25', dateLabel: 'September 25, 2026', sunday: false,
    noun: 'sailing', listLabel: 'the harbour board',
    attrs: ['port', 'day'],
    who: ['Silas', 'Cato'],
    cards: [
      { a: 'Bergen', b: 'Saturday' }, { a: 'Bergen', b: 'Sunday' }, { a: 'Palermo', b: 'Tuesday' },
      { a: 'Tangier', b: 'Sunday' }, { a: 'Kotor', b: 'Tuesday' }, { a: 'Split', b: 'Friday' },
      { a: 'Palermo', b: 'Thursday' }, { a: 'Cadiz', b: 'Monday' }, { a: 'Tangier', b: 'Saturday' },
      { a: 'Tangier', b: 'Monday' }, { a: 'Tangier', b: 'Thursday' }, { a: 'Bergen', b: 'Friday' },
    ],
    script: [
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 65, quizId: 'hearsay-9-26-26', live: '2026-09-26', dateLabel: 'September 26, 2026', sunday: false,
    noun: 'submission', listLabel: 'the reading pile',
    attrs: ['genre', 'length'],
    who: ['Wilhelmina', 'Osric'],
    cards: [
      { a: 'a thriller', b: '221 pages' }, { a: 'a farce', b: '412 pages' }, { a: 'a memoir', b: '305 pages' },
      { a: 'a ghost story', b: '221 pages' }, { a: 'a thriller', b: '188 pages' }, { a: 'a verse novel', b: '412 pages' },
      { a: 'a travelogue', b: '305 pages' }, { a: 'a travelogue', b: '140 pages' }, { a: 'a memoir', b: '92 pages' },
      { a: 'a verse novel', b: '221 pages' }, { a: 'a ghost story', b: '412 pages' }, { a: 'a verse novel', b: '92 pages' },
    ],
    script: [
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'stillDontKnow' },
      { who: 'a', type: 'know' },
    ],
  },
  {
    num: 66, quizId: 'hearsay-9-27-26', live: '2026-09-27', dateLabel: 'September 27, 2026', sunday: true,
    noun: 'seedling', listLabel: 'the nursery bench',
    attrs: ['tray', 'stock', 'tag'],
    who: ['Odette', 'Bram', 'Hester'],
    cards: [
      { a: 'tray one', b: 'cherry stock', c: 'a green tag' }, { a: 'tray four', b: 'plum stock', c: 'a green tag' }, { a: 'tray one', b: 'plum stock', c: 'a green tag' },
      { a: 'tray four', b: 'cherry stock', c: 'a blue tag' }, { a: 'tray seven', b: 'apple stock', c: 'a blue tag' }, { a: 'tray twelve', b: 'plum stock', c: 'a green tag' },
      { a: 'tray twelve', b: 'apple stock', c: 'a blue tag' }, { a: 'tray twelve', b: 'apple stock', c: 'a green tag' }, { a: 'tray seven', b: 'quince stock', c: 'a green tag' },
      { a: 'tray twelve', b: 'pear stock', c: 'a green tag' }, { a: 'tray twelve', b: 'plum stock', c: 'a plain tag' }, { a: 'tray twelve', b: 'apple stock', c: 'a plain tag' },
      { a: 'tray four', b: 'pear stock', c: 'a plain tag' }, { a: 'tray twelve', b: 'quince stock', c: 'a red tag' },
    ],
    script: [
      { who: 'c', type: 'dontKnow' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'c', type: 'knowOtherDoesnt', other: 'a' },
      { who: 'b', type: 'knowOtherDoesnt', other: 'c' },
      { who: 'a', type: 'know' },
    ],
  },
  {
    num: 67, quizId: 'hearsay-9-28-26', live: '2026-09-28', dateLabel: 'September 28, 2026', sunday: false,
    noun: 'cheese', listLabel: 'the counter card',
    attrs: ['dairy', 'age'],
    who: ['Ottoline', 'Anouk'],
    cards: [
      { a: 'Stane End', b: '18 months' }, { a: 'Stane End', b: '3 months' }, { a: 'Wintersett', b: '9 months' },
      { a: 'Pilcher', b: '24 months' }, { a: 'Havercroft', b: '9 months' }, { a: 'Pilcher', b: '6 months' },
      { a: 'Redbourne', b: '3 months' }, { a: 'Redbourne', b: '14 months' }, { a: 'Longmere', b: '24 months' },
      { a: 'Redbourne', b: '6 months' }, { a: 'Wintersett', b: '6 months' },
    ],
    script: [
      { who: 'a', type: 'dontKnow' },
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'knowNowOtherStill', other: 'b' },
      { who: 'b', type: 'know' },
    ],
  },
  {
    num: 68, quizId: 'hearsay-9-29-26', live: '2026-09-29', dateLabel: 'September 29, 2026', sunday: false,
    noun: 'observation', listLabel: 'the night log',
    attrs: ['telescope', 'object'],
    who: ['Beatrix', 'Bram'],
    cards: [
      { a: 'the survey scope', b: 'a nebula' }, { a: 'the 8-inch reflector', b: 'a comet' }, { a: 'the astrograph', b: 'a comet' },
      { a: 'the refractor', b: 'a comet' }, { a: 'the 12-inch reflector', b: 'a planetary moon' }, { a: 'the astrograph', b: 'a planetary moon' },
      { a: 'the refractor', b: 'a double star' }, { a: 'the refractor', b: 'a planetary moon' }, { a: 'the survey scope', b: 'a double star' },
      { a: 'the 8-inch reflector', b: 'a variable star' }, { a: 'the club scope', b: 'a globular cluster' }, { a: 'the 12-inch reflector', b: 'a globular cluster' },
    ],
    script: [
      { who: 'b', type: 'dontKnow' },
      { who: 'a', type: 'knowOtherDoesnt', other: 'b' },
      { who: 'b', type: 'stillDontKnow' },
      { who: 'a', type: 'know' },
    ],
  },
];
