// Puzzle data for Scrab, the daily Scrabble endgame. Imported ONLY by the
// server page (app/scrab/page.js), which filters live<=today AND strips `foe`
// before handing anything to the browser. The opponent's rack is never sent:
// the client re-derives it exactly the way the player is meant to, as the bag
// minus the board minus their own rack, so the tile tracker, the engine and the
// player are all working from the same public information.
//
// Each day is the tail of a real self-played game (scripts/gen-scrab.mjs): the
// bag is empty and the player holds five tiles, six in the Sunday Edition.
//
// `par` is the spread our solver ACHIEVES from the player's seat against the
// very defence the browser plays (solveLine in lib/scrab-engine.js), so it is
// reachable by construction rather than a theoretical ceiling nobody can hit.
// `greedy` is what grabbing the biggest number every turn gets you; every
// banked day pays at least 4 more than that for playing the endgame properly.
//
// Validate with scripts/verify-scrab.mjs after ANY edit to this file or to the
// engine. It replays every line and fails if a par stops being reachable.
export const PUZZLES = [
  { num: 1, quizId: "scrab-8-2-26", live: "2026-08-02", dateLabel: "August 2, 2026", sunday: true, par: 44, greedy: -19,
    rack: ["R","U","H","G","E","I"], foe: ["V","C","U","S","N","L"],
    board: ["ORD....DO.Z", "MY....FIBRE", ".AXE.KA.A.L", "..INMATE...", "....ERS....", "....ET.....", "...IT......", "..DOS......", "..ON.PLUG..", ".WHITE.....", "JO.CAN....."] },
  { num: 2, quizId: "scrab-8-3-26", live: "2026-08-03", dateLabel: "August 3, 2026", sunday: false, par: 19, greedy: 10,
    rack: ["V","R","A","D","S"], foe: ["T","M","T","C","I"],
    board: ["..........N", "......H.JET", "......EWE.H", ".....B.EUK.", "....LIFT.Y.", "....AZO.CUR", ".GLAM.L.U..", "PE.RAIDER..", "ONS..OS.EN.", ".OI......O.", "DANG.....XI"] },
  { num: 3, quizId: "scrab-8-4-26", live: "2026-08-04", dateLabel: "August 4, 2026", sunday: false, par: 11, greedy: -11,
    rack: ["T","U","U","E","B"], foe: ["R","I","A","C","N"],
    board: ["...........", "...........", "..H.MIZ.C..", "..AHI.ALONG", "..JOSS..U..", ".E...LAMP..", ".R.FROG....", "NOTE.WOX...", ".DIRK....V.", ".E.NYE...I.", "AD.SETTLED."] },
  { num: 4, quizId: "scrab-8-5-26", live: "2026-08-05", dateLabel: "August 5, 2026", sunday: false, par: 12, greedy: -9,
    rack: ["V","N","G","R","A"], foe: ["L","T","U","R","I"],
    board: ["...COZ.MILE", "....WIFE.OH", ".....TUM...", "...K..REN..", "...EATS.ID.", "...RHO..XU.", ".J.NANA..B.", ".ODE.IDS...", "..EL.COAT..", "..G....YEP.", ".......S..."] },
  { num: 5, quizId: "scrab-8-6-26", live: "2026-08-06", dateLabel: "August 6, 2026", sunday: false, par: 31, greedy: -20,
    rack: ["T","G","D","T","E"], foe: ["N","D","U","R","Z"],
    board: [".......HEIR", "PLACE.JOR..", "OOM...ORA..", ".BACK.IN...", "....I.N....", "..M.LATEX..", "..YON.SEI..", "...W.......", "..SLAVE...U", "......FIGHT", ".......DUES"] },
  { num: 6, quizId: "scrab-8-7-26", live: "2026-08-07", dateLabel: "August 7, 2026", sunday: false, par: 27, greedy: 17,
    rack: ["U","O","D","R","O"], foe: ["L","U","L","R","U"],
    board: ["........NAN", ".......ZAX.", ".SNITCH.V..", ".....R.FY..", "....HI.O...", "...CAN.R...", "..GADGETS..", "...PEE.EA..", "JOKES...IT.", "EMO.....DIM", "T.WEB....LI"] },
  { num: 7, quizId: "scrab-8-8-26", live: "2026-08-08", dateLabel: "August 8, 2026", sunday: false, par: 11, greedy: 1,
    rack: ["T","T","L","O","I"], foe: ["C","R","R","E","R"],
    board: ["ZA.UM......", ".V.PUR.....", "COL.NYE....", "OI..DEX....", "OD.TA.OS...", ".SHINE.K...", "..ANE.FEG..", ".MUG..AWE..", ".IN...B.L..", "..TAJ......", "DISH......."] },
  { num: 8, quizId: "scrab-8-9-26", live: "2026-08-09", dateLabel: "August 9, 2026", sunday: true, par: 31, greedy: 15,
    rack: ["U","U","K","I","R","N"], foe: ["N","R","O","L","J"],
    board: [".........H.", "......AXIAL", ".......I.WO", "..........C", "....Z.C...A", "P.FLESH..ST", "UVA.E.IT.YE", "R.....NOON.", "GEM...ORB..", "EMITS..TED.", "DEG......AD"] },
  { num: 9, quizId: "scrab-8-10-26", live: "2026-08-10", dateLabel: "August 10, 2026", sunday: false, par: 8, greedy: 3,
    rack: ["N","T","E","E","B"], foe: ["T","L","U","U","E"],
    board: ["..G........", ".JAG.......", ".IDE...D...", ".N.L...ZO..", "AXE.F.SOH..", "..HURST.M..", "....A.A..M.", "...ON.CIVIL", "I.TOC.K..N.", "WRAPS.E..O.", "I.....DERRY"] },
  { num: 10, quizId: "scrab-8-11-26", live: "2026-08-11", dateLabel: "August 11, 2026", sunday: false, par: 24, greedy: 16,
    rack: ["T","I","E","P","Y"], foe: ["N","U","N","N","G"],
    board: ["CUR..NO...G", "ORE.JAW...I", "M.BLAH.HERS", "E..ID.META.", "T...EKE..V.", "S....ADZ...", ".....ISO.F.", ".......LORD", "........XU.", ".......COIL", ".........TA"] },
  { num: 11, quizId: "scrab-8-12-26", live: "2026-08-12", dateLabel: "August 12, 2026", sunday: false, par: 38, greedy: 25,
    rack: ["O","N","N","D","E"], foe: ["I","T","L","D","J"],
    board: ["ATOMS......", "REB........", ".FILLS.S...", "....O..CRUX", ".CHAT.WOE..", "...DIVERT..", "..AZO.YE...", "..U.N..RING", ".KA.......A", "GI.......HM", "UP.......EE"] },
  { num: 12, quizId: "scrab-8-13-26", live: "2026-08-13", dateLabel: "August 13, 2026", sunday: false, par: 19, greedy: -8,
    rack: ["S","O","U","C","P"], foe: ["L","W","I","I","T"],
    board: ["LOCAL......", "..R.IN.....", ".RYA.......", "DA.D.......", "OH.V.......", "N.KEEN.....", ".FARE..JAB.", "GI.T...E...", "OX.SH.DUG..", "NE..MIZ.UM.", "ES....OTTER"] },
  { num: 13, quizId: "scrab-8-14-26", live: "2026-08-14", dateLabel: "August 14, 2026", sunday: false, par: 30, greedy: 3,
    rack: ["R","R","N","A","O"], foe: ["C","I","V","L","I"],
    board: [".PUNT.IF...", "YO....DE...", "EXCUSES....", "....T......", ".JO.R.L....", "..BLAMED...", "G...I.ZA...", "HUMAN..T...", "O..EEK.I...", "SH..DOWNER.", "TA.....G..."] },
  { num: 14, quizId: "scrab-8-15-26", live: "2026-08-15", dateLabel: "August 15, 2026", sunday: false, par: 11, greedy: 2,
    rack: ["V","N","G","O","O"], foe: ["U","O","I","R","I"],
    board: ["STAB.......", "...EM.F....", "..PLAZA.L..", "..EL.IT.O..", "URGE.NETS..", ".....C.HE.J", ".......A.MU", ".....C.N.OD", "....SHAKER.", "ID..WEX..N.", "DIRTY......"] },
  { num: 15, quizId: "scrab-8-16-26", live: "2026-08-16", dateLabel: "August 16, 2026", sunday: true, par: 14, greedy: 1,
    rack: ["N","T","E","R","E","I"], foe: ["U","L","U","A","N"],
    board: ["K..........", "AG.....THY.", "TAD...DOE..", ".MIX.WORN..", "..SIGH.....", "..C.JIB....", ".C.SUPER...", "FONT..ZAS.D", "OI.....MOLE", "EL......VAE", "..........R"] },
  { num: 16, quizId: "scrab-8-17-26", live: "2026-08-17", dateLabel: "August 17, 2026", sunday: false, par: 36, greedy: -1,
    rack: ["E","I","O","C","T"], foe: ["V","L","N","J","I"],
    board: ["AG.C.L.HERD", "TENURE.U...", "OM.T.ZAG...", "M..ER.IS...", "....EHS....", "....DE.....", "NY..OXO....", ".OAF..U....", "..BLANKS...", "...ID..I...", "WARP...T..."] },
  { num: 17, quizId: "scrab-8-18-26", live: "2026-08-18", dateLabel: "August 18, 2026", sunday: false, par: 17, greedy: 11,
    rack: ["N","N","U","O","S"], foe: ["I","N","L","R","D"],
    board: ["FAB...R.DSO", ".GOTH.I.OH.", "LET.ECZEMA.", "...C...U.D.", "...U...R.Y.", "...L.APEX..", "...TWEAK...", ".VIS...AM..", "........E..", "....JIG.E..", "......INTRO"] },
  { num: 18, quizId: "scrab-8-19-26", live: "2026-08-19", dateLabel: "August 19, 2026", sunday: false, par: 24, greedy: 19,
    rack: ["S","G","K","I","R"], foe: ["L","R","T","I","N"],
    board: ["...J.....MM", "...UH...IO.", ".FEDEX.DOWN", ".I..CUES...", ".Z..T.HOT..", "...COY.....", ".P.AREA....", ".L.G.......", ".AVENUE....", ".T..ARSON..", "DE.....BAIL"] },
  { num: 19, quizId: "scrab-8-20-26", live: "2026-08-20", dateLabel: "August 20, 2026", sunday: false, par: 18, greedy: 8,
    rack: ["R","G","N","G","I"], foe: ["R","U","D","T","R"],
    board: ["...........", "........CUE", ".......JOT.", "...CONDONE.", "......OLE..", "..H.POZ....", ".MAYA.EFT..", "SABER.NAW..", ".XI....KAE.", ".IT.LIVE.L.", "UMS....DISH"] },
  { num: 20, quizId: "scrab-8-21-26", live: "2026-08-21", dateLabel: "August 21, 2026", sunday: false, par: 32, greedy: 5,
    rack: ["W","G","C","E","A"], foe: ["U","G","N","D","N"],
    board: [".......H...", "....ZONE.C.", "..AKA.ER.R.", "...E.BUS.IN", ".DUP.IT..MY", "...T.DROVE.", "....H.A..ST", "...JAILS...", "..LOR..I...", "...EME.FOX.", ".......TOIL"] },
  { num: 21, quizId: "scrab-8-22-26", live: "2026-08-22", dateLabel: "August 22, 2026", sunday: false, par: 25, greedy: 7,
    rack: ["T","E","C","I","E"], foe: ["N","S","L","U","D"],
    board: ["AH.ABUNDANT", "GOODY..I...", "..FOE.JEW..", "..T...AT...", "....U.R....", ".RHINOS....", "....R..C...", "...VEX.OM..", "..Z.A..PE..", ".KILLERS...", "MIG........"] },
  { num: 22, quizId: "scrab-8-23-26", live: "2026-08-23", dateLabel: "August 23, 2026", sunday: true, par: 25, greedy: 21,
    rack: ["G","A","F","N","I","T"], foe: ["U","N","P","N","R","O"],
    board: [".......WEBS", ".....EXO.L.", "........ZA.", "..TRIVIA.D.", "......S..D.", ".....LOUDER", ".K..CALMER.", "MYTH..AUE..", "..EIGHT....", "......E..JO", "......SCION"] },
  { num: 23, quizId: "scrab-8-24-26", live: "2026-08-24", dateLabel: "August 24, 2026", sunday: false, par: 44, greedy: 26,
    rack: ["O","U","T","R","E"], foe: ["R","N","N","Z","O"],
    board: ["..........B", ".........WE", ".JAG.....RE", "..LICKED.IN", "....O.LIST.", "..FAME.THEE", ".DAMP.L..R.", "..DUO.UH.S.", "..I.SAVOY..", "..N.T..A...", "CIG....X..."] },
  { num: 24, quizId: "scrab-8-25-26", live: "2026-08-25", dateLabel: "August 25, 2026", sunday: false, par: 18, greedy: 3,
    rack: ["U","U","R","N","L"], foe: ["T","A","L","L","C"],
    board: [".........GO", ".J.KNOT.MOY", ".OWE.RAPID.", ".RET..XIS..", "....AHI....", "..FARES....", ".SAGE....V.", "BODE...ENE.", ".Z.DUTCH.I.", "....MI...N.", "..........."] },
  { num: 25, quizId: "scrab-8-26-26", live: "2026-08-26", dateLabel: "August 26, 2026", sunday: false, par: 16, greedy: 9,
    rack: ["N","N","I","G","A"], foe: ["R","O","T","L","N"],
    board: [".........V.", ".....SCREAM", ".....I..XU.", "...S.....L.", "...PEH.ZIT.", "..MIRAGE...", ".FINED.DEW.", "..KA....LO.", ".DECOY.UT..", "JO.HEART...", "OBS....U..."] },
  { num: 26, quizId: "scrab-8-27-26", live: "2026-08-27", dateLabel: "August 27, 2026", sunday: false, par: 50, greedy: 20,
    rack: ["D","C","Y","L","A"], foe: ["O","O","E","I","L"],
    board: ["P.......Z..", "R.......ES.", "O.......LI.", "N...R..R.G.", "ET..A.BUSH.", ".ACUTE.N.EN", ".V.HIRED.DI", "....O.MOM.X", "..JUST.W...", ".AA...KNIT.", "........FEG"] },
  { num: 27, quizId: "scrab-8-28-26", live: "2026-08-28", dateLabel: "August 28, 2026", sunday: false, par: 8, greedy: -3,
    rack: ["L","T","U","G","L"], foe: ["R","U","R","S","I"],
    board: ["...BOD....P", "....MOM..TA", "..GI.WATERS", "...FINK.HAT", ".........Y.", ".....EXECS.", "HE..JAIL...", "EN.VAU.D...", "R.CID......", "OZONE......", "N.OE......."] },
  { num: 28, quizId: "scrab-8-29-26", live: "2026-08-29", dateLabel: "August 29, 2026", sunday: false, par: 14, greedy: -9,
    rack: ["L","O","T","C","R"], foe: ["J","S","A","X","R"],
    board: ["Y.W........", "E.OO...T.I.", "T.FOB..A.N.", "IN.MU..C.D.", ".A..LURK.I.", ".THIGH.L.E.", ".U..E.GEMS.", ".R...VISA..", "PEN...E.Z..", "ODA.....E..", "D.N........"] },
  { num: 29, quizId: "scrab-8-30-26", live: "2026-08-30", dateLabel: "August 30, 2026", sunday: true, par: 12, greedy: -8,
    rack: ["W","B","C","O","E","T"], foe: ["L","N","G","S","U","N"],
    board: [".........AY", "....INFERNO", "......L....", "...ZO.ET...", "...H..EH...", "R.COUP.R...", "OD..MIME...", "KI.JUG.E...", ".VIA....D..", ".A.RATTLED.", ".S.....AXIS"] },
  { num: 30, quizId: "scrab-8-31-26", live: "2026-08-31", dateLabel: "August 31, 2026", sunday: false, par: 10, greedy: 5,
    rack: ["U","T","N","N","O"], foe: ["U","O","I","G","H"],
    board: ["P......DART", "EF.....IN..", ".UR...BEN..", ".GAR..ID...", "..VAW.L....", "...JAIL....", "....STY....", "...THE.....", ".ECO.MOLE..", ".MARK.XIS..", "CODE....SEZ"] },
  { num: 31, quizId: "scrab-9-1-26", live: "2026-09-01", dateLabel: "September 1, 2026", sunday: false, par: 21, greedy: 5,
    rack: ["S","S","E","E","X"], foe: ["U","T","R","I","P"],
    board: ["G......G...", "E......RAJ.", "MOD..VIOLA.", ".ROB...I.W.", ".AMU.ZINC..", "...THE..H..", "...TAD..IF.", "..CEL...NU.", "..E.L...ORD", "..N.S....YA", "KETO......N"] },
  { num: 32, quizId: "scrab-9-2-26", live: "2026-09-02", dateLabel: "September 2, 2026", sunday: false, par: 10, greedy: -6,
    rack: ["U","R","U","O","L"], foe: ["O","H","L","F","U"],
    board: ["DRAPED.CROW", "...I..AHA..", ".JIN..GIT..", "...TE.EME..", ".C..V.NE...", "LONGEST....", ".Z..N.S....", "KY..TO.....", "A.AD.B.....", "MIXERS.....", "I.........."] },
  { num: 33, quizId: "scrab-9-3-26", live: "2026-09-03", dateLabel: "September 3, 2026", sunday: false, par: 38, greedy: 34,
    rack: ["Z","R","G","T","E"], foe: ["I","I","I","L","R"],
    board: [".......COIN", "....ER.UNS.", "..SNEAKS...", "..HONG.P..B", ".YAD.....JO", "..MELT...U.", ".WE..ADULT.", "...FAVOR...", "..TEC......", "....HOX....", "...MEDIA..."] },
  { num: 34, quizId: "scrab-9-4-26", live: "2026-09-04", dateLabel: "September 4, 2026", sunday: false, par: 16, greedy: 7,
    rack: ["I","S","E","G","K"], foe: ["R","R","U","O","O"],
    board: [".C.....JA..", ".AW...S.ZEL", ".DEL.APRON.", "..MI..I....", "...BENT..C.", ".THEME..GO.", ".H.LOFT.UR.", "AI....AX.N.", "IN....DUTY.", "DEV........", "S.........."] },
  { num: 35, quizId: "scrab-9-5-26", live: "2026-09-05", dateLabel: "September 5, 2026", sunday: false, par: 29, greedy: 4,
    rack: ["I","R","E","L","C"], foe: ["L","V","G","U","D"],
    board: ["DZO.......C", "OE....AGA.R", "BAN...DEN.O", ".LOX..JOT.S", "..W.K.U.INS", "..HINTS..I.", ".FE.I.T.UM.", "YAR.T...R..", "EME.....P..", "AE.........", "H.........."] },
];
