// Puzzle data for the daily game. Imported ONLY by the server page
// component, which filters to live<=today before passing puzzles to
// the client — so future puzzles (and their answers) never ship to the
// browser bundle.
export const PUZZLES = [
  {
    num: 1,
    quizId: 'garble-7-9-26',
    live: '2026-07-09',
    dateLabel: 'July 9, 2026',
    clue: 'The only perfect vision — it just shows up too late.',
    final: 'HINDSIGHT',
    words: [
      { answer: 'HABIT', scramble: 'TABHI', marks: [0, 3] },
      { answer: 'DRESS', scramble: 'REDSS', marks: [0, 4] },
      { answer: 'GRAIN', scramble: 'NARGI', marks: [0, 4] },
      { answer: 'WEIGHT', scramble: 'HEWGIT', marks: [2, 4] },
      { answer: 'STRAND', scramble: 'DARNTS', marks: [1] },
    ],
  },
  {
    num: 2,
    quizId: 'garble-7-10-26',
    live: '2026-07-10',
    dateLabel: 'July 10, 2026',
    clue: "What the arsonist's master plan did.",
    final: 'BACKFIRE',
    words: [
      { answer: 'FABLE', scramble: 'LEFBA', marks: [0, 1] },
      { answer: 'BRICK', scramble: 'RKBCI', marks: [0, 3] },
      { answer: 'KIOSK', scramble: 'KKOIS', marks: [0] },
      { answer: 'IRATE', scramble: 'TREAI', marks: [0, 1] },
      { answer: 'EVADE', scramble: 'VDAEE', marks: [0] },
    ],
  },
  {
    num: 3,
    quizId: 'garble-7-11-26',
    live: '2026-07-11',
    dateLabel: 'July 11, 2026',
    clue: "How the ski-resort mayor won re-election.",
    final: 'LANDSLIDE',
    words: [
      { answer: 'BLAND', scramble: 'BDLAN', marks: [1, 2, 3] },
      { answer: 'DITCH', scramble: 'DTCHI', marks: [0, 1] },
      { answer: 'SPELL', scramble: 'PELSL', marks: [0, 3] },
      { answer: 'EVOKE', scramble: 'OVEEK', marks: [0] },
      { answer: 'DEPTH', scramble: 'HEPDT', marks: [0] },
    ],
  },
  {
    num: 4,
    quizId: 'garble-7-12-26',
    live: '2026-07-12',
    dateLabel: 'July 12, 2026',
    clue: "The suggestion box, to whoever actually reads it.",
    final: 'GOLDMINE',
    words: [
      { answer: 'GLOOM', scramble: 'GMOLO', marks: [0, 4] },
      { answer: 'AVOID', scramble: 'AIODV', marks: [2, 4] },
      { answer: 'MINCE', scramble: 'NMIEC', marks: [1, 2] },
      { answer: 'EJECT', scramble: 'TCEEJ', marks: [0] },
      { answer: 'LILAC', scramble: 'ALCIL', marks: [0] },
    ],
  },
  {
    num: 5,
    quizId: 'garble-7-13-26',
    live: '2026-07-13',
    dateLabel: 'July 13, 2026',
    clue: "The insomniac's only dream.",
    final: 'NIGHTMARE',
    words: [
      { answer: 'MIGHT', scramble: 'GHMTI', marks: [0, 1, 2] },
      { answer: 'TENTH', scramble: 'HTTNE', marks: [0, 2, 4] },
      { answer: 'ANKLE', scramble: 'NKALE', marks: [0] },
      { answer: 'RIVER', scramble: 'IRVER', marks: [0] },
      { answer: 'ELUDE', scramble: 'LUEED', marks: [0] },
    ],
  },
  {
    num: 6,
    quizId: 'garble-7-14-26',
    live: '2026-07-14',
    dateLabel: 'July 14, 2026',
    clue: "How the chess hustler says goodbye.",
    final: 'CHECKMATE',
    words: [
      { answer: 'CHIME', scramble: 'CIEMH', marks: [0, 1] },
      { answer: 'MAGIC', scramble: 'AICGM', marks: [0, 4] },
      { answer: 'TRACK', scramble: 'CKRTA', marks: [2, 4] },
      { answer: 'TEMPO', scramble: 'TMPEO', marks: [0, 1] },
      { answer: 'EVENT', scramble: 'VENET', marks: [0] },
    ],
  },
  {
    num: 7,
    quizId: 'garble-7-15-26',
    live: '2026-07-15',
    dateLabel: 'July 15, 2026',
    clue: "Forecast for the pity party.",
    final: 'DOWNPOUR',
    words: [
      { answer: 'DONUT', scramble: 'DNTUO', marks: [0, 2] },
      { answer: 'WAGON', scramble: 'GWNAO', marks: [0] },
      { answer: 'PROUD', scramble: 'URDOP', marks: [0, 1, 3] },
      { answer: 'OASIS', scramble: 'IASSO', marks: [0] },
      { answer: 'ORBIT', scramble: 'RITOB', marks: [0] },
    ],
  },
  {
    num: 8,
    quizId: 'garble-7-16-26',
    live: '2026-07-16',
    dateLabel: 'July 16, 2026',
    clue: "What the hat shop hands out free of charge.",
    final: 'HEADACHE',
    words: [
      { answer: 'HEDGE', scramble: 'HDGEE', marks: [0, 2] },
      { answer: 'COACH', scramble: 'OACHC', marks: [0, 4] },
      { answer: 'ADAPT', scramble: 'PATDA', marks: [0, 2] },
      { answer: 'ELEGY', scramble: 'ELYGE', marks: [0] },
      { answer: 'EIGHT', scramble: 'THEIG', marks: [0] },
    ],
  },
  {
    num: 9,
    quizId: 'garble-7-17-26',
    live: '2026-07-17',
    dateLabel: 'July 17, 2026',
    clue: "Set it to remember it; type it to forget it.",
    final: 'PASSWORD',
    words: [
      { answer: 'SWAMP', scramble: 'MASPW', marks: [1, 4] },
      { answer: 'DRAMA', scramble: 'ADAMR', marks: [0, 2] },
      { answer: 'SCOUT', scramble: 'UOCTS', marks: [0, 2] },
      { answer: 'RUMOR', scramble: 'ROURM', marks: [0] },
      { answer: 'SYRUP', scramble: 'URSPY', marks: [0] },
    ],
  },
  {
    num: 10,
    quizId: 'garble-7-18-26',
    live: '2026-07-18',
    dateLabel: 'July 18, 2026',
    clue: "The turkey's last will and testament.",
    final: 'WISHBONE',
    words: [
      { answer: 'WHISK', scramble: 'SKIWH', marks: [0, 1, 3] },
      { answer: 'BANJO', scramble: 'NAJOB', marks: [0, 2] },
      { answer: 'OZONE', scramble: 'ZNOEO', marks: [0] },
      { answer: 'IGLOO', scramble: 'IGOOL', marks: [0] },
      { answer: 'ELECT', scramble: 'ECELT', marks: [0] },
    ],
  },
  {
    num: 11,
    quizId: 'garble-7-19-26',
    live: '2026-07-19',
    dateLabel: 'July 19, 2026',
    clue: "The kite's five-o'clock routine.",
    final: 'TAILSPIN',
    words: [
      { answer: 'TWIRL', scramble: 'LIRTW', marks: [0, 4] },
      { answer: 'PIANO', scramble: 'NAPOI', marks: [0, 2] },
      { answer: 'INEPT', scramble: 'PITNE', marks: [0, 1] },
      { answer: 'SKIES', scramble: 'SISKE', marks: [0] },
      { answer: 'IVORY', scramble: 'RVIOY', marks: [0] },
    ],
  },
  {
    num: 12,
    quizId: 'garble-7-20-26',
    live: '2026-07-20',
    dateLabel: 'July 20, 2026',
    clue: "A commute for astronauts who missed the bus.",
    final: 'MOONWALK',
    words: [
      { answer: 'KNOLL', scramble: 'NOLLK', marks: [0, 1, 3] },
      { answer: 'WOMAN', scramble: 'NOMWA', marks: [0, 3] },
      { answer: 'MERCY', scramble: 'YMRCE', marks: [0] },
      { answer: 'OPERA', scramble: 'PAEOR', marks: [0] },
      { answer: 'OFTEN', scramble: 'NEOFT', marks: [0] },
    ],
  },
  {
    num: 13,
    quizId: 'garble-7-21-26',
    live: '2026-07-21',
    dateLabel: 'July 21, 2026',
    clue: "The hero's permanent plus-one.",
    final: 'SIDEKICK',
    words: [
      { answer: 'CIVIC', scramble: 'CIICV', marks: [0] },
      { answer: 'SKUNK', scramble: 'NKKSU', marks: [0, 1] },
      { answer: 'KHAKI', scramble: 'HKAKI', marks: [0] },
      { answer: 'DIODE', scramble: 'DDEIO', marks: [0, 1] },
      { answer: 'IMBUE', scramble: 'MEUBI', marks: [0, 4] },
    ],
  },
  {
    num: 14,
    quizId: 'garble-7-22-26',
    live: '2026-07-22',
    dateLabel: 'July 22, 2026',
    clue: "Where cruise ships keep the extra drama.",
    final: 'OVERBOARD',
    words: [
      { answer: 'BRAVO', scramble: 'ABORV', marks: [0, 1, 3] },
      { answer: 'MAJOR', scramble: 'JAMRO', marks: [1, 3] },
      { answer: 'DODGE', scramble: 'EDODG', marks: [0, 1] },
      { answer: 'RODEO', scramble: 'EROOD', marks: [0] },
      { answer: 'EPOXY', scramble: 'YOPXE', marks: [0] },
    ],
  },
  {
    num: 15,
    quizId: 'garble-7-23-26',
    live: '2026-07-23',
    dateLabel: 'July 23, 2026',
    clue: "The comedian always gets the last word. This one.",
    final: 'PUNCHLINE',
    words: [
      { answer: 'PLUCK', scramble: 'CUKPL', marks: [0] },
      { answer: 'LOGIC', scramble: 'LGIOC', marks: [0, 4] },
      { answer: 'NINTH', scramble: 'HINTN', marks: [0, 2, 4] },
      { answer: 'UNITY', scramble: 'NYITU', marks: [0, 2] },
      { answer: 'ELOPE', scramble: 'EELPO', marks: [0] },
    ],
  },
  {
    num: 16,
    quizId: 'garble-7-24-26',
    live: '2026-07-24',
    dateLabel: 'July 24, 2026',
    clue: "Where marshmallows and ghost stories meet their end.",
    final: 'CAMPFIRE',
    words: [
      { answer: 'CABIN', scramble: 'IBCAN', marks: [0, 1] },
      { answer: 'PRIME', scramble: 'ERMPI', marks: [0, 3] },
      { answer: 'FLINT', scramble: 'ILFNT', marks: [0, 2] },
      { answer: 'ROBIN', scramble: 'NIBRO', marks: [0] },
      { answer: 'ENJOY', scramble: 'NOYJE', marks: [0] },
    ],
  },
  {
    num: 17,
    quizId: 'garble-7-25-26',
    live: '2026-07-25',
    dateLabel: 'July 25, 2026',
    clue: "The meeting you attend without leaving your chair.",
    final: 'DAYDREAM',
    words: [
      { answer: 'ADAGE', scramble: 'AAGED', marks: [0, 1] },
      { answer: 'MURKY', scramble: 'MRUKY', marks: [0, 4] },
      { answer: 'DINER', scramble: 'RNDIE', marks: [0, 4] },
      { answer: 'APRON', scramble: 'APNRO', marks: [0] },
      { answer: 'ERUPT', scramble: 'EURTP', marks: [0] },
    ],
  },
  {
    num: 18,
    quizId: 'garble-7-26-26',
    live: '2026-07-26',
    dateLabel: 'July 26, 2026',
    sunday: true,
    clue: "Every skyscraper's baby photo.",
    final: 'BLUEPRINT',
    // SUNDAY EDITION: every answer is SIX letters instead of five. Same five
    // words, same 9 marked letters feeding BLUEPRINT, just a longer unscramble.
    words: [
      { answer: 'BRIDGE', scramble: 'IEDGBR', marks: [0, 2] },
      { answer: 'PLANET', scramble: 'TNLEAP', marks: [0, 1] },
      { answer: 'ROCKET', scramble: 'KCRTOE', marks: [0, 4] },
      { answer: 'TURTLE', scramble: 'ETTLRU', marks: [0, 1] },
      { answer: 'SALMON', scramble: 'NLOSMA', marks: [5] },
    ],
  },
  {
    num: 19,
    quizId: 'garble-7-27-26',
    live: '2026-07-27',
    dateLabel: 'July 27, 2026',
    clue: "The ground's way of asking you to stay.",
    final: 'QUICKSAND',
    words: [
      { answer: 'QUILT', scramble: 'UTLQI', marks: [0, 1, 2] },
      { answer: 'SNACK', scramble: 'NSACK', marks: [3, 4] },
      { answer: 'DUSKY', scramble: 'YDKSU', marks: [0, 2] },
      { answer: 'ADOPT', scramble: 'ODAPT', marks: [0] },
      { answer: 'NUDGE', scramble: 'GNEDU', marks: [0] },
    ],
  },
  {
    num: 20,
    quizId: 'garble-7-28-26',
    live: '2026-07-28',
    dateLabel: 'July 28, 2026',
    clue: "Miles and miles without an inch of progress.",
    final: 'TREADMILL',
    words: [
      { answer: 'MEDAL', scramble: 'MDALE', marks: [0, 2] },
      { answer: 'LEMUR', scramble: 'ERMLU', marks: [0, 4] },
      { answer: 'TWANG', scramble: 'TNWGA', marks: [0, 2] },
      { answer: 'LINEN', scramble: 'ILNEN', marks: [0, 1] },
      { answer: 'EMBER', scramble: 'EEMRB', marks: [0] },
    ],
  },
  {
    num: 21,
    quizId: 'garble-7-29-26',
    live: '2026-07-29',
    dateLabel: 'July 29, 2026',
    clue: "The trip with a lifetime of terms and conditions.",
    final: 'HONEYMOON',
    words: [
      { answer: 'MOODY', scramble: 'OOMDY', marks: [0, 1] },
      { answer: 'HYENA', scramble: 'NAYEH', marks: [0, 1] },
      { answer: 'ONION', scramble: 'OONIN', marks: [0, 1] },
      { answer: 'ENEMY', scramble: 'NMEEY', marks: [0, 1] },
      { answer: 'OUNCE', scramble: 'NEOUC', marks: [0] },
    ],
  },
  {
    num: 22,
    quizId: 'garble-7-30-26',
    live: '2026-07-30',
    dateLabel: 'July 30, 2026',
    clue: "It never sails, but every ship trusts it.",
    final: 'LIGHTHOUSE',
    words: [
      { answer: 'GHOUL', scramble: 'LHOUG', marks: [0, 1] },
      { answer: 'HOTEL', scramble: 'HLEOT', marks: [0, 2] },
      { answer: 'LOUSE', scramble: 'OLUES', marks: [1, 2] },
      { answer: 'SLICE', scramble: 'LEISC', marks: [0, 1] },
      { answer: 'EXILE', scramble: 'EEILX', marks: [0, 2] },
    ],
  },
  {
    num: 23,
    quizId: 'garble-7-31-26',
    live: '2026-07-31',
    dateLabel: 'July 31, 2026',
    clue: "Winter's overdue apology, finally paid back in blossoms.",
    final: 'SPRINGTIME',
    words: [
      { answer: 'PLUSH', scramble: 'HPLUS', marks: [0, 3] },
      { answer: 'PRIZE', scramble: 'EIPRZ', marks: [1, 2] },
      { answer: 'GRANT', scramble: 'AGNTR', marks: [0, 3] },
      { answer: 'TWICE', scramble: 'CETIW', marks: [0, 2] },
      { answer: 'MONEY', scramble: 'EMOYN', marks: [0, 3] },
    ],
  },
  {
    num: 24,
    quizId: 'garble-8-1-26',
    live: '2026-08-01',
    dateLabel: 'August 1, 2026',
    clue: "The brain the whole heist quietly reports to.",
    final: 'MASTERMIND',
    words: [
      { answer: 'MAYBE', scramble: 'ABEMY', marks: [0, 1] },
      { answer: 'MUDDY', scramble: 'DDMYU', marks: [0, 2] },
      { answer: 'STUNT', scramble: 'NSTTU', marks: [0, 1] },
      { answer: 'RIVER', scramble: 'ERIRV', marks: [0, 3] },
      { answer: 'UNITY', scramble: 'ITNYU', marks: [1, 2] },
    ],
  },
  {
    num: 25,
    quizId: 'garble-8-2-26',
    live: '2026-08-02',
    dateLabel: 'August 2, 2026',
    sunday: true,
    clue: "What the map's X has been guarding all along.",
    final: 'TREASURE',
    words: [
      { answer: 'MARKET', scramble: 'AKTREM', marks: [1] },
      { answer: 'QUARTZ', scramble: 'URZATQ', marks: [1] },
      { answer: 'GRAVEL', scramble: 'RVLAEG', marks: [1] },
      { answer: 'ROTATE', scramble: 'OAETTR', marks: [0, 2, 5] },
      { answer: 'SQUARE', scramble: 'QAEURS', marks: [0, 5] },
    ],
  },
  {
    num: 26,
    quizId: 'garble-8-3-26',
    live: '2026-08-03',
    dateLabel: 'August 3, 2026',
    sunday: false,
    clue: "A pale ribbon of light the night lays across the floor.",
    final: 'MOONBEAM',
    words: [
      { answer: 'MONEY', scramble: 'OEMNY', marks: [0, 1, 2] },
      { answer: 'PLUMB', scramble: 'LMPUB', marks: [3] },
      { answer: 'THUMB', scramble: 'HMTUB', marks: [4] },
      { answer: 'GLOVE', scramble: 'LVGOE', marks: [2] },
      { answer: 'BRAVE', scramble: 'RVBAE', marks: [2, 4] },
    ],
  },
  {
    num: 27,
    quizId: 'garble-8-4-26',
    live: '2026-08-04',
    dateLabel: 'August 4, 2026',
    sunday: false,
    clue: "What floods the room the moment the blinds come up.",
    final: 'SUNSHINE',
    words: [
      { answer: 'SHINE', scramble: 'ENSHI', marks: [0, 1, 3, 4] },
      { answer: 'HOUSE', scramble: 'SHOEU', marks: [2] },
      { answer: 'SUNNY', scramble: 'USYNN', marks: [0] },
      { answer: 'MUSIC', scramble: 'CIMUS', marks: [3] },
      { answer: 'UNION', scramble: 'OUNNI', marks: [1] },
    ],
  },
  {
    num: 28,
    quizId: 'garble-8-5-26',
    live: '2026-08-05',
    dateLabel: 'August 5, 2026',
    sunday: false,
    clue: "The first pale light that ends the night.",
    final: 'DAYBREAK',
    words: [
      { answer: 'GRAND', scramble: 'NDGRA', marks: [1, 2, 4] },
      { answer: 'BRAVE', scramble: 'BERVA', marks: [0, 4] },
      { answer: 'RHYME', scramble: 'HMERY', marks: [2] },
      { answer: 'KOALA', scramble: 'OLKAA', marks: [0] },
      { answer: 'PLANT', scramble: 'PTLNA', marks: [2] },
    ],
  },
  {
    num: 29,
    quizId: 'garble-8-6-26',
    live: '2026-08-06',
    dateLabel: 'August 6, 2026',
    sunday: false,
    clue: "The finale that paints the Fourth of July sky.",
    final: 'FIREWORK',
    words: [
      { answer: 'FLOOR', scramble: 'OFLRO', marks: [0, 2, 4] },
      { answer: 'IVORY', scramble: 'VIYRO', marks: [0, 3] },
      { answer: 'CROWD', scramble: 'DWCRO', marks: [3] },
      { answer: 'BRAVE', scramble: 'EBRAV', marks: [4] },
      { answer: 'BRICK', scramble: 'KRIBC', marks: [4] },
    ],
  },
  {
    num: 30,
    quizId: 'garble-8-7-26',
    live: '2026-08-07',
    dateLabel: 'August 7, 2026',
    sunday: false,
    clue: "Winter's quiet white blanket, drifting down.",
    final: 'SNOWFALL',
    words: [
      { answer: 'FLOOR', scramble: 'FOLRO', marks: [0, 1, 2] },
      { answer: 'JELLY', scramble: 'EYLJL', marks: [2] },
      { answer: 'CROWD', scramble: 'ODCRW', marks: [3] },
      { answer: 'PLANT', scramble: 'PALTN', marks: [2, 3] },
      { answer: 'MUSIC', scramble: 'UCSMI', marks: [2] },
    ],
  },
  {
    num: 31,
    quizId: 'garble-8-8-26',
    live: '2026-08-08',
    dateLabel: 'August 8, 2026',
    sunday: false,
    clue: "What too much noise and paperwork leaves pounding.",
    final: 'HEADACHE',
    words: [
      { answer: 'BEACH', scramble: 'BEAHC', marks: [1, 2, 3, 4] },
      { answer: 'CHAIR', scramble: 'ARCHI', marks: [2] },
      { answer: 'KNEEL', scramble: 'LKNEE', marks: [2] },
      { answer: 'GRAND', scramble: 'GRADN', marks: [4] },
      { answer: 'HONEY', scramble: 'YNHOE', marks: [0] },
    ],
  },
  {
    num: 32,
    quizId: 'garble-8-9-26',
    live: '2026-08-09',
    dateLabel: 'August 9, 2026',
    sunday: true,
    clue: "Where every day feels like an endless holiday.",
    final: 'PARADISE',
    words: [
      { answer: 'PARADE', scramble: 'ERAAPD', marks: [0, 1, 2, 3] },
      { answer: 'ISLAND', scramble: 'ASDILN', marks: [5] },
      { answer: 'SAILOR', scramble: 'RISALO', marks: [2] },
      { answer: 'SPRING', scramble: 'GRPISN', marks: [0] },
      { answer: 'ENGINE', scramble: 'INEEGN', marks: [0] },
    ],
  },
  {
    num: 33,
    quizId: 'garble-8-10-26',
    live: '2026-08-10',
    dateLabel: 'August 10, 2026',
    sunday: false,
    clue: "The moon's slow climb over the evening horizon.",
    final: 'MOONRISE',
    words: [
      { answer: 'GOOSE', scramble: 'OGOES', marks: [1, 2, 3] },
      { answer: 'MONEY', scramble: 'NYMOE', marks: [0, 2] },
      { answer: 'SHINE', scramble: 'SEHIN', marks: [4] },
      { answer: 'UNION', scramble: 'NUINO', marks: [2] },
      { answer: 'RHYME', scramble: 'YERHM', marks: [0] },
    ],
  },

];
