// Puzzle data for Barter, the daily letter-trade lattice. Imported ONLY by the
// server page (app/barter/page.js), which filters live<=today before handing
// the bank to the client, so future boards never ship to the browser.
//
// AUTHORING RULES (enforced by scripts/verify-barter.mjs; regenerate boards
// with scripts/gen-barter.mjs, which shares its engine via scripts/barter-core.mjs):
//
//   - Weekdays are a 5x5 lattice: three across words on rows 0/2/4 and three
//     down words on columns 0/2/4, holes at the odd-odd cells, 21 tiles.
//     Sunday Editions are 7x7: four words each way, 40 tiles.
//   - `sol` is the answer grid ('.' = hole), `start` is the opening
//     arrangement of the SAME tile multiset. `par` is the PROVEN minimum
//     number of two-tile trades from start to sol (exact search over the
//     letter multigraph: misplaced tiles minus the maximum cycle decomposition).
//     The trade budget is always par + 5; the client derives it, never stores it.
//   - Par bands: weekday 11-14, Sunday 20-25. At most 2 tiles (Sunday 4) may
//     start on their correct square, and no word may start already solved.
//   - Solution words come from the common band of the shared vocabulary
//     (app/warmer/vocab.js top 20,000) AND the site dictionary
//     (public/crux-words.txt), minus the British-spelling and proper-noun
//     blocklists in scripts/barter-core.mjs. US spellings only. No word is
//     ever reused across the bank.
//   - Every board is UNIQUE UP TO TRANSPOSITION against that common pool: the
//     only common-word fillings of the lattice with these tiles are the answer
//     and its mirror, and the green/yellow feedback pins the answer itself.
//   - `sunday: true` is the source of truth for the Sunday Edition badge and
//     must sit on real Eastern Sundays only (size 7 if and only if sunday).
export const PUZZLES = [
  {
    num: 1,
    quizId: 'barter-8-14-26',
    live: '2026-08-14',
    dateLabel: 'August 14, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['alloy', 'e.o.e', 'gotta', 'i.t.s', 'shout'],
    start: ['easeo', 's.l.l', 'ttgoy', 'i.h.t', 'aotuo'],
  },
  {
    num: 2,
    quizId: 'barter-8-15-26',
    live: '2026-08-15',
    dateLabel: 'August 15, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['sniff', 'p.n.i', 'expel', 'a.u.e', 'rated'],
    start: ['iarte', 'p.a.l', 'eenps', 'x.n.i', 'eufdf'],
  },
  {
    num: 3,
    quizId: 'barter-8-16-26',
    live: '2026-08-16',
    dateLabel: 'August 16, 2026',
    sunday: true,
    size: 7,
    par: 24,
    sol: ['infancy', 'n.a.e.i', 'dispute', 'i.t.t.l', 'cheered', 'e.s.a.e', 'settled'],
    start: ['eeieeee', 't.t.n.t', 'psdcehf', 'd.s.n.a', 'irnaiil', 'e.c.l.a', 'euttysd'],
  },
  {
    num: 4,
    quizId: 'barter-8-17-26',
    live: '2026-08-17',
    dateLabel: 'August 17, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['exact', 'p.b.r', 'ozone', 'x.v.n', 'yield'],
    start: ['obtrx', 'v.a.n', 'dpezi', 'x.n.c', 'eyleo'],
  },
  {
    num: 5,
    quizId: 'barter-8-18-26',
    live: '2026-08-18',
    dateLabel: 'August 18, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['berry', 'l.e.u', 'opium', 'n.g.m', 'dandy'],
    start: ['yordm', 'u.e.d', 'nigen', 'u.r.b', 'lympa'],
  },
  {
    num: 6,
    quizId: 'barter-8-19-26',
    live: '2026-08-19',
    dateLabel: 'August 19, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['towel', 'o.o.e', 'round', 'c.n.g', 'hedge'],
    start: ['huocd', 't.r.g', 'oenol', 'w.e.g', 'eeond'],
  },
  {
    num: 7,
    quizId: 'barter-8-20-26',
    live: '2026-08-20',
    dateLabel: 'August 20, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['write', 'o.n.e', 'maker', 'e.e.i', 'nudge'],
    start: ['eekei', 'n.w.e', 'rerem', 'a.o.g', 'inudt'],
  },
  {
    num: 8,
    quizId: 'barter-8-21-26',
    live: '2026-08-21',
    dateLabel: 'August 21, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['dough', 'r.n.o', 'occur', 'w.l.d', 'niece'],
    start: ['wiedc', 'e.r.o', 'druog', 'o.u.n', 'chlcn'],
  },
  {
    num: 9,
    quizId: 'barter-8-22-26',
    live: '2026-08-22',
    dateLabel: 'August 22, 2026',
    sunday: false,
    size: 5,
    par: 12,
    sol: ['hotel', 'e.o.i', 'linen', 'l.a.e', 'oiled'],
    start: ['olioe', 'i.n.t', 'eledh', 'n.l.e', 'oeila'],
  },
  {
    num: 10,
    quizId: 'barter-8-23-26',
    live: '2026-08-23',
    dateLabel: 'August 23, 2026',
    sunday: true,
    size: 7,
    par: 25,
    sol: ['funeral', 'a.e.a.i', 'nailing', 'b.t.l.h', 'atheist', 's.e.n.e', 'enraged'],
    start: ['glnnirg', 'u.n.t.n', 'aeeflai', 'a.s.e.h', 'eieadet', 'a.l.r.b', 'esnihat'],
  },
  {
    num: 11,
    quizId: 'barter-8-24-26',
    live: '2026-08-24',
    dateLabel: 'August 24, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['rugby', 'o.u.a', 'which', 'e.l.o', 'ratio'],
    start: ['coaai', 'y.o.t', 'wbroi', 'r.e.u', 'lhguh'],
  },
  {
    num: 12,
    quizId: 'barter-8-25-26',
    live: '2026-08-25',
    dateLabel: 'August 25, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['giant', 'i.m.e', 'viola', 'e.u.s', 'nerve'],
    start: ['tioil', 'e.a.g', 'mrsae', 'n.n.e', 'vviue'],
  },
  {
    num: 13,
    quizId: 'barter-8-26-26',
    live: '2026-08-26',
    dateLabel: 'August 26, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['trove', 'h.c.x', 'inept', 'c.a.r', 'kinda'],
    start: ['rvare', 't.a.n', 'nipxd', 'e.c.h', 'tiock'],
  },
  {
    num: 14,
    quizId: 'barter-8-27-26',
    live: '2026-08-27',
    dateLabel: 'August 27, 2026',
    sunday: false,
    size: 5,
    par: 12,
    sol: ['stool', 'l.u.o', 'often', 'p.e.e', 'error'],
    start: ['trnet', 'o.r.e', 'losoo', 'e.l.o', 'fuper'],
  },
  {
    num: 15,
    quizId: 'barter-8-28-26',
    live: '2026-08-28',
    dateLabel: 'August 28, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['vowel', 'i.a.a', 'night', 'y.e.t', 'lodge'],
    start: ['enyhg', 'v.l.i', 'giett', 'e.o.l', 'awoda'],
  },
  {
    num: 16,
    quizId: 'barter-8-29-26',
    live: '2026-08-29',
    dateLabel: 'August 29, 2026',
    sunday: false,
    size: 5,
    par: 12,
    sol: ['famed', 'i.a.e', 'loyal', 'l.o.a', 'sorry'],
    start: ['oralo', 'l.s.r', 'edlma', 'i.o.y', 'yefaa'],
  },
  {
    num: 17,
    quizId: 'barter-8-30-26',
    live: '2026-08-30',
    dateLabel: 'August 30, 2026',
    sunday: true,
    size: 7,
    par: 24,
    sol: ['boating', 'a.d.l.r', 'revolve', 'r.i.e.e', 'insight', 'e.e.a.e', 'riddled'],
    start: ['treehod', 'i.e.d.i', 'glselro', 'l.d.e.a', 'dnbeagv', 'a.r.i.e', 'teriniv'],
  },
  {
    num: 18,
    quizId: 'barter-8-31-26',
    live: '2026-08-31',
    dateLabel: 'August 31, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['bloom', 'l.p.o', 'optic', 'c.e.k', 'kudos'],
    start: ['ikoud', 't.b.m', 'llcoo', 's.o.k', 'peopc'],
  },
  {
    num: 19,
    quizId: 'barter-9-1-26',
    live: '2026-09-01',
    dateLabel: 'September 1, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['delve', 'e.o.s', 'focus', 'e.u.a', 'risky'],
    start: ['deies', 'l.e.k', 'ousyr', 'c.e.f', 'soavu'],
  },
  {
    num: 20,
    quizId: 'barter-9-2-26',
    live: '2026-09-02',
    dateLabel: 'September 2, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['fling', 'o.n.i', 'ruler', 'g.e.l', 'entry'],
    start: ['enrer', 'i.f.l', 'eoygn', 'i.u.g', 'nltrl'],
  },
  {
    num: 21,
    quizId: 'barter-9-3-26',
    live: '2026-09-03',
    dateLabel: 'September 3, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['crack', 'r.r.n', 'eagle', 'e.u.e', 'dwell'],
    start: ['klelr', 'u.n.c', 'dreew', 'r.a.a', 'gcele'],
  },
  {
    num: 22,
    quizId: 'barter-9-4-26',
    live: '2026-09-04',
    dateLabel: 'September 4, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['shall', 't.n.a', 'edged', 'i.e.e', 'nylon'],
    start: ['ehlnd', 'e.a.g', 'saond', 'e.i.y', 'llnte'],
  },
  {
    num: 23,
    quizId: 'barter-9-5-26',
    live: '2026-09-05',
    dateLabel: 'September 5, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['cobra', 'i.l.p', 'treat', 'e.s.l', 'dusty'],
    start: ['srpir', 'o.l.t', 'uelyd', 'a.t.a', 'tbecs'],
  },
  {
    num: 24,
    quizId: 'barter-9-6-26',
    live: '2026-09-06',
    dateLabel: 'September 6, 2026',
    sunday: true,
    size: 7,
    par: 25,
    sol: ['impetus', 'n.r.r.w', 'storage', 't.c.i.l', 'eternal', 'a.s.e.e', 'desired'],
    start: ['aeedelp', 'e.e.i.w', 'grsrdin', 'l.e.a.t', 'atuiocs', 'e.r.r.t', 'tmssenr'],
  },
  {
    num: 25,
    quizId: 'barter-9-7-26',
    live: '2026-09-07',
    dateLabel: 'September 7, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['woken', 'h.a.o', 'inner', 'f.j.t', 'faith'],
    start: ['ottfr', 'o.n.a', 'nfwnj', 'a.e.i', 'hhike'],
  },
  {
    num: 26,
    quizId: 'barter-9-8-26',
    live: '2026-09-08',
    dateLabel: 'September 8, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['pearl', 'u.n.y', 'prism', 'i.m.p', 'leech'],
    start: ['splui', 'r.e.r', 'ecpmm', 'e.i.a', 'lynhp'],
  },
  {
    num: 27,
    quizId: 'barter-9-9-26',
    live: '2026-09-09',
    dateLabel: 'September 9, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['skirt', 'u.m.w', 'erase', 'd.g.e', 'elect'],
    start: ['atsmu', 'l.i.d', 'etrek', 'e.r.w', 'ceseg'],
  },
  {
    num: 28,
    quizId: 'barter-9-10-26',
    live: '2026-09-10',
    dateLabel: 'September 10, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['safer', 't.l.u', 'yours', 'l.t.t', 'emery'],
    start: ['yurso', 'f.t.l', 'lruse', 't.a.r', 'temey'],
  },
  {
    num: 29,
    quizId: 'barter-9-11-26',
    live: '2026-09-11',
    dateLabel: 'September 11, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['fluid', 'i.r.r', 'noble', 'a.a.s', 'longs'],
    start: ['irofl', 'n.r.d', 'sblog', 'i.a.a', 'nseul'],
  },
  {
    num: 30,
    quizId: 'barter-9-12-26',
    live: '2026-09-12',
    dateLabel: 'September 12, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['audio', 'c.i.t', 'tight', 'o.i.e', 'rotor'],
    start: ['triuh', 'r.o.t', 'idioo', 't.o.t', 'agiec'],
  },
  {
    num: 31,
    quizId: 'barter-9-13-26',
    live: '2026-09-13',
    dateLabel: 'September 13, 2026',
    sunday: true,
    size: 7,
    par: 25,
    sol: ['nominal', 'e.o.o.o', 'runaway', 'v.s.h.a', 'oatmeal', 'u.e.r.t', 'surgery'],
    start: ['ysrryao', 'a.n.o.i', 'wtomule', 'n.g.u.a', 'ovhltoa', 'r.u.m.e', 'esaerna'],
  },
  {
    num: 32,
    quizId: 'barter-9-14-26',
    live: '2026-09-14',
    dateLabel: 'September 14, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['ceded', 'h.a.u', 'actin', 'l.e.n', 'kiddo'],
    start: ['iecca', 'd.d.n', 'naued', 'o.l.e', 'dkiht'],
  },
  {
    num: 33,
    quizId: 'barter-9-15-26',
    live: '2026-09-15',
    dateLabel: 'September 15, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['arena', 'l.v.f', 'overt', 'n.n.e', 'ester'],
    start: ['vetfr', 'n.a.l', 'nrast', 'e.e.n', 'reove'],
  },
  {
    num: 34,
    quizId: 'barter-9-16-26',
    live: '2026-09-16',
    dateLabel: 'September 16, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['taker', 'h.a.h', 'early', 'r.m.m', 'evade'],
    start: ['rmvmh', 'y.e.r', 'adkea', 'r.h.t', 'aelae'],
  },
  {
    num: 35,
    quizId: 'barter-9-17-26',
    live: '2026-09-17',
    dateLabel: 'September 17, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['trail', 'u.l.a', 'noisy', 'e.g.e', 'diner'],
    start: ['dunao', 'y.i.r', 'geinr', 'e.e.l', 'lsita'],
  },
  {
    num: 36,
    quizId: 'barter-9-18-26',
    live: '2026-09-18',
    dateLabel: 'September 18, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['harms', 'a.a.w', 'taboo', 'e.i.r', 'sedan'],
    start: ['amrha', 'o.n.b', 'aadrs', 'w.o.e', 'iseta'],
  },
  {
    num: 37,
    quizId: 'barter-9-19-26',
    live: '2026-09-19',
    dateLabel: 'September 19, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['ebony', 'x.t.a', 'ethic', 'r.e.h', 'tarot'],
    start: ['tbatn', 'h.e.t', 'orahe', 'y.e.c', 'itoxr'],
  },
  {
    num: 38,
    quizId: 'barter-9-20-26',
    live: '2026-09-20',
    dateLabel: 'September 20, 2026',
    sunday: true,
    size: 7,
    par: 25,
    sol: ['haircut', 'a.g.o.e', 'mention', 's.o.n.u', 'tornado', 'e.e.g.u', 'redress'],
    start: ['neeeird', 't.h.c.d', 'oouraun', 'o.n.e.a', 'gtinstm', 'e.a.o.o', 'ssgeurr'],
  },
  {
    num: 39,
    quizId: 'barter-9-21-26',
    live: '2026-09-21',
    dateLabel: 'September 21, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['intro', 's.h.r', 'speed', 'u.f.e', 'enter'],
    start: ['rtisd', 'e.n.p', 'sunrr', 'e.e.h', 'feoet'],
  },
  {
    num: 40,
    quizId: 'barter-9-22-26',
    live: '2026-09-22',
    dateLabel: 'September 22, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['spent', 'a.a.r', 'nitro', 'd.e.o', 'strap'],
    start: ['dinrr', 'a.o.e', 'tpota', 'r.n.s', 'paest'],
  },
  {
    num: 41,
    quizId: 'barter-9-23-26',
    live: '2026-09-23',
    dateLabel: 'September 23, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['alibi', 'w.r.n', 'aloud', 'i.n.i', 'thyme'],
    start: ['ioedb', 'm.a.t', 'awrnl', 'n.i.i', 'iyhlu'],
  },
  {
    num: 42,
    quizId: 'barter-9-24-26',
    live: '2026-09-24',
    dateLabel: 'September 24, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['choir', 'r.l.e', 'onion', 's.v.a', 'shell'],
    start: ['laier', 'h.n.s', 'leoro', 'l.o.v', 'chnis'],
  },
  {
    num: 43,
    quizId: 'barter-9-25-26',
    live: '2026-09-25',
    dateLabel: 'September 25, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['shawl', 't.n.a', 'ionic', 'f.e.e', 'fixed'],
    start: ['nxehs', 'a.i.d', 'cfwei', 'f.l.e', 'naoit'],
  },
  {
    num: 44,
    quizId: 'barter-9-26-26',
    live: '2026-09-26',
    dateLabel: 'September 26, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['grail', 'o.r.a', 'orbit', 's.o.c', 'earth'],
    start: ['aabce', 'o.s.r', 'laigr', 'h.i.r', 'ttroo'],
  },
  {
    num: 45,
    quizId: 'barter-9-27-26',
    live: '2026-09-27',
    dateLabel: 'September 27, 2026',
    sunday: true,
    size: 7,
    par: 25,
    sol: ['checker', 'o.x.i.a', 'reigned', 'd.t.e.i', 'idiotic', 'a.n.i.a', 'logical'],
    start: ['iaicong', 'i.e.c.g', 'eaehoic', 'd.i.a.k', 'doreint', 'r.e.c.l', 'ailxdit'],
  },
  {
    num: 46,
    quizId: 'barter-9-28-26',
    live: '2026-09-28',
    dateLabel: 'September 28, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['unite', 'l.v.t', 'tooth', 'r.r.o', 'abyss'],
    start: ['lttst', 'e.v.s', 'otori', 'b.a.u', 'yhron'],
  },
  {
    num: 47,
    quizId: 'barter-9-29-26',
    live: '2026-09-29',
    dateLabel: 'September 29, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['quart', 'u.m.e', 'oxide', 't.n.t', 'epoch'],
    start: ['qtien', 'r.m.u', 'eceoh', 'p.x.o', 'atudt'],
  },
  {
    num: 48,
    quizId: 'barter-9-30-26',
    live: '2026-09-30',
    dateLabel: 'September 30, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['young', 'o.p.o', 'upped', 't.e.l', 'hardy'],
    start: ['oydpl', 'e.g.y', 'odpoa', 'u.n.e', 'thrpu'],
  },
  {
    num: 49,
    quizId: 'barter-10-1-26',
    live: '2026-10-01',
    dateLabel: 'October 1, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['mania', 'i.a.r', 'never', 'o.a.a', 'relay'],
    start: ['arrne', 'n.l.a', 'raeav', 'i.y.a', 'ioema'],
  },
  {
    num: 50,
    quizId: 'barter-10-2-26',
    live: '2026-10-02',
    dateLabel: 'October 2, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['spoof', 'm.l.a', 'audit', 's.e.t', 'hurry'],
    start: ['mslth', 'f.p.u', 'rsoiy', 'a.e.r', 'oadut'],
  },
  {
    num: 51,
    quizId: 'barter-10-3-26',
    live: '2026-10-03',
    dateLabel: 'October 3, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['scant', 'c.g.e', 'elite', 'n.l.n', 'every'],
    start: ['csetn', 'n.n.r', 'leelt', 'g.c.v', 'ieyea'],
  },
  {
    num: 52,
    quizId: 'barter-10-4-26',
    live: '2026-10-04',
    dateLabel: 'October 4, 2026',
    sunday: true,
    size: 7,
    par: 25,
    sol: ['donated', 'a.o.i.r', 'revenge', 'l.e.i.s', 'illness', 'n.l.s.e', 'granted'],
    start: ['eillnnr', 's.d.g.i', 'leiveas', 'e.l.n.o', 'rasdote', 'e.e.a.s', 'rdnnget'],
  },
  {
    num: 53,
    quizId: 'barter-10-5-26',
    live: '2026-10-05',
    dateLabel: 'October 5, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['boost', 'a.w.h', 'condo', 'o.e.s', 'nurse'],
    start: ['otern', 's.o.o', 'shnbc', 'w.s.a', 'uedoo'],
  },
  {
    num: 54,
    quizId: 'barter-10-6-26',
    live: '2026-10-06',
    dateLabel: 'October 6, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['mince', 'e.i.n', 'diced', 'a.e.e', 'lured'],
    start: ['cldrn', 'e.e.i', 'edune', 'a.i.i', 'emdce'],
  },
  {
    num: 55,
    quizId: 'barter-10-7-26',
    live: '2026-10-07',
    dateLabel: 'October 7, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['haram', 'o.a.i', 'peril', 'e.e.k', 'derby'],
    start: ['roalp', 'r.r.a', 'ehkea', 'y.e.i', 'bdemi'],
  },
  {
    num: 56,
    quizId: 'barter-10-8-26',
    live: '2026-10-08',
    dateLabel: 'October 8, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['mount', 'i.s.o', 'glued', 'h.a.a', 'tally'],
    start: ['duott', 'a.s.l', 'amhlu', 'n.o.i', 'glyea'],
  },
  {
    num: 57,
    quizId: 'barter-10-9-26',
    live: '2026-10-09',
    dateLabel: 'October 9, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['threw', 'r.h.a', 'using', 'c.n.o', 'known'],
    start: ['nonro', 't.r.w', 'sunie', 'w.h.h', 'cgakn'],
  },
  {
    num: 58,
    quizId: 'barter-10-10-26',
    live: '2026-10-10',
    dateLabel: 'October 10, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['vista', 'o.h.g', 'cargo', 'a.u.n', 'lobby'],
    start: ['cvals', 'u.g.i', 'tobna', 'a.b.o', 'yorgh'],
  },
  {
    num: 59,
    quizId: 'barter-10-11-26',
    live: '2026-10-11',
    dateLabel: 'October 11, 2026',
    sunday: true,
    size: 7,
    par: 25,
    sol: ['shatter', 'p.b.r.e', 'instant', 'n.t.i.i', 'adapter', 'c.i.o.e', 'honored'],
    start: ['iphnaco', 'e.t.i.r', 'ntostaa', 'i.r.b.e', 'horeire', 't.n.d.e', 'nspattd'],
  },
  {
    num: 60,
    quizId: 'barter-10-12-26',
    live: '2026-10-12',
    dateLabel: 'October 12, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['civil', 'l.o.a', 'inter', 'f.e.g', 'forte'],
    start: ['roeei', 'i.t.l', 'loafc', 'i.f.t', 'gnver'],
  },
  {
    num: 61,
    quizId: 'barter-10-13-26',
    live: '2026-10-13',
    dateLabel: 'October 13, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['chili', 'a.c.n', 'maize', 'e.n.r', 'legit'],
    start: ['zcier', 'e.n.l', 'iegta', 'n.h.m', 'iaicl'],
  },
  {
    num: 62,
    quizId: 'barter-10-14-26',
    live: '2026-10-14',
    dateLabel: 'October 14, 2026',
    sunday: false,
    size: 5,
    par: 12,
    sol: ['lunch', 'a.i.a', 'bonus', 'e.j.t', 'leafy'],
    start: ['baney', 'n.f.c', 'lalie', 't.j.s', 'oauuh'],
  },
  {
    num: 63,
    quizId: 'barter-10-15-26',
    live: '2026-10-15',
    dateLabel: 'October 15, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['roach', 'e.p.o', 'arrow', 'l.o.d', 'manly'],
    start: ['ordoc', 'a.e.o', 'ranlp', 'a.y.m', 'wlhor'],
  },
  {
    num: 64,
    quizId: 'barter-10-16-26',
    live: '2026-10-16',
    dateLabel: 'October 16, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['vivid', 'a.i.r', 'purge', 'o.a.a', 'ruled'],
    start: ['rrdap', 'u.a.e', 'argiv', 'u.i.i', 'edvol'],
  },
  {
    num: 65,
    quizId: 'barter-10-17-26',
    live: '2026-10-17',
    dateLabel: 'October 17, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['surge', 'h.a.i', 'aging', 'v.s.h', 'erect'],
    start: ['ershs', 'e.g.e', 'avrii', 'c.n.g', 'tahgu'],
  },
  {
    num: 66,
    quizId: 'barter-10-18-26',
    live: '2026-10-18',
    dateLabel: 'October 18, 2026',
    sunday: true,
    size: 7,
    par: 24,
    sol: ['wearing', 'r.e.m.u', 'acreage', 'p.o.g.s', 'possess', 'e.o.r.e', 'delayed'],
    start: ['gsassle', 'e.a.s.r', 'grpgeoe', 'y.e.w.e', 'adcomou', 'i.p.s.e', 'aeedrnr'],
  },
  {
    num: 67,
    quizId: 'barter-10-19-26',
    live: '2026-10-19',
    dateLabel: 'October 19, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['ether', 'q.a.a', 'union', 'i.r.c', 'psych'],
    start: ['tnnac', 's.o.u', 'crqhe', 'r.e.i', 'pihay'],
  },
  {
    num: 68,
    quizId: 'barter-10-20-26',
    live: '2026-10-20',
    dateLabel: 'October 20, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['alert', 't.m.i', 'least', 'a.i.a', 'salon'],
    start: ['aalii', 'l.a.a', 'osntl', 'e.s.r', 'tteam'],
  },
  {
    num: 69,
    quizId: 'barter-10-21-26',
    live: '2026-10-21',
    dateLabel: 'October 21, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['moved', 'o.o.o', 'widen', 'e.k.u', 'react'],
    start: ['oovaw', 'm.n.e', 'doecr', 't.o.e', 'ekuid'],
  },
  {
    num: 70,
    quizId: 'barter-10-22-26',
    live: '2026-10-22',
    dateLabel: 'October 22, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['quark', 'u.m.a', 'imply', 'l.l.a', 'tweak'],
    start: ['qtmle', 'u.k.k', 'yaarl', 'a.p.m', 'ulaiw'],
  },
  {
    num: 71,
    quizId: 'barter-10-23-26',
    live: '2026-10-23',
    dateLabel: 'October 23, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['quota', 'u.w.g', 'arise', 'i.n.n', 'light'],
    start: ['tnrui', 'q.e.u', 'gwoaa', 'i.s.g', 'lhnti'],
  },
  {
    num: 72,
    quizId: 'barter-10-24-26',
    live: '2026-10-24',
    dateLabel: 'October 24, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['alter', 's.o.e', 'kappa', 'e.i.d', 'decay'],
    start: ['deork', 'c.e.e', 'pslae', 'y.a.d', 'iaapt'],
  },
  {
    num: 73,
    quizId: 'barter-10-25-26',
    live: '2026-10-25',
    dateLabel: 'October 25, 2026',
    sunday: true,
    size: 7,
    par: 23,
    sol: ['painter', 'i.n.e.e', 'cleaned', 'k.r.d.h', 'lattice', 'e.i.n.a', 'dragged'],
    start: ['rdthdin', 'r.d.n.t', 'ipdgaae', 'e.c.n.r', 'angeeca', 'e.l.k.i', 'eealtei'],
  },
  {
    num: 74,
    quizId: 'barter-10-26-26',
    live: '2026-10-26',
    dateLabel: 'October 26, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['swear', 'h.r.u', 'avoid', 'l.d.d', 'enemy'],
    start: ['ndoim', 'h.e.l', 'ryrea', 'w.e.d', 'vsdau'],
  },
  {
    num: 75,
    quizId: 'barter-10-27-26',
    live: '2026-10-27',
    dateLabel: 'October 27, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['relic', 'e.e.l', 'plaza', 'e.p.s', 'lotus'],
    start: ['lusei', 'a.z.l', 'lpoee', 'p.e.t', 'scral'],
  },
  {
    num: 76,
    quizId: 'barter-10-28-26',
    live: '2026-10-28',
    dateLabel: 'October 28, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['grade', 'r.l.a', 'alias', 's.e.e', 'synod'],
    start: ['ssdrd', 'l.l.e', 'eeaiy', 'o.a.g', 'naras'],
  },
  {
    num: 77,
    quizId: 'barter-10-29-26',
    live: '2026-10-29',
    dateLabel: 'October 29, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['plaid', 'r.n.a', 'organ', 'm.l.c', 'obese'],
    start: ['oeser', 'n.a.n', 'arbcp', 'l.m.d', 'lgoia'],
  },
  {
    num: 78,
    quizId: 'barter-10-30-26',
    live: '2026-10-30',
    dateLabel: 'October 30, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['hinge', 'o.a.v', 'limbo', 'e.e.k', 'dodge'],
    start: ['eeioh', 'e.v.e', 'odmng', 'a.k.g', 'oblid'],
  },
  {
    num: 79,
    quizId: 'barter-10-31-26',
    live: '2026-10-31',
    dateLabel: 'October 31, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['plush', 'l.n.e', 'ulcer', 'm.u.o', 'eaten'],
    start: ['nslel', 'e.n.u', 'elmrc', 'u.e.a', 'touhp'],
  },
  {
    num: 80,
    quizId: 'barter-11-1-26',
    live: '2026-11-01',
    dateLabel: 'November 1, 2026',
    sunday: true,
    size: 7,
    par: 24,
    sol: ['cheetah', 'a.x.h.u', 'pattern', 'a.r.a.d', 'blaster', 'l.c.e.e', 'entered'],
    start: ['ntlncra', 't.a.e.a', 'hettdre', 's.e.r.e', 'eehacpa', 'x.e.h.a', 'udreblt'],
  },
  {
    num: 81,
    quizId: 'barter-11-2-26',
    live: '2026-11-02',
    dateLabel: 'November 2, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['munch', 'e.i.o', 'local', 'o.h.l', 'needy'],
    start: ['aenol', 'u.o.h', 'enodc', 'e.y.l', 'clhmi'],
  },
  {
    num: 82,
    quizId: 'barter-11-3-26',
    live: '2026-11-03',
    dateLabel: 'November 3, 2026',
    sunday: false,
    size: 5,
    par: 12,
    sol: ['revel', 'o.i.a', 'upset', 'g.i.e', 'hater'],
    start: ['hlapu', 'e.e.o', 'tetvs', 'g.a.i', 'riere'],
  },
  {
    num: 83,
    quizId: 'barter-11-4-26',
    live: '2026-11-04',
    dateLabel: 'November 4, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['nomad', 'o.i.e', 'tonic', 'c.u.o', 'husky'],
    start: ['hocao', 'd.t.o', 'oyusu', 'm.c.n', 'kenii'],
  },
  {
    num: 84,
    quizId: 'barter-11-5-26',
    live: '2026-11-05',
    dateLabel: 'November 5, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['motto', 'e.u.w', 'ramen', 'c.o.e', 'hired'],
    start: ['ueewt', 'h.o.e', 'rreto', 'a.m.n', 'iomcd'],
  },
  {
    num: 85,
    quizId: 'barter-11-6-26',
    live: '2026-11-06',
    dateLabel: 'November 6, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['siren', 'n.i.e', 'under', 'f.e.d', 'furry'],
    start: ['rreid', 'n.u.f', 'eeird', 'y.e.u', 'rnnfs'],
  },
  {
    num: 86,
    quizId: 'barter-11-7-26',
    live: '2026-11-07',
    dateLabel: 'November 7, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['dazed', 'e.o.r', 'banjo', 'u.e.o', 'tidal'],
    start: ['adebe', 'd.z.d', 'lenio', 'a.o.a', 'outrj'],
  },
  {
    num: 87,
    quizId: 'barter-11-8-26',
    live: '2026-11-08',
    dateLabel: 'November 8, 2026',
    sunday: true,
    size: 7,
    par: 25,
    sol: ['dictate', 'e.o.d.j', 'concave', 'i.t.m.c', 'dormant', 'e.o.n.e', 'diluted'],
    start: ['iaaojel', 'd.o.e.n', 'daoetnr', 'u.v.d.d', 'omctctt', 'm.t.i.e', 'cediecn'],
  },
  {
    num: 88,
    quizId: 'barter-11-9-26',
    live: '2026-11-09',
    dateLabel: 'November 9, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['flank', 'i.l.i', 'robot', 'e.u.t', 'dummy'],
    start: ['uoibu', 'e.t.t', 'mnlmo', 'y.k.d', 'ifrla'],
  },
  {
    num: 89,
    quizId: 'barter-11-10-26',
    live: '2026-11-10',
    dateLabel: 'November 10, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['range', 'i.o.l', 'voted', 'e.e.e', 'radar'],
    start: ['eeeno', 'd.d.v', 'raeog', 'a.a.r', 'etirl'],
  },
  {
    num: 90,
    quizId: 'barter-11-11-26',
    live: '2026-11-11',
    dateLabel: 'November 11, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['smith', 'h.n.i', 'excel', 'l.u.l', 'forty'],
    start: ['yttci', 'l.e.o', 'hfmll', 'n.u.r', 'xeihs'],
  },
  {
    num: 91,
    quizId: 'barter-11-12-26',
    live: '2026-11-12',
    dateLabel: 'November 12, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['small', 'w.l.u', 'attic', 'm.a.k', 'parry'],
    start: ['apwuk', 'l.a.s', 'larmt', 'c.t.r', 'laimy'],
  },
  {
    num: 92,
    quizId: 'barter-11-13-26',
    live: '2026-11-13',
    dateLabel: 'November 13, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['algae', 'n.r.x', 'group', 'e.o.a', 'remit'],
    start: ['rgmtg', 'a.a.o', 'nioea', 'e.l.e', 'pxurr'],
  },
  {
    num: 93,
    quizId: 'barter-11-14-26',
    live: '2026-11-14',
    dateLabel: 'November 14, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['brush', 'r.n.y', 'acted', 'n.i.r', 'delta'],
    start: ['tanbd', 'h.e.a', 'rtdnu', 'e.i.l', 'cyrsr'],
  },
  {
    num: 94,
    quizId: 'barter-11-15-26',
    live: '2026-11-15',
    dateLabel: 'November 15, 2026',
    sunday: true,
    size: 7,
    par: 25,
    sol: ['shopped', 'p.v.r.r', 'awesome', 'n.r.b.a', 'nestled', 'e.e.e.e', 'dreamed'],
    start: ['paeoawp', 's.r.s.s', 'ednenpr', 'd.t.a.e', 'mloeeem', 'e.r.e.v', 'ddberhe'],
  },
  {
    num: 95,
    quizId: 'barter-11-16-26',
    live: '2026-11-16',
    dateLabel: 'November 16, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['weird', 'a.d.a', 'freed', 'e.a.d', 'rally'],
    start: ['ydled', 'e.l.a', 'reawi', 'f.d.r', 'edaar'],
  },
  {
    num: 96,
    quizId: 'barter-11-17-26',
    live: '2026-11-17',
    dateLabel: 'November 17, 2026',
    sunday: false,
    size: 5,
    par: 12,
    sol: ['rodeo', 'a.e.d', 'paved', 'i.i.l', 'dolly'],
    start: ['loodl', 'i.i.l', 'pddya', 'o.r.e', 'evdae'],
  },
  {
    num: 97,
    quizId: 'barter-11-18-26',
    live: '2026-11-18',
    dateLabel: 'November 18, 2026',
    sunday: false,
    size: 5,
    par: 14,
    sol: ['flung', 'r.n.a', 'axiom', 'u.t.e', 'dryer'],
    start: ['aerfi', 'u.r.u', 'oydmn', 'a.n.l', 'tgxre'],
  },
  {
    num: 98,
    quizId: 'barter-11-19-26',
    live: '2026-11-19',
    dateLabel: 'November 19, 2026',
    sunday: false,
    size: 5,
    par: 13,
    sol: ['prone', 'i.a.n', 'pasta', 'e.i.c', 'reset'],
    start: ['staen', 'i.s.p', 'ciper', 'n.e.t', 'eaora'],
  },
];
