// Puzzle data for Emcee, the daily mini crossword. Imported ONLY by the
// server page (app/emcee/page.js), which filters live<=today before passing
// puzzles to the client — so future grids, and their answers, never ship to
// the browser (same gating as every other daily).
//
// Each puzzle: `grid` rows use '#' for a block and the SOLUTION letter for a
// fillable square (today's answers ship, like every daily). `across`/`down`
// carry {n, r, c, len, clue}; answers are read off the grid, and numbering
// follows standard crossword rules (validated by the generator). Weekdays are
// a 5x5 with 10 words; Sundays step up to a 7x7 pinwheel with 22. Score is
// words correct out of the word count — a full clean solve is score = total —
// with ties broken by fewest checks (guessesUsed) and then fastest time.
//
// ── AUTHORING RULES (added 2026-08-12 after a bad bulk extension) ──────────
//
// 1. EVERY CLUE IS HAND-WRITTEN AND CLUES ITS OWN ANSWER. Clues come from the
//    curated bank in scripts/emcee-wordbank.txt (WORD|clue, one per line), so
//    a word can only enter a grid if a real crossword clue exists for it.
//    NEVER generate a clue from a dictionary/WordNet gloss. The bulk batch
//    that filled 2026-08-11 → 2026-09-29 did exactly that and, because a
//    gloss defines a whole synonym set, it repeatedly clued the wrong word:
//    CUE was clued "Evidence that helps to solve a problem" (that is CLUE),
//    ACRES got the gloss of DEMESNE, PAR the gloss of PARITY, PEG the gloss
//    of LAND, PET the gloss of FAVORITE. Players read it as letters missing
//    from the words. Rebuilt 2026-08-12 from #28 on; #1–#27 are frozen.
// 2. GRIDS ARE FULLY CHECKED. Every white square belongs to BOTH an across
//    and a down word, so there are no 1-letter runs. On a 5x5 that means each
//    row and each column holds exactly one run, of length >= 2, which is what
//    gives exactly 10 words. #24 and #26 predate the rule and are grandfathered.
// 3. NO OBSCURITIES. Everyday words only. The old batch shipped ATE (the Greek
//    goddess), GRAD (one-hundredth of a right angle) and ORE (a Scandinavian
//    monetary subunit) — none of which belong in a one-minute mini.
// 4. VARIETY IS CAPPED ACROSS THE BANK, not just per board: an answer appears
//    at most 3 times, two boards share at most 2 answers (3 between two
//    Sundays, which carry 22 each), and no grid shape repeats within a week.
// 5. THE PAST IS FROZEN. Never rewrite a board that has already gone live.
//
// Regenerate with `node scripts/build-emcee-bank.mjs`; verify with
// `node scripts/verify-daily-banks.mjs emcee`, which enforces 1, 2 and 4.
export const PUZZLES = [
  {
    num: 1,
    quizId: 'emcee-7-16-26',
    live: '2026-07-16',
    dateLabel: 'July 16, 2026',
    sunday: false,
    size: 5,
    grid: ['##TOE', '#HEAR', 'SANTA', 'PUSH#', 'ALE##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Piggy that went to market' },
      { n: 4, r: 1, c: 1, len: 4, clue: 'Pick up with your ears' },
      { n: 5, r: 2, c: 0, len: 5, clue: 'Sleigh driver with a list' },
      { n: 6, r: 3, c: 0, len: 4, clue: 'Opposite of pull' },
      { n: 7, r: 4, c: 0, len: 3, clue: 'Pub pint' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Like a nail-biter\'s nerves' },
      { n: 2, r: 0, c: 3, len: 4, clue: 'Courtroom promise' },
      { n: 3, r: 0, c: 4, len: 3, clue: 'Historic stretch of time' },
      { n: 4, r: 1, c: 1, len: 4, clue: 'Big load to carry' },
      { n: 5, r: 2, c: 0, len: 3, clue: 'Place for a massage and a mud bath' },
    ],
  },
  {
    num: 2,
    quizId: 'emcee-7-17-26',
    live: '2026-07-17',
    dateLabel: 'July 17, 2026',
    sunday: false,
    size: 5,
    grid: ['#ELSE', 'BLOOD', 'AISLE', 'STEIN', 'HERD#'],
    across: [
      { n: 1, r: 0, c: 1, len: 4, clue: '"Or ___!" (threat ender)' },
      { n: 5, r: 1, c: 0, len: 5, clue: 'Type O fluid' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Walk down it at a wedding' },
      { n: 7, r: 3, c: 0, len: 5, clue: 'Oktoberfest mug' },
      { n: 8, r: 4, c: 0, len: 4, clue: 'Cattle crowd' },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: 'Top-tier' },
      { n: 2, r: 0, c: 2, len: 5, clue: 'One who didn\'t win' },
      { n: 3, r: 0, c: 3, len: 5, clue: 'Neither liquid nor gas' },
      { n: 4, r: 0, c: 4, len: 4, clue: 'Garden with a serpent' },
      { n: 5, r: 1, c: 0, len: 4, clue: 'Big party' },
    ],
  },
  {
    num: 3,
    quizId: 'emcee-7-18-26',
    live: '2026-07-18',
    dateLabel: 'July 18, 2026',
    sunday: false,
    size: 5,
    grid: ['#SET#', 'APART', 'RATIO', 'CREEP', '#END#'],
    across: [
      { n: 1, r: 0, c: 1, len: 3, clue: 'Tennis unit' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'Separated' },
      { n: 6, r: 2, c: 0, len: 5, clue: '16:9, for a TV screen' },
      { n: 7, r: 3, c: 0, len: 5, clue: 'Move like a cautious cat' },
      { n: 8, r: 4, c: 1, len: 3, clue: 'Finale' },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: 'Extra tire in the trunk' },
      { n: 2, r: 0, c: 2, len: 5, clue: 'Gone, as leftovers' },
      { n: 3, r: 0, c: 3, len: 5, clue: 'Gave it a shot' },
      { n: 4, r: 1, c: 0, len: 3, clue: 'Rainbow\'s shape' },
      { n: 5, r: 1, c: 4, len: 3, clue: 'Spinning toy' },
    ],
  },
  {
    num: 4,
    quizId: 'emcee-7-19-26',
    live: '2026-07-19',
    dateLabel: 'July 19, 2026',
    sunday: true,
    size: 7,
    grid: ['ARE#OWL', 'RIM#PIE', 'MOORING', '##TEN##', 'ACIDITY', 'DUO#OWE', 'DEN#NOT'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: '"How ___ you?"' },
      { n: 4, r: 0, c: 4, len: 3, clue: 'Night bird asking "who?"' },
      { n: 7, r: 1, c: 0, len: 3, clue: 'Basketball hoop\'s edge' },
      { n: 8, r: 1, c: 4, len: 3, clue: 'Dessert with a lattice crust' },
      { n: 9, r: 2, c: 0, len: 7, clue: 'Boat\'s tie-up spot' },
      { n: 11, r: 3, c: 2, len: 3, clue: 'Perfect gymnastics score' },
      { n: 12, r: 4, c: 0, len: 7, clue: 'What pH measures' },
      { n: 16, r: 5, c: 0, len: 3, clue: 'Batman and Robin, e.g.' },
      { n: 17, r: 5, c: 4, len: 3, clue: 'Have debts' },
      { n: 18, r: 6, c: 0, len: 3, clue: 'Lion\'s lair' },
      { n: 19, r: 6, c: 4, len: 3, clue: '"___ so fast!"' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Elbow\'s limb' },
      { n: 2, r: 0, c: 1, len: 3, clue: 'Brazil\'s carnival city, briefly' },
      { n: 3, r: 0, c: 2, len: 7, clue: 'Joy or anger' },
      { n: 4, r: 0, c: 4, len: 7, clue: 'Everyone has one, they say' },
      { n: 5, r: 0, c: 5, len: 3, clue: 'Come in first' },
      { n: 6, r: 0, c: 6, len: 3, clue: 'Relay race segment' },
      { n: 10, r: 2, c: 3, len: 3, clue: 'Stop-light color' },
      { n: 12, r: 4, c: 0, len: 3, clue: 'Do sums' },
      { n: 13, r: 4, c: 1, len: 3, clue: 'Pool stick' },
      { n: 14, r: 4, c: 5, len: 3, clue: 'Tango\'s number' },
      { n: 15, r: 4, c: 6, len: 3, clue: '"Are we there ___?"' },
    ],
  },
  {
    num: 5,
    quizId: 'emcee-7-20-26',
    live: '2026-07-20',
    dateLabel: 'July 20, 2026',
    sunday: false,
    size: 5,
    grid: ['#LATE', '#AWAY', 'SNAKE', 'ACRE#', 'TEEN#'],
    across: [
      { n: 1, r: 0, c: 1, len: 4, clue: 'Past the deadline' },
      { n: 5, r: 1, c: 1, len: 4, clue: 'Not home' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Slithering reptile' },
      { n: 7, r: 3, c: 0, len: 4, clue: 'Farm measure' },
      { n: 8, r: 4, c: 0, len: 4, clue: 'High schooler, usually' },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: 'Jousting knight\'s weapon' },
      { n: 2, r: 0, c: 2, len: 5, clue: 'In the know' },
      { n: 3, r: 0, c: 3, len: 5, clue: 'Not single' },
      { n: 4, r: 0, c: 4, len: 3, clue: 'Hurricane\'s calm center' },
      { n: 6, r: 2, c: 0, len: 3, clue: 'Took a seat' },
    ],
  },
  {
    num: 6,
    quizId: 'emcee-7-21-26',
    live: '2026-07-21',
    dateLabel: 'July 21, 2026',
    sunday: false,
    size: 5,
    grid: ['LEAN#', 'ENDED', 'STORE', 'SERVE', '#REED'],
    across: [
      { n: 1, r: 0, c: 0, len: 4, clue: 'Tilt, like Pisa\'s tower' },
      { n: 5, r: 1, c: 0, len: 5, clue: 'Wrapped up' },
      { n: 7, r: 2, c: 0, len: 5, clue: 'Where to shop' },
      { n: 8, r: 3, c: 0, len: 5, clue: 'Start a tennis point' },
      { n: 9, r: 4, c: 1, len: 4, clue: 'Clarinet mouthpiece part' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 4, clue: '"More or ___"' },
      { n: 2, r: 0, c: 1, len: 5, clue: 'Big key on a keyboard' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Love to bits' },
      { n: 4, r: 0, c: 3, len: 5, clue: 'Audacity' },
      { n: 6, r: 1, c: 4, len: 4, clue: 'Good Scout\'s daily act' },
    ],
  },
  {
    num: 7,
    quizId: 'emcee-7-22-26',
    live: '2026-07-22',
    dateLabel: 'July 22, 2026',
    sunday: false,
    size: 5,
    grid: ['##RAT', 'CHILI', 'LEGAL', 'ARISE', 'NOD##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Maze runner in a lab' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'Cook-off stew with beans' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Above board' },
      { n: 7, r: 3, c: 0, len: 5, clue: 'Get up' },
      { n: 8, r: 4, c: 0, len: 3, clue: 'Silent yes' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Not flexible' },
      { n: 2, r: 0, c: 3, len: 4, clue: '"Sadly..."' },
      { n: 3, r: 0, c: 4, len: 4, clue: 'Bathroom floor square' },
      { n: 4, r: 1, c: 0, len: 4, clue: 'Scottish family group' },
      { n: 5, r: 1, c: 1, len: 4, clue: 'Cape wearer' },
    ],
  },
  {
    num: 8,
    quizId: 'emcee-7-23-26',
    live: '2026-07-23',
    dateLabel: 'July 23, 2026',
    sunday: false,
    size: 5,
    grid: ['##ERA', '#FLAG', 'NIECE', 'ONCE#', 'WET##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'The disco ___' },
      { n: 4, r: 1, c: 1, len: 4, clue: 'Stars and Stripes, e.g.' },
      { n: 5, r: 2, c: 0, len: 5, clue: 'Sibling\'s daughter' },
      { n: 6, r: 3, c: 0, len: 4, clue: '"___ upon a time"' },
      { n: 7, r: 4, c: 0, len: 3, clue: 'Like fresh paint' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Choose by ballot' },
      { n: 2, r: 0, c: 3, len: 4, clue: 'Marathon, for one' },
      { n: 3, r: 0, c: 4, len: 3, clue: 'Birthday count' },
      { n: 4, r: 1, c: 1, len: 4, clue: 'Parking ticket penalty' },
      { n: 5, r: 2, c: 0, len: 3, clue: '"Do it ___!"' },
    ],
  },
  {
    num: 9,
    quizId: 'emcee-7-24-26',
    live: '2026-07-24',
    dateLabel: 'July 24, 2026',
    sunday: false,
    size: 5,
    grid: ['#CARE', 'SALAD', 'UNITE', 'RAVEN', 'FLED#'],
    across: [
      { n: 1, r: 0, c: 1, len: 4, clue: 'Handle with ___' },
      { n: 5, r: 1, c: 0, len: 5, clue: 'Course with croutons' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Come together' },
      { n: 7, r: 3, c: 0, len: 5, clue: 'Poe\'s "Nevermore" bird' },
      { n: 8, r: 4, c: 0, len: 4, clue: 'Ran off' },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: 'Panama passage' },
      { n: 2, r: 0, c: 2, len: 5, clue: '"It\'s ___!" (mad scientist\'s cry)' },
      { n: 3, r: 0, c: 3, len: 5, clue: 'Given stars' },
      { n: 4, r: 0, c: 4, len: 4, clue: 'Adam and Eve\'s address' },
      { n: 5, r: 1, c: 0, len: 4, clue: 'Ride a wave' },
    ],
  },
  {
    num: 10,
    quizId: 'emcee-7-25-26',
    live: '2026-07-25',
    dateLabel: 'July 25, 2026',
    sunday: false,
    size: 5,
    grid: ['#ANT#', 'BLOOM', 'ALIKE', 'RESET', '#YEN#'],
    across: [
      { n: 1, r: 0, c: 1, len: 3, clue: 'Picnic crasher' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'What roses do in spring' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Two peas in a pod are this' },
      { n: 7, r: 3, c: 0, len: 5, clue: 'Fix-it button on a router' },
      { n: 8, r: 4, c: 1, len: 3, clue: 'Tokyo currency' },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: 'Bowling lane' },
      { n: 2, r: 0, c: 2, len: 5, clue: 'Racket' },
      { n: 3, r: 0, c: 3, len: 5, clue: 'Arcade coin' },
      { n: 4, r: 1, c: 0, len: 3, clue: 'Chocolate unit' },
      { n: 5, r: 1, c: 4, len: 3, clue: 'Made someone\'s acquaintance' },
    ],
  },
  {
    num: 11,
    quizId: 'emcee-7-26-26',
    live: '2026-07-26',
    dateLabel: 'July 26, 2026',
    sunday: true,
    size: 7,
    grid: ['ARE#HAT', 'WED#EGO', 'EDITION', '##FOR##', 'STIPEND', 'ARC#SEE', 'DYE#SON'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: '"You ___ here"' },
      { n: 4, r: 0, c: 4, len: 3, clue: 'Top hat or beanie' },
      { n: 7, r: 1, c: 0, len: 3, clue: 'Tie the knot' },
      { n: 8, r: 1, c: 4, len: 3, clue: 'Sense of self' },
      { n: 9, r: 2, c: 0, len: 7, clue: 'Limited ___ (collector\'s release)' },
      { n: 11, r: 3, c: 2, len: 3, clue: '"___ example"' },
      { n: 12, r: 4, c: 0, len: 7, clue: 'Intern\'s modest pay' },
      { n: 16, r: 5, c: 0, len: 3, clue: 'Story ___ (plot line)' },
      { n: 17, r: 5, c: 4, len: 3, clue: '"___ you later!"' },
      { n: 18, r: 6, c: 0, len: 3, clue: 'Easter egg colorer' },
      { n: 19, r: 6, c: 4, len: 3, clue: 'Father\'s boy' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Grand Canyon reaction' },
      { n: 2, r: 0, c: 1, len: 3, clue: 'Rose\'s classic color' },
      { n: 3, r: 0, c: 2, len: 7, clue: 'Grand building' },
      { n: 4, r: 0, c: 4, len: 7, clue: 'Fortune inheritor' },
      { n: 5, r: 0, c: 5, len: 3, clue: 'Long, long ___' },
      { n: 6, r: 0, c: 6, len: 3, clue: '2,000 pounds' },
      { n: 10, r: 2, c: 3, len: 3, clue: 'Mountain\'s peak' },
      { n: 12, r: 4, c: 0, len: 3, clue: 'Blue' },
      { n: 13, r: 4, c: 1, len: 3, clue: 'Give it a whirl' },
      { n: 14, r: 4, c: 5, len: 3, clue: '"The Matrix" hero' },
      { n: 15, r: 4, c: 6, len: 3, clue: 'Cozy TV room' },
    ],
  },
  {
    num: 12,
    quizId: 'emcee-7-27-26',
    live: '2026-07-27',
    dateLabel: 'July 27, 2026',
    sunday: false,
    size: 5,
    grid: ['#STAR', '#HALO', 'HABIT', 'IDLE#', 'SEEN#'],
    across: [
      { n: 1, r: 0, c: 1, len: 4, clue: 'Walk of Fame symbol' },
      { n: 5, r: 1, c: 1, len: 4, clue: 'Angel\'s ring' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Hard thing to break' },
      { n: 7, r: 3, c: 0, len: 4, clue: 'Just sitting around' },
      { n: 8, r: 4, c: 0, len: 4, clue: 'Spotted' },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: 'Where to cool off on a sunny day' },
      { n: 2, r: 0, c: 2, len: 5, clue: 'Dinner setting spot' },
      { n: 3, r: 0, c: 3, len: 5, clue: 'UFO pilot' },
      { n: 4, r: 0, c: 4, len: 3, clue: 'Spoil' },
      { n: 6, r: 2, c: 0, len: 3, clue: 'Hers\' partner' },
    ],
  },
  {
    num: 13,
    quizId: 'emcee-7-28-26',
    live: '2026-07-28',
    dateLabel: 'July 28, 2026',
    sunday: false,
    size: 5,
    grid: ['##TEA', '#GRAY', 'FLARE', 'RUIN#', 'YET##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Earl Grey, e.g.' },
      { n: 4, r: 1, c: 1, len: 4, clue: 'Color of storm clouds' },
      { n: 5, r: 2, c: 0, len: 5, clue: 'Emergency roadside light' },
      { n: 6, r: 3, c: 0, len: 4, clue: 'Spoil completely' },
      { n: 7, r: 4, c: 0, len: 3, clue: 'So far' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Inherited quality' },
      { n: 2, r: 0, c: 3, len: 4, clue: 'Bring home, as a salary' },
      { n: 3, r: 0, c: 4, len: 3, clue: 'Sailor\'s yes' },
      { n: 4, r: 1, c: 1, len: 4, clue: 'Craft-table sticker' },
      { n: 5, r: 2, c: 0, len: 3, clue: 'Cook in hot oil' },
    ],
  },
  {
    num: 14,
    quizId: 'emcee-7-29-26',
    live: '2026-07-29',
    dateLabel: 'July 29, 2026',
    sunday: false,
    size: 5,
    grid: ['##ICE', 'STRAY', 'AROSE', 'LINED', 'TOY##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Rink surface' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'Shelter cat, once' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Got out of bed' },
      { n: 7, r: 3, c: 0, len: 5, clue: 'Like notebook paper' },
      { n: 8, r: 4, c: 0, len: 3, clue: 'Yo-yo or teddy bear' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: '"Rain on your wedding day," per Alanis' },
      { n: 2, r: 0, c: 3, len: 4, clue: 'Detective\'s assignment' },
      { n: 3, r: 0, c: 4, len: 4, clue: 'Looked at' },
      { n: 4, r: 1, c: 0, len: 4, clue: 'Pepper\'s partner' },
      { n: 5, r: 1, c: 1, len: 4, clue: 'Group of three' },
    ],
  },
  {
    num: 15,
    quizId: 'emcee-7-30-26',
    live: '2026-07-30',
    dateLabel: 'July 30, 2026',
    sunday: false,
    size: 5,
    grid: ['##RAT', 'AWARE', 'CIVIL', 'IDEAL', 'DEN##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Rodent that deserts a sinking ship' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'Not oblivious' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Polite, if a bit cool' },
      { n: 7, r: 3, c: 0, len: 5, clue: 'Just perfect' },
      { n: 8, r: 4, c: 0, len: 3, clue: 'Home office, often' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Glossy jet-black bird' },
      { n: 2, r: 0, c: 3, len: 4, clue: 'Opera showstopper' },
      { n: 3, r: 0, c: 4, len: 4, clue: 'Poker player\'s giveaway' },
      { n: 4, r: 1, c: 0, len: 4, clue: 'Opposite of base, in chemistry' },
      { n: 5, r: 1, c: 1, len: 4, clue: 'Not narrow' },
    ],
  },
  {
    num: 16,
    quizId: 'emcee-7-31-26',
    live: '2026-07-31',
    dateLabel: 'July 31, 2026',
    sunday: false,
    size: 5,
    grid: ['##RAG', 'SCOUR', 'PLANE', 'RUSTY', 'YET##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Old cloth for dusting' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'Scrub hard, as a greasy pan' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Jet at the airport' },
      { n: 7, r: 3, c: 0, len: 5, clue: 'Out of practice' },
      { n: 8, r: 4, c: 0, len: 3, clue: 'Nevertheless' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Cook in the oven, as a chicken' },
      { n: 2, r: 0, c: 3, len: 4, clue: 'Uncle\'s wife' },
      { n: 3, r: 0, c: 4, len: 4, clue: 'Elephant\'s hue' },
      { n: 4, r: 1, c: 0, len: 4, clue: 'Nimble, despite the years' },
      { n: 5, r: 1, c: 1, len: 4, clue: 'Detective\'s lead' },
    ],
  },
  {
    num: 17,
    quizId: 'emcee-8-1-26',
    live: '2026-08-01',
    dateLabel: 'August 1, 2026',
    sunday: false,
    size: 5,
    grid: ['RID##', 'ITEMS', 'OCTET', 'THEME', '##ROW'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Get ___ of (eliminate)' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'Things on a to-do list' },
      { n: 7, r: 2, c: 0, len: 5, clue: 'Group of eight singers' },
      { n: 8, r: 3, c: 0, len: 5, clue: 'Central topic of an essay' },
      { n: 9, r: 4, c: 2, len: 3, clue: 'Line of seats at a theater' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 4, clue: 'Unruly crowd disturbance' },
      { n: 2, r: 0, c: 1, len: 4, clue: 'Reason to scratch' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Discourage from doing something' },
      { n: 5, r: 1, c: 3, len: 4, clue: 'Quick office note' },
      { n: 6, r: 1, c: 4, len: 4, clue: 'Simmered beef-and-vegetable dish' },
    ],
  },
  {
    num: 18,
    quizId: 'emcee-8-2-26',
    live: '2026-08-02',
    dateLabel: 'August 2, 2026',
    sunday: true,
    size: 7,
    grid: ['DOE#GOO', 'OWL#END', 'NEEDLED', '##VIA##', 'PHANTOM', 'RAT#IRE', 'ODE#NET'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Female deer' },
      { n: 4, r: 0, c: 4, len: 3, clue: 'Sticky gunk' },
      { n: 7, r: 1, c: 0, len: 3, clue: 'Nighttime hooter' },
      { n: 8, r: 1, c: 4, len: 3, clue: 'Finish line, of a sort' },
      { n: 9, r: 2, c: 0, len: 7, clue: 'Teased or prodded persistently' },
      { n: 11, r: 3, c: 2, len: 3, clue: 'By way of' },
      { n: 12, r: 4, c: 0, len: 7, clue: 'Spooky apparition, or the "of the Opera"' },
      { n: 16, r: 5, c: 0, len: 3, clue: 'Sewer rodent' },
      { n: 17, r: 5, c: 4, len: 3, clue: 'Boiling anger' },
      { n: 18, r: 6, c: 0, len: 3, clue: 'Poem of praise' },
      { n: 19, r: 6, c: 4, len: 3, clue: "Goalie's target" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Put on, as a coat' },
      { n: 2, r: 0, c: 1, len: 3, clue: 'Be in debt' },
      { n: 3, r: 0, c: 2, len: 7, clue: 'Raise up' },
      { n: 4, r: 0, c: 4, len: 7, clue: 'Jell-O base' },
      { n: 5, r: 0, c: 5, len: 3, clue: 'The loneliest number, in song' },
      { n: 6, r: 0, c: 6, len: 3, clue: 'Not even' },
      { n: 10, r: 2, c: 3, len: 3, clue: 'Loud racket' },
      { n: 12, r: 4, c: 0, len: 3, clue: 'Seasoned expert' },
      { n: 13, r: 4, c: 1, len: 3, clue: 'Possessed, in the past' },
      { n: 14, r: 4, c: 5, len: 3, clue: 'Rock with metal in it' },
      { n: 15, r: 4, c: 6, len: 3, clue: 'Ran into, as an old friend' },
    ],
  },
  {
    num: 19,
    quizId: 'emcee-8-3-26',
    live: '2026-08-03',
    dateLabel: 'August 3, 2026',
    sunday: false,
    size: 5,
    grid: ['##RIB', 'PRIDE', 'EASEL', 'STEAL', 'TEN##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Barbecue rack cut' },
      { n: 4, r: 1, c: 0, len: 5, clue: "Lions' group, or a deadly sin" },
      { n: 6, r: 2, c: 0, len: 5, clue: "Painter's three-legged stand" },
      { n: 7, r: 3, c: 0, len: 5, clue: "Swipe, or a base runner's feat" },
      { n: 8, r: 4, c: 0, len: 3, clue: 'Perfect gymnastics score' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Come up, like bread dough' },
      { n: 2, r: 0, c: 3, len: 4, clue: 'Lightbulb moment' },
      { n: 3, r: 0, c: 4, len: 4, clue: 'It rings at recess' },
      { n: 4, r: 1, c: 0, len: 4, clue: 'Annoying little insect' },
      { n: 5, r: 1, c: 1, len: 4, clue: 'Speed, or an interest figure' },
    ],
  },
  {
    num: 20,
    quizId: 'emcee-8-4-26',
    live: '2026-08-04',
    dateLabel: 'August 4, 2026',
    sunday: false,
    size: 5,
    grid: ['##OUR', 'ABUSE', 'RATES', 'CREST', 'HER##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Belonging to us' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'Mistreat or misuse' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Hotel room prices' },
      { n: 7, r: 3, c: 0, len: 5, clue: 'Top of a hill or wave' },
      { n: 8, r: 4, c: 0, len: 3, clue: 'Belonging to her' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Farthest from the center' },
      { n: 2, r: 0, c: 3, len: 4, clue: 'Puts to work' },
      { n: 3, r: 0, c: 4, len: 4, clue: 'Take a breather' },
      { n: 4, r: 1, c: 0, len: 4, clue: 'Curved doorway shape' },
      { n: 5, r: 1, c: 1, len: 4, clue: 'Uncovered, as feet' },
    ],
  },
  {
    num: 21,
    quizId: 'emcee-8-5-26',
    live: '2026-08-05',
    dateLabel: 'August 5, 2026',
    sunday: false,
    size: 5,
    grid: ['#HASH', 'FORCE', 'ANGEL', 'SOUND', 'TREE#'],
    across: [
      { n: 1, r: 0, c: 1, len: 4, clue: 'Corned beef ___ (diner dish)' },
      { n: 5, r: 1, c: 0, len: 5, clue: 'Push or pull, in physics' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Winged heavenly figure' },
      { n: 7, r: 3, c: 0, len: 5, clue: 'What the ears pick up' },
      { n: 8, r: 4, c: 0, len: 4, clue: 'Oak or maple, for one' },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: 'Great respect' },
      { n: 2, r: 0, c: 2, len: 5, clue: 'Bicker heatedly' },
      { n: 3, r: 0, c: 3, len: 5, clue: 'Part of a play or movie' },
      { n: 4, r: 0, c: 4, len: 4, clue: 'Kept a firm grip on' },
      { n: 5, r: 1, c: 0, len: 4, clue: 'Speedy' },
    ],
  },
  {
    num: 22,
    quizId: 'emcee-8-6-26',
    live: '2026-08-06',
    dateLabel: 'August 6, 2026',
    sunday: false,
    size: 5,
    grid: ['ABS##', 'NOISE', 'TOTAL', 'ITEMS', '##SEE'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Six-pack muscles, briefly' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'Loud racket' },
      { n: 7, r: 2, c: 0, len: 5, clue: 'Grand sum' },
      { n: 8, r: 3, c: 0, len: 5, clue: 'Things on a shopping list' },
      { n: 9, r: 4, c: 2, len: 3, clue: 'Take a look' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 4, clue: 'Prefix meaning against' },
      { n: 2, r: 0, c: 1, len: 4, clue: 'Ankle-high footwear' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Construction locations' },
      { n: 5, r: 1, c: 3, len: 4, clue: 'Identical' },
      { n: 6, r: 1, c: 4, len: 4, clue: '"Or ___!"' },
    ],
  },
  {
    num: 23,
    quizId: 'emcee-8-7-26',
    live: '2026-08-07',
    dateLabel: 'August 7, 2026',
    sunday: false,
    size: 5,
    grid: ['STAR#', 'ERROR', 'PIECE', 'TANKS', '#LAST'],
    across: [
      { n: 1, r: 0, c: 0, len: 4, clue: 'Twinkler in the night sky' },
      { n: 5, r: 1, c: 0, len: 5, clue: 'Blooper or mistake' },
      { n: 7, r: 2, c: 0, len: 5, clue: 'Slice of pie, e.g.' },
      { n: 8, r: 3, c: 0, len: 5, clue: 'Treaded army vehicles' },
      { n: 9, r: 4, c: 1, len: 4, clue: 'Final' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 4, clue: 'Fall mo. after Aug.' },
      { n: 2, r: 0, c: 1, len: 5, clue: 'Courtroom proceeding' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Big indoor sports venue' },
      { n: 4, r: 0, c: 3, len: 5, clue: 'On the ___ (over ice)' },
      { n: 6, r: 1, c: 4, len: 4, clue: 'What weary legs need' },
    ],
  },
  {
    num: 24,
    quizId: 'emcee-8-8-26',
    live: '2026-08-08',
    dateLabel: 'August 8, 2026',
    sunday: false,
    size: 5,
    grid: ['E#PIG', 'SPICE', 'SALON', 'ALONE', 'YET#S'],
    across: [
      { n: 2, r: 0, c: 2, len: 3, clue: 'Barnyard animal that oinks' },
      { n: 5, r: 1, c: 0, len: 5, clue: 'Cinnamon or cumin' },
      { n: 7, r: 2, c: 0, len: 5, clue: 'Place for a haircut' },
      { n: 8, r: 3, c: 0, len: 5, clue: 'All by oneself' },
      { n: 9, r: 4, c: 0, len: 3, clue: 'Nevertheless' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 5, clue: 'Short written composition' },
      { n: 2, r: 0, c: 2, len: 5, clue: 'Cockpit occupant' },
      { n: 3, r: 0, c: 3, len: 4, clue: 'Little app symbol you tap' },
      { n: 4, r: 0, c: 4, len: 5, clue: 'Units of heredity' },
      { n: 6, r: 1, c: 1, len: 4, clue: 'Lacking color' },
    ],
  },
  {
    num: 25,
    quizId: 'emcee-8-9-26',
    live: '2026-08-09',
    dateLabel: 'August 9, 2026',
    sunday: true,
    size: 7,
    grid: ['HAS#ARE', 'ONE#BUG', 'WARNING', '##VOL##', 'SHERIFF', 'PAR#TEA', 'ADS#YEN'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Owns' },
      { n: 4, r: 0, c: 4, len: 3, clue: '"You ___ here"' },
      { n: 7, r: 1, c: 0, len: 3, clue: 'Loneliest number, in song' },
      { n: 8, r: 1, c: 4, len: 3, clue: 'Ladybug, for one' },
      { n: 9, r: 2, c: 0, len: 7, clue: 'Heads-up about danger' },
      { n: 11, r: 3, c: 2, len: 3, clue: 'Encyclopedia ___. (book abbr.)' },
      { n: 12, r: 4, c: 0, len: 7, clue: 'Wild West lawman with a badge' },
      { n: 16, r: 5, c: 0, len: 3, clue: 'Golf course standard' },
      { n: 17, r: 5, c: 4, len: 3, clue: 'Steeped hot drink' },
      { n: 18, r: 6, c: 0, len: 3, clue: 'Commercials, for short' },
      { n: 19, r: 6, c: 4, len: 3, clue: 'Currency in Tokyo' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: '"___ are you doing?"' },
      { n: 2, r: 0, c: 1, len: 3, clue: 'Actress de Armas' },
      { n: 3, r: 0, c: 2, len: 7, clue: 'Restaurant waitstaff' },
      { n: 4, r: 0, c: 4, len: 7, clue: 'Skill or talent' },
      { n: 5, r: 0, c: 5, len: 3, clue: 'Move faster than a walk' },
      { n: 6, r: 0, c: 6, len: 3, clue: 'Breakfast item you scramble' },
      { n: 10, r: 2, c: 3, len: 3, clue: 'Neither\'s partner' },
      { n: 12, r: 4, c: 0, len: 3, clue: 'Place for a mud bath' },
      { n: 13, r: 4, c: 1, len: 3, clue: 'Owned, in the past' },
      { n: 14, r: 4, c: 5, len: 3, clue: 'Charge for a service' },
      { n: 15, r: 4, c: 6, len: 3, clue: 'Cooling device on a hot day' },
    ],
  },
  {
    num: 26,
    quizId: 'emcee-8-10-26',
    live: '2026-08-10',
    dateLabel: 'August 10, 2026',
    sunday: false,
    size: 5,
    grid: ['ADS#R', 'CRIME', 'TOTAL', 'OPERA', 'R#SKY'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Magazine commercials' },
      { n: 5, r: 1, c: 0, len: 5, clue: 'Robbery or burglary' },
      { n: 7, r: 2, c: 0, len: 5, clue: 'Add up to' },
      { n: 8, r: 3, c: 0, len: 5, clue: 'Stage show full of arias' },
      { n: 9, r: 4, c: 2, len: 3, clue: 'Where the clouds drift' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 5, clue: 'Movie cast member' },
      { n: 2, r: 0, c: 1, len: 4, clue: 'Let fall' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Building locations' },
      { n: 4, r: 0, c: 4, len: 5, clue: 'Track race with a baton' },
      { n: 6, r: 1, c: 3, len: 4, clue: 'Grade on a test' },
    ],
  },
  {
    num: 27,
    quizId: 'emcee-8-11-26',
    live: '2026-08-11',
    dateLabel: 'August 11, 2026',
    sunday: false,
    size: 5,
    grid: ["##DIM", "##ERA", "CREEP", "ROD##", "YES##"],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: "Switch from a higher to a lower beam" },
      { n: 4, r: 1, c: 2, len: 3, clue: "Major division of geological time" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Move slowly" },
      { n: 7, r: 3, c: 0, len: 3, clue: "Long thin implement made of metal or wood" },
      { n: 8, r: 4, c: 0, len: 3, clue: "Affirmative" },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: "Performance of moral or religious acts" },
      { n: 2, r: 0, c: 3, len: 3, clue: "Strong emotion" },
      { n: 3, r: 0, c: 4, len: 3, clue: "Diagrammatic representation of the earth's surface" },
      { n: 5, r: 2, c: 0, len: 3, clue: "Loud utterance" },
      { n: 6, r: 2, c: 1, len: 3, clue: "Fish eggs or egg-filled ovary" },
    ],
  },
  {
    num: 28,
    quizId: 'emcee-8-12-26',
    rev: 2,   // grid rebuilt mid-day; resets in-flight saves
    live: '2026-08-12',
    dateLabel: 'August 12, 2026',
    sunday: false,
    size: 5,
    grid: ['ORAL#', 'HOLE#', 'METAL', '##EVE', '##RED'],
    across: [
      { n: 1, r: 0, c: 0, len: 4, clue: 'Spoken' },
      { n: 5, r: 1, c: 0, len: 4, clue: 'Donut\'s center' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Iron or tin' },
      { n: 8, r: 3, c: 2, len: 3, clue: 'Night before' },
      { n: 9, r: 4, c: 2, len: 3, clue: 'Stop sign color' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Resistance unit' },
      { n: 2, r: 0, c: 1, len: 3, clue: 'Fish eggs' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Change' },
      { n: 4, r: 0, c: 3, len: 5, clue: 'Head out' },
      { n: 7, r: 2, c: 4, len: 3, clue: 'Guided' },
    ],
  },
  {
    num: 29,
    quizId: 'emcee-8-13-26',
    live: '2026-08-13',
    dateLabel: 'August 13, 2026',
    sunday: false,
    size: 5,
    grid: ['SEEM#', 'ARROW', 'GRADE', '##SEA', '##ELK'],
    across: [
      { n: 1, r: 0, c: 0, len: 4, clue: 'Appear' },
      { n: 5, r: 1, c: 0, len: 5, clue: 'Bow\'s partner' },
      { n: 7, r: 2, c: 0, len: 5, clue: 'Report card mark' },
      { n: 8, r: 3, c: 2, len: 3, clue: 'Ocean' },
      { n: 9, r: 4, c: 2, len: 3, clue: 'Antlered animal' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Droop' },
      { n: 2, r: 0, c: 1, len: 3, clue: 'Slip up' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Rub out' },
      { n: 4, r: 0, c: 3, len: 5, clue: 'Runway walker' },
      { n: 6, r: 1, c: 4, len: 4, clue: 'Not strong' },
    ],
  },
  {
    num: 30,
    quizId: 'emcee-8-14-26',
    live: '2026-08-14',
    dateLabel: 'August 14, 2026',
    sunday: false,
    size: 5,
    grid: ['#ACE#', '#CLAM', 'STARE', 'POINT', 'ARM##'],
    across: [
      { n: 1, r: 0, c: 1, len: 3, clue: 'Serve that can\'t be returned' },
      { n: 4, r: 1, c: 1, len: 4, clue: 'Chowder shellfish' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Long look' },
      { n: 7, r: 3, c: 0, len: 5, clue: 'Pencil\'s tip' },
      { n: 8, r: 4, c: 0, len: 3, clue: 'Elbow\'s home' },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: 'Stage performer' },
      { n: 2, r: 0, c: 2, len: 5, clue: 'Assert' },
      { n: 3, r: 0, c: 3, len: 4, clue: 'Work for' },
      { n: 5, r: 1, c: 4, len: 3, clue: 'Ran into' },
      { n: 6, r: 2, c: 0, len: 3, clue: 'Massage destination' },
    ],
  },
  {
    num: 31,
    quizId: 'emcee-8-15-26',
    live: '2026-08-15',
    dateLabel: 'August 15, 2026',
    sunday: false,
    size: 5,
    grid: ['SOD##', 'OVEN#', 'MELON', 'ERASE', '##YEW'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Lawn strip' },
      { n: 4, r: 1, c: 0, len: 4, clue: 'Baking box' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Summer fruit' },
      { n: 8, r: 3, c: 0, len: 5, clue: 'Rub out' },
      { n: 9, r: 4, c: 2, len: 3, clue: 'Evergreen shrub' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 4, clue: 'A few' },
      { n: 2, r: 0, c: 1, len: 4, clue: 'Finished' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Hold up' },
      { n: 5, r: 1, c: 3, len: 4, clue: 'Smeller' },
      { n: 7, r: 2, c: 4, len: 3, clue: 'Fresh off the line' },
    ],
  },
  {
    num: 32,
    quizId: 'emcee-8-16-26',
    live: '2026-08-16',
    dateLabel: 'August 16, 2026',
    sunday: true,
    size: 7,
    grid: ['TIN#LAY', 'ALE#ICE', 'GLASSES', '##RUT##', 'ELEMENT', 'GAS#NOR', 'OPT#STY'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Cookie container' },
      { n: 4, r: 0, c: 4, len: 3, clue: 'Put down' },
      { n: 7, r: 1, c: 0, len: 3, clue: 'Pub pint' },
      { n: 8, r: 1, c: 4, len: 3, clue: 'Rink surface' },
      { n: 9, r: 2, c: 0, len: 7, clue: 'Spectacles' },
      { n: 11, r: 3, c: 2, len: 3, clue: 'Wheel groove' },
      { n: 12, r: 4, c: 0, len: 7, clue: 'Table entry' },
      { n: 16, r: 5, c: 0, len: 3, clue: 'Pump purchase' },
      { n: 17, r: 5, c: 4, len: 3, clue: 'Neither\'s partner' },
      { n: 18, r: 6, c: 0, len: 3, clue: 'Choose' },
      { n: 19, r: 6, c: 4, len: 3, clue: 'Pig\'s pen' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Playground chase' },
      { n: 2, r: 0, c: 1, len: 3, clue: 'Under the weather' },
      { n: 3, r: 0, c: 2, len: 7, clue: 'Closest' },
      { n: 4, r: 0, c: 4, len: 7, clue: 'Lends an ear' },
      { n: 5, r: 0, c: 5, len: 3, clue: 'Serve that can\'t be returned' },
      { n: 6, r: 0, c: 6, len: 3, clue: 'Affirmative reply' },
      { n: 10, r: 2, c: 3, len: 3, clue: 'Total' },
      { n: 12, r: 4, c: 0, len: 3, clue: 'Sense of self' },
      { n: 13, r: 4, c: 1, len: 3, clue: 'Track circuit' },
      { n: 14, r: 4, c: 5, len: 3, clue: 'Negative word' },
      { n: 15, r: 4, c: 6, len: 3, clue: 'Give it a shot' },
    ],
  },
  {
    num: 33,
    quizId: 'emcee-8-17-26',
    live: '2026-08-17',
    dateLabel: 'August 17, 2026',
    sunday: false,
    size: 5,
    grid: ['##SAW', 'APPLE', 'CEASE', 'HERO#', 'ELK##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Cutting tool' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'Orchard fruit' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Stop' },
      { n: 7, r: 3, c: 0, len: 4, clue: 'Caped rescuer' },
      { n: 8, r: 4, c: 0, len: 3, clue: 'Antlered animal' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Fire\'s start' },
      { n: 2, r: 0, c: 3, len: 4, clue: 'In addition' },
      { n: 3, r: 0, c: 4, len: 3, clue: 'Tiny' },
      { n: 4, r: 1, c: 0, len: 4, clue: 'Dull pain' },
      { n: 5, r: 1, c: 1, len: 4, clue: 'Banana\'s jacket' },
    ],
  },
  {
    num: 34,
    quizId: 'emcee-8-18-26',
    live: '2026-08-18',
    dateLabel: 'August 18, 2026',
    sunday: false,
    size: 5,
    grid: ['#SLIP', 'STORE', 'ORDER', 'LAG##', 'OWE##'],
    across: [
      { n: 1, r: 0, c: 1, len: 4, clue: 'Lose footing' },
      { n: 5, r: 1, c: 0, len: 5, clue: 'Shop' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Diner request' },
      { n: 7, r: 3, c: 0, len: 3, clue: 'Fall behind' },
      { n: 8, r: 4, c: 0, len: 3, clue: 'Be in debt' },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: 'Sipper' },
      { n: 2, r: 0, c: 2, len: 5, clue: 'Ski retreat' },
      { n: 3, r: 0, c: 3, len: 3, clue: 'Anger' },
      { n: 4, r: 0, c: 4, len: 3, clue: 'For each' },
      { n: 5, r: 1, c: 0, len: 4, clue: 'On one\'s own' },
    ],
  },
  {
    num: 35,
    quizId: 'emcee-8-19-26',
    live: '2026-08-19',
    dateLabel: 'August 19, 2026',
    sunday: false,
    size: 5,
    grid: ['SAP##', 'AGO##', 'DELTA', '#NAIL', '#TREE'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Maple syrup source' },
      { n: 4, r: 1, c: 0, len: 3, clue: 'In the past' },
      { n: 5, r: 2, c: 0, len: 5, clue: 'River\'s mouth' },
      { n: 8, r: 3, c: 1, len: 4, clue: 'Hammer\'s target' },
      { n: 9, r: 4, c: 1, len: 4, clue: 'Trunk and branches' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Feeling blue' },
      { n: 2, r: 0, c: 1, len: 5, clue: 'Deal broker' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Like a certain bear' },
      { n: 6, r: 2, c: 3, len: 3, clue: 'Neck accessory' },
      { n: 7, r: 2, c: 4, len: 3, clue: 'Pub pint' },
    ],
  },
  {
    num: 36,
    quizId: 'emcee-8-20-26',
    live: '2026-08-20',
    dateLabel: 'August 20, 2026',
    sunday: false,
    size: 5,
    grid: ['AHA##', 'MERIT', 'PRIDE', '##SEA', '##EAR'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: '"Got it!"' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'Deserve' },
      { n: 7, r: 2, c: 0, len: 5, clue: 'Lion group' },
      { n: 8, r: 3, c: 2, len: 3, clue: 'Ocean' },
      { n: 9, r: 4, c: 2, len: 3, clue: 'Corn unit' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Guitar\'s booster' },
      { n: 2, r: 0, c: 1, len: 3, clue: 'Belonging to she' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Get up' },
      { n: 5, r: 1, c: 3, len: 4, clue: 'Lightbulb moment' },
      { n: 6, r: 1, c: 4, len: 4, clue: 'Rip' },
    ],
  },
  {
    num: 37,
    quizId: 'emcee-8-21-26',
    live: '2026-08-21',
    dateLabel: 'August 21, 2026',
    sunday: false,
    size: 5,
    grid: ['CAR##', 'ORAL#', 'TODAY', '#MAKE', '#AREA'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Driveway sight' },
      { n: 4, r: 1, c: 0, len: 4, clue: 'Spoken' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'This very day' },
      { n: 8, r: 3, c: 1, len: 4, clue: 'Build' },
      { n: 9, r: 4, c: 1, len: 4, clue: 'Region' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Camp bed' },
      { n: 2, r: 0, c: 1, len: 5, clue: 'Kitchen smell' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Blip source' },
      { n: 5, r: 1, c: 3, len: 4, clue: 'Inland water' },
      { n: 7, r: 2, c: 4, len: 3, clue: 'Vote for' },
    ],
  },
  {
    num: 38,
    quizId: 'emcee-8-22-26',
    live: '2026-08-22',
    dateLabel: 'August 22, 2026',
    sunday: false,
    size: 5,
    grid: ['#SAFE', '#AWAY', 'BLADE', 'OAR##', 'ODD##'],
    across: [
      { n: 1, r: 0, c: 1, len: 4, clue: 'Out of danger' },
      { n: 5, r: 1, c: 1, len: 4, clue: 'Not here' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Knife\'s edge' },
      { n: 7, r: 3, c: 0, len: 3, clue: 'Rowboat paddle' },
      { n: 8, r: 4, c: 0, len: 3, clue: 'Not even' },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: 'Greens bowl' },
      { n: 2, r: 0, c: 2, len: 5, clue: 'Trophy' },
      { n: 3, r: 0, c: 3, len: 3, clue: 'Passing craze' },
      { n: 4, r: 0, c: 4, len: 3, clue: 'Needle\'s hole' },
      { n: 6, r: 2, c: 0, len: 3, clue: 'Ghost\'s greeting' },
    ],
  },
  {
    num: 39,
    quizId: 'emcee-8-23-26',
    live: '2026-08-23',
    dateLabel: 'August 23, 2026',
    sunday: true,
    size: 7,
    grid: ['EWE#WAY', 'LAP#ODE', 'FRIENDS', '##SAD##', 'PROTECT', 'ROD#RUE', 'OWE#SPA'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Female sheep' },
      { n: 4, r: 0, c: 4, len: 3, clue: 'Route' },
      { n: 7, r: 1, c: 0, len: 3, clue: 'Track circuit' },
      { n: 8, r: 1, c: 4, len: 3, clue: 'Poem of praise' },
      { n: 9, r: 2, c: 0, len: 7, clue: 'Pals' },
      { n: 11, r: 3, c: 2, len: 3, clue: 'Feeling blue' },
      { n: 12, r: 4, c: 0, len: 7, clue: 'Keep safe' },
      { n: 16, r: 5, c: 0, len: 3, clue: 'Fishing pole' },
      { n: 17, r: 5, c: 4, len: 3, clue: 'Feel sorry about' },
      { n: 18, r: 6, c: 0, len: 3, clue: 'Be in debt' },
      { n: 19, r: 6, c: 4, len: 3, clue: 'Massage destination' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Santa\'s helper' },
      { n: 2, r: 0, c: 1, len: 3, clue: 'Peace\'s opposite' },
      { n: 3, r: 0, c: 2, len: 7, clue: 'Series installment' },
      { n: 4, r: 0, c: 4, len: 7, clue: 'Marvels' },
      { n: 5, r: 0, c: 5, len: 3, clue: 'Do some sums' },
      { n: 6, r: 0, c: 6, len: 3, clue: 'Affirmative reply' },
      { n: 10, r: 2, c: 3, len: 3, clue: 'Have a meal' },
      { n: 12, r: 4, c: 0, len: 3, clue: 'Not an amateur' },
      { n: 13, r: 4, c: 1, len: 3, clue: 'Line of seats' },
      { n: 14, r: 4, c: 5, len: 3, clue: 'Coffee holder' },
      { n: 15, r: 4, c: 6, len: 3, clue: 'Steeped drink' },
    ],
  },
  {
    num: 40,
    quizId: 'emcee-8-24-26',
    live: '2026-08-24',
    dateLabel: 'August 24, 2026',
    sunday: false,
    size: 5,
    grid: ['MOB##', 'OUR##', 'STATE', 'SEVEN', '#READ'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Unruly crowd' },
      { n: 4, r: 1, c: 0, len: 3, clue: 'Belonging to us' },
      { n: 5, r: 2, c: 0, len: 5, clue: 'Fifty of them' },
      { n: 8, r: 3, c: 0, len: 5, clue: 'Lucky number' },
      { n: 9, r: 4, c: 1, len: 4, clue: 'Take in a book' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 4, clue: 'Rock\'s green' },
      { n: 2, r: 0, c: 1, len: 5, clue: 'Not inner' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Fearless' },
      { n: 6, r: 2, c: 3, len: 3, clue: 'Steeped drink' },
      { n: 7, r: 2, c: 4, len: 3, clue: 'Finish' },
    ],
  },
  {
    num: 41,
    quizId: 'emcee-8-25-26',
    live: '2026-08-25',
    dateLabel: 'August 25, 2026',
    sunday: false,
    size: 5,
    grid: ['NIP##', 'ACID#', 'BEARD', '##NAY', '##OWE'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Small bite' },
      { n: 4, r: 1, c: 0, len: 4, clue: 'Lemon juice quality' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Chin growth' },
      { n: 8, r: 3, c: 2, len: 3, clue: 'Vote against' },
      { n: 9, r: 4, c: 2, len: 3, clue: 'Be in debt' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Catch' },
      { n: 2, r: 0, c: 1, len: 3, clue: 'Rink surface' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Eighty-eight keys' },
      { n: 5, r: 1, c: 3, len: 4, clue: 'Sketch' },
      { n: 7, r: 2, c: 4, len: 3, clue: 'Change the color of' },
    ],
  },
  {
    num: 42,
    quizId: 'emcee-8-26-26',
    live: '2026-08-26',
    dateLabel: 'August 26, 2026',
    sunday: false,
    size: 5,
    grid: ['##BUS', 'ARENA', 'MERIT', 'PART#', '#DYE#'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'City ride with a route' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'Concert venue' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Deserve' },
      { n: 7, r: 3, c: 0, len: 4, clue: 'Piece' },
      { n: 8, r: 4, c: 1, len: 3, clue: 'Change the color of' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Blueberry, for one' },
      { n: 2, r: 0, c: 3, len: 5, clue: 'Join together' },
      { n: 3, r: 0, c: 4, len: 3, clue: 'Took a seat' },
      { n: 4, r: 1, c: 0, len: 3, clue: 'Guitar\'s booster' },
      { n: 5, r: 1, c: 1, len: 4, clue: 'Take in a book' },
    ],
  },
  {
    num: 43,
    quizId: 'emcee-8-27-26',
    live: '2026-08-27',
    dateLabel: 'August 27, 2026',
    sunday: false,
    size: 5,
    grid: ['ROAD#', 'UNDER', 'TEMPO', '##ITS', '##THE'],
    across: [
      { n: 1, r: 0, c: 0, len: 4, clue: 'Paved route' },
      { n: 5, r: 1, c: 0, len: 5, clue: 'Beneath' },
      { n: 7, r: 2, c: 0, len: 5, clue: 'Music\'s speed' },
      { n: 8, r: 3, c: 2, len: 3, clue: 'Belonging to it' },
      { n: 9, r: 4, c: 2, len: 3, clue: 'Most common article' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Wheel groove' },
      { n: 2, r: 0, c: 1, len: 3, clue: 'Number of noses you have' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Let in' },
      { n: 4, r: 0, c: 3, len: 5, clue: 'How deep' },
      { n: 6, r: 1, c: 4, len: 4, clue: 'Valentine flower' },
    ],
  },
  {
    num: 44,
    quizId: 'emcee-8-28-26',
    live: '2026-08-28',
    dateLabel: 'August 28, 2026',
    sunday: false,
    size: 5,
    grid: ['TIP##', 'ALIKE', 'BLEND', '##COG', '##EWE'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Waiter\'s extra' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'Two peas in a pod' },
      { n: 7, r: 2, c: 0, len: 5, clue: 'Mix together' },
      { n: 8, r: 3, c: 2, len: 3, clue: 'Gear tooth' },
      { n: 9, r: 4, c: 2, len: 3, clue: 'Female sheep' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Bar bill' },
      { n: 2, r: 0, c: 1, len: 3, clue: 'Under the weather' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Portion' },
      { n: 5, r: 1, c: 3, len: 4, clue: 'Be sure of' },
      { n: 6, r: 1, c: 4, len: 4, clue: 'Table\'s rim' },
    ],
  },
  {
    num: 45,
    quizId: 'emcee-8-29-26',
    live: '2026-08-29',
    dateLabel: 'August 29, 2026',
    sunday: false,
    size: 5,
    grid: ['#DOSE', 'METER', 'ALTER', 'STEM#', 'TAR##'],
    across: [
      { n: 1, r: 0, c: 1, len: 4, clue: 'Medicine amount' },
      { n: 5, r: 1, c: 0, len: 5, clue: 'Parking timer' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Change' },
      { n: 7, r: 3, c: 0, len: 4, clue: 'Flower\'s stalk' },
      { n: 8, r: 4, c: 0, len: 3, clue: 'Road paving goo' },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: 'River\'s mouth' },
      { n: 2, r: 0, c: 2, len: 5, clue: 'Playful swimmer' },
      { n: 3, r: 0, c: 3, len: 4, clue: 'Appear' },
      { n: 4, r: 0, c: 4, len: 3, clue: 'Slip up' },
      { n: 5, r: 1, c: 0, len: 4, clue: 'Sail\'s pole' },
    ],
  },
  {
    num: 46,
    quizId: 'emcee-8-30-26',
    live: '2026-08-30',
    dateLabel: 'August 30, 2026',
    sunday: true,
    size: 7,
    grid: ['YEP#SHE', 'AWL#PEG', 'KEEPING', '##AID##', 'RESPECT', 'ORE#ROE', 'BAD#SPA'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Casual yes' },
      { n: 4, r: 0, c: 4, len: 3, clue: 'That woman' },
      { n: 7, r: 1, c: 0, len: 3, clue: 'Leather punch' },
      { n: 8, r: 1, c: 4, len: 3, clue: 'Coat hook' },
      { n: 9, r: 2, c: 0, len: 7, clue: 'Holding on to' },
      { n: 11, r: 3, c: 2, len: 3, clue: 'Help out' },
      { n: 12, r: 4, c: 0, len: 7, clue: 'Look up to' },
      { n: 16, r: 5, c: 0, len: 3, clue: 'Miner\'s find' },
      { n: 17, r: 5, c: 4, len: 3, clue: 'Fish eggs' },
      { n: 18, r: 6, c: 0, len: 3, clue: 'Not good' },
      { n: 19, r: 6, c: 4, len: 3, clue: 'Massage destination' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Shaggy ox' },
      { n: 2, r: 0, c: 1, len: 3, clue: 'Female sheep' },
      { n: 3, r: 0, c: 2, len: 7, clue: 'Happy' },
      { n: 4, r: 0, c: 4, len: 7, clue: 'Web spinners' },
      { n: 5, r: 0, c: 5, len: 3, clue: 'Egg layer' },
      { n: 6, r: 0, c: 6, len: 3, clue: 'Breakfast oval' },
      { n: 10, r: 2, c: 3, len: 3, clue: 'Apple seed' },
      { n: 12, r: 4, c: 0, len: 3, clue: 'Hold up' },
      { n: 13, r: 4, c: 1, len: 3, clue: 'Historic stretch of time' },
      { n: 14, r: 4, c: 5, len: 3, clue: 'Officer on a beat' },
      { n: 15, r: 4, c: 6, len: 3, clue: 'Steeped drink' },
    ],
  },
  {
    num: 47,
    quizId: 'emcee-8-31-26',
    live: '2026-08-31',
    dateLabel: 'August 31, 2026',
    sunday: false,
    size: 5,
    grid: ['HOT##', 'OAR##', 'STAGE', 'THING', '##LUG'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Like a stove top' },
      { n: 4, r: 1, c: 0, len: 3, clue: 'Rowboat paddle' },
      { n: 5, r: 2, c: 0, len: 5, clue: 'Theater platform' },
      { n: 8, r: 3, c: 0, len: 5, clue: 'Object' },
      { n: 9, r: 4, c: 2, len: 3, clue: 'Haul' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 4, clue: 'Party thrower' },
      { n: 2, r: 0, c: 1, len: 4, clue: 'Courtroom promise' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Hiker\'s path' },
      { n: 6, r: 2, c: 3, len: 3, clue: 'African antelope' },
      { n: 7, r: 2, c: 4, len: 3, clue: 'Breakfast oval' },
    ],
  },
  {
    num: 48,
    quizId: 'emcee-9-1-26',
    live: '2026-09-01',
    dateLabel: 'September 1, 2026',
    sunday: false,
    size: 5,
    grid: ['##POP', '##EVE', 'ORDER', 'ROAR#', 'EEL##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Soda' },
      { n: 4, r: 1, c: 2, len: 3, clue: 'Night before' },
      { n: 5, r: 2, c: 0, len: 5, clue: 'Diner request' },
      { n: 7, r: 3, c: 0, len: 4, clue: 'Lion\'s sound' },
      { n: 8, r: 4, c: 0, len: 3, clue: 'Slippery swimmer' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Bike pusher' },
      { n: 2, r: 0, c: 3, len: 4, clue: 'Finished' },
      { n: 3, r: 0, c: 4, len: 3, clue: 'For each' },
      { n: 5, r: 2, c: 0, len: 3, clue: 'Miner\'s find' },
      { n: 6, r: 2, c: 1, len: 3, clue: 'Fish eggs' },
    ],
  },
  {
    num: 49,
    quizId: 'emcee-9-2-26',
    live: '2026-09-02',
    dateLabel: 'September 2, 2026',
    sunday: false,
    size: 5,
    grid: ['##GAP', '##ORE', 'AROMA', 'HIS##', 'AGE##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Space between' },
      { n: 4, r: 1, c: 2, len: 3, clue: 'Miner\'s find' },
      { n: 5, r: 2, c: 0, len: 5, clue: 'Kitchen smell' },
      { n: 7, r: 3, c: 0, len: 3, clue: 'Belonging to he' },
      { n: 8, r: 4, c: 0, len: 3, clue: 'Number of birthdays' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Honking bird' },
      { n: 2, r: 0, c: 3, len: 3, clue: 'Elbow\'s home' },
      { n: 3, r: 0, c: 4, len: 3, clue: 'Pod veggie' },
      { n: 5, r: 2, c: 0, len: 3, clue: '"Got it!"' },
      { n: 6, r: 2, c: 1, len: 3, clue: 'Set up' },
    ],
  },
  {
    num: 50,
    quizId: 'emcee-9-3-26',
    live: '2026-09-03',
    dateLabel: 'September 3, 2026',
    sunday: false,
    size: 5,
    grid: ['##BID', '#CARE', 'WAGON', 'EVEN#', 'EEL##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Auction offer' },
      { n: 4, r: 1, c: 1, len: 4, clue: 'Look after' },
      { n: 5, r: 2, c: 0, len: 5, clue: 'Kid\'s puller' },
      { n: 6, r: 3, c: 0, len: 4, clue: 'Not odd' },
      { n: 7, r: 4, c: 0, len: 3, clue: 'Slippery swimmer' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Boiled-then-baked roll' },
      { n: 2, r: 0, c: 3, len: 4, clue: 'Wrinkle remover' },
      { n: 3, r: 0, c: 4, len: 3, clue: 'Cozy home room' },
      { n: 4, r: 1, c: 1, len: 4, clue: 'Bat\'s home' },
      { n: 5, r: 2, c: 0, len: 3, clue: 'Tiny' },
    ],
  },
  {
    num: 51,
    quizId: 'emcee-9-4-26',
    live: '2026-09-04',
    dateLabel: 'September 4, 2026',
    sunday: false,
    size: 5,
    grid: ['LAB##', 'OIL##', 'BRASS', '##NUT', '##KEY'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Science room' },
      { n: 4, r: 1, c: 0, len: 3, clue: 'Salad dressing base' },
      { n: 5, r: 2, c: 0, len: 5, clue: 'Trumpet metal' },
      { n: 8, r: 3, c: 2, len: 3, clue: 'Bolt\'s partner' },
      { n: 9, r: 4, c: 2, len: 3, clue: 'Lock opener' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'High toss' },
      { n: 2, r: 0, c: 1, len: 3, clue: 'What you breathe' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Empty' },
      { n: 6, r: 2, c: 3, len: 3, clue: 'Take to court' },
      { n: 7, r: 2, c: 4, len: 3, clue: 'Pig\'s pen' },
    ],
  },
  {
    num: 52,
    quizId: 'emcee-9-5-26',
    live: '2026-09-05',
    dateLabel: 'September 5, 2026',
    sunday: false,
    size: 5,
    grid: ['#CAGE', 'DELAY', 'RAISE', 'ASK##', 'WEE##'],
    across: [
      { n: 1, r: 0, c: 1, len: 4, clue: 'Zoo enclosure' },
      { n: 5, r: 1, c: 0, len: 5, clue: 'Hold up' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Lift up' },
      { n: 7, r: 3, c: 0, len: 3, clue: 'Pose a question' },
      { n: 8, r: 4, c: 0, len: 3, clue: 'Tiny' },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: 'Stop' },
      { n: 2, r: 0, c: 2, len: 5, clue: 'Two peas in a pod' },
      { n: 3, r: 0, c: 3, len: 3, clue: 'Pump purchase' },
      { n: 4, r: 0, c: 4, len: 3, clue: 'Needle\'s hole' },
      { n: 5, r: 1, c: 0, len: 4, clue: 'Sketch' },
    ],
  },
  {
    num: 53,
    quizId: 'emcee-9-6-26',
    live: '2026-09-06',
    dateLabel: 'September 6, 2026',
    sunday: true,
    size: 7,
    grid: ['ORB#PAN', 'DUE#EGO', 'ENTERED', '##TAM##', 'INITIAL', 'RAN#THE', 'EGG#SAT'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Sphere' },
      { n: 4, r: 0, c: 4, len: 3, clue: 'Skillet' },
      { n: 7, r: 1, c: 0, len: 3, clue: 'Owed' },
      { n: 8, r: 1, c: 4, len: 3, clue: 'Sense of self' },
      { n: 9, r: 2, c: 0, len: 7, clue: 'Went in' },
      { n: 11, r: 3, c: 2, len: 3, clue: 'Scottish cap' },
      { n: 12, r: 4, c: 0, len: 7, clue: 'First letter' },
      { n: 16, r: 5, c: 0, len: 3, clue: 'Took off' },
      { n: 17, r: 5, c: 4, len: 3, clue: 'Most common article' },
      { n: 18, r: 6, c: 0, len: 3, clue: 'Breakfast oval' },
      { n: 19, r: 6, c: 4, len: 3, clue: 'Took a seat' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Poem of praise' },
      { n: 2, r: 0, c: 1, len: 3, clue: 'Sprint' },
      { n: 3, r: 0, c: 2, len: 7, clue: 'Wagering' },
      { n: 4, r: 0, c: 4, len: 7, clue: 'Allows' },
      { n: 5, r: 0, c: 5, len: 3, clue: 'Number of birthdays' },
      { n: 6, r: 0, c: 6, len: 3, clue: 'Yes, wordlessly' },
      { n: 10, r: 2, c: 3, len: 3, clue: 'Have a meal' },
      { n: 12, r: 4, c: 0, len: 3, clue: 'Anger' },
      { n: 13, r: 4, c: 1, len: 3, clue: 'Pester' },
      { n: 14, r: 4, c: 5, len: 3, clue: '"Got it!"' },
      { n: 15, r: 4, c: 6, len: 3, clue: 'Allow' },
    ],
  },
  {
    num: 54,
    quizId: 'emcee-9-7-26',
    live: '2026-09-07',
    dateLabel: 'September 7, 2026',
    sunday: false,
    size: 5,
    grid: ['BEST#', 'OATH#', 'GREEN', '##EMU', '##PET'],
    across: [
      { n: 1, r: 0, c: 0, len: 4, clue: 'Top of the heap' },
      { n: 5, r: 1, c: 0, len: 4, clue: 'Courtroom promise' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Grass color' },
      { n: 8, r: 3, c: 2, len: 3, clue: 'Flightless bird' },
      { n: 9, r: 4, c: 2, len: 3, clue: 'Dog or cat' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Marshy ground' },
      { n: 2, r: 0, c: 1, len: 3, clue: 'Corn unit' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Sharply sloped' },
      { n: 4, r: 0, c: 3, len: 5, clue: 'Party\'s motif' },
      { n: 7, r: 2, c: 4, len: 3, clue: 'Bolt\'s partner' },
    ],
  },
  {
    num: 55,
    quizId: 'emcee-9-8-26',
    live: '2026-09-08',
    dateLabel: 'September 8, 2026',
    sunday: false,
    size: 5,
    grid: ['##PEN', '#HIRE', 'HEART', 'URN##', 'GOO##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Ink writer' },
      { n: 4, r: 1, c: 1, len: 4, clue: 'Take on staff' },
      { n: 5, r: 2, c: 0, len: 5, clue: 'Valentine shape' },
      { n: 6, r: 3, c: 0, len: 3, clue: 'Coffee dispenser' },
      { n: 7, r: 4, c: 0, len: 3, clue: 'Sticky stuff' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Eighty-eight keys' },
      { n: 2, r: 0, c: 3, len: 3, clue: 'Slip up' },
      { n: 3, r: 0, c: 4, len: 3, clue: 'Tennis divider' },
      { n: 4, r: 1, c: 1, len: 4, clue: 'Caped rescuer' },
      { n: 5, r: 2, c: 0, len: 3, clue: 'Warm squeeze' },
    ],
  },
  {
    num: 56,
    quizId: 'emcee-9-9-26',
    live: '2026-09-09',
    dateLabel: 'September 9, 2026',
    sunday: false,
    size: 5,
    grid: ['ELM##', 'BOA##', 'BAGEL', '#FIRE', '##CAT'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Shade tree' },
      { n: 4, r: 1, c: 0, len: 3, clue: 'Feathery scarf' },
      { n: 5, r: 2, c: 0, len: 5, clue: 'Boiled-then-baked roll' },
      { n: 8, r: 3, c: 1, len: 4, clue: 'Campsite blaze' },
      { n: 9, r: 4, c: 2, len: 3, clue: 'Purring pet' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Tide\'s retreat' },
      { n: 2, r: 0, c: 1, len: 4, clue: 'Bread unit' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Rabbit-from-a-hat art' },
      { n: 6, r: 2, c: 3, len: 3, clue: 'Historic stretch of time' },
      { n: 7, r: 2, c: 4, len: 3, clue: 'Allow' },
    ],
  },
  {
    num: 57,
    quizId: 'emcee-9-10-26',
    live: '2026-09-10',
    dateLabel: 'September 10, 2026',
    sunday: false,
    size: 5,
    grid: ['ALSO#', 'ROOT#', 'MOUTH', '#KNEE', '##DRY'],
    across: [
      { n: 1, r: 0, c: 0, len: 4, clue: 'In addition' },
      { n: 5, r: 1, c: 0, len: 4, clue: 'Plant\'s anchor' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Where food goes' },
      { n: 8, r: 3, c: 1, len: 4, clue: 'Leg joint' },
      { n: 9, r: 4, c: 2, len: 3, clue: 'Not wet' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Elbow\'s home' },
      { n: 2, r: 0, c: 1, len: 4, clue: 'Take a peek' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Ear\'s input' },
      { n: 4, r: 0, c: 3, len: 5, clue: 'Playful swimmer' },
      { n: 7, r: 2, c: 4, len: 3, clue: 'Attention getter' },
    ],
  },
  {
    num: 58,
    quizId: 'emcee-9-11-26',
    live: '2026-09-11',
    dateLabel: 'September 11, 2026',
    sunday: false,
    size: 5,
    grid: ['##HIM', 'ALONE', 'MOUNT', 'POSE#', '#PER#'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'That fellow' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'By yourself' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Climb onto' },
      { n: 7, r: 3, c: 0, len: 4, clue: 'Model\'s stance' },
      { n: 8, r: 4, c: 1, len: 3, clue: 'For each' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Home' },
      { n: 2, r: 0, c: 3, len: 5, clue: 'Not outer' },
      { n: 3, r: 0, c: 4, len: 3, clue: 'Ran into' },
      { n: 4, r: 1, c: 0, len: 3, clue: 'Guitar\'s booster' },
      { n: 5, r: 1, c: 1, len: 4, clue: 'Full circle' },
    ],
  },
  {
    num: 59,
    quizId: 'emcee-9-12-26',
    live: '2026-09-12',
    dateLabel: 'September 12, 2026',
    sunday: false,
    size: 5,
    grid: ['APP##', 'PALM#', 'TRAIL', '#TILE', '##NET'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Phone download' },
      { n: 4, r: 1, c: 0, len: 4, clue: 'Beach tree' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Hiker\'s path' },
      { n: 8, r: 3, c: 1, len: 4, clue: 'Bathroom square' },
      { n: 9, r: 4, c: 2, len: 3, clue: 'Tennis divider' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Fitting' },
      { n: 2, r: 0, c: 1, len: 4, clue: 'Piece' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Simple' },
      { n: 5, r: 1, c: 3, len: 4, clue: 'Race unit' },
      { n: 7, r: 2, c: 4, len: 3, clue: 'Allow' },
    ],
  },
  {
    num: 60,
    quizId: 'emcee-9-13-26',
    live: '2026-09-13',
    dateLabel: 'September 13, 2026',
    sunday: true,
    size: 7,
    grid: ['SUB#MOO', 'ERA#ADD', 'ENTERED', '##TAB##', 'OVERLAP', 'AIR#EGO', 'KEY#SOD'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Long sandwich' },
      { n: 4, r: 0, c: 4, len: 3, clue: 'Cow\'s call' },
      { n: 7, r: 1, c: 0, len: 3, clue: 'Historic stretch of time' },
      { n: 8, r: 1, c: 4, len: 3, clue: 'Do some sums' },
      { n: 9, r: 2, c: 0, len: 7, clue: 'Went in' },
      { n: 11, r: 3, c: 2, len: 3, clue: 'Bar bill' },
      { n: 12, r: 4, c: 0, len: 7, clue: 'Partly cover' },
      { n: 16, r: 5, c: 0, len: 3, clue: 'What you breathe' },
      { n: 17, r: 5, c: 4, len: 3, clue: 'Sense of self' },
      { n: 18, r: 6, c: 0, len: 3, clue: 'Lock opener' },
      { n: 19, r: 6, c: 4, len: 3, clue: 'Lawn strip' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Look at' },
      { n: 2, r: 0, c: 1, len: 3, clue: 'Coffee dispenser' },
      { n: 3, r: 0, c: 2, len: 7, clue: 'Flashlight filler' },
      { n: 4, r: 0, c: 4, len: 7, clue: 'Shooter\'s game pieces' },
      { n: 5, r: 0, c: 5, len: 3, clue: 'Poem of praise' },
      { n: 6, r: 0, c: 6, len: 3, clue: 'Not even' },
      { n: 10, r: 2, c: 3, len: 3, clue: 'Corn unit' },
      { n: 12, r: 4, c: 0, len: 3, clue: 'Acorn tree' },
      { n: 13, r: 4, c: 1, len: 3, clue: 'Compete' },
      { n: 14, r: 4, c: 5, len: 3, clue: 'In the past' },
      { n: 15, r: 4, c: 6, len: 3, clue: 'Whale group' },
    ],
  },
  {
    num: 61,
    quizId: 'emcee-9-14-26',
    live: '2026-09-14',
    dateLabel: 'September 14, 2026',
    sunday: false,
    size: 5,
    grid: ['ART##', 'LEA##', 'LABOR', '#CLUE', '#HERD'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Museum\'s stock' },
      { n: 4, r: 1, c: 0, len: 3, clue: 'Meadow' },
      { n: 5, r: 2, c: 0, len: 5, clue: 'Hard work' },
      { n: 8, r: 3, c: 1, len: 4, clue: 'Detective\'s lead' },
      { n: 9, r: 4, c: 1, len: 4, clue: 'Cattle crowd' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Every last bit' },
      { n: 2, r: 0, c: 1, len: 5, clue: 'Stretch for' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Dining surface' },
      { n: 6, r: 2, c: 3, len: 3, clue: 'Belonging to us' },
      { n: 7, r: 2, c: 4, len: 3, clue: 'Stop sign color' },
    ],
  },
  {
    num: 62,
    quizId: 'emcee-9-15-26',
    live: '2026-09-15',
    dateLabel: 'September 15, 2026',
    sunday: false,
    size: 5,
    grid: ['##BEG', '##LEA', 'SMALL', 'HAM##', 'EYE##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Plead' },
      { n: 4, r: 1, c: 2, len: 3, clue: 'Meadow' },
      { n: 5, r: 2, c: 0, len: 5, clue: 'Little' },
      { n: 7, r: 3, c: 0, len: 3, clue: 'Deli meat' },
      { n: 8, r: 4, c: 0, len: 3, clue: 'Needle\'s hole' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Point the finger at' },
      { n: 2, r: 0, c: 3, len: 3, clue: 'Slippery swimmer' },
      { n: 3, r: 0, c: 4, len: 3, clue: 'Young woman' },
      { n: 5, r: 2, c: 0, len: 3, clue: 'That woman' },
      { n: 6, r: 2, c: 1, len: 3, clue: 'Fifth month' },
    ],
  },
  {
    num: 63,
    quizId: 'emcee-9-16-26',
    live: '2026-09-16',
    dateLabel: 'September 16, 2026',
    sunday: false,
    size: 5,
    grid: ['HOP##', 'EVEN#', 'RADAR', 'BLAME', '##LED'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Bunny\'s move' },
      { n: 4, r: 1, c: 0, len: 4, clue: 'Not odd' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Blip source' },
      { n: 8, r: 3, c: 0, len: 5, clue: 'Point the finger at' },
      { n: 9, r: 4, c: 2, len: 3, clue: 'Guided' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 4, clue: 'Basil or thyme' },
      { n: 2, r: 0, c: 1, len: 4, clue: 'Egg\'s shape' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Bike pusher' },
      { n: 5, r: 1, c: 3, len: 4, clue: 'What you\'re called' },
      { n: 7, r: 2, c: 4, len: 3, clue: 'Stop sign color' },
    ],
  },
  {
    num: 64,
    quizId: 'emcee-9-17-26',
    live: '2026-09-17',
    dateLabel: 'September 17, 2026',
    sunday: false,
    size: 5,
    grid: ['##PAY', '#TRUE', 'ARENA', 'NEST#', 'YES##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Settle the bill' },
      { n: 4, r: 1, c: 1, len: 4, clue: 'Not false' },
      { n: 5, r: 2, c: 0, len: 5, clue: 'Concert venue' },
      { n: 6, r: 3, c: 0, len: 4, clue: 'Bird\'s cradle' },
      { n: 7, r: 4, c: 0, len: 3, clue: 'Affirmative reply' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Push down' },
      { n: 2, r: 0, c: 3, len: 4, clue: 'Mom\'s sister' },
      { n: 3, r: 0, c: 4, len: 3, clue: 'Vote for' },
      { n: 4, r: 1, c: 1, len: 4, clue: 'Trunk and branches' },
      { n: 5, r: 2, c: 0, len: 3, clue: 'Some at all' },
    ],
  },
  {
    num: 65,
    quizId: 'emcee-9-18-26',
    live: '2026-09-18',
    dateLabel: 'September 18, 2026',
    sunday: false,
    size: 5,
    grid: ['##SIP', 'ALONE', 'COUNT', 'RAN##', 'END##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Small drink' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'By yourself' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Tally up' },
      { n: 7, r: 3, c: 0, len: 3, clue: 'Took off' },
      { n: 8, r: 4, c: 0, len: 3, clue: 'Finish' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Ear\'s input' },
      { n: 2, r: 0, c: 3, len: 3, clue: 'Roadside lodging' },
      { n: 3, r: 0, c: 4, len: 3, clue: 'Dog or cat' },
      { n: 4, r: 1, c: 0, len: 4, clue: 'Land measure' },
      { n: 5, r: 1, c: 1, len: 4, clue: 'Bank offer' },
    ],
  },
  {
    num: 66,
    quizId: 'emcee-9-19-26',
    live: '2026-09-19',
    dateLabel: 'September 19, 2026',
    sunday: false,
    size: 5,
    grid: ['##ALP', '##LIE', 'PRINT', 'RAKE#', 'OPEN#'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Swiss peak' },
      { n: 4, r: 1, c: 2, len: 3, clue: 'Untruth' },
      { n: 5, r: 2, c: 0, len: 5, clue: 'Send to the printer' },
      { n: 7, r: 3, c: 0, len: 4, clue: 'Leaf gatherer' },
      { n: 8, r: 4, c: 0, len: 4, clue: 'Not shut' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Two peas in a pod' },
      { n: 2, r: 0, c: 3, len: 5, clue: 'Tablecloth fabric' },
      { n: 3, r: 0, c: 4, len: 3, clue: 'Dog or cat' },
      { n: 5, r: 2, c: 0, len: 3, clue: 'Not an amateur' },
      { n: 6, r: 2, c: 1, len: 3, clue: 'Knock' },
    ],
  },
  {
    num: 67,
    quizId: 'emcee-9-20-26',
    live: '2026-09-20',
    dateLabel: 'September 20, 2026',
    sunday: true,
    size: 7,
    grid: ['MOM#SAP', 'ANY#TWO', 'RESCUED', '##TAD##', 'WHEREAS', 'OUR#NIL', 'KEY#TRY'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Mother' },
      { n: 4, r: 0, c: 4, len: 3, clue: 'Maple syrup source' },
      { n: 7, r: 1, c: 0, len: 3, clue: 'Some at all' },
      { n: 8, r: 1, c: 4, len: 3, clue: 'Pair' },
      { n: 9, r: 2, c: 0, len: 7, clue: 'Saved' },
      { n: 11, r: 3, c: 2, len: 3, clue: 'Little bit' },
      { n: 12, r: 4, c: 0, len: 7, clue: 'While on the other hand' },
      { n: 16, r: 5, c: 0, len: 3, clue: 'Belonging to us' },
      { n: 17, r: 5, c: 4, len: 3, clue: 'Zero' },
      { n: 18, r: 6, c: 0, len: 3, clue: 'Lock opener' },
      { n: 19, r: 6, c: 4, len: 3, clue: 'Give it a shot' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Spoil' },
      { n: 2, r: 0, c: 1, len: 3, clue: 'Number of noses you have' },
      { n: 3, r: 0, c: 2, len: 7, clue: 'Whodunit' },
      { n: 4, r: 0, c: 4, len: 7, clue: 'Class member' },
      { n: 5, r: 0, c: 5, len: 3, clue: 'Jaw-dropping wonder' },
      { n: 6, r: 0, c: 6, len: 3, clue: 'Whale group' },
      { n: 10, r: 2, c: 3, len: 3, clue: 'Driveway sight' },
      { n: 12, r: 4, c: 0, len: 3, clue: 'Stir-fry pan' },
      { n: 13, r: 4, c: 1, len: 3, clue: 'Shade of color' },
      { n: 14, r: 4, c: 5, len: 3, clue: 'What you breathe' },
      { n: 15, r: 4, c: 6, len: 3, clue: 'Foxlike' },
    ],
  },
  {
    num: 68,
    quizId: 'emcee-9-21-26',
    live: '2026-09-21',
    dateLabel: 'September 21, 2026',
    sunday: false,
    size: 5,
    grid: ['PEP##', 'AXE##', 'DIARY', '#TRUE', '##LEA'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Energy' },
      { n: 4, r: 1, c: 0, len: 3, clue: 'Woodcutter\'s tool' },
      { n: 5, r: 2, c: 0, len: 5, clue: 'Daily journal' },
      { n: 8, r: 3, c: 1, len: 4, clue: 'Not false' },
      { n: 9, r: 4, c: 2, len: 3, clue: 'Meadow' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Notepad' },
      { n: 2, r: 0, c: 1, len: 4, clue: 'Way out' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Oyster\'s gem' },
      { n: 6, r: 2, c: 3, len: 3, clue: 'Feel sorry about' },
      { n: 7, r: 2, c: 4, len: 3, clue: 'Vote for' },
    ],
  },
  {
    num: 69,
    quizId: 'emcee-9-22-26',
    live: '2026-09-22',
    dateLabel: 'September 22, 2026',
    sunday: false,
    size: 5,
    grid: ['##RUG', 'CLOSE', 'LABEL', 'ACID#', 'YEN##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Floor covering' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'Shut' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Jar sticker' },
      { n: 7, r: 3, c: 0, len: 4, clue: 'Lemon juice quality' },
      { n: 8, r: 4, c: 0, len: 3, clue: 'Strong craving' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Red-breasted bird' },
      { n: 2, r: 0, c: 3, len: 4, clue: 'Secondhand' },
      { n: 3, r: 0, c: 4, len: 3, clue: 'Hair goo' },
      { n: 4, r: 1, c: 0, len: 4, clue: 'Potter\'s material' },
      { n: 5, r: 1, c: 1, len: 4, clue: 'Shoe string' },
    ],
  },
  {
    num: 70,
    quizId: 'emcee-9-23-26',
    live: '2026-09-23',
    dateLabel: 'September 23, 2026',
    sunday: false,
    size: 5,
    grid: ['##SIT', '#PATH', 'FALSE', 'AGO##', 'DEN##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Take a seat' },
      { n: 4, r: 1, c: 1, len: 4, clue: 'Trail' },
      { n: 5, r: 2, c: 0, len: 5, clue: 'Not true' },
      { n: 6, r: 3, c: 0, len: 3, clue: 'In the past' },
      { n: 7, r: 4, c: 0, len: 3, clue: 'Cozy home room' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Hair spot' },
      { n: 2, r: 0, c: 3, len: 3, clue: 'Belonging to it' },
      { n: 3, r: 0, c: 4, len: 3, clue: 'Most common article' },
      { n: 4, r: 1, c: 1, len: 4, clue: 'Book leaf' },
      { n: 5, r: 2, c: 0, len: 3, clue: 'Passing craze' },
    ],
  },
  {
    num: 71,
    quizId: 'emcee-9-24-26',
    live: '2026-09-24',
    dateLabel: 'September 24, 2026',
    sunday: false,
    size: 5,
    grid: ['VET##', 'OAR##', 'TRUST', 'ENTER', '##HAY'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Animal doctor' },
      { n: 4, r: 1, c: 0, len: 3, clue: 'Rowboat paddle' },
      { n: 5, r: 2, c: 0, len: 5, clue: 'Rely on' },
      { n: 8, r: 3, c: 0, len: 5, clue: 'Go in' },
      { n: 9, r: 4, c: 2, len: 3, clue: 'Barn bale' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 4, clue: 'Ballot cast' },
      { n: 2, r: 0, c: 1, len: 4, clue: 'Work for' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'The real story' },
      { n: 6, r: 2, c: 3, len: 3, clue: 'Ocean' },
      { n: 7, r: 2, c: 4, len: 3, clue: 'Give it a shot' },
    ],
  },
  {
    num: 72,
    quizId: 'emcee-9-25-26',
    live: '2026-09-25',
    dateLabel: 'September 25, 2026',
    sunday: false,
    size: 5,
    grid: ['##LAW', '#SORE', 'TOWEL', 'IDEAL', 'CAR##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Rule on the books' },
      { n: 4, r: 1, c: 1, len: 4, clue: 'Achy' },
      { n: 5, r: 2, c: 0, len: 5, clue: 'Beach drier' },
      { n: 6, r: 3, c: 0, len: 5, clue: 'Perfect' },
      { n: 7, r: 4, c: 0, len: 3, clue: 'Driveway sight' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Bring down' },
      { n: 2, r: 0, c: 3, len: 4, clue: 'Region' },
      { n: 3, r: 0, c: 4, len: 4, clue: 'Water source' },
      { n: 4, r: 1, c: 1, len: 4, clue: 'Fizzy drink' },
      { n: 5, r: 2, c: 0, len: 3, clue: 'Nervous twitch' },
    ],
  },
  {
    num: 73,
    quizId: 'emcee-9-26-26',
    live: '2026-09-26',
    dateLabel: 'September 26, 2026',
    sunday: false,
    size: 5,
    grid: ['HAS##', 'ARENA', 'DIVER', '#SEEK', '#END#'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Owns' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'Concert venue' },
      { n: 7, r: 2, c: 0, len: 5, clue: 'Pool plunger' },
      { n: 8, r: 3, c: 1, len: 4, clue: 'Look for' },
      { n: 9, r: 4, c: 1, len: 3, clue: 'Finish' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Possessed' },
      { n: 2, r: 0, c: 1, len: 5, clue: 'Get up' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Lucky number' },
      { n: 5, r: 1, c: 3, len: 4, clue: 'Must have' },
      { n: 6, r: 1, c: 4, len: 3, clue: 'Noah\'s boat' },
    ],
  },
  {
    num: 74,
    quizId: 'emcee-9-27-26',
    live: '2026-09-27',
    dateLabel: 'September 27, 2026',
    sunday: true,
    size: 7,
    grid: ['APE#SUB', 'SIX#PRO', 'HEARING', '##MAD##', 'HAPPENS', 'ALL#RAT', 'SEE#SPY'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Chimp or gorilla' },
      { n: 4, r: 0, c: 4, len: 3, clue: 'Long sandwich' },
      { n: 7, r: 1, c: 0, len: 3, clue: 'Half a dozen' },
      { n: 8, r: 1, c: 4, len: 3, clue: 'Not an amateur' },
      { n: 9, r: 2, c: 0, len: 7, clue: 'Sense of sound' },
      { n: 11, r: 3, c: 2, len: 3, clue: 'Furious' },
      { n: 12, r: 4, c: 0, len: 7, clue: 'Occurs' },
      { n: 16, r: 5, c: 0, len: 3, clue: 'Every last bit' },
      { n: 17, r: 5, c: 4, len: 3, clue: 'Sewer rodent' },
      { n: 18, r: 6, c: 0, len: 3, clue: 'Look at' },
      { n: 19, r: 6, c: 4, len: 3, clue: 'Secret agent' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Fireplace leftover' },
      { n: 2, r: 0, c: 1, len: 3, clue: 'Slice of dessert' },
      { n: 3, r: 0, c: 2, len: 7, clue: 'For instance' },
      { n: 4, r: 0, c: 4, len: 7, clue: 'Web spinners' },
      { n: 5, r: 0, c: 5, len: 3, clue: 'Coffee dispenser' },
      { n: 6, r: 0, c: 6, len: 3, clue: 'Marshy ground' },
      { n: 10, r: 2, c: 3, len: 3, clue: 'Knock' },
      { n: 12, r: 4, c: 0, len: 3, clue: 'Owns' },
      { n: 13, r: 4, c: 1, len: 3, clue: 'Pub pint' },
      { n: 14, r: 4, c: 5, len: 3, clue: 'Short sleep' },
      { n: 15, r: 4, c: 6, len: 3, clue: 'Pig\'s pen' },
    ],
  },
  {
    num: 75,
    quizId: 'emcee-9-28-26',
    live: '2026-09-28',
    dateLabel: 'September 28, 2026',
    sunday: false,
    size: 5,
    grid: ['##TAB', 'WHILE', 'EAGLE', 'TREE#', '#DRY#'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Bar bill' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'During' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Bald bird' },
      { n: 7, r: 3, c: 0, len: 4, clue: 'Trunk and branches' },
      { n: 8, r: 4, c: 1, len: 3, clue: 'Not wet' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Striped cat' },
      { n: 2, r: 0, c: 3, len: 5, clue: 'Bowling venue' },
      { n: 3, r: 0, c: 4, len: 3, clue: 'Honey maker' },
      { n: 4, r: 1, c: 0, len: 3, clue: 'Soaked' },
      { n: 5, r: 1, c: 1, len: 4, clue: 'Tough' },
    ],
  },
  {
    num: 76,
    quizId: 'emcee-9-29-26',
    live: '2026-09-29',
    dateLabel: 'September 29, 2026',
    sunday: false,
    size: 5,
    grid: ['##IMP', '##MOO', 'PLATE', 'EIGHT', 'ATE##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Little troublemaker' },
      { n: 4, r: 1, c: 2, len: 3, clue: 'Cow\'s call' },
      { n: 5, r: 2, c: 0, len: 5, clue: 'Dinner disc' },
      { n: 7, r: 3, c: 0, len: 5, clue: 'Spider\'s leg count' },
      { n: 8, r: 4, c: 0, len: 3, clue: 'Had dinner' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Picture' },
      { n: 2, r: 0, c: 3, len: 4, clue: 'Flame circler' },
      { n: 3, r: 0, c: 4, len: 4, clue: 'Verse writer' },
      { n: 5, r: 2, c: 0, len: 3, clue: 'Pod veggie' },
      { n: 6, r: 2, c: 1, len: 3, clue: 'Illuminated' },
    ],
  },
];
