// Puzzle data for the daily game. Imported ONLY by the server page
// component, which filters to live<=today before passing puzzles to the client,
// so future boards never reach the browser bundle. app/strata/page.js also
// strips `owners` and `pool` from every day it does hand over: the client gets
// the letters and the answer list, never the map saying which cell belongs to
// which word.
//
// FIELDS
//   columns  one string per column, that column's letters BOTTOM first. Index 0
//            renders at the bottom row, because that is the end gravity packs to.
//   owners   the same shape in digits: which `words` index owns each cell. The
//            verifier's exact-cover and intended-line checks run off this; it is
//            never shipped to a player.
//   words    the answers, in the order the board was BUILT (which is one valid
//            solve order, not the only one).
//   pool     the rest of the day's category, for the decoy check.
//   opening  how many words can be read on the untouched grid.
//   deepest  how many finds the last word waits for.
//
// AUTHORING RULE (every one of these is machine-checked by
// scripts/verify-strata.mjs, and a board ships only if all of them pass):
//
//   1. EXACT COVER. Every cell belongs to exactly one answer. A spare cell could
//      never be cleared, so the board could not be finished.
//   2. NO DEAD END, ANYWHERE REACHABLE. Whatever order the player clears in, the
//      board can still be finished. This is why Strata has no fail state, needs
//      no undo, and can let a wrong trace cost nothing.
//   3. ONE PLACEMENT PER WORD PER STATE. A word never reads in two places at
//      once, so a correct-looking trace is never refused.
//   4. THE GATE IS REAL. At most three words (in practice one or two) are
//      readable on the untouched grid, and the last word waits on at least two
//      finds, four on a Sunday. Without this the collapse is decoration.
//   5. NO CRUEL DECOY. No other member of the day's category can be traced at any
//      reachable state. Seeing SLEET on a weather grid and having the board
//      refuse it is the worst thing this format can do to somebody.
//
// Boards are BUILT BACKWARDS by scripts/strata-gen.mjs (insert the last word
// into an empty grid, then the second last on top of it, and so on), because a
// grid partitioned forwards has every word contiguous at the start and therefore
// gates nothing. Weekdays are 5x5 on one thread; Sunday Editions are 6x7 and run
// two threads at once.
export const PUZZLES = [
  {
    num: 1,
    quizId: 'strata-8-6-26',
    live: '2026-08-06',
    dateLabel: 'August 6, 2026',
    rows: 5,
    cols: 5,
    themes: ['Sewing'],
    columns: ['BOBON', 'IBHTT', 'RECNT', 'SGDEA', 'SMASU'],
    owners: ['33311', '33112', '42134', '22404', '20002'],
    words: ['SEAM', 'NOTCH', 'GUSSET', 'BOBBIN', 'DART'],
    tier: undefined,
    pool: ['THIMBLE', 'BOBBIN', 'SEAM', 'HEM', 'PLEAT', 'DART', 'BASTE', 'SERGE', 'GUSSET', 'SELVAGE', 'NOTCH'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 2,
    quizId: 'strata-8-7-26',
    live: '2026-08-07',
    dateLabel: 'August 7, 2026',
    rows: 5,
    cols: 5,
    themes: ['Big cats'],
    columns: ['EAIUT', 'RIGMP', 'LGORN', 'ARAUA', 'GUOCJ'],
    owners: ['43434', '42433', '21212', '00111', '00001'],
    words: ['COUGAR', 'JAGUAR', 'LION', 'PUMA', 'TIGER'],
    tier: 2,
    minZipf: 3.22,
    pool: ['LION', 'TIGER', 'LEOPARD', 'JAGUAR', 'CHEETAH', 'COUGAR', 'PUMA', 'LYNX', 'OCELOT', 'PANTHER', 'BOBCAT'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 3,
    quizId: 'strata-8-8-26',
    live: '2026-08-08',
    dateLabel: 'August 8, 2026',
    rows: 5,
    cols: 5,
    themes: ['Chess'],
    columns: ['AODOK', 'OCRBR', 'HGAMQ', 'EUEBK', 'ENCIT'],
    owners: ['33344', '42334', '20001', '11202', '11200'],
    words: ['GAMBIT', 'QUEEN', 'CHECK', 'BOARD', 'ROOK'],
    tier: 2,
    minZipf: 3.1,
    pool: ['ROOK', 'BISHOP', 'KNIGHT', 'QUEEN', 'GAMBIT', 'FORK', 'SKEWER', 'CASTLE', 'ENDGAME', 'CHECK', 'BOARD'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 4,
    quizId: 'strata-8-9-26',
    live: '2026-08-09',
    dateLabel: 'August 9, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Kitchen tools', 'Bones'],
    columns: ['SASGETR', 'KONLDSU', 'TLKLIUL', 'LCIASSP', 'AEIAUTA', 'BVELRIT'],
    owners: ['6522445', '6224556', '2446556', '1143400', '1130000', '3110133'],
    words: ['SPATULA', 'CLEAVER', 'TONGS', 'TIBIA', 'SKILLET', 'RADIUS', 'SKULL'],
    tier: 3,
    minZipf: 2.8,
    pool: ['WHISK', 'LADLE', 'SPATULA', 'GRATER', 'PEELER', 'SIEVE', 'TONGS', 'MASHER', 'SKILLET', 'CLEAVER', 'MORTAR', 'FEMUR', 'TIBIA', 'FIBULA', 'RADIUS', 'SCAPULA', 'PATELLA', 'SACRUM', 'CARPAL', 'SKULL', 'STERNUM'],
    opening: 2,
    deepest: 5,
  },
  {
    num: 5,
    quizId: 'strata-8-10-26',
    live: '2026-08-10',
    dateLabel: 'August 10, 2026',
    rows: 5,
    cols: 5,
    themes: ['Body parts'],
    columns: ['UAEHT', 'HMRIF', 'GTBNR', 'SEIER', 'TEWNK'],
    owners: ['10001', '11022', '20122', '42434', '43433'],
    words: ['HEART', 'THUMB', 'FINGER', 'KNEE', 'WRIST'],
    tier: 1,
    minZipf: 4.01,
    pool: ['ELBOW', 'WRIST', 'ANKLE', 'THIGH', 'SHOULDER', 'FINGER', 'THUMB', 'KNEE', 'HEART', 'LIVER', 'SPLEEN', 'TEMPLE', 'STOMACH'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 6,
    quizId: 'strata-8-11-26',
    live: '2026-08-11',
    dateLabel: 'August 11, 2026',
    rows: 5,
    cols: 5,
    themes: ['Colors'],
    columns: ['EAMRC', 'TLOEN', 'VWROR', 'BELIG', 'ENBUE'],
    owners: ['23333', '22434', '24124', '41021', '11000'],
    words: ['BLUE', 'GREEN', 'VIOLET', 'CREAM', 'BROWN'],
    tier: 1,
    minZipf: 3.84,
    pool: ['BLUE', 'GREEN', 'BLACK', 'WHITE', 'BROWN', 'PINK', 'PURPLE', 'ORANGE', 'SILVER', 'GOLDEN', 'YELLOW', 'SCARLET', 'VIOLET', 'CREAM', 'CRIMSON'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 7,
    quizId: 'strata-8-12-26',
    live: '2026-08-12',
    dateLabel: 'August 12, 2026',
    rows: 5,
    cols: 5,
    themes: ['Furniture'],
    columns: ['EHBER', 'LOFNS', 'RIHKC', 'TLMRS', 'BAEDE'],
    owners: ['44113', '43414', '33101', '22330', '22200'],
    words: ['DESK', 'BENCH', 'TABLE', 'MIRROR', 'SHELF'],
    tier: 1,
    minZipf: 4.02,
    pool: ['CHAIR', 'TABLE', 'SOFA', 'DESK', 'SHELF', 'STOOL', 'BENCH', 'LAMP', 'MIRROR', 'COUCH', 'DRESSER', 'CABINET', 'CUPBOARD'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 8,
    quizId: 'strata-8-13-26',
    live: '2026-08-13',
    dateLabel: 'August 13, 2026',
    rows: 5,
    cols: 5,
    themes: ['Fabrics'],
    columns: ['TELKN', 'DIEIV', 'VMLWS', 'EOSLV', 'AONAC'],
    owners: ['21001', '11202', '21230', '23434', '43444'],
    words: ['SILK', 'DENIM', 'VELVET', 'WOOL', 'CANVAS'],
    tier: 2,
    minZipf: 3.52,
    pool: ['LINEN', 'SILK', 'DENIM', 'VELVET', 'SATIN', 'TWEED', 'COTTON', 'CANVAS', 'CHIFFON', 'FLANNEL', 'MUSLIN', 'SUEDE', 'WOOL'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 9,
    quizId: 'strata-8-14-26',
    live: '2026-08-14',
    dateLabel: 'August 14, 2026',
    rows: 5,
    cols: 5,
    themes: ['Rooms in a house'],
    columns: ['NHAGL', 'ULOEA', 'YLTTI', 'TRCOD', 'SHCPU'],
    owners: ['10011', '10112', '40222', '43234', '43334'],
    words: ['HALL', 'LOUNGE', 'ATTIC', 'PORCH', 'STUDY'],
    tier: 1,
    minZipf: 3.63,
    pool: ['KITCHEN', 'BEDROOM', 'ATTIC', 'CELLAR', 'HALL', 'PORCH', 'STUDY', 'PANTRY', 'GARAGE', 'LOUNGE', 'LANDING'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 10,
    quizId: 'strata-8-15-26',
    live: '2026-08-15',
    dateLabel: 'August 15, 2026',
    rows: 5,
    cols: 5,
    themes: ['Gemstones'],
    columns: ['PAAER', 'ORBLM', 'RAEBY', 'PNUGJ', 'TERSA'],
    owners: ['33444', '32434', '11200', '21012', '11022'],
    words: ['RUBY', 'GARNET', 'JASPER', 'OPAL', 'AMBER'],
    tier: 2,
    minZipf: 3.17,
    pool: ['RUBY', 'OPAL', 'JADE', 'TOPAZ', 'PEARL', 'AMBER', 'GARNET', 'ZIRCON', 'BERYL', 'ONYX', 'AGATE', 'JASPER', 'EMERALD'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 11,
    quizId: 'strata-8-16-26',
    live: '2026-08-16',
    dateLabel: 'August 16, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Dances', 'Sea creatures'],
    columns: ['TVOANGO', 'ESYIMAF', 'ETCNEJL', 'UROBSSS', 'OTUQOCI', 'LERDPOT'],
    owners: ['3213333', '2112000', '1100020', '6104456', '4456556', '4446555'],
    words: ['FLAMENCO', 'OYSTER', 'JIVE', 'TANGO', 'LOBSTER', 'OCTOPUS', 'SQUID'],
    tier: 2,
    minZipf: 2.93,
    pool: ['TANGO', 'SALSA', 'WALTZ', 'RUMBA', 'SAMBA', 'MAMBO', 'POLKA', 'JIVE', 'BOLERO', 'FLAMENCO', 'FOXTROT', 'OCTOPUS', 'SQUID', 'CORAL', 'URCHIN', 'MANTA', 'WHALE', 'WALRUS', 'LOBSTER', 'PRAWN', 'MUSSEL', 'OYSTER'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 12,
    quizId: 'strata-8-17-26',
    live: '2026-08-17',
    dateLabel: 'August 17, 2026',
    rows: 5,
    cols: 5,
    themes: ['Farm animals'],
    columns: ['TUDEL', 'AYURK', 'MKCBN', 'EOATI', 'GKCHC'],
    owners: ['11012', '21011', '20024', '43334', '34444'],
    words: ['DUCK', 'TURKEY', 'LAMB', 'GOAT', 'CHICKEN'],
    tier: 1,
    minZipf: 4.02,
    pool: ['HORSE', 'SHEEP', 'GOAT', 'DUCK', 'GOOSE', 'DONKEY', 'RABBIT', 'CHICKEN', 'CATTLE', 'LAMB', 'CALF', 'FOAL', 'TURKEY'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 13,
    quizId: 'strata-8-18-26',
    live: '2026-08-18',
    dateLabel: 'August 18, 2026',
    rows: 5,
    cols: 5,
    themes: ['At the beach'],
    columns: ['LLTOW', 'HEEEO', 'CESLA', 'RSOVN', 'SHEWA'],
    owners: ['33000', '33404', '42304', '21214', '22111'],
    words: ['TOWEL', 'WAVES', 'SHORE', 'SHELL', 'OCEAN'],
    tier: 1,
    minZipf: 3.94,
    pool: ['SAND', 'WAVES', 'SHELL', 'TOWEL', 'SURF', 'TIDE', 'OCEAN', 'PALM', 'CRAB', 'DUNE', 'SHORE', 'PEBBLE', 'SEAWEED'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 14,
    quizId: 'strata-8-19-26',
    live: '2026-08-19',
    dateLabel: 'August 19, 2026',
    rows: 5,
    cols: 5,
    themes: ['Shades of red'],
    columns: ['ROCRB', 'KISAR', 'ORLES', 'ELACC', 'YBURT'],
    owners: ['11333', '33144', '42412', '22224', '00002'],
    words: ['RUBY', 'ROSE', 'SCARLET', 'BRICK', 'CORAL'],
    tier: 2,
    minZipf: 3.64,
    pool: ['CRIMSON', 'SCARLET', 'RUBY', 'CORAL', 'CARMINE', 'MAROON', 'GARNET', 'BRICK', 'ROSE', 'BLUSH', 'CHERRY'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 15,
    quizId: 'strata-8-20-26',
    live: '2026-08-20',
    dateLabel: 'August 20, 2026',
    rows: 5,
    cols: 5,
    themes: ['In the kitchen'],
    columns: ['NNEEB', 'DERLV', 'POOON', 'OBKES', 'WNIFL'],
    owners: ['32232', '22223', '43444', '11004', '10001'],
    words: ['KNIFE', 'BOWL', 'BLENDER', 'OVEN', 'SPOON'],
    tier: 1,
    minZipf: 3.43,
    pool: ['KNIFE', 'SPOON', 'PLATE', 'BOWL', 'KETTLE', 'OVEN', 'FRIDGE', 'TOASTER', 'BLENDER', 'WHISK', 'SAUCER', 'TEAPOT'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 16,
    quizId: 'strata-8-21-26',
    live: '2026-08-21',
    dateLabel: 'August 21, 2026',
    rows: 5,
    cols: 5,
    themes: ['Fish'],
    columns: ['RIHAB', 'RENGS', 'USTHN', 'UTATC', 'ORPER'],
    owners: ['11122', '11112', '42304', '33440', '33000'],
    words: ['PERCH', 'HERRING', 'BASS', 'TROUT', 'TUNA'],
    tier: 2,
    minZipf: 3.29,
    pool: ['TROUT', 'SALMON', 'TUNA', 'PERCH', 'BASS', 'PIKE', 'CARP', 'MULLET', 'HERRING', 'MACKEREL', 'SARDINE', 'HALIBUT'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 17,
    quizId: 'strata-8-22-26',
    live: '2026-08-22',
    dateLabel: 'August 22, 2026',
    rows: 5,
    cols: 5,
    themes: ['Flowers'],
    columns: ['SIYSA', 'LAIER', 'AIDTA', 'ZLUCP', 'ILLAI'],
    owners: ['11003', '30031', '31042', '32424', '22434'],
    words: ['DAISY', 'IRIS', 'LILAC', 'AZALEA', 'TULIP'],
    tier: 2,
    minZipf: 3.05,
    pool: ['TULIP', 'DAHLIA', 'PEONY', 'ORCHID', 'LILAC', 'IRIS', 'ASTER', 'POPPY', 'DAISY', 'AZALEA', 'VIOLET', 'JASMINE'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 18,
    quizId: 'strata-8-23-26',
    live: '2026-08-23',
    dateLabel: 'August 23, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Bones', 'Knots'],
    columns: ['YNNAEHT', 'RETRSPF', 'EIBDGLM', 'LRNECUL', 'UIUESED', 'SERKFAR'],
    owners: ['0000111', '1110334', '4322034', '5422345', '7753567', '7665677'],
    words: ['GRANNY', 'TETHER', 'BEND', 'SPLICE', 'FEMUR', 'SKULL', 'REEF', 'RADIUS'],
    tier: 3,
    minZipf: 2.87,
    pool: ['FEMUR', 'TIBIA', 'FIBULA', 'RADIUS', 'SCAPULA', 'PATELLA', 'SACRUM', 'CARPAL', 'SKULL', 'STERNUM', 'CLOVE', 'HITCH', 'REEF', 'GRANNY', 'TIMBER', 'BEND', 'SPLICE', 'LANYARD', 'TETHER'],
    opening: 2,
    deepest: 7,
  },
  {
    num: 19,
    quizId: 'strata-8-24-26',
    live: '2026-08-24',
    dateLabel: 'August 24, 2026',
    rows: 5,
    cols: 5,
    themes: ['Body parts'],
    columns: ['EEKBT', 'MERHN', 'EETUV', 'LMIRS', 'PLWIT'],
    owners: ['33344', '42243', '11142', '11200', '12000'],
    words: ['WRIST', 'TEMPLE', 'LIVER', 'KNEE', 'THUMB'],
    tier: 1,
    minZipf: 4.01,
    pool: ['ELBOW', 'WRIST', 'ANKLE', 'THIGH', 'SHOULDER', 'FINGER', 'THUMB', 'KNEE', 'HEART', 'LIVER', 'SPLEEN', 'TEMPLE', 'STOMACH'],
    opening: 2,
    deepest: 3,
  },
  {
    num: 20,
    quizId: 'strata-8-25-26',
    live: '2026-08-25',
    dateLabel: 'August 25, 2026',
    rows: 5,
    cols: 5,
    themes: ['Ways to travel'],
    columns: ['RYGAW', 'BRNYO', 'FEUWA', 'ASTTK', 'RXIUC'],
    owners: ['00222', '10212', '00111', '31344', '43344'],
    words: ['FERRY', 'SUBWAY', 'WAGON', 'TAXI', 'TRUCK'],
    tier: 1,
    minZipf: 3.9,
    pool: ['TRUCK', 'TRAIN', 'PLANE', 'BOAT', 'BIKE', 'SHIP', 'TAXI', 'FERRY', 'WAGON', 'SCOOTER', 'TRACTOR', 'SUBWAY', 'CANOE'],
    opening: 1,
    deepest: 3,
  },
  {
    num: 21,
    quizId: 'strata-8-26-26',
    live: '2026-08-26',
    dateLabel: 'August 26, 2026',
    rows: 5,
    cols: 5,
    themes: ['Drinks'],
    columns: ['WVIEA', 'KDOON', 'CIHWA', 'BSRCO', 'EKEYE'],
    owners: ['31334', '11143', '40001', '20244', '20002'],
    words: ['WHISKEY', 'VODKA', 'BEER', 'WINE', 'COCOA'],
    tier: 1,
    minZipf: 3.64,
    pool: ['WATER', 'COFFEE', 'JUICE', 'CIDER', 'LEMONADE', 'COCOA', 'BRANDY', 'WHISKEY', 'SHERRY', 'VODKA', 'WINE', 'BEER'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 22,
    quizId: 'strata-8-27-26',
    live: '2026-08-27',
    dateLabel: 'August 27, 2026',
    rows: 5,
    cols: 5,
    themes: ['Chess'],
    columns: ['EECEN', 'CUPHQ', 'OBHOK', 'DASKF', 'RIROB'],
    owners: ['43344', '34234', '11223', '11200', '12002'],
    words: ['FORK', 'BOARD', 'BISHOP', 'CHECK', 'QUEEN'],
    tier: 2,
    minZipf: 4.03,
    pool: ['ROOK', 'BISHOP', 'KNIGHT', 'QUEEN', 'GAMBIT', 'FORK', 'SKEWER', 'CASTLE', 'ENDGAME', 'CHECK', 'BOARD'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 23,
    quizId: 'strata-8-28-26',
    live: '2026-08-28',
    dateLabel: 'August 28, 2026',
    rows: 5,
    cols: 5,
    themes: ['Golf'],
    columns: ['SICEE', 'LNIDL', 'ROGAR', 'REIWG', 'EEVDE'],
    owners: ['00002', '01132', '11223', '32344', '43344'],
    words: ['SLICE', 'IRON', 'EAGLE', 'DRIVER', 'WEDGE'],
    tier: 2,
    minZipf: 3.62,
    pool: ['BIRDIE', 'EAGLE', 'BOGEY', 'PUTT', 'DRIVER', 'WEDGE', 'FAIRWAY', 'BUNKER', 'CADDIE', 'IRON', 'SLICE'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 24,
    quizId: 'strata-8-29-26',
    live: '2026-08-29',
    dateLabel: 'August 29, 2026',
    rows: 5,
    cols: 5,
    themes: ['Theater'],
    columns: ['PSNGS', 'WSUIO', 'RHERE', 'SPOCG', 'ATRAT'],
    owners: ['22111', '10012', '20004', '42334', '43334'],
    words: ['USHER', 'WINGS', 'PROPS', 'ACTOR', 'STAGE'],
    tier: 2,
    minZipf: 3.51,
    pool: ['STAGE', 'CURTAIN', 'SCRIPT', 'ACTOR', 'WINGS', 'PROPS', 'USHER', 'BALCONY', 'ENCORE', 'MATINEE', 'CHORUS', 'PROMPT'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 25,
    quizId: 'strata-8-30-26',
    live: '2026-08-30',
    dateLabel: 'August 30, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Ancient Rome', 'Printing'],
    columns: ['GIOERPR', 'SLLOFIA', 'LRAGSMN', 'ORYCTOE', 'EOMEHIC', 'PSAIMAR'],
    owners: ['6445556', '5344466', '3233566', '2230003', '2112001', '2111200'],
    words: ['CHARIOT', 'MOSAIC', 'EMPEROR', 'GALLEY', 'FOLIO', 'PRESS', 'MARGIN'],
    tier: 3,
    minZipf: 3.11,
    pool: ['TOGA', 'FORUM', 'LEGION', 'SENATE', 'COLUMN', 'CHARIOT', 'VILLA', 'ARENA', 'MOSAIC', 'TUNIC', 'EMPEROR', 'SERIF', 'GALLEY', 'FOLIO', 'QUARTO', 'INKWELL', 'PRESS', 'TYPEFACE', 'MARGIN'],
    opening: 2,
    deepest: 6,
  },
  {
    num: 26,
    quizId: 'strata-8-31-26',
    live: '2026-08-31',
    dateLabel: 'August 31, 2026',
    rows: 5,
    cols: 5,
    themes: ['Furniture'],
    columns: ['IHCLM', 'ERNFR', 'HSOEB', 'RUOHD', 'KSECC'],
    owners: ['20012', '12012', '11200', '24443', '33344'],
    words: ['BENCH', 'SHELF', 'MIRROR', 'DESK', 'COUCH'],
    tier: 1,
    minZipf: 4.02,
    pool: ['CHAIR', 'TABLE', 'SOFA', 'DESK', 'SHELF', 'STOOL', 'BENCH', 'LAMP', 'MIRROR', 'COUCH', 'DRESSER', 'CABINET', 'CUPBOARD'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 27,
    quizId: 'strata-9-1-26',
    live: '2026-09-01',
    dateLabel: 'September 1, 2026',
    rows: 5,
    cols: 5,
    themes: ['Farm animals'],
    columns: ['GKTUO', 'BEROR', 'ABYSE', 'GITBT', 'MALAO'],
    owners: ['10001', '20012', '22011', '42234', '33344'],
    words: ['TURKEY', 'GOOSE', 'RABBIT', 'LAMB', 'GOAT'],
    tier: 1,
    minZipf: 3.84,
    pool: ['HORSE', 'SHEEP', 'GOAT', 'DUCK', 'GOOSE', 'DONKEY', 'RABBIT', 'CHICKEN', 'CATTLE', 'LAMB', 'CALF', 'FOAL', 'TURKEY'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 28,
    quizId: 'strata-9-2-26',
    live: '2026-09-02',
    dateLabel: 'September 2, 2026',
    rows: 5,
    cols: 5,
    themes: ['Shades of red'],
    columns: ['SIRCR', 'CKOBA', 'SBRYT', 'UCELE', 'ORRAL'],
    owners: ['10013', '00301', '32121', '24311', '42444'],
    words: ['BRICK', 'SCARLET', 'RUBY', 'ROSE', 'CORAL'],
    tier: 2,
    minZipf: 3.64,
    pool: ['CRIMSON', 'SCARLET', 'RUBY', 'CORAL', 'CARMINE', 'MAROON', 'GARNET', 'BRICK', 'ROSE', 'BLUSH', 'CHERRY'],
    opening: 1,
    deepest: 3,
  },
  {
    num: 29,
    quizId: 'strata-9-3-26',
    live: '2026-09-03',
    dateLabel: 'September 3, 2026',
    rows: 5,
    cols: 5,
    themes: ['At the beach'],
    columns: ['IEDFS', 'RTUER', 'CRASO', 'AMHDB', 'PSANL'],
    owners: ['43455', '34545', '22233', '11302', '10001'],
    words: ['SAND', 'PALM', 'CRAB', 'SHORE', 'TIDE', 'SURF'],
    tier: 1,
    minZipf: 3.76,
    pool: ['SAND', 'WAVES', 'SHELL', 'TOWEL', 'SURF', 'TIDE', 'OCEAN', 'PALM', 'CRAB', 'DUNE', 'SHORE', 'PEBBLE', 'SEAWEED'],
    opening: 1,
    deepest: 5,
  },
  {
    num: 30,
    quizId: 'strata-9-4-26',
    live: '2026-09-04',
    dateLabel: 'September 4, 2026',
    rows: 5,
    cols: 5,
    themes: ['Big cats'],
    columns: ['ARUJA', 'GTRGO', 'UIGEC', 'IANUA', 'ORPML'],
    owners: ['11122', '20011', '20001', '42433', '42334'],
    words: ['TIGER', 'COUGAR', 'JAGUAR', 'PUMA', 'LION'],
    tier: 2,
    minZipf: 3.22,
    pool: ['LION', 'TIGER', 'LEOPARD', 'JAGUAR', 'CHEETAH', 'COUGAR', 'PUMA', 'LYNX', 'OCELOT', 'PANTHER', 'BOBCAT'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 31,
    quizId: 'strata-9-5-26',
    live: '2026-09-05',
    dateLabel: 'September 5, 2026',
    rows: 5,
    cols: 5,
    themes: ['Fish'],
    columns: ['COTEP', 'USRHR', 'STHAB', 'CAEPR', 'RIRNG'],
    owners: ['41144', '13144', '31233', '00202', '22022'],
    words: ['CARP', 'TROUT', 'HERRING', 'BASS', 'PERCH'],
    tier: 2,
    minZipf: 3.18,
    pool: ['TROUT', 'SALMON', 'TUNA', 'PERCH', 'BASS', 'PIKE', 'CARP', 'MULLET', 'HERRING', 'MACKEREL', 'SARDINE', 'HALIBUT'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 32,
    quizId: 'strata-9-6-26',
    live: '2026-09-06',
    dateLabel: 'September 6, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Birds of prey', 'Kitchen tools'],
    columns: ['ATGNOTU', 'PASUBLA', 'MZRZRSV', 'UEDLINR', 'LUEEVSH', 'TWEIISK'],
    owners: ['3300003', '3202233', '1212234', '4121114', '4445556', '4655666'],
    words: ['TONGS', 'MERLIN', 'BUZZARD', 'SPATULA', 'VULTURE', 'SIEVE', 'WHISK'],
    tier: 3,
    minZipf: 2.8,
    pool: ['EAGLE', 'HAWK', 'FALCON', 'KESTREL', 'OSPREY', 'HARRIER', 'BUZZARD', 'CONDOR', 'VULTURE', 'MERLIN', 'WHISK', 'LADLE', 'SPATULA', 'GRATER', 'PEELER', 'SIEVE', 'TONGS', 'MASHER', 'SKILLET', 'CLEAVER', 'MORTAR'],
    opening: 2,
    deepest: 5,
  },
  {
    num: 33,
    quizId: 'strata-9-7-26',
    live: '2026-09-07',
    dateLabel: 'September 7, 2026',
    rows: 5,
    cols: 5,
    themes: ['Colors'],
    columns: ['LEYEN', 'LOREW', 'EGPIK', 'GLNUR', 'BANEO'],
    owners: ['11100', '11001', '40222', '43234', '34434'],
    words: ['GREEN', 'YELLOW', 'PINK', 'BLUE', 'ORANGE'],
    tier: 1,
    minZipf: 4.52,
    pool: ['BLUE', 'GREEN', 'BLACK', 'WHITE', 'BROWN', 'PINK', 'PURPLE', 'ORANGE', 'SILVER', 'GOLDEN', 'YELLOW', 'SCARLET', 'VIOLET', 'CREAM', 'CRIMSON'],
    opening: 1,
    deepest: 3,
  },
  {
    num: 34,
    quizId: 'strata-9-8-26',
    live: '2026-09-08',
    dateLabel: 'September 8, 2026',
    rows: 5,
    cols: 5,
    themes: ['Bathroom'],
    columns: ['UROOS', 'STABW', 'EHWPR', 'ELNSO', 'SHIAB'],
    owners: ['11200', '12012', '21404', '42334', '44333'],
    words: ['SOAP', 'BRUSH', 'TOWEL', 'BASIN', 'SHOWER'],
    tier: 1,
    minZipf: 3.94,
    pool: ['TOWEL', 'SOAP', 'MIRROR', 'SHOWER', 'BRUSH', 'RAZOR', 'SPONGE', 'TOILET', 'BASIN', 'COMB', 'SHAMPOO'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 35,
    quizId: 'strata-9-9-26',
    live: '2026-09-09',
    dateLabel: 'September 9, 2026',
    rows: 5,
    cols: 5,
    themes: ['Body parts'],
    columns: ['AETNE', 'TLMKL', 'PNSBE', 'KIEMH', 'WRUET'],
    owners: ['43344', '13344', '30123', '01022', '11202'],
    words: ['KNEE', 'WRIST', 'THUMB', 'TEMPLE', 'ANKLE'],
    tier: 1,
    minZipf: 3.97,
    pool: ['ELBOW', 'WRIST', 'ANKLE', 'THIGH', 'SHOULDER', 'FINGER', 'THUMB', 'KNEE', 'HEART', 'LIVER', 'SPLEEN', 'TEMPLE', 'STOMACH'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 36,
    quizId: 'strata-9-10-26',
    live: '2026-09-10',
    dateLabel: 'September 10, 2026',
    rows: 5,
    cols: 5,
    themes: ['Fabrics'],
    columns: ['OWVAC', 'ONLAS', 'NLSKI', 'LONNO', 'CITET'],
    owners: ['22444', '24343', '12433', '01001', '10101'],
    words: ['LINEN', 'COTTON', 'WOOL', 'SILK', 'CANVAS'],
    tier: 2,
    minZipf: 3.61,
    pool: ['LINEN', 'SILK', 'DENIM', 'VELVET', 'SATIN', 'TWEED', 'COTTON', 'CANVAS', 'CHIFFON', 'FLANNEL', 'MUSLIN', 'SUEDE', 'WOOL'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 37,
    quizId: 'strata-9-11-26',
    live: '2026-09-11',
    dateLabel: 'September 11, 2026',
    rows: 5,
    cols: 5,
    themes: ['Chess'],
    columns: ['HKEBI', 'OCSHC', 'OPBRO', 'NAKFE', 'RDEQU'],
    owners: ['10011', '10100', '31322', '43224', '33444'],
    words: ['CHECK', 'BISHOP', 'FORK', 'BOARD', 'QUEEN'],
    tier: 2,
    minZipf: 4.03,
    pool: ['ROOK', 'BISHOP', 'KNIGHT', 'QUEEN', 'GAMBIT', 'FORK', 'SKEWER', 'CASTLE', 'ENDGAME', 'CHECK', 'BOARD'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 38,
    quizId: 'strata-9-12-26',
    live: '2026-09-12',
    dateLabel: 'September 12, 2026',
    rows: 5,
    cols: 5,
    themes: ['Theater'],
    columns: ['POPSN', 'IRGTS', 'ECWOR', 'GUAHS', 'ASERT'],
    owners: ['00002', '20212', '41211', '43134', '43334'],
    words: ['PROPS', 'ACTOR', 'WINGS', 'USHER', 'STAGE'],
    tier: 2,
    minZipf: 3.51,
    pool: ['STAGE', 'CURTAIN', 'SCRIPT', 'ACTOR', 'WINGS', 'PROPS', 'USHER', 'BALCONY', 'ENCORE', 'MATINEE', 'CHORUS', 'PROMPT'],
    opening: 1,
    deepest: 3,
  },
  {
    num: 39,
    quizId: 'strata-9-13-26',
    live: '2026-09-13',
    dateLabel: 'September 13, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Sea creatures', 'Printing'],
    columns: ['WYLEOEL', 'GAHEAIL', 'FECAQLI', 'TPSOUFD', 'PSOYSLW', 'UOTCRUA'],
    owners: ['4644566', '6242456', '2226353', '2235353', '1112000', '1111000'],
    words: ['WALRUS', 'OCTOPUS', 'TYPEFACE', 'SQUID', 'WHALE', 'FOLIO', 'GALLEY'],
    tier: 3,
    minZipf: 2.85,
    pool: ['OCTOPUS', 'SQUID', 'CORAL', 'URCHIN', 'MANTA', 'WHALE', 'WALRUS', 'LOBSTER', 'PRAWN', 'MUSSEL', 'OYSTER', 'SERIF', 'GALLEY', 'FOLIO', 'QUARTO', 'INKWELL', 'PRESS', 'TYPEFACE', 'MARGIN'],
    opening: 2,
    deepest: 5,
  },
  {
    num: 40,
    quizId: 'strata-9-14-26',
    live: '2026-09-14',
    dateLabel: 'September 14, 2026',
    rows: 5,
    cols: 5,
    themes: ['Clothing'],
    columns: ['OESAJ', 'SAHKC', 'JENSE', 'OTTRS', 'CDAES'],
    owners: ['11122', '10122', '00002', '42433', '43433'],
    words: ['JEANS', 'SHOES', 'JACKET', 'DRESS', 'COAT'],
    tier: 1,
    minZipf: 4.09,
    pool: ['SHIRT', 'DRESS', 'COAT', 'SKIRT', 'JEANS', 'SOCKS', 'SCARF', 'GLOVE', 'BOOTS', 'BELT', 'JACKET', 'SWEATER', 'SHOES', 'BLOUSE'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 41,
    quizId: 'strata-9-15-26',
    live: '2026-09-15',
    dateLabel: 'September 15, 2026',
    rows: 5,
    cols: 5,
    themes: ['Weather'],
    columns: ['SRDFW', 'TOENI', 'WRANR', 'EOIEH', 'ZESRB'],
    owners: ['33232', '33422', '40004', '14014', '11411'],
    words: ['RAIN', 'BREEZE', 'WIND', 'FROST', 'SHOWER'],
    tier: 1,
    minZipf: 3.86,
    pool: ['RAIN', 'SNOW', 'HAIL', 'STORM', 'FROST', 'WIND', 'CLOUD', 'THUNDER', 'BREEZE', 'DRIZZLE', 'GALE', 'THAW', 'MIST', 'SLEET', 'SHOWER', 'SUNSHINE'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 42,
    quizId: 'strata-9-16-26',
    live: '2026-09-16',
    dateLabel: 'September 16, 2026',
    rows: 5,
    cols: 5,
    themes: ['Furniture'],
    columns: ['MESAL', 'DRPKA', 'ROFRS', 'IBCON', 'AMIET'],
    owners: ['10011', '03102', '33232', '34424', '43444'],
    words: ['DESK', 'LAMP', 'SOFA', 'MIRROR', 'CABINET'],
    tier: 1,
    minZipf: 3.81,
    pool: ['CHAIR', 'TABLE', 'SOFA', 'DESK', 'SHELF', 'STOOL', 'BENCH', 'LAMP', 'MIRROR', 'COUCH', 'DRESSER', 'CABINET', 'CUPBOARD'],
    opening: 1,
    deepest: 3,
  },
  {
    num: 43,
    quizId: 'strata-9-17-26',
    live: '2026-09-17',
    dateLabel: 'September 17, 2026',
    rows: 5,
    cols: 5,
    themes: ['In the garden'],
    columns: ['NLCOF', 'EEEIS', 'KRSBT', 'UAGSC', 'HEDGE'],
    owners: ['43434', '41433', '10011', '10001', '22222'],
    words: ['GRASS', 'BUCKET', 'HEDGE', 'SOIL', 'FENCE'],
    tier: 1,
    minZipf: 3.74,
    pool: ['FLOWER', 'GRASS', 'FENCE', 'SHOVEL', 'BUCKET', 'HEDGE', 'WEEDS', 'SOIL', 'SEEDS', 'SPADE', 'BLOSSOM', 'COMPOST'],
    opening: 2,
    deepest: 3,
  },
  {
    num: 44,
    quizId: 'strata-9-18-26',
    live: '2026-09-18',
    dateLabel: 'September 18, 2026',
    rows: 5,
    cols: 5,
    themes: ['Golf'],
    columns: ['ACILE', 'GLIEE', 'NWORS', 'EEBKR', 'GDNUE'],
    owners: ['43344', '43234', '21223', '11000', '11000'],
    words: ['BUNKER', 'WEDGE', 'IRON', 'SLICE', 'EAGLE'],
    tier: 2,
    minZipf: 3.62,
    pool: ['BIRDIE', 'EAGLE', 'BOGEY', 'PUTT', 'DRIVER', 'WEDGE', 'FAIRWAY', 'BUNKER', 'CADDIE', 'IRON', 'SLICE'],
    opening: 2,
    deepest: 3,
  },
  {
    num: 45,
    quizId: 'strata-9-19-26',
    live: '2026-09-19',
    dateLabel: 'September 19, 2026',
    rows: 5,
    cols: 5,
    themes: ['Boats'],
    columns: ['HAYRY', 'CKTRE', 'AFBAE', 'YERKO', 'ACANG'],
    owners: ['33344', '32344', '24110', '21120', '20001'],
    words: ['CANOE', 'BARGE', 'KAYAK', 'YACHT', 'FERRY'],
    tier: 2,
    minZipf: 3.24,
    pool: ['KAYAK', 'CANOE', 'FERRY', 'YACHT', 'SKIFF', 'BARGE', 'SLOOP', 'TRAWLER', 'DINGHY', 'CUTTER', 'GALLEY'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 46,
    quizId: 'strata-9-20-26',
    live: '2026-09-20',
    dateLabel: 'September 20, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Sewing', 'Birds of prey'],
    columns: ['HDNEEAD', 'ZFAERRT', 'AZLUDBE', 'RCOELNM', 'VATIRUS', 'ULAOLET'],
    owners: ['6300666', '3110366', '3313035', '5110014', '5422254', '5522245'],
    words: ['NEEDLE', 'FALCON', 'TAILOR', 'BUZZARD', 'SEAM', 'VULTURE', 'THREAD'],
    tier: 3,
    minZipf: 2.83,
    pool: ['THIMBLE', 'BOBBIN', 'SEAM', 'PLEAT', 'BASTE', 'GUSSET', 'NOTCH', 'STITCH', 'NEEDLE', 'THREAD', 'HEMLINE', 'TAILOR', 'EAGLE', 'HAWK', 'FALCON', 'KESTREL', 'OSPREY', 'HARRIER', 'BUZZARD', 'CONDOR', 'VULTURE', 'MERLIN'],
    opening: 2,
    deepest: 5,
  },
  {
    num: 47,
    quizId: 'strata-9-21-26',
    live: '2026-09-21',
    dateLabel: 'September 21, 2026',
    rows: 5,
    cols: 5,
    themes: ['Ways to travel'],
    columns: ['KCURA', 'LRNET', 'SREYP', 'BUIXF', 'WTAAY'],
    owners: ['11114', '43441', '23334', '22003', '20022'],
    words: ['TAXI', 'TRUCK', 'SUBWAY', 'FERRY', 'PLANE'],
    tier: 1,
    minZipf: 4.02,
    pool: ['TRUCK', 'TRAIN', 'PLANE', 'BOAT', 'BIKE', 'SHIP', 'TAXI', 'FERRY', 'WAGON', 'SCOOTER', 'TRACTOR', 'SUBWAY', 'CANOE'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 48,
    quizId: 'strata-9-22-26',
    live: '2026-09-22',
    dateLabel: 'September 22, 2026',
    rows: 5,
    cols: 5,
    themes: ['At the beach'],
    columns: ['OVWSL', 'ATSEE', 'WNAHE', 'SCHOL', 'OELER'],
    owners: ['21212', '12012', '13303', '43404', '34400'],
    words: ['SHORE', 'WAVES', 'TOWEL', 'OCEAN', 'SHELL'],
    tier: 1,
    minZipf: 3.94,
    pool: ['SAND', 'WAVES', 'SHELL', 'TOWEL', 'SURF', 'TIDE', 'OCEAN', 'PALM', 'CRAB', 'DUNE', 'SHORE', 'PEBBLE', 'SEAWEED'],
    opening: 1,
    deepest: 3,
  },
  {
    num: 49,
    quizId: 'strata-9-23-26',
    live: '2026-09-23',
    dateLabel: 'September 23, 2026',
    rows: 5,
    cols: 5,
    themes: ['Bathroom'],
    columns: ['THOSS', 'BOWAU', 'RPLBE', 'ITEAT', 'NISOL'],
    owners: ['24334', '42234', '43202', '11101', '00011'],
    words: ['BASIN', 'TOILET', 'TOWEL', 'SOAP', 'BRUSH'],
    tier: 1,
    minZipf: 3.94,
    pool: ['TOWEL', 'SOAP', 'MIRROR', 'SHOWER', 'BRUSH', 'RAZOR', 'SPONGE', 'TOILET', 'BASIN', 'COMB', 'SHAMPOO'],
    opening: 1,
    deepest: 3,
  },
  {
    num: 50,
    quizId: 'strata-9-24-26',
    live: '2026-09-24',
    dateLabel: 'September 24, 2026',
    rows: 5,
    cols: 5,
    themes: ['Fabrics'],
    columns: ['IOOWM', 'NLELS', 'IKDLE', 'VAVCV', 'TSANE'],
    owners: ['10001', '10122', '22144', '43334', '43334'],
    words: ['WOOL', 'DENIM', 'SILK', 'CANVAS', 'VELVET'],
    tier: 2,
    minZipf: 3.52,
    pool: ['LINEN', 'SILK', 'DENIM', 'VELVET', 'SATIN', 'TWEED', 'COTTON', 'CANVAS', 'CHIFFON', 'FLANNEL', 'MUSLIN', 'SUEDE', 'WOOL'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 51,
    quizId: 'strata-9-25-26',
    live: '2026-09-25',
    dateLabel: 'September 25, 2026',
    rows: 5,
    cols: 5,
    themes: ['Fish'],
    columns: ['UNIRH', 'TRANE', 'SMNGA', 'ELOBS', 'SKIPA'],
    owners: ['00333', '03033', '42234', '12244', '21112'],
    words: ['TUNA', 'PIKE', 'SALMON', 'HERRING', 'BASS'],
    tier: 2,
    minZipf: 3.48,
    pool: ['TROUT', 'SALMON', 'TUNA', 'PERCH', 'BASS', 'PIKE', 'CARP', 'MULLET', 'HERRING', 'MACKEREL', 'SARDINE', 'HALIBUT'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 52,
    quizId: 'strata-9-26-26',
    live: '2026-09-26',
    dateLabel: 'September 26, 2026',
    rows: 5,
    cols: 5,
    themes: ['Big cats'],
    columns: ['AELNR', 'PNYHX', 'ROTIJ', 'ALANA', 'PUMGU'],
    owners: ['11001', '11010', '43134', '43234', '22244'],
    words: ['LYNX', 'PANTHER', 'PUMA', 'LION', 'JAGUAR'],
    tier: 2,
    minZipf: 3.06,
    pool: ['LION', 'TIGER', 'LEOPARD', 'JAGUAR', 'CHEETAH', 'COUGAR', 'PUMA', 'LYNX', 'OCELOT', 'PANTHER', 'BOBCAT'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 53,
    quizId: 'strata-9-27-26',
    live: '2026-09-27',
    dateLabel: 'September 27, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Printing', 'Dog breeds'],
    columns: ['CFUEPYT', 'EAARSNH', 'PKAMEGI', 'YBLGOOL', 'LOLDRIC', 'LEYXEOE'],
    owners: ['6626666', '6611212', '4201411', '2300444', '5304355', '5003355'],
    words: ['GALLEY', 'MARGIN', 'HUSKY', 'BOXER', 'POODLE', 'COLLIE', 'TYPEFACE'],
    tier: 3,
    minZipf: 2.85,
    pool: ['SERIF', 'KERNING', 'GALLEY', 'PLATEN', 'QUOIN', 'FOLIO', 'QUARTO', 'INKWELL', 'PRESS', 'TYPEFACE', 'MARGIN', 'BEAGLE', 'BOXER', 'COLLIE', 'POODLE', 'TERRIER', 'SPANIEL', 'HUSKY', 'SETTER', 'MASTIFF', 'WHIPPET'],
    opening: 1,
    deepest: 5,
  },
  {
    num: 54,
    quizId: 'strata-9-28-26',
    live: '2026-09-28',
    dateLabel: 'September 28, 2026',
    rows: 5,
    cols: 5,
    themes: ['Farm animals'],
    columns: ['RBARU', 'KTBIY', 'TETPO', 'EASGM', 'LAEBH'],
    owners: ['10001', '11001', '21042', '42423', '33434'],
    words: ['RABBIT', 'TURKEY', 'GOAT', 'LAMB', 'SHEEP'],
    tier: 1,
    minZipf: 4.02,
    pool: ['HORSE', 'SHEEP', 'GOAT', 'DUCK', 'GOOSE', 'DONKEY', 'RABBIT', 'CHICKEN', 'CATTLE', 'LAMB', 'CALF', 'FOAL', 'TURKEY'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 55,
    quizId: 'strata-9-29-26',
    live: '2026-09-29',
    dateLabel: 'September 29, 2026',
    rows: 5,
    cols: 5,
    themes: ['Clothing'],
    columns: ['ACKET', 'SOKCJ', 'OOSBB', 'TELNJ', 'ATESS'],
    owners: ['10111', '00011', '44024', '42233', '32334'],
    words: ['SOCKS', 'JACKET', 'BELT', 'JEANS', 'BOOTS'],
    tier: 1,
    minZipf: 4.03,
    pool: ['SHIRT', 'DRESS', 'COAT', 'SKIRT', 'JEANS', 'SOCKS', 'SCARF', 'GLOVE', 'BOOTS', 'BELT', 'JACKET', 'SWEATER', 'SHOES', 'BLOUSE'],
    opening: 1,
    deepest: 3,
  },
  {
    num: 56,
    quizId: 'strata-9-30-26',
    live: '2026-09-30',
    dateLabel: 'September 30, 2026',
    rows: 5,
    cols: 5,
    themes: ['Shades of red'],
    columns: ['ORSRC', 'OANIM', 'RELSY', 'OBRIK', 'CUCRB'],
    owners: ['21222', '10222', '01013', '03344', '03444'],
    words: ['CORAL', 'ROSE', 'CRIMSON', 'RUBY', 'BRICK'],
    tier: 2,
    minZipf: 3.6,
    pool: ['CRIMSON', 'SCARLET', 'RUBY', 'CORAL', 'CARMINE', 'MAROON', 'GARNET', 'BRICK', 'ROSE', 'BLUSH', 'CHERRY'],
    opening: 1,
    deepest: 3,
  },
  {
    num: 57,
    quizId: 'strata-10-1-26',
    live: '2026-10-01',
    dateLabel: 'October 1, 2026',
    rows: 5,
    cols: 5,
    themes: ['Instruments'],
    columns: ['FAORE', 'LNIHP', 'DEAND', 'RATIF', 'GOPUL'],
    owners: ['43234', '42433', '40214', '11020', '11200'],
    words: ['FLUTE', 'ORGAN', 'PIANO', 'HARP', 'FIDDLE'],
    tier: 1,
    minZipf: 3.4,
    pool: ['PIANO', 'GUITAR', 'DRUMS', 'VIOLIN', 'FLUTE', 'TRUMPET', 'CELLO', 'HARP', 'BANJO', 'ORGAN', 'FIDDLE', 'OBOE'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 58,
    quizId: 'strata-10-2-26',
    live: '2026-10-02',
    dateLabel: 'October 2, 2026',
    rows: 5,
    cols: 5,
    themes: ['Gemstones'],
    columns: ['AAJEP', 'RLORD', 'UMDBE', 'EELPY', 'RJASA'],
    owners: ['43334', '24403', '21120', '11102', '10001'],
    words: ['JASPER', 'EMERALD', 'RUBY', 'JADE', 'OPAL'],
    tier: 2,
    minZipf: 3.2,
    pool: ['RUBY', 'OPAL', 'JADE', 'TOPAZ', 'PEARL', 'AMBER', 'GARNET', 'ZIRCON', 'BERYL', 'ONYX', 'AGATE', 'JASPER', 'EMERALD'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 59,
    quizId: 'strata-10-3-26',
    live: '2026-10-03',
    dateLabel: 'October 3, 2026',
    rows: 5,
    cols: 5,
    themes: ['Boats'],
    columns: ['BACAY', 'ERHEK', 'GATON', 'KAYRY', 'RCAEF'],
    owners: ['11000', '11023', '13022', '32344', '42344'],
    words: ['YACHT', 'BARGE', 'CANOE', 'KAYAK', 'FERRY'],
    tier: 2,
    minZipf: 3.24,
    pool: ['KAYAK', 'CANOE', 'FERRY', 'YACHT', 'SKIFF', 'BARGE', 'SLOOP', 'TRAWLER', 'DINGHY', 'CUTTER', 'GALLEY'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 60,
    quizId: 'strata-10-4-26',
    live: '2026-10-04',
    dateLabel: 'October 4, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Knots', 'Herbs and spices'],
    columns: ['FFRSPEY', 'RSCALVA', 'YOENOLE', 'NNTELMY', 'APTSIGH', 'REHTECR'],
    owners: ['6644444', '6654456', '2636555', '2200133', '2101123', '0003112'],
    words: ['TETHER', 'SPLICE', 'GRANNY', 'THYME', 'PARSLEY', 'CLOVE', 'SAFFRON'],
    tier: 3,
    minZipf: 2.87,
    pool: ['BOWLINE', 'CLOVE', 'HITCH', 'REEF', 'GRANNY', 'TIMBER', 'PRUSIK', 'BEND', 'SPLICE', 'LANYARD', 'TETHER', 'BASIL', 'THYME', 'SAGE', 'CUMIN', 'ANISE', 'CLOVE', 'NUTMEG', 'PAPRIKA', 'OREGANO', 'PARSLEY', 'GINGER', 'SAFFRON', 'MINT'],
    opening: 2,
    deepest: 6,
  },
  {
    num: 61,
    quizId: 'strata-10-5-26',
    live: '2026-10-05',
    dateLabel: 'October 5, 2026',
    rows: 5,
    cols: 5,
    themes: ['Weather'],
    columns: ['INEWD', 'NSHDI', 'NUNSO', 'OCUSL', 'RAINW'],
    owners: ['22244', '41234', '13223', '13223', '00001'],
    words: ['RAIN', 'SNOW', 'SUNSHINE', 'CLOUD', 'WIND'],
    tier: 1,
    minZipf: 4.16,
    pool: ['RAIN', 'SNOW', 'HAIL', 'STORM', 'FROST', 'WIND', 'CLOUD', 'THUNDER', 'BREEZE', 'DRIZZLE', 'GALE', 'THAW', 'MIST', 'SLEET', 'SHOWER', 'SUNSHINE'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 62,
    quizId: 'strata-10-6-26',
    live: '2026-10-06',
    dateLabel: 'October 6, 2026',
    rows: 5,
    cols: 5,
    themes: ['Ways to travel'],
    columns: ['SHAIP', 'BUKWY', 'PRCSU', 'RALET', 'TINAN'],
    owners: ['44344', '31133', '21133', '00221', '00022'],
    words: ['TRAIN', 'TRUCK', 'PLANE', 'SUBWAY', 'SHIP'],
    tier: 1,
    minZipf: 4.05,
    pool: ['TRUCK', 'TRAIN', 'PLANE', 'BOAT', 'BIKE', 'SHIP', 'TAXI', 'FERRY', 'WAGON', 'SCOOTER', 'TRACTOR', 'SUBWAY', 'CANOE'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 63,
    quizId: 'strata-10-7-26',
    live: '2026-10-07',
    dateLabel: 'October 7, 2026',
    rows: 5,
    cols: 5,
    themes: ['Fruit'],
    columns: ['LEMON', 'GRACH', 'RPLRE', 'YEIPE', 'MPLAE'],
    owners: ['00000', '11144', '41344', '41322', '32223'],
    words: ['LEMON', 'GRAPE', 'APPLE', 'LIME', 'CHERRY'],
    tier: 1,
    minZipf: 3.7,
    pool: ['APPLE', 'ORANGE', 'BANANA', 'GRAPE', 'PEACH', 'PLUM', 'LEMON', 'CHERRY', 'MELON', 'BERRY', 'MANGO', 'PEAR', 'LIME', 'APRICOT'],
    opening: 2,
    deepest: 3,
  },
  {
    num: 64,
    quizId: 'strata-10-8-26',
    live: '2026-10-08',
    dateLabel: 'October 8, 2026',
    rows: 5,
    cols: 5,
    themes: ['School'],
    columns: ['OLKHN', 'SREAC', 'EUCSL', 'SALLR', 'DESKS'],
    owners: ['43334', '42433', '22144', '11122', '00001'],
    words: ['DESK', 'CLASS', 'RULER', 'CHALK', 'LESSON'],
    tier: 1,
    minZipf: 3.69,
    pool: ['PENCIL', 'LESSON', 'CLASS', 'DESK', 'CHALK', 'RULER', 'HOMEWORK', 'LIBRARY', 'STUDENT', 'TEACHER', 'RECESS', 'ERASER'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 65,
    quizId: 'strata-10-9-26',
    live: '2026-10-09',
    dateLabel: 'October 9, 2026',
    rows: 5,
    cols: 5,
    themes: ['Birds'],
    columns: ['WORCN', 'CEVIN', 'BAROL', 'ONOEA', 'FGSOR'],
    owners: ['00002', '42233', '32244', '34114', '41113'],
    words: ['CROW', 'GOOSE', 'RAVEN', 'ROBIN', 'FALCON'],
    tier: 1,
    minZipf: 3.74,
    pool: ['ROBIN', 'EAGLE', 'SPARROW', 'PIGEON', 'FALCON', 'RAVEN', 'CROW', 'SWAN', 'GOOSE', 'PARROT', 'PENGUIN', 'HERON'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 66,
    quizId: 'strata-10-10-26',
    live: '2026-10-10',
    dateLabel: 'October 10, 2026',
    rows: 5,
    cols: 5,
    themes: ['Flowers'],
    columns: ['LDSYI', 'VAIPL', 'PCAOI', 'OPYIT', 'LRISE'],
    owners: ['10001', '40021', '21124', '42234', '43334'],
    words: ['DAISY', 'LILAC', 'POPPY', 'IRIS', 'VIOLET'],
    tier: 2,
    minZipf: 3.11,
    pool: ['TULIP', 'DAHLIA', 'PEONY', 'ORCHID', 'LILAC', 'IRIS', 'ASTER', 'POPPY', 'DAISY', 'AZALEA', 'VIOLET', 'JASMINE'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 67,
    quizId: 'strata-10-11-26',
    live: '2026-10-11',
    dateLabel: 'October 11, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Sewing', 'Rooms in a house'],
    columns: ['POCHTLO', 'DAHIARR', 'CEHPATY', 'TDRNTRL', 'EEIORBE', 'ENTMODS'],
    owners: ['5555666', '1146656', '4110010', '4310003', '3342222', '3342224'],
    words: ['PANTRY', 'THREAD', 'BEDROOM', 'NEEDLE', 'STITCH', 'PORCH', 'TAILOR'],
    tier: 3,
    minZipf: 3.23,
    pool: ['THIMBLE', 'BOBBIN', 'SEAM', 'PLEAT', 'BASTE', 'GUSSET', 'NOTCH', 'STITCH', 'NEEDLE', 'THREAD', 'HEMLINE', 'TAILOR', 'KITCHEN', 'BEDROOM', 'ATTIC', 'CELLAR', 'HALL', 'PORCH', 'STUDY', 'PANTRY', 'GARAGE', 'LOUNGE', 'LANDING'],
    opening: 2,
    deepest: 6,
  },
  {
    num: 68,
    quizId: 'strata-10-12-26',
    live: '2026-10-12',
    dateLabel: 'October 12, 2026',
    rows: 5,
    cols: 5,
    themes: ['Colors'],
    columns: ['LRANG', 'LEOWE', 'EPMYO', 'RKIAU', 'BLNCE'],
    owners: ['43333', '44343', '20244', '20021', '11021'],
    words: ['PINK', 'BLUE', 'CREAM', 'ORANGE', 'YELLOW'],
    tier: 1,
    minZipf: 4.52,
    pool: ['BLUE', 'GREEN', 'BLACK', 'WHITE', 'BROWN', 'PINK', 'PURPLE', 'ORANGE', 'SILVER', 'GOLDEN', 'YELLOW', 'SCARLET', 'VIOLET', 'CREAM', 'CRIMSON'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 69,
    quizId: 'strata-10-13-26',
    live: '2026-10-13',
    dateLabel: 'October 13, 2026',
    rows: 5,
    cols: 5,
    themes: ['Bathroom'],
    columns: ['WIELO', 'OMRRR', 'STHPN', 'BAIUB', 'RAOSS'],
    owners: ['10110', '10000', '41423', '32344', '43223'],
    words: ['MIRROR', 'TOWEL', 'SOAP', 'BASIN', 'BRUSH'],
    tier: 1,
    minZipf: 3.94,
    pool: ['TOWEL', 'SOAP', 'MIRROR', 'SHOWER', 'BRUSH', 'RAZOR', 'SPONGE', 'TOILET', 'BASIN', 'COMB', 'SHAMPOO'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 70,
    quizId: 'strata-10-14-26',
    live: '2026-10-14',
    dateLabel: 'October 14, 2026',
    rows: 5,
    cols: 5,
    themes: ['Drinks'],
    columns: ['IWOBE', 'ECNEA', 'YCWOR', 'EWIEA', 'KSHTR'],
    owners: ['44300', '43403', '13230', '11122', '11122'],
    words: ['BEER', 'WHISKEY', 'WATER', 'COCOA', 'WINE'],
    tier: 1,
    minZipf: 3.64,
    pool: ['WATER', 'COFFEE', 'JUICE', 'CIDER', 'LEMONADE', 'COCOA', 'BRANDY', 'WHISKEY', 'SHERRY', 'VODKA', 'WINE', 'BEER'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 71,
    quizId: 'strata-10-15-26',
    live: '2026-10-15',
    dateLabel: 'October 15, 2026',
    rows: 5,
    cols: 5,
    themes: ['In the garden'],
    columns: ['SECNL', 'OIFLE', 'ESOVE', 'HEDAS', 'SGSRS'],
    owners: ['43334', '44313', '00111', '10022', '12022'],
    words: ['SEEDS', 'SHOVEL', 'GRASS', 'FENCE', 'SOIL'],
    tier: 1,
    minZipf: 3.5,
    pool: ['FLOWER', 'GRASS', 'FENCE', 'SHOVEL', 'BUCKET', 'HEDGE', 'WEEDS', 'SOIL', 'SEEDS', 'SPADE', 'BLOSSOM', 'COMPOST'],
    opening: 1,
    deepest: 3,
  },
  {
    num: 72,
    quizId: 'strata-10-16-26',
    live: '2026-10-16',
    dateLabel: 'October 16, 2026',
    rows: 5,
    cols: 5,
    themes: ['Theater'],
    columns: ['SHEPR', 'SPUOS', 'GTARS', 'EGWNR', 'ACTOI'],
    owners: ['33323', '12322', '41124', '11440', '00004'],
    words: ['ACTOR', 'STAGE', 'PROPS', 'USHER', 'WINGS'],
    tier: 2,
    minZipf: 3.51,
    pool: ['STAGE', 'CURTAIN', 'SCRIPT', 'ACTOR', 'WINGS', 'PROPS', 'USHER', 'BALCONY', 'ENCORE', 'MATINEE', 'CHORUS', 'PROMPT'],
    opening: 2,
    deepest: 3,
  },
  {
    num: 73,
    quizId: 'strata-10-17-26',
    live: '2026-10-17',
    dateLabel: 'October 17, 2026',
    rows: 5,
    cols: 5,
    themes: ['Gemstones'],
    columns: ['EURDO', 'BJAAP', 'LYERE', 'AJSRM', 'LAEPD'],
    owners: ['10012', '01122', '20444', '43334', '43334'],
    words: ['RUBY', 'JADE', 'OPAL', 'JASPER', 'EMERALD'],
    tier: 2,
    minZipf: 3.2,
    pool: ['RUBY', 'OPAL', 'JADE', 'TOPAZ', 'PEARL', 'AMBER', 'GARNET', 'ZIRCON', 'BERYL', 'ONYX', 'AGATE', 'JASPER', 'EMERALD'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 74,
    quizId: 'strata-10-18-26',
    live: '2026-10-18',
    dateLabel: 'October 18, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Knots', 'Sea creatures'],
    columns: ['HCTIHDB', 'LNEORWD', 'VCSIAPN', 'UNRTAEQ', 'AOMYAEG', 'LBSNNRT'],
    owners: ['0000033', '5335776', '5566777', '6424456', '4241121', '2221112'],
    words: ['HITCH', 'GRANNY', 'LOBSTER', 'BEND', 'MANTA', 'CLOVE', 'SQUID', 'PRAWN'],
    tier: 3,
    minZipf: 2.82,
    pool: ['BOWLINE', 'CLOVE', 'HITCH', 'REEF', 'GRANNY', 'TIMBER', 'PRUSIK', 'BEND', 'SPLICE', 'LANYARD', 'TETHER', 'OCTOPUS', 'SQUID', 'CORAL', 'URCHIN', 'MANTA', 'WHALE', 'WALRUS', 'LOBSTER', 'PRAWN', 'MUSSEL', 'OYSTER'],
    opening: 3,
    deepest: 6,
  },
  {
    num: 75,
    quizId: 'strata-10-19-26',
    live: '2026-10-19',
    dateLabel: 'October 19, 2026',
    rows: 5,
    cols: 5,
    themes: ['Weather'],
    columns: ['DRDNU', 'UOEHC', 'ILNMT', 'OANRS', 'RWSOT'],
    owners: ['10000', '11001', '21240', '32344', '23344'],
    words: ['THUNDER', 'CLOUD', 'RAIN', 'SNOW', 'STORM'],
    tier: 1,
    minZipf: 4.14,
    pool: ['RAIN', 'SNOW', 'HAIL', 'STORM', 'FROST', 'WIND', 'CLOUD', 'THUNDER', 'BREEZE', 'DRIZZLE', 'GALE', 'THAW', 'MIST', 'SLEET', 'SHOWER', 'SUNSHINE'],
    opening: 2,
    deepest: 3,
  },
  {
    num: 76,
    quizId: 'strata-10-20-26',
    live: '2026-10-20',
    dateLabel: 'October 20, 2026',
    rows: 5,
    cols: 5,
    themes: ['Clothing'],
    columns: ['JEANS', 'ELTHO', 'BSSTE', 'SOJKE', 'COBAT'],
    owners: ['44444', '00022', '02112', '21333', '31133'],
    words: ['BELT', 'BOOTS', 'SHOES', 'JACKET', 'JEANS'],
    tier: 1,
    minZipf: 4.09,
    pool: ['SHIRT', 'DRESS', 'COAT', 'SKIRT', 'JEANS', 'SOCKS', 'SCARF', 'GLOVE', 'BOOTS', 'BELT', 'JACKET', 'SWEATER', 'SHOES', 'BLOUSE'],
    opening: 2,
    deepest: 3,
  },
  {
    num: 77,
    quizId: 'strata-10-21-26',
    live: '2026-10-21',
    dateLabel: 'October 21, 2026',
    rows: 5,
    cols: 5,
    themes: ['Metals'],
    columns: ['YOLLA', 'ZLIRB', 'NCETO', 'NSESR', 'SAZBE'],
    owners: ['00000', '21244', '22114', '43113', '33434'],
    words: ['ALLOY', 'STEEL', 'ZINC', 'BRASS', 'BRONZE'],
    tier: 2,
    minZipf: 3.61,
    pool: ['IRON', 'STEEL', 'COPPER', 'SILVER', 'BRASS', 'BRONZE', 'NICKEL', 'LEAD', 'ZINC', 'PEWTER', 'COBALT', 'ALLOY'],
    opening: 2,
    deepest: 3,
  },
  {
    num: 78,
    quizId: 'strata-10-22-26',
    live: '2026-10-22',
    dateLabel: 'October 22, 2026',
    rows: 5,
    cols: 5,
    themes: ['Landscape'],
    columns: ['IHAEL', 'LNGIP', 'DLITR', 'OMPUI', 'LSMES'],
    owners: ['00434', '04344', '30113', '21213', '22121'],
    words: ['HILL', 'SUMMIT', 'SLOPE', 'RIDGE', 'PLAIN'],
    tier: 2,
    minZipf: 3.9,
    pool: ['HILL', 'CLIFF', 'VALLEY', 'RIDGE', 'CANYON', 'PLAIN', 'DUNE', 'MESA', 'PLATEAU', 'SUMMIT', 'SLOPE', 'MEADOW'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 79,
    quizId: 'strata-10-23-26',
    live: '2026-10-23',
    dateLabel: 'October 23, 2026',
    rows: 5,
    cols: 5,
    themes: ['Fasteners'],
    columns: ['CEULE', 'APLBK', 'LCTBS', 'PLNAO', 'IAMLT'],
    owners: ['43444', '33344', '22303', '21120', '11200'],
    words: ['BOLT', 'NAIL', 'CLAMP', 'STAPLE', 'BUCKLE'],
    tier: 2,
    minZipf: 3.45,
    pool: ['NAIL', 'SCREW', 'BOLT', 'RIVET', 'STAPLE', 'CLAMP', 'HINGE', 'BUCKLE', 'ZIPPER', 'LATCH'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 80,
    quizId: 'strata-10-24-26',
    live: '2026-10-24',
    dateLabel: 'October 24, 2026',
    rows: 5,
    cols: 5,
    themes: ['Bread'],
    columns: ['GDUSB', 'EROTA', 'MUCLN', 'GHIUO', 'LLRFF'],
    owners: ['20112', '21012', '40124', '00443', '33344'],
    words: ['DOUGH', 'CRUST', 'BAGEL', 'ROLL', 'MUFFIN'],
    tier: 2,
    minZipf: 3.18,
    pool: ['LOAF', 'ROLL', 'BAGEL', 'TOAST', 'CRUST', 'SCONE', 'MUFFIN', 'BRIOCHE', 'PITA', 'DOUGH'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 81,
    quizId: 'strata-10-25-26',
    live: '2026-10-25',
    dateLabel: 'October 25, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Kitchen tools', 'Sports'],
    columns: ['TOISSHM', 'AKRLQAL', 'OFRSTEU', 'SISKKLG', 'HWLISAN', 'LABEBIG'],
    owners: ['6654446', '6565445', '3365554', '2000233', '0012112', '1111122'],
    words: ['WHISK', 'BASEBALL', 'SKIING', 'GOLF', 'SQUASH', 'SKILLET', 'MORTAR'],
    tier: 3,
    minZipf: 3.08,
    pool: ['WHISK', 'LADLE', 'SPATULA', 'GRATER', 'PEELER', 'SIEVE', 'TONGS', 'MASHER', 'SKILLET', 'CLEAVER', 'MORTAR', 'TENNIS', 'SOCCER', 'RUGBY', 'BOXING', 'SKIING', 'HOCKEY', 'DARTS', 'GOLF', 'CRICKET', 'ROWING', 'SQUASH', 'CYCLING', 'BASEBALL'],
    opening: 1,
    deepest: 6,
  },
  {
    num: 82,
    quizId: 'strata-10-26-26',
    live: '2026-10-26',
    dateLabel: 'October 26, 2026',
    rows: 5,
    cols: 5,
    themes: ['Nighttime'],
    columns: ['RATKS', 'SDRAM', 'OTBON', 'EAMDL', 'KERNA'],
    owners: ['30303', '30034', '42244', '21112', '21122'],
    words: ['DARK', 'DREAM', 'BLANKET', 'STARS', 'MOON'],
    tier: 1,
    minZipf: 4.07,
    pool: ['MOON', 'STARS', 'DARK', 'OWLS', 'DREAM', 'SLEEP', 'PILLOW', 'BLANKET', 'LAMP', 'CURTAIN'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 83,
    quizId: 'strata-10-27-26',
    live: '2026-10-27',
    dateLabel: 'October 27, 2026',
    rows: 5,
    cols: 5,
    themes: ['Toys'],
    columns: ['ZZOLE', 'UNGAP', 'LYWDA', 'DIDRL', 'NTEOT'],
    owners: ['11011', '10001', '42023', '43234', '32243'],
    words: ['WAGON', 'PUZZLE', 'TEDDY', 'TRAIN', 'DOLL'],
    tier: 1,
    minZipf: 3.88,
    pool: ['BALL', 'DOLL', 'BLOCKS', 'PUZZLE', 'KITE', 'MARBLE', 'ROBOT', 'TRAIN', 'TEDDY', 'WAGON', 'YOYO'],
    opening: 1,
    deepest: 3,
  },
  {
    num: 84,
    quizId: 'strata-10-28-26',
    live: '2026-10-28',
    dateLabel: 'October 28, 2026',
    rows: 5,
    cols: 5,
    themes: ['At the doctor'],
    columns: ['ASTLE', 'BIHTT', 'DLTWC', 'EVLRA', 'RIPEF'],
    owners: ['43344', '43344', '20323', '11022', '10011'],
    words: ['PILL', 'FEVER', 'WARD', 'STITCH', 'TABLET'],
    tier: 2,
    minZipf: 3.64,
    pool: ['NURSE', 'WARD', 'PILL', 'TABLET', 'SYRINGE', 'BANDAGE', 'CLINIC', 'SURGEON', 'FEVER', 'STITCH'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 85,
    quizId: 'strata-10-29-26',
    live: '2026-10-29',
    dateLabel: 'October 29, 2026',
    rows: 5,
    cols: 5,
    themes: ['Camping'],
    columns: ['TNTEK', 'HEIPR', 'OEABC', 'CSAKV', 'OKPTE'],
    owners: ['00011', '10122', '22333', '34334', '43344'],
    words: ['TENT', 'HIKE', 'ROPE', 'BACKPACK', 'STOVE'],
    tier: 2,
    minZipf: 3.71,
    pool: ['TENT', 'ROPE', 'STOVE', 'LANTERN', 'TRAIL', 'COMPASS', 'MATCH', 'FLASK', 'BONFIRE', 'HIKE', 'BACKPACK'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 86,
    quizId: 'strata-10-30-26',
    live: '2026-10-30',
    dateLabel: 'October 30, 2026',
    rows: 5,
    cols: 5,
    themes: ['Baking'],
    columns: ['OUFOD', 'CULRH', 'IISTG', 'RTNYU', 'SGAEC'],
    owners: ['33344', '04334', '00224', '21012', '10112'],
    words: ['ICING', 'YEAST', 'CRUST', 'FLOUR', 'DOUGH'],
    tier: 2,
    minZipf: 3.49,
    pool: ['FLOUR', 'SUGAR', 'YEAST', 'DOUGH', 'BATTER', 'ICING', 'CRUST', 'KNEAD', 'PASTRY', 'SPONGE', 'CRUMB', 'GLAZE'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 87,
    quizId: 'strata-10-31-26',
    live: '2026-10-31',
    dateLabel: 'October 31, 2026',
    rows: 5,
    cols: 5,
    themes: ['Herbs and spices'],
    columns: ['ASINT', 'LEGEM', 'ETRSY', 'ISMHA', 'LABYP'],
    owners: ['33444', '22334', '11222', '00112', '00012'],
    words: ['BASIL', 'THYME', 'PARSLEY', 'SAGE', 'MINT'],
    tier: 2,
    minZipf: 3.07,
    pool: ['BASIL', 'THYME', 'SAGE', 'CUMIN', 'ANISE', 'CLOVE', 'NUTMEG', 'PAPRIKA', 'OREGANO', 'PARSLEY', 'GINGER', 'SAFFRON', 'MINT'],
    opening: 1,
    deepest: 3,
  },
  {
    num: 88,
    quizId: 'strata-11-1-26',
    live: '2026-11-01',
    dateLabel: 'November 1, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Weapons and armor', 'Dances'],
    columns: ['ALLADKE', 'RESSVLI', 'ISAQPOU', 'TNGVLMH', 'AEIEOET', 'SAMBAHJ'],
    owners: ['6533567', '7533767', '5537667', '2221445', '2411244', '0000041'],
    words: ['SAMBA', 'JIVE', 'TANGO', 'SALSA', 'HELMET', 'SHIELD', 'POLKA', 'QUIVER'],
    tier: 2,
    minZipf: 2.84,
    pool: ['LANCE', 'SABER', 'RAPIER', 'DAGGER', 'MUSKET', 'SHIELD', 'HELMET', 'VISOR', 'ARROW', 'QUIVER', 'ARMOR', 'TANGO', 'SALSA', 'WALTZ', 'RUMBA', 'SAMBA', 'MAMBO', 'POLKA', 'JIVE', 'BOLERO', 'FLAMENCO', 'FOXTROT'],
    opening: 2,
    deepest: 7,
  },
  {
    num: 89,
    quizId: 'strata-11-2-26',
    live: '2026-11-02',
    dateLabel: 'November 2, 2026',
    rows: 5,
    cols: 5,
    themes: ['Space'],
    columns: ['BKORO', 'ICETR', 'TNYXR', 'AOSAG', 'AOTML'],
    owners: ['10001', '10001', '13442', '43224', '43234'],
    words: ['ROCKET', 'ORBIT', 'STAR', 'MOON', 'GALAXY'],
    tier: 1,
    minZipf: 4.03,
    pool: ['STAR', 'MOON', 'COMET', 'ORBIT', 'PLANET', 'GALAXY', 'ROCKET', 'METEOR', 'CRATER', 'SOLAR', 'LUNAR', 'SHUTTLE'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 90,
    quizId: 'strata-11-3-26',
    live: '2026-11-03',
    dateLabel: 'November 3, 2026',
    rows: 5,
    cols: 5,
    themes: ['Books'],
    columns: ['EPVYN', 'ORLRO', 'IYBAE', 'STRML', 'PAOGE'],
    owners: ['43414', '31414', '10113', '00031', '22022'],
    words: ['STORY', 'LIBRARY', 'PAGE', 'POEM', 'NOVEL'],
    tier: 1,
    minZipf: 4.25,
    pool: ['NOVEL', 'PAGE', 'CHAPTER', 'TITLE', 'COVER', 'INDEX', 'PREFACE', 'AUTHOR', 'LIBRARY', 'POEM', 'STORY'],
    opening: 1,
    deepest: 3,
  },
  {
    num: 91,
    quizId: 'strata-11-4-26',
    live: '2026-11-04',
    dateLabel: 'November 4, 2026',
    rows: 5,
    cols: 5,
    themes: ['Metals'],
    columns: ['COSII', 'PEOLR', 'RSNVP', 'BCZSE', 'RANRI'],
    owners: ['44003', '44303', '42304', '21120', '22101'],
    words: ['SILVER', 'ZINC', 'BRASS', 'IRON', 'COPPER'],
    tier: 2,
    minZipf: 3.65,
    pool: ['IRON', 'STEEL', 'COPPER', 'SILVER', 'BRASS', 'BRONZE', 'NICKEL', 'LEAD', 'ZINC', 'PEWTER', 'COBALT', 'ALLOY'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 92,
    quizId: 'strata-11-5-26',
    live: '2026-11-05',
    dateLabel: 'November 5, 2026',
    rows: 5,
    cols: 5,
    themes: ['Landscape'],
    columns: ['LILPH', 'ILRAE', 'ODPID', 'AGWNO', 'SLEME'],
    owners: ['11001', '21203', '42304', '42403', '33244'],
    words: ['PLAIN', 'HILL', 'RIDGE', 'SLOPE', 'MEADOW'],
    tier: 2,
    minZipf: 3.6,
    pool: ['HILL', 'CLIFF', 'VALLEY', 'RIDGE', 'CANYON', 'PLAIN', 'DUNE', 'MESA', 'PLATEAU', 'SUMMIT', 'SLOPE', 'MEADOW'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 93,
    quizId: 'strata-11-6-26',
    live: '2026-11-06',
    dateLabel: 'November 6, 2026',
    rows: 5,
    cols: 5,
    themes: ['Fasteners'],
    columns: ['LUIAN', 'PIZBC', 'EPRKL', 'EOWCE', 'LTBSR'],
    owners: ['43444', '11133', '21233', '10223', '00021'],
    words: ['BOLT', 'ZIPPER', 'SCREW', 'BUCKLE', 'NAIL'],
    tier: 2,
    minZipf: 3.3,
    pool: ['NAIL', 'SCREW', 'BOLT', 'RIVET', 'STAPLE', 'CLAMP', 'HINGE', 'BUCKLE', 'ZIPPER', 'LATCH'],
    opening: 1,
    deepest: 3,
  },
  {
    num: 94,
    quizId: 'strata-11-7-26',
    live: '2026-11-07',
    dateLabel: 'November 7, 2026',
    rows: 5,
    cols: 5,
    themes: ['Bread'],
    columns: ['SDTMH', 'CUOGU', 'FTRUN', 'STOIF', 'IPATA'],
    owners: ['32342', '33224', '41324', '10144', '00011'],
    words: ['PITA', 'TOAST', 'DOUGH', 'CRUST', 'MUFFIN'],
    tier: 2,
    minZipf: 3,
    pool: ['LOAF', 'ROLL', 'BAGEL', 'TOAST', 'CRUST', 'SCONE', 'MUFFIN', 'BRIOCHE', 'PITA', 'DOUGH'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 95,
    quizId: 'strata-11-8-26',
    live: '2026-11-08',
    dateLabel: 'November 8, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Insects', 'Dog breeds'],
    columns: ['LESPSAW', 'BDKUHOH', 'TEOOMYM', 'CPOLNAA', 'UBTEGXE', 'TISOLSR'],
    owners: ['1160000', '3166677', '7315267', '5115223', '5423344', '5224354'],
    words: ['WASP', 'POODLE', 'MANTIS', 'BEAGLE', 'BOXER', 'LOCUST', 'HUSKY', 'MOTH'],
    tier: 2,
    minZipf: 3,
    pool: ['BEETLE', 'MOTH', 'WASP', 'HORNET', 'LOCUST', 'APHID', 'MANTIS', 'FLEA', 'MIDGE', 'WEEVIL', 'TERMITE', 'BEAGLE', 'BOXER', 'COLLIE', 'POODLE', 'TERRIER', 'SPANIEL', 'HUSKY', 'SETTER', 'MASTIFF', 'WHIPPET'],
    opening: 2,
    deepest: 6,
  },
  {
    num: 96,
    quizId: 'strata-11-9-26',
    live: '2026-11-09',
    dateLabel: 'November 9, 2026',
    rows: 5,
    cols: 5,
    themes: ['Telling time'],
    columns: ['NOCES', 'KODNR', 'EUOHH', 'ETASG', 'NIESW'],
    owners: ['33333', '24304', '24014', '21001', '11002'],
    words: ['SEASON', 'NIGHT', 'WEEK', 'SECOND', 'HOUR'],
    tier: 1,
    minZipf: 5.18,
    pool: ['HOUR', 'WEEK', 'YEAR', 'MONTH', 'MINUTE', 'SECOND', 'DECADE', 'MOMENT', 'SEASON', 'DAWN', 'DUSK', 'NIGHT'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 97,
    quizId: 'strata-11-10-26',
    live: '2026-11-10',
    dateLabel: 'November 10, 2026',
    rows: 5,
    cols: 5,
    themes: ['The office'],
    columns: ['RONET', 'EEPHN', 'OMMKI', 'ASPPR', 'EDPER'],
    owners: ['43334', '40334', '00014', '21244', '11222'],
    words: ['MEMO', 'DESK', 'PAPER', 'PHONE', 'PRINTER'],
    tier: 1,
    minZipf: 3.81,
    pool: ['DESK', 'PHONE', 'FOLDER', 'STAPLER', 'PRINTER', 'MEMO', 'REPORT', 'BINDER', 'PAPER', 'LEDGER', 'FILING'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 98,
    quizId: 'strata-11-11-26',
    live: '2026-11-11',
    dateLabel: 'November 11, 2026',
    rows: 5,
    cols: 5,
    themes: ['At the doctor'],
    columns: ['CTILI', 'HSNTC', 'LLCWI', 'EAIRD', 'SRUNP'],
    owners: ['44334', '44343', '11323', '02122', '00001'],
    words: ['NURSE', 'PILL', 'WARD', 'CLINIC', 'STITCH'],
    tier: 2,
    minZipf: 3.64,
    pool: ['NURSE', 'WARD', 'PILL', 'TABLET', 'SYRINGE', 'BANDAGE', 'CLINIC', 'SURGEON', 'FEVER', 'STITCH'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 99,
    quizId: 'strata-11-12-26',
    live: '2026-11-12',
    dateLabel: 'November 12, 2026',
    rows: 5,
    cols: 5,
    themes: ['Shapes'],
    columns: ['OMNCA', 'NRIOE', 'ACDED', 'ECUHR', 'BSQAU'],
    owners: ['33223', '31322', '11303', '44010', '40004'],
    words: ['SQUARE', 'ARCH', 'CONE', 'DIAMOND', 'CUBE'],
    tier: 1,
    minZipf: 3.82,
    pool: ['CIRCLE', 'SQUARE', 'OVAL', 'CONE', 'CUBE', 'PRISM', 'SPHERE', 'ARCH', 'WEDGE', 'ANGLE', 'DIAMOND', 'CURVE'],
    opening: 1,
    deepest: 3,
  },
  {
    num: 100,
    quizId: 'strata-11-13-26',
    live: '2026-11-13',
    dateLabel: 'November 13, 2026',
    rows: 5,
    cols: 5,
    themes: ['Baking'],
    columns: ['SRCIC', 'THULI', 'YNGAG', 'ZUEGE', 'ODAST'],
    owners: ['22233', '20243', '13044', '40134', '00111'],
    words: ['DOUGH', 'YEAST', 'CRUST', 'ICING', 'GLAZE'],
    tier: 2,
    minZipf: 3.28,
    pool: ['FLOUR', 'SUGAR', 'YEAST', 'DOUGH', 'BATTER', 'ICING', 'CRUST', 'KNEAD', 'PASTRY', 'SPONGE', 'CRUMB', 'GLAZE'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 101,
    quizId: 'strata-11-14-26',
    live: '2026-11-14',
    dateLabel: 'November 14, 2026',
    rows: 5,
    cols: 5,
    themes: ['Camping'],
    columns: ['AIHIL', 'RKTEK', 'SAASS', 'LTFPO', 'CMNET'],
    owners: ['44334', '41433', '11222', '10122', '22000'],
    words: ['TENT', 'FLASK', 'COMPASS', 'HIKE', 'TRAIL'],
    tier: 2,
    minZipf: 3.2,
    pool: ['TENT', 'ROPE', 'STOVE', 'LANTERN', 'TRAIL', 'COMPASS', 'MATCH', 'FLASK', 'BONFIRE', 'HIKE', 'BACKPACK'],
    opening: 2,
    deepest: 3,
  },
  {
    num: 102,
    quizId: 'strata-11-15-26',
    live: '2026-11-15',
    dateLabel: 'November 15, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Reptiles', 'Boats'],
    columns: ['THKONLL', 'YAYAGAE', 'POKNSYO', 'MITRCEP', 'TRUERRE', 'TETABGN'],
    owners: ['2212200', '2111000', '2313503', '3333655', '6565464', '6654445'],
    words: ['GALLEY', 'KAYAK', 'PYTHON', 'MONITOR', 'BARGE', 'SERPENT', 'CUTTER'],
    tier: 2,
    minZipf: 3.22,
    pool: ['GECKO', 'IGUANA', 'COBRA', 'VIPER', 'PYTHON', 'ADDER', 'TURTLE', 'MONITOR', 'CAIMAN', 'LIZARD', 'SERPENT', 'KAYAK', 'CANOE', 'FERRY', 'YACHT', 'SKIFF', 'BARGE', 'SLOOP', 'TRAWLER', 'DINGHY', 'CUTTER', 'GALLEY'],
    opening: 3,
    deepest: 6,
  },
  {
    num: 103,
    quizId: 'strata-11-16-26',
    live: '2026-11-16',
    dateLabel: 'November 16, 2026',
    rows: 5,
    cols: 5,
    themes: ['Money'],
    columns: ['ORSIT', 'PFNEG', 'EHTWA', 'CNAAR', 'HSCGE'],
    owners: ['11011', '11400', '43400', '33234', '22233'],
    words: ['WAGES', 'PROFIT', 'CASH', 'CHANGE', 'RENT'],
    tier: 1,
    minZipf: 4.25,
    pool: ['COIN', 'CASH', 'LOAN', 'WAGES', 'RENT', 'SALARY', 'BUDGET', 'CREDIT', 'PROFIT', 'CHANGE', 'INCOME', 'DEBT'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 104,
    quizId: 'strata-11-17-26',
    live: '2026-11-17',
    dateLabel: 'November 17, 2026',
    rows: 5,
    cols: 5,
    themes: ['Rivers and lakes'],
    columns: ['EKECP', 'ERAOR', 'SRTMN', 'AMIDE', 'RSVRH'],
    owners: ['44340', '43304', '31330', '22101', '22112'],
    words: ['POND', 'RIVER', 'MARSH', 'STREAM', 'CREEK'],
    tier: 1,
    minZipf: 3.87,
    pool: ['RIVER', 'LAKE', 'POND', 'CREEK', 'BROOK', 'STREAM', 'CANAL', 'MARSH', 'DELTA', 'LAGOON', 'RAPIDS'],
    opening: 1,
    deepest: 3,
  },
  {
    num: 105,
    quizId: 'strata-11-18-26',
    live: '2026-11-18',
    dateLabel: 'November 18, 2026',
    rows: 5,
    cols: 5,
    themes: ['Metals'],
    columns: ['SSRBC', 'OAYOE', 'LAPPR', 'NLITL', 'RSEEO'],
    owners: ['00002', '10122', '11222', '41433', '43334'],
    words: ['BRASS', 'ALLOY', 'COPPER', 'STEEL', 'IRON'],
    tier: 2,
    minZipf: 3.61,
    pool: ['IRON', 'STEEL', 'COPPER', 'SILVER', 'BRASS', 'BRONZE', 'NICKEL', 'LEAD', 'ZINC', 'PEWTER', 'COBALT', 'ALLOY'],
    opening: 2,
    deepest: 3,
  },
  {
    num: 106,
    quizId: 'strata-11-19-26',
    live: '2026-11-19',
    dateLabel: 'November 19, 2026',
    rows: 5,
    cols: 5,
    themes: ['Landscape'],
    columns: ['IMLVL', 'EFFHA', 'IWSLL', 'OLMAE', 'DAEYC'],
    owners: ['43404', '32240', '21300', '12130', '11102'],
    words: ['VALLEY', 'MEADOW', 'CLIFF', 'MESA', 'HILL'],
    tier: 2,
    minZipf: 3.5,
    pool: ['HILL', 'CLIFF', 'VALLEY', 'RIDGE', 'CANYON', 'PLAIN', 'DUNE', 'MESA', 'PLATEAU', 'SUMMIT', 'SLOPE', 'MEADOW'],
    opening: 2,
    deepest: 4,
  },
];
