// Puzzle data for the daily game. Imported ONLY by the server page
// component, which filters to live<=today before passing puzzles to the client,
// so future boards never reach the browser bundle. app/strata/page.js also
// strips `owners` and `pool` from every day it does hand over: the client gets
// the letters and the answer list, never the map saying which cell belongs to
// which word.
//
// FIELDS
//   columns  one string per column, that column's letters BOTTOM first. Index 0
//            renders at the bottom row, because that is the end gravity packs to.
//   owners   the same shape in digits: which `words` index owns each cell. The
//            verifier's exact-cover and intended-line checks run off this; it is
//            never shipped to a player.
//   words    the answers, in the order the board was BUILT (which is one valid
//            solve order, not the only one).
//   pool     the rest of the day's category, for the decoy check.
//   opening  how many words can be read on the untouched grid.
//   deepest  how many finds the last word waits for.
//
// AUTHORING RULE (every one of these is machine-checked by
// scripts/verify-strata.mjs, and a board ships only if all of them pass):
//
//   1. EXACT COVER. Every cell belongs to exactly one answer. A spare cell could
//      never be cleared, so the board could not be finished.
//   2. NO DEAD END, ANYWHERE REACHABLE. Whatever order the player clears in, the
//      board can still be finished. This is why Strata has no fail state, needs
//      no undo, and can let a wrong trace cost nothing.
//   3. ONE PLACEMENT PER WORD PER STATE. A word never reads in two places at
//      once, so a correct-looking trace is never refused.
//   4. THE GATE IS REAL. At most three words (in practice one or two) are
//      readable on the untouched grid, and the last word waits on at least two
//      finds, four on a Sunday. Without this the collapse is decoration.
//   5. NO CRUEL DECOY. No other member of the day's category can be traced at any
//      reachable state. Seeing SLEET on a weather grid and having the board
//      refuse it is the worst thing this format can do to somebody.
//
// Boards are BUILT BACKWARDS by scripts/strata-gen.mjs (insert the last word
// into an empty grid, then the second last on top of it, and so on), because a
// grid partitioned forwards has every word contiguous at the start and therefore
// gates nothing. Weekdays are 5x5 on one thread; Sunday Editions are 6x7 and run
// two threads at once.
export const PUZZLES = [
  {
    num: 1,
    quizId: 'strata-8-6-26',
    live: '2026-08-06',
    dateLabel: 'August 6, 2026',
    rows: 5,
    cols: 5,
    themes: ['Sewing'],
    columns: ['BOBON', 'IBHTT', 'RECNT', 'SGDEA', 'SMASU'],
    owners: ['33311', '33112', '42134', '22404', '20002'],
    words: ['SEAM', 'NOTCH', 'GUSSET', 'BOBBIN', 'DART'],
    pool: ['THIMBLE', 'BOBBIN', 'SEAM', 'HEM', 'PLEAT', 'DART', 'BASTE', 'SERGE', 'GUSSET', 'SELVAGE', 'NOTCH'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 2,
    quizId: 'strata-8-7-26',
    live: '2026-08-07',
    dateLabel: 'August 7, 2026',
    rows: 5,
    cols: 5,
    themes: ['Weather'],
    columns: ['DRSMR', 'NRETO', 'FTOUT', 'HESLA', 'WGONS'],
    owners: ['11222', '10122', '00011', '13033', '43444'],
    words: ['FROST', 'THUNDER', 'STORM', 'GALE', 'SNOW'],
    pool: ['RAIN', 'SNOW', 'HAIL', 'SLEET', 'FROST', 'THAW', 'GUST', 'STORM', 'THUNDER', 'DRIZZLE', 'BREEZE', 'MIST', 'GALE', 'SQUALL'],
    opening: 2,
    deepest: 3,
  },
  {
    num: 3,
    quizId: 'strata-8-8-26',
    live: '2026-08-08',
    dateLabel: 'August 8, 2026',
    rows: 5,
    cols: 5,
    themes: ['Fish'],
    columns: ['CALLU', 'EPMRP', 'TIKNE', 'APLOH', 'SMERC'],
    owners: ['33444', '42433', '42212', '10110', '11000'],
    words: ['PERCH', 'SALMON', 'PIKE', 'CARP', 'MULLET'],
    pool: ['TROUT', 'SALMON', 'TUNA', 'PERCH', 'BASS', 'PIKE', 'CARP', 'MULLET', 'HERRING', 'MACKEREL', 'SARDINE', 'HALIBUT', 'TURBOT'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 4,
    quizId: 'strata-8-9-26',
    live: '2026-08-09',
    dateLabel: 'August 9, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Birds of prey', 'Pasta shapes'],
    columns: ['NEUINGB', 'ENZEUIN', 'PZALDAL', 'GEREOCA', 'NSLONEA', 'DRAGHWK'],
    owners: ['0021112', '0021111', '0221233', '3323664', '6446445', '6644555'],
    words: ['PENNE', 'LINGUINE', 'BUZZARD', 'EAGLE', 'LASAGNE', 'HAWK', 'CONDOR'],
    pool: ['EAGLE', 'HAWK', 'FALCON', 'KESTREL', 'OSPREY', 'HARRIER', 'BUZZARD', 'CONDOR', 'VULTURE', 'MERLIN', 'GOSHAWK', 'PENNE', 'FUSILLI', 'RIGATONI', 'ORZO', 'FARFALLE', 'LINGUINE', 'ROTINI', 'ZITI', 'LASAGNE', 'RAVIOLI', 'GNOCCHI'],
    opening: 2,
    deepest: 5,
  },
  {
    num: 5,
    quizId: 'strata-8-10-26',
    live: '2026-08-10',
    dateLabel: 'August 10, 2026',
    rows: 5,
    cols: 5,
    themes: ['Musical instruments'],
    columns: ['FORLF', 'AIGUT', 'OEADN', 'LTDBE', 'LECLU'],
    owners: ['23344', '32344', '04123', '01212', '00021'],
    words: ['CELLO', 'TUBA', 'FIDDLE', 'ORGAN', 'FLUTE'],
    pool: ['VIOLA', 'CELLO', 'ORGAN', 'FLUTE', 'OBOE', 'HARP', 'TUBA', 'PIANO', 'BANJO', 'FIDDLE', 'TRUMPET', 'DRUM'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 6,
    quizId: 'strata-8-11-26',
    live: '2026-08-11',
    dateLabel: 'August 11, 2026',
    rows: 5,
    cols: 5,
    themes: ['Boats'],
    columns: ['ODIPK', 'ONLSA', 'NGTYK', 'HAOUC', 'PEYNA'],
    owners: ['31134', '31334', '21244', '14020', '20100'],
    words: ['CANOE', 'DINGHY', 'PUNT', 'SLOOP', 'KAYAK'],
    pool: ['KAYAK', 'CANOE', 'FERRY', 'YACHT', 'SKIFF', 'BARGE', 'SLOOP', 'KETCH', 'TRAWLER', 'GALLEON', 'DINGHY', 'CUTTER', 'PUNT'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 7,
    quizId: 'strata-8-12-26',
    live: '2026-08-12',
    dateLabel: 'August 12, 2026',
    rows: 5,
    cols: 5,
    themes: ['Big cats'],
    columns: ['GTOIL', 'INTER', 'UMAAO', 'SBPCB', 'ERVAL'],
    owners: ['44000', '40344', '22233', '13233', '11111'],
    words: ['LION', 'SERVAL', 'PUMA', 'BOBCAT', 'TIGER'],
    pool: ['LION', 'TIGER', 'LEOPARD', 'JAGUAR', 'CHEETAH', 'COUGAR', 'PUMA', 'LYNX', 'OCELOT', 'PANTHER', 'CARACAL', 'SERVAL', 'BOBCAT'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 8,
    quizId: 'strata-8-13-26',
    live: '2026-08-13',
    dateLabel: 'August 13, 2026',
    rows: 5,
    cols: 5,
    themes: ['Bones'],
    columns: ['LLNLT', 'AAEUA', 'SBPAR', 'CUISL', 'RKULM'],
    owners: ['11001', '10101', '42142', '44233', '43334'],
    words: ['ULNA', 'PATELLA', 'RIB', 'SKULL', 'SACRUM'],
    pool: ['FEMUR', 'TIBIA', 'FIBULA', 'RADIUS', 'ULNA', 'SCAPULA', 'PATELLA', 'SACRUM', 'CARPAL', 'RIB', 'SKULL', 'STAPES'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 9,
    quizId: 'strata-8-14-26',
    live: '2026-08-14',
    dateLabel: 'August 14, 2026',
    rows: 5,
    cols: 5,
    themes: ['Chess'],
    columns: ['IANTA', 'BWGMG', 'WNPUZ', 'OGPAZ', 'ROKNI'],
    owners: ['43344', '43344', '22233', '03123', '00011'],
    words: ['ROOK', 'PIN', 'PAWN', 'ZUGZWANG', 'GAMBIT'],
    pool: ['ROOK', 'BISHOP', 'KNIGHT', 'PAWN', 'QUEEN', 'GAMBIT', 'ZUGZWANG', 'FORK', 'PIN', 'SKEWER', 'CASTLE', 'ENDGAME'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 10,
    quizId: 'strata-8-15-26',
    live: '2026-08-15',
    dateLabel: 'August 15, 2026',
    rows: 5,
    cols: 5,
    themes: ['Body parts'],
    columns: ['RWSTO', 'BIWYN', 'ENEDL', 'IHIKS', 'REVIL'],
    owners: ['11114', '41422', '43224', '33223', '00000'],
    words: ['LIVER', 'WRIST', 'KIDNEY', 'SHIN', 'ELBOW'],
    pool: ['SPLEEN', 'TEMPLE', 'KIDNEY', 'LIVER', 'ANKLE', 'WRIST', 'SHIN', 'ELBOW', 'THIGH', 'PELVIS', 'STERNUM', 'TENDON', 'RETINA'],
    opening: 2,
    deepest: 3,
  },
  {
    num: 11,
    quizId: 'strata-8-16-26',
    live: '2026-08-16',
    dateLabel: 'August 16, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Reptiles', 'Constellations'],
    columns: ['ABRRBIA', 'MTTUMAL', 'EAROMLA', 'ORNAIIC', 'YNGCOVO', 'LRIRUSV'],
    owners: ['5534445', '5333544', '3122030', '2100200', '1276667', '1776667'],
    words: ['CAIMAN', 'LYRA', 'ORION', 'TURTLE', 'LIBRA', 'MAMBA', 'CORVUS', 'VIRGO'],
    pool: ['GECKO', 'IGUANA', 'COBRA', 'VIPER', 'PYTHON', 'ADDER', 'TURTLE', 'SKINK', 'MONITOR', 'CAIMAN', 'MAMBA', 'KRAIT', 'ORION', 'LYRA', 'DRACO', 'CYGNUS', 'PERSEUS', 'PEGASUS', 'HYDRA', 'ARIES', 'TAURUS', 'VIRGO', 'LIBRA', 'CORVUS'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 12,
    quizId: 'strata-8-17-26',
    live: '2026-08-17',
    dateLabel: 'August 17, 2026',
    rows: 5,
    cols: 5,
    themes: ['Currencies'],
    columns: ['OFLLO', 'RNADT', 'IRUON', 'NRPOD', 'AKYEN'],
    owners: ['22111', '22112', '21434', '33444', '33000'],
    words: ['YEN', 'DOLLAR', 'FORINT', 'KRONA', 'POUND'],
    pool: ['EURO', 'YEN', 'PESO', 'RUPEE', 'DINAR', 'FRANC', 'KRONA', 'RAND', 'POUND', 'DOLLAR', 'SHEKEL', 'FORINT', 'DIRHAM'],
    opening: 2,
    deepest: 3,
  },
  {
    num: 13,
    quizId: 'strata-8-18-26',
    live: '2026-08-18',
    dateLabel: 'August 18, 2026',
    rows: 5,
    cols: 5,
    themes: ['Card games'],
    columns: ['OERAF', 'PKHRI', 'SYOMW', 'TDSMP', 'EASRU'],
    owners: ['11100', '11303', '32023', '34424', '44422'],
    words: ['FARO', 'POKER', 'RUMMY', 'WHIST', 'SPADES'],
    pool: ['HEARTS', 'BRIDGE', 'POKER', 'RUMMY', 'CANASTA', 'EUCHRE', 'SPADES', 'WHIST', 'CRIBBAGE', 'FARO'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 14,
    quizId: 'strata-8-19-26',
    live: '2026-08-19',
    dateLabel: 'August 19, 2026',
    rows: 5,
    cols: 5,
    themes: ['Gemstones'],
    columns: ['CAMON', 'RZBLA', 'IOPEJ', 'ASDJR', 'PEREA'],
    owners: ['10011', '11022', '12203', '33440', '33344'],
    words: ['AMBER', 'ZIRCON', 'OPAL', 'JASPER', 'JADE'],
    pool: ['RUBY', 'OPAL', 'JADE', 'TOPAZ', 'PEARL', 'AMBER', 'GARNET', 'ZIRCON', 'BERYL', 'ONYX', 'AGATE', 'JASPER', 'EMERALD'],
    opening: 1,
    deepest: 3,
  },
  {
    num: 15,
    quizId: 'strata-8-20-26',
    live: '2026-08-20',
    dateLabel: 'August 20, 2026',
    rows: 5,
    cols: 5,
    themes: ['Golf terms'],
    columns: ['CBYEE', 'LIOGR', 'ESEKL', 'BNTGA', 'TUEUP'],
    owners: ['10001', '11002', '31223', '22433', '42344'],
    words: ['BOGEY', 'SLICE', 'BUNKER', 'EAGLE', 'PUTT'],
    pool: ['BIRDIE', 'EAGLE', 'BOGEY', 'PUTT', 'DRIVER', 'WEDGE', 'FAIRWAY', 'BUNKER', 'CADDIE', 'IRON', 'SLICE', 'ALBATROS'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 16,
    quizId: 'strata-8-21-26',
    live: '2026-08-21',
    dateLabel: 'August 21, 2026',
    rows: 5,
    cols: 5,
    themes: ['Breads'],
    columns: ['RYUFI', 'FEMAN', 'ANCEL', 'HNEOB', 'BAGIR'],
    owners: ['00111', '10121', '22443', '42344', '33344'],
    words: ['RYE', 'MUFFIN', 'NAAN', 'BAGEL', 'BRIOCHE'],
    pool: ['BAGEL', 'BRIOCHE', 'CIABATTA', 'PITA', 'NAAN', 'RYE', 'BAGUETTE', 'CHALLAH', 'MUFFIN', 'SCONE', 'BANNOCK'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 17,
    quizId: 'strata-8-22-26',
    live: '2026-08-22',
    dateLabel: 'August 22, 2026',
    rows: 5,
    cols: 5,
    themes: ['Cheeses'],
    columns: ['ISTIA', 'AOTLS', 'ARNEG', 'TFBIO', 'MADEE'],
    owners: ['43334', '43334', '12324', '11224', '00001'],
    words: ['EDAM', 'FETA', 'BRIE', 'STILTON', 'ASIAGO'],
    pool: ['BRIE', 'GOUDA', 'EDAM', 'FETA', 'STILTON', 'CHEDDAR', 'GRUYERE', 'MANCHEGO', 'RICOTTA', 'HALLOUMI', 'ASIAGO'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 18,
    quizId: 'strata-8-23-26',
    live: '2026-08-23',
    dateLabel: 'August 23, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Dog breeds', 'Theater'],
    columns: ['NBXIRRT', 'OPCUOEA', 'ODLEALH', 'SIBCOUY', 'ULSCNKE', 'LROHOCY'],
    owners: ['6556566', '0066556', '0000223', '1422233', '1431234', '4111442'],
    words: ['POODLE', 'CHORUS', 'BALCONY', 'HUSKY', 'COLLIE', 'BOXER', 'CURTAIN'],
    pool: ['BEAGLE', 'BOXER', 'COLLIE', 'POODLE', 'TERRIER', 'SPANIEL', 'HUSKY', 'SETTER', 'MASTIFF', 'WHIPPET', 'BORZOI', 'STAGE', 'CURTAIN', 'SCRIPT', 'ACTOR', 'WINGS', 'PROPS', 'USHER', 'BALCONY', 'ENCORE', 'MATINEE', 'CHORUS', 'PROMPT'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 19,
    quizId: 'strata-8-24-26',
    live: '2026-08-24',
    dateLabel: 'August 24, 2026',
    rows: 5,
    cols: 5,
    themes: ['Trees'],
    columns: ['RAAKS', 'HZOPU', 'IWLEC', 'LOAEE', 'WSPNL'],
    owners: ['43114', '33144', '22334', '22004', '20002'],
    words: ['ASPEN', 'OAK', 'WILLOW', 'HAZEL', 'SPRUCE'],
    pool: ['OAK', 'ELM', 'ASH', 'BIRCH', 'CEDAR', 'MAPLE', 'WILLOW', 'ASPEN', 'ALDER', 'POPLAR', 'SPRUCE', 'LARCH', 'BEECH', 'HAZEL'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 20,
    quizId: 'strata-8-25-26',
    live: '2026-08-25',
    dateLabel: 'August 25, 2026',
    rows: 5,
    cols: 5,
    themes: ['Fish'],
    columns: ['LASIN', 'OMERG', 'SHNNR', 'SUAPC', 'RABTA'],
    owners: ['33344', '33444', '04134', '01122', '20012'],
    words: ['BASS', 'TUNA', 'CARP', 'SALMON', 'HERRING'],
    pool: ['TROUT', 'SALMON', 'TUNA', 'PERCH', 'BASS', 'PIKE', 'CARP', 'MULLET', 'HERRING', 'MACKEREL', 'SARDINE', 'HALIBUT', 'TURBOT'],
    opening: 1,
    deepest: 3,
  },
  {
    num: 21,
    quizId: 'strata-8-26-26',
    live: '2026-08-26',
    dateLabel: 'August 26, 2026',
    rows: 5,
    cols: 5,
    themes: ['Printing'],
    columns: ['FITYN', 'IOPNE', 'EREQU', 'ITLFS', 'OLAPO'],
    owners: ['24334', '24303', '22044', '10012', '11001'],
    words: ['PLATEN', 'FOLIO', 'SERIF', 'TYPE', 'QUOIN'],
    pool: ['SERIF', 'KERNING', 'GALLEY', 'PLATEN', 'QUOIN', 'FOLIO', 'QUARTO', 'LIGATURE', 'INKWELL', 'PRESS', 'TYPE'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 22,
    quizId: 'strata-8-27-26',
    live: '2026-08-27',
    dateLabel: 'August 27, 2026',
    rows: 5,
    cols: 5,
    themes: ['Musical instruments'],
    columns: ['TUMUL', 'REDFT', 'LOPEH', 'RLPAM', 'TERCU'],
    owners: ['34411', '43411', '22310', '32003', '32023'],
    words: ['HARP', 'FLUTE', 'CELLO', 'TRUMPET', 'DRUM'],
    pool: ['VIOLA', 'CELLO', 'ORGAN', 'FLUTE', 'OBOE', 'HARP', 'TUBA', 'PIANO', 'BANJO', 'FIDDLE', 'TRUMPET', 'DRUM'],
    opening: 2,
    deepest: 3,
  },
  {
    num: 23,
    quizId: 'strata-8-28-26',
    live: '2026-08-28',
    dateLabel: 'August 28, 2026',
    rows: 5,
    cols: 5,
    themes: ['Shades of red'],
    columns: ['YBUIE', 'NMRHB', 'KRSLE', 'ABSUC', 'RCROI'],
    owners: ['22233', '33200', '43001', '34104', '43114'],
    words: ['BLUSH', 'ROSE', 'RUBY', 'CARMINE', 'BRICK'],
    pool: ['CRIMSON', 'SCARLET', 'RUBY', 'CORAL', 'CARMINE', 'MAROON', 'CERISE', 'GARNET', 'BRICK', 'ROSE', 'BLUSH'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 24,
    quizId: 'strata-8-29-26',
    live: '2026-08-29',
    dateLabel: 'August 29, 2026',
    rows: 5,
    cols: 5,
    themes: ['Sea creatures'],
    columns: ['RETLA', 'EOYSH', 'WARAN', 'CRAWO', 'MANTP'],
    owners: ['00011', '10001', '14433', '43234', '22223'],
    words: ['OYSTER', 'WHALE', 'MANTA', 'PRAWN', 'ORCA'],
    pool: ['OCTOPUS', 'SQUID', 'CORAL', 'URCHIN', 'MANTA', 'WHALE', 'ORCA', 'WALRUS', 'LOBSTER', 'PRAWN', 'MUSSEL', 'OYSTER'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 25,
    quizId: 'strata-8-30-26',
    live: '2026-08-30',
    dateLabel: 'August 30, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Winds', 'Cocktails'],
    columns: ['UDMLTAR', 'IQIEIAO', 'RABRIGJ', 'TNIDLUS', 'OMENEOE', 'NRONOPG'],
    owners: ['5544456', '5544566', '3365540', '3223001', '2121013', '2211102'],
    words: ['JULEP', 'MONSOON', 'NEGRONI', 'TRADE', 'GIMLET', 'DAIQUIRI', 'BORA'],
    pool: ['MISTRAL', 'SIROCCO', 'CHINOOK', 'MONSOON', 'TRADE', 'ZEPHYR', 'BORA', 'HABOOB', 'SANTAANA', 'LEVANTER', 'MARTINI', 'NEGRONI', 'DAIQUIRI', 'MOJITO', 'SIDECAR', 'GIMLET', 'SAZERAC', 'PALOMA', 'BELLINI', 'JULEP'],
    opening: 1,
    deepest: 6,
  },
  {
    num: 26,
    quizId: 'strata-8-31-26',
    live: '2026-08-31',
    dateLabel: 'August 31, 2026',
    rows: 5,
    cols: 5,
    themes: ['Hand tools'],
    columns: ['PEALR', 'IVLLS', 'ASDER', 'NDGLE', 'EOUGR'],
    owners: ['42434', '32234', '11323', '11020', '10001'],
    words: ['GOUGE', 'SANDER', 'LEVEL', 'DRILL', 'RASP'],
    pool: ['HAMMER', 'WRENCH', 'PLIERS', 'CHISEL', 'DRILL', 'SANDER', 'MALLET', 'CLAMP', 'RASP', 'PLANE', 'LEVEL', 'GOUGE'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 27,
    quizId: 'strata-9-1-26',
    live: '2026-09-01',
    dateLabel: 'September 1, 2026',
    rows: 5,
    cols: 5,
    themes: ['Big cats'],
    columns: ['LMAPS', 'EVUAI', 'REOLH', 'CLXEN', 'YNTAH'],
    owners: ['31112', '22123', '24324', '40043', '00444'],
    words: ['LYNX', 'PUMA', 'SERVAL', 'LION', 'CHEETAH'],
    pool: ['LION', 'TIGER', 'LEOPARD', 'JAGUAR', 'CHEETAH', 'COUGAR', 'PUMA', 'LYNX', 'OCELOT', 'PANTHER', 'CARACAL', 'SERVAL', 'BOBCAT'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 28,
    quizId: 'strata-9-2-26',
    live: '2026-09-02',
    dateLabel: 'September 2, 2026',
    rows: 5,
    cols: 5,
    themes: ['Rivers'],
    columns: ['GEBEU', 'ATLSO', 'EDRON', 'ENNHH', 'ARNIS'],
    owners: ['10001', '11012', '32344', '24334', '42434'],
    words: ['ELBE', 'TAGUS', 'ODER', 'RHINE', 'SHANNON'],
    pool: ['DANUBE', 'VOLGA', 'RHINE', 'SEINE', 'THAMES', 'TIBER', 'EBRO', 'LOIRE', 'ODER', 'ELBE', 'SHANNON', 'TAGUS'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 29,
    quizId: 'strata-9-3-26',
    live: '2026-09-03',
    dateLabel: 'September 3, 2026',
    rows: 5,
    cols: 5,
    themes: ['Herbs and spices'],
    columns: ['MYHVA', 'ETOEK', 'APRIL', 'CPMAG', 'SINET'],
    owners: ['11120', '11220', '00002', '20433', '34434'],
    words: ['PAPRIKA', 'THYME', 'CLOVE', 'SAGE', 'MINT'],
    pool: ['BASIL', 'THYME', 'SAGE', 'CUMIN', 'ANISE', 'CLOVE', 'NUTMEG', 'PAPRIKA', 'OREGANO', 'PARSLEY', 'GINGER', 'SAFFRON', 'MINT'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 30,
    quizId: 'strata-9-4-26',
    live: '2026-09-04',
    dateLabel: 'September 4, 2026',
    rows: 5,
    cols: 5,
    themes: ['Body parts'],
    columns: ['HEBOS', 'NTILW', 'IYEDH', 'GLNIH', 'IVEKR'],
    owners: ['43334', '42433', '20002', '21002', '11101'],
    words: ['KIDNEY', 'LIVER', 'THIGH', 'ELBOW', 'SHIN'],
    pool: ['SPLEEN', 'TEMPLE', 'KIDNEY', 'LIVER', 'ANKLE', 'WRIST', 'SHIN', 'ELBOW', 'THIGH', 'PELVIS', 'STERNUM', 'TENDON', 'RETINA'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 31,
    quizId: 'strata-9-5-26',
    live: '2026-09-05',
    dateLabel: 'September 5, 2026',
    rows: 5,
    cols: 5,
    themes: ['Fabrics'],
    columns: ['FFUED', 'INSEO', 'SLNCH', 'OATKI', 'SILOW'],
    owners: ['44333', '44334', '21244', '12202', '00011'],
    words: ['SILK', 'WOOL', 'SATIN', 'SUEDE', 'CHIFFON'],
    pool: ['LINEN', 'SILK', 'DENIM', 'VELVET', 'SATIN', 'TWEED', 'COTTON', 'CANVAS', 'CHIFFON', 'FLANNEL', 'MUSLIN', 'SUEDE', 'WOOL'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 32,
    quizId: 'strata-9-6-26',
    live: '2026-09-06',
    dateLabel: 'September 6, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Breads', 'Kitchen tools'],
    columns: ['HKIASRL', 'ASMHEEL', 'OLNCANT', 'NCGRLHA', 'EAATESS', 'PATURLA'],
    owners: ['2665556', '2655566', '1242446', '1100224', '1200013', '3333033'],
    words: ['GRATER', 'SCONE', 'CHALLAH', 'SPATULA', 'NAAN', 'MASHER', 'SKILLET'],
    pool: ['BAGEL', 'BRIOCHE', 'CIABATTA', 'PITA', 'NAAN', 'RYE', 'BAGUETTE', 'CHALLAH', 'MUFFIN', 'SCONE', 'BANNOCK', 'WHISK', 'LADLE', 'SPATULA', 'GRATER', 'PEELER', 'SIEVE', 'TONGS', 'MASHER', 'SKILLET', 'KETTLE', 'CLEAVER', 'MORTAR'],
    opening: 2,
    deepest: 4,
  },
];
