// Puzzle data for the daily game. Imported ONLY by the server page
// component, which filters to live<=today before passing puzzles to the client,
// so future boards never reach the browser bundle. app/strata/page.js also
// strips `owners` and `pool` from every day it does hand over: the client gets
// the letters and the answer list, never the map saying which cell belongs to
// which word.
//
// FIELDS
//   columns  one string per column, that column's letters BOTTOM first. Index 0
//            renders at the bottom row, because that is the end gravity packs to.
//   owners   the same shape in digits: which `words` index owns each cell. The
//            verifier's exact-cover and intended-line checks run off this; it is
//            never shipped to a player.
//   words    the answers, in the order the board was BUILT (which is one valid
//            solve order, not the only one).
//   pool     the rest of the day's category, for the decoy check.
//   opening  how many words can be read on the untouched grid.
//   deepest  how many finds the last word waits for.
//
// AUTHORING RULE (every one of these is machine-checked by
// scripts/verify-strata.mjs, and a board ships only if all of them pass):
//
//   1. EXACT COVER. Every cell belongs to exactly one answer. A spare cell could
//      never be cleared, so the board could not be finished.
//   2. NO DEAD END, ANYWHERE REACHABLE. Whatever order the player clears in, the
//      board can still be finished. This is why Strata has no fail state, needs
//      no undo, and can let a wrong trace cost nothing.
//   3. ONE PLACEMENT PER WORD PER STATE. A word never reads in two places at
//      once, so a correct-looking trace is never refused.
//   4. THE GATE IS REAL. At most three words (in practice one or two) are
//      readable on the untouched grid, and the last word waits on at least two
//      finds, four on a Sunday. Without this the collapse is decoration.
//   5. NO CRUEL DECOY. No other member of the day's category can be traced at any
//      reachable state. Seeing SLEET on a weather grid and having the board
//      refuse it is the worst thing this format can do to somebody.
//
// Boards are BUILT BACKWARDS by scripts/strata-gen.mjs (insert the last word
// into an empty grid, then the second last on top of it, and so on), because a
// grid partitioned forwards has every word contiguous at the start and therefore
// gates nothing. Weekdays are 5x5 on one thread; Sunday Editions are 6x7 and run
// two threads at once.
export const PUZZLES = [
  {
    num: 1,
    quizId: 'strata-8-6-26',
    live: '2026-08-06',
    dateLabel: 'August 6, 2026',
    rows: 5,
    cols: 5,
    themes: ['Sewing'],
    columns: ['BOBON', 'IBHTT', 'RECNT', 'SGDEA', 'SMASU'],
    owners: ['33311', '33112', '42134', '22404', '20002'],
    words: ['SEAM', 'NOTCH', 'GUSSET', 'BOBBIN', 'DART'],
    tier: undefined,
    pool: ['THIMBLE', 'BOBBIN', 'SEAM', 'HEM', 'PLEAT', 'DART', 'BASTE', 'SERGE', 'GUSSET', 'SELVAGE', 'NOTCH'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 2,
    quizId: 'strata-8-7-26',
    live: '2026-08-07',
    dateLabel: 'August 7, 2026',
    rows: 5,
    cols: 5,
    themes: ['Big cats'],
    columns: ['EAIUT', 'RIGMP', 'LGORN', 'ARAUA', 'GUOCJ'],
    owners: ['43434', '42433', '21212', '00111', '00001'],
    words: ['COUGAR', 'JAGUAR', 'LION', 'PUMA', 'TIGER'],
    tier: 2,
    minZipf: 3.22,
    pool: ['LION', 'TIGER', 'LEOPARD', 'JAGUAR', 'CHEETAH', 'COUGAR', 'PUMA', 'LYNX', 'OCELOT', 'PANTHER', 'BOBCAT'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 3,
    quizId: 'strata-8-8-26',
    live: '2026-08-08',
    dateLabel: 'August 8, 2026',
    rows: 5,
    cols: 5,
    themes: ['Chess'],
    columns: ['AODOK', 'OCRBR', 'HGAMQ', 'EUEBK', 'ENCIT'],
    owners: ['33344', '42334', '20001', '11202', '11200'],
    words: ['GAMBIT', 'QUEEN', 'CHECK', 'BOARD', 'ROOK'],
    tier: 2,
    minZipf: 3.1,
    pool: ['ROOK', 'BISHOP', 'KNIGHT', 'QUEEN', 'GAMBIT', 'FORK', 'SKEWER', 'CASTLE', 'ENDGAME', 'CHECK', 'BOARD'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 4,
    quizId: 'strata-8-9-26',
    live: '2026-08-09',
    dateLabel: 'August 9, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Kitchen tools', 'Bones'],
    columns: ['SASGETR', 'KONLDSU', 'TLKLIUL', 'LCIASSP', 'AEIAUTA', 'BVELRIT'],
    owners: ['6522445', '6224556', '2446556', '1143400', '1130000', '3110133'],
    words: ['SPATULA', 'CLEAVER', 'TONGS', 'TIBIA', 'SKILLET', 'RADIUS', 'SKULL'],
    tier: 3,
    minZipf: 2.8,
    pool: ['WHISK', 'LADLE', 'SPATULA', 'GRATER', 'PEELER', 'SIEVE', 'TONGS', 'MASHER', 'SKILLET', 'CLEAVER', 'MORTAR', 'FEMUR', 'TIBIA', 'FIBULA', 'RADIUS', 'SCAPULA', 'PATELLA', 'SACRUM', 'CARPAL', 'SKULL', 'STERNUM'],
    opening: 2,
    deepest: 5,
  },
  {
    num: 5,
    quizId: 'strata-8-10-26',
    live: '2026-08-10',
    dateLabel: 'August 10, 2026',
    rows: 5,
    cols: 5,
    themes: ['Body parts'],
    columns: ['UAEHT', 'HMRIF', 'GTBNR', 'SEIER', 'TEWNK'],
    owners: ['10001', '11022', '20122', '42434', '43433'],
    words: ['HEART', 'THUMB', 'FINGER', 'KNEE', 'WRIST'],
    tier: 1,
    minZipf: 4.01,
    pool: ['ELBOW', 'WRIST', 'ANKLE', 'THIGH', 'SHOULDER', 'FINGER', 'THUMB', 'KNEE', 'HEART', 'LIVER', 'SPLEEN', 'TEMPLE', 'STOMACH'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 6,
    quizId: 'strata-8-11-26',
    live: '2026-08-11',
    dateLabel: 'August 11, 2026',
    rows: 5,
    cols: 5,
    themes: ['Colors'],
    columns: ['EAMRC', 'TLOEN', 'VWROR', 'BELIG', 'ENBUE'],
    owners: ['23333', '22434', '24124', '41021', '11000'],
    words: ['BLUE', 'GREEN', 'VIOLET', 'CREAM', 'BROWN'],
    tier: 1,
    minZipf: 3.84,
    pool: ['BLUE', 'GREEN', 'BLACK', 'WHITE', 'BROWN', 'PINK', 'PURPLE', 'ORANGE', 'SILVER', 'GOLDEN', 'YELLOW', 'SCARLET', 'VIOLET', 'CREAM', 'CRIMSON'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 7,
    quizId: 'strata-8-12-26',
    live: '2026-08-12',
    dateLabel: 'August 12, 2026',
    rows: 5,
    cols: 5,
    themes: ['Furniture'],
    columns: ['EHBER', 'LOFNS', 'RIHKC', 'TLMRS', 'BAEDE'],
    owners: ['44113', '43414', '33101', '22330', '22200'],
    words: ['DESK', 'BENCH', 'TABLE', 'MIRROR', 'SHELF'],
    tier: 1,
    minZipf: 4.02,
    pool: ['CHAIR', 'TABLE', 'SOFA', 'DESK', 'SHELF', 'STOOL', 'BENCH', 'LAMP', 'MIRROR', 'COUCH', 'DRESSER', 'CABINET', 'CUPBOARD'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 8,
    quizId: 'strata-8-13-26',
    live: '2026-08-13',
    dateLabel: 'August 13, 2026',
    rows: 5,
    cols: 5,
    themes: ['Fabrics'],
    columns: ['NCTAC', 'VTOAS', 'ILKON', 'DLMIS', 'OOWEN'],
    owners: ['43344', '43344', '22233', '10112', '00011'],
    words: ['WOOL', 'DENIM', 'SILK', 'COTTON', 'CANVAS'],
    tier: 2,
    minZipf: 3.52,
    pool: ['LINEN', 'SILK', 'DENIM', 'VELVET', 'SATIN', 'TWEED', 'COTTON', 'CANVAS', 'CHIFFON', 'FLANNEL', 'MUSLIN', 'SUEDE', 'WOOL'],
    opening: 1,
    deepest: 3,
  },
  {
    num: 9,
    quizId: 'strata-8-14-26',
    live: '2026-08-14',
    dateLabel: 'August 14, 2026',
    rows: 5,
    cols: 5,
    themes: ['Rooms in a house'],
    columns: ['NHAGL', 'ULOEA', 'YLTTI', 'TRCOD', 'SHCPU'],
    owners: ['10011', '10112', '40222', '43234', '43334'],
    words: ['HALL', 'LOUNGE', 'ATTIC', 'PORCH', 'STUDY'],
    tier: 1,
    minZipf: 3.63,
    pool: ['KITCHEN', 'BEDROOM', 'ATTIC', 'CELLAR', 'HALL', 'PORCH', 'STUDY', 'PANTRY', 'GARAGE', 'LOUNGE', 'LANDING'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 10,
    quizId: 'strata-8-15-26',
    live: '2026-08-15',
    dateLabel: 'August 15, 2026',
    rows: 5,
    cols: 5,
    themes: ['Gemstones'],
    columns: ['PAAER', 'ORBLM', 'RAEBY', 'PNUGJ', 'TERSA'],
    owners: ['33444', '32434', '11200', '21012', '11022'],
    words: ['RUBY', 'GARNET', 'JASPER', 'OPAL', 'AMBER'],
    tier: 2,
    minZipf: 3.17,
    pool: ['RUBY', 'OPAL', 'JADE', 'TOPAZ', 'PEARL', 'AMBER', 'GARNET', 'ZIRCON', 'BERYL', 'ONYX', 'AGATE', 'JASPER', 'EMERALD'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 11,
    quizId: 'strata-8-16-26',
    live: '2026-08-16',
    dateLabel: 'August 16, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Dances', 'Sea creatures'],
    columns: ['TVOANGO', 'ESYIMAF', 'ETCNEJL', 'UROBSSS', 'OTUQOCI', 'LERDPOT'],
    owners: ['3213333', '2112000', '1100020', '6104456', '4456556', '4446555'],
    words: ['FLAMENCO', 'OYSTER', 'JIVE', 'TANGO', 'LOBSTER', 'OCTOPUS', 'SQUID'],
    tier: 2,
    minZipf: 2.93,
    pool: ['TANGO', 'SALSA', 'WALTZ', 'RUMBA', 'SAMBA', 'MAMBO', 'POLKA', 'JIVE', 'BOLERO', 'FLAMENCO', 'FOXTROT', 'OCTOPUS', 'SQUID', 'CORAL', 'URCHIN', 'MANTA', 'WHALE', 'WALRUS', 'LOBSTER', 'PRAWN', 'MUSSEL', 'OYSTER'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 12,
    quizId: 'strata-8-17-26',
    live: '2026-08-17',
    dateLabel: 'August 17, 2026',
    rows: 5,
    cols: 5,
    themes: ['Farm animals'],
    columns: ['TUDEL', 'AYURK', 'MKCBN', 'EOATI', 'GKCHC'],
    owners: ['11012', '21011', '20024', '43334', '34444'],
    words: ['DUCK', 'TURKEY', 'LAMB', 'GOAT', 'CHICKEN'],
    tier: 1,
    minZipf: 4.02,
    pool: ['HORSE', 'SHEEP', 'GOAT', 'DUCK', 'GOOSE', 'DONKEY', 'RABBIT', 'CHICKEN', 'CATTLE', 'LAMB', 'CALF', 'FOAL', 'TURKEY'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 13,
    quizId: 'strata-8-18-26',
    live: '2026-08-18',
    dateLabel: 'August 18, 2026',
    rows: 5,
    cols: 5,
    themes: ['At the beach'],
    columns: ['LLTOW', 'HEEEO', 'CESLA', 'RSOVN', 'SHEWA'],
    owners: ['33000', '33404', '42304', '21214', '22111'],
    words: ['TOWEL', 'WAVES', 'SHORE', 'SHELL', 'OCEAN'],
    tier: 1,
    minZipf: 3.94,
    pool: ['SAND', 'WAVES', 'SHELL', 'TOWEL', 'SURF', 'TIDE', 'OCEAN', 'PALM', 'CRAB', 'DUNE', 'SHORE', 'PEBBLE', 'SEAWEED'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 14,
    quizId: 'strata-8-19-26',
    live: '2026-08-19',
    dateLabel: 'August 19, 2026',
    rows: 5,
    cols: 5,
    themes: ['Shades of red'],
    columns: ['RABUT', 'CYLER', 'SIECK', 'SBRLR', 'ORAOC'],
    owners: ['11001', '10110', '14344', '34224', '33222'],
    words: ['RUBY', 'SCARLET', 'CORAL', 'ROSE', 'BRICK'],
    tier: 2,
    minZipf: 3.64,
    pool: ['CRIMSON', 'SCARLET', 'RUBY', 'CORAL', 'CARMINE', 'MAROON', 'GARNET', 'BRICK', 'ROSE', 'BLUSH', 'CHERRY'],
    opening: 2,
    deepest: 3,
  },
  {
    num: 15,
    quizId: 'strata-8-20-26',
    live: '2026-08-20',
    dateLabel: 'August 20, 2026',
    rows: 5,
    cols: 5,
    themes: ['In the kitchen'],
    columns: ['NNEEB', 'DERLV', 'POOON', 'OBKES', 'WNIFL'],
    owners: ['32232', '22223', '43444', '11004', '10001'],
    words: ['KNIFE', 'BOWL', 'BLENDER', 'OVEN', 'SPOON'],
    tier: 1,
    minZipf: 3.43,
    pool: ['KNIFE', 'SPOON', 'PLATE', 'BOWL', 'KETTLE', 'OVEN', 'FRIDGE', 'TOASTER', 'BLENDER', 'WHISK', 'SAUCER', 'TEAPOT'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 16,
    quizId: 'strata-8-21-26',
    live: '2026-08-21',
    dateLabel: 'August 21, 2026',
    rows: 5,
    cols: 5,
    themes: ['Fish'],
    columns: ['RIHAB', 'RENGS', 'USTHN', 'UTATC', 'ORPER'],
    owners: ['11122', '11112', '42304', '33440', '33000'],
    words: ['PERCH', 'HERRING', 'BASS', 'TROUT', 'TUNA'],
    tier: 2,
    minZipf: 3.29,
    pool: ['TROUT', 'SALMON', 'TUNA', 'PERCH', 'BASS', 'PIKE', 'CARP', 'MULLET', 'HERRING', 'MACKEREL', 'SARDINE', 'HALIBUT'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 17,
    quizId: 'strata-8-22-26',
    live: '2026-08-22',
    dateLabel: 'August 22, 2026',
    rows: 5,
    cols: 5,
    themes: ['Flowers'],
    columns: ['SIYSA', 'LAIER', 'AIDTA', 'ZLUCP', 'ILLAI'],
    owners: ['11003', '30031', '31042', '32424', '22434'],
    words: ['DAISY', 'IRIS', 'LILAC', 'AZALEA', 'TULIP'],
    tier: 2,
    minZipf: 3.05,
    pool: ['TULIP', 'DAHLIA', 'PEONY', 'ORCHID', 'LILAC', 'IRIS', 'ASTER', 'POPPY', 'DAISY', 'AZALEA', 'VIOLET', 'JASMINE'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 18,
    quizId: 'strata-8-23-26',
    live: '2026-08-23',
    dateLabel: 'August 23, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Bones', 'Knots'],
    columns: ['YNNAEHT', 'RETRSPF', 'EIBDGLM', 'LRNECUL', 'UIUESED', 'SERKFAR'],
    owners: ['0000111', '1110334', '4322034', '5422345', '7753567', '7665677'],
    words: ['GRANNY', 'TETHER', 'BEND', 'SPLICE', 'FEMUR', 'SKULL', 'REEF', 'RADIUS'],
    tier: 3,
    minZipf: 2.87,
    pool: ['FEMUR', 'TIBIA', 'FIBULA', 'RADIUS', 'SCAPULA', 'PATELLA', 'SACRUM', 'CARPAL', 'SKULL', 'STERNUM', 'CLOVE', 'HITCH', 'REEF', 'GRANNY', 'TIMBER', 'BEND', 'SPLICE', 'LANYARD', 'TETHER'],
    opening: 2,
    deepest: 7,
  },
  {
    num: 19,
    quizId: 'strata-8-24-26',
    live: '2026-08-24',
    dateLabel: 'August 24, 2026',
    rows: 5,
    cols: 5,
    themes: ['Body parts'],
    columns: ['EEKBT', 'MERHN', 'EETUV', 'LMIRS', 'PLWIT'],
    owners: ['33344', '42243', '11142', '11200', '12000'],
    words: ['WRIST', 'TEMPLE', 'LIVER', 'KNEE', 'THUMB'],
    tier: 1,
    minZipf: 4.01,
    pool: ['ELBOW', 'WRIST', 'ANKLE', 'THIGH', 'SHOULDER', 'FINGER', 'THUMB', 'KNEE', 'HEART', 'LIVER', 'SPLEEN', 'TEMPLE', 'STOMACH'],
    opening: 2,
    deepest: 3,
  },
  {
    num: 20,
    quizId: 'strata-8-25-26',
    live: '2026-08-25',
    dateLabel: 'August 25, 2026',
    rows: 5,
    cols: 5,
    themes: ['Ways to travel'],
    columns: ['RYGAW', 'BRNYO', 'FEUWA', 'ASTTK', 'RXIUC'],
    owners: ['00222', '10212', '00111', '31344', '43344'],
    words: ['FERRY', 'SUBWAY', 'WAGON', 'TAXI', 'TRUCK'],
    tier: 1,
    minZipf: 3.9,
    pool: ['TRUCK', 'TRAIN', 'PLANE', 'BOAT', 'BIKE', 'SHIP', 'TAXI', 'FERRY', 'WAGON', 'SCOOTER', 'TRACTOR', 'SUBWAY', 'CANOE'],
    opening: 1,
    deepest: 3,
  },
  {
    num: 21,
    quizId: 'strata-8-26-26',
    live: '2026-08-26',
    dateLabel: 'August 26, 2026',
    rows: 5,
    cols: 5,
    themes: ['Drinks'],
    columns: ['WVIEA', 'KDOON', 'CIHWA', 'BSRCO', 'EKEYE'],
    owners: ['31334', '11143', '40001', '20244', '20002'],
    words: ['WHISKEY', 'VODKA', 'BEER', 'WINE', 'COCOA'],
    tier: 1,
    minZipf: 3.64,
    pool: ['WATER', 'COFFEE', 'JUICE', 'CIDER', 'LEMONADE', 'COCOA', 'BRANDY', 'WHISKEY', 'SHERRY', 'VODKA', 'WINE', 'BEER'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 22,
    quizId: 'strata-8-27-26',
    live: '2026-08-27',
    dateLabel: 'August 27, 2026',
    rows: 5,
    cols: 5,
    themes: ['Chess'],
    columns: ['EECEN', 'CUPHQ', 'OBHOK', 'DASKF', 'RIROB'],
    owners: ['43344', '34234', '11223', '11200', '12002'],
    words: ['FORK', 'BOARD', 'BISHOP', 'CHECK', 'QUEEN'],
    tier: 2,
    minZipf: 4.03,
    pool: ['ROOK', 'BISHOP', 'KNIGHT', 'QUEEN', 'GAMBIT', 'FORK', 'SKEWER', 'CASTLE', 'ENDGAME', 'CHECK', 'BOARD'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 23,
    quizId: 'strata-8-28-26',
    live: '2026-08-28',
    dateLabel: 'August 28, 2026',
    rows: 5,
    cols: 5,
    themes: ['Golf'],
    columns: ['SICEE', 'LNIDL', 'ROGAR', 'REIWG', 'EEVDE'],
    owners: ['00002', '01132', '11223', '32344', '43344'],
    words: ['SLICE', 'IRON', 'EAGLE', 'DRIVER', 'WEDGE'],
    tier: 2,
    minZipf: 3.62,
    pool: ['BIRDIE', 'EAGLE', 'BOGEY', 'PUTT', 'DRIVER', 'WEDGE', 'FAIRWAY', 'BUNKER', 'CADDIE', 'IRON', 'SLICE'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 24,
    quizId: 'strata-8-29-26',
    live: '2026-08-29',
    dateLabel: 'August 29, 2026',
    rows: 5,
    cols: 5,
    themes: ['Theater'],
    columns: ['PSNGS', 'WSUIO', 'RHERE', 'SPOCG', 'ATRAT'],
    owners: ['22111', '10012', '20004', '42334', '43334'],
    words: ['USHER', 'WINGS', 'PROPS', 'ACTOR', 'STAGE'],
    tier: 2,
    minZipf: 3.51,
    pool: ['STAGE', 'CURTAIN', 'SCRIPT', 'ACTOR', 'WINGS', 'PROPS', 'USHER', 'BALCONY', 'ENCORE', 'MATINEE', 'CHORUS', 'PROMPT'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 25,
    quizId: 'strata-8-30-26',
    live: '2026-08-30',
    dateLabel: 'August 30, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Ancient Rome', 'Printing'],
    columns: ['GIOERPR', 'SLLOFIA', 'LRAGSMN', 'ORYCTOE', 'EOMEHIC', 'PSAIMAR'],
    owners: ['6445556', '5344466', '3233566', '2230003', '2112001', '2111200'],
    words: ['CHARIOT', 'MOSAIC', 'EMPEROR', 'GALLEY', 'FOLIO', 'PRESS', 'MARGIN'],
    tier: 3,
    minZipf: 3.11,
    pool: ['TOGA', 'FORUM', 'LEGION', 'SENATE', 'COLUMN', 'CHARIOT', 'VILLA', 'ARENA', 'MOSAIC', 'TUNIC', 'EMPEROR', 'SERIF', 'GALLEY', 'FOLIO', 'QUARTO', 'INKWELL', 'PRESS', 'TYPEFACE', 'MARGIN'],
    opening: 2,
    deepest: 6,
  },
  {
    num: 26,
    quizId: 'strata-8-31-26',
    live: '2026-08-31',
    dateLabel: 'August 31, 2026',
    rows: 5,
    cols: 5,
    themes: ['Furniture'],
    columns: ['IHCLM', 'ERNFR', 'HSOEB', 'RUOHD', 'KSECC'],
    owners: ['20012', '12012', '11200', '24443', '33344'],
    words: ['BENCH', 'SHELF', 'MIRROR', 'DESK', 'COUCH'],
    tier: 1,
    minZipf: 4.02,
    pool: ['CHAIR', 'TABLE', 'SOFA', 'DESK', 'SHELF', 'STOOL', 'BENCH', 'LAMP', 'MIRROR', 'COUCH', 'DRESSER', 'CABINET', 'CUPBOARD'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 27,
    quizId: 'strata-9-1-26',
    live: '2026-09-01',
    dateLabel: 'September 1, 2026',
    rows: 5,
    cols: 5,
    themes: ['Farm animals'],
    columns: ['GKTUO', 'BEROR', 'ABYSE', 'GITBT', 'MALAO'],
    owners: ['10001', '20012', '22011', '42234', '33344'],
    words: ['TURKEY', 'GOOSE', 'RABBIT', 'LAMB', 'GOAT'],
    tier: 1,
    minZipf: 3.84,
    pool: ['HORSE', 'SHEEP', 'GOAT', 'DUCK', 'GOOSE', 'DONKEY', 'RABBIT', 'CHICKEN', 'CATTLE', 'LAMB', 'CALF', 'FOAL', 'TURKEY'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 28,
    quizId: 'strata-9-2-26',
    live: '2026-09-02',
    dateLabel: 'September 2, 2026',
    rows: 5,
    cols: 5,
    themes: ['Shades of red'],
    columns: ['SIRCR', 'CKOBA', 'SBRYT', 'UCELE', 'ORRAL'],
    owners: ['10013', '00301', '32121', '24311', '42444'],
    words: ['BRICK', 'SCARLET', 'RUBY', 'ROSE', 'CORAL'],
    tier: 2,
    minZipf: 3.64,
    pool: ['CRIMSON', 'SCARLET', 'RUBY', 'CORAL', 'CARMINE', 'MAROON', 'GARNET', 'BRICK', 'ROSE', 'BLUSH', 'CHERRY'],
    opening: 1,
    deepest: 3,
  },
  {
    num: 29,
    quizId: 'strata-9-3-26',
    live: '2026-09-03',
    dateLabel: 'September 3, 2026',
    rows: 5,
    cols: 5,
    themes: ['At the beach'],
    columns: ['IEDFS', 'RTUER', 'CRASO', 'AMHDB', 'PSANL'],
    owners: ['43455', '34545', '22233', '11302', '10001'],
    words: ['SAND', 'PALM', 'CRAB', 'SHORE', 'TIDE', 'SURF'],
    tier: 1,
    minZipf: 3.76,
    pool: ['SAND', 'WAVES', 'SHELL', 'TOWEL', 'SURF', 'TIDE', 'OCEAN', 'PALM', 'CRAB', 'DUNE', 'SHORE', 'PEBBLE', 'SEAWEED'],
    opening: 1,
    deepest: 5,
  },
  {
    num: 30,
    quizId: 'strata-9-4-26',
    live: '2026-09-04',
    dateLabel: 'September 4, 2026',
    rows: 5,
    cols: 5,
    themes: ['Big cats'],
    columns: ['ARUJA', 'GTRGO', 'UIGEC', 'IANUA', 'ORPML'],
    owners: ['11122', '20011', '20001', '42433', '42334'],
    words: ['TIGER', 'COUGAR', 'JAGUAR', 'PUMA', 'LION'],
    tier: 2,
    minZipf: 3.22,
    pool: ['LION', 'TIGER', 'LEOPARD', 'JAGUAR', 'CHEETAH', 'COUGAR', 'PUMA', 'LYNX', 'OCELOT', 'PANTHER', 'BOBCAT'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 31,
    quizId: 'strata-9-5-26',
    live: '2026-09-05',
    dateLabel: 'September 5, 2026',
    rows: 5,
    cols: 5,
    themes: ['Fish'],
    columns: ['PNRAC', 'NAGTU', 'ONREM', 'BIRLH', 'AASSS'],
    owners: ['43444', '13033', '10001', '20010', '21122'],
    words: ['HERRING', 'SALMON', 'BASS', 'TUNA', 'CARP'],
    tier: 2,
    minZipf: 3.18,
    pool: ['TROUT', 'SALMON', 'TUNA', 'PERCH', 'BASS', 'PIKE', 'CARP', 'MULLET', 'HERRING', 'MACKEREL', 'SARDINE', 'HALIBUT'],
    opening: 2,
    deepest: 3,
  },
  {
    num: 32,
    quizId: 'strata-9-6-26',
    live: '2026-09-06',
    dateLabel: 'September 6, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Birds of prey', 'Kitchen tools'],
    columns: ['IGESREO', 'ALKLYPS', 'EVLARDE', 'EBZZISE', 'TSTEARU', 'CGNOLVE'],
    owners: ['6446555', '4466555', '3362224', '3222336', '6001112', '1000111'],
    words: ['TONGS', 'CLEAVER', 'BUZZARD', 'SIEVE', 'EAGLE', 'OSPREY', 'SKILLET'],
    tier: 3,
    minZipf: 2.8,
    pool: ['EAGLE', 'HAWK', 'FALCON', 'KESTREL', 'OSPREY', 'HARRIER', 'BUZZARD', 'CONDOR', 'VULTURE', 'MERLIN', 'WHISK', 'LADLE', 'SPATULA', 'GRATER', 'PEELER', 'SIEVE', 'TONGS', 'MASHER', 'SKILLET', 'CLEAVER', 'MORTAR'],
    opening: 3,
    deepest: 5,
  },
  {
    num: 33,
    quizId: 'strata-9-7-26',
    live: '2026-09-07',
    dateLabel: 'September 7, 2026',
    rows: 5,
    cols: 5,
    themes: ['Colors'],
    columns: ['LEYEN', 'LOREW', 'EGPIK', 'GLNUR', 'BANEO'],
    owners: ['11100', '11001', '40222', '43234', '34434'],
    words: ['GREEN', 'YELLOW', 'PINK', 'BLUE', 'ORANGE'],
    tier: 1,
    minZipf: 4.52,
    pool: ['BLUE', 'GREEN', 'BLACK', 'WHITE', 'BROWN', 'PINK', 'PURPLE', 'ORANGE', 'SILVER', 'GOLDEN', 'YELLOW', 'SCARLET', 'VIOLET', 'CREAM', 'CRIMSON'],
    opening: 1,
    deepest: 3,
  },
  {
    num: 34,
    quizId: 'strata-9-8-26',
    live: '2026-09-08',
    dateLabel: 'September 8, 2026',
    rows: 5,
    cols: 5,
    themes: ['Bathroom'],
    columns: ['UROOS', 'STABW', 'EHWPR', 'ELNSO', 'SHIAB'],
    owners: ['11200', '12012', '21404', '42334', '44333'],
    words: ['SOAP', 'BRUSH', 'TOWEL', 'BASIN', 'SHOWER'],
    tier: 1,
    minZipf: 3.94,
    pool: ['TOWEL', 'SOAP', 'MIRROR', 'SHOWER', 'BRUSH', 'RAZOR', 'SPONGE', 'TOILET', 'BASIN', 'COMB', 'SHAMPOO'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 35,
    quizId: 'strata-9-9-26',
    live: '2026-09-09',
    dateLabel: 'September 9, 2026',
    rows: 5,
    cols: 5,
    themes: ['Body parts'],
    columns: ['AETNE', 'TLMKL', 'PNSBE', 'KIEMH', 'WRUET'],
    owners: ['43344', '13344', '30123', '01022', '11202'],
    words: ['KNEE', 'WRIST', 'THUMB', 'TEMPLE', 'ANKLE'],
    tier: 1,
    minZipf: 3.97,
    pool: ['ELBOW', 'WRIST', 'ANKLE', 'THIGH', 'SHOULDER', 'FINGER', 'THUMB', 'KNEE', 'HEART', 'LIVER', 'SPLEEN', 'TEMPLE', 'STOMACH'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 36,
    quizId: 'strata-9-10-26',
    live: '2026-09-10',
    dateLabel: 'September 10, 2026',
    rows: 5,
    cols: 5,
    themes: ['Fabrics'],
    columns: ['OWVAC', 'ONLAS', 'NLSKI', 'LONNO', 'CITET'],
    owners: ['22444', '24343', '12433', '01001', '10101'],
    words: ['LINEN', 'COTTON', 'WOOL', 'SILK', 'CANVAS'],
    tier: 2,
    minZipf: 3.61,
    pool: ['LINEN', 'SILK', 'DENIM', 'VELVET', 'SATIN', 'TWEED', 'COTTON', 'CANVAS', 'CHIFFON', 'FLANNEL', 'MUSLIN', 'SUEDE', 'WOOL'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 37,
    quizId: 'strata-9-11-26',
    live: '2026-09-11',
    dateLabel: 'September 11, 2026',
    rows: 5,
    cols: 5,
    themes: ['Chess'],
    columns: ['HKEBI', 'OCSHC', 'OPBRO', 'NAKFE', 'RDEQU'],
    owners: ['10011', '10100', '31322', '43224', '33444'],
    words: ['CHECK', 'BISHOP', 'FORK', 'BOARD', 'QUEEN'],
    tier: 2,
    minZipf: 4.03,
    pool: ['ROOK', 'BISHOP', 'KNIGHT', 'QUEEN', 'GAMBIT', 'FORK', 'SKEWER', 'CASTLE', 'ENDGAME', 'CHECK', 'BOARD'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 38,
    quizId: 'strata-9-12-26',
    live: '2026-09-12',
    dateLabel: 'September 12, 2026',
    rows: 5,
    cols: 5,
    themes: ['Theater'],
    columns: ['POPSN', 'IRGTS', 'ECWOR', 'GUAHS', 'ASERT'],
    owners: ['00002', '20212', '41211', '43134', '43334'],
    words: ['PROPS', 'ACTOR', 'WINGS', 'USHER', 'STAGE'],
    tier: 2,
    minZipf: 3.51,
    pool: ['STAGE', 'CURTAIN', 'SCRIPT', 'ACTOR', 'WINGS', 'PROPS', 'USHER', 'BALCONY', 'ENCORE', 'MATINEE', 'CHORUS', 'PROMPT'],
    opening: 1,
    deepest: 3,
  },
  {
    num: 39,
    quizId: 'strata-9-13-26',
    live: '2026-09-13',
    dateLabel: 'September 13, 2026',
    sunday: true,
    rows: 7,
    cols: 6,
    themes: ['Sea creatures', 'Printing'],
    columns: ['WYLEOEL', 'GAHEAIL', 'FECAQLI', 'TPSOUFD', 'PSOYSLW', 'UOTCRUA'],
    owners: ['4644566', '6242456', '2226353', '2235353', '1112000', '1111000'],
    words: ['WALRUS', 'OCTOPUS', 'TYPEFACE', 'SQUID', 'WHALE', 'FOLIO', 'GALLEY'],
    tier: 3,
    minZipf: 2.85,
    pool: ['OCTOPUS', 'SQUID', 'CORAL', 'URCHIN', 'MANTA', 'WHALE', 'WALRUS', 'LOBSTER', 'PRAWN', 'MUSSEL', 'OYSTER', 'SERIF', 'GALLEY', 'FOLIO', 'QUARTO', 'INKWELL', 'PRESS', 'TYPEFACE', 'MARGIN'],
    opening: 2,
    deepest: 5,
  },
  {
    num: 40,
    quizId: 'strata-9-14-26',
    live: '2026-09-14',
    dateLabel: 'September 14, 2026',
    rows: 5,
    cols: 5,
    themes: ['Clothing'],
    columns: ['OESAJ', 'SAHKC', 'JENSE', 'OTTRS', 'CDAES'],
    owners: ['11122', '10122', '00002', '42433', '43433'],
    words: ['JEANS', 'SHOES', 'JACKET', 'DRESS', 'COAT'],
    tier: 1,
    minZipf: 4.09,
    pool: ['SHIRT', 'DRESS', 'COAT', 'SKIRT', 'JEANS', 'SOCKS', 'SCARF', 'GLOVE', 'BOOTS', 'BELT', 'JACKET', 'SWEATER', 'SHOES', 'BLOUSE'],
    opening: 1,
    deepest: 4,
  },
  {
    num: 41,
    quizId: 'strata-9-15-26',
    live: '2026-09-15',
    dateLabel: 'September 15, 2026',
    rows: 5,
    cols: 5,
    themes: ['Weather'],
    columns: ['SRDFW', 'TOENI', 'WRANR', 'EOIEH', 'ZESRB'],
    owners: ['33232', '33422', '40004', '14014', '11411'],
    words: ['RAIN', 'BREEZE', 'WIND', 'FROST', 'SHOWER'],
    tier: 1,
    minZipf: 3.86,
    pool: ['RAIN', 'SNOW', 'HAIL', 'STORM', 'FROST', 'WIND', 'CLOUD', 'THUNDER', 'BREEZE', 'DRIZZLE', 'GALE', 'THAW', 'MIST', 'SLEET', 'SHOWER', 'SUNSHINE'],
    opening: 2,
    deepest: 4,
  },
  {
    num: 42,
    quizId: 'strata-9-16-26',
    live: '2026-09-16',
    dateLabel: 'September 16, 2026',
    rows: 5,
    cols: 5,
    themes: ['Furniture'],
    columns: ['MESAL', 'DRPKA', 'ROFRS', 'IBCON', 'AMIET'],
    owners: ['10011', '03102', '33232', '34424', '43444'],
    words: ['DESK', 'LAMP', 'SOFA', 'MIRROR', 'CABINET'],
    tier: 1,
    minZipf: 3.81,
    pool: ['CHAIR', 'TABLE', 'SOFA', 'DESK', 'SHELF', 'STOOL', 'BENCH', 'LAMP', 'MIRROR', 'COUCH', 'DRESSER', 'CABINET', 'CUPBOARD'],
    opening: 1,
    deepest: 3,
  },
];
