// Question bank for Deep, the daily single-topic trivia dive. Imported ONLY by
// the server page (app/deep/page.js), which resolves the picked day's fifteen
// questions and hands the client just that day, so the rest of the bank never
// reaches a browser.
//
//   id       'd<day>q<slot>' — authored day and play order (slot 1..15)
//   tier     1 (gimme) .. 5 (deepest); a day ramps 3 questions per tier, all on
//            the SAME topic, named on the day's puzzle entry
//   choices  exactly four, one defensibly correct; the correct position came
//            from a per-day balanced no-3-run sequence at build time, so do NOT
//            hand-reorder choices here
//
// Facts are evergreen general knowledge, verified at authoring time
// (2026-08-07). Extending the bank: author new days in the same shape (one
// topic, 3 questions per tier, easy to deepest), rebuild, and run
// scripts/verify-deep.mjs. Never reuse an id or repeat a question.
export const QUESTIONS = [
  { id: 'd01q01', tier: 1, q: 'According to legend, which pair of twin brothers founded the city on the Tiber?', choices: ['Romulus and Remus', 'Tiberius and Gaius', 'Aeneas and Ascanius', 'Castor and Pollux'], correct: 0 },
  { id: 'd01q02', tier: 1, q: 'What were the armed fighters who battled for public entertainment in the arena called?', choices: ['Centurions', 'Gladiators', 'Legates', 'Praetorians'], correct: 1 },
  { id: 'd01q03', tier: 1, q: 'The Colosseum stands in which modern country?', choices: ['Turkey', 'Spain', 'Italy', 'Greece'], correct: 2 },
  { id: 'd01q04', tier: 2, q: 'Which volcano buried Pompeii in AD 79?', choices: ['Vulcano', 'Stromboli', 'Vesuvius', 'Etna'], correct: 2 },
  { id: 'd01q05', tier: 2, q: 'Who is counted as the first emperor?', choices: ['Nero', 'Tiberius', 'Julius Caesar', 'Augustus'], correct: 3 },
  { id: 'd01q06', tier: 2, q: 'Which Carthaginian general famously crossed the Alps with war elephants?', choices: ['Mago', 'Hannibal', 'Hasdrubal', 'Hamilcar'], correct: 1 },
  { id: 'd01q07', tier: 3, q: 'Which emperor built the fortified wall across northern Britain?', choices: ['Trajan', 'Claudius', 'Septimius Severus', 'Hadrian'], correct: 3 },
  { id: 'd01q08', tier: 3, q: 'The Edict of Milan in 313 legalized Christianity under which emperor?', choices: ['Constantine', 'Diocletian', 'Justinian', 'Theodosius'], correct: 0 },
  { id: 'd01q09', tier: 3, q: 'A legion at full imperial strength numbered roughly how many men?', choices: ['About 500', 'About 50,000', 'About 5,000', 'About 20,000'], correct: 2 },
  { id: 'd01q10', tier: 4, q: 'Which emperor split the empire into a tetrarchy of four rulers?', choices: ['Aurelian', 'Diocletian', 'Gallienus', 'Valerian'], correct: 1 },
  { id: 'd01q11', tier: 4, q: 'The Third Punic War ended with the destruction of which city?', choices: ['Numantia', 'Syracuse', 'Corinth', 'Carthage'], correct: 3 },
  { id: 'd01q12', tier: 4, q: 'In AD 9 a Germanic ambush annihilated three legions under which commander?', choices: ['Germanicus', 'Varus', 'Agrippa', 'Drusus'], correct: 1 },
  { id: 'd01q13', tier: 5, q: 'Whose death in 180 is often taken as the end of the Pax Romana?', choices: ['Marcus Aurelius', 'Antoninus Pius', 'Commodus', 'Lucius Verus'], correct: 0 },
  { id: 'd01q14', tier: 5, q: 'Which year is conventionally given for the fall of the Western empire?', choices: ['476', '493', '455', '410'], correct: 0 },
  { id: 'd01q15', tier: 5, q: 'Which great republican road ran from the capital south to Brundisium?', choices: ['The Via Flaminia', 'The Via Egnatia', 'The Appian Way', 'The Via Aurelia'], correct: 2 },
  { id: 'd02q01', tier: 1, q: 'Which planet do we live on?', choices: ['Mercury', 'Venus', 'Earth', 'Mars'], correct: 2 },
  { id: 'd02q02', tier: 1, q: 'Which planet is known as the Red Planet?', choices: ['Neptune', 'Mars', 'Venus', 'Jupiter'], correct: 1 },
  { id: 'd02q03', tier: 1, q: 'What object sits at the center of our system?', choices: ['Jupiter', 'Polaris', 'The Sun', 'The Moon'], correct: 2 },
  { id: 'd02q04', tier: 2, q: 'Which planet is the largest?', choices: ['Uranus', 'Neptune', 'Saturn', 'Jupiter'], correct: 3 },
  { id: 'd02q05', tier: 2, q: 'Which planet orbits closest to the Sun?', choices: ['Mercury', 'Earth', 'Mars', 'Venus'], correct: 0 },
  { id: 'd02q06', tier: 2, q: 'Which planet is famous for its bright ring system?', choices: ['Neptune', 'Jupiter', 'Uranus', 'Saturn'], correct: 3 },
  { id: 'd02q07', tier: 3, q: 'Which planet is the hottest at its surface?', choices: ['Jupiter', 'Mercury', 'Venus', 'Mars'], correct: 2 },
  { id: 'd02q08', tier: 3, q: 'What is the name of the largest moon of Saturn?', choices: ['Enceladus', 'Rhea', 'Iapetus', 'Titan'], correct: 3 },
  { id: 'd02q09', tier: 3, q: 'Where does the asteroid belt lie?', choices: ['Between Mars and Jupiter', 'Between Jupiter and Saturn', 'Beyond Neptune', 'Between Earth and Mars'], correct: 0 },
  { id: 'd02q10', tier: 4, q: 'Which moon of Jupiter is the most volcanically active body known?', choices: ['Ganymede', 'Io', 'Europa', 'Callisto'], correct: 1 },
  { id: 'd02q11', tier: 4, q: 'Which planet rotates on its side, tipped nearly a right angle to its orbit?', choices: ['Venus', 'Neptune', 'Uranus', 'Saturn'], correct: 2 },
  { id: 'd02q12', tier: 4, q: 'Roughly how long does sunlight take to reach us?', choices: ['About 8 seconds', 'About 80 seconds', 'About 8 hours', 'About 8 minutes'], correct: 3 },
  { id: 'd02q13', tier: 5, q: 'Which dwarf planet is the largest object in the asteroid belt?', choices: ['Juno', 'Ceres', 'Vesta', 'Pallas'], correct: 1 },
  { id: 'd02q14', tier: 5, q: 'What name is given to the distant spherical cloud of icy bodies thought to source long-period comets?', choices: ['The Oort cloud', 'The Kuiper belt', 'The heliosheath', 'The Hills sphere'], correct: 0 },
  { id: 'd02q15', tier: 5, q: 'Which moon of Neptune orbits backwards, against its planet’s spin?', choices: ['Triton', 'Proteus', 'Larissa', 'Nereid'], correct: 0 },
  { id: 'd03q01', tier: 1, q: 'Which play features the star-crossed lovers of Verona?', choices: ['The Tempest', 'Romeo and Juliet', 'King Lear', 'Twelfth Night'], correct: 1 },
  { id: 'd03q02', tier: 1, q: 'In which English town was the playwright born?', choices: ['York', 'Canterbury', 'Bath', 'Stratford-upon-Avon'], correct: 3 },
  { id: 'd03q03', tier: 1, q: 'Which Danish prince asks whether to be or not to be?', choices: ['Horatio', 'Hamlet', 'Laertes', 'Fortinbras'], correct: 1 },
  { id: 'd03q04', tier: 2, q: 'Which play is set in Scotland and turns on three witches’ prophecy?', choices: ['Pericles', 'Cymbeline', 'Coriolanus', 'Macbeth'], correct: 3 },
  { id: 'd03q05', tier: 2, q: 'Which London playhouse was most associated with his company?', choices: ['The Globe', 'The Rose', 'The Curtain', 'The Swan'], correct: 0 },
  { id: 'd03q06', tier: 2, q: 'Which Moorish general is destroyed by Iago’s scheming?', choices: ['Antony', 'Timon', 'Othello', 'Titus'], correct: 2 },
  { id: 'd03q07', tier: 3, q: 'How many lines does a standard sonnet of his have?', choices: ['20', '16', '12', '14'], correct: 3 },
  { id: 'd03q08', tier: 3, q: 'Which comedy features the fairy king Oberon and the mischievous Puck?', choices: ['The Winter’s Tale', 'As You Like It', 'Much Ado About Nothing', 'A Midsummer Night’s Dream'], correct: 3 },
  { id: 'd03q09', tier: 3, q: 'Which play opens with a shipwreck conjured by the magician Prospero?', choices: ['The Tempest', 'The Comedy of Errors', 'Pericles', 'Cymbeline'], correct: 0 },
  { id: 'd03q10', tier: 4, q: 'What is the metrical name for the unrhymed five-beat line he wrote in?', choices: ['Alexandrine', 'Blank verse', 'Heroic couplet', 'Free verse'], correct: 1 },
  { id: 'd03q11', tier: 4, q: 'Which acting company did he belong to before it was renamed the King’s Men?', choices: ['Queen Anne’s Men', 'The Lord Chamberlain’s Men', 'The Admiral’s Men', 'The Children of the Chapel'], correct: 1 },
  { id: 'd03q12', tier: 4, q: 'Which fat knight appears in the Henry IV plays and The Merry Wives of Windsor?', choices: ['Bottom', 'Malvolio', 'Falstaff', 'Dogberry'], correct: 2 },
  { id: 'd03q13', tier: 5, q: 'What is the name of the 1623 collected edition of his plays?', choices: ['The First Folio', 'The Quarto Miscellany', 'The Stationers’ Register', 'The Bankside Edition'], correct: 0 },
  { id: 'd03q14', tier: 5, q: 'Which of his tragedies is set in Rome and features the Andronicus family?', choices: ['Titus Andronicus', 'Antony and Cleopatra', 'Julius Caesar', 'Coriolanus'], correct: 0 },
  { id: 'd03q15', tier: 5, q: 'Which stage direction, from The Winter’s Tale, is the most famous he ever wrote?', choices: ['A storm, and thunder within', 'Alarum. Enter the ghost', 'Exit, pursued by a bear', 'They fight, and die'], correct: 2 },
  { id: 'd04q01', tier: 1, q: 'How many interlocking rings appear on the flag?', choices: ['Seven', 'Six', 'Five', 'Four'], correct: 2 },
  { id: 'd04q02', tier: 1, q: 'Which country hosted the first modern Games in 1896?', choices: ['Britain', 'France', 'Italy', 'Greece'], correct: 3 },
  { id: 'd04q03', tier: 1, q: 'What metal is the medal for third place?', choices: ['Copper', 'Bronze', 'Gold', 'Silver'], correct: 1 },
  { id: 'd04q04', tier: 2, q: 'What is lit at the start and burns for the duration of the Games?', choices: ['The founder’s torch', 'The laurel lantern', 'The victory beacon', 'The cauldron flame'], correct: 3 },
  { id: 'd04q05', tier: 2, q: 'How many years normally separate one Summer Games from the next?', choices: ['Three', 'Two', 'Five', 'Four'], correct: 3 },
  { id: 'd04q06', tier: 2, q: 'Which sprinter and long jumper won four golds at the 1936 Berlin Games?', choices: ['Harrison Dillard', 'Jesse Owens', 'Ralph Metcalfe', 'Carl Lewis'], correct: 1 },
  { id: 'd04q07', tier: 3, q: 'In which city were the first Winter Games held in 1924?', choices: ['St. Moritz', 'Chamonix', 'Lake Placid', 'Garmisch-Partenkirchen'], correct: 1 },
  { id: 'd04q08', tier: 3, q: 'Which swimmer won eight golds at a single Games in 2008?', choices: ['Ryan Lochte', 'Mark Spitz', 'Ian Thorpe', 'Michael Phelps'], correct: 3 },
  { id: 'd04q09', tier: 3, q: 'Which gymnast scored the first perfect ten in 1976?', choices: ['Nadia Comaneci', 'Olga Korbut', 'Vera Caslavska', 'Ludmilla Tourischeva'], correct: 0 },
  { id: 'd04q10', tier: 4, q: 'Who founded the modern Games and led the movement from 1896?', choices: ['Demetrios Vikelas', 'Henri de Baillet-Latour', 'Pierre de Coubertin', 'Avery Brundage'], correct: 2 },
  { id: 'd04q11', tier: 4, q: 'The Latin motto Citius, Altius, Fortius translates as what?', choices: ['Faster, Higher, Stronger', 'Farther, Longer, Harder', 'Swifter, Braver, Truer', 'Bolder, Faster, Prouder'], correct: 0 },
  { id: 'd04q12', tier: 4, q: 'Which city hosted the 1968 Summer Games at high altitude?', choices: ['Mexico City', 'La Paz', 'Quito', 'Bogota'], correct: 0 },
  { id: 'd04q13', tier: 5, q: 'Which three Games were cancelled outright by the two world wars?', choices: ['1914, 1940 and 1944', '1916, 1940 and 1944', '1916, 1940 and 1948', '1916, 1936 and 1944'], correct: 1 },
  { id: 'd04q14', tier: 5, q: 'Which sport joined the Summer program in 1964 in Tokyo and has stayed since?', choices: ['Judo', 'Handball', 'Badminton', 'Taekwondo'], correct: 0 },
  { id: 'd04q15', tier: 5, q: 'Which city hosted the Summer Games twice in the 20th century and again in 2012?', choices: ['Los Angeles', 'Athens', 'London', 'Paris'], correct: 2 },
  { id: 'd05q01', tier: 1, q: 'Which river runs the length of the country and made farming possible?', choices: ['The Tigris', 'The Euphrates', 'The Nile', 'The Jordan'], correct: 2 },
  { id: 'd05q02', tier: 1, q: 'What is the title of the king who ruled the ancient kingdom?', choices: ['Sultan', 'Satrap', 'Pharaoh', 'Caliph'], correct: 2 },
  { id: 'd05q03', tier: 1, q: 'What great limestone monument with a lion’s body and a human head guards Giza?', choices: ['The Obelisk of Ra', 'The Sphinx', 'The Great Cat', 'The Colossus'], correct: 1 },
  { id: 'd05q04', tier: 2, q: 'Whose largely intact tomb did Howard Carter open in 1922?', choices: ['Tutankhamun', 'Seti I', 'Akhenaten', 'Ramesses II'], correct: 0 },
  { id: 'd05q05', tier: 2, q: 'What is the picture-based writing system called?', choices: ['Hieroglyphs', 'Runes', 'Linear B', 'Cuneiform'], correct: 0 },
  { id: 'd05q06', tier: 2, q: 'What was the preserved, wrapped body of the dead called?', choices: ['A cartouche', 'A mummy', 'A sarcophagus', 'A reliquary'], correct: 1 },
  { id: 'd05q07', tier: 3, q: 'Which stone, found in 1799, unlocked the ancient script?', choices: ['The Palermo Stone', 'The Narmer Palette', 'The Merneptah Stele', 'The Rosetta Stone'], correct: 3 },
  { id: 'd05q08', tier: 3, q: 'Which pharaoh built the temples at Abu Simbel?', choices: ['Amenhotep III', 'Ramesses II', 'Khufu', 'Thutmose III'], correct: 1 },
  { id: 'd05q09', tier: 3, q: 'Which god of the dead is shown with the head of a jackal?', choices: ['Sobek', 'Horus', 'Thoth', 'Anubis'], correct: 3 },
  { id: 'd05q10', tier: 4, q: 'Which pharaoh abandoned the old gods for the sun disc Aten?', choices: ['Menkaure', 'Akhenaten', 'Djoser', 'Hatshepsut'], correct: 1 },
  { id: 'd05q11', tier: 4, q: 'Which queen ruled as pharaoh and built a terraced temple at Deir el-Bahari?', choices: ['Hatshepsut', 'Cleopatra VII', 'Nefertiti', 'Nefertari'], correct: 0 },
  { id: 'd05q12', tier: 4, q: 'The Great Pyramid at Giza was built for which king?', choices: ['Khufu', 'Menkaure', 'Khafre', 'Sneferu'], correct: 0 },
  { id: 'd05q13', tier: 5, q: 'Which architect is credited with the step pyramid at Saqqara?', choices: ['Ineni', 'Senenmut', 'Hemiunu', 'Imhotep'], correct: 3 },
  { id: 'd05q14', tier: 5, q: 'In the weighing of the heart, the heart was balanced against what?', choices: ['A grain of wheat', 'A gold ring', 'A feather', 'A scarab'], correct: 2 },
  { id: 'd05q15', tier: 5, q: 'The Battle of Kadesh was fought against which empire?', choices: ['The Assyrians', 'The Persians', 'The Hittites', 'The Babylonians'], correct: 2 },
  { id: 'd06q01', tier: 1, q: 'Which organ pumps blood around the body?', choices: ['The heart', 'The liver', 'The kidneys', 'The lungs'], correct: 0 },
  { id: 'd06q02', tier: 1, q: 'How many lungs does a person have?', choices: ['One', 'Four', 'Two', 'Three'], correct: 2 },
  { id: 'd06q03', tier: 1, q: 'What is the hard tissue that makes up the skeleton?', choices: ['Tendon', 'Bone', 'Enamel', 'Cartilage'], correct: 1 },
  { id: 'd06q04', tier: 2, q: 'Which organ filters waste from the blood to make urine?', choices: ['The pancreas', 'The kidney', 'The gallbladder', 'The spleen'], correct: 1 },
  { id: 'd06q05', tier: 2, q: 'What is the largest organ of the body?', choices: ['The brain', 'The liver', 'The skin', 'The intestine'], correct: 2 },
  { id: 'd06q06', tier: 2, q: 'What protein in the blood carries oxygen?', choices: ['Hemoglobin', 'Keratin', 'Collagen', 'Insulin'], correct: 0 },
  { id: 'd06q07', tier: 3, q: 'How many bones are in a typical adult skeleton?', choices: ['226', '206', '256', '186'], correct: 1 },
  { id: 'd06q08', tier: 3, q: 'Which part of the brain governs balance and coordination?', choices: ['The cerebellum', 'The hippocampus', 'The pituitary', 'The thalamus'], correct: 0 },
  { id: 'd06q09', tier: 3, q: 'What is the longest bone in the body?', choices: ['The femur', 'The tibia', 'The humerus', 'The fibula'], correct: 0 },
  { id: 'd06q10', tier: 4, q: 'Which gland, at the base of the brain, is called the master gland?', choices: ['The thyroid', 'The adrenal', 'The pituitary', 'The thymus'], correct: 2 },
  { id: 'd06q11', tier: 4, q: 'Which nutrient does skin produce when exposed to sunlight?', choices: ['Vitamin K', 'Vitamin D', 'Vitamin C', 'Vitamin A'], correct: 1 },
  { id: 'd06q12', tier: 4, q: 'What is the smallest bone in the body, found in the ear?', choices: ['The hyoid', 'The malleus', 'The incus', 'The stapes'], correct: 3 },
  { id: 'd06q13', tier: 5, q: 'Which cranial nerve wanders from the brainstem to the gut and slows the heart?', choices: ['The phrenic nerve', 'The trigeminal nerve', 'The vagus nerve', 'The sciatic nerve'], correct: 2 },
  { id: 'd06q14', tier: 5, q: 'Which vessel carries oxygen-poor blood from the heart to the lungs?', choices: ['The aorta', 'The pulmonary vein', 'The vena cava', 'The pulmonary artery'], correct: 3 },
  { id: 'd06q15', tier: 5, q: 'Which part of the small intestine comes first, straight after the stomach?', choices: ['The ileum', 'The jejunum', 'The cecum', 'The duodenum'], correct: 3 },
  { id: 'd07q01', tier: 1, q: 'Who was the king of the gods, ruling from Mount Olympus?', choices: ['Zeus', 'Ares', 'Hermes', 'Apollo'], correct: 0 },
  { id: 'd07q02', tier: 1, q: 'Which hero performed twelve labors?', choices: ['Perseus', 'Heracles', 'Jason', 'Theseus'], correct: 1 },
  { id: 'd07q03', tier: 1, q: 'What creature was half man and half bull, kept in a labyrinth?', choices: ['The Chimera', 'The Centaur', 'The Minotaur', 'The Sphinx'], correct: 2 },
  { id: 'd07q04', tier: 2, q: 'Who was the god of the sea?', choices: ['Poseidon', 'Triton', 'Hades', 'Helios'], correct: 0 },
  { id: 'd07q05', tier: 2, q: 'Whose face is said to have launched a thousand ships?', choices: ['Andromache', 'Cassandra', 'Penelope', 'Helen'], correct: 3 },
  { id: 'd07q06', tier: 2, q: 'Which hero took ten years to sail home to Ithaca?', choices: ['Achilles', 'Ajax', 'Odysseus', 'Menelaus'], correct: 2 },
  { id: 'd07q07', tier: 3, q: 'Who stole fire for humankind and was chained to a rock for it?', choices: ['Prometheus', 'Epimetheus', 'Tantalus', 'Atlas'], correct: 0 },
  { id: 'd07q08', tier: 3, q: 'Which river did the dead cross into the underworld?', choices: ['The Eridanos', 'The Styx', 'The Phlegethon', 'The Lethe'], correct: 1 },
  { id: 'd07q09', tier: 3, q: 'Which goddess of wisdom sprang fully formed from her father’s head?', choices: ['Hera', 'Demeter', 'Artemis', 'Athena'], correct: 3 },
  { id: 'd07q10', tier: 4, q: 'Which musician tried to lead his wife back out of the underworld and looked back?', choices: ['Orpheus', 'Linus', 'Marsyas', 'Amphion'], correct: 0 },
  { id: 'd07q11', tier: 4, q: 'Which titan was condemned to hold up the sky?', choices: ['Hyperion', 'Cronus', 'Atlas', 'Oceanus'], correct: 2 },
  { id: 'd07q12', tier: 4, q: 'Whose eating of pomegranate seeds bound her to the underworld for part of each year?', choices: ['Hecate', 'Eurydice', 'Ariadne', 'Persephone'], correct: 3 },
  { id: 'd07q13', tier: 5, q: 'What was the name of the ship that carried the heroes after the golden fleece?', choices: ['The Naxos', 'The Argo', 'The Aeolus', 'The Pelias'], correct: 1 },
  { id: 'd07q14', tier: 5, q: 'Which three sisters spun, measured and cut the thread of every life?', choices: ['The Graces', 'The Furies', 'The Muses', 'The Fates'], correct: 3 },
  { id: 'd07q15', tier: 5, q: 'Which mortal king was punished by rolling a boulder uphill forever?', choices: ['Tityos', 'Ixion', 'Sisyphus', 'Salmoneus'], correct: 2 },
  { id: 'd08q01', tier: 1, q: 'How many strikes make an out?', choices: ['Three', 'Four', 'Five', 'Two'], correct: 0 },
  { id: 'd08q02', tier: 1, q: 'How many bases must a runner touch to score, counting home plate?', choices: ['Five', 'Three', 'Six', 'Four'], correct: 3 },
  { id: 'd08q03', tier: 1, q: 'What is a hit that clears the fence in fair territory called?', choices: ['A sacrifice', 'A triple', 'A home run', 'A ground rule'], correct: 2 },
  { id: 'd08q04', tier: 2, q: 'How many players from one team are on the field on defense?', choices: ['Eight', 'Eleven', 'Nine', 'Ten'], correct: 2 },
  { id: 'd08q05', tier: 2, q: 'What is the championship series at the end of the major league season called?', choices: ['The Fall Classic Cup', 'The Commissioner’s Cup', 'The Grand Final', 'The World Series'], correct: 3 },
  { id: 'd08q06', tier: 2, q: 'Which fielder crouches behind home plate?', choices: ['The catcher', 'The pitcher', 'The shortstop', 'The third baseman'], correct: 0 },
  { id: 'd08q07', tier: 3, q: 'Who broke the major leagues’ color barrier in 1947?', choices: ['Roy Campanella', 'Larry Doby', 'Jackie Robinson', 'Satchel Paige'], correct: 2 },
  { id: 'd08q08', tier: 3, q: 'Which slugger hit 714 home runs and starred for the Yankees in the 1920s?', choices: ['Lou Gehrig', 'Babe Ruth', 'Ty Cobb', 'Jimmie Foxx'], correct: 1 },
  { id: 'd08q09', tier: 3, q: 'How many feet apart are the bases on a regulation diamond?', choices: ['60', '90', '75', '100'], correct: 1 },
  { id: 'd08q10', tier: 4, q: 'Whose consecutive-games streak of 2,632 stands as the record?', choices: ['Steve Garvey', 'Pete Rose', 'Lou Gehrig', 'Cal Ripken Jr.'], correct: 3 },
  { id: 'd08q11', tier: 4, q: 'How far is the pitching rubber from home plate?', choices: ['58 feet 6 inches', '60 feet 6 inches', '64 feet 3 inches', '62 feet even'], correct: 1 },
  { id: 'd08q12', tier: 4, q: 'Which player holds the career record for hits?', choices: ['Pete Rose', 'Stan Musial', 'Hank Aaron', 'Ty Cobb'], correct: 0 },
  { id: 'd08q13', tier: 5, q: 'Which pitcher threw a record seven no-hitters?', choices: ['Nolan Ryan', 'Bob Feller', 'Cy Young', 'Sandy Koufax'], correct: 0 },
  { id: 'd08q14', tier: 5, q: 'Who was the last player to bat over .400 in a season?', choices: ['Rod Carew', 'Ted Williams', 'Tony Gwynn', 'George Brett'], correct: 1 },
  { id: 'd08q15', tier: 5, q: 'In which city is the National Baseball Hall of Fame?', choices: ['Canton', 'Springfield', 'Cooperstown', 'Saratoga Springs'], correct: 2 },
  { id: 'd09q01', tier: 1, q: 'In which year did the war in Europe end?', choices: ['1944', '1945', '1946', '1943'], correct: 1 },
  { id: 'd09q02', tier: 1, q: 'Which country did Germany invade in September 1939 to start the war?', choices: ['Poland', 'Norway', 'France', 'Belgium'], correct: 0 },
  { id: 'd09q03', tier: 1, q: 'Which harbor was attacked in December 1941, bringing America in?', choices: ['Guantanamo Bay', 'Subic Bay', 'Manila Bay', 'Pearl Harbor'], correct: 3 },
  { id: 'd09q04', tier: 2, q: 'Who was the British prime minister for most of the war?', choices: ['Winston Churchill', 'Clement Attlee', 'Neville Chamberlain', 'Anthony Eden'], correct: 0 },
  { id: 'd09q05', tier: 2, q: 'What is the name for the Allied landings in Normandy on 6 June 1944?', choices: ['D-Day', 'Operation Torch', 'Operation Husky', 'V-Day'], correct: 0 },
  { id: 'd09q06', tier: 2, q: 'Which two Japanese cities were struck by atomic bombs?', choices: ['Yokohama and Kobe', 'Hiroshima and Nagasaki', 'Kyoto and Osaka', 'Sapporo and Sendai'], correct: 1 },
  { id: 'd09q07', tier: 3, q: 'Which battle on the Volga cost Germany an entire army in 1942 and 1943?', choices: ['Rostov', 'Kharkov', 'Kursk', 'Stalingrad'], correct: 3 },
  { id: 'd09q08', tier: 3, q: 'What was the codename for the German invasion of the Soviet Union?', choices: ['Operation Typhoon', 'Operation Sea Lion', 'Operation Citadel', 'Operation Barbarossa'], correct: 3 },
  { id: 'd09q09', tier: 3, q: 'Which Pacific carrier battle in June 1942 turned the war against Japan?', choices: ['Coral Sea', 'Guadalcanal', 'Midway', 'Leyte Gulf'], correct: 2 },
  { id: 'd09q10', tier: 4, q: 'At which English country house were German codes broken?', choices: ['Chartwell', 'Hatfield House', 'Bletchley Park', 'Chequers'], correct: 2 },
  { id: 'd09q11', tier: 4, q: 'What was the codename for the American atomic bomb program?', choices: ['The Trinity Program', 'The Manhattan Project', 'Project Alsos', 'The Tube Alloys Project'], correct: 1 },
  { id: 'd09q12', tier: 4, q: 'Which German counteroffensive in the Ardennes began in December 1944?', choices: ['The Battle of the Bulge', 'The Saar offensive', 'Operation Market Garden', 'The Rhineland campaign'], correct: 0 },
  { id: 'd09q13', tier: 5, q: 'At which 1945 conference did the Big Three meet in Crimea?', choices: ['Potsdam', 'Tehran', 'Casablanca', 'Yalta'], correct: 3 },
  { id: 'd09q14', tier: 5, q: 'Which German battleship was sunk in May 1941 after a long chase?', choices: ['The Tirpitz', 'The Scharnhorst', 'The Bismarck', 'The Graf Spee'], correct: 2 },
  { id: 'd09q15', tier: 5, q: 'On which ship did Japan formally surrender in September 1945?', choices: ['USS Enterprise', 'USS Missouri', 'USS Arizona', 'USS Iowa'], correct: 1 },
  { id: 'd10q01', tier: 1, q: 'Which giant predator’s name means tyrant lizard king?', choices: ['Velociraptor', 'Tyrannosaurus rex', 'Allosaurus', 'Spinosaurus'], correct: 1 },
  { id: 'd10q02', tier: 1, q: 'What are the preserved remains that teach us about them called?', choices: ['Fossils', 'Relics', 'Sediments', 'Isotopes'], correct: 0 },
  { id: 'd10q03', tier: 1, q: 'Which plated dinosaur had spikes on its tail?', choices: ['Triceratops', 'Stegosaurus', 'Iguanodon', 'Ankylosaurus'], correct: 1 },
  { id: 'd10q04', tier: 2, q: 'How many horns did Triceratops have on its head?', choices: ['Five', 'Four', 'Two', 'Three'], correct: 3 },
  { id: 'd10q05', tier: 2, q: 'Which era is called the age of dinosaurs?', choices: ['The Cenozoic', 'The Mesozoic', 'The Paleozoic', 'The Precambrian'], correct: 1 },
  { id: 'd10q06', tier: 2, q: 'What is thought to have struck Earth and helped end their reign?', choices: ['A comet swarm', 'A gamma-ray burst', 'An asteroid', 'A solar flare'], correct: 2 },
  { id: 'd10q07', tier: 3, q: 'Which of the three Mesozoic periods came first?', choices: ['Jurassic', 'Triassic', 'Permian', 'Cretaceous'], correct: 1 },
  { id: 'd10q08', tier: 3, q: 'Which long-necked plant eater was once widely called Brontosaurus?', choices: ['Diplodocus', 'Brachiosaurus', 'Camarasaurus', 'Apatosaurus'], correct: 3 },
  { id: 'd10q09', tier: 3, q: 'Modern birds descend from which dinosaur group?', choices: ['Ornithopods', 'Ceratopsians', 'Theropods', 'Sauropods'], correct: 2 },
  { id: 'd10q10', tier: 4, q: 'Roughly how many million years ago did the mass extinction occur?', choices: ['About 25', 'About 145', 'About 66', 'About 250'], correct: 2 },
  { id: 'd10q11', tier: 4, q: 'Which crater in Mexico marks the impact site?', choices: ['Chicxulub', 'Sudbury', 'Manicouagan', 'Vredefort'], correct: 0 },
  { id: 'd10q12', tier: 4, q: 'Which feathered fossil from Bavaria is the classic link to birds?', choices: ['Ichthyornis', 'Hesperornis', 'Archaeopteryx', 'Confuciusornis'], correct: 2 },
  { id: 'd10q13', tier: 5, q: 'The two great orders are divided by the shape of what?', choices: ['The shoulder blade', 'The skull', 'The teeth', 'The hip bones'], correct: 3 },
  { id: 'd10q14', tier: 5, q: 'Which sail-backed predator, known from North Africa, hunted in water?', choices: ['Spinosaurus', 'Giganotosaurus', 'Carcharodontosaurus', 'Baryonyx'], correct: 0 },
  { id: 'd10q15', tier: 5, q: 'Which Victorian anatomist coined the word for these animals in 1842?', choices: ['William Buckland', 'Gideon Mantell', 'Charles Lyell', 'Richard Owen'], correct: 3 },
  { id: 'd11q01', tier: 1, q: 'Which award is the golden statuette given out each spring in Hollywood?', choices: ['The Bafta', 'The Oscar', 'The Palme d’Or', 'The Golden Globe'], correct: 1 },
  { id: 'd11q02', tier: 1, q: 'Which 1977 space adventure introduced Luke Skywalker?', choices: ['Star Trek', 'Flash Gordon', 'Dune', 'Star Wars'], correct: 3 },
  { id: 'd11q03', tier: 1, q: 'Which director made Jaws, E.T. and Jurassic Park?', choices: ['Steven Spielberg', 'George Lucas', 'Ridley Scott', 'James Cameron'], correct: 0 },
  { id: 'd11q04', tier: 2, q: 'Which 1972 crime film opens with a wedding at the Corleone house?', choices: ['The Godfather', 'Once Upon a Time in America', 'Scarface', 'Goodfellas'], correct: 0 },
  { id: 'd11q05', tier: 2, q: 'Which studio made Snow White, the first feature-length cel-animated film?', choices: ['MGM', 'Fleischer Studios', 'Warner Bros.', 'Disney'], correct: 3 },
  { id: 'd11q06', tier: 2, q: 'Which French seaside town hosts the most famous film festival, each May?', choices: ['Biarritz', 'Deauville', 'Nice', 'Cannes'], correct: 3 },
  { id: 'd11q07', tier: 3, q: 'Which 1941 film by Orson Welles is routinely called the greatest ever made?', choices: ['Casablanca', 'Citizen Kane', 'Touch of Evil', 'The Third Man'], correct: 1 },
  { id: 'd11q08', tier: 3, q: 'Which Japanese director made Seven Samurai and Rashomon?', choices: ['Masaki Kobayashi', 'Kenji Mizoguchi', 'Yasujiro Ozu', 'Akira Kurosawa'], correct: 3 },
  { id: 'd11q09', tier: 3, q: 'What is the term for a shot taken in one continuous, unbroken take?', choices: ['A jump cut', 'A match cut', 'A long take', 'A dissolve'], correct: 2 },
  { id: 'd11q10', tier: 4, q: 'Which 1927 film is usually called the first feature-length talkie?', choices: ['The Lights of New York', 'Sunrise', 'The Jazz Singer', 'Metropolis'], correct: 2 },
  { id: 'd11q11', tier: 4, q: 'Which Italian movement gave us Bicycle Thieves and Rome, Open City?', choices: ['Expressionism', 'Neorealism', 'The New Wave', 'Dogme 95'], correct: 1 },
  { id: 'd11q12', tier: 4, q: 'Which film won the very first Academy Award for best picture?', choices: ['The Broadway Melody', 'Sunrise', 'Wings', 'All Quiet on the Western Front'], correct: 2 },
  { id: 'd11q13', tier: 5, q: 'Which French critic-turned-director made The 400 Blows in 1959?', choices: ['Eric Rohmer', 'Jean-Luc Godard', 'Francois Truffaut', 'Claude Chabrol'], correct: 2 },
  { id: 'd11q14', tier: 5, q: 'Which 1902 short by Georges Melies shows a capsule hitting the moon’s eye?', choices: ['The Great Train Robbery', 'A Trip to the Moon', 'The Arrival of a Train', 'The Impossible Voyage'], correct: 1 },
  { id: 'd11q15', tier: 5, q: 'What was the two-color, then three-color, process that brought color to Hollywood?', choices: ['Technicolor', 'Cinerama', 'Kinemacolor', 'Eastmancolor'], correct: 0 },
  { id: 'd12q01', tier: 1, q: 'What is the molten rock called once it flows out onto the surface?', choices: ['Lava', 'Tephra', 'Magma', 'Basalt'], correct: 0 },
  { id: 'd12q02', tier: 1, q: 'What is the bowl-shaped opening at the summit called?', choices: ['The caldera', 'The fumarole', 'The crater', 'The vent shaft'], correct: 2 },
  { id: 'd12q03', tier: 1, q: 'Which Italian volcano destroyed Pompeii?', choices: ['Etna', 'Stromboli', 'Vulture', 'Vesuvius'], correct: 3 },
  { id: 'd12q04', tier: 2, q: 'What is the horseshoe-shaped belt of volcanoes around the Pacific called?', choices: ['The Pacific Arc', 'The Ring of Fire', 'The Andesite Line', 'The Fire Belt'], correct: 1 },
  { id: 'd12q05', tier: 2, q: 'Which US volcano erupted spectacularly in May 1980?', choices: ['Mount Shasta', 'Mount St. Helens', 'Mount Rainier', 'Lassen Peak'], correct: 1 },
  { id: 'd12q06', tier: 2, q: 'Which island chain in the Pacific was built entirely by volcanoes?', choices: ['The Maldives', 'The Bahamas', 'Hawaii', 'The Azores'], correct: 2 },
  { id: 'd12q07', tier: 3, q: 'What is molten rock called while it is still underground?', choices: ['Pumice', 'Lava', 'Obsidian', 'Magma'], correct: 3 },
  { id: 'd12q08', tier: 3, q: 'What is the broad, gently sloping type of volcano built by runny lava called?', choices: ['A lava dome', 'A cinder cone', 'A shield volcano', 'A stratovolcano'], correct: 2 },
  { id: 'd12q09', tier: 3, q: 'Which Indonesian volcano exploded in 1883 with a blast heard thousands of miles away?', choices: ['Krakatoa', 'Tambora', 'Agung', 'Merapi'], correct: 0 },
  { id: 'd12q10', tier: 4, q: 'What is the fast-moving cloud of hot gas and ash that races downslope called?', choices: ['A tephra fall', 'A pyroclastic flow', 'A nuee cloud', 'A lahar'], correct: 1 },
  { id: 'd12q11', tier: 4, q: 'Which 1815 eruption led to the following year without a summer?', choices: ['Pinatubo', 'Laki', 'Krakatoa', 'Tambora'], correct: 3 },
  { id: 'd12q12', tier: 4, q: 'What is a volcanic mudflow, often deadlier than the lava, called?', choices: ['A jokulhlaup', 'A lahar', 'A pahoehoe', 'A surge'], correct: 1 },
  { id: 'd12q13', tier: 5, q: 'Which scale measures the size of an explosive eruption?', choices: ['The Mercalli scale', 'The Richter scale', 'The Fujita scale', 'The Volcanic Explosivity Index'], correct: 3 },
  { id: 'd12q14', tier: 5, q: 'Which Icelandic fissure eruption of 1783 poisoned much of Europe’s air?', choices: ['Laki', 'Askja', 'Hekla', 'Katla'], correct: 0 },
  { id: 'd12q15', tier: 5, q: 'What are the two Hawaiian words for smooth and jagged lava surfaces?', choices: ['Pahoehoe and aa', 'Tuff and scoria', 'Pele and Lono', 'Kipuka and pali'], correct: 0 },
  { id: 'd13q01', tier: 1, q: 'Who was the first person to hold the office?', choices: ['George Washington', 'John Adams', 'Benjamin Franklin', 'Thomas Jefferson'], correct: 0 },
  { id: 'd13q02', tier: 1, q: 'What is the official residence in Washington called?', choices: ['The White House', 'Blair House', 'The Executive Lodge', 'The Capitol'], correct: 0 },
  { id: 'd13q03', tier: 1, q: 'How many years are in a single term?', choices: ['Two', 'Four', 'Five', 'Six'], correct: 1 },
  { id: 'd13q04', tier: 2, q: 'Who was in office during the Civil War?', choices: ['James Buchanan', 'Abraham Lincoln', 'Andrew Johnson', 'Ulysses S. Grant'], correct: 1 },
  { id: 'd13q05', tier: 2, q: 'Which official succeeds first if the office falls vacant?', choices: ['The vice president', 'The chief justice', 'The speaker of the House', 'The secretary of state'], correct: 0 },
  { id: 'd13q06', tier: 2, q: 'Who resigned in 1974 over the Watergate scandal?', choices: ['Lyndon Johnson', 'Gerald Ford', 'Richard Nixon', 'Spiro Agnew'], correct: 2 },
  { id: 'd13q07', tier: 3, q: 'Who is the only person elected to four terms?', choices: ['Dwight Eisenhower', 'Woodrow Wilson', 'Theodore Roosevelt', 'Franklin D. Roosevelt'], correct: 3 },
  { id: 'd13q08', tier: 3, q: 'How many terms does the Twenty-second Amendment allow?', choices: ['Four', 'One', 'Three', 'Two'], correct: 3 },
  { id: 'd13q09', tier: 3, q: 'Which two men have been impeached by the House and then acquitted in the 19th and 20th centuries?', choices: ['Ulysses S. Grant and Bill Clinton', 'Andrew Johnson and Richard Nixon', 'Andrew Johnson and Bill Clinton', 'Andrew Jackson and Bill Clinton'], correct: 2 },
  { id: 'd13q10', tier: 4, q: 'Who is the only person to serve two non-consecutive terms in the 19th century?', choices: ['Rutherford B. Hayes', 'Benjamin Harrison', 'Chester A. Arthur', 'Grover Cleveland'], correct: 3 },
  { id: 'd13q11', tier: 4, q: 'What is the minimum age set by the Constitution?', choices: ['30', '35', '25', '40'], correct: 1 },
  { id: 'd13q12', tier: 4, q: 'Who was the youngest ever to take the office, on the death of his predecessor?', choices: ['Ulysses S. Grant', 'Theodore Roosevelt', 'Bill Clinton', 'John F. Kennedy'], correct: 1 },
  { id: 'd13q13', tier: 5, q: 'Which president served the shortest time, dying within weeks of taking office?', choices: ['James A. Garfield', 'Warren G. Harding', 'Zachary Taylor', 'William Henry Harrison'], correct: 3 },
  { id: 'd13q14', tier: 5, q: 'Which amendment moved inauguration day from March to January?', choices: ['The Twentieth', 'The Twenty-fifth', 'The Twelfth', 'The Seventeenth'], correct: 0 },
  { id: 'd13q15', tier: 5, q: 'Which president was never elected to either the presidency or the vice presidency?', choices: ['Chester A. Arthur', 'Millard Fillmore', 'Gerald Ford', 'Andrew Johnson'], correct: 2 },
  { id: 'd14q01', tier: 1, q: 'Which large flightless bird of Africa is the heaviest living bird?', choices: ['The emu', 'The ostrich', 'The cassowary', 'The rhea'], correct: 1 },
  { id: 'd14q02', tier: 1, q: 'What covers a bird’s body and lets most of them fly?', choices: ['Fur', 'Feathers', 'Membranes', 'Scales'], correct: 1 },
  { id: 'd14q03', tier: 1, q: 'Which black-and-white seabird of the far south cannot fly but swims superbly?', choices: ['The auk', 'The petrel', 'The puffin', 'The penguin'], correct: 3 },
  { id: 'd14q04', tier: 2, q: 'Which bird is the fastest animal on Earth in a dive?', choices: ['The golden eagle', 'The swift', 'The frigatebird', 'The peregrine falcon'], correct: 3 },
  { id: 'd14q05', tier: 2, q: 'Which tiny bird can hover in place and fly backwards?', choices: ['The hummingbird', 'The kinglet', 'The wren', 'The sunbird'], correct: 0 },
  { id: 'd14q06', tier: 2, q: 'What is a group of crows traditionally called?', choices: ['A parliament', 'A gaggle', 'A charm', 'A murder'], correct: 3 },
  { id: 'd14q07', tier: 3, q: 'Which flightless New Zealand bird lays an egg enormous for its body size?', choices: ['The kiwi', 'The weka', 'The takahe', 'The kakapo'], correct: 0 },
  { id: 'd14q08', tier: 3, q: 'Which bird has the largest wingspan of any living species?', choices: ['The great bustard', 'The Andean condor', 'The marabou stork', 'The wandering albatross'], correct: 3 },
  { id: 'd14q09', tier: 3, q: 'Which North American bird was hunted from billions to extinction by 1914?', choices: ['The Carolina parakeet', 'The heath hen', 'The passenger pigeon', 'The great auk'], correct: 2 },
  { id: 'd14q10', tier: 4, q: 'Which Arctic bird makes the longest annual migration of any animal?', choices: ['The red knot', 'The Arctic tern', 'The sooty shearwater', 'The bar-tailed godwit'], correct: 1 },
  { id: 'd14q11', tier: 4, q: 'What is the study of birds called?', choices: ['Ornithology', 'Ichthyology', 'Entomology', 'Herpetology'], correct: 0 },
  { id: 'd14q12', tier: 4, q: 'Which bird lays its eggs in other species’ nests across much of Europe?', choices: ['The common cuckoo', 'The corncrake', 'The shrike', 'The nightjar'], correct: 0 },
  { id: 'd14q13', tier: 5, q: 'What is the name for the muscular organ birds use to grind food, often with grit?', choices: ['The crop', 'The syrinx', 'The gizzard', 'The cloaca'], correct: 2 },
  { id: 'd14q14', tier: 5, q: 'Which vocal organ, unique to birds, produces their song?', choices: ['The larynx', 'The syrinx', 'The glottis', 'The pharynx'], correct: 1 },
  { id: 'd14q15', tier: 5, q: 'Which giant flightless bird of Madagascar laid the largest eggs known?', choices: ['The terror bird', 'The moa', 'The elephant bird', 'The dodo'], correct: 2 },
  { id: 'd15q01', tier: 1, q: 'Which instrument has 88 keys?', choices: ['The piano', 'The organ', 'The celesta', 'The harpsichord'], correct: 0 },
  { id: 'd15q02', tier: 1, q: 'Who leads an orchestra from the podium with a baton?', choices: ['The repetiteur', 'The impresario', 'The conductor', 'The concertmaster'], correct: 2 },
  { id: 'd15q03', tier: 1, q: 'Which deaf German composer wrote the Fifth Symphony, with its four-note opening?', choices: ['Brahms', 'Schumann', 'Beethoven', 'Schubert'], correct: 2 },
  { id: 'd15q04', tier: 2, q: 'Which Austrian child prodigy wrote The Marriage of Figaro?', choices: ['Gluck', 'Haydn', 'Salieri', 'Mozart'], correct: 3 },
  { id: 'd15q05', tier: 2, q: 'Which Italian composer wrote The Four Seasons?', choices: ['Vivaldi', 'Albinoni', 'Scarlatti', 'Corelli'], correct: 0 },
  { id: 'd15q06', tier: 2, q: 'Which Russian wrote the Nutcracker and Swan Lake ballets?', choices: ['Tchaikovsky', 'Rimsky-Korsakov', 'Mussorgsky', 'Borodin'], correct: 0 },
  { id: 'd15q07', tier: 3, q: 'How many symphonies did Beethoven complete?', choices: ['Seven', 'Eight', 'Nine', 'Ten'], correct: 2 },
  { id: 'd15q08', tier: 3, q: 'Which composer, who worked in Leipzig, wrote the Brandenburg Concertos?', choices: ['Bach', 'Buxtehude', 'Telemann', 'Handel'], correct: 0 },
  { id: 'd15q09', tier: 3, q: 'Which four-part group of strings is the standard chamber ensemble?', choices: ['The piano trio', 'The wind quintet', 'The brass quartet', 'The string quartet'], correct: 3 },
  { id: 'd15q10', tier: 4, q: 'Whose four-opera cycle is the Ring of the Nibelung?', choices: ['Weber', 'Strauss', 'Verdi', 'Wagner'], correct: 3 },
  { id: 'd15q11', tier: 4, q: 'Which Finnish composer wrote Finlandia?', choices: ['Grieg', 'Sibelius', 'Nielsen', 'Alfven'], correct: 1 },
  { id: 'd15q12', tier: 4, q: 'Which 1913 ballet premiere in Paris caused a riot?', choices: ['Daphnis and Chloe', 'The Rite of Spring', 'Petrushka', 'The Firebird'], correct: 1 },
  { id: 'd15q13', tier: 5, q: 'Which composer wrote a symphony left unfinished at two movements, in B minor?', choices: ['Mahler', 'Bruckner', 'Schubert', 'Dvorak'], correct: 2 },
  { id: 'd15q14', tier: 5, q: 'What is the Italian term for gradually getting louder?', choices: ['Diminuendo', 'Sforzando', 'Ritardando', 'Crescendo'], correct: 3 },
  { id: 'd15q15', tier: 5, q: 'Which Austrian founded the twelve-tone method of composition?', choices: ['Zemlinsky', 'Schoenberg', 'Berg', 'Webern'], correct: 1 },
  { id: 'd16q01', tier: 1, q: 'Which pole lies on this continent?', choices: ['The South Pole', 'The magnetic north pole', 'The geomagnetic north pole', 'The North Pole'], correct: 0 },
  { id: 'd16q02', tier: 1, q: 'What covers almost the entire land surface?', choices: ['Tundra grass', 'Ice', 'Forest', 'Sand'], correct: 1 },
  { id: 'd16q03', tier: 1, q: 'Which flightless seabirds breed there in vast colonies?', choices: ['Puffins', 'Gannets', 'Penguins', 'Auks'], correct: 2 },
  { id: 'd16q04', tier: 2, q: 'Which Norwegian led the first party to the South Pole in 1911?', choices: ['Fridtjof Nansen', 'Robert Falcon Scott', 'Ernest Shackleton', 'Roald Amundsen'], correct: 3 },
  { id: 'd16q05', tier: 2, q: 'How many native land mammal species live there?', choices: ['Eleven', 'Three', 'One', 'None'], correct: 3 },
  { id: 'd16q06', tier: 2, q: 'Which ocean surrounds the continent?', choices: ['The Southern Ocean', 'The Tasman Sea', 'The Indian Ocean alone', 'The Arctic Ocean'], correct: 0 },
  { id: 'd16q07', tier: 3, q: 'Which British explorer’s ship Endurance was crushed by pack ice in 1915?', choices: ['James Clark Ross', 'Douglas Mawson', 'Ernest Shackleton', 'Robert Falcon Scott'], correct: 2 },
  { id: 'd16q08', tier: 3, q: 'Which treaty, signed in 1959, set the continent aside for peaceful science?', choices: ['The Convention of Hobart', 'The Ross Accord', 'The Madrid Protocol', 'The Antarctic Treaty'], correct: 3 },
  { id: 'd16q09', tier: 3, q: 'Roughly what share of the world’s fresh water is locked in the ice sheet?', choices: ['About 30 percent', 'About 70 percent', 'About 10 percent', 'About 95 percent'], correct: 1 },
  { id: 'd16q10', tier: 4, q: 'Which enormous ice shelf, the largest, fringes the sea named for the same explorer?', choices: ['The Amery Ice Shelf', 'The Larsen Ice Shelf', 'The Ross Ice Shelf', 'The Ronne Ice Shelf'], correct: 2 },
  { id: 'd16q11', tier: 4, q: 'Which is the highest mountain on the continent?', choices: ['Mount Markham', 'Mount Kirkpatrick', 'Mount Erebus', 'Vinson Massif'], correct: 3 },
  { id: 'd16q12', tier: 4, q: 'Which active volcano rises above the Ross Island research bases?', choices: ['Mount Melbourne', 'Mount Erebus', 'Mount Terror', 'Deception Peak'], correct: 1 },
  { id: 'd16q13', tier: 5, q: 'Which vast subglacial lake sits under four kilometers of ice near a Russian station?', choices: ['Lake Ellsworth', 'Lake Whillans', 'Lake Vostok', 'Lake Concordia'], correct: 2 },
  { id: 'd16q14', tier: 5, q: 'What are the ice-free desert basins near McMurdo Sound called?', choices: ['The Dry Valleys', 'The Nunatak Flats', 'The Windless Bight', 'The Bare Reaches'], correct: 0 },
  { id: 'd16q15', tier: 5, q: 'The coldest natural temperature ever recorded on Earth was measured on this continent at roughly what?', choices: ['Minus 89 degrees Celsius', 'Minus 104 degrees Celsius', 'Minus 71 degrees Celsius', 'Minus 62 degrees Celsius'], correct: 0 },
  { id: 'd17q01', tier: 1, q: 'Which two superpowers faced off for four decades?', choices: ['Britain and the Soviet Union', 'The United States and Cuba', 'The United States and the Soviet Union', 'The United States and China'], correct: 2 },
  { id: 'd17q02', tier: 1, q: 'Which city was split by a famous wall from 1961 to 1989?', choices: ['Warsaw', 'Berlin', 'Vienna', 'Prague'], correct: 1 },
  { id: 'd17q03', tier: 1, q: 'What was the race to reach the moon called?', choices: ['The space race', 'The orbital war', 'The lunar contest', 'The rocket rivalry'], correct: 0 },
  { id: 'd17q04', tier: 2, q: 'Which 1962 crisis brought missiles to an island 90 miles from Florida?', choices: ['The Berlin airlift', 'The Bay of Pigs', 'The Cuban missile crisis', 'The Suez crisis'], correct: 2 },
  { id: 'd17q05', tier: 2, q: 'Which Western military alliance was founded in 1949?', choices: ['The Warsaw Pact', 'NATO', 'The Comintern', 'SEATO'], correct: 1 },
  { id: 'd17q06', tier: 2, q: 'Which Soviet leader oversaw glasnost and perestroika?', choices: ['Mikhail Gorbachev', 'Yuri Andropov', 'Nikita Khrushchev', 'Leonid Brezhnev'], correct: 0 },
  { id: 'd17q07', tier: 3, q: 'Which speech by Churchill in 1946 popularized the phrase iron curtain?', choices: ['The Harvard address', 'The Chequers broadcast', 'The Zurich speech', 'The Fulton speech in Missouri'], correct: 3 },
  { id: 'd17q08', tier: 3, q: 'Which American plan poured aid into rebuilding Western Europe?', choices: ['The Point Four Program', 'The Dawes Plan', 'The Truman Plan', 'The Marshall Plan'], correct: 3 },
  { id: 'd17q09', tier: 3, q: 'Which satellite, launched in 1957, started the space race?', choices: ['Luna', 'Sputnik', 'Vanguard', 'Explorer'], correct: 1 },
  { id: 'd17q10', tier: 4, q: 'What was the doctrine of deterrence by guaranteed retaliation abbreviated to?', choices: ['MAD', 'SALT', 'NORAD', 'START'], correct: 0 },
  { id: 'd17q11', tier: 4, q: 'The Warsaw Pact invaded which country in 1968 to crush its reforms?', choices: ['Poland', 'Hungary', 'Romania', 'Czechoslovakia'], correct: 3 },
  { id: 'd17q12', tier: 4, q: 'Which American U-2 pilot was shot down over Soviet territory in 1960?', choices: ['Francis Gary Powers', 'Chuck Yeager', 'Frederick Pryor', 'Rudolf Abel'], correct: 0 },
  { id: 'd17q13', tier: 5, q: 'Which 1948 and 1949 operation supplied a blockaded city entirely by air?', choices: ['Operation Vittles West', 'Operation Plainfare Two', 'The Berlin airlift', 'The Rhine bridge'], correct: 2 },
  { id: 'd17q14', tier: 5, q: 'Which 1975 accords in Finland set out European security and human rights principles?', choices: ['The Vienna Convention', 'The Reykjavik Accords', 'The Helsinki Accords', 'The Oslo Agreement'], correct: 2 },
  { id: 'd17q15', tier: 5, q: 'Which Soviet officer is credited with judging a 1983 missile alert a false alarm?', choices: ['Viktor Belenko', 'Stanislav Petrov', 'Vasili Arkhipov', 'Oleg Penkovsky'], correct: 1 },
  { id: 'd18q01', tier: 1, q: 'Which element is the lightest and most abundant in the universe?', choices: ['Carbon', 'Oxygen', 'Hydrogen', 'Helium'], correct: 2 },
  { id: 'd18q02', tier: 1, q: 'What is the chemical symbol for oxygen?', choices: ['On', 'Og', 'Ox', 'O'], correct: 3 },
  { id: 'd18q03', tier: 1, q: 'Which element do diamonds and pencil leads have in common?', choices: ['Carbon', 'Silicon', 'Sulfur', 'Boron'], correct: 0 },
  { id: 'd18q04', tier: 2, q: 'What is the symbol for gold?', choices: ['Ag', 'Go', 'Gd', 'Au'], correct: 3 },
  { id: 'd18q05', tier: 2, q: 'What is the symbol for sodium?', choices: ['Sd', 'Na', 'Sn', 'So'], correct: 1 },
  { id: 'd18q06', tier: 2, q: 'Which gas fills party balloons and makes them float?', choices: ['Hydrogen', 'Neon', 'Helium', 'Argon'], correct: 2 },
  { id: 'd18q07', tier: 3, q: 'Which Russian chemist published the first widely accepted version of the table?', choices: ['Mendeleev', 'Butlerov', 'Zinin', 'Lomonosov'], correct: 0 },
  { id: 'd18q08', tier: 3, q: 'What does an element’s atomic number count?', choices: ['Isotopes', 'Protons', 'Neutrons', 'Electrons in the outer shell'], correct: 1 },
  { id: 'd18q09', tier: 3, q: 'The unreactive noble gases occupy which numbered column of the table?', choices: ['Group 1', 'Group 17', 'Group 18', 'Group 15'], correct: 2 },
  { id: 'd18q10', tier: 4, q: 'Which element is liquid at room temperature and is a metal?', choices: ['Bromine', 'Gallium', 'Cesium', 'Mercury'], correct: 3 },
  { id: 'd18q11', tier: 4, q: 'What is the symbol for tungsten?', choices: ['Tu', 'Tn', 'Tg', 'W'], correct: 3 },
  { id: 'd18q12', tier: 4, q: 'Which element, number 26, has the symbol Fe?', choices: ['Fermium', 'Iron', 'Francium', 'Ferrium'], correct: 1 },
  { id: 'd18q13', tier: 5, q: 'Which element was named after the scientist couple who discovered polonium and radium?', choices: ['Curium', 'Rutherfordium', 'Bohrium', 'Nobelium'], correct: 0 },
  { id: 'd18q14', tier: 5, q: 'Which is the heaviest element that occurs naturally in more than trace amounts?', choices: ['Uranium', 'Thorium', 'Plutonium', 'Radium'], correct: 0 },
  { id: 'd18q15', tier: 5, q: 'Which element, named for a Greek word meaning hidden, is a noble gas?', choices: ['Argon', 'Krypton', 'Xenon', 'Radon'], correct: 1 },
  { id: 'd19q01', tier: 1, q: 'How many players from one team are on the pitch at kickoff?', choices: ['Nine', 'Twelve', 'Ten', 'Eleven'], correct: 3 },
  { id: 'd19q02', tier: 1, q: 'How often is the men’s tournament normally held?', choices: ['Every four years', 'Every three years', 'Every five years', 'Every two years'], correct: 0 },
  { id: 'd19q03', tier: 1, q: 'What color card sends a player off?', choices: ['Red', 'Black', 'Blue', 'Yellow'], correct: 0 },
  { id: 'd19q04', tier: 2, q: 'Which country has won the men’s tournament the most times?', choices: ['Italy', 'Brazil', 'Germany', 'Argentina'], correct: 1 },
  { id: 'd19q05', tier: 2, q: 'Which country hosted and won the first tournament in 1930?', choices: ['Brazil', 'Argentina', 'Italy', 'Uruguay'], correct: 3 },
  { id: 'd19q06', tier: 2, q: 'Which Argentine won the 1986 tournament almost single-handed?', choices: ['Mario Kempes', 'Gabriel Batistuta', 'Daniel Passarella', 'Diego Maradona'], correct: 3 },
  { id: 'd19q07', tier: 3, q: 'Which country won the 1966 tournament on home soil?', choices: ['Portugal', 'The Soviet Union', 'England', 'West Germany'], correct: 2 },
  { id: 'd19q08', tier: 3, q: 'Which country hosted the first tournament held in Asia, shared with a neighbor, in 2002?', choices: ['Japan and Taiwan', 'South Korea and China', 'South Korea and Japan', 'China and Japan'], correct: 2 },
  { id: 'd19q09', tier: 3, q: 'Which German striker’s goal won the 2014 final in extra time?', choices: ['Mario Gotze', 'Andre Schurrle', 'Thomas Muller', 'Miroslav Klose'], correct: 0 },
  { id: 'd19q10', tier: 4, q: 'Which African nation first reached the quarter-finals, in 1990?', choices: ['Nigeria', 'Senegal', 'Cameroon', 'Ghana'], correct: 2 },
  { id: 'd19q11', tier: 4, q: 'Which player holds the record for goals across all men’s tournaments?', choices: ['Just Fontaine', 'Ronaldo', 'Gerd Muller', 'Miroslav Klose'], correct: 3 },
  { id: 'd19q12', tier: 4, q: 'Which country won the first Women’s World Cup, in 1991?', choices: ['Sweden', 'The United States', 'Norway', 'Germany'], correct: 1 },
  { id: 'd19q13', tier: 5, q: 'What is the name of the 1950 upset in which Uruguay silenced the Maracana?', choices: ['The Maracanazo', 'The Mineirazo', 'The Rio Shock', 'The Estadiazo'], correct: 0 },
  { id: 'd19q14', tier: 5, q: 'Which Frenchman scored 13 goals at a single tournament in 1958?', choices: ['Roger Piantoni', 'Just Fontaine', 'Raymond Kopa', 'Michel Platini'], correct: 1 },
  { id: 'd19q15', tier: 5, q: 'Which trophy, awarded before the current one, was stolen and never recovered in 1983?', choices: ['The Rous Trophy', 'The Jules Rimet Trophy', 'The Coupe Mondiale', 'The Havelange Cup'], correct: 1 },
  { id: 'd20q01', tier: 1, q: 'Which ocean is the largest?', choices: ['The Pacific', 'The Indian', 'The Atlantic', 'The Arctic'], correct: 0 },
  { id: 'd20q02', tier: 1, q: 'Which is the largest animal alive today?', choices: ['The whale shark', 'The blue whale', 'The great white shark', 'The giant squid'], correct: 1 },
  { id: 'd20q03', tier: 1, q: 'What makes seawater different from river water?', choices: ['It is denser with sand', 'It is warmer', 'It is salty', 'It is acidic'], correct: 2 },
  { id: 'd20q04', tier: 2, q: 'Roughly what share of the planet’s surface is ocean?', choices: ['About 50 percent', 'About 85 percent', 'About 60 percent', 'About 71 percent'], correct: 3 },
  { id: 'd20q05', tier: 2, q: 'What mainly causes the tides?', choices: ['The moon’s gravity', 'Ocean currents', 'Earth’s magnetic field', 'Prevailing winds'], correct: 0 },
  { id: 'd20q06', tier: 2, q: 'Which is the largest fish in the sea?', choices: ['The basking shark', 'The great white shark', 'The oarfish', 'The whale shark'], correct: 3 },
  { id: 'd20q07', tier: 3, q: 'What is the deepest point in the ocean called?', choices: ['The Horizon Deep', 'The Meteor Deep', 'The Sirena Deep', 'The Challenger Deep'], correct: 3 },
  { id: 'd20q08', tier: 3, q: 'Which warm current carries tropical water north-east across the Atlantic?', choices: ['The Gulf Stream', 'The Canary Current', 'The Labrador Current', 'The Humboldt Current'], correct: 0 },
  { id: 'd20q09', tier: 3, q: 'Which reef off Queensland is the largest structure built by living things?', choices: ['The Maldives Atoll', 'The Coral Triangle', 'The Great Barrier Reef', 'The Belize Barrier Reef'], correct: 2 },
  { id: 'd20q10', tier: 4, q: 'Which trench holds the deepest known water?', choices: ['The Java Trench', 'The Puerto Rico Trench', 'The Mariana Trench', 'The Tonga Trench'], correct: 2 },
  { id: 'd20q11', tier: 4, q: 'What is the sunlit upper layer of the ocean called?', choices: ['The benthic zone', 'The abyssal zone', 'The hadal zone', 'The photic zone'], correct: 3 },
  { id: 'd20q12', tier: 4, q: 'What phenomenon warms the eastern Pacific and disrupts weather worldwide?', choices: ['The monsoon reversal', 'El Nino', 'The Coriolis surge', 'The polar vortex'], correct: 1 },
  { id: 'd20q13', tier: 5, q: 'What are the deep-sea springs that host life without sunlight called?', choices: ['Salt domes', 'Hydrothermal vents', 'Brine pools', 'Cold seeps'], correct: 1 },
  { id: 'd20q14', tier: 5, q: 'What is the vast slow circulation driven by heat and salt often nicknamed?', choices: ['The global conveyor belt', 'The Ekman spiral', 'The Coriolis cascade', 'The Sverdrup drift'], correct: 0 },
  { id: 'd20q15', tier: 5, q: 'Which underwater mountain range runs down the middle of the Atlantic?', choices: ['The Azores Plateau', 'The Mid-Atlantic Ridge', 'The Walvis Ridge', 'The Reykjanes Rise'], correct: 1 },
  { id: 'd21q01', tier: 1, q: 'Who painted the Mona Lisa?', choices: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Botticelli'], correct: 1 },
  { id: 'd21q02', tier: 1, q: 'In which country did the movement begin?', choices: ['Spain', 'Germany', 'France', 'Italy'], correct: 3 },
  { id: 'd21q03', tier: 1, q: 'Who sculpted the marble David that stands in Florence?', choices: ['Donatello', 'Michelangelo', 'Cellini', 'Bernini'], correct: 1 },
  { id: 'd21q04', tier: 2, q: 'Which Florentine family bankrolled much of the art of the era?', choices: ['The Sforza', 'The Borgia', 'The Este', 'The Medici'], correct: 3 },
  { id: 'd21q05', tier: 2, q: 'Which chapel ceiling did Michelangelo paint for the pope?', choices: ['The Brancacci Chapel', 'The Pauline Chapel', 'The Scrovegni Chapel', 'The Sistine Chapel'], correct: 3 },
  { id: 'd21q06', tier: 2, q: 'Which German invented the movable-type printing press around 1440?', choices: ['Caxton', 'Schoeffer', 'Gutenberg', 'Fust'], correct: 2 },
  { id: 'd21q07', tier: 3, q: 'Which painter gave us The Birth of Venus?', choices: ['Titian', 'Botticelli', 'Ghirlandaio', 'Giorgione'], correct: 1 },
  { id: 'd21q08', tier: 3, q: 'Which Florentine wrote The Prince, a cold handbook for rulers?', choices: ['Machiavelli', 'Guicciardini', 'Castiglione', 'Savonarola'], correct: 0 },
  { id: 'd21q09', tier: 3, q: 'Who painted The School of Athens in the Vatican?', choices: ['Bramante', 'Raphael', 'Perugino', 'Signorelli'], correct: 1 },
  { id: 'd21q10', tier: 4, q: 'Which architect engineered the great dome of Florence cathedral?', choices: ['Alberti', 'Sangallo', 'Ghiberti', 'Brunelleschi'], correct: 3 },
  { id: 'd21q11', tier: 4, q: 'Which Venetian master painted Assumption of the Virgin and worked into his eighties?', choices: ['Veronese', 'Tintoretto', 'Titian', 'Bellini'], correct: 2 },
  { id: 'd21q12', tier: 4, q: 'Which northern painter made the Arnolfini portrait with its convex mirror?', choices: ['Hans Memling', 'Rogier van der Weyden', 'Jan van Eyck', 'Hieronymus Bosch'], correct: 2 },
  { id: 'd21q13', tier: 5, q: 'Which sculptor made the bronze doors of the Florence baptistery, later nicknamed the Gates of Paradise?', choices: ['Ghiberti', 'Verrocchio', 'Donatello', 'Pisano'], correct: 0 },
  { id: 'd21q14', tier: 5, q: 'Which friar briefly ruled Florence and burned luxuries in the bonfire of the vanities?', choices: ['Savonarola', 'Aquinas', 'Erasmus', 'Bruno'], correct: 0 },
  { id: 'd21q15', tier: 5, q: 'Which Dutch humanist wrote In Praise of Folly?', choices: ['Thomas More', 'Grotius', 'Erasmus', 'Spinoza'], correct: 2 },
  { id: 'd22q01', tier: 1, q: 'Who was the first person to walk on the moon?', choices: ['Yuri Gagarin', 'Buzz Aldrin', 'John Glenn', 'Neil Armstrong'], correct: 3 },
  { id: 'd22q02', tier: 1, q: 'What agency runs the American civilian space program?', choices: ['NOAA', 'NASA', 'DARPA', 'NORAD'], correct: 1 },
  { id: 'd22q03', tier: 1, q: 'In which year did humans first land on the moon?', choices: ['1969', '1965', '1972', '1961'], correct: 0 },
  { id: 'd22q04', tier: 2, q: 'Who was the first human in space, in 1961?', choices: ['Valentina Tereshkova', 'German Titov', 'Yuri Gagarin', 'Alan Shepard'], correct: 2 },
  { id: 'd22q05', tier: 2, q: 'Which program landed the first crews on the moon?', choices: ['Mercury', 'Apollo', 'Skylab', 'Gemini'], correct: 1 },
  { id: 'd22q06', tier: 2, q: 'Which telescope, launched in 1990, orbits Earth and takes deep-sky images?', choices: ['Kepler', 'Chandra', 'Hubble', 'Spitzer'], correct: 2 },
  { id: 'd22q07', tier: 3, q: 'Which was the first woman in space, in 1963?', choices: ['Valentina Tereshkova', 'Sally Ride', 'Judith Resnik', 'Svetlana Savitskaya'], correct: 0 },
  { id: 'd22q08', tier: 3, q: 'Which two probes launched in 1977 have since left the planets behind?', choices: ['The Voyagers', 'The Mariners', 'The Pioneers', 'The Vikings'], correct: 0 },
  { id: 'd22q09', tier: 3, q: 'How many crewed missions landed on the moon?', choices: ['Seven', 'Six', 'Four', 'Five'], correct: 1 },
  { id: 'd22q10', tier: 4, q: 'Which crewed moon mission suffered an oxygen tank explosion on the way out?', choices: ['Apollo 8', 'Apollo 1', 'Apollo 13', 'Apollo 12'], correct: 2 },
  { id: 'd22q11', tier: 4, q: 'Which Soviet space station preceded the current international one and flew until 2001?', choices: ['Mir', 'Buran', 'Salyut 7', 'Almaz'], correct: 0 },
  { id: 'd22q12', tier: 4, q: 'Which two rovers landed on Mars in 2004 and vastly outlived their planned missions?', choices: ['Curiosity and Perseverance', 'Sojourner and Pathfinder', 'Viking 1 and Viking 2', 'Spirit and Opportunity'], correct: 3 },
  { id: 'd22q13', tier: 5, q: 'Which mission carried the first humans to orbit the moon, at Christmas 1968?', choices: ['Apollo 9', 'Apollo 8', 'Apollo 10', 'Apollo 7'], correct: 1 },
  { id: 'd22q14', tier: 5, q: 'Which probe made the first close flyby of Pluto, in 2015?', choices: ['Juno', 'Dawn', 'Cassini', 'New Horizons'], correct: 3 },
  { id: 'd22q15', tier: 5, q: 'Who designed the Saturn V rocket program for NASA?', choices: ['Sergei Korolev', 'Robert Goddard', 'Wernher von Braun', 'Hermann Oberth'], correct: 2 },
  { id: 'd23q01', tier: 1, q: 'How many squares are on the board?', choices: ['64', '81', '100', '48'], correct: 0 },
  { id: 'd23q02', tier: 1, q: 'Which piece can only ever move one square at a time in any direction?', choices: ['The king', 'The pawn', 'The queen', 'The knight'], correct: 0 },
  { id: 'd23q03', tier: 1, q: 'Which color always moves first?', choices: ['Black', 'The player who won the last game', 'White', 'Whoever holds a pawn'], correct: 2 },
  { id: 'd23q04', tier: 2, q: 'Which piece is the most powerful on the board?', choices: ['The rook', 'The knight', 'The bishop', 'The queen'], correct: 3 },
  { id: 'd23q05', tier: 2, q: 'Which piece moves in an L shape and can jump over others?', choices: ['The rook', 'The bishop', 'The king', 'The knight'], correct: 3 },
  { id: 'd23q06', tier: 2, q: 'What is the result called when a player to move has no legal move and is not in check?', choices: ['Checkmate', 'Resignation', 'Stalemate', 'Zugzwang'], correct: 2 },
  { id: 'd23q07', tier: 3, q: 'What is the special king and rook move called?', choices: ['Fianchetto', 'Castling', 'En passant', 'Promotion'], correct: 1 },
  { id: 'd23q08', tier: 3, q: 'Which piece can never leave the color of square it started on?', choices: ['The queen', 'The bishop', 'The knight', 'The rook'], correct: 1 },
  { id: 'd23q09', tier: 3, q: 'What is the opening move 1.e4 e5 2.Nf3 Nc6 3.Bb5 called?', choices: ['The Italian Game', 'The Four Knights', 'The Ruy Lopez', 'The Scotch Game'], correct: 2 },
  { id: 'd23q10', tier: 4, q: 'Which American became world champion in 1972 by beating Boris Spassky?', choices: ['Paul Keres', 'Sam Reshevsky', 'Reuben Fine', 'Bobby Fischer'], correct: 3 },
  { id: 'd23q11', tier: 4, q: 'Which computer beat the reigning world champion in a match in 1997?', choices: ['Deep Blue', 'Hydra', 'Deep Thought', 'Fritz'], correct: 0 },
  { id: 'd23q12', tier: 4, q: 'What is the capture of a pawn that has just moved two squares, taken as if it moved one, called?', choices: ['The passed capture', 'The pawn storm', 'Underpromotion', 'En passant'], correct: 3 },
  { id: 'd23q13', tier: 5, q: 'Who was the first official world champion, crowned in 1886?', choices: ['Emanuel Lasker', 'Adolf Anderssen', 'Wilhelm Steinitz', 'Paul Morphy'], correct: 2 },
  { id: 'd23q14', tier: 5, q: 'Which champion held the title for 27 years, the longest reign?', choices: ['Emanuel Lasker', 'Jose Raul Capablanca', 'Mikhail Botvinnik', 'Alexander Alekhine'], correct: 0 },
  { id: 'd23q15', tier: 5, q: 'What is the term for a position where any move a player makes worsens their position?', choices: ['Prophylaxis', 'Zugzwang', 'Tempo loss', 'Zwischenzug'], correct: 1 },
  { id: 'd24q01', tier: 1, q: 'Which river flows through Cairo?', choices: ['The Niger', 'The Congo', 'The Nile', 'The Zambezi'], correct: 2 },
  { id: 'd24q02', tier: 1, q: 'Which river runs through London?', choices: ['The Severn', 'The Trent', 'The Mersey', 'The Thames'], correct: 3 },
  { id: 'd24q03', tier: 1, q: 'What is the mouth of a river where it fans into many channels called?', choices: ['A fjord', 'A cirque', 'An estuary bar', 'A delta'], correct: 3 },
  { id: 'd24q04', tier: 2, q: 'Which river drains the world’s largest rainforest?', choices: ['The Amazon', 'The Orinoco', 'The Parana', 'The Rio Negro'], correct: 0 },
  { id: 'd24q05', tier: 2, q: 'Which river flows through Paris?', choices: ['The Garonne', 'The Rhone', 'The Loire', 'The Seine'], correct: 3 },
  { id: 'd24q06', tier: 2, q: 'Which American river is the country’s longest single river?', choices: ['The Mississippi', 'The Missouri', 'The Colorado', 'The Ohio'], correct: 1 },
  { id: 'd24q07', tier: 3, q: 'Which river is sacred to Hindus and flows past Varanasi?', choices: ['The Yamuna', 'The Brahmaputra', 'The Ganges', 'The Indus'], correct: 2 },
  { id: 'd24q08', tier: 3, q: 'Which river carved the Grand Canyon?', choices: ['The Colorado', 'The Snake', 'The Green', 'The Rio Grande'], correct: 0 },
  { id: 'd24q09', tier: 3, q: 'Which river runs through Vienna, Budapest and Belgrade?', choices: ['The Elbe', 'The Danube', 'The Vistula', 'The Dnieper'], correct: 1 },
  { id: 'd24q10', tier: 4, q: 'Which is the longest river in Europe?', choices: ['The Rhine', 'The Dnieper', 'The Volga', 'The Danube'], correct: 2 },
  { id: 'd24q11', tier: 4, q: 'Which is the longest river in Asia?', choices: ['The Mekong', 'The Ob', 'The Yangtze', 'The Yellow River'], correct: 2 },
  { id: 'd24q12', tier: 4, q: 'Which two rivers framed ancient Mesopotamia?', choices: ['The Karun and Halys', 'The Tigris and Euphrates', 'The Nile and Litani', 'The Jordan and Orontes'], correct: 1 },
  { id: 'd24q13', tier: 5, q: 'Which river forms much of the border between Texas and Mexico?', choices: ['The Rio Grande', 'The Nueces', 'The Brazos', 'The Pecos'], correct: 0 },
  { id: 'd24q14', tier: 5, q: 'Which African river plunges over Victoria Falls?', choices: ['The Okavango', 'The Limpopo', 'The Orange', 'The Zambezi'], correct: 3 },
  { id: 'd24q15', tier: 5, q: 'Which river, second longest in South America, feeds the Itaipu dam?', choices: ['The Parana', 'The Magdalena', 'The Orinoco', 'The Sao Francisco'], correct: 0 },
  { id: 'd25q01', tier: 1, q: 'Which American city is usually called the birthplace of the music?', choices: ['Chicago', 'Kansas City', 'Memphis', 'New Orleans'], correct: 3 },
  { id: 'd25q02', tier: 1, q: 'Which gravel-voiced trumpeter sang What a Wonderful World?', choices: ['Dizzy Gillespie', 'Duke Ellington', 'Nat King Cole', 'Louis Armstrong'], correct: 3 },
  { id: 'd25q03', tier: 1, q: 'What is the term for making up a solo on the spot?', choices: ['Syncopation', 'Improvisation', 'Transcription', 'Modulation'], correct: 1 },
  { id: 'd25q04', tier: 2, q: 'Which bandleader and composer led the orchestra at the Cotton Club and wrote Mood Indigo?', choices: ['Duke Ellington', 'Cab Calloway', 'Fletcher Henderson', 'Count Basie'], correct: 0 },
  { id: 'd25q05', tier: 2, q: 'What is wordless singing on nonsense syllables called?', choices: ['Riffing', 'Doo-wop', 'Vibrato', 'Scat'], correct: 3 },
  { id: 'd25q06', tier: 2, q: 'Which singer was nicknamed Lady Day?', choices: ['Dinah Washington', 'Ella Fitzgerald', 'Billie Holiday', 'Sarah Vaughan'], correct: 2 },
  { id: 'd25q07', tier: 3, q: 'Which 1959 album by Miles Davis is the best selling in the genre?', choices: ['Birth of the Cool', 'Kind of Blue', 'Sketches of Spain', 'Bitches Brew'], correct: 1 },
  { id: 'd25q08', tier: 3, q: 'Which fast, harmonically dense style emerged in the 1940s?', choices: ['Swing', 'Cool jazz', 'Bebop', 'Dixieland'], correct: 2 },
  { id: 'd25q09', tier: 3, q: 'Which saxophonist recorded A Love Supreme?', choices: ['Sonny Rollins', 'Dexter Gordon', 'John Coltrane', 'Wayne Shorter'], correct: 2 },
  { id: 'd25q10', tier: 4, q: 'Which alto saxophonist was nicknamed Bird?', choices: ['Benny Carter', 'Charlie Parker', 'Johnny Hodges', 'Cannonball Adderley'], correct: 1 },
  { id: 'd25q11', tier: 4, q: 'Which pianist and composer wrote Maple Leaf Rag, a ragtime ancestor of the music?', choices: ['Scott Joplin', 'Jelly Roll Morton', 'Fats Waller', 'James P. Johnson'], correct: 0 },
  { id: 'd25q12', tier: 4, q: 'Which 1959 Dave Brubeck album is built on odd meters like five-four?', choices: ['Time Out', 'Jazz Goes to College', 'Brubeck Plays Brubeck', 'Jazz Impressions'], correct: 0 },
  { id: 'd25q13', tier: 5, q: 'Which saxophonist’s 1959 album The Shape of Jazz to Come launched free jazz?', choices: ['Eric Dolphy', 'Ornette Coleman', 'Archie Shepp', 'Albert Ayler'], correct: 1 },
  { id: 'd25q14', tier: 5, q: 'Which pianist, known for angular playing, wrote Round Midnight?', choices: ['Bud Powell', 'Herbie Hancock', 'Bill Evans', 'Thelonious Monk'], correct: 3 },
  { id: 'd25q15', tier: 5, q: 'Which city’s Reno Club scene produced Count Basie’s hard-swinging band?', choices: ['Kansas City', 'Detroit', 'St. Louis', 'Cleveland'], correct: 0 },
  { id: 'd26q01', tier: 1, q: 'What instrument measures temperature?', choices: ['A hygrometer', 'A barometer', 'A thermometer', 'An anemometer'], correct: 2 },
  { id: 'd26q02', tier: 1, q: 'What is frozen rain that falls as balls of ice called?', choices: ['Sleet', 'Frost', 'Hail', 'Graupel'], correct: 2 },
  { id: 'd26q03', tier: 1, q: 'What arc of colors appears when sunlight passes through raindrops?', choices: ['A corona', 'A halo', 'A sundog', 'A rainbow'], correct: 3 },
  { id: 'd26q04', tier: 2, q: 'What instrument measures air pressure?', choices: ['A rain gauge', 'A barometer', 'A thermometer', 'An anemometer'], correct: 1 },
  { id: 'd26q05', tier: 2, q: 'What is a violently rotating column of air touching the ground called?', choices: ['A hurricane', 'A haboob', 'A derecho', 'A tornado'], correct: 3 },
  { id: 'd26q06', tier: 2, q: 'Which cloud type towers upward and brings thunderstorms?', choices: ['Cumulonimbus', 'Cirrus', 'Stratus', 'Altocumulus'], correct: 0 },
  { id: 'd26q07', tier: 3, q: 'What is the wispy, high, ice-crystal cloud called?', choices: ['Cumulus', 'Nimbostratus', 'Stratocumulus', 'Cirrus'], correct: 3 },
  { id: 'd26q08', tier: 3, q: 'Which scale rates the strength of a tornado?', choices: ['The Beaufort scale', 'The Fujita scale', 'The Saffir-Simpson scale', 'The Mercalli scale'], correct: 1 },
  { id: 'd26q09', tier: 3, q: 'What is the calm center of a hurricane called?', choices: ['The still', 'The vortex well', 'The core', 'The eye'], correct: 3 },
  { id: 'd26q10', tier: 4, q: 'Which scale rates wind force from calm to hurricane at sea?', choices: ['The Saffir-Simpson scale', 'The Douglas scale', 'The Beaufort scale', 'The Fujita scale'], correct: 2 },
  { id: 'd26q11', tier: 4, q: 'What is the boundary where a cold air mass pushes under warm air called?', choices: ['A warm front', 'A trough line', 'A cold front', 'An occluded front'], correct: 2 },
  { id: 'd26q12', tier: 4, q: 'What effect, caused by Earth’s rotation, curves the path of winds?', choices: ['The Coriolis effect', 'The Magnus effect', 'The Venturi effect', 'The Foehn effect'], correct: 0 },
  { id: 'd26q13', tier: 5, q: 'What is the fast, narrow ribbon of high-altitude wind called?', choices: ['The jet stream', 'The Hadley band', 'The polar drift', 'The trade belt'], correct: 0 },
  { id: 'd26q14', tier: 5, q: 'What is the temperature at which air becomes saturated and dew forms called?', choices: ['The lapse point', 'The dew point', 'The wet bulb', 'The frost line'], correct: 1 },
  { id: 'd26q15', tier: 5, q: 'What is the warm dry wind that descends the lee side of a mountain range called?', choices: ['A sirocco', 'A foehn wind', 'A mistral', 'A monsoon'], correct: 1 },
  { id: 'd27q01', tier: 1, q: 'What is the capital city?', choices: ['Kyoto', 'Tokyo', 'Nagoya', 'Osaka'], correct: 1 },
  { id: 'd27q02', tier: 1, q: 'What is the snow-capped volcano that is the country’s highest peak?', choices: ['Mount Hakusan', 'Mount Aso', 'Mount Fuji', 'Mount Ontake'], correct: 2 },
  { id: 'd27q03', tier: 1, q: 'What is the raw fish and vinegared rice dish called?', choices: ['Ramen', 'Udon', 'Tempura', 'Sushi'], correct: 3 },
  { id: 'd27q04', tier: 2, q: 'What is the currency?', choices: ['The yen', 'The baht', 'The won', 'The yuan'], correct: 0 },
  { id: 'd27q05', tier: 2, q: 'Which warrior class served the feudal lords?', choices: ['The ronin', 'The samurai', 'The daimyo', 'The shogun'], correct: 1 },
  { id: 'd27q06', tier: 2, q: 'What is the country’s traditional wrestling sport?', choices: ['Judo', 'Aikido', 'Kendo', 'Sumo'], correct: 3 },
  { id: 'd27q07', tier: 3, q: 'Which former capital is famous for its temples and geisha district?', choices: ['Kyoto', 'Kamakura', 'Nara', 'Kanazawa'], correct: 0 },
  { id: 'd27q08', tier: 3, q: 'Which of the four main islands is the largest?', choices: ['Hokkaido', 'Honshu', 'Shikoku', 'Kyushu'], correct: 1 },
  { id: 'd27q09', tier: 3, q: 'What is the indigenous religion of kami and shrines called?', choices: ['Shinto', 'Tendai', 'Shugendo', 'Zen'], correct: 0 },
  { id: 'd27q10', tier: 4, q: 'What is the high-speed train network known as?', choices: ['The Yamanote', 'The Tokaido Express', 'The Shinkansen', 'The Keihin'], correct: 2 },
  { id: 'd27q11', tier: 4, q: 'Which era, from 1603 to 1868, saw rule by the Tokugawa shoguns?', choices: ['The Meiji period', 'The Muromachi period', 'The Edo period', 'The Heian period'], correct: 2 },
  { id: 'd27q12', tier: 4, q: 'Which 11th-century courtier wrote The Tale of Genji?', choices: ['Sei Shonagon', 'Izumi Shikibu', 'Ki no Tsurayuki', 'Murasaki Shikibu'], correct: 3 },
  { id: 'd27q13', tier: 5, q: 'Which artist made the woodblock print of a wave off Kanagawa?', choices: ['Sharaku', 'Hokusai', 'Utamaro', 'Hiroshige'], correct: 1 },
  { id: 'd27q14', tier: 5, q: 'Which 1868 restoration returned formal power to the emperor?', choices: ['The Kenmu Restoration', 'The Taisho Restoration', 'The Meiji Restoration', 'The Showa Restoration'], correct: 2 },
  { id: 'd27q15', tier: 5, q: 'Which strait separates the two largest islands, now crossed by an undersea tunnel?', choices: ['The Tsugaru Strait', 'The Kanmon Strait', 'The Bungo Channel', 'The Soya Strait'], correct: 0 },
  { id: 'd28q01', tier: 1, q: 'Who wrote Pride and Prejudice?', choices: ['Elizabeth Gaskell', 'Jane Austen', 'Charlotte Bronte', 'George Eliot'], correct: 1 },
  { id: 'd28q02', tier: 1, q: 'Which novel opens with a boy asking for more gruel in a workhouse?', choices: ['Nicholas Nickleby', 'Great Expectations', 'Oliver Twist', 'David Copperfield'], correct: 2 },
  { id: 'd28q03', tier: 1, q: 'Which Russian novel follows Natasha, Pierre and Andrei through Napoleon’s invasion?', choices: ['War and Peace', 'Crime and Punishment', 'Anna Karenina', 'Fathers and Sons'], correct: 0 },
  { id: 'd28q04', tier: 2, q: 'Which novel begins Call me Ishmael?', choices: ['The Old Man and the Sea', 'Treasure Island', 'Moby-Dick', 'Billy Budd'], correct: 2 },
  { id: 'd28q05', tier: 2, q: 'Who wrote Crime and Punishment?', choices: ['Dostoevsky', 'Chekhov', 'Gogol', 'Turgenev'], correct: 0 },
  { id: 'd28q06', tier: 2, q: 'Which Bronte sister wrote Jane Eyre?', choices: ['Emily', 'Anne', 'Maria', 'Charlotte'], correct: 3 },
  { id: 'd28q07', tier: 3, q: 'Which novel’s narrator Nick Carraway rents a cottage next to a mansion on Long Island?', choices: ['Tender Is the Night', 'The Great Gatsby', 'An American Tragedy', 'The Age of Innocence'], correct: 1 },
  { id: 'd28q08', tier: 3, q: 'Who wrote One Hundred Years of Solitude?', choices: ['Julio Cortazar', 'Gabriel Garcia Marquez', 'Jorge Luis Borges', 'Mario Vargas Llosa'], correct: 1 },
  { id: 'd28q09', tier: 3, q: 'Which novel by George Orwell imagines a state watched by Big Brother?', choices: ['Nineteen Eighty-Four', 'Brave New World', 'We', 'Animal Farm'], correct: 0 },
  { id: 'd28q10', tier: 4, q: 'Which French novel follows the convict Jean Valjean?', choices: ['Les Miserables', 'Germinal', 'The Red and the Black', 'The Count of Monte Cristo'], correct: 0 },
  { id: 'd28q11', tier: 4, q: 'Which Irish novel unfolds over one Dublin day in June 1904?', choices: ['The Third Policeman', 'Dubliners', 'Ulysses', 'At Swim-Two-Birds'], correct: 2 },
  { id: 'd28q12', tier: 4, q: 'Which Spanish novel follows a knight who tilts at windmills?', choices: ['Fortunata and Jacinta', 'Lazarillo de Tormes', 'The Swindler', 'Don Quixote'], correct: 3 },
  { id: 'd28q13', tier: 5, q: 'Which Thomas Mann novel is set in a sanatorium in the Swiss Alps?', choices: ['Death in Venice', 'Doctor Faustus', 'Buddenbrooks', 'The Magic Mountain'], correct: 3 },
  { id: 'd28q14', tier: 5, q: 'Which novel by Melville’s contemporary Nathaniel Hawthorne centers on Hester Prynne?', choices: ['The Marble Faun', 'The House of the Seven Gables', 'The Scarlet Letter', 'The Blithedale Romance'], correct: 2 },
  { id: 'd28q15', tier: 5, q: 'Which Proust work is a seven-volume novel begun with a madeleine dipped in tea?', choices: ['Pleasures and Days', 'Jean Santeuil', 'The Guermantes Chronicle', 'In Search of Lost Time'], correct: 3 },
  { id: 'd29q01', tier: 1, q: 'Which is the highest mountain above sea level?', choices: ['Kilimanjaro', 'Everest', 'K2', 'Denali'], correct: 1 },
  { id: 'd29q02', tier: 1, q: 'Which range runs through Switzerland, Austria and northern Italy?', choices: ['The Pyrenees', 'The Carpathians', 'The Alps', 'The Apennines'], correct: 2 },
  { id: 'd29q03', tier: 1, q: 'Which range holds the world’s highest peaks, along the edge of Nepal and Tibet?', choices: ['The Karakoram', 'The Himalayas', 'The Andes', 'The Hindu Kush'], correct: 1 },
  { id: 'd29q04', tier: 2, q: 'Which is the highest mountain in Africa?', choices: ['Mount Kenya', 'Ras Dashen', 'Kilimanjaro', 'Mount Stanley'], correct: 2 },
  { id: 'd29q05', tier: 2, q: 'Which is the longest mountain range on land?', choices: ['The Urals', 'The Rockies', 'The Himalayas', 'The Andes'], correct: 3 },
  { id: 'd29q06', tier: 2, q: 'Which two men reached the summit of Everest first, in 1953?', choices: ['Mallory and Irvine', 'Hillary and Tenzing', 'Hunt and Bourdillon', 'Bonington and Scott'], correct: 1 },
  { id: 'd29q07', tier: 3, q: 'Which is the second-highest mountain in the world?', choices: ['K2', 'Makalu', 'Lhotse', 'Kangchenjunga'], correct: 0 },
  { id: 'd29q08', tier: 3, q: 'Which is the highest peak in North America?', choices: ['Denali', 'Mount Logan', 'Mount Whitney', 'Pico de Orizaba'], correct: 0 },
  { id: 'd29q09', tier: 3, q: 'Which range separates Europe from Asia in Russia?', choices: ['The Altai', 'The Sayan', 'The Urals', 'The Caucasus'], correct: 2 },
  { id: 'd29q10', tier: 4, q: 'How many peaks on Earth rise above 8,000 meters?', choices: ['14', '18', '10', '12'], correct: 0 },
  { id: 'd29q11', tier: 4, q: 'Which is the highest mountain in Europe, in the Caucasus?', choices: ['Elbrus', 'Kazbek', 'The Matterhorn', 'Mont Blanc'], correct: 0 },
  { id: 'd29q12', tier: 4, q: 'Which climber famously disappeared near Everest’s summit ridge in 1924?', choices: ['Edward Norton', 'Howard Somervell', 'Eric Shipton', 'George Mallory'], correct: 3 },
  { id: 'd29q13', tier: 5, q: 'Which peak’s summit is the farthest point on the surface from Earth’s center?', choices: ['Huascaran', 'Cotopaxi', 'Aconcagua', 'Chimborazo'], correct: 3 },
  { id: 'd29q14', tier: 5, q: 'Which mountain, measured from its base on the seafloor, is the tallest on Earth?', choices: ['Mauna Loa', 'Mauna Kea', 'Mount Fuji', 'Pico'], correct: 1 },
  { id: 'd29q15', tier: 5, q: 'What is the deadly altitude above roughly 8,000 meters usually called?', choices: ['The ice fall', 'The col band', 'The death zone', 'The cornice line'], correct: 2 },
  { id: 'd30q01', tier: 1, q: 'From which part of Europe did they come?', choices: ['The Low Countries', 'The Baltic coast of Poland', 'Scandinavia', 'Brittany'], correct: 2 },
  { id: 'd30q02', tier: 1, q: 'What kind of vessel did they raid and trade in?', choices: ['The galleon', 'The longship', 'The junk', 'The trireme'], correct: 1 },
  { id: 'd30q03', tier: 1, q: 'Which one-eyed god ruled their pantheon?', choices: ['Odin', 'Thor', 'Loki', 'Freyr'], correct: 0 },
  { id: 'd30q04', tier: 2, q: 'Which hall did slain warriors hope to reach?', choices: ['Midgard', 'Asgard’s gate', 'Helheim', 'Valhalla'], correct: 3 },
  { id: 'd30q05', tier: 2, q: 'Which god wielded the hammer Mjolnir?', choices: ['Thor', 'Tyr', 'Baldr', 'Heimdall'], correct: 0 },
  { id: 'd30q06', tier: 2, q: 'Which English monastery was famously raided in 793?', choices: ['Whitby', 'Iona', 'Lindisfarne', 'Jarrow'], correct: 2 },
  { id: 'd30q07', tier: 3, q: 'What was the writing system of carved angular letters called?', choices: ['Futharkless script', 'Glagolitic', 'Ogham', 'Runes'], correct: 3 },
  { id: 'd30q08', tier: 3, q: 'Which explorer is credited with reaching North America around the year 1000?', choices: ['Erik the Red', 'Leif Erikson', 'Thorfinn Karlsefni', 'Bjarni Herjolfsson'], correct: 1 },
  { id: 'd30q09', tier: 3, q: 'Which large area of England came under their law in the ninth century?', choices: ['The Pale', 'Wessex', 'The Marches', 'The Danelaw'], correct: 3 },
  { id: 'd30q10', tier: 4, q: 'What name did they give their North American landfall of vines and timber?', choices: ['Markland', 'Greenland', 'Vinland', 'Helluland'], correct: 2 },
  { id: 'd30q11', tier: 4, q: 'Which Newfoundland site preserves a Norse settlement?', choices: ['Gardar', 'Hvalsey', 'L’Anse aux Meadows', 'Brattahlid'], correct: 2 },
  { id: 'd30q12', tier: 4, q: 'Which Norse assembly, the ancestor of parliaments, met in the open air?', choices: ['The Thing', 'The Diet', 'The Moot Hall', 'The Witan'], correct: 0 },
  { id: 'd30q13', tier: 5, q: 'Which Norwegian king’s defeat at Stamford Bridge in 1066 is often called the end of the age?', choices: ['Harald Bluetooth', 'Olaf Tryggvason', 'Magnus the Good', 'Harald Hardrada'], correct: 3 },
  { id: 'd30q14', tier: 5, q: 'Which duchy in northern France was granted to a Norse leader in 911?', choices: ['Aquitaine', 'Normandy', 'Brittany', 'Flanders'], correct: 1 },
  { id: 'd30q15', tier: 5, q: 'What is the prophesied final battle of the gods called?', choices: ['Yggdrasil', 'Ragnarok', 'Fimbulwinter', 'Gjallarhorn'], correct: 1 },
];

export const QUESTION_MAP = Object.fromEntries(QUESTIONS.map((q) => [q.id, q]));
