// Puzzle data for the daily game. Imported ONLY by the server page
// component, which filters to live<=today before passing puzzles to
// the client — so future puzzles (and their answers) never ship to the
// browser bundle.
// AUTHORING RULE (owner ruling 2026-07-15): every puzzle must carry AT LEAST
// TWO cross-category collisions — words that plausibly read as another
// category on the same board — ideally more, while keeping exactly ONE valid
// filing. Pin every trap by elimination: a trap word's fake home must already
// be full of its own true members (homophone teases are free extras — they
// can never validate semantically).
export const PUZZLES = [
  {
    num: 1,
    quizId: 'crux-7-6-26',
    live: '2026-07-06',
    dateLabel: 'July 6, 2026',
    guesses: 18,
    rows: 9,
    cols: 10,
    categories: [
      { name: 'Card games', words: ['HEARTS', 'BRIDGE'] },
      { name: 'Musical instruments', words: ['ORGAN', 'VIOLA'] },
      { name: 'Body parts', words: ['SPLEEN', 'TEMPLE'] },
      { name: 'Structures', words: ['TOWER', 'STEEPLE'] },
    ],
    slots: [
      { id: '1D', word: 'VIOLA', row: 0, col: 1, dir: 'D' },
      { id: '2D', word: 'HEARTS', row: 1, col: 3, dir: 'D' },
      { id: '3D', word: 'BRIDGE', row: 1, col: 9, dir: 'D' },
      { id: '4A', word: 'TOWER', row: 2, col: 0, dir: 'A' },
      { id: '5D', word: 'SPLEEN', row: 3, col: 5, dir: 'D' },
      { id: '6D', word: 'TEMPLE', row: 3, col: 7, dir: 'D' },
      { id: '7A', word: 'STEEPLE', row: 6, col: 3, dir: 'A' },
      { id: '8A', word: 'ORGAN', row: 8, col: 1, dir: 'A' },
    ],
  },
  {
    num: 2,
    quizId: 'crux-7-7-26',
    live: '2026-07-07',
    dateLabel: 'July 7, 2026',
    guesses: 18,
    rows: 9,
    cols: 9,
    // Trap cycle: PUNCH looks boxing (it's a drink), SWING looks boxing (it's
    // a dance), HOOK looks fishing (it's a punch), REEL looks like a dance
    // (it's fishing gear). HOOK even crosses TACKLE on the board.
    categories: [
      { name: 'Party drinks', words: ['PUNCH', 'CIDER'] },
      { name: 'Dances', words: ['SWING', 'TANGO'] },
      { name: 'Boxing blows', words: ['HOOK', 'UPPERCUT'] },
      { name: 'Fishing gear', words: ['REEL', 'TACKLE'] },
    ],
    slots: [
      { id: '1A', word: 'PUNCH', row: 0, col: 2, dir: 'A' },
      { id: '2D', word: 'HOOK', row: 0, col: 6, dir: 'D' },
      { id: '3D', word: 'UPPERCUT', row: 0, col: 8, dir: 'D' },
      { id: '4D', word: 'TANGO', row: 2, col: 4, dir: 'D' },
      { id: '5A', word: 'TACKLE', row: 3, col: 3, dir: 'A' },
      { id: '6D', word: 'CIDER', row: 4, col: 2, dir: 'D' },
      { id: '7A', word: 'SWING', row: 5, col: 0, dir: 'A' },
      { id: '8A', word: 'REEL', row: 8, col: 2, dir: 'A' },
    ],
  },
  {
    num: 3,
    quizId: 'crux-7-8-26',
    live: '2026-07-08',
    dateLabel: 'July 8, 2026',
    guesses: 18,
    rows: 9,
    cols: 8,
    rev: 2,
    // rev 2 (2026-07-08): ARCH/CALF -> ELBOW/WRIST. The old body pair was
    // interchangeable with the shoe pair (arch supports, boot calves) —
    // two valid solutions. TONGUE/SOLE/SCALE keep the traps, all resolvable.
    categories: [
      { name: 'Fish', words: ['PERCH', 'SOLE'] },
      { name: 'Shoe parts', words: ['HEEL', 'TONGUE'] },
      { name: 'Body parts', words: ['ELBOW', 'WRIST'] },
      { name: 'Music terms', words: ['SCALE', 'PITCH'] },
    ],
    slots: [
      { id: '1A', word: 'WRIST', row: 0, col: 3, dir: 'A' },
      { id: '2D', word: 'TONGUE', row: 0, col: 7, dir: 'D' },
      { id: '3A', word: 'PERCH', row: 3, col: 0, dir: 'A' },
      { id: '3D', word: 'PITCH', row: 3, col: 0, dir: 'D' },
      { id: '4A', word: 'SCALE', row: 5, col: 3, dir: 'A' },
      { id: '4D', word: 'SOLE', row: 5, col: 3, dir: 'D' },
      { id: '5A', word: 'HEEL', row: 7, col: 0, dir: 'A' },
      { id: '6A', word: 'ELBOW', row: 8, col: 3, dir: 'A' },
    ],
  },
  {
    num: 4,
    quizId: 'crux-7-9-26',
    live: '2026-07-09',
    dateLabel: 'July 9, 2026',
    guesses: 18,
    rows: 10,
    cols: 9,
    categories: [
      { name: 'Baking', words: ['DOUGH', 'BATTER'] },
      { name: 'Money slang', words: ['BUCK', 'LOOT'] },
      { name: 'Baseball', words: ['MOUND', 'DIAMOND'] },
      { name: 'Gems', words: ['PEARL', 'OPAL'] },
    ],
    slots: [
      { id: '1D', word: 'PEARL', row: 0, col: 8, dir: 'D' },
      { id: '2A', word: 'MOUND', row: 1, col: 0, dir: 'A' },
      { id: '3D', word: 'OPAL', row: 1, col: 1, dir: 'D' },
      { id: '4D', word: 'DIAMOND', row: 1, col: 4, dir: 'D' },
      { id: '5A', word: 'BATTER', row: 3, col: 3, dir: 'A' },
      { id: '6A', word: 'LOOT', row: 5, col: 2, dir: 'A' },
      { id: '7D', word: 'BUCK', row: 6, col: 6, dir: 'D' },
      { id: '8A', word: 'DOUGH', row: 7, col: 4, dir: 'A' },
    ],
  },
  {
    num: 5,
    quizId: 'crux-7-10-26',
    live: '2026-07-10',
    dateLabel: 'July 10, 2026',
    guesses: 18,
    rows: 9,
    cols: 9,
    categories: [
      { name: 'Laundry day', words: ['FOLD', 'HAMPER'] },
      { name: 'Poker terms', words: ['FLUSH', 'ANTE'] },
      { name: 'Birds', words: ['CRANE', 'SWALLOW'] },
      { name: 'Golf terms', words: ['IRON', 'EAGLE'] },
    ],
    slots: [
      { id: '1D', word: 'FLUSH', row: 0, col: 2, dir: 'D' },
      { id: '2D', word: 'EAGLE', row: 0, col: 6, dir: 'D' },
      { id: '3A', word: 'FOLD', row: 1, col: 0, dir: 'A' },
      { id: '4D', word: 'HAMPER', row: 2, col: 4, dir: 'D' },
      { id: '5A', word: 'SWALLOW', row: 3, col: 2, dir: 'A' },
      { id: '6D', word: 'IRON', row: 5, col: 1, dir: 'D' },
      { id: '7A', word: 'CRANE', row: 6, col: 0, dir: 'A' },
      { id: '8A', word: 'ANTE', row: 8, col: 0, dir: 'A' },
    ],
  },
  {
    num: 6,
    quizId: 'crux-7-11-26',
    live: '2026-07-11',
    dateLabel: 'July 11, 2026',
    guesses: 18,
    rows: 6,
    cols: 11,
    categories: [
      { name: 'Fruits', words: ['DATE', 'MANGO'] },
      { name: 'Toast spreads', words: ['JAM', 'BUTTER'] },
      { name: 'Music genres', words: ['ROCK', 'METAL'] },
      { name: 'Terms of endearment', words: ['HONEY', 'PEACH'] },
    ],
    slots: [
      { id: '1A', word: 'JAM', row: 0, col: 0, dir: 'A' },
      { id: '2D', word: 'METAL', row: 0, col: 2, dir: 'D' },
      { id: '3D', word: 'PEACH', row: 1, col: 4, dir: 'D' },
      { id: '4A', word: 'BUTTER', row: 2, col: 0, dir: 'A' },
      { id: '5D', word: 'DATE', row: 2, col: 7, dir: 'D' },
      { id: '6D', word: 'ROCK', row: 2, col: 10, dir: 'D' },
      { id: '7A', word: 'MANGO', row: 3, col: 6, dir: 'A' },
      { id: '8A', word: 'HONEY', row: 5, col: 4, dir: 'A' },
    ],
  },
  {
    num: 7,
    quizId: 'crux-7-12-26',
    live: '2026-07-12',
    dateLabel: 'July 12, 2026',
    sunday: true,
    // rev 2: slot 7 became the first Sunday Edition mid-day — the rev keys a
    // fresh localStorage save so anyone who started the displaced 8-worder
    // (now No. 29) doesn't load its state into this grid.
    rev: 2,
    guesses: 27,
    rows: 9,
    cols: 11,
    // Sunday Edition No. 1 (Sundays run bigger and harder by design — owner
    // ruling 2026-07-11). Three deceptions, all pinned by elimination:
    // VAULT reads gym apparatus (BEAM/RINGS/POMMEL fill the gym), RINGS reads
    // tree rings (ROOT has no other home), POMMEL reads sword part
    // (HILT/BLADE/EDGE fill the sword).
    categories: [
      { name: 'Tree parts', words: ['TRUNK', 'BARK', 'ROOT'] },
      { name: 'Bank things', words: ['VAULT', 'TELLER', 'BRANCH'] },
      { name: 'Sword parts', words: ['HILT', 'BLADE', 'EDGE'] },
      { name: 'Gym apparatus', words: ['BEAM', 'RINGS', 'POMMEL'] },
    ],
    slots: [
      { id: '1D', word: 'BEAM', row: 0, col: 3, dir: 'D' },
      { id: '2D', word: 'VAULT', row: 0, col: 10, dir: 'D' },
      { id: '3A', word: 'EDGE', row: 1, col: 0, dir: 'A' },
      { id: '4D', word: 'TELLER', row: 1, col: 5, dir: 'D' },
      { id: '5A', word: 'POMMEL', row: 3, col: 0, dir: 'A' },
      { id: '6D', word: 'BRANCH', row: 3, col: 7, dir: 'D' },
      { id: '7A', word: 'ROOT', row: 4, col: 7, dir: 'A' },
      { id: '8A', word: 'BLADE', row: 5, col: 1, dir: 'A' },
      { id: '8D', word: 'BARK', row: 5, col: 1, dir: 'D' },
      { id: '9A', word: 'RINGS', row: 6, col: 5, dir: 'A' },
      { id: '10A', word: 'TRUNK', row: 7, col: 0, dir: 'A' },
      { id: '11A', word: 'HILT', row: 8, col: 7, dir: 'A' },
    ],
  },
  {
    num: 8,
    quizId: 'crux-7-13-26',
    live: '2026-07-13',
    dateLabel: 'July 13, 2026',
    guesses: 18,
    rows: 9,
    cols: 8,
    rev: 2,
    // rev 2 (2026-07-08): NEPTUNE/JUPITER/VENUS were gods AND planets —
    // multiple valid solutions. EARTH+URANUS are planets but not Roman gods
    // (Uranus is Greek); JUNO+MINERVA are gods but not planets. MARS and
    // MERCURY keep the deception, both resolvable by elimination.
    categories: [
      { name: 'Candy bars', words: ['MARS', 'CRUNCH'] },
      { name: 'Chemical elements', words: ['MERCURY', 'CARBON'] },
      { name: 'Planets', words: ['EARTH', 'URANUS'] },
      { name: 'Roman gods', words: ['JUNO', 'MINERVA'] },
    ],
    slots: [
      { id: '1D', word: 'EARTH', row: 0, col: 5, dir: 'D' },
      { id: '2D', word: 'MERCURY', row: 1, col: 0, dir: 'D' },
      { id: '3A', word: 'MARS', row: 2, col: 3, dir: 'A' },
      { id: '3D', word: 'MINERVA', row: 2, col: 3, dir: 'D' },
      { id: '4A', word: 'CRUNCH', row: 4, col: 0, dir: 'A' },
      { id: '5D', word: 'JUNO', row: 5, col: 6, dir: 'D' },
      { id: '6A', word: 'URANUS', row: 6, col: 2, dir: 'A' },
      { id: '7A', word: 'CARBON', row: 8, col: 2, dir: 'A' },
    ],
  },
  {
    num: 9,
    quizId: 'crux-7-14-26',
    live: '2026-07-14',
    dateLabel: 'July 14, 2026',
    guesses: 18,
    rows: 9,
    cols: 8,
    categories: [
      { name: 'Pencil case', words: ['RULER', 'ERASER'] },
      { name: 'Flowers', words: ['TULIP', 'DAISY'] },
      { name: 'Eye parts', words: ['PUPIL', 'IRIS'] },
      { name: 'Royalty', words: ['CROWN', 'THRONE'] },
    ],
    slots: [
      { id: '1A', word: 'TULIP', row: 0, col: 1, dir: 'A' },
      { id: '2D', word: 'PUPIL', row: 0, col: 5, dir: 'D' },
      { id: '3D', word: 'THRONE', row: 2, col: 7, dir: 'D' },
      { id: '4D', word: 'ERASER', row: 3, col: 3, dir: 'D' },
      { id: '5D', word: 'DAISY', row: 4, col: 0, dir: 'D' },
      { id: '6A', word: 'RULER', row: 4, col: 3, dir: 'A' },
      { id: '7A', word: 'IRIS', row: 6, col: 0, dir: 'A' },
      { id: '8A', word: 'CROWN', row: 8, col: 2, dir: 'A' },
    ],
  },
  {
    num: 10,
    quizId: 'crux-7-15-26',
    live: '2026-07-15',
    dateLabel: 'July 15, 2026',
    guesses: 18,
    rows: 10,
    cols: 8,
    categories: [
      { name: 'Birds', words: ['RAVEN', 'FINCH'] },
      { name: 'Castle features', words: ['MOAT', 'TURRET'] },
      { name: 'Shades of black', words: ['EBONY', 'JET'] },
      { name: 'Chess pieces', words: ['KNIGHT', 'ROOK'] },
    ],
    slots: [
      { id: '1A', word: 'ROOK', row: 0, col: 4, dir: 'A' },
      { id: '2D', word: 'KNIGHT', row: 0, col: 7, dir: 'D' },
      { id: '3D', word: 'JET', row: 2, col: 0, dir: 'D' },
      { id: '4D', word: 'MOAT', row: 2, col: 2, dir: 'D' },
      { id: '5A', word: 'EBONY', row: 3, col: 0, dir: 'A' },
      { id: '6A', word: 'TURRET', row: 5, col: 2, dir: 'A' },
      { id: '7D', word: 'RAVEN', row: 5, col: 4, dir: 'D' },
      { id: '8A', word: 'FINCH', row: 9, col: 2, dir: 'A' },
    ],
  },
  {
    num: 11,
    quizId: 'crux-7-16-26',
    live: '2026-07-16',
    dateLabel: 'July 16, 2026',
    guesses: 18,
    rows: 7,
    cols: 10,
    categories: [
      { name: 'Long journeys', words: ['TREK', 'VOYAGE'] },
      { name: 'Water sources', words: ['WELL', 'GEYSER'] },
      { name: 'Ways to tumble', words: ['TRIP', 'STUMBLE'] },
      { name: 'Seasons', words: ['SPRING', 'FALL'] },
    ],
    slots: [
      { id: '1A', word: 'SPRING', row: 0, col: 1, dir: 'A' },
      { id: '1D', word: 'STUMBLE', row: 0, col: 1, dir: 'D' },
      { id: '2D', word: 'GEYSER', row: 0, col: 6, dir: 'D' },
      { id: '3D', word: 'TREK', row: 0, col: 9, dir: 'D' },
      { id: '4A', word: 'VOYAGE', row: 2, col: 4, dir: 'A' },
      { id: '5D', word: 'FALL', row: 3, col: 3, dir: 'D' },
      { id: '6A', word: 'TRIP', row: 5, col: 5, dir: 'A' },
      { id: '7A', word: 'WELL', row: 6, col: 0, dir: 'A' },
    ],
  },
  {
    num: 12,
    quizId: 'crux-7-17-26',
    live: '2026-07-17',
    dateLabel: 'July 17, 2026',
    guesses: 18,
    rows: 8,
    cols: 9,
    categories: [
      { name: 'Rocket parts', words: ['STAGE', 'BOOSTER'] },
      { name: 'Movie-set jobs', words: ['GRIP', 'GAFFER'] },
      { name: 'Car parts', words: ['CLUTCH', 'FENDER'] },
      { name: 'Firm holds', words: ['CLASP', 'GRASP'] },
    ],
    slots: [
      { id: '1D', word: 'CLUTCH', row: 0, col: 0, dir: 'D' },
      { id: '2A', word: 'GRIP', row: 0, col: 4, dir: 'A' },
      { id: '2D', word: 'GRASP', row: 0, col: 4, dir: 'D' },
      { id: '3D', word: 'GAFFER', row: 2, col: 6, dir: 'D' },
      { id: '4D', word: 'FENDER', row: 2, col: 8, dir: 'D' },
      { id: '5A', word: 'STAGE', row: 3, col: 4, dir: 'A' },
      { id: '6A', word: 'CLASP', row: 4, col: 0, dir: 'A' },
      { id: '7A', word: 'BOOSTER', row: 7, col: 0, dir: 'A' },
    ],
  },
  {
    num: 13,
    quizId: 'crux-7-18-26',
    live: '2026-07-18',
    dateLabel: 'July 18, 2026',
    guesses: 18,
    rows: 8,
    cols: 9,
    categories: [
      { name: 'Flower parts', words: ['PETAL', 'STEM'] },
      { name: 'Computer keys', words: ['SHIFT', 'ESCAPE'] },
      { name: 'Horse gear', words: ['BRIDLE', 'REINS'] },
      { name: 'Bike parts', words: ['PEDAL', 'SADDLE'] },
    ],
    slots: [
      { id: '1A', word: 'STEM', row: 0, col: 0, dir: 'A' },
      { id: '2D', word: 'ESCAPE', row: 0, col: 2, dir: 'D' },
      { id: '3D', word: 'BRIDLE', row: 0, col: 6, dir: 'D' },
      { id: '4D', word: 'PETAL', row: 0, col: 8, dir: 'D' },
      { id: '5A', word: 'SHIFT', row: 2, col: 4, dir: 'A' },
      { id: '5D', word: 'SADDLE', row: 2, col: 4, dir: 'D' },
      { id: '6A', word: 'PEDAL', row: 4, col: 2, dir: 'A' },
      { id: '7A', word: 'REINS', row: 7, col: 3, dir: 'A' },
    ],
  },
  {
    num: 14,
    quizId: 'crux-7-19-26',
    live: '2026-07-19',
    dateLabel: 'July 19, 2026',
    sunday: true,
    guesses: 27,
    rows: 12,
    cols: 10,
    // First SUNDAY EDITION: four categories of THREE (score /24). Traps all
    // pinned: CRICKET and SQUASH read as sports (their real homes fill the
    // sports slots), SEAL reads navy, BAT reads sports gear, SUB reads
    // sandwich, POLO reads shirts.
    categories: [
      { name: 'Vegetables', words: ['LEEK', 'RADISH', 'TURNIP'] },
      { name: 'Navy things', words: ['ANCHOR', 'SUB', 'FLEET'] },
      { name: 'Sports', words: ['SQUASH', 'RUGBY', 'POLO'] },
      { name: 'Animals', words: ['BAT', 'CRICKET', 'SEAL'] },
    ],
    slots: [
      { id: '1D', word: 'POLO', row: 0, col: 6, dir: 'D' },
      { id: '2A', word: 'ANCHOR', row: 1, col: 2, dir: 'A' },
      { id: '3D', word: 'CRICKET', row: 1, col: 4, dir: 'D' },
      { id: '4D', word: 'FLEET', row: 3, col: 2, dir: 'D' },
      { id: '5D', word: 'RADISH', row: 4, col: 8, dir: 'D' },
      { id: '6A', word: 'LEEK', row: 5, col: 1, dir: 'A' },
      { id: '7A', word: 'SEAL', row: 5, col: 6, dir: 'A' },
      { id: '8A', word: 'BAT', row: 7, col: 0, dir: 'A' },
      { id: '9A', word: 'TURNIP', row: 7, col: 4, dir: 'A' },
      { id: '10A', word: 'SQUASH', row: 9, col: 3, dir: 'A' },
      { id: '10D', word: 'SUB', row: 9, col: 3, dir: 'D' },
      { id: '11A', word: 'RUGBY', row: 11, col: 0, dir: 'A' },
    ],
  },
  {
    num: 15,
    quizId: 'crux-7-20-26',
    live: '2026-07-20',
    dateLabel: 'July 20, 2026',
    guesses: 18,
    rows: 7,
    cols: 9,
    categories: [
      { name: 'Tennis shots', words: ['LOB', 'VOLLEY'] },
      { name: 'Dog commands', words: ['SIT', 'STAY'] },
      { name: 'Hotel spaces', words: ['SUITE', 'LOBBY'] },
      { name: 'Congress things', words: ['SENATE', 'VETO'] },
    ],
    slots: [
      { id: '1D', word: 'SIT', row: 0, col: 2, dir: 'D' },
      { id: '2D', word: 'VETO', row: 0, col: 4, dir: 'D' },
      { id: '3D', word: 'STAY', row: 0, col: 8, dir: 'D' },
      { id: '4A', word: 'SUITE', row: 1, col: 0, dir: 'A' },
      { id: '4D', word: 'SENATE', row: 1, col: 0, dir: 'D' },
      { id: '5A', word: 'VOLLEY', row: 3, col: 3, dir: 'A' },
      { id: '6D', word: 'LOB', row: 3, col: 6, dir: 'D' },
      { id: '7A', word: 'LOBBY', row: 5, col: 3, dir: 'A' },
    ],
  },
  {
    num: 16,
    quizId: 'crux-7-21-26',
    live: '2026-07-21',
    dateLabel: 'July 21, 2026',
    guesses: 18,
    rows: 9,
    cols: 9,
    // rev 2 (2026-07-15, two-collision rule): OMELET -> ROLL. SNARE reads
    // hunting (snare trap; hunting is full — DECOY+CAMO) and ROLL reads drums
    // (drum roll; the kit is full — SNARE+CYMBAL). Both pinned by elimination.
    rev: 2,
    categories: [
      { name: 'Breakfast items', words: ['ROLL', 'WAFFLE'] },
      { name: 'Pans', words: ['SKILLET', 'WOK'] },
      { name: 'Hunting things', words: ['DECOY', 'CAMO'] },
      { name: 'Drum kit parts', words: ['SNARE', 'CYMBAL'] },
    ],
    slots: [
      { id: '1A', word: 'SKILLET', row: 0, col: 1, dir: 'A' },
      { id: '1D', word: 'SNARE', row: 0, col: 1, dir: 'D' },
      { id: '2A', word: 'CAMO', row: 2, col: 0, dir: 'A' },
      { id: '3D', word: 'CYMBAL', row: 3, col: 4, dir: 'D' },
      { id: '4A', word: 'DECOY', row: 4, col: 0, dir: 'A' },
      { id: '5D', word: 'ROLL', row: 4, col: 7, dir: 'D' },
      { id: '6A', word: 'WOK', row: 5, col: 6, dir: 'A' },
      { id: '7A', word: 'WAFFLE', row: 7, col: 3, dir: 'A' },
    ],
  },
  {
    num: 17,
    quizId: 'crux-7-22-26',
    live: '2026-07-22',
    dateLabel: 'July 22, 2026',
    guesses: 18,
    rows: 9,
    cols: 8,
    // rev 2 (2026-07-15, two-collision rule): PHASE -> SEA. The moon's seas
    // give a real second trap: SEA reads beach (beach is full — TIDE+DUNE),
    // and CLAUSE keeps teasing Santa (Claus — a homophone can't validate,
    // and the sleigh kit is full anyway).
    rev: 2,
    categories: [
      { name: 'Beach features', words: ['TIDE', 'DUNE'] },
      { name: "Santa's gear", words: ['SLEIGH', 'SACK'] },
      { name: 'Moon features', words: ['CRATER', 'SEA'] },
      { name: 'Grammar terms', words: ['TENSE', 'CLAUSE'] },
    ],
    slots: [
      { id: '1A', word: 'CRATER', row: 0, col: 2, dir: 'A' },
      { id: '2D', word: 'TENSE', row: 0, col: 5, dir: 'D' },
      { id: '3D', word: 'SACK', row: 2, col: 7, dir: 'D' },
      { id: '4D', word: 'SLEIGH', row: 3, col: 1, dir: 'D' },
      { id: '5D', word: 'DUNE', row: 3, col: 3, dir: 'D' },
      { id: '6A', word: 'SEA', row: 3, col: 5, dir: 'A' },
      { id: '7A', word: 'CLAUSE', row: 4, col: 0, dir: 'A' },
      { id: '8A', word: 'TIDE', row: 6, col: 0, dir: 'A' },
    ],
  },
  {
    num: 18,
    quizId: 'crux-7-23-26',
    live: '2026-07-23',
    dateLabel: 'July 23, 2026',
    guesses: 18,
    rows: 9,
    cols: 10,
    categories: [
      { name: 'Office supplies', words: ['STAPLER', 'BINDER'] },
      { name: 'Front-door things', words: ['KNOCKER', 'PORCH'] },
      { name: 'Book parts', words: ['SPINE', 'JACKET'] },
      { name: 'Gym things', words: ['BARBELL', 'MAT'] },
    ],
    slots: [
      { id: '1D', word: 'STAPLER', row: 0, col: 1, dir: 'D' },
      { id: '2D', word: 'MAT', row: 0, col: 5, dir: 'D' },
      { id: '3D', word: 'BINDER', row: 0, col: 7, dir: 'D' },
      { id: '4A', word: 'JACKET', row: 2, col: 0, dir: 'A' },
      { id: '5D', word: 'KNOCKER', row: 2, col: 3, dir: 'D' },
      { id: '6D', word: 'SPINE', row: 4, col: 5, dir: 'D' },
      { id: '7A', word: 'PORCH', row: 5, col: 5, dir: 'A' },
      { id: '8A', word: 'BARBELL', row: 8, col: 1, dir: 'A' },
    ],
  },
  {
    num: 19,
    quizId: 'crux-7-24-26',
    live: '2026-07-24',
    dateLabel: 'July 24, 2026',
    guesses: 18,
    rows: 9,
    cols: 9,
    // rev 2 (2026-07-15, two-collision rule): PROLOGUE -> HOOK. TWIST reads
    // story beat (plot twist; story is full — HOOK+CLIMAX) and HOOK reads
    // sewing kit (crochet hook, hook-and-eye; sewing is full — THIMBLE+
    // BOBBIN). One-way pins: THIMBLE/BOBBIN can't be story beats and
    // OLIVE can't be one, so neither trap can swap back.
    rev: 2,
    categories: [
      { name: 'Sewing kit', words: ['THIMBLE', 'BOBBIN'] },
      { name: 'Bar orders', words: ['NEAT', 'DOUBLE'] },
      { name: 'Story beats', words: ['HOOK', 'CLIMAX'] },
      { name: 'Cocktail garnishes', words: ['OLIVE', 'TWIST'] },
    ],
    slots: [
      { id: '1D', word: 'HOOK', row: 0, col: 0, dir: 'D' },
      { id: '2D', word: 'CLIMAX', row: 0, col: 2, dir: 'D' },
      { id: '3D', word: 'NEAT', row: 1, col: 4, dir: 'D' },
      { id: '4A', word: 'OLIVE', row: 2, col: 0, dir: 'A' },
      { id: '5D', word: 'THIMBLE', row: 2, col: 6, dir: 'D' },
      { id: '6A', word: 'TWIST', row: 4, col: 4, dir: 'A' },
      { id: '7A', word: 'BOBBIN', row: 6, col: 3, dir: 'A' },
      { id: '8A', word: 'DOUBLE', row: 8, col: 1, dir: 'A' },
    ],
  },
  {
    num: 20,
    quizId: 'crux-7-25-26',
    live: '2026-07-25',
    dateLabel: 'July 25, 2026',
    guesses: 18,
    rows: 9,
    cols: 9,
    categories: [
      { name: 'Coffee orders', words: ['LATTE', 'DECAF'] },
      { name: 'Exercises', words: ['SQUAT', 'LUNGE'] },
      { name: 'Shades of brown', words: ['MOCHA', 'TAN'] },
      { name: 'Pirate things', words: ['PLANK', 'PARROT'] },
    ],
    slots: [
      { id: '1D', word: 'PLANK', row: 0, col: 2, dir: 'D' },
      { id: '2D', word: 'DECAF', row: 2, col: 4, dir: 'D' },
      { id: '3A', word: 'LUNGE', row: 3, col: 0, dir: 'A' },
      { id: '3D', word: 'LATTE', row: 3, col: 0, dir: 'D' },
      { id: '4D', word: 'MOCHA', row: 4, col: 7, dir: 'D' },
      { id: '5A', word: 'PARROT', row: 5, col: 3, dir: 'A' },
      { id: '6A', word: 'TAN', row: 6, col: 0, dir: 'A' },
      { id: '7A', word: 'SQUAT', row: 8, col: 4, dir: 'A' },
    ],
  },
  {
    num: 21,
    quizId: 'crux-7-26-26',
    live: '2026-07-26',
    dateLabel: 'July 26, 2026',
    sunday: true,
    guesses: 27,
    rows: 10,
    cols: 11,
    // Sunday Edition #2. BUN is the pivot trap (hair vs burger — pinned:
    // hair has exactly three viable words). COMBO leans fast-food, DASH
    // leans sprinting, COLON leans anatomy; all pinned by full categories.
    categories: [
      { name: 'Punctuation marks', words: ['DASH', 'COLON', 'COMMA'] },
      { name: 'Burger parts', words: ['PATTY', 'PICKLE', 'ONION'] },
      { name: 'Music groups', words: ['TRIO', 'QUARTET', 'COMBO'] },
      { name: 'Hairstyles', words: ['BUN', 'BRAID', 'BANGS'] },
    ],
    slots: [
      { id: '1D', word: 'BRAID', row: 0, col: 3, dir: 'D' },
      { id: '2A', word: 'PATTY', row: 2, col: 2, dir: 'A' },
      { id: '3D', word: 'TRIO', row: 2, col: 5, dir: 'D' },
      { id: '4D', word: 'ONION', row: 2, col: 10, dir: 'D' },
      { id: '5A', word: 'BUN', row: 3, col: 8, dir: 'A' },
      { id: '5D', word: 'BANGS', row: 3, col: 8, dir: 'D' },
      { id: '6D', word: 'PICKLE', row: 4, col: 0, dir: 'D' },
      { id: '7A', word: 'COLON', row: 5, col: 4, dir: 'A' },
      { id: '7D', word: 'COMMA', row: 5, col: 4, dir: 'D' },
      { id: '8A', word: 'COMBO', row: 6, col: 0, dir: 'A' },
      { id: '9A', word: 'DASH', row: 7, col: 6, dir: 'A' },
      { id: '10A', word: 'QUARTET', row: 9, col: 2, dir: 'A' },
    ],
  },
  {
    num: 22,
    quizId: 'crux-7-27-26',
    live: '2026-07-27',
    dateLabel: 'July 27, 2026',
    guesses: 18,
    rows: 9,
    cols: 11,
    // rev 2 (2026-07-15, two-collision rule): SCARLET -> CARDINAL, and
    // 'Parts of a church' loosened to 'Church things'. BISHOP (chess) and
    // CARDINAL (shade of red) BOTH read church now — pinned because ALTAR+
    // PULPIT fill the church and neither of those can be red or a chess
    // piece. FAWN keeps its off-board deer/color tease.
    rev: 2,
    categories: [
      { name: 'Chess pieces', words: ['BISHOP', 'PAWN'] },
      { name: 'Church things', words: ['ALTAR', 'PULPIT'] },
      { name: 'Shades of red', words: ['CRIMSON', 'CARDINAL'] },
      { name: 'Baby animals', words: ['CUB', 'FAWN'] },
    ],
    slots: [
      { id: '1D', word: 'FAWN', row: 0, col: 6, dir: 'D' },
      { id: '2D', word: 'PULPIT', row: 1, col: 8, dir: 'D' },
      { id: '3A', word: 'CARDINAL', row: 3, col: 1, dir: 'A' },
      { id: '3D', word: 'CUB', row: 3, col: 1, dir: 'D' },
      { id: '4A', word: 'BISHOP', row: 5, col: 1, dir: 'A' },
      { id: '5D', word: 'PAWN', row: 5, col: 6, dir: 'D' },
      { id: '6A', word: 'ALTAR', row: 6, col: 6, dir: 'A' },
      { id: '7A', word: 'CRIMSON', row: 8, col: 0, dir: 'A' },
    ],
  },
  {
    num: 23,
    quizId: 'crux-7-28-26',
    live: '2026-07-28',
    dateLabel: 'July 28, 2026',
    guesses: 18,
    rows: 10,
    cols: 9,
    // rev 2 (2026-07-15, two-collision rule): COMB -> RAKE. SAW and RAKE both
    // read tools (a rake IS a garden tool) — but the pin is one-way: tools
    // are full (HAMMER+CHISEL) and neither a hammer nor a chisel has teeth,
    // so the reverse swap can never validate. Two collisions, one solution.
    rev: 2,
    categories: [
      { name: 'Things with teeth', words: ['SAW', 'RAKE'] },
      { name: 'Tools', words: ['HAMMER', 'CHISEL'] },
      { name: 'Zodiac signs', words: ['LIBRA', 'GEMINI'] },
      { name: 'Breads', words: ['RYE', 'BRIOCHE'] },
    ],
    slots: [
      { id: '1D', word: 'SAW', row: 0, col: 4, dir: 'D' },
      { id: '2A', word: 'LIBRA', row: 1, col: 0, dir: 'A' },
      { id: '3D', word: 'BRIOCHE', row: 1, col: 2, dir: 'D' },
      { id: '4D', word: 'GEMINI', row: 4, col: 5, dir: 'D' },
      { id: '5A', word: 'HAMMER', row: 6, col: 2, dir: 'A' },
      { id: '6D', word: 'RAKE', row: 6, col: 7, dir: 'D' },
      { id: '7A', word: 'RYE', row: 7, col: 0, dir: 'A' },
      { id: '8A', word: 'CHISEL', row: 9, col: 3, dir: 'A' },
    ],
  },
  {
    num: 24,
    quizId: 'crux-7-29-26',
    live: '2026-07-29',
    dateLabel: 'July 29, 2026',
    guesses: 18,
    rows: 8,
    cols: 8,
    // CAPE reads vampire and DELTA reads Greek letter (both are the landforms) — pinned: each alternate home fills without them.
    categories: [
      { name: 'Coastal landforms', words: ['CAPE', 'DELTA'] },
      { name: 'Greek letters', words: ['OMEGA', 'SIGMA'] },
      { name: 'Vampire essentials', words: ['FANG', 'COFFIN'] },
      { name: 'Fencing swords', words: ['EPEE', 'FOIL'] },
    ],
    slots: [
      { id: '1A', word: 'DELTA', row: 0, col: 1, dir: 'A' },
      { id: '2D', word: 'EPEE', row: 0, col: 2, dir: 'D' },
      { id: '3D', word: 'COFFIN', row: 2, col: 0, dir: 'D' },
      { id: '4A', word: 'FOIL', row: 2, col: 4, dir: 'A' },
      { id: '4D', word: 'FANG', row: 2, col: 4, dir: 'D' },
      { id: '5A', word: 'OMEGA', row: 3, col: 0, dir: 'A' },
      { id: '6D', word: 'CAPE', row: 4, col: 6, dir: 'D' },
      { id: '7A', word: 'SIGMA', row: 5, col: 2, dir: 'A' },
    ],
  },
  {
    num: 25,
    quizId: 'crux-7-30-26',
    live: '2026-07-30',
    dateLabel: 'July 30, 2026',
    guesses: 18,
    rows: 8,
    cols: 11,
    // rev 2 (2026-07-15, two-collision rule): circus acts + ERA -> TV show
    // parts + SEASON. SEASON is the pivot trap: it reads TV (PILOT+FINALE
    // fill that group), seasoning next to the herbs, and winter next to the
    // parkas — but PILOT/FINALE can't be stretches of time, so SEASON is
    // pinned to time. THYME keeps the homophone tease against the time group.
    rev: 2,
    categories: [
      { name: 'Winter wear', words: ['PARKA', 'MITTEN'] },
      { name: 'TV show parts', words: ['PILOT', 'FINALE'] },
      { name: 'Herbs', words: ['BASIL', 'THYME'] },
      { name: 'Stretches of time', words: ['SEASON', 'EPOCH'] },
    ],
    slots: [
      { id: '1D', word: 'PARKA', row: 0, col: 4, dir: 'D' },
      { id: '2D', word: 'MITTEN', row: 0, col: 6, dir: 'D' },
      { id: '3A', word: 'BASIL', row: 1, col: 3, dir: 'A' },
      { id: '4D', word: 'SEASON', row: 2, col: 10, dir: 'D' },
      { id: '5D', word: 'PILOT', row: 3, col: 2, dir: 'D' },
      { id: '6A', word: 'THYME', row: 3, col: 6, dir: 'A' },
      { id: '7A', word: 'FINALE', row: 4, col: 1, dir: 'A' },
      { id: '8A', word: 'EPOCH', row: 6, col: 0, dir: 'A' },
    ],
  },
  {
    num: 26,
    quizId: 'crux-7-31-26',
    live: '2026-07-31',
    dateLabel: 'July 31, 2026',
    guesses: 18,
    rows: 10,
    cols: 9,
    // rev 2 (2026-07-15, two-collision rule): CELLAR -> PORT. CORK reads wine
    // (wine is full — VINTAGE+PORT) and PORT reads nautical next to the
    // boats (a port isn't a vessel, and the boats are full — KAYAK+FERRY).
    rev: 2,
    categories: [
      { name: 'Things that pop', words: ['CORK', 'BALLOON'] },
      { name: 'Wine words', words: ['VINTAGE', 'PORT'] },
      { name: 'Boats', words: ['KAYAK', 'FERRY'] },
      { name: 'Dairy case', words: ['YOGURT', 'CHEDDAR'] },
    ],
    slots: [
      { id: '1A', word: 'CORK', row: 0, col: 0, dir: 'A' },
      { id: '2D', word: 'KAYAK', row: 0, col: 3, dir: 'D' },
      { id: '3D', word: 'VINTAGE', row: 1, col: 8, dir: 'D' },
      { id: '4D', word: 'YOGURT', row: 2, col: 6, dir: 'D' },
      { id: '5A', word: 'BALLOON', row: 3, col: 2, dir: 'A' },
      { id: '6D', word: 'FERRY', row: 5, col: 2, dir: 'D' },
      { id: '7A', word: 'CHEDDAR', row: 6, col: 0, dir: 'A' },
      { id: '8A', word: 'PORT', row: 8, col: 0, dir: 'A' },
    ],
  },
  {
    num: 27,
    quizId: 'crux-8-1-26',
    live: '2026-08-01',
    dateLabel: 'August 1, 2026',
    guesses: 18,
    rows: 9,
    cols: 8,
    // Double trap: CHARM reads jewelry (LOCKET+BANGLE fill it) and DRONE reads loud sound (BLARE+CLANG fill it) — both pinned by elimination.
    categories: [
      { name: 'Spells', words: ['HEX', 'CHARM'] },
      { name: 'Jewelry', words: ['LOCKET', 'BANGLE'] },
      { name: 'Beekeeping', words: ['HIVE', 'DRONE'] },
      { name: 'Loud sounds', words: ['BLARE', 'CLANG'] },
    ],
    slots: [
      { id: '1A', word: 'LOCKET', row: 0, col: 2, dir: 'A' },
      { id: '2D', word: 'CLANG', row: 0, col: 4, dir: 'D' },
      { id: '3A', word: 'CHARM', row: 2, col: 2, dir: 'A' },
      { id: '4A', word: 'BANGLE', row: 4, col: 1, dir: 'A' },
      { id: '4D', word: 'BLARE', row: 4, col: 1, dir: 'D' },
      { id: '5A', word: 'HIVE', row: 6, col: 4, dir: 'A' },
      { id: '5D', word: 'HEX', row: 6, col: 4, dir: 'D' },
      { id: '6A', word: 'DRONE', row: 7, col: 0, dir: 'A' },
    ],
  },
  {
    num: 28,
    quizId: 'crux-8-2-26',
    live: '2026-08-02',
    dateLabel: 'August 2, 2026',
    sunday: true,
    guesses: 27,
    rows: 12,
    cols: 11,
    // SAGE (herb/wise), JADE (gem), TRIANGLE (shape) all have off-board readings but no second on-board home; salad bar is full so no green escapes.
    categories: [
      { name: 'Salad bar', words: ['CROUTON', 'ROMAINE', 'ARUGULA'] },
      { name: 'Shades of green', words: ['JADE', 'SAGE', 'EMERALD'] },
      { name: 'Percussion', words: ['GONG', 'BONGO', 'TRIANGLE'] },
      { name: '___board', words: ['SURF', 'CHALK', 'CLIP'] },
    ],
    slots: [
      { id: '1A', word: 'SURF', row: 0, col: 0, dir: 'A' },
      { id: '1D', word: 'SAGE', row: 0, col: 0, dir: 'D' },
      { id: '2A', word: 'CLIP', row: 0, col: 5, dir: 'A' },
      { id: '2D', word: 'CHALK', row: 0, col: 5, dir: 'D' },
      { id: '3D', word: 'ROMAINE', row: 0, col: 10, dir: 'D' },
      { id: '4D', word: 'CROUTON', row: 2, col: 3, dir: 'D' },
      { id: '5A', word: 'EMERALD', row: 3, col: 0, dir: 'A' },
      { id: '6D', word: 'BONGO', row: 3, col: 8, dir: 'D' },
      { id: '7D', word: 'ARUGULA', row: 5, col: 1, dir: 'D' },
      { id: '8D', word: 'JADE', row: 5, col: 6, dir: 'D' },
      { id: '9A', word: 'TRIANGLE', row: 6, col: 3, dir: 'A' },
      { id: '10A', word: 'GONG', row: 8, col: 1, dir: 'A' },
    ],
  },
  {
    num: 29,
    quizId: 'crux-8-3-26',
    live: '2026-08-03',
    dateLabel: 'August 3, 2026',
    guesses: 18,
    rows: 10,
    cols: 8,
    categories: [
      { name: 'Headwear', words: ['BEANIE', 'VISOR'] },
      { name: 'Bottle parts', words: ['NECK', 'CAP'] },
      { name: 'Shirt parts', words: ['COLLAR', 'CUFF'] },
      { name: 'Guitar parts', words: ['FRET', 'STRING'] },
    ],
    slots: [
      { id: '1A', word: 'COLLAR', row: 0, col: 2, dir: 'A' },
      { id: '1D', word: 'CUFF', row: 0, col: 2, dir: 'D' },
      { id: '2D', word: 'BEANIE', row: 2, col: 4, dir: 'D' },
      { id: '3D', word: 'VISOR', row: 3, col: 0, dir: 'D' },
      { id: '4A', word: 'FRET', row: 3, col: 2, dir: 'A' },
      { id: '5A', word: 'STRING', row: 5, col: 0, dir: 'A' },
      { id: '6A', word: 'NECK', row: 7, col: 3, dir: 'A' },
      { id: '7D', word: 'CAP', row: 7, col: 5, dir: 'D' },
    ],
  },
  {
    num: 30,
    quizId: 'crux-8-4-26',
    live: '2026-08-04',
    dateLabel: 'August 4, 2026',
    guesses: 18,
    rows: 11,
    cols: 9,
    categories: [
      { name: 'Fruits', words: ['MELON', 'PEACH'] },
      { name: 'Trees', words: ['MAPLE', 'BIRCH'] },
      { name: 'Metals', words: ['COPPER', 'SILVER'] },
      { name: 'Flowers', words: ['TULIP', 'DAISY'] },
    ],
    slots: [
      { id: '7A', word: 'COPPER', row: 6, col: 0, dir: 'A' },
      { id: '3D', word: 'TULIP', row: 2, col: 2, dir: 'D' },
      { id: '6A', word: 'DAISY', row: 5, col: 0, dir: 'A' },
      { id: '5A', word: 'MELON', row: 4, col: 0, dir: 'A' },
      { id: '2D', word: 'SILVER', row: 1, col: 5, dir: 'D' },
      { id: '4A', word: 'BIRCH', row: 2, col: 4, dir: 'A' },
      { id: '1D', word: 'MAPLE', row: 0, col: 1, dir: 'D' },
      { id: '8D', word: 'PEACH', row: 6, col: 3, dir: 'D' },
    ],
  },
  {
    num: 31,
    quizId: 'crux-8-5-26',
    live: '2026-08-05',
    dateLabel: 'August 5, 2026',
    guesses: 18,
    rows: 11,
    cols: 7,
    categories: [
      { name: 'Weather', words: ['STORM', 'CLOUD'] },
      { name: 'Kitchen tools', words: ['WHISK', 'LADLE'] },
      { name: 'Big cats', words: ['TIGER', 'LEOPARD'] },
      { name: 'Gems', words: ['PEARL', 'TOPAZ'] },
    ],
    slots: [
      { id: '6A', word: 'TIGER', row: 5, col: 0, dir: 'A' },
      { id: '5D', word: 'PEARL', row: 4, col: 3, dir: 'D' },
      { id: '4A', word: 'TOPAZ', row: 4, col: 1, dir: 'A' },
      { id: '3D', word: 'STORM', row: 4, col: 0, dir: 'D' },
      { id: '1D', word: 'LEOPARD', row: 0, col: 4, dir: 'D' },
      { id: '7A', word: 'LADLE', row: 6, col: 2, dir: 'A' },
      { id: '8A', word: 'WHISK', row: 10, col: 0, dir: 'A' },
      { id: '2A', word: 'CLOUD', row: 2, col: 2, dir: 'A' },
    ],
  },
  {
    num: 32,
    quizId: 'crux-8-6-26',
    live: '2026-08-06',
    dateLabel: 'August 6, 2026',
    guesses: 18,
    rows: 11,
    cols: 9,
    categories: [
      { name: 'Birds', words: ['RAVEN', 'FINCH'] },
      { name: 'Dances', words: ['TANGO', 'WALTZ'] },
      { name: 'Planets', words: ['VENUS', 'MARS'] },
      { name: 'Tools', words: ['HAMMER', 'PLIERS'] },
    ],
    slots: [
      { id: '8A', word: 'VENUS', row: 8, col: 2, dir: 'A' },
      { id: '3D', word: 'HAMMER', row: 4, col: 3, dir: 'D' },
      { id: '2D', word: 'PLIERS', row: 3, col: 6, dir: 'D' },
      { id: '7A', word: 'RAVEN', row: 8, col: 0, dir: 'A' },
      { id: '6D', word: 'MARS', row: 7, col: 1, dir: 'D' },
      { id: '4A', word: 'WALTZ', row: 4, col: 4, dir: 'A' },
      { id: '5D', word: 'TANGO', row: 4, col: 7, dir: 'D' },
      { id: '1D', word: 'FINCH', row: 0, col: 3, dir: 'D' },
    ],
  },
  {
    num: 33,
    quizId: 'crux-8-7-26',
    live: '2026-08-07',
    dateLabel: 'August 7, 2026',
    guesses: 18,
    rows: 12,
    cols: 9,
    categories: [
      { name: 'Colors', words: ['MAROON', 'INDIGO'] },
      { name: 'Instruments', words: ['BANJO', 'FLUTE'] },
      { name: 'Rooms', words: ['PANTRY', 'STUDIO'] },
      { name: 'Vegetables', words: ['CARROT', 'CELERY'] },
    ],
    slots: [
      { id: '5A', word: 'PANTRY', row: 4, col: 3, dir: 'A' },
      { id: '4D', word: 'CARROT', row: 3, col: 4, dir: 'D' },
      { id: '1D', word: 'CELERY', row: 0, col: 7, dir: 'D' },
      { id: '7A', word: 'MAROON', row: 7, col: 0, dir: 'A' },
      { id: '8A', word: 'STUDIO', row: 8, col: 3, dir: 'A' },
      { id: '2D', word: 'FLUTE', row: 1, col: 6, dir: 'D' },
      { id: '3D', word: 'BANJO', row: 2, col: 5, dir: 'D' },
      { id: '6D', word: 'INDIGO', row: 6, col: 6, dir: 'D' },
    ],
  },
  {
    num: 34,
    quizId: 'crux-8-8-26',
    live: '2026-08-08',
    dateLabel: 'August 8, 2026',
    guesses: 18,
    rows: 11,
    cols: 12,
    categories: [
      { name: 'Sports', words: ['TENNIS', 'HOCKEY'] },
      { name: 'Boats', words: ['CANOE', 'YACHT'] },
      { name: 'Spices', words: ['GINGER', 'PEPPER'] },
      { name: 'Furniture', words: ['COUCH', 'TABLE'] },
    ],
    slots: [
      { id: '7A', word: 'GINGER', row: 8, col: 3, dir: 'A' },
      { id: '8A', word: 'COUCH', row: 10, col: 3, dir: 'A' },
      { id: '5D', word: 'TABLE', row: 4, col: 7, dir: 'D' },
      { id: '4D', word: 'TENNIS', row: 4, col: 4, dir: 'D' },
      { id: '6A', word: 'PEPPER', row: 5, col: 0, dir: 'A' },
      { id: '1D', word: 'YACHT', row: 0, col: 7, dir: 'D' },
      { id: '3A', word: 'CANOE', row: 2, col: 7, dir: 'A' },
      { id: '2D', word: 'HOCKEY', row: 1, col: 10, dir: 'D' },
    ],
  },
  {
    num: 35,
    quizId: 'crux-8-9-26',
    live: '2026-08-09',
    dateLabel: 'August 9, 2026',
    sunday: true,
    guesses: 27,
    rows: 11,
    cols: 13,
    categories: [
      { name: 'Fruits', words: ['BANANA', 'ORANGE', 'CHERRY'] },
      { name: 'Instruments', words: ['GUITAR', 'VIOLIN', 'TRUMPET'] },
      { name: 'Animals', words: ['RABBIT', 'MONKEY', 'TURTLE'] },
      { name: 'Metals', words: ['COPPER', 'NICKEL', 'BRONZE'] },
    ],
    slots: [
      { id: '9A', word: 'VIOLIN', row: 6, col: 2, dir: 'A' },
      { id: '6D', word: 'MONKEY', row: 4, col: 7, dir: 'D' },
      { id: '7D', word: 'COPPER', row: 5, col: 4, dir: 'D' },
      { id: '8A', word: 'BRONZE', row: 5, col: 5, dir: 'A' },
      { id: '11A', word: 'TRUMPET', row: 7, col: 0, dir: 'A' },
      { id: '4D', word: 'RABBIT', row: 2, col: 0, dir: 'D' },
      { id: '5A', word: 'BANANA', row: 4, col: 0, dir: 'A' },
      { id: '12A', word: 'TURTLE', row: 10, col: 2, dir: 'A' },
      { id: '1D', word: 'GUITAR', row: 0, col: 1, dir: 'D' },
      { id: '2D', word: 'ORANGE', row: 0, col: 10, dir: 'D' },
      { id: '10A', word: 'NICKEL', row: 6, col: 7, dir: 'A' },
      { id: '3A', word: 'CHERRY', row: 1, col: 6, dir: 'A' },
    ],
  },
  {
    num: 36,
    quizId: 'crux-8-10-26',
    live: '2026-08-10',
    dateLabel: 'August 10, 2026',
    guesses: 18,
    rows: 10,
    cols: 11,
    categories: [
      { name: 'Beverages', words: ['COFFEE', 'COCOA'] },
      { name: 'Tools', words: ['WRENCH', 'CHISEL'] },
      { name: 'Reptiles', words: ['COBRA', 'GECKO'] },
      { name: 'Shapes', words: ['CIRCLE', 'SQUARE'] },
    ],
    slots: [
      { id: '5A', word: 'COBRA', row: 4, col: 5, dir: 'A' },
      { id: '5D', word: 'CIRCLE', row: 4, col: 5, dir: 'D' },
      { id: '3D', word: 'SQUARE', row: 0, col: 8, dir: 'D' },
      { id: '7A', word: 'COFFEE', row: 9, col: 0, dir: 'A' },
      { id: '6D', word: 'GECKO', row: 5, col: 1, dir: 'D' },
      { id: '2A', word: 'CHISEL', row: 0, col: 5, dir: 'A' },
      { id: '1A', word: 'WRENCH', row: 0, col: 1, dir: 'A' },
      { id: '4D', word: 'COCOA', row: 3, col: 6, dir: 'D' },
    ],
  },
];
