// Niche facts: ANIMALS (the Tuesday universe). A curated set of well-known
// animals. CURATION RULE (the Etch rule): an animal whose value would be
// genuinely arguable for ANY field below is DROPPED from the set rather than
// nudged into a value — that is why there is no generic "bear" (black bears
// straddle the weight line) and no rattlesnake-style edge case left in.
//
// FIELD RULES (generous where two readings exist):
//   cls   mammal | bird | reptile | amphibian | fish | bug | invert
//   fly   flies under its own power (a chicken's short burst counts, the
//         generous reading).
//   aqua  lives mostly in the water (a penguin spends most of its life at sea,
//         so it counts).
//   afr   found in the wild in Africa (Madagascar counts; the African penguin
//         makes the penguin count, the generous reading).
//   legs4 walks on four legs.
//   eggs  lays eggs (the platypus is the famous mammal yes; live-bearing fish
//         and sharks are correctly no).
//   big   typically heavier than a grown man full grown (roughly 220 lb).
//         Borderline species are simply not flagged.
//   dom   commonly kept as a pet or farm animal.
//   hunt  hunts other animals for food.
export const ANIMALS = [
  // ── mammals ──
  { t: 'Lion', cls: 'mammal', afr: 1, legs4: 1, big: 1, hunt: 1 },
  { t: 'Tiger', cls: 'mammal', legs4: 1, big: 1, hunt: 1 },
  { t: 'Cheetah', cls: 'mammal', afr: 1, legs4: 1, hunt: 1 },
  { t: 'Leopard', cls: 'mammal', afr: 1, legs4: 1, hunt: 1 },
  { t: 'Jaguar', cls: 'mammal', legs4: 1, hunt: 1 },
  { t: 'Cougar', a: ['mountain lion', 'puma'], cls: 'mammal', legs4: 1, hunt: 1 },
  { t: 'Elephant', cls: 'mammal', afr: 1, legs4: 1, big: 1 },
  { t: 'Giraffe', cls: 'mammal', afr: 1, legs4: 1, big: 1 },
  { t: 'Zebra', cls: 'mammal', afr: 1, legs4: 1 },
  { t: 'Hippopotamus', a: ['hippo'], cls: 'mammal', afr: 1, aqua: 1, legs4: 1, big: 1 },
  { t: 'Rhinoceros', a: ['rhino'], cls: 'mammal', afr: 1, legs4: 1, big: 1 },
  { t: 'Gorilla', cls: 'mammal', afr: 1, big: 1 },
  { t: 'Chimpanzee', a: ['chimp'], cls: 'mammal', afr: 1 },
  { t: 'Baboon', cls: 'mammal', afr: 1, legs4: 1 },
  { t: 'Orangutan', cls: 'mammal' },
  { t: 'Gibbon', cls: 'mammal' },
  { t: 'Lemur', cls: 'mammal', afr: 1, legs4: 1 },
  { t: 'Hyena', cls: 'mammal', afr: 1, legs4: 1, hunt: 1 },
  { t: 'Jackal', cls: 'mammal', afr: 1, legs4: 1, hunt: 1 },
  { t: 'Meerkat', cls: 'mammal', afr: 1, legs4: 1, hunt: 1 },
  { t: 'Mongoose', cls: 'mammal', afr: 1, legs4: 1, hunt: 1 },
  { t: 'Warthog', cls: 'mammal', afr: 1, legs4: 1 },
  { t: 'Wildebeest', a: ['gnu'], cls: 'mammal', afr: 1, legs4: 1, big: 1 },
  { t: 'Gazelle', cls: 'mammal', afr: 1, legs4: 1 },
  { t: 'Antelope', cls: 'mammal', afr: 1, legs4: 1 },
  { t: 'Aardvark', cls: 'mammal', afr: 1, legs4: 1 },
  { t: 'Grizzly Bear', cls: 'mammal', legs4: 1, big: 1, hunt: 1 },
  { t: 'Polar Bear', cls: 'mammal', legs4: 1, big: 1, hunt: 1 },
  { t: 'Panda', a: ['giant panda'], cls: 'mammal', legs4: 1, big: 1 },
  { t: 'Wolf', cls: 'mammal', legs4: 1, hunt: 1 },
  { t: 'Coyote', cls: 'mammal', legs4: 1, hunt: 1 },
  { t: 'Fox', cls: 'mammal', legs4: 1, hunt: 1 },
  { t: 'Raccoon', cls: 'mammal', legs4: 1 },
  { t: 'Skunk', cls: 'mammal', legs4: 1 },
  { t: 'Badger', cls: 'mammal', legs4: 1, hunt: 1 },
  { t: 'Otter', cls: 'mammal', aqua: 1, legs4: 1, hunt: 1 },
  { t: 'Beaver', cls: 'mammal', aqua: 1, legs4: 1 },
  { t: 'Moose', cls: 'mammal', legs4: 1, big: 1 },
  { t: 'Elk', cls: 'mammal', legs4: 1, big: 1 },
  { t: 'Deer', cls: 'mammal', legs4: 1 },
  { t: 'Bison', a: ['buffalo'], cls: 'mammal', legs4: 1, big: 1 },
  { t: 'Camel', cls: 'mammal', afr: 1, legs4: 1, big: 1, dom: 1 },
  { t: 'Llama', cls: 'mammal', legs4: 1, big: 1, dom: 1 },
  { t: 'Alpaca', cls: 'mammal', legs4: 1, dom: 1 },
  { t: 'Horse', cls: 'mammal', legs4: 1, big: 1, dom: 1 },
  { t: 'Donkey', cls: 'mammal', legs4: 1, big: 1, dom: 1 },
  { t: 'Cow', a: ['cattle'], cls: 'mammal', legs4: 1, big: 1, dom: 1 },
  { t: 'Pig', a: ['hog'], cls: 'mammal', legs4: 1, big: 1, dom: 1 },
  { t: 'Sheep', cls: 'mammal', legs4: 1, dom: 1 },
  { t: 'Goat', cls: 'mammal', legs4: 1, dom: 1 },
  { t: 'Dog', cls: 'mammal', legs4: 1, dom: 1 },
  { t: 'Cat', cls: 'mammal', legs4: 1, dom: 1, hunt: 1 },
  { t: 'Rabbit', cls: 'mammal', legs4: 1, dom: 1 },
  { t: 'Hamster', cls: 'mammal', legs4: 1, dom: 1 },
  { t: 'Guinea Pig', cls: 'mammal', legs4: 1, dom: 1 },
  { t: 'Ferret', cls: 'mammal', legs4: 1, dom: 1, hunt: 1 },
  { t: 'Mouse', cls: 'mammal', legs4: 1 },
  { t: 'Rat', cls: 'mammal', legs4: 1 },
  { t: 'Squirrel', cls: 'mammal', legs4: 1 },
  { t: 'Chipmunk', cls: 'mammal', legs4: 1 },
  { t: 'Hedgehog', cls: 'mammal', afr: 1, legs4: 1, hunt: 1 },
  { t: 'Porcupine', cls: 'mammal', afr: 1, legs4: 1 },
  { t: 'Armadillo', cls: 'mammal', legs4: 1 },
  { t: 'Sloth', cls: 'mammal', legs4: 1 },
  { t: 'Anteater', cls: 'mammal', legs4: 1, hunt: 1 },
  { t: 'Kangaroo', cls: 'mammal' },
  { t: 'Koala', cls: 'mammal', legs4: 1 },
  { t: 'Wombat', cls: 'mammal', legs4: 1 },
  { t: 'Platypus', cls: 'mammal', aqua: 1, legs4: 1, eggs: 1, hunt: 1 },
  { t: 'Bat', cls: 'mammal', fly: 1, hunt: 1 },
  { t: 'Dolphin', cls: 'mammal', aqua: 1, big: 1, hunt: 1 },
  { t: 'Orca', a: ['killer whale'], cls: 'mammal', aqua: 1, big: 1, hunt: 1 },
  { t: 'Blue Whale', cls: 'mammal', aqua: 1, big: 1, hunt: 1 },
  { t: 'Humpback Whale', cls: 'mammal', aqua: 1, big: 1, hunt: 1 },
  { t: 'Walrus', cls: 'mammal', aqua: 1, big: 1, hunt: 1 },
  { t: 'Seal', cls: 'mammal', aqua: 1, big: 1, hunt: 1 },
  { t: 'Sea Lion', cls: 'mammal', aqua: 1, big: 1, hunt: 1 },
  { t: 'Manatee', cls: 'mammal', aqua: 1, big: 1 },
  // ── birds ──
  { t: 'Bald Eagle', a: ['eagle'], cls: 'bird', fly: 1, eggs: 1, hunt: 1 },
  { t: 'Hawk', cls: 'bird', fly: 1, eggs: 1, hunt: 1 },
  { t: 'Falcon', cls: 'bird', fly: 1, eggs: 1, hunt: 1 },
  { t: 'Owl', cls: 'bird', fly: 1, eggs: 1, hunt: 1 },
  { t: 'Vulture', cls: 'bird', fly: 1, afr: 1, eggs: 1 },
  { t: 'Ostrich', cls: 'bird', afr: 1, eggs: 1, big: 1 },
  { t: 'Emu', cls: 'bird', eggs: 1 },
  { t: 'Penguin', cls: 'bird', aqua: 1, afr: 1, eggs: 1, hunt: 1 },
  { t: 'Flamingo', cls: 'bird', fly: 1, afr: 1, eggs: 1 },
  { t: 'Pelican', cls: 'bird', fly: 1, afr: 1, eggs: 1, hunt: 1 },
  { t: 'Stork', cls: 'bird', fly: 1, afr: 1, eggs: 1, hunt: 1 },
  { t: 'Crane', cls: 'bird', fly: 1, afr: 1, eggs: 1 },
  { t: 'Heron', cls: 'bird', fly: 1, afr: 1, eggs: 1, hunt: 1 },
  { t: 'Swan', cls: 'bird', fly: 1, aqua: 1, eggs: 1 },
  { t: 'Goose', cls: 'bird', fly: 1, aqua: 1, eggs: 1, dom: 1 },
  { t: 'Duck', cls: 'bird', fly: 1, aqua: 1, eggs: 1, dom: 1 },
  { t: 'Chicken', a: ['hen', 'rooster'], cls: 'bird', fly: 1, eggs: 1, dom: 1 },
  { t: 'Turkey', cls: 'bird', fly: 1, eggs: 1, dom: 1 },
  { t: 'Peacock', a: ['peafowl'], cls: 'bird', fly: 1, eggs: 1 },
  { t: 'Parrot', cls: 'bird', fly: 1, afr: 1, eggs: 1, dom: 1 },
  { t: 'Toucan', cls: 'bird', fly: 1, eggs: 1 },
  { t: 'Hummingbird', cls: 'bird', fly: 1, eggs: 1 },
  { t: 'Woodpecker', cls: 'bird', fly: 1, eggs: 1 },
  { t: 'Crow', cls: 'bird', fly: 1, eggs: 1 },
  { t: 'Raven', cls: 'bird', fly: 1, eggs: 1 },
  { t: 'Pigeon', a: ['dove'], cls: 'bird', fly: 1, afr: 1, eggs: 1 },
  { t: 'Robin', cls: 'bird', fly: 1, eggs: 1 },
  { t: 'Sparrow', cls: 'bird', fly: 1, afr: 1, eggs: 1 },
  { t: 'Seagull', a: ['gull'], cls: 'bird', fly: 1, eggs: 1 },
  { t: 'Albatross', cls: 'bird', fly: 1, aqua: 1, eggs: 1, hunt: 1 },
  { t: 'Kiwi', cls: 'bird', eggs: 1, hunt: 1 },
  // ── reptiles & amphibians ──
  { t: 'Crocodile', cls: 'reptile', afr: 1, aqua: 1, legs4: 1, eggs: 1, big: 1, hunt: 1 },
  { t: 'Alligator', cls: 'reptile', aqua: 1, legs4: 1, eggs: 1, big: 1, hunt: 1 },
  { t: 'Komodo Dragon', cls: 'reptile', legs4: 1, eggs: 1, hunt: 1 },
  { t: 'Iguana', cls: 'reptile', legs4: 1, eggs: 1 },
  { t: 'Chameleon', cls: 'reptile', afr: 1, legs4: 1, eggs: 1, hunt: 1 },
  { t: 'Gecko', cls: 'reptile', afr: 1, legs4: 1, eggs: 1, hunt: 1 },
  { t: 'Cobra', cls: 'reptile', afr: 1, eggs: 1, hunt: 1 },
  { t: 'Python', cls: 'reptile', afr: 1, eggs: 1, hunt: 1 },
  { t: 'Sea Turtle', cls: 'reptile', aqua: 1, eggs: 1 },
  { t: 'Tortoise', cls: 'reptile', afr: 1, legs4: 1, eggs: 1 },
  { t: 'Frog', cls: 'amphibian', legs4: 1, eggs: 1, hunt: 1 },
  { t: 'Toad', cls: 'amphibian', legs4: 1, eggs: 1, hunt: 1 },
  { t: 'Salamander', cls: 'amphibian', legs4: 1, eggs: 1, hunt: 1 },
  { t: 'Axolotl', cls: 'amphibian', aqua: 1, legs4: 1, eggs: 1, hunt: 1, dom: 1 },
  // ── fish & sea creatures ──
  { t: 'Great White Shark', cls: 'fish', afr: 1, aqua: 1, big: 1, hunt: 1 },
  { t: 'Hammerhead Shark', cls: 'fish', aqua: 1, big: 1, hunt: 1 },
  { t: 'Whale Shark', cls: 'fish', afr: 1, aqua: 1, big: 1 },
  { t: 'Goldfish', cls: 'fish', aqua: 1, eggs: 1, dom: 1 },
  { t: 'Clownfish', cls: 'fish', aqua: 1, eggs: 1, dom: 1 },
  { t: 'Salmon', cls: 'fish', aqua: 1, eggs: 1, hunt: 1 },
  { t: 'Trout', cls: 'fish', aqua: 1, eggs: 1, hunt: 1 },
  { t: 'Catfish', cls: 'fish', afr: 1, aqua: 1, eggs: 1, hunt: 1 },
  { t: 'Swordfish', cls: 'fish', aqua: 1, eggs: 1, big: 1, hunt: 1 },
  { t: 'Piranha', cls: 'fish', aqua: 1, eggs: 1, hunt: 1 },
  { t: 'Eel', cls: 'fish', aqua: 1, eggs: 1, hunt: 1 },
  { t: 'Seahorse', cls: 'fish', aqua: 1, eggs: 1, hunt: 1 },
  { t: 'Stingray', cls: 'fish', aqua: 1, hunt: 1 },
  { t: 'Octopus', cls: 'invert', aqua: 1, eggs: 1, hunt: 1 },
  { t: 'Squid', cls: 'invert', aqua: 1, eggs: 1, hunt: 1 },
  { t: 'Jellyfish', cls: 'invert', aqua: 1, eggs: 1, hunt: 1 },
  { t: 'Lobster', cls: 'invert', aqua: 1, eggs: 1, hunt: 1 },
  { t: 'Crab', cls: 'invert', aqua: 1, eggs: 1, hunt: 1 },
  { t: 'Shrimp', cls: 'invert', aqua: 1, eggs: 1 },
  { t: 'Starfish', a: ['sea star'], cls: 'invert', aqua: 1, eggs: 1, hunt: 1 },
  // ── bugs & small invertebrates ──
  { t: 'Butterfly', cls: 'bug', fly: 1, eggs: 1 },
  { t: 'Moth', cls: 'bug', fly: 1, afr: 1, eggs: 1 },
  { t: 'Honeybee', a: ['bee'], cls: 'bug', fly: 1, afr: 1, eggs: 1, dom: 1 },
  { t: 'Wasp', cls: 'bug', fly: 1, afr: 1, eggs: 1, hunt: 1 },
  { t: 'Dragonfly', cls: 'bug', fly: 1, afr: 1, eggs: 1, hunt: 1 },
  { t: 'Ladybug', cls: 'bug', fly: 1, eggs: 1, hunt: 1 },
  { t: 'Mosquito', cls: 'bug', fly: 1, afr: 1, eggs: 1 },
  { t: 'Grasshopper', cls: 'bug', fly: 1, afr: 1, eggs: 1 },
  { t: 'Cricket', cls: 'bug', fly: 1, afr: 1, eggs: 1 },
  { t: 'Beetle', cls: 'bug', fly: 1, afr: 1, eggs: 1 },
  { t: 'Ant', cls: 'bug', afr: 1, eggs: 1 },
  { t: 'Spider', cls: 'bug', afr: 1, eggs: 1, hunt: 1 },
  { t: 'Scorpion', cls: 'bug', afr: 1, hunt: 1 },
  { t: 'Snail', cls: 'invert', afr: 1, eggs: 1 },
  { t: 'Earthworm', a: ['worm'], cls: 'invert', afr: 1, eggs: 1 },
];
