// Auto-generated data file for Consensus Gurus

/* =========================================================================
   AFFILIATE CONFIGURATION
   ========================================================================= */
const AMAZON_AFFILIATE_TAG = 'cgurus-20';
const BOOKING_AFFILIATE_AID = '';
const TRIPADVISOR_PARTNER = '';

/* =========================================================================
   TYPES (for filtering chips)
   A list can match multiple types via its `tags` array.
   ========================================================================= */
const TYPES = [
  { id: 'all', label: 'All' },
  { id: 'food', label: 'Food & Drink' },
  { id: 'bars', label: 'Bars' },
  { id: 'nightlife', label: 'Nightlife' },
  { id: 'stores', label: 'Places & Stores' },
  { id: 'travel', label: 'Travel' },
  { id: 'entertainment', label: 'Entertainment' },
  { id: 'tech', label: 'Tech' },
  { id: 'product', label: 'Products' },
  { id: 'other', label: 'Other' },
];

const COLORS = {
  cream: '#f4ede0',
  paper: '#ebe2d0',
  ink: '#1a1611',
  ember: '#c0392b',
  rust: '#a44a26',
  forest: '#3d4f2b',
  faded: '#7a6f5e',
};

/* =========================================================================
   LISTS
   - type: primary category (used for legacy code paths)
   - tags (optional): array of all categories this list belongs to. If absent,
     falls back to [type]. The filter chips on the home page use tags.
   - mode (optional): 'facts' (no voting), 'votes' (no source tab)
   ========================================================================= */

const LISTS = [
  /* ----- TRAVEL ----- */
  {
    id: 'miami-beach-hotels',
    publishedDate: '2026-05-24',
    title: 'Miami Beach Hotels',
    category: 'Miami Beach',
    type: 'travel',
    linkType: 'mapsCity',
    blurb: 'Ocean Drive icons, Art Deco glamour, and the resorts that anchor South Beach.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ['Faena Hotel Miami Beach', 'The Setai, Miami Beach', 'Four Seasons Hotel at The Surf Club', '1 Hotel South Beach', 'The Miami Beach EDITION', 'Nobu Hotel Miami Beach', 'W South Beach', 'St. Regis Bal Harbour Resort', 'The Ritz-Carlton, South Beach', 'Loews Miami Beach Hotel'] },
      tlleisure: { label: 'Travel + Leisure Readers', items: ['Four Seasons Hotel at The Surf Club', 'St. Regis Bal Harbour Resort', 'The Setai, Miami Beach', 'Faena Hotel Miami Beach', 'The Ritz-Carlton, Key Biscayne', '1 Hotel South Beach', 'The Miami Beach EDITION', 'Nobu Hotel Miami Beach', 'W South Beach', 'Eden Roc Miami Beach'] },
      forbes: { label: 'Forbes Travel Guide 5-Star', items: ['Acqualina Resort & Spa', 'Faena Hotel Miami Beach', 'Four Seasons Hotel at The Surf Club', 'The Ritz-Carlton, South Beach', 'The Setai, Miami Beach', 'St. Regis Bal Harbour Resort', 'Nobu Hotel Miami Beach', 'The Miami Beach EDITION', '1 Hotel South Beach', 'W South Beach'] },
      tripadvisor: { label: 'Tripadvisor Travelers Choice', items: ['The Setai, Miami Beach', 'Faena Hotel Miami Beach', 'Four Seasons Hotel at The Surf Club', '1 Hotel South Beach', 'Acqualina Resort & Spa', 'The Gabriel South Beach', 'Nobu Hotel Miami Beach', 'The Miami Beach EDITION', 'Loews Miami Beach Hotel', 'Eden Roc Miami Beach'] },
    },
    vote: { items: ['Faena Hotel Miami Beach', 'The Setai, Miami Beach', 'Four Seasons Hotel at The Surf Club', '1 Hotel South Beach', 'Nobu Hotel Miami Beach', 'The Miami Beach EDITION', 'St. Regis Bal Harbour Resort', 'Acqualina Resort & Spa', 'W South Beach', 'The Ritz-Carlton, South Beach'] },
  },
  {
    id: 'lobster-rolls',
    publishedDate: '2026-05-24',
    title: 'Lobster Rolls in America',
    category: 'New England',
    type: 'food',
    tags: ['food', 'stores'],
    linkType: 'mapsCity',
    blurb: 'Maine-style cold with mayo or Connecticut-style warm with butter. Defend your shack.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ["Red's Eats", 'The Clam Shack', 'Neptune Oyster', "Luke's Lobster", 'McLoons Lobster Shack', 'Five Islands Lobster Co', 'Bite Into Maine', 'Eventide Oyster Co', "Abbott's Lobster in the Rough", 'Lobster Hut Plymouth'] },
      yankee: { label: 'Yankee Magazine', items: ["Red's Eats", 'The Clam Shack', 'McLoons Lobster Shack', 'Five Islands Lobster Co', "Abbott's Lobster in the Rough", 'Chatham Pier Fish Market', "Markey's Lobster Pool", 'Bite Into Maine', 'Lobster Hut Plymouth', 'Sea Swirl'] },
      lobsteranywhere: { label: 'LobsterAnywhere USA Guide', items: ['Neptune Oyster', "Red's Eats", "Luke's Lobster", 'Eventide Oyster Co', 'The Clam Shack', 'Bite Into Maine', "Pauli's Boston", "Ed's Lobster Bar", 'Saltie Girl', 'James Hook & Co'] },
    },
    vote: { items: ["Red's Eats", 'Neptune Oyster', 'The Clam Shack', "Luke's Lobster", 'Eventide Oyster Co', 'McLoons Lobster Shack', 'Bite Into Maine', 'Five Islands Lobster Co', "Abbott's Lobster in the Rough", 'Lobster Hut Plymouth'] },
  },
  {
    id: 'pacific-ocean-resorts',
    publishedDate: '2026-05-24',
    title: 'Pacific Ocean Island Resorts',
    category: 'South Pacific',
    type: 'travel',
    linkType: 'mapsCity',
    blurb: 'Overwater bungalows and private atolls, from Bora Bora to Fiji to the Maldives.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ['Four Seasons Resort Bora Bora', 'The St. Regis Bora Bora Resort', 'InterContinental Thalasso Spa Bora Bora', "Le Taha'a by Pearl Resorts", 'Six Senses Fiji', 'Laucala Island Resort, Fiji', 'Como Laucala Island', 'The Brando, Tetiaroa', 'Soneva Fushi, Maldives', 'North Island, Seychelles'] },
      tlleisure: { label: 'Travel + Leisure Best Islands', items: ['The Brando, Tetiaroa', 'Four Seasons Resort Bora Bora', 'Laucala Island Resort, Fiji', 'Soneva Fushi, Maldives', 'North Island, Seychelles', 'Como Laucala Island', 'Six Senses Laamu, Maldives', 'The St. Regis Bora Bora Resort', 'Vomo Island Resort, Fiji', "Le Taha'a by Pearl Resorts"] },
      luxurytravelexpert: { label: 'Luxury Travel Expert', items: ['Kudadoo Maldives', 'Soneva Jani, Maldives', 'Cheval Blanc Randheli, Maldives', 'Soneva Fushi, Maldives', 'Six Senses Laamu, Maldives', 'The Brando, Tetiaroa', 'Laucala Island Resort, Fiji', 'Four Seasons Resort Bora Bora', 'North Island, Seychelles', 'Anantara Kihavah Maldives Villas'] },
      tripadvisor: { label: 'Tripadvisor Travelers Choice', items: ['Four Seasons Resort Bora Bora', 'The St. Regis Bora Bora Resort', 'Conrad Bora Bora Nui', 'Le Bora Bora by Pearl Resorts', 'InterContinental Thalasso Spa Bora Bora', 'Soneva Fushi, Maldives', 'Como Laucala Island', 'Vomo Island Resort, Fiji', 'Likuliku Lagoon Resort, Fiji', 'Tokoriki Island Resort, Fiji'] },
    },
    vote: { items: ['The Brando, Tetiaroa', 'Four Seasons Resort Bora Bora', 'Laucala Island Resort, Fiji', 'Soneva Fushi, Maldives', 'The St. Regis Bora Bora Resort', 'Como Laucala Island', 'Kudadoo Maldives', 'North Island, Seychelles', 'InterContinental Thalasso Spa Bora Bora', 'Six Senses Laamu, Maldives'] },
  },
  {
    id: 'cabo-hotels',
    publishedDate: '2026-05-24',
    title: 'Cabo San Lucas Hotels',
    category: 'Cabo San Lucas',
    type: 'travel',
    linkType: 'mapsCity',
    blurb: 'Where the Sea of Cortez meets the Pacific. Cliffside suites, infinity pools, and El Arco views.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ['Waldorf Astoria Los Cabos Pedregal', 'Esperanza, Auberge Collection', 'One&Only Palmilla', 'Las Ventanas al Paraiso, A Rosewood Resort', 'Grand Velas Los Cabos', 'Nobu Hotel Los Cabos', 'Montage Los Cabos', 'Four Seasons Resort Los Cabos at Costa Palmas', 'Chileno Bay Resort, Auberge Collection', 'Hotel El Ganzo'] },
      tripadvisor: { label: 'Tripadvisor Travelers Choice', items: ['Grand Solmar Pacific Dunes', 'Esperanza, Auberge Collection', 'Waldorf Astoria Los Cabos Pedregal', 'Garza Blanca Resort & Spa Los Cabos', 'Pueblo Bonito Sunset Beach', 'One&Only Palmilla', 'Chileno Bay Resort, Auberge Collection', 'Las Ventanas al Paraiso, A Rosewood Resort', 'Nobu Hotel Los Cabos', 'Hyatt Ziva Los Cabos'] },
      trip: { label: 'Trip.com Popular', items: ['Waldorf Astoria Los Cabos Pedregal', '1 Homes Preview Cabo', 'Esperanza, Auberge Collection', 'One&Only Palmilla', 'Grand Velas Los Cabos', 'Montage Los Cabos', 'Nobu Hotel Los Cabos', 'Chileno Bay Resort, Auberge Collection', 'Las Ventanas al Paraiso, A Rosewood Resort', 'Four Seasons Resort Los Cabos at Costa Palmas'] },
    },
    vote: { items: ['Waldorf Astoria Los Cabos Pedregal', 'Esperanza, Auberge Collection', 'One&Only Palmilla', 'Las Ventanas al Paraiso, A Rosewood Resort', 'Montage Los Cabos', 'Four Seasons Resort Los Cabos at Costa Palmas', 'Grand Velas Los Cabos', 'Nobu Hotel Los Cabos', 'Chileno Bay Resort, Auberge Collection', 'Grand Solmar Pacific Dunes'] },
  },
  {
    id: 'european-ski-resorts',
    publishedDate: '2026-05-25',
    title: 'European Ski Resorts',
    category: 'Alps',
    type: 'travel',
    linkType: 'mapsCity',
    blurb: 'From Verbier glamour to Zermatt views to the Dolomites. Where the lifts are long and the apres-ski is legendary.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ['Verbier, Switzerland', 'Zermatt, Switzerland', 'St. Moritz, Switzerland', 'Courchevel, France', "Val d'Isère, France", "Cortina d'Ampezzo, Italy", 'Chamonix-Mont Blanc, France', 'Kitzbühel, Austria', 'Val Thorens, France', 'Gstaad, Switzerland'] },
      cntraveler: { label: 'Conde Nast Traveler Readers Choice 2025', items: ['Verbier, Switzerland', 'Zermatt, Switzerland', 'St. Moritz, Switzerland', 'Courchevel, France', "Cortina d'Ampezzo, Italy", 'Levi, Finland', 'Crans-Montana, Switzerland', "Val d'Isère, France", 'Innsbruck, Austria', 'Corvara - Alta Badia, Italy'] },
      timeout: { label: 'Time Out · Omio Data', items: ['Arosa Lenzerheide, Switzerland', 'Sölden, Austria', 'SkiWelt Wilder Kaiser-Brixental, Austria', 'Saalbach Hinterglemm Leogang Fieberbrunn, Austria', 'Zermatt, Switzerland', 'Val Thorens, France', 'Chamonix-Mont Blanc, France', 'Kitzbühel, Austria', 'St. Anton am Arlberg, Austria', 'Val Gardena, Italy'] },
      worldskiawards: { label: 'World Ski Awards', items: ['Val Thorens, France', 'Zermatt, Switzerland', 'Verbier, Switzerland', 'St. Anton am Arlberg, Austria', 'Courchevel, France', 'Chamonix-Mont Blanc, France', 'Kitzbühel, Austria', "Val d'Isère, France", "Cortina d'Ampezzo, Italy", 'Lech, Austria'] },
    },
    vote: { items: ['Verbier, Switzerland', 'Zermatt, Switzerland', 'Chamonix-Mont Blanc, France', 'St. Moritz, Switzerland', 'Courchevel, France', "Val d'Isère, France", "Cortina d'Ampezzo, Italy", 'Kitzbühel, Austria', 'St. Anton am Arlberg, Austria', 'Val Thorens, France'] },
  },
  {
    id: 'greek-isles-hotels',
    publishedDate: '2026-05-25',
    title: 'Hotels in the Greek Isles',
    category: 'Greek Islands',
    type: 'travel',
    linkType: 'mapsCity',
    blurb: 'Cave suites in Oia, Cycladic whitewash in Mykonos, and the boutique hideouts that earn the Aegean its reputation.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ['Perivolas, Santorini', 'Grace Hotel Santorini, Auberge Resorts Collection', 'Kalesma Mykonos', 'Cavo Tagoo Mykonos', 'Bill & Coo Mykonos', 'Kivotos Santorini', 'Mystique, a Luxury Collection Hotel, Santorini', 'Myconian Naia', 'Canaves Oia', 'Santa Marina, a Luxury Collection Resort, Mykonos'] },
      timeout: { label: 'Time Out Greece', items: ['Kivotos Santorini', 'Grace Hotel Santorini, Auberge Resorts Collection', 'Voreina Gallery Suites Santorini', 'Kalesma Mykonos', 'Kove Mykonos', 'Anemelia Mykonos', 'Perivolas, Santorini', 'Mystique, Santorini', 'Canaves Oia', 'Bill & Coo Mykonos'] },
      trip: { label: 'Trip.com Luxury Rankings', items: ['Kalesma Mykonos', 'Aeonic Suites and Spa, Mykonos', 'Myconian Naia', 'Cavo Tagoo Mykonos', 'Mystique, Santorini', 'Grace Hotel Santorini, Auberge Resorts Collection', 'Canaves Oia', 'Bill & Coo Mykonos', 'Santa Marina, Mykonos', 'Perivolas, Santorini'] },
      findus: { label: 'Find Us Lost Editor Picks', items: ['Perivolas, Santorini', 'Panoptis Escape, Mykonos', 'Aristide Hotel, Syros', 'Odera Hotel, Tinos', 'Kalesma Mykonos', 'Canaves Oia', 'Mystique, Santorini', 'Grace Hotel Santorini, Auberge Resorts Collection', 'Bill & Coo Mykonos', 'Cavo Tagoo Mykonos'] },
    },
    vote: { items: ['Perivolas, Santorini', 'Kalesma Mykonos', 'Mystique, Santorini', 'Bill & Coo Mykonos', 'Canaves Oia', 'Cavo Tagoo Mykonos', 'Grace Hotel Santorini, Auberge Resorts Collection', 'Santa Marina, Mykonos', 'Kivotos Santorini', 'Myconian Naia'] },
  },
  {
    id: 'boston-hotels',
    publishedDate: '2026-05-26',
    title: 'Boston Hotels',
    category: 'Boston',
    type: 'travel',
    linkType: 'mapsCity',
    blurb: 'Back Bay luxury at Mandarin Oriental, harbor views at InterContinental, Public Garden frontage at Four Seasons. The hotels that anchor a city built on bricks and history.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: ['Mandarin Oriental Boston', 'InterContinental Boston', 'Four Seasons Hotel Boston', 'The Ritz-Carlton Boston', 'Raffles Boston', 'The Newbury Boston', 'Boston Harbor Hotel', 'The Langham Boston', 'Hotel AKA Boston Common', 'XV Beacon'],
      },
      usnews: {
        label: 'U.S. News 25 Best 2026',
        items: ['Mandarin Oriental Boston', 'Four Seasons Hotel Boston', 'The Ritz-Carlton Boston', 'Raffles Boston', 'The Newbury Boston', 'Boston Harbor Hotel', 'InterContinental Boston', 'XV Beacon', 'The Langham Boston', 'Four Seasons Hotel One Dalton Street'],
      },
      cntraveler: {
        label: "Conde Nast Readers' Choice",
        items: ['InterContinental Boston', 'Mandarin Oriental Boston', 'Hotel AKA Boston Common', 'Hyatt Regency Boston', 'Four Seasons Hotel Boston', 'The Ritz-Carlton Boston', 'The Langham Boston', 'Boston Harbor Hotel', 'Raffles Boston', 'The Newbury Boston'],
      },
      forbes: {
        label: 'Forbes Travel Guide',
        items: ['Mandarin Oriental Boston', 'Four Seasons Hotel Boston', 'The Ritz-Carlton Boston', 'Boston Harbor Hotel', 'The Langham Boston', 'Raffles Boston', 'The Newbury Boston', 'InterContinental Boston', 'Four Seasons Hotel One Dalton Street', 'XV Beacon'],
      },
    },
    vote: {
      items: ['Mandarin Oriental Boston', 'Four Seasons Hotel Boston', 'InterContinental Boston', 'The Ritz-Carlton Boston', 'Raffles Boston', 'The Newbury Boston', 'Boston Harbor Hotel', 'The Langham Boston', 'XV Beacon', 'Hotel AKA Boston Common'],
    },
  },
  {
    id: 'vegas-casino-hotels',
    publishedDate: '2026-05-25',
    title: 'Hotel Casinos in Las Vegas',
    category: 'Las Vegas',
    type: 'travel',
    tags: ['travel', 'entertainment', 'nightlife'],
    linkType: 'mapsCity',
    blurb: "The Strip's heaviest hitters, where the fountains dance, the suites overlook the desert, and the casino floors never close.",
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ['Wynn Las Vegas', 'Bellagio', 'The Venetian Resort Las Vegas', 'Encore at Wynn Las Vegas', 'Aria Resort & Casino', 'The Cosmopolitan of Las Vegas', 'Caesars Palace', 'Fontainebleau Las Vegas', 'MGM Grand', 'Resorts World Las Vegas'] },
      tlleisure: { label: "Travel + Leisure World's Best", items: ['Wynn Las Vegas', 'Bellagio', 'Encore at Wynn Las Vegas', 'The Venetian Resort Las Vegas', 'Four Seasons Hotel Las Vegas', 'Aria Resort & Casino', 'The Cosmopolitan of Las Vegas', 'Mandalay Bay', 'Caesars Palace', 'Resorts World Las Vegas'] },
      usnews: { label: 'U.S. News Best Hotels', items: ['Wynn Las Vegas', 'Bellagio', 'The Venetian Resort Las Vegas', 'Aria Resort & Casino', 'Four Seasons Hotel Las Vegas', 'Encore at Wynn Las Vegas', 'The Cosmopolitan of Las Vegas', 'Vdara Hotel & Spa', 'Waldorf Astoria Las Vegas', 'NoMad Las Vegas'] },
      forbes: { label: 'Forbes Travel Guide', items: ['Wynn Las Vegas', 'Encore at Wynn Las Vegas', 'Bellagio', 'The Venetian Resort Las Vegas', 'Four Seasons Hotel Las Vegas', 'Aria Sky Suites', 'Waldorf Astoria Las Vegas', 'The Cosmopolitan of Las Vegas', 'Caesars Palace', 'Skylofts at MGM Grand'] },
    },
    vote: { items: ['Wynn Las Vegas', 'Bellagio', 'The Venetian Resort Las Vegas', 'The Cosmopolitan of Las Vegas', 'Caesars Palace', 'Encore at Wynn Las Vegas', 'Aria Resort & Casino', 'Fontainebleau Las Vegas', 'Mandalay Bay', 'MGM Grand'] },
  },
  {
    id: 'f1-fan-experience',
    publishedDate: '2026-05-25',
    title: 'F1 Races for Fan Experience',
    category: 'Formula 1',
    type: 'travel',
    tags: ['travel', 'entertainment'],
    linkType: 'wiki',
    blurb: 'Where the atmosphere outshines the cars. Tifosi in Monza, festival vibes at Zandvoort, and the unrivaled pageantry of Monaco.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ['Monaco Grand Prix', 'British Grand Prix', 'Italian Grand Prix', 'Belgian Grand Prix', 'Mexico City Grand Prix', 'Japanese Grand Prix', 'São Paulo Grand Prix', 'Dutch Grand Prix', 'Singapore Grand Prix', 'Las Vegas Grand Prix'] },
      f1experiences: { label: 'F1 Experiences', items: ['Italian Grand Prix', 'British Grand Prix', 'Monaco Grand Prix', 'Belgian Grand Prix', 'Japanese Grand Prix', 'Australian Grand Prix', 'Canadian Grand Prix', 'United States Grand Prix', 'São Paulo Grand Prix', 'Hungarian Grand Prix'] },
      motorsport: { label: 'Motorsport.com', items: ['Monaco Grand Prix', 'Dutch Grand Prix', 'British Grand Prix', 'Mexico City Grand Prix', 'Italian Grand Prix', 'Belgian Grand Prix', 'Japanese Grand Prix', 'São Paulo Grand Prix', 'Singapore Grand Prix', 'United States Grand Prix'] },
      grandprix247: { label: 'GrandPrix247', items: ['Monaco Grand Prix', 'British Grand Prix', 'Belgian Grand Prix', 'Italian Grand Prix', 'Japanese Grand Prix', 'Mexico City Grand Prix', 'São Paulo Grand Prix', 'Australian Grand Prix', 'Singapore Grand Prix', 'Canadian Grand Prix'] },
    },
    vote: { items: ['Monaco Grand Prix', 'British Grand Prix', 'Italian Grand Prix', 'Belgian Grand Prix', 'Japanese Grand Prix', 'São Paulo Grand Prix', 'Mexico City Grand Prix', 'Dutch Grand Prix', 'Singapore Grand Prix', 'Las Vegas Grand Prix'] },
  },
  {
    id: 'exclusive-golf-clubs',
    publishedDate: '2026-05-26',
    title: 'Most Exclusive Golf Clubs in the World',
    category: 'Golf',
    type: 'entertainment',
    tags: ['entertainment', 'travel'],
    linkType: 'wiki',
    blurb: 'Invitation only. No application process. Fewer than 300 members at most. The clubs where Augusta National looks almost accessible by comparison.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: ['Augusta National Golf Club', 'Pine Valley Golf Club', 'Cypress Point Club', 'Muirfield (Honourable Company of Edinburgh Golfers)', 'Royal Melbourne Golf Club (West)', 'Shinnecock Hills Golf Club', 'Seminole Golf Club', 'National Golf Links of America', 'Hirono Golf Club', 'Loch Lomond Golf Club'],
      },
      golfmag: {
        label: 'GOLF Magazine 14 Most Exclusive',
        items: ['Pine Valley Golf Club', 'Seminole Golf Club', 'Chicago Golf Club', 'Cypress Point Club', 'Nanea Golf Club', 'Augusta National Golf Club', 'Shinnecock Hills Golf Club', 'National Golf Links of America', 'San Francisco Golf Club', 'Merion Golf Club'],
      },
      billionaire: {
        label: 'Billionaire.com Top 10',
        items: ['Cypress Point Club', 'National Golf Links of America', 'Augusta National Golf Club', 'Golf de Morfontaine', 'Loch Lomond Golf Club', 'Los Angeles Country Club', 'Royal Melbourne Golf Club (West)', 'Hirono Golf Club', 'Swinley Forest Golf Club', 'Gleneagles'],
      },
      yourgolftravel: {
        label: 'Your Golf Travel · Fairway Tours',
        items: ['Augusta National Golf Club', 'Pine Valley Golf Club', 'Muirfield (Honourable Company of Edinburgh Golfers)', 'Royal Melbourne Golf Club (West)', 'Royal County Down Golf Club', 'Hirono Golf Club', 'Loch Lomond Golf Club', 'Cypress Point Club', 'Shinnecock Hills Golf Club', 'Swinley Forest Golf Club'],
      },
    },
    vote: {
      items: ['Augusta National Golf Club', 'Pine Valley Golf Club', 'Cypress Point Club', 'Shinnecock Hills Golf Club', 'Muirfield (Honourable Company of Edinburgh Golfers)', 'Seminole Golf Club', 'Royal Melbourne Golf Club (West)', 'National Golf Links of America', 'Loch Lomond Golf Club', 'Hirono Golf Club'],
    },
  },

  /* ----- ENTERTAINMENT ----- */
  {
    id: 'movies',
    publishedDate: '2026-05-24',
    title: 'Movies of All Time',
    category: 'Cinema',
    type: 'entertainment',
    linkType: 'imdb',
    blurb: 'The films that defined the medium and the ones the public refuses to forget.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ['The Godfather', 'Citizen Kane', 'Casablanca', 'The Shawshank Redemption', "Schindler's List", 'Pulp Fiction', '2001: A Space Odyssey', 'Vertigo', 'Seven Samurai', 'Lawrence of Arabia', 'The Godfather Part II', 'Goodfellas'] },
      imdb: { label: 'IMDB Top Rated', items: ['The Shawshank Redemption', 'The Godfather', 'The Dark Knight', 'The Godfather Part II', '12 Angry Men', "Schindler's List", 'The Lord of the Rings: The Return of the King', 'Pulp Fiction', 'The Lord of the Rings: The Fellowship of the Ring', 'The Good, the Bad and the Ugly', 'Forrest Gump', 'Fight Club'] },
      rotten: { label: 'Rotten Tomatoes 100 Best', items: ['Citizen Kane', 'Casablanca', 'The Wizard of Oz', 'Modern Times', 'Black Panther', 'Parasite', 'Avengers: Endgame', 'It Happened One Night', 'Get Out', 'The Cabinet of Dr. Caligari', "Singin' in the Rain", 'All About Eve'] },
    },
    vote: { items: ['The Dark Knight', 'Inception', 'Forrest Gump', 'Goodfellas', 'The Matrix', 'Spirited Away', 'Parasite', 'Fight Club', 'Back to the Future', 'Interstellar'] },
  },
  {
    id: 'top-grossing-films-1990',
    publishedDate: '2026-05-25',
    title: 'Top-Grossing Films of 1990',
    category: 'Movies · 1990',
    type: 'entertainment',
    linkType: 'imdb',
    mode: 'facts',
    blurb: 'The box office champions of 1990, ranked by worldwide gross. Ghost led the year, Home Alone became a Christmas institution, and Dances With Wolves swept the Oscars.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'Box Office Mojo · Worldwide Gross', items: ['Ghost', 'Home Alone', 'Pretty Woman', 'Dances with Wolves', 'Total Recall', 'Back to the Future Part III', 'Die Hard 2', 'Presumed Innocent', 'Teenage Mutant Ninja Turtles', 'Kindergarten Cop'] },
    },
  },
  {
    id: 'tv',
    publishedDate: '2026-05-24',
    title: 'TV Shows',
    category: 'Television',
    type: 'entertainment',
    linkType: 'imdb',
    blurb: 'The most watched television of the modern era versus the most beloved.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ['Breaking Bad', 'The Sopranos', 'The Wire', 'Mad Men', 'Game of Thrones', 'The Simpsons', 'Seinfeld', 'Better Call Saul', 'Friends', 'The Office'] },
      imdb: { label: 'IMDB Top Rated', items: ['Breaking Bad', 'Band of Brothers', 'Chernobyl', 'The Wire', 'Avatar: The Last Airbender', 'The Sopranos', 'Better Call Saul', 'Game of Thrones', 'Cosmos', 'Rick and Morty'] },
    },
    vote: { items: ['Breaking Bad', 'The Wire', 'Better Call Saul', 'The Sopranos', 'Succession', 'Mad Men', 'Chernobyl', 'Fleabag', 'Severance', 'The Leftovers'] },
  },
  {
    id: 'books',
    publishedDate: '2026-05-24',
    title: 'Books Ever Written',
    category: 'Literature',
    type: 'entertainment',
    linkType: 'amazon',
    blurb: 'The texts that sold a billion copies versus the ones that changed minds.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ['Don Quixote', 'A Tale of Two Cities', 'The Lord of the Rings', 'The Little Prince', "Harry Potter and the Philosopher's Stone", 'And Then There Were None', 'Dream of the Red Chamber', 'The Hobbit', "Alice's Adventures in Wonderland", 'The Da Vinci Code'] },
      goodreads: { label: 'Goodreads Most Loved', items: ['To Kill a Mockingbird', 'Pride and Prejudice', 'The Great Gatsby', 'The Book Thief', 'The Kite Runner', 'A Little Life', 'The Night Circus', 'Where the Crawdads Sing', 'The Song of Achilles', 'Project Hail Mary'] },
    },
    vote: { items: ['1984', 'To Kill a Mockingbird', 'Crime and Punishment', 'One Hundred Years of Solitude', 'The Brothers Karamazov', 'Beloved', 'Brave New World', 'East of Eden', 'The Master and Margarita', 'Catch-22'] },
  },
  {
    id: 'games',
    publishedDate: '2026-05-24',
    title: 'Video Games',
    category: 'Gaming',
    type: 'entertainment',
    linkType: 'steam',
    blurb: 'The titles that sold a planet versus the ones people will defend forever.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ['Minecraft', 'Grand Theft Auto V', 'Tetris', 'Wii Sports', 'PUBG: Battlegrounds', 'Mario Kart 8 Deluxe', 'Red Dead Redemption 2', 'Terraria', 'Super Mario Bros.', 'The Witcher 3: Wild Hunt'] },
      metacritic: { label: 'Metacritic All Time', items: ['The Legend of Zelda: Ocarina of Time', "Tony Hawk's Pro Skater 2", 'Grand Theft Auto IV', 'SoulCalibur', 'Super Mario Galaxy', 'Super Mario Galaxy 2', 'Red Dead Redemption 2', 'Grand Theft Auto V', 'The Orange Box', 'Metroid Prime'] },
    },
    vote: { items: ['The Legend of Zelda: Breath of the Wild', 'Elden Ring', 'The Witcher 3: Wild Hunt', 'Red Dead Redemption 2', 'Portal 2', 'Disco Elysium', 'Half-Life 2', 'Hollow Knight', 'Dark Souls', 'Stardew Valley'] },
  },

  /* ----- STORES / PLACES ----- */
  {
    id: 'pizza-nyc',
    publishedDate: '2026-05-24',
    title: 'Pizza Slices in NYC',
    category: 'New York',
    type: 'stores',
    tags: ['stores', 'food'],
    linkType: 'mapsCity',
    blurb: 'The city that built the slice. Old guard versus the new wave.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ["Joe's Pizza", 'Di Fara', 'L&B Spumoni Gardens', 'Lucali', "Patsy's Pizzeria", "John's of Bleecker Street", "Lombardi's", "Totonno's", "Roberta's", 'Prince Street Pizza', "Scarr's", "Mama's Too"] },
      eater: { label: 'Eater NY Essential 38', items: ["L'industrie", 'Lucali', 'Una Pizza Napoletana', 'Di Fara', "Joe's Pizza", 'Prince Street Pizza', "Scarr's", "Mama's Too", 'Best Pizza', 'Rubirosa'] },
      timeout: { label: 'Time Out New York', items: ["Joe's Pizza", 'Lucali', 'Di Fara', 'Prince Street Pizza', "Roberta's", "Paulie Gee's", "Lombardi's", "Totonno's", "Mama's Too", "L'industrie"] },
    },
    vote: { items: ["Joe's Pizza", "L'industrie", "Scarr's", "Mama's Too", 'Lucali', "Roberta's", 'Prince Street Pizza', 'Di Fara', 'Best Pizza', "Joe & Pat's"] },
  },
  {
    id: 'tacos-la',
    publishedDate: '2026-05-24',
    title: 'Tacos in Los Angeles',
    category: 'Los Angeles',
    type: 'stores',
    tags: ['stores', 'food'],
    linkType: 'mapsCity',
    blurb: 'A taqueria capital. Awards on one side, taco truck loyalty on the other.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ['Mariscos Jalisco', 'Guisados', 'Tacos 1986', 'Sonoratown', "Leo's Taco Truck", 'Holbox', 'B.S. Taqueria', 'Carnitas El Momo', 'El Ruso', 'Tire Shop Taqueria'] },
      latimes: { label: 'LA Times 101 Best', items: ['Mariscos Jalisco', 'Sonoratown', 'Tacos 1986', 'Carnitas El Momo', 'El Ruso', "Villa's Tacos", 'Holbox', "Leo's Taco Truck", 'Tire Shop Taqueria', 'Guisados'] },
      eater: { label: 'Eater LA', items: ['Tacos 1986', 'Sonoratown', 'Mariscos Jalisco', "Villa's Tacos", 'Carnitas El Momo', 'El Ruso', 'Guisados', 'Holbox', 'Loqui', "Leo's Taco Truck"] },
    },
    vote: { items: ['Tacos 1986', 'Sonoratown', 'Mariscos Jalisco', "Leo's Taco Truck", "Villa's Tacos", 'Guisados', 'El Ruso', 'Carnitas El Momo', 'Holbox', 'Tire Shop Taqueria'] },
  },
  {
    id: 'burritos-san-diego',
    publishedDate: '2026-05-25',
    title: 'Burritos in San Diego',
    category: 'San Diego',
    type: 'stores',
    tags: ['stores', 'food'],
    linkType: 'mapsCity',
    blurb: 'Carne asada, no beans, no rice. The California burrito was invented here and the surf shops defend it.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ["Lolita's Mexican Food", 'Las Cuatro Milpas', "Ortiz's Taco Shop", 'Taco Stand (La Jolla)', 'El Zarape', 'Lucha Libre Gourmet Taco Shop', "Adalberto's Mexican Food", "Don Tommy's", "Nico's Mexican Food", 'La Puerta'] },
      thrillist: { label: 'Thrillist · The Daily Meal', items: ['Lucha Libre Gourmet Taco Shop', "Lolita's Mexican Food", 'Las Cuatro Milpas', 'Taco Stand (La Jolla)', 'El Zarape', 'La Perla Cocina', "Nico's Mexican Food", "Adalberto's Mexican Food", 'Taco Surf', 'Don Carlos Taco Shop'] },
      plnu: { label: 'PLNU Great Burrito Bracket', items: ["Ortiz's Taco Shop", "Adalberto's Mexican Food", "Don Tommy's", 'El Zarape', 'Las Cuatro Milpas', "Lolita's Mexican Food", 'Taco Stand (La Jolla)', "Roberto's Taco Shop", 'Lucha Libre Gourmet Taco Shop', 'La Puerta'] },
      trip: { label: 'Trip.com California Burrito', items: ['El Zarape Taco Shop', 'El Zarape', 'La Puerta', 'Taco Surf', "Nico's Mexican Food", 'Don Carlos Taco Shop', "JV's Mexican Food", 'La Playa Taco Shop', "Kono's Cafe", "Lolita's Mexican Food"] },
    },
    vote: { items: ["Lolita's Mexican Food", 'Las Cuatro Milpas', 'Lucha Libre Gourmet Taco Shop', 'El Zarape', 'Taco Stand (La Jolla)', "Ortiz's Taco Shop", "Adalberto's Mexican Food", "Don Tommy's", 'La Puerta', "Roberto's Taco Shop"] },
  },
  {
    id: 'burritos-nyc',
    publishedDate: '2026-05-25',
    title: 'Burritos in NYC',
    category: 'New York',
    type: 'stores',
    tags: ['stores', 'food'],
    linkType: 'mapsCity',
    blurb: 'Mission-style transplants, fresh masa tortillas, and the breakfast burritos worth the trip uptown.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ['Sobre Masa', "B'Klyn Burro", 'La Taq (Park Slope)', 'Dos Toros Taqueria', 'Corima', 'Tacombi', 'Los Tacos No. 1', 'Birria-Landia', 'Taqueria Ramirez', 'Mission Cantina'] },
      infatuation: { label: 'The Infatuation', items: ["B'Klyn Burro", 'La Taq (Park Slope)', 'Sobre Masa', 'Tacombi', 'Los Tacos No. 1', 'Corima', 'Mission Cantina', 'Taqueria Ramirez', 'Birria-Landia', 'Calexico'] },
      timeout: { label: 'Time Out NY', items: ['Sobre Masa', 'Caballero (Park Slope)', 'La Taq (Park Slope)', 'Tacombi', 'Dos Toros Taqueria', "B'Klyn Burro", 'Los Tacos No. 1', 'Corima', 'Birria-Landia', 'Taqueria Ramirez'] },
      bestofnyc: { label: 'Best of NYC 2025', items: ['Dos Toros Taqueria', 'Tacombi', 'Los Tacos No. 1', 'Sobre Masa', 'Chipotle', 'La Esquina', "B'Klyn Burro", 'Mission Cantina', 'Calexico', 'Salvation Taco'] },
    },
    vote: { items: ['Sobre Masa', "B'Klyn Burro", 'La Taq (Park Slope)', 'Los Tacos No. 1', 'Tacombi', 'Corima', 'Dos Toros Taqueria', 'Taqueria Ramirez', 'Birria-Landia', 'Mission Cantina'] },
  },
  {
    id: 'caesar-wraps-nyc',
    publishedDate: '2026-05-26',
    title: 'Chicken Caesar Wraps in NYC',
    category: 'New York',
    type: 'stores',
    tags: ['stores', 'food'],
    linkType: 'mapsCity',
    blurb: 'The viral lunch of the decade. Crisp romaine, parmesan, grilled or fried chicken bundled in a tortilla. The shops that built the cult.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: ['Milano Market', 'Lenwich', 'Bobwhite Counter', "Jacob's Pickles", 'Heavenly Market', 'La Villa Pizzeria', "Compton's", 'Brown Bag Sandwich', "Edith's", 'Smith Gourmet Deli'],
      },
      modernluxury: {
        label: 'Modern Luxury · Gotham',
        items: ['Milano Market', 'Lenwich', 'Heavenly Market', 'La Villa Pizzeria', 'Bobwhite Counter', "Jacob's Pickles", 'The Arch Cafe', "Compton's", 'Brown Bag Sandwich', "Edith's"],
      },
      infatuation: {
        label: 'The Infatuation',
        items: ['Milano Market', 'Lenwich', 'Bobwhite Counter', "Jacob's Pickles", "Compton's", 'Brown Bag Sandwich', "Edith's", 'Smith Gourmet Deli', 'Heavenly Market', 'La Villa Pizzeria'],
      },
      yelp: {
        label: 'Yelp Top 10',
        items: ['Brown Bag Sandwich', 'Bobwhite Counter', "Edith's", "Jacob's Pickles", "Sunny and Annie's", 'Milano Market', 'Smith Gourmet Deli', "Compton's", 'Lenwich', 'Heavenly Market'],
      },
    },
    vote: {
      items: ['Milano Market', 'Lenwich', 'Bobwhite Counter', "Jacob's Pickles", "Edith's", 'Heavenly Market', "Compton's", 'La Villa Pizzeria', 'Brown Bag Sandwich', 'Smith Gourmet Deli'],
    },
  },
  {
    id: 'caesar-wraps-la',
    publishedDate: '2026-05-26',
    title: 'Chicken Caesar Wraps in LA',
    category: 'Los Angeles',
    type: 'stores',
    tags: ['stores', 'food'],
    linkType: 'mapsCity',
    blurb: 'Ggiata started a movement and the rest of the city followed. Crispy chicken, romaine, parmesan. The only debate is the dressing.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: ['Ggiata', "Uncle Paulie's Deli", 'Goop Kitchen', 'Garden Cafe', 'Aroma Coffee & Tea', 'Il Tramezzino', "Joan's on Third", 'Cafe Bizou', 'Black Rabbit Cafe', 'Leora Cafe'],
      },
      yelp: {
        label: 'Yelp Top 10',
        items: ['Ggiata', "Uncle Paulie's Deli", 'Garden Cafe', 'Aroma Coffee & Tea', 'Goop Kitchen', 'Ggiata West Hollywood', 'Il Tramezzino', 'Black Rabbit Cafe', "Joan's on Third", 'Leora Cafe'],
      },
      latimes: {
        label: 'LA Times · Eater LA',
        items: ['Ggiata', "Uncle Paulie's Deli", 'Cafe Bizou', "Joan's on Third", 'Goop Kitchen', 'Il Tramezzino', 'Garden Cafe', 'Aroma Coffee & Tea', 'Black Rabbit Cafe', 'Leora Cafe'],
      },
      timeout: {
        label: 'Time Out Los Angeles',
        items: ['Ggiata', 'Goop Kitchen', "Uncle Paulie's Deli", "Joan's on Third", 'Garden Cafe', 'Leora Cafe', 'Cafe Bizou', 'Aroma Coffee & Tea', 'Il Tramezzino', 'Black Rabbit Cafe'],
      },
    },
    vote: {
      items: ['Ggiata', "Uncle Paulie's Deli", 'Goop Kitchen', "Joan's on Third", 'Garden Cafe', 'Il Tramezzino', 'Aroma Coffee & Tea', 'Cafe Bizou', 'Leora Cafe', 'Black Rabbit Cafe'],
    },
  },
  {
    id: 'caesar-wraps-miami',
    publishedDate: '2026-05-26',
    title: 'Chicken Caesar Wraps in Miami',
    category: 'Miami',
    type: 'stores',
    tags: ['stores', 'food'],
    linkType: 'mapsCity',
    blurb: "Boca's Vinny's Cafe set Florida on fire. The Miami spots that followed bring beach-town twists to the viral wrap.",
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: ['Tap 42', "Vinny's Cafe (Boca)", 'The Brightside', 'Carrot Express', 'Pura Vida Miami', 'Mister O1 South Beach', 'Pane e Vino', 'Cafe Papillon By The Beach', 'Giardino', 'High Tide'],
      },
      miaminewtimes: {
        label: 'Miami New Times',
        items: ["Vinny's Cafe (Boca)", 'Tap 42', 'The Brightside', 'Pura Vida Miami', 'Carrot Express', 'Giardino', 'Mister O1 South Beach', 'Pane e Vino', 'High Tide', 'Cafe Papillon By The Beach'],
      },
      yelp: {
        label: 'Yelp Top 10',
        items: ['Carrot Express', 'The Brightside', 'Pura Vida Miami', 'Mister O1 South Beach', 'Pane e Vino', 'Cafe Papillon By The Beach', 'High Tide', 'Tap 42', 'Giardino', "Vinny's Cafe (Boca)"],
      },
      timeout: {
        label: 'Time Out Miami',
        items: ['Tap 42', "Vinny's Cafe (Boca)", 'Pura Vida Miami', 'Carrot Express', 'The Brightside', 'Giardino', 'Pane e Vino', 'Mister O1 South Beach', 'High Tide', 'Cafe Papillon By The Beach'],
      },
    },
    vote: {
      items: ['Tap 42', "Vinny's Cafe (Boca)", 'Carrot Express', 'The Brightside', 'Pura Vida Miami', 'Giardino', 'Mister O1 South Beach', 'Pane e Vino', 'High Tide', 'Cafe Papillon By The Beach'],
    },
  },
  {
    id: 'caesar-wraps-chicago',
    publishedDate: '2026-05-26',
    title: 'Chicken Caesar Wraps in Chicago',
    category: 'Chicago',
    type: 'stores',
    tags: ['stores', 'food'],
    linkType: 'mapsCity',
    blurb: 'From Bridgeport flatbread originals to Wicker Park fried chicken collabs. The CCW capital of the Midwest.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: ["Punky's Pizza & Pasta", 'Little Victories', 'Nohea Cafe', 'Village Tap', 'Moonwalker', "GG's Chicken Shop", "D'Amato's Bakery", 'Pompeii', 'Buttermilk Fry', 'Spilt Milk'],
      },
      infatuation: {
        label: 'The Infatuation 8 Best',
        items: ["Punky's Pizza & Pasta", 'Little Victories', 'Nohea Cafe', 'Village Tap', 'Moonwalker', 'Buttermilk Fry', "GG's Chicken Shop", "D'Amato's Bakery", 'Spilt Milk', 'Pompeii'],
      },
      tribune: {
        label: 'Chicago Tribune',
        items: ["Punky's Pizza & Pasta", 'Nohea Cafe', 'Village Tap', 'Moonwalker', 'Little Victories', "GG's Chicken Shop", 'Buttermilk Fry', "D'Amato's Bakery", 'Pompeii', 'Spilt Milk'],
      },
      yelp: {
        label: 'Yelp Top 10',
        items: ['Little Victories', "Punky's Pizza & Pasta", 'Nohea Cafe', "GG's Chicken Shop", 'Village Tap', "D'Amato's Bakery", 'Moonwalker', 'Buttermilk Fry', 'Pompeii', 'Spilt Milk'],
      },
    },
    vote: {
      items: ["Punky's Pizza & Pasta", 'Little Victories', 'Nohea Cafe', 'Village Tap', 'Moonwalker', "GG's Chicken Shop", 'Buttermilk Fry', "D'Amato's Bakery", 'Pompeii', 'Spilt Milk'],
    },
  },
  {
    id: 'cocktails-williamsburg',
    publishedDate: '2026-05-25',
    title: 'Cocktail Bars in Williamsburg',
    category: 'Williamsburg, Brooklyn',
    type: 'stores',
    tags: ['stores', 'food', 'bars', 'nightlife'],
    linkType: 'mapsCity',
    blurb: 'Oyster-bar standards, rooftop skyline pours, and the no-menu mixology rooms that put Brooklyn on the cocktail map.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ['Maison Premiere', 'Fresh Kills Bar', 'Bar Blondeau', 'Westlight', 'Rose Marie', 'Bar Madonna', 'Sauced', 'Layla', 'Pokito', 'Le Crocodile'] },
      infatuation: { label: 'The Infatuation 22 Best', items: ['Maison Premiere', 'Rose Marie', 'Bar Blondeau', 'Sauced', 'Layla', 'Fresh Kills Bar', 'Bar Madonna', 'Westlight', "Mo's General", 'Le Crocodile'] },
      timeout: { label: 'Time Out New York', items: ['Maison Premiere', 'Bar Madonna', 'Velvet Brooklyn', 'The Twenty Bar', 'Fresh Kills Bar', 'Pokito', 'Westlight', 'Bar Blondeau', 'Bar Milagro', 'Layla'] },
      worlds50best: { label: "World's 50 Best Bars (NA)", items: ['Maison Premiere', 'Fresh Kills Bar', 'Bar Blondeau', 'Rose Marie', 'Le Crocodile', 'Westlight', 'Bar Madonna', 'Layla', 'Sauced', 'Pokito'] },
    },
    vote: { items: ['Maison Premiere', 'Fresh Kills Bar', 'Bar Blondeau', 'Westlight', 'Rose Marie', 'Bar Madonna', 'Le Crocodile', 'Layla', 'Sauced', 'Pokito'] },
  },
  {
    id: 'live-music-nyc',
    publishedDate: '2026-05-25',
    title: 'Live Music Bars in NYC',
    category: 'New York',
    type: 'stores',
    tags: ['stores', 'entertainment', 'bars', 'nightlife'],
    linkType: 'mapsCity',
    blurb: "The rooms where Vampire Weekend, The Strokes, and a thousand more got their break. Indie, jazz, and the rising acts you'll claim you saw first.",
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ['Bowery Ballroom', 'Mercury Lounge', 'Music Hall of Williamsburg', 'Rockwood Music Hall', "Arlene's Grocery", 'Blue Note Jazz Club', 'Village Vanguard', 'Birdland Jazz Club', "Baby's All Right", 'The Bitter End'] },
      timeout: { label: 'Time Out New York', items: ['Bowery Ballroom', 'Music Hall of Williamsburg', 'Mercury Lounge', "Baby's All Right", 'Rockwood Music Hall', 'Village Vanguard', 'Blue Note Jazz Club', 'Birdland Jazz Club', "Pete's Candy Store", 'The Django'] },
      happyhour: { label: 'Happy Hour NYC Guide', items: ["Baby's All Right", 'Birdland Jazz Club', 'Blue Note Jazz Club', 'Bowery Ballroom', 'Mercury Lounge', "Pete's Candy Store", 'Rockwood Music Hall', 'Terra Blues', 'The Django', 'Village Vanguard'] },
      gwepa: { label: 'GWEPA 55 Best Venues', items: ['Bowery Ballroom', 'Mercury Lounge', 'Rockwood Music Hall', 'Bowery Electric', "Arlene's Grocery", 'Highline Ballroom', 'Music Hall of Williamsburg', 'Pianos', 'The Bitter End', 'Slake'] },
    },
    vote: { items: ['Bowery Ballroom', 'Mercury Lounge', 'Village Vanguard', 'Music Hall of Williamsburg', 'Blue Note Jazz Club', 'Rockwood Music Hall', "Baby's All Right", 'Birdland Jazz Club', "Arlene's Grocery", 'The Bitter End'] },
  },
  {
    id: 'dive-bars-williamsburg',
    publishedDate: '2026-05-26',
    title: 'Dive Bars in Williamsburg',
    category: 'Williamsburg, Brooklyn',
    type: 'stores',
    tags: ['stores', 'bars', 'nightlife'],
    linkType: 'mapsCity',
    blurb: 'Sticky floors, cheap beer, classic rock jukeboxes. The bars that resisted the gentrification or learned to coexist with it.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: ['The Commodore', 'Rocka Rolla', "Turkey's Nest", 'Skinny Dennis', "Sharlene's", "Duff's Brooklyn", 'R Bar', "Clem's", "Pete's Candy Store", 'Boobie Trap'],
      },
      infatuation: {
        label: 'The Infatuation',
        items: ['Rocka Rolla', 'The Commodore', "Turkey's Nest", "Clem's", 'R Bar', "Duff's Brooklyn", 'Skinny Dennis', "Sharlene's", "Pete's Candy Store", 'Boobie Trap'],
      },
      timeout: {
        label: 'Time Out New York',
        items: ['The Commodore', 'Skinny Dennis', "Turkey's Nest", 'Rocka Rolla', 'R Bar', "Duff's Brooklyn", "Sharlene's", "Clem's", 'Boobie Trap', "Pete's Candy Store"],
      },
      vinepair: {
        label: 'VinePair 20 Best',
        items: ["Duff's Brooklyn", 'The Commodore', "Turkey's Nest", 'Skinny Dennis', 'Rocka Rolla', "Sharlene's", "Clem's", "Pete's Candy Store", 'R Bar', 'Boobie Trap'],
      },
    },
    vote: {
      items: ['The Commodore', "Turkey's Nest", 'Skinny Dennis', 'Rocka Rolla', "Duff's Brooklyn", "Sharlene's", "Clem's", "Pete's Candy Store", 'R Bar', 'Boobie Trap'],
    },
  },
  {
    id: 'dive-bars-greenpoint',
    publishedDate: '2026-05-26',
    title: 'Dive Bars in Greenpoint',
    category: 'Greenpoint, Brooklyn',
    type: 'stores',
    tags: ['stores', 'bars', 'nightlife'],
    linkType: 'mapsCity',
    blurb: 'Pinball machines, jello shots, and the Polish bar crawls that put Greenpoint on the map. Where the G train regulars roost.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: ['Black Rabbit', 'Sunshine Laundromat & Pinball', 'Lake Street', 'The Drift', "Temkin's Bar", 'Broken Land', 'The Capri Social Club', 'Palace Cafe', 'The Moonlight Mile', "Connie O's Pub"],
      },
      infatuation: {
        label: 'The Infatuation',
        items: ['Lake Street', 'Sunshine Laundromat & Pinball', 'Black Rabbit', 'Broken Land', 'The Drift', "Temkin's Bar", 'Palace Cafe', "Connie O's Pub", 'The Capri Social Club', 'The Moonlight Mile'],
      },
      yelp: {
        label: 'Yelp Top 10',
        items: ["Temkin's Bar", 'A Bar', 'Broken Land', 'Lake Street', 'The Drift', 'The Capri Social Club', 'Sunshine Laundromat & Pinball', 'The Moonlight Mile', 'Oak and Iron', 'Black Rabbit'],
      },
      timeout: {
        label: 'Time Out New York',
        items: ['Black Rabbit', 'Sunshine Laundromat & Pinball', 'The Drift', 'Lake Street', "Temkin's Bar", 'Palace Cafe', 'Broken Land', "Connie O's Pub", 'The Capri Social Club', 'The Moonlight Mile'],
      },
    },
    vote: {
      items: ['Black Rabbit', 'Sunshine Laundromat & Pinball', 'Lake Street', "Temkin's Bar", 'The Drift', 'Broken Land', 'Palace Cafe', 'The Capri Social Club', "Connie O's Pub", 'The Moonlight Mile'],
    },
  },
  {
    id: 'dive-bars-east-village',
    publishedDate: '2026-05-26',
    title: 'Dive Bars in the East Village',
    category: 'East Village',
    type: 'stores',
    tags: ['stores', 'bars', 'nightlife'],
    linkType: 'mapsCity',
    blurb: "McSorley's since 1854. Lucy's reborn. The grit and grime that gave New York nightlife its reputation.",
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: ["McSorley's Old Ale House", "Lucy's", 'Holiday Cocktail Lounge', 'Tile Bar', "Sophie's", 'KGB Bar', 'Blue & Gold Tavern', 'Cherry Tavern', "Mona's", "Milano's Bar"],
      },
      infatuation: {
        label: 'The Infatuation',
        items: ["Lucy's", 'Holiday Cocktail Lounge', "McSorley's Old Ale House", 'Tile Bar', "Sophie's", 'KGB Bar', 'Blue & Gold Tavern', "Mona's", 'Cherry Tavern', "Milano's Bar"],
      },
      vinepair: {
        label: 'VinePair 20 Best',
        items: ["Sophie's", "McSorley's Old Ale House", 'Holiday Cocktail Lounge', "Lucy's", 'Blue & Gold Tavern', 'Tile Bar', 'KGB Bar', "Mona's", "Milano's Bar", 'Cherry Tavern'],
      },
      timeout: {
        label: 'Time Out New York',
        items: ["McSorley's Old Ale House", 'Holiday Cocktail Lounge', "Lucy's", 'Tile Bar', "Sophie's", 'Blue & Gold Tavern', 'KGB Bar', "Milano's Bar", "Mona's", 'Cherry Tavern'],
      },
    },
    vote: {
      items: ["McSorley's Old Ale House", "Lucy's", 'Holiday Cocktail Lounge', 'Tile Bar', "Sophie's", 'KGB Bar', 'Blue & Gold Tavern', "Mona's", "Milano's Bar", 'Cherry Tavern'],
    },
  },
  {
    id: 'dive-bars-greenwich-village',
    publishedDate: '2026-05-26',
    title: 'Dive Bars in Greenwich Village',
    category: 'Greenwich Village',
    type: 'stores',
    tags: ['stores', 'bars', 'nightlife'],
    linkType: 'mapsCity',
    blurb: 'Where the Beats drank. Where Dylan sang. Time-capsule bars on the same blocks as Bleecker Street tourists.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: ['Kettle of Fish', 'Down the Hatch', "Johnny's Bar", "Julius'", 'The Four-Faced Liar', 'Peculier Pub', 'Bleecker Street Bar', 'The Library', 'PubKey', 'Fish Bar'],
      },
      eater: {
        label: 'Eater NY 25 Best',
        items: ["Johnny's Bar", "Julius'", 'Kettle of Fish', 'Down the Hatch', 'The Four-Faced Liar', 'Bleecker Street Bar', 'Peculier Pub', 'The Library', 'PubKey', 'Fish Bar'],
      },
      yelp: {
        label: 'Yelp Top 10',
        items: ['124 Old Rabbit Club', 'The Four-Faced Liar', 'PubKey', 'Wide Shut', 'Beltane', 'The Library', 'Peculier Pub', 'Park Bar', "Johnny's Bar", 'Bleecker Street Bar'],
      },
      timeout: {
        label: 'Time Out New York',
        items: ['Kettle of Fish', "Johnny's Bar", "Julius'", 'Down the Hatch', 'The Four-Faced Liar', 'Bleecker Street Bar', 'The Library', 'Peculier Pub', 'PubKey', 'Fish Bar'],
      },
    },
    vote: {
      items: ['Kettle of Fish', "Johnny's Bar", 'Down the Hatch', "Julius'", 'The Four-Faced Liar', 'Peculier Pub', 'Bleecker Street Bar', 'The Library', 'PubKey', 'Fish Bar'],
    },
  },
  {
    id: 'dive-bars-cape-cod',
    publishedDate: '2026-05-26',
    title: 'Dive Bars on Cape Cod',
    category: 'Cape Cod',
    type: 'stores',
    tags: ['stores', 'bars', 'nightlife'],
    linkType: 'mapsCity',
    blurb: 'Where the locals drink when the summer crowds clear out. Old Colony in P-town, the 19th Hole in Hyannis since 1930, and the Fox Hole patron saint of Osterville.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: ['Old Colony Tap (Provincetown)', '19th Hole Tavern (Hyannis)', 'The Fox Hole (Osterville)', 'Bomb Shelter (Wellfleet)', 'The Underground (Provincetown)', 'Chatham Squire (Chatham)', "Sundancer's (West Dennis)", 'Quarterdeck Lounge (Hyannis)', 'Duck Inn Pub (Hyannis)', 'Four Point Tavern (Hyannis)'],
      },
      capecodchamber: {
        label: 'Cape Cod Chamber',
        items: ['Old Colony Tap (Provincetown)', '19th Hole Tavern (Hyannis)', 'The Fox Hole (Osterville)', 'Bomb Shelter (Wellfleet)', "Sundancer's (West Dennis)", 'Chatham Squire (Chatham)', 'The Underground (Provincetown)', 'Quarterdeck Lounge (Hyannis)', 'Duck Inn Pub (Hyannis)', 'Four Point Tavern (Hyannis)'],
      },
      yelp: {
        label: 'Yelp Top Picks',
        items: ['Old Colony Tap (Provincetown)', 'The Underground (Provincetown)', '19th Hole Tavern (Hyannis)', 'Bomb Shelter (Wellfleet)', 'The Fox Hole (Osterville)', 'Chatham Squire (Chatham)', "Sundancer's (West Dennis)", 'Quarterdeck Lounge (Hyannis)', 'Duck Inn Pub (Hyannis)', 'Four Point Tavern (Hyannis)'],
      },
      vacationcapecod: {
        label: 'Vacation Cape Cod',
        items: ['Old Colony Tap (Provincetown)', 'The Underground (Provincetown)', 'Chatham Squire (Chatham)', 'The Fox Hole (Osterville)', '19th Hole Tavern (Hyannis)', 'Bomb Shelter (Wellfleet)', "Sundancer's (West Dennis)", 'Quarterdeck Lounge (Hyannis)', 'Duck Inn Pub (Hyannis)', 'Four Point Tavern (Hyannis)'],
      },
    },
    vote: {
      items: ['Old Colony Tap (Provincetown)', '19th Hole Tavern (Hyannis)', 'The Fox Hole (Osterville)', 'The Underground (Provincetown)', 'Bomb Shelter (Wellfleet)', 'Chatham Squire (Chatham)', "Sundancer's (West Dennis)", 'Quarterdeck Lounge (Hyannis)', 'Duck Inn Pub (Hyannis)', 'Four Point Tavern (Hyannis)'],
    },
  },
  {
    id: 'cocktails-west-village',
    publishedDate: '2026-05-26',
    title: 'Cocktail Bars in the West Village',
    category: 'West Village',
    type: 'stores',
    tags: ['stores', 'food', 'bars', 'nightlife'],
    linkType: 'mapsCity',
    blurb: "Dante set the standard when it was named World's Best. Bandits, Little Branch, and Katana Kitten kept the pressure on.",
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: ['Dante', 'Bandits', 'Little Branch', 'Katana Kitten', 'Employees Only', 'Bar Pisellino', "Angel's Share", 'Sip & Guzzle', 'Bobo', 'Analogue'],
      },
      infatuation: {
        label: 'The Infatuation 20 Best',
        items: ['Dante', 'Katana Kitten', "Angel's Share", 'Sip & Guzzle', 'Bar Pisellino', 'Little Branch', 'Employees Only', 'Bandits', 'Bobo', 'Binx'],
      },
      timeout: {
        label: 'Time Out 14 Best',
        items: ['Dante', 'Bandits', 'Little Branch', 'Employees Only', 'Bar Pisellino', 'Katana Kitten', "Angel's Share", 'Analogue', 'Bobo', 'Sip & Guzzle'],
      },
      worlds50best: {
        label: "World's 50 Best Bars",
        items: ['Dante', "Angel's Share", 'Katana Kitten', 'Sip & Guzzle', 'Employees Only', 'Little Branch', 'Bar Pisellino', 'Bandits', 'Analogue', 'Bobo'],
      },
    },
    vote: {
      items: ['Dante', 'Bandits', 'Little Branch', 'Katana Kitten', 'Employees Only', 'Bar Pisellino', "Angel's Share", 'Sip & Guzzle', 'Analogue', 'Bobo'],
    },
  },
  {
    id: 'cocktails-soho',
    publishedDate: '2026-05-26',
    title: 'Cocktail Bars in SoHo',
    category: 'SoHo',
    type: 'stores',
    tags: ['stores', 'food', 'bars', 'nightlife'],
    linkType: 'mapsCity',
    blurb: "Hotel hideouts, micro bars tucked above home goods stores, and the speakeasies that survived the neighborhood's gallery-to-luxury pivot.",
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: ['South Soho Bar', "Sloane's", "Milady's", 'Guild Bar', 'La Compagnie des Vins Surnaturels', 'Kabin', 'Foxtail', 'The Ship', 'Grand Bar', 'Broome Street Bar'],
      },
      infatuation: {
        label: 'The Infatuation 12 Best',
        items: ['South Soho Bar', "Milady's", 'Guild Bar', 'La Compagnie des Vins Surnaturels', 'Broome Street Bar', 'Kabin', "Sloane's", 'Foxtail', 'The Ship', 'Grand Bar'],
      },
      timeout: {
        label: 'Time Out New York',
        items: ["Sloane's", 'Kabin', 'South Soho Bar', "Milady's", 'Grand Bar', 'Foxtail', 'Guild Bar', 'La Compagnie des Vins Surnaturels', 'The Ship', 'Broome Street Bar'],
      },
      sohoweekly: {
        label: 'SoHo Weekly 15 Best',
        items: ["Sloane's", 'Grand Bar', 'South Soho Bar', "Milady's", 'Kabin', 'Guild Bar', 'Foxtail', 'La Compagnie des Vins Surnaturels', 'The Ship', 'Broome Street Bar'],
      },
    },
    vote: {
      items: ['South Soho Bar', "Sloane's", "Milady's", 'Kabin', 'Guild Bar', 'Grand Bar', 'Foxtail', 'La Compagnie des Vins Surnaturels', 'The Ship', 'Broome Street Bar'],
    },
  },
  {
    id: 'ramen-tokyo',
    publishedDate: '2026-05-24',
    title: 'Ramen Shops in Tokyo',
    category: 'Tokyo',
    type: 'stores',
    tags: ['stores', 'food'],
    linkType: 'mapsCity',
    blurb: 'Michelin-starred broth versus the bowls locals queue an hour for.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ['Tsuta', 'Nakiryu', 'Konjiki Hototogisu', 'Afuri', 'Rokurinsha', 'Mensho', 'Menya Musashi', 'Ginza Kagari', 'Ippudo', 'Ramen Jiro'] },
      michelin: { label: 'Michelin Guide Tokyo', items: ['Nakiryu', 'Tsuta', 'Konjiki Hototogisu', 'Ginza Kagari', 'Soranoiro', 'Mensho', 'Afuri', 'Menya Itto', 'Ramen Tatsunoya', 'Rokurinsha'] },
      timeout: { label: 'Time Out Tokyo', items: ['Afuri', 'Ichiran', 'Mensho', 'Konjiki Hototogisu', 'Rokurinsha', 'Tsuta', 'Ramen Jiro', 'Menya Musashi', 'Ippudo', 'Ginza Kagari'] },
    },
    vote: { items: ['Ichiran', 'Konjiki Hototogisu', 'Afuri', 'Tsuta', 'Mensho', 'Ginza Kagari', 'Rokurinsha', 'Ippudo', 'Nakiryu', 'Menya Musashi'] },
  },
  {
    id: 'bagels-nyc',
    publishedDate: '2026-05-24',
    title: 'Bagel Shops in NYC',
    category: 'New York',
    type: 'stores',
    tags: ['stores', 'food'],
    linkType: 'mapsCity',
    blurb: 'Boiled, baked, and argued about. Institutions face the new generation.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ['Russ & Daughters', 'Ess-a-Bagel', 'Absolute Bagels', "Murray's Bagels", 'H&H Bagels', 'Tompkins Square Bagels', 'Brooklyn Bagel & Coffee Company', 'Black Seed', "Bo's Bagels", 'Utopia Bagels'] },
      eater: { label: 'Eater NY', items: ['Ess-a-Bagel', 'Russ & Daughters', 'Apollo Bagels', 'PopUp Bagels', 'Utopia Bagels', 'Tompkins Square Bagels', "Bo's Bagels", 'Best Bagel & Coffee', 'Tal Bagels', 'Black Seed'] },
    },
    vote: { items: ['Ess-a-Bagel', 'Russ & Daughters', 'Apollo Bagels', 'PopUp Bagels', 'Tompkins Square Bagels', 'Utopia Bagels', 'Tal Bagels', "Bo's Bagels", 'Best Bagel & Coffee', 'Absolute Bagels'] },
  },
  {
    id: 'breakfast-sandwiches-hamptons',
    publishedDate: '2026-05-26',
    title: 'Breakfast Sandwiches in the Hamptons',
    category: 'The Hamptons',
    type: 'stores',
    tags: ['stores', 'food'],
    linkType: 'mapsCity',
    blurb: "The BEC reigns from Montauk to Westhampton. Goldberg's hobo, Carissa's sourdough upgrade, and Cove's triple bypass. Where the East End starts its mornings.",
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: ["Carissa's The Bakery (East Hampton)", "Goldberg's Famous Bagels (Multiple Locations)", 'Cove Delicatessen (Sag Harbor)', 'Bonfire Coffeehouse (East Hampton)', "Cromer's Market (Noyac)", 'Hampton Kitchen Delicatessen (Water Mill)', 'Golden Pear Cafe (Multiple Locations)', 'Harbor Market & Kitchen (Sag Harbor)', 'John Papas Cafe (East Hampton)', "Damark's Market (East Hampton)"],
      },
      southforker: {
        label: 'Southforker',
        items: ['Bonfire Coffeehouse (East Hampton)', "Goldberg's Famous Bagels (Multiple Locations)", 'Cove Delicatessen (Sag Harbor)', 'Hampton Kitchen Delicatessen (Water Mill)', "Carissa's The Bakery (East Hampton)", "Cromer's Market (Noyac)", 'Harbor Market & Kitchen (Sag Harbor)', "Damark's Market (East Hampton)", 'Golden Pear Cafe (Multiple Locations)', 'John Papas Cafe (East Hampton)'],
      },
      purewow: {
        label: 'PureWow',
        items: ["Carissa's The Bakery (East Hampton)", "Goldberg's Famous Bagels (Multiple Locations)", 'Harbor Market & Kitchen (Sag Harbor)', 'Golden Pear Cafe (Multiple Locations)', 'Bonfire Coffeehouse (East Hampton)', 'Sant Ambroeus (Southampton)', "Cromer's Market (Noyac)", 'Cove Delicatessen (Sag Harbor)', 'Hampton Kitchen Delicatessen (Water Mill)', 'John Papas Cafe (East Hampton)'],
      },
      yelp: {
        label: 'Yelp Top 10',
        items: ['Bonfire Coffeehouse (East Hampton)', "Goldberg's Famous Bagels (Multiple Locations)", "Carissa's The Bakery (East Hampton)", 'Cove Delicatessen (Sag Harbor)', 'John Papas Cafe (East Hampton)', "Damark's Market (East Hampton)", 'Hampton Chutney (East Hampton)', 'Golden Pear Cafe (Multiple Locations)', "Cromer's Market (Noyac)", 'Harbor Market & Kitchen (Sag Harbor)'],
      },
    },
    vote: {
      items: ["Carissa's The Bakery (East Hampton)", "Goldberg's Famous Bagels (Multiple Locations)", 'Bonfire Coffeehouse (East Hampton)', 'Cove Delicatessen (Sag Harbor)', "Cromer's Market (Noyac)", 'Hampton Kitchen Delicatessen (Water Mill)', 'Golden Pear Cafe (Multiple Locations)', 'Harbor Market & Kitchen (Sag Harbor)', 'John Papas Cafe (East Hampton)', "Damark's Market (East Hampton)"],
    },
  },
  {
    id: 'bbq-texas',
    publishedDate: '2026-05-24',
    title: 'BBQ Joints in Texas',
    category: 'Texas',
    type: 'stores',
    tags: ['stores', 'food'],
    linkType: 'mapsCity',
    blurb: 'Smoke rings, brisket bark, and central Texas heritage on the line.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ["Snow's BBQ", 'Franklin Barbecue', "Goldee's BBQ", 'Pecan Lodge', 'Louie Mueller Barbecue', "Black's Barbecue", 'Kreuz Market', 'Cattleack Barbeque', 'La Barbecue', 'Truth BBQ'] },
      texasmonthly: { label: 'Texas Monthly Top 50', items: ["Goldee's BBQ", "Snow's BBQ", 'Franklin Barbecue', 'Interstellar BBQ', 'Truth BBQ', 'Cattleack Barbeque', 'Pecan Lodge', 'La Barbecue', 'Louie Mueller Barbecue', "Brotherton's Black Iron Barbecue"] },
    },
    vote: { items: ['Franklin Barbecue', "Goldee's BBQ", "Snow's BBQ", "Terry Black's", 'La Barbecue', 'Pecan Lodge', 'Truth BBQ', 'Hutchins BBQ', 'Cattleack Barbeque', 'InterStellar BBQ'] },
  },
  {
    id: 'pasta-rome',
    publishedDate: '2026-05-24',
    title: 'Pasta in Rome',
    category: 'Rome',
    type: 'stores',
    tags: ['stores', 'food'],
    linkType: 'mapsCity',
    blurb: 'Carbonara, cacio e pepe, amatriciana. Tradition rules, but who does it best?',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ['Roscioli', 'Armando al Pantheon', 'Da Enzo al 29', 'Felice a Testaccio', 'Pierluigi', 'Cesare al Casaletto', "L'Arcangelo", 'Da Danilo', 'Trattoria Pennestri', 'Salumeria Roscioli'] },
      eater: { label: 'Eater Rome Guides', items: ['Roscioli', 'Da Enzo al 29', 'Felice a Testaccio', 'Armando al Pantheon', 'Trattoria Pennestri', 'Cesare al Casaletto', 'Pianostrada', 'Sora Lella', 'Pierluigi', 'Tonnarello'] },
    },
    vote: { items: ['Roscioli', 'Da Enzo al 29', 'Felice a Testaccio', 'Armando al Pantheon', 'Tonnarello', 'Pierluigi', 'Sora Lella', 'Trattoria Pennestri', 'Pianostrada', 'Cesare al Casaletto'] },
  },
  {
    id: 'cocktails-london',
    publishedDate: '2026-05-24',
    title: 'Cocktail Bars in London',
    category: 'London',
    type: 'stores',
    tags: ['stores', 'food', 'bars', 'nightlife'],
    linkType: 'mapsCity',
    blurb: 'Hotel bars in dinner jackets versus the speakeasy crowd shaking the future.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ['Connaught Bar', 'Tayer + Elementary', 'Swift', 'Lyaness', 'A Bar with Shapes for a Name', 'Side Hustle', "Satan's Whiskers", 'Kwānt', 'Three Sheets', 'Happiness Forgets'] },
      worlds50best: { label: "World's 50 Best Bars", items: ['A Bar with Shapes for a Name', 'Tayer + Elementary', 'Connaught Bar', 'Swift', 'Side Hustle', 'Kwānt', 'Below Stone Nest', 'Lyaness', "Satan's Whiskers", 'Three Sheets'] },
    },
    vote: { items: ['Connaught Bar', 'A Bar with Shapes for a Name', 'Tayer + Elementary', 'Swift', 'Below Stone Nest', "Satan's Whiskers", 'Happiness Forgets', 'Lyaness', 'Bar Termini', 'Side Hustle'] },
  },
  {
    id: 'steakhouse-chicago',
    publishedDate: '2026-05-25',
    title: 'Steakhouses in Chicago',
    category: 'Chicago',
    type: 'stores',
    tags: ['stores', 'food'],
    linkType: 'mapsCity',
    blurb: 'Where the porterhouse is sacred and the martinis are big enough to swim in.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ["Bavette's Bar & Boeuf", "Gibson's Bar & Steakhouse", 'Gene & Georgetti', 'Maple & Ash', 'Swift & Sons', 'RPM Steak', 'Chicago Cut Steakhouse', "Mastro's", 'Smith & Wollensky', 'Boeufhaus'] },
      tribune: { label: 'Chicago Tribune', items: ["Bavette's Bar & Boeuf", 'Maple & Ash', "Gibson's Bar & Steakhouse", 'Swift & Sons', 'Boeufhaus', 'RPM Steak', 'Gene & Georgetti', 'Chicago Cut Steakhouse', 'Rosebud Steakhouse', 'Tango Sur'] },
    },
    vote: { items: ["Bavette's Bar & Boeuf", "Gibson's Bar & Steakhouse", 'Maple & Ash', 'Swift & Sons', 'RPM Steak', 'Boeufhaus', 'Gene & Georgetti', 'Chicago Cut Steakhouse', "Mastro's", 'Smith & Wollensky'] },
  },
  {
    id: 'bookstores-paris',
    publishedDate: '2026-05-25',
    title: 'Bookstores in Paris',
    category: 'Paris',
    type: 'stores',
    linkType: 'mapsCity',
    blurb: 'Storied institutions and the indie shops keeping reading alive.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ['Shakespeare and Company', 'Librairie Galignani', 'La Hune', 'Librairie Gallimard', "L'Écume des Pages", 'Le Divan', 'Gibert Joseph', 'Assouline', 'Librairie Petite Égypte', 'Librairie Picard'] },
      timeout: { label: 'Time Out Paris', items: ['Shakespeare and Company', 'Librairie Galignani', 'Ofr.', "L'Écume des Pages", '7L', 'Yvon Lambert', 'La Hune', 'Le Divan', 'Berkeley Books of Paris', 'Librairie Petite Égypte'] },
    },
    vote: { items: ['Shakespeare and Company', 'Librairie Galignani', "L'Écume des Pages", 'La Hune', 'Le Divan', 'Ofr.', 'Yvon Lambert', '7L', 'Berkeley Books of Paris', 'Librairie Petite Égypte'] },
  },
  {
    id: 'dimsum-hk',
    publishedDate: '2026-05-25',
    title: 'Dim Sum in Hong Kong',
    category: 'Hong Kong',
    type: 'stores',
    tags: ['stores', 'food'],
    linkType: 'mapsCity',
    blurb: 'Trolley dining at noon, cheap baskets at dawn, three-star refinement in between.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ['Lung King Heen', "T'ang Court", 'Yan Toh Heen', 'Fook Lam Moon', 'Tim Ho Wan', 'One Harbour Road', 'Lin Heung Tea House', "Maxim's Palace", 'Luk Yu Tea House', "Duddell's"] },
      michelin: { label: 'Michelin Guide Hong Kong', items: ['Lung King Heen', "T'ang Court", 'Yan Toh Heen', 'Tim Ho Wan', "Duddell's", 'Fook Lam Moon', 'Above & Beyond', 'Spring Moon', 'Cuisine Cuisine', 'One Harbour Road'] },
    },
    vote: { items: ['Tim Ho Wan', 'Lung King Heen', 'Lin Heung Tea House', "Maxim's Palace", 'Fook Lam Moon', 'Yum Cha', 'One Dim Sum', 'Dim Sum Square', 'Luk Yu Tea House', 'Social Place'] },
  },
  {
    id: 'coffee-melbourne',
    publishedDate: '2026-05-25',
    title: 'Coffee Shops in Melbourne',
    category: 'Melbourne',
    type: 'stores',
    tags: ['stores', 'food'],
    linkType: 'mapsCity',
    blurb: 'The city that turned the flat white into a competitive sport.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ['Patricia Coffee Brewers', 'Market Lane Coffee', 'Industry Beans', 'Brother Baba Budan', 'Seven Seeds', 'ST. ALi', 'Proud Mary', 'Auction Rooms', 'Padre Coffee', 'Code Black Coffee'] },
      broadsheet: { label: 'Broadsheet Melbourne', items: ['Patricia Coffee Brewers', 'Market Lane Coffee', 'Proud Mary', 'ST. ALi', 'Industry Beans', 'Padre Coffee', 'Brother Baba Budan', 'Common Galaxia', 'Seven Seeds', 'Auction Rooms'] },
    },
    vote: { items: ['Patricia Coffee Brewers', 'Market Lane Coffee', 'Proud Mary', 'Brother Baba Budan', 'ST. ALi', 'Industry Beans', 'Padre Coffee', 'Auction Rooms', 'Seven Seeds', 'Common Galaxia'] },
  },
  {
    id: 'hotdog-chicago',
    publishedDate: '2026-05-25',
    title: 'Hot Dog Stands in Chicago',
    category: 'Chicago',
    type: 'stores',
    tags: ['stores', 'food'],
    linkType: 'mapsCity',
    blurb: 'Poppy seed buns, sport peppers, no ketchup. Defend your stand.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'AI Optimized', items: ["Portillo's", 'Superdawg Drive-In', "Gene & Jude's", 'The Wieners Circle', "Byron's Hot Dogs", "Jim's Original", 'Devil Dawgs', 'U Lucky Dawg', 'Chubby Wieners', 'Redhot Ranch'] },
      eater: { label: 'Eater Chicago', items: ["Gene & Jude's", "Portillo's", 'Superdawg Drive-In', 'The Wieners Circle', "Byron's Hot Dogs", 'Redhot Ranch', 'Devil Dawgs', "Jim's Original", 'U Lucky Dawg', 'Hot G Dog'] },
    },
    vote: { items: ["Portillo's", 'Superdawg Drive-In', "Gene & Jude's", 'The Wieners Circle', "Byron's Hot Dogs", 'Devil Dawgs', "Jim's Original", 'Redhot Ranch', 'U Lucky Dawg', 'Chubby Wieners'] },
  },

  /* ----- PRODUCT ----- */
  {
    id: 'headphones-overear',
    publishedDate: '2026-05-26',
    title: 'Over-Ear Headphones',
    category: 'Audio',
    type: 'product',
    linkType: 'amazon',
    blurb: 'Noise-cancellers, audiophile cans, and the budget pairs that punch above their price.',
    defaultSource: 'ai',
    links: {
      'Sony WH-1000XM6': 'https://amzn.to/4e3OsIg',
      'Bose QuietComfort Ultra Headphones': 'https://amzn.to/3RtlzMR',
      'Apple AirPods Max': 'https://amzn.to/4fFFeD9',
      'Bowers & Wilkins Px7 S3': 'https://amzn.to/3Q1zpWj',
      'Sennheiser HDB 630': 'https://amzn.to/4f7tb1k',
      'Sonos Ace': 'https://amzn.to/43uZGzm',
      'Focal Bathys': 'https://amzn.to/42QncXv',
      'Bose QuietComfort Headphones': 'https://amzn.to/4v1fzcK',
      'JBL Tour One M3': 'https://amzn.to/4uzFIzA',
    },
    sources: {
      ai: { label: 'AI Optimized', items: ['Sony WH-1000XM6', 'Bose QuietComfort Ultra Headphones', 'Sennheiser MOMENTUM 4 Wireless', 'Apple AirPods Max', 'Bowers & Wilkins Px7 S3', 'Sennheiser HDB 630', 'Sonos Ace', 'Focal Bathys', 'Bose QuietComfort Headphones', 'JBL Tour One M3'] },
      whathifi: { label: 'What Hi-Fi? 2026', items: ['Sony WH-1000XM6', 'Bowers & Wilkins Px7 S3', 'Sennheiser HDB 630', 'Bose QuietComfort Ultra Headphones', 'Apple AirPods Max', 'Focal Bathys Mg', 'Beyerdynamic DT 990 Pro X', 'Sennheiser HD 505', 'Bose QuietComfort Headphones', 'Sennheiser MOMENTUM 4 Wireless'] },
      cnn: { label: 'CNN Underscored', items: ['Sony WH-1000XM6', 'Bose QuietComfort Ultra Headphones', 'EarFun Tune Pro', 'Sennheiser MOMENTUM 4 Wireless', 'Sonos Ace', 'Apple AirPods Max', 'Bose QuietComfort Headphones', 'Anker Soundcore Space Q45', 'JBL Tour One M3', 'Bowers & Wilkins Px7 S3'] },
      rtings: { label: 'RTINGS.com', items: ['Sony WH-1000XM6', 'Bose QuietComfort Ultra Headphones', 'Audeze Maxwell', 'Sennheiser HDB 630', 'Sennheiser MOMENTUM 4 Wireless', 'Anker Soundcore Space Q45', 'Sony WH-1000XM5', 'Sony WH-1000XM4', 'Razer BlackShark V3 Pro', 'Anker Soundcore Life Q20'] },
      soundguys: { label: 'SoundGuys', items: ['Sony WH-1000XM6', 'Sennheiser MOMENTUM 4 Wireless', 'Bose QuietComfort Ultra Headphones', 'JBL Tour One M3', 'Focal Bathys', 'Apple AirPods Max', 'Bowers & Wilkins Px7 S3', 'JLab JBuds Lux ANC', 'Sennheiser HDB 630', 'Anker Soundcore Space Q45'] },
    },
    vote: { items: ['Sony WH-1000XM6', 'Sennheiser MOMENTUM 4 Wireless', 'Bose QuietComfort Ultra Headphones', 'Audeze Maxwell', 'Focal Bathys', 'Bowers & Wilkins Px7 S3', 'Apple AirPods Max', 'Sonos Ace', 'Anker Soundcore Space Q45', 'Beyerdynamic DT 990 Pro X'] },
  },
  {
    id: 'home-espresso-machines',
    publishedDate: '2026-05-26',
    title: 'Home Espresso Machines',
    category: 'Coffee',
    type: 'product',
    linkType: 'amazon',
    blurb: 'From compact countertop thermojets to dual-boiler prosumer rigs. The machines that bring cafe-quality espresso to your kitchen.',
    defaultSource: 'ai',
    // Per-item link overrides for affiliate short links. Items not listed
    // here fall back to an Amazon search with the cgurus-20 tag attached.
    links: {
      'Breville Bambino': 'https://amzn.to/43wqvTO',
      'Breville Bambino Plus': 'https://amzn.to/4tSTRqt',
      "De'Longhi Stilosa": 'https://amzn.to/4uwc2mF',
      'Gaggia Classic Pro': 'https://amzn.to/4nVlkqa',
      'Casabrews 3700 Essential': 'https://amzn.to/4o9moXD',
      'Breville Barista Express': 'https://amzn.to/4dxXOvQ',
      "De'Longhi La Specialista Arte Evo": 'https://amzn.to/4f9fmzy',
      "De'Longhi La Specialista Touch": 'https://amzn.to/4veykJS',
      "De'Longhi La Specialista Opera": 'https://amzn.to/4dFTzOV',
      'Ninja Luxe Café Pro': 'https://amzn.to/4nSBPmT',
      'Rancilio Silvia M': 'https://amzn.to/49ox2U3',
      'Rancilio Silvia Pro X': 'https://amzn.to/3RxwVzp',
      'Breville Oracle Dual Boiler': 'https://amzn.to/4fIkivi',
    },
    sources: {
      ai: {
        label: 'AI Optimized',
        items: ['Lelit Bianca V3', 'Rancilio Silvia Pro X', 'Breville Oracle Dual Boiler', 'Rancilio Silvia M', 'Lelit Victoria', 'Breville Bambino Plus', "De'Longhi La Specialista Opera", 'Breville Barista Express', "De'Longhi La Specialista Touch", 'Gaggia Classic Pro'],
      },
      tomsguide: {
        label: "Tom's Guide 2026",
        items: ["De'Longhi La Specialista Touch", 'Breville Bambino', "De'Longhi Stilosa", 'Ninja Luxe Café Pro', 'Breville Bambino Plus', "De'Longhi La Specialista Opera", 'Breville Oracle Dual Boiler', "De'Longhi La Specialista Arte Evo", 'Breville Barista Express', 'Gaggia Classic Pro'],
      },
      cr: {
        label: 'Wirecutter · Consumer Reports',
        items: ['Breville Bambino Plus', 'Lelit Victoria', 'Rancilio Silvia Pro X', 'Breville Bambino', 'Breville Barista Express', "De'Longhi La Specialista Arte Evo", 'Rancilio Silvia M', 'Gaggia Classic Pro', "De'Longhi La Specialista Touch", 'Breville Oracle Dual Boiler'],
      },
      homegrounds: {
        label: 'HomeGrounds Enthusiast',
        items: ['Rancilio Silvia M', 'Lelit Bianca V3', 'Rancilio Silvia Pro X', 'Profitec Go', 'Lelit Victoria', 'Lelit Anna PID', 'Gaggia Classic Pro', 'Breville Barista Express', 'Breville Bambino Plus', 'Breville Oracle Dual Boiler'],
      },
    },
    vote: {
      items: ['Breville Bambino Plus', 'Breville Bambino', 'Breville Barista Express', "De'Longhi La Specialista Touch", 'Casabrews 3700 Essential', "De'Longhi La Specialista Arte Evo", 'Gaggia Classic Pro', "De'Longhi Stilosa", 'Rancilio Silvia M', "De'Longhi La Specialista Opera"],
    },
  },

  /* ----- FOOD & DRINK (vote-only) ----- */
  {
    id: 'alani-nu-flavors',
    publishedDate: '2026-05-25',
    title: 'Alani Nu Energy Flavors',
    category: 'Drinks',
    type: 'food',
    linkType: 'amazon',
    mode: 'votes',
    blurb: 'Every Alani Nu energy flavor, ranked by you. Loose expert order to start, your votes take it from there.',
    defaultSource: 'ai',
    vote: { items: ["Witch's Brew", 'Breezeberry', 'Cosmic Stardust', 'Hawaiian Shaved Ice', 'Juicy Peach', 'Mimosa', 'Tropsicle', 'Watermelon Wave', 'Cherry Slush', 'Munchies'] },
  },
  {
    id: 'prestigious-boarding-schools',
    publishedDate: '2026-05-26',
    title: 'Most Prestigious Boarding Schools in the US',
    category: 'Education',
    type: 'other',
    linkType: 'wiki',
    blurb: 'The schools that feed the Ivy League, shape future presidents, and charge $70K a year for the privilege. Harkness tables, Gothic quads, and admissions rates that rival Harvard.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: ['Phillips Exeter Academy', 'Phillips Academy Andover', 'The Hotchkiss School', 'Groton School', "St. Paul's School", 'Choate Rosemary Hall', 'The Lawrenceville School', 'Deerfield Academy', 'Milton Academy', 'Cate School'],
      },
      niche: {
        label: 'Niche 2026 Best Boarding Schools',
        items: ['The Hotchkiss School', 'Phillips Exeter Academy', 'Choate Rosemary Hall', 'The Lawrenceville School', 'Groton School', 'Phillips Academy Andover', "St. Paul's School", 'Cate School', 'Deerfield Academy', 'Milton Academy'],
      },
      admissionsight: {
        label: 'AdmissionSight Top 10',
        items: ['Phillips Exeter Academy', 'Phillips Academy Andover', 'Choate Rosemary Hall', 'The Lawrenceville School', 'Groton School', "St. Paul's School", 'Deerfield Academy', 'Cate School', 'The Hotchkiss School', 'Milton Academy'],
      },
      findingschool: {
        label: 'FindingSchool 2026',
        items: ['Phillips Academy Andover', 'Phillips Exeter Academy', 'The Lawrenceville School', 'Deerfield Academy', 'Choate Rosemary Hall', 'The Hotchkiss School', "St. Paul's School", 'Groton School', 'Middlesex School', 'The Taft School'],
      },
    },
    vote: {
      items: ['Phillips Exeter Academy', 'Phillips Academy Andover', 'Groton School', 'The Hotchkiss School', "St. Paul's School", 'Choate Rosemary Hall', 'Deerfield Academy', 'The Lawrenceville School', 'Milton Academy', 'Cate School'],
    },
  },
  {
    id: 'three-martini-lunch-manhattan',
    publishedDate: '2026-05-26',
    title: 'Three-Martini Weekday Lunch in Manhattan',
    category: 'New York',
    type: 'stores',
    tags: ['stores', 'food', 'bars'],
    linkType: 'mapsCity',
    blurb: 'The power lunch never died, it just moved tables. Where to order a gin martini at noon on a Tuesday and nobody blinks. Steak, tablecloths, and a cab home.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: ['The Grill', 'Torrisi Bar & Restaurant', "Dowling's at The Carlyle", 'La Marchande', 'Carbone', 'Balthazar', 'The Polo Bar', 'Ci Siamo', 'Smith & Wollensky', 'King'],
      },
      resy: {
        label: 'Resy Power Lunch Guide 2025',
        items: ["Dowling's at The Carlyle", 'Time and Tide', 'Le Coucou', 'King', "L'Artusi", 'Ci Siamo', 'La Marchande', 'Avra Estiatorio', 'Le Crocodile', 'Manuela'],
      },
      infatuation: {
        label: 'The Infatuation',
        items: ['Torrisi Bar & Restaurant', 'Ci Siamo', 'Carbone', 'The Grill', 'Balthazar', "Raoul's", 'King', "Dowling's at The Carlyle", "L'Artusi", 'Smith & Wollensky'],
      },
      robbreport: {
        label: "Robb Report · Gentleman's Journal",
        items: ['The Grill', "Coco's", "Raf's", 'Torrisi Bar & Restaurant', 'Carbone', "Michael's", 'La Marchande', 'The Polo Bar', 'Balthazar', "Dowling's at The Carlyle"],
      },
    },
    vote: {
      items: ['Torrisi Bar & Restaurant', 'The Grill', 'Carbone', 'Balthazar', "Dowling's at The Carlyle", 'Smith & Wollensky', 'La Marchande', 'The Polo Bar', 'Ci Siamo', 'King'],
    },
  },
];

export { LISTS, TYPES, COLORS, AMAZON_AFFILIATE_TAG, BOOKING_AFFILIATE_AID, TRIPADVISOR_PARTNER };
