// Auto-generated data file for Consensus Gurus

/* =========================================================================
   AFFILIATE CONFIGURATION
   Replace these with your own affiliate identifiers.
   ========================================================================= */
const AMAZON_AFFILIATE_TAG = 'cgurus-20'; // Amazon Associates tracking tag
const BOOKING_AFFILIATE_AID = ''; // Booking.com Partner aid (optional)
const TRIPADVISOR_PARTNER = ''; // Tripadvisor partner code (optional)

/* =========================================================================
   TYPES (for filtering)
   ========================================================================= */
const TYPES = [
  { id: 'all', label: 'All' },
  { id: 'food', label: 'Food & Drink' },
  { id: 'stores', label: 'Places & Stores' },
  { id: 'travel', label: 'Travel' },
  { id: 'entertainment', label: 'Entertainment' },
  { id: 'tech', label: 'Tech' },
  { id: 'product', label: 'Products' },
  { id: 'other', label: 'Other' },
];

const COLORS = {
  cream: '#f4ede0',
  paper: '#ebe2d0',
  ink: '#1a1611',
  ember: '#c0392b',
  rust: '#a44a26',
  forest: '#3d4f2b',
  faded: '#7a6f5e',
};

/* =========================================================================
   LISTS
   Each list has:
     - type: top-level filter category
     - linkType: how to build per-item affiliate / search links
     - sources: { sourceId: { label, items[] } }  (ai is always first)
     - defaultSource: which source loads first
     - vote: starting vote ordering
   ========================================================================= */

const LISTS = [
  /* ----- TRAVEL (new lists) ----- */
  {
    id: 'miami-beach-hotels',
    title: 'Miami Beach Hotels',
    category: 'Miami Beach',
    type: 'travel',
    linkType: 'mapsCity',
    blurb: 'Ocean Drive icons, Art Deco glamour, and the resorts that anchor South Beach.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: [
          'Faena Hotel Miami Beach',
          'The Setai, Miami Beach',
          'Four Seasons Hotel at The Surf Club',
          '1 Hotel South Beach',
          'The Miami Beach EDITION',
          'Nobu Hotel Miami Beach',
          'W South Beach',
          'St. Regis Bal Harbour Resort',
          'The Ritz-Carlton, South Beach',
          'Loews Miami Beach Hotel',
        ],
      },
      tlleisure: {
        label: 'Travel + Leisure Readers',
        items: [
          'Four Seasons Hotel at The Surf Club',
          'St. Regis Bal Harbour Resort',
          'The Setai, Miami Beach',
          'Faena Hotel Miami Beach',
          'The Ritz-Carlton, Key Biscayne',
          '1 Hotel South Beach',
          'The Miami Beach EDITION',
          'Nobu Hotel Miami Beach',
          'W South Beach',
          'Eden Roc Miami Beach',
        ],
      },
      forbes: {
        label: 'Forbes Travel Guide 5-Star',
        items: [
          'Acqualina Resort & Spa',
          'Faena Hotel Miami Beach',
          'Four Seasons Hotel at The Surf Club',
          'The Ritz-Carlton, South Beach',
          'The Setai, Miami Beach',
          'St. Regis Bal Harbour Resort',
          'Nobu Hotel Miami Beach',
          'The Miami Beach EDITION',
          '1 Hotel South Beach',
          'W South Beach',
        ],
      },
      tripadvisor: {
        label: 'Tripadvisor Travelers Choice',
        items: [
          'The Setai, Miami Beach',
          'Faena Hotel Miami Beach',
          'Four Seasons Hotel at The Surf Club',
          '1 Hotel South Beach',
          'Acqualina Resort & Spa',
          'The Gabriel South Beach',
          'Nobu Hotel Miami Beach',
          'The Miami Beach EDITION',
          'Loews Miami Beach Hotel',
          'Eden Roc Miami Beach',
        ],
      },
    },
    vote: {
      items: [
        'Faena Hotel Miami Beach',
        'The Setai, Miami Beach',
        'Four Seasons Hotel at The Surf Club',
        '1 Hotel South Beach',
        'Nobu Hotel Miami Beach',
        'The Miami Beach EDITION',
        'St. Regis Bal Harbour Resort',
        'Acqualina Resort & Spa',
        'W South Beach',
        'The Ritz-Carlton, South Beach',
      ],
    },
  },
  {
    id: 'lobster-rolls',
    title: 'Lobster Rolls in America',
    category: 'New England',
    type: 'food',
    linkType: 'mapsCity',
    blurb: 'Maine-style cold with mayo or Connecticut-style warm with butter. Defend your shack.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: [
          "Red's Eats",
          'The Clam Shack',
          'Neptune Oyster',
          "Luke's Lobster",
          'McLoons Lobster Shack',
          'Five Islands Lobster Co',
          'Bite Into Maine',
          'Eventide Oyster Co',
          "Abbott's Lobster in the Rough",
          'Lobster Hut Plymouth',
        ],
      },
      yankee: {
        label: 'Yankee Magazine',
        items: [
          "Red's Eats",
          'The Clam Shack',
          'McLoons Lobster Shack',
          'Five Islands Lobster Co',
          "Abbott's Lobster in the Rough",
          'Chatham Pier Fish Market',
          "Markey's Lobster Pool",
          'Bite Into Maine',
          'Lobster Hut Plymouth',
          'Sea Swirl',
        ],
      },
      lobsteranywhere: {
        label: 'LobsterAnywhere USA Guide',
        items: [
          'Neptune Oyster',
          "Red's Eats",
          "Luke's Lobster",
          'Eventide Oyster Co',
          'The Clam Shack',
          'Bite Into Maine',
          "Pauli's Boston",
          "Ed's Lobster Bar",
          'Saltie Girl',
          'James Hook & Co',
        ],
      },
    },
    vote: {
      items: [
        "Red's Eats",
        'Neptune Oyster',
        'The Clam Shack',
        "Luke's Lobster",
        'Eventide Oyster Co',
        'McLoons Lobster Shack',
        'Bite Into Maine',
        'Five Islands Lobster Co',
        "Abbott's Lobster in the Rough",
        'Lobster Hut Plymouth',
      ],
    },
  },
  {
    id: 'pacific-ocean-resorts',
    title: 'Pacific Ocean Island Resorts',
    category: 'South Pacific',
    type: 'travel',
    linkType: 'mapsCity',
    blurb: 'Overwater bungalows and private atolls, from Bora Bora to Fiji to the Maldives.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: [
          'Four Seasons Resort Bora Bora',
          'The St. Regis Bora Bora Resort',
          'InterContinental Thalasso Spa Bora Bora',
          "Le Taha'a by Pearl Resorts",
          'Six Senses Fiji',
          'Laucala Island Resort, Fiji',
          'Como Laucala Island',
          'The Brando, Tetiaroa',
          'Soneva Fushi, Maldives',
          'North Island, Seychelles',
        ],
      },
      tlleisure: {
        label: 'Travel + Leisure Best Islands',
        items: [
          'The Brando, Tetiaroa',
          'Four Seasons Resort Bora Bora',
          'Laucala Island Resort, Fiji',
          'Soneva Fushi, Maldives',
          'North Island, Seychelles',
          'Como Laucala Island',
          'Six Senses Laamu, Maldives',
          'The St. Regis Bora Bora Resort',
          'Vomo Island Resort, Fiji',
          "Le Taha'a by Pearl Resorts",
        ],
      },
      luxurytravelexpert: {
        label: 'Luxury Travel Expert',
        items: [
          'Kudadoo Maldives',
          'Soneva Jani, Maldives',
          'Cheval Blanc Randheli, Maldives',
          'Soneva Fushi, Maldives',
          'Six Senses Laamu, Maldives',
          'The Brando, Tetiaroa',
          'Laucala Island Resort, Fiji',
          'Four Seasons Resort Bora Bora',
          'North Island, Seychelles',
          'Anantara Kihavah Maldives Villas',
        ],
      },
      tripadvisor: {
        label: 'Tripadvisor Travelers Choice',
        items: [
          'Four Seasons Resort Bora Bora',
          'The St. Regis Bora Bora Resort',
          'Conrad Bora Bora Nui',
          'Le Bora Bora by Pearl Resorts',
          'InterContinental Thalasso Spa Bora Bora',
          'Soneva Fushi, Maldives',
          'Como Laucala Island',
          'Vomo Island Resort, Fiji',
          'Likuliku Lagoon Resort, Fiji',
          'Tokoriki Island Resort, Fiji',
        ],
      },
    },
    vote: {
      items: [
        'The Brando, Tetiaroa',
        'Four Seasons Resort Bora Bora',
        'Laucala Island Resort, Fiji',
        'Soneva Fushi, Maldives',
        'The St. Regis Bora Bora Resort',
        'Como Laucala Island',
        'Kudadoo Maldives',
        'North Island, Seychelles',
        'InterContinental Thalasso Spa Bora Bora',
        'Six Senses Laamu, Maldives',
      ],
    },
  },
  {
    id: 'cabo-hotels',
    title: 'Cabo San Lucas Hotels',
    category: 'Cabo San Lucas',
    type: 'travel',
    linkType: 'mapsCity',
    blurb: 'Where the Sea of Cortez meets the Pacific. Cliffside suites, infinity pools, and El Arco views.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: [
          'Waldorf Astoria Los Cabos Pedregal',
          'Esperanza, Auberge Collection',
          'One&Only Palmilla',
          'Las Ventanas al Paraiso, A Rosewood Resort',
          'Grand Velas Los Cabos',
          'Nobu Hotel Los Cabos',
          'Montage Los Cabos',
          'Four Seasons Resort Los Cabos at Costa Palmas',
          'Chileno Bay Resort, Auberge Collection',
          'Hotel El Ganzo',
        ],
      },
      tripadvisor: {
        label: 'Tripadvisor Travelers Choice',
        items: [
          'Grand Solmar Pacific Dunes',
          'Esperanza, Auberge Collection',
          'Waldorf Astoria Los Cabos Pedregal',
          'Garza Blanca Resort & Spa Los Cabos',
          'Pueblo Bonito Sunset Beach',
          'One&Only Palmilla',
          'Chileno Bay Resort, Auberge Collection',
          'Las Ventanas al Paraiso, A Rosewood Resort',
          'Nobu Hotel Los Cabos',
          'Hyatt Ziva Los Cabos',
        ],
      },
      trip: {
        label: 'Trip.com Popular',
        items: [
          'Waldorf Astoria Los Cabos Pedregal',
          '1 Homes Preview Cabo',
          'Esperanza, Auberge Collection',
          'One&Only Palmilla',
          'Grand Velas Los Cabos',
          'Montage Los Cabos',
          'Nobu Hotel Los Cabos',
          'Chileno Bay Resort, Auberge Collection',
          'Las Ventanas al Paraiso, A Rosewood Resort',
          'Four Seasons Resort Los Cabos at Costa Palmas',
        ],
      },
    },
    vote: {
      items: [
        'Waldorf Astoria Los Cabos Pedregal',
        'Esperanza, Auberge Collection',
        'One&Only Palmilla',
        'Las Ventanas al Paraiso, A Rosewood Resort',
        'Montage Los Cabos',
        'Four Seasons Resort Los Cabos at Costa Palmas',
        'Grand Velas Los Cabos',
        'Nobu Hotel Los Cabos',
        'Chileno Bay Resort, Auberge Collection',
        'Grand Solmar Pacific Dunes',
      ],
    },
  },

  /* ----- ENTERTAINMENT ----- */
  {
    id: 'movies',
    title: 'Movies of All Time',
    category: 'Cinema',
    type: 'entertainment',
    linkType: 'imdb',
    blurb: 'The films that defined the medium and the ones the public refuses to forget.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: [
          'The Godfather',
          'Citizen Kane',
          'Casablanca',
          'The Shawshank Redemption',
          "Schindler's List",
          'Pulp Fiction',
          '2001: A Space Odyssey',
          'Vertigo',
          'Seven Samurai',
          'Lawrence of Arabia',
          'The Godfather Part II',
          'Goodfellas',
        ],
      },
      imdb: {
        label: 'IMDB Top Rated',
        items: [
          'The Shawshank Redemption',
          'The Godfather',
          'The Dark Knight',
          'The Godfather Part II',
          '12 Angry Men',
          "Schindler's List",
          'The Lord of the Rings: The Return of the King',
          'Pulp Fiction',
          'The Lord of the Rings: The Fellowship of the Ring',
          'The Good, the Bad and the Ugly',
          'Forrest Gump',
          'Fight Club',
        ],
      },
      rotten: {
        label: 'Rotten Tomatoes 100 Best',
        items: [
          'Citizen Kane',
          'Casablanca',
          'The Wizard of Oz',
          'Modern Times',
          'Black Panther',
          'Parasite',
          'Avengers: Endgame',
          'It Happened One Night',
          'Get Out',
          'The Cabinet of Dr. Caligari',
          "Singin' in the Rain",
          'All About Eve',
        ],
      },
    },
    vote: {
      items: [
        'The Dark Knight',
        'Inception',
        'Forrest Gump',
        'Goodfellas',
        'The Matrix',
        'Spirited Away',
        'Parasite',
        'Fight Club',
        'Back to the Future',
        'Interstellar',
      ],
    },
  },
  {
    id: 'tv',
    title: 'TV Shows',
    category: 'Television',
    type: 'entertainment',
    linkType: 'imdb',
    blurb: 'The most watched television of the modern era versus the most beloved.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: [
          'Breaking Bad',
          'The Sopranos',
          'The Wire',
          'Mad Men',
          'Game of Thrones',
          'The Simpsons',
          'Seinfeld',
          'Better Call Saul',
          'Friends',
          'The Office',
        ],
      },
      imdb: {
        label: 'IMDB Top Rated',
        items: [
          'Breaking Bad',
          'Band of Brothers',
          'Chernobyl',
          'The Wire',
          'Avatar: The Last Airbender',
          'The Sopranos',
          'Better Call Saul',
          'Game of Thrones',
          'Cosmos',
          'Rick and Morty',
        ],
      },
    },
    vote: {
      items: [
        'Breaking Bad',
        'The Wire',
        'Better Call Saul',
        'The Sopranos',
        'Succession',
        'Mad Men',
        'Chernobyl',
        'Fleabag',
        'Severance',
        'The Leftovers',
      ],
    },
  },
  {
    id: 'books',
    title: 'Books Ever Written',
    category: 'Literature',
    type: 'entertainment',
    linkType: 'amazon',
    blurb: 'The texts that sold a billion copies versus the ones that changed minds.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: [
          'Don Quixote',
          'A Tale of Two Cities',
          'The Lord of the Rings',
          'The Little Prince',
          "Harry Potter and the Philosopher's Stone",
          'And Then There Were None',
          'Dream of the Red Chamber',
          'The Hobbit',
          "Alice's Adventures in Wonderland",
          'The Da Vinci Code',
        ],
      },
      goodreads: {
        label: 'Goodreads Most Loved',
        items: [
          'To Kill a Mockingbird',
          'Pride and Prejudice',
          'The Great Gatsby',
          'The Book Thief',
          'The Kite Runner',
          'A Little Life',
          'The Night Circus',
          'Where the Crawdads Sing',
          'The Song of Achilles',
          'Project Hail Mary',
        ],
      },
    },
    vote: {
      items: [
        '1984',
        'To Kill a Mockingbird',
        'Crime and Punishment',
        'One Hundred Years of Solitude',
        'The Brothers Karamazov',
        'Beloved',
        'Brave New World',
        'East of Eden',
        'The Master and Margarita',
        'Catch-22',
      ],
    },
  },
  {
    id: 'games',
    title: 'Video Games',
    category: 'Gaming',
    type: 'entertainment',
    linkType: 'steam',
    blurb: 'The titles that sold a planet versus the ones people will defend forever.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: [
          'Minecraft',
          'Grand Theft Auto V',
          'Tetris',
          'Wii Sports',
          'PUBG: Battlegrounds',
          'Mario Kart 8 Deluxe',
          'Red Dead Redemption 2',
          'Terraria',
          'Super Mario Bros.',
          'The Witcher 3: Wild Hunt',
        ],
      },
      metacritic: {
        label: 'Metacritic All Time',
        items: [
          'The Legend of Zelda: Ocarina of Time',
          "Tony Hawk's Pro Skater 2",
          'Grand Theft Auto IV',
          'SoulCalibur',
          'Super Mario Galaxy',
          'Super Mario Galaxy 2',
          'Red Dead Redemption 2',
          'Grand Theft Auto V',
          'The Orange Box',
          'Metroid Prime',
        ],
      },
    },
    vote: {
      items: [
        'The Legend of Zelda: Breath of the Wild',
        'Elden Ring',
        'The Witcher 3: Wild Hunt',
        'Red Dead Redemption 2',
        'Portal 2',
        'Disco Elysium',
        'Half-Life 2',
        'Hollow Knight',
        'Dark Souls',
        'Stardew Valley',
      ],
    },
  },

  /* ----- STORES / PLACES (city-specific spots) ----- */
  {
    id: 'pizza-nyc',
    title: 'Pizza Slices in NYC',
    category: 'New York',
    type: 'stores',
    linkType: 'mapsCity',
    blurb: 'The city that built the slice. Old guard versus the new wave.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: [
          "Joe's Pizza",
          'Di Fara',
          'L&B Spumoni Gardens',
          'Lucali',
          "Patsy's Pizzeria",
          "John's of Bleecker Street",
          "Lombardi's",
          "Totonno's",
          "Roberta's",
          'Prince Street Pizza',
          "Scarr's",
          "Mama's Too",
        ],
      },
      eater: {
        label: 'Eater NY Essential 38',
        items: [
          "L'industrie",
          'Lucali',
          'Una Pizza Napoletana',
          'Di Fara',
          "Joe's Pizza",
          'Prince Street Pizza',
          "Scarr's",
          "Mama's Too",
          'Best Pizza',
          'Rubirosa',
        ],
      },
      timeout: {
        label: 'Time Out New York',
        items: [
          "Joe's Pizza",
          'Lucali',
          'Di Fara',
          'Prince Street Pizza',
          "Roberta's",
          "Paulie Gee's",
          "Lombardi's",
          "Totonno's",
          "Mama's Too",
          "L'industrie",
        ],
      },
    },
    vote: {
      items: [
        "Joe's Pizza",
        "L'industrie",
        "Scarr's",
        "Mama's Too",
        'Lucali',
        "Roberta's",
        'Prince Street Pizza',
        'Di Fara',
        'Best Pizza',
        "Joe & Pat's",
      ],
    },
  },
  {
    id: 'tacos-la',
    title: 'Tacos in Los Angeles',
    category: 'Los Angeles',
    type: 'stores',
    linkType: 'mapsCity',
    blurb: 'A taqueria capital. Awards on one side, taco truck loyalty on the other.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: [
          'Mariscos Jalisco',
          'Guisados',
          'Tacos 1986',
          'Sonoratown',
          "Leo's Taco Truck",
          'Holbox',
          'B.S. Taqueria',
          'Carnitas El Momo',
          'El Ruso',
          'Tire Shop Taqueria',
        ],
      },
      latimes: {
        label: 'LA Times 101 Best',
        items: [
          'Mariscos Jalisco',
          'Sonoratown',
          'Tacos 1986',
          'Carnitas El Momo',
          'El Ruso',
          "Villa's Tacos",
          'Holbox',
          "Leo's Taco Truck",
          'Tire Shop Taqueria',
          'Guisados',
        ],
      },
      eater: {
        label: 'Eater LA',
        items: [
          'Tacos 1986',
          'Sonoratown',
          'Mariscos Jalisco',
          "Villa's Tacos",
          'Carnitas El Momo',
          'El Ruso',
          'Guisados',
          'Holbox',
          'Loqui',
          "Leo's Taco Truck",
        ],
      },
    },
    vote: {
      items: [
        'Tacos 1986',
        'Sonoratown',
        'Mariscos Jalisco',
        "Leo's Taco Truck",
        "Villa's Tacos",
        'Guisados',
        'El Ruso',
        'Carnitas El Momo',
        'Holbox',
        'Tire Shop Taqueria',
      ],
    },
  },
  {
    id: 'ramen-tokyo',
    title: 'Ramen Shops in Tokyo',
    category: 'Tokyo',
    type: 'stores',
    linkType: 'mapsCity',
    blurb: 'Michelin-starred broth versus the bowls locals queue an hour for.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: [
          'Tsuta',
          'Nakiryu',
          'Konjiki Hototogisu',
          'Afuri',
          'Rokurinsha',
          'Mensho',
          'Menya Musashi',
          'Ginza Kagari',
          'Ippudo',
          'Ramen Jiro',
        ],
      },
      michelin: {
        label: 'Michelin Guide Tokyo',
        items: [
          'Nakiryu',
          'Tsuta',
          'Konjiki Hototogisu',
          'Ginza Kagari',
          'Soranoiro',
          'Mensho',
          'Afuri',
          'Menya Itto',
          'Ramen Tatsunoya',
          'Rokurinsha',
        ],
      },
      timeout: {
        label: 'Time Out Tokyo',
        items: [
          'Afuri',
          'Ichiran',
          'Mensho',
          'Konjiki Hototogisu',
          'Rokurinsha',
          'Tsuta',
          'Ramen Jiro',
          'Menya Musashi',
          'Ippudo',
          'Ginza Kagari',
        ],
      },
    },
    vote: {
      items: [
        'Ichiran',
        'Konjiki Hototogisu',
        'Afuri',
        'Tsuta',
        'Mensho',
        'Ginza Kagari',
        'Rokurinsha',
        'Ippudo',
        'Nakiryu',
        'Menya Musashi',
      ],
    },
  },
  {
    id: 'bagels-nyc',
    title: 'Bagel Shops in NYC',
    category: 'New York',
    type: 'stores',
    linkType: 'mapsCity',
    blurb: 'Boiled, baked, and argued about. Institutions face the new generation.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: [
          'Russ & Daughters',
          'Ess-a-Bagel',
          'Absolute Bagels',
          "Murray's Bagels",
          'H&H Bagels',
          'Tompkins Square Bagels',
          'Brooklyn Bagel & Coffee Company',
          'Black Seed',
          "Bo's Bagels",
          'Utopia Bagels',
        ],
      },
      eater: {
        label: 'Eater NY',
        items: [
          'Ess-a-Bagel',
          'Russ & Daughters',
          'Apollo Bagels',
          'PopUp Bagels',
          'Utopia Bagels',
          'Tompkins Square Bagels',
          "Bo's Bagels",
          'Best Bagel & Coffee',
          'Tal Bagels',
          'Black Seed',
        ],
      },
    },
    vote: {
      items: [
        'Ess-a-Bagel',
        'Russ & Daughters',
        'Apollo Bagels',
        'PopUp Bagels',
        'Tompkins Square Bagels',
        'Utopia Bagels',
        'Tal Bagels',
        "Bo's Bagels",
        'Best Bagel & Coffee',
        'Absolute Bagels',
      ],
    },
  },
  {
    id: 'bbq-texas',
    title: 'BBQ Joints in Texas',
    category: 'Texas',
    type: 'stores',
    linkType: 'mapsCity',
    blurb: 'Smoke rings, brisket bark, and central Texas heritage on the line.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: [
          "Snow's BBQ",
          'Franklin Barbecue',
          "Goldee's BBQ",
          'Pecan Lodge',
          'Louie Mueller Barbecue',
          "Black's Barbecue",
          'Kreuz Market',
          'Cattleack Barbeque',
          'La Barbecue',
          'Truth BBQ',
        ],
      },
      texasmonthly: {
        label: 'Texas Monthly Top 50',
        items: [
          "Goldee's BBQ",
          "Snow's BBQ",
          'Franklin Barbecue',
          'Interstellar BBQ',
          'Truth BBQ',
          'Cattleack Barbeque',
          'Pecan Lodge',
          'La Barbecue',
          'Louie Mueller Barbecue',
          "Brotherton's Black Iron Barbecue",
        ],
      },
    },
    vote: {
      items: [
        'Franklin Barbecue',
        "Goldee's BBQ",
        "Snow's BBQ",
        "Terry Black's",
        'La Barbecue',
        'Pecan Lodge',
        'Truth BBQ',
        'Hutchins BBQ',
        'Cattleack Barbeque',
        'InterStellar BBQ',
      ],
    },
  },
  {
    id: 'pasta-rome',
    title: 'Pasta in Rome',
    category: 'Rome',
    type: 'stores',
    linkType: 'mapsCity',
    blurb: 'Carbonara, cacio e pepe, amatriciana. Tradition rules, but who does it best?',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: [
          'Roscioli',
          'Armando al Pantheon',
          'Da Enzo al 29',
          'Felice a Testaccio',
          'Pierluigi',
          'Cesare al Casaletto',
          "L'Arcangelo",
          'Da Danilo',
          'Trattoria Pennestri',
          'Salumeria Roscioli',
        ],
      },
      eater: {
        label: 'Eater Rome Guides',
        items: [
          'Roscioli',
          'Da Enzo al 29',
          'Felice a Testaccio',
          'Armando al Pantheon',
          'Trattoria Pennestri',
          'Cesare al Casaletto',
          'Pianostrada',
          'Sora Lella',
          'Pierluigi',
          'Tonnarello',
        ],
      },
    },
    vote: {
      items: [
        'Roscioli',
        'Da Enzo al 29',
        'Felice a Testaccio',
        'Armando al Pantheon',
        'Tonnarello',
        'Pierluigi',
        'Sora Lella',
        'Trattoria Pennestri',
        'Pianostrada',
        'Cesare al Casaletto',
      ],
    },
  },
  {
    id: 'cocktails-london',
    title: 'Cocktail Bars in London',
    category: 'London',
    type: 'stores',
    linkType: 'mapsCity',
    blurb: 'Hotel bars in dinner jackets versus the speakeasy crowd shaking the future.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: [
          'Connaught Bar',
          'Tayer + Elementary',
          'Swift',
          'Lyaness',
          'A Bar with Shapes for a Name',
          'Side Hustle',
          "Satan's Whiskers",
          'Kwānt',
          'Three Sheets',
          'Happiness Forgets',
        ],
      },
      worlds50best: {
        label: "World's 50 Best Bars",
        items: [
          'A Bar with Shapes for a Name',
          'Tayer + Elementary',
          'Connaught Bar',
          'Swift',
          'Side Hustle',
          'Kwānt',
          'Below Stone Nest',
          'Lyaness',
          "Satan's Whiskers",
          'Three Sheets',
        ],
      },
    },
    vote: {
      items: [
        'Connaught Bar',
        'A Bar with Shapes for a Name',
        'Tayer + Elementary',
        'Swift',
        'Below Stone Nest',
        "Satan's Whiskers",
        'Happiness Forgets',
        'Lyaness',
        'Bar Termini',
        'Side Hustle',
      ],
    },
  },
  {
    id: 'steakhouse-chicago',
    title: 'Steakhouses in Chicago',
    category: 'Chicago',
    type: 'stores',
    linkType: 'mapsCity',
    blurb: 'Where the porterhouse is sacred and the martinis are big enough to swim in.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: [
          "Bavette's Bar & Boeuf",
          "Gibson's Bar & Steakhouse",
          'Gene & Georgetti',
          'Maple & Ash',
          'Swift & Sons',
          'RPM Steak',
          'Chicago Cut Steakhouse',
          "Mastro's",
          'Smith & Wollensky',
          'Boeufhaus',
        ],
      },
      tribune: {
        label: 'Chicago Tribune',
        items: [
          "Bavette's Bar & Boeuf",
          'Maple & Ash',
          "Gibson's Bar & Steakhouse",
          'Swift & Sons',
          'Boeufhaus',
          'RPM Steak',
          'Gene & Georgetti',
          'Chicago Cut Steakhouse',
          'Rosebud Steakhouse',
          'Tango Sur',
        ],
      },
    },
    vote: {
      items: [
        "Bavette's Bar & Boeuf",
        "Gibson's Bar & Steakhouse",
        'Maple & Ash',
        'Swift & Sons',
        'RPM Steak',
        'Boeufhaus',
        'Gene & Georgetti',
        'Chicago Cut Steakhouse',
        "Mastro's",
        'Smith & Wollensky',
      ],
    },
  },
  {
    id: 'bookstores-paris',
    title: 'Bookstores in Paris',
    category: 'Paris',
    type: 'stores',
    linkType: 'mapsCity',
    blurb: 'Storied institutions and the indie shops keeping reading alive.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: [
          'Shakespeare and Company',
          'Librairie Galignani',
          'La Hune',
          'Librairie Gallimard',
          "L'Écume des Pages",
          'Le Divan',
          'Gibert Joseph',
          'Assouline',
          'Librairie Petite Égypte',
          'Librairie Picard',
        ],
      },
      timeout: {
        label: 'Time Out Paris',
        items: [
          'Shakespeare and Company',
          'Librairie Galignani',
          'Ofr.',
          "L'Écume des Pages",
          '7L',
          'Yvon Lambert',
          'La Hune',
          'Le Divan',
          'Berkeley Books of Paris',
          'Librairie Petite Égypte',
        ],
      },
    },
    vote: {
      items: [
        'Shakespeare and Company',
        'Librairie Galignani',
        "L'Écume des Pages",
        'La Hune',
        'Le Divan',
        'Ofr.',
        'Yvon Lambert',
        '7L',
        'Berkeley Books of Paris',
        'Librairie Petite Égypte',
      ],
    },
  },
  {
    id: 'dimsum-hk',
    title: 'Dim Sum in Hong Kong',
    category: 'Hong Kong',
    type: 'stores',
    linkType: 'mapsCity',
    blurb: 'Trolley dining at noon, cheap baskets at dawn, three-star refinement in between.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: [
          'Lung King Heen',
          "T'ang Court",
          'Yan Toh Heen',
          'Fook Lam Moon',
          'Tim Ho Wan',
          'One Harbour Road',
          'Lin Heung Tea House',
          "Maxim's Palace",
          'Luk Yu Tea House',
          "Duddell's",
        ],
      },
      michelin: {
        label: 'Michelin Guide Hong Kong',
        items: [
          'Lung King Heen',
          "T'ang Court",
          'Yan Toh Heen',
          'Tim Ho Wan',
          "Duddell's",
          'Fook Lam Moon',
          'Above & Beyond',
          'Spring Moon',
          'Cuisine Cuisine',
          'One Harbour Road',
        ],
      },
    },
    vote: {
      items: [
        'Tim Ho Wan',
        'Lung King Heen',
        'Lin Heung Tea House',
        "Maxim's Palace",
        'Fook Lam Moon',
        'Yum Cha',
        'One Dim Sum',
        'Dim Sum Square',
        'Luk Yu Tea House',
        'Social Place',
      ],
    },
  },
  {
    id: 'coffee-melbourne',
    title: 'Coffee Shops in Melbourne',
    category: 'Melbourne',
    type: 'stores',
    linkType: 'mapsCity',
    blurb: 'The city that turned the flat white into a competitive sport.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: [
          'Patricia Coffee Brewers',
          'Market Lane Coffee',
          'Industry Beans',
          'Brother Baba Budan',
          'Seven Seeds',
          'ST. ALi',
          'Proud Mary',
          'Auction Rooms',
          'Padre Coffee',
          'Code Black Coffee',
        ],
      },
      broadsheet: {
        label: 'Broadsheet Melbourne',
        items: [
          'Patricia Coffee Brewers',
          'Market Lane Coffee',
          'Proud Mary',
          'ST. ALi',
          'Industry Beans',
          'Padre Coffee',
          'Brother Baba Budan',
          'Common Galaxia',
          'Seven Seeds',
          'Auction Rooms',
        ],
      },
    },
    vote: {
      items: [
        'Patricia Coffee Brewers',
        'Market Lane Coffee',
        'Proud Mary',
        'Brother Baba Budan',
        'ST. ALi',
        'Industry Beans',
        'Padre Coffee',
        'Auction Rooms',
        'Seven Seeds',
        'Common Galaxia',
      ],
    },
  },
  {
    id: 'hotdog-chicago',
    title: 'Hot Dog Stands in Chicago',
    category: 'Chicago',
    type: 'stores',
    linkType: 'mapsCity',
    blurb: 'Poppy seed buns, sport peppers, no ketchup. Defend your stand.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'AI Optimized',
        items: [
          "Portillo's",
          'Superdawg Drive-In',
          "Gene & Jude's",
          'The Wieners Circle',
          "Byron's Hot Dogs",
          "Jim's Original",
          'Devil Dawgs',
          'U Lucky Dawg',
          'Chubby Wieners',
          'Redhot Ranch',
        ],
      },
      eater: {
        label: 'Eater Chicago',
        items: [
          "Gene & Jude's",
          "Portillo's",
          'Superdawg Drive-In',
          'The Wieners Circle',
          "Byron's Hot Dogs",
          'Redhot Ranch',
          'Devil Dawgs',
          "Jim's Original",
          'U Lucky Dawg',
          'Hot G Dog',
        ],
      },
    },
    vote: {
      items: [
        "Portillo's",
        'Superdawg Drive-In',
        "Gene & Jude's",
        'The Wieners Circle',
        "Byron's Hot Dogs",
        'Devil Dawgs',
        "Jim's Original",
        'Redhot Ranch',
        'U Lucky Dawg',
        'Chubby Wieners',
      ],
    },
  },

  /* ----- PRODUCT ----- */
  {
    id: 'headphones-overear',
    title: 'Over-Ear Headphones',
    category: 'Audio',
    type: 'product',
    linkType: 'amazon',
    blurb: 'Noise-cancellers, audiophile cans, and the budget pairs that punch above their price.',
    defaultSource: 'ai',
    // Per-item link overrides. Keys are matched case-insensitively against
    // the item name. Replace each with the amzn.to short link you generate
    // from Amazon SiteStripe for that exact product. Any item not listed
    // here falls back to an Amazon search with your affiliate tag.
    links: {
      'Sony WH-1000XM6': 'https://amzn.to/4e3OsIg',
      'Bose QuietComfort Ultra Headphones': 'https://amzn.to/3RtlzMR',
      // 'Sennheiser MOMENTUM 4 Wireless': 'https://amzn.to/...',
      'Apple AirPods Max': 'https://amzn.to/4fFFeD9',
      'Bowers & Wilkins Px7 S3': 'https://amzn.to/3Q1zpWj',
      'Sennheiser HDB 630': 'https://amzn.to/4f7tb1k',
      'Sonos Ace': 'https://amzn.to/43uZGzm',
      'Focal Bathys': 'https://amzn.to/42QncXv',
      'Bose QuietComfort Headphones': 'https://amzn.to/4v1fzcK',
      'JBL Tour One M3': 'https://amzn.to/4uzFIzA',
    },
    sources: {
      ai: {
        label: 'AI Optimized',
        items: [
          'Sony WH-1000XM6',
          'Bose QuietComfort Ultra Headphones',
          'Sennheiser MOMENTUM 4 Wireless',
          'Apple AirPods Max',
          'Bowers & Wilkins Px7 S3',
          'Sennheiser HDB 630',
          'Sonos Ace',
          'Focal Bathys',
          'Bose QuietComfort Headphones',
          'JBL Tour One M3',
        ],
      },
      whathifi: {
        label: 'What Hi-Fi? 2026',
        items: [
          'Sony WH-1000XM6',
          'Bowers & Wilkins Px7 S3',
          'Sennheiser HDB 630',
          'Bose QuietComfort Ultra Headphones',
          'Apple AirPods Max',
          'Focal Bathys Mg',
          'Beyerdynamic DT 990 Pro X',
          'Sennheiser HD 505',
          'Bose QuietComfort Headphones',
          'Sennheiser MOMENTUM 4 Wireless',
        ],
      },
      cnn: {
        label: 'CNN Underscored',
        items: [
          'Sony WH-1000XM6',
          'Bose QuietComfort Ultra Headphones',
          'EarFun Tune Pro',
          'Sennheiser MOMENTUM 4 Wireless',
          'Sonos Ace',
          'Apple AirPods Max',
          'Bose QuietComfort Headphones',
          'Anker Soundcore Space Q45',
          'JBL Tour One M3',
          'Bowers & Wilkins Px7 S3',
        ],
      },
      rtings: {
        label: 'RTINGS.com',
        items: [
          'Sony WH-1000XM6',
          'Bose QuietComfort Ultra Headphones',
          'Audeze Maxwell',
          'Sennheiser HDB 630',
          'Sennheiser MOMENTUM 4 Wireless',
          'Anker Soundcore Space Q45',
          'Sony WH-1000XM5',
          'Sony WH-1000XM4',
          'Razer BlackShark V3 Pro',
          'Anker Soundcore Life Q20',
        ],
      },
      soundguys: {
        label: 'SoundGuys',
        items: [
          'Sony WH-1000XM6',
          'Sennheiser MOMENTUM 4 Wireless',
          'Bose QuietComfort Ultra Headphones',
          'JBL Tour One M3',
          'Focal Bathys',
          'Apple AirPods Max',
          'Bowers & Wilkins Px7 S3',
          'JLab JBuds Lux ANC',
          'Sennheiser HDB 630',
          'Anker Soundcore Space Q45',
        ],
      },
    },
    vote: {
      items: [
        'Sony WH-1000XM6',
        'Sennheiser MOMENTUM 4 Wireless',
        'Bose QuietComfort Ultra Headphones',
        'Audeze Maxwell',
        'Focal Bathys',
        'Bowers & Wilkins Px7 S3',
        'Apple AirPods Max',
        'Sonos Ace',
        'Anker Soundcore Space Q45',
        'Beyerdynamic DT 990 Pro X',
      ],
    },
  },
];

export { LISTS, TYPES, COLORS, AMAZON_AFFILIATE_TAG, BOOKING_AFFILIATE_AID, TRIPADVISOR_PARTNER };
