// Auto-generated data file for Consensus Gurus

/* =========================================================================
   AFFILIATE CONFIGURATION
   ========================================================================= */
const AMAZON_AFFILIATE_TAG = 'cgurus-20';
const BOOKING_AFFILIATE_AID = '';
const TRIPADVISOR_PARTNER = '';

/* =========================================================================
   TYPES (for filtering chips)
   A list can match multiple types via its `tags` array.
   ========================================================================= */
const TYPES = [
  { id: 'all', label: 'All' },
  { id: 'food', label: 'Food & Drink' },
  { id: 'bars', label: 'Bars' },
  { id: 'nightlife', label: 'Nightlife' },
  { id: 'stores', label: 'Places & Stores' },
  { id: 'travel', label: 'Travel' },
  { id: 'entertainment', label: 'Entertainment' },
  { id: 'tech', label: 'Tech' },
  { id: 'product', label: 'Products' },
  { id: 'other', label: 'Other' },
];

const COLORS = {
  cream: '#f4ede0',
  paper: '#ebe2d0',
  ink: '#1a1611',
  ember: '#c0392b',
  rust: '#a44a26',
  forest: '#3d4f2b',
  faded: '#7a6f5e',
};

/* =========================================================================
   LISTS
   - type: primary category (used for legacy code paths)
   - tags (optional): array of all categories this list belongs to. If absent,
     falls back to [type]. The filter chips on the home page use tags.
   - mode (optional): 'facts' (no voting), 'votes' (no source tab)
   - sources: expert source lists can have any number of items (not limited to 10)
     Consensus will always be exactly 10 items (top 10 by Borda scoring)
   ========================================================================= */

const LISTS = [
  /* ----- REAL ESTATE ----- */
  {
    id: 'top-grossing-realtors-2025',
    publishedDate: '2026-05-27',
    title: 'Top-Grossing Realtors in 2025',
    category: 'Real Estate',
    type: 'other',
    tags: ['other'],
    linkType: 'google',
    mode: 'facts',
    blurb: 'The highest-volume residential real estate agents in America in 2025, ranked by verified sales volume.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'RealTrends Verified',
        items: [
          'Ben Caballero (Dallas; $3.9B)',
          'Deborah Kern (New York City; $1.1B)',
          'Christian Angle (Palm Beach; $792.4M)',
          'Jonathan Minerick (San Diego; $764.8M)',
          'Drew Fenton (Beverly Hills; $750.0M)',
          'Steven Koleno (Chicago; $703.7M)',
          'Thomas Ullrich (Englewood; $665.1M)',
          'David Roberts (Boca Raton; $623.9M)',
          'Chris Cortazzo (Malibu; $596.9M)',
          'Tracy Campion (Boston; $528.2M)',
        ],
      },
    },
    vote: {
      items: [
        'Ben Caballero (Dallas; $3.9B)',
        'Deborah Kern (New York City; $1.1B)',
        'Christian Angle (Palm Beach; $792.4M)',
        'Jonathan Minerick (San Diego; $764.8M)',
        'Drew Fenton (Beverly Hills; $750.0M)',
        'Steven Koleno (Chicago; $703.7M)',
        'Thomas Ullrich (Englewood; $665.1M)',
        'David Roberts (Boca Raton; $623.9M)',
        'Chris Cortazzo (Malibu; $596.9M)',
        'Tracy Campion (Boston; $528.2M)',
      ],
    },
    links: {
      'Ben Caballero (Dallas; $3.9B)': 'https://www.google.com/search?q=Ben+Caballero+Dallas+realtor',
      'Deborah Kern (New York City; $1.1B)': 'https://www.google.com/search?q=Deborah+Kern+New+York+City+realtor',
      'Christian Angle (Palm Beach; $792.4M)': 'https://www.google.com/search?q=Christian+Angle+Palm+Beach+realtor',
      'Jonathan Minerick (San Diego; $764.8M)': 'https://www.google.com/search?q=Jonathan+Minerick+San+Diego+realtor',
      'Drew Fenton (Beverly Hills; $750.0M)': 'https://www.google.com/search?q=Drew+Fenton+Beverly+Hills+realtor',
      'Steven Koleno (Chicago; $703.7M)': 'https://www.google.com/search?q=Steven+Koleno+Chicago+realtor',
      'Thomas Ullrich (Englewood; $665.1M)': 'https://www.google.com/search?q=Thomas+Ullrich+Englewood+realtor',
      'David Roberts (Boca Raton; $623.9M)': 'https://www.google.com/search?q=David+Roberts+Boca+Raton+realtor',
      'Chris Cortazzo (Malibu; $596.9M)': 'https://www.google.com/search?q=Chris+Cortazzo+Malibu+realtor',
      'Tracy Campion (Boston; $528.2M)': 'https://www.google.com/search?q=Tracy+Campion+Boston+realtor',
    },
  },

  /* ----- TRAVEL ----- */
  {
    id: 'miami-beach-hotels',
    publishedDate: '2026-05-24',
    title: 'Best Miami Beach Hotels',
    category: 'Miami Beach',
    type: 'travel',
    tags: ['travel', 'luxury', 'stores'],
    linkType: 'mapsCity',
    blurb: 'Ocean Drive icons, Art Deco glamour, and the resorts that anchor South Beach.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'Consensus AI', items: ['Faena Hotel Miami Beach', 'The Setai, Miami Beach', 'Four Seasons Hotel at The Surf Club', '1 Hotel South Beach', 'The Miami Beach EDITION', 'Nobu Hotel Miami Beach', 'W South Beach', 'St. Regis Bal Harbour Resort', 'The Ritz-Carlton, South Beach', 'Loews Miami Beach Hotel'] },
      tlleisure: { label: 'Travel + Leisure Readers', items: ['Four Seasons Hotel at The Surf Club', 'St. Regis Bal Harbour Resort', 'The Setai, Miami Beach', 'Faena Hotel Miami Beach', 'The Ritz-Carlton, Key Biscayne', '1 Hotel South Beach', 'The Miami Beach EDITION', 'Nobu Hotel Miami Beach', 'W South Beach', 'Eden Roc Miami Beach'] },
      forbes: { label: 'Forbes Travel Guide 5-Star', items: ['Acqualina Resort & Spa', 'Faena Hotel Miami Beach', 'Four Seasons Hotel at The Surf Club', 'The Ritz-Carlton, South Beach', 'The Setai, Miami Beach', 'St. Regis Bal Harbour Resort', 'Nobu Hotel Miami Beach', 'The Miami Beach EDITION', '1 Hotel South Beach', 'W South Beach'] },
      tripadvisor: { label: 'Tripadvisor Travelers Choice', items: ['The Setai, Miami Beach', 'Faena Hotel Miami Beach', 'Four Seasons Hotel at The Surf Club', '1 Hotel South Beach', 'Acqualina Resort & Spa', 'The Gabriel South Beach', 'Nobu Hotel Miami Beach', 'The Miami Beach EDITION', 'Loews Miami Beach Hotel', 'Eden Roc Miami Beach'] },
    },
    vote: { items: ['Faena Hotel Miami Beach', 'The Setai, Miami Beach', 'Four Seasons Hotel at The Surf Club', '1 Hotel South Beach', 'Nobu Hotel Miami Beach', 'The Miami Beach EDITION', 'St. Regis Bal Harbour Resort', 'Acqualina Resort & Spa', 'W South Beach', 'The Ritz-Carlton, South Beach'] },
  },
  {
    id: 'lobster-rolls',
    publishedDate: '2026-05-24',
    title: 'Best Lobster Rolls in America',
    category: 'New England',
    type: 'food',
    tags: ['food', 'food-drink', 'stores'],
    linkType: 'mapsCity',
    blurb: 'Maine-style cold with mayo or Connecticut-style warm with butter. Defend your shack.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'Consensus AI', items: ["Red's Eats", 'The Clam Shack', 'Neptune Oyster', "Luke's Lobster", 'McLoons Lobster Shack', 'Five Islands Lobster Co', 'Bite Into Maine', 'Eventide Oyster Co', "Abbott's Lobster in the Rough", 'Lobster Hut Plymouth'] },
      yankee: { label: 'Yankee Magazine', items: ["Red's Eats", 'The Clam Shack', 'McLoons Lobster Shack', 'Five Islands Lobster Co', "Abbott's Lobster in the Rough", 'Chatham Pier Fish Market', "Markey's Lobster Pool", 'Bite Into Maine', 'Lobster Hut Plymouth', 'Sea Swirl'] },
      lobsteranywhere: { label: 'LobsterAnywhere USA Guide', items: ['Neptune Oyster', "Red's Eats", "Luke's Lobster", 'Eventide Oyster Co', 'The Clam Shack', 'Bite Into Maine', "Pauli's Boston", "Ed's Lobster Bar", 'Saltie Girl', 'James Hook & Co'] },
    },
    vote: { items: ["Red's Eats", 'Neptune Oyster', 'The Clam Shack', "Luke's Lobster", 'Eventide Oyster Co', 'McLoons Lobster Shack', 'Bite Into Maine', 'Five Islands Lobster Co', "Abbott's Lobster in the Rough", 'Lobster Hut Plymouth'] },
  },
  {
    id: 'pacific-ocean-resorts',
    publishedDate: '2026-05-24',
    title: 'Best Pacific Ocean Island Resorts',
    category: 'South Pacific',
    type: 'travel',
    tags: ['travel', 'luxury', 'stores'],
    linkType: 'mapsCity',
    blurb: 'Overwater bungalows and private atolls, from Bora Bora to Fiji to the Maldives.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'Consensus AI', items: ['Four Seasons Resort Bora Bora', 'The St. Regis Bora Bora Resort', 'InterContinental Thalasso Spa Bora Bora', "Le Taha'a by Pearl Resorts", 'Six Senses Fiji', 'Laucala Island Resort, Fiji', 'Como Laucala Island', 'The Brando, Tetiaroa', 'Soneva Fushi, Maldives', 'North Island, Seychelles'] },
      tlleisure: { label: 'Travel + Leisure Best Islands', items: ['The Brando, Tetiaroa', 'Four Seasons Resort Bora Bora', 'Laucala Island Resort, Fiji', 'Soneva Fushi, Maldives', 'North Island, Seychelles', 'Como Laucala Island', 'Six Senses Laamu, Maldives', 'The St. Regis Bora Bora Resort', 'Vomo Island Resort, Fiji', "Le Taha'a by Pearl Resorts"] },
      luxurytravelexpert: { label: 'Luxury Travel Expert', items: ['Kudadoo Maldives', 'Soneva Jani, Maldives', 'Cheval Blanc Randheli, Maldives', 'Soneva Fushi, Maldives', 'Six Senses Laamu, Maldives', 'The Brando, Tetiaroa', 'Laucala Island Resort, Fiji', 'Four Seasons Resort Bora Bora', 'North Island, Seychelles', 'Anantara Kihavah Maldives Villas'] },
      tripadvisor: { label: 'Tripadvisor Travelers Choice', items: ['Four Seasons Resort Bora Bora', 'The St. Regis Bora Bora Resort', 'Conrad Bora Bora Nui', 'Le Bora Bora by Pearl Resorts', 'InterContinental Thalasso Spa Bora Bora', 'Soneva Fushi, Maldives', 'Como Laucala Island', 'Vomo Island Resort, Fiji', 'Likuliku Lagoon Resort, Fiji', 'Tokoriki Island Resort, Fiji'] },
    },
    vote: { items: ['The Brando, Tetiaroa', 'Four Seasons Resort Bora Bora', 'Laucala Island Resort, Fiji', 'Soneva Fushi, Maldives', 'The St. Regis Bora Bora Resort', 'Como Laucala Island', 'Kudadoo Maldives', 'North Island, Seychelles', 'InterContinental Thalasso Spa Bora Bora', 'Six Senses Laamu, Maldives'] },
  },
  {
    id: 'cabo-hotels',
    publishedDate: '2026-05-24',
    title: 'Best Cabo San Lucas Hotels',
    category: 'Cabo San Lucas',
    type: 'travel',
    tags: ['travel', 'luxury', 'stores'],
    linkType: 'mapsCity',
    blurb: 'Where the Sea of Cortez meets the Pacific. Cliffside suites, infinity pools, and El Arco views.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'Consensus AI', items: ['Waldorf Astoria Los Cabos Pedregal', 'Esperanza, Auberge Collection', 'One&Only Palmilla', 'Las Ventanas al Paraiso, A Rosewood Resort', 'Grand Velas Los Cabos', 'Nobu Hotel Los Cabos', 'Montage Los Cabos', 'Four Seasons Resort Los Cabos at Costa Palmas', 'Chileno Bay Resort, Auberge Collection', 'Hotel El Ganzo'] },
      tripadvisor: { label: 'Tripadvisor Travelers Choice', items: ['Grand Solmar Pacific Dunes', 'Esperanza, Auberge Collection', 'Waldorf Astoria Los Cabos Pedregal', 'Garza Blanca Resort & Spa Los Cabos', 'Pueblo Bonito Sunset Beach', 'One&Only Palmilla', 'Chileno Bay Resort, Auberge Collection', 'Las Ventanas al Paraiso, A Rosewood Resort', 'Nobu Hotel Los Cabos', 'Hyatt Ziva Los Cabos'] },
      trip: { label: 'Trip.com Popular', items: ['Waldorf Astoria Los Cabos Pedregal', '1 Homes Preview Cabo', 'Esperanza, Auberge Collection', 'One&Only Palmilla', 'Grand Velas Los Cabos', 'Montage Los Cabos', 'Nobu Hotel Los Cabos', 'Chileno Bay Resort, Auberge Collection', 'Las Ventanas al Paraiso, A Rosewood Resort', 'Four Seasons Resort Los Cabos at Costa Palmas'] },
    },
    vote: { items: ['Waldorf Astoria Los Cabos Pedregal', 'Esperanza, Auberge Collection', 'One&Only Palmilla', 'Las Ventanas al Paraiso, A Rosewood Resort', 'Montage Los Cabos', 'Four Seasons Resort Los Cabos at Costa Palmas', 'Grand Velas Los Cabos', 'Nobu Hotel Los Cabos', 'Chileno Bay Resort, Auberge Collection', 'Grand Solmar Pacific Dunes'] },
  },
  {
    id: 'european-ski-resorts',
    publishedDate: '2026-05-25',
    title: 'Best European Ski Resorts',
    category: 'Alps',
    type: 'travel',
    tags: ['travel', 'luxury', 'entertainment', 'stores'],
    linkType: 'mapsCity',
    blurb: 'From Verbier glamour to Zermatt views to the Dolomites. Where the lifts are long and the apres-ski is legendary.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'Consensus AI', items: ['Verbier, Switzerland', 'Zermatt, Switzerland', 'St. Moritz, Switzerland', 'Courchevel, France', "Val d'Isère, France", "Cortina d'Ampezzo, Italy", 'Chamonix-Mont Blanc, France', 'Kitzbühel, Austria', 'Val Thorens, France', 'Gstaad, Switzerland'] },
      cntraveler: { label: 'Conde Nast Traveler Readers Choice 2025', items: ['Verbier, Switzerland', 'Zermatt, Switzerland', 'St. Moritz, Switzerland', 'Courchevel, France', "Cortina d'Ampezzo, Italy", 'Levi, Finland', 'Crans-Montana, Switzerland', "Val d'Isère, France", 'Innsbruck, Austria', 'Corvara - Alta Badia, Italy'] },
      timeout: { label: 'Time Out · Omio Data', items: ['Arosa Lenzerheide, Switzerland', 'Sölden, Austria', 'SkiWelt Wilder Kaiser-Brixental, Austria', 'Saalbach Hinterglemm Leogang Fieberbrunn, Austria', 'Zermatt, Switzerland', 'Val Thorens, France', 'Chamonix-Mont Blanc, France', 'Kitzbühel, Austria', 'St. Anton am Arlberg, Austria', 'Val Gardena, Italy'] },
      worldskiawards: { label: 'World Ski Awards', items: ['Val Thorens, France', 'Zermatt, Switzerland', 'Verbier, Switzerland', 'St. Anton am Arlberg, Austria', 'Courchevel, France', 'Chamonix-Mont Blanc, France', 'Kitzbühel, Austria', "Val d'Isère, France", "Cortina d'Ampezzo, Italy", 'Lech, Austria'] },
    },
    vote: { items: ['Verbier, Switzerland', 'Zermatt, Switzerland', 'Chamonix-Mont Blanc, France', 'St. Moritz, Switzerland', 'Courchevel, France', "Val d'Isère, France", "Cortina d'Ampezzo, Italy", 'Kitzbühel, Austria', 'St. Anton am Arlberg, Austria', 'Val Thorens, France'] },
  },
  {
    id: 'greek-isles-hotels',
    publishedDate: '2026-05-25',
    title: 'Best Hotels in the Greek Isles',
    category: 'Greek Islands',
    type: 'travel',
    tags: ['travel', 'luxury', 'stores'],
    linkType: 'mapsCity',
    blurb: 'Cave suites in Oia, Cycladic whitewash in Mykonos, and the boutique hideouts that earn the Aegean its reputation.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'Consensus AI', items: ['Perivolas, Santorini', 'Grace Hotel Santorini, Auberge Resorts Collection', 'Kalesma Mykonos', 'Cavo Tagoo Mykonos', 'Bill & Coo Mykonos', 'Kivotos Santorini', 'Mystique, a Luxury Collection Hotel, Santorini', 'Myconian Naia', 'Canaves Oia', 'Santa Marina, a Luxury Collection Resort, Mykonos'] },
      timeout: { label: 'Time Out Greece', items: ['Kivotos Santorini', 'Grace Hotel Santorini, Auberge Resorts Collection', 'Voreina Gallery Suites Santorini', 'Kalesma Mykonos', 'Kove Mykonos', 'Anemelia Mykonos', 'Perivolas, Santorini', 'Mystique, Santorini', 'Canaves Oia', 'Bill & Coo Mykonos'] },
      trip: { label: 'Trip.com Luxury Rankings', items: ['Kalesma Mykonos', 'Aeonic Suites and Spa, Mykonos', 'Myconian Naia', 'Cavo Tagoo Mykonos', 'Mystique, Santorini', 'Grace Hotel Santorini, Auberge Resorts Collection', 'Canaves Oia', 'Bill & Coo Mykonos', 'Santa Marina, Mykonos', 'Perivolas, Santorini'] },
      findus: { label: 'Find Us Lost Editor Picks', items: ['Perivolas, Santorini', 'Panoptis Escape, Mykonos', 'Aristide Hotel, Syros', 'Odera Hotel, Tinos', 'Kalesma Mykonos', 'Canaves Oia', 'Mystique, Santorini', 'Grace Hotel Santorini, Auberge Resorts Collection', 'Bill & Coo Mykonos', 'Cavo Tagoo Mykonos'] },
    },
    vote: { items: ['Perivolas, Santorini', 'Kalesma Mykonos', 'Mystique, Santorini', 'Bill & Coo Mykonos', 'Canaves Oia', 'Cavo Tagoo Mykonos', 'Grace Hotel Santorini, Auberge Resorts Collection', 'Santa Marina, Mykonos', 'Kivotos Santorini', 'Myconian Naia'] },
  },
  {
    id: 'boston-hotels',
    publishedDate: '2026-05-26',
    title: 'Best Boston Hotels',
    category: 'Boston',
    type: 'travel',
    tags: ['travel', 'luxury', 'stores'],
    linkType: 'mapsCity',
    blurb: 'Back Bay luxury at Mandarin Oriental, harbor views at InterContinental, Public Garden frontage at Four Seasons. The hotels that anchor a city built on bricks and history.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'Consensus AI',
        items: ['Mandarin Oriental Boston', 'InterContinental Boston', 'Four Seasons Hotel Boston', 'The Ritz-Carlton Boston', 'Raffles Boston', 'The Newbury Boston', 'Boston Harbor Hotel', 'The Langham Boston', 'Hotel AKA Boston Common', 'XV Beacon'],
      },
      usnews: {
        label: 'U.S. News 25 Best 2026',
        items: ['Mandarin Oriental Boston', 'Four Seasons Hotel Boston', 'The Ritz-Carlton Boston', 'Raffles Boston', 'The Newbury Boston', 'Boston Harbor Hotel', 'InterContinental Boston', 'XV Beacon', 'The Langham Boston', 'Four Seasons Hotel One Dalton Street'],
      },
      cntraveler: {
        label: "Conde Nast Readers' Choice",
        items: ['InterContinental Boston', 'Mandarin Oriental Boston', 'Hotel AKA Boston Common', 'Hyatt Regency Boston', 'Four Seasons Hotel Boston', 'The Ritz-Carlton Boston', 'The Langham Boston', 'Boston Harbor Hotel', 'Raffles Boston', 'The Newbury Boston'],
      },
      forbes: {
        label: 'Forbes Travel Guide',
        items: ['Mandarin Oriental Boston', 'Four Seasons Hotel Boston', 'The Ritz-Carlton Boston', 'Boston Harbor Hotel', 'The Langham Boston', 'Raffles Boston', 'The Newbury Boston', 'InterContinental Boston', 'Four Seasons Hotel One Dalton Street', 'XV Beacon'],
      },
    },
    vote: {
      items: ['Mandarin Oriental Boston', 'Four Seasons Hotel Boston', 'InterContinental Boston', 'The Ritz-Carlton Boston', 'Raffles Boston', 'The Newbury Boston', 'Boston Harbor Hotel', 'The Langham Boston', 'XV Beacon', 'Hotel AKA Boston Common'],
    },
  },
  {
    id: 'vegas-casino-hotels',
    publishedDate: '2026-05-25',
    title: 'Best Hotel Casinos in Las Vegas',
    category: 'Las Vegas',
    type: 'travel',
    tags: ['travel', 'luxury', 'entertainment', 'nightlife', 'bars', 'stores'],
    linkType: 'mapsCity',
    blurb: "The Strip's heaviest hitters, where the fountains dance, the suites overlook the desert, and the casino floors never close.",
    defaultSource: 'ai',
    sources: {
      ai: { label: 'Consensus AI', items: ['Wynn Las Vegas', 'Bellagio', 'The Venetian Resort Las Vegas', 'Encore at Wynn Las Vegas', 'Aria Resort & Casino', 'The Cosmopolitan of Las Vegas', 'Caesars Palace', 'Fontainebleau Las Vegas', 'MGM Grand', 'Resorts World Las Vegas'] },
      tlleisure: { label: "Travel + Leisure World's Best", items: ['Wynn Las Vegas', 'Bellagio', 'Encore at Wynn Las Vegas', 'The Venetian Resort Las Vegas', 'Four Seasons Hotel Las Vegas', 'Aria Resort & Casino', 'The Cosmopolitan of Las Vegas', 'Mandalay Bay', 'Caesars Palace', 'Resorts World Las Vegas'] },
      usnews: { label: 'U.S. News Best Hotels', items: ['Wynn Las Vegas', 'Bellagio', 'The Venetian Resort Las Vegas', 'Aria Resort & Casino', 'Four Seasons Hotel Las Vegas', 'Encore at Wynn Las Vegas', 'The Cosmopolitan of Las Vegas', 'Vdara Hotel & Spa', 'Waldorf Astoria Las Vegas', 'NoMad Las Vegas'] },
      forbes: { label: 'Forbes Travel Guide', items: ['Wynn Las Vegas', 'Encore at Wynn Las Vegas', 'Bellagio', 'The Venetian Resort Las Vegas', 'Four Seasons Hotel Las Vegas', 'Aria Sky Suites', 'Waldorf Astoria Las Vegas', 'The Cosmopolitan of Las Vegas', 'Caesars Palace', 'Skylofts at MGM Grand'] },
    },
    vote: { items: ['Wynn Las Vegas', 'Bellagio', 'The Venetian Resort Las Vegas', 'The Cosmopolitan of Las Vegas', 'Caesars Palace', 'Encore at Wynn Las Vegas', 'Aria Resort & Casino', 'Fontainebleau Las Vegas', 'Mandalay Bay', 'MGM Grand'] },
  },
  {
    id: 'f1-fan-experience',
    publishedDate: '2026-05-25',
    title: 'Best F1 Races for Fan Experience',
    category: 'Formula 1',
    type: 'travel',
    tags: ['travel', 'entertainment'],
    linkType: 'wiki',
    blurb: 'Where the atmosphere outshines the cars. Tifosi in Monza, festival vibes at Zandvoort, and the unrivaled pageantry of Monaco.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'Consensus AI', items: ['Monaco Grand Prix', 'British Grand Prix', 'Italian Grand Prix', 'Belgian Grand Prix', 'Mexico City Grand Prix', 'Japanese Grand Prix', 'São Paulo Grand Prix', 'Dutch Grand Prix', 'Singapore Grand Prix', 'Las Vegas Grand Prix'] },
      f1experiences: { label: 'F1 Experiences', items: ['Italian Grand Prix', 'British Grand Prix', 'Monaco Grand Prix', 'Belgian Grand Prix', 'Japanese Grand Prix', 'Australian Grand Prix', 'Canadian Grand Prix', 'United States Grand Prix', 'São Paulo Grand Prix', 'Hungarian Grand Prix'] },
      motorsport: { label: 'Motorsport.com', items: ['Monaco Grand Prix', 'Dutch Grand Prix', 'British Grand Prix', 'Mexico City Grand Prix', 'Italian Grand Prix', 'Belgian Grand Prix', 'Japanese Grand Prix', 'São Paulo Grand Prix', 'Singapore Grand Prix', 'United States Grand Prix'] },
      grandprix247: { label: 'GrandPrix247', items: ['Monaco Grand Prix', 'British Grand Prix', 'Belgian Grand Prix', 'Italian Grand Prix', 'Japanese Grand Prix', 'Mexico City Grand Prix', 'São Paulo Grand Prix', 'Australian Grand Prix', 'Singapore Grand Prix', 'Canadian Grand Prix'] },
    },
    vote: { items: ['Monaco Grand Prix', 'British Grand Prix', 'Italian Grand Prix', 'Belgian Grand Prix', 'Japanese Grand Prix', 'São Paulo Grand Prix', 'Mexico City Grand Prix', 'Dutch Grand Prix', 'Singapore Grand Prix', 'Las Vegas Grand Prix'] },
  },
  {
    id: 'exclusive-golf-clubs',
    publishedDate: '2026-05-26',
    title: 'Most Exclusive Golf Clubs in the World',
    category: 'Golf',
    type: 'entertainment',
    tags: ['entertainment', 'travel', 'luxury', 'stores'],
    linkType: 'wiki',
    blurb: 'Invitation only. No application process. Fewer than 300 members at most. The clubs where Augusta National looks almost accessible by comparison.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'Consensus AI',
        items: ['Augusta National Golf Club', 'Pine Valley Golf Club', 'Cypress Point Club', 'Muirfield (Honourable Company of Edinburgh Golfers)', 'Royal Melbourne Golf Club (West)', 'Shinnecock Hills Golf Club', 'Seminole Golf Club', 'National Golf Links of America', 'Hirono Golf Club', 'Loch Lomond Golf Club'],
      },
      golfmag: {
        label: 'GOLF Magazine 14 Most Exclusive',
        items: ['Pine Valley Golf Club', 'Seminole Golf Club', 'Chicago Golf Club', 'Cypress Point Club', 'Nanea Golf Club', 'Augusta National Golf Club', 'Shinnecock Hills Golf Club', 'National Golf Links of America', 'San Francisco Golf Club', 'Merion Golf Club'],
      },
      billionaire: {
        label: 'Billionaire.com Top 10',
        items: ['Cypress Point Club', 'National Golf Links of America', 'Augusta National Golf Club', 'Golf de Morfontaine', 'Loch Lomond Golf Club', 'Los Angeles Country Club', 'Royal Melbourne Golf Club (West)', 'Hirono Golf Club', 'Swinley Forest Golf Club', 'Gleneagles'],
      },
      yourgolftravel: {
        label: 'Your Golf Travel · Fairway Tours',
        items: ['Augusta National Golf Club', 'Pine Valley Golf Club', 'Muirfield (Honourable Company of Edinburgh Golfers)', 'Royal Melbourne Golf Club (West)', 'Royal County Down Golf Club', 'Hirono Golf Club', 'Loch Lomond Golf Club', 'Cypress Point Club', 'Shinnecock Hills Golf Club', 'Swinley Forest Golf Club'],
      },
    },
    vote: {
      items: ['Augusta National Golf Club', 'Pine Valley Golf Club', 'Cypress Point Club', 'Shinnecock Hills Golf Club', 'Muirfield (Honourable Company of Edinburgh Golfers)', 'Seminole Golf Club', 'Royal Melbourne Golf Club (West)', 'National Golf Links of America', 'Loch Lomond Golf Club', 'Hirono Golf Club'],
    },
  },

  /* ----- ENTERTAINMENT ----- */
  {
    id: 'movies',
    publishedDate: '2026-05-24',
    title: 'Best Movies of All Time',
    category: 'Cinema',
    type: 'entertainment',
    tags: ['entertainment'],
    linkType: 'imdb',
    blurb: 'The films that defined the medium and the ones the public refuses to forget.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'Consensus AI', items: ['The Godfather', 'Citizen Kane', 'Casablanca', 'The Shawshank Redemption', "Schindler's List", 'Pulp Fiction', '2001: A Space Odyssey', 'Vertigo', 'Seven Samurai', 'Lawrence of Arabia', 'The Godfather Part II', 'Goodfellas'] },
      imdb: { label: 'IMDB Top Rated', items: ['The Shawshank Redemption', 'The Godfather', 'The Dark Knight', 'The Godfather Part II', '12 Angry Men', "Schindler's List", 'The Lord of the Rings: The Return of the King', 'Pulp Fiction', 'The Lord of the Rings: The Fellowship of the Ring', 'The Good, the Bad and the Ugly', 'Forrest Gump', 'Fight Club'] },
      rotten: { label: 'Rotten Tomatoes 100 Best', items: ['Citizen Kane', 'Casablanca', 'The Wizard of Oz', 'Modern Times', 'Black Panther', 'Parasite', 'Avengers: Endgame', 'It Happened One Night', 'Get Out', 'The Cabinet of Dr. Caligari', "Singin' in the Rain", 'All About Eve'] },
    },
    vote: { items: ['The Dark Knight', 'Inception', 'Forrest Gump', 'Goodfellas', 'The Matrix', 'Spirited Away', 'Parasite', 'Fight Club', 'Back to the Future', 'Interstellar'] },
  },
  {
    id: 'top-grossing-films-1990',
    publishedDate: '2026-05-25',
    title: 'Top-Grossing Films of 1990',
    category: 'Movies · 1990',
    type: 'entertainment',
    tags: ['entertainment'],
    linkType: 'imdb',
    mode: 'facts',
    blurb: 'The box office champions of 1990, ranked by worldwide gross. Ghost led the year, Home Alone became a Christmas institution, and Dances With Wolves swept the Oscars.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'Box Office Mojo · Worldwide Gross', items: ['Ghost', 'Home Alone', 'Pretty Woman', 'Dances with Wolves', 'Total Recall', 'Back to the Future Part III', 'Die Hard 2', 'Presumed Innocent', 'Teenage Mutant Ninja Turtles', 'Kindergarten Cop'] },
    },
  },
  {
    id: 'tv',
    publishedDate: '2026-05-24',
    title: 'Best TV Shows',
    category: 'Television',
    type: 'entertainment',
    tags: ['entertainment'],
    linkType: 'imdb',
    blurb: 'The most watched television of the modern era versus the most beloved.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'Consensus AI', items: ['Breaking Bad', 'The Sopranos', 'The Wire', 'Mad Men', 'Game of Thrones', 'The Simpsons', 'Seinfeld', 'Better Call Saul', 'Friends', 'The Office'] },
      imdb: { label: 'IMDB Top Rated', items: ['Breaking Bad', 'Band of Brothers', 'Chernobyl', 'The Wire', 'Avatar: The Last Airbender', 'The Sopranos', 'Better Call Saul', 'Game of Thrones', 'Cosmos', 'Rick and Morty'] },
    },
    vote: { items: ['Breaking Bad', 'The Wire', 'Better Call Saul', 'The Sopranos', 'Succession', 'Mad Men', 'Chernobyl', 'Fleabag', 'Severance', 'The Leftovers'] },
  },
  /* ----- STORES / PLACES ----- */
  {
    id: 'pizza-nyc',
    publishedDate: '2026-05-27',
    title: 'Best Pizza in NYC',
    category: 'New York',
    type: 'stores',
    tags: ['food', 'food-drink', 'stores'],
    linkType: 'mapsCity',
    blurb: "Slices and whole pies. L'Industrie's burrata square, Lucali's basil-piled rounds, Una Pizza's Neapolitan benchmarks, and the L&B square that earned its rite-of-passage status.",
    defaultSource: 'ai',
    sources: {
      ai: { label: 'Consensus AI', items: ["L'Industrie Pizzeria", 'Lucali', 'Una Pizza Napoletana', 'L&B Spumoni Gardens', "Mama's Too", "Joe's Pizza", 'Di Fara Pizza', "Roberta's", "Scarr's Pizza", 'Prince Street Pizza'] },
      infatuation: { label: 'The Infatuation 23 Best', items: ["L'Industrie Pizzeria", 'Lucali', 'L&B Spumoni Gardens', 'Una Pizza Napoletana', "Mama's Too", "Joe's Pizza", "Roberta's", 'Di Fara Pizza', "Scarr's Pizza", 'Prince Street Pizza'] },
      timeout: { label: 'Time Out New York', items: ["Mama's Too", "L'Industrie Pizzeria", 'Una Pizza Napoletana', 'Lucali', "Roberta's", 'L&B Spumoni Gardens', 'Di Fara Pizza', 'Prince Street Pizza', "Joe's Pizza", "Paulie Gee's"] },
      topfifty: { label: '50 Top Pizza USA 2025', items: ['Una Pizza Napoletana', 'Ribalta', "L'Industrie Pizzeria", 'Lucali', 'Stretch Pizza', 'Don Antonio', "Mama's Too", "Roberta's", 'Una Pizza Napoletana', 'Di Fara Pizza'] },
    },
    vote: { items: ["L'Industrie Pizzeria", 'Lucali', "Mama's Too", "Joe's Pizza", 'Una Pizza Napoletana', "Scarr's Pizza", "Roberta's", 'Prince Street Pizza', 'Di Fara Pizza', 'L&B Spumoni Gardens'] },
  },
  {
    id: 'tacos-la',
    publishedDate: '2026-05-24',
    title: 'Best Tacos in Los Angeles',
    category: 'Los Angeles',
    type: 'stores',
    tags: ['food', 'food-drink', 'stores'],
    linkType: 'mapsCity',
    blurb: 'A taqueria capital. Awards on one side, taco truck loyalty on the other.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'Consensus AI', items: ['Mariscos Jalisco', 'Guisados', 'Tacos 1986', 'Sonoratown', "Leo's Taco Truck", 'Holbox', 'B.S. Taqueria', 'Carnitas El Momo', 'El Ruso', 'Tire Shop Taqueria'] },
      latimes: { label: 'LA Times 101 Best', items: ['Mariscos Jalisco', 'Sonoratown', 'Tacos 1986', 'Carnitas El Momo', 'El Ruso', "Villa's Tacos", 'Holbox', "Leo's Taco Truck", 'Tire Shop Taqueria', 'Guisados'] },
      eater: { label: 'Eater LA', items: ['Tacos 1986', 'Sonoratown', 'Mariscos Jalisco', "Villa's Tacos", 'Carnitas El Momo', 'El Ruso', 'Guisados', 'Holbox', 'Loqui', "Leo's Taco Truck"] },
    },
    vote: { items: ['Tacos 1986', 'Sonoratown', 'Mariscos Jalisco', "Leo's Taco Truck", "Villa's Tacos", 'Guisados', 'El Ruso', 'Carnitas El Momo', 'Holbox', 'Tire Shop Taqueria'] },
  },
  {
    id: 'burritos-san-diego',
    publishedDate: '2026-05-27',
    title: 'Best Burritos in San Diego',
    category: 'San Diego',
    type: 'stores',
    tags: ['food', 'food-drink', 'stores'],
    linkType: 'mapsCity',
    blurb: "Carne asada, no beans, no rice. The California burrito was invented here and the surf shops defend it. Every spot below makes a burrito worth ordering, even when 'Taco Shop' is on the sign.",
    defaultSource: 'ai',
    sources: {
      ai: { label: 'Consensus AI', items: ["Lolita's Mexican Food", 'Lucha Libre Gourmet Taco Shop', 'El Zarape', 'Taco Stand (La Jolla)', "Adalberto's Mexican Food", "Nico's Mexican Food", "Roberto's Taco Shop", 'Don Carlos Taco Shop', 'La Puerta', 'Las Cuatro Milpas'] },
      thrillist: { label: 'Thrillist · The Daily Meal', items: ['Lucha Libre Gourmet Taco Shop', "Lolita's Mexican Food", 'Taco Stand (La Jolla)', 'El Zarape', 'La Perla Cocina', "Nico's Mexican Food", "Adalberto's Mexican Food", 'Taco Surf', 'Don Carlos Taco Shop', "Roberto's Taco Shop"] },
      plnu: { label: 'PLNU Great Burrito Bracket', items: ["Adalberto's Mexican Food", 'El Zarape', 'Las Cuatro Milpas', "Lolita's Mexican Food", 'Taco Stand (La Jolla)', "Roberto's Taco Shop", 'Lucha Libre Gourmet Taco Shop', 'La Puerta', 'Taco Surf', "Nico's Mexican Food"] },
    },
    vote: { items: ["Lolita's Mexican Food", 'Lucha Libre Gourmet Taco Shop', 'El Zarape', 'Taco Stand (La Jolla)', "Adalberto's Mexican Food", "Nico's Mexican Food", "Roberto's Taco Shop", 'La Puerta', 'Don Carlos Taco Shop', 'Las Cuatro Milpas'] },
  },
  {
    id: 'burritos-nyc',
    publishedDate: '2026-05-27',
    title: 'Best Burritos in NYC',
    category: 'New York',
    type: 'stores',
    tags: ['food', 'food-drink', 'stores'],
    linkType: 'mapsCity',
    blurb: "Mission-style transplants, Sonoran imports, and the Fort Greene shop hand-rolling lard tortillas to order. Where NYC's burrito scene actually lives.",
    defaultSource: 'ai',
    sources: {
      ai: { label: 'Consensus AI', items: ["B'Klyn Burro", 'Plaza Ortega', 'Super Burrito (Williamsburg)', 'Son Del North', 'Los Burritos Juárez', 'La Taq (Park Slope)', 'Taqueria Tlaxcalli', 'Electric Burrito', 'Calexico', 'Dos Toros Taqueria'] },
      infatuation: { label: 'The Infatuation 16 Best', items: ['Plaza Ortega', 'Super Burrito (Williamsburg)', 'Son Del North', 'Los Burritos Juárez', "B'Klyn Burro", 'Taqueria Tlaxcalli', 'La Taq (Park Slope)', 'Electric Burrito', 'Downtown Burritos', 'Super Burrito (Rockaway)'] },
      timeout: { label: 'Time Out New York', items: ['Los Burritos Juárez', "B'Klyn Burro", 'Plaza Ortega', 'Son Del North', 'La Taq (Park Slope)', 'Super Burrito (Williamsburg)', 'Taqueria Tlaxcalli', 'Electric Burrito', 'Calexico', 'Dos Toros Taqueria'] },
      fivethirtyeight: { label: 'FiveThirtyEight Burrito Bracket', items: ['Taqueria Tlaxcalli', 'Mission Cantina', "B'Klyn Burro", 'Calexico', 'Dos Toros Taqueria', 'Tres Carnes', 'La Taq (Park Slope)', 'Chipotle', 'Plaza Ortega', 'Son Del North'] },
    },
    vote: { items: ["B'Klyn Burro", 'Plaza Ortega', 'Super Burrito (Williamsburg)', 'Son Del North', 'Los Burritos Juárez', 'La Taq (Park Slope)', 'Taqueria Tlaxcalli', 'Electric Burrito', 'Calexico', 'Dos Toros Taqueria'] },
  },
  {
    id: 'caesar-wraps-nyc',
    publishedDate: '2026-05-26',
    title: 'Best Chicken Caesar Wraps in NYC',
    category: 'New York',
    type: 'stores',
    tags: ['food', 'food-drink', 'stores'],
    linkType: 'mapsCity',
    blurb: 'The viral lunch of the decade. Crisp romaine, parmesan, grilled or fried chicken bundled in a tortilla. The shops that built the cult.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'Consensus AI',
        items: ['Milano Market', 'Lenwich', 'Bobwhite Counter', "Jacob's Pickles", 'Heavenly Market', 'La Villa Pizzeria', "Compton's", 'Brown Bag Sandwich', "Edith's", 'Smith Gourmet Deli'],
      },
      modernluxury: {
        label: 'Modern Luxury · Gotham',
        items: ['Milano Market', 'Lenwich', 'Heavenly Market', 'La Villa Pizzeria', 'Bobwhite Counter', "Jacob's Pickles", 'The Arch Cafe', "Compton's", 'Brown Bag Sandwich', "Edith's"],
      },
      infatuation: {
        label: 'The Infatuation',
        items: ['Milano Market', 'Lenwich', 'Bobwhite Counter', "Jacob's Pickles", "Compton's", 'Brown Bag Sandwich', "Edith's", 'Smith Gourmet Deli', 'Heavenly Market', 'La Villa Pizzeria'],
      },
      yelp: {
        label: 'Yelp Top 10',
        items: ['Brown Bag Sandwich', 'Bobwhite Counter', "Edith's", "Jacob's Pickles", "Sunny and Annie's", 'Milano Market', 'Smith Gourmet Deli', "Compton's", 'Lenwich', 'Heavenly Market'],
      },
    },
    vote: {
      items: ['Milano Market', 'Lenwich', 'Bobwhite Counter', "Jacob's Pickles", "Edith's", 'Heavenly Market', "Compton's", 'La Villa Pizzeria', 'Brown Bag Sandwich', 'Smith Gourmet Deli'],
    },
  },
  {
    id: 'caesar-wraps-la',
    publishedDate: '2026-05-26',
    title: 'Best Chicken Caesar Wraps in LA',
    category: 'Los Angeles',
    type: 'stores',
    tags: ['food', 'food-drink', 'stores'],
    linkType: 'mapsCity',
    blurb: 'Ggiata started a movement and the rest of the city followed. Crispy chicken, romaine, parmesan. The only debate is the dressing.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'Consensus AI',
        items: ['Ggiata', "Uncle Paulie's Deli", 'Goop Kitchen', 'Garden Cafe', 'Aroma Coffee & Tea', 'Il Tramezzino', "Joan's on Third", 'Cafe Bizou', 'Black Rabbit Cafe', 'Leora Cafe'],
      },
      yelp: {
        label: 'Yelp Top 10',
        items: ['Ggiata', "Uncle Paulie's Deli", 'Garden Cafe', 'Aroma Coffee & Tea', 'Goop Kitchen', 'Ggiata West Hollywood', 'Il Tramezzino', 'Black Rabbit Cafe', "Joan's on Third", 'Leora Cafe'],
      },
      latimes: {
        label: 'LA Times · Eater LA',
        items: ['Ggiata', "Uncle Paulie's Deli", 'Cafe Bizou', "Joan's on Third", 'Goop Kitchen', 'Il Tramezzino', 'Garden Cafe', 'Aroma Coffee & Tea', 'Black Rabbit Cafe', 'Leora Cafe'],
      },
      timeout: {
        label: 'Time Out Los Angeles',
        items: ['Ggiata', 'Goop Kitchen', "Uncle Paulie's Deli", "Joan's on Third", 'Garden Cafe', 'Leora Cafe', 'Cafe Bizou', 'Aroma Coffee & Tea', 'Il Tramezzino', 'Black Rabbit Cafe'],
      },
    },
    vote: {
      items: ['Ggiata', "Uncle Paulie's Deli", 'Goop Kitchen', "Joan's on Third", 'Garden Cafe', 'Il Tramezzino', 'Aroma Coffee & Tea', 'Cafe Bizou', 'Leora Cafe', 'Black Rabbit Cafe'],
    },
  },
  {
    id: 'caesar-wraps-miami',
    publishedDate: '2026-05-26',
    title: 'Best Chicken Caesar Wraps in Miami',
    category: 'Miami',
    type: 'stores',
    tags: ['food', 'food-drink', 'stores'],
    linkType: 'mapsCity',
    blurb: "Boca's Vinny's Cafe set Florida on fire. The Miami spots that followed bring beach-town twists to the viral wrap.",
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'Consensus AI',
        items: ['Tap 42', "Vinny's Cafe (Boca)", 'The Brightside', 'Carrot Express', 'Pura Vida Miami', 'Mister O1 South Beach', 'Pane e Vino', 'Cafe Papillon By The Beach', 'Giardino', 'High Tide'],
      },
      miaminewtimes: {
        label: 'Miami New Times',
        items: ["Vinny's Cafe (Boca)", 'Tap 42', 'The Brightside', 'Pura Vida Miami', 'Carrot Express', 'Giardino', 'Mister O1 South Beach', 'Pane e Vino', 'High Tide', 'Cafe Papillon By The Beach'],
      },
      yelp: {
        label: 'Yelp Top 10',
        items: ['Carrot Express', 'The Brightside', 'Pura Vida Miami', 'Mister O1 South Beach', 'Pane e Vino', 'Cafe Papillon By The Beach', 'High Tide', 'Tap 42', 'Giardino', "Vinny's Cafe (Boca)"],
      },
      timeout: {
        label: 'Time Out Miami',
        items: ['Tap 42', "Vinny's Cafe (Boca)", 'Pura Vida Miami', 'Carrot Express', 'The Brightside', 'Giardino', 'Pane e Vino', 'Mister O1 South Beach', 'High Tide', 'Cafe Papillon By The Beach'],
      },
    },
    vote: {
      items: ['Tap 42', "Vinny's Cafe (Boca)", 'Carrot Express', 'The Brightside', 'Pura Vida Miami', 'Giardino', 'Mister O1 South Beach', 'Pane e Vino', 'High Tide', 'Cafe Papillon By The Beach'],
    },
  },
  {
    id: 'caesar-wraps-chicago',
    publishedDate: '2026-05-26',
    title: 'Best Chicken Caesar Wraps in Chicago',
    category: 'Chicago',
    type: 'stores',
    tags: ['food', 'food-drink', 'stores'],
    linkType: 'mapsCity',
    blurb: 'From Bridgeport flatbread originals to Wicker Park fried chicken collabs. The CCW capital of the Midwest.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'Consensus AI',
        items: ["Punky's Pizza & Pasta", 'Little Victories', 'Nohea Cafe', 'Village Tap', 'Moonwalker', "GG's Chicken Shop", "D'Amato's Bakery", 'Pompeii', 'Buttermilk Fry', 'Spilt Milk'],
      },
      infatuation: {
        label: 'The Infatuation 8 Best',
        items: ["Punky's Pizza & Pasta", 'Little Victories', 'Nohea Cafe', 'Village Tap', 'Moonwalker', 'Buttermilk Fry', "GG's Chicken Shop", "D'Amato's Bakery", 'Spilt Milk', 'Pompeii'],
      },
      tribune: {
        label: 'Chicago Tribune',
        items: ["Punky's Pizza & Pasta", 'Nohea Cafe', 'Village Tap', 'Moonwalker', 'Little Victories', "GG's Chicken Shop", 'Buttermilk Fry', "D'Amato's Bakery", 'Pompeii', 'Spilt Milk'],
      },
      yelp: {
        label: 'Yelp Top 10',
        items: ['Little Victories', "Punky's Pizza & Pasta", 'Nohea Cafe', "GG's Chicken Shop", 'Village Tap', "D'Amato's Bakery", 'Moonwalker', 'Buttermilk Fry', 'Pompeii', 'Spilt Milk'],
      },
    },
    vote: {
      items: ["Punky's Pizza & Pasta", 'Little Victories', 'Nohea Cafe', 'Village Tap', 'Moonwalker', "GG's Chicken Shop", 'Buttermilk Fry', "D'Amato's Bakery", 'Pompeii', 'Spilt Milk'],
    },
  },
  {
    id: 'cocktails-williamsburg',
    publishedDate: '2026-05-25',
    title: 'Best Cocktail Bars in Williamsburg',
    category: 'Williamsburg, Brooklyn',
    type: 'stores',
    tags: ['bars', 'nightlife', 'food-drink', 'stores', 'entertainment'],
    linkType: 'mapsCity',
    blurb: 'Oyster-bar standards, rooftop skyline pours, and the no-menu mixology rooms that put Brooklyn on the cocktail map.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'Consensus AI', items: ['Maison Premiere', 'Fresh Kills Bar', 'Bar Blondeau', 'Westlight', 'Rose Marie', 'Bar Madonna', 'Sauced', 'Layla', 'Pokito', 'Le Crocodile'] },
      infatuation: { label: 'The Infatuation 22 Best', items: ['Maison Premiere', 'Rose Marie', 'Bar Blondeau', 'Sauced', 'Layla', 'Fresh Kills Bar', 'Bar Madonna', 'Westlight', "Mo's General", 'Le Crocodile'] },
      timeout: { label: 'Time Out New York', items: ['Maison Premiere', 'Bar Madonna', 'Velvet Brooklyn', 'The Twenty Bar', 'Fresh Kills Bar', 'Pokito', 'Westlight', 'Bar Blondeau', 'Bar Milagro', 'Layla'] },
      worlds50best: { label: "World's 50 Best Bars (NA)", items: ['Maison Premiere', 'Fresh Kills Bar', 'Bar Blondeau', 'Rose Marie', 'Le Crocodile', 'Westlight', 'Bar Madonna', 'Layla', 'Sauced', 'Pokito'] },
    },
    vote: { items: ['Maison Premiere', 'Fresh Kills Bar', 'Bar Blondeau', 'Westlight', 'Rose Marie', 'Bar Madonna', 'Le Crocodile', 'Layla', 'Sauced', 'Pokito'] },
  },
  {
    id: 'live-music-nyc',
    publishedDate: '2026-05-25',
    title: 'Best Live Music Bars in NYC',
    category: 'New York',
    type: 'stores',
    tags: ['bars', 'nightlife', 'food-drink', 'stores', 'entertainment'],
    linkType: 'mapsCity',
    blurb: "The rooms where Vampire Weekend, The Strokes, and a thousand more got their break. Indie, jazz, and the rising acts you'll claim you saw first.",
    defaultSource: 'ai',
    sources: {
      ai: { label: 'Consensus AI', items: ['Bowery Ballroom', 'Mercury Lounge', 'Music Hall of Williamsburg', 'Rockwood Music Hall', "Arlene's Grocery", 'Blue Note Jazz Club', 'Village Vanguard', 'Birdland Jazz Club', "Baby's All Right", 'The Bitter End'] },
      timeout: { label: 'Time Out New York', items: ['Bowery Ballroom', 'Music Hall of Williamsburg', 'Mercury Lounge', "Baby's All Right", 'Rockwood Music Hall', 'Village Vanguard', 'Blue Note Jazz Club', 'Birdland Jazz Club', "Pete's Candy Store", 'The Django'] },
      happyhour: { label: 'Happy Hour NYC Guide', items: ["Baby's All Right", 'Birdland Jazz Club', 'Blue Note Jazz Club', 'Bowery Ballroom', 'Mercury Lounge', "Pete's Candy Store", 'Rockwood Music Hall', 'Terra Blues', 'The Django', 'Village Vanguard'] },
      gwepa: { label: 'GWEPA 55 Best Venues', items: ['Bowery Ballroom', 'Mercury Lounge', 'Rockwood Music Hall', 'Bowery Electric', "Arlene's Grocery", 'Highline Ballroom', 'Music Hall of Williamsburg', 'Pianos', 'The Bitter End', 'Slake'] },
    },
    vote: { items: ['Bowery Ballroom', 'Mercury Lounge', 'Village Vanguard', 'Music Hall of Williamsburg', 'Blue Note Jazz Club', 'Rockwood Music Hall', "Baby's All Right", 'Birdland Jazz Club', "Arlene's Grocery", 'The Bitter End'] },
  },
  {
    id: 'dive-bars-williamsburg',
    publishedDate: '2026-05-26',
    title: 'Best Dive Bars in Williamsburg',
    category: 'Williamsburg, Brooklyn',
    type: 'stores',
    tags: ['bars', 'nightlife', 'food-drink', 'stores', 'entertainment'],
    linkType: 'mapsCity',
    blurb: 'Sticky floors, cheap beer, classic rock jukeboxes. The bars that resisted the gentrification or learned to coexist with it.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'Consensus AI',
        items: ['The Commodore', 'Rocka Rolla', "Turkey's Nest", 'Skinny Dennis', "Sharlene's", "Duff's Brooklyn", 'R Bar', "Clem's", "Pete's Candy Store", 'Boobie Trap'],
      },
      infatuation: {
        label: 'The Infatuation',
        items: ['Rocka Rolla', 'The Commodore', "Turkey's Nest", "Clem's", 'R Bar', "Duff's Brooklyn", 'Skinny Dennis', "Sharlene's", "Pete's Candy Store", 'Boobie Trap'],
      },
      timeout: {
        label: 'Time Out New York',
        items: ['The Commodore', 'Skinny Dennis', "Turkey's Nest", 'Rocka Rolla', 'R Bar', "Duff's Brooklyn", "Sharlene's", "Clem's", 'Boobie Trap', "Pete's Candy Store"],
      },
      vinepair: {
        label: 'VinePair 20 Best',
        items: ["Duff's Brooklyn", 'The Commodore', "Turkey's Nest", 'Skinny Dennis', 'Rocka Rolla', "Sharlene's", "Clem's", "Pete's Candy Store", 'R Bar', 'Boobie Trap'],
      },
    },
    vote: {
      items: ['The Commodore', "Turkey's Nest", 'Skinny Dennis', 'Rocka Rolla', "Duff's Brooklyn", "Sharlene's", "Clem's", "Pete's Candy Store", 'R Bar', 'Boobie Trap'],
    },
  },
  {
    id: 'dive-bars-greenpoint',
    publishedDate: '2026-05-26',
    title: 'Best Dive Bars in Greenpoint',
    category: 'Greenpoint, Brooklyn',
    type: 'stores',
    tags: ['bars', 'nightlife', 'food-drink', 'stores', 'entertainment'],
    linkType: 'mapsCity',
    blurb: 'Pinball machines, jello shots, and the Polish bar crawls that put Greenpoint on the map. Where the G train regulars roost.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'Consensus AI',
        items: ['Black Rabbit', 'Sunshine Laundromat & Pinball', 'Lake Street', 'The Drift', "Temkin's Bar", 'Broken Land', 'The Capri Social Club', 'Palace Cafe', 'The Moonlight Mile', "Connie O's Pub"],
      },
      infatuation: {
        label: 'The Infatuation',
        items: ['Lake Street', 'Sunshine Laundromat & Pinball', 'Black Rabbit', 'Broken Land', 'The Drift', "Temkin's Bar", 'Palace Cafe', "Connie O's Pub", 'The Capri Social Club', 'The Moonlight Mile'],
      },
      yelp: {
        label: 'Yelp Top 10',
        items: ["Temkin's Bar", 'A Bar', 'Broken Land', 'Lake Street', 'The Drift', 'The Capri Social Club', 'Sunshine Laundromat & Pinball', 'The Moonlight Mile', 'Oak and Iron', 'Black Rabbit'],
      },
      timeout: {
        label: 'Time Out New York',
        items: ['Black Rabbit', 'Sunshine Laundromat & Pinball', 'The Drift', 'Lake Street', "Temkin's Bar", 'Palace Cafe', 'Broken Land', "Connie O's Pub", 'The Capri Social Club', 'The Moonlight Mile'],
      },
    },
    vote: {
      items: ['Black Rabbit', 'Sunshine Laundromat & Pinball', 'Lake Street', "Temkin's Bar", 'The Drift', 'Broken Land', 'Palace Cafe', 'The Capri Social Club', "Connie O's Pub", 'The Moonlight Mile'],
    },
  },
  {
    id: 'dive-bars-east-village',
    publishedDate: '2026-05-26',
    title: 'Best Dive Bars in the East Village',
    category: 'East Village',
    type: 'stores',
    tags: ['bars', 'nightlife', 'food-drink', 'stores', 'entertainment'],
    linkType: 'mapsCity',
    blurb: "McSorley's since 1854. Lucy's reborn. The grit and grime that gave New York nightlife its reputation.",
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'Consensus AI',
        items: ["McSorley's Old Ale House", "Lucy's", 'Holiday Cocktail Lounge', 'Tile Bar', "Sophie's", 'KGB Bar', 'Blue & Gold Tavern', 'Cherry Tavern', "Mona's", "Milano's Bar"],
      },
      infatuation: {
        label: 'The Infatuation',
        items: ["Lucy's", 'Holiday Cocktail Lounge', "McSorley's Old Ale House", 'Tile Bar', "Sophie's", 'KGB Bar', 'Blue & Gold Tavern', "Mona's", 'Cherry Tavern', "Milano's Bar"],
      },
      vinepair: {
        label: 'VinePair 20 Best',
        items: ["Sophie's", "McSorley's Old Ale House", 'Holiday Cocktail Lounge', "Lucy's", 'Blue & Gold Tavern', 'Tile Bar', 'KGB Bar', "Mona's", "Milano's Bar", 'Cherry Tavern'],
      },
      timeout: {
        label: 'Time Out New York',
        items: ["McSorley's Old Ale House", 'Holiday Cocktail Lounge', "Lucy's", 'Tile Bar', "Sophie's", 'Blue & Gold Tavern', 'KGB Bar', "Milano's Bar", "Mona's", 'Cherry Tavern'],
      },
    },
    vote: {
      items: ["McSorley's Old Ale House", "Lucy's", 'Holiday Cocktail Lounge', 'Tile Bar', "Sophie's", 'KGB Bar', 'Blue & Gold Tavern', "Mona's", "Milano's Bar", 'Cherry Tavern'],
    },
  },
  {
    id: 'dive-bars-greenwich-village',
    publishedDate: '2026-05-26',
    title: 'Best Dive Bars in Greenwich Village',
    category: 'Greenwich Village',
    type: 'stores',
    tags: ['bars', 'nightlife', 'food-drink', 'stores', 'entertainment'],
    linkType: 'mapsCity',
    blurb: 'Where the Beats drank. Where Dylan sang. Time-capsule bars on the same blocks as Bleecker Street tourists.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'Consensus AI',
        items: ['Kettle of Fish', 'Down the Hatch', "Johnny's Bar", "Julius'", 'The Four-Faced Liar', 'Peculier Pub', 'Bleecker Street Bar', 'The Library', 'PubKey', 'Fish Bar'],
      },
      eater: {
        label: 'Eater NY 25 Best',
        items: ["Johnny's Bar", "Julius'", 'Kettle of Fish', 'Down the Hatch', 'The Four-Faced Liar', 'Bleecker Street Bar', 'Peculier Pub', 'The Library', 'PubKey', 'Fish Bar'],
      },
      yelp: {
        label: 'Yelp Top 10',
        items: ['124 Old Rabbit Club', 'The Four-Faced Liar', 'PubKey', 'Wide Shut', 'Beltane', 'The Library', 'Peculier Pub', 'Park Bar', "Johnny's Bar", 'Bleecker Street Bar'],
      },
      timeout: {
        label: 'Time Out New York',
        items: ['Kettle of Fish', "Johnny's Bar", "Julius'", 'Down the Hatch', 'The Four-Faced Liar', 'Bleecker Street Bar', 'The Library', 'Peculier Pub', 'PubKey', 'Fish Bar'],
      },
    },
    vote: {
      items: ['Kettle of Fish', "Johnny's Bar", 'Down the Hatch', "Julius'", 'The Four-Faced Liar', 'Peculier Pub', 'Bleecker Street Bar', 'The Library', 'PubKey', 'Fish Bar'],
    },
  },
  {
    id: 'dive-bars-cape-cod',
    publishedDate: '2026-05-26',
    title: 'Best Dive Bars on Cape Cod',
    category: 'Cape Cod',
    type: 'stores',
    tags: ['bars', 'nightlife', 'food-drink', 'stores', 'entertainment', 'travel'],
    linkType: 'mapsCity',
    blurb: 'Where the locals drink when the summer crowds clear out. Old Colony in P-town, the 19th Hole in Hyannis since 1930, and the Fox Hole patron saint of Osterville.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'Consensus AI',
        items: ['Old Colony Tap (Provincetown)', '19th Hole Tavern (Hyannis)', 'The Fox Hole (Osterville)', 'Bomb Shelter (Wellfleet)', 'The Underground (Provincetown)', 'Chatham Squire (Chatham)', "Sundancer's (West Dennis)", 'Quarterdeck Lounge (Hyannis)', 'Duck Inn Pub (Hyannis)', 'Four Point Tavern (Hyannis)'],
      },
      capecodchamber: {
        label: 'Cape Cod Chamber',
        items: ['Old Colony Tap (Provincetown)', '19th Hole Tavern (Hyannis)', 'The Fox Hole (Osterville)', 'Bomb Shelter (Wellfleet)', "Sundancer's (West Dennis)", 'Chatham Squire (Chatham)', 'The Underground (Provincetown)', 'Quarterdeck Lounge (Hyannis)', 'Duck Inn Pub (Hyannis)', 'Four Point Tavern (Hyannis)'],
      },
      yelp: {
        label: 'Yelp Top Picks',
        items: ['Old Colony Tap (Provincetown)', 'The Underground (Provincetown)', '19th Hole Tavern (Hyannis)', 'Bomb Shelter (Wellfleet)', 'The Fox Hole (Osterville)', 'Chatham Squire (Chatham)', "Sundancer's (West Dennis)", 'Quarterdeck Lounge (Hyannis)', 'Duck Inn Pub (Hyannis)', 'Four Point Tavern (Hyannis)'],
      },
      vacationcapecod: {
        label: 'Vacation Cape Cod',
        items: ['Old Colony Tap (Provincetown)', 'The Underground (Provincetown)', 'Chatham Squire (Chatham)', 'The Fox Hole (Osterville)', '19th Hole Tavern (Hyannis)', 'Bomb Shelter (Wellfleet)', "Sundancer's (West Dennis)", 'Quarterdeck Lounge (Hyannis)', 'Duck Inn Pub (Hyannis)', 'Four Point Tavern (Hyannis)'],
      },
    },
    vote: {
      items: ['Old Colony Tap (Provincetown)', '19th Hole Tavern (Hyannis)', 'The Fox Hole (Osterville)', 'The Underground (Provincetown)', 'Bomb Shelter (Wellfleet)', 'Chatham Squire (Chatham)', "Sundancer's (West Dennis)", 'Quarterdeck Lounge (Hyannis)', 'Duck Inn Pub (Hyannis)', 'Four Point Tavern (Hyannis)'],
    },
  },
  {
    id: 'cocktails-west-village',
    publishedDate: '2026-05-26',
    title: 'Best Cocktail Bars in the West Village',
    category: 'West Village',
    type: 'stores',
    tags: ['bars', 'nightlife', 'food-drink', 'stores', 'entertainment'],
    linkType: 'mapsCity',
    blurb: "Dante set the standard when it was named World's Best. Bandits, Little Branch, and Katana Kitten kept the pressure on.",
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'Consensus AI',
        items: ['Dante', 'Bandits', 'Little Branch', 'Katana Kitten', 'Employees Only', 'Bar Pisellino', "Angel's Share", 'Sip & Guzzle', 'Bobo', 'Analogue'],
      },
      infatuation: {
        label: 'The Infatuation 20 Best',
        items: ['Dante', 'Katana Kitten', "Angel's Share", 'Sip & Guzzle', 'Bar Pisellino', 'Little Branch', 'Employees Only', 'Bandits', 'Bobo', 'Binx'],
      },
      timeout: {
        label: 'Time Out 14 Best',
        items: ['Dante', 'Bandits', 'Little Branch', 'Employees Only', 'Bar Pisellino', 'Katana Kitten', "Angel's Share", 'Analogue', 'Bobo', 'Sip & Guzzle'],
      },
      worlds50best: {
        label: "World's 50 Best Bars",
        items: ['Dante', "Angel's Share", 'Katana Kitten', 'Sip & Guzzle', 'Employees Only', 'Little Branch', 'Bar Pisellino', 'Bandits', 'Analogue', 'Bobo'],
      },
    },
    vote: {
      items: ['Dante', 'Bandits', 'Little Branch', 'Katana Kitten', 'Employees Only', 'Bar Pisellino', "Angel's Share", 'Sip & Guzzle', 'Analogue', 'Bobo'],
    },
  },
  {
    id: 'cocktails-soho',
    publishedDate: '2026-05-26',
    title: 'Best Cocktail Bars in SoHo',
    category: 'SoHo',
    type: 'stores',
    tags: ['bars', 'nightlife', 'food-drink', 'stores', 'entertainment'],
    linkType: 'mapsCity',
    blurb: "Hotel hideouts, micro bars tucked above home goods stores, and the speakeasies that survived the neighborhood's gallery-to-luxury pivot.",
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'Consensus AI',
        items: ['South Soho Bar', "Sloane's", "Milady's", 'Guild Bar', 'La Compagnie des Vins Surnaturels', 'Kabin', 'Foxtail', 'The Ship', 'Grand Bar', 'Broome Street Bar'],
      },
      infatuation: {
        label: 'The Infatuation 12 Best',
        items: ['South Soho Bar', "Milady's", 'Guild Bar', 'La Compagnie des Vins Surnaturels', 'Broome Street Bar', 'Kabin', "Sloane's", 'Foxtail', 'The Ship', 'Grand Bar'],
      },
      timeout: {
        label: 'Time Out New York',
        items: ["Sloane's", 'Kabin', 'South Soho Bar', "Milady's", 'Grand Bar', 'Foxtail', 'Guild Bar', 'La Compagnie des Vins Surnaturels', 'The Ship', 'Broome Street Bar'],
      },
      sohoweekly: {
        label: 'SoHo Weekly 15 Best',
        items: ["Sloane's", 'Grand Bar', 'South Soho Bar', "Milady's", 'Kabin', 'Guild Bar', 'Foxtail', 'La Compagnie des Vins Surnaturels', 'The Ship', 'Broome Street Bar'],
      },
    },
    vote: {
      items: ['South Soho Bar', "Sloane's", "Milady's", 'Kabin', 'Guild Bar', 'Grand Bar', 'Foxtail', 'La Compagnie des Vins Surnaturels', 'The Ship', 'Broome Street Bar'],
    },
  },
  {
    id: 'ramen-tokyo',
    publishedDate: '2026-05-24',
    title: 'Best Ramen Shops in Tokyo',
    category: 'Tokyo',
    type: 'stores',
    tags: ['food', 'food-drink', 'stores', 'travel'],
    linkType: 'mapsCity',
    blurb: 'Michelin-starred broth versus the bowls locals queue an hour for.',
    defaultSource: 'ai',
    sources: {
      ai: { label: 'Consensus AI', items: ['Tsuta', 'Nakiryu', 'Konjiki Hototogisu', 'Afuri', 'Rokurinsha', 'Mensho', 'Menya Musashi', 'Ginza Kagari', 'Ippudo', 'Ramen Jiro'] },
      michelin: { label: 'Michelin Guide Tokyo', items: ['Nakiryu', 'Tsuta', 'Konjiki Hototogisu', 'Ginza Kagari', 'Soranoiro', 'Mensho', 'Afuri', 'Menya Itto', 'Ramen Tatsunoya', 'Rokurinsha'] },
      timeout: { label: 'Time Out Tokyo', items: ['Afuri', 'Ichiran', 'Mensho', 'Konjiki Hototogisu', 'Rokurinsha', 'Tsuta', 'Ramen Jiro', 'Menya Musashi', 'Ippudo', 'Ginza Kagari'] },
    },
    vote: { items: ['Ichiran', 'Konjiki Hototogisu', 'Afuri', 'Tsuta', 'Mensho', 'Ginza Kagari', 'Rokurinsha', 'Ippudo', 'Nakiryu', 'Menya Musashi'] },
  },  {
    id: 'breakfast-sandwiches-hamptons',
    publishedDate: '2026-05-26',
    title: 'Best Breakfast Sandwiches in the Hamptons',
    category: 'The Hamptons',
    type: 'stores',
    tags: ['food', 'food-drink', 'stores', 'travel'],
    linkType: 'mapsCity',
    blurb: "The BEC reigns from Montauk to Westhampton. Goldberg's hobo, Carissa's sourdough upgrade, and Cove's triple bypass. Where the East End starts its mornings.",
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'Consensus AI',
        items: ["Carissa's The Bakery (East Hampton)", "Goldberg's Famous Bagels (Multiple Locations)", 'Cove Delicatessen (Sag Harbor)', 'Bonfire Coffeehouse (East Hampton)', "Cromer's Market (Noyac)", 'Hampton Kitchen Delicatessen (Water Mill)', 'Golden Pear Cafe (Multiple Locations)', 'Harbor Market & Kitchen (Sag Harbor)', 'John Papas Cafe (East Hampton)', "Damark's Market (East Hampton)"],
      },
      southforker: {
        label: 'Southforker',
        items: ['Bonfire Coffeehouse (East Hampton)', "Goldberg's Famous Bagels (Multiple Locations)", 'Cove Delicatessen (Sag Harbor)', 'Hampton Kitchen Delicatessen (Water Mill)', "Carissa's The Bakery (East Hampton)", "Cromer's Market (Noyac)", 'Harbor Market & Kitchen (Sag Harbor)', "Damark's Market (East Hampton)", 'Golden Pear Cafe (Multiple Locations)', 'John Papas Cafe (East Hampton)'],
      },
      purewow: {
        label: 'PureWow',
        items: ["Carissa's The Bakery (East Hampton)", "Goldberg's Famous Bagels (Multiple Locations)", 'Harbor Market & Kitchen (Sag Harbor)', 'Golden Pear Cafe (Multiple Locations)', 'Bonfire Coffeehouse (East Hampton)', 'Sant Ambroeus (Southampton)', "Cromer's Market (Noyac)", 'Cove Delicatessen (Sag Harbor)', 'Hampton Kitchen Delicatessen (Water Mill)', 'John Papas Cafe (East Hampton)'],
      },
      yelp: {
        label: 'Yelp Top 10',
        items: ['Bonfire Coffeehouse (East Hampton)', "Goldberg's Famous Bagels (Multiple Locations)", "Carissa's The Bakery (East Hampton)", 'Cove Delicatessen (Sag Harbor)', 'John Papas Cafe (East Hampton)', "Damark's Market (East Hampton)", 'Hampton Chutney (East Hampton)', 'Golden Pear Cafe (Multiple Locations)', "Cromer's Market (Noyac)", 'Harbor Market & Kitchen (Sag Harbor)'],
      },
    },
    vote: {
      items: ["Carissa's The Bakery (East Hampton)", "Goldberg's Famous Bagels (Multiple Locations)", 'Bonfire Coffeehouse (East Hampton)', 'Cove Delicatessen (Sag Harbor)', "Cromer's Market (Noyac)", 'Hampton Kitchen Delicatessen (Water Mill)', 'Golden Pear Cafe (Multiple Locations)', 'Harbor Market & Kitchen (Sag Harbor)', 'John Papas Cafe (East Hampton)', "Damark's Market (East Hampton)"],
    },
  },  /* ----- PRODUCT ----- */
  {
    id: 'headphones-overear',
    publishedDate: '2026-05-26',
    title: 'Best Over-Ear Headphones',
    category: 'Audio',
    type: 'product',
    tags: ['tech', 'product'],
    linkType: 'amazon',
    blurb: 'Noise-cancellers, audiophile cans, and the budget pairs that punch above their price.',
    defaultSource: 'ai',
    links: {
      'Sony WH-1000XM6': 'https://amzn.to/4e3OsIg',
      'Bose QuietComfort Ultra Headphones': 'https://amzn.to/3RtlzMR',
      'Apple AirPods Max': 'https://amzn.to/4fFFeD9',
      'Bowers & Wilkins Px7 S3': 'https://amzn.to/3Q1zpWj',
      'Sennheiser HDB 630': 'https://amzn.to/4f7tb1k',
      'Sonos Ace': 'https://amzn.to/43uZGzm',
      'Focal Bathys': 'https://amzn.to/42QncXv',
      'Bose QuietComfort Headphones': 'https://amzn.to/4v1fzcK',
      'JBL Tour One M3': 'https://amzn.to/4uzFIzA',
    },
    sources: {
      ai: { label: 'Consensus AI', items: ['Sony WH-1000XM6', 'Bose QuietComfort Ultra Headphones', 'Sennheiser MOMENTUM 4 Wireless', 'Apple AirPods Max', 'Bowers & Wilkins Px7 S3', 'Sennheiser HDB 630', 'Sonos Ace', 'Focal Bathys', 'Bose QuietComfort Headphones', 'JBL Tour One M3'] },
      whathifi: { label: 'What Hi-Fi? 2026', items: ['Sony WH-1000XM6', 'Bowers & Wilkins Px7 S3', 'Sennheiser HDB 630', 'Bose QuietComfort Ultra Headphones', 'Apple AirPods Max', 'Focal Bathys Mg', 'Beyerdynamic DT 990 Pro X', 'Sennheiser HD 505', 'Bose QuietComfort Headphones', 'Sennheiser MOMENTUM 4 Wireless'] },
      cnn: { label: 'CNN Underscored', items: ['Sony WH-1000XM6', 'Bose QuietComfort Ultra Headphones', 'EarFun Tune Pro', 'Sennheiser MOMENTUM 4 Wireless', 'Sonos Ace', 'Apple AirPods Max', 'Bose QuietComfort Headphones', 'Anker Soundcore Space Q45', 'JBL Tour One M3', 'Bowers & Wilkins Px7 S3'] },
      rtings: { label: 'RTINGS.com', items: ['Sony WH-1000XM6', 'Bose QuietComfort Ultra Headphones', 'Audeze Maxwell', 'Sennheiser HDB 630', 'Sennheiser MOMENTUM 4 Wireless', 'Anker Soundcore Space Q45', 'Sony WH-1000XM5', 'Sony WH-1000XM4', 'Razer BlackShark V3 Pro', 'Anker Soundcore Life Q20'] },
      soundguys: { label: 'SoundGuys', items: ['Sony WH-1000XM6', 'Sennheiser MOMENTUM 4 Wireless', 'Bose QuietComfort Ultra Headphones', 'JBL Tour One M3', 'Focal Bathys', 'Apple AirPods Max', 'Bowers & Wilkins Px7 S3', 'JLab JBuds Lux ANC', 'Sennheiser HDB 630', 'Anker Soundcore Space Q45'] },
    },
    vote: { items: ['Sony WH-1000XM6', 'Sennheiser MOMENTUM 4 Wireless', 'Bose QuietComfort Ultra Headphones', 'Audeze Maxwell', 'Focal Bathys', 'Bowers & Wilkins Px7 S3', 'Apple AirPods Max', 'Sonos Ace', 'Anker Soundcore Space Q45', 'Beyerdynamic DT 990 Pro X'] },
  },
  {
    id: 'home-espresso-machines',
    publishedDate: '2026-05-27',
    title: 'Best Home Espresso Machines',
    category: 'Coffee',
    type: 'product',
    tags: ['tech', 'product'],
    linkType: 'amazon',
    blurb: 'The dream machines. Hand-built dual boilers, saturated commercial groups, and the prosumer flagships that turn a kitchen counter into a proper cafe bar. Ranked by which is nicest, not which is the best deal.',
    defaultSource: 'ai',
    links: {
      'Rancilio Silvia Pro X': 'https://amzn.to/3RxwVzp',
      'Breville Oracle Dual Boiler': 'https://amzn.to/4fIkivi',
    },
    sources: {
      ai: {
        label: 'Consensus AI',
        items: ['La Marzocco GS3', 'La Marzocco Linea Mini', 'Slayer Single Group', 'ECM Synchronika', 'Rocket R58', 'Lelit Bianca V3', 'Profitec Pro 700', 'Breville Oracle Dual Boiler', 'Rancilio Silvia Pro X', 'Rocket Appartamento'],
      },
      seattlecoffeegear: {
        label: 'Seattle Coffee Gear High-End 2026',
        items: ['La Marzocco Linea Mini', 'La Marzocco GS3', 'ECM Synchronika', 'Profitec Pro 700', 'Lelit Bianca V3', 'Rocket R58', 'Slayer Single Group', 'Profitec Pro 600', 'Rocket Appartamento', 'Lelit Elizabeth'],
      },
      cliffandpebble: {
        label: 'Cliff & Pebble Prosumer 2026',
        items: ['Lelit Bianca V3', 'Rocket R58', 'Profitec Pro 700', 'ECM Synchronika', 'La Marzocco Linea Mini', 'La Marzocco GS3', 'Slayer Single Group', 'LUCCA A53 Mini', 'Rancilio Silvia Pro X', 'Profitec Pro 600'],
      },
      homegrounds: {
        label: 'HomeGrounds 2026',
        items: ['La Marzocco GS3', 'Slayer Single Group', 'ECM Synchronika', 'Lelit Bianca V3', 'Rocket R58', 'La Marzocco Linea Mini', 'Profitec Pro 700', 'Rancilio Silvia Pro X', 'Rocket Appartamento', 'Breville Oracle Dual Boiler'],
      },
      wholelattelove: {
        label: 'Whole Latte Love 2026',
        items: ['ECM Synchronika', 'Profitec Pro 700', 'La Marzocco GS3', 'Rocket R58', 'Lelit Bianca V3', 'La Marzocco Linea Mini', 'Slayer Single Group', 'ECM Mechanika', 'Rocket Mozzafiato', 'Profitec Pro 600'],
      },
    },
    vote: {
      items: ['La Marzocco Linea Mini', 'La Marzocco GS3', 'Lelit Bianca V3', 'ECM Synchronika', 'Rocket R58', 'Profitec Pro 700', 'Slayer Single Group', 'Rocket Appartamento', 'Rancilio Silvia Pro X', 'Breville Oracle Dual Boiler'],
    },
  },

  /* ----- FOOD & DRINK (vote-only) ----- */
  {
    id: 'alani-nu-flavors',
    publishedDate: '2026-05-25',
    title: 'Best Alani Nu Energy Flavors',
    category: 'Drinks',
    type: 'food',
    tags: ['food', 'food-drink', 'product'],
    linkType: 'amazon',
    mode: 'votes',
    blurb: 'Every Alani Nu energy flavor, ranked by you. Loose expert order to start, your votes take it from there.',
    defaultSource: 'ai',
    vote: { items: ["Witch's Brew", 'Breezeberry', 'Cosmic Stardust', 'Hawaiian Shaved Ice', 'Juicy Peach', 'Mimosa', 'Tropsicle', 'Watermelon Wave', 'Cherry Slush', 'Munchies'] },
  },
  {
    id: 'prestigious-boarding-schools',
    publishedDate: '2026-05-26',
    title: 'Most Prestigious Boarding Schools in the US',
    category: 'Education',
    type: 'other',
    tags: ['luxury', 'other'],
    linkType: 'wiki',
    blurb: 'The schools that feed the Ivy League, shape future presidents, and charge $70K a year for the privilege. Harkness tables, Gothic quads, and admissions rates that rival Harvard.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'Consensus AI',
        items: ['Phillips Exeter Academy', 'Phillips Academy Andover', 'The Hotchkiss School', 'Groton School', "St. Paul's School", 'Choate Rosemary Hall', 'The Lawrenceville School', 'Deerfield Academy', 'Milton Academy', 'Cate School'],
      },
      niche: {
        label: 'Niche 2026 Best Boarding Schools',
        items: ['The Hotchkiss School', 'Phillips Exeter Academy', 'Choate Rosemary Hall', 'The Lawrenceville School', 'Groton School', 'Phillips Academy Andover', "St. Paul's School", 'Cate School', 'Deerfield Academy', 'Milton Academy'],
      },
      admissionsight: {
        label: 'AdmissionSight Top 10',
        items: ['Phillips Exeter Academy', 'Phillips Academy Andover', 'Choate Rosemary Hall', 'The Lawrenceville School', 'Groton School', "St. Paul's School", 'Deerfield Academy', 'Cate School', 'The Hotchkiss School', 'Milton Academy'],
      },
      findingschool: {
        label: 'FindingSchool 2026',
        items: ['Phillips Academy Andover', 'Phillips Exeter Academy', 'The Lawrenceville School', 'Deerfield Academy', 'Choate Rosemary Hall', 'The Hotchkiss School', "St. Paul's School", 'Groton School', 'Middlesex School', 'The Taft School'],
      },
    },
    vote: {
      items: ['Phillips Exeter Academy', 'Phillips Academy Andover', 'Groton School', 'The Hotchkiss School', "St. Paul's School", 'Choate Rosemary Hall', 'Deerfield Academy', 'The Lawrenceville School', 'Milton Academy', 'Cate School'],
    },
  },
  {
    id: 'three-martini-lunch-manhattan',
    publishedDate: '2026-05-26',
    title: 'Best Three-Martini Weekday Lunches in Manhattan',
    category: 'New York',
    type: 'stores',
    tags: ['food', 'food-drink', 'bars', 'stores', 'luxury'],
    linkType: 'mapsCity',
    blurb: 'The power lunch never died, it just moved tables. Where to order a gin martini at noon on a Tuesday and nobody blinks. Steak, tablecloths, and a cab home.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'Consensus AI',
        items: ['The Grill', 'Torrisi Bar & Restaurant', "Dowling's at The Carlyle", 'La Marchande', 'Carbone', 'Balthazar', 'The Polo Bar', 'Ci Siamo', 'Smith & Wollensky', 'King'],
      },
      resy: {
        label: 'Resy Power Lunch Guide 2025',
        items: ["Dowling's at The Carlyle", 'Time and Tide', 'Le Coucou', 'King', "L'Artusi", 'Ci Siamo', 'La Marchande', 'Avra Estiatorio', 'Le Crocodile', 'Manuela'],
      },
      infatuation: {
        label: 'The Infatuation',
        items: ['Torrisi Bar & Restaurant', 'Ci Siamo', 'Carbone', 'The Grill', 'Balthazar', "Raoul's", 'King', "Dowling's at The Carlyle", "L'Artusi", 'Smith & Wollensky'],
      },
      robbreport: {
        label: "Robb Report · Gentleman's Journal",
        items: ['The Grill', "Coco's", "Raf's", 'Torrisi Bar & Restaurant', 'Carbone', "Michael's", 'La Marchande', 'The Polo Bar', 'Balthazar', "Dowling's at The Carlyle"],
      },
    },
    vote: {
      items: ['Torrisi Bar & Restaurant', 'The Grill', 'Carbone', 'Balthazar', "Dowling's at The Carlyle", 'Smith & Wollensky', 'La Marchande', 'The Polo Bar', 'Ci Siamo', 'King'],
    },
  },
  /* ----- TECH PRODUCTS ----- */
  {
    id: 'travel-monitors',
    publishedDate: '2026-05-27',
    title: 'Best Travel Computer Monitor',
    category: 'Tech',
    type: 'product',
    tags: ['tech', 'product'],
    linkType: 'amazon',
    blurb: 'The nicest portable displays you can pack in a laptop bag. OLED panels, true 4K resolution, and aircraft-grade aluminum builds, ranked by outright quality rather than price.',
    defaultSource: 'ai',
    links: {
      'Espresso Display 15 Touch': 'https://amzn.to/4uwq87F',
      'INNOCN 13K1F (13.3" OLED)': 'https://amzn.to/3PEJEQn',
      'INNOCN PU15-Pre': 'https://amzn.to/3RwQbx2',
      'LG gram + View': 'https://amzn.to/4vbOBPy',
      'ASUS ROG Strix XG17AHPE': 'https://amzn.to/4e8K6zu',
      'ViewSonic VX1655-4K-OLED': 'https://amzn.to/3RoR0bg',
      'ASUS ZenScreen Touch (MB16AMT)': 'https://amzn.to/3PRb1GK',
      'Espresso 17 Pro': 'https://amzn.to/4u3E4Fk',
      'Lenovo ThinkVision M14t': 'https://amzn.to/4vb7UZl',
    },
    sources: {
      ai: {
        label: 'Consensus AI',
        items: ['ViewSonic VX1655-4K-OLED', 'ViewSonic VP16-OLED', 'Espresso Display 15 Touch', 'Espresso 17 Pro', 'INNOCN 13K1F (13.3" OLED)', 'INNOCN PU15-Pre', 'ASUS ROG Strix XG17AHPE', 'LG gram + View', 'Lenovo ThinkVision M14t', 'ASUS ZenScreen Touch (MB16AMT)'],
      },
      rtings: {
        label: 'RTINGS 2026',
        items: ['ViewSonic VX1655-4K-OLED', 'Espresso Display 15 Touch', 'INNOCN 13K1F (13.3" OLED)', 'ViewSonic VP16-OLED', 'ASUS ROG Strix XG17AHPE', 'Espresso 17 Pro', 'INNOCN PU15-Pre'],
      },
      tomshardware: {
        label: "Tom's Hardware 2026",
        items: ['Espresso 17 Pro', 'ViewSonic VX1655-4K-OLED', 'INNOCN PU15-Pre', 'Espresso Display 15 Touch', 'ViewSonic VP16-OLED', 'ASUS ZenScreen Touch (MB16AMT)', 'INNOCN 13K1F (13.3" OLED)', 'LG gram + View'],
      },
      pcworld: {
        label: 'PCWorld 2026',
        items: ['ViewSonic VX1655-4K-OLED', 'Espresso Display 15 Touch', 'ViewSonic VP16-OLED', 'INNOCN 13K1F (13.3" OLED)', 'Espresso 17 Pro', 'LG gram + View', 'ASUS ROG Strix XG17AHPE'],
      },
      engadget: {
        label: 'Engadget 2026',
        items: ['Espresso Display 15 Touch', 'ViewSonic VX1655-4K-OLED', 'INNOCN PU15-Pre', 'ViewSonic VP16-OLED', 'Espresso 17 Pro', 'ASUS ZenScreen Touch (MB16AMT)', 'Lenovo ThinkVision M14t'],
      },
    },
    vote: {
      items: ['ViewSonic VX1655-4K-OLED', 'Espresso Display 15 Touch', 'ViewSonic VP16-OLED', 'INNOCN 13K1F (13.3" OLED)', 'Espresso 17 Pro', 'INNOCN PU15-Pre', 'ASUS ROG Strix XG17AHPE', 'LG gram + View', 'Lenovo ThinkVision M14t', 'ASUS ZenScreen Touch (MB16AMT)'],
    },
  },
  {
    id: 'thailand-beachfront-hotels',
    publishedDate: '2026-05-27',
    title: 'Best Beachfront Hotels and Resorts in Thailand',
    category: 'Travel',
    type: 'travel',
    tags: ['travel', 'luxury', 'stores'],
    linkType: 'mapsCity',
    blurb: 'Private pools, limestone karsts, and turquoise waters. The Andaman Sea and Gulf of Siam are home to Thailand\'s most coveted beachfront sanctuaries.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'Consensus AI',
        items: [
          'Amanpuri (Phuket)',
          'Trisara (Phuket)',
          'Six Senses Yao Noi (Phang Nga)',
          'Phulay Bay, a Ritz-Carlton Reserve (Krabi)',
          'Rosewood Phuket',
          'Four Seasons Resort Koh Samui',
          'Rayavadee (Krabi)',
          'Soneva Kiri (Koh Kood)',
          'Six Senses Samui (Koh Samui)',
          'Keemala (Phuket)',
        ],
      },
      tripcom: {
        label: 'Trip.com Best Luxury Hotels',
        items: [
          'Four Seasons Resort Koh Samui',
          'Amanpuri (Phuket)',
          'Trisara (Phuket)',
          'Six Senses Yao Noi (Phang Nga)',
          'Rosewood Phuket',
          'Andara Resort & Villas (Phuket)',
          'Keemala (Phuket)',
          'Phulay Bay, a Ritz-Carlton Reserve (Krabi)',
          'Sri Panwa (Phuket)',
          'Banyan Tree Krabi',
        ],
      },
      michelin: {
        label: 'Michelin Key Hotels',
        items: [
          'Amanpuri (Phuket)',
          'Phulay Bay, a Ritz-Carlton Reserve (Krabi)',
          'Six Senses Yao Noi (Phang Nga)',
          'Six Senses Samui (Koh Samui)',
          'Banyan Tree Samui (Koh Samui)',
          'Keemala (Phuket)',
          'Samujana Villas (Koh Samui)',
          'The Sarojin (Phang Nga)',
          'Napasai (Koh Samui)',
          'Cape Fahn Hotel (Koh Samui)',
        ],
      },
      luxuryexpert: {
        label: 'Luxury Travel Expert',
        items: [
          'Soneva Kiri (Koh Kood)',
          'Six Senses Yao Noi (Phang Nga)',
          'Rayavadee (Krabi)',
          'Trisara (Phuket)',
          'Amanpuri (Phuket)',
          'Banyan Tree Samui (Koh Samui)',
          'Four Seasons Resort Koh Samui',
          'Anantara Rasananda (Koh Phangan)',
          'Cape Fahn Hotel (Koh Samui)',
          'Rosewood Phuket',
        ],
      },
      hotelguru: {
        label: 'The Hotel Guru',
        items: [
          'Trisara (Phuket)',
          'Amanpuri (Phuket)',
          'Six Senses Yao Noi (Phang Nga)',
          'Rosewood Phuket',
          'Keemala (Phuket)',
          'Sri Panwa (Phuket)',
          'Six Senses Samui (Koh Samui)',
          'Rayavadee (Krabi)',
          'Cape Fahn Hotel (Koh Samui)',
          'Soneva Kiri (Koh Kood)',
        ],
      },
    },
    vote: {
      items: [
        'Amanpuri (Phuket)',
        'Trisara (Phuket)',
        'Six Senses Yao Noi (Phang Nga)',
        'Phulay Bay, a Ritz-Carlton Reserve (Krabi)',
        'Rosewood Phuket',
        'Four Seasons Resort Koh Samui',
        'Rayavadee (Krabi)',
        'Soneva Kiri (Koh Kood)',
        'Six Senses Samui (Koh Samui)',
        'Keemala (Phuket)',
      ],
    },
  },
  {
    id: 'sec-dive-bars',
    publishedDate: '2026-05-27',
    title: 'Best SEC Dive Bars',
    category: 'Travel',
    type: 'travel',
    tags: ['bars', 'nightlife', 'food-drink', 'stores', 'entertainment', 'travel'],
    blurb: 'Game day tradition in the South. Cheap wings, neon beer signs, and decades of Gator, Tiger, and Bulldog memories.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'Consensus AI',
        items: [
          "The Houndstooth (Alabama)",
          "SkyBar Cafe (Auburn)",
          "Sideways (Arkansas)",
          "Fred's Bar (LSU)",
          "The Chimes (LSU)",
          "The Globe (Georgia)",
          "Two Keys Tavern (Kentucky)",
          "Dixie Chicken (Texas A&M)",
          "The Half Barrel (Tennessee)",
          "Walk-On's Sports Bistreaux (LSU)",
        ],
      },
      secrant: {
        label: 'SEC Rant',
        items: [
          "The Houndstooth (Alabama)",
          "Sideways (Arkansas)",
          "Dave's Dark Horse Tavern (Mississippi State)",
          "The Chimes (LSU)",
          "Flying Saucer (Vanderbilt)",
          "The Whig (South Carolina)",
          "Chimy's (Texas A&M)",
          "The Globe (Georgia)",
          "Two Keys Tavern (Kentucky)",
          "Harry's Bar (Alabama)",
        ],
      },
      saturdaydownsouth: {
        label: 'Saturday Down South',
        items: [
          "The Houndstooth (Alabama)",
          "Sideways (Arkansas)",
          "The Chimes (LSU)",
          "Dave's Dark Horse Tavern (Mississippi State)",
          "The Globe (Georgia)",
          "Two Keys Tavern (Kentucky)",
          "Shiloh Bar & Grill (Missouri)",
          "Flying Saucer (Vanderbilt)",
          "Chimy's (Texas A&M)",
        ],
      },
      fanbuzz: {
        label: 'FanBuzz',
        items: [
          "The Houndstooth (Alabama)",
          "Quixote's (Auburn)",
          "Fred's Bar (LSU)",
          "The Chimes (LSU)",
          "Cool Beans (Tennessee)",
          "Chimy's (Texas A&M)",
          "Piranha's Bar and Grill (Vanderbilt)",
          "The Half Barrel (Tennessee)",
          "Sideways (Arkansas)",
        ],
      },
      campussports: {
        label: 'Campus Sports',
        items: [
          "SkyBar Cafe (Auburn)",
          "The Houndstooth (Alabama)",
          "Fred's Bar (LSU)",
          "Dave's Dark Horse Tavern (Mississippi State)",
          "The Half Barrel (Tennessee)",
          "Bogie's Bar (LSU)",
          "Bin 612 (Mississippi State)",
          "The Chimes (LSU)",
        ],
      },
      thetakeout: {
        label: 'The Takeout',
        items: [
          "SkyBar Cafe (Auburn)",
          "Kings Live Music (Auburn)",
          "The Houndstooth (Alabama)",
          "The Chimes (LSU)",
          "Sideways (Arkansas)",
          "The Globe (Georgia)",
          "Two Keys Tavern (Kentucky)",
          "Chimy's (Texas A&M)",
        ],
      },
    },
    vote: {
      items: [
        "The Houndstooth (Alabama)",
        "SkyBar Cafe (Auburn)",
        "Sideways (Arkansas)",
        "Fred's Bar (LSU)",
        "The Chimes (LSU)",
        "The Globe (Georgia)",
        "Two Keys Tavern (Kentucky)",
        "Dixie Chicken (Texas A&M)",
        "The Half Barrel (Tennessee)",
        "Walk-On's Sports Bistreaux (LSU)",
      ],
    },
  },
  {
    id: 'ivy-league-dive-bars',
    publishedDate: '2026-05-27',
    title: 'Best Ivy League Dive Bars',
    category: 'Travel',
    type: 'travel',
    tags: ['bars', 'nightlife', 'food-drink', 'stores', 'entertainment', 'travel'],
    blurb: 'Cheap pitchers, sticky floors, and decades of student tradition. The bars that defined every Ivy campus.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'Consensus AI',
        items: [
          "Charlie's Kitchen (Harvard)",
          "Smokey Joe's Tavern (Penn)",
          "1020 Bar (Columbia)",
          "Ivy Inn (Princeton)",
          "Graduate Center Bar (Brown)",
          "The Anchor Spa (Yale)",
          "Toad's Place (Yale)",
          "Chapter House (Cornell)",
          "Murphy's on the Green (Dartmouth)",
          "Salt Hill Pub (Dartmouth)",
        ],
      },
      yelp: {
        label: 'Yelp Top Picks Near Campus',
        items: [
          "Charlie's Kitchen (Harvard)",
          "The Dugout (Harvard)",
          "Sligo Pub (Harvard)",
          "1020 Bar (Columbia)",
          "Broadway Dive Bar (Columbia)",
          "Smokey Joe's Tavern (Penn)",
          "New Deck Tavern (Penn)",
          "Ivy Inn (Princeton)",
          "Toad's Place (Yale)",
          "Chanticleer (Cornell)",
        ],
      },
      campusvoices: {
        label: 'Campus Newspapers · Alumni Reflections',
        items: [
          "Charlie's Kitchen (Harvard)",
          "Smokey Joe's Tavern (Penn)",
          "1020 Bar (Columbia)",
          "Ivy Inn (Princeton)",
          "Graduate Center Bar (Brown)",
          "The Anchor Spa (Yale)",
          "Chapter House (Cornell)",
          "Chanticleer (Cornell)",
          "Murphy's on the Green (Dartmouth)",
          "Salt Hill Pub (Dartmouth)",
        ],
      },
      tripadvisor: {
        label: 'Tripadvisor Top-Rated',
        items: [
          "Charlie's Kitchen (Harvard)",
          "Ivy Inn (Princeton)",
          "Toad's Place (Yale)",
          "The Anchor Spa (Yale)",
          "Smokey Joe's Tavern (Penn)",
          "Murphy's on the Green (Dartmouth)",
          "Salt Hill Pub (Dartmouth)",
          "Sligo Pub (Harvard)",
          "The Dugout (Harvard)",
        ],
      },
      timeout: {
        label: 'Time Out · The Infatuation · Boston Mag',
        items: [
          "Charlie's Kitchen (Harvard)",
          "Model Cafe (Harvard)",
          "1020 Bar (Columbia)",
          "Smokey Joe's Tavern (Penn)",
          "Ivy Inn (Princeton)",
          "Graduate Center Bar (Brown)",
          "The Anchor Spa (Yale)",
          "Toad's Place (Yale)",
          "Chapter House (Cornell)",
        ],
      },
    },
    vote: {
      items: [
        "Charlie's Kitchen (Harvard)",
        "Smokey Joe's Tavern (Penn)",
        "1020 Bar (Columbia)",
        "Ivy Inn (Princeton)",
        "Graduate Center Bar (Brown)",
        "The Anchor Spa (Yale)",
        "Toad's Place (Yale)",
        "Chapter House (Cornell)",
        "Murphy's on the Green (Dartmouth)",
        "Salt Hill Pub (Dartmouth)",
      ],
    },
  },
  /* ----- TRAVEL ----- */
  {
    id: 'best-aman-resorts-world',
    publishedDate: '2026-05-27',
    title: 'Best Aman Resorts in the World',
    category: 'Travel',
    type: 'travel',
    tags: ['travel', 'luxury', 'stores'],
    linkType: 'mapsCity',
    blurb: 'Pavilions carved into red-rock canyons, palazzos on the Grand Canal, villas above lotus-filled bays. Aman built the template for understated, off-the-grid luxury, and these are the retreats its devotees chase around the planet.',
    defaultSource: 'ai',
    sources: {
      ai: {
        label: 'Consensus Seed',
        items: [
          'Amangiri (Canyon Point, Utah)',
          'Amanoi (Vinh Hy Bay, Vietnam)',
          'Amanzoe (Porto Heli, Greece)',
          'Amanpuri (Phuket, Thailand)',
          'Aman Tokyo (Japan)',
          'Amankila (Bali, Indonesia)',
          'Aman Venice (Italy)',
          'Amanyara (Turks & Caicos)',
          'Aman New York (United States)',
          'Amanpulo (Pamalican Island, Philippines)',
        ],
      },
      luxetravelexpert: {
        label: 'The Luxury Travel Expert 2024',
        items: [
          'Amangiri (Canyon Point, Utah)',
          'Amanoi (Vinh Hy Bay, Vietnam)',
          'Amanzoe (Porto Heli, Greece)',
          'Amanera (Dominican Republic)',
          'Aman Tokyo (Japan)',
          'Aman Venice (Italy)',
          'Amanyara (Turks & Caicos)',
          'Amanpuri (Phuket, Thailand)',
          'Amankila (Bali, Indonesia)',
          'Aman New York (United States)',
        ],
      },
      upgradedpoints: {
        label: 'Upgraded Points 2025',
        items: [
          'Amanoi (Vinh Hy Bay, Vietnam)',
          'Amanpulo (Pamalican Island, Philippines)',
          'Amanbagh (Rajasthan, India)',
          'Amanzoe (Porto Heli, Greece)',
          'Amankila (Bali, Indonesia)',
          'Amanjiwo (Central Java, Indonesia)',
          'Amankora (Paro, Bhutan)',
          'Aman-i-Khas (Ranthambore, India)',
          'Aman Sveti Stefan (Montenegro)',
          'Amangiri (Canyon Point, Utah)',
          'Amanera (Dominican Republic)',
          'Amansara (Siem Reap, Cambodia)',
          'Amanpuri (Phuket, Thailand)',
          'Amanemu (Mie, Japan)',
          'Amanyara (Turks & Caicos)',
          'Aman New York (United States)',
        ],
      },
      pursuitist: {
        label: 'Pursuitist 2026',
        items: [
          'Amangiri (Canyon Point, Utah)',
          'Aman Kyoto (Japan)',
          'Aman Sveti Stefan (Montenegro)',
          'Amanyara (Turks & Caicos)',
          'Aman Venice (Italy)',
        ],
      },
    },
    vote: {
      items: [
        'Amangiri (Canyon Point, Utah)',
        'Amanoi (Vinh Hy Bay, Vietnam)',
        'Amanzoe (Porto Heli, Greece)',
        'Amanpuri (Phuket, Thailand)',
        'Aman Tokyo (Japan)',
        'Amankila (Bali, Indonesia)',
        'Aman Venice (Italy)',
        'Amanyara (Turks & Caicos)',
        'Aman New York (United States)',
        'Amanpulo (Pamalican Island, Philippines)',
      ],
    },
  },
];

export { LISTS, TYPES, COLORS, AMAZON_AFFILIATE_TAG, BOOKING_AFFILIATE_AID, TRIPADVISOR_PARTNER };