// Item descriptions shown in the list overview tiles.
// Key: list ID -> item name (exact string, parenthetical included) -> 1-2 sentence description.
// No em dashes. Keep to 1-2 sentences, specific and editorial.
export const DESCRIPTIONS = {
  'headphones-overear': {
    'Sony WH-1000XM6': 'The benchmark wireless headphone: Sony\'s sharpest noise cancellation yet, a folding design that returned, and 30 hours of battery. Reviewers call it the best all-rounder money can buy, with ANC that erases airplane cabins.',
    'Bose QuietComfort Ultra Headphones (2nd Gen)': 'Bose\'s flagship still sets the bar for raw noise cancellation and long-haul comfort. Buyers consistently praise the plush fit and silence, with sound quality a close second to the hush.',
    'Sennheiser HDB 630': 'An audiophile headphone that happens to be wireless: refined, even-handed tuning, aptX Lossless support, and roughly 60 hours per charge. Reviewers say it needs less EQ fiddling than anything else in the class.',
    'Focal Bathys Mg': 'The French hi-fi house\'s wireless statement piece, with magnesium drivers borrowed from its audiophile line. Reviewers rate it the best-sounding ANC headphone made, at a price to match.',
    'Apple AirPods Max': 'Aluminum and mesh luxury with the most seamless ecosystem tricks in the business, from instant device switching to spatial audio. Buyers love the build and ANC but note the weight and the smart-case quirks.',
    'Bowers & Wilkins Px8 S2 McLaren Edition': 'B&W\'s leather-and-metal flagship in papaya-accented McLaren livery, tuned for a rich, dynamic presentation. A statement headphone for people who want their carbon-cone drivers to match their car.',
    'JBL Tour One M3': 'The value flagship: strong ANC, a transmitter case that beams audio from airplane seatbacks, and marathon battery life. Reviewers call it the most feature-dense headphone under the big-three flagships.',
    'Bowers & Wilkins Px7 S3': 'The sweet spot in B&W\'s lineup, with much of the Px8\'s luxurious midrange at a friendlier price. Reviewers consistently single out its musicality over rivals\' processed sound.',
    'Sonos Ace': 'Sonos\'s first headphone, with a trick no rival has: handing off TV audio from a Sonos soundbar for private home-theater listening. Buyers praise the comfort and clean design.',
    'Cambridge P100 SE': 'A spaciousness specialist with aptX Lossless, metal earcups, and a user-replaceable battery rated at up to 100 hours with ANC off. Reviewers call it the endurance champion of serious wireless headphones.',
  },
  'miami-beach-hotels': {
    'Four Seasons Hotel at The Surf Club (Surfside)': 'The 1930 Surf Club reborn under Richard Meier glass, where Sinatra-era glamour meets the best service operation in South Florida. Thomas Keller\'s Surf Club Restaurant and a cabana-lined beach seal it.',
    'Faena Hotel Miami Beach (Mid-Beach)': 'Baz Luhrmann-designed maximalism: gold columns, a gilded woolly mammoth by Damien Hirst, and the Saxony Theater\'s cabaret. The most theatrical hotel in America, and proud of it.',
    'The Setai (South Beach)': 'Art Deco bones with a serene, Asian-minimalist interior and three temperature-tiered pools facing the Atlantic. The courtyard\'s jazz brunch and bronze-clad calm feel a world away from Collins Avenue.',
    'Acqualina Resort & Spa (Sunny Isles Beach)': 'A Mediterranean-style palazzo on 400 feet of private beach, routinely ranked among the top beach resorts in the country. Generous suites and a true family-meets-luxury formula.',
    '1 Hotel South Beach (South Beach)': 'Eco-luxury at scale: driftwood lobbies, living walls, four pools, and the largest rooms on the beach. The rooftop adults-only pool has the best sunset vantage in South Beach.',
    'St. Regis Bal Harbour Resort (Bal Harbour)': 'Glass towers across from Bal Harbour Shops with butler service on every booking and a polished, quiet beach. The grande dame of Miami\'s northern gold coast.',
    'Nobu Hotel Miami Beach (Mid-Beach)': 'A Japanese-inflected hideaway inside the Eden Roc, with Nobu Matsuhisa\'s flagship restaurant steps from the pool. Understated rooms let the omakase and the ocean do the talking.',
    'The Miami Beach EDITION (Mid-Beach)': 'Ian Schrager\'s polished playground: a lobby of white marble and palm trees, Jean-Georges dining, and a basement with a skating rink and nightclub. Scene and serenity in one building.',
    'The Ritz-Carlton (South Beach)': 'A restored 1953 Morris Lapidus landmark at the quiet end of Lincoln Road, rebuilt top to bottom in 2020. Classic Ritz polish with a DiLido Beach Club on the sand.',
    'The Ritz-Carlton (Key Biscayne)': 'The family flagship across the Rickenbacker Causeway, with 11 tennis courts, a renowned kids\' program, and a calmer, residential stretch of beach. Miami luxury without the South Beach volume.',
  },
  'best-aman-resorts-world': {
    'Amanoi (Vinh Hy Bay, Vietnam)': 'Pavilions scattered through Nui Chua National Park above a turquoise bay, with a spa built around two hammam houses and a lotus lake. The most secluded Aman in Asia, and many devotees\' favorite.',
    'Amangiri (Canyon Point, Utah)': 'Concrete minimalism folded into 900 acres of Utah slickrock, with a pool wrapped around a sandstone escarpment. The American desert icon that made Aman a celebrity byword.',
    'Amanyara (Turks & Caicos)': 'Timber pavilions around black reflecting ponds on a wild stretch of Northwest Point, steps from some of the best wall diving in the Caribbean. Barefoot seclusion with serious culinary firepower.',
    'Aman Venice (Italy)': 'A 16th-century palazzo on the Grand Canal with Tiepolo frescoes and gilded ballroom salons as common spaces. The rare city Aman, and arguably the most beautiful hotel in Venice.',
    'Amanzoe (Porto Heli, Greece)': 'A hilltop acropolis of columned pavilions overlooking the Peloponnese coast, each with its own pool. The beach club across the olive groves is Greece\'s most polished.',
    'Aman Sveti Stefan (Montenegro)': 'An entire 15th-century fortified islet of stone cottages joined to a mainland villa where royals once summered. The Adriatic\'s most romantic address when its gates are open.',
    'Aman Kyoto (Japan)': 'A hidden garden valley of latticed pavilions in the forested foothills near Kinkaku-ji, built on a never-completed textile magnate\'s estate. Moss, maples, and onsen baths in profound quiet.',
    'Amanpulo (Pamalican Island, Philippines)': 'A private island in the Sulu Sea ringed by powder sand and a house reef, reached only by Aman\'s own plane. Casitas modeled on Filipino bahay homes set the castaway standard.',
    'Amankila (Bali, Indonesia)': 'Three tiered infinity pools stepping down a jungled hillside toward the Lombok Strait, in quiet east Bali far from the island\'s crowds. A 1992 original that still defines the genre.',
    'Amanbagh (Rajasthan, India)': 'A domed, rose-sandstone palace compound in a Mughal hunting valley outside Jaipur, with camel-country excursions and haveli-style suites. The most transporting Aman in India.',
  },
  'home-espresso-machines': {
    'Rocket R58': 'A dual-boiler Italian icon with PID temperature control hidden behind classic E61 styling. The default recommendation when someone asks for one prosumer machine to last decades.',
    'Lelit Bianca V3': 'The flow-profiling favorite: a paddle on the E61 group lets you shape pre-infusion and pressure mid-shot. Enthusiasts call it the most capability per dollar in espresso.',
    'ECM Synchronika': 'German-built dual boiler with arguably the finest fit and finish in the category, from the stainless panels to the slow, deliberate build quality. The machine forums tell you to buy once and cry once.',
    'La Marzocco GS3': 'The commercial benchmark shrunk for the kitchen counter: a saturated group, rock-solid temperature stability, and cafe-grade steam. What baristas buy when they go home.',
    'Profitec Pro 700': 'A dual-boiler workhorse from ECM\'s sister brand, prized for quiet rotary pumping, plumbability, and unflappable shot-to-shot consistency. The sensible pick of the German heavyweights.',
    'La Marzocco Linea Mini': 'The home version of the cafe-defining Linea, with the same saturated brew group and a cult following to match. As much a design object as an espresso machine.',
    'Slayer Single Group': 'Seattle\'s flow-profiling pioneer in domestic form, with the needle-valve pre-brew that created a whole espresso style. For people who want to chase cafe-level sweetness at home.',
    'Rancilio Silvia Pro X': 'The legendary Silvia grown up: dual boilers, PID, and a soft pre-infusion in a compact, no-nonsense steel box. Serious espresso without the chrome jewelry.',
    'Rocket Appartamento': 'The gateway heat-exchanger machine, compact enough for small kitchens and handsome enough to show off. The most recommended first "real" espresso machine of the past decade.',
    'Breville Oracle Dual Boiler': 'Automatic grinding, dosing, and tamping bolted to a true dual-boiler engine. Reviewers call it the easiest path to genuinely excellent espresso without learning barista technique.',
  },
  'caesar-wraps-nyc': {
    'Milano Market (multiple locations)': 'The Upper West Side gourmet deli whose chicken Caesar wrap became a city-wide obsession: hot chopped cutlets, cold crisp romaine, and a heavy hand with the parm. The standard every other wrap gets measured against.',
    'Jacob\'s Pickles (Upper West Side)': 'The Southern comfort institution applies its buttermilk fried chicken to the form, wrapped with romaine and a punchy Caesar. Indulgent where the deli versions are lean.',
    'Bobwhite Counter (multiple locations)': 'The East Village fried chicken counter\'s Caesar wrap rides its famous brined-and-fried thighs. A cult order for people who know the menu past the chicken box.',
    'Lenwich (multiple locations)': 'The citywide sandwich chain\'s sleeper hit: dependable grilled chicken, fresh romaine, and proper dressing ratios at dozens of locations. Consistency is the achievement.',
    'Brown Bag Sandwich (multiple locations)': 'Chopped-sandwich specialists who treat the Caesar wrap with house-roasted chicken, house croutons, and chives. A deli classic rebuilt from scratch components.',
    'Edith\'s (Williamsburg)': 'The Jewish-diaspora all-day cafe gives the wrap a laffa-adjacent upgrade with punchy dressing and pickled accents. The Brooklyn answer to the Manhattan deli versions.',
    'Compton\'s (multiple locations)': 'Alex Compton\'s sandwich shops made the chicken Caesar wrap a signature, with juicy chopped chicken and a sharp, anchovy-forward dressing. Grew from one Queens shop to a small cult empire.',
    'Heavenly Market (multiple locations)': 'Classic NYC deli-counter execution: grilled chicken, cold romaine, croutons, and parm rolled tight and cut to order. The everyday wrap done exactly right.',
    'La Villa Pizzeria (multiple locations)': 'The Brooklyn red-sauce pizzeria\'s wrap benefits from an Italian kitchen\'s instincts: real grated cheese, garlicky dressing, and grilled chicken with actual char.',
    'Smith Gourmet Deli (Cobble Hill)': 'A neighborhood bodega-deli whose Caesar wrap earned an outsized reputation on Smith Street: generous, cheap, and made while you watch. The local\'s pick on this list.',
  },
  'travel-monitors': {
    'ViewSonic VX1655-4K-OLED': 'A 15.6-inch 4K OLED panel in a slab barely heavier than a magazine, with perfect blacks that make hotel-room movie nights worth it. The picture-quality champion of portable monitors.',
    'Espresso Display 15 Touch': 'The Australian design darling: a 5.5mm aluminum body, glass touchscreen, and magnetic stand system that feels Apple-grade. The most polished hardware in the category.',
    'Espresso 17 Pro': 'A 17.3-inch 4K touchscreen that turns an airport lounge into a dual-monitor office, with the same machined-aluminum build as its smaller sibling. The premium pick for serious remote work.',
    'ViewSonic VP16-OLED': 'A color-accurate OLED aimed at traveling creatives, with a clever built-in kickstand-handle and factory calibration. The photographer\'s portable monitor.',
    'INNOCN 13K1F (13.3" OLED)': 'A 13.3-inch OLED that weighs almost nothing and slips into a tablet sleeve, regularly found at an impulse-buy price. The best small-and-light option with a flagship panel.',
    'INNOCN PU15-Pre': 'A 15.6-inch 4K OLED with mini-HDMI and USB-C in a budget-brand body that undercuts the big names. Buyers tolerate the plain chassis for the panel quality.',
    'Lenovo ThinkVision M14t': 'The corporate road-warrior standard: pen-and-touch input, a sturdy tilting base, and plug-and-play USB-C that just works with a ThinkPad. Built like the laptops it travels with.',
    'ASUS ROG Strix XG17AHPE': 'A 240Hz portable gaming monitor with its own battery, fast enough for competitive shooters on the road. The unambiguous pick for travel gaming.',
    'LG gram + View': 'A 16-inch 16:10 IPS companion made to pair with LG\'s featherweight gram laptops, matching their resolution and finish. Tall-screen productivity in a 670-gram slab.',
    'ASUS ZenScreen Touch (MB16AMT)': 'The long-running ZenScreen with 10-point touch, a built-in battery, and auto-rotation. A dependable all-rounder that has survived generations of copycats.',
  },
  'best-beach-clubs-mediterranean': {
    'Club 55 (Saint-Tropez, France)': 'The 1955 Pampelonne original where Bardot\'s film crew ate, still run by the de Colmont family. Linen-shaded lunches, the famous crudité basket, and the Med\'s most storied sand.',
    'La Fontelina (Capri, Italy)': 'Sunbeds wedged among the rocks facing the Faraglioni, reached by boat or a cliff path from Tragara. Lunch is spaghetti alle vongole and white wine over impossibly blue water.',
    'Nammos (Mykonos, Greece)': 'Psarou Beach\'s champagne-soaked colossus, where superyachts anchor stern-to for the afternoon scene. The loudest, glossiest table on the Aegean.',
    'Maçakızı (Bodrum, Turkey)': 'The Bodrum peninsula\'s legend: a hillside hotel whose teak waterfront platforms and Aegean-Mediterranean kitchen draw Istanbul society every July. Glamour with real culinary chops.',
    'Bonj Les Bains (Hvar, Croatia)': 'A 1930s stone colonnade carved into a pine-fringed cove, restored as the Adriatic\'s most elegant bathing establishment. Cabanas, cold rosé, and crystalline swimming.',
    'Alemagou (Mykonos, Greece)': 'The bamboo-and-thatch bohemian answer to Mykonos gloss, on windswept Ftelia Bay. Barefoot DJ afternoons and Aegean-modern cooking without the bottle-service theater.',
    'Beachouse (Ibiza, Spain)': 'Playa d\'en Bossa\'s grown-up beach club: Balearic-paced lunches, four-poster daybeds, and sunset sessions that stop short of superclub chaos. Ibiza for people past the foam parties.',
    'La Guérite (Cannes, France)': 'A boat-access table on Île Sainte-Marguerite across from the Croisette, where Greek-Mediterranean plates escalate into a full-room party by 4pm. The Riviera\'s best lunch-to-fete pipeline.',
    'Scorpios (Mykonos, Greece)': 'The sunset-ritual phenomenon on Paraga\'s headland, equal parts beach club, amphitheater, and bohemian temple. Its slow-burn DJ ceremonies spawned imitators across the Med.',
    'Gran Folies (Mallorca, Spain)': 'A cliff-cut pool club above a private cove near Port d\'Andratx, far from Magaluf\'s noise. Mallorca\'s quiet contender with the island\'s best swimming platform.',
  },
  'three-martini-lunch-manhattan': {
    'The Grill (Midtown)': 'The Seagram Building\'s mid-century power room, where tuxedoed captains carve prime rib tableside under Philip Johnson\'s walnut walls. The definitive expense-account lunch in America.',
    'Torrisi Bar & Restaurant (Nolita)': 'Major Food Group\'s love letter to Italian-American New York inside the old Puck Building, with a dining room built for deal-closing. The martinis arrive sized like commitments.',
    'Ci Siamo (Hudson Yards)': 'Danny Meyer\'s wood-fired Italian with corner-office views and service calibrated for the long lunch. The carbonara-and-Tanqueray crowd\'s downtown-west headquarters.',
    'Dowling\'s at The Carlyle (Upper East Side)': 'Clubby leather, black-and-white photographs, and a Dover sole filleted tableside in the Carlyle\'s wood-paneled jewel box. Old New York lunch at its most unapologetic.',
    'Carbone (Greenwich Village)': 'The red-sauce theater piece where captains in burgundy tuxedos toss Caesar tableside and the spicy rigatoni earns its fame. Lunch reservations remain a competitive sport.',
    'Balthazar (SoHo)': 'Keith McNally\'s eternal brasserie, pouring martinis under nicotine-glow mirrors since 1997. The steak frites lunch that makes everyone feel like a regular.',
    'King (Hudson Square)': 'A chef-driven corner room where the handwritten daily menu leans French-Italian and the martinis are ice-cold and serious. The connoisseur\'s quiet choice on this list.',
    'L\'Artusi (West Village)': 'The West Village\'s polished Italian crowd-pleaser, where cacio e pepe and a 50/50 martini make a case for never going back to the office. Energy without the scene tax.',
    'La Marchande (Financial District)': 'A grand French brasserie in the Wall Street Hotel, built for the downtown deal lunch with raw towers and textbook steak au poivre. FiDi finally has its three-martini room.',
    'Coco\'s (Midtown)': 'A swaggering Midtown newcomer engineered for the modern power lunch: prime steaks, a deep martini program, and banquettes meant for staying awhile.',
  },
  'burgers-nyc': {
    'Red Hook Tavern (Red Hook)': 'Billy Durney\'s dry-aged cheeseburger with white onion and American cheese on a sesame bun became the city\'s modern benchmark. A bar burger executed with steakhouse obsession.',
    '4 Charles Prime Rib (West Village)': 'The basement steakhouse\'s double-patty Au Cheval descendant, blanketed in cheese with house pickles. Scoring one at the bar remains a New York badge of honor.',
    'Nowon (East Village)': 'The Korean-American "classic cheeseburger" with kimchi mayo and a double smashed patty that wins citywide blind tastings. Bar-food swagger with real technique.',
    'Rolo\'s (Ridgewood)': 'The wood-fired neighborhood restaurant\'s burger built on house-ground beef, sharp cheddar, and a legendary fry program. Worth the M train ride by itself.',
    'Sip & Guzzle (West Village)': 'The cocktail den\'s Japanese-inflected luxury burger, griddled to a deep crust and dressed with restraint. A bartender\'s burger that outclasses most kitchens.',
    'Hamburger America (Soho)': 'George Motz\'s living museum of regional American burgers, from the Oklahoma fried-onion to the classic smash. The country\'s foremost burger scholar cooking his canon.',
    'Gotham Burger Social Club (Lower East Side)': 'The pop-up turned storefront whose smashburgers and gold-standard potato buns built an Instagram empire. The line moves fast and the burger justifies it.',
    '7th Street Burger (East Village)': 'The $9 smash that conquered the city: lacy-edged patties, American cheese, and house sauce from a closet-sized kitchen, now copied everywhere. New York\'s value champion.',
    'Deux Luxe (Nolita)': 'Wagyu smashburgers with garlic aioli from the team behind Westchester\'s Café Deux, served from a sleek Broome Street counter. The luxury end of the smash wave.',
    'Minetta Tavern (Greenwich Village)': 'The Black Label: dry-aged ribeye and short rib ground into the most famous luxury burger in America, served with caramelized onions in a 1937 room. Still the special-occasion answer.',
  },
  'cocktails-williamsburg': {
    'Maison Premiere': 'The oyster-and-absinthe salon that brought New Orleans romance to Bedford Avenue, with a James Beard Award for its bar program. The marble horseshoe bar remains Brooklyn\'s most transporting seat.',
    'Fresh Kills Bar': 'From the Dutch Kills family, a no-nonsense room where hand-cut ice and housemade syrups meet some of the most exacting classic-cocktail technique in the borough.',
    'Bar Blondeau': 'The Wythe Hotel\'s sixth-floor wine-and-cocktail room, where French-leaning drinks come with a postcard Manhattan skyline. Golden hour here is a Williamsburg institution.',
    'Bar Madonna': 'An Italian-American cocktail bar on Metropolitan where the drinks get avant-garde and the kitchen sends out a smashed meatball parm. Williamsburg\'s most fun new-school room.',
    'Westlight': 'The William Vale\'s 22nd-floor aerie with wraparound terraces and the best panoramic view in Brooklyn. The cocktails keep up with the skyline.',
    'Layla': 'A Middle Eastern-leaning all-day restaurant whose bar quietly pours some of the neighborhood\'s best drinks, heavy on arak, citrus, and spice. Small plates make it dangerous to leave.',
    'Sauced': 'The no-menu wine-and-drinks den on Grand Street: tell the bartender what you like and bottles come out of the ice bucket until one fits. Williamsburg hospitality at its loosest.',
    'Pokito': 'A tiny pan-Latin bar with an overachieving mezcal-and-pisco list and a backyard built for summer. Big flavors in one of the neighborhood\'s smallest rooms.',
    'Velvet Brooklyn': 'A plush cafe-by-day, cocktail-lounge-by-night hybrid with serious espresso-hour-to-amaro-hour range. The neighborhood\'s most versatile room.',
    'Bar Milagro': 'An agave-focused corner bar pouring thoughtful mezcal and tequila drinks without the party-bar clichés. The local\'s pick for a quiet, serious margarita.',
  },
};
