// Quiz definitions for /quiz/[id].
//
// Shape:
//   id         kebab slug -> /quiz/<id>
//   listId     OPTIONAL paired /list/<listId>
//   title      headline
//   category   eyebrow label
//   blurb      one-line italic description
//   timeLimit  seconds on the clock
//   answers    ranked slots. Each: t (display name), keys (match substrings), anti (block substrings)
//
// Leniency rules:
//   Sports teams: year alone accepted; repeated franchises need year + team.
//   Menu items: core food name accepted without brand qualifier.
//   Stadiums: school name or team nickname accepted.
//   Standup: comedian last name for first-ranked special; later appearance requires title.
//   Soundtracks / games: movie/game title alone accepted.

export const QUIZZES = [

  // ── Airlines ─────────────────────────────────────────────────────────────

  {
    id: 'best-airlines-north-america',
    listId: 'best-airlines-north-america',
    publishedDate: '2026-06-11',
    title: 'Name the Best Airlines in North America',
    category: 'Travel',
    type: 'travel',
    tags: ['travel', 'other'],
    timeLimit: 90,
    blurb: 'Skytrax, The Points Guy, the WSJ scorecard, and Cirium on-time data — condensed to a single ranked ten. Name them all.',
    answers: [
      { t: 'Delta Air Lines', keys: ['delta'] },
      { t: 'United Airlines', keys: ['united'] },
      { t: 'Alaska Airlines', keys: ['alaska'] },
      { t: 'Southwest Airlines', keys: ['southwest', 'south west'] },
      { t: 'JetBlue', keys: ['jetblue', 'jet blue'] },
      { t: 'American Airlines', keys: ['american'] },
      { t: 'Allegiant Air', keys: ['allegiant'] },
      { t: 'Air Canada', keys: ['air canada'] },
      { t: 'Frontier Airlines', keys: ['frontier'] },
      { t: 'Porter Airlines', keys: ['porter'] },
    ],
  },

  {
    id: 'best-airlines-world',
    listId: 'best-airlines-world',
    publishedDate: '2026-06-11',
    title: 'Name the Best Airlines in the World',
    category: 'Travel',
    type: 'travel',
    tags: ['travel', 'other'],
    timeLimit: 90,
    blurb: 'Skytrax World Airline Awards and multiple global rankings condensed to a single consensus top ten. Name them all.',
    answers: [
      { t: 'Qatar Airways', keys: ['qatar'] },
      { t: 'Cathay Pacific', keys: ['cathay'] },
      { t: 'Singapore Airlines', keys: ['singapore'] },
      { t: 'Korean Air', keys: ['korean'] },
      { t: 'Emirates', keys: ['emirates'] },
      { t: 'Etihad Airways', keys: ['etihad'] },
      { t: 'Turkish Airlines', keys: ['turkish'] },
      { t: 'Virgin Atlantic', keys: ['virgin atlantic', 'virgin'] },
      { t: 'Qantas', keys: ['qantas'] },
      { t: 'Japan Airlines', keys: ['japan airlines', 'jal'] },
    ],
  },

  // ── Sports teams ─────────────────────────────────────────────────────────

  {
    id: 'best-nfl-teams',
    listId: 'best-nfl-teams',
    publishedDate: '2026-06-11',
    title: 'Name the Greatest NFL Teams of All Time',
    category: 'Sports',
    type: 'entertainment',
    tags: ['entertainment', 'other'],
    timeLimit: 120,
    blurb: "The consensus on the greatest rosters in NFL history. The year alone is enough to identify each team.",
    answers: [
      { t: '1972 Miami Dolphins', keys: ['1972', '72 miami', '72 dolphins', 'dolphins', 'miami dolphins'] },
      { t: '1985 Chicago Bears', keys: ['1985', '85 bears', 'chicago bears', 'bears'] },
      { t: '1978 Pittsburgh Steelers', keys: ['1978', '78 steelers', 'steelers', 'pittsburgh steelers'] },
      { t: '1984 San Francisco 49ers', keys: ['1984', '84 san francisco', '84 49ers', '84 niners'], anti: ['1989', '89'] },
      { t: '1989 San Francisco 49ers', keys: ['1989', '89 san francisco', '89 49ers', '89 niners'], anti: ['1984', '84'] },
      { t: '1992 Dallas Cowboys', keys: ['1992', '92 cowboys', 'cowboys', 'dallas cowboys'] },
      { t: '2007 New England Patriots', keys: ['2007', '07 patriots', 'patriots', 'new england'] },
      { t: '1976 Oakland Raiders', keys: ['1976', '76 raiders', 'raiders', 'oakland raiders'] },
      { t: '1961 Green Bay Packers', keys: ['1961', '61 packers', 'packers', 'green bay'] },
      { t: '1998 Denver Broncos', keys: ['1998', '98 broncos', 'broncos', 'denver broncos'] },
    ],
  },

  {
    id: 'best-nba-teams',
    listId: 'best-nba-teams',
    publishedDate: '2026-06-11',
    title: 'Name the Greatest NBA Teams of All Time',
    category: 'Sports',
    type: 'entertainment',
    tags: ['entertainment', 'other'],
    timeLimit: 120,
    blurb: "Jordan's Bulls are the obvious answer. The Bulls and Lakers each appear twice — the season (e.g. 95-96) disambiguates.",
    answers: [
      { t: '1995-96 Chicago Bulls', keys: ['1995', '95-96 bulls', '95-96 chicago', '95/96'], anti: ['1990', '90'] },
      { t: '1985-86 Boston Celtics', keys: ['1985', '85-86', 'celtics', 'boston celtics'] },
      { t: '1971-72 Los Angeles Lakers', keys: ['1971', '71-72', '71-72 lakers', '71-72 la'], anti: ['1986', '86'] },
      { t: '1986-87 Los Angeles Lakers', keys: ['1986', '86-87', '86-87 lakers', '86-87 la'], anti: ['1971', '71'] },
      { t: '2016-17 Golden State Warriors', keys: ['2016', '16-17', 'warriors', 'golden state'] },
      { t: '1982-83 Philadelphia 76ers', keys: ['1982', '82-83', '82-83 sixers', '82-83 76ers'], anti: ['1966', '66'] },
      { t: '1988-89 Detroit Pistons', keys: ['1988', '88-89', 'pistons', 'detroit pistons'] },
      { t: '1970-71 Milwaukee Bucks', keys: ['1970', '70-71', 'bucks', 'milwaukee bucks'] },
      { t: '1990-91 Chicago Bulls', keys: ['1990', '90-91', '90-91 bulls', '90-91 chicago'], anti: ['1995', '95'] },
      { t: '1966-67 Philadelphia 76ers', keys: ['1966', '66-67', '66-67 sixers', '66-67 76ers'], anti: ['1982', '82'] },
    ],
  },

  {
    id: 'best-mlb-teams',
    listId: 'best-mlb-teams',
    publishedDate: '2026-06-11',
    title: 'Name the Greatest MLB Teams of All Time',
    category: 'Sports',
    type: 'entertainment',
    tags: ['entertainment', 'other'],
    timeLimit: 120,
    blurb: 'Warning: four Yankees teams made the list. For Yankees and Dodgers entries, include the year to disambiguate.',
    answers: [
      { t: '1939 New York Yankees', keys: ['1939', '1939 yankees'], anti: ['1927', '1961', '1998'] },
      { t: '1998 New York Yankees', keys: ['1998', '1998 yankees'], anti: ['1927', '1939', '1961'] },
      { t: '1927 New York Yankees', keys: ['1927', '1927 yankees'], anti: ['1939', '1961', '1998'] },
      { t: '1906 Chicago Cubs', keys: ['1906', '1906 cubs', 'cubs 1906'] },
      { t: '1961 New York Yankees', keys: ['1961', '1961 yankees'], anti: ['1927', '1939', '1998'] },
      { t: '2001 Seattle Mariners', keys: ['2001', 'mariners', 'seattle mariners'] },
      { t: '2022 Los Angeles Dodgers', keys: ['2022', '2022 dodgers'], anti: ['2020'] },
      { t: '2020 Los Angeles Dodgers', keys: ['2020', '2020 dodgers'], anti: ['2022'] },
      { t: '1902 Pittsburgh Pirates', keys: ['1902', 'pirates', 'pittsburgh pirates'] },
      { t: '1954 Cleveland Indians', keys: ['1954', 'indians', 'cleveland indians', 'cleveland guardians'] },
    ],
  },

  {
    id: 'best-college-football-teams',
    listId: 'best-college-football-teams',
    publishedDate: '2026-06-11',
    title: 'Name the Greatest College Football Teams of All Time',
    category: 'Sports',
    type: 'entertainment',
    tags: ['entertainment', 'other'],
    timeLimit: 120,
    blurb: 'Nebraska and USC each appear twice. The season year disambiguates — just know your dynasties.',
    answers: [
      { t: '1971 Nebraska Cornhuskers', keys: ['1971', '1971 nebraska', '71 huskers', '1971 huskers'], anti: ['1995'] },
      { t: '2001 Miami Hurricanes', keys: ['2001', '2001 miami', '01 miami', 'miami hurricanes'] },
      { t: '1995 Nebraska Cornhuskers', keys: ['1995', '1995 nebraska', '95 huskers', '1995 huskers'], anti: ['1971'] },
      { t: '1972 USC Trojans', keys: ['1972', '1972 usc', '72 trojans', '1972 trojans'], anti: ['2004'] },
      { t: '2019 LSU Tigers', keys: ['2019', '2019 lsu', '19 lsu'], anti: ['2018'] },
      { t: '2018 Clemson Tigers', keys: ['2018', '2018 clemson', '18 clemson'], anti: ['2019'] },
      { t: '2004 USC Trojans', keys: ['2004', '2004 usc', '04 trojans', '2004 trojans'], anti: ['1972'] },
      { t: '2025 Indiana Hoosiers', keys: ['2025', '2025 indiana', '25 indiana', 'indiana hoosiers'] },
      { t: '2005 Texas Longhorns', keys: ['2005', '2005 texas', '05 texas', 'texas longhorns'] },
      { t: '2020 Alabama Crimson Tide', keys: ['2020 alabama', '20 alabama', 'alabama', '2020 crimson tide'] },
    ],
  },

  {
    id: 'best-college-basketball-teams',
    listId: 'best-college-basketball-teams',
    publishedDate: '2026-06-11',
    title: 'Name the Greatest College Basketball Teams of All Time',
    category: 'Sports',
    type: 'entertainment',
    tags: ['entertainment', 'other'],
    timeLimit: 120,
    blurb: "UCLA appears three times, Duke and Kentucky twice each. The season year disambiguates — if you know your dynasties.",
    answers: [
      { t: '1971-72 UCLA Bruins', keys: ['1971', '71-72', '71-72 ucla', '71-72 bruins'], anti: ['1966', '1967'] },
      { t: '1985-86 Boston Celtics', keys: ['1985', '85-86', 'celtics', 'boston celtics'] },
      { t: '1991-92 Duke Blue Devils', keys: ['1991', '91-92', '91-92 duke'], anti: ['2000'] },
      { t: '2011-12 Kentucky Wildcats', keys: ['2011', '11-12', '11-12 kentucky'], anti: ['1995'] },
      { t: '1975-76 Indiana Hoosiers', keys: ['1975', '75-76', 'indiana hoosiers', '75-76 indiana'] },
      { t: '2000-01 Duke Blue Devils', keys: ['2000', '00-01', '00-01 duke'], anti: ['1991'] },
      { t: '1967-68 UCLA Bruins', keys: ['1967', '67-68', '67-68 ucla'], anti: ['1966', '1971'] },
      { t: '1973-74 NC State Wolfpack', keys: ['1973', '73-74', 'nc state', 'wolfpack'] },
      { t: '1995-96 Kentucky Wildcats', keys: ['1995', '95-96', '95-96 kentucky'], anti: ['2011'] },
      { t: '1981-82 North Carolina Tar Heels', keys: ['1981', '81-82', 'north carolina', 'tar heels', 'unc'] },
    ],
  },

  // ── Music ─────────────────────────────────────────────────────────────────

  {
    id: 'best-selling-albums-all-time',
    listId: 'best-selling-albums-all-time',
    publishedDate: '2026-06-11',
    title: 'Name the Best-Selling Albums of All Time',
    category: 'Music',
    type: 'entertainment',
    tags: ['entertainment'],
    timeLimit: 90,
    blurb: 'Estimated global sales of 40 million copies or more. Album title or artist name both accepted.',
    answers: [
      { t: 'Thriller — Michael Jackson', keys: ['thriller', 'michael jackson'] },
      { t: 'Back in Black — AC/DC', keys: ['back in black', 'ac/dc', 'acdc'] },
      { t: 'The Bodyguard — Whitney Houston', keys: ['bodyguard', 'whitney houston', 'whitney'] },
      { t: 'The Dark Side of the Moon — Pink Floyd', keys: ['dark side', 'dark side of the moon', 'pink floyd'] },
      { t: 'Their Greatest Hits 1971-1975 — Eagles', keys: ['their greatest hits', 'greatest hits 1971', '1971-1975 eagles'], anti: ['hotel california'] },
      { t: 'Hotel California — Eagles', keys: ['hotel california'], anti: ['greatest hits'] },
      { t: 'Come On Over — Shania Twain', keys: ['come on over', 'shania twain', 'shania'] },
      { t: 'Rumours — Fleetwood Mac', keys: ['rumours', 'rumors', 'fleetwood mac', 'fleetwood'] },
      { t: 'Bat Out of Hell — Meat Loaf', keys: ['bat out of hell', 'meat loaf', 'meatloaf'] },
      { t: 'Saturday Night Fever — Bee Gees', keys: ['saturday night fever', 'bee gees'] },
    ],
  },

  {
    id: 'best-selling-soundtracks-all-time',
    listId: 'best-selling-soundtracks-all-time',
    publishedDate: '2026-06-11',
    title: 'Name the Best-Selling Movie Soundtracks of All Time',
    category: 'Music',
    type: 'entertainment',
    tags: ['entertainment'],
    timeLimit: 90,
    blurb: 'The movie soundtracks that became cultural events in their own right. Movie title alone counts.',
    answers: [
      { t: 'The Bodyguard (1992)', keys: ['bodyguard'] },
      { t: 'Saturday Night Fever (1977)', keys: ['saturday night fever', 'night fever'] },
      { t: 'Dirty Dancing (1987)', keys: ['dirty dancing'] },
      { t: 'Purple Rain (1984)', keys: ['purple rain', 'prince'] },
      { t: 'Titanic (1997)', keys: ['titanic'] },
      { t: 'Grease (1978)', keys: ['grease'] },
      { t: 'Forrest Gump (1994)', keys: ['forrest gump', 'gump'] },
      { t: 'Footloose (1984)', keys: ['footloose'] },
      { t: 'Flashdance (1983)', keys: ['flashdance', 'flash dance'] },
      { t: 'Top Gun (1986)', keys: ['top gun'] },
    ],
  },

  // ── TV & film ─────────────────────────────────────────────────────────────

  {
    id: 'standup-specials-netflix',
    listId: 'standup-specials-netflix',
    publishedDate: '2026-06-11',
    title: 'Name the Best Standup Specials on Netflix',
    category: 'Comedy',
    type: 'entertainment',
    tags: ['entertainment'],
    timeLimit: 120,
    blurb: "Comedian last name is enough — unless they appear twice in the top ten. A repeat comedian needs the title for their second special.",
    answers: [
      { t: 'Bo Burnham: Inside', keys: ['burnham', 'bo burnham', 'inside'] },
      { t: 'Richard Pryor: Live in Concert', keys: ['pryor', 'richard pryor', 'live in concert'] },
      { t: 'Bo Burnham: Make Happy', keys: ['make happy'] },
      { t: 'Hannah Gadsby: Nanette', keys: ['gadsby', 'nanette', 'hannah gadsby'] },
      { t: 'John Mulaney: The Comeback Kid', keys: ['mulaney', 'john mulaney', 'comeback kid', 'comeback'] },
      { t: 'John Mulaney: Kid Gorgeous at Radio City', keys: ['kid gorgeous', 'gorgeous', 'radio city'] },
      { t: 'James Acaster: Repertoire', keys: ['acaster', 'repertoire', 'james acaster'] },
      { t: 'Adam Sandler: 100% Fresh', keys: ['sandler', 'adam sandler', '100% fresh'] },
      { t: 'Mike Birbiglia: The New One', keys: ['birbiglia', 'new one', 'mike birbiglia'] },
      { t: 'Hasan Minhaj: Homecoming King', keys: ['minhaj', 'homecoming king', 'hasan minhaj'] },
    ],
  },

  {
    id: 'true-crime-docuseries',
    listId: 'true-crime-docuseries',
    publishedDate: '2026-06-11',
    title: 'Name the Best True Crime Docuseries on Netflix',
    category: 'TV',
    type: 'entertainment',
    tags: ['entertainment'],
    timeLimit: 120,
    blurb: 'Nine docuseries that gripped the world. Title alone is enough — skip the year.',
    answers: [
      { t: 'Making a Murderer (2015)', keys: ['making a murderer', 'murderer'] },
      { t: 'The Keepers (2017)', keys: ['the keepers', 'keepers'] },
      { t: 'The Jinx (2015)', keys: ['the jinx', 'jinx'] },
      { t: 'The Trials of Gabriel Fernandez (2020)', keys: ['gabriel fernandez', 'fernandez'] },
      { t: 'Jeffrey Epstein: Filthy Rich (2020)', keys: ['epstein', 'filthy rich'] },
      { t: 'O.J.: Made in America (2016)', keys: ['o.j.', 'oj', 'made in america', 'oj simpson'] },
      { t: 'Unsolved Mysteries (2020)', keys: ['unsolved mysteries', 'unsolved'] },
      { t: 'Night Stalker: The Hunt for a Serial Killer (2021)', keys: ['night stalker', 'richard ramirez'] },
      { t: 'Seduced: Inside the NXIVM Cult (2020)', keys: ['nxivm', 'seduced'] },
    ],
  },

  // ── Books ─────────────────────────────────────────────────────────────────

  {
    id: 'spy-novels',
    listId: 'spy-novels',
    publishedDate: '2026-06-11',
    title: 'Name the Best Spy Novels',
    category: 'Books',
    type: 'entertainment',
    tags: ['entertainment'],
    timeLimit: 120,
    blurb: 'Two authors each have two entries. Last name is enough for a first appearance — the second needs the title to disambiguate.',
    answers: [
      { t: 'Tinker, Tailor, Soldier, Spy — John le Carré', keys: ['tinker tailor', 'tinker, tailor', 'le carré', 'le carre'] },
      { t: 'The Day of the Jackal — Frederick Forsyth', keys: ['day of the jackal', 'jackal', 'forsyth'] },
      { t: 'Slough House — Mick Herron', keys: ['slough house', 'herron', 'mick herron'], anti: ['slow horses'] },
      { t: 'A Coffin for Dimitrios — Eric Ambler', keys: ['coffin for dimitrios', 'dimitrios', 'ambler'] },
      { t: 'The Spy Who Came In from the Cold — John le Carré', keys: ['spy who came in', 'came in from the cold', 'from the cold'] },
      { t: 'Eye of the Needle — Ken Follett', keys: ['eye of the needle', 'needle', 'follett'] },
      { t: 'An Officer and a Spy — Robert Harris', keys: ['officer and a spy', 'officer spy', 'dreyfus'] },
      { t: 'The Hunt for Red October — Tom Clancy', keys: ['hunt for red october', 'red october', 'clancy'] },
      { t: 'Casino Royale — Ian Fleming', keys: ['casino royale', 'fleming', 'james bond', 'bond'] },
      { t: 'Slow Horses — Mick Herron', keys: ['slow horses', 'slow horse'], anti: ['slough house'] },
    ],
  },

  // ── Gaming ────────────────────────────────────────────────────────────────

  {
    id: 'best-selling-games-all-time',
    listId: 'best-selling-games-all-time',
    publishedDate: '2026-06-11',
    title: 'Name the Best-Selling Video Games of All Time',
    category: 'Gaming',
    type: 'entertainment',
    tags: ['entertainment', 'tech'],
    timeLimit: 90,
    blurb: 'The best-selling video games of all time, ranked by copies sold. Game title alone — no year or sales figure needed.',
    answers: [
      { t: 'Tetris (520M)', keys: ['tetris'] },
      { t: 'Minecraft (350M)', keys: ['minecraft'] },
      { t: 'Grand Theft Auto V (225M)', keys: ['grand theft auto', 'gta v', 'gta 5', 'gta5'] },
      { t: 'Wii Sports (83M)', keys: ['wii sports'] },
      { t: 'Red Dead Redemption 2 (82M)', keys: ['red dead redemption', 'red dead', 'rdr2', 'rdr 2'] },
      { t: 'Mario Kart 8 / Deluxe (79M)', keys: ['mario kart', 'mario kart 8', 'mk8'] },
      { t: 'PUBG: Battlegrounds (75M)', keys: ['pubg', 'battlegrounds', 'playerunknown'] },
      { t: 'Terraria (64M)', keys: ['terraria'] },
      { t: 'The Witcher 3: Wild Hunt (60M)', keys: ['witcher 3', 'witcher', 'wild hunt'] },
      { t: 'Super Mario Bros. (58M)', keys: ['super mario bros', 'super mario brothers'], anti: ['kart', 'odyssey', 'world', 'galaxy', '64', 'wonder'] },
    ],
  },

  {
    id: 'mario-quest-games',
    listId: 'mario-quest-games',
    publishedDate: '2026-06-11',
    title: 'Name the Best Original Quest Mario Games',
    category: 'Gaming',
    type: 'entertainment',
    tags: ['entertainment', 'tech'],
    timeLimit: 120,
    blurb: 'No Kart, no Party, no sports spinoffs — just the mainline platformers and RPGs. Nine games. Name them all.',
    answers: [
      { t: 'Super Mario Odyssey', keys: ['odyssey', 'mario odyssey'] },
      { t: 'Super Mario World', keys: ['mario world', 'super mario world'], anti: ['galaxy', 'odyssey', '64'] },
      { t: 'Super Mario Galaxy 2', keys: ['galaxy 2', 'mario galaxy 2'], anti: ['galaxy 1'] },
      { t: 'Super Mario Galaxy', keys: ['galaxy', 'mario galaxy'], anti: ['galaxy 2', 'galaxy two'] },
      { t: 'Super Mario Bros. 3', keys: ['mario bros. 3', 'mario bros 3', 'super mario 3', 'mario 3', 'smb3'] },
      { t: 'Super Mario 64', keys: ['mario 64', 'super mario 64', 'sm64'] },
      { t: 'Super Mario Bros. Wonder', keys: ['wonder', 'mario wonder', 'mario bros. wonder'] },
      { t: 'Paper Mario: The Thousand-Year Door', keys: ['thousand-year door', 'thousand year door', 'paper mario', 'ttyd'] },
      { t: 'New Super Mario Bros.', keys: ['new super mario', 'nsmb', 'new mario bros'] },
    ],
  },

  // ── Food & snacks ─────────────────────────────────────────────────────────

  {
    id: 'girl-scout-cookies',
    listId: 'girl-scout-cookies',
    publishedDate: '2026-06-11',
    title: 'Name the Best Girl Scout Cookies',
    category: 'Food',
    type: 'food',
    tags: ['food', 'product'],
    timeLimit: 60,
    blurb: 'Ten cookies, sixty seconds. Either the official name or the regional alternate accepted.',
    answers: [
      { t: 'Samoas (Caramel deLites)', keys: ['samoas', 'samoa', 'caramel delites', 'caramel de-lites'] },
      { t: 'Thin Mints', keys: ['thin mints', 'thin mint'] },
      { t: 'Tagalongs (Peanut Butter Patties)', keys: ['tagalongs', 'tagalong', 'peanut butter patties'] },
      { t: 'Do-si-dos (Peanut Butter Sandwich)', keys: ['do-si-dos', 'do si dos', 'dosidos', 'peanut butter sandwich'] },
      { t: 'Lemonades', keys: ['lemonades', 'lemonade'] },
      { t: 'Trefoils', keys: ['trefoils', 'trefoil', 'shortbread'] },
      { t: 'Toffee-tastic (Gluten-Free)', keys: ['toffee-tastic', 'toffeetastic', 'toffee tastic'] },
      { t: 'Adventurefuls', keys: ['adventurefuls', 'adventureful'] },
      { t: 'Exploremores', keys: ['exploremores', 'exploremore'] },
      { t: 'Lemon-Ups', keys: ['lemon-ups', 'lemon ups', 'lemon up'] },
    ],
  },

  {
    id: 'best-classic-chips',
    listId: 'best-classic-chips',
    publishedDate: '2026-06-11',
    title: 'Name the Best Classic Chips',
    category: 'Snacks',
    type: 'product',
    tags: ['product', 'food'],
    timeLimit: 90,
    blurb: "The definitive ranking of America's classic chip flavors. Flavor name or brand-and-flavor both accepted.",
    answers: [
      { t: "Doritos Nacho Cheese", keys: ['nacho cheese', 'doritos nacho'], anti: ['cool ranch', 'spicy sweet'] },
      { t: "Ruffles Cheddar & Sour Cream", keys: ['ruffles cheddar', 'cheddar sour cream', 'cheddar & sour cream'], anti: ['ruffles original', 'ruffles sour cream & onion'] },
      { t: "Lay's Sour Cream & Onion", keys: ["lay's sour cream", 'lays sour cream', 'lay sour cream'], anti: ['ruffles'] },
      { t: "Ruffles Original", keys: ['ruffles original'], anti: ['cheddar', 'sour cream'] },
      { t: "Doritos Cool Ranch", keys: ['cool ranch', 'doritos cool ranch'], anti: ['nacho', 'spicy sweet'] },
      { t: "Doritos Spicy Sweet Chili", keys: ['spicy sweet chili', 'spicy sweet', 'doritos spicy'] },
      { t: "Fritos Original", keys: ['fritos', 'fritos original'] },
      { t: "Lay's Classic", keys: ["lay's classic", 'lays classic', "lay's original", 'lays original'], anti: ['sour cream'] },
      { t: "Tostitos Scoops", keys: ['tostitos scoops', 'tostitos', 'scoops'] },
      { t: "Ruffles Sour Cream & Onion", keys: ['ruffles sour cream & onion', 'ruffles sour cream onion', 'ruffles sour cream'], anti: ['cheddar'] },
    ],
  },

  {
    id: 'best-sandwich-types',
    listId: 'best-sandwich-types',
    publishedDate: '2026-06-11',
    title: 'Name the Best Sandwich Types',
    category: 'Food',
    type: 'food',
    tags: ['food'],
    timeLimit: 90,
    blurb: 'The ten greatest sandwich types by global consensus. Short names work — no need for every word.',
    answers: [
      { t: 'Philly Cheesesteak', keys: ['philly cheesesteak', 'cheesesteak', 'philly'] },
      { t: 'Bánh Mì', keys: ['bánh mì', 'banh mi', 'bahn mi'] },
      { t: 'Reuben', keys: ['reuben'] },
      { t: "Po' Boy", keys: ["po' boy", 'po boy', 'poboy'] },
      { t: 'Cuban Sandwich', keys: ['cuban', 'cuban sandwich', 'cubano'] },
      { t: 'Lobster Roll', keys: ['lobster roll', 'lobster'] },
      { t: 'Texas Brisket Sandwich', keys: ['texas brisket', 'brisket sandwich', 'brisket'] },
      { t: 'Grilled Cheese', keys: ['grilled cheese'] },
      { t: 'Italian Sub (Hoagie)', keys: ['italian sub', 'hoagie', 'italian hoagie', 'sub', 'hero'] },
      { t: 'Torta', keys: ['torta'] },
    ],
  },

  {
    id: 'best-chain-pizza-restaurants',
    listId: 'best-chain-pizza-restaurants',
    publishedDate: '2026-06-11',
    title: 'Name the Best Chain Pizza Restaurants',
    category: 'Food',
    type: 'food',
    tags: ['food'],
    timeLimit: 90,
    blurb: "The ranked consensus on America's best national pizza chains. Name all ten.",
    answers: [
      { t: "Domino's", keys: ["domino's", 'dominos', 'domino'] },
      { t: "Jet's Pizza", keys: ["jet's pizza", 'jets pizza', "jet's"] },
      { t: 'California Pizza Kitchen', keys: ['california pizza kitchen', 'cpk'] },
      { t: 'Pizza Hut', keys: ['pizza hut'] },
      { t: "Marco's Pizza", keys: ["marco's pizza", 'marcos pizza', "marco's"] },
      { t: 'Little Caesars', keys: ['little caesars', 'little caesar'] },
      { t: 'Blaze Pizza', keys: ['blaze pizza', 'blaze'] },
      { t: 'MOD Pizza', keys: ['mod pizza', 'mod'] },
      { t: "Anthony's Coal Fired Pizza", keys: ["anthony's coal fired", "anthony's coal", 'anthonys coal'] },
      { t: "Papa John's", keys: ["papa john's", 'papa johns', 'papa john'] },
    ],
  },

  {
    id: 'best-sub-chains',
    listId: 'best-sub-chains',
    publishedDate: '2026-06-11',
    title: 'Name the Best Sub Chains in America',
    category: 'Food',
    type: 'food',
    tags: ['food'],
    timeLimit: 90,
    blurb: 'The ten best sandwich chains ranked by editorial consensus. Name them all.',
    answers: [
      { t: "Jersey Mike's", keys: ["jersey mike's", 'jersey mikes', 'jersey mike'] },
      { t: 'Potbelly', keys: ['potbelly', 'pot belly'] },
      { t: 'Firehouse Subs', keys: ['firehouse subs', 'firehouse'] },
      { t: "Jimmy John's", keys: ["jimmy john's", 'jimmy johns', 'jimmy john'] },
      { t: 'Penn Station East Coast Subs', keys: ['penn station', 'penn station east coast'] },
      { t: "Capriotti's Sandwich Shop", keys: ["capriotti's", 'capriottis', 'capriotti'] },
      { t: 'Which Wich', keys: ['which wich'] },
      { t: "Schlotzsky's", keys: ["schlotzsky's", 'schlotzskys', 'schlotzsky'] },
      { t: 'PrimoHoagies', keys: ['primohoagies', 'primo hoagies', 'primo'] },
      { t: 'Subway', keys: ['subway'] },
    ],
  },

  {
    id: 'taco-bell-menu-items',
    listId: 'taco-bell-menu-items',
    publishedDate: '2026-06-11',
    title: 'Name the Best Taco Bell Menu Items',
    category: 'Food',
    type: 'food',
    tags: ['food'],
    timeLimit: 90,
    blurb: "Ten Taco Bell classics. Short names are fine — can you name them all?",
    answers: [
      { t: 'Crunchwrap Supreme', keys: ['crunchwrap', 'crunch wrap'] },
      { t: 'Cheesy Gordita Crunch', keys: ['gordita', 'cheesy gordita', 'gordita crunch'] },
      { t: 'Mexican Pizza', keys: ['mexican pizza'] },
      { t: 'Crunchy Taco', keys: ['crunchy taco'], anti: ['locos', 'doritos', 'nacho cheese'] },
      { t: 'Nacho Cheese Doritos Locos Tacos', keys: ['doritos locos', 'locos taco', 'nacho cheese locos', 'locos tacos'] },
      { t: 'Cinnamon Twists', keys: ['cinnamon twists', 'twists'] },
      { t: 'Chicken Quesadilla', keys: ['quesadilla', 'chicken quesadilla'] },
      { t: 'Nachos BellGrande', keys: ['nachos bellgrande', 'bellgrande', 'bell grande', 'nachos bell grande'] },
      { t: 'Beefy 5-Layer Burrito', keys: ['beefy 5-layer', 'beefy 5 layer', 'beefy five layer', '5-layer burrito', 'five layer'] },
      { t: 'Cantina Chicken Burrito', keys: ['cantina chicken', 'cantina burrito', 'cantina'] },
    ],
  },

  {
    id: 'mcdonalds-menu-items',
    listId: 'mcdonalds-menu-items',
    publishedDate: '2026-06-11',
    title: "Name the Best McDonald's Menu Items",
    category: 'Food',
    type: 'food',
    tags: ['food'],
    timeLimit: 90,
    blurb: "Everyone's been there. Can you name the top ten by editorial and fan consensus? Short names accepted.",
    answers: [
      { t: 'Quarter Pounder with Cheese', keys: ['quarter pounder', 'qpc'] },
      { t: 'World Famous Fries', keys: ['fries', 'world famous fries', 'mcdonalds fries'] },
      { t: 'Baked Apple Pie', keys: ['apple pie', 'baked apple pie', 'baked apple'] },
      { t: 'Chicken McNuggets', keys: ['mcnuggets', 'nuggets', 'chicken mcnuggets'] },
      { t: 'Big Mac', keys: ['big mac'] },
      { t: 'McDouble', keys: ['mcdouble', 'mc double'] },
      { t: 'Bacon, Egg & Cheese McGriddles', keys: ['mcgriddles', 'mc griddles', 'griddles', 'mcgriddle'] },
      { t: 'Diet Coke', keys: ['diet coke'] },
      { t: 'Filet-O-Fish', keys: ['filet-o-fish', 'filet o fish', 'filet', 'fish sandwich', 'fish filet'] },
      { t: 'Egg McMuffin', keys: ['egg mcmuffin', 'mcmuffin', 'egg muffin'] },
    ],
  },

  // ── Places & travel ───────────────────────────────────────────────────────

  {
    id: 'best-beaches-us',
    listId: 'best-beaches-us',
    publishedDate: '2026-06-11',
    title: 'Name the Best Beaches in the US',
    category: 'Travel',
    type: 'travel',
    tags: ['travel'],
    timeLimit: 120,
    blurb: 'From the Gulf Coast to the Oregon shore. State not required — just the beach or park name.',
    answers: [
      { t: 'Clearwater Beach (FL)', keys: ['clearwater'] },
      { t: 'Poipu Beach (Kauai, HI)', keys: ['poipu', 'kauai'] },
      { t: 'Assateague Island National Seashore (MD/VA)', keys: ['assateague'] },
      { t: 'Siesta Beach (Siesta Key, FL)', keys: ['siesta'] },
      { t: 'Caladesi Island State Park (Dunedin, FL)', keys: ['caladesi'] },
      { t: 'Cannon Beach (OR)', keys: ['cannon beach', 'cannon'] },
      { t: 'Pfeiffer Beach (Big Sur, CA)', keys: ['pfeiffer', 'big sur'] },
      { t: 'Driftwood Beach (Jekyll Island, GA)', keys: ['driftwood', 'jekyll'] },
      { t: 'St. Andrews State Park (Panama City Beach, FL)', keys: ['st. andrews', 'st andrews', 'panama city beach', 'panama city'] },
      { t: 'Carmel Beach (CA)', keys: ['carmel'] },
    ],
  },

  {
    id: 'college-towns-america',
    listId: 'college-towns-america',
    publishedDate: '2026-06-11',
    title: 'Name the Best College Towns in America',
    category: 'Travel',
    type: 'travel',
    tags: ['travel', 'other'],
    timeLimit: 90,
    blurb: 'The top ten college towns by quality of life, culture, and campus energy. City name alone is enough.',
    answers: [
      { t: 'Ann Arbor (Michigan)', keys: ['ann arbor'] },
      { t: 'Gainesville (Florida)', keys: ['gainesville'], anti: ['virginia'] },
      { t: 'Austin (Texas)', keys: ['austin'] },
      { t: 'Bozeman (Montana)', keys: ['bozeman'] },
      { t: 'Pullman (Washington)', keys: ['pullman'] },
      { t: 'Orlando (Florida)', keys: ['orlando'] },
      { t: 'Boone (North Carolina)', keys: ['boone'] },
      { t: 'Clemson (South Carolina)', keys: ['clemson'] },
      { t: 'East Lansing (Michigan)', keys: ['east lansing', 'lansing'] },
      { t: 'Moscow (Idaho)', keys: ['moscow idaho', 'moscow, idaho', 'moscow id'], anti: ['russia'] },
    ],
  },

  // ── Stadiums ──────────────────────────────────────────────────────────────

  {
    id: 'loudest-college-football-stadiums',
    listId: 'loudest-college-football-stadiums',
    publishedDate: '2026-06-11',
    title: 'Name the Loudest College Football Stadiums',
    category: 'Sports',
    type: 'entertainment',
    tags: ['entertainment', 'other'],
    timeLimit: 90,
    blurb: 'Stadium name, school name, team nickname, or famous nickname all accepted. How loud is your football knowledge?',
    answers: [
      { t: 'Ben Hill Griffin Stadium (Florida)', keys: ['ben hill griffin', 'florida', 'the swamp', 'swamp', 'gators'] },
      { t: 'Tiger Stadium (LSU)', keys: ['tiger stadium', 'lsu', 'death valley lsu', 'baton rouge'], anti: ['clemson', 'memorial stadium'] },
      { t: 'Neyland Stadium (Tennessee)', keys: ['neyland', 'tennessee', 'vols', 'knoxville'] },
      { t: 'Kyle Field (Texas A&M)', keys: ['kyle field', 'texas a&m', 'a&m', 'aggies'] },
      { t: 'Husky Stadium (Washington)', keys: ['husky stadium', 'washington', 'huskies', 'dawgs'] },
      { t: 'Memorial Stadium (Clemson)', keys: ['memorial stadium', 'clemson', 'clemson death valley'], anti: ['lsu', 'baton rouge'] },
      { t: 'Beaver Stadium (Penn State)', keys: ['beaver stadium', 'penn state', 'happy valley', 'nittany lions', 'nittany'] },
      { t: 'Autzen Stadium (Oregon)', keys: ['autzen', 'oregon', 'ducks', 'eugene'] },
      { t: 'Williams-Brice Stadium (South Carolina)', keys: ['williams-brice', 'williams brice', 'south carolina', 'gamecocks'] },
      { t: 'Ohio Stadium (Ohio State)', keys: ['ohio stadium', 'ohio state', 'horseshoe', 'the shoe', 'buckeyes', 'columbus'] },
    ],
  },

  // ── Director filmographies ────────────────────────────────────────────────

  {
    id: 'movies-david-fincher',
    listId: 'movies-david-fincher',
    publishedDate: '2026-06-11',
    title: 'Name the Best David Fincher Films',
    category: 'Cinema',
    type: 'entertainment',
    tags: ['entertainment'],
    timeLimit: 90,
    blurb: 'Ten films from the master of paranoid precision — from Se7en to The Social Network. Year or title alone accepted.',
    answers: [
      { t: 'The Social Network (2010)', keys: ['social network', 'facebook movie'] },
      { t: 'Se7en (1995)', keys: ['se7en', 'seven'] },
      { t: 'Fight Club (1999)', keys: ['fight club'] },
      { t: 'Gone Girl (2014)', keys: ['gone girl'] },
      { t: 'Zodiac (2007)', keys: ['zodiac'] },
      { t: 'The Girl with the Dragon Tattoo (2011)', keys: ['dragon tattoo', 'girl with the dragon tattoo', 'lisbeth salander'] },
      { t: 'The Game (1997)', keys: ['the game', 'fincher game'], anti: ['hunger', 'squid'] },
      { t: 'The Curious Case of Benjamin Button (2008)', keys: ['benjamin button', 'curious case'] },
      { t: 'The Killer (2023)', keys: ['the killer', 'fincher killer'] },
      { t: 'Mank (2020)', keys: ['mank'] },
    ],
  },

  {
    id: 'john-hughes-movies',
    listId: 'john-hughes-movies',
    publishedDate: '2026-06-11',
    title: 'Name the Best Movies Written by John Hughes',
    category: 'Cinema',
    type: 'entertainment',
    tags: ['entertainment'],
    timeLimit: 90,
    blurb: "The writer behind Ferris Bueller, The Breakfast Club, and Home Alone. Title alone works - skip the year.",
    answers: [
      { t: "Ferris Bueller's Day Off (1986)", keys: ["ferris bueller", "day off", "ferris"] },
      { t: 'The Breakfast Club (1985)', keys: ['breakfast club'] },
      { t: 'Home Alone (1990)', keys: ['home alone'], anti: ['home alone 2', 'lost in new york'] },
      { t: 'Planes, Trains and Automobiles (1987)', keys: ['planes, trains', 'planes trains', 'planes and trains'] },
      { t: "National Lampoon's Vacation (1983)", keys: ["lampoon vacation", 'vacation 1983', "national lampoon vacation"], anti: ['christmas vacation'] },
      { t: "National Lampoon's Christmas Vacation (1989)", keys: ['christmas vacation', 'griswold christmas', 'lampoon christmas'] },
      { t: 'Sixteen Candles (1984)', keys: ['sixteen candles', '16 candles'] },
      { t: 'Uncle Buck (1989)', keys: ['uncle buck'] },
      { t: 'Some Kind of Wonderful (1987)', keys: ['some kind of wonderful', 'wonderful 1987'] },
      { t: 'Home Alone 2: Lost in New York (1992)', keys: ['home alone 2', 'lost in new york'] },
    ],
  },


];

export function getQuiz(id) {
  return QUIZZES.find((q) => q.id === id);
}
