// Quiz definitions for /quiz/[id]. See getQuiz() at bottom.
//
// Each quiz plays as a timed "name them all" game.
//   id/listId  pair with /list/<id>
//   noun       used in the input placeholder ("Type a film…")
//   blurb      a NON-SPOILER prompt: describes what to name (the ranking
//              criterion/source), never the answers themselves.
//   answers    ranked slots (slot i = rank i+1): { t, keys[, anti] }
//                t = revealed display name; keys = lowercase substrings that
//                count as a correct guess; anti = substrings that BLOCK a match.

export const QUIZZES = [
  {
    id: "best-airlines-north-america",
    listId: "best-airlines-north-america",
    publishedDate: "2026-06-11",
    title: "Name the Best Airlines in North America",
    category: "Travel",
    type: "travel",
    tags: ["travel","other"],
    timeLimit: 90,
    noun: "airline",
    blurb: "The best airlines flying in North America, by the combined ranking of Skytrax, The Points Guy, the WSJ scorecard, and Cirium on-time data.",
    answers: [
      { t: "Delta Air Lines", keys: ["delta"] },
      { t: "United Airlines", keys: ["united"] },
      { t: "Alaska Airlines", keys: ["alaska"] },
      { t: "Southwest Airlines", keys: ["southwest","south west"] },
      { t: "JetBlue", keys: ["jetblue","jet blue"] },
      { t: "American Airlines", keys: ["american"] },
      { t: "Allegiant Air", keys: ["allegiant"] },
      { t: "Air Canada", keys: ["air canada"] },
      { t: "Frontier Airlines", keys: ["frontier"] },
      { t: "Porter Airlines", keys: ["porter"] },
    ],
  },
  {
    id: "top-grossing-films-1990",
    listId: "top-grossing-films-1990",
    publishedDate: "2026-06-11",
    title: "Name the Top-Grossing Films of 1990",
    category: "Movies · 1990",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "film",
    blurb: "The highest-grossing films of 1990, by worldwide box office.",
    answers: [
      { t: "Ghost", keys: ["ghost"] },
      { t: "Home Alone", keys: ["home alone"] },
      { t: "Pretty Woman", keys: ["pretty woman"] },
      { t: "Dances with Wolves", keys: ["dances with wolves"] },
      { t: "Total Recall", keys: ["total recall"] },
      { t: "Back to the Future Part III", keys: ["back to the future part iii"] },
      { t: "Die Hard 2", keys: ["die hard 2"] },
      { t: "Presumed Innocent", keys: ["presumed innocent"] },
      { t: "Teenage Mutant Ninja Turtles", keys: ["teenage mutant ninja turtles"] },
      { t: "Kindergarten Cop", keys: ["kindergarten cop"] },
    ],
  },
  {
    id: "top-grossing-films-1970s",
    listId: "top-grossing-films-1970s",
    publishedDate: "2026-06-11",
    title: "Name the Top-Grossing Films of the 1970s",
    category: "Movies · 1970s",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "film",
    blurb: "The highest-grossing films released in the 1970s, by worldwide box office.",
    answers: [
      { t: "Star Wars (1977)", keys: ["star wars"] },
      { t: "Jaws (1975)", keys: ["jaws"] },
      { t: "The Exorcist (1973)", keys: ["the exorcist","exorcist"] },
      { t: "Enter the Dragon (1973)", keys: ["enter the dragon"] },
      { t: "Grease (1978)", keys: ["grease"] },
      { t: "Close Encounters of the Third Kind (1977)", keys: ["close encounters of the third kind"] },
      { t: "Superman (1978)", keys: ["superman"] },
      { t: "Smokey and the Bandit (1977)", keys: ["smokey and the bandit","bandit"] },
      { t: "The Godfather (1972)", keys: ["the godfather","godfather"] },
      { t: "Saturday Night Fever (1977)", keys: ["saturday night fever"] },
    ],
  },
  {
    id: "top-grossing-films-1980s",
    listId: "top-grossing-films-1980s",
    publishedDate: "2026-06-11",
    title: "Name the Top-Grossing Films of the 1980s",
    category: "Movies · 1980s",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "film",
    blurb: "The highest-grossing films released in the 1980s, by worldwide box office.",
    answers: [
      { t: "E.T. the Extra-Terrestrial (1982)", keys: ["e t the extra terrestrial","extra terrestrial"] },
      { t: "Star Wars: The Empire Strikes Back (1980)", keys: ["star wars the empire strikes back","the empire strikes back","empire strikes back"] },
      { t: "Indiana Jones and the Last Crusade (1989)", keys: ["indiana jones and the last crusade","last crusade"] },
      { t: "Batman (1989)", keys: ["batman"] },
      { t: "Back to the Future (1985)", keys: ["back to the future"] },
      { t: "Star Wars: Return of the Jedi (1983)", keys: ["star wars return of the jedi","return of the jedi"] },
      { t: "Top Gun (1986)", keys: ["top gun"] },
      { t: "Rain Man (1988)", keys: ["rain man"] },
      { t: "Raiders of the Lost Ark (1981)", keys: ["raiders of the lost ark"] },
      { t: "Indiana Jones and the Temple of Doom (1984)", keys: ["indiana jones and the temple of doom","temple of doom"] },
    ],
  },
  {
    id: "top-grossing-films-1990s",
    listId: "top-grossing-films-1990s",
    publishedDate: "2026-06-11",
    title: "Name the Top-Grossing Films of the 1990s",
    category: "Movies · 1990s",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "film",
    blurb: "The highest-grossing films released in the 1990s, by worldwide box office.",
    answers: [
      { t: "Titanic (1997)", keys: ["titanic"] },
      { t: "Star Wars: The Phantom Menace (1999)", keys: ["star wars the phantom menace","the phantom menace","phantom menace"] },
      { t: "Jurassic Park (1993)", keys: ["jurassic park"], anti: ["lost world"] },
      { t: "Independence Day (1996)", keys: ["independence day"] },
      { t: "The Lion King (1994)", keys: ["the lion king","lion king"] },
      { t: "Forrest Gump (1994)", keys: ["forrest gump"] },
      { t: "The Sixth Sense (1999)", keys: ["the sixth sense","sixth sense"] },
      { t: "The Lost World: Jurassic Park (1997)", keys: ["the lost world","lost world"] },
      { t: "Men in Black (1997)", keys: ["men in black"] },
      { t: "Armageddon (1998)", keys: ["armageddon"] },
    ],
  },
  {
    id: "top-grossing-films-2000s",
    listId: "top-grossing-films-2000s",
    publishedDate: "2026-06-11",
    title: "Name the Top-Grossing Films of the 2000s",
    category: "Movies · 2000s",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "film",
    blurb: "The highest-grossing films released in the 2000s, by worldwide box office.",
    answers: [
      { t: "Avatar (2009)", keys: ["avatar"] },
      { t: "The Lord of the Rings: The Return of the King (2003)", keys: ["the lord of the rings the return of the king","the return of the king","lord of the rings the return of the king","return of the king"] },
      { t: "Pirates of the Caribbean: Dead Man's Chest (2006)", keys: ["pirates of the caribbean dead man s chest","dead man s chest"] },
      { t: "The Dark Knight (2008)", keys: ["the dark knight","dark knight"] },
      { t: "Harry Potter and the Sorcerer's Stone (2001)", keys: ["harry potter and the sorcerer s stone","sorcerer s stone","sorcerers stone","philosophers stone"] },
      { t: "Pirates of the Caribbean: At World's End (2007)", keys: ["pirates of the caribbean at world s end","at world s end"] },
      { t: "Harry Potter and the Order of the Phoenix (2007)", keys: ["harry potter and the order of the phoenix","order of the phoenix"] },
      { t: "Harry Potter and the Half-Blood Prince (2009)", keys: ["harry potter and the half blood prince","half blood prince"] },
      { t: "The Lord of the Rings: The Two Towers (2002)", keys: ["the lord of the rings the two towers","the two towers","lord of the rings the two towers","two towers"] },
      { t: "Shrek 2 (2004)", keys: ["shrek 2"] },
    ],
  },
  {
    id: "top-grossing-films-2010s",
    listId: "top-grossing-films-2010s",
    publishedDate: "2026-06-11",
    title: "Name the Top-Grossing Films of the 2010s",
    category: "Movies · 2010s",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "film",
    blurb: "The highest-grossing films released in the 2010s, by worldwide box office.",
    answers: [
      { t: "Avengers: Endgame (2019)", keys: ["avengers endgame","endgame"] },
      { t: "Star Wars: The Force Awakens (2015)", keys: ["star wars the force awakens","the force awakens","force awakens"] },
      { t: "Avengers: Infinity War (2018)", keys: ["avengers infinity war","infinity war"] },
      { t: "Jurassic World (2015)", keys: ["jurassic world"] },
      { t: "The Lion King (2019)", keys: ["the lion king","lion king"] },
      { t: "The Avengers (2012)", keys: ["the avengers"] },
      { t: "Furious 7 (2015)", keys: ["furious 7"] },
      { t: "Frozen II (2019)", keys: ["frozen ii"] },
      { t: "Avengers: Age of Ultron (2015)", keys: ["avengers age of ultron","age of ultron"] },
      { t: "Black Panther (2018)", keys: ["black panther"] },
    ],
  },
  {
    id: "top-grossing-films-inflation-adjusted",
    listId: "top-grossing-films-inflation-adjusted",
    publishedDate: "2026-06-11",
    title: "Name the Top-Grossing Films of All Time, Adjusted for Inflation",
    category: "Film",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "film",
    blurb: "The highest-grossing films of all time, adjusted for inflation.",
    answers: [
      { t: "Gone with the Wind (1939)", keys: ["gone with the wind"] },
      { t: "Avatar (2009)", keys: ["avatar"] },
      { t: "Titanic (1997)", keys: ["titanic"] },
      { t: "Star Wars (1977)", keys: ["star wars"], anti: ["force awakens"] },
      { t: "The Sound of Music (1965)", keys: ["the sound of music","sound of music"] },
      { t: "E.T. the Extra-Terrestrial (1982)", keys: ["e t the extra terrestrial","extra terrestrial"] },
      { t: "The Ten Commandments (1956)", keys: ["the ten commandments","ten commandments"] },
      { t: "Doctor Zhivago (1965)", keys: ["doctor zhivago"] },
      { t: "Star Wars: The Force Awakens (2015)", keys: ["star wars the force awakens","the force awakens","force awakens"] },
      { t: "Avengers: Endgame (2019)", keys: ["avengers endgame","endgame"] },
    ],
  },
  {
    id: "top-grossing-animated-films",
    listId: "top-grossing-animated-films",
    publishedDate: "2026-06-11",
    title: "Name the Top-Grossing Animated Films of All Time",
    category: "Film",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "film",
    blurb: "The highest-grossing animated films of all time, by worldwide box office.",
    answers: [
      { t: "Ne Zha 2 (2025)", keys: ["ne zha 2"] },
      { t: "Zootopia 2 (2025)", keys: ["zootopia 2"] },
      { t: "Inside Out 2 (2024)", keys: ["inside out 2"] },
      { t: "The Lion King (2019)", keys: ["the lion king","lion king"] },
      { t: "Frozen 2 (2019)", keys: ["frozen 2"] },
      { t: "The Super Mario Bros. Movie (2023)", keys: ["the super mario bros movie","super mario bros movie"] },
      { t: "Frozen (2013)", keys: ["frozen"] },
      { t: "Incredibles 2 (2018)", keys: ["incredibles 2"] },
      { t: "Minions (2015)", keys: ["minions"] },
      { t: "Toy Story 4 (2019)", keys: ["toy story 4"] },
    ],
  },
  {
    id: "most-expensive-movies",
    listId: "most-expensive-movies",
    publishedDate: "2026-06-11",
    title: "Name the Most Expensive Movies Ever Made",
    category: "Film",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "movie",
    blurb: "The most expensive films ever made, by production budget.",
    answers: [
      { t: "Star Wars: The Force Awakens (2015)", keys: ["star wars the force awakens","the force awakens","force awakens"] },
      { t: "Star Wars: The Rise of Skywalker (2019)", keys: ["star wars the rise of skywalker","the rise of skywalker","rise of skywalker"] },
      { t: "Jurassic World Dominion (2022)", keys: ["jurassic world dominion"] },
      { t: "Jurassic World: Fallen Kingdom (2018)", keys: ["jurassic world fallen kingdom","fallen kingdom"] },
      { t: "Deadpool & Wolverine (2024)", keys: ["deadpool wolverine"] },
      { t: "Fast X (2023)", keys: ["fast x"] },
      { t: "Pirates of the Caribbean: On Stranger Tides (2011)", keys: ["pirates of the caribbean on stranger tides","on stranger tides"] },
      { t: "Avengers: Age of Ultron (2015)", keys: ["avengers age of ultron","age of ultron"] },
      { t: "Avengers: Endgame (2019)", keys: ["avengers endgame","endgame"] },
      { t: "Indiana Jones and the Dial of Destiny (2023)", keys: ["indiana jones and the dial of destiny","dial of destiny"] },
    ],
  },
  {
    id: "best-selling-soundtracks-all-time",
    listId: "best-selling-soundtracks-all-time",
    publishedDate: "2026-06-11",
    title: "Name the Best-Selling Soundtracks of All Time",
    category: "Music",
    type: "entertainment",
    tags: ["entertainment","product"],
    timeLimit: 90,
    noun: "soundtrack",
    blurb: "The best-selling movie soundtrack albums of all time.",
    answers: [
      { t: "The Bodyguard (1992)", keys: ["the bodyguard","bodyguard"] },
      { t: "Saturday Night Fever (1977)", keys: ["saturday night fever"] },
      { t: "Dirty Dancing (1987)", keys: ["dirty dancing"] },
      { t: "Purple Rain (1984)", keys: ["purple rain"] },
      { t: "Titanic (1997)", keys: ["titanic"] },
      { t: "Grease (1978)", keys: ["grease"] },
      { t: "Forrest Gump (1994)", keys: ["forrest gump"] },
      { t: "Footloose (1984)", keys: ["footloose"] },
      { t: "Flashdance (1983)", keys: ["flashdance"] },
      { t: "Top Gun (1986)", keys: ["top gun"] },
    ],
  },
  {
    id: "top-grossing-film-franchises",
    listId: "top-grossing-film-franchises",
    publishedDate: "2026-06-11",
    title: "Name the Top-Grossing Film Franchises of All Time",
    category: "Film",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "franchise",
    blurb: "The highest-grossing film franchises of all time, by total box office.",
    answers: [
      { t: "Marvel Cinematic Universe", keys: ["marvel cinematic universe","mcu","marvel"] },
      { t: "Spider-Man", keys: ["spider man","spiderman"] },
      { t: "Star Wars", keys: ["star wars"] },
      { t: "Wizarding World", keys: ["wizarding world","harry potter","wizarding"] },
      { t: "James Bond", keys: ["james bond","007","bond"] },
      { t: "DC Extended Universe", keys: ["dc extended universe","dceu","dc universe"] },
      { t: "The Fast and the Furious", keys: ["the fast and the furious","fast and furious","fast furious","fast and the furious"] },
      { t: "Batman", keys: ["batman"] },
      { t: "Jurassic Park", keys: ["jurassic park"] },
      { t: "X-Men", keys: ["x men","xmen"] },
    ],
  },
  {
    id: "top-grossing-actors",
    listId: "top-grossing-actors",
    publishedDate: "2026-06-11",
    title: "Name the Top-Grossing Actors and Actresses of All Time",
    category: "Film",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "actor",
    blurb: "The highest-grossing actors of all time, by the cumulative box office of their films.",
    answers: [
      { t: "Zoe Saldana", keys: ["zoe saldana","saldana"] },
      { t: "Scarlett Johansson", keys: ["scarlett johansson","johansson"] },
      { t: "Samuel L. Jackson", keys: ["samuel l jackson","jackson"] },
      { t: "Robert Downey Jr.", keys: ["robert downey jr","downey"] },
      { t: "Chris Pratt", keys: ["chris pratt","pratt"] },
      { t: "Tom Cruise", keys: ["tom cruise","cruise"] },
      { t: "Chris Hemsworth", keys: ["chris hemsworth","hemsworth"] },
      { t: "Vin Diesel", keys: ["vin diesel","diesel"] },
      { t: "Chris Evans", keys: ["chris evans","evans"] },
      { t: "Dwayne Johnson", keys: ["dwayne johnson","johnson","the rock","rock"] },
    ],
  },
  {
    id: "top-grossing-directors",
    listId: "top-grossing-directors",
    publishedDate: "2026-06-11",
    title: "Name the Top-Grossing Directors of All Time",
    category: "Film",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "director",
    blurb: "The highest-grossing film directors of all time, by total box office.",
    answers: [
      { t: "Steven Spielberg", keys: ["steven spielberg","spielberg"] },
      { t: "James Cameron", keys: ["james cameron","cameron"] },
      { t: "The Russo Brothers", keys: ["the russo brothers","brothers","russo brothers"] },
      { t: "Peter Jackson", keys: ["peter jackson","jackson"] },
      { t: "Michael Bay", keys: ["michael bay","bay"] },
      { t: "David Yates", keys: ["david yates","yates"] },
      { t: "Christopher Nolan", keys: ["christopher nolan","nolan"] },
      { t: "Ridley Scott", keys: ["ridley scott","scott"] },
      { t: "Tim Burton", keys: ["tim burton","burton"] },
      { t: "J.J. Abrams", keys: ["j j abrams","abrams"] },
    ],
  },
  {
    id: "highest-grossing-directors",
    listId: "highest-grossing-directors",
    publishedDate: "2026-06-11",
    title: "Name the Highest-Grossing Film Directors of All Time",
    category: "Box Office",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "director",
    blurb: "The highest-grossing film directors of all time, by cumulative worldwide box office.",
    answers: [
      { t: "Steven Spielberg", keys: ["steven spielberg","spielberg"] },
      { t: "James Cameron", keys: ["james cameron","cameron"] },
      { t: "Russo Brothers", keys: ["russo brothers","brothers"] },
      { t: "Peter Jackson", keys: ["peter jackson","jackson"] },
      { t: "Michael Bay", keys: ["michael bay","bay"] },
      { t: "David Yates", keys: ["david yates","yates"] },
      { t: "Christopher Nolan", keys: ["christopher nolan","nolan"] },
      { t: "Ridley Scott", keys: ["ridley scott","scott"] },
      { t: "Tim Burton", keys: ["tim burton","burton"] },
      { t: "J.J. Abrams", keys: ["j j abrams","abrams"] },
    ],
  },
  {
    id: "top-songs-1960s",
    listId: "top-songs-1960s",
    publishedDate: "2026-06-11",
    title: "Name the Top Songs of the 1960s",
    category: "Music",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "song",
    blurb: "The biggest hit songs of the 1960s on the US year-end charts.",
    answers: [
      { t: "The Twist (Chubby Checker)", keys: ["the twist","twist"] },
      { t: "Hey Jude (The Beatles)", keys: ["hey jude"] },
      { t: "Theme from A Summer Place (Percy Faith)", keys: ["theme from a summer place"] },
      { t: "Tossin' and Turnin' (Bobby Lewis)", keys: ["tossin and turnin"] },
      { t: "I Want to Hold Your Hand (The Beatles)", keys: ["i want to hold your hand"] },
      { t: "I'm a Believer (The Monkees)", keys: ["i m a believer"] },
      { t: "Aquarius / Let the Sunshine In (The 5th Dimension)", keys: ["aquarius let the sunshine in"] },
      { t: "Sugar, Sugar (The Archies)", keys: ["sugar sugar"] },
      { t: "I Heard It Through the Grapevine (Marvin Gaye)", keys: ["i heard it through the grapevine"] },
      { t: "Are You Lonesome Tonight? (Elvis Presley)", keys: ["are you lonesome tonight"] },
    ],
  },
  {
    id: "top-songs-1970s",
    listId: "top-songs-1970s",
    publishedDate: "2026-06-11",
    title: "Name the Top Songs of the 1970s",
    category: "Music",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "song",
    blurb: "The biggest hit songs of the 1970s on the US year-end charts.",
    answers: [
      { t: "You Light Up My Life (Debby Boone)", keys: ["you light up my life"] },
      { t: "Tonight's the Night (Rod Stewart)", keys: ["tonight s the night"] },
      { t: "Le Freak (Chic)", keys: ["le freak"] },
      { t: "How Deep Is Your Love (Bee Gees)", keys: ["how deep is your love"] },
      { t: "I Just Want to Be Your Everything (Andy Gibb)", keys: ["i just want to be your everything"] },
      { t: "Silly Love Songs (Wings)", keys: ["silly love songs"] },
      { t: "Let's Get It On (Marvin Gaye)", keys: ["let s get it on"] },
      { t: "Night Fever (Bee Gees)", keys: ["night fever"] },
      { t: "Tie a Yellow Ribbon Round the Ole Oak Tree (Tony Orlando and Dawn)", keys: ["tie a yellow ribbon round the ole oak tree"] },
      { t: "Shadow Dancing (Andy Gibb)", keys: ["shadow dancing"] },
    ],
  },
  {
    id: "top-songs-1980s",
    listId: "top-songs-1980s",
    publishedDate: "2026-06-11",
    title: "Name the Top Songs of the 1980s",
    category: "Music",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "song",
    blurb: "The biggest hit songs of the 1980s on the US year-end charts.",
    answers: [
      { t: "Physical (Olivia Newton-John)", keys: ["physical"] },
      { t: "Bette Davis Eyes (Kim Carnes)", keys: ["bette davis eyes"] },
      { t: "Endless Love (Diana Ross and Lionel Richie)", keys: ["endless love"] },
      { t: "Eye of the Tiger (Survivor)", keys: ["eye of the tiger"] },
      { t: "Every Breath You Take (The Police)", keys: ["every breath you take"] },
      { t: "Flashdance... What a Feeling (Irene Cara)", keys: ["flashdance what a feeling"] },
      { t: "Another One Bites the Dust (Queen)", keys: ["another one bites the dust"] },
      { t: "Say Say Say (Paul McCartney and Michael Jackson)", keys: ["say say say"] },
      { t: "Call Me (Blondie)", keys: ["call me"] },
      { t: "Lady (Kenny Rogers)", keys: ["lady"] },
    ],
  },
  {
    id: "top-songs-1990s",
    listId: "top-songs-1990s",
    publishedDate: "2026-06-11",
    title: "Name the Top Songs of the 1990s",
    category: "Music",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "song",
    blurb: "The biggest hit songs of the 1990s on the US year-end charts.",
    answers: [
      { t: "How Do I Live (LeAnn Rimes)", keys: ["how do i live"] },
      { t: "Macarena (Los Del Rio)", keys: ["macarena"] },
      { t: "Un-Break My Heart (Toni Braxton)", keys: ["un break my heart"] },
      { t: "You Were Meant for Me / Foolish Games (Jewel)", keys: ["you were meant for me foolish games"] },
      { t: "(Everything I Do) I Do It for You (Bryan Adams)", keys: ["everything i do i do it for you"] },
      { t: "I'll Make Love to You (Boyz II Men)", keys: ["i ll make love to you"] },
      { t: "Too Close (Next)", keys: ["too close"] },
      { t: "One Sweet Day (Mariah Carey and Boyz II Men)", keys: ["one sweet day"] },
      { t: "Truly Madly Deeply (Savage Garden)", keys: ["truly madly deeply"] },
      { t: "Candle in the Wind 1997 (Elton John)", keys: ["candle in the wind 1997"] },
    ],
  },
  {
    id: "top-songs-2000s",
    listId: "top-songs-2000s",
    publishedDate: "2026-06-11",
    title: "Name the Top Songs of the 2000s",
    category: "Music",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "song",
    blurb: "The biggest hit songs of the 2000s on the US year-end charts.",
    answers: [
      { t: "We Belong Together (Mariah Carey)", keys: ["we belong together"] },
      { t: "Yeah! (Usher feat. Lil Jon and Ludacris)", keys: ["yeah"] },
      { t: "Low (Flo Rida feat. T-Pain)", keys: ["low"] },
      { t: "I Gotta Feeling (The Black Eyed Peas)", keys: ["i gotta feeling"] },
      { t: "How You Remind Me (Nickelback)", keys: ["how you remind me"] },
      { t: "No One (Alicia Keys)", keys: ["no one"] },
      { t: "Boom Boom Pow (The Black Eyed Peas)", keys: ["boom boom pow"] },
      { t: "Let Me Love You (Mario)", keys: ["let me love you"] },
      { t: "Gold Digger (Kanye West feat. Jamie Foxx)", keys: ["gold digger"] },
      { t: "Apologize (Timbaland feat. OneRepublic)", keys: ["apologize"] },
    ],
  },
  {
    id: "top-songs-2010s",
    listId: "top-songs-2010s",
    publishedDate: "2026-06-11",
    title: "Name the Top Songs of the 2010s",
    category: "Music",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "song",
    blurb: "The biggest hit songs of the 2010s on the US year-end charts.",
    answers: [
      { t: "Uptown Funk (Mark Ronson feat. Bruno Mars)", keys: ["uptown funk"] },
      { t: "Party Rock Anthem (LMFAO)", keys: ["party rock anthem"] },
      { t: "Shape of You (Ed Sheeran)", keys: ["shape of you"] },
      { t: "Closer (The Chainsmokers feat. Halsey)", keys: ["closer"] },
      { t: "Girls Like You (Maroon 5 feat. Cardi B)", keys: ["girls like you"] },
      { t: "We Found Love (Rihanna feat. Calvin Harris)", keys: ["we found love"] },
      { t: "Old Town Road (Lil Nas X feat. Billy Ray Cyrus)", keys: ["old town road"] },
      { t: "Somebody That I Used to Know (Gotye feat. Kimbra)", keys: ["somebody that i used to know"] },
      { t: "Despacito (Luis Fonsi and Daddy Yankee feat. Justin Bieber)", keys: ["despacito"] },
      { t: "Rolling in the Deep (Adele)", keys: ["rolling in the deep"] },
    ],
  },
  {
    id: "most-weeks-billboard-hot-100",
    listId: "most-weeks-billboard-hot-100",
    publishedDate: "2026-06-11",
    title: "Name the Songs With the Most Weeks on the Billboard Hot 100",
    category: "Music · Hot 100",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "song",
    blurb: "The songs that have spent the most weeks on the Billboard Hot 100.",
    answers: [
      { t: "Lose Control (Teddy Swims)", keys: ["lose control"] },
      { t: "Heat Waves (Glass Animals)", keys: ["heat waves"] },
      { t: "Blinding Lights (The Weeknd)", keys: ["blinding lights"] },
      { t: "Beautiful Things (Benson Boone)", keys: ["beautiful things"] },
      { t: "Radioactive (Imagine Dragons)", keys: ["radioactive"] },
      { t: "Sail (AWOLNATION)", keys: ["sail"] },
      { t: "All I Want for Christmas Is You (Mariah Carey)", keys: ["all i want for christmas is you"] },
      { t: "Levitating (Dua Lipa)", keys: ["levitating"] },
      { t: "I'm Yours (Jason Mraz)", keys: ["i m yours"] },
      { t: "Snooze (SZA)", keys: ["snooze"] },
    ],
  },
  {
    id: "best-selling-albums-all-time",
    listId: "best-selling-albums-all-time",
    publishedDate: "2026-06-11",
    title: "Name the Best-Selling Albums of All Time",
    category: "Music",
    type: "entertainment",
    tags: ["entertainment","product"],
    timeLimit: 90,
    noun: "album",
    blurb: "The best-selling albums of all time, by certified worldwide sales.",
    answers: [
      { t: "Thriller (Michael Jackson)", keys: ["thriller"] },
      { t: "Back in Black (AC/DC)", keys: ["back in black"] },
      { t: "The Bodyguard (Whitney Houston)", keys: ["the bodyguard","bodyguard"] },
      { t: "The Dark Side of the Moon (Pink Floyd)", keys: ["the dark side of the moon","dark side of the moon"] },
      { t: "Their Greatest Hits 1971-1975 (Eagles)", keys: ["their greatest hits 1971 1975","greatest hits"] },
      { t: "Hotel California (Eagles)", keys: ["hotel california"] },
      { t: "Come On Over (Shania Twain)", keys: ["come on over"] },
      { t: "Rumours (Fleetwood Mac)", keys: ["rumours"] },
      { t: "Bat Out of Hell (Meat Loaf)", keys: ["bat out of hell"] },
      { t: "Saturday Night Fever (Bee Gees)", keys: ["saturday night fever"] },
    ],
  },
  {
    id: "best-selling-singles",
    listId: "best-selling-singles",
    publishedDate: "2026-06-11",
    title: "Name the Best-Selling Singles of All Time",
    category: "Music",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "single",
    blurb: "The best-selling singles of all time, by worldwide sales.",
    answers: [
      { t: "Spotlight (Xiao Zhan)", keys: ["spotlight"] },
      { t: "White Christmas (Bing Crosby)", keys: ["white christmas"] },
      { t: "Candle in the Wind 1997 (Elton John)", keys: ["candle in the wind 1997"] },
      { t: "Silent Night (Bing Crosby)", keys: ["silent night"] },
      { t: "Petit Papa Noël (Tino Rossi)", keys: ["petit papa no l"] },
      { t: "Rock Around the Clock (Bill Haley & His Comets)", keys: ["rock around the clock"] },
      { t: "I Will Always Love You (Whitney Houston)", keys: ["i will always love you"] },
      { t: "Rolling in the Deep (Adele)", keys: ["rolling in the deep"] },
      { t: "It's Now or Never (Elvis Presley)", keys: ["it s now or never"] },
      { t: "We Are the World (USA for Africa)", keys: ["we are the world"] },
    ],
  },
  {
    id: "most-streamed-spotify-songs",
    listId: "most-streamed-spotify-songs",
    publishedDate: "2026-06-11",
    title: "Name the Most-Streamed Songs on Spotify",
    category: "Music",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "song",
    blurb: "The most-streamed songs in Spotify history.",
    answers: [
      { t: "Blinding Lights (The Weeknd)", keys: ["blinding lights"] },
      { t: "Shape of You (Ed Sheeran)", keys: ["shape of you"] },
      { t: "Sweater Weather (The Neighbourhood)", keys: ["sweater weather"] },
      { t: "Starboy (The Weeknd feat. Daft Punk)", keys: ["starboy"] },
      { t: "As It Was (Harry Styles)", keys: ["as it was"] },
      { t: "Someone You Loved (Lewis Capaldi)", keys: ["someone you loved"] },
      { t: "Sunflower (Post Malone & Swae Lee)", keys: ["sunflower"] },
      { t: "One Dance (Drake)", keys: ["one dance"] },
      { t: "Perfect (Ed Sheeran)", keys: ["perfect"] },
      { t: "STAY (The Kid LAROI & Justin Bieber)", keys: ["stay"] },
    ],
  },
  {
    id: "most-viewed-music-videos",
    listId: "most-viewed-music-videos",
    publishedDate: "2026-06-11",
    title: "Name the Most-Viewed Music Videos on YouTube",
    category: "Music",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "music video",
    blurb: "The most-viewed music videos on YouTube.",
    answers: [
      { t: "Despacito (Luis Fonsi feat. Daddy Yankee)", keys: ["despacito"] },
      { t: "See You Again (Wiz Khalifa feat. Charlie Puth)", keys: ["see you again"] },
      { t: "Shape of You (Ed Sheeran)", keys: ["shape of you"] },
      { t: "Gangnam Style (PSY)", keys: ["gangnam style"] },
      { t: "Axel F (Crazy Frog)", keys: ["axel f"] },
      { t: "Uptown Funk (Mark Ronson feat. Bruno Mars)", keys: ["uptown funk"] },
      { t: "Dame Tu Cosita (El Chombo)", keys: ["dame tu cosita"] },
      { t: "Shree Hanuman Chalisa (Gulshan Kumar)", keys: ["shree hanuman chalisa"] },
      { t: "Waka Waka (This Time for Africa) (Shakira)", keys: ["waka waka"] },
      { t: "Counting Stars (OneRepublic)", keys: ["counting stars"] },
    ],
  },
  {
    id: "top-grossing-concert-tours",
    listId: "top-grossing-concert-tours",
    publishedDate: "2026-06-11",
    title: "Name the Top-Grossing Concert Tours of All Time",
    category: "Music",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "tour",
    blurb: "The highest-grossing concert tours of all time, by gross revenue.",
    answers: [
      { t: "The Eras Tour (Taylor Swift)", keys: ["the eras tour","eras tour"] },
      { t: "Music of the Spheres World Tour (Coldplay)", keys: ["music of the spheres world tour"] },
      { t: "Farewell Yellow Brick Road (Elton John)", keys: ["farewell yellow brick road"] },
      { t: "Mathematics Tour (Ed Sheeran)", keys: ["mathematics tour"] },
      { t: "Divide Tour (Ed Sheeran)", keys: ["divide tour"] },
      { t: "360° Tour (U2)", keys: ["360 tour"] },
      { t: "2023 to 2025 Tour (Bruce Springsteen and the E Street Band)", keys: ["2023 to 2025 tour"] },
      { t: "After Hours til Dawn Tour (The Weeknd)", keys: ["after hours til dawn tour"] },
      { t: "Love On Tour (Harry Styles)", keys: ["love on tour"] },
      { t: "Summer Carnival (Pink)", keys: ["summer carnival"] },
    ],
  },
  {
    id: "best-selling-books",
    listId: "best-selling-books",
    publishedDate: "2026-06-11",
    title: "Name the Best-Selling Non-Religious Books of All Time",
    category: "Books",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "book",
    blurb: "The best-selling non-religious books of all time, by copies sold.",
    answers: [
      { t: "A Tale of Two Cities (Charles Dickens)", keys: ["a tale of two cities","tale of two cities"] },
      { t: "The Little Prince (Antoine de Saint-Exupéry)", keys: ["the little prince","little prince"] },
      { t: "The Alchemist (Paulo Coelho)", keys: ["the alchemist","alchemist"] },
      { t: "Harry Potter and the Philosopher's Stone (J. K. Rowling)", keys: ["harry potter and the philosopher s stone"] },
      { t: "And Then There Were None (Agatha Christie)", keys: ["and then there were none"] },
      { t: "Dream of the Red Chamber (Cao Xueqin)", keys: ["dream of the red chamber"] },
      { t: "The Hobbit (J. R. R. Tolkien)", keys: ["the hobbit","hobbit"] },
      { t: "Alice's Adventures in Wonderland (Lewis Carroll)", keys: ["alice s adventures in wonderland"] },
      { t: "She: A History of Adventure (H. Rider Haggard)", keys: ["she a history of adventure"] },
      { t: "The Da Vinci Code (Dan Brown)", keys: ["the da vinci code","da vinci code"] },
    ],
  },
  {
    id: "highest-grossing-video-games",
    listId: "highest-grossing-video-games",
    publishedDate: "2026-06-11",
    title: "Name the Highest-Grossing Video Games of All Time",
    category: "Video Games",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "game",
    blurb: "The highest-grossing video games of all time, by total revenue.",
    answers: [
      { t: "Dungeon Fighter Online", keys: ["dungeon fighter online"] },
      { t: "Fortnite", keys: ["fortnite"] },
      { t: "Honor of Kings", keys: ["honor of kings"] },
      { t: "PUBG: Battlegrounds", keys: ["pubg battlegrounds","pubg"] },
      { t: "League of Legends", keys: ["league of legends","lol"] },
      { t: "Pac-Man", keys: ["pac man","pacman"] },
      { t: "CrossFire", keys: ["crossfire"] },
      { t: "World of Warcraft", keys: ["world of warcraft","wow"] },
      { t: "Candy Crush Saga", keys: ["candy crush saga","candy crush"] },
      { t: "Monster Strike", keys: ["monster strike"] },
    ],
  },
  {
    id: "highest-grossing-console-video-games",
    listId: "highest-grossing-console-video-games",
    publishedDate: "2026-06-11",
    title: "Name the Highest-Grossing Console Video Games of All Time",
    category: "Video Games",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "game",
    blurb: "The highest-grossing console video games of all time, by total revenue.",
    answers: [
      { t: "Fortnite", keys: ["fortnite"] },
      { t: "PUBG: Battlegrounds", keys: ["pubg battlegrounds","pubg"] },
      { t: "Grand Theft Auto V", keys: ["grand theft auto v","gta v","gta 5","grand theft auto"] },
      { t: "Wii Sports", keys: ["wii sports"] },
      { t: "Wii Fit", keys: ["wii fit"] },
      { t: "Mario Kart 8 Deluxe", keys: ["mario kart 8 deluxe","mario kart"] },
      { t: "Apex Legends", keys: ["apex legends"] },
      { t: "Super Mario Bros.", keys: ["super mario bros","super mario"] },
      { t: "Final Fantasy XIV", keys: ["final fantasy xiv","ff14","final fantasy 14"] },
      { t: "Minecraft", keys: ["minecraft"] },
    ],
  },
  {
    id: "best-selling-games-all-time",
    listId: "best-selling-games-all-time",
    publishedDate: "2026-06-11",
    title: "Name the Best-Selling Video Games of All Time",
    category: "Games",
    type: "entertainment",
    tags: ["entertainment","other"],
    timeLimit: 90,
    noun: "game",
    blurb: "The best-selling video games of all time, by units sold.",
    answers: [
      { t: "Tetris", keys: ["tetris"] },
      { t: "Minecraft", keys: ["minecraft"] },
      { t: "Grand Theft Auto V", keys: ["grand theft auto v","gta v","gta 5","grand theft auto"] },
      { t: "Wii Sports", keys: ["wii sports"] },
      { t: "Red Dead Redemption 2", keys: ["red dead redemption 2","red dead","rdr2"] },
      { t: "Mario Kart 8 / Deluxe", keys: ["mario kart 8 deluxe","mario kart"] },
      { t: "PUBG: Battlegrounds", keys: ["pubg battlegrounds","pubg"] },
      { t: "Terraria", keys: ["terraria"] },
      { t: "The Witcher 3: Wild Hunt", keys: ["the witcher 3 wild hunt","witcher 3","the witcher","witcher 3 wild hunt","witcher"] },
      { t: "Super Mario Bros.", keys: ["super mario bros","super mario"] },
    ],
  },
  {
    id: "best-selling-cars-all-time",
    listId: "best-selling-cars-all-time",
    publishedDate: "2026-06-11",
    title: "Name the Best-Selling Cars of All Time",
    category: "Cars",
    type: "product",
    tags: ["product","tech"],
    timeLimit: 90,
    noun: "car",
    blurb: "The best-selling car models of all time, by units sold.",
    answers: [
      { t: "Toyota Corolla", keys: ["toyota corolla","corolla"] },
      { t: "Ford F-Series", keys: ["ford f series","f series","f150","f 150"] },
      { t: "Volkswagen Golf", keys: ["volkswagen golf","golf","vw golf"] },
      { t: "Volkswagen Passat", keys: ["volkswagen passat","passat"] },
      { t: "Honda Civic", keys: ["honda civic","civic"] },
      { t: "Toyota Camry", keys: ["toyota camry","camry"] },
      { t: "Ford Fiesta", keys: ["ford fiesta","fiesta"] },
      { t: "Volkswagen Beetle", keys: ["volkswagen beetle","beetle"] },
      { t: "Toyota Hilux", keys: ["toyota hilux","hilux"] },
      { t: "Honda Accord", keys: ["honda accord","accord"] },
    ],
  },
  {
    id: "most-subscribed-youtube-channels",
    listId: "most-subscribed-youtube-channels",
    publishedDate: "2026-06-11",
    title: "Name the Most-Subscribed YouTube Channels",
    category: "Internet",
    type: "entertainment",
    tags: ["entertainment","tech"],
    timeLimit: 90,
    noun: "channel",
    blurb: "The most-subscribed channels on YouTube.",
    answers: [
      { t: "MrBeast", keys: ["mrbeast","mr beast"] },
      { t: "T-Series", keys: ["t series","tseries"] },
      { t: "Cocomelon - Nursery Rhymes", keys: ["cocomelon nursery rhymes","cocomelon"] },
      { t: "SET India", keys: ["set india"] },
      { t: "Vlad and Niki", keys: ["vlad and niki"] },
      { t: "Stokes Twins", keys: ["stokes twins"] },
      { t: "Kids Diana Show", keys: ["kids diana show"] },
      { t: "Like Nastya", keys: ["like nastya"] },
      { t: "Kimpro", keys: ["kimpro"] },
      { t: "Zee Music Company", keys: ["zee music company","zee music"] },
    ],
  },
  {
    id: "most-followed-instagram-accounts",
    listId: "most-followed-instagram-accounts",
    publishedDate: "2026-06-11",
    title: "Name the Most-Followed Instagram Accounts",
    category: "Internet",
    type: "entertainment",
    tags: ["entertainment","tech"],
    timeLimit: 90,
    noun: "account",
    blurb: "The most-followed accounts on Instagram.",
    answers: [
      { t: "Instagram", keys: ["instagram"] },
      { t: "Cristiano Ronaldo", keys: ["cristiano ronaldo","ronaldo","cristiano"] },
      { t: "Lionel Messi", keys: ["lionel messi","messi"] },
      { t: "Selena Gomez", keys: ["selena gomez","selena"] },
      { t: "Kylie Jenner", keys: ["kylie jenner","kylie"] },
      { t: "Dwayne Johnson", keys: ["dwayne johnson","the rock","therock"] },
      { t: "Ariana Grande", keys: ["ariana grande","ariana"] },
      { t: "Kim Kardashian", keys: ["kim kardashian","kim k"] },
      { t: "Beyoncé", keys: ["beyonce","beyonc"] },
      { t: "Khloé Kardashian", keys: ["khloe kardashian","khloe"] },
    ],
  },
  {
    id: "most-visited-theme-parks",
    listId: "most-visited-theme-parks",
    publishedDate: "2026-06-11",
    title: "Name the Most Visited Theme Parks in the World",
    category: "Travel",
    type: "travel",
    tags: ["travel","entertainment"],
    timeLimit: 90,
    noun: "theme park",
    blurb: "The most-visited theme parks in the world, by annual attendance.",
    answers: [
      { t: "Magic Kingdom (Walt Disney World)", keys: ["magic kingdom"] },
      { t: "Disneyland Park (Anaheim)", keys: ["disneyland anaheim","anaheim"] },
      { t: "Universal Studios Japan", keys: ["universal studios japan","universal japan","usj"] },
      { t: "Tokyo Disneyland", keys: ["tokyo disneyland"] },
      { t: "Shanghai Disneyland", keys: ["shanghai disneyland"] },
      { t: "Chimelong Ocean Kingdom", keys: ["chimelong"] },
      { t: "Tokyo DisneySea", keys: ["tokyo disneysea","disneysea"] },
      { t: "EPCOT", keys: ["epcot"] },
      { t: "Disney's Hollywood Studios", keys: ["hollywood studios"] },
      { t: "Disneyland Paris", keys: ["disneyland paris","paris"] },
    ],
  },
  {
    id: "most-visited-us-national-parks",
    listId: "most-visited-us-national-parks",
    publishedDate: "2026-06-11",
    title: "Name the Most Visited US National Parks",
    category: "Travel",
    type: "travel",
    tags: ["travel"],
    timeLimit: 90,
    noun: "national park",
    blurb: "The most-visited national parks in the US, by annual visitors.",
    answers: [
      { t: "Great Smoky Mountains National Park", keys: ["great smoky mountains national park","great smoky mountains"] },
      { t: "Zion National Park", keys: ["zion national park","zion"] },
      { t: "Grand Canyon National Park", keys: ["grand canyon national park","grand canyon"] },
      { t: "Yellowstone National Park", keys: ["yellowstone national park","yellowstone"] },
      { t: "Rocky Mountain National Park", keys: ["rocky mountain national park","rocky mountain"] },
      { t: "Yosemite National Park", keys: ["yosemite national park","yosemite"] },
      { t: "Acadia National Park", keys: ["acadia national park","acadia"] },
      { t: "Olympic National Park", keys: ["olympic national park","olympic"] },
      { t: "Grand Teton National Park", keys: ["grand teton national park","grand teton"] },
      { t: "Glacier National Park", keys: ["glacier national park","glacier"] },
    ],
  },
  {
    id: "largest-university-endowments",
    listId: "largest-university-endowments",
    publishedDate: "2026-06-11",
    title: "Name the Largest University Endowments",
    category: "Education",
    type: "other",
    tags: ["other"],
    timeLimit: 90,
    noun: "university",
    blurb: "The US universities with the largest endowments.",
    answers: [
      { t: "Harvard University", keys: ["harvard"] },
      { t: "University of Texas System", keys: ["university of texas","ut system","texas system"], anti: ["a m","a and m","aggie"] },
      { t: "Yale University", keys: ["yale"] },
      { t: "Stanford University", keys: ["stanford"] },
      { t: "Princeton University", keys: ["princeton"] },
      { t: "Massachusetts Institute of Technology", keys: ["mit","massachusetts institute"] },
      { t: "Texas A&M University System", keys: ["texas a m","texas a and m","aggies"] },
      { t: "University of Pennsylvania", keys: ["pennsylvania","upenn","penn"] },
      { t: "University of Michigan", keys: ["michigan"] },
      { t: "University of California System", keys: ["university of california","uc system"] },
    ],
  },
  {
    id: "top-grossing-broadway-shows",
    listId: "top-grossing-broadway-shows",
    publishedDate: "2026-06-11",
    title: "Name the Top-Grossing Broadway Shows of All Time",
    category: "Theater",
    type: "entertainment",
    tags: ["entertainment"],
    timeLimit: 90,
    noun: "show",
    blurb: "The highest-grossing Broadway shows of all time.",
    answers: [
      { t: "The Lion King", keys: ["the lion king","lion king"] },
      { t: "Wicked", keys: ["wicked"] },
      { t: "The Phantom of the Opera", keys: ["the phantom of the opera","phantom of the opera"] },
      { t: "Hamilton", keys: ["hamilton"] },
      { t: "The Book of Mormon", keys: ["the book of mormon","book of mormon"] },
      { t: "Chicago", keys: ["chicago"] },
      { t: "Aladdin", keys: ["aladdin"] },
      { t: "Mamma Mia!", keys: ["mamma mia"] },
      { t: "Jersey Boys", keys: ["jersey boys"] },
      { t: "Les Miserables", keys: ["les miserables","les mis"] },
    ],
  },
  {
    id: "world-cup-winners",
    publishedDate: "2026-06-11",
    title: "Name the Last 10 World Cup Winners",
    category: "Soccer",
    type: "entertainment",
    tags: ["entertainment","other"],
    timeLimit: 90,
    noun: "country",
    format: "matched",
    source: { label: "FIFA: World Cup Champions, 1982-2022", url: "https://www.fifa.com/en/tournaments/mens/worldcup/articles/world-cup-champions-1982-2022-italy-argentina-germany-brazil-france-spain" },
    blurb: "The men's FIFA World Cup champions from the last ten tournaments. Each slot is a year: name the country that lifted the trophy.",
    answers: [
      { label: "2022", t: "Argentina", keys: ["argentina"] },
      { label: "2018", t: "France", keys: ["france"] },
      { label: "2014", t: "Germany", keys: ["germany"] },
      { label: "2010", t: "Spain", keys: ["spain"] },
      { label: "2006", t: "Italy", keys: ["italy"] },
      { label: "2002", t: "Brazil", keys: ["brazil"] },
      { label: "1998", t: "France", keys: ["france"] },
      { label: "1994", t: "Brazil", keys: ["brazil"] },
      { label: "1990", t: "West Germany", keys: ["west germany","germany"] },
      { label: "1986", t: "Argentina", keys: ["argentina"] },
    ],
  },
  {
    id: 'busiest-airports-world',
    listId: 'busiest-airports-world',
    publishedDate: '2026-06-11',
    title: 'Name the Busiest Airports in the World',
    category: 'Travel',
    type: 'travel',
    tags: ['travel', 'other'],
    timeLimit: 90,
    blurb: 'The world\'s ten busiest airports by total 2025 passenger traffic, per Airports Council International. Ninety seconds. Name all ten.',
    answers: [
      { t: 'Hartsfield-Jackson Atlanta (ATL)', keys: ['atlanta', 'hartsfield', 'atl'] },
      { t: 'Dubai International (DXB)', keys: ['dubai', 'dxb'] },
      { t: 'Tokyo Haneda (HND)', keys: ['haneda', 'tokyo', 'hnd'] },
      { t: 'Dallas Fort Worth (DFW)', keys: ['dallas', 'fort worth', 'dfw'] },
      { t: 'Shanghai Pudong (PVG)', keys: ['pudong', 'shanghai', 'pvg'] },
      { t: 'Chicago O\'Hare (ORD)', keys: ['o hare', 'ohare', 'chicago', 'ord'] },
      { t: 'London Heathrow (LHR)', keys: ['heathrow', 'london', 'lhr'] },
      { t: 'Istanbul Airport (IST)', keys: ['istanbul', 'ist'] },
      { t: 'Guangzhou Baiyun (CAN)', keys: ['guangzhou', 'baiyun'] },
      { t: 'Denver International (DEN)', keys: ['denver', 'den'] },
    ],
  },
  {
    id: 'busiest-airports-us',
    listId: 'busiest-airports-us',
    publishedDate: '2026-06-11',
    title: 'Name the Busiest Airports in the US',
    category: 'USA',
    type: 'travel',
    tags: ['travel', 'other'],
    timeLimit: 90,
    blurb: 'America\'s ten busiest airports by total 2025 passenger traffic, per Airports Council International. Ninety seconds. Name all ten.',
    answers: [
      { t: 'Hartsfield-Jackson Atlanta (ATL)', keys: ['atlanta', 'hartsfield', 'atl'] },
      { t: 'Dallas Fort Worth (DFW)', keys: ['dallas', 'fort worth', 'dfw'] },
      { t: 'Chicago O\'Hare (ORD)', keys: ['o hare', 'ohare', 'chicago', 'ord'] },
      { t: 'Denver International (DEN)', keys: ['denver', 'den'] },
      { t: 'Los Angeles International (LAX)', keys: ['los angeles', 'lax'] },
      { t: 'New York JFK (JFK)', keys: ['jfk', 'kennedy', 'new york'] },
      { t: 'Orlando International (MCO)', keys: ['orlando', 'mco'] },
      { t: 'Miami International (MIA)', keys: ['miami', 'mia'] },
      { t: 'Las Vegas Harry Reid (LAS)', keys: ['las vegas', 'vegas', 'harry reid'] },
      { t: 'San Francisco International (SFO)', keys: ['san francisco', 'sfo'] },
    ],
  },
  {
    id: 'busiest-airports-outside-us',
    listId: 'busiest-airports-outside-us',
    publishedDate: '2026-06-11',
    title: 'Name the Busiest Airports Outside the US',
    category: 'World',
    type: 'travel',
    tags: ['travel', 'other'],
    timeLimit: 90,
    blurb: 'The ten busiest airports outside the United States by total 2025 passenger traffic, per Airports Council International. Ninety seconds. Name all ten.',
    answers: [
      { t: 'Dubai International (DXB)', keys: ['dubai', 'dxb'] },
      { t: 'Tokyo Haneda (HND)', keys: ['haneda', 'tokyo', 'hnd'] },
      { t: 'Shanghai Pudong (PVG)', keys: ['pudong', 'shanghai', 'pvg'] },
      { t: 'London Heathrow (LHR)', keys: ['heathrow', 'london', 'lhr'] },
      { t: 'Istanbul Airport (IST)', keys: ['istanbul', 'ist'] },
      { t: 'Guangzhou Baiyun (CAN)', keys: ['guangzhou', 'baiyun'] },
      { t: 'Delhi Indira Gandhi (DEL)', keys: ['delhi', 'indira gandhi', 'del'] },
      { t: 'Seoul Incheon (ICN)', keys: ['incheon', 'seoul', 'icn'] },
      { t: 'Paris Charles de Gaulle (CDG)', keys: ['charles de gaulle', 'de gaulle', 'paris', 'cdg'] },
      { t: 'Beijing Capital (PEK)', keys: ['beijing', 'capital', 'pek'] },
    ],
  },
];

export function getQuiz(id) {
  return QUIZZES.find((q) => q.id === id);
}
