// Puzzle data for Glyph, the daily codeword. Imported ONLY by the server page
// (app/glyph/page.js), which filters live<=today before handing the bank to the
// client, so tomorrow's grid and its key never reach the browser.
//
// Each puzzle is a filled crossword grid with every letter replaced by a number
// 1-26, consistent across the whole grid. `rows` encodes the board one string
// per line: '.' is a block, and 'a'-'z' are the numbers 1-26. `key` is the
// answer, where key[i-1] is the letter that number i stands for, so all 26
// letters appear on every board. `given` lists the numbers revealed at the
// start (three on weekdays, two on the bigger Sunday Edition).
//
// Every board was machine-verified (scripts/verify-glyph.mjs) to use only
// dictionary words and to have EXACTLY ONE consistent letter mapping, so the
// grid is always solvable by deduction and never by guesswork.
export const PUZZLES = [
  {
    num: 1,
    quizId: 'glyph-8-2-26',
    live: '2026-08-02',
    dateLabel: 'August 2, 2026',
    sunday: true,
    w: 17, h: 17, words: 41,
    given: [6, 21],
    key: 'OPJMQUTYDWBGHFEVNZSACLKIRX',
    rows: [
      'uyaji.akgtxqoi...',
      'a..a.s.x....z..o.',
      'p..d.x.g..soxrxql',
      'o.yoqojoi...s..c.',
      'y..q.l..oqtug.saq',
      's.u.oov.u.v.o..h.',
      '..t.....x.bfqw.x.',
      'mfks..b.i.m.g.tqh',
      '...m.loqoytv.s.l.',
      '.tuyo.b.i...sfo..',
      '...a..g...b.gozgs',
      '..eftvxnh.v.y.g.f',
      '.l.i..i...t.t.o.b',
      'xvv.kvooi.gyhxql.',
      '.a..x.s.ola...i.a',
      'uakyt...k.a..votn',
      '.d..sbtygtq...i.g',
    ],
  },
  {
    num: 2,
    quizId: 'glyph-8-3-26',
    live: '2026-08-03',
    dateLabel: 'August 3, 2026',
    sunday: false,
    w: 15, h: 15, words: 35,
    given: [1, 2, 12],
    key: 'AYXLMIOQUECZFKTHBWDVPRSGJN',
    rows: [
      'xgg..s.a..wrfmo',
      'a...sjwufwj..i.',
      'd....f.j..j.azs',
      'asyiwo.wgizs.s.',
      'c.a..b..t..j.w.',
      'b.f.d.qva.bjr..',
      '..d.j.v.o..u...',
      '.l.vaofmfjs.jei',
      '.g..z.e.g.j...z',
      'pgejw...z.uflla',
      'a.....y...f...v',
      'rjdkgejs..kgg.e',
      'n..v..v.g.o.n.j',
      'whifs.nfzxw.a.s',
      '...q....j..xbe.',
    ],
  },
  {
    num: 3,
    quizId: 'glyph-8-4-26',
    live: '2026-08-04',
    dateLabel: 'August 4, 2026',
    sunday: false,
    w: 15, h: 15, words: 36,
    given: [8, 17, 22],
    key: 'CSZIEGRLBFTMNPUWAJXOQYDHKV',
    rows: [
      '.....qibemkee..',
      '..w.dlql.......',
      'ktgv.ngtreakb..',
      'q.q....y..e.u..',
      'bojjgqfe.jhtog.',
      'k.k..k.g..h.q.l',
      'ehbe.k...k.igde',
      'b...nqkxpqv.e.q',
      '.a...d.t.a..b.h',
      '.o.atmaegk...e.',
      'lehtm....dmits.',
      '...ceqh..h...n.',
      'bpqv.l.zdepb.t.',
      '..f..l....q.ngt',
      'letp.tgaxdwb.k.',
    ],
  },
  {
    num: 4,
    quizId: 'glyph-8-5-26',
    live: '2026-08-05',
    dateLabel: 'August 5, 2026',
    sunday: false,
    w: 15, h: 15, words: 35,
    given: [11, 12, 23],
    key: 'RFENUILZXHGKQVTWDBMYPJCOSA',
    rows: [
      '..m.....u.b..n.',
      'yxeoj..rfhzaac.',
      'l.c.....c.o..a.',
      'f.y.u.pxaoj..t.',
      'u.ozao....x.y..',
      'u...x..yersfoy.',
      'c.vfk..j....a.z',
      'a.c.azqfzg.yfwl',
      '.ugcz..d.x..u.f',
      'j.g.szwc.k..y.d',
      'zrtyy..ydxpt.b.',
      'o....y....z..f.',
      'acq..e.lfyyfdk.',
      'c.ciwfoc..j.x..',
      'q.p..o.kcg..aed',
    ],
  },
  {
    num: 5,
    quizId: 'glyph-8-6-26',
    live: '2026-08-06',
    dateLabel: 'August 6, 2026',
    sunday: false,
    w: 15, h: 15, words: 28,
    given: [9, 16, 26],
    key: 'XKWNMSFODCITYZBEVUJQRGALPH',
    rows: [
      '..t....ewakeknp',
      'jurdjz.w.......',
      'z.k.w..n...nwy.',
      'h.ipowlpi.i..k.',
      'y...o.w...kdipa',
      'f..xwrvzkdv....',
      '....v........q.',
      '...dplchubf.jwu',
      '...h....h.l..u.',
      '.shl.g.jruum.k.',
      '.p.jhkx.l.p..p.',
      'eplz.g.u..fplf.',
      '.n...l.h..f....',
      '....fzuwydpx...',
      '.....f.i..i....',
    ],
  },
  {
    num: 6,
    quizId: 'glyph-8-7-26',
    live: '2026-08-07',
    dateLabel: 'August 7, 2026',
    sunday: false,
    w: 15, h: 15, words: 34,
    given: [15, 22, 23],
    key: 'YGDVZUIMKFQPTBEJXHWROCSLNA',
    rows: [
      '........t......',
      '....oqvxfcow..m',
      '...z..xoc.k...u',
      '..ltolzgc.f.pzs',
      '...v..s.o.g.u.o',
      '.e.rzh.mtulra.t',
      '.u.g..h..z....w',
      '.c.dzxgcgma.g..',
      'xgnox.c..w..y.w',
      '.z.conmw....wgy',
      'zvm...o.z...l.z',
      '...c.btzvo.mgvi',
      'zvmut.h.f...tfo',
      'c..u....moycotw',
      'c.jtzbgxo...w..',
    ],
  },
  {
    num: 7,
    quizId: 'glyph-8-8-26',
    live: '2026-08-08',
    dateLabel: 'August 8, 2026',
    sunday: false,
    w: 15, h: 15, words: 31,
    given: [10, 12, 25],
    key: 'VOJPTUXQMFNHIEDLZKARGBCWSY',
    rows: [
      '...h....i..y.s.',
      'v.dfu.vbbyenty.',
      'n..s....b..w.d.',
      'p..onspmku.y...',
      'b...j.....l..m.',
      'xlstj.ambpseno.',
      '.f..m...s.t..b.',
      'enn.wlsmtno..p.',
      '..g.s.u...kbmyz',
      'o.s.wsttz.n....',
      'n.i.z.s...ysrn.',
      'kbmt.wtnndy....',
      'y.k.y.m..t.q.c.',
      'nankefsp.b.b.n.',
      '..o.z.k..vbbyey',
    ],
  },
  {
    num: 8,
    quizId: 'glyph-8-9-26',
    live: '2026-08-09',
    dateLabel: 'August 9, 2026',
    sunday: true,
    w: 17, h: 17, words: 44,
    given: [3, 18],
    key: 'JCXSGPOFQILVNDBZWTYREAUKHM',
    rows: [
      'mweeur.......djkx',
      'u.t....d...j.y.j.',
      'dgjk.lvjm.jmdjdrd',
      'r.z.t..z.h.djf.r.',
      '.oukgmed.v.ukz.u.',
      '....b....mwbkuvt.',
      'okjmx.bgbv.w.m...',
      '.v..u.w..r.twry..',
      'mwr.rgtrgjdu...f.',
      '.m.o..r..b...autx',
      '.b.wfqvtnd.i...g.',
      'dyun..j...fwod.k.',
      '.u..humbun.u..oge',
      'ntwz..d.c..d.k.m.',
      'j..j.p..vmsryjme.',
      'hvwc.g..b....u...',
      'h...tgogrd...dgvf',
    ],
  },
  {
    num: 9,
    quizId: 'glyph-8-10-26',
    live: '2026-08-10',
    dateLabel: 'August 10, 2026',
    sunday: false,
    w: 15, h: 15, words: 38,
    given: [2, 13, 22],
    key: 'JOKDIERZXFMQTNWYAUSGCBLPVH',
    rows: [
      '....m.q.mfims..',
      '..scennfg...l..',
      '..e.f.d.q.gbrm.',
      '.swrg...p.r.q.k',
      '..b..cessfd.mbb',
      '.m.x..s...f...g',
      '.q.r..w.k...vbq',
      '.y.wejfwbnt.q.w',
      'vffx..sqd.g.g.w',
      '.g.e...xfdqtbtp',
      'snemuz..wbm.n..',
      'f....q.j.tfw...',
      'gbo..h.q..j.aqv',
      't..uzfuc..r.q..',
      'fvv..w.f.vwbos.',
    ],
  },
  {
    num: 10,
    quizId: 'glyph-8-11-26',
    live: '2026-08-11',
    dateLabel: 'August 11, 2026',
    sunday: false,
    w: 15, h: 15, words: 30,
    given: [11, 18, 21],
    key: 'CBWKXSGVJPLENRTAYDQOUZMHFI',
    rows: [
      '.ilo.ntuolf....',
      '...x......xzadf',
      '.c.l.ykphtn.t.j',
      'otnq..u...u.w.n',
      '.n..vlm.jug.y.p',
      '.k....g.p.gtt.z',
      '.rub.f..u.l.num',
      '.k.lmaktflr.o.l',
      '.q.a.n..l...fpr',
      '..wpwp.g.k.....',
      '...w.jlnyuwl.p.',
      '.i.l.j.t.k.s.c.',
      '.t...l.u.u.u.p.',
      '.zmhprzmg.wpezw',
      '.m.....r...k.o.',
    ],
  },
  {
    num: 11,
    quizId: 'glyph-8-12-26',
    live: '2026-08-12',
    dateLabel: 'August 12, 2026',
    sunday: false,
    w: 15, h: 15, words: 33,
    given: [10, 20, 24],
    key: 'WEMZIJSGNPXBAUVCYQTLOHKRDF',
    rows: [
      '...r..c........',
      '...n.zbcmtbg...',
      'g.duu.c...k....',
      'v..s.xbhntmxg.n',
      'xeomt.....c.n.j',
      'b.....epq.j.iuy',
      'yuxc...q..t.w.m',
      'y.m.xbtmjgb.bms',
      'b.l....i..gei.b',
      'y.luvbcemi.i..y',
      '..e..xby...l...',
      '.m.vbmsby.vuegs',
      '.ztba.b.b..k.v.',
      '.m.xbfuepb..ymc',
      '.x.u..x.u....q.',
    ],
  },
  {
    num: 12,
    quizId: 'glyph-8-13-26',
    live: '2026-08-13',
    dateLabel: 'August 13, 2026',
    sunday: false,
    w: 15, h: 15, words: 36,
    given: [3, 17, 21],
    key: 'INTKEZUGQVXJCBYOHDSPAMFRWL',
    rows: [
      'u.......q.vpns.',
      'wphho.l.e...p.u',
      'c.u..ypxvs.txpr',
      '..z...n..o..p.r',
      'musq.v.s.v..g.a',
      'z...qeut.npghqc',
      'uzts.c.e.p..q.a',
      's...cukunze.s.j',
      'qex.p..d..i...e',
      'e.a.t.w..hgcs..',
      's.stabumq.a.p.w',
      '..d.mur...c.g.a',
      'zea.utek..o.xan',
      '..b.z.s......b.',
      'fah.......xeabs',
    ],
  },
  {
    num: 13,
    quizId: 'glyph-8-14-26',
    live: '2026-08-14',
    dateLabel: 'August 14, 2026',
    sunday: false,
    w: 15, h: 15, words: 36,
    given: [2, 16, 25],
    key: 'ONVXKDGCFLSQMIJBZRYEPHATUW',
    rows: [
      'khrypptf..w.caz',
      'v.w.r...o.r.a..',
      'w.p.a.r.y.ryjt.',
      'm.pwbenbg.w.x.k',
      't.n.q.b...b.wga',
      'i..vtfgtvag.g.u',
      'y....n..w.tdth.',
      'j.p.zwjbyx...a.',
      '.iwr.j..j..wlyw',
      'rajt.s...uwr.b.',
      '.rtiyktk...t.h.',
      '.m...n..wxt.cnw',
      'pwuxnkm..r.j.j.',
      '.j..r..fnwutrk.',
      '..gatk...m.f...',
    ],
  },
  {
    num: 14,
    quizId: 'glyph-8-15-26',
    live: '2026-08-15',
    dateLabel: 'August 15, 2026',
    sunday: false,
    w: 15, h: 15, words: 34,
    given: [13, 21, 25],
    key: 'ZUWQRLDJTIFXYONKGBAHSCPMVE',
    rows: [
      '.e.t...f.......',
      'wziji.anxrjz.g.',
      '.d.esw.y..g.beo',
      'hbyzojfz..z..b.',
      '.z...o...rnunx.',
      '.ubz.vnr..f....',
      '.i.l.t....n.uim',
      '.u.wnjoijoq..e.',
      '...e.o.t..m.qzi',
      'rmiz.q.s.w...s.',
      'mzsui.jovfbgzu.',
      'zseu.g.p.z...b.',
      '.e..tsfkcsm..e.',
      'jff..i.b...tsmu',
      '.m.nyzefnsg....',
    ],
  },
  {
    num: 15,
    quizId: 'glyph-8-16-26',
    live: '2026-08-16',
    dateLabel: 'August 16, 2026',
    sunday: true,
    w: 17, h: 17, words: 36,
    given: [6, 8],
    key: 'DRNSWPGIMKXOETCYFAHVQJLZUB',
    rows: [
      'qrwdmwp..........',
      '.w.r...h.ron.....',
      '.zlggwhcg.l.z..d.',
      '.r.m.m.j.hifywdmd',
      '..d..t....z.w..h.',
      '.uylnmd..q..w..x.',
      '..i..w.mrbzyad.m.',
      '.flddm...y..l.laa',
      '.....amnrhw.g....',
      'lbz......n....e..',
      '.r.fybosrdm.vmbjd',
      '.a...m.h..k...l.m',
      'ehns.t.a..o.dlc.r',
      '.r...h..dnycn.g.d',
      'qwrewmdd..d.r.w.l',
      '...r.e.y.dmcnbp.c',
      'smrbnd.z..d.d...d',
    ],
  },
  {
    num: 16,
    quizId: 'glyph-8-17-26',
    live: '2026-08-17',
    dateLabel: 'August 17, 2026',
    sunday: false,
    w: 15, h: 15, words: 37,
    given: [5, 17, 20],
    key: 'XKANCBEVHWTYQJLOGMUIRDZFPS',
    rows: [
      'cug.p.w.h..zlde',
      'd..curcrgdk...p',
      'cqp.g.y.k.g.ncr',
      'o.u..u..p.a.c.y',
      'l.cofsrz..k.t..',
      'wgd..d.p.mstok.',
      'g.q....x..u.g..',
      '..g.vtekckg.vcv',
      '.o.....o.g.n..c',
      'rctdzkcl.u.s..q',
      '.b..e...yucdb.q',
      'rgkguz.u.t.b..g',
      '.u..g.ipdgv.ycu',
      '.zdpj..p.u.ncq.',
      '....zktxx...vpk',
    ],
  },
  {
    num: 17,
    quizId: 'glyph-8-18-26',
    live: '2026-08-18',
    dateLabel: 'August 18, 2026',
    sunday: false,
    w: 15, h: 15, words: 33,
    given: [5, 19, 23],
    key: 'QLXYPKDEOACTZIRSWGHVFUJNBM',
    rows: [
      'x.lohxgp.......',
      'i.j.b..l.k.....',
      'v.c.f.qjrixp...',
      'x.e..rhl.b.n..r',
      'pzjol.gvhb.bjfh',
      '..d..u.h.hri..j',
      'whhm.i...r..eho',
      'v.o.avjoohb.v.n',
      'z..e.x...p..rnx',
      'e.wvxlj....l..r',
      'h..y.j...r.s...',
      'o...knesho.d.t.',
      'pjrh.x.j.j.z.n.',
      '..i....vzyohbbj',
      'psioh..b.p...h.',
    ],
  },
  {
    num: 18,
    quizId: 'glyph-8-19-26',
    live: '2026-08-19',
    dateLabel: 'August 19, 2026',
    sunday: false,
    w: 15, h: 15, words: 32,
    given: [2, 8, 25],
    key: 'RYTHQAIMDXPJUKLWZSVGNBCEFO',
    rows: [
      '....n.n.......a',
      'i.kxurgzu.kazrx',
      'x.o.x.u.zax...y',
      'wafqx...s.a.w.r',
      'a.b...d.fhguz..',
      'x.rmhhzu..r.omt',
      'x.....m.o.dfi..',
      'i.y.txuixa...d.',
      '..a.f.i.f...lzv',
      '.uxjc..xigcr.h.',
      '..e.x...x.p..x.',
      '..m.i.yzawxymo.',
      '.vxi.a....u..f.',
      '..u..f....cpgur',
      'vgcr.czmwdb..i.',
    ],
  },
  {
    num: 19,
    quizId: 'glyph-8-20-26',
    live: '2026-08-20',
    dateLabel: 'August 20, 2026',
    sunday: false,
    w: 15, h: 15, words: 36,
    given: [6, 20, 22],
    key: 'QZFWNTCASMOVBYIKRLUDEHXGPJ',
    rows: [
      '.....f..d..d...',
      'lhf.uhxuq.fkwog',
      '.q.h.j..o..e...',
      '.gkefujyf..tscc',
      '.v.e....u..u..h',
      'mufh.ighqouq..r',
      '.q...khf.f.iuhr',
      'o..vntqkxue.x.k',
      'e..u...j.j..xes',
      'a.fqhgui.i....f',
      's..i......t.z..',
      'o..uluqnthn.u.b',
      'qkrr..k.k.u.d.k',
      'u..c..mse...uxk',
      '....cku.iporr.j',
    ],
  },
  {
    num: 20,
    quizId: 'glyph-8-21-26',
    live: '2026-08-21',
    dateLabel: 'August 21, 2026',
    sunday: false,
    w: 15, h: 15, words: 36,
    given: [11, 16, 4],
    key: 'ATFJZSMIQPNRLKXGWUOVECYBDH',
    rows: [
      'u..blhxu..hkbs.',
      'a.x...l.c..r..h',
      'b.l.xuubmu.nuuk',
      'fzhta.u.a..u..c',
      '..k.n.ehp.z.s.m',
      'iruru.u.fru.r.r',
      '.....y..z.y.bao',
      'l.d.wummhkp.h..',
      'u.s..v..j.u.krb',
      'k.xluabz..z.p.z',
      's..h.y..vlsjf.u',
      'r..jsug.l.p..b.',
      'ksbu.fsgu....z.',
      'v.r...s.qhkbulf',
      'uppjmakb.....r.',
    ],
  },
  {
    num: 21,
    quizId: 'glyph-8-22-26',
    live: '2026-08-22',
    dateLabel: 'August 22, 2026',
    sunday: false,
    w: 15, h: 15, words: 30,
    given: [9, 15, 19],
    key: 'SNYMKBJTIALFEQDGCVPHXROZWU',
    rows: [
      'szkama.g.j.k..v',
      '...n...wfahjqkm',
      '.y.z.o.e.t.i..k',
      '.mujdibmv.qvjxc',
      '.j.a.j.v....o..',
      '.e.tzat.s...r.a',
      'xmb..s..v.k.i.j',
      '.v.lwwhbwhm.azs',
      '..f..v....h.m..',
      '.tcovj.tzbhmv..',
      '..m.w.....i..e.',
      '...fkwq.fwboibp',
      '..d.k..d..p..m.',
      '.ajrmo.w.....m.',
      '..c.o..djhhmva.',
    ],
  },
  {
    num: 22,
    quizId: 'glyph-8-23-26',
    live: '2026-08-23',
    dateLabel: 'August 23, 2026',
    sunday: true,
    w: 17, h: 17, words: 43,
    given: [10, 13],
    key: 'GELZHPMAQUWXVYJRSKNCTIOBDF',
    rows: [
      '......f...s.....x',
      '..chgxbpu.wfu.x.w',
      '..w...k..tjp.twfn',
      '.uhcrq..qnswy.a.t',
      'a.u..uen.q.u..j.w',
      'p.e..h...upbsyq.u',
      'hlb.huwgq..v.h..u',
      'u....j.w...shgby.',
      'b.d.pbtpjvuq.f...',
      '.dwsb..q......f..',
      '..w.q.ybhz..j.baa',
      '....t.v..p..f.u.v',
      '.cvijvy.qhmvwjp.p',
      'o...b....g..s.w.h',
      'hymvqb.mvbkq..c.z',
      'g.v....h.y......z',
      'qbhq.thub..qfpvub',
    ],
  },
  {
    num: 23,
    quizId: 'glyph-8-24-26',
    live: '2026-08-24',
    dateLabel: 'August 24, 2026',
    sunday: false,
    w: 15, h: 15, words: 34,
    given: [3, 11, 15],
    key: 'GDAZSTFUVHCXQRWIJLKNOMBPYE',
    rows: [
      '....vyfjpk.dpx.',
      '.epl..u..h...z.',
      '.f..kcnz.t.ghny',
      'xcfpu.k..t.z.e.',
      '.a..r.j.ipfcvpt',
      'ozw.r..vct.f.e.',
      '.b.xcbbpta.h.f.',
      '..o.x..t..cnf.a',
      '.rcee..k.g.zckj',
      'q.i.z.nzvptbe.u',
      'u.z......a..s.e',
      'spbtzy.g.euwe.f',
      'z..c...r..o....',
      '.xjyepmhz.tcfcr',
      '...............',
    ],
  },
  {
    num: 24,
    quizId: 'glyph-8-25-26',
    live: '2026-08-25',
    dateLabel: 'August 25, 2026',
    sunday: false,
    w: 15, h: 15, words: 31,
    given: [12, 23, 26],
    key: 'RHQTWBDPGZFMUKNLAVOYCXEIJS',
    rows: [
      'f.fmzdpxoi..y..',
      'a.p.t.q..w..m.a',
      'x.q.osg..q..g.x',
      'gxuwg.z..axgiwz',
      'w.n.a...s...l.w',
      '.jwas.e.l.hswlz',
      '..g.l.x.w.m.o..',
      '.g..woixowz.d..',
      'lxv...i...b...g',
      '.z....pszd.p..w',
      '.uskkww.c.tsm.l',
      '.s...t..m..u..q',
      'qrsxgwg.xobmlqo',
      '.w...g..a..z..g',
      'dasmd.zbwgz.twz',
    ],
  },
  {
    num: 25,
    quizId: 'glyph-8-26-26',
    live: '2026-08-26',
    dateLabel: 'August 26, 2026',
    sunday: false,
    w: 15, h: 15, words: 36,
    given: [6, 12, 19],
    key: 'LXVGBDPIAQOCYTFKMZRWEJUSHN',
    rows: [
      '.x.jwhan.k.u.x.',
      'xnm....igguzfhb',
      '.h.v...p.n.n.r.',
      '.lkwznhux.tiaux',
      '.p.d..z....h.x.',
      '......v.oihax.c',
      '.d....w.a.....u',
      'lig.nisqil..s.s',
      '.s..k.u.t..fuah',
      '.f..skf.a.ywe.o',
      'quinm..gufidkdm',
      '.z....f.x.h.w..',
      'ixy.xyktx.shzdx',
      'f...i.u...u.f.k',
      'fihsm..yuifx..e',
    ],
  },
  {
    num: 26,
    quizId: 'glyph-8-27-26',
    live: '2026-08-27',
    dateLabel: 'August 27, 2026',
    sunday: false,
    w: 15, h: 15, words: 32,
    given: [4, 5, 16],
    key: 'AEIUFVWBOTRYPJLMGHCNDKXQSZ',
    rows: [
      '.........s....n',
      'scysi.m.kidjb.a',
      'c..d.ekbbu....s',
      'j..k..c.y.sobkv',
      'c.fbtjy.c....b.',
      'z.....i.ukag.s.',
      'bwmi..t.d..b.l.',
      't...payyby.hdsv',
      'yma.d...y..s.o.',
      '..o.p....hkasby',
      'rajb.r.....p..j',
      '..b..aundyj.x.d',
      'eiksby...o..d.t',
      'a.b..j..ycmmctq',
      'tiu.hljb.u..u..',
    ],
  },
  {
    num: 27,
    quizId: 'glyph-8-28-26',
    live: '2026-08-28',
    dateLabel: 'August 28, 2026',
    sunday: false,
    w: 15, h: 15, words: 38,
    given: [3, 22, 25],
    key: 'PEOUJRHCVLSGMXFZBITWKNDYAQ',
    rows: [
      '.......ywirhb.t',
      'qyvk..e.c..d..b',
      'y.y.sfcabk.fdks',
      'v.a.g.q..a.j.s.',
      'zdcsb.k.krmrjyf',
      'd.j.v..c.w.v.q.',
      'bnbh.v.w.b.l...',
      's.c.wbscdf..wrm',
      '..v..h.f.kymb.r',
      '...bju..m...ocn',
      '.i.j.khfymqjb..',
      '.cww...ytb..v..',
      '.t.b.s.p.trvwx.',
      'abyf.tgc....b..',
      '.w.k.c.fgbscfrh',
    ],
  },
  {
    num: 28,
    quizId: 'glyph-8-29-26',
    live: '2026-08-29',
    dateLabel: 'August 29, 2026',
    sunday: false,
    w: 15, h: 15, words: 36,
    given: [2, 5, 10],
    key: 'LYAIBEWJUPDMTHGNFXOCRQSZKV',
    rows: [
      'a.tsiak.hffx..w',
      'c.c.....s.j...s',
      'xfp.e...b.d.a.t',
      'b.msitnfw.tndad',
      '....q.s.....v.c',
      '.liqqdpw.e..i.a',
      '.s....s..ucedk.',
      'fay.tiucmf..k.o',
      '.k.n..w..c..wdu',
      'ldrdpo.w.y.p..d',
      '.p.l..sjjswfk.p',
      'ion..u.d.i.r.j.',
      'u..w.f.tim.i.s.',
      'o.zsbcofu..wafg',
      'f..b.j..pdj..l.',
    ],
  },
  {
    num: 29,
    quizId: 'glyph-8-30-26',
    live: '2026-08-30',
    dateLabel: 'August 30, 2026',
    sunday: true,
    w: 17, h: 17, words: 44,
    given: [13, 23],
    key: 'CHAXOZYSJWFRMLVGENBKDTUQPI',
    rows: [
      '..haclqu..pcnney.',
      '.k..r...e.....szr',
      'ocwnv.ywsh.pneoq.',
      '.l..q...i.....z.j',
      '.v.wrzxwq.s.xwevc',
      '.h..r...a.w...w.n',
      'n..acy..vblerqh.v',
      'q.k.h.h...h..r..f',
      'kqq..crdzqvg.clm.',
      'v.jcu.c.o....a..c',
      '.k..e.t.g.zrhvcnn',
      'rcllejqu.k...z..n',
      '.n..m.h.bzvmcr..z',
      'knqc.v.n.r.q.pcfq',
      'w..r.z.z.a.c..r.h',
      'h..r.uenybzr..v..',
      'hwpclg.g...hyezn.',
    ],
  },
  {
    num: 30,
    quizId: 'glyph-8-31-26',
    live: '2026-08-31',
    dateLabel: 'August 31, 2026',
    sunday: false,
    w: 15, h: 15, words: 31,
    given: [10, 14, 17],
    key: 'BTXULAVRJPSYCDEZNGWIOHMFKQ',
    rows: [
      'f........z.a...',
      'wlkbtm.fzdfhtdw',
      't..s..a..o.o..t',
      'n..o.wfqodgoh.m',
      '.o.f..m..o.p..y',
      '.c.yqub...vonro',
      'afq...o.m.....l',
      '.w..rfhefqn..l.',
      'xtqoh.t.q...sus',
      '.q..t.f.u..i.d.',
      'yobbeo.homhdtbk',
      '.n..e...k..n.v.',
      'u.rdokk..q.rfkj',
      's.l.n..kjtqo..f',
      'qdwa.....a.keus',
    ],
  },
  {
    num: 31,
    quizId: 'glyph-9-1-26',
    live: '2026-09-01',
    dateLabel: 'September 1, 2026',
    sunday: false,
    w: 15, h: 15, words: 32,
    given: [1, 2, 22],
    key: 'DIJFHSOPREGAVYZTBXWCQLMUKN',
    rows: [
      '......ftejwj...',
      '.z..o.....x.a..',
      'tgn.g.f.cxfpbdn',
      '.m..z.n.x.p.f.l',
      '.lvajiwlz.lvv.y',
      '..j...q.y.z.b..',
      'uxbpf.g...k.ybz',
      '....hlvltjf.j..',
      't.w.i.f..a....e',
      'i.lrbf..ibkf..g',
      'x.i.z..s.p.bzpg',
      'f.q.p.ijtgia..a',
      'elvpja.j.igj..b',
      'j.j.i..h..l...j',
      'ixfp....elizjff',
    ],
  },
  {
    num: 32,
    quizId: 'glyph-9-2-26',
    live: '2026-09-02',
    dateLabel: 'September 2, 2026',
    sunday: false,
    w: 15, h: 15, words: 32,
    given: [15, 17, 25],
    key: 'IKXZENWGOHJUTPFCRMYVQSBDAL',
    rows: [
      '..o..s...lnjezx',
      '.eqyvex...y....',
      '..y..y...apifv.',
      '..f.k...p.b..i.',
      '.vpqlw.vifyq.q.',
      '.y..r.xar.h.pix',
      'lqf.n.ezr.e..q.',
      '.a.vemmzeqv.rac',
      '....x.i.f....m.',
      'dan...c.m..o.s.',
      '..q..g..vmiap.n',
      '.vazty.....f..e',
      '..i..meefyhe..e',
      'oyq..e...s.qavb',
      '...wyqiule.....',
    ],
  },
  {
    num: 33,
    quizId: 'glyph-9-3-26',
    live: '2026-09-03',
    dateLabel: 'September 3, 2026',
    sunday: false,
    w: 15, h: 15, words: 35,
    given: [1, 8, 15],
    key: 'PYDINJTCBXMOVRGQKFSAZULWHE',
    rows: [
      'l..b.flqzn.wzrg',
      'r.gtn..e..k..w.',
      'rwtkdeol..b..d.',
      '..j.g..htvsdeo.',
      'anduz..q..a..y.',
      'l....ill.gti.g.',
      'glgs.z.v..h....',
      '..n.xtngdkz.nvg',
      'h.d..n........n',
      'y.aybsdhs...i.t',
      't.w.......rdnzs',
      'anzmdzxs.a..z.y',
      'g.c..t.vedpvz.z',
      'z..wtgzn.w.s..c',
      'nvz..s.rdwwzc..',
    ],
  },
  {
    num: 34,
    quizId: 'glyph-9-4-26',
    live: '2026-09-04',
    dateLabel: 'September 4, 2026',
    sunday: false,
    w: 15, h: 15, words: 32,
    given: [3, 14, 23],
    key: 'GSAKPBYIWHMENLDQXTFCVZUROJ',
    rows: [
      '...r.p.........',
      'j.flcw.uhc.r...',
      'y..l.h...klyi..',
      'cel..l...y.i.x.',
      'x..thrhvlm.lkhr',
      'ocrc...h.aln.f.',
      '...r.x.m.b....b',
      '.o..scwtlr.s..n',
      'rlxk.k..q.ancvl',
      '.t.y.f..e..c..o',
      'flcm.n.xlswbhma',
      '.m.d.h..n..j..l',
      'btxllmb..zcgb..',
      '.g.g.a...w..w..',
      '......xlbryxlb.',
    ],
  },
  {
    num: 35,
    quizId: 'glyph-9-5-26',
    live: '2026-09-05',
    dateLabel: 'September 5, 2026',
    sunday: false,
    w: 15, h: 15, words: 35,
    given: [10, 12, 20],
    key: 'THVZARCGNBDUPQFWEKOIXMLJSY',
    rows: [
      '...xsjy.yaqevqk',
      '.m...e...q...v.',
      '.fqoqfqq.f.j.m.',
      '.t.s.r..evsliay',
      '.d.t....v..a.z.',
      '.q.wssmtih.g.t.',
      'lyq.e...q.gbtis',
      'h...abtfya...h.',
      'w..b.l..t...b..',
      'z.gqfqjfew..s.n',
      '.v.e..s...e.hil',
      '.q.c..pfsihy..e',
      '.k.zqe..t.q.jsz',
      '.t..w.yewsi.s..',
      '.gsfr...z.aeuqk',
    ],
  },
  {
    num: 36,
    quizId: 'glyph-9-6-26',
    live: '2026-09-06',
    dateLabel: 'September 6, 2026',
    sunday: true,
    w: 17, h: 17, words: 43,
    given: [8, 11],
    key: 'ZQEKCXIBFSYGDWNJRTAHPVMOUL',
    rows: [
      'j..z.i....gobygqk',
      'smvgjcq.e..y..q.c',
      'o..o.z.psn.msod.z',
      'm..o.z..l..l....z',
      'nxn..siicercm.axx',
      'g....j.s.....c..n',
      'e.wxw.zgwh.gohxf.',
      't.x..j.z.x.r.h...',
      '..r.txzgjrge..h.v',
      '..g..e.o.t.tcsq.s',
      'jtxuugol...g..cqq',
      '..o..s...lcocqs.g',
      'h..uxzsq...l..m.x',
      's...i.w..l...j..y',
      'eyu.rkutxxo.oxqwj',
      'd.c.c....o...i.y.',
      '.vsgo.uxglosor.w.',
    ],
  },
  {
    num: 37,
    quizId: 'glyph-9-7-26',
    live: '2026-09-07',
    dateLabel: 'September 7, 2026',
    sunday: false,
    w: 15, h: 15, words: 39,
    given: [1, 15, 25],
    key: 'TJOIYVZQREKHPBUDSAGNXCWLFM',
    rows: [
      '.b.rudq...mrx..',
      'mdsq.x..dvj..y.',
      '.n.q.x.v.ejq.i.',
      '..noa.mcxridae.',
      '.f.i...z.t.g..j',
      'pjyji.qmcdxjp.j',
      '.d..j..j.p.qdxx',
      '.x..yjralji.r..',
      'njj.c..j....s.w',
      '.p.nijjpji.qcxc',
      '..a.z.h...adt.i',
      'nxcsq.o..kriraj',
      'o.a...d.c.u.x..',
      'x...lcmjp......',
      'xcrp....pjydtjp',
    ],
  },
  {
    num: 38,
    quizId: 'glyph-9-8-26',
    live: '2026-09-08',
    dateLabel: 'September 8, 2026',
    sunday: false,
    w: 15, h: 15, words: 34,
    given: [4, 12, 25],
    key: 'UIBSGRVWTEDPCZOJKQXNHMLFYA',
    rows: [
      '..m.ihjji.z....',
      '.poqj.e.b.ezgj.',
      'c.z.v.o.x.z.z..',
      'jsmjli..xzfjd..',
      'i.u.o.......i..',
      'f.jzfwy..uzbwd.',
      'zbk.z....z..y..',
      'y..xwbllbte....',
      '.....t...e.l...',
      '..dibxwj.dyfal.',
      '.r.z.j..x..b.o.',
      '.a.vzfmujk.n.i.',
      'dbkj..z.fzfj.b.',
      '.w....f.fyj.hoq',
      '.i.xatk.y.x..t.',
    ],
  },
  {
    num: 39,
    quizId: 'glyph-9-9-26',
    live: '2026-09-09',
    dateLabel: 'September 9, 2026',
    sunday: false,
    w: 15, h: 15, words: 33,
    given: [11, 20, 23],
    key: 'ZLXBQKNOYHARDGUVSTWMJPEICF',
    rows: [
      '....r..qvwm.vwn',
      '.qrhlt..o...o.o',
      '.x..k.uotvxgn.t',
      '.c..v...v.g...q',
      'qrkl...d..y.n..',
      '.w..v.zhlwjwkm.',
      'awdlk..m..w.t..',
      '.g..qhpxwrq.w..',
      '..d.j..w.h.rlhr',
      '.ybwklwm.s..q.o',
      'm.h......w....x',
      'x.s.d..rhbb.dxr',
      'tiqrwli..q.k..x',
      '...xyi.....r..h',
      'eoxyfwqr..bwklg',
    ],
  },
  {
    num: 40,
    quizId: 'glyph-9-10-26',
    live: '2026-09-10',
    dateLabel: 'September 10, 2026',
    sunday: false,
    w: 15, h: 15, words: 34,
    given: [9, 15, 24],
    key: 'TKUXZBQSLGAMVDCPWJHOYFNIRE',
    rows: [
      '...z...v.o.rcnt',
      '.ncwb..x.k.k...',
      '.k.n.pkybqku..v',
      '.l...c.z...h..y',
      '.hxezn.n.l..p.z',
      '...z.n..wcoizch',
      '.q.w.i.y.h..z.s',
      'lxd.fzskmzn.i.i',
      '.a.....w.c.txiu',
      '.otlfxwj.l..w..',
      '.s..z..z.hltj.y',
      '.z.lkxi....k..z',
      'khp.a.xwgcxyu.o',
      'x.y...z.....zjt',
      'n.u..xwrcyxzh.w',
    ],
  },
  {
    num: 41,
    quizId: 'glyph-9-11-26',
    live: '2026-09-11',
    dateLabel: 'September 11, 2026',
    sunday: false,
    w: 15, h: 15, words: 30,
    given: [6, 17, 25],
    key: 'BDVOWANEMUIZXHRGPSKJYLTFCQ',
    rows: [
      '..ydfynhb...b.o',
      '.....j..j.rqdsh',
      '.nddbr..g.z.g.y',
      '.d...w..p.j...h',
      '.o.qfdvd.xfgr.k',
      '.o...i....b.q.c',
      'xkgh.h...r..njh',
      '.a..poflkgp.h.r',
      '.v....v..h..o..',
      'thos..w.efrwhb.',
      'j.h.fpd..s..r.h',
      'b.j.p..afur...b',
      'd.rwfxx...h.c.b',
      '..h.k...aofchvu',
      '..bhgkhr..i.m..',
    ],
  },
  {
    num: 42,
    quizId: 'glyph-9-12-26',
    live: '2026-09-12',
    dateLabel: 'September 12, 2026',
    sunday: false,
    w: 15, h: 15, words: 40,
    given: [10, 14, 20],
    key: 'SYHBEZUVRKNIAPJWOFDGTXCLMQ',
    rows: [
      '.dgrr..y.emae..',
      '...g.x.lwb.l.r.',
      '.rqipmis.iqu.i.',
      '..i..g...e..omp',
      'wbdqit.t..m..k.',
      'i....cei.jkmwj.',
      'mzgm.u.m..k.m.w',
      'f...ueekmte.u.c',
      'b.y..i..a.v...e',
      '.uqna.aenu.aqsm',
      'c.h..n..l..u..u',
      'mne..g..iewqisa',
      'i.ajbxlke..kmb.',
      'm....n.l.icbyea',
      'ymke...n.....a.',
    ],
  },
  {
    num: 43,
    quizId: 'glyph-9-13-26',
    live: '2026-09-13',
    dateLabel: 'September 13, 2026',
    sunday: true,
    w: 17, h: 17, words: 44,
    given: [13, 15],
    key: 'LSKJZHCOPXYQGFBMWNDUVIAERT',
    rows: [
      '.mvnzb.ohm.......',
      '.v.ywaak..b..d...',
      '.a.hyx.x.yxuvxqb.',
      'bavp.s..a.l..y.x.',
      'h....m.phstaxb.x.',
      'i.tbfxy.o.x..x.c.',
      '.f.w....o.a..kxb.',
      'rhyp.h..k..qwb...',
      '.a.o.iywvyvx.....',
      '.v.wiz..r..bvex..',
      '.b...v..m..z...y.',
      '.zhjvg.w..yxnxyxx',
      '.v.....g.g.y...p.',
      '.gawpi.gfwvrxs.w.',
      'w..iwtbx.p...h.v.',
      'awzxrz.i.ihyzpwr.',
      'z..b.zhzx....x.b.',
    ],
  },
  {
    num: 44,
    quizId: 'glyph-9-14-26',
    live: '2026-09-14',
    dateLabel: 'September 14, 2026',
    sunday: false,
    w: 15, h: 15, words: 33,
    given: [19, 20, 18],
    key: 'OACKJLRVHQEYSNIUXBWTGDZFMP',
    rows: [
      '....ekbnm..m..r',
      'vati..d.p.ionuk',
      'g..b..o.r..q..v',
      'l..msonum..t.m.',
      'o...g.....uoxtm',
      'n.mcbgkv...k.o.',
      'ukf.z.q..s.motm',
      '..k.zazpfbg..c.',
      'j.k.o.a..g.w.i.',
      'p.hbnm.mpghohkv',
      'b.k.u.a..b.u.m.',
      'domm.ybdonu...m',
      'k..n..t..t..fbs',
      '..kbgtil.laub.b',
      '...u........q.n',
    ],
  },
  {
    num: 45,
    quizId: 'glyph-9-15-26',
    live: '2026-09-15',
    dateLabel: 'September 15, 2026',
    sunday: false,
    w: 15, h: 15, words: 37,
    given: [6, 18, 23],
    key: 'ZVCXMOEKLANDUFYPSTIHBWGQRJ',
    rows: [
      'pguuigq..qrjkcg',
      's..y....z.f..i.',
      'p..sepfrgkr..g.',
      'g..g.s..j.g.zju',
      '.c.njr..k..cmy.',
      'uyjq.jyc.ujsr..',
      '.o....j..i.p.l.',
      'nsy.nsksrg.t.f.',
      '.k..f.h..qvgpr.',
      '.wyffe.tjq.y.q.',
      'w...r.....a....',
      'j.x.v.r.y.f.mwt',
      'q.m.gigbjrfy.i.',
      'pijoj.d.n....j.',
      '..l.y.rjrrffgl.',
    ],
  },
  {
    num: 46,
    quizId: 'glyph-9-16-26',
    live: '2026-09-16',
    dateLabel: 'September 16, 2026',
    sunday: false,
    w: 15, h: 15, words: 36,
    given: [4, 21, 23],
    key: 'DNCMWJVBPEOYKZAUXFRQLTIGHS',
    rows: [
      'hkpxyv...psxjbv',
      '....j.f.j....k.',
      's.m.s.olj.h..h.',
      'y.w.hkeju.s.gwo',
      'l.b..i.v..o..u.',
      'doaodj.wbzwxbwo',
      'j.u..s....a..v.',
      '..l.yoiijbz.ulj',
      't....v.j.j.....',
      'p..c.j.voq.x..o',
      'o.rkuaz..vwbajs',
      's..g..keb..p..d',
      'vwdjuwbj.o..yol',
      'n..s...o.a..o..',
      '...vyobmlkp.xpv',
    ],
  },
  {
    num: 47,
    quizId: 'glyph-9-17-26',
    live: '2026-09-17',
    dateLabel: 'September 17, 2026',
    sunday: false,
    w: 15, h: 15, words: 36,
    given: [1, 6, 7],
    key: 'LUZHSCFNGOPXTRAVJQIMEKBWYD',
    rows: [
      '...m..waocune..',
      'wudjaz.s..f.u..',
      'n..n..jpunduoz.',
      's..s.b.s.sjhe.m',
      'u.k..h.h.k.q..d',
      'gnofvshi..ijjgy',
      's.s..g..u..y..t',
      'h.z.wjonzuz...u',
      'i..ton..s.xum..',
      '...ontksm.u.uij',
      '.m.n.e....a.l.s',
      'rbsmu..fdoaum.a',
      '.t.y.o..u...euu',
      'mjbnuz..x.....n',
      '.n.e.zsi.fajeue',
    ],
  },
  {
    num: 48,
    quizId: 'glyph-9-18-26',
    live: '2026-09-18',
    dateLabel: 'September 18, 2026',
    sunday: false,
    w: 15, h: 15, words: 33,
    given: [11, 12, 18],
    key: 'ILFTMPBGCZSDRAXYQKOEJHWVUN',
    rows: [
      '.kyzh.s..g.....',
      '.n..mtztwtl....',
      '.p..n.k..l.....',
      '..b.lptl..e....',
      'txsrt.d.cmsh...',
      'o.g....i..z.f.q',
      'a...x..v..n.y.y',
      'k.b.azdthtm.r.s',
      'dwnaz..n..ivtkd',
      'a.j.p..d..v...t',
      'z.p.badt..pnf..',
      'h..k.m.m.b..syd',
      '.kdair.kdylas.m',
      '...j.....i..bpt',
      '..utdk.usrtk..r',
    ],
  },
  {
    num: 49,
    quizId: 'glyph-9-19-26',
    live: '2026-09-19',
    dateLabel: 'September 19, 2026',
    sunday: false,
    w: 15, h: 15, words: 34,
    given: [3, 6, 23],
    key: 'TLRUVKMEWJFXSZGANDHBQCOYPI',
    rows: [
      '.mfx.p.vhchtcpb',
      '.s.w.mawch....x',
      '.z.o.f.ocpyshqh',
      '.kbpo.p..r.w.w.',
      '.a..c.m..z.w.a.',
      '.h.ydgyfzq.kbpy',
      '.r..r....o...a.',
      'm.c.obdvwmh.bza',
      'udzah.q.b....w.',
      'd.t...a.z..c.q.',
      'p.m..vwqehxhr.i',
      'a..m....h..v..p',
      'm.ypjpgpm..z..b',
      '.xpf.....hlahqa',
      '..chezhim..h..n',
    ],
  },
];
