// Puzzle data for Sweep, the daily minesweeper with no bottom edge. Imported
// ONLY by the server page (app/sweep/page.js), which filters live<=today before
// handing the bank to the client, so no future day's field is ever in a page.
//
// A row is the day's frame plus its field:
//
//   par    the day's BENCHMARK cell count, not a ceiling. Cells uncovered are
//          the score: it is the thing you actually do, every player digs the
//          same field, and unlike a timer it cannot be padded by sitting still.
//          The posted score is the raw count, UNCAPPED, and par is only the
//          denominator daily-combined uses for its completion ratio (it clamps
//          at 1, so digging past par is safe and still separates players on
//          placement). Clearing par wins the end card. Sunday's par is lower
//          because the same field carries more mines.
//
//          SET BLIND at launch, exactly as Blocks' were, and expected to be
//          WRONG. 120 is roughly fifteen rows on a weekday field. Revisit both
//          numbers once a fortnight of real scores exists, and expect them to
//          RISE as players learn to read the strip.
//
//   field  the mine map: 9 columns x 200 rows of one bit, base64'd, about 300
//          characters. Depth 200 is not a bottom, it is ~1,500 safe cells and
//          an order of magnitude past par.
//
// EVERY FIELD IS PROVEN GUESS-FREE BEFORE IT SHIPS. A run is one life, so a
// board that forced a guess would end a run through no fault of the player.
// scripts/gen-sweep-bank.mjs builds each field against the solver in
// lib/sweep-field and repairs it until the whole thing is deducible from the
// surface row down; scripts/verify-sweep.mjs re-proves all of it through that
// same module rather than trusting this comment. Never hand-edit a field: it
// would not be re-proven, and the guarantee is the entire design.
//
// SUNDAY EDITION: density rises from 15% to 18.5%. Density is the right knob
// here because there is no clock to steepen and narrowing the strip would take
// away the constraints deduction needs. `sunday` must be true if and only if
// `live` really is a Sunday; the flag is the ONLY source of truth for the badge
// (see lib/sunday-editions.js).
export const PUZZLES = [
  { num: 1, quizId: 'sweep-8-8-26', live: '2026-08-08', dateLabel: 'August 8, 2026', sunday: false, par: 120,
    field: 'AAICERCAABhBEEJUEAAAIAIQGBEBCIQKCwEAgABAAAAKGQAAAFIGAAAAAkCAUICEAAAEBQAkCCAABRQQQAgEEAQAMBUAACRAACANABZKBgIUQgAQAEAAgZwABiAIAHAEBoigAAAEMQQAEAgUAAIAEICCIASiACIAgCA0AgQCIAABABAIQOAKABAUFDSIARwwAAgACEIAiQBQQAQQAABgAKAkBGAECIhAEBAIAJgARCQBKAAgBDCCAQABAAgEECCQWEQgggAEIAiYAAEQIAAYABgAQAErCADEBEQYAAoBEQBA' },
  { num: 2, quizId: 'sweep-8-9-26', live: '2026-08-09', dateLabel: 'August 9, 2026', sunday: true, par: 90,
    field: 'AAAgAzoApAAAGAQoAUQBCFhAQgQQAwAWQiwCGATCCiVmIIBQUIADoEAAWQFAhIgwxwmACAARAAAFCxaAERFIFLAgFCAQCQFEAIxCBhAAEhQEQQAJgAJIAJBAG4UxEQAJAEAEAACJAEQAIQBIEAkAhIAQDDEAAAJkhACgAAFHIAAIYIATAAtIAYQiDQAwDECEAAA4AZgAYBEcACAABAAIEAABMAJpAAAAIoQBEggCQgQQogIACIADVAZAAQIDIgEgSMygEBCQACAQGIgARUADgjABQIIEJGEOBAEg6AQBAABb' },
  { num: 3, quizId: 'sweep-8-10-26', live: '2026-08-10', dateLabel: 'August 10, 2026', sunday: false, par: 120,
    field: 'AAAYABQFAAJwAEABQMGABCAQIEBQQCAAIACABAAMBPIAgQAQGQQCKIAAAgQBqEAIIKQBhAAQACQgABKAAAAAAUAKCAAjQAIAgAYBQIAApRCABAEAQICAiAAGBAASAgUQiAAJAASAgABIIADpUAAoAQiiABgAAQABoIKgAaBQAAQAWIgBAAAAIAAAAwGAQAAgOIIBAIAgAAgIBAAYiAEIAABAiEBIBBgAckBzMBIRAAAAAEFQAAMJQRAQkgQoEEAYBCBAAAAgoIAgAAgEIAAAMAIWQkQARIAAFRQAcLAAgKAA' },
  { num: 4, quizId: 'sweep-8-11-26', live: '2026-08-11', dateLabel: 'August 11, 2026', sunday: false, par: 120,
    field: 'ABAiEAAQYAABQIAXAtACAACSgRAAHkgsIAiAEIBQAgCCAAEAAAEAAEAAAAAAAAAggIADICAQQYkAAEekCAAAE0AAHCBAAABAAhAYAEAAAAAECBAIEAEAIAABIAAAogIYIIgZQGAEQAAAEAgAAEAAYhgUACABAqJ0AAACBAACAAgQCiBAAAAgAARAQgRAQMAQAAgGgACAghBRgEQAAAgEQAERQAASGAAAACQgKAAAAAwCAgCEAgCAcACBCAAlAgMekAAgAAAEqABGADEAgooAaAgEIADARgUKAcCEARAABAUI' },
  { num: 5, quizId: 'sweep-8-12-26', live: '2026-08-12', dateLabel: 'August 12, 2026', sunday: false, par: 120,
    field: 'AACBQAdAWAACKAAAAgI2BIAWgAEAAAAcikAQIAWQASkQAQgIQQIBAAZBAABENhEMEEAAAAAEIhAAKAAMBAEBAIMiIBECABhAgABAsgANAAAAAAIAAgJAWAEaBYAFDBMAggCDBAAFAIQgACBACoChmAAEYgiAgAAEDMGAAAAARAAIBQwAAgMI4QCIAAiCACAAREQgASgIASkQIIogCYIAgRAKCIARwDQgAAgUAwgAJACgAAgBABAKAQIAQAgAgIAAQACCAigAIAEAMEIEDAAQEGAAAAJARAAAEggAAAAAwEAc' },
  { num: 6, quizId: 'sweep-8-13-26', live: '2026-08-13', dateLabel: 'August 13, 2026', sunday: false, par: 120,
    field: 'ACAAAgIIBg4EECAKAQDAAACBAAAAIQCEAQACoAAARIDAwEAAQAiQciAEAQIhwQYSIAAQDkEgqCAABEIIAAQaIAUCAjQCQABACCAIcBIAgBoIBAIcwAFAEAAADAQAAABBAQxgAARgAAICgQAAQRAAAQBAAACCgAAqAAgAK1AQCgSRAgAEJgQBgAAAEMhBACI4EGIIBEUQAhCABGEqCBAcAAAIBAYhAEEAwAAAAAAECkAAEJAAiAiAjAAgAAAAABAgAOCBABEMiAAQABBiAECIAAAAJgAAEJQEhAIAIAACBQYQ' },
  { num: 7, quizId: 'sweep-8-14-26', live: '2026-08-14', dateLabel: 'August 14, 2026', sunday: false, par: 120,
    field: 'AAIhkAAEAEAIgSAigCqRAAIAAFgCAAGBCCiBAQAACAoBAAAQYAGAAAAAiEQAAAYhAEAGLHAjkIAAFQAAABAAMAQgAQgSAgAIACABCgSIBBAIgEAEABAAQABRgDAAEBADADCgQIQAACAACQFNAAEAAaIUQAASCQRSAgEEQARERQIAIABAIAQABCAgAYAAAAAsESMAiBABAAIqAAAEgAACCCCIAAEEgAEAAAACRABgAECACABBwAAAAEIIgVCRgFoAAACAEACBIAAAIABwAABgtAoABAAAAQIAACBQCBQAAEAA' },
  { num: 8, quizId: 'sweep-8-15-26', live: '2026-08-15', dateLabel: 'August 15, 2026', sunday: false, par: 120,
    field: 'AADACgABAABC0AAAAwIAoACAEgmAKAKAAVAIAAADCEIYAQIABEAAAAaAAgACAYIQoEG4IgMAQGgCAgCAAAAiADAAADAPAIAAwQAEgEUoAAAAJIDABAAISAAAQAABDQCAAgQAAQAgQIRIHgIoQKCQIQAQABAQGoSAAgYEgISAAAMCCBAAQASBCgAokAAgAEMABAIIxAA0khAgERQIIgAYIAiAAAAAAEAQAA2AOAAA2QCACAAAIGKIAAACBCAgiACRQEGgEgAEBDkaAAKAAACgCJAIAGgFAAACAQEAEgEACACB' },
  { num: 9, quizId: 'sweep-8-16-26', live: '2026-08-16', dateLabel: 'August 16, 2026', sunday: true, par: 90,
    field: 'AHnAAIgCCRIEMYAABAACAEBABAADAEMCCACAiABCAEASCIMkIAAIBAAAFAAAAELCQCAVQYGECwAhAKAoAEAQBIAARJ4ZCAQIAASJBIBBEAMhBAFiAjEIIEAAHFAiAQBMEgsAwAgAAAA0CIqIASCAMACAUCQoDAiAAABGACiAIADQAmQAoIAaAJADSAIkAgA8LA0CAAgAAAAAIgNABVABQQEIAA8AQAUAMAABACSUAkACpAFAAE0IQAgQAIAAgQIIAACAAKBADIABKUQAQMCUAGAQKFAAQAggEghUIAsCQBSK' },
  { num: 10, quizId: 'sweep-8-17-26', live: '2026-08-17', dateLabel: 'August 17, 2026', sunday: false, par: 120,
    field: 'AAECmoCAABIAAFAQICgAwRQAEAQCwCESoII2gAQQCBAAIAAAAhOIIAAAQgBCEhAAAiAAQgQEgAAECiAAgkQgAIEAQAMAADIEBgAAAQIACAAQAAAEUkAREAMQBXAAABgkAAEoCBISAAAFAAAABAyhIkIgMEBAEEQAACgBYAIgSABAAgC0AAAZAADAZAkLGAAgAAACAgBIAACzAAABAAAwJAIAIUEAgIgASBYZAAEAGRgmQAACMAgBAABFAECgAEIEBAAAYABIJEEINAACAJoAAEJgQCBEAQgIQAQQAAAAEIIg' },
  { num: 11, quizId: 'sweep-8-18-26', live: '2026-08-18', dateLabel: 'August 18, 2026', sunday: false, par: 120,
    field: 'AAQwCRAACgABABAAAAARTACEBJGAAEEFAGQAAFFiAIAAgIAEASAQBQAAIAIABBwACEKAAEBICQFgBQEIQgICiNCggQsYgABAACGEAFIAJAAigEAgIASABQAABgAEARSFAACYMBDCBFgAAgDWJAhAihAAJkIAABCIxAACAEACgAAEgQAQCRAQBAAAAUEwDAAIEQAgCKAAQwApUAB4ACAAUSACgkAIEAABHCEKABAABAgJBAAQkKAAsIIAUSBwYwAIAAKAAAUIACEhABAQQUAEAAIAEAAAAgYBUAAACIiAREAA' },
  { num: 12, quizId: 'sweep-8-19-26', live: '2026-08-19', dateLabel: 'August 19, 2026', sunday: false, par: 120,
    field: 'ABcBCIAAECAAIAAICAIAEAAMCgIySDQAAgBACASCgAACARAAAACAFAABBgIJAAEBFQggAAAAAEBYQBAAAIgAAACDQBpAIBAAAAAIBYAAAIAAABIAAQAQihCAAEBEQIAjCDxAAKAAkAIAcEAgEhAACCEBgkBEAhEEAEADAJAAYEIAmCgEAAyAAJKMAAAgAAwECgUQEgQAABAEAEAAIAAAKAChgADgYAIAWAAAwAUoCCEEAQEQAggECikAAIQEIgQEAAAjAAQASgACEAQQAAGBABgAAgVAAQApRAQAAkAhEQAA' },
  { num: 13, quizId: 'sweep-8-20-26', live: '2026-08-20', dateLabel: 'August 20, 2026', sunday: false, par: 120,
    field: 'AAACBgQBEKgAABRAAgAEAFgQDMIcgIAiBApHEJBBFBZAJgQCIABSBABUAAWQCQABgQYUAAYBAIQABEYkBAAAjQEQIMEAIBIgAABCAAAAIQIAYAAIwggwAQjgiCQQBAABAhBAAGAggAAAAgAoggEhCAhgABFAIAgYQAGCACAAABAhGABAIAICiEQABgAiEQgQARAEBCAkESCEwBQAAAhAwIEgACAEwIASAAAQAARAITAAhAAAAoCgAQQBAwIAMAAARBUABUAEgCKBSEBECASWQSAQAAABhGAkSJIABACwIABQ' },
  { num: 14, quizId: 'sweep-8-21-26', live: '2026-08-21', dateLabel: 'August 21, 2026', sunday: false, par: 120,
    field: 'AAAKEIAQMADAAAQIAIMAEFAQRIABQGQg5AAEhAAoBEkAAgCC4ACAEABCIBEAACAoAmAQiAgEAAAFwBCAQAAiIkEBLAQAJAICAIAoAkAgkEIEgAGCECAAANCgIgEBBAoUARAAikAlIgIAJAACBBAQIAEIBAABAAIBAEgAI0kgOABAQAOAkEAACAHJJRAEAiwgAIAAiACgwAYAAgAQQCACCDBcAQyAAJSAICQAgBAApADBAAAAACiBAgCABIQABAwAAADAQMAwUICIACRCAEAQYBIJBEAgUJRAAkBBQCADQABY' },
  { num: 15, quizId: 'sweep-8-22-26', live: '2026-08-22', dateLabel: 'August 22, 2026', sunday: false, par: 120,
    field: 'ACACJQEAAAghACpEqBEBCIEAiAAAAQoAIAIQAAECQEIAJAOAAECBJAAIAQiAMgIAtYAAgIAASAAAIAAAAEQgAAAAAhAJGDQQAQEgAAAAkUAQEGAAAAAEAEiAIAAQMACACSMAAAAIAImEABAMCAAAiIAABAIACAABAggAggQVQAAUFEIAqUQACEAgJEAAuQIAJAQAhEBgAACAQJEMgAAAwkgAMAkIwAAEh0AIAABEIAwAAASAAAABSDAAKAEAIAaIAAREAIBgQnEoAUBABAABCCQAoAAMAoAAgICCAAEABQQA' },
  { num: 16, quizId: 'sweep-8-23-26', live: '2026-08-23', dateLabel: 'August 23, 2026', sunday: true, par: 90,
    field: 'ACGAJDCAAABACCDYAACYAABACFIEACFBECAkCURCAABoAhESQAAIjUAJQCowAMAFBAAAASEMIwAoggYMQDAAAEiYAYAAAASiDBxAAAAAqIADgQwEKDEIAIgwIAFAQQoQCQEJIATiQAAkIiAASgAUCABAiIgEEAgAGAAJABEkwGAEAAAICqAicABYJAABhIIIgQIAQsAkjIgKAQRCKiQdAAQAEAUAAABEAUQESBAWIQAQwgCARQAEAAkBwAAq8ACgAIAIKkiAQCAAaAhggEAMBTBgAwHogQgMIECiAVBiAgMk' },
  { num: 17, quizId: 'sweep-8-24-26', live: '2026-08-24', dateLabel: 'August 24, 2026', sunday: false, par: 120,
    field: 'ACAgMAEEEUBgRAREAgkISUAAIgQAABIDIEICAgAABBgIQCQECACQYAAIAIBKBEAECACCgGRSEAIAAEBSBAEkAAoACRAABAAACCAIEADAESAkIACAASIABQBAAEwABiA4AoAYUCIACD5AAIEAgAAjAALEBgQAYYAUAIAAAAAAiIAyAAAGQhEQoAAQARAABAAgAAACAAkDAAgECkRAAAAIAJACACMAgAAcoxAQCqMACUgBAAkAEQkIAOCCBlAAATAAACgoAAEAiAgIUchAACDAAAAgEAQBAIKNAACRAEQSAAAR' },
  { num: 18, quizId: 'sweep-8-25-26', live: '2026-08-25', dateLabel: 'August 25, 2026', sunday: false, par: 120,
    field: 'ABAEghABAikBgAFBgAQAAAUAAAAARAjACJAAAgIEAAAgBpABTCAkIGAUGgKcAAA4AQkAAAAKgCIBBQMwABDBAzJGAA0AAclAAEDAByALEAKgBgLAgAIgAIxKBACQCJAUgATAAjkgABCCAQAKACAAAKAAGBgkiJAECAABwAkIgECBAwAEBAhUQCIAEwAoAGkAABIAICEUAIgIIYgEiAhAAAhgAGAAAAACAACQgEIACCsAIBAAJ4QQgEAUABwpgAAKJEIAJBAgAAQEEAAhASQABIIClYAACAAhCRUAIAAFUAAI' },
  { num: 19, quizId: 'sweep-8-26-26', live: '2026-08-26', dateLabel: 'August 26, 2026', sunday: false, par: 120,
    field: 'AGBBAAAKAITBDAA4AIAggEgAIAAKBIQEEA1AQgCIAhQAAiggEIAwEAgBAgASgAAEB0FEBAAAACBCIQCGJQAAAAUgDiAEBAiaAAABAMYBIACAAEwzAFAIJCIAACIAPQAUBIADABJAhAAAoQEBQQgBIAAAAgAQCgAJJAgQQgBAEIDAAIMAEIoAJUQAAIIHAAIgAAgAAIAAGAyAIQJDIAYAACABmSCAUACAQUACAgAFABBIQQIEQBrAIAhAACQxAAREADCIEgACBKBACIAEKAABCAM1CAAAAi4gwoAwgQCwAAhQ' },
  { num: 20, quizId: 'sweep-8-27-26', live: '2026-08-27', dateLabel: 'August 27, 2026', sunday: false, par: 120,
    field: 'ABAACQhAMATBgIIIEAkCAEBAgFCAEgACiGBhAkUAGggAMESCcMhAEwgAAQEAAAiICiQ4EoAAPBBAwAQAWCggISCLCIAAEABCAAAFAAAAEAAAhAAIAgEAAAB2gQMAEAQhAgAAhAIIQohARAAAIAVCQNAMAhoAgAEAIlAEKAgAAEoAAGACSA1AkICAABICiACgCgEhQAAFBACCkAEAQhIAAAAAgIAsAWAAAAwIAAIAgAwIAABAAIAACAABEBEIAAoMAgAAChAACAxEIBAghADAAghYEAJbAgAAAAMAQADIRRBG' },
  { num: 21, quizId: 'sweep-8-28-26', live: '2026-08-28', dateLabel: 'August 28, 2026', sunday: false, par: 120,
    field: 'AAoQAAAAQBZUAACgAAAAAFQAoQgBAAACFkISQAQiQBAQECIgAAEQABCgEkGRQAgAAAg2QAgAgAAACQSMANEAqAQAAgQCgAAJACQAAAAIhACAoAAIUAEECBkQgAAACAGJAAEgIDMAoAgADASIAAQAAIIKACIDQgAEUAgQRgBEAACAIIQQEhACAACFEAEAJCACBooBBAFECAAhQAAAgAMAAAAGUgQQABAAAIAEIAACCIEggBiAEAQRUgARwBIEAEECIACQgAABiACLQAAhCIwQgAAGAAAAAAAAAAAAQAAFMAgA' },
  { num: 22, quizId: 'sweep-8-29-26', live: '2026-08-29', dateLabel: 'August 29, 2026', sunday: false, par: 120,
    field: 'AAQCAkMAJAADAAAVQZAAxAhEgAiAAAAIAAAACAAIJgAABYhIIACBBQCAQQAIAABABEBAQAACggUEFAFIAAAAkQIQAASIgAFAACARDgAAAKAgCAIgMAQACkkBYAAgMCQEIACBAQwQAEIAgIRkAkAAAIQgAJCSAYAIRAgAgIAGAChgCIAAgQADIAAAoCAEAAAASEACKIiAIAIhAoAEBEAABDvgAgQAJgAABACAIBAACwBAAAAAGkAgEAAJKAACIAACCCEFioAEAIAADLICIAJEAUACBACIAQgQogAABIkCAARo' },
  { num: 23, quizId: 'sweep-8-30-26', live: '2026-08-30', dateLabel: 'August 30, 2026', sunday: true, par: 90,
    field: 'AACAAVAggIACQkAABgQICMhQAAAEAIECAAGAAEBBAAAakADoADEwECECCRaQCgIAiCCAwGGGFAAAGSAiVIAhMBTAFAIFAApAIwICAYUgIgCECaAAQCAOFQFQDFAYgAAcAIAAKAMOBiECIAFIAEiESowYWAEQSiEAhkiEICggBgAEghgACIFgEphEDABGAACkIgABABowKCwQLAgAAgAAgBAEQkAgAkBBhHAJFgIACTEAIOADigATkAMAaFACQEBCEADEIIAAAQqCCQAAEgHQEhgyECgIARgAEAJJBGJBAZAN' },
  { num: 24, quizId: 'sweep-8-31-26', live: '2026-08-31', dateLabel: 'August 31, 2026', sunday: false, par: 120,
    field: 'AAAAwUMACCIAVEAYAQCgBEBAAHIAAFUgQACOCRAgNQgAhgAEAAIA9AYGkEAKIaBaEABAIBEAAAA4qAAEQCIhIIBIgEACBgBkARiQgAABCEAIUAggGwCAJQRgAIUIABAAAAgCBUFAMAYJAIsAAEpCIAAAAQAgcAAwARFCCIQZIKCAAgIGEcAAwoICGgEIABiAAAAJFACAAIQIRMAIYQASKTAAAQgGYABUAIBAAAAAEAAAACBiAIQEAAGFgAAAHgAKQFCIAAACAACACCAgAQEBAKkhEgKIRQAMJgCAEIMAEAEB' },
  { num: 25, quizId: 'sweep-9-1-26', live: '2026-09-01', dateLabel: 'September 1, 2026', sunday: false, par: 120,
    field: 'ABAABoBBIAAAAAAAFAYQEBQBgAUggCAgAIAAABIAACAQkYAIAPIEAEAIA1BMEAhAKAEAYCCABgQACgEAgAAkCAJgAAAQEYBJKRABQCACNAAAAkAEE2AgBACIAFAAAMDDAAAUgAkCgQJIkQCAAGCAAAIAglQIUHCIAKEJAwFAABwCCBEFAgMAAAEhAEAQoUAAgBCEIABBC0ggABCAhAAECAAiBAAAEFESAAJCAWiQAAKUAEAiAEIgAQADABIAABgggAEKABAASEAQJgQhEAgCIAACEAQAAAJiAGwAAIQACQAA' },
  { num: 26, quizId: 'sweep-9-2-26', live: '2026-09-02', dateLabel: 'September 2, 2026', sunday: false, par: 120,
    field: 'AChFAQBAAAEBEAAkQCgIAEEABhQAEAAQAQCIEwCAAAgAAQQAADQMABAAAABABwAQAgACAAAiAQoGIQhMMQiggAAIIQoNEApAiUUAAAKABQAAhEFACCAAIARy8AAAAgsgHAgEAAFAsJIAAIAgWEASHAgBCgACCRAEIiEBLAAEIAIAEAICAgMAkkCAiQAAAQgqIAgIABACAAECIKMAEACQECAEBAQAAQAsMABZMIDBCAIAATBgAAMUAAQgABUQBBAAwIAACSAgBICgEEAAAAAgiCAAEAMAiAAAEQAOQpAIFAAA' },
  { num: 27, quizId: 'sweep-9-3-26', live: '2026-09-03', dateLabel: 'September 3, 2026', sunday: false, par: 120,
    field: 'ABIASAImIEAYBEBgIBAAgAAAAAwACAEIEEAQACMgInIhKgQZABABUgEAABCMAAAAiwAPgKQAAAACCBBkACwQAEEAGTAAEAAAAGgBACAJAAAEAAKEQACABAgQEAIggAAKAIABYAAGgCAgYABAAAFSQACAAAglIAAQmAAIIJICDSEOAEYJgIAAEBAAQgQgAKJCiAfQTBQCQAgQEAYGCQAMBGkRgkMAAIAAABAEAgAERBAAwDEAgARAJAAJwAAoEhggIFQoglARAAAAAQkIBACEAiAkUoBiACAAgJAAACABAANA' },
  { num: 28, quizId: 'sweep-9-4-26', live: '2026-09-04', dateLabel: 'September 4, 2026', sunday: false, par: 120,
    field: 'ABEEiIQFAAFoACABQ2AAgAGEB4wBAAAAQBAELgA4AAAACIAAAKEiQIAgIAGANDCBAAgIkAcAJABIJAAFAISCgKBgABAEgAAIKIRQkAggAAIAQbAIAAAEAkAZQgIAACEAiGCIAAIIoGEACQIJQAAAAgCASQBhAAAFMCBISAAEBAxhAAIEBEBgAuAZAAgACgGABAAAPWaCBgCCEAAGACYAAAAgIAIAAAAQCWAEQoAAQEgQAgQAAADCCAggAAiRAIgAKACFABgAYBFAFAIAIACIIAhQACgQBBCFAADCAwkAAACA' },
  { num: 29, quizId: 'sweep-9-5-26', live: '2026-09-05', dateLabel: 'September 5, 2026', sunday: false, par: 120,
    field: 'AAAgIAkQAABIIgPEBAAIABAgQAUAADrRAgCAQRQAAIkARCIEQYgAQCyBAAAAggIoAAooIAgEAEAAaAABDJQgEABKAIIkAABBAhQAGgABBoAggQIQEUAIAEYMQCAQEASAaBnAAgAIBCBBAJCAAaAAACAkIAgJIJCCAIQQAEAEAAAgliCAFCEAmBAgQAAuAEAwUCAgAQQAQAAFASAAUCAEAABACABRQCEDgEQiAiPACCAAIABBAgABm4CAMgBAAhAABSARDAIABAABBBBSiIAAKggiADEAgxAAFBAEnICAoICh' },
  { num: 30, quizId: 'sweep-9-6-26', live: '2026-09-06', dateLabel: 'September 6, 2026', sunday: true, par: 90,
    field: 'AAQygAEAFACQAAjAMgAUAAjAAA4iEECCCIRAIXQMAAAACUWAFohYJIKBEKEECCQABCAIAAAQMCBAgFYAEGABhwIFYEwTBAQAIAATQBEgwKEgQAQAiZgAaJAgIIAAAQwABAACACYABAA4QKCAACQDQgIgAAXAFIgBCCJAgAQCAIESgAIgiHQHQAIUAIAAYIQBIgHSAEAhBMAMAoAAAQCCJmAFAIgAEEYgYCAIgABAAYIASEEFACSIIAIYMgBUhAByBCCAQACEAkAEAAAgBMQgAQAikAAiACERiABNCgAGEhBg' },
  { num: 31, quizId: 'sweep-9-7-26', live: '2026-09-07', dateLabel: 'September 7, 2026', sunday: false, par: 120,
    field: 'AAQAlgAIJQACAgEAADYAANBAAIIABaIQEGgAIBYNBhAEACgQUFAyAKACBQIIoEGQAABA9EAAAEAAgAACLI4EAwAgIAAAQBEAAQACQSMQwABAACBeIBhAAAFAAAiCIRBAAACGAYEAQBGCQgCACEkAyCGDAAAARYACQAAkIECEZCgQMChBIACQMEhQAAAERAghAMCQAgAAogoAADNIwAQhAAAAUAgIxAEAAwCgFEA4ACRQQoECkECCAEAIggAAALEACgGIAAhAAAAAAAIQCAFwACCABRAhAEkQgQQAUAAQAAAA' },
  { num: 32, quizId: 'sweep-9-8-26', live: '2026-09-08', dateLabel: 'September 8, 2026', sunday: false, par: 120,
    field: 'AEgAxDASAAAGFAAQBAQQAAAAAEoBCUAIQAmAABCASIAQwAAAwAEAEAQhAEAAgIcAg4AAAQoBCEAFISAABAABJAAIRAIAEQiJAAAAABEEKQMASIABCICAEBQigBgAAAAASYEAmAAQAAigDBAgIgEBAAhAAYAiXAABgIAAYEBAAAAQAAEgAAggIDAAIAFAEAAAAGAAAAIBJEAAAABABADAAjAoQAoAACRwAECCQAAAAxAAAgAAgAAggAEAAIwiAAgUDCMgIIAiSEAAoBABAEGAgAAIASCgBAAAEASEGADJAAQA' },
  { num: 33, quizId: 'sweep-9-9-26', live: '2026-09-09', dateLabel: 'September 9, 2026', sunday: false, par: 120,
    field: 'AEAACABgQAAAQCCIAASBIUAgABEgAAARAAABAEAgigCQECQMAAAoEABAAIIAAqjAAEBQqEABgACEEAQAgkgAAAghIABQFAApKCIAEECAIAYhAEogIEgAKACHhIAiEQgAAIBQGACIKAGCMAACKBiBCEAEIQgCAkAIAQgBQAIIACyAAECAAAgKECAAZBBAQQAgCQwCIAAAEAJECgAGBGBsBAEIAACAAIAAwEAAFAJAIEAIIEEAhAAACAAACBMBAkBgCEAQEIBgEAQQGQYAAAAgBJAVCLQAgAQAAFACAJDSAAAJ' },
  { num: 34, quizId: 'sweep-9-10-26', live: '2026-09-10', dateLabel: 'September 10, 2026', sunday: false, par: 120,
    field: 'AAEQCBIQQBCAAAUQAAYIQRAAgQhABEgkAKQABAgIiACAQBBAAQCAACAQYABCAQACCBIAAACGKECCUQI0UDAohBECAAAQQEDZIYACAGQAqERYQBAADAEAkAAAACECCBCAiEBAAQAAAAARQgCIBAA0EIAiAwgEAEEgCIEgBAggIQCAgIEAAAAAAEICgECQACEiACAAqAAEAQgCAAUAACABBIAAkAACIhACAhkFEABAIRDSYAgABkgIQwECAAAEAErACAgTEAAKgPAAAEAGRAABAgEJAYwCgBAEQQggAACBsIQA' },
  { num: 35, quizId: 'sweep-9-11-26', live: '2026-09-11', dateLabel: 'September 11, 2026', sunday: false, par: 120,
    field: 'AAEEBAAAMBBEcAIQARABQBRAEQCACApgAACAIAAjAEJgAAAQAAAgCAhnAAEACFDAAAQCJRgAgCAAioQABESAoAAgCAQAAAEABAAIYAEgAEAAKBIAAABQGKIAAAAAAAEhAAFUAhAAjAgAEDAAUQKAAAEAAwUEAgAAJKRAgIQBBQADIAQAgCIAAiAEAEVgIBADgAAAAYCQAEAQ1ICEAAAgmQAAFCgQkFAJEgA+DAAEhAgQACAUIAEAAAABQCIAiQAAABgDEgAMAgiQCIAAAgEJAAkQEIAORAMBBIIAAAAAgAIA' },
  { num: 36, quizId: 'sweep-9-12-26', live: '2026-09-12', dateLabel: 'September 12, 2026', sunday: false, par: 120,
    field: 'AEAABAAbziABANAiAKRRRASQwAYIiBBkIAgQABAAAGYABiEAFgIEAA9CUAZBAAGgIYAAAgRAAgJAAAAABAJACoEaQACAAUABQAAEAgABkAGIgAAgAICAOAAgBAAABAgJIDAACDBAgAwAgABAglAGgQKgAgAAMAAAACwgAAsAQY0AAmEB6BAgwAwiACEIAEQAAMAAGCQCMARAgAEBDBAhAKC04AIAGyBIIIBEAgRgARBgEGIAASAgAqAGSBECIAAgkIUAAAoVAEEAEFAkAAAFIAoABAAAinDAdQAAAAAMEkAA' },
  { num: 37, quizId: 'sweep-9-13-26', live: '2026-09-13', dateLabel: 'September 13, 2026', sunday: true, par: 90,
    field: 'AAACIIIABAKAABgAECAAACABCLAiIQBwAoBUAgAAAiVAQACEBALIECEkAgAGEBQEAGBgbAMZAAIDBCAQAtIAAAAAAACgAAkgkMASJCAAARgACVsAgACQABJEcIBAAQooYggABBAAQmEiERCCEgBQEgBFEjMhMCGAAIAKIAQDCBADlQRCBRQkwgIAcAoAGOACAgBoBgAIAAC4IBT4AIAEQEFDACKAAAAQAgBjAAAAIIh8AQAAAAIIIQAoQAgAAxAgAGwCAECBYABAAAAMDAgZAgAAbAIEygECAAGggAgggAhg' },
  { num: 38, quizId: 'sweep-9-14-26', live: '2026-09-14', dateLabel: 'September 14, 2026', sunday: false, par: 120,
    field: 'AAQIAABCBJAAIFIAAASUIgEBAACIAASAgpCAJFhAIAQAAgAAQBZIgkAIAwCgCcAECIAAoLBAFUEFAHJmgAABAMCCEAAABwgBEoAAWWAAqGIAAIAAjUBAUQBSYyDQAPAhAAGIAAAgGABECAABQgAIEAAIAkIAkIBACICIAAAQAAAAJAAlAAAzAABAECAiQAAAAQiJBAAwmBQIVIBkQRAABUAAAAAiAAiAAAEAAAgIQYAAhCCACAAgACoAIACAAAgAEIABASFBGAAEACCBBAFVACmAACOAAIIAACAIYAABAg1Q' },
  { num: 39, quizId: 'sweep-9-15-26', live: '2026-09-15', dateLabel: 'September 15, 2026', sunday: false, par: 120,
    field: 'AFBMIACAGgAQAEAAIIEBAAACMAAIAACmABAIFAASKYCgAAAAAEAFBQAAAC0gggiEEBQAEAAACwAAAhYBgEQABACECEJCAAJEgAQQKAEAAAgjQiEA0BDAQDCAIQPIIEEABIBgABhAAQABgCAEAAgSAABAwIAgEAAAAMAACSAIKgANBAkgABAAQIsFCoQIAASAIAIBCxBAQKAiIAUgBQKIRAAIHMCERQCBMBLIBAMEACAEQggAQNRAmABAAAAACQCwACEAAIEAAAIGAApAEIDEARAsQCgACAhsABAAlAQBACAA' },
  { num: 40, quizId: 'sweep-9-16-26', live: '2026-09-16', dateLabel: 'September 16, 2026', sunday: false, par: 120,
    field: 'ACAEAAAQCAAACEIAAAWAQAgAgwYBQEAKIQggCQoQgAAAAQAAgACAAEAQIADAAQCAAAAwAAACAkESQAAogAGBBUACIgQJAAAAAYQAAIAYAgDAAgAAAACACAdIEgAMQEAAQIQGhmICgAIEAAjVIIUCACAAAQmAQsAgEgEEAACAACAEAFBgAKAQAAIAABAGBgBMAAERAhEagBAIAJQBhYAgQDACBAAAIIBBAHABQBAAAABgIQKIAIADAAIgIEABQBCAgIaRoAAIgQRiAAFBggAoEAIAiBIIAMAEAAiAUAQEMBAG' },
  { num: 41, quizId: 'sweep-9-17-26', live: '2026-09-17', dateLabel: 'September 17, 2026', sunday: false, par: 120,
    field: 'AAdmAESBABqsBOAIAAgAgIAEgYTEkAAAgAABAEiAhAgAAiIMkCAkAEAoBBAAAIKJBAChMEABCIBQIiAQSRAICAYAAQOBYIBRIIMAACIQECAAADIAJQEAABjABAAQAAAADMBAIAhIMgGCGAmJPAhRgAAQIg0ABIYAFYGAAiDgAAghAFCAACgEAIABESIUBCYIAgAAAIEAwBxQAkAFAAAEIAGAEAAIIAAJBgECIACwUAgBiQoAIADAIIAQwAGAAAAiEAEIRCSwBIAQCgwAxAgEASAiAgEEMEgYBESRAQAgAAQm' },
  { num: 42, quizId: 'sweep-9-18-26', live: '2026-09-18', dateLabel: 'September 18, 2026', sunday: false, par: 120,
    field: 'AAgAAIAAECQAAICgAAoQAoKABAAiE4AwAAEBAAAAAAAAgCAEAoDBKACEiEQCAIAgiAYMHIgCRAggABEgBVBASEBAAgIggAQkIADAAAggBIAGQBMAACB4gEgABBCAIAwYAAACAAAAOkBCIwAAQ3AAShAAEEEACgDQAAkOAkQEAIEAAAAQAIJxFAgAAACGABAEBgQAwAsAEIRAAQCBRAAAQQyACESABCCERAgAAYIYxAAAGABAQAAkQCIAkAQAACqIRQAAIEMAAABAQAAAIAAGCAAAAQAICAESIgCAAEIAIEQg' },
  { num: 43, quizId: 'sweep-9-19-26', live: '2026-09-19', dateLabel: 'September 19, 2026', sunday: false, par: 120,
    field: 'AFBYAEAIgIgCQCgAEACSAkAAECABBQgoApAAwkBAAAAIAoAAAigAFgAAQJEFAI5BAQgAAAAAAABEAAAgQBoQRAARGgoABCBOEEAAAKABBACESCIgIAEIAAxgAICAAQBBAIAALICAEIhEAJwgAQCAEkRIIAAASWIAAOIAEYAIAAIQFsgBCEECkYEAAEkAjEFEIgsoAQQgggAQQAAYBADCEAAAUIAAEKBgAAKBQAEAIA0QMgAAABAAAYABBJFAEFQQBQgAARgABAAAAQAAAYAsQJAAAAogAIAgAQMJAAABAgQI' },
  { num: 44, quizId: 'sweep-9-20-26', live: '2026-09-20', dateLabel: 'September 20, 2026', sunday: true, par: 90,
    field: 'AAEAlMQCIIQACEAiAAADQAaAgBIgoAAgKoJCEAAhAlAUAADBBEggEAAQQQIApCIAABChEBEgFAEICTSIBAgwIIABBBiAQijoIAMAAQACSAQEQAAAQwgQDDgCoCBoGAAEUAQCAEAIglAYEAEEAAGk5AAAEQAIQ0DBAEAAQAEEIAAhQCACAwAAASCAESgABAAoiQEEAEgTAgSgACwFBAhgATmAAoARAABMAAICAKFAEBCISJAAgEQQIAAFLAAdBBIQADIQAEAAAqoBAROAAAACgBUAAoAAAEEAICFgAwIAEMAA' },
  { num: 45, quizId: 'sweep-9-21-26', live: '2026-09-21', dateLabel: 'September 21, 2026', sunday: false, par: 120,
    field: 'ACAkJwQIgCA4AAIACIAhABEAAOZQJEBAAJAACAAYQAgQAABAEAAA0EAECIIEAACACEAKCUAiRAJBgqABAABAIAAQoCiCBAAQAIIoEQCDAxAAIUAQCAoQIMIA0QgQEoQBhAIAAgAAQEAAIDQgBIAIAyADgAxAAAwGBIMIAAgAAEAAkhAQI5BAAwDDECAFQACCEAcBAAhAEAAKQAEQIAkQEdQAQEAnhAAAAAgRQEgAIAAIEFAAiAABCAAaAEAECUcQAAgEwAAggAIIhAACICDBAEAABAEAQBiCAQAgFCGBEjAA' },
  { num: 46, quizId: 'sweep-9-22-26', live: '2026-09-22', dateLabel: 'September 22, 2026', sunday: false, par: 120,
    field: 'AFwAZAJAhAEAQAQIBAoAHAAEQiIACCAFAIREhAgACAGEAYAEAAgBAKAIAAEAAggMwAFBJJAAEAIAMAoACQQAgAAACCCCKgEIFgKBAAIRBCAAAASOEAF0CgIAgAAIAIgAASAFgEAAA0CIACAQQACIAIADCGA1BQAAAAAAEiAwQEAANKAAAAAQQQAAYAOAAAEAAAEAWACAgEDAAKBALACglICIAhaAQABACAAQQIAggJAQAGwAAAbABAsgQQgAEhoBUAgAKRiAASEAAIAocSCAQkQAgAgyCABADAAAACAWAKGA' },
  { num: 47, quizId: 'sweep-9-23-26', live: '2026-09-23', dateLabel: 'September 23, 2026', sunday: false, par: 120,
    field: 'AAAgGEDAAAINASAxAAAAAAxgAAAQEBQAwCEEJIEQACAACUCBgIAgAAAMAAASIAFABEAQkIKAAMAAEAwgyABQEAQABQAIABIACGBBgACKAEGEBIAAQARBQASkAJCAEACYAEAACchQAAEAhQCBBQEGQCAgAARAAARgAAgAIEQIAAAChgEACEABBBghEAAAUIAYYQIIAgAIAQIoAQQBABAQAAJBEgAGgAABQQACAQAkCFAAACAAAUABQFCQAAwYAgCEDCBAAgABCAWAAAGAAfAAgAAAYIskAAAIQBQUCARagBkA' },
  { num: 48, quizId: 'sweep-9-24-26', live: '2026-09-24', dateLabel: 'September 24, 2026', sunday: false, par: 120,
    field: 'AAI0hIAAQAExKGAoAAIQIAQGCiMEIwAkAAICQEAgXIIAI5QBAkCMBICggABAAAAAEQCEE8ACkAAAKQAAIARCgEEEI0AgIABAAwBSEqQIAIEAAIEAAAioEAIAgIQAkhIFQQAAUBAEQAKgYQEAwAAAAAgoAAAaAIAAACAlCAQAABhABCERBDyAwIDAAIBMAJAAACAIUABI4AAgAiQDIAAAKFALAABhAQBDAAAwEAARAEIgIUIQYYIHAAQAgIECMiAQEAAAAAxIBoSAAAECBQAREABCGAAACEEAZBCA4iAAxEAA' },
  { num: 49, quizId: 'sweep-9-25-26', live: '2026-09-25', dateLabel: 'September 25, 2026', sunday: false, par: 120,
    field: 'AAIMIAAAEJwgQIAEABJJABICkAARQgAAIBAFMEDIgQLA6RAjAAQAAGAAmEQgACAAOYAAAIAEZAAJAIAYCoAERIAiEgAAAQCKBAUBEAAGACAQAhkQAgADYACAAABQFIAAAAABCAAqCBEAJQIAUAxUAJACCABASECgEDQAAEADnCAgJAJBggYQAAgUQAEAgAAMAAhAOAMAIBAAAhEAIAABwGMIAEJBAICAHAAoCCgAQhEAAFAQgBCCAgAEUAFKkAAQZIUAwCDIwADAiAJIBQRACAACCAgkoAgIIhCACAEgCgAC' },
  { num: 50, quizId: 'sweep-9-26-26', live: '2026-09-26', dateLabel: 'September 26, 2026', sunday: false, par: 120,
    field: 'AAABAACgARAAAIcEEAAgCRoQCxBgAEEQIDAAAAIQASgAAQgAAZABCAFCBAwMAoAASABAAQAkAAAAgAAABAIKAQAgIADAEAAACLQAgAAQAAAAIAAACgAGAAEBiAgAAAAMlAgIAIEA0AwIHAIgAgogAgFAHAKADIAxRAIAgohgkABUEDSAUgUBCAzICBIECUQAAAJGAAQBIBkAEJAFAAABQIAggAEAFYACCAQACJAIQAgCAMGcAAAGIKABRgIAQQGBESAAoABAAiAAqCAggSCgADCKZAQAAAQABAAgIAgKAkEB' },
  { num: 51, quizId: 'sweep-9-27-26', live: '2026-09-27', dateLabel: 'September 27, 2026', sunday: true, par: 90,
    field: 'AACAQAAuQAIBAAAggJgBgJQEDALEAAQCACAAIQAFAGMKRTBAAAoAAGglAAAnkAAAQRCADFAJgKACgQAFAAUQAgQAAAAACATABgkCCApwACJABAAXgSASQAAIEOAQAAAAEhAqCJAAyAAIAAcgAgBAIIIBBABEEICgCCgkAEEKEABCQAKgARIAIQQcIUIAKLJBlBAIAAkYQABMoAQPCMjAIAAAFAgAIAhIEAACAACGgJIJIBA0ACAAkAYIMEGEAAAAAAgGigRQAAoECgwRgBQCAAAAAACCRBARImIEEBCQQwFA' },
  { num: 52, quizId: 'sweep-9-28-26', live: '2026-09-28', dateLabel: 'September 28, 2026', sunday: false, par: 120,
    field: 'AAAAYEABgASEgBASAAIAAECQAkSAMAgCEEABAAIJAGCAIIAABgACAgAgGkACAAAAMEBKAREEAHQAgMSAkBAQKAAAACQAIAEQi4IRAAgAABRAAoEgEBQEBAAGCAEACAEAAgAgRggAMohBIGgAEAoAACAEICRIAIAACEQAAMCEAEIQhQIgAAAABABIwCCSAqggBIAAAAAABMAMAAACCIkBCYCAAAAIABAASkIyRAQAEAEARIAAkgAMAEkACAARKggkGAAAAjAQIAFAMAAEBACCAIDCIQgCCACEACBkAJQEIAgA' },
  { num: 53, quizId: 'sweep-9-29-26', live: '2026-09-29', dateLabel: 'September 29, 2026', sunday: false, par: 120,
    field: 'AAJBAgBAABBCRAAgAAAgEAYAAAoAAQCkAOAgAgAwoARAAAQAgCBIEAFQAEAAAAwgFmQIQAAkIBoEAAACEEAASMQACAQgAEJAAABDCQAIECIQUAIJAEBAABEAQAC0CQAIKAUQAAgREaDiCAYCAAIAwAQBAQIgmACogAUCIAEIAAADIAgAAAMJZAAEqAUAAAFEAkQhKBIogEADAAAQAAECEEAQoBEwCyCEAAAIIAkCQYIACFAhIYEAQBCAAAACAAADAA0CAIAAKAAgAAAAAIAABTYAiAAAQAAIQACQCARACIDA' },
  { num: 54, quizId: 'sweep-9-30-26', live: '2026-09-30', dateLabel: 'September 30, 2026', sunday: false, par: 120,
    field: 'AEAAAAAUAAABAACiAIAwglRAACAKAUXCEAACAAEAEAGIABgULAADjAgAIAgsAIAhEABEAIQRAAGgKIQAAJpAACAAAAACBAkQGJkKAIAMAAABAACEBEBAAABEMAAJJBgAAABACCAAANAYSIAAABABiACAAACAEAdCAgAAAWJAwJALIBAACECHDAAADAAAeAAcIEAAwHkkAAIJBARAIIgCGwGQBQBCAkQA2CFAEAMABADgDIAIAgAAEEDAsAakgEDEAQQAAAAACAEAABAQBABgAYAJAEgAiAAAQCNAAgAYAESF' },
  { num: 55, quizId: 'sweep-10-1-26', live: '2026-10-01', dateLabel: 'October 1, 2026', sunday: false, par: 120,
    field: 'AAABKkYOCBCAgQCIAUAAACAAEAAAAAACQAACAh0AAAIQAyBAACIDGIAYEABAAAFCABgAAgAmDIABoAEIqggEg4AECEBAoRABAIAdKHAQQCBAAABIAEgAAQBBAAEIIQCAQwQhADSABACAIAggEBABAIAAAAgIHACAIBIEEAAEgAAAABEgZkBQAAFAEHACghEAC4AEIAACAGgwCgCDAiASgAR8A4QogKEAABAAIIGBAEIEkAAwgJCAFgEqEgDBMAzAQkAQQgAIKGIAACwCAAgwIAEFABAAAAAAQBCAQQIAYAAA' },
  { num: 56, quizId: 'sweep-10-2-26', live: '2026-10-02', dateLabel: 'October 2, 2026', sunday: false, par: 120,
    field: 'ABAAAAQADEoAIABAlIAAYIgQAGQgAEhAEgCiIADEAAQgqABCCAAGgAIggEIwgAEgBICEACCAAIAAAkABABBQQhAAAACARAASAhGIIhQgAAiIiCAAQB4FG0AVBUAgQAQQiApgAAgIA4IwAEAgCAgCBAAUAAAgQAAALiQAAAQBAowAABgICIAQKAAAAEBcBGKBEAICAkANQCAAAgAAIAABQYAwQAAQyBACABKgAoACgI4AoAAJABiAAHmAAAEIAMIGIQQA2QBgkIBAExACgCgAgqEEEACIAwEAAAQRAAAgZABC' },
  { num: 57, quizId: 'sweep-10-3-26', live: '2026-10-03', dateLabel: 'October 3, 2026', sunday: false, par: 120,
    field: 'ABQgBBABLAAQACABkTAEAQJCECABAJKGAAEAEAAAAAAgECAMgwBCJAG0UABgIwIAgFQERAEAJBAAQCQAASgBQCgAEKAJBQjAAAgAAAABwJAIAkEAIQgwgEAAhYQZAAedAAAjQAJABAChFACBAEACgEAhBlCABIAgCBIFCACAUAgAACQAiAAEIMECAAASEBgIAAQgEAQAZAAgCYkQAARADQRKERAEIAAAgVAJAmICAgDEBAgICAAAAAIoAkEEUIIiFIQAwQAAQiKAYEBACLRMACABCMEZAgMEAAAAAQCIQwAB' },
  { num: 58, quizId: 'sweep-10-4-26', live: '2026-10-04', dateLabel: 'October 4, 2026', sunday: true, par: 90,
    field: 'AABIoBABAFMTgAQIgAEOABAA1gQANCQAACABSBgYAIQAAmEQiEATSAgBABQIQBEAgAwIAgEcIEBqBQgAJAAwYlIAAAgEGAEIMJAEAFqAQIgEJAEDBEiAGlGAAIsMYCACgAASFIAAMAEDEAcAYSgAgAEAVAAYDgAGgIIAChA0DhIg0YAgAAhyEARAIAIAAEBAoUBgAgAAQMggCAAGAgABnAAAAAIBEBAAhFggARMgFIAAAQOBBQIIIQKgmALQgAAAAABAomEgEQAAAgMDgACASAsEYAMAAAEQACBQAYAAgQEQ' },
  { num: 59, quizId: 'sweep-10-5-26', live: '2026-10-05', dateLabel: 'October 5, 2026', sunday: false, par: 120,
    field: 'AABAUAkGBIADCAAIKiQCEQICYAkyAAABA4ICBAggGwhiABaBAAFAAAACRBANEACAgAAAEEOMAgAKAhIYgENCBgAMAAAAKIAgEBWIBACAAIhAAAIQKABDDIQIEAEACAAAAS4GgEEgIIwIhABkgABJAASAQDAAAKAwAQpgAIQADKARQQAxIlAACAAAgAKABsAAwASEASCBAIAIqACQ0AAIAZYIASCAECAIAhAgAMECCgBgwAKoIBAAggDCAQEAAIgAAEACSAgAAACAmkAAI0ACgBiMCAAAAACEKAGSAIEQICEE' },
  { num: 60, quizId: 'sweep-10-6-26', live: '2026-10-06', dateLabel: 'October 6, 2026', sunday: false, par: 120,
    field: 'AAAgAAAAAAAIABAAgYABQAACAIACAIAAECEQsAAFAACAQDhIAQqDAUAAQBAgQAgAEAAAAAAAAUCASgAADgBDABQAAAAAoQAAgIEAAAAEoCACIQYJIAEkIHAIBHIAGAAIIsCkYIAAAAABUAUJAAgQAQACwIAEACASGHxAgCRAQAAAAEGKKAUFARCZgEAgCyADggAAAAUACEEBABRAAIAmExCAAREAhCABUAAASIQAICAAAAoAACAAJATKEAwBQBgACAAAAAAAQAqQQEEkIChAAFgIFCgAGEQCWCAAAAYA0EAB' },
];
