// ──────────────────────────────────────────────────────────────────────────
// Standardized-test practice data — six exams, each with ten hard, original
// questions and a 50-deep school ranking used for the "Where Will You Get In?"
// payoff. Consumed by app/exams/ExamQuizClient.jsx (the shared engine) and the
// hub at app/exams/page.js. Questions are original, written in each exam's
// style; school rankings are sourced from U.S. News (2025–26 / 2026) except the
// medical list, which uses a research-reputation ordering because U.S. News now
// publishes medical schools in tiers rather than numbered ranks.
//
// Each question: { type, q, prompt?, choices[], correct, note }. When `prompt`
// is present, `q` is the stimulus shown above the bold prompt (used for the
// reading/logic items); otherwise `q` itself is the bold prompt.
// ──────────────────────────────────────────────────────────────────────────

// correct count (0..10) -> 0-based start index of the 5-school reach window.
// A value of -1 means "below the threshold for a ranked program" — no school is
// named, the result screen shows an honest keep-studying message instead. The
// curve is deliberately harsh: 3/10 reaches only the very bottom of the top 50,
// and 0-2 correct clears no ranked program at all.
export const REACH_START = [-1, -1, -1, 45, 37, 28, 20, 13, 7, 3, 0];

const LAW_SCHOOLS = [
  'Stanford University', 'Yale University', 'University of Chicago', 'University of Virginia',
  'University of Pennsylvania (Carey)', 'Duke University', 'Harvard University', 'New York University',
  'University of Michigan (Ann Arbor)', 'Northwestern University (Pritzker)', 'Columbia University',
  'University of California, Berkeley', 'UCLA', 'Cornell University', 'University of Texas at Austin',
  'Washington University in St. Louis', 'Georgetown University', 'Vanderbilt University',
  'University of North Carolina (Chapel Hill)', 'University of Notre Dame', 'University of Minnesota',
  'Boston University', 'Boston College', 'Texas A&M University', 'University of Georgia',
  'University of Southern California (Gould)', 'Wake Forest University', 'Ohio State University (Moritz)',
  'Brigham Young University (Clark)', 'University of Wisconsin–Madison', 'George Washington University',
  'William & Mary', 'University of Alabama', 'George Mason University (Scalia)', 'University of Utah (Quinney)',
  'University of Iowa', 'Washington and Lee University', 'Florida State University', 'Emory University',
  'University of California, Irvine', 'Fordham University', 'University of Florida (Levin)', 'Baylor University',
  'Southern Methodist University (Dedman)', 'Arizona State University (O’Connor)', 'University of Colorado–Boulder',
  'Indiana University–Bloomington (Maurer)', 'Villanova University', 'University of Illinois Urbana-Champaign',
  'University of California, Davis',
];

const BUSINESS_SCHOOLS = [
  'Stanford University (GSB)', 'University of Pennsylvania (Wharton)', 'University of Chicago (Booth)',
  'Harvard University (HBS)', 'Northwestern University (Kellogg)', 'MIT (Sloan)', 'Columbia University',
  'New York University (Stern)', 'Dartmouth College (Tuck)', 'University of California, Berkeley (Haas)',
  'Yale University (SOM)', 'University of Michigan (Ross)', 'University of Virginia (Darden)',
  'Duke University (Fuqua)', 'Cornell University (Johnson)', 'UCLA (Anderson)',
  'Carnegie Mellon University (Tepper)', 'University of Texas at Austin (McCombs)',
  'University of Southern California (Marshall)', 'University of North Carolina (Kenan-Flagler)',
  'Indiana University (Kelley)', 'University of Washington (Foster)', 'Emory University (Goizueta)',
  'Georgetown University (McDonough)', 'University of Notre Dame (Mendoza)', 'Vanderbilt University (Owen)',
  'Rice University (Jones)', 'Washington University in St. Louis (Olin)', 'University of Florida (Warrington)',
  'Georgia Institute of Technology (Scheller)', 'University of Wisconsin–Madison', 'University of Minnesota (Carlson)',
  'Ohio State University (Fisher)', 'University of Georgia (Terry)', 'Arizona State University (W. P. Carey)',
  'University of Rochester (Simon)', 'Pennsylvania State University (Smeal)', 'Brigham Young University (Marriott)',
  'University of Maryland (Smith)', 'Michigan State University (Broad)', 'Purdue University (Daniels)',
  'Texas A&M University (Mays)', 'Boston University (Questrom)', 'University of California, Irvine (Merage)',
  'Southern Methodist University (Cox)', 'University of Illinois Urbana-Champaign (Gies)',
  'University of Tennessee (Haslam)', 'Boston College (Carroll)', 'University of Pittsburgh (Katz)',
  'University of Iowa (Tippie)',
];

const COLLEGES = [
  'Princeton University', 'MIT', 'Harvard University', 'Stanford University', 'Yale University',
  'University of Chicago', 'Duke University', 'Johns Hopkins University', 'Northwestern University',
  'University of Pennsylvania', 'Caltech', 'Cornell University', 'Brown University', 'Dartmouth College',
  'Columbia University', 'University of California, Berkeley', 'Rice University', 'UCLA', 'Vanderbilt University',
  'Carnegie Mellon University', 'University of Michigan (Ann Arbor)', 'University of Notre Dame',
  'Washington University in St. Louis', 'Emory University', 'Georgetown University',
  'University of North Carolina (Chapel Hill)', 'University of Virginia', 'University of Southern California',
  'UC San Diego', 'University of Florida', 'University of Texas at Austin', 'Georgia Institute of Technology',
  'New York University', 'UC Davis', 'UC Irvine', 'Boston College', 'Tufts University',
  'University of Illinois Urbana-Champaign', 'University of Wisconsin–Madison', 'UC Santa Barbara',
  'Ohio State University', 'Boston University', 'Rutgers University', 'University of Maryland',
  'University of Washington', 'Lehigh University', 'Northeastern University', 'Purdue University',
  'University of Georgia', 'University of Rochester',
];

const MEDICAL_SCHOOLS = [
  'Harvard University', 'Johns Hopkins University', 'University of Pennsylvania (Perelman)', 'Stanford University',
  'University of California, San Francisco', 'Columbia University (Vagelos)', 'Duke University',
  'Washington University in St. Louis', 'Yale University', 'New York University (Grossman)', 'Mayo Clinic (Alix)',
  'UCLA (Geffen)', 'University of Michigan', 'Cornell University (Weill)', 'University of Pittsburgh',
  'University of Washington', 'UC San Diego', 'Northwestern University (Feinberg)', 'Vanderbilt University',
  'University of Chicago (Pritzker)', 'Icahn School of Medicine at Mount Sinai', 'Emory University',
  'Baylor College of Medicine', 'University of North Carolina (Chapel Hill)', 'Case Western Reserve University',
  'University of Wisconsin–Madison', 'Boston University (Chobanian & Avedisian)', 'University of Southern California (Keck)',
  'Ohio State University', 'University of Texas Southwestern', 'University of Colorado', 'University of Virginia',
  'University of Minnesota', 'Oregon Health & Science University', 'University of Alabama at Birmingham',
  'University of Maryland', 'Indiana University', 'University of Rochester', 'University of Iowa (Carver)',
  'UC Davis', 'University of Florida', 'University of Cincinnati', 'University of Massachusetts (Chan)',
  'Georgetown University', 'Tufts University', 'University of Miami (Miller)', 'Wake Forest University',
  'Dartmouth College (Geisel)', 'University of Utah', 'Brown University (Alpert)',
];

// ── LSAT — hard logical reasoning ──
const LSAT_Q = [
  {
    type: 'Necessary assumption',
    q: 'Critic: The newly restored film cannot be considered the director’s authentic vision. The restoration team recolored several scenes that the director, working with the technology of his era, had deliberately left in black and white. A restoration that alters an artist’s deliberate choices fails to preserve the work’s authenticity.',
    prompt: 'The critic’s argument depends on assuming which one of the following?',
    choices: [
      'The director would have preferred color in those scenes had the technology been available to him.',
      'Authenticity is the most important criterion for evaluating any film restoration.',
      'No restoration that preserves a work’s authenticity alters any feature of the original whatsoever.',
      'The recoloring was not a change the director had himself sanctioned for a later restoration.',
      'The technology of the director’s era was incapable of producing color images.',
    ],
    correct: 3,
    note: 'If the director had authorized the recoloring for a future restoration, altering the black-and-white scenes would not betray his choices, and the argument collapses. (C) is far too strong, and (B) about importance is beside the point of whether THIS restoration is authentic.',
  },
  {
    type: 'Parallel flaw',
    q: 'Everyone who has mastered calculus has first mastered algebra. Priya has not mastered calculus. So Priya must not have mastered algebra.',
    prompt: 'The flawed reasoning above is most similar to that in which one of the following?',
    choices: [
      'Every accredited hospital employs at least one anesthesiologist. The clinic on Fifth Street is not accredited, so it employs no anesthesiologist.',
      'All published novelists have completed a manuscript. Tomas has completed a manuscript, so he is a published novelist.',
      'No reptile is warm-blooded. The platypus is warm-blooded, so the platypus is not a reptile.',
      'Most experienced pilots have flown at night. Dana is an experienced pilot, so Dana has very likely flown at night.',
      'If a bill has majority support, it will pass. This bill passed, so it had majority support.',
    ],
    correct: 0,
    note: 'The original treats a necessary condition as sufficient: lacking calculus is wrongly taken to mean lacking algebra (denying the antecedent). Only (A) repeats that exact error. (B) and (E) affirm the consequent; (C) is a valid contrapositive.',
  },
  {
    type: 'Strengthen',
    q: 'In a large company, employees who took the optional midday exercise class later used fewer sick days than employees who did not take it. The company concluded that the class reduces illness and is weighing whether to make it mandatory.',
    prompt: 'Which one of the following, if true, most strengthens the company’s conclusion?',
    choices: [
      'The class was taught by a certified fitness instructor.',
      'Sick-day use across the whole company declined during the year the class was introduced.',
      'Some employees who took the class reported that they enjoyed it.',
      'Employees who already used many sick days were less likely to enroll in the class.',
      'Employees who exercise regularly outside of work were no more likely to enroll in the class than other employees.',
    ],
    correct: 4,
    note: 'The threat to the causal claim is self-selection: if already-healthy, exercise-prone people chose the class, their fewer sick days prove nothing. (E) closes that gap. (D) actually deepens the selection problem.',
  },
  {
    type: 'Flaw',
    q: 'Spokesperson: Our critics claim our factory pollutes the river. But these same critics never acknowledge the hundreds of jobs the factory brings to this community. Until they give us credit for the good we do, their accusations about pollution deserve no response.',
    prompt: 'The reasoning is most vulnerable to criticism on the grounds that it',
    choices: [
      'treats the critics’ failure to disprove a claim as establishing that claim',
      'presumes, without warrant, that an organization providing benefits cannot also cause harm',
      'rejects a claim merely because of a perceived shortcoming in those who advance it',
      'relies on the testimony of people who are not experts about pollution',
      'draws a conclusion about one factory from a generalization about factories',
    ],
    correct: 2,
    note: 'The spokesperson refuses to engage the pollution claim because the critics are ungrateful — dismissing the argument by faulting its source. (B) is the trap, but the argument never asserts that benefits rule out harm.',
  },
  {
    type: 'Inference',
    q: 'Every council member who voted for the zoning change also voted for the tax levy. No council member who attended the budget workshop voted for the tax levy. Some council members who attended the budget workshop are first-term members.',
    prompt: 'If the statements above are true, which one of the following must also be true?',
    choices: [
      'No first-term council member voted for the zoning change.',
      'Some first-term council members did not vote for the zoning change.',
      'Every council member who voted for the tax levy voted for the zoning change.',
      'No first-term council member attended the budget workshop.',
      'Some council members who voted for the zoning change attended the budget workshop.',
    ],
    correct: 1,
    note: 'Workshop attendees did not vote for the levy, so (zoning → levy) they did not vote for the zoning change. Some first-termers attended the workshop, so those did not vote for the zoning change. (A) overreaches to ALL first-termers.',
  },
  {
    type: 'Sufficient assumption',
    q: 'If a scientific theory is genuinely explanatory, it rules out at least some conceivable observations. The theory of “universal vital energy” is compatible with every conceivable observation. Therefore, the theory of universal vital energy is not science.',
    prompt: 'The conclusion follows logically if which one of the following is assumed?',
    choices: [
      'Any theory that is genuinely explanatory is a science.',
      'A theory is a science only if it is widely accepted by experts.',
      'Some sciences rule out at least some conceivable observations.',
      'Only genuinely explanatory theories are sciences.',
      'No theory that is compatible with every observation is widely accepted.',
    ],
    correct: 3,
    note: 'The premises already make vital-energy theory non-explanatory. To reach “not science,” you need science to require being explanatory — that is, “only explanatory theories are science” (D). (A) runs the conditional backwards.',
  },
  {
    type: 'Resolve the paradox',
    q: 'A coastal town imposed a strict limit on the daily catch allowed per fishing boat, intending to let fish populations recover. Five years later, the total weight of fish caught per year in the town’s waters had actually increased, though the number of fishing boats was unchanged.',
    prompt: 'Which one of the following, if true, most helps to resolve the apparent discrepancy?',
    choices: [
      'Neighboring towns adopted similar catch limits over the same five years.',
      'The market price of fish rose sharply during the five-year period.',
      'The recovering fish population let boats reach their daily limit on far more days than they used to.',
      'Several boat owners retired and sold their boats to newcomers during the period.',
      'Some of the fish caught after the limit took effect were substantially larger than those caught before it.',
    ],
    correct: 2,
    note: 'A per-boat daily cap can still yield more total fish if a rebounding population lets every boat hit its cap on many more days. (E) is tempting, but a strict daily limit would still cap each day’s output.',
  },
  {
    type: 'Principle (application)',
    q: 'Principle: A person is morally responsible for a harmful outcome only if that person could have reasonably foreseen the outcome and could have acted otherwise.',
    prompt: 'Which one of the following judgments conforms most closely to the principle?',
    choices: [
      'Mara is responsible for a guest’s allergic reaction, though she had no way of knowing of the allergy, because she cooked the meal.',
      'Owen is responsible for the data loss because its consequences were severe, whether or not he could have prevented it.',
      'Lena is not responsible for missing the clearly marked deadline she chose to ignore, because the project was difficult.',
      'Priya is responsible for the traffic delay merely because she was present when it occurred.',
      'Devin could have foreseen that the worn ladder might break, but since no safer ladder was available and he had to reach the roof, he is not responsible for his fall.',
    ],
    correct: 4,
    note: 'The principle makes responsibility require BOTH foreseeability AND the ability to act otherwise. (E) tracks it exactly: Devin foresaw the risk but had no reasonable alternative. (A), (B), and (D) assign responsibility while a required condition is missing.',
  },
  {
    type: 'Role of a claim',
    q: 'Historian: It is often said that the printing press caused the rapid spread of literacy in early modern Europe. But in several regions literacy rates had already begun climbing decades before printed books became widely available there. The press surely accelerated a trend, but a trend cannot have been caused by something that postdates its beginning.',
    prompt: 'The claim that literacy rates had begun climbing before printed books became widely available plays which role in the argument?',
    choices: [
      'It is evidence offered against the claim that the printing press was the original cause of rising literacy.',
      'It is the main conclusion the historian’s argument is designed to establish.',
      'It is a general principle from which the historian’s conclusion is deduced.',
      'It is an example illustrating how the historian defines literacy.',
      'It is a concession that, if true, would undermine the historian’s own position.',
    ],
    correct: 0,
    note: 'The timing fact is the evidence that the press could not be the original cause (a cause cannot postdate the trend). The conclusion is the final causal claim; the timing point supports it.',
  },
  {
    type: 'Weaken',
    q: 'Nutritionist: A recent study found that people who regularly eat breakfast weigh less, on average, than people who skip it. Clearly, eating breakfast helps keep weight down, so anyone trying to lose weight should be sure to eat it.',
    prompt: 'Which one of the following, if true, most undermines the nutritionist’s recommendation?',
    choices: [
      'The study’s participants ranged widely in age.',
      'Among people actively trying to lose weight, those who added breakfast to their usual diet ate more total daily calories and gained weight.',
      'The study did not record what the participants actually ate for breakfast.',
      'Many people who eat breakfast also exercise in the morning.',
      'People who skip breakfast tend to eat substantially more later in the day.',
    ],
    correct: 1,
    note: 'The advice targets people trying to lose weight, and (B) shows that for exactly that group adding breakfast backfired. (D) weakens the general causal claim, but (B) strikes the actual recommendation far more directly.',
  },
];

// ── GMAT — quant problem solving, data sufficiency, critical reasoning ──
const GMAT_Q = [
  {
    type: 'Problem solving',
    q: 'Machine A can fill a tank in 6 hours and machine B in 9 hours. They run together for 2 hours, then A is shut off and B finishes the job alone. How long does the entire job take?',
    choices: ['5 hours', '5 hours 20 minutes', '6 hours', '6 hours 30 minutes', '7 hours'],
    correct: 2,
    note: 'Together they fill 1/6 + 1/9 = 5/18 per hour, so 2 hours fills 5/9. The remaining 4/9 at B’s rate of 1/9 per hour takes 4 hours. Total: 2 + 4 = 6 hours.',
  },
  {
    type: 'Problem solving',
    q: 'A solution is 20% acid by volume. How many liters of pure water must be added to 10 liters of this solution to make it 8% acid?',
    choices: ['10', '12.5', '18', '15', '25'],
    correct: 3,
    note: 'The 10 liters contain 2 liters of acid, which is unchanged. Set 2 / (10 + x) = 0.08, so 10 + x = 25 and x = 15 liters.',
  },
  {
    type: 'Problem solving',
    q: 'A committee of 3 people is chosen at random from 5 men and 4 women. How many possible committees include at least one woman?',
    choices: ['64', '70', '74', '80', '84'],
    correct: 2,
    note: 'Total committees: C(9,3) = 84. All-male committees: C(5,3) = 10. At least one woman: 84 − 10 = 74.',
  },
  {
    type: 'Problem solving',
    q: 'n is a positive integer and n² is divisible by 72. What is the largest integer that must divide n?',
    choices: ['6', '12', '24', '36', '8'],
    correct: 1,
    note: '72 = 2³·3². For n² to contain 2³, n must contain 2² (exponents in a square are even, so ≥4); for 3², n must contain 3¹. So n is divisible by 2²·3 = 12.',
  },
  {
    type: 'Critical reasoning',
    q: 'To curb turnover, a firm raised starting salaries 15%. In the following year, turnover among new hires fell sharply. Management concluded the raise caused the drop and plans to raise salaries again.',
    prompt: 'Which one of the following, if true, most weakens the conclusion?',
    choices: [
      'The firm’s leading competitors also raised salaries that year.',
      'During the same year a regional downturn sharply cut the number of jobs available elsewhere, so few employees could leave.',
      'The 15% raise significantly increased the firm’s payroll costs.',
      'A handful of new hires left despite receiving the raise.',
      'Employee satisfaction survey scores improved over the year.',
    ],
    correct: 1,
    note: 'If a downturn left employees with nowhere to go, the lower turnover may owe to the job market, not the raise — an alternative cause that undercuts the causal claim.',
  },
  {
    type: 'Critical reasoning',
    q: 'A retailer found that customers who use its mobile app spend more per visit than customers who do not. It plans to push every customer onto the app to raise overall spending.',
    prompt: 'Which one of the following, if true, most weakens the retailer’s plan?',
    choices: [
      'Developing and maintaining the app is expensive.',
      'Most of the retailer’s customers own smartphones capable of running the app.',
      'The customers who adopted the app were already the retailer’s highest-spending loyalty members before it launched.',
      'A few app users spend very little per visit.',
      'Several competing retailers also offer shopping apps.',
    ],
    correct: 2,
    note: 'If high spenders simply self-selected into the app, the app didn’t cause the spending, and pushing low spenders onto it need not raise their spending at all.',
  },
  {
    type: 'Problem solving',
    q: 'A car travels from town X to town Y at 40 mph and returns along the same road at 60 mph. What is its average speed for the round trip?',
    choices: ['48 mph', '50 mph', '52 mph', '45 mph', '55 mph'],
    correct: 0,
    note: 'Average speed for equal distances is the harmonic mean: 2·40·60 / (40 + 60) = 4800 / 100 = 48 mph — not the arithmetic mean of 50.',
  },
  {
    type: 'Problem solving',
    q: 'If x + 1/x = 4, what is the value of x² + 1/x²?',
    choices: ['12', '14', '16', '18', '8'],
    correct: 1,
    note: 'Square both sides: (x + 1/x)² = x² + 2 + 1/x² = 16, so x² + 1/x² = 14.',
  },
  {
    type: 'Problem solving',
    q: 'At a constant rate of simple interest, a sum of money doubles in 8 years. In how many years will it triple at the same rate?',
    choices: ['12', '14', '20', '24', '16'],
    correct: 4,
    note: 'Doubling means the interest equals the principal in 8 years. Tripling needs interest equal to twice the principal, which at the same rate takes 16 years.',
  },
  {
    type: 'Data sufficiency',
    q: 'Is the integer n even? (1) n² is even. (2) 3n is even.',
    prompt: 'Using the standard data-sufficiency answer choices, which applies?',
    choices: [
      'Statement (1) ALONE is sufficient, but (2) alone is not.',
      'Statement (2) ALONE is sufficient, but (1) alone is not.',
      'BOTH statements together are sufficient, but neither alone is.',
      'EACH statement ALONE is sufficient.',
      'The statements TOGETHER are not sufficient.',
    ],
    correct: 3,
    note: 'If n² is even, n is even (odd² is odd), so (1) suffices. If 3n is even, n is even (3 is odd), so (2) suffices. Each statement alone is sufficient.',
  },
];

// ── SAT — Reading & Writing + Math ──
const SAT_Q = [
  {
    type: 'Math · Heart of Algebra',
    q: 'If x² − 6x + 8 = 0 and x > 3, what is the value of x?',
    choices: ['2', '3', '8', '4'],
    correct: 3,
    note: 'Factor: (x − 2)(x − 4) = 0, so x = 2 or x = 4. The condition x > 3 selects x = 4.',
  },
  {
    type: 'Math · exponential growth',
    q: 'A bacteria population doubles every 3 hours. If it starts at 500, how many bacteria are there after 12 hours?',
    choices: ['2,000', '4,000', '8,000', '16,000'],
    correct: 2,
    note: '12 hours is 4 doublings (12 ÷ 3). 500 × 2⁴ = 500 × 16 = 8,000.',
  },
  {
    type: 'Math · linear functions',
    q: 'A line passes through the points (2, 5) and (6, 13). What is its y-intercept?',
    choices: ['0', '1', '2', '3'],
    correct: 1,
    note: 'Slope = (13 − 5)/(6 − 2) = 2. Using y = 2x + b with (2, 5): 5 = 4 + b, so b = 1.',
  },
  {
    type: 'Math · percentages',
    q: 'A price is first increased by 25%, then the new price is decreased by 20%. The final price is what percent of the original?',
    choices: ['95%', '105%', '100%', '110%'],
    correct: 2,
    note: '1.25 × 0.80 = 1.00, so the final price equals the original — exactly 100%.',
  },
  {
    type: 'Math · geometry',
    q: 'A circle has an area of 36π. What is its circumference?',
    choices: ['6π', '12π', '18π', '36π'],
    correct: 1,
    note: 'Area πr² = 36π gives r = 6. Circumference = 2πr = 12π.',
  },
  {
    type: 'Reading & Writing · words in context',
    q: 'The editor urged the writer to temper her sweeping claims with concrete evidence.',
    prompt: 'As used in the sentence, “temper” most nearly means',
    choices: ['moderate', 'intensify', 'ignore', 'conceal'],
    correct: 0,
    note: 'To “temper” a claim is to soften or moderate it — here, to qualify sweeping claims with evidence.',
  },
  {
    type: 'Reading & Writing · conventions',
    q: 'The collection of rare manuscripts ____ stored in a climate-controlled vault beneath the library.',
    prompt: 'Which choice conforms to the conventions of Standard English?',
    choices: ['are', 'were being', 'have been', 'is'],
    correct: 3,
    note: 'The subject is the singular “collection” (not “manuscripts,” which is in a prepositional phrase), so the singular verb “is” is correct.',
  },
  {
    type: 'Reading & Writing · transitions',
    q: '____ the bridge had been inspected only months earlier, engineers were stunned by its sudden collapse.',
    prompt: 'Which transition best fits the logic of the sentence?',
    choices: ['Because', 'Although', 'Therefore', 'For instance'],
    correct: 1,
    note: 'A recent inspection contrasts with a sudden collapse, so a concessive transition (“Although”) is needed, not a causal one.',
  },
  {
    type: 'Reading & Writing · inference',
    q: 'The novelist refused all interviews after her debut, yet her sales climbed each year, driven entirely by word of mouth among readers.',
    prompt: 'The sentence most strongly suggests that',
    choices: [
      'her books sustained interest without author promotion',
      'publicity is necessary for strong book sales',
      'reviewers generally disliked her work',
      'she came to regret avoiding interviews',
    ],
    correct: 0,
    note: 'Rising sales with no interviews and only word of mouth shows the books held interest on their own, without the author promoting them.',
  },
  {
    type: 'Reading & Writing · command of evidence',
    q: 'A student argues that a town’s new recycling program succeeded in its first year.',
    prompt: 'Which finding, if true, would most directly support that claim?',
    choices: [
      'The program was advertised on local radio and billboards.',
      'Most residents said in a survey that they liked the idea of recycling.',
      'The town’s landfill waste fell 30% in the year after the program began.',
      'Recycling bins were delivered to every household in town.',
    ],
    correct: 2,
    note: 'Success means a measurable result. A 30% drop in landfill waste is direct evidence of impact; advertising, attitudes, and bin delivery are inputs, not outcomes.',
  },
];

// ── ACT — English, Math, Reading, Science ──
const ACT_Q = [
  {
    type: 'Math · exponents',
    q: 'If 3^(x + 1) = 81, what is the value of x?',
    choices: ['3', '2', '4', '26', '27'],
    correct: 0,
    note: '81 = 3⁴, so x + 1 = 4 and x = 3.',
  },
  {
    type: 'Math · right triangles',
    q: 'In a right triangle, the side opposite a 30° angle has length 5. What is the length of the hypotenuse?',
    choices: ['2.5', '5', '5√3', '10', '10√3'],
    correct: 3,
    note: 'sin 30° = opposite / hypotenuse = 0.5 = 5 / h, so h = 10. (In a 30-60-90 triangle the hypotenuse is twice the short leg.)',
  },
  {
    type: 'Math · sequences',
    q: 'An arithmetic sequence has first term 4 and common difference 3. What is its 10th term?',
    choices: ['27', '30', '31', '34', '37'],
    correct: 2,
    note: 'aₙ = a₁ + (n − 1)d = 4 + 9 × 3 = 31.',
  },
  {
    type: 'Math · probability',
    q: 'A bag holds 3 red, 4 blue, and 5 green marbles. One marble is drawn at random. What is the probability it is NOT blue?',
    choices: ['1/3', '5/12', '1/2', '3/4', '2/3'],
    correct: 4,
    note: 'There are 12 marbles and 8 are not blue, so P(not blue) = 8/12 = 2/3.',
  },
  {
    type: 'English · sentence structure',
    q: 'The hikers reached the summit ____ they celebrated with a quiet lunch above the clouds.',
    prompt: 'Which choice produces a grammatically correct sentence?',
    choices: [
      'summit they',
      'summit, they',
      'summit; they',
      'summit: they',
    ],
    correct: 2,
    note: 'Two independent clauses joined with no coordinating conjunction require a semicolon. A comma alone (B) creates a comma splice.',
  },
  {
    type: 'English · concision',
    q: 'Choose the most concise version that retains the meaning: “The annual report, which comes out once a year, summarizes the firm’s finances.”',
    prompt: 'Which revision is best?',
    choices: [
      'The annual report, which comes out once a year, summarizes',
      'The annual report, an event happening yearly, summarizes',
      'The annual report summarizes',
      'The annual yearly report summarizes',
    ],
    correct: 2,
    note: '“Annual” already means once a year, so any added phrase saying so is redundant. (C) removes the redundancy cleanly.',
  },
  {
    type: 'English · modifiers',
    q: 'Which version contains no dangling or misplaced modifier?',
    choices: [
      'Walking through the museum, the paintings impressed Lena.',
      'Walking through the museum, Lena admired the paintings.',
      'Walking through the museum, the paintings were admired by Lena.',
      'The paintings, walking through the museum, impressed Lena.',
    ],
    correct: 1,
    note: 'The opening modifier “Walking through the museum” must describe the subject. Only in (B) is the walker (Lena) the subject; the others make the paintings walk.',
  },
  {
    type: 'Reading · inference',
    q: 'Although the inventor never profited from her design, every modern version of the device traces directly to her original patent.',
    prompt: 'Which inference is best supported?',
    choices: [
      'Her design turned out to be commercially worthless.',
      'Her design was foundational even though she did not profit from it.',
      'She sold her patent for a large sum of money.',
      'Modern devices differ entirely from her original design.',
    ],
    correct: 1,
    note: 'Not profiting is separate from influence; since every modern version traces to her patent, the design was foundational despite her lack of profit.',
  },
  {
    type: 'Science · interpreting results',
    q: 'A study finds that plants given red light grow taller, while plants given blue light grow bushier. A gardener wants the tallest possible plants.',
    prompt: 'Based on the data, the gardener should use',
    choices: ['blue light', 'red light', 'no light', 'equal red and blue light'],
    correct: 1,
    note: 'The data link red light to greater height, so red light is the choice for tall plants.',
  },
  {
    type: 'Science · reading a trend',
    q: 'In an experiment, a reaction’s rate rose as temperature increased from 10°C to 40°C, then fell as temperature rose further from 40°C to 60°C.',
    prompt: 'The reaction rate was highest at approximately',
    choices: ['10°C', '25°C', '40°C', '60°C'],
    correct: 2,
    note: 'The rate climbs up to 40°C and declines afterward, so it peaks at 40°C — typical of an enzyme-driven reaction that denatures at higher temperatures.',
  },
];

// ── GRE — verbal reasoning + quant ──
const GRE_Q = [
  {
    type: 'Text completion',
    q: 'Far from being ____, the senator’s remarks were so equivocal that listeners left the hall uncertain of her actual position.',
    prompt: 'Which word best completes the sentence?',
    choices: ['evasive', 'categorical', 'verbose', 'hostile', 'trivial'],
    correct: 1,
    note: '“Far from being ___” signals a contrast with “equivocal” (ambiguous). The opposite is “categorical” — clear and unqualified.',
  },
  {
    type: 'Text completion',
    q: 'The critic was famous for her ____ reviews: she praised nearly everything and rarely found any fault.',
    prompt: 'Which word best completes the sentence?',
    choices: ['caustic', 'equivocal', 'perfunctory', 'indulgent', 'austere'],
    correct: 3,
    note: '“Praised nearly everything” and “rarely found fault” describe an indulgent (lenient) critic. “Caustic” is the opposite.',
  },
  {
    type: 'Vocabulary',
    q: 'Which word is most nearly OPPOSITE in meaning to “laconic”?',
    choices: ['terse', 'blunt', 'aloof', 'candid', 'garrulous'],
    correct: 4,
    note: '“Laconic” means using few words. Its opposite is “garrulous” — excessively talkative.',
  },
  {
    type: 'Reading comprehension',
    q: 'While early critics dismissed the composer’s dissonances as errors, later scholars recognized them as deliberate departures that anticipated atonal music by a generation.',
    prompt: 'The passage suggests that later scholars regarded the dissonances as',
    choices: [
      'accidental mistakes of a careless composer',
      'intentional innovations ahead of their time',
      'techniques borrowed from atonal composers',
      'features universally admired in his own era',
      'irrelevant to the later development of music',
    ],
    correct: 1,
    note: '“Deliberate departures that anticipated atonal music” marks the dissonances as intentional innovations that came before, not after, atonal music.',
  },
  {
    type: 'Quantitative · statistics',
    q: 'The average (arithmetic mean) of five consecutive even integers is 20. What is the largest of the five integers?',
    choices: ['22', '24', '26', '28', '20'],
    correct: 1,
    note: 'For consecutive integers the mean is the middle value, so the set is 16, 18, 20, 22, 24, and the largest is 24.',
  },
  {
    type: 'Quantitative · algebra',
    q: 'When a number is increased by 25%, the result is 75. What is the number?',
    choices: ['50', '56.25', '60', '65', '100'],
    correct: 2,
    note: '1.25x = 75, so x = 60.',
  },
  {
    type: 'Quantitative comparison',
    q: 'Quantity A: 2¹⁰.  Quantity B: 10³.',
    prompt: 'Which of the following is true?',
    choices: [
      'Quantity A is greater.',
      'Quantity B is greater.',
      'The two quantities are equal.',
      'The relationship cannot be determined.',
    ],
    correct: 0,
    note: '2¹⁰ = 1,024 and 10³ = 1,000, so Quantity A is greater.',
  },
  {
    type: 'Quantitative · probability',
    q: 'One card is drawn at random from a standard 52-card deck. What is the probability that it is a face card (jack, queen, or king)?',
    choices: ['1/13', '1/4', '4/13', '3/13', '3/26'],
    correct: 3,
    note: 'There are 12 face cards (3 per suit × 4 suits), so the probability is 12/52 = 3/13.',
  },
  {
    type: 'Quantitative · geometry',
    q: 'A rectangle’s length is twice its width, and its perimeter is 36. What is its area?',
    choices: ['54', '64', '72', '81', '96'],
    correct: 2,
    note: 'L = 2W and 2(L + W) = 36 give W = 6 and L = 12, so the area is 12 × 6 = 72.',
  },
  {
    type: 'Text completion',
    q: 'Although the treaty was hailed as a triumph of ____, its vague language soon gave rise to precisely the disputes it was meant to forestall.',
    prompt: 'Which word best completes the sentence?',
    choices: ['belligerence', 'obfuscation', 'indifference', 'austerity', 'diplomacy'],
    correct: 4,
    note: 'A treaty celebrated as a triumph would be a triumph of “diplomacy.” The irony is that its vagueness then caused disputes.',
  },
];

// ── MCAT — biology, chemistry, physics, biochem, psych/soc ──
const MCAT_Q = [
  {
    type: 'Biochemistry',
    q: 'What is the net yield of ATP produced per glucose molecule during glycolysis alone?',
    choices: ['2', '4', '36', '38'],
    correct: 0,
    note: 'Glycolysis produces 4 ATP but consumes 2, for a net of 2 ATP (plus 2 NADH). The larger totals require the full aerobic pathway.',
  },
  {
    type: 'General chemistry',
    q: 'A weak acid has a pKa of 4.76. At a pH of 4.76, what is the ratio [A⁻]/[HA] of conjugate base to acid?',
    choices: ['0.1', '1', '10', '100'],
    correct: 1,
    note: 'By Henderson–Hasselbalch, when pH = pKa the log term is zero, so [A⁻]/[HA] = 1.',
  },
  {
    type: 'Physics',
    q: 'A 2 kg object is lifted 5 m at constant velocity. Using g = 10 m/s², how much work is done against gravity?',
    choices: ['10 J', '50 J', '100 J', '1,000 J'],
    correct: 2,
    note: 'Work against gravity = mgh = 2 × 10 × 5 = 100 J.',
  },
  {
    type: 'Genetics',
    q: 'Two parents are each heterozygous (Aa) for a gene with a recessive trait. What fraction of their offspring is expected to display the recessive phenotype?',
    choices: ['0', '1/2', '3/4', '1/4'],
    correct: 3,
    note: 'An Aa × Aa cross yields genotypes 1 AA : 2 Aa : 1 aa. Only aa shows the recessive phenotype — 1/4.',
  },
  {
    type: 'Physiology',
    q: 'Which segment of the nephron reabsorbs the largest fraction of filtered water and solutes?',
    choices: ['the proximal convoluted tubule', 'the glomerulus', 'the loop of Henle', 'the collecting duct'],
    correct: 0,
    note: 'The proximal convoluted tubule reabsorbs roughly two-thirds of filtered water and most filtered solutes. The glomerulus filters but does not reabsorb.',
  },
  {
    type: 'Biochemistry · enzymes',
    q: 'How does a competitive inhibitor affect an enzyme’s Michaelis–Menten kinetics?',
    choices: [
      'It decreases Vmax while leaving Km unchanged.',
      'It increases the apparent Km while leaving Vmax unchanged.',
      'It decreases both Vmax and Km.',
      'It increases Vmax.',
    ],
    correct: 1,
    note: 'A competitive inhibitor can be outcompeted by substrate, so Vmax is unchanged, but more substrate is needed to reach half-Vmax — the apparent Km rises.',
  },
  {
    type: 'General chemistry · redox',
    q: 'In the reaction Zn + Cu²⁺ → Zn²⁺ + Cu, the zinc atom is',
    choices: ['reduced', 'left unchanged', 'oxidized', 'the oxidizing agent'],
    correct: 2,
    note: 'Zinc loses two electrons (Zn → Zn²⁺), so it is oxidized; it acts as the reducing agent, while Cu²⁺ is reduced.',
  },
  {
    type: 'Physics · circuits',
    q: 'Two 4-ohm resistors are connected in parallel. What is their equivalent resistance?',
    choices: ['2 ohms', '4 ohms', '8 ohms', '16 ohms'],
    correct: 0,
    note: 'For two equal resistors in parallel the equivalent is half of one: 4/2 = 2 ohms (1/R = 1/4 + 1/4 = 1/2).',
  },
  {
    type: 'Psychology / sociology',
    q: 'A researcher observes that the mere presence of other people improves an expert’s performance on a well-practiced task. This effect is called',
    choices: ['groupthink', 'the bystander effect', 'deindividuation', 'social facilitation'],
    correct: 3,
    note: 'Social facilitation is the improvement of performance on simple or well-learned tasks in the presence of others.',
  },
  {
    type: 'Molecular biology',
    q: 'Translation of an mRNA molecule into a polypeptide takes place at the',
    choices: ['nucleus', 'ribosome', 'Golgi apparatus', 'mitochondrion'],
    correct: 1,
    note: 'Ribosomes carry out translation, reading mRNA codons and assembling the corresponding amino acids into a polypeptide.',
  },
];

export const EXAMS = {
  lsat: {
    slug: 'lsat',
    label: 'LSAT',
    name: 'LSAT',
    tagline: 'Law school admissions',
    blurb: 'Ten hard LSAT-style logical reasoning questions, 75 seconds each. We’ll match your score to a shortlist of law schools.',
    payoffNoun: 'law schools',
    rankingNote: 'School ranking: U.S. News & World Report Best Law Schools, 2025–26.',
    questions: LSAT_Q,
    schools: LAW_SCHOOLS,
  },
  gmat: {
    slug: 'gmat',
    label: 'GMAT',
    name: 'GMAT',
    tagline: 'MBA / business school admissions',
    blurb: 'Ten hard GMAT-style questions across quant, data sufficiency, and critical reasoning, 75 seconds each. We’ll match your score to a shortlist of business schools.',
    payoffNoun: 'business schools',
    rankingNote: 'School ranking: U.S. News & World Report Best Business Schools (MBA), 2026.',
    questions: GMAT_Q,
    schools: BUSINESS_SCHOOLS,
  },
  sat: {
    slug: 'sat',
    label: 'SAT',
    name: 'SAT',
    tagline: 'Undergraduate admissions',
    blurb: 'Ten hard SAT-style Reading & Writing and Math questions, 75 seconds each. We’ll match your score to a shortlist of colleges.',
    payoffNoun: 'colleges',
    rankingNote: 'School ranking: U.S. News & World Report Best National Universities, 2026.',
    questions: SAT_Q,
    schools: COLLEGES,
  },
  act: {
    slug: 'act',
    label: 'ACT',
    name: 'ACT',
    tagline: 'Undergraduate admissions',
    blurb: 'Ten hard ACT-style English, Math, Reading, and Science questions, 75 seconds each. We’ll match your score to a shortlist of colleges.',
    payoffNoun: 'colleges',
    rankingNote: 'School ranking: U.S. News & World Report Best National Universities, 2026.',
    questions: ACT_Q,
    schools: COLLEGES,
  },
  gre: {
    slug: 'gre',
    label: 'GRE',
    name: 'GRE',
    tagline: 'Graduate school admissions',
    blurb: 'Ten hard GRE-style verbal and quantitative questions, 75 seconds each. We’ll match your score to a shortlist of graduate universities.',
    payoffNoun: 'graduate programs',
    rankingNote: 'School ranking: U.S. News & World Report Best National Universities, 2026.',
    questions: GRE_Q,
    schools: COLLEGES,
  },
  mcat: {
    slug: 'mcat',
    label: 'MCAT',
    name: 'MCAT',
    tagline: 'Medical school admissions',
    blurb: 'Ten hard MCAT-style questions across biology, chemistry, physics, and psychology, 75 seconds each. We’ll match your score to a shortlist of medical schools.',
    payoffNoun: 'medical schools',
    rankingNote: 'School ranking: leading U.S. medical schools by research reputation (U.S. News now groups medical schools in tiers rather than numbered ranks).',
    questions: MCAT_Q,
    schools: MEDICAL_SCHOOLS,
  },
};

export const EXAM_ORDER = ['lsat', 'gmat', 'sat', 'act', 'gre', 'mcat'];
