// Puzzle data for Rung, the daily word ladder. Imported ONLY by the server page
// (app/rung/page.js), which filters live<=today before handing the bank to the
// client, so tomorrow's pair never reaches a browser.
//
//   start / target  the two ends of the ladder, both familiar words
//   par             the EXACT shortest ladder between them, by breadth-first
//                   search over VOCAB, confirmed by an independent bidirectional
//                   search. Weekdays 10 to 12 rungs, Sundays 15 or more.
//   routes          how many distinct shortest ladders exist, capped at 9999.
//                   Often 1, which is why matching par is hard.
//   example         one shortest ladder, shown only after the game ends.
//
// VOCAB is the whole word list, and it is the ONLY thing a rung may be: common
// five-letter words, built from the site's frequency list, filtered to words the
// dictionary knows in lower case (which drops proper nouns) and then screened
// for anything unsuitable. Par is computed over exactly this list, so validating
// against exactly this list is what keeps par honest: a wider dictionary would
// let a player find a shorter ladder than the one par was measured on.
export const VOCAB = ["abide", "abode", "abort", "about", "above", "abuse", "acorn", "adapt", "adept", "admin", "admit", "adobe", "adopt", "adore", "adorn", "alert", "alien", "align", "alley", "allow", "alloy", "aloha", "alone", "along", "aloud", "alpha", "altar", "alter", "among", "ample", "amuse", "angel", "anger", "angle", "ankle", "apple", "apply", "arbor", "arise", "armor", "arose", "aside", "assay", "audio", "audit", "avert", "awake", "award", "aware", "awoke", "bacon", "badge", "baggy", "baked", "baker", "barge", "baron", "barre", "basal", "basic", "basil", "basin", "basis", "batch", "bathe", "baths", "baton", "beach", "beard", "beast", "beech", "began", "begin", "begun", "being", "belle", "belly", "bench", "benny", "berry", "berth", "biker", "billy", "binge", "bingo", "birch", "birth", "black", "blade", "blame", "bland", "blank", "blast", "blaze", "bleak", "bleed", "bleep", "blend", "bless", "blind", "blink", "bliss", "block", "bloke", "blond", "blood", "bloom", "blown", "bluff", "blunt", "blush", "board", "boast", "bobby", "bogus", "bonus", "boost", "booth", "booty", "bound", "bowed", "bowel", "bower", "boxer", "brace", "braid", "brain", "brake", "brand", "brass", "brave", "bravo", "brawl", "bread", "break", "breed", "brent", "bribe", "brick", "bride", "brief", "brill", "brine", "bring", "brink", "brisk", "broad", "brock", "broke", "brood", "brook", "broom", "broth", "brown", "brunt", "brush", "buddy", "budge", "buggy", "build", "built", "bulge", "bulky", "bully", "bunch", "bunny", "burnt", "burst", "butch", "cabal", "cable", "cadre", "caged", "camel", "cameo", "canal", "candy", "canoe", "canon", "carry", "carte", "carve", "caste", "catch", "cater", "cause", "cease", "cello", "chain", "chair", "champ", "chant", "charm", "chart", "chase", "cheap", "cheat", "check", "cheek", "cheer", "chess", "chest", "chick", "chico", "chief", "child", "chili", "chill", "chime", "china", "chino", "choir", "choke", "chord", "chore", "chose", "chuck", "chunk", "cider", "cisco", "civic", "civil", "clamp", "clash", "clasp", "class", "clean", "clear", "click", "cling", "cloak", "clock", "clone", "close", "cloth", "cloud", "clout", "clown", "coach", "coast", "cocky", "colon", "color", "condo", "conte", "coral", "couch", "cough", "could", "count", "court", "coven", "cover", "craft", "cramp", "crane", "crank", "crash", "crate", "crave", "crawl", "craze", "crazy", "cream", "creed", "creek", "creep", "creme", "crept", "crest", "crime", "crock", "croft", "crook", "crore", "cross", "crowd", "crown", "crush", "crust", "crypt", "cubic", "curly", "curry", "curse", "curve", "curvy", "daddy", "daily", "dairy", "daisy", "dance", "dandy", "dated", "dazed", "death", "debit", "debut", "decal", "decay", "decor", "decoy", "delay", "demon", "dense", "depth", "derby", "derry", "deter", "diner", "disco", "ditch", "diver", "dixie", "dodge", "dodgy", "doggy", "doing", "dolly", "donna", "donor", "dough", "draft", "drain", "drake", "drank", "drawn", "dread", "dream", "dress", "drier", "drift", "drill", "drink", "drive", "drone", "drove", "drown", "drunk", "dryer", "dummy", "dusty", "dutch", "dwell", "eager", "eaten", "eater", "eight", "elect", "emery", "enact", "enjoy", "enter", "envoy", "erect", "essay", "ester", "ether", "every", "exact", "excel", "expel", "fable", "faint", "fairy", "fancy", "farce", "fatal", "fatty", "fault", "fauna", "feast", "felon", "fence", "feral", "ferry", "fetal", "fetch", "fever", "fiber", "field", "fiend", "fifth", "fifty", "fight", "filly", "filth", "finch", "fired", "firth", "fitch", "fixed", "fixer", "flake", "flame", "flank", "flare", "flash", "flask", "flesh", "flick", "fling", "flint", "flirt", "flock", "flood", "floor", "floss", "flour", "flown", "fluff", "fluke", "flung", "flush", "flute", "focal", "focus", "foggy", "folio", "folly", "footy", "foray", "force", "forge", "forte", "forty", "found", "frail", "frame", "franc", "frank", "freak", "fresh", "front", "frost", "frown", "fudge", "fully", "funky", "funny", "furry", "gable", "gamma", "gemma", "genes", "genie", "genre", "genus", "giant", "given", "giver", "gland", "glare", "glass", "glaze", "glide", "globe", "gloom", "gloss", "glove", "going", "gonna", "goods", "goody", "goofy", "goose", "gorge", "grace", "grade", "graft", "grail", "grain", "grand", "grant", "grape", "graph", "grasp", "grass", "grate", "grave", "gravy", "graze", "great", "greed", "green", "greet", "grief", "grill", "grime", "grind", "groan", "groin", "groom", "gross", "grove", "growl", "grown", "grunt", "guess", "guest", "guide", "guild", "guilt", "guise", "gully", "hairy", "handy", "happy", "hardy", "harry", "harsh", "haste", "hasty", "hatch", "hater", "haven", "heard", "heart", "heath", "hedge", "hefty", "heist", "hello", "hence", "highs", "hilly", "hinge", "hippo", "hippy", "hitch", "hoard", "hobby", "hogan", "hoist", "holly", "homer", "honey", "honor", "horde", "horse", "hotel", "hound", "house", "hover", "howdy", "hubby", "humor", "hunch", "hurry", "hurst", "hutch", "hydra", "hydro", "inept", "inert", "infer", "inner", "intel", "inter", "ionic", "jelly", "jenny", "jerky", "jerry", "jetty", "joint", "joker", "jolly", "judge", "juice", "juicy", "kelly", "kinda", "kinds", "kitty", "knack", "knock", "kraft", "label", "lager", "lance", "large", "laser", "latch", "latte", "layer", "leach", "leafy", "leaky", "leapt", "lease", "leash", "least", "leave", "ledge", "leech", "lefty", "legal", "lemon", "level", "lever", "libel", "light", "lined", "linen", "liner", "lingo", "liter", "liver", "lobby", "local", "locus", "lodge", "lofty", "logan", "logic", "login", "loner", "loose", "lorry", "loser", "lotto", "lotus", "loved", "lover", "lower", "loyal", "lunch", "lying", "lynch", "macho", "macro", "mafia", "magic", "magma", "major", "maker", "mamma", "manga", "mango", "mania", "manic", "manor", "march", "marge", "maria", "marry", "marsh", "match", "matte", "mayor", "medal", "media", "medic", "melon", "mercy", "merge", "merle", "merry", "messy", "metal", "meter", "metro", "micro", "might", "milky", "mince", "miner", "minor", "minus", "missy", "misty", "mixed", "mixer", "modal", "model", "modem", "moist", "molly", "mommy", "monde", "money", "monte", "month", "moody", "moose", "moral", "moray", "morse", "motel", "moths", "motor", "motto", "mound", "mount", "mouse", "mouth", "moved", "mover", "mower", "muddy", "mummy", "munch", "mural", "myths", "nacho", "naive", "naked", "named", "nancy", "nanny", "nasal", "nasty", "natal", "naval", "needy", "nelly", "nerdy", "nerve", "never", "niece", "nifty", "night", "noise", "noisy", "north", "nudge", "nurse", "oasis", "onion", "other", "otter", "overt", "owned", "owner", "paddy", "padre", "paint", "palsy", "panic", "paper", "parry", "party", "pasha", "pasta", "paste", "patch", "paths", "patio", "patsy", "patty", "pause", "paved", "payer", "peace", "peach", "pedal", "penal", "pence", "penny", "perch", "perry", "petal", "peter", "petty", "phase", "phone", "phony", "piece", "pilot", "pinch", "piper", "pitch", "pivot", "pixie", "place", "plaid", "plain", "plane", "plank", "plant", "plate", "playa", "plaza", "plead", "pleas", "plume", "plump", "plush", "point", "poise", "poker", "polar", "polio", "poppy", "porch", "posse", "potty", "pouch", "pound", "power", "prank", "press", "price", "pride", "prime", "print", "prize", "probe", "prose", "prove", "pubic", "pulse", "punch", "puppy", "purge", "purse", "quack", "quark", "quart", "queen", "queer", "quell", "quest", "quick", "quiet", "quill", "quilt", "quirk", "quite", "quota", "quote", "rabid", "radio", "rally", "randy", "rapid", "rated", "ratio", "raven", "reach", "react", "rebel", "regal", "relax", "relay", "remit", "remix", "renal", "repel", "retro", "revel", "rhino", "rhyme", "rider", "right", "rigor", "river", "roach", "roast", "rocky", "rodeo", "roger", "rogue", "roman", "romeo", "rondo", "roost", "roper", "rotor", "rouge", "rough", "round", "rouse", "route", "rover", "rowan", "rowdy", "rower", "royal", "ruddy", "rumor", "rural", "rusty", "saber", "saint", "sally", "salty", "sandy", "sassy", "sauna", "saved", "saver", "savoy", "savvy", "scale", "scalp", "scant", "scare", "scarf", "scary", "scene", "scent", "scoop", "scope", "score", "scorn", "scout", "scrap", "scrub", "scrum", "seine", "seize", "sense", "serge", "serum", "serve", "seven", "sever", "sewer", "shack", "shade", "shady", "shaft", "shake", "shaky", "shale", "shall", "shalt", "shame", "shank", "shape", "shard", "share", "shark", "sharp", "shave", "shawl", "shear", "sheen", "sheep", "sheer", "sheet", "shelf", "shell", "shift", "shine", "shiny", "shire", "shirt", "shock", "shone", "shook", "shoot", "shore", "short", "shout", "shove", "shrub", "shrug", "siege", "sieve", "sighs", "sight", "silky", "silly", "since", "sinus", "sissy", "sixth", "sixty", "skate", "skill", "skirt", "skull", "slack", "slang", "slant", "slash", "slate", "slave", "sleek", "sleep", "slept", "slice", "slick", "slide", "slime", "slimy", "sling", "slope", "sloth", "slump", "smack", "small", "smart", "smash", "smear", "smell", "smoke", "smoky", "snack", "snake", "snare", "sneak", "sniff", "snipe", "snoop", "snort", "snout", "snuff", "sober", "soggy", "solar", "sonar", "sonic", "sonny", "sorry", "sound", "south", "space", "spade", "spank", "spare", "spark", "speak", "spear", "speck", "specs", "speed", "spell", "spend", "spent", "spice", "spicy", "spike", "spill", "spine", "spire", "spite", "spoke", "spoof", "spoon", "spore", "sport", "spout", "spray", "squad", "squat", "squid", "stack", "staff", "stage", "stain", "stair", "stake", "stale", "stalk", "stall", "stamp", "stare", "stark", "start", "stash", "state", "stave", "stead", "steak", "steal", "steam", "steel", "steep", "steer", "stein", "stern", "stick", "stiff", "still", "sting", "stink", "stint", "stock", "stoke", "stole", "stomp", "stone", "stony", "stood", "stool", "stoop", "store", "storm", "story", "stout", "stove", "strap", "straw", "stray", "strip", "strut", "stuck", "stuff", "stump", "stung", "stunt", "style", "suede", "suite", "sully", "sunny", "surge", "swain", "swami", "swamp", "swear", "sweat", "swede", "sweep", "sweet", "swell", "swept", "swift", "swine", "swing", "swipe", "swoop", "sword", "swore", "sworn", "swung", "table", "tacky", "taken", "taker", "takin", "tally", "tamed", "tammy", "tango", "taper", "taser", "taste", "tasty", "taxed", "teach", "tease", "telly", "tempo", "tempt", "tense", "terra", "terry", "thank", "theme", "there", "these", "thick", "thief", "thine", "thing", "think", "thong", "those", "three", "threw", "throw", "thyme", "tiger", "tight", "timer", "tired", "toast", "token", "tonal", "toner", "tonic", "tooth", "topic", "torch", "total", "touch", "tough", "towel", "tower", "toxic", "toxin", "trace", "track", "tract", "trade", "trail", "train", "trait", "tramp", "trash", "tread", "treat", "trend", "triad", "trial", "tribe", "trick", "tried", "trope", "trove", "truce", "truck", "trump", "trunk", "truss", "trust", "tummy", "tumor", "tunic", "tutor", "twain", "tweed", "tweet", "tying", "unify", "union", "unite", "unity", "upped", "upper", "urine", "utter", "vague", "valor", "value", "valve", "vapor", "vault", "vegan", "verge", "verse", "vigor", "villa", "viola", "viper", "viral", "vital", "vocal", "vogue", "vouch", "vowel", "wacky", "wafer", "waged", "wager", "waist", "waive", "wally", "waste", "watch", "water", "weave", "wedge", "whack", "whale", "wheat", "where", "while", "whine", "white", "whole", "whose", "wield", "wight", "winch", "wired", "witch", "witty", "woman", "women", "woods", "woody", "world", "worry", "worse", "worst", "worth", "would", "wound", "woven", "wrist", "write", "wrote", "yeast", "yield", "youth", "yummy"];

export const PUZZLES = [
  {
    num: 1,
    quizId: 'rung-7-30-26',
    live: '2026-07-30',
    dateLabel: 'July 30, 2026',
    sunday: false,
    par: 10,
    start: 'suite',
    target: 'creep',
    routes: 1,
    example: ["suite", "spite", "spice", "slice", "slick", "click", "chick", "check", "cheek", "creek", "creep"],
  },
  {
    num: 2,
    quizId: 'rung-7-31-26',
    live: '2026-07-31',
    dateLabel: 'July 31, 2026',
    sunday: false,
    par: 11,
    start: 'shock',
    target: 'spend',
    routes: 2,
    example: ["shock", "shack", "slack", "black", "blank", "plank", "plant", "slant", "scant", "scent", "spent", "spend"],
  },
  {
    num: 3,
    quizId: 'rung-8-1-26',
    live: '2026-08-01',
    dateLabel: 'August 1, 2026',
    sunday: false,
    par: 12,
    start: 'suite',
    target: 'bread',
    routes: 7,
    example: ["suite", "spite", "spice", "slice", "slick", "slack", "black", "block", "brock", "brook", "brood", "broad", "bread"],
  },
  {
    num: 4,
    quizId: 'rung-8-2-26',
    live: '2026-08-02',
    dateLabel: 'August 2, 2026',
    sunday: true,
    par: 15,
    start: 'crane',
    target: 'theme',
    routes: 8,
    example: ["crane", "crank", "prank", "plank", "plane", "plate", "slate", "slave", "shave", "shale", "whale", "whole", "whose", "those", "these", "theme"],
  },
  {
    num: 5,
    quizId: 'rung-8-3-26',
    live: '2026-08-03',
    dateLabel: 'August 3, 2026',
    sunday: false,
    par: 10,
    start: 'shock',
    target: 'scene',
    routes: 2,
    example: ["shock", "shack", "slack", "black", "blank", "plank", "plant", "slant", "scant", "scent", "scene"],
  },
  {
    num: 6,
    quizId: 'rung-8-4-26',
    live: '2026-08-04',
    dateLabel: 'August 4, 2026',
    sunday: false,
    par: 11,
    start: 'suite',
    target: 'broad',
    routes: 5,
    example: ["suite", "spite", "spice", "slice", "slick", "slack", "black", "block", "brock", "brook", "brood", "broad"],
  },
  {
    num: 7,
    quizId: 'rung-8-5-26',
    live: '2026-08-05',
    dateLabel: 'August 5, 2026',
    sunday: false,
    par: 12,
    start: 'shock',
    target: 'speed',
    routes: 2,
    example: ["shock", "shack", "slack", "black", "blank", "plank", "plant", "slant", "scant", "scent", "spent", "spend", "speed"],
  },
  {
    num: 8,
    quizId: 'rung-8-6-26',
    live: '2026-08-06',
    dateLabel: 'August 6, 2026',
    sunday: false,
    par: 10,
    start: 'suite',
    target: 'creed',
    routes: 1,
    example: ["suite", "spite", "spice", "slice", "slick", "click", "chick", "check", "cheek", "creek", "creed"],
  },
  {
    num: 9,
    quizId: 'rung-8-7-26',
    live: '2026-08-07',
    dateLabel: 'August 7, 2026',
    sunday: false,
    par: 11,
    start: 'shock',
    target: 'steel',
    routes: 3,
    example: ["shock", "shack", "slack", "black", "blank", "bland", "blend", "bleed", "bleep", "sleep", "steep", "steel"],
  },
  {
    num: 10,
    quizId: 'rung-8-8-26',
    live: '2026-08-08',
    dateLabel: 'August 8, 2026',
    sunday: false,
    par: 12,
    start: 'suite',
    target: 'green',
    routes: 1,
    example: ["suite", "spite", "spice", "slice", "slick", "click", "chick", "check", "cheek", "creek", "creed", "greed", "green"],
  },
  {
    num: 11,
    quizId: 'rung-8-9-26',
    live: '2026-08-09',
    dateLabel: 'August 9, 2026',
    sunday: true,
    par: 16,
    start: 'shock',
    target: 'rouge',
    routes: 4,
    example: ["shock", "shack", "slack", "black", "blank", "plank", "plane", "place", "peace", "peach", "perch", "porch", "torch", "touch", "tough", "rough", "rouge"],
  },
  {
    num: 12,
    quizId: 'rung-8-10-26',
    live: '2026-08-10',
    dateLabel: 'August 10, 2026',
    sunday: false,
    par: 10,
    start: 'crane',
    target: 'crest',
    routes: 1,
    example: ["crane", "crank", "frank", "flank", "flask", "flash", "clash", "crash", "crush", "crust", "crest"],
  },
  {
    num: 13,
    quizId: 'rung-8-11-26',
    live: '2026-08-11',
    dateLabel: 'August 11, 2026',
    sunday: false,
    par: 11,
    start: 'suite',
    target: 'bloom',
    routes: 6,
    example: ["suite", "spite", "spice", "slice", "slick", "slack", "black", "blank", "bland", "blond", "blood", "bloom"],
  },
  {
    num: 14,
    quizId: 'rung-8-12-26',
    live: '2026-08-12',
    dateLabel: 'August 12, 2026',
    sunday: false,
    par: 12,
    start: 'shock',
    target: 'steal',
    routes: 3,
    example: ["shock", "shack", "slack", "black", "blank", "bland", "blend", "bleed", "bleep", "sleep", "steep", "steel", "steal"],
  },
  {
    num: 15,
    quizId: 'rung-8-13-26',
    live: '2026-08-13',
    dateLabel: 'August 13, 2026',
    sunday: false,
    par: 10,
    start: 'suite',
    target: 'sheer',
    routes: 1,
    example: ["suite", "spite", "spice", "slice", "slick", "click", "chick", "check", "cheek", "cheer", "sheer"],
  },
  {
    num: 16,
    quizId: 'rung-8-14-26',
    live: '2026-08-14',
    dateLabel: 'August 14, 2026',
    sunday: false,
    par: 11,
    start: 'shock',
    target: 'sweet',
    routes: 3,
    example: ["shock", "stock", "stick", "slick", "click", "chick", "check", "cheek", "cheer", "sheer", "sheet", "sweet"],
  },
  {
    num: 17,
    quizId: 'rung-8-15-26',
    live: '2026-08-15',
    dateLabel: 'August 15, 2026',
    sunday: false,
    par: 12,
    start: 'suite',
    target: 'greet',
    routes: 1,
    example: ["suite", "spite", "spice", "slice", "slick", "click", "chick", "check", "cheek", "creek", "creed", "greed", "greet"],
  },
  {
    num: 18,
    quizId: 'rung-8-16-26',
    live: '2026-08-16',
    dateLabel: 'August 16, 2026',
    sunday: true,
    par: 15,
    start: 'crane',
    target: 'there',
    routes: 8,
    example: ["crane", "crank", "prank", "plank", "plane", "plate", "slate", "slave", "shave", "shale", "whale", "whole", "whose", "those", "these", "there"],
  },
  {
    num: 19,
    quizId: 'rung-8-17-26',
    live: '2026-08-17',
    dateLabel: 'August 17, 2026',
    sunday: false,
    par: 10,
    start: 'shock',
    target: 'steer',
    routes: 2,
    example: ["shock", "stock", "stick", "slick", "click", "chick", "check", "cheek", "cheer", "sheer", "steer"],
  },
  {
    num: 20,
    quizId: 'rung-8-18-26',
    live: '2026-08-18',
    dateLabel: 'August 18, 2026',
    sunday: false,
    par: 11,
    start: 'suite',
    target: 'groom',
    routes: 5,
    example: ["suite", "spite", "spice", "slice", "slick", "slack", "black", "block", "brock", "brook", "broom", "groom"],
  },
  {
    num: 21,
    quizId: 'rung-8-19-26',
    live: '2026-08-19',
    dateLabel: 'August 19, 2026',
    sunday: false,
    par: 12,
    start: 'shock',
    target: 'sweat',
    routes: 5,
    example: ["shock", "stock", "stick", "slick", "click", "chick", "check", "cheek", "cheer", "sheer", "sheet", "sweet", "sweat"],
  },
  {
    num: 22,
    quizId: 'rung-8-20-26',
    live: '2026-08-20',
    dateLabel: 'August 20, 2026',
    sunday: false,
    par: 10,
    start: 'suite',
    target: 'blood',
    routes: 1,
    example: ["suite", "spite", "spice", "slice", "slick", "slack", "black", "blank", "bland", "blond", "blood"],
  },
  {
    num: 23,
    quizId: 'rung-8-21-26',
    live: '2026-08-21',
    dateLabel: 'August 21, 2026',
    sunday: false,
    par: 11,
    start: 'shock',
    target: 'swear',
    routes: 2,
    example: ["shock", "stock", "stick", "slick", "click", "chick", "check", "cheek", "cheer", "sheer", "shear", "swear"],
  },
  {
    num: 24,
    quizId: 'rung-8-22-26',
    live: '2026-08-22',
    dateLabel: 'August 22, 2026',
    sunday: false,
    par: 12,
    start: 'suite',
    target: 'steel',
    routes: 1,
    example: ["suite", "spite", "spice", "slice", "slick", "click", "chick", "check", "cheek", "cheer", "sheer", "steer", "steel"],
  },
  {
    num: 25,
    quizId: 'rung-8-23-26',
    live: '2026-08-23',
    dateLabel: 'August 23, 2026',
    sunday: true,
    par: 18,
    start: 'shock',
    target: 'house',
    routes: 4,
    example: ["shock", "shack", "slack", "black", "blank", "plank", "plane", "place", "peace", "peach", "perch", "porch", "torch", "touch", "tough", "rough", "rouge", "rouse", "house"],
  },
  {
    num: 26,
    quizId: 'rung-8-24-26',
    live: '2026-08-24',
    dateLabel: 'August 24, 2026',
    sunday: false,
    par: 10,
    start: 'crane',
    target: 'trust',
    routes: 1,
    example: ["crane", "crank", "frank", "flank", "flask", "flash", "clash", "crash", "crush", "crust", "trust"],
  },
  {
    num: 27,
    quizId: 'rung-8-25-26',
    live: '2026-08-25',
    dateLabel: 'August 25, 2026',
    sunday: false,
    par: 11,
    start: 'suite',
    target: 'breed',
    routes: 2,
    example: ["suite", "spite", "spice", "slice", "slick", "slack", "black", "blank", "bland", "blend", "bleed", "breed"],
  },
  {
    num: 28,
    quizId: 'rung-8-26-26',
    live: '2026-08-26',
    dateLabel: 'August 26, 2026',
    sunday: false,
    par: 12,
    start: 'shock',
    target: 'swept',
    routes: 3,
    example: ["shock", "stock", "stick", "slick", "click", "chick", "check", "cheek", "cheer", "sheer", "sheet", "sweet", "swept"],
  },
];
