// Puzzle data for Babel, the daily Scrabble-style endgame. Imported ONLY by
// the server page (app/babel/page.js), which filters live<=today AND strips
// `foe` before handing anything to the browser.
//
// The opponent's rack is never sent, and there is no tracker: the page prints
// the bag, the board is in front of you, and the subtraction is yours to do.
// The client derives `foe` the same way the player is meant to, purely to
// drive the engine.
//
// Each day is the tail of a real self-played game (scripts/gen-babel.mjs): the
// bag is empty and the player holds five tiles, six in the Sunday Edition. The
// Q lands wherever the game put it, which is on the board about three times in
// four and otherwise on one of the two racks.
//
// `benchmark` is the spread our solver ACHIEVES from the player's seat against
// the very defence the browser plays (solveLine in lib/babel-engine.js), so it
// is reachable by construction rather than a ceiling nobody can hit. It is a
// solver mark to beat, NOT an average round, which is why it is not called par.
// `greedy` is
// what grabbing the biggest number every turn gets you.
//
// Validate with scripts/verify-babel.mjs after ANY edit to this file or the
// engine. It replays every line and fails if a benchmark stops being reachable.
export const PUZZLES = [
  { num: 1, quizId: "babel-8-2-26", live: "2026-08-02", dateLabel: "August 2, 2026", sunday: true, benchmark: 43, greedy: 33,
    rack: ["D","L","K","A","O","O"], foe: ["O","U","I","L","R","R"],
    board: ["....NE.....", "....ET.....", "..J.SHALT..", ".QUIT.RE...", "DIM.I.FAUX.", "..PING.R...", "OBS.G..N...", "YE.....EM..", ".Z.....DA..", "..CAVE..C..", "...W.HONEST"] },
  { num: 2, quizId: "babel-8-3-26", live: "2026-08-03", dateLabel: "August 3, 2026", sunday: false, benchmark: 34, greedy: 7,
    rack: ["T","L","R","S","E"], foe: ["L","L","N","U","I"],
    board: ["...........", "...........", "..CAW.....F", "...MOA.C.AR", ".....VOR.ZA", "....QI.UPO.", "...HIDES...", ".NEON.THEY.", "DEEM.K..DOG", "AG.EXITS..J", "B..RIN.T..U"] },
  { num: 3, quizId: "babel-8-4-26", live: "2026-08-04", dateLabel: "August 4, 2026", sunday: false, benchmark: 54, greedy: 40,
    rack: ["L","W","U","D","I"], foe: ["R","R","Q","I","U"],
    board: ["V.R........", "OHO.C......", "LIT.U......", ".MANS..L...", "..TOP.JAK..", "..ET.GI.I..", "...CORNY.N.", ".FEH.A.AXES", ".EME.BE..ET", ".Z.D.SO..DA", "......N...G"] },
  { num: 4, quizId: "babel-8-5-26", live: "2026-08-05", dateLabel: "August 5, 2026", sunday: false, benchmark: 13, greedy: 1,
    rack: ["U","O","T","C","F"], foe: ["N","N","Q","R","A"],
    board: ["...G....C.V", "..NOX...U.I", "...R....T.N", "...G....I.E", "..ME.MODELS", "PHO.JEW..U.", "..BEATER.ZO", "...LI..YA.D", "....LATER.D", "....SAI...S", "......KHI.."] },
  { num: 5, quizId: "babel-8-6-26", live: "2026-08-06", dateLabel: "August 6, 2026", sunday: false, benchmark: 24, greedy: 11,
    rack: ["N","D","U","O","L"], foe: ["R","U","L","G","C"],
    board: ["QIS....HOOF", "U.T..CLAMP.", "I.AMA.ATE..", "Z.BOX.REN..", "...TE.G....", "..WISHED...", ".E.V..R....", ".N.E.......", ".JEST......", "IO..IRK....", "NY....AD..."] },
  { num: 6, quizId: "babel-8-7-26", live: "2026-08-07", dateLabel: "August 7, 2026", sunday: false, benchmark: 45, greedy: 36,
    rack: ["T","T","U","U","H"], foe: ["N","R","O","N","Q"],
    board: [".......BRIM", "REZ...SO...", "..AG.FAWN..", "..XU.ELL.E.", "...META..DI", "....RAD.C.O", "...PEL.JOYS", "...H...ATE.", "..DIVING.SI", ".KO.......C", "..........E"] },
  { num: 7, quizId: "babel-8-8-26", live: "2026-08-08", dateLabel: "August 8, 2026", sunday: false, benchmark: 27, greedy: -2,
    rack: ["R","R","T","A","Y"], foe: ["N","G","V","L","O"],
    board: ["P....K.MACE", "OB..CAW.X..", "LO.ZA.IDE..", "IT.AN.NUS..", "OHO.I.DE...", "..FINEST...", "HET.EM.....", "EL.J.U.....", "R.SI.......", "DRUG.......", "..Q........"] },
  { num: 8, quizId: "babel-8-9-26", live: "2026-08-09", dateLabel: "August 9, 2026", sunday: true, benchmark: 34, greedy: 23,
    rack: ["O","R","L","S","X","L"], foe: ["U","U","R","N","T","W"],
    board: ["..........Y", ".........GI", ".......QUID", "....Z.AIN..", "...BEST....", "..FISH...K.", ".JA.TELECOM", "CONE.DAE..O", ".N......TAV", "AG...EMPIRE", "H......OD.R"] },
  { num: 9, quizId: "babel-8-10-26", live: "2026-08-10", dateLabel: "August 10, 2026", sunday: false, benchmark: 26, greedy: 12,
    rack: ["O","O","L","E","P"], foe: ["R","N","U","U","M"],
    board: [".......S.RE", "..DEX.BA.AL", ".QIN.FOLKS.", "..VET.OE.HI", "TWA.HIM...N", "...JETS...T", "..COY....ER", "DRUG.....NA", "AID....CIG.", ".Z.........", "..........."] },
  { num: 10, quizId: "babel-8-11-26", live: "2026-08-11", dateLabel: "August 11, 2026", sunday: false, benchmark: 18, greedy: -17,
    rack: ["U","I","R","U","N"], foe: ["O","T","B","T","Q"],
    board: ["EUK....CALM", "THIEF...C..", "...X....R..", "..RAV..WE..", "...MARSH.L.", "..PINE.AGO.", "JOINED.LIG.", "OD.E...ES..", "...DZO.ST..", "....ANY....", "..........."] },
  { num: 11, quizId: "babel-8-12-26", live: "2026-08-12", dateLabel: "August 12, 2026", sunday: false, benchmark: 29, greedy: 21,
    rack: ["X","C","U","I","E"], foe: ["U","N","N","T","R"],
    board: ["..........C", ".........PA", "..JO.....ER", "...REV.ONTO", "....LOUSY.L", ".....W.....", "...LIST..K.", "..QI...OBE.", ".DIGS.HERTZ", "FAN.HEM.I.A", "AE.DAD..M.G"] },
  { num: 12, quizId: "babel-8-13-26", live: "2026-08-13", dateLabel: "August 13, 2026", sunday: false, benchmark: 12, greedy: -3,
    rack: ["N","O","A","K","I"], foe: ["L","N","U","T","A"],
    board: ["......SIEGE", "......C.DUN", "......R....", "......UT...", "....MIME...", "..JAYS.XI..", ".ZOL..ATT..", "GOR..QIS...", "AN....D.FOH", "RE..CLEVER.", "B..PHO..DEW"] },
  { num: 13, quizId: "babel-8-14-26", live: "2026-08-14", dateLabel: "August 14, 2026", sunday: false, benchmark: 28, greedy: 22,
    rack: ["D","T","E","W","I"], foe: ["U","L","D","N","T"],
    board: ["JAR........", "..ALF......", "..V..ZEROS.", "..ES...E.UG", "...PYA.C.QI", "..BEAM.KI..", "...EDITORS.", "...C...NON.", ".HEH....NUR", "LOX......GI", ".TOM......A"] },
  { num: 14, quizId: "babel-8-15-26", live: "2026-08-15", dateLabel: "August 15, 2026", sunday: false, benchmark: 34, greedy: 21,
    rack: ["E","N","I","D","U"], foe: ["I","O","R","P","B"],
    board: ["G..Q....TUN", "R.TI...MEGA", "O.U...KEX..", "WARD..NE...", "L.FEZ.O....", "....ATTIC..", "..HOS.S.Y..", ".JAR....C..", ".AHS....L..", "MI....EVEN.", "OLD........"] },
  { num: 15, quizId: "babel-8-16-26", live: "2026-08-16", dateLabel: "August 16, 2026", sunday: true, benchmark: 33, greedy: 19,
    rack: ["T","T","U","X","R","A"], foe: ["T","N","T","L","I","I"],
    board: ["..........D", ".G..C....JO", ".R..H...DOD", ".AQUA.....G", ".BI.POEM.MY", "..S.ENSURE.", "....L.C..HI", ".....ARK...", ".....ZOA...", "....FOWL...", "SEINE..EVEN"] },
  { num: 16, quizId: "babel-8-17-26", live: "2026-08-17", dateLabel: "August 17, 2026", sunday: false, benchmark: 36, greedy: 20,
    rack: ["T","F","U","U","P"], foe: ["T","Q","N","O","O"],
    board: [".......C...", "......CULTS", ".....MAR...", "DA..JOBS...", ".ME.I.SEWN.", "AIDING..R..", "EDH.XI.ZOO.", "R....V.ETH.", "INK..E.AE..", "AYE..R.L...", "L.G........"] },
  { num: 17, quizId: "babel-8-18-26", live: "2026-08-18", dateLabel: "August 18, 2026", sunday: false, benchmark: 67, greedy: 8,
    rack: ["I","G","T","N","R"], foe: ["Q","R","L","J","E"],
    board: [".........OW", ".........AR", ".LEZ.....KI", ".AMID.....S", ".HONE.A.COT", "....FEMUR..", "......B.EXO", ".D.PLAINS..", ".AVO.YE.TUI", ".D..GEN...C", ".S..U.T...H"] },
  { num: 18, quizId: "babel-8-19-26", live: "2026-08-19", dateLabel: "August 19, 2026", sunday: false, benchmark: 22, greedy: 10,
    rack: ["G","L","G","T","U"], foe: ["L","A","R","J","L"],
    board: ["..MAPS....R", "QUINOA..C.E", "..Z.ED..ODE", "....T...RIF", "....I.DUKES", "....COY..T.", ".....HEX...", "...THO.INN.", "..VIE..SEAM", "....RAN..WO", "..........B"] },
  { num: 19, quizId: "babel-8-20-26", live: "2026-08-20", dateLabel: "August 20, 2026", sunday: false, benchmark: 22, greedy: 14,
    rack: ["O","T","L","I","S"], foe: ["U","A","F","A","H"],
    board: [".G.....M...", "TA....QI...", "OE...JUNK..", "X.....IT...", "ID..REZ....", "CENTER.....", ".LOOP...DI.", "GLOW...BAND", "...N.YEAH..", "...SCUM....", ".....SERVER"] },
  { num: 20, quizId: "babel-8-21-26", live: "2026-08-21", dateLabel: "August 21, 2026", sunday: false, benchmark: 12, greedy: 7,
    rack: ["D","N","R","E","U"], foe: ["R","A","E","O","N"],
    board: ["SUB..VOLLEY", "..A.TIX..HO", "..C.HM..N..", "..KOW..JEST", "...PA.MARE.", "..CERT..DIG", "....TOFU.ZA", ".......GLEN", "........ID.", "......QIS..", "......I...."] },
  { num: 21, quizId: "babel-8-22-26", live: "2026-08-22", dateLabel: "August 22, 2026", sunday: false, benchmark: 21, greedy: 12,
    rack: ["U","K","N","N","E"], foe: ["I","L","M","F","D"],
    board: ["...........", "........V..", "..G....REW.", "..L....AIA.", ".PACT.DING.", "..MU.COD.EH", "...ZEROS..O", ".....AR...R", ".JETTY..Q.N", "LOSE..HOUSE", "...XI..BAIT"] },
  { num: 22, quizId: "babel-8-23-26", live: "2026-08-23", dateLabel: "August 23, 2026", sunday: true, benchmark: 98, greedy: 9,
    rack: ["U","X","O","E","O","Z"], foe: ["Q","B","I"],
    board: ["......OCEAN", ".TAVERN....", "..YE....S..", "...T.J..L.T", "...SHUT.UGH", "....ANA.MOI", "....W.IDS.R", ".FINK.LI..D", "GED..COMP..", ".REAL.RE...", "..........."] },
  { num: 23, quizId: "babel-8-24-26", live: "2026-08-24", dateLabel: "August 24, 2026", sunday: false, benchmark: 19, greedy: -9,
    rack: ["L","C","T","I","D"], foe: ["R","T","O","U","Z"],
    board: [".......L..C", "......HO..A", ".YAD.HIPS.K", "GAME.OR.WEE", ".RELIVE.EX.", ".....ED.A..", ".MINOR..T..", "..NUB...SUQ", "JIN.OFT....", "ANS........", "G.........."] },
  { num: 24, quizId: "babel-8-25-26", live: "2026-08-25", dateLabel: "August 25, 2026", sunday: false, benchmark: 26, greedy: 22,
    rack: ["R","I","T","C","I"], foe: ["N","E","C","B","J"],
    board: [".........T.", ".........U.", ".SUQ...MANE", "...IF.LAGER", "RHINO.Y.ODA", "....LUMP...", "....K..A...", "RANTS..V...", ".LOO..ZED..", ".STEW..DEG.", "HOE.....XI."] },
  { num: 25, quizId: "babel-8-26-26", live: "2026-08-26", dateLabel: "August 26, 2026", sunday: false, benchmark: 42, greedy: 24,
    rack: ["O","A","M","O","T"], foe: ["Y","U","L","L","L"],
    board: [".GRAVES.NOW", "......PAIR.", "...Z.MAID..", "..COHORT...", "...NU...E..", "..BEGS..XU.", ".QI.E...ET.", "..D...HIC..", "..D..KEF...", ".TENNIS....", "JAR........"] },
  { num: 26, quizId: "babel-8-27-26", live: "2026-08-27", dateLabel: "August 27, 2026", sunday: false, benchmark: 15, greedy: 3,
    rack: ["L","T","N","D","I"], foe: ["U","R","O","N","U"],
    board: ["C..........", "A......C...", "PALM...OF..", "S..UKE.AR..", ".JAM.DETOX.", "....QI.IN..", "..WRIT.NTH.", ".ZEE...G.O.", "..YES..SOV.", "....HI..BED", "......GLARE"] },
  { num: 27, quizId: "babel-8-28-26", live: "2026-08-28", dateLabel: "August 28, 2026", sunday: false, benchmark: 19, greedy: -1,
    rack: ["V","N","I","U","L"], foe: ["L","M","E","O","E"],
    board: ["........F.P", "........UTS", "........MAT", "..QIN.T..N.", ".GI.AWA..K.", ".....EXECS.", "....AYE.U..", "..BRR.D.ZOO", ".HA......GI", "JOL...HI.R.", "ODDS.CENTER"] },
  { num: 28, quizId: "babel-8-29-26", live: "2026-08-29", dateLabel: "August 29, 2026", sunday: false, benchmark: 49, greedy: 11,
    rack: ["R","I","D","T","B"], foe: ["N","L","V","I","N"],
    board: ["IF.......GO", "TA.J..G.REW", ".CHOP.R.AM.", ".T.ER.O.T..", ".SH.E.U.ID.", "....QIN.OE.", "....U.D.NY.", "...LEASES..", "..CALM.....", "..U..AKE...", "..Z...OX..."] },
  { num: 29, quizId: "babel-8-30-26", live: "2026-08-30", dateLabel: "August 30, 2026", sunday: true, benchmark: 19, greedy: -9,
    rack: ["N","T","E","J","R","D"], foe: ["L","V","G","A","R","X"],
    board: ["...........", "........RIZ", ".......TAO.", "....LEGIT..", ".....MODEM.", "..PACED....", ".QI.L.SHOUT", ".I.KOI.AY..", "..FAWN.HENS", "..E.N.....U", "COURSE....B"] },
  { num: 30, quizId: "babel-8-31-26", live: "2026-08-31", dateLabel: "August 31, 2026", sunday: false, benchmark: 17, greedy: 7,
    rack: ["L","G","D","E","N"], foe: ["L","U","P","F","O"],
    board: ["QUIET.....E", "IN..R.MATHS", "....AZO.R.T", "...BIO..U..", "..GET.C.CH.", ".....DANK..", "..WYE.R.SOV", "...ERODE...", ".MIX..S....", "JA.........", "ANIL......."] },
  { num: 31, quizId: "babel-9-1-26", live: "2026-09-01", dateLabel: "September 1, 2026", sunday: false, benchmark: 70, greedy: 57,
    rack: ["U","R","T","E","E"], foe: ["Q","R","Z","U","F"],
    board: ["WARMS......", "ED.O.......", "N.JA.V.....", "T.I.BONG...", ".CLAIM.....", "..L..I.....", "T....TEL...", "O.GNU.XI...", "KAI.HOPES..", "ERS..CODED.", "NY...H..A.."] },
  { num: 32, quizId: "babel-9-2-26", live: "2026-09-02", dateLabel: "September 2, 2026", sunday: false, benchmark: 33, greedy: 28,
    rack: ["V","C","N","A","D"], foe: ["O","S","L","L","S"],
    board: ["..........P", "........DZO", ".......HI.R", ".....DEER.T", "....AUE.KY.", "..HUNG...IF", ".BORA...ANA", "JIG....XI.C", "E.......MET", "SUQ..WE..MO", "T.INTEL..OR"] },
  { num: 33, quizId: "babel-9-3-26", live: "2026-09-03", dateLabel: "September 3, 2026", sunday: false, benchmark: 17, greedy: 5,
    rack: ["R","R","G","O","O"], foe: ["L","I","R","I","I"],
    board: [".........FA", ".MANA.AD.L.", "JIN.H.BYTE.", ".C.QI..E.X.", ".K.U.SUD...", "..ZEST.....", "...EM.S....", "...NE.LOU..", "....ADOPT..", "...CREW.EVO", ".NTH.G....."] },
  { num: 34, quizId: "babel-9-4-26", live: "2026-09-04", dateLabel: "September 4, 2026", sunday: false, benchmark: 23, greedy: 7,
    rack: ["C","N","G","I","U"], foe: ["T","A","L","T","S"],
    board: ["..P.....LAX", "..R...KNIT.", "..I.....Q..", "..MM....U..", ".WEASEL.IF.", "...J.TUNDRA", "..ZOO.V..E.", "..ORB..HEED", ".EASE.CONDO", ".....GHI..R", "..........Y"] },
  { num: 35, quizId: "babel-9-5-26", live: "2026-09-05", dateLabel: "September 5, 2026", sunday: false, benchmark: 40, greedy: 16,
    rack: ["T","T","W","M","E"], foe: ["I","U","I","Q","I"],
    board: [".......G.UM", "......HINGE", "..C..ZAP...", "OVAL.ES....", "..R.BAT....", ".RE.EL.....", ".OD.N.S....", ".D.ADULT...", "JEAN.HI....", "OOR...CONF.", "R....SKY.EX"] },
  { num: 36, quizId: "babel-9-6-26", live: "2026-09-06", dateLabel: "September 6, 2026", sunday: true, benchmark: 20, greedy: -3,
    rack: ["Q","U","R","E","A","P"], foe: ["L","L","N","R","E"],
    board: ["N...DOCTORS", "ET.......I.", "TAG....FEZ.", ".JUT..WAR..", "...HELIX...", "Y.VISAS.U..", "O..N.CHAD..", "MEME...NO..", ".GI....D...", "KOB........", "I.........."] },
  { num: 37, quizId: "babel-9-7-26", live: "2026-09-07", dateLabel: "September 7, 2026", sunday: false, benchmark: 20, greedy: 8,
    rack: ["U","T","N","M","O"], foe: ["N","V","B","E","L"],
    board: ["SILO..JA...", "..ERK.UH...", ".DA...R....", "WAND.TOC...", "EH.AFAR....", "...DEX.....", ".LOST..Z...", "QI...U.E...", "IGG..PIETY.", "..ORCS.....", "MINE......."] },
  { num: 38, quizId: "babel-9-8-26", live: "2026-09-08", dateLabel: "September 8, 2026", sunday: false, benchmark: 70, greedy: 63,
    rack: ["E","E","T","R","Z"], foe: ["L","R","R","U","I"],
    board: ["...QIS..L..", "...UTA.JONG", "..OI.M.AG..", "..NE..HM...", "..ETA.U....", "..S.CANDY..", "...PI.KO...", "..FID..W...", ".LOX.DANCE.", "BOH.VETS...", "ER........."] },
  { num: 39, quizId: "babel-9-9-26", live: "2026-09-09", dateLabel: "September 9, 2026", sunday: false, benchmark: 8, greedy: -17,
    rack: ["J","N","I","G","Z"], foe: ["T","R","N","D","O"],
    board: ["...BAM.....", "LUCID......", "..R.....L..", "..E.....EH.", ".DEVOUT.AI.", ".OPE.HALF..", ".C.N..WAYS.", ".TOE.....K.", "GONE....QIS", "UR.R....AMI", "ES......T.X"] },
  { num: 40, quizId: "babel-9-10-26", live: "2026-09-10", dateLabel: "September 10, 2026", sunday: false, benchmark: 35, greedy: 9,
    rack: ["O","T","N","A","I"], foe: ["V","U","F","R","L"],
    board: ["..........G", ".........QI", "..S.....PI.", "..T....DIN.", ".ZED..DUX..", "..E..JOKES.", "..REC.CELL.", ".MI.HUTS.AB", "OON..MO.HYE", "NAG...R.A.A", "ET......W.R"] },
  { num: 41, quizId: "babel-9-11-26", live: "2026-09-11", dateLabel: "September 11, 2026", sunday: false, benchmark: 42, greedy: 28,
    rack: ["U","L","G","I","E"], foe: ["V","Q","L","N","O"],
    board: [".........MI", ".......J.EN", "..C...LANDS", "..R....M..I", ".ZA.OWES..D", "T.FIXER..TE", "HAT.OBA..O.", "YU.......UP", ".NERD....GI", ".TE.ORC..H.", "ASK........"] },
  { num: 42, quizId: "babel-9-12-26", live: "2026-09-12", dateLabel: "September 12, 2026", sunday: false, benchmark: 48, greedy: 32,
    rack: ["N","E","T","S","Z"], foe: ["U","O","Q","N","E"],
    board: ["I.B..HINGED", "COACH.F.URE", "E.MEM...T..", "D..L..JOT..", "...L.TOWER.", "..KALI..R..", ".VAR.PAX...", "...S..DING.", ".......SAI.", "........YOU", "..........."] },
  { num: 43, quizId: "babel-9-13-26", live: "2026-09-13", dateLabel: "September 13, 2026", sunday: true, benchmark: 29, greedy: -1,
    rack: ["N","L","B","R","K","I"], foe: ["U","T","U","I","H","T"],
    board: ["....G.T....", ".ZA.A.A....", "..C.LAX....", "..HOODED...", "...UR.D....", "...RES.....", ".....L.....", "..MOVIES...", ".GYM.C..REF", "QI..JEAN.WE", "INTO.S.OPEN"] },
  { num: 44, quizId: "babel-9-14-26", live: "2026-09-14", dateLabel: "September 14, 2026", sunday: false, benchmark: 32, greedy: -5,
    rack: ["R","N","I","U","S"], foe: ["V","D","U","I","C"],
    board: ["...J.PACERS", "...AZO.....", "....ED..KO.", "...TE..BO..", "..QI.FLIRT.", "..AXLE.....", "..T.ARGUE.I", "...WYN.HAND", "GONE......O", ".HET......L", "MM........S"] },
  { num: 45, quizId: "babel-9-15-26", live: "2026-09-15", dateLabel: "September 15, 2026", sunday: false, benchmark: 27, greedy: 19,
    rack: ["U","N","P","F","A"], foe: ["R","R","L","U","C"],
    board: ["DE.C...X...", "AN.AD.BIT..", ".JOR.WISH..", "ZONED...I..", "OY.SEEM.N..", "A....GEEK..", "....VOLT...", "......TAS.E", "....QI..OLM", ".....THUG.I", "..........R"] },
  { num: 46, quizId: "babel-9-16-26", live: "2026-09-16", dateLabel: "September 16, 2026", sunday: false, benchmark: 11, greedy: -11,
    rack: ["V","G","O","I","N"], foe: ["L","E","N","I"],
    board: ["S........QI", "T.......GI.", "U.C....LOSE", "BEAN...AR..", "..T.J.AXES.", "..HOUND..U.", ".KO.T.ZO.R.", ".ADD...MA..", "PEER....R..", "L..EFT..C..", "Y..W....HIM"] },
  { num: 47, quizId: "babel-9-17-26", live: "2026-09-17", dateLabel: "September 17, 2026", sunday: false, benchmark: 23, greedy: 11,
    rack: ["G","L","U","O","S"], foe: ["R","O","I","T","U"],
    board: ["..........J", ".......Q.LO", ".......UTE.", "M......ION.", "IN..C.FEND.", "BA.PARITY..", ".V..WEX....", "ZAS..G.....", ".LINER.....", "..C.HEH.AD.", "OAKS.TERMED"] },
  { num: 48, quizId: "babel-9-18-26", live: "2026-09-18", dateLabel: "September 18, 2026", sunday: false, benchmark: 10, greedy: -6,
    rack: ["N","N","G","D","O"], foe: ["T","R","U","P","T"],
    board: ["...........", "...........", "........EM.", "......DI.OX", ".JOL.TA.CRU", "..HIGH..R..", "NYS..AQUA.N", "I..VOW..Z.E", "C.S.....EFT", "ELK.BASE.E.", "R.IDEA.LIMO"] },
  { num: 49, quizId: "babel-9-19-26", live: "2026-09-19", dateLabel: "September 19, 2026", sunday: false, benchmark: 42, greedy: 36,
    rack: ["U","G","L","T","V"], foe: ["R","R","O","S","Q"],
    board: ["ED..CURB.YO", "TENTH..ECO.", ".LI...HEAD.", "..DUMPING..", "....AAS.EWK", "..JARS...I.", ".NOX...FIZ.", "..LI...AN..", "..TOE......", "...ME......", "..........."] },
  { num: 50, quizId: "babel-9-20-26", live: "2026-09-20", dateLabel: "September 20, 2026", sunday: true, benchmark: 28, greedy: 13,
    rack: ["I","M","O","O","T","P"], foe: ["R","T","T","O","F","U"],
    board: ["G......Q.LA", "U......I.EH", "M.JACK.NOX.", "SEEN....L..", "..TENSE.I..", ".....C..V..", "D..HURDLES.", "O..ARIA....", "WING.B.....", "R...ZED....", "Y...A......"] },
  { num: 51, quizId: "babel-9-21-26", live: "2026-09-21", dateLabel: "September 21, 2026", sunday: false, benchmark: 21, greedy: 10,
    rack: ["L","R","O","E","O"], foe: ["W","E","U","O","G"],
    board: ["...JA....Q.", ".GLAM...SI.", "..I....DIN.", "..V...BEZ..", ".MENACE.EX.", ".ID..R.A...", ".N.FOODS...", "NU.I.C.T...", "UT.L.K.R...", "TE.T..HARP.", "S..H...Y..."] },
  { num: 52, quizId: "babel-9-22-26", live: "2026-09-22", dateLabel: "September 22, 2026", sunday: false, benchmark: 36, greedy: 13,
    rack: ["T","O","E","V","I"], foe: ["U","G","R","Z","F"],
    board: ["EL......TEC", "LAM....QAT.", ".MOLD..I...", "...ORGANIC.", "....I.N..HE", ".A.UNUSED..", ".P..K.W....", "JANE..EXO..", "OR.HYBRID..", "ST.........", "S.........."] },
  { num: 53, quizId: "babel-9-23-26", live: "2026-09-23", dateLabel: "September 23, 2026", sunday: false, benchmark: 9, greedy: -3,
    rack: ["N","L","W","I","N"], foe: ["S","T","L","U","E"],
    board: [".J.........", "KOB........", "ERR....AG..", "X.I....Q.P.", ".GENIE.U.H.", "..FAST.ADO.", "...IMAM.I..", ".R.V..ELECT", "CADETS..D.U", "OHO..OY...R", "Z.........N"] },
  { num: 54, quizId: "babel-9-24-26", live: "2026-09-24", dateLabel: "September 24, 2026", sunday: false, benchmark: 62, greedy: 42,
    rack: ["N","O","G","K","T"], foe: ["L","I","V","Z","C"],
    board: ["URGE.....DA", "..I....MAIL", ".OF...LORD.", ".B...SORE..", ".E..JOW..P.", ".SQUAD..MIC", "TE..RAX.ETH", "E.....INN..", "N.......U..", "T.....EASY.", "H.........."] },
  { num: 55, quizId: "babel-9-25-26", live: "2026-09-25", dateLabel: "September 25, 2026", sunday: false, benchmark: 21, greedy: 14,
    rack: ["I","I","L","E","N"], foe: ["M","D","O","T","V"],
    board: ["..QI......B", ".GID.....TA", ".L......GEN", "JO..DOCTORS", "OW.ZA....M.", "K.YARN...S.", "ECU.EARL...", ".R.....AUNT", ".UP.....HEH", ".XI......FE", "..S.......E"] },
  { num: 56, quizId: "babel-9-26-26", live: "2026-09-26", dateLabel: "September 26, 2026", sunday: false, benchmark: 24, greedy: 18,
    rack: ["G","T","L","N","O"], foe: ["U","P","X","Q","U"],
    board: ["..BE.......", ".JAR.......", ".OI........", "WITH...TI..", ".N..G.CH...", ".SKILL.EF..", "....A.ARENA", "ED.UNITED.R", "DOY.C....SO", ".MOVERS..EM", ".........ZA"] },
  { num: 57, quizId: "babel-9-27-26", live: "2026-09-27", dateLabel: "September 27, 2026", sunday: true, benchmark: 17, greedy: 12,
    rack: ["U","R","N","T","O","L"], foe: ["U","N","N","I","Z","I"],
    board: ["..........C", "....JO.P.EA", ".....DOUBTS", ".......C.HA", "....MARKS..", "...FOXY.MEE", "..QAT.E.ED.", "GRIN....L..", "A..GHI..L..", "V...I.WEST.", "E....ROD..."] },
  { num: 58, quizId: "babel-9-28-26", live: "2026-09-28", dateLabel: "September 28, 2026", sunday: false, benchmark: 37, greedy: 17,
    rack: ["T","N","E","A","R"], foe: ["Q","N","I","D","I"],
    board: [".......BRAD", "....COME.WO", ".GO..DEG.AH", "LUMP...IVY.", "...SATIN...", "R.FILES....", "EKE.EXO....", "Z....T.....", ".UNJUST....", "...OH......", "CARL......."] },
  { num: 59, quizId: "babel-9-29-26", live: "2026-09-29", dateLabel: "September 29, 2026", sunday: false, benchmark: 40, greedy: 35,
    rack: ["N","E","L","E","R"], foe: ["O","R","N","Q","L"],
    board: ["........UG.", "....C...GI.", "....U..CHE.", "SONATA.A...", ".BAL.MOZ...", "DIP.SIX....", "....H......", "..WIENER...", ".JEDI.FEM..", "TOY.K.STUD.", "OR......TAV"] },
  { num: 60, quizId: "babel-9-30-26", live: "2026-09-30", dateLabel: "September 30, 2026", sunday: false, benchmark: 28, greedy: 7,
    rack: ["A","R","I","M","I"], foe: ["V","G","R","U","D"],
    board: ["SAZ.......G", ".WILDLY..BO", "..N.U...JOE", "..CREASE.OR", "EX..T.TEAMS", ".UFO.QIN...", "..ACTIN....", ".PEH.NTH...", "KO.........", "EL.........", "D.........."] },
  { num: 61, quizId: "babel-10-1-26", live: "2026-10-01", dateLabel: "October 1, 2026", sunday: false, benchmark: 9, greedy: 1,
    rack: ["R","L","N","E","S"], foe: ["R","Z","I","T","U"],
    board: ["..JO.WROTE.", ".OUNCE.MAX.", "..NE.DYE...", "......UNS..", ".Q..KAM.AH.", ".AVOID..C..", "ST..FOG.R..", "A......PE..", "H......ID..", "I......L...", "B.....LEGIT"] },
  { num: 62, quizId: "babel-10-2-26", live: "2026-10-02", dateLabel: "October 2, 2026", sunday: false, benchmark: 49, greedy: 20,
    rack: ["N","I","D","V","E"], foe: ["C","Q","Y","U","X"],
    board: ["........NA.", ".......JOLT", "..R....EH.I", "..U....D..K", "..N.I.TI.W.", "..GATOR.BO.", "....S.O.EN.", "CREME.UGS..", "..MAL.POT..", "...IF.ES...", "ZEAL...HARD"] },
  { num: 63, quizId: "babel-10-3-26", live: "2026-10-03", dateLabel: "October 3, 2026", sunday: false, benchmark: 32, greedy: 5,
    rack: ["L","C","E","X","A"], foe: ["R","T","N","L","O"],
    board: ["U..GENT....", "N.WUD......", "DZO........", "E..B.......", "RACES......", "..HEMP.....", ".VITAL...Q.", "...S.OM..IF", "..A.KYE...E", "JOR.I.HOURS", "AIDING....T"] },
  { num: 64, quizId: "babel-10-4-26", live: "2026-10-04", dateLabel: "October 4, 2026", sunday: true, benchmark: 27, greedy: -7,
    rack: ["T","A","R","M","E","T"], foe: ["V","L","C","K","N","E"],
    board: ["P........MI", "L......STUD", "U.OXO..HAG.", "SQUID.FAB..", "HID.EYE....", ".....EARL..", ".I..CARE...", ".R.....J...", ".OZONE.O...", ".N...TWIGS.", ".......N..."] },
  { num: 65, quizId: "babel-10-5-26", live: "2026-10-05", dateLabel: "October 5, 2026", sunday: false, benchmark: 30, greedy: 16,
    rack: ["L","R","O","D","A"], foe: ["O","T","N","R","J"],
    board: ["..........I", "..VAC.....T", ".KI.....MIC", "Q.ST...MESH", "IF.WALNUT..", ".OZONE..HEX", ".PI.YEAR.NU", "..G....E...", ".......E...", ".....LODGE.", ".....ABSURD"] },
  { num: 66, quizId: "babel-10-6-26", live: "2026-10-06", dateLabel: "October 6, 2026", sunday: false, benchmark: 17, greedy: 2,
    rack: ["U","I","G","Q","L"], foe: ["R","Z","O","M"],
    board: ["........PEC", ".......WEX.", "JUICY..EH..", "...I...B...", "...TASKS...", ".....TO.FIE", "....HANGED.", "...TAN.L...", "..ARID.OD..", "..MOR.AVERT", "NOUNS..EL.."] },
  { num: 67, quizId: "babel-10-7-26", live: "2026-10-07", dateLabel: "October 7, 2026", sunday: false, benchmark: 51, greedy: 8,
    rack: ["L","T","R","R","E"], foe: ["N","N","Q","E","H"],
    board: ["T..V...D...", "R.JAW.DUI..", "UPON.MACS..", "C..ETA.TOG.", "E...OIK..UH", "..FEED...LA", ".GEMS....L.", "BIZ........", "I..........", "AIRY.N.....", "S..OXO....."] },
  { num: 68, quizId: "babel-10-8-26", live: "2026-10-08", dateLabel: "October 8, 2026", sunday: false, benchmark: 31, greedy: 5,
    rack: ["Q","T","U","L","A"], foe: ["P","U","U","R","N"],
    board: [".......MACS", "........DO.", ".......GOR.", ".......L.D.", "......HE..C", ".....JEEZ.O", "WIN.LAX.AYS", "R..HOB..SAT", "ID.IO.....I", "TENET..KERN", "EF....VIM.G"] },
  { num: 69, quizId: "babel-10-9-26", live: "2026-10-09", dateLabel: "October 9, 2026", sunday: false, benchmark: 34, greedy: -5,
    rack: ["V","E","E","T","D"], foe: ["J","I","P","U","U"],
    board: ["...MA.....M", ".FLEX....DA", "....L...WAY", "...RE...E.O", "...H......R", "..QI.T.SECS", "..INDIGO...", "...O.N.HINT", ".ZOS.K.....", "GOR.NEBULA.", ".ACT.R....."] },
  { num: 70, quizId: "babel-10-10-26", live: "2026-10-10", dateLabel: "October 10, 2026", sunday: false, benchmark: 24, greedy: 11,
    rack: ["G","T","R","I","N"], foe: ["P","G","T","T","O"],
    board: ["S......QIN.", "C......UTA.", "R.....HIS..", "E...R.ED...", "ABOVE.A.AZO", "MIX.FULLY..", "....U.S....", "KNOWN......", "A.MEDIC..J.", "L...E.HERO.", "E...D......"] },
  { num: 71, quizId: "babel-10-11-26", live: "2026-10-11", dateLabel: "October 11, 2026", sunday: true, benchmark: 19, greedy: 10,
    rack: ["L","E","V","I","I","R"], foe: ["L","O","L","N","U","G"],
    board: ["...CREDIT.H", "........AMA", ".......GEY.", ".....DAN...", "..C.NEXUS..", "..HOOF..T..", "QUEER..ZA..", "..M....ARB.", ".JO....SKIP", ".O.......DI", "NEWT.....ST"] },
  { num: 72, quizId: "babel-10-12-26", live: "2026-10-12", dateLabel: "October 12, 2026", sunday: false, benchmark: 21, greedy: 8,
    rack: ["T","E","N","C","U"], foe: ["G","R","L","U","H"],
    board: [".....BOH...", "......PINS.", "..CALMED.U.", "...D.....MY", "...R..SEZ.O", "REVISIT...W", "...FINALE..", ".QAT..GOX..", "TI...REDO..", "..JOKE.....", "..ANA......"] },
  { num: 73, quizId: "babel-10-13-26", live: "2026-10-13", dateLabel: "October 13, 2026", sunday: false, benchmark: 22, greedy: 13,
    rack: ["L","S","A","O","E"], foe: ["C","N","R","U","T"],
    board: [".........ME", ".B......DID", ".AG.....EM.", ".TO.....C.J", ".H....F.OXO", ".I...TINY.L", ".N.PLAZA..T", ".GHI...WE..", "..EUROS.V..", ".....DINERS", "...QUAKER.."] },
  { num: 74, quizId: "babel-10-14-26", live: "2026-10-14", dateLabel: "October 14, 2026", sunday: false, benchmark: 19, greedy: 13,
    rack: ["O","U","O","S","D"], foe: ["L","R","E","Y","M"],
    board: ["..........Z", "..........I", "TECH.V.AUNT", "...ALIGHT..", ".QAT.C.....", "PIE.BEE....", "IN..R.M.NU.", "....R.FROGS", ".......EX..", "....JADE.O.", "KINDA..LOWS"] },
  { num: 75, quizId: "babel-10-15-26", live: "2026-10-15", dateLabel: "October 15, 2026", sunday: false, benchmark: 32, greedy: 18,
    rack: ["D","L","N","A","O"], foe: ["L","C","I","U","D"],
    board: ["EXEC.....ST", "MI.OH....RE", "...MUN..QIS", "...ANY..U..", "....T..WAG.", "...FEZ.R.O.", ".P..RATION.", "JAILS..T.G.", ".V.....EH..", ".E.....ROK.", "ED......B.."] },
  { num: 76, quizId: "babel-10-16-26", live: "2026-10-16", dateLabel: "October 16, 2026", sunday: false, benchmark: 50, greedy: 44,
    rack: ["N","T","N","R","O"], foe: ["V","G","L","E","Q"],
    board: ["AN.....CRAB", "YA....ZO.HO", ".KEF.WET.SO", ".E.O.AE....", ".D.U.L.....", "...G.L.....", "..CHASER...", "..UT...UM..", "..P....DIN.", ".RIT....XIS", "JEDI.....MI"] },
  { num: 77, quizId: "babel-10-17-26", live: "2026-10-17", dateLabel: "October 17, 2026", sunday: false, benchmark: 51, greedy: 22,
    rack: ["L","T","O","O","F"], foe: ["D","P","I","K","J"],
    board: ["....CLAM...", "...CH.QIN..", "......U....", "....V.AG...", "....I..RIZ.", "..GREETED..", "....W..A...", "MINDS.UTA.B", ".OYE..REX.E", ".....UNREST", "SALOON....H"] },
  { num: 78, quizId: "babel-10-18-26", live: "2026-10-18", dateLabel: "October 18, 2026", sunday: true, benchmark: 26, greedy: 15,
    rack: ["I","A","I","I","O","R"], foe: ["T","M","M","Q","O"],
    board: ["...........", ".G.J...G...", ".L.UH..U...", "BE.DAW.L...", "AN..REEL...", "N.CODEX....", "DZO.Y.E..FA", "I.R...C..EH", "TSK...STIR.", ".A.......N.", "UPON...VEST"] },
  { num: 79, quizId: "babel-10-19-26", live: "2026-10-19", dateLabel: "October 19, 2026", sunday: false, benchmark: 29, greedy: 14,
    rack: ["T","I","I","T","O"], foe: ["R","U","S","R","N"],
    board: ["GENRE.....Z", ".X..MEH..FA", ".....LEVEL.", "..DIRK.O.U.", ".......L.I.", "...SUQ.T.DA", "..MONIES..C", ".JOY.NA...C", "BAG......DE", "AW.......OP", "H.........T"] },
  { num: 80, quizId: "babel-10-20-26", live: "2026-10-20", dateLabel: "October 20, 2026", sunday: false, benchmark: 37, greedy: 24,
    rack: ["U","U","D","E","L"], foe: ["Q","R","U","R","L"],
    board: ["...J.BADGES", "..POM.C.ID.", "..A.A.T.GHI", "Y..ATTIC..W", "EM..T.NO..I", "XI.FEH.V...", ".N..R.LEAK.", "ZONES..N...", "ORE........", "OS.........", "..........."] },
  { num: 81, quizId: "babel-10-21-26", live: "2026-10-21", dateLabel: "October 21, 2026", sunday: false, benchmark: 12, greedy: 2,
    rack: ["U","R","R","L","C"], foe: ["L","T","G","A","T"],
    board: ["......E..ME", ".RANSOM.TUX", "......SOH..", ".......DAK.", ".FE..TEENY.", "..WAGER....", ".JEDI.NOVA.", "PO.ZOL.BI..", "HIC....ID..", "IN.........", ".SUQ......."] },
  { num: 82, quizId: "babel-10-22-26", live: "2026-10-22", dateLabel: "October 22, 2026", sunday: false, benchmark: 19, greedy: 11,
    rack: ["O","M","T","T","R"], foe: ["R","N","L","I","T"],
    board: ["...JEE..CIT", ".....SQUAD.", ".....SI.R..", "...C..NEP..", "...ES..B.A.", "..FLAW.O.G.", ".KO.LOUNGE.", "U.AHI..YOD.", "RAMEN...V..", ".D.HEX.....", ".Z...I....."] },
  { num: 83, quizId: "babel-10-23-26", live: "2026-10-23", dateLabel: "October 23, 2026", sunday: false, benchmark: 35, greedy: -20,
    rack: ["E","P","H","A","V"], foe: ["T","R","N","M","E"],
    board: ["ROUX.TRYING", "..TIKI.....", ".JA..DWELL.", "......O....", ".....OUNCE.", ".....BLAH..", "...ICED.OF.", ".QAT....REZ", ".I......D.A", ".S....MUSES", ".....NOG..."] },
  { num: 84, quizId: "babel-10-24-26", live: "2026-10-24", dateLabel: "October 24, 2026", sunday: false, benchmark: 12, greedy: 7,
    rack: ["U","L","R","N","O"], foe: ["L","I","I","U","B"],
    board: [".....GOVERN", "....Q.D.C..", "..P.AHS.U..", "..R.TO.....", ".LIE.MY....", "CAZ.SEER...", "AWE.T.XI...", "T.DEE..F...", "SI.DAK.TAJ.", "...HM...NON", ".........GO"] },
  { num: 85, quizId: "babel-10-25-26", live: "2026-10-25", dateLabel: "October 25, 2026", sunday: true, benchmark: 14, greedy: -17,
    rack: ["N","A","M","A","X","R"], foe: ["U","J","L","E","I","U"],
    board: [".......PUTT", "......WERE.", ".....C.R...", "...Z.HAM...", "...OB.I....", ".ADORED....", ".C.SI.E....", ".T..NOS....", "QIN.KY.FALL", ".N...SIEGE.", ".GOV...DOTH"] },
  { num: 86, quizId: "babel-10-26-26", live: "2026-10-26", dateLabel: "October 26, 2026", sunday: false, benchmark: 24, greedy: 6,
    rack: ["U","U","D","F","R"], foe: ["I","T","I","G","L"],
    board: [".......JEST", ".QUART..XI.", ".IN..E..INK", ".....CHAT.Y", "......MM.OE", ".....C.B...", "...WHOLE...", ".ZOO.R.R...", "DADS.P.....", "AGE..S.EVO.", "N...LEAN..."] },
  { num: 87, quizId: "babel-10-27-26", live: "2026-10-27", dateLabel: "October 27, 2026", sunday: false, benchmark: 13, greedy: 9,
    rack: ["L","G","T","U","O"], foe: ["N","R","E","C","Y"],
    board: ["DO.XU..B.AW", "INCUR.ROLL.", "..A....A...", "..ZAG..T...", "...MOTHS...", "..HIVE.....", ".QI.E......", "..STRIPED..", "..SAND.MINK", "......JEE.E", "......O...F"] },
  { num: 88, quizId: "babel-10-28-26", live: "2026-10-28", dateLabel: "October 28, 2026", sunday: false, benchmark: 9, greedy: 5,
    rack: ["R","E","E","E","N"], foe: ["L","T","P","T","O"],
    board: [".......B...", ".ZINC..R.U.", "NOO.EQUALS.", "T..JAI.G.EF", "HM.IS....DI", ".OWNED.L..R", ".R..DIVA..S", ".G.....CH.T", "YU....OKA..", "AE....X....", "M.........."] },
  { num: 89, quizId: "babel-10-29-26", live: "2026-10-29", dateLabel: "October 29, 2026", sunday: false, benchmark: 16, greedy: -9,
    rack: ["T","V","B","N","I"], foe: ["I","P","Q","I","L"],
    board: ["..AHEM....D", ".CHORE....O", ".....MU..LO", "..JADE.G.UR", ".GALA..RIZ.", "..WAYS.E...", ".IS..TREND.", "......EN.UT", "......C..KO", ".....FOX.ET", "......N...S"] },
  { num: 90, quizId: "babel-10-30-26", live: "2026-10-30", dateLabel: "October 30, 2026", sunday: false, benchmark: 17, greedy: 1,
    rack: ["U","B","O","N","D"], foe: ["U","U","L","Y","L"],
    board: ["........G..", "......V.I..", ".....JARS..", "...Q.ORE.E.", "...IS.N.AXE", "....TRIAD..", ".F..R.SNOW.", ".O.TIGHT.HM", ".L..D...ZEE", ".I.PECK.ANA", "COME......T"] },
  { num: 91, quizId: "babel-10-31-26", live: "2026-10-31", dateLabel: "October 31, 2026", sunday: false, benchmark: 17, greedy: -15,
    rack: ["O","U","U","I","N"], foe: ["Q","I","T","A","K"],
    board: ["...........", "....JUN....", ".....MOWER.", "......XI..M", "....D..L.GO", "N..COZ.TRIO", "AG.HEAD..V.", ".ABA.PIC.E.", "SLED..FERNS", "EST....E..H", "L.......TRY"] },
  { num: 92, quizId: "babel-11-1-26", live: "2026-11-01", dateLabel: "November 1, 2026", sunday: true, benchmark: 22, greedy: 12,
    rack: ["C","V","U","E","S","T"], foe: ["L","L","T","W","I","R"],
    board: ["...........", "..Q..RUG...", ".BARKER....", ".ITA......N", "...JUN...PA", "....DEX.HEN", ".Z.MODI.ITA", "COLE..SNY..", ".OOH....AGO", "ES.......ID", "M........FE"] },
  { num: 93, quizId: "babel-11-2-26", live: "2026-11-02", dateLabel: "November 2, 2026", sunday: false, benchmark: 25, greedy: 19,
    rack: ["N","U","B","D","T"], foe: ["C","J","T","E","T"],
    board: ["..VIM.HEP..", "...FEDEX...", "..ES.U.....", "I...QI..C..", "L...U.ANA..", "L...ARSON..", "E.GAY.HOT..", "GROW...NO..", "A.ROM...R..", "L..KI......", "SIZED......"] },
  { num: 94, quizId: "babel-11-3-26", live: "2026-11-03", dateLabel: "November 3, 2026", sunday: false, benchmark: 20, greedy: 7,
    rack: ["U","I","G","L","E"], foe: ["N","Q","R","N","O"],
    board: ["P..J.......", "OD.OS......", "OR.KI..L...", "HI.ET.MA...", ".F..C.AXE..", ".THROWN....", "..Y.M.E..V.", "..B......A.", "..R..ASSIGN", ".DILUTE....", "ZED...ACUTE"] },
  { num: 95, quizId: "babel-11-4-26", live: "2026-11-04", dateLabel: "November 4, 2026", sunday: false, benchmark: 25, greedy: 5,
    rack: ["I","E","I","E","R"], foe: ["N","N","T","N","A"],
    board: ["GODS....R..", "..ZAS..HAJ.", ".SOL..BETA.", ".T...FAX...", ".R..QIN.KO.", ".I...EDGY.L", ".PER..E.UMU", "C.COULD...V", "I.HM.......", "TWO........", "E.........."] },
  { num: 96, quizId: "babel-11-5-26", live: "2026-11-05", dateLabel: "November 5, 2026", sunday: false, benchmark: 25, greedy: -7,
    rack: ["T","O","S","N","A"], foe: ["R","R","V","S","E"],
    board: ["..C.....L.G", ".CHEF...OHO", "..A.EX.NUMB", "...PRIZED.L", "....A.E..DI", "..MILES.GIN", ".QAT..T.OD.", "..K....YU..", "..E....AT..", ".......W...", ".....JUNIOR"] },
  { num: 97, quizId: "babel-11-6-26", live: "2026-11-06", dateLabel: "November 6, 2026", sunday: false, benchmark: 32, greedy: 18,
    rack: ["L","D","E","S","I"], foe: ["I","C","Q","L","X"],
    board: [".......ROUT", "......TANGO", ".....JADE..", "..C..E.....", ".PA.DRUMS..", ".OB..K.EH..", ".WAVES.NY..", "GER....T...", "URE....I...", "L.T...HO.ZA", "F....MINION"] },
  { num: 98, quizId: "babel-11-7-26", live: "2026-11-07", dateLabel: "November 7, 2026", sunday: false, benchmark: 17, greedy: 1,
    rack: ["O","L","V","A","O"], foe: ["T","N","C","A","K"],
    board: ["...E...L.E.", ".G.NY.HITS.", ".R.DO.ANI..", "JAW.G.REX..", ".I..U.M....", "INFORMS....", ".S.UTE.....", "...D.R....B", "....ZEE.Q.L", "....I.CHUTE", "....P.O.A.D"] },
  { num: 99, quizId: "babel-11-8-26", live: "2026-11-08", dateLabel: "November 8, 2026", sunday: true, benchmark: 26, greedy: 18,
    rack: ["I","F","Q","E","N","L"], foe: ["R","V","R","B","E","N"],
    board: ["HI.ZEA...YU", "MOJO....COR", "..U.EXTRA..", "DING...INTO", "AD..WEPT...", "LEASES.....", "..LOT......", "SMUG.......", "KA.........", "ICH........", "D.........."] },
  { num: 100, quizId: "babel-11-9-26", live: "2026-11-09", dateLabel: "November 9, 2026", sunday: false, benchmark: 30, greedy: 12,
    rack: ["N","T","A","G","E"], foe: ["L","R","C","J","E"],
    board: [".......HIND", "....CORONA.", "...QI......", "....PLUS...", "....HOTTER.", "MOVIES...ID", ".X..R....FA", "LI........M", "ADZ...BOUTS", "WEEK..YUG..", "N.EA......."] },
  { num: 101, quizId: "babel-11-10-26", live: "2026-11-10", dateLabel: "November 10, 2026", sunday: false, benchmark: 15, greedy: 11,
    rack: ["N","O","O","R","E"], foe: ["L","U","R","N","M"],
    board: ["ARID..O....", "..FACTS....", "QIS..W.....", ".V.JEE.....", "BY..REZ....", "U.D.ATE....", "L.I.S.EH...", "KANG...UH..", ".XI....MOP.", "DEN.....LO.", "..G...ATTIC"] },
  { num: 102, quizId: "babel-11-11-26", live: "2026-11-11", dateLabel: "November 11, 2026", sunday: false, benchmark: 19, greedy: 9,
    rack: ["U","T","T","E","O"], foe: ["G","N","T","T","I"],
    board: ["...HOC.....", "..LID......", ".M.RAJ.....", ".OYE.......", ".ZA.GOV....", "..DARN.....", "QI..O.....K", ".FLAWED.IRE", "..A.EXECS.B", "..M.R.EH...", "LUPUS..INNS"] },
  { num: 103, quizId: "babel-11-12-26", live: "2026-11-12", dateLabel: "November 12, 2026", sunday: false, benchmark: 20, greedy: 14,
    rack: ["G","O","L","I","U"], foe: ["N","N","V","U","N"],
    board: ["...PED..HUI", ".FEET.DRAGS", "DEX.AWAITS.", "Z......N..Q", "OCH.JERKY.A", "..MOOR..ACT", ".EMIR....O.", ".E.....BILL", ".........T.", ".........S.", "..........."] },
  { num: 104, quizId: "babel-11-13-26", live: "2026-11-13", dateLabel: "November 13, 2026", sunday: false, benchmark: 38, greedy: -4,
    rack: ["R","L","U","I","C"], foe: ["W","Q","E","O","V"],
    board: ["T......BLUR", "OPIUM..YAM.", "X......T...", "ID.....E...", "NE.FLOSS.J.", ".CHAOS...A.", ".K..N...ZIT", "...AGENDA.E", "..TIED..GEN", "....R....HO", "..........R"] },
  { num: 105, quizId: "babel-11-14-26", live: "2026-11-14", dateLabel: "November 14, 2026", sunday: false, benchmark: 16, greedy: 9,
    rack: ["U","I","I","I","S"], foe: ["Q","A","O","R","D"],
    board: [".V.P......L", ".UTA.....DE", ".GEN....LEE", "..NEF.DRIES", "..T.O.I.C..", "..HARMS.KAT", "....C.H..ZA", "...BE....OR", "...L.MUN..T", ".W.OXY.....", "JONG......."] },
  { num: 106, quizId: "babel-11-15-26", live: "2026-11-15", dateLabel: "November 15, 2026", sunday: true, benchmark: 40, greedy: 5,
    rack: ["R","E","R","A","O","T"], foe: ["C","I","L","J","Q","I"],
    board: [".......V...", "....G.ZO...", "....O..IF..", "...AW..DA..", "....N.C.S..", "....SOUGHT.", "......R.I..", "ALUM.ALMOND", "..TEENY.N..", ".BEER...SUD", "XI.KEPT..HE"] },
  { num: 107, quizId: "babel-11-16-26", live: "2026-11-16", dateLabel: "November 16, 2026", sunday: false, benchmark: 28, greedy: 5,
    rack: ["N","A","N","W","B"], foe: ["T","T","R","V","O"],
    board: ["J......MILD", "OH.......OU", ".EPIC..ZOOS", "QI...GEAR.T", "UR..DANG...", "I.FEED.....", "THEME......", "SAYS.AN....", ".C...XU....", ".KILLER....", "..........."] },
  { num: 108, quizId: "babel-11-17-26", live: "2026-11-17", dateLabel: "November 17, 2026", sunday: false, benchmark: 83, greedy: 61,
    rack: ["L","S","O","N","J"], foe: ["Q","T","R","U"],
    board: [".........LA", "......REPAY", "....G..AID.", "...KRAFT...", "....I.L..C.", "..GENIUS.O.", "WOUND.XI.R.", ".MED...CHE.", "MI.SOZ..A..", "ET..HO..V..", "E......BENT"] },
  { num: 109, quizId: "babel-11-18-26", live: "2026-11-18", dateLabel: "November 18, 2026", sunday: false, benchmark: 8, greedy: -11,
    rack: ["J","E","L","O","A"], foe: ["M","P","A","T","U"],
    board: ["DUH.QI..C..", ".TOXINS.R..", "..V.S.T.U..", "..EA.BEDS..", "...LA.W.H..", "FRYING.....", "I..KOI.....", "E.GENT.....", "R.L........", "CRAZED.....", "E.MONO....."] },
  { num: 110, quizId: "babel-11-19-26", live: "2026-11-19", dateLabel: "November 19, 2026", sunday: false, benchmark: 50, greedy: 11,
    rack: ["R","I","T","C","S"], foe: ["T","Q","R","U","N"],
    board: ["....M....KO", "....I...FIX", "....L..ZA..", "...WE.DOT..", ".DOR..ALA..", "..HAVEN.L..", "...I..C....", "..ST..EMO..", ".DOH.GREEN.", "NAG.BIS..YU", "UP.JEE....."] },
];
