// Puzzle data for Babel, the daily Scrabble-style endgame. Imported ONLY by
// the server page (app/babel/page.js), which filters live<=today AND strips
// `foe` before handing anything to the browser.
//
// The opponent's rack is never sent, and there is no tracker: the page prints
// the bag, the board is in front of you, and the subtraction is yours to do.
// The client derives `foe` the same way the player is meant to, purely to
// drive the engine.
//
// Each day is the tail of a real self-played game (scripts/gen-babel.mjs): the
// bag is empty and the player holds five tiles, six in the Sunday Edition. The
// Q lands wherever the game put it, which is on the board about three times in
// four and otherwise on one of the two racks.
//
// `benchmark` is the spread our solver ACHIEVES from the player's seat against
// the very defence the browser plays (solveLine in lib/babel-engine.js), so it
// is reachable by construction rather than a ceiling nobody can hit. It is a
// solver mark to beat, NOT an average round, which is why it is not called par.
// `greedy` is
// what grabbing the biggest number every turn gets you.
//
// Validate with scripts/verify-babel.mjs after ANY edit to this file or the
// engine. It replays every line and fails if a benchmark stops being reachable.
export const PUZZLES = [
  { num: 1, quizId: "babel-8-2-26", live: "2026-08-02", dateLabel: "August 2, 2026", sunday: true, benchmark: 43, greedy: 33,
    rack: ["D","L","K","A","O","O"], foe: ["O","U","I","L","R","R"],
    board: ["....NE.....", "....ET.....", "..J.SHALT..", ".QUIT.RE...", "DIM.I.FAUX.", "..PING.R...", "OBS.G..N...", "YE.....EM..", ".Z.....DA..", "..CAVE..C..", "...W.HONEST"] },
  { num: 2, quizId: "babel-8-3-26", live: "2026-08-03", dateLabel: "August 3, 2026", sunday: false, benchmark: 34, greedy: 7,
    rack: ["T","L","R","S","E"], foe: ["L","L","N","U","I"],
    board: ["...........", "...........", "..CAW.....F", "...MOA.C.AR", ".....VOR.ZA", "....QI.UPO.", "...HIDES...", ".NEON.THEY.", "DEEM.K..DOG", "AG.EXITS..J", "B..RIN.T..U"] },
  { num: 3, quizId: "babel-8-4-26", live: "2026-08-04", dateLabel: "August 4, 2026", sunday: false, benchmark: 54, greedy: 40,
    rack: ["L","W","U","D","I"], foe: ["R","R","Q","I","U"],
    board: ["V.R........", "OHO.C......", "LIT.U......", ".MANS..L...", "..TOP.JAK..", "..ET.GI.I..", "...CORNY.N.", ".FEH.A.AXES", ".EME.BE..ET", ".Z.D.SO..DA", "......N...G"] },
  { num: 4, quizId: "babel-8-5-26", live: "2026-08-05", dateLabel: "August 5, 2026", sunday: false, benchmark: 13, greedy: 1,
    rack: ["U","O","T","C","F"], foe: ["N","N","Q","R","A"],
    board: ["...G....C.V", "..NOX...U.I", "...R....T.N", "...G....I.E", "..ME.MODELS", "PHO.JEW..U.", "..BEATER.ZO", "...LI..YA.D", "....LATER.D", "....SAI...S", "......KHI.."] },
  { num: 5, quizId: "babel-8-6-26", live: "2026-08-06", dateLabel: "August 6, 2026", sunday: false, benchmark: 24, greedy: 11,
    rack: ["N","D","U","O","L"], foe: ["R","U","L","G","C"],
    board: ["QIS....HOOF", "U.T..CLAMP.", "I.AMA.ATE..", "Z.BOX.REN..", "...TE.G....", "..WISHED...", ".E.V..R....", ".N.E.......", ".JEST......", "IO..IRK....", "NY....AD..."] },
  { num: 6, quizId: "babel-8-7-26", live: "2026-08-07", dateLabel: "August 7, 2026", sunday: false, benchmark: 45, greedy: 36,
    rack: ["T","T","U","U","H"], foe: ["N","R","O","N","Q"],
    board: [".......BRIM", "REZ...SO...", "..AG.FAWN..", "..XU.ELL.E.", "...META..DI", "....RAD.C.O", "...PEL.JOYS", "...H...ATE.", "..DIVING.SI", ".KO.......C", "..........E"] },
  { num: 7, quizId: "babel-8-8-26", live: "2026-08-08", dateLabel: "August 8, 2026", sunday: false, benchmark: 27, greedy: -2,
    rack: ["R","R","T","A","Y"], foe: ["N","G","V","L","O"],
    board: ["P....K.MACE", "OB..CAW.X..", "LO.ZA.IDE..", "IT.AN.NUS..", "OHO.I.DE...", "..FINEST...", "HET.EM.....", "EL.J.U.....", "R.SI.......", "DRUG.......", "..Q........"] },
  { num: 8, quizId: "babel-8-9-26", live: "2026-08-09", dateLabel: "August 9, 2026", sunday: true, benchmark: 34, greedy: 23,
    rack: ["O","R","L","S","X","L"], foe: ["U","U","R","N","T","W"],
    board: ["..........Y", ".........GI", ".......QUID", "....Z.AIN..", "...BEST....", "..FISH...K.", ".JA.TELECOM", "CONE.DAE..O", ".N......TAV", "AG...EMPIRE", "H......OD.R"] },
  { num: 9, quizId: "babel-8-10-26", live: "2026-08-10", dateLabel: "August 10, 2026", sunday: false, benchmark: 26, greedy: 12,
    rack: ["O","O","L","E","P"], foe: ["R","N","U","U","M"],
    board: [".......S.RE", "..DEX.BA.AL", ".QIN.FOLKS.", "..VET.OE.HI", "TWA.HIM...N", "...JETS...T", "..COY....ER", "DRUG.....NA", "AID....CIG.", ".Z.........", "..........."] },
  { num: 10, quizId: "babel-8-11-26", live: "2026-08-11", dateLabel: "August 11, 2026", sunday: false, benchmark: 18, greedy: -17,
    rack: ["U","I","R","U","N"], foe: ["O","T","B","T","Q"],
    board: ["EUK....CALM", "THIEF...C..", "...X....R..", "..RAV..WE..", "...MARSH.L.", "..PINE.AGO.", "JOINED.LIG.", "OD.E...ES..", "...DZO.ST..", "....ANY....", "..........."] },
  { num: 11, quizId: "babel-8-12-26", live: "2026-08-12", dateLabel: "August 12, 2026", sunday: false, benchmark: 29, greedy: 21,
    rack: ["X","C","U","I","E"], foe: ["U","N","N","T","R"],
    board: ["..........C", ".........PA", "..JO.....ER", "...REV.ONTO", "....LOUSY.L", ".....W.....", "...LIST..K.", "..QI...OBE.", ".DIGS.HERTZ", "FAN.HEM.I.A", "AE.DAD..M.G"] },
  { num: 12, quizId: "babel-8-13-26", live: "2026-08-13", dateLabel: "August 13, 2026", sunday: false, benchmark: 12, greedy: -3,
    rack: ["N","O","A","K","I"], foe: ["L","N","U","T","A"],
    board: ["......SIEGE", "......C.DUN", "......R....", "......UT...", "....MIME...", "..JAYS.XI..", ".ZOL..ATT..", "GOR..QIS...", "AN....D.FOH", "RE..CLEVER.", "B..PHO..DEW"] },
  { num: 13, quizId: "babel-8-14-26", live: "2026-08-14", dateLabel: "August 14, 2026", sunday: false, benchmark: 28, greedy: 22,
    rack: ["D","T","E","W","I"], foe: ["U","L","D","N","T"],
    board: ["JAR........", "..ALF......", "..V..ZEROS.", "..ES...E.UG", "...PYA.C.QI", "..BEAM.KI..", "...EDITORS.", "...C...NON.", ".HEH....NUR", "LOX......GI", ".TOM......A"] },
  { num: 14, quizId: "babel-8-15-26", live: "2026-08-15", dateLabel: "August 15, 2026", sunday: false, benchmark: 34, greedy: 21,
    rack: ["E","N","I","D","U"], foe: ["I","O","R","P","B"],
    board: ["G..Q....TUN", "R.TI...MEGA", "O.U...KEX..", "WARD..NE...", "L.FEZ.O....", "....ATTIC..", "..HOS.S.Y..", ".JAR....C..", ".AHS....L..", "MI....EVEN.", "OLD........"] },
  { num: 15, quizId: "babel-8-16-26", live: "2026-08-16", dateLabel: "August 16, 2026", sunday: true, benchmark: 33, greedy: 19,
    rack: ["T","T","U","X","R","A"], foe: ["T","N","T","L","I","I"],
    board: ["..........D", ".G..C....JO", ".R..H...DOD", ".AQUA.....G", ".BI.POEM.MY", "..S.ENSURE.", "....L.C..HI", ".....ARK...", ".....ZOA...", "....FOWL...", "SEINE..EVEN"] },
  { num: 16, quizId: "babel-8-17-26", live: "2026-08-17", dateLabel: "August 17, 2026", sunday: false, benchmark: 36, greedy: 20,
    rack: ["T","F","U","U","P"], foe: ["T","Q","N","O","O"],
    board: [".......C...", "......CULTS", ".....MAR...", "DA..JOBS...", ".ME.I.SEWN.", "AIDING..R..", "EDH.XI.ZOO.", "R....V.ETH.", "INK..E.AE..", "AYE..R.L...", "L.G........"] },
  { num: 17, quizId: "babel-8-18-26", live: "2026-08-18", dateLabel: "August 18, 2026", sunday: false, benchmark: 67, greedy: 8,
    rack: ["I","G","T","N","R"], foe: ["Q","R","L","J","E"],
    board: [".........OW", ".........AR", ".LEZ.....KI", ".AMID.....S", ".HONE.A.COT", "....FEMUR..", "......B.EXO", ".D.PLAINS..", ".AVO.YE.TUI", ".D..GEN...C", ".S..U.T...H"] },
  { num: 18, quizId: "babel-8-19-26", live: "2026-08-19", dateLabel: "August 19, 2026", sunday: false, benchmark: 22, greedy: 10,
    rack: ["G","L","G","T","U"], foe: ["L","A","R","J","L"],
    board: ["..MAPS....R", "QUINOA..C.E", "..Z.ED..ODE", "....T...RIF", "....I.DUKES", "....COY..T.", ".....HEX...", "...THO.INN.", "..VIE..SEAM", "....RAN..WO", "..........B"] },
  { num: 19, quizId: "babel-8-20-26", live: "2026-08-20", dateLabel: "August 20, 2026", sunday: false, benchmark: 22, greedy: 14,
    rack: ["O","T","L","I","S"], foe: ["U","A","F","A","H"],
    board: [".G.....M...", "TA....QI...", "OE...JUNK..", "X.....IT...", "ID..REZ....", "CENTER.....", ".LOOP...DI.", "GLOW...BAND", "...N.YEAH..", "...SCUM....", ".....SERVER"] },
  { num: 20, quizId: "babel-8-21-26", live: "2026-08-21", dateLabel: "August 21, 2026", sunday: false, benchmark: 12, greedy: 7,
    rack: ["D","N","R","E","U"], foe: ["R","A","E","O","N"],
    board: ["SUB..VOLLEY", "..A.TIX..HO", "..C.HM..N..", "..KOW..JEST", "...PA.MARE.", "..CERT..DIG", "....TOFU.ZA", ".......GLEN", "........ID.", "......QIS..", "......I...."] },
  { num: 21, quizId: "babel-8-22-26", live: "2026-08-22", dateLabel: "August 22, 2026", sunday: false, benchmark: 21, greedy: 12,
    rack: ["U","K","N","N","E"], foe: ["I","L","M","F","D"],
    board: ["...........", "........V..", "..G....REW.", "..L....AIA.", ".PACT.DING.", "..MU.COD.EH", "...ZEROS..O", ".....AR...R", ".JETTY..Q.N", "LOSE..HOUSE", "...XI..BAIT"] },
  { num: 22, quizId: "babel-8-23-26", live: "2026-08-23", dateLabel: "August 23, 2026", sunday: true, benchmark: 98, greedy: 9,
    rack: ["U","X","O","E","O","Z"], foe: ["Q","B","I"],
    board: ["......OCEAN", ".TAVERN....", "..YE....S..", "...T.J..L.T", "...SHUT.UGH", "....ANA.MOI", "....W.IDS.R", ".FINK.LI..D", "GED..COMP..", ".REAL.RE...", "..........."] },
  { num: 23, quizId: "babel-8-24-26", live: "2026-08-24", dateLabel: "August 24, 2026", sunday: false, benchmark: 19, greedy: -9,
    rack: ["L","C","T","I","D"], foe: ["R","T","O","U","Z"],
    board: [".......L..C", "......HO..A", ".YAD.HIPS.K", "GAME.OR.WEE", ".RELIVE.EX.", ".....ED.A..", ".MINOR..T..", "..NUB...SUQ", "JIN.OFT....", "ANS........", "G.........."] },
  { num: 24, quizId: "babel-8-25-26", live: "2026-08-25", dateLabel: "August 25, 2026", sunday: false, benchmark: 26, greedy: 22,
    rack: ["R","I","T","C","I"], foe: ["N","E","C","B","J"],
    board: [".........T.", ".........U.", ".SUQ...MANE", "...IF.LAGER", "RHINO.Y.ODA", "....LUMP...", "....K..A...", "RANTS..V...", ".LOO..ZED..", ".STEW..DEG.", "HOE.....XI."] },
  { num: 25, quizId: "babel-8-26-26", live: "2026-08-26", dateLabel: "August 26, 2026", sunday: false, benchmark: 42, greedy: 24,
    rack: ["O","A","M","O","T"], foe: ["Y","U","L","L","L"],
    board: [".GRAVES.NOW", "......PAIR.", "...Z.MAID..", "..COHORT...", "...NU...E..", "..BEGS..XU.", ".QI.E...ET.", "..D...HIC..", "..D..KEF...", ".TENNIS....", "JAR........"] },
  { num: 26, quizId: "babel-8-27-26", live: "2026-08-27", dateLabel: "August 27, 2026", sunday: false, benchmark: 15, greedy: 3,
    rack: ["L","T","N","D","I"], foe: ["U","R","O","N","U"],
    board: ["C..........", "A......C...", "PALM...OF..", "S..UKE.AR..", ".JAM.DETOX.", "....QI.IN..", "..WRIT.NTH.", ".ZEE...G.O.", "..YES..SOV.", "....HI..BED", "......GLARE"] },
  { num: 27, quizId: "babel-8-28-26", live: "2026-08-28", dateLabel: "August 28, 2026", sunday: false, benchmark: 19, greedy: -1,
    rack: ["V","N","I","U","L"], foe: ["L","M","E","O","E"],
    board: ["........F.P", "........UTS", "........MAT", "..QIN.T..N.", ".GI.AWA..K.", ".....EXECS.", "....AYE.U..", "..BRR.D.ZOO", ".HA......GI", "JOL...HI.R.", "ODDS.CENTER"] },
  { num: 28, quizId: "babel-8-29-26", live: "2026-08-29", dateLabel: "August 29, 2026", sunday: false, benchmark: 49, greedy: 11,
    rack: ["R","I","D","T","B"], foe: ["N","L","V","I","N"],
    board: ["IF.......GO", "TA.J..G.REW", ".CHOP.R.AM.", ".T.ER.O.T..", ".SH.E.U.ID.", "....QIN.OE.", "....U.D.NY.", "...LEASES..", "..CALM.....", "..U..AKE...", "..Z...OX..."] },
  { num: 29, quizId: "babel-8-30-26", live: "2026-08-30", dateLabel: "August 30, 2026", sunday: true, benchmark: 19, greedy: -9,
    rack: ["N","T","E","J","R","D"], foe: ["L","V","G","A","R","X"],
    board: ["...........", "........RIZ", ".......TAO.", "....LEGIT..", ".....MODEM.", "..PACED....", ".QI.L.SHOUT", ".I.KOI.AY..", "..FAWN.HENS", "..E.N.....U", "COURSE....B"] },
  { num: 30, quizId: "babel-8-31-26", live: "2026-08-31", dateLabel: "August 31, 2026", sunday: false, benchmark: 17, greedy: 7,
    rack: ["L","G","D","E","N"], foe: ["L","U","P","F","O"],
    board: ["QUIET.....E", "IN..R.MATHS", "....AZO.R.T", "...BIO..U..", "..GET.C.CH.", ".....DANK..", "..WYE.R.SOV", "...ERODE...", ".MIX..S....", "JA.........", "ANIL......."] },
  { num: 31, quizId: "babel-9-1-26", live: "2026-09-01", dateLabel: "September 1, 2026", sunday: false, benchmark: 70, greedy: 57,
    rack: ["U","R","T","E","E"], foe: ["Q","R","Z","U","F"],
    board: ["WARMS......", "ED.O.......", "N.JA.V.....", "T.I.BONG...", ".CLAIM.....", "..L..I.....", "T....TEL...", "O.GNU.XI...", "KAI.HOPES..", "ERS..CODED.", "NY...H..A.."] },
  { num: 32, quizId: "babel-9-2-26", live: "2026-09-02", dateLabel: "September 2, 2026", sunday: false, benchmark: 33, greedy: 28,
    rack: ["V","C","N","A","D"], foe: ["O","S","L","L","S"],
    board: ["..........P", "........DZO", ".......HI.R", ".....DEER.T", "....AUE.KY.", "..HUNG...IF", ".BORA...ANA", "JIG....XI.C", "E.......MET", "SUQ..WE..MO", "T.INTEL..OR"] },
  { num: 33, quizId: "babel-9-3-26", live: "2026-09-03", dateLabel: "September 3, 2026", sunday: false, benchmark: 17, greedy: 5,
    rack: ["R","R","G","O","O"], foe: ["L","I","R","I","I"],
    board: [".........FA", ".MANA.AD.L.", "JIN.H.BYTE.", ".C.QI..E.X.", ".K.U.SUD...", "..ZEST.....", "...EM.S....", "...NE.LOU..", "....ADOPT..", "...CREW.EVO", ".NTH.G....."] },
  { num: 34, quizId: "babel-9-4-26", live: "2026-09-04", dateLabel: "September 4, 2026", sunday: false, benchmark: 23, greedy: 7,
    rack: ["C","N","G","I","U"], foe: ["T","A","L","T","S"],
    board: ["..P.....LAX", "..R...KNIT.", "..I.....Q..", "..MM....U..", ".WEASEL.IF.", "...J.TUNDRA", "..ZOO.V..E.", "..ORB..HEED", ".EASE.CONDO", ".....GHI..R", "..........Y"] },
  { num: 35, quizId: "babel-9-5-26", live: "2026-09-05", dateLabel: "September 5, 2026", sunday: false, benchmark: 40, greedy: 16,
    rack: ["T","T","W","M","E"], foe: ["I","U","I","Q","I"],
    board: [".......G.UM", "......HINGE", "..C..ZAP...", "OVAL.ES....", "..R.BAT....", ".RE.EL.....", ".OD.N.S....", ".D.ADULT...", "JEAN.HI....", "OOR...CONF.", "R....SKY.EX"] },
  { num: 36, quizId: "babel-9-6-26", live: "2026-09-06", dateLabel: "September 6, 2026", sunday: true, benchmark: 20, greedy: -3,
    rack: ["Q","U","R","E","A","P"], foe: ["L","L","N","R","E"],
    board: ["N...DOCTORS", "ET.......I.", "TAG....FEZ.", ".JUT..WAR..", "...HELIX...", "Y.VISAS.U..", "O..N.CHAD..", "MEME...NO..", ".GI....D...", "KOB........", "I.........."] },
  { num: 37, quizId: "babel-9-7-26", live: "2026-09-07", dateLabel: "September 7, 2026", sunday: false, benchmark: 20, greedy: 8,
    rack: ["U","T","N","M","O"], foe: ["N","V","B","E","L"],
    board: ["SILO..JA...", "..ERK.UH...", ".DA...R....", "WAND.TOC...", "EH.AFAR....", "...DEX.....", ".LOST..Z...", "QI...U.E...", "IGG..PIETY.", "..ORCS.....", "MINE......."] },
  { num: 38, quizId: "babel-9-8-26", live: "2026-09-08", dateLabel: "September 8, 2026", sunday: false, benchmark: 70, greedy: 63,
    rack: ["E","E","T","R","Z"], foe: ["L","R","R","U","I"],
    board: ["...QIS..L..", "...UTA.JONG", "..OI.M.AG..", "..NE..HM...", "..ETA.U....", "..S.CANDY..", "...PI.KO...", "..FID..W...", ".LOX.DANCE.", "BOH.VETS...", "ER........."] },
];
