// Puzzle data for Extra, the daily front page. Imported ONLY by the server
// page (app/extra/page.js), which filters live<=today before passing puzzles
// to the client — so future headlines, and their answers, never ship to the
// browser bundle.
//
// One historic front page a day. `head` is the headline (period wire style,
// written in-house — never a copied real headline). `hidden` lists EXACTLY SIX
// words, in TEAR/reveal order (least identifying first, giveaway last); each
// entry must match exactly one headline word (trailing punctuation ignored),
// or use 'WORD#2' for a repeated word's 2nd occurrence. `dateline` is revealed
// only by the free hint. `keys` are normalized answer substrings (lowercase
// alphanumerics+spaces) — a guess is right if its normalized text CONTAINS any
// key; keys must never appear in the always-visible headline words or the
// answer is readable on screen (validator enforces). `d` is the end-screen
// story line (15–110 chars). Sundays (`sunday: true`) are the same mechanic
// with a trickier story. Never reuse a moment banked here, in Circa, or in
// Dating.
export const PUZZLES = [
  {
    num: 1,
    quizId: 'extra-7-15-26',
    live: '2026-07-15',
    dateLabel: 'July 15, 2026',
    sunday: false,
    head: 'EXPLORERS OPEN SEALED TOMB OF BOY KING AFTER 3,000 YEARS UNDISTURBED',
    hidden: ['EXPLORERS', 'SEALED', '3,000', 'TOMB', 'BOY', 'KING'],
    dateline: 'NOVEMBER 26, 1922 · LUXOR, EGYPT',
    answer: "The discovery of King Tut's tomb",
    year: 1922,
    keys: ['tutankhamun', 'tutankhamen', 'king tut', 'tuts tomb', 'howard carter', 'valley of the kings', 'pharaoh'],
    d: "Asked if he could see anything through the hole, Howard Carter answered: 'Yes, wonderful things.'",
  },
  {
    num: 2,
    quizId: 'extra-7-16-26',
    live: '2026-07-16',
    dateLabel: 'July 16, 2026',
    sunday: false,
    head: "ALLIED ARMIES STORM BEACHES OF NORMANDY IN HISTORY'S GREATEST SEABORNE INVASION",
    hidden: ['STORM', 'INVASION', 'SEABORNE', 'ALLIED', 'BEACHES', 'NORMANDY'],
    dateline: 'JUNE 6, 1944 · OFF THE COAST OF FRANCE',
    answer: 'D-Day — the Allied invasion of Normandy',
    year: 1944,
    keys: ['d day', 'dday', 'normandy', 'operation overlord'],
    d: 'Some 156,000 men landed by sea and air on day one; the deception plan kept German armor waiting at Calais.',
  },
  {
    num: 3,
    quizId: 'extra-7-17-26',
    live: '2026-07-17',
    dateLabel: 'July 17, 2026',
    sunday: false,
    head: 'GIANT AIRSHIP BURSTS INTO FLAME AND FALLS AT MOORING MAST; 36 DEAD',
    hidden: ['36', 'FLAME', 'GIANT', 'MOORING', 'MAST', 'AIRSHIP'],
    dateline: 'MAY 6, 1937 · LAKEHURST, NEW JERSEY',
    answer: 'The Hindenburg disaster',
    year: 1937,
    keys: ['hindenburg', 'zeppelin', 'airship'],
    d: "Herbert Morrison's 'Oh, the humanity!' was recorded as the zeppelin burned in under a minute.",
  },
  {
    num: 4,
    quizId: 'extra-7-18-26',
    live: '2026-07-18',
    dateLabel: 'July 18, 2026',
    sunday: false,
    head: 'DODGERS ROOKIE BREAKS COLOR LINE IN MAJOR LEAGUE DEBUT AT FIRST BASE',
    hidden: ['LEAGUE', 'MAJOR', 'BASE', 'LINE', 'COLOR', 'DODGERS'],
    dateline: 'APRIL 15, 1947 · BROOKLYN',
    answer: "Jackie Robinson breaks baseball's color barrier",
    year: 1947,
    keys: ['jackie robinson', 'robinson', 'color barrier', 'colour barrier', 'color line'],
    d: 'He was Rookie of the Year that same season and took the Dodgers to the pennant.',
  },
  {
    num: 5,
    quizId: 'extra-7-19-26',
    live: '2026-07-19',
    dateLabel: 'July 19, 2026',
    sunday: true,
    head: 'MILLIONS PANIC AS RADIO DRAMA STAGES MARTIAN INVASION OF NEW JERSEY',
    hidden: ['NEW', 'JERSEY', 'DRAMA', 'RADIO', 'INVASION', 'MARTIAN'],
    dateline: 'OCTOBER 30, 1938 · NEW YORK',
    answer: "Orson Welles' War of the Worlds broadcast",
    year: 1938,
    keys: ['war of the worlds', 'orson welles', 'welles broadcast', 'martian broadcast', 'radio panic'],
    d: 'Welles was 23; the mass panic was mostly a newspaper invention, but it made him famous overnight.',
  },
  {
    num: 6,
    quizId: 'extra-7-20-26',
    live: '2026-07-20',
    dateLabel: 'July 20, 2026',
    sunday: false,
    head: 'PRESIDENT ORDERS NAVAL BLOCKADE AS SOVIET MISSILES ARE FOUND 90 MILES FROM FLORIDA',
    hidden: ['NAVAL', '90', 'BLOCKADE', 'FLORIDA', 'SOVIET', 'MISSILES'],
    dateline: 'OCTOBER 22, 1962 · WASHINGTON',
    answer: 'The Cuban Missile Crisis',
    year: 1962,
    keys: ['cuban missile', 'missile crisis', 'cuba missiles', 'cuba blockade', 'cuba quarantine'],
    d: 'Thirteen days on the edge; the deal that ended it quietly traded away American missiles in Turkey.',
  },
  {
    num: 7,
    quizId: 'extra-7-21-26',
    live: '2026-07-21',
    dateLabel: 'July 21, 2026',
    sunday: false,
    head: 'ATLANTIC AND PACIFIC JOINED AS FIRST SHIP SAILS THE NEW CANAL BETWEEN THE SEAS',
    hidden: ['SHIP', 'SEAS', 'JOINED', 'ATLANTIC', 'PACIFIC', 'CANAL'],
    dateline: 'AUGUST 15, 1914 · THE CANAL ZONE',
    answer: 'The Panama Canal opens',
    year: 1914,
    keys: ['panama'],
    d: 'The SS Ancon made the first official transit; the French attempt had collapsed 25 years earlier.',
  },
  {
    num: 8,
    quizId: 'extra-7-22-26',
    live: '2026-07-22',
    dateLabel: 'July 22, 2026',
    sunday: false,
    head: 'PRESIDENT QUITS OFFICE, FIRST EVER TO RESIGN, AS SCANDAL ENGULFS WHITE HOUSE',
    hidden: ['WHITE', 'HOUSE', 'QUITS', 'SCANDAL', 'RESIGN', 'PRESIDENT'],
    dateline: 'AUGUST 8, 1974 · WASHINGTON',
    answer: 'Nixon resigns over Watergate',
    year: 1974,
    keys: ['nixon', 'watergate'],
    d: "'I have never been a quitter,' he said in the broadcast, and then became the only president to quit.",
  },
  {
    num: 9,
    quizId: 'extra-7-23-26',
    live: '2026-07-23',
    dateLabel: 'July 23, 2026',
    sunday: false,
    head: 'SUFFRAGE AMENDMENT RATIFIED; 26 MILLION WOMEN WIN THE BALLOT',
    hidden: ['26', 'MILLION', 'AMENDMENT', 'BALLOT', 'WOMEN', 'SUFFRAGE'],
    dateline: 'AUGUST 26, 1920 · WASHINGTON',
    answer: 'The 19th Amendment gives women the vote',
    year: 1920,
    keys: ['19th amendment', 'nineteenth amendment', 'womens suffrage', 'women suffrage', 'women win the vote', 'women get the vote', 'womens vote', 'women vote', 'female suffrage', 'suffrage', 'right to vote'],
    d: 'Tennessee ratified by one vote, cast by 24-year-old Harry Burn after a letter from his mother.',
  },
  {
    num: 10,
    quizId: 'extra-7-24-26',
    live: '2026-07-24',
    dateLabel: 'July 24, 2026',
    sunday: false,
    head: 'SPACE SHUTTLE EXPLODES 73 SECONDS AFTER LIFTOFF; SEVEN ASTRONAUTS LOST',
    hidden: ['73', 'SEVEN', 'LIFTOFF', 'SPACE', 'ASTRONAUTS', 'SHUTTLE'],
    dateline: 'JANUARY 28, 1986 · CAPE CANAVERAL, FLORIDA',
    answer: 'The Challenger disaster',
    year: 1986,
    keys: ['challenger', 'shuttle disaster', 'shuttle explosion', 'shuttle explodes'],
    d: 'A frozen O-ring failed at launch; teacher Christa McAuliffe was aboard as millions watched live.',
  },
  {
    num: 11,
    quizId: 'extra-7-25-26',
    live: '2026-07-25',
    dateLabel: 'July 25, 2026',
    sunday: false,
    head: 'THREE DAYS OF BATTLE AT PENNSYLVANIA CROSSROADS TURN THE TIDE OF THE WAR',
    hidden: ['TIDE', 'THREE', 'WAR', 'CROSSROADS', 'BATTLE', 'PENNSYLVANIA'],
    dateline: 'JULY 3, 1863 · PENNSYLVANIA',
    answer: 'The Battle of Gettysburg',
    year: 1863,
    keys: ['gettysburg'],
    d: "Lincoln's address that November ran about 270 words; the day's featured speaker went two hours.",
  },
  {
    num: 12,
    quizId: 'extra-7-26-26',
    live: '2026-07-26',
    dateLabel: 'July 26, 2026',
    sunday: true,
    head: 'ASTRONOMERS VOTE TO STRIP NINTH PLANET OF ITS TITLE; SOLAR SYSTEM SHRINKS TO EIGHT',
    hidden: ['EIGHT', 'SOLAR', 'SYSTEM', 'ASTRONOMERS', 'NINTH', 'PLANET'],
    dateline: 'AUGUST 24, 2006 · PRAGUE',
    answer: 'Pluto is demoted from planet status',
    year: 2006,
    keys: ['pluto'],
    d: "The vote in Prague made it a 'dwarf planet'; New Horizons was already flying toward it.",
  },
  {
    num: 13,
    quizId: 'extra-7-27-26',
    live: '2026-07-27',
    dateLabel: 'July 27, 2026',
    sunday: false,
    head: 'THE GUNS FALL SILENT: ARMISTICE SIGNED, ENDING FOUR YEARS OF WORLD WAR',
    hidden: ['FOUR', 'GUNS', 'SILENT', 'WORLD', 'WAR', 'ARMISTICE'],
    dateline: 'NOVEMBER 11, 1918 · COMPIEGNE, FRANCE',
    answer: 'The Armistice ends World War I',
    year: 1918,
    keys: ['armistice', 'world war i ends', 'world war one ends', 'end of world war', 'end of the first world war', 'first world war ends', 'ww1 ends', 'wwi ends', 'great war ends'],
    d: 'Signed in a railway carriage at 5 a.m., effective at 11; the fighting ran on until the final minute.',
  },
  {
    num: 14,
    quizId: 'extra-7-28-26',
    live: '2026-07-28',
    dateLabel: 'July 28, 2026',
    sunday: false,
    head: 'NEW GATEWAY FOR IMMIGRANTS OPENS IN NEW YORK HARBOR; IRISH GIRL IS FIRST THROUGH',
    hidden: ['HARBOR', 'NEW#2', 'YORK', 'GATEWAY', 'IRISH', 'IMMIGRANTS'],
    dateline: 'JANUARY 1, 1892 · NEW YORK',
    answer: 'Ellis Island opens',
    year: 1892,
    keys: ['ellis'],
    d: 'Teenager Annie Moore from Cork was the first of some 12 million to pass through.',
  },
  {
    num: 15,
    quizId: 'extra-7-29-26',
    live: '2026-07-29',
    dateLabel: 'July 29, 2026',
    sunday: false,
    head: "SURGEONS PLACE A LIVING HUMAN HEART IN A DYING MAN'S CHEST",
    hidden: ['DYING', 'CHEST', 'LIVING', 'SURGEONS', 'HUMAN', 'HEART'],
    dateline: 'DECEMBER 3, 1967 · CAPE TOWN, SOUTH AFRICA',
    answer: 'The first human heart transplant',
    year: 1967,
    keys: ['heart transplant', 'christiaan barnard', 'barnard', 'transplant'],
    d: "Christiaan Barnard's patient lived 18 days; the operation changed surgery forever.",
  },
  {
    num: 16,
    quizId: 'extra-7-30-26',
    live: '2026-07-30',
    dateLabel: 'July 30, 2026',
    sunday: false,
    head: 'UNION JACK LOWERED AT MIDNIGHT AS COLONY RETURNS TO CHINA AFTER 156 YEARS',
    hidden: ['156', 'LOWERED', 'COLONY', 'UNION', 'JACK', 'CHINA'],
    dateline: 'JULY 1, 1997 · VICTORIA HARBOUR',
    answer: 'The Hong Kong handover',
    year: 1997,
    keys: ['hong kong'],
    d: "Prince Charles and Governor Patten sailed out on the royal yacht; Britain's 156-year colony was gone.",
  },
  {
    num: 17,
    quizId: 'extra-7-31-26',
    live: '2026-07-31',
    dateLabel: 'July 31, 2026',
    sunday: false,
    head: 'VOLCANO IN WASHINGTON STATE BLASTS 1,300 FEET OFF ITS OWN PEAK',
    hidden: ['FEET', '1,300', 'STATE', 'PEAK', 'VOLCANO', 'WASHINGTON'],
    dateline: 'MAY 18, 1980 · SKAMANIA COUNTY, WASHINGTON',
    answer: 'Mount St. Helens erupts',
    year: 1980,
    keys: ['st helens', 'saint helens'],
    d: 'The north face collapsed in the largest landslide ever recorded; ash fell across eleven states.',
  },
  {
    num: 18,
    quizId: 'extra-8-1-26',
    live: '2026-08-01',
    dateLabel: 'August 1, 2026',
    sunday: false,
    head: 'WESTERN PLANES BEGIN ROUND-THE-CLOCK FLIGHTS TO FEED A BLOCKADED CITY',
    hidden: ['CITY', 'FEED', 'WESTERN', 'FLIGHTS', 'PLANES', 'BLOCKADED'],
    dateline: 'JUNE 26, 1948 · BERLIN',
    answer: 'The Berlin Airlift begins',
    year: 1948,
    keys: ['berlin airlift', 'airlift'],
    d: "At its peak a plane landed about every 45 seconds; 'candy bombers' dropped sweets to children.",
  },
  {
    num: 19,
    quizId: 'extra-8-2-26',
    live: '2026-08-02',
    dateLabel: 'August 2, 2026',
    sunday: true,
    head: 'TANK BURSTS AND WAVE OF MOLASSES DROWNS CITY STREETS; 21 DEAD',
    hidden: ['21', 'STREETS', 'TANK', 'WAVE', 'DROWNS', 'MOLASSES'],
    dateline: 'JANUARY 15, 1919 · BOSTON',
    answer: 'The Great Boston Molasses Flood',
    year: 1919,
    keys: ['molasses'],
    d: 'A 25-foot wave moving 35 mph; locals swore the North End smelled sweet on hot days for decades.',
  },
  {
    num: 20,
    quizId: 'extra-8-3-26',
    live: '2026-08-03',
    dateLabel: 'August 3, 2026',
    sunday: false,
    head: 'TWIN CONCERTS ON TWO CONTINENTS PLAY TO A BILLION VIEWERS FOR FAMINE RELIEF',
    hidden: ['TWIN', 'BILLION', 'CONTINENTS', 'RELIEF', 'FAMINE', 'CONCERTS'],
    dateline: 'JULY 13, 1985 · LONDON AND PHILADELPHIA',
    answer: 'Live Aid',
    year: 1985,
    keys: ['live aid', 'liveaid'],
    d: "Bob Geldof pulled it together in ten weeks; Queen's 20-minute Wembley set became rock legend.",
  },
  {
    num: 21,
    quizId: 'extra-8-4-26',
    live: '2026-08-04',
    dateLabel: 'August 4, 2026',
    sunday: false,
    head: 'GOLDEN SPIKE DRIVEN IN UTAH; RAILS NOW LINK THE ATLANTIC TO THE PACIFIC',
    hidden: ['ATLANTIC', 'PACIFIC', 'RAILS', 'UTAH', 'GOLDEN', 'SPIKE'],
    dateline: 'MAY 10, 1869 · PROMONTORY SUMMIT, UTAH',
    answer: 'The transcontinental railroad is completed',
    year: 1869,
    keys: ['transcontinental', 'golden spike', 'pacific railroad', 'railroad completed', 'railroad complete'],
    d: "Leland Stanford swung at the last spike and missed; the telegraph flashed 'DONE' nationwide anyway.",
  },
];
