// Puzzle data for Extra, the daily front page. Imported ONLY by the server
// page (app/extra/page.js), which filters live<=today before passing puzzles
// to the client — so future headlines, and their answers, never ship to the
// browser bundle.
//
// One historic front page a day. `head` is the headline (period wire style,
// written in-house — never a copied real headline). `hidden` lists EXACTLY SIX
// words, in TEAR/reveal order (least identifying first, giveaway last); each
// entry must match exactly one headline word (trailing punctuation ignored),
// or use 'WORD#2' for a repeated word's 2nd occurrence. `dateline` is revealed
// only by the free hint. `keys` are normalized answer substrings (lowercase
// alphanumerics+spaces) — a guess is right if its normalized text CONTAINS any
// key; keys must never appear in the always-visible headline words or the
// answer is readable on screen (validator enforces). `d` is the end-screen
// story line (15–110 chars). Sundays (`sunday: true`) are the same mechanic
// with a trickier story. Never reuse a moment banked here, in Circa, or in
// Dating.
export const PUZZLES = [
  {
    num: 1,
    quizId: 'extra-7-15-26',
    live: '2026-07-15',
    dateLabel: 'July 15, 2026',
    sunday: false,
    head: 'EXPLORERS OPEN SEALED TOMB OF BOY KING AFTER 3,000 YEARS UNDISTURBED',
    hidden: ['EXPLORERS', 'SEALED', '3,000', 'TOMB', 'BOY', 'KING'],
    dateline: 'NOVEMBER 26, 1922 · LUXOR, EGYPT',
    answer: "The discovery of King Tut's tomb",
    year: 1922,
    keys: ['tutankhamun', 'tutankhamen', 'king tut', 'tuts tomb', 'howard carter', 'valley of the kings', 'pharaoh'],
    d: "Asked if he could see anything through the hole, Howard Carter answered: 'Yes, wonderful things.'",
  },
  {
    num: 2,
    quizId: 'extra-7-16-26',
    live: '2026-07-16',
    dateLabel: 'July 16, 2026',
    sunday: false,
    head: "ALLIED ARMIES STORM BEACHES OF NORMANDY IN HISTORY'S GREATEST SEABORNE INVASION",
    hidden: ['STORM', 'INVASION', 'SEABORNE', 'ALLIED', 'BEACHES', 'NORMANDY'],
    dateline: 'JUNE 6, 1944 · OFF THE COAST OF FRANCE',
    answer: 'D-Day — the Allied invasion of Normandy',
    year: 1944,
    keys: ['d day', 'dday', 'normandy', 'operation overlord'],
    d: 'Some 156,000 men landed by sea and air on day one; the deception plan kept German armor waiting at Calais.',
  },
  {
    num: 3,
    quizId: 'extra-7-17-26',
    live: '2026-07-17',
    dateLabel: 'July 17, 2026',
    sunday: false,
    head: 'GIANT AIRSHIP BURSTS INTO FLAME AND FALLS AT MOORING MAST; 36 DEAD',
    hidden: ['36', 'FLAME', 'GIANT', 'MOORING', 'MAST', 'AIRSHIP'],
    dateline: 'MAY 6, 1937 · LAKEHURST, NEW JERSEY',
    answer: 'The Hindenburg disaster',
    year: 1937,
    keys: ['hindenburg', 'zeppelin', 'airship'],
    d: "Herbert Morrison's 'Oh, the humanity!' was recorded as the zeppelin burned in under a minute.",
  },
  {
    num: 4,
    quizId: 'extra-7-18-26',
    live: '2026-07-18',
    dateLabel: 'July 18, 2026',
    sunday: false,
    head: 'DODGERS ROOKIE BREAKS COLOR LINE IN MAJOR LEAGUE DEBUT AT FIRST BASE',
    hidden: ['LEAGUE', 'MAJOR', 'BASE', 'LINE', 'COLOR', 'DODGERS'],
    dateline: 'APRIL 15, 1947 · BROOKLYN',
    answer: "Jackie Robinson breaks baseball's color barrier",
    year: 1947,
    keys: ['jackie robinson', 'robinson', 'color barrier', 'colour barrier', 'color line'],
    d: 'He was Rookie of the Year that same season and took the Dodgers to the pennant.',
  },
  {
    num: 5,
    quizId: 'extra-7-19-26',
    live: '2026-07-19',
    dateLabel: 'July 19, 2026',
    sunday: true,
    head: 'MILLIONS PANIC AS RADIO DRAMA STAGES MARTIAN INVASION OF NEW JERSEY',
    hidden: ['NEW', 'JERSEY', 'DRAMA', 'RADIO', 'INVASION', 'MARTIAN'],
    dateline: 'OCTOBER 30, 1938 · NEW YORK',
    answer: "Orson Welles' War of the Worlds broadcast",
    year: 1938,
    keys: ['war of the worlds', 'orson welles', 'welles broadcast', 'martian broadcast', 'radio panic'],
    d: 'Welles was 23; the mass panic was mostly a newspaper invention, but it made him famous overnight.',
  },
  {
    num: 6,
    quizId: 'extra-7-20-26',
    live: '2026-07-20',
    dateLabel: 'July 20, 2026',
    sunday: false,
    head: 'PRESIDENT ORDERS NAVAL BLOCKADE AS SOVIET MISSILES ARE FOUND 90 MILES FROM FLORIDA',
    hidden: ['NAVAL', '90', 'BLOCKADE', 'FLORIDA', 'SOVIET', 'MISSILES'],
    dateline: 'OCTOBER 22, 1962 · WASHINGTON',
    answer: 'The Cuban Missile Crisis',
    year: 1962,
    keys: ['cuban missile', 'missile crisis', 'cuba missiles', 'cuba blockade', 'cuba quarantine'],
    d: 'Thirteen days on the edge; the deal that ended it quietly traded away American missiles in Turkey.',
  },
  {
    num: 7,
    quizId: 'extra-7-21-26',
    live: '2026-07-21',
    dateLabel: 'July 21, 2026',
    sunday: false,
    head: 'ATLANTIC AND PACIFIC JOINED AS FIRST SHIP SAILS THE NEW CANAL BETWEEN THE SEAS',
    hidden: ['SHIP', 'SEAS', 'JOINED', 'ATLANTIC', 'PACIFIC', 'CANAL'],
    dateline: 'AUGUST 15, 1914 · THE CANAL ZONE',
    answer: 'The Panama Canal opens',
    year: 1914,
    keys: ['panama'],
    d: 'The SS Ancon made the first official transit; the French attempt had collapsed 25 years earlier.',
  },
  {
    num: 8,
    quizId: 'extra-7-22-26',
    live: '2026-07-22',
    dateLabel: 'July 22, 2026',
    sunday: false,
    head: 'PRESIDENT QUITS OFFICE, FIRST EVER TO RESIGN, AS SCANDAL ENGULFS WHITE HOUSE',
    hidden: ['WHITE', 'HOUSE', 'QUITS', 'SCANDAL', 'RESIGN', 'PRESIDENT'],
    dateline: 'AUGUST 8, 1974 · WASHINGTON',
    answer: 'Nixon resigns over Watergate',
    year: 1974,
    keys: ['nixon', 'watergate'],
    d: "'I have never been a quitter,' he said in the broadcast, and then became the only president to quit.",
  },
  {
    num: 9,
    quizId: 'extra-7-23-26',
    live: '2026-07-23',
    dateLabel: 'July 23, 2026',
    sunday: false,
    head: 'SUFFRAGE AMENDMENT RATIFIED; 26 MILLION WOMEN WIN THE BALLOT',
    hidden: ['26', 'MILLION', 'AMENDMENT', 'BALLOT', 'WOMEN', 'SUFFRAGE'],
    dateline: 'AUGUST 26, 1920 · WASHINGTON',
    answer: 'The 19th Amendment gives women the vote',
    year: 1920,
    keys: ['19th amendment', 'nineteenth amendment', 'womens suffrage', 'women suffrage', 'women win the vote', 'women get the vote', 'womens vote', 'women vote', 'female suffrage', 'suffrage', 'right to vote'],
    d: 'Tennessee ratified by one vote, cast by 24-year-old Harry Burn after a letter from his mother.',
  },
  {
    num: 10,
    quizId: 'extra-7-24-26',
    live: '2026-07-24',
    dateLabel: 'July 24, 2026',
    sunday: false,
    head: 'SPACE SHUTTLE EXPLODES 73 SECONDS AFTER LIFTOFF; SEVEN ASTRONAUTS LOST',
    hidden: ['73', 'SEVEN', 'LIFTOFF', 'SPACE', 'ASTRONAUTS', 'SHUTTLE'],
    dateline: 'JANUARY 28, 1986 · CAPE CANAVERAL, FLORIDA',
    answer: 'The Challenger disaster',
    year: 1986,
    keys: ['challenger', 'shuttle disaster', 'shuttle explosion', 'shuttle explodes'],
    d: 'A frozen O-ring failed at launch; teacher Christa McAuliffe was aboard as millions watched live.',
  },
  {
    num: 11,
    quizId: 'extra-7-25-26',
    live: '2026-07-25',
    dateLabel: 'July 25, 2026',
    sunday: false,
    head: 'THREE DAYS OF BATTLE AT PENNSYLVANIA CROSSROADS TURN THE TIDE OF THE WAR',
    hidden: ['TIDE', 'THREE', 'WAR', 'CROSSROADS', 'BATTLE', 'PENNSYLVANIA'],
    dateline: 'JULY 3, 1863 · PENNSYLVANIA',
    answer: 'The Battle of Gettysburg',
    year: 1863,
    keys: ['gettysburg'],
    d: "Lincoln's address that November ran about 270 words; the day's featured speaker went two hours.",
  },
  {
    num: 12,
    quizId: 'extra-7-26-26',
    live: '2026-07-26',
    dateLabel: 'July 26, 2026',
    sunday: true,
    head: 'ASTRONOMERS VOTE TO STRIP NINTH PLANET OF ITS TITLE; SOLAR SYSTEM SHRINKS TO EIGHT',
    hidden: ['EIGHT', 'SOLAR', 'SYSTEM', 'ASTRONOMERS', 'NINTH', 'PLANET'],
    dateline: 'AUGUST 24, 2006 · PRAGUE',
    answer: 'Pluto is demoted from planet status',
    year: 2006,
    keys: ['pluto'],
    d: "The vote in Prague made it a 'dwarf planet'; New Horizons was already flying toward it.",
  },
  {
    num: 13,
    quizId: 'extra-7-27-26',
    live: '2026-07-27',
    dateLabel: 'July 27, 2026',
    sunday: false,
    head: 'THE GUNS FALL SILENT: ARMISTICE SIGNED, ENDING FOUR YEARS OF WORLD WAR',
    hidden: ['FOUR', 'GUNS', 'SILENT', 'WORLD', 'WAR', 'ARMISTICE'],
    dateline: 'NOVEMBER 11, 1918 · COMPIEGNE, FRANCE',
    answer: 'The Armistice ends World War I',
    year: 1918,
    keys: ['armistice', 'world war i ends', 'world war one ends', 'end of world war', 'end of the first world war', 'first world war ends', 'ww1 ends', 'wwi ends', 'great war ends'],
    d: 'Signed in a railway carriage at 5 a.m., effective at 11; the fighting ran on until the final minute.',
  },
  {
    num: 14,
    quizId: 'extra-7-28-26',
    live: '2026-07-28',
    dateLabel: 'July 28, 2026',
    sunday: false,
    head: 'NEW GATEWAY FOR IMMIGRANTS OPENS IN NEW YORK HARBOR; IRISH GIRL IS FIRST THROUGH',
    hidden: ['HARBOR', 'NEW#2', 'YORK', 'GATEWAY', 'IRISH', 'IMMIGRANTS'],
    dateline: 'JANUARY 1, 1892 · NEW YORK',
    answer: 'Ellis Island opens',
    year: 1892,
    keys: ['ellis'],
    d: 'Teenager Annie Moore from Cork was the first of some 12 million to pass through.',
  },
  {
    num: 15,
    quizId: 'extra-7-29-26',
    live: '2026-07-29',
    dateLabel: 'July 29, 2026',
    sunday: false,
    head: "SURGEONS PLACE A LIVING HUMAN HEART IN A DYING MAN'S CHEST",
    hidden: ['DYING', 'CHEST', 'LIVING', 'SURGEONS', 'HUMAN', 'HEART'],
    dateline: 'DECEMBER 3, 1967 · CAPE TOWN, SOUTH AFRICA',
    answer: 'The first human heart transplant',
    year: 1967,
    keys: ['heart transplant', 'christiaan barnard', 'barnard', 'transplant'],
    d: "Christiaan Barnard's patient lived 18 days; the operation changed surgery forever.",
  },
  {
    num: 16,
    quizId: 'extra-7-30-26',
    live: '2026-07-30',
    dateLabel: 'July 30, 2026',
    sunday: false,
    head: 'UNION JACK LOWERED AT MIDNIGHT AS COLONY RETURNS TO CHINA AFTER 156 YEARS',
    hidden: ['156', 'LOWERED', 'COLONY', 'UNION', 'JACK', 'CHINA'],
    dateline: 'JULY 1, 1997 · VICTORIA HARBOUR',
    answer: 'The Hong Kong handover',
    year: 1997,
    keys: ['hong kong'],
    d: "Prince Charles and Governor Patten sailed out on the royal yacht; Britain's 156-year colony was gone.",
  },
  {
    num: 17,
    quizId: 'extra-7-31-26',
    live: '2026-07-31',
    dateLabel: 'July 31, 2026',
    sunday: false,
    head: 'VOLCANO IN WASHINGTON STATE BLASTS 1,300 FEET OFF ITS OWN PEAK',
    hidden: ['FEET', '1,300', 'STATE', 'PEAK', 'VOLCANO', 'WASHINGTON'],
    dateline: 'MAY 18, 1980 · SKAMANIA COUNTY, WASHINGTON',
    answer: 'Mount St. Helens erupts',
    year: 1980,
    keys: ['st helens', 'saint helens'],
    d: 'The north face collapsed in the largest landslide ever recorded; ash fell across eleven states.',
  },
  {
    num: 18,
    quizId: 'extra-8-1-26',
    live: '2026-08-01',
    dateLabel: 'August 1, 2026',
    sunday: false,
    head: 'WESTERN PLANES BEGIN ROUND-THE-CLOCK FLIGHTS TO FEED A BLOCKADED CITY',
    hidden: ['CITY', 'FEED', 'WESTERN', 'FLIGHTS', 'PLANES', 'BLOCKADED'],
    dateline: 'JUNE 26, 1948 · BERLIN',
    answer: 'The Berlin Airlift begins',
    year: 1948,
    keys: ['berlin airlift', 'airlift'],
    d: "At its peak a plane landed about every 45 seconds; 'candy bombers' dropped sweets to children.",
  },
  {
    num: 19,
    quizId: 'extra-8-2-26',
    live: '2026-08-02',
    dateLabel: 'August 2, 2026',
    sunday: true,
    head: 'TANK BURSTS AND WAVE OF MOLASSES DROWNS CITY STREETS; 21 DEAD',
    hidden: ['21', 'STREETS', 'TANK', 'WAVE', 'DROWNS', 'MOLASSES'],
    dateline: 'JANUARY 15, 1919 · BOSTON',
    answer: 'The Great Boston Molasses Flood',
    year: 1919,
    keys: ['molasses'],
    d: 'A 25-foot wave moving 35 mph; locals swore the North End smelled sweet on hot days for decades.',
  },
  {
    num: 20,
    quizId: 'extra-8-3-26',
    live: '2026-08-03',
    dateLabel: 'August 3, 2026',
    sunday: false,
    head: 'TWIN CONCERTS ON TWO CONTINENTS PLAY TO A BILLION VIEWERS FOR FAMINE RELIEF',
    hidden: ['TWIN', 'BILLION', 'CONTINENTS', 'RELIEF', 'FAMINE', 'CONCERTS'],
    dateline: 'JULY 13, 1985 · LONDON AND PHILADELPHIA',
    answer: 'Live Aid',
    year: 1985,
    keys: ['live aid', 'liveaid'],
    d: "Bob Geldof pulled it together in ten weeks; Queen's 20-minute Wembley set became rock legend.",
  },
  {
    num: 21,
    quizId: 'extra-8-4-26',
    live: '2026-08-04',
    dateLabel: 'August 4, 2026',
    sunday: false,
    head: 'GOLDEN SPIKE DRIVEN IN UTAH; RAILS NOW LINK THE ATLANTIC TO THE PACIFIC',
    hidden: ['ATLANTIC', 'PACIFIC', 'RAILS', 'UTAH', 'GOLDEN', 'SPIKE'],
    dateline: 'MAY 10, 1869 · PROMONTORY SUMMIT, UTAH',
    answer: 'The transcontinental railroad is completed',
    year: 1869,
    keys: ['transcontinental', 'golden spike', 'pacific railroad', 'railroad completed', 'railroad complete'],
    d: "Leland Stanford swung at the last spike and missed; the telegraph flashed 'DONE' nationwide anyway.",
  },
  {
    num: 22,
    quizId: 'extra-8-5-26',
    live: '2026-08-05',
    dateLabel: 'August 5, 2026',
    sunday: false,
    head: 'TWO AMERICANS WALK ON THE MOON AS HALF THE WORLD WATCHES THE LANDING',
    hidden: ['TWO', 'HALF', 'WALK', 'AMERICANS', 'MOON', 'LANDING'],
    dateline: 'JULY 20, 1969 · SEA OF TRANQUILITY, THE MOON',
    answer: 'The first Moon landing (Apollo 11)',
    year: 1969,
    keys: ['apollo', 'moon landing', 'neil armstrong', 'armstrong', 'lunar module', 'giant leap'],
    d: "Neil Armstrong's first step drew an estimated 600 million viewers, the largest TV audience to that date.",
  },
  {
    num: 23,
    quizId: 'extra-8-6-26',
    live: '2026-08-06',
    dateLabel: 'August 6, 2026',
    sunday: false,
    head: 'GIANT LINER CALLED UNSINKABLE STRIKES ICEBERG AND GOES DOWN ON MAIDEN VOYAGE',
    hidden: ['GIANT', 'VOYAGE', 'STRIKES', 'MAIDEN', 'ICEBERG', 'UNSINKABLE'],
    dateline: 'APRIL 15, 1912 · NORTH ATLANTIC OCEAN',
    answer: 'The sinking of the Titanic',
    year: 1912,
    keys: ['titanic'],
    d: 'About 1,500 died in the frozen North Atlantic; the ship carried lifeboats for barely half aboard.',
  },
  {
    num: 24,
    quizId: 'extra-8-7-26',
    live: '2026-08-07',
    dateLabel: 'August 7, 2026',
    sunday: false,
    head: 'CROWDS SWARM THE WALL AS EAST GERMANY THROWS OPEN ITS BORDERS OVERNIGHT',
    hidden: ['CROWDS', 'OVERNIGHT', 'SWARM', 'BORDERS', 'GERMANY', 'WALL'],
    dateline: 'NOVEMBER 9, 1989 · BERLIN',
    answer: 'The fall of the Berlin Wall',
    year: 1989,
    keys: ['berlin wall', 'fall of the berlin wall'],
    d: "The Cold War's most infamous barrier fell peacefully; Germans danced atop it as the guards stood aside.",
  },
  {
    num: 25,
    quizId: 'extra-8-8-26',
    live: '2026-08-08',
    dateLabel: 'August 8, 2026',
    sunday: false,
    head: 'TWO BROTHERS FLY A POWERED MACHINE OVER SANDS AT KITTY HAWK',
    hidden: ['TWO', 'SANDS', 'MACHINE', 'BROTHERS', 'KITTY', 'HAWK'],
    dateline: 'DECEMBER 17, 1903 · KITTY HAWK, NORTH CAROLINA',
    answer: "The Wright brothers' first flight",
    year: 1903,
    keys: ['wright brothers', 'wright', 'first powered flight', 'first airplane'],
    d: 'Orville flew 120 feet in 12 seconds over the Carolina dunes; few newspapers believed the report at first.',
  },
  {
    num: 26,
    quizId: 'extra-8-9-26',
    live: '2026-08-09',
    dateLabel: 'August 9, 2026',
    sunday: true,
    head: 'MIGHTY BLAST FLATTENS MILES OF SIBERIAN FOREST; NO CRATER FOUND',
    hidden: ['MIGHTY', 'FOUND', 'MILES', 'FLATTENS', 'BLAST', 'SIBERIAN'],
    dateline: 'JUNE 30, 1908 · TUNGUSKA, SIBERIA',
    answer: 'The Tunguska event',
    year: 1908,
    keys: ['tunguska'],
    d: 'An air-burst leveled some 800 square miles of remote taiga; no impact crater was ever found.',
  },
  {
    num: 27,
    quizId: 'extra-8-10-26',
    live: '2026-08-10',
    dateLabel: 'August 10, 2026',
    sunday: false,
    head: 'GREAT QUAKE AND FIRE LEVEL MUCH OF THE CITY BY THE BAY',
    hidden: ['MUCH', 'GREAT', 'LEVEL', 'FIRE', 'BAY', 'QUAKE'],
    dateline: 'APRIL 18, 1906 · SAN FRANCISCO',
    answer: 'The 1906 San Francisco earthquake',
    year: 1906,
    keys: ['san francisco earthquake', 'san francisco quake', '1906 earthquake', 'great san francisco'],
    d: 'A magnitude 7.9 shock and three days of fire destroyed most of San Francisco and left the city in ashes.',
  },
  {
    num: 28,
    quizId: 'extra-8-11-26',
    live: '2026-08-11',
    dateLabel: 'August 11, 2026',
    sunday: false,
    head: "FIRST GAMES OF THE REVIVED OLYMPIAD OPEN IN THE OLD STADIUM",
    hidden: ["GAMES", "OPEN", "STADIUM", "FIRST", "OLD"],
    dateline: "APRIL 6, 1896 · ATHENS",
    answer: "The first modern Olympic Games",
    year: 1896,
    keys: ["modern olympics", "first modern olympic", "1896 olympics", "athens olympics"],
    d: "Fourteen nations and some two hundred and forty athletes competed in a marble stadium rebuilt for the occasion.",
  },
  {
    num: 29,
    quizId: 'extra-8-12-26',
    live: '2026-08-12',
    dateLabel: 'August 12, 2026',
    sunday: false,
    head: "CANAL OPENS AND THE DESERT IS CUT IN TWO",
    hidden: ["CANAL", "OPENS", "DESERT", "CUT", "TWO"],
    dateline: "NOVEMBER 1869 · PORT SAID",
    answer: "The opening of the Suez Canal",
    year: 1869,
    keys: ["suez canal", "suez", "canal opens egypt"],
    d: "A hundred miles of cutting joined the Mediterranean to the Red Sea and halved the voyage to India.",
  },
  {
    num: 30,
    quizId: 'extra-8-13-26',
    live: '2026-08-13',
    dateLabel: 'August 13, 2026',
    sunday: false,
    head: "GLASS PALACE THROWN OPEN TO THE MULTITUDE",
    hidden: ["GLASS", "PALACE", "OPEN", "MULTITUDE", "THROWN"],
    dateline: "MAY 1, 1851 · LONDON",
    answer: "The opening of the Great Exhibition",
    year: 1851,
    keys: ["great exhibition", "crystal palace", "1851 exhibition"],
    d: "Six million visitors passed through Paxton's iron and glass hall in Hyde Park over five months.",
  },
  {
    num: 31,
    quizId: 'extra-8-14-26',
    live: '2026-08-14',
    dateLabel: 'August 14, 2026',
    sunday: false,
    head: "SIXTY RIDERS SET OFF ON A RACE AROUND THE WHOLE COUNTRY",
    hidden: ["RIDERS", "RACE", "WHOLE", "COUNTRY", "SET"],
    dateline: "JULY 1903 · PARIS",
    answer: "The first Tour de France",
    year: 1903,
    keys: ["tour de france", "first tour de france", "1903 tour"],
    d: "A newspaper stunt sent riders on six enormous stages, and only twenty-one of them finished.",
  },
  {
    num: 32,
    quizId: 'extra-8-15-26',
    live: '2026-08-15',
    dateLabel: 'August 15, 2026',
    sunday: false,
    head: "ISLAND BLOWN APART AND THE SOUND HEARD THREE THOUSAND MILES AWAY",
    hidden: ["ISLAND", "BLOWN", "SOUND", "HEARD", "MILES"],
    dateline: "AUGUST 1883 · SUNDA STRAIT",
    answer: "The eruption of Krakatoa",
    year: 1883,
    keys: ["krakatoa", "krakatau", "krakatoa eruption"],
    d: "The blast destroyed most of the island, and the report was heard as far off as Rodrigues.",
  },
  {
    num: 33,
    quizId: 'extra-8-16-26',
    live: '2026-08-16',
    dateLabel: 'August 16, 2026',
    sunday: true,
    head: "CITY OF POMPEII BURIED AS THE MOUNTAIN ERUPTS",
    hidden: ["POMPEII", "BURIED", "MOUNTAIN", "ERUPTS", "CITY"],
    dateline: "AD 79 · CAMPANIA",
    answer: "The eruption of Vesuvius that buried Pompeii",
    year: 79,
    keys: ["vesuvius", "pompeii", "mount vesuvius"],
    d: "Ash and pyroclastic flow sealed Pompeii and Herculaneum, preserving both towns for seventeen centuries.",
  },
  {
    num: 34,
    quizId: 'extra-8-17-26',
    live: '2026-08-17',
    dateLabel: 'August 17, 2026',
    sunday: false,
    head: "KING SIGNS THE CHARTER IN A MEADOW BY THE THAMES",
    hidden: ["KING", "CHARTER", "MEADOW", "THAMES", "SIGNS"],
    dateline: "JUNE 15, 1215 · RUNNYMEDE",
    answer: "The sealing of Magna Carta",
    year: 1215,
    keys: ["magna carta", "great charter", "runnymede"],
    d: "King John accepted the barons' charter at Runnymede, conceding that the crown was not above the law.",
  },
  {
    num: 35,
    quizId: 'extra-8-18-26',
    live: '2026-08-18',
    dateLabel: 'August 18, 2026',
    sunday: false,
    head: "PRINTER COMPLETES A BIBLE SET IN MOVABLE TYPE",
    hidden: ["PRINTER", "BIBLE", "MOVABLE", "TYPE", "SET"],
    dateline: "1455 · MAINZ",
    answer: "Gutenberg's printing of the first movable-type Bible",
    year: 1455,
    keys: ["gutenberg", "gutenberg bible", "printing press"],
    d: "Johannes Gutenberg finished a Bible printed with movable metal type, and reading was never the same.",
  },
  {
    num: 36,
    quizId: 'extra-8-19-26',
    live: '2026-08-19',
    dateLabel: 'August 19, 2026',
    sunday: false,
    head: "SHIPS SIGHT LAND AFTER FIVE WEEKS AT SEA",
    hidden: ["SHIPS", "LAND", "WEEKS", "SEA", "SIGHT"],
    dateline: "OCTOBER 12, 1492 · THE BAHAMAS",
    answer: "Columbus reaching the Americas",
    year: 1492,
    keys: ["columbus", "christopher columbus", "1492"],
    d: "Three Spanish ships made landfall in the Bahamas, opening four centuries of European expansion westward.",
  },
  {
    num: 37,
    quizId: 'extra-8-20-26',
    live: '2026-08-20',
    dateLabel: 'August 20, 2026',
    sunday: false,
    head: "MONK NAILS NINETY FIVE THESES TO A CHURCH DOOR",
    hidden: ["MONK", "THESES", "CHURCH", "DOOR", "NINETY"],
    dateline: "OCTOBER 1517 · WITTENBERG",
    answer: "Luther's Ninety-five Theses and the start of the Reformation",
    year: 1517,
    keys: ["luther", "martin luther", "ninety-five theses", "reformation"],
    d: "Martin Luther's objections to indulgences split Western Christianity within a generation.",
  },
  {
    num: 38,
    quizId: 'extra-8-21-26',
    live: '2026-08-21',
    dateLabel: 'August 21, 2026',
    sunday: false,
    head: "COLONIES DECLARE THEMSELVES FREE AND INDEPENDENT STATES",
    hidden: ["COLONIES", "DECLARE", "FREE", "INDEPENDENT", "STATES"],
    dateline: "JULY 4, 1776 · PHILADELPHIA",
    answer: "The signing of the Declaration of Independence",
    year: 1776,
    keys: ["declaration of independence", "american independence", "1776"],
    d: "Thirteen colonies adopted Jefferson's text and announced their separation from the British crown.",
  },
  {
    num: 39,
    quizId: 'extra-8-22-26',
    live: '2026-08-22',
    dateLabel: 'August 22, 2026',
    sunday: false,
    head: "CROWD STORMS THE OLD FORTRESS PRISON",
    hidden: ["CROWD", "STORMS", "FORTRESS", "PRISON", "OLD"],
    dateline: "JULY 14, 1789 · PARIS",
    answer: "The storming of the Bastille",
    year: 1789,
    keys: ["bastille", "storming of the bastille", "french revolution"],
    d: "Parisians took the fortress and its gunpowder, the day that came to stand for the whole revolution.",
  },
  {
    num: 40,
    quizId: 'extra-8-23-26',
    live: '2026-08-23',
    dateLabel: 'August 23, 2026',
    sunday: true,
    head: "EMPEROR MEETS HIS FINAL DEFEAT ON A MUDDY FIELD",
    hidden: ["EMPEROR", "FINAL", "DEFEAT", "MUDDY", "FIELD"],
    dateline: "JUNE 18, 1815 · WATERLOO",
    answer: "The Battle of Waterloo",
    year: 1815,
    keys: ["waterloo", "battle of waterloo", "napoleon defeated"],
    d: "Wellington and Blucher ended Napoleon's hundred-day return and with it two decades of European war.",
  },
  {
    num: 41,
    quizId: 'extra-8-24-26',
    live: '2026-08-24',
    dateLabel: 'August 24, 2026',
    sunday: false,
    head: "NATURALIST PUBLISHES A THEORY OF NATURAL SELECTION",
    hidden: ["NATURALIST", "THEORY", "NATURAL", "SELECTION", "PUBLISHES"],
    dateline: "NOVEMBER 24, 1859 · LONDON",
    answer: "The publication of On the Origin of Species",
    year: 1859,
    keys: ["origin of species", "darwin", "natural selection"],
    d: "Darwin's book sold out on its first day and recast the whole of biology around descent with modification.",
  },
  {
    num: 42,
    quizId: 'extra-8-25-26',
    live: '2026-08-25',
    dateLabel: 'August 25, 2026',
    sunday: false,
    head: "PRESIDENT SHOT AT THE THEATRE",
    hidden: ["PRESIDENT", "SHOT", "THEATRE"],
    dateline: "APRIL 14, 1865 · WASHINGTON",
    answer: "The assassination of Abraham Lincoln",
    year: 1865,
    keys: ["lincoln", "abraham lincoln", "lincoln assassination"],
    d: "John Wilkes Booth shot the president at Ford's Theatre five days after the surrender at Appomattox.",
  },
  {
    num: 43,
    quizId: 'extra-8-26-26',
    live: '2026-08-26',
    dateLabel: 'August 26, 2026',
    sunday: false,
    head: "INVENTOR SPEAKS THE FIRST WORDS DOWN A WIRE",
    hidden: ["INVENTOR", "SPEAKS", "WORDS", "WIRE", "FIRST"],
    dateline: "MARCH 10, 1876 · BOSTON",
    answer: "Bell's first telephone call",
    year: 1876,
    keys: ["telephone", "alexander graham bell", "first telephone call"],
    d: "Alexander Graham Bell called his assistant in the next room, and the human voice travelled by wire.",
  },
  {
    num: 44,
    quizId: 'extra-8-27-26',
    live: '2026-08-27',
    dateLabel: 'August 27, 2026',
    sunday: false,
    head: "ARCHDUKE SHOT IN THE STREET AS EUROPE HOLDS ITS BREATH",
    hidden: ["ARCHDUKE", "STREET", "EUROPE", "BREATH", "SHOT"],
    dateline: "JUNE 28, 1914 · SARAJEVO",
    answer: "The assassination of Archduke Franz Ferdinand",
    year: 1914,
    keys: ["franz ferdinand", "archduke", "sarajevo"],
    d: "Gavrilo Princip's shots in Sarajevo set off the alliances that dragged the continent into war within weeks.",
  },
  {
    num: 45,
    quizId: 'extra-8-28-26',
    live: '2026-08-28',
    dateLabel: 'August 28, 2026',
    sunday: false,
    head: "DOCTOR NOTICES A MOULD THAT KILLS THE BACTERIA",
    hidden: ["DOCTOR", "MOULD", "KILLS", "BACTERIA", "NOTICES"],
    dateline: "SEPTEMBER 1928 · LONDON",
    answer: "Fleming's discovery of penicillin",
    year: 1928,
    keys: ["penicillin", "fleming", "alexander fleming"],
    d: "Alexander Fleming returned from holiday to find a contaminated dish clearing itself of staphylococcus.",
  },
  {
    num: 46,
    quizId: 'extra-8-29-26',
    live: '2026-08-29',
    dateLabel: 'August 29, 2026',
    sunday: false,
    head: "MARKET COLLAPSES AS SELLING SWEEPS THE FLOOR",
    hidden: ["MARKET", "COLLAPSES", "SELLING", "SWEEPS", "FLOOR"],
    dateline: "OCTOBER 29, 1929 · NEW YORK",
    answer: "The Wall Street Crash",
    year: 1929,
    keys: ["wall street crash", "black tuesday", "1929 crash"],
    d: "Sixteen million shares changed hands on Black Tuesday and the Depression followed within months.",
  },
  {
    num: 47,
    quizId: 'extra-8-30-26',
    live: '2026-08-30',
    dateLabel: 'August 30, 2026',
    sunday: true,
    head: "COLOSSAL FIGURE UNVEILED IN THE HARBOUR MIST",
    hidden: ["FIGURE", "UNVEILED", "HARBOUR", "MIST", "COLOSSAL"],
    dateline: "OCTOBER 1886 · NEW YORK",
    answer: "The dedication of the Statue of Liberty",
    year: 1886,
    keys: ["statue of liberty", "liberty enlightening", "liberty dedicated"],
    d: "France's gift was unveiled on Bedloe's Island in fog so thick the crowd could barely see it.",
  },
  {
    num: 48,
    quizId: 'extra-8-31-26',
    live: '2026-08-31',
    dateLabel: 'August 31, 2026',
    sunday: false,
    head: "CITY DESTROYED BY A SINGLE BOMB",
    hidden: ["CITY", "DESTROYED", "SINGLE", "BOMB"],
    dateline: "AUGUST 6, 1945 · HIROSHIMA",
    answer: "The atomic bombing of Hiroshima",
    year: 1945,
    keys: ["hiroshima", "atomic bomb", "nuclear bomb"],
    d: "One weapon flattened the city centre, and Japan surrendered within nine days.",
  },
  {
    num: 49,
    quizId: 'extra-9-1-26',
    live: '2026-09-01',
    dateLabel: 'September 1, 2026',
    sunday: false,
    head: "TWO MEN REACH THE SUMMIT OF THE HIGHEST MOUNTAIN",
    hidden: ["MEN", "SUMMIT", "HIGHEST", "MOUNTAIN", "TWO"],
    dateline: "MAY 29, 1953 · NEPAL",
    answer: "The first ascent of Everest",
    year: 1953,
    keys: ["everest", "hillary", "tenzing", "first ascent of everest"],
    d: "Edmund Hillary and Tenzing Norgay stood on the top of Everest and were back down by nightfall.",
  },
  {
    num: 50,
    quizId: 'extra-9-2-26',
    live: '2026-09-02',
    dateLabel: 'September 2, 2026',
    sunday: false,
    head: "SCIENTISTS DESCRIBE THE STRUCTURE OF THE MOLECULE OF LIFE",
    hidden: ["SCIENTISTS", "STRUCTURE", "MOLECULE", "LIFE", "DESCRIBE"],
    dateline: "APRIL 25, 1953 · CAMBRIDGE",
    answer: "The discovery of the DNA double helix",
    year: 1953,
    keys: ["dna", "double helix", "watson and crick"],
    d: "Watson and Crick's one-page paper in Nature set out the double helix and how heredity is copied.",
  },
  {
    num: 51,
    quizId: 'extra-9-3-26',
    live: '2026-09-03',
    dateLabel: 'September 3, 2026',
    sunday: false,
    head: "SOVIET SPHERE CIRCLES THE EARTH EVERY NINETY MINUTES",
    hidden: ["SPHERE", "CIRCLES", "EARTH", "NINETY", "MINUTES"],
    dateline: "OCTOBER 4, 1957 · BAIKONUR",
    answer: "The launch of Sputnik 1",
    year: 1957,
    keys: ["sputnik", "first satellite", "sputnik 1"],
    d: "A polished metal ball the size of a beach ball began the space age and alarmed Washington.",
  },
  {
    num: 52,
    quizId: 'extra-9-4-26',
    live: '2026-09-04',
    dateLabel: 'September 4, 2026',
    sunday: false,
    head: "PREACHER TELLS THE CROWD OF HIS DREAM",
    hidden: ["PREACHER", "CROWD", "DREAM", "TELLS"],
    dateline: "AUGUST 28, 1963 · WASHINGTON",
    answer: "Martin Luther King's I Have a Dream speech",
    year: 1963,
    keys: ["i have a dream", "martin luther king", "march on washington"],
    d: "King spoke from the Lincoln Memorial steps to a quarter of a million people at the March on Washington.",
  },
  {
    num: 53,
    quizId: 'extra-9-5-26',
    live: '2026-09-05',
    dateLabel: 'September 5, 2026',
    sunday: false,
    head: "PRESIDENT KILLED BY RIFLE FIRE IN AN OPEN CAR",
    hidden: ["PRESIDENT", "KILLED", "RIFLE", "OPEN", "CAR"],
    dateline: "NOVEMBER 22, 1963 · DALLAS",
    answer: "The assassination of John F. Kennedy",
    year: 1963,
    keys: ["kennedy", "jfk", "kennedy assassination"],
    d: "Shots struck the president's motorcade in Dealey Plaza shortly after half past twelve.",
  },
  {
    num: 54,
    quizId: 'extra-9-6-26',
    live: '2026-09-06',
    dateLabel: 'September 6, 2026',
    sunday: true,
    head: "REACTOR EXPLODES AND A CLOUD DRIFTS WEST",
    hidden: ["REACTOR", "EXPLODES", "CLOUD", "DRIFTS", "WEST"],
    dateline: "APRIL 26, 1986 · PRIPYAT",
    answer: "The Chernobyl disaster",
    year: 1986,
    keys: ["chernobyl", "chornobyl", "reactor four"],
    d: "A botched safety test blew the roof off reactor four and contaminated a swathe of Europe.",
  },
  {
    num: 55,
    quizId: 'extra-9-7-26',
    live: '2026-09-07',
    dateLabel: 'September 7, 2026',
    sunday: false,
    head: "IRON TOWER FINISHED AND THE CITY LOOKS UP",
    hidden: ["IRON", "TOWER", "FINISHED", "CITY", "LOOKS"],
    dateline: "MARCH 1889 · PARIS",
    answer: "The completion of the Eiffel Tower",
    year: 1889,
    keys: ["eiffel tower", "eiffel", "tour eiffel"],
    d: "Three hundred metres of wrought iron went up in two years and stayed, despite the petitions.",
  },
  {
    num: 56,
    quizId: 'extra-9-8-26',
    live: '2026-09-08',
    dateLabel: 'September 8, 2026',
    sunday: false,
    head: "PRISONER WALKS FREE AFTER TWENTY SEVEN YEARS",
    hidden: ["PRISONER", "WALKS", "FREE", "TWENTY", "YEARS"],
    dateline: "FEBRUARY 11, 1990 · CAPE TOWN",
    answer: "Nelson Mandela's release from prison",
    year: 1990,
    keys: ["mandela", "nelson mandela", "mandela released"],
    d: "Mandela walked out of Victor Verster prison and addressed a vast crowd in Cape Town that evening.",
  },
  {
    num: 57,
    quizId: 'extra-9-9-26',
    live: '2026-09-09',
    dateLabel: 'September 9, 2026',
    sunday: false,
    head: "TWO TOWERS FALL AFTER AIRCRAFT STRIKE",
    hidden: ["TOWERS", "FALL", "AIRCRAFT", "STRIKE", "TWO"],
    dateline: "SEPTEMBER 11, 2001 · NEW YORK",
    answer: "The September 11 attacks",
    year: 2001,
    keys: ["september 11", "9/11", "twin towers", "world trade center"],
    d: "Hijacked airliners brought down the World Trade Center towers and struck the Pentagon.",
  },
  {
    num: 58,
    quizId: 'extra-9-10-26',
    live: '2026-09-10',
    dateLabel: 'September 10, 2026',
    sunday: false,
    head: "WAVE CROSSES THE OCEAN AND STRIKES A DOZEN COUNTRIES",
    hidden: ["WAVE", "CROSSES", "OCEAN", "STRIKES", "COUNTRIES"],
    dateline: "DECEMBER 26, 2004 · SUMATRA",
    answer: "The Indian Ocean tsunami",
    year: 2004,
    keys: ["indian ocean tsunami", "boxing day tsunami", "2004 tsunami"],
    d: "A magnitude 9.1 rupture off Sumatra sent waves across the Indian Ocean and killed some 230,000 people.",
  },
  {
    num: 59,
    quizId: 'extra-9-11-26',
    live: '2026-09-11',
    dateLabel: 'September 11, 2026',
    sunday: false,
    head: "COMPANY UNVEILS A TELEPHONE WITH NO KEYS",
    hidden: ["COMPANY", "TELEPHONE", "KEYS", "UNVEILS"],
    dateline: "JANUARY 9, 2007 · SAN FRANCISCO",
    answer: "The unveiling of the first iPhone",
    year: 2007,
    keys: ["iphone", "first iphone", "apple iphone"],
    d: "Steve Jobs showed a phone that was all screen, and the pocket computer arrived.",
  },
  {
    num: 60,
    quizId: 'extra-9-12-26',
    live: '2026-09-12',
    dateLabel: 'September 12, 2026',
    sunday: false,
    head: "ENGINEERS SWITCH ON THE GREAT RING BENEATH THE BORDER",
    hidden: ["ENGINEERS", "SWITCH", "RING", "BENEATH", "BORDER"],
    dateline: "SEPTEMBER 10, 2008 · GENEVA",
    answer: "The first beam in the Large Hadron Collider",
    year: 2008,
    keys: ["large hadron collider", "lhc", "cern collider"],
    d: "Protons ran the full twenty-seven kilometre ring for the first time under the French-Swiss border.",
  },
  {
    num: 61,
    quizId: 'extra-9-13-26',
    live: '2026-09-13',
    dateLabel: 'September 13, 2026',
    sunday: true,
    head: "LABORATORY REPORTS A NEW PARTICLE AT LAST",
    hidden: ["LABORATORY", "REPORTS", "PARTICLE", "LAST", "NEW"],
    dateline: "JULY 4, 2012 · GENEVA",
    answer: "The discovery of the Higgs boson",
    year: 2012,
    keys: ["higgs", "higgs boson", "god particle"],
    d: "Two CERN experiments announced a boson consistent with the particle predicted almost fifty years earlier.",
  },
  {
    num: 62,
    quizId: 'extra-9-14-26',
    live: '2026-09-14',
    dateLabel: 'September 14, 2026',
    sunday: false,
    head: "QUEEN CROWNED AS THE ABBEY BELLS RING OUT",
    hidden: ["QUEEN", "CROWNED", "ABBEY", "BELLS", "RING"],
    dateline: "JUNE 2, 1953 · LONDON",
    answer: "The coronation of Elizabeth II",
    year: 1953,
    keys: ["coronation of elizabeth", "elizabeth ii coronation", "1953 coronation"],
    d: "Twenty-seven million watched the first televised coronation from Westminster Abbey.",
  },
  {
    num: 63,
    quizId: 'extra-9-15-26',
    live: '2026-09-15',
    dateLabel: 'September 15, 2026',
    sunday: false,
    head: "FLEET SCATTERED BY FIRE SHIPS AND A RISING GALE",
    hidden: ["FLEET", "SCATTERED", "FIRE", "SHIPS", "GALE"],
    dateline: "AUGUST 8, 1588 · GRAVELINES",
    answer: "The defeat of the Spanish Armada",
    year: 1588,
    keys: ["spanish armada", "armada", "gravelines"],
    d: "English fire ships broke the crescent off Calais and the weather finished what the guns began.",
  },
  {
    num: 64,
    quizId: 'extra-9-16-26',
    live: '2026-09-16',
    dateLabel: 'September 16, 2026',
    sunday: false,
    head: "GREAT FIRE SWEEPS THE CITY FROM A BAKERS OVEN",
    hidden: ["FIRE", "SWEEPS", "CITY", "BAKERS", "OVEN"],
    dateline: "SEPTEMBER 2, 1666 · LONDON",
    answer: "The Great Fire of London",
    year: 1666,
    keys: ["great fire of london", "london fire", "pudding lane"],
    d: "Four days of fire from Pudding Lane destroyed thirteen thousand houses and old St Paul's.",
  },
  {
    num: 65,
    quizId: 'extra-9-17-26',
    live: '2026-09-17',
    dateLabel: 'September 17, 2026',
    sunday: false,
    head: "CHANNEL CROSSED BY A FLYING MACHINE",
    hidden: ["CHANNEL", "CROSSED", "FLYING", "MACHINE"],
    dateline: "JULY 25, 1909 · CALAIS",
    answer: "Bleriot's flight across the English Channel",
    year: 1909,
    keys: ["bleriot", "channel flight", "bleriot channel"],
    d: "Louis Bleriot flew from Calais to Dover in thirty-seven minutes and won a newspaper prize.",
  },
  {
    num: 66,
    quizId: 'extra-9-18-26',
    live: '2026-09-18',
    dateLabel: 'September 18, 2026',
    sunday: false,
    head: "EXPLORERS REACH THE BOTTOM OF THE WORLD",
    hidden: ["EXPLORERS", "REACH", "BOTTOM", "WORLD"],
    dateline: "DECEMBER 14, 1911 · ANTARCTICA",
    answer: "Amundsen reaching the South Pole",
    year: 1911,
    keys: ["amundsen", "south pole", "first to the south pole"],
    d: "Roald Amundsen's party arrived five weeks ahead of Scott and returned without loss.",
  },
  {
    num: 67,
    quizId: 'extra-9-19-26',
    live: '2026-09-19',
    dateLabel: 'September 19, 2026',
    sunday: false,
    head: "CURTAIN FALLS ON A CENTURY OF EMPIRE AT MIDNIGHT",
    hidden: ["CURTAIN", "FALLS", "CENTURY", "EMPIRE", "MIDNIGHT"],
    dateline: "AUGUST 15, 1947 · NEW DELHI",
    answer: "Indian independence and partition",
    year: 1947,
    keys: ["indian independence", "partition of india", "india independent"],
    d: "India woke to freedom at midnight, and partition displaced perhaps fifteen million people.",
  },
  {
    num: 68,
    quizId: 'extra-9-20-26',
    live: '2026-09-20',
    dateLabel: 'September 20, 2026',
    sunday: true,
    head: "PLAGUE CARRIED WEST ALONG THE TRADE ROUTES",
    hidden: ["PLAGUE", "CARRIED", "WEST", "TRADE", "ROUTES"],
    dateline: "OCTOBER 1, 1347 · MESSINA",
    answer: "The arrival of the Black Death in Europe",
    year: 1347,
    keys: ["black death", "bubonic plague", "the plague"],
    d: "Genoese galleys put in at Messina carrying the plague that killed a third of Europe.",
  },
  {
    num: 69,
    quizId: 'extra-9-21-26',
    live: '2026-09-21',
    dateLabel: 'September 21, 2026',
    sunday: false,
    head: "CITY WALLS BREACHED AFTER FIFTY THREE DAYS",
    hidden: ["WALLS", "BREACHED", "FIFTY", "DAYS", "CITY"],
    dateline: "MAY 29, 1453 · CONSTANTINOPLE",
    answer: "The fall of Constantinople",
    year: 1453,
    keys: ["fall of constantinople", "constantinople", "byzantine empire ends"],
    d: "Ottoman cannon brought down the Theodosian walls and the Byzantine empire ended that morning.",
  },
  {
    num: 70,
    quizId: 'extra-9-22-26',
    live: '2026-09-22',
    dateLabel: 'September 22, 2026',
    sunday: false,
    head: "ASTRONOMER PUTS THE SUN AT THE CENTRE OF THINGS",
    hidden: ["ASTRONOMER", "SUN", "CENTRE", "THINGS", "PUTS"],
    dateline: "1543 · NUREMBERG",
    answer: "The publication of Copernicus's heliocentric model",
    year: 1543,
    keys: ["copernicus", "heliocentric", "on the revolutions"],
    d: "Copernicus received the printed book on his deathbed, and the Earth stopped being the centre.",
  },
  {
    num: 71,
    quizId: 'extra-9-23-26',
    live: '2026-09-23',
    dateLabel: 'September 23, 2026',
    sunday: false,
    head: "SHIP RETURNS ALONE AFTER CIRCLING THE GLOBE",
    hidden: ["SHIP", "RETURNS", "ALONE", "CIRCLING", "GLOBE"],
    dateline: "SEPTEMBER 6, 1522 · SEVILLE",
    answer: "The first circumnavigation of the globe",
    year: 1522,
    keys: ["magellan", "circumnavigation", "elcano"],
    d: "Eighteen men aboard the Victoria completed the first voyage around the world under Elcano.",
  },
  {
    num: 72,
    quizId: 'extra-9-24-26',
    live: '2026-09-24',
    dateLabel: 'September 24, 2026',
    sunday: false,
    head: "TEA THROWN INTO THE HARBOUR BY MEN IN DISGUISE",
    hidden: ["TEA", "THROWN", "HARBOUR", "MEN", "DISGUISE"],
    dateline: "DECEMBER 16, 1773 · BOSTON",
    answer: "The Boston Tea Party",
    year: 1773,
    keys: ["boston tea party", "tea party", "boston harbour"],
    d: "Colonists tipped three hundred and forty-two chests of tea into the harbour over a tax.",
  },
  {
    num: 73,
    quizId: 'extra-9-25-26',
    live: '2026-09-25',
    dateLabel: 'September 25, 2026',
    sunday: false,
    head: "TELEGRAPH LINE JOINS THE TWO COASTS",
    hidden: ["TELEGRAPH", "LINE", "JOINS", "COASTS", "TWO"],
    dateline: "OCTOBER 24, 1861 · SALT LAKE CITY",
    answer: "The completion of the first transcontinental telegraph",
    year: 1861,
    keys: ["transcontinental telegraph", "telegraph line", "pony express ends"],
    d: "The wires met in Salt Lake City, and the Pony Express closed two days later.",
  },
  {
    num: 74,
    quizId: 'extra-9-26-26',
    live: '2026-09-26',
    dateLabel: 'September 26, 2026',
    sunday: false,
    head: "HOSTS TAKE THE FINAL BEFORE A ROARING STADIUM",
    hidden: ["HOSTS", "FINAL", "ROARING", "STADIUM", "TAKE"],
    dateline: "JULY 1930 · MONTEVIDEO",
    answer: "The first FIFA World Cup final",
    year: 1930,
    keys: ["world cup 1930", "first world cup", "uruguay world cup"],
    d: "Uruguay beat Argentina four goals to two in the Estadio Centenario, built for the tournament.",
  },
  {
    num: 75,
    quizId: 'extra-9-27-26',
    live: '2026-09-27',
    dateLabel: 'September 27, 2026',
    sunday: true,
    head: "RUNNER BREAKS THE FOUR MINUTE BARRIER ON A WINDY TRACK",
    hidden: ["RUNNER", "BREAKS", "MINUTE", "BARRIER", "TRACK"],
    dateline: "MAY 1954 · OXFORD",
    answer: "Roger Bannister's four-minute mile",
    year: 1954,
    keys: ["four minute mile", "bannister", "roger bannister"],
    d: "Bannister ran three minutes fifty-nine and four tenths at Iffley Road, paced by two friends.",
  },
  {
    num: 76,
    quizId: 'extra-9-28-26',
    live: '2026-09-28',
    dateLabel: 'September 28, 2026',
    sunday: false,
    head: "FOUR YOUNG MEN PLAY TO THE LARGEST AUDIENCE EVER SEEN",
    hidden: ["YOUNG", "PLAY", "LARGEST", "AUDIENCE", "FOUR"],
    dateline: "FEBRUARY 1964 · NEW YORK",
    answer: "The Beatles' first Ed Sullivan appearance",
    year: 1964,
    keys: ["ed sullivan", "beatles ed sullivan", "beatles america"],
    d: "Seventy-three million Americans watched the band play five songs on a Sunday night variety show.",
  },
  {
    num: 77,
    quizId: 'extra-9-29-26',
    live: '2026-09-29',
    dateLabel: 'September 29, 2026',
    sunday: false,
    head: "SUPERSONIC AIRLINER CARRIES ITS FIRST PAYING PASSENGERS",
    hidden: ["AIRLINER", "CARRIES", "FIRST", "PAYING", "PASSENGERS"],
    dateline: "JANUARY 1976 · LONDON",
    answer: "Concorde's first commercial flights",
    year: 1976,
    keys: ["concorde", "supersonic airliner", "concorde first flight"],
    d: "Two aircraft left London and Paris within minutes of each other, cruising at twice the speed of sound.",
  },
];
