// Puzzle data for Emcee, the daily mini crossword. Imported ONLY by the
// server page (app/emcee/page.js), which filters live<=today before passing
// puzzles to the client — so future grids, and their answers, never ship to
// the browser (same gating as every other daily).
//
// Each puzzle: `grid` rows use '#' for a block and the SOLUTION letter for a
// fillable square (today's answers ship, like every daily). `across`/`down`
// carry {n, r, c, len, clue}; answers are read off the grid, and numbering
// follows standard crossword rules (validated by the generator). Weekdays are
// a 5x5 with 10 words; Sundays step up to a 7x7 pinwheel with 22. Score is
// words correct out of the word count — a full clean solve is score = total —
// with ties broken by fewest checks (guessesUsed) and then fastest time.
export const PUZZLES = [
  {
    num: 1,
    quizId: 'emcee-7-16-26',
    live: '2026-07-16',
    dateLabel: 'July 16, 2026',
    sunday: false,
    size: 5,
    grid: ['##TOE', '#HEAR', 'SANTA', 'PUSH#', 'ALE##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Piggy that went to market' },
      { n: 4, r: 1, c: 1, len: 4, clue: 'Pick up with your ears' },
      { n: 5, r: 2, c: 0, len: 5, clue: 'Sleigh driver with a list' },
      { n: 6, r: 3, c: 0, len: 4, clue: 'Opposite of pull' },
      { n: 7, r: 4, c: 0, len: 3, clue: 'Pub pint' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Like a nail-biter\'s nerves' },
      { n: 2, r: 0, c: 3, len: 4, clue: 'Courtroom promise' },
      { n: 3, r: 0, c: 4, len: 3, clue: 'Historic stretch of time' },
      { n: 4, r: 1, c: 1, len: 4, clue: 'Big load to carry' },
      { n: 5, r: 2, c: 0, len: 3, clue: 'Place for a massage and a mud bath' },
    ],
  },
  {
    num: 2,
    quizId: 'emcee-7-17-26',
    live: '2026-07-17',
    dateLabel: 'July 17, 2026',
    sunday: false,
    size: 5,
    grid: ['#ELSE', 'BLOOD', 'AISLE', 'STEIN', 'HERD#'],
    across: [
      { n: 1, r: 0, c: 1, len: 4, clue: '"Or ___!" (threat ender)' },
      { n: 5, r: 1, c: 0, len: 5, clue: 'Type O fluid' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Walk down it at a wedding' },
      { n: 7, r: 3, c: 0, len: 5, clue: 'Oktoberfest mug' },
      { n: 8, r: 4, c: 0, len: 4, clue: 'Cattle crowd' },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: 'Top-tier' },
      { n: 2, r: 0, c: 2, len: 5, clue: 'One who didn\'t win' },
      { n: 3, r: 0, c: 3, len: 5, clue: 'Neither liquid nor gas' },
      { n: 4, r: 0, c: 4, len: 4, clue: 'Garden with a serpent' },
      { n: 5, r: 1, c: 0, len: 4, clue: 'Big party' },
    ],
  },
  {
    num: 3,
    quizId: 'emcee-7-18-26',
    live: '2026-07-18',
    dateLabel: 'July 18, 2026',
    sunday: false,
    size: 5,
    grid: ['#SET#', 'APART', 'RATIO', 'CREEP', '#END#'],
    across: [
      { n: 1, r: 0, c: 1, len: 3, clue: 'Tennis unit' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'Separated' },
      { n: 6, r: 2, c: 0, len: 5, clue: '16:9, for a TV screen' },
      { n: 7, r: 3, c: 0, len: 5, clue: 'Move like a cautious cat' },
      { n: 8, r: 4, c: 1, len: 3, clue: 'Finale' },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: 'Extra tire in the trunk' },
      { n: 2, r: 0, c: 2, len: 5, clue: 'Gone, as leftovers' },
      { n: 3, r: 0, c: 3, len: 5, clue: 'Gave it a shot' },
      { n: 4, r: 1, c: 0, len: 3, clue: 'Rainbow\'s shape' },
      { n: 5, r: 1, c: 4, len: 3, clue: 'Spinning toy' },
    ],
  },
  {
    num: 4,
    quizId: 'emcee-7-19-26',
    live: '2026-07-19',
    dateLabel: 'July 19, 2026',
    sunday: true,
    size: 7,
    grid: ['ARE#OWL', 'RIM#PIE', 'MOORING', '##TEN##', 'ACIDITY', 'DUO#OWE', 'DEN#NOT'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: '"How ___ you?"' },
      { n: 4, r: 0, c: 4, len: 3, clue: 'Night bird asking "who?"' },
      { n: 7, r: 1, c: 0, len: 3, clue: 'Basketball hoop\'s edge' },
      { n: 8, r: 1, c: 4, len: 3, clue: 'Dessert with a lattice crust' },
      { n: 9, r: 2, c: 0, len: 7, clue: 'Boat\'s tie-up spot' },
      { n: 11, r: 3, c: 2, len: 3, clue: 'Perfect gymnastics score' },
      { n: 12, r: 4, c: 0, len: 7, clue: 'What pH measures' },
      { n: 16, r: 5, c: 0, len: 3, clue: 'Batman and Robin, e.g.' },
      { n: 17, r: 5, c: 4, len: 3, clue: 'Have debts' },
      { n: 18, r: 6, c: 0, len: 3, clue: 'Lion\'s lair' },
      { n: 19, r: 6, c: 4, len: 3, clue: '"___ so fast!"' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Elbow\'s limb' },
      { n: 2, r: 0, c: 1, len: 3, clue: 'Brazil\'s carnival city, briefly' },
      { n: 3, r: 0, c: 2, len: 7, clue: 'Joy or anger' },
      { n: 4, r: 0, c: 4, len: 7, clue: 'Everyone has one, they say' },
      { n: 5, r: 0, c: 5, len: 3, clue: 'Come in first' },
      { n: 6, r: 0, c: 6, len: 3, clue: 'Relay race segment' },
      { n: 10, r: 2, c: 3, len: 3, clue: 'Stop-light color' },
      { n: 12, r: 4, c: 0, len: 3, clue: 'Do sums' },
      { n: 13, r: 4, c: 1, len: 3, clue: 'Pool stick' },
      { n: 14, r: 4, c: 5, len: 3, clue: 'Tango\'s number' },
      { n: 15, r: 4, c: 6, len: 3, clue: '"Are we there ___?"' },
    ],
  },
  {
    num: 5,
    quizId: 'emcee-7-20-26',
    live: '2026-07-20',
    dateLabel: 'July 20, 2026',
    sunday: false,
    size: 5,
    grid: ['#LATE', '#AWAY', 'SNAKE', 'ACRE#', 'TEEN#'],
    across: [
      { n: 1, r: 0, c: 1, len: 4, clue: 'Past the deadline' },
      { n: 5, r: 1, c: 1, len: 4, clue: 'Not home' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Slithering reptile' },
      { n: 7, r: 3, c: 0, len: 4, clue: 'Farm measure' },
      { n: 8, r: 4, c: 0, len: 4, clue: 'High schooler, usually' },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: 'Jousting knight\'s weapon' },
      { n: 2, r: 0, c: 2, len: 5, clue: 'In the know' },
      { n: 3, r: 0, c: 3, len: 5, clue: 'Not single' },
      { n: 4, r: 0, c: 4, len: 3, clue: 'Hurricane\'s calm center' },
      { n: 6, r: 2, c: 0, len: 3, clue: 'Took a seat' },
    ],
  },
  {
    num: 6,
    quizId: 'emcee-7-21-26',
    live: '2026-07-21',
    dateLabel: 'July 21, 2026',
    sunday: false,
    size: 5,
    grid: ['LEAN#', 'ENDED', 'STORE', 'SERVE', '#REED'],
    across: [
      { n: 1, r: 0, c: 0, len: 4, clue: 'Tilt, like Pisa\'s tower' },
      { n: 5, r: 1, c: 0, len: 5, clue: 'Wrapped up' },
      { n: 7, r: 2, c: 0, len: 5, clue: 'Where to shop' },
      { n: 8, r: 3, c: 0, len: 5, clue: 'Start a tennis point' },
      { n: 9, r: 4, c: 1, len: 4, clue: 'Clarinet mouthpiece part' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 4, clue: '"More or ___"' },
      { n: 2, r: 0, c: 1, len: 5, clue: 'Big key on a keyboard' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Love to bits' },
      { n: 4, r: 0, c: 3, len: 5, clue: 'Audacity' },
      { n: 6, r: 1, c: 4, len: 4, clue: 'Good Scout\'s daily act' },
    ],
  },
  {
    num: 7,
    quizId: 'emcee-7-22-26',
    live: '2026-07-22',
    dateLabel: 'July 22, 2026',
    sunday: false,
    size: 5,
    grid: ['##RAT', 'CHILI', 'LEGAL', 'ARISE', 'NOD##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Maze runner in a lab' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'Cook-off stew with beans' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Above board' },
      { n: 7, r: 3, c: 0, len: 5, clue: 'Get up' },
      { n: 8, r: 4, c: 0, len: 3, clue: 'Silent yes' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Not flexible' },
      { n: 2, r: 0, c: 3, len: 4, clue: '"Sadly..."' },
      { n: 3, r: 0, c: 4, len: 4, clue: 'Bathroom floor square' },
      { n: 4, r: 1, c: 0, len: 4, clue: 'Scottish family group' },
      { n: 5, r: 1, c: 1, len: 4, clue: 'Cape wearer' },
    ],
  },
  {
    num: 8,
    quizId: 'emcee-7-23-26',
    live: '2026-07-23',
    dateLabel: 'July 23, 2026',
    sunday: false,
    size: 5,
    grid: ['##ERA', '#FLAG', 'NIECE', 'ONCE#', 'WET##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'The disco ___' },
      { n: 4, r: 1, c: 1, len: 4, clue: 'Stars and Stripes, e.g.' },
      { n: 5, r: 2, c: 0, len: 5, clue: 'Sibling\'s daughter' },
      { n: 6, r: 3, c: 0, len: 4, clue: '"___ upon a time"' },
      { n: 7, r: 4, c: 0, len: 3, clue: 'Like fresh paint' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Choose by ballot' },
      { n: 2, r: 0, c: 3, len: 4, clue: 'Marathon, for one' },
      { n: 3, r: 0, c: 4, len: 3, clue: 'Birthday count' },
      { n: 4, r: 1, c: 1, len: 4, clue: 'Parking ticket penalty' },
      { n: 5, r: 2, c: 0, len: 3, clue: '"Do it ___!"' },
    ],
  },
  {
    num: 9,
    quizId: 'emcee-7-24-26',
    live: '2026-07-24',
    dateLabel: 'July 24, 2026',
    sunday: false,
    size: 5,
    grid: ['#CARE', 'SALAD', 'UNITE', 'RAVEN', 'FLED#'],
    across: [
      { n: 1, r: 0, c: 1, len: 4, clue: 'Handle with ___' },
      { n: 5, r: 1, c: 0, len: 5, clue: 'Course with croutons' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Come together' },
      { n: 7, r: 3, c: 0, len: 5, clue: 'Poe\'s "Nevermore" bird' },
      { n: 8, r: 4, c: 0, len: 4, clue: 'Ran off' },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: 'Panama passage' },
      { n: 2, r: 0, c: 2, len: 5, clue: '"It\'s ___!" (mad scientist\'s cry)' },
      { n: 3, r: 0, c: 3, len: 5, clue: 'Given stars' },
      { n: 4, r: 0, c: 4, len: 4, clue: 'Adam and Eve\'s address' },
      { n: 5, r: 1, c: 0, len: 4, clue: 'Ride a wave' },
    ],
  },
  {
    num: 10,
    quizId: 'emcee-7-25-26',
    live: '2026-07-25',
    dateLabel: 'July 25, 2026',
    sunday: false,
    size: 5,
    grid: ['#ANT#', 'BLOOM', 'ALIKE', 'RESET', '#YEN#'],
    across: [
      { n: 1, r: 0, c: 1, len: 3, clue: 'Picnic crasher' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'What roses do in spring' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Two peas in a pod are this' },
      { n: 7, r: 3, c: 0, len: 5, clue: 'Fix-it button on a router' },
      { n: 8, r: 4, c: 1, len: 3, clue: 'Tokyo currency' },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: 'Bowling lane' },
      { n: 2, r: 0, c: 2, len: 5, clue: 'Racket' },
      { n: 3, r: 0, c: 3, len: 5, clue: 'Arcade coin' },
      { n: 4, r: 1, c: 0, len: 3, clue: 'Chocolate unit' },
      { n: 5, r: 1, c: 4, len: 3, clue: 'Made someone\'s acquaintance' },
    ],
  },
  {
    num: 11,
    quizId: 'emcee-7-26-26',
    live: '2026-07-26',
    dateLabel: 'July 26, 2026',
    sunday: true,
    size: 7,
    grid: ['ARE#HAT', 'WED#EGO', 'EDITION', '##FOR##', 'STIPEND', 'ARC#SEE', 'DYE#SON'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: '"You ___ here"' },
      { n: 4, r: 0, c: 4, len: 3, clue: 'Top hat or beanie' },
      { n: 7, r: 1, c: 0, len: 3, clue: 'Tie the knot' },
      { n: 8, r: 1, c: 4, len: 3, clue: 'Sense of self' },
      { n: 9, r: 2, c: 0, len: 7, clue: 'Limited ___ (collector\'s release)' },
      { n: 11, r: 3, c: 2, len: 3, clue: '"___ example"' },
      { n: 12, r: 4, c: 0, len: 7, clue: 'Intern\'s modest pay' },
      { n: 16, r: 5, c: 0, len: 3, clue: 'Story ___ (plot line)' },
      { n: 17, r: 5, c: 4, len: 3, clue: '"___ you later!"' },
      { n: 18, r: 6, c: 0, len: 3, clue: 'Easter egg colorer' },
      { n: 19, r: 6, c: 4, len: 3, clue: 'Father\'s boy' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Grand Canyon reaction' },
      { n: 2, r: 0, c: 1, len: 3, clue: 'Rose\'s classic color' },
      { n: 3, r: 0, c: 2, len: 7, clue: 'Grand building' },
      { n: 4, r: 0, c: 4, len: 7, clue: 'Fortune inheritor' },
      { n: 5, r: 0, c: 5, len: 3, clue: 'Long, long ___' },
      { n: 6, r: 0, c: 6, len: 3, clue: '2,000 pounds' },
      { n: 10, r: 2, c: 3, len: 3, clue: 'Mountain\'s peak' },
      { n: 12, r: 4, c: 0, len: 3, clue: 'Blue' },
      { n: 13, r: 4, c: 1, len: 3, clue: 'Give it a whirl' },
      { n: 14, r: 4, c: 5, len: 3, clue: '"The Matrix" hero' },
      { n: 15, r: 4, c: 6, len: 3, clue: 'Cozy TV room' },
    ],
  },
  {
    num: 12,
    quizId: 'emcee-7-27-26',
    live: '2026-07-27',
    dateLabel: 'July 27, 2026',
    sunday: false,
    size: 5,
    grid: ['#STAR', '#HALO', 'HABIT', 'IDLE#', 'SEEN#'],
    across: [
      { n: 1, r: 0, c: 1, len: 4, clue: 'Walk of Fame symbol' },
      { n: 5, r: 1, c: 1, len: 4, clue: 'Angel\'s ring' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Hard thing to break' },
      { n: 7, r: 3, c: 0, len: 4, clue: 'Just sitting around' },
      { n: 8, r: 4, c: 0, len: 4, clue: 'Spotted' },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: 'Where to cool off on a sunny day' },
      { n: 2, r: 0, c: 2, len: 5, clue: 'Dinner setting spot' },
      { n: 3, r: 0, c: 3, len: 5, clue: 'UFO pilot' },
      { n: 4, r: 0, c: 4, len: 3, clue: 'Spoil' },
      { n: 6, r: 2, c: 0, len: 3, clue: 'Hers\' partner' },
    ],
  },
  {
    num: 13,
    quizId: 'emcee-7-28-26',
    live: '2026-07-28',
    dateLabel: 'July 28, 2026',
    sunday: false,
    size: 5,
    grid: ['##TEA', '#GRAY', 'FLARE', 'RUIN#', 'YET##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Earl Grey, e.g.' },
      { n: 4, r: 1, c: 1, len: 4, clue: 'Color of storm clouds' },
      { n: 5, r: 2, c: 0, len: 5, clue: 'Emergency roadside light' },
      { n: 6, r: 3, c: 0, len: 4, clue: 'Spoil completely' },
      { n: 7, r: 4, c: 0, len: 3, clue: 'So far' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Inherited quality' },
      { n: 2, r: 0, c: 3, len: 4, clue: 'Bring home, as a salary' },
      { n: 3, r: 0, c: 4, len: 3, clue: 'Sailor\'s yes' },
      { n: 4, r: 1, c: 1, len: 4, clue: 'Craft-table sticker' },
      { n: 5, r: 2, c: 0, len: 3, clue: 'Cook in hot oil' },
    ],
  },
  {
    num: 14,
    quizId: 'emcee-7-29-26',
    live: '2026-07-29',
    dateLabel: 'July 29, 2026',
    sunday: false,
    size: 5,
    grid: ['##ICE', 'STRAY', 'AROSE', 'LINED', 'TOY##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Rink surface' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'Shelter cat, once' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Got out of bed' },
      { n: 7, r: 3, c: 0, len: 5, clue: 'Like notebook paper' },
      { n: 8, r: 4, c: 0, len: 3, clue: 'Yo-yo or teddy bear' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: '"Rain on your wedding day," per Alanis' },
      { n: 2, r: 0, c: 3, len: 4, clue: 'Detective\'s assignment' },
      { n: 3, r: 0, c: 4, len: 4, clue: 'Looked at' },
      { n: 4, r: 1, c: 0, len: 4, clue: 'Pepper\'s partner' },
      { n: 5, r: 1, c: 1, len: 4, clue: 'Group of three' },
    ],
  },
  {
    num: 15,
    quizId: 'emcee-7-30-26',
    live: '2026-07-30',
    dateLabel: 'July 30, 2026',
    sunday: false,
    size: 5,
    grid: ['##RAT', 'AWARE', 'CIVIL', 'IDEAL', 'DEN##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Rodent that deserts a sinking ship' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'Not oblivious' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Polite, if a bit cool' },
      { n: 7, r: 3, c: 0, len: 5, clue: 'Just perfect' },
      { n: 8, r: 4, c: 0, len: 3, clue: 'Home office, often' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Glossy jet-black bird' },
      { n: 2, r: 0, c: 3, len: 4, clue: 'Opera showstopper' },
      { n: 3, r: 0, c: 4, len: 4, clue: 'Poker player\'s giveaway' },
      { n: 4, r: 1, c: 0, len: 4, clue: 'Opposite of base, in chemistry' },
      { n: 5, r: 1, c: 1, len: 4, clue: 'Not narrow' },
    ],
  },
  {
    num: 16,
    quizId: 'emcee-7-31-26',
    live: '2026-07-31',
    dateLabel: 'July 31, 2026',
    sunday: false,
    size: 5,
    grid: ['##RAG', 'SCOUR', 'PLANE', 'RUSTY', 'YET##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Old cloth for dusting' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'Scrub hard, as a greasy pan' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Jet at the airport' },
      { n: 7, r: 3, c: 0, len: 5, clue: 'Out of practice' },
      { n: 8, r: 4, c: 0, len: 3, clue: 'Nevertheless' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Cook in the oven, as a chicken' },
      { n: 2, r: 0, c: 3, len: 4, clue: 'Uncle\'s wife' },
      { n: 3, r: 0, c: 4, len: 4, clue: 'Elephant\'s hue' },
      { n: 4, r: 1, c: 0, len: 4, clue: 'Nimble, despite the years' },
      { n: 5, r: 1, c: 1, len: 4, clue: 'Detective\'s lead' },
    ],
  },
  {
    num: 17,
    quizId: 'emcee-8-1-26',
    live: '2026-08-01',
    dateLabel: 'August 1, 2026',
    sunday: false,
    size: 5,
    grid: ['RID##', 'ITEMS', 'OCTET', 'THEME', '##ROW'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Get ___ of (eliminate)' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'Things on a to-do list' },
      { n: 7, r: 2, c: 0, len: 5, clue: 'Group of eight singers' },
      { n: 8, r: 3, c: 0, len: 5, clue: 'Central topic of an essay' },
      { n: 9, r: 4, c: 2, len: 3, clue: 'Line of seats at a theater' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 4, clue: 'Unruly crowd disturbance' },
      { n: 2, r: 0, c: 1, len: 4, clue: 'Reason to scratch' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Discourage from doing something' },
      { n: 5, r: 1, c: 3, len: 4, clue: 'Quick office note' },
      { n: 6, r: 1, c: 4, len: 4, clue: 'Simmered beef-and-vegetable dish' },
    ],
  },
  {
    num: 18,
    quizId: 'emcee-8-2-26',
    live: '2026-08-02',
    dateLabel: 'August 2, 2026',
    sunday: true,
    size: 7,
    grid: ['DOE#GOO', 'OWL#END', 'NEEDLED', '##VIA##', 'PHANTOM', 'RAT#IRE', 'ODE#NET'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Female deer' },
      { n: 4, r: 0, c: 4, len: 3, clue: 'Sticky gunk' },
      { n: 7, r: 1, c: 0, len: 3, clue: 'Nighttime hooter' },
      { n: 8, r: 1, c: 4, len: 3, clue: 'Finish line, of a sort' },
      { n: 9, r: 2, c: 0, len: 7, clue: 'Teased or prodded persistently' },
      { n: 11, r: 3, c: 2, len: 3, clue: 'By way of' },
      { n: 12, r: 4, c: 0, len: 7, clue: 'Spooky apparition, or the "of the Opera"' },
      { n: 16, r: 5, c: 0, len: 3, clue: 'Sewer rodent' },
      { n: 17, r: 5, c: 4, len: 3, clue: 'Boiling anger' },
      { n: 18, r: 6, c: 0, len: 3, clue: 'Poem of praise' },
      { n: 19, r: 6, c: 4, len: 3, clue: "Goalie's target" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Put on, as a coat' },
      { n: 2, r: 0, c: 1, len: 3, clue: 'Be in debt' },
      { n: 3, r: 0, c: 2, len: 7, clue: 'Raise up' },
      { n: 4, r: 0, c: 4, len: 7, clue: 'Jell-O base' },
      { n: 5, r: 0, c: 5, len: 3, clue: 'The loneliest number, in song' },
      { n: 6, r: 0, c: 6, len: 3, clue: 'Not even' },
      { n: 10, r: 2, c: 3, len: 3, clue: 'Loud racket' },
      { n: 12, r: 4, c: 0, len: 3, clue: 'Seasoned expert' },
      { n: 13, r: 4, c: 1, len: 3, clue: 'Possessed, in the past' },
      { n: 14, r: 4, c: 5, len: 3, clue: 'Rock with metal in it' },
      { n: 15, r: 4, c: 6, len: 3, clue: 'Ran into, as an old friend' },
    ],
  },
  {
    num: 19,
    quizId: 'emcee-8-3-26',
    live: '2026-08-03',
    dateLabel: 'August 3, 2026',
    sunday: false,
    size: 5,
    grid: ['##RIB', 'PRIDE', 'EASEL', 'STEAL', 'TEN##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Barbecue rack cut' },
      { n: 4, r: 1, c: 0, len: 5, clue: "Lions' group, or a deadly sin" },
      { n: 6, r: 2, c: 0, len: 5, clue: "Painter's three-legged stand" },
      { n: 7, r: 3, c: 0, len: 5, clue: "Swipe, or a base runner's feat" },
      { n: 8, r: 4, c: 0, len: 3, clue: 'Perfect gymnastics score' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Come up, like bread dough' },
      { n: 2, r: 0, c: 3, len: 4, clue: 'Lightbulb moment' },
      { n: 3, r: 0, c: 4, len: 4, clue: 'It rings at recess' },
      { n: 4, r: 1, c: 0, len: 4, clue: 'Annoying little insect' },
      { n: 5, r: 1, c: 1, len: 4, clue: 'Speed, or an interest figure' },
    ],
  },
  {
    num: 20,
    quizId: 'emcee-8-4-26',
    live: '2026-08-04',
    dateLabel: 'August 4, 2026',
    sunday: false,
    size: 5,
    grid: ['##OUR', 'ABUSE', 'RATES', 'CREST', 'HER##'],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: 'Belonging to us' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'Mistreat or misuse' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Hotel room prices' },
      { n: 7, r: 3, c: 0, len: 5, clue: 'Top of a hill or wave' },
      { n: 8, r: 4, c: 0, len: 3, clue: 'Belonging to her' },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: 'Farthest from the center' },
      { n: 2, r: 0, c: 3, len: 4, clue: 'Puts to work' },
      { n: 3, r: 0, c: 4, len: 4, clue: 'Take a breather' },
      { n: 4, r: 1, c: 0, len: 4, clue: 'Curved doorway shape' },
      { n: 5, r: 1, c: 1, len: 4, clue: 'Uncovered, as feet' },
    ],
  },
  {
    num: 21,
    quizId: 'emcee-8-5-26',
    live: '2026-08-05',
    dateLabel: 'August 5, 2026',
    sunday: false,
    size: 5,
    grid: ['#HASH', 'FORCE', 'ANGEL', 'SOUND', 'TREE#'],
    across: [
      { n: 1, r: 0, c: 1, len: 4, clue: 'Corned beef ___ (diner dish)' },
      { n: 5, r: 1, c: 0, len: 5, clue: 'Push or pull, in physics' },
      { n: 6, r: 2, c: 0, len: 5, clue: 'Winged heavenly figure' },
      { n: 7, r: 3, c: 0, len: 5, clue: 'What the ears pick up' },
      { n: 8, r: 4, c: 0, len: 4, clue: 'Oak or maple, for one' },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: 'Great respect' },
      { n: 2, r: 0, c: 2, len: 5, clue: 'Bicker heatedly' },
      { n: 3, r: 0, c: 3, len: 5, clue: 'Part of a play or movie' },
      { n: 4, r: 0, c: 4, len: 4, clue: 'Kept a firm grip on' },
      { n: 5, r: 1, c: 0, len: 4, clue: 'Speedy' },
    ],
  },
  {
    num: 22,
    quizId: 'emcee-8-6-26',
    live: '2026-08-06',
    dateLabel: 'August 6, 2026',
    sunday: false,
    size: 5,
    grid: ['ABS##', 'NOISE', 'TOTAL', 'ITEMS', '##SEE'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Six-pack muscles, briefly' },
      { n: 4, r: 1, c: 0, len: 5, clue: 'Loud racket' },
      { n: 7, r: 2, c: 0, len: 5, clue: 'Grand sum' },
      { n: 8, r: 3, c: 0, len: 5, clue: 'Things on a shopping list' },
      { n: 9, r: 4, c: 2, len: 3, clue: 'Take a look' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 4, clue: 'Prefix meaning against' },
      { n: 2, r: 0, c: 1, len: 4, clue: 'Ankle-high footwear' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Construction locations' },
      { n: 5, r: 1, c: 3, len: 4, clue: 'Identical' },
      { n: 6, r: 1, c: 4, len: 4, clue: '"Or ___!"' },
    ],
  },
  {
    num: 23,
    quizId: 'emcee-8-7-26',
    live: '2026-08-07',
    dateLabel: 'August 7, 2026',
    sunday: false,
    size: 5,
    grid: ['STAR#', 'ERROR', 'PIECE', 'TANKS', '#LAST'],
    across: [
      { n: 1, r: 0, c: 0, len: 4, clue: 'Twinkler in the night sky' },
      { n: 5, r: 1, c: 0, len: 5, clue: 'Blooper or mistake' },
      { n: 7, r: 2, c: 0, len: 5, clue: 'Slice of pie, e.g.' },
      { n: 8, r: 3, c: 0, len: 5, clue: 'Treaded army vehicles' },
      { n: 9, r: 4, c: 1, len: 4, clue: 'Final' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 4, clue: 'Fall mo. after Aug.' },
      { n: 2, r: 0, c: 1, len: 5, clue: 'Courtroom proceeding' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Big indoor sports venue' },
      { n: 4, r: 0, c: 3, len: 5, clue: 'On the ___ (over ice)' },
      { n: 6, r: 1, c: 4, len: 4, clue: 'What weary legs need' },
    ],
  },
  {
    num: 24,
    quizId: 'emcee-8-8-26',
    live: '2026-08-08',
    dateLabel: 'August 8, 2026',
    sunday: false,
    size: 5,
    grid: ['E#PIG', 'SPICE', 'SALON', 'ALONE', 'YET#S'],
    across: [
      { n: 2, r: 0, c: 2, len: 3, clue: 'Barnyard animal that oinks' },
      { n: 5, r: 1, c: 0, len: 5, clue: 'Cinnamon or cumin' },
      { n: 7, r: 2, c: 0, len: 5, clue: 'Place for a haircut' },
      { n: 8, r: 3, c: 0, len: 5, clue: 'All by oneself' },
      { n: 9, r: 4, c: 0, len: 3, clue: 'Nevertheless' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 5, clue: 'Short written composition' },
      { n: 2, r: 0, c: 2, len: 5, clue: 'Cockpit occupant' },
      { n: 3, r: 0, c: 3, len: 4, clue: 'Little app symbol you tap' },
      { n: 4, r: 0, c: 4, len: 5, clue: 'Units of heredity' },
      { n: 6, r: 1, c: 1, len: 4, clue: 'Lacking color' },
    ],
  },
  {
    num: 25,
    quizId: 'emcee-8-9-26',
    live: '2026-08-09',
    dateLabel: 'August 9, 2026',
    sunday: true,
    size: 7,
    grid: ['HAS#ARE', 'ONE#BUG', 'WARNING', '##VOL##', 'SHERIFF', 'PAR#TEA', 'ADS#YEN'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Owns' },
      { n: 4, r: 0, c: 4, len: 3, clue: '"You ___ here"' },
      { n: 7, r: 1, c: 0, len: 3, clue: 'Loneliest number, in song' },
      { n: 8, r: 1, c: 4, len: 3, clue: 'Ladybug, for one' },
      { n: 9, r: 2, c: 0, len: 7, clue: 'Heads-up about danger' },
      { n: 11, r: 3, c: 2, len: 3, clue: 'Encyclopedia ___. (book abbr.)' },
      { n: 12, r: 4, c: 0, len: 7, clue: 'Wild West lawman with a badge' },
      { n: 16, r: 5, c: 0, len: 3, clue: 'Golf course standard' },
      { n: 17, r: 5, c: 4, len: 3, clue: 'Steeped hot drink' },
      { n: 18, r: 6, c: 0, len: 3, clue: 'Commercials, for short' },
      { n: 19, r: 6, c: 4, len: 3, clue: 'Currency in Tokyo' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: '"___ are you doing?"' },
      { n: 2, r: 0, c: 1, len: 3, clue: 'Actress de Armas' },
      { n: 3, r: 0, c: 2, len: 7, clue: 'Restaurant waitstaff' },
      { n: 4, r: 0, c: 4, len: 7, clue: 'Skill or talent' },
      { n: 5, r: 0, c: 5, len: 3, clue: 'Move faster than a walk' },
      { n: 6, r: 0, c: 6, len: 3, clue: 'Breakfast item you scramble' },
      { n: 10, r: 2, c: 3, len: 3, clue: 'Neither\'s partner' },
      { n: 12, r: 4, c: 0, len: 3, clue: 'Place for a mud bath' },
      { n: 13, r: 4, c: 1, len: 3, clue: 'Owned, in the past' },
      { n: 14, r: 4, c: 5, len: 3, clue: 'Charge for a service' },
      { n: 15, r: 4, c: 6, len: 3, clue: 'Cooling device on a hot day' },
    ],
  },
  {
    num: 26,
    quizId: 'emcee-8-10-26',
    live: '2026-08-10',
    dateLabel: 'August 10, 2026',
    sunday: false,
    size: 5,
    grid: ['ADS#R', 'CRIME', 'TOTAL', 'OPERA', 'R#SKY'],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: 'Magazine commercials' },
      { n: 5, r: 1, c: 0, len: 5, clue: 'Robbery or burglary' },
      { n: 7, r: 2, c: 0, len: 5, clue: 'Add up to' },
      { n: 8, r: 3, c: 0, len: 5, clue: 'Stage show full of arias' },
      { n: 9, r: 4, c: 2, len: 3, clue: 'Where the clouds drift' },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 5, clue: 'Movie cast member' },
      { n: 2, r: 0, c: 1, len: 4, clue: 'Let fall' },
      { n: 3, r: 0, c: 2, len: 5, clue: 'Building locations' },
      { n: 4, r: 0, c: 4, len: 5, clue: 'Track race with a baton' },
      { n: 6, r: 1, c: 3, len: 4, clue: 'Grade on a test' },
    ],
  },
  {
    num: 27,
    quizId: 'emcee-8-11-26',
    live: '2026-08-11',
    dateLabel: 'August 11, 2026',
    sunday: false,
    size: 5,
    grid: ["##DIM", "##ERA", "CREEP", "ROD##", "YES##"],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: "Switch from a higher to a lower beam" },
      { n: 4, r: 1, c: 2, len: 3, clue: "Major division of geological time" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Move slowly" },
      { n: 7, r: 3, c: 0, len: 3, clue: "Long thin implement made of metal or wood" },
      { n: 8, r: 4, c: 0, len: 3, clue: "Affirmative" },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: "Performance of moral or religious acts" },
      { n: 2, r: 0, c: 3, len: 3, clue: "Strong emotion" },
      { n: 3, r: 0, c: 4, len: 3, clue: "Diagrammatic representation of the earth's surface" },
      { n: 5, r: 2, c: 0, len: 3, clue: "Loud utterance" },
      { n: 6, r: 2, c: 1, len: 3, clue: "Fish eggs or egg-filled ovary" },
    ],
  },
  {
    num: 28,
    quizId: 'emcee-8-12-26',
    live: '2026-08-12',
    dateLabel: 'August 12, 2026',
    sunday: false,
    size: 5,
    grid: ["##SAY", "##ICE", "ACRES", "RUE##", "TEN##"],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: "Chance to speak" },
      { n: 4, r: 1, c: 2, len: 3, clue: "Decorate with frosting" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Extensive landed property retained by the owner for his own use" },
      { n: 7, r: 3, c: 0, len: 3, clue: "Feel remorse for" },
      { n: 8, r: 4, c: 0, len: 3, clue: "Being one more than nine" },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: "Woman who is considered to be dangerously seductive" },
      { n: 2, r: 0, c: 3, len: 3, clue: "Of the highest quality" },
      { n: 3, r: 0, c: 4, len: 3, clue: "Affirmative" },
      { n: 5, r: 2, c: 0, len: 3, clue: "Products of human creativity" },
      { n: 6, r: 2, c: 1, len: 3, clue: "Evidence that helps to solve a problem" },
    ],
  },
  {
    num: 29,
    quizId: 'emcee-8-13-26',
    live: '2026-08-13',
    dateLabel: 'August 13, 2026',
    sunday: false,
    size: 5,
    grid: ["#MISS", "#ANTI", "UNDER", "SLIP#", "EYES#"],
    across: [
      { n: 1, r: 0, c: 1, len: 4, clue: "Young female" },
      { n: 5, r: 1, c: 1, len: 4, clue: "Not in favor of" },
      { n: 6, r: 2, c: 0, len: 5, clue: "Located below or beneath something else" },
      { n: 7, r: 3, c: 0, len: 4, clue: "Move stealthily" },
      { n: 8, r: 4, c: 0, len: 4, clue: "Opinion or judgment" },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: "In a manful manner" },
      { n: 2, r: 0, c: 2, len: 5, clue: "Not affiliated with a major recording company" },
      { n: 3, r: 0, c: 3, len: 5, clue: "Course along which a person has walked or is walking in" },
      { n: 4, r: 0, c: 4, len: 3, clue: "Term of address for a man" },
      { n: 6, r: 2, c: 0, len: 3, clue: "Act of using" },
    ],
  },
  {
    num: 30,
    quizId: 'emcee-8-14-26',
    live: '2026-08-14',
    dateLabel: 'August 14, 2026',
    sunday: false,
    size: 5,
    grid: ["##LIT", "##ACE", "SPREE", "PEG##", "ATE##"],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: "Provided with artificial light" },
      { n: 4, r: 1, c: 2, len: 3, clue: "Of the highest quality" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Brief indulgence of your impulses" },
      { n: 7, r: 3, c: 0, len: 3, clue: "Succeed in obtaining a position" },
      { n: 8, r: 4, c: 0, len: 3, clue: "Goddess of criminal rashness and its punishment" },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: "At a distance, wide of something" },
      { n: 2, r: 0, c: 3, len: 3, clue: "Decorate with frosting" },
      { n: 3, r: 0, c: 4, len: 3, clue: "Starting place for each hole on a golf course" },
      { n: 5, r: 2, c: 0, len: 3, clue: "Health resort near a spring or at the seaside" },
      { n: 6, r: 2, c: 1, len: 3, clue: "Preferred above all others and treated with partiality" },
    ],
  },
  {
    num: 31,
    quizId: 'emcee-8-15-26',
    live: '2026-08-15',
    dateLabel: 'August 15, 2026',
    sunday: false,
    size: 5,
    grid: ["##WOO", "##EAR", "STARE", "PAR##", "ANY##"],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: "Seek someone's favor" },
      { n: 4, r: 1, c: 2, len: 3, clue: "Sense organ for hearing and equilibrium" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Fixed look with eyes open wide" },
      { n: 7, r: 3, c: 0, len: 3, clue: "State of being essentially equal or equivalent" },
      { n: 8, r: 4, c: 0, len: 3, clue: "One or some or every or all without specification" },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: "Physically and mentally fatigued" },
      { n: 2, r: 0, c: 3, len: 3, clue: "Implement used to propel or steer a boat" },
      { n: 3, r: 0, c: 4, len: 3, clue: "Monetary subunit in Denmark and Norway and Sweden" },
      { n: 5, r: 2, c: 0, len: 3, clue: "Health resort near a spring or at the seaside" },
      { n: 6, r: 2, c: 1, len: 3, clue: "Of a light yellowish-brown color" },
    ],
  },
  {
    num: 32,
    quizId: 'emcee-8-16-26',
    live: '2026-08-16',
    dateLabel: 'August 16, 2026',
    sunday: true,
    size: 7,
    grid: ["HUT#SPA", "ASH#PET", "TEENAGE", "##OUT##", "PARTIAL", "ICE#AGO", "GEM#LEG"],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Temporary military shelter" },
      { n: 4, r: 0, c: 4, len: 3, clue: "Health resort near a spring or at the seaside" },
      { n: 7, r: 1, c: 0, len: 3, clue: "Residue that remains when something is burned" },
      { n: 8, r: 1, c: 4, len: 3, clue: "Preferred above all others and treated with partiality" },
      { n: 9, r: 2, c: 0, len: 7, clue: "Being of the age 13 through 19" },
      { n: 11, r: 3, c: 2, len: 3, clue: "Away from home" },
      { n: 12, r: 4, c: 0, len: 7, clue: "Being or affecting only a part" },
      { n: 16, r: 5, c: 0, len: 3, clue: "Decorate with frosting" },
      { n: 17, r: 5, c: 4, len: 3, clue: "In the past" },
      { n: 18, r: 6, c: 0, len: 3, clue: "Art highly prized for its beauty or perfection" },
      { n: 19, r: 6, c: 4, len: 3, clue: "Human limb" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Headdress that protects the head from bad weather" },
      { n: 2, r: 0, c: 1, len: 3, clue: "Act of using" },
      { n: 3, r: 0, c: 2, len: 7, clue: "Proposition deducible from basic postulates" },
      { n: 4, r: 0, c: 4, len: 7, clue: "Pertaining to or involving or having the nature of space" },
      { n: 5, r: 0, c: 5, len: 3, clue: "Succeed in obtaining a position" },
      { n: 6, r: 0, c: 6, len: 3, clue: "Goddess of criminal rashness and its punishment" },
      { n: 10, r: 2, c: 3, len: 3, clue: "Usually large hard-shelled seed" },
      { n: 12, r: 4, c: 0, len: 3, clue: "Eat greedily" },
      { n: 13, r: 4, c: 1, len: 3, clue: "Of the highest quality" },
      { n: 14, r: 4, c: 5, len: 3, clue: "Begin to seem older" },
      { n: 15, r: 4, c: 6, len: 3, clue: "Cut lumber, as in woods and forests" },
    ],
  },
  {
    num: 33,
    quizId: 'emcee-8-17-26',
    live: '2026-08-17',
    dateLabel: 'August 17, 2026',
    sunday: false,
    size: 5,
    grid: ["##EGG", "MANOR", "ARENA", "TIMED", "HAY##"],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: "Oval reproductive body of a fowl used as food" },
      { n: 4, r: 1, c: 0, len: 5, clue: "Mansion of a lord or wealthy person" },
      { n: 6, r: 2, c: 0, len: 5, clue: "Particular environment or walk of life" },
      { n: 7, r: 3, c: 0, len: 5, clue: "Regularly spaced in time" },
      { n: 8, r: 4, c: 0, len: 3, clue: "Grass mowed and cured for use as fodder" },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: "Opposing military force" },
      { n: 2, r: 0, c: 3, len: 4, clue: "Well in the past" },
      { n: 3, r: 0, c: 4, len: 4, clue: "One-hundredth of a right angle" },
      { n: 4, r: 1, c: 0, len: 4, clue: "Science dealing with the logic of quantity and shape and arrangement" },
      { n: 5, r: 1, c: 1, len: 4, clue: "Elaborate song for solo voice" },
    ],
  },
  {
    num: 34,
    quizId: 'emcee-8-18-26',
    live: '2026-08-18',
    dateLabel: 'August 18, 2026',
    sunday: false,
    size: 5,
    grid: ["#CAR#", "FUMES", "ARISE", "RENEW", "#DOT#"],
    across: [
      { n: 1, r: 0, c: 1, len: 3, clue: "Motor vehicle with four wheels" },
      { n: 4, r: 1, c: 0, len: 5, clue: "Gases ejected from an engine as waste products" },
      { n: 6, r: 2, c: 0, len: 5, clue: "Come into existence" },
      { n: 7, r: 3, c: 0, len: 5, clue: "Cause to appear in a new form" },
      { n: 8, r: 4, c: 1, len: 3, clue: "Distribute loosely" },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: "Freed from illness or injury" },
      { n: 2, r: 0, c: 2, len: 5, clue: "Radical -NH2" },
      { n: 3, r: 0, c: 3, len: 5, clue: "Set anew" },
      { n: 4, r: 1, c: 0, len: 3, clue: "Located at a great distance in time or space or degree" },
      { n: 5, r: 1, c: 4, len: 3, clue: "Create with cloth" },
    ],
  },
  {
    num: 35,
    quizId: 'emcee-8-19-26',
    live: '2026-08-19',
    dateLabel: 'August 19, 2026',
    sunday: false,
    size: 5,
    grid: ["##IMP", "##CAR", "AMINO", "PUN##", "EGG##"],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: "Fairies that are somewhat mischievous" },
      { n: 4, r: 1, c: 2, len: 3, clue: "Motor vehicle with four wheels" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Radical -NH2" },
      { n: 7, r: 3, c: 0, len: 3, clue: "Make a play on words" },
      { n: 8, r: 4, c: 0, len: 3, clue: "Oval reproductive body of a fowl used as food" },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: "Formation of frost or ice on a surface" },
      { n: 2, r: 0, c: 3, len: 3, clue: "Take charge of a certain job" },
      { n: 3, r: 0, c: 4, len: 3, clue: "In favor of" },
      { n: 5, r: 2, c: 0, len: 3, clue: "Imitate uncritically and in every aspect" },
      { n: 6, r: 2, c: 1, len: 3, clue: "Rob at gunpoint or with the threat of violence" },
    ],
  },
  {
    num: 36,
    quizId: 'emcee-8-20-26',
    live: '2026-08-20',
    dateLabel: 'August 20, 2026',
    sunday: false,
    size: 5,
    grid: ["##NAG", "##ICE", "TWEET", "ARC##", "RYE##"],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: "Someone who annoys people by constantly finding fault" },
      { n: 4, r: 1, c: 2, len: 3, clue: "Decorate with frosting" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Weak chirping sound as of a small bird" },
      { n: 7, r: 3, c: 0, len: 3, clue: "Continuous portion of a circle" },
      { n: 8, r: 4, c: 0, len: 3, clue: "Seed of the cereal grass" },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: "Daughter of your brother or sister" },
      { n: 2, r: 0, c: 3, len: 3, clue: "Of the highest quality" },
      { n: 3, r: 0, c: 4, len: 3, clue: "Come into the possession of something concrete or abstract" },
      { n: 5, r: 2, c: 0, len: 3, clue: "Man who serves as a sailor" },
      { n: 6, r: 2, c: 1, len: 3, clue: "Humorously sarcastic or mocking" },
    ],
  },
  {
    num: 37,
    quizId: 'emcee-8-21-26',
    live: '2026-08-21',
    dateLabel: 'August 21, 2026',
    sunday: false,
    size: 5,
    grid: ["TOE##", "EATS#", "ETHIC", "#HERO", "##RED"],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: "One of the digits of the foot" },
      { n: 4, r: 1, c: 0, len: 4, clue: "Informal terms for a meal" },
      { n: 6, r: 2, c: 0, len: 5, clue: "System of principles governing morality and acceptable conduct" },
      { n: 8, r: 3, c: 1, len: 4, clue: "Man distinguished by exceptional courage and nobility and strength" },
      { n: 9, r: 4, c: 2, len: 3, clue: "Of a color at the end of the color spectrum" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Starting place for each hole on a golf course" },
      { n: 2, r: 0, c: 1, len: 4, clue: "Commitment to tell the truth" },
      { n: 3, r: 0, c: 2, len: 5, clue: "Fifth and highest element after air and earth and fire and water" },
      { n: 5, r: 1, c: 3, len: 4, clue: "Make by reproduction" },
      { n: 7, r: 2, c: 4, len: 3, clue: "Collecting the charges upon delivery" },
    ],
  },
  {
    num: 38,
    quizId: 'emcee-8-22-26',
    live: '2026-08-22',
    dateLabel: 'August 22, 2026',
    sunday: false,
    size: 5,
    grid: ["JET##", "ORE##", "TASTE", "##LAY", "##AXE"],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Of the blackest black" },
      { n: 4, r: 1, c: 0, len: 3, clue: "Monetary subunit in Denmark and Norway and Sweden" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Have flavor" },
      { n: 8, r: 3, c: 2, len: 3, clue: "Characteristic of those who are not members of the clergy" },
      { n: 9, r: 4, c: 2, len: 3, clue: "Edge tool with a heavy bladed head mounted across a handle" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Write briefly or hurriedly" },
      { n: 2, r: 0, c: 1, len: 3, clue: "Major division of geological time" },
      { n: 3, r: 0, c: 2, len: 5, clue: "Unit of magnetic flux density equal to one weber per square meter" },
      { n: 6, r: 2, c: 3, len: 3, clue: "Set or determine the amount of" },
      { n: 7, r: 2, c: 4, len: 3, clue: "Organ of sight" },
    ],
  },
  {
    num: 39,
    quizId: 'emcee-8-23-26',
    live: '2026-08-23',
    dateLabel: 'August 23, 2026',
    sunday: true,
    size: 7,
    grid: ["APE#TIP", "SIX#ROE", "HEADING", "##MEN##", "OPINION", "URN#TWO", "TOE#YET"],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Imitate uncritically and in every aspect" },
      { n: 4, r: 0, c: 4, len: 3, clue: "Extreme end of something" },
      { n: 7, r: 1, c: 0, len: 3, clue: "Cardinal number that is the sum of five and one" },
      { n: 8, r: 1, c: 4, len: 3, clue: "Fish eggs or egg-filled ovary" },
      { n: 9, r: 2, c: 0, len: 7, clue: "Line of text serving to indicate what the passage below it is about" },
      { n: 11, r: 3, c: 2, len: 3, clue: "Force of workers available" },
      { n: 12, r: 4, c: 0, len: 7, clue: "Message expressing a belief about something" },
      { n: 16, r: 5, c: 0, len: 3, clue: "Large vase that usually has a pedestal or feet" },
      { n: 17, r: 5, c: 4, len: 3, clue: "Being one more than one" },
      { n: 18, r: 6, c: 0, len: 3, clue: "One of the digits of the foot" },
      { n: 19, r: 6, c: 4, len: 3, clue: "Up to the present time" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Residue that remains when something is burned" },
      { n: 2, r: 0, c: 1, len: 3, clue: "Dish baked in pastry-lined pan often with a pastry top" },
      { n: 3, r: 0, c: 2, len: 7, clue: "Observe, check out, and look over carefully or inspect" },
      { n: 4, r: 0, c: 4, len: 7, clue: "Cardinal number that is the sum of one and one and one" },
      { n: 5, r: 0, c: 5, len: 3, clue: "Particle that is electrically charged" },
      { n: 6, r: 0, c: 6, len: 3, clue: "Succeed in obtaining a position" },
      { n: 10, r: 2, c: 3, len: 3, clue: "Habitation of wild animals" },
      { n: 12, r: 4, c: 0, len: 3, clue: "Away from home" },
      { n: 13, r: 4, c: 1, len: 3, clue: "In favor of" },
      { n: 14, r: 4, c: 5, len: 3, clue: "Be obliged to pay or repay" },
      { n: 15, r: 4, c: 6, len: 3, clue: "Negation of a word or group of words" },
    ],
  },
  {
    num: 40,
    quizId: 'emcee-8-24-26',
    live: '2026-08-24',
    dateLabel: 'August 24, 2026',
    sunday: false,
    size: 5,
    grid: ["TAN##", "EGO##", "NOISE", "##SEA", "##YET"],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Of a light yellowish-brown color" },
      { n: 4, r: 1, c: 0, len: 3, clue: "Inflated feeling of pride in your superiority to others" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Sound of any kind" },
      { n: 8, r: 3, c: 2, len: 3, clue: "Anything apparently limitless in quantity or volume" },
      { n: 9, r: 4, c: 2, len: 3, clue: "Up to the present time" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Being one more than nine" },
      { n: 2, r: 0, c: 1, len: 3, clue: "In the past" },
      { n: 3, r: 0, c: 2, len: 5, clue: "Full of or characterized by loud and nonmusical sounds" },
      { n: 6, r: 2, c: 3, len: 3, clue: "Seat within a bishop's diocese where his cathedral is located" },
      { n: 7, r: 2, c: 4, len: 3, clue: "Take in solid food" },
    ],
  },
  {
    num: 41,
    quizId: 'emcee-8-25-26',
    live: '2026-08-25',
    dateLabel: 'August 25, 2026',
    sunday: false,
    size: 5,
    grid: ["ADD##", "WEED#", "ELBOW", "#LIMO", "##TEE"],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Condition characterized by behavioral and learning disorders" },
      { n: 4, r: 1, c: 0, len: 4, clue: "Any plant that crowds out cultivated plants" },
      { n: 6, r: 2, c: 0, len: 5, clue: "Sharp bend in a road or river" },
      { n: 8, r: 3, c: 1, len: 4, clue: "Large luxurious car" },
      { n: 9, r: 4, c: 2, len: 3, clue: "Starting place for each hole on a golf course" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Overwhelming feeling of wonder or admiration" },
      { n: 2, r: 0, c: 1, len: 4, clue: "Small wooded hollow" },
      { n: 3, r: 0, c: 2, len: 5, clue: "Accounting entry acknowledging sums that are owing" },
      { n: 5, r: 1, c: 3, len: 4, clue: "Informal terms for a human head" },
      { n: 7, r: 2, c: 4, len: 3, clue: "Misery resulting from affliction" },
    ],
  },
  {
    num: 42,
    quizId: 'emcee-8-26-26',
    live: '2026-08-26',
    dateLabel: 'August 26, 2026',
    sunday: false,
    size: 5,
    grid: ["##MOB", "BRAVO", "RISEN", "ADORE", "TEN##"],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: "Press tightly together or cram" },
      { n: 4, r: 1, c: 0, len: 5, clue: "Cry of approval as from an audience at the end of great performance" },
      { n: 6, r: 2, c: 0, len: 5, clue: "Above the horizon" },
      { n: 7, r: 3, c: 0, len: 5, clue: "Love intensely" },
      { n: 8, r: 4, c: 0, len: 3, clue: "Being one more than nine" },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: "English film actor" },
      { n: 2, r: 0, c: 3, len: 4, clue: "Having come or been brought to a conclusion" },
      { n: 3, r: 0, c: 4, len: 4, clue: "Study intensively, as before an exam" },
      { n: 4, r: 1, c: 0, len: 4, clue: "Very troublesome child" },
      { n: 5, r: 1, c: 1, len: 4, clue: "Journey in a vehicle" },
    ],
  },
  {
    num: 43,
    quizId: 'emcee-8-27-26',
    live: '2026-08-27',
    dateLabel: 'August 27, 2026',
    sunday: false,
    size: 5,
    grid: ["##JAB", "##ERA", "SALTY", "ILL##", "PLY##"],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: "Poke or thrust abruptly" },
      { n: 4, r: 1, c: 2, len: 3, clue: "Major division of geological time" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Engagingly stimulating or provocative" },
      { n: 7, r: 3, c: 0, len: 3, clue: "In a poor or improper or unsatisfactory manner" },
      { n: 8, r: 4, c: 0, len: 3, clue: "Apply oneself diligently" },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: "Preserve made of the jelled juice of fruit" },
      { n: 2, r: 0, c: 3, len: 3, clue: "Products of human creativity" },
      { n: 3, r: 0, c: 4, len: 3, clue: "Of a moderate reddish-brown color" },
      { n: 5, r: 2, c: 0, len: 3, clue: "Small drink" },
      { n: 6, r: 2, c: 1, len: 3, clue: "To a complete degree or to the full or entire extent" },
    ],
  },
  {
    num: 44,
    quizId: 'emcee-8-28-26',
    live: '2026-08-28',
    dateLabel: 'August 28, 2026',
    sunday: false,
    size: 5,
    grid: ["RIM##", "ATOM#", "PERIL", "#MADE", "##LIT"],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Shape of a raised edge of a more or less circular object" },
      { n: 4, r: 1, c: 0, len: 4, clue: "Tiny piece of anything" },
      { n: 6, r: 2, c: 0, len: 5, clue: "Pose a threat to" },
      { n: 8, r: 3, c: 1, len: 4, clue: "Produced by a manufacturing process" },
      { n: 9, r: 4, c: 2, len: 3, clue: "Provided with artificial light" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Strike sharply" },
      { n: 2, r: 0, c: 1, len: 4, clue: "Small part that can be considered separately from the whole" },
      { n: 3, r: 0, c: 2, len: 5, clue: "Significance of a story or event" },
      { n: 5, r: 1, c: 3, len: 4, clue: "Used of women's clothing having a hemline at mid-calf" },
      { n: 7, r: 2, c: 4, len: 3, clue: "Serve that strikes the net before falling into the receiver's court" },
    ],
  },
  {
    num: 45,
    quizId: 'emcee-8-29-26',
    live: '2026-08-29',
    dateLabel: 'August 29, 2026',
    sunday: false,
    size: 5,
    grid: ["##BUT", "##ORE", "PLANE", "AIR##", "RED##"],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: "And nothing more" },
      { n: 4, r: 1, c: 2, len: 3, clue: "Monetary subunit in Denmark and Norway and Sweden" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Travel on the surface of water" },
      { n: 7, r: 3, c: 0, len: 3, clue: "Be broadcast" },
      { n: 8, r: 4, c: 0, len: 3, clue: "Of a color at the end of the color spectrum" },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: "Live and take one's meals at or in" },
      { n: 2, r: 0, c: 3, len: 3, clue: "Large vase that usually has a pedestal or feet" },
      { n: 3, r: 0, c: 4, len: 3, clue: "Starting place for each hole on a golf course" },
      { n: 5, r: 2, c: 0, len: 3, clue: "State of being essentially equal or equivalent" },
      { n: 6, r: 2, c: 1, len: 3, clue: "Statement that deviates from or perverts the truth" },
    ],
  },
  {
    num: 46,
    quizId: 'emcee-8-30-26',
    live: '2026-08-30',
    dateLabel: 'August 30, 2026',
    sunday: true,
    size: 7,
    grid: ["JAR#TWO", "ICE#OAR", "GESTURE", "##CAR##", "TOURIST", "OWE#SEE", "END#MAN"],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Vessel with a wide mouth and without handles" },
      { n: 4, r: 0, c: 4, len: 3, clue: "Being one more than one" },
      { n: 7, r: 1, c: 0, len: 3, clue: "Decorate with frosting" },
      { n: 8, r: 1, c: 4, len: 3, clue: "Implement used to propel or steer a boat" },
      { n: 9, r: 2, c: 0, len: 7, clue: "Show, express or direct through movement" },
      { n: 11, r: 3, c: 2, len: 3, clue: "Motor vehicle with four wheels" },
      { n: 12, r: 4, c: 0, len: 7, clue: "Someone who travels for pleasure" },
      { n: 16, r: 5, c: 0, len: 3, clue: "Be obliged to pay or repay" },
      { n: 17, r: 5, c: 4, len: 3, clue: "Seat within a bishop's diocese where his cathedral is located" },
      { n: 18, r: 6, c: 0, len: 3, clue: "Either extremity of something that has length" },
      { n: 19, r: 6, c: 4, len: 3, clue: "Take charge of a certain job" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Dance a quick dance with leaping and kicking motions" },
      { n: 2, r: 0, c: 1, len: 3, clue: "Of the highest quality" },
      { n: 3, r: 0, c: 2, len: 7, clue: "Delivered from danger" },
      { n: 4, r: 0, c: 4, len: 7, clue: "Business of providing services to tourists" },
      { n: 5, r: 0, c: 5, len: 3, clue: "Waging of armed conflict against an enemy" },
      { n: 6, r: 0, c: 6, len: 3, clue: "Monetary subunit in Denmark and Norway and Sweden" },
      { n: 10, r: 2, c: 3, len: 3, clue: "Man who serves as a sailor" },
      { n: 12, r: 4, c: 0, len: 3, clue: "One of the digits of the foot" },
      { n: 13, r: 4, c: 1, len: 3, clue: "Belonging to or on behalf of a specified person" },
      { n: 14, r: 4, c: 5, len: 3, clue: "Anything apparently limitless in quantity or volume" },
      { n: 15, r: 4, c: 6, len: 3, clue: "Being one more than nine" },
    ],
  },
  {
    num: 47,
    quizId: 'emcee-8-31-26',
    live: '2026-08-31',
    dateLabel: 'August 31, 2026',
    sunday: false,
    size: 5,
    grid: ["POT##", "EAR##", "WRATH", "##SEA", "##HEM"],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Plumbing fixture for defecation and urination" },
      { n: 4, r: 1, c: 0, len: 3, clue: "Sense organ for hearing and equilibrium" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Intense anger" },
      { n: 8, r: 3, c: 2, len: 3, clue: "Anything apparently limitless in quantity or volume" },
      { n: 9, r: 4, c: 2, len: 3, clue: "Edge of a piece of cloth" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Long bench with backs" },
      { n: 2, r: 0, c: 1, len: 3, clue: "Implement used to propel or steer a boat" },
      { n: 3, r: 0, c: 2, len: 5, clue: "Dispose of" },
      { n: 6, r: 2, c: 3, len: 3, clue: "Starting place for each hole on a golf course" },
      { n: 7, r: 2, c: 4, len: 3, clue: "Exaggerate one's acting" },
    ],
  },
  {
    num: 48,
    quizId: 'emcee-9-1-26',
    live: '2026-09-01',
    dateLabel: 'September 1, 2026',
    sunday: false,
    size: 5,
    grid: ["ODE##", "NOT##", "ETHOS", "##ERA", "##RED"],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Lyric poem with complex stanza forms" },
      { n: 4, r: 1, c: 0, len: 3, clue: "Negation of a word or group of words" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Distinctive spirit of a culture or an era" },
      { n: 8, r: 3, c: 2, len: 3, clue: "Major division of geological time" },
      { n: 9, r: 4, c: 2, len: 3, clue: "Of a color at the end of the color spectrum" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Smallest whole number or a numeral representing this number" },
      { n: 2, r: 0, c: 1, len: 3, clue: "Distribute loosely" },
      { n: 3, r: 0, c: 2, len: 5, clue: "Fifth and highest element after air and earth and fire and water" },
      { n: 6, r: 2, c: 3, len: 3, clue: "Monetary subunit in Denmark and Norway and Sweden" },
      { n: 7, r: 2, c: 4, len: 3, clue: "Experiencing or showing sorrow or unhappiness" },
    ],
  },
  {
    num: 49,
    quizId: 'emcee-9-2-26',
    live: '2026-09-02',
    dateLabel: 'September 2, 2026',
    sunday: false,
    size: 5,
    grid: ["BUT##", "ANON#", "TITAN", "#TAME", "##LET"],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: "And nothing more" },
      { n: 4, r: 1, c: 0, len: 4, clue: "At another time" },
      { n: 6, r: 2, c: 0, len: 5, clue: "Person of exceptional importance and reputation" },
      { n: 8, r: 3, c: 1, len: 4, clue: "Flat and uninspiring" },
      { n: 9, r: 4, c: 2, len: 3, clue: "Serve that strikes the net before falling into the receiver's court" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Wink briefly" },
      { n: 2, r: 0, c: 1, len: 4, clue: "Organization regarded as part of a larger social group" },
      { n: 3, r: 0, c: 2, len: 5, clue: "Constituting the full quantity or extent" },
      { n: 5, r: 1, c: 3, len: 4, clue: "Language unit by which a person or thing is known" },
      { n: 7, r: 2, c: 4, len: 3, clue: "Remaining after all deductions" },
    ],
  },
  {
    num: 50,
    quizId: 'emcee-9-3-26',
    live: '2026-09-03',
    dateLabel: 'September 3, 2026',
    sunday: false,
    size: 5,
    grid: ["#PEN#", "CORAL", "AWAKE", "RESET", "#RED#"],
    across: [
      { n: 1, r: 0, c: 1, len: 3, clue: "Produce a literary work" },
      { n: 4, r: 1, c: 0, len: 5, clue: "Of a strong pink to yellowish-pink color" },
      { n: 6, r: 2, c: 0, len: 5, clue: "Stop sleeping" },
      { n: 7, r: 3, c: 0, len: 5, clue: "Set anew" },
      { n: 8, r: 4, c: 1, len: 3, clue: "Of a color at the end of the color spectrum" },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: "Possession of controlling influence" },
      { n: 2, r: 0, c: 2, len: 5, clue: "Remove from memory or existence" },
      { n: 3, r: 0, c: 3, len: 5, clue: "Completely unclothed" },
      { n: 4, r: 1, c: 0, len: 3, clue: "Motor vehicle with four wheels" },
      { n: 5, r: 1, c: 4, len: 3, clue: "Serve that strikes the net before falling into the receiver's court" },
    ],
  },
  {
    num: 51,
    quizId: 'emcee-9-4-26',
    live: '2026-09-04',
    dateLabel: 'September 4, 2026',
    sunday: false,
    size: 5,
    grid: ["##EAR", "##VIE", "AWARD", "COD##", "TOE##"],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: "Sense organ for hearing and equilibrium" },
      { n: 4, r: 1, c: 2, len: 3, clue: "Compete for something" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Give, especially as an honor or reward" },
      { n: 7, r: 3, c: 0, len: 3, clue: "Collecting the charges upon delivery" },
      { n: 8, r: 4, c: 0, len: 3, clue: "One of the digits of the foot" },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: "Avoid or try to avoid fulfilling, answering, or performing" },
      { n: 2, r: 0, c: 3, len: 3, clue: "Be broadcast" },
      { n: 3, r: 0, c: 4, len: 3, clue: "Of a color at the end of the color spectrum" },
      { n: 5, r: 2, c: 0, len: 3, clue: "Something that people do or cause to happen" },
      { n: 6, r: 2, c: 1, len: 3, clue: "Seek someone's favor" },
    ],
  },
  {
    num: 52,
    quizId: 'emcee-9-5-26',
    live: '2026-09-05',
    dateLabel: 'September 5, 2026',
    sunday: false,
    size: 5,
    grid: ["TEE##", "OATH#", "OTHER", "#SORE", "##SOD"],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Starting place for each hole on a golf course" },
      { n: 4, r: 1, c: 0, len: 4, clue: "Commitment to tell the truth" },
      { n: 6, r: 2, c: 0, len: 5, clue: "Not the same one or ones already mentioned or implied" },
      { n: 8, r: 3, c: 1, len: 4, clue: "Causing misery or pain or distress" },
      { n: 9, r: 4, c: 2, len: 3, clue: "Someone who engages in anal copulation" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "To a degree exceeding normal or proper limits" },
      { n: 2, r: 0, c: 1, len: 4, clue: "Informal terms for a meal" },
      { n: 3, r: 0, c: 2, len: 5, clue: "Distinctive spirit of a culture or an era" },
      { n: 5, r: 1, c: 3, len: 4, clue: "Man distinguished by exceptional courage and nobility and strength" },
      { n: 7, r: 2, c: 4, len: 3, clue: "Of a color at the end of the color spectrum" },
    ],
  },
  {
    num: 53,
    quizId: 'emcee-9-6-26',
    live: '2026-09-06',
    dateLabel: 'September 6, 2026',
    sunday: true,
    size: 7,
    grid: ["LAW#STY", "AGO#PIE", "PERHAPS", "##KIT##", "EDITION", "BIN#AWE", "BEG#LET"],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Collection of rules imposed by authority" },
      { n: 4, r: 0, c: 4, len: 3, clue: "Pen for swine" },
      { n: 7, r: 1, c: 0, len: 3, clue: "In the past" },
      { n: 8, r: 1, c: 4, len: 3, clue: "Dish baked in pastry-lined pan often with a pastry top" },
      { n: 9, r: 2, c: 0, len: 7, clue: "By chance" },
      { n: 11, r: 3, c: 2, len: 3, clue: "Supply with a set of articles or tools" },
      { n: 12, r: 4, c: 0, len: 7, clue: "Form in which a text is published" },
      { n: 16, r: 5, c: 0, len: 3, clue: "Container" },
      { n: 17, r: 5, c: 4, len: 3, clue: "Overwhelming feeling of wonder or admiration" },
      { n: 18, r: 6, c: 0, len: 3, clue: "Call upon in supplication" },
      { n: 19, r: 6, c: 4, len: 3, clue: "Serve that strikes the net before falling into the receiver's court" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Lie partly over or alongside of something or of one another" },
      { n: 2, r: 0, c: 1, len: 3, clue: "Begin to seem older" },
      { n: 3, r: 0, c: 2, len: 7, clue: "Adequate for practical use" },
      { n: 4, r: 0, c: 4, len: 7, clue: "Pertaining to or involving or having the nature of space" },
      { n: 5, r: 0, c: 5, len: 3, clue: "Extreme end of something" },
      { n: 6, r: 0, c: 6, len: 3, clue: "Affirmative" },
      { n: 10, r: 2, c: 3, len: 3, clue: "Successful stroke in an athletic contest" },
      { n: 12, r: 4, c: 0, len: 3, clue: "Gradual decline" },
      { n: 13, r: 4, c: 1, len: 3, clue: "Small cube with 1 to 6 spots on the six faces" },
      { n: 14, r: 4, c: 5, len: 3, clue: "Be obliged to pay or repay" },
      { n: 15, r: 4, c: 6, len: 3, clue: "Remaining after all deductions" },
    ],
  },
  {
    num: 54,
    quizId: 'emcee-9-7-26',
    live: '2026-09-07',
    dateLabel: 'September 7, 2026',
    sunday: false,
    size: 5,
    grid: ["##LEG", "ABIDE", "RANGE", "CREEK", "HEN##"],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: "Human limb" },
      { n: 4, r: 1, c: 0, len: 5, clue: "Put up with something or somebody unpleasant" },
      { n: 6, r: 2, c: 0, len: 5, clue: "Change or be different within limits" },
      { n: 7, r: 3, c: 0, len: 5, clue: "Natural stream of water smaller than a river" },
      { n: 8, r: 4, c: 0, len: 3, clue: "Adult female chicken" },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: "Fabric woven with fibers from the flax plant" },
      { n: 2, r: 0, c: 3, len: 4, clue: "Advance slowly, as if by inches" },
      { n: 3, r: 0, c: 4, len: 4, clue: "Carnival performer who does disgusting acts" },
      { n: 4, r: 1, c: 0, len: 4, clue: "Characteristic of those who treat others with condescension" },
      { n: 5, r: 1, c: 1, len: 4, clue: "Make public" },
    ],
  },
  {
    num: 55,
    quizId: 'emcee-9-8-26',
    live: '2026-09-08',
    dateLabel: 'September 8, 2026',
    sunday: false,
    size: 5,
    grid: ["WAN##", "ORE##", "OMEGA", "##DEN", "##STY"],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Become pale and sickly" },
      { n: 4, r: 1, c: 0, len: 3, clue: "Monetary subunit in Denmark and Norway and Sweden" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Ending of a series or sequence" },
      { n: 8, r: 3, c: 2, len: 3, clue: "Habitation of wild animals" },
      { n: 9, r: 4, c: 2, len: 3, clue: "Pen for swine" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Seek someone's favor" },
      { n: 2, r: 0, c: 1, len: 3, clue: "Prepare oneself for a military confrontation" },
      { n: 3, r: 0, c: 2, len: 5, clue: "In such a manner as could not be otherwise" },
      { n: 6, r: 2, c: 3, len: 3, clue: "Come into the possession of something concrete or abstract" },
      { n: 7, r: 2, c: 4, len: 3, clue: "One or some or every or all without specification" },
    ],
  },
  {
    num: 56,
    quizId: 'emcee-9-9-26',
    live: '2026-09-09',
    dateLabel: 'September 9, 2026',
    sunday: false,
    size: 5,
    grid: ["##PUN", "##ORE", "MOUNT", "OWN##", "BED##"],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: "Make a play on words" },
      { n: 4, r: 1, c: 2, len: 3, clue: "Monetary subunit in Denmark and Norway and Sweden" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Lightweight horse kept for riding only" },
      { n: 7, r: 3, c: 0, len: 3, clue: "Belonging to or on behalf of a specified person" },
      { n: 8, r: 4, c: 0, len: 3, clue: "Prepare for sleep" },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: "Hit hard with the hand, fist, or some heavy instrument" },
      { n: 2, r: 0, c: 3, len: 3, clue: "Large vase that usually has a pedestal or feet" },
      { n: 3, r: 0, c: 4, len: 3, clue: "Remaining after all deductions" },
      { n: 5, r: 2, c: 0, len: 3, clue: "Press tightly together or cram" },
      { n: 6, r: 2, c: 1, len: 3, clue: "Be obliged to pay or repay" },
    ],
  },
  {
    num: 57,
    quizId: 'emcee-9-10-26',
    live: '2026-09-10',
    dateLabel: 'September 10, 2026',
    sunday: false,
    size: 5,
    grid: ["#FEW#", "PERIL", "AWARE", "RESET", "#RED#"],
    across: [
      { n: 1, r: 0, c: 1, len: 3, clue: "Small elite group" },
      { n: 4, r: 1, c: 0, len: 5, clue: "Pose a threat to" },
      { n: 6, r: 2, c: 0, len: 5, clue: "Bearing in mind" },
      { n: 7, r: 3, c: 0, len: 5, clue: "Set anew" },
      { n: 8, r: 4, c: 1, len: 3, clue: "Of a color at the end of the color spectrum" },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: "Quantifier meaning a smaller number of" },
      { n: 2, r: 0, c: 2, len: 5, clue: "Remove from memory or existence" },
      { n: 3, r: 0, c: 3, len: 5, clue: "Tense with excitement and enthusiasm as from a rush of adrenaline" },
      { n: 4, r: 1, c: 0, len: 3, clue: "State of being essentially equal or equivalent" },
      { n: 5, r: 1, c: 4, len: 3, clue: "Serve that strikes the net before falling into the receiver's court" },
    ],
  },
  {
    num: 58,
    quizId: 'emcee-9-11-26',
    live: '2026-09-11',
    dateLabel: 'September 11, 2026',
    sunday: false,
    size: 5,
    grid: ["BAG##", "EGO##", "TOOTH", "##FEE", "##YEN"],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Bulge out" },
      { n: 4, r: 1, c: 0, len: 3, clue: "Inflated feeling of pride in your superiority to others" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Hard bonelike structures in the jaws of vertebrates" },
      { n: 8, r: 3, c: 2, len: 3, clue: "Fixed charge for a privilege or for professional services" },
      { n: 9, r: 4, c: 2, len: 3, clue: "Have a desire for something or someone who is not present" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Money risked on a gamble" },
      { n: 2, r: 0, c: 1, len: 3, clue: "In the past" },
      { n: 3, r: 0, c: 2, len: 5, clue: "Ludicrous, foolish" },
      { n: 6, r: 2, c: 3, len: 3, clue: "Starting place for each hole on a golf course" },
      { n: 7, r: 2, c: 4, len: 3, clue: "Adult female chicken" },
    ],
  },
  {
    num: 59,
    quizId: 'emcee-9-12-26',
    live: '2026-09-12',
    dateLabel: 'September 12, 2026',
    sunday: false,
    size: 5,
    grid: ["##GEM", "##RYE", "ALIEN", "GIN##", "ODD##"],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: "Art highly prized for its beauty or perfection" },
      { n: 4, r: 1, c: 2, len: 3, clue: "Seed of the cereal grass" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Transfer property or ownership" },
      { n: 7, r: 3, c: 0, len: 3, clue: "Trap with a snare" },
      { n: 8, r: 4, c: 0, len: 3, clue: "Not divisible by two" },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: "Grade of particle fineness to which a substance is ground" },
      { n: 2, r: 0, c: 3, len: 3, clue: "Organ of sight" },
      { n: 3, r: 0, c: 4, len: 3, clue: "Force of workers available" },
      { n: 5, r: 2, c: 0, len: 3, clue: "In the past" },
      { n: 6, r: 2, c: 1, len: 3, clue: "Headdress that protects the head from bad weather" },
    ],
  },
  {
    num: 60,
    quizId: 'emcee-9-13-26',
    live: '2026-09-13',
    dateLabel: 'September 13, 2026',
    sunday: true,
    size: 7,
    grid: ["SET#EBB", "OAR#DIE", "DRAWING", "##CAT##", "TRINITY", "ION#OWE", "PEG#NOT"],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: "On the point of or strongly disposed" },
      { n: 4, r: 0, c: 4, len: 3, clue: "Gradual decline" },
      { n: 7, r: 1, c: 0, len: 3, clue: "Implement used to propel or steer a boat" },
      { n: 8, r: 1, c: 4, len: 3, clue: "Small cube with 1 to 6 spots on the six faces" },
      { n: 9, r: 2, c: 0, len: 7, clue: "Representation of forms or objects on a surface by means of lines" },
      { n: 11, r: 3, c: 2, len: 3, clue: "Eject the contents of the stomach through the mouth" },
      { n: 12, r: 4, c: 0, len: 7, clue: "Cardinal number that is the sum of one and one and one" },
      { n: 16, r: 5, c: 0, len: 3, clue: "Particle that is electrically charged" },
      { n: 17, r: 5, c: 4, len: 3, clue: "Be obliged to pay or repay" },
      { n: 18, r: 6, c: 0, len: 3, clue: "Succeed in obtaining a position" },
      { n: 19, r: 6, c: 4, len: 3, clue: "Negation of a word or group of words" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Someone who engages in anal copulation" },
      { n: 2, r: 0, c: 1, len: 3, clue: "Sense organ for hearing and equilibrium" },
      { n: 3, r: 0, c: 2, len: 7, clue: "Act of drawing a plan or diagram or outline" },
      { n: 4, r: 0, c: 4, len: 7, clue: "Form in which a text is published" },
      { n: 5, r: 0, c: 5, len: 3, clue: "Container" },
      { n: 6, r: 0, c: 6, len: 3, clue: "Call upon in supplication" },
      { n: 10, r: 2, c: 3, len: 3, clue: "Become pale and sickly" },
      { n: 12, r: 4, c: 0, len: 3, clue: "Extreme end of something" },
      { n: 13, r: 4, c: 1, len: 3, clue: "Fish eggs or egg-filled ovary" },
      { n: 14, r: 4, c: 5, len: 3, clue: "Being one more than one" },
      { n: 15, r: 4, c: 6, len: 3, clue: "Up to the present time" },
    ],
  },
  {
    num: 61,
    quizId: 'emcee-9-14-26',
    live: '2026-09-14',
    dateLabel: 'September 14, 2026',
    sunday: false,
    size: 5,
    grid: ["#BUD#", "RELIC", "ALTAR", "WORRY", "#WAY#"],
    across: [
      { n: 1, r: 0, c: 1, len: 3, clue: "Start to grow or develop" },
      { n: 4, r: 1, c: 0, len: 5, clue: "Antiquity that has survived from the distant past" },
      { n: 6, r: 2, c: 0, len: 5, clue: "Table in Christian churches where communion is given" },
      { n: 7, r: 3, c: 0, len: 5, clue: "Something or someone that causes anxiety" },
      { n: 8, r: 4, c: 1, len: 3, clue: "To a great degree or by a great distance" },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: "In or to a place that is lower" },
      { n: 2, r: 0, c: 2, len: 5, clue: "Far beyond the norm" },
      { n: 3, r: 0, c: 3, len: 5, clue: "Daily written record of experiences and observations" },
      { n: 4, r: 1, c: 0, len: 3, clue: "Informal terms for nakedness" },
      { n: 5, r: 1, c: 4, len: 3, clue: "Loud utterance" },
    ],
  },
  {
    num: 62,
    quizId: 'emcee-9-15-26',
    live: '2026-09-15',
    dateLabel: 'September 15, 2026',
    sunday: false,
    size: 5,
    grid: ["##LAW", "#FAIR", "HARDY", "URGE#", "TEE##"],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: "Collection of rules imposed by authority" },
      { n: 4, r: 1, c: 1, len: 4, clue: "Join so that the external surfaces blend smoothly" },
      { n: 5, r: 2, c: 0, len: 5, clue: "English novelist and poet" },
      { n: 6, r: 3, c: 0, len: 4, clue: "Instinctive motive" },
      { n: 7, r: 4, c: 0, len: 3, clue: "Starting place for each hole on a golf course" },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: "At a distance, wide of something" },
      { n: 2, r: 0, c: 3, len: 4, clue: "Officer who acts as military assistant to a more senior officer" },
      { n: 3, r: 0, c: 4, len: 3, clue: "Humorously sarcastic or mocking" },
      { n: 4, r: 1, c: 1, len: 4, clue: "Proceed or get along" },
      { n: 5, r: 2, c: 0, len: 3, clue: "Temporary military shelter" },
    ],
  },
  {
    num: 63,
    quizId: 'emcee-9-16-26',
    live: '2026-09-16',
    dateLabel: 'September 16, 2026',
    sunday: false,
    size: 5,
    grid: ["##TOY", "#TIRE", "TITAN", "WELL#", "ODE##"],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: "Behave carelessly or indifferently" },
      { n: 4, r: 1, c: 1, len: 4, clue: "Hoop that covers a wheel" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Person of exceptional importance and reputation" },
      { n: 6, r: 3, c: 0, len: 4, clue: "Come up, as of a liquid" },
      { n: 7, r: 4, c: 0, len: 3, clue: "Lyric poem with complex stanza forms" },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: "Designate by an identifying term" },
      { n: 2, r: 0, c: 3, len: 4, clue: "Examination conducted by spoken communication" },
      { n: 3, r: 0, c: 4, len: 3, clue: "Have a desire for something or someone who is not present" },
      { n: 4, r: 1, c: 1, len: 4, clue: "Bound or secured closely" },
      { n: 5, r: 2, c: 0, len: 3, clue: "Being one more than one" },
    ],
  },
  {
    num: 64,
    quizId: 'emcee-9-17-26',
    live: '2026-09-17',
    dateLabel: 'September 17, 2026',
    sunday: false,
    size: 5,
    grid: ["##BIN", "##ROE", "SCENT", "PAN##", "ART##"],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: "Container" },
      { n: 4, r: 1, c: 2, len: 3, clue: "Fish eggs or egg-filled ovary" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Cause to smell or be smelly" },
      { n: 7, r: 3, c: 0, len: 3, clue: "Make a sweeping movement" },
      { n: 8, r: 4, c: 0, len: 3, clue: "Products of human creativity" },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: "Small dark geese that breed in the north and migrate southward" },
      { n: 2, r: 0, c: 3, len: 3, clue: "Particle that is electrically charged" },
      { n: 3, r: 0, c: 4, len: 3, clue: "Remaining after all deductions" },
      { n: 5, r: 2, c: 0, len: 3, clue: "Health resort near a spring or at the seaside" },
      { n: 6, r: 2, c: 1, len: 3, clue: "Motor vehicle with four wheels" },
    ],
  },
  {
    num: 65,
    quizId: 'emcee-9-18-26',
    live: '2026-09-18',
    dateLabel: 'September 18, 2026',
    sunday: false,
    size: 5,
    grid: ["ZAP##", "ILL##", "PLATE", "##ION", "##NOD"],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Strike suddenly and with force" },
      { n: 4, r: 1, c: 0, len: 3, clue: "In a poor or improper or unsatisfactory manner" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Coat with a layer of metal" },
      { n: 8, r: 3, c: 2, len: 3, clue: "Particle that is electrically charged" },
      { n: 9, r: 4, c: 2, len: 3, clue: "Sign of assent or salutation or command" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Move very fast" },
      { n: 2, r: 0, c: 1, len: 3, clue: "To a complete degree or to the full or entire extent" },
      { n: 3, r: 0, c: 2, len: 5, clue: "Express complaints, discontent, displeasure, or unhappiness" },
      { n: 6, r: 2, c: 3, len: 3, clue: "To a degree exceeding normal or proper limits" },
      { n: 7, r: 2, c: 4, len: 3, clue: "Either extremity of something that has length" },
    ],
  },
  {
    num: 66,
    quizId: 'emcee-9-19-26',
    live: '2026-09-19',
    dateLabel: 'September 19, 2026',
    sunday: false,
    size: 5,
    grid: ["TAG##", "ILL##", "CLOSE", "##SEA", "##SET"],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Small piece of cloth or paper" },
      { n: 4, r: 1, c: 0, len: 3, clue: "In a poor or improper or unsatisfactory manner" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Near in time or place or relationship" },
      { n: 8, r: 3, c: 2, len: 3, clue: "Anything apparently limitless in quantity or volume" },
      { n: 9, r: 4, c: 2, len: 3, clue: "On the point of or strongly disposed" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Local and habitual twitching especially in the face" },
      { n: 2, r: 0, c: 1, len: 3, clue: "To a complete degree or to the full or entire extent" },
      { n: 3, r: 0, c: 2, len: 5, clue: "Provide interlinear explanations for words or phrases" },
      { n: 6, r: 2, c: 3, len: 3, clue: "Seat within a bishop's diocese where his cathedral is located" },
      { n: 7, r: 2, c: 4, len: 3, clue: "Take in solid food" },
    ],
  },
  {
    num: 67,
    quizId: 'emcee-9-20-26',
    live: '2026-09-20',
    dateLabel: 'September 20, 2026',
    sunday: true,
    size: 7,
    grid: ["USE#CAP", "RUM#AGE", "NEUTRON", "##LID##", "PIANIST", "ROT#AIR", "ONE#CRY"],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Act of using" },
      { n: 4, r: 0, c: 4, len: 3, clue: "Lie at the top of" },
      { n: 7, r: 1, c: 0, len: 3, clue: "Beyond or deviating from the usual or expected" },
      { n: 8, r: 1, c: 4, len: 3, clue: "Begin to seem older" },
      { n: 9, r: 2, c: 0, len: 7, clue: "Elementary particle with 0 charge and mass about equal to a proton" },
      { n: 11, r: 3, c: 2, len: 3, clue: "Headdress that protects the head from bad weather" },
      { n: 12, r: 4, c: 0, len: 7, clue: "Person who plays the piano" },
      { n: 16, r: 5, c: 0, len: 3, clue: "Break down" },
      { n: 17, r: 5, c: 4, len: 3, clue: "Be broadcast" },
      { n: 18, r: 6, c: 0, len: 3, clue: "Smallest whole number or a numeral representing this number" },
      { n: 19, r: 6, c: 4, len: 3, clue: "Loud utterance" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Large vase that usually has a pedestal or feet" },
      { n: 2, r: 0, c: 1, len: 3, clue: "Institute legal proceedings against" },
      { n: 3, r: 0, c: 2, len: 7, clue: "Strive to equal or match, especially by imitating" },
      { n: 4, r: 0, c: 4, len: 7, clue: "Of or relating to the heart" },
      { n: 5, r: 0, c: 5, len: 3, clue: "In the past" },
      { n: 6, r: 0, c: 6, len: 3, clue: "Produce a literary work" },
      { n: 10, r: 2, c: 3, len: 3, clue: "Silvery malleable metallic element that resists corrosion" },
      { n: 12, r: 4, c: 0, len: 3, clue: "In favor of" },
      { n: 13, r: 4, c: 1, len: 3, clue: "Particle that is electrically charged" },
      { n: 14, r: 4, c: 5, len: 3, clue: "Term of address for a man" },
      { n: 15, r: 4, c: 6, len: 3, clue: "Make an effort or attempt" },
    ],
  },
  {
    num: 68,
    quizId: 'emcee-9-21-26',
    live: '2026-09-21',
    dateLabel: 'September 21, 2026',
    sunday: false,
    size: 5,
    grid: ["RAT##", "EGO##", "DENIM", "##ERA", "##DEN"],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Someone who works during a strike" },
      { n: 4, r: 1, c: 0, len: 3, clue: "Inflated feeling of pride in your superiority to others" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Coarse durable twill-weave cotton fabric" },
      { n: 8, r: 3, c: 2, len: 3, clue: "Major division of geological time" },
      { n: 9, r: 4, c: 2, len: 3, clue: "Habitation of wild animals" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Of a color at the end of the color spectrum" },
      { n: 2, r: 0, c: 1, len: 3, clue: "Begin to seem older" },
      { n: 3, r: 0, c: 2, len: 5, clue: "Having or characterized or distinguished by tone or a specific tone" },
      { n: 6, r: 2, c: 3, len: 3, clue: "Strong emotion" },
      { n: 7, r: 2, c: 4, len: 3, clue: "Take charge of a certain job" },
    ],
  },
  {
    num: 69,
    quizId: 'emcee-9-22-26',
    live: '2026-09-22',
    dateLabel: 'September 22, 2026',
    sunday: false,
    size: 5,
    grid: ["#STEW", "#LIVE", "TIMED", "AMEN#", "BEST#"],
    across: [
      { n: 1, r: 0, c: 1, len: 4, clue: "Agitation resulting from active worry" },
      { n: 5, r: 1, c: 1, len: 4, clue: "Not recorded" },
      { n: 6, r: 2, c: 0, len: 5, clue: "Regularly spaced in time" },
      { n: 7, r: 3, c: 0, len: 4, clue: "Primeval Egyptian personification of air and breath" },
      { n: 8, r: 4, c: 0, len: 4, clue: "Get the better of" },
    ],
    down: [
      { n: 1, r: 0, c: 1, len: 5, clue: "Any thick, viscous matter" },
      { n: 2, r: 0, c: 2, len: 5, clue: "More or less definite period of time now or previously present" },
      { n: 3, r: 0, c: 3, len: 5, clue: "Something that happens at a given place and time" },
      { n: 4, r: 0, c: 4, len: 3, clue: "Having been taken in marriage" },
      { n: 6, r: 2, c: 0, len: 3, clue: "Bill in a restaurant" },
    ],
  },
  {
    num: 70,
    quizId: 'emcee-9-23-26',
    live: '2026-09-23',
    dateLabel: 'September 23, 2026',
    sunday: false,
    size: 5,
    grid: ["##PEW", "SPADE", "LARGE", "AIRED", "PRY##"],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: "Long bench with backs" },
      { n: 4, r: 1, c: 0, len: 5, clue: "Sturdy hand shovel that can be pushed into the earth with the foot" },
      { n: 6, r: 2, c: 0, len: 5, clue: "At a distance, wide of something" },
      { n: 7, r: 3, c: 0, len: 5, clue: "Open to or abounding in fresh air" },
      { n: 8, r: 4, c: 0, len: 3, clue: "Heavy iron lever with one end forged into a wedge" },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: "Return punch" },
      { n: 2, r: 0, c: 3, len: 4, clue: "Advance slowly, as if by inches" },
      { n: 3, r: 0, c: 4, len: 4, clue: "Any plant that crowds out cultivated plants" },
      { n: 4, r: 1, c: 0, len: 4, clue: "Directly" },
      { n: 5, r: 1, c: 1, len: 4, clue: "Set of two similar things considered as a unit" },
    ],
  },
  {
    num: 71,
    quizId: 'emcee-9-24-26',
    live: '2026-09-24',
    dateLabel: 'September 24, 2026',
    sunday: false,
    size: 5,
    grid: ["DOSE#", "ACHE#", "YEARS", "#ARIA", "#NEED"],
    across: [
      { n: 1, r: 0, c: 0, len: 4, clue: "Treat with an agent" },
      { n: 5, r: 1, c: 0, len: 4, clue: "Dull persistent pain" },
      { n: 6, r: 2, c: 0, len: 5, clue: "Late time of life" },
      { n: 8, r: 3, c: 1, len: 4, clue: "Elaborate song for solo voice" },
      { n: 9, r: 4, c: 1, len: 4, clue: "Require as useful, just, or proper" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Time for Earth to make a complete rotation on its axis" },
      { n: 2, r: 0, c: 1, len: 5, clue: "Large body of water constituting a principal part of the hydrosphere" },
      { n: 3, r: 0, c: 2, len: 5, clue: "Have in common" },
      { n: 4, r: 0, c: 3, len: 5, clue: "Suggestive of the supernatural" },
      { n: 7, r: 2, c: 4, len: 3, clue: "Experiencing or showing sorrow or unhappiness" },
    ],
  },
  {
    num: 72,
    quizId: 'emcee-9-25-26',
    live: '2026-09-25',
    dateLabel: 'September 25, 2026',
    sunday: false,
    size: 5,
    grid: ["##PIE", "##ANY", "SPIKE", "PAN##", "ART##"],
    across: [
      { n: 1, r: 0, c: 2, len: 3, clue: "Dish baked in pastry-lined pan often with a pastry top" },
      { n: 4, r: 1, c: 2, len: 3, clue: "One or some or every or all without specification" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Stand in the way of" },
      { n: 7, r: 3, c: 0, len: 3, clue: "Make a sweeping movement" },
      { n: 8, r: 4, c: 0, len: 3, clue: "Products of human creativity" },
    ],
    down: [
      { n: 1, r: 0, c: 2, len: 5, clue: "Apply a liquid to" },
      { n: 2, r: 0, c: 3, len: 3, clue: "Liquid used for printing or writing or drawing" },
      { n: 3, r: 0, c: 4, len: 3, clue: "Organ of sight" },
      { n: 5, r: 2, c: 0, len: 3, clue: "Health resort near a spring or at the seaside" },
      { n: 6, r: 2, c: 1, len: 3, clue: "State of being essentially equal or equivalent" },
    ],
  },
  {
    num: 73,
    quizId: 'emcee-9-26-26',
    live: '2026-09-26',
    dateLabel: 'September 26, 2026',
    sunday: false,
    size: 5,
    grid: ["BUT##", "ASH##", "REUSE", "##MUG", "##BEG"],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: "And nothing more" },
      { n: 4, r: 1, c: 0, len: 3, clue: "Residue that remains when something is burned" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Use again after processing" },
      { n: 8, r: 3, c: 2, len: 3, clue: "Rob at gunpoint or with the threat of violence" },
      { n: 9, r: 4, c: 2, len: 3, clue: "Call upon in supplication" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Prevent from entering" },
      { n: 2, r: 0, c: 1, len: 3, clue: "Act of using" },
      { n: 3, r: 0, c: 2, len: 5, clue: "Travel by getting free rides from motorists" },
      { n: 6, r: 2, c: 3, len: 3, clue: "Institute legal proceedings against" },
      { n: 7, r: 2, c: 4, len: 3, clue: "Oval reproductive body of a fowl used as food" },
    ],
  },
  {
    num: 74,
    quizId: 'emcee-9-27-26',
    live: '2026-09-27',
    dateLabel: 'September 27, 2026',
    sunday: true,
    size: 7,
    grid: ["HOP#SPA", "ERA#PIT", "MESSAGE", "##SIR##", "TWITTER", "ION#AGE", "PEG#NOD"],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Informal dance where popular music is played" },
      { n: 4, r: 0, c: 4, len: 3, clue: "Health resort near a spring or at the seaside" },
      { n: 7, r: 1, c: 0, len: 3, clue: "Major division of geological time" },
      { n: 8, r: 1, c: 4, len: 3, clue: "Set into opposition or rivalry" },
      { n: 9, r: 2, c: 0, len: 7, clue: "Communication that is written or spoken or signaled" },
      { n: 11, r: 3, c: 2, len: 3, clue: "Term of address for a man" },
      { n: 12, r: 4, c: 0, len: 7, clue: "Make high-pitched sounds, as of birds" },
      { n: 16, r: 5, c: 0, len: 3, clue: "Particle that is electrically charged" },
      { n: 17, r: 5, c: 4, len: 3, clue: "Begin to seem older" },
      { n: 18, r: 6, c: 0, len: 3, clue: "Succeed in obtaining a position" },
      { n: 19, r: 6, c: 4, len: 3, clue: "Sign of assent or salutation or command" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Edge of a piece of cloth" },
      { n: 2, r: 0, c: 1, len: 3, clue: "Monetary subunit in Denmark and Norway and Sweden" },
      { n: 3, r: 0, c: 2, len: 7, clue: "To an extraordinary degree" },
      { n: 4, r: 0, c: 4, len: 7, clue: "Resident of Sparta" },
      { n: 5, r: 0, c: 5, len: 3, clue: "Eat greedily" },
      { n: 6, r: 0, c: 6, len: 3, clue: "Goddess of criminal rashness and its punishment" },
      { n: 10, r: 2, c: 3, len: 3, clue: "Be seated" },
      { n: 12, r: 4, c: 0, len: 3, clue: "Extreme end of something" },
      { n: 13, r: 4, c: 1, len: 3, clue: "Misery resulting from affliction" },
      { n: 14, r: 4, c: 5, len: 3, clue: "Inflated feeling of pride in your superiority to others" },
      { n: 15, r: 4, c: 6, len: 3, clue: "Of a color at the end of the color spectrum" },
    ],
  },
  {
    num: 75,
    quizId: 'emcee-9-28-26',
    live: '2026-09-28',
    dateLabel: 'September 28, 2026',
    sunday: false,
    size: 5,
    grid: ["OLD##", "WARP#", "EMAIL", "#BIKE", "##NET"],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Past times" },
      { n: 4, r: 1, c: 0, len: 4, clue: "Make false by mutilation or addition" },
      { n: 6, r: 2, c: 0, len: 5, clue: "Communicate electronically on the computer" },
      { n: 8, r: 3, c: 1, len: 4, clue: "Ride a bicycle" },
      { n: 9, r: 4, c: 2, len: 3, clue: "Remaining after all deductions" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Be obliged to pay or repay" },
      { n: 2, r: 0, c: 1, len: 4, clue: "Young sheep" },
      { n: 3, r: 0, c: 2, len: 5, clue: "Flow off gradually" },
      { n: 5, r: 1, c: 3, len: 4, clue: "Broad highway designed for high-speed traffic" },
      { n: 7, r: 2, c: 4, len: 3, clue: "Serve that strikes the net before falling into the receiver's court" },
    ],
  },
  {
    num: 76,
    quizId: 'emcee-9-29-26',
    live: '2026-09-29',
    dateLabel: 'September 29, 2026',
    sunday: false,
    size: 5,
    grid: ["SAC##", "ERA##", "ACRES", "##RYE", "##YET"],
    across: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Enclosed space" },
      { n: 4, r: 1, c: 0, len: 3, clue: "Major division of geological time" },
      { n: 5, r: 2, c: 0, len: 5, clue: "Extensive landed property retained by the owner for his own use" },
      { n: 8, r: 3, c: 2, len: 3, clue: "Seed of the cereal grass" },
      { n: 9, r: 4, c: 2, len: 3, clue: "Up to the present time" },
    ],
    down: [
      { n: 1, r: 0, c: 0, len: 3, clue: "Anything apparently limitless in quantity or volume" },
      { n: 2, r: 0, c: 1, len: 3, clue: "Continuous portion of a circle" },
      { n: 3, r: 0, c: 2, len: 5, clue: "Have with oneself" },
      { n: 6, r: 2, c: 3, len: 3, clue: "Organ of sight" },
      { n: 7, r: 2, c: 4, len: 3, clue: "On the point of or strongly disposed" },
    ],
  },
];
