// Puzzle data for Alibi, the daily logic deduction game. Imported
// ONLY by the server page (app/alibi/page.js), which filters live<=today AND
// strips the solution before passing puzzles to the client (the client derives
// the unique solution from the clues with its own 4!^3 brute-force solver, so
// the answer never ships over the wire).
//
// Every puzzle was generated (seeded constraint solver: random solution ->
// pool of true clues -> greedy add until unique -> prune redundant) and then
// INDEPENDENTLY re-verified to have exactly one solution, with 8-11 clues.
// Validate with scripts/verify-alibi.mjs after ANY edit.
//
// Clue schema (indices into suspects/rooms/objects/times):
//   notRoom {s,r}   suspect s was never in room r
//   notObj  {s,o}   suspect s was not carrying object o
//   roomObj {r,o}   whoever was in room r carried object o
//   roomTime{r,t}   the guest in room r left at time t
//   before  {s1,s2} s1 left earlier than s2
//   beforeRoom {s,r} s left before the guest in room r (s not in r)
//   hasObj  {s,o}   suspect s carried object o
export const PUZZLES = [
  {
    num: 1, quizId: "alibi-7-18-26", live: "2026-07-18", dateLabel: "July 18, 2026", sunday: false,
    suspects: ["Hugo","Ambrose","Beatrix","Ingrid"],
    rooms: ["Greenhouse","Gallery","Kitchen","Library"],
    objects: ["ivory comb","empty vial","torn letter","brass key"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "the Marlowe Emerald",
    venue: "Thornfield Manor",
    clues: [
      {"type":"roomObj","r":2,"o":3},
      {"type":"beforeRoom","s":1,"r":0},
      {"type":"roomTime","r":3,"t":1},
      {"type":"notObj","s":3,"o":2},
      {"type":"notRoom","s":2,"r":0},
      {"type":"notObj","s":0,"o":2},
      {"type":"roomTime","r":2,"t":3},
      {"type":"notRoom","s":1,"r":3},
      {"type":"before","s1":0,"s2":3},
      {"type":"roomObj","r":1,"o":0},
    ],
    solution: {"room":[0,1,3,2],"time":[2,0,1,3],"obj":[1,0,2,3]},
  },
  {
    num: 2, quizId: "alibi-7-19-26", live: "2026-07-19", dateLabel: "July 19, 2026", sunday: false,
    suspects: ["Ingrid","Otto","Silas","Ambrose"],
    rooms: ["Gallery","Ballroom","Conservatory","Billiard Room"],
    objects: ["wax-sealed envelope","black umbrella","brass key","silver flask"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "a Stradivarius violin",
    venue: "Blackwood Hall",
    clues: [
      {"type":"before","s1":3,"s2":2},
      {"type":"roomTime","r":0,"t":3},
      {"type":"beforeRoom","s":0,"r":1},
      {"type":"notRoom","s":0,"r":2},
      {"type":"before","s1":1,"s2":0},
      {"type":"roomObj","r":3,"o":2},
      {"type":"roomObj","r":1,"o":0},
      {"type":"roomObj","r":0,"o":1},
    ],
    solution: {"room":[3,2,0,1],"time":[1,0,3,2],"obj":[2,3,1,0]},
  },
  {
    num: 3, quizId: "alibi-7-20-26", live: "2026-07-20", dateLabel: "July 20, 2026", sunday: false,
    suspects: ["Hugo","Ingrid","Minerva","Casper"],
    rooms: ["Observatory","Gallery","Billiard Room","Conservatory"],
    objects: ["torn letter","opera glasses","empty vial","ivory comb"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "the Duchess's will",
    venue: "the Grand Hotel Meridian",
    clues: [
      {"type":"roomTime","r":1,"t":1},
      {"type":"beforeRoom","s":2,"r":3},
      {"type":"roomTime","r":3,"t":3},
      {"type":"before","s1":1,"s2":2},
      {"type":"roomObj","r":3,"o":1},
      {"type":"notRoom","s":0,"r":2},
      {"type":"before","s1":0,"s2":3},
      {"type":"notRoom","s":0,"r":0},
      {"type":"notObj","s":2,"o":0},
      {"type":"roomObj","r":0,"o":0},
      {"type":"roomObj","r":1,"o":2},
    ],
    solution: {"room":[1,0,2,3],"time":[1,0,2,3],"obj":[2,0,3,1]},
  },
  {
    num: 4, quizId: "alibi-7-21-26", live: "2026-07-21", dateLabel: "July 21, 2026", sunday: false,
    suspects: ["Edmund","Leopold","Opal","Hugo"],
    rooms: ["Ballroom","Greenhouse","Gallery","Wine Cellar"],
    objects: ["ivory comb","brass key","black umbrella","wax-sealed envelope"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "a jeweled dagger",
    venue: "Ashcombe House",
    clues: [
      {"type":"notObj","s":3,"o":3},
      {"type":"beforeRoom","s":2,"r":2},
      {"type":"notObj","s":3,"o":0},
      {"type":"notObj","s":3,"o":1},
      {"type":"roomTime","r":3,"t":2},
      {"type":"notRoom","s":0,"r":2},
      {"type":"notObj","s":0,"o":3},
      {"type":"roomObj","r":2,"o":1},
      {"type":"roomObj","r":0,"o":2},
      {"type":"before","s1":1,"s2":3},
    ],
    solution: {"room":[3,2,1,0],"time":[2,1,0,3],"obj":[0,1,3,2]},
  },
  {
    num: 5, quizId: "alibi-7-22-26", live: "2026-07-22", dateLabel: "July 22, 2026", sunday: false,
    suspects: ["Hugo","Vera","Rufus","Leopold"],
    rooms: ["Kitchen","Study","Conservatory","Wine Cellar"],
    objects: ["wax-sealed envelope","pocket watch","black umbrella","muddy gloves"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "the deed to the estate",
    venue: "the Yacht Aurora",
    clues: [
      {"type":"roomObj","r":1,"o":3},
      {"type":"roomTime","r":2,"t":3},
      {"type":"roomObj","r":3,"o":2},
      {"type":"beforeRoom","s":3,"r":2},
      {"type":"beforeRoom","s":2,"r":0},
      {"type":"notRoom","s":2,"r":1},
      {"type":"before","s1":0,"s2":2},
      {"type":"roomObj","r":2,"o":1},
    ],
    solution: {"room":[1,2,3,0],"time":[0,3,1,2],"obj":[3,1,2,0]},
  },
  {
    num: 6, quizId: "alibi-7-23-26", live: "2026-07-23", dateLabel: "July 23, 2026", sunday: false,
    suspects: ["Vera","Cleo","Otto","Ambrose"],
    rooms: ["Gallery","Kitchen","Observatory","Billiard Room"],
    objects: ["ivory comb","muddy gloves","empty vial","pocket watch"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "the Admiral's ruby ring",
    venue: "Wexley Court",
    clues: [
      {"type":"notRoom","s":0,"r":3},
      {"type":"beforeRoom","s":2,"r":1},
      {"type":"notObj","s":0,"o":1},
      {"type":"roomObj","r":1,"o":2},
      {"type":"notObj","s":0,"o":0},
      {"type":"notRoom","s":2,"r":2},
      {"type":"notObj","s":2,"o":0},
      {"type":"beforeRoom","s":1,"r":0},
      {"type":"before","s1":0,"s2":2},
      {"type":"notRoom","s":0,"r":2},
    ],
    solution: {"room":[0,2,3,1],"time":[1,0,2,3],"obj":[3,0,1,2]},
  },
  {
    num: 7, quizId: "alibi-7-24-26", live: "2026-07-24", dateLabel: "July 24, 2026", sunday: false,
    suspects: ["Edmund","Ingrid","Cleo","Ambrose"],
    rooms: ["Study","Kitchen","Library","Conservatory"],
    objects: ["silver flask","ivory comb","empty vial","black umbrella"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "a case of rare stamps",
    venue: "the Pemberton Club",
    clues: [
      {"type":"beforeRoom","s":2,"r":2},
      {"type":"notRoom","s":0,"r":1},
      {"type":"notObj","s":2,"o":0},
      {"type":"before","s1":2,"s2":3},
      {"type":"notRoom","s":0,"r":3},
      {"type":"roomObj","r":1,"o":0},
      {"type":"roomObj","r":3,"o":2},
      {"type":"before","s1":0,"s2":2},
      {"type":"roomTime","r":1,"t":1},
      {"type":"roomObj","r":2,"o":3},
    ],
    solution: {"room":[0,1,3,2],"time":[0,1,2,3],"obj":[1,0,2,3]},
  },
  {
    num: 8, quizId: "alibi-7-25-26", live: "2026-07-25", dateLabel: "July 25, 2026", sunday: false,
    suspects: ["Casper","Vera","Freya","Otto"],
    rooms: ["Conservatory","Billiard Room","Wine Cellar","Greenhouse"],
    objects: ["torn letter","black umbrella","silver flask","ivory comb"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "the Countess's pearl choker",
    venue: "Larkspur Lodge",
    clues: [
      {"type":"beforeRoom","s":0,"r":1},
      {"type":"roomTime","r":2,"t":0},
      {"type":"roomObj","r":2,"o":0},
      {"type":"notRoom","s":3,"r":3},
      {"type":"notObj","s":2,"o":0},
      {"type":"roomTime","r":3,"t":3},
      {"type":"notRoom","s":2,"r":0},
      {"type":"notObj","s":2,"o":3},
      {"type":"before","s1":2,"s2":3},
      {"type":"roomObj","r":3,"o":1},
    ],
    solution: {"room":[2,3,1,0],"time":[0,3,1,2],"obj":[0,1,2,3]},
  },
  {
    // SUNDAY EDITION: five suspects instead of four (5 rooms, 5 times, 5 items,
    // 15 facts to confirm). Unique solution, reachable by pure propagation.
    num: 9, quizId: "alibi-7-26-26", live: "2026-07-26", dateLabel: "July 26, 2026", sunday: true,
    suspects: ["Beatrix","Casper","Leopold","Opal","Winifred"],
    rooms: ["Billiard Room","Library","Gallery","Ballroom","Conservatory"],
    objects: ["pocket watch","wax-sealed envelope","torn letter","silver flask","brass telescope key"],
    times: ["7 pm","8 pm","9 pm","10 pm","11 pm"],
    stolen: "an original Vermeer sketch",
    venue: "the Observatory at Dunmore",
    clues: [
      {"type":"notObj","s":1,"o":1},
      {"type":"roomTime","r":0,"t":2},
      {"type":"notObj","s":3,"o":1},
      {"type":"beforeRoom","s":1,"r":2},
      {"type":"hasObj","s":4,"o":3},
      {"type":"notObj","s":3,"o":4},
      {"type":"before","s1":2,"s2":3},
      {"type":"roomObj","r":3,"o":0},
      {"type":"beforeRoom","s":3,"r":4},
      {"type":"before","s1":3,"s2":1},
      {"type":"beforeRoom","s":2,"r":1},
      {"type":"roomObj","r":1,"o":3},
    ],
    solution: {"room":[2,4,3,0,1],"time":[4,3,0,2,1],"obj":[1,4,0,2,3]},
  },
  {
    num: 10, quizId: "alibi-7-27-26", live: "2026-07-27", dateLabel: "July 27, 2026", sunday: false,
    suspects: ["Beatrix","Rufus","Hugo","Freya"],
    rooms: ["Wine Cellar","Billiard Room","Greenhouse","Observatory"],
    objects: ["pocket watch","silver flask","empty vial","muddy gloves"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "the key to the vault",
    venue: "Hollybrook Abbey",
    clues: [
      {"type":"beforeRoom","s":0,"r":2},
      {"type":"roomObj","r":1,"o":2},
      {"type":"notRoom","s":1,"r":0},
      {"type":"beforeRoom","s":1,"r":1},
      {"type":"notObj","s":1,"o":3},
      {"type":"roomObj","r":2,"o":3},
      {"type":"before","s1":0,"s2":1},
      {"type":"roomObj","r":0,"o":0},
      {"type":"before","s1":3,"s2":1},
    ],
    solution: {"room":[0,3,1,2],"time":[0,2,3,1],"obj":[0,1,2,3]},
  },
  {
    num: 11, quizId: "alibi-7-28-26", live: "2026-07-28", dateLabel: "July 28, 2026", sunday: false,
    suspects: ["Silas","Leopold","Hugo","Vera"],
    rooms: ["Ballroom","Study","Gallery","Wine Cellar"],
    objects: ["torn letter","black umbrella","pocket watch","brass key"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "a first-edition folio",
    venue: "the Midnight Express",
    clues: [
      {"type":"roomObj","r":3,"o":3},
      {"type":"beforeRoom","s":0,"r":2},
      {"type":"notObj","s":2,"o":0},
      {"type":"beforeRoom","s":0,"r":3},
      {"type":"beforeRoom","s":1,"r":0},
      {"type":"notObj","s":1,"o":1},
      {"type":"beforeRoom","s":0,"r":0},
      {"type":"before","s1":2,"s2":3},
      {"type":"before","s1":1,"s2":2},
      {"type":"roomObj","r":0,"o":0},
      {"type":"roomObj","r":1,"o":2},
    ],
    solution: {"room":[1,3,2,0],"time":[0,1,2,3],"obj":[2,3,1,0]},
  },
  {
    num: 12, quizId: "alibi-7-29-26", live: "2026-07-29", dateLabel: "July 29, 2026", sunday: false,
    suspects: ["Minerva","Vera","Leopold","Cleo"],
    rooms: ["Gallery","Kitchen","Library","Greenhouse"],
    objects: ["empty vial","torn letter","silver flask","muddy gloves"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "the Baron's gold snuffbox",
    venue: "Ravenswood Estate",
    clues: [
      {"type":"roomObj","r":1,"o":0},
      {"type":"notRoom","s":2,"r":1},
      {"type":"beforeRoom","s":2,"r":3},
      {"type":"notObj","s":1,"o":2},
      {"type":"notObj","s":1,"o":3},
      {"type":"beforeRoom","s":1,"r":1},
      {"type":"roomObj","r":2,"o":2},
      {"type":"beforeRoom","s":3,"r":3},
      {"type":"roomTime","r":2,"t":1},
      {"type":"roomTime","r":3,"t":3},
    ],
    solution: {"room":[3,0,2,1],"time":[3,0,1,2],"obj":[3,1,2,0]},
  },
  {
    num: 13, quizId: "alibi-7-30-26", live: "2026-07-30", dateLabel: "July 30, 2026", sunday: false,
    suspects: ["Freya","Cleo","Silas","Casper"],
    rooms: ["Study","Wine Cellar","Kitchen","Gallery"],
    objects: ["black umbrella","torn letter","empty vial","wax-sealed envelope"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "a map to the family crypt",
    venue: "the Gilded Peacock Theatre",
    clues: [
      {"type":"notRoom","s":3,"r":0},
      {"type":"notRoom","s":3,"r":3},
      {"type":"roomObj","r":0,"o":1},
      {"type":"beforeRoom","s":0,"r":0},
      {"type":"roomObj","r":1,"o":3},
      {"type":"beforeRoom","s":0,"r":3},
      {"type":"notRoom","s":1,"r":0},
      {"type":"beforeRoom","s":3,"r":2},
      {"type":"before","s1":2,"s2":1},
      {"type":"notObj","s":1,"o":2},
    ],
    solution: {"room":[2,3,0,1],"time":[1,3,2,0],"obj":[2,0,1,3]},
  },
  {
    num: 14, quizId: "alibi-7-31-26", live: "2026-07-31", dateLabel: "July 31, 2026", sunday: false,
    suspects: ["Beatrix","Otto","Dorothea","Cleo"],
    rooms: ["Ballroom","Study","Observatory","Billiard Room"],
    objects: ["brass key","silver flask","torn letter","pocket watch"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "the opera house ledger",
    venue: "Foxglove Priory",
    clues: [
      {"type":"before","s1":3,"s2":1},
      {"type":"roomObj","r":2,"o":1},
      {"type":"beforeRoom","s":3,"r":3},
      {"type":"beforeRoom","s":2,"r":2},
      {"type":"before","s1":1,"s2":0},
      {"type":"roomTime","r":0,"t":1},
      {"type":"notObj","s":0,"o":2},
      {"type":"beforeRoom","s":2,"r":0},
      {"type":"notObj","s":2,"o":3},
      {"type":"notObj","s":3,"o":2},
      {"type":"notObj","s":2,"o":2},
    ],
    solution: {"room":[2,3,1,0],"time":[3,2,0,1],"obj":[1,2,0,3]},
  },
  {
    num: 15, quizId: "alibi-8-1-26", live: "2026-08-01", dateLabel: "August 1, 2026", sunday: false,
    suspects: ["Rosalind","Percival","Mathilda","Bartholomew"],
    rooms: ["Music Room","Smoking Room","Orangery","Boathouse"],
    objects: ["velvet mask","tarnished locket","riding crop","monogrammed handkerchief"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "the Ravensworth diamond tiara",
    venue: "Elderberry Grange",
    clues: [
      {"type":"hasObj","s":3,"o":2},
      {"type":"notRoom","s":0,"r":2},
      {"type":"notObj","s":0,"o":3},
      {"type":"before","s1":2,"s2":3},
      {"type":"notObj","s":1,"o":1},
      {"type":"roomTime","r":3,"t":3},
      {"type":"roomTime","r":2,"t":2},
      {"type":"roomObj","r":0,"o":2},
      {"type":"notRoom","s":2,"r":2},
      {"type":"notObj","s":1,"o":3},
    ],
    solution: {"room":[3,2,1,0],"time":[3,2,0,1],"obj":[1,0,3,2]},
  },
  {
    num: 16, quizId: "alibi-8-2-26", live: "2026-08-02", dateLabel: "August 2, 2026", sunday: true,
    suspects: ["Cordelia","Rupert","Genevieve","Alistair","Prudence"],
    rooms: ["Drawing Room","Wine Cellar","Turret","Chapel","Rose Garden"],
    objects: ["pearl brooch","silver candlestick","leather diary","jade figurine","crystal decanter"],
    times: ["7 pm","8 pm","9 pm","10 pm","11 pm"],
    stolen: "the Ashworth sapphire necklace",
    venue: "Ravenscar Abbey",
    clues: [
      {"type":"roomTime","r":3,"t":4},
      {"type":"hasObj","s":2,"o":2},
      {"type":"hasObj","s":3,"o":3},
      {"type":"beforeRoom","s":4,"r":1},
      {"type":"roomTime","r":2,"t":0},
      {"type":"beforeRoom","s":0,"r":4},
      {"type":"roomObj","r":0,"o":1},
      {"type":"roomTime","r":4,"t":2},
      {"type":"beforeRoom","s":3,"r":4},
      {"type":"roomObj","r":3,"o":4},
    ],
    solution: {"room":[0,3,1,2,4],"time":[1,4,3,0,2],"obj":[1,4,2,3,0]},
  },
  {
    num: 17, quizId: "alibi-8-3-26", live: "2026-08-03", dateLabel: "August 3, 2026", sunday: false,
    suspects: ["Lavinia","Cornelius","Winifred","Jasper"],
    rooms: ["Parlor","Armory","Solarium","Boat House"],
    objects: ["bronze medallion","folded map","feather quill","glass paperweight"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "the Vale family emerald ring",
    venue: "Hollowmere Court",
    clues: [
      {"type":"beforeRoom","s":0,"r":3},
      {"type":"beforeRoom","s":1,"r":1},
      {"type":"roomObj","r":2,"o":3},
      {"type":"roomTime","r":2,"t":0},
      {"type":"roomObj","r":3,"o":2},
      {"type":"roomTime","r":3,"t":1},
      {"type":"notObj","s":3,"o":0},
      {"type":"before","s1":2,"s2":1},
    ],
    solution: {"room":[2,0,3,1],"time":[0,2,1,3],"obj":[3,0,2,1]},
  },
  {
    num: 18, quizId: "alibi-8-4-26", live: "2026-08-04", dateLabel: "August 4, 2026", sunday: false,
    suspects: ["Evangeline","Cassius","Marguerite","Fenwick"],
    rooms: ["Conservatory","Billiard Room","Wine Cellar","Study"],
    objects: ["silver snuffbox","wax seal","pressed rose","opera glasses"],
    times: ["6 pm","7 pm","8 pm","9 pm"],
    stolen: "the Halloway ruby brooch",
    venue: "Wyndham Hall",
    clues: [
      {"type":"notObj","s":3,"o":1},
      {"type":"hasObj","s":2,"o":0},
      {"type":"roomObj","r":3,"o":2},
      {"type":"notRoom","s":0,"r":0},
      {"type":"roomTime","r":0,"t":2},
      {"type":"beforeRoom","s":1,"r":0},
      {"type":"notRoom","s":0,"r":3},
      {"type":"roomTime","r":1,"t":0},
      {"type":"notObj","s":3,"o":2},
      {"type":"roomObj","r":2,"o":3},
    ],
    solution: {"room":[1,3,0,2],"time":[0,1,2,3],"obj":[1,2,0,3]},
  },
  {
    num: 19, quizId: "alibi-8-5-26", live: "2026-08-05", dateLabel: "August 5, 2026", sunday: false,
    suspects: ["Octavia","Bertram","Seraphina","Montague"],
    rooms: ["Ballroom","Pantry","Observatory","Trophy Room"],
    objects: ["ivory fan","silk glove","brass compass","tortoiseshell comb"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "the Pemberton pearl choker",
    venue: "Blackwood House",
    clues: [
      {"type":"roomTime","r":0,"t":1},
      {"type":"roomObj","r":2,"o":1},
      {"type":"hasObj","s":0,"o":1},
      {"type":"beforeRoom","s":3,"r":1},
      {"type":"hasObj","s":2,"o":3},
      {"type":"notObj","s":1,"o":0},
      {"type":"beforeRoom","s":1,"r":0},
      {"type":"beforeRoom","s":0,"r":1},
    ],
    solution: {"room":[2,3,1,0],"time":[2,0,3,1],"obj":[1,2,3,0]},
  },
  {
    num: 20, quizId: "alibi-8-6-26", live: "2026-08-06", dateLabel: "August 6, 2026", sunday: false,
    suspects: ["Lucinda","Algernon","Rosamund","Horace"],
    rooms: ["Morning Room","Hunting Lodge","Cloister","Card Room"],
    objects: ["jet mourning ring","silver flask","folded telegram","peacock brooch"],
    times: ["6 pm","7 pm","8 pm","9 pm"],
    stolen: "the Fairfax gold pocket watch",
    venue: "Grimsby Grange",
    clues: [
      {"type":"beforeRoom","s":1,"r":2},
      {"type":"notRoom","s":1,"r":0},
      {"type":"notObj","s":3,"o":0},
      {"type":"roomObj","r":1,"o":1},
      {"type":"before","s1":2,"s2":1},
      {"type":"hasObj","s":2,"o":3},
      {"type":"roomObj","r":2,"o":2},
      {"type":"before","s1":3,"s2":2},
    ],
    solution: {"room":[2,3,0,1],"time":[3,2,1,0],"obj":[2,0,3,1]},
  },
  {
    num: 21, quizId: "alibi-8-7-26", live: "2026-08-07", dateLabel: "August 7, 2026", sunday: false,
    suspects: ["Arabella","Cuthbert","Philippa","Desmond"],
    rooms: ["Drawing Room","Scullery","Belvedere","Gun Room"],
    objects: ["lace handkerchief","ebony cane","silver thimble","crystal inkwell"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "the Wexford emerald cravat pin",
    venue: "Ashcombe Manor",
    clues: [
      {"type":"roomObj","r":1,"o":3},
      {"type":"notRoom","s":2,"r":2},
      {"type":"notRoom","s":1,"r":2},
      {"type":"roomObj","r":2,"o":1},
      {"type":"notObj","s":3,"o":2},
      {"type":"beforeRoom","s":1,"r":0},
      {"type":"notRoom","s":2,"r":1},
      {"type":"before","s1":2,"s2":1},
      {"type":"beforeRoom","s":0,"r":3},
    ],
    solution: {"room":[2,1,3,0],"time":[0,2,1,3],"obj":[1,3,2,0]},
  },
  {
    num: 22, quizId: "alibi-8-8-26", live: "2026-08-08", dateLabel: "August 8, 2026", sunday: false,
    suspects: ["Georgiana","Sebastian","Henrietta","Lucius"],
    rooms: ["Library","Aviary","Smoking Lounge","Boot Room"],
    objects: ["gilt hand mirror","leather glove","silver matchbox","jade seal"],
    times: ["6 pm","7 pm","8 pm","9 pm"],
    stolen: "the Ashby diamond stickpin",
    venue: "Foxglove Court",
    clues: [
      {"type":"before","s1":0,"s2":1},
      {"type":"hasObj","s":2,"o":2},
      {"type":"hasObj","s":0,"o":3},
      {"type":"roomTime","r":1,"t":3},
      {"type":"roomTime","r":0,"t":2},
      {"type":"hasObj","s":1,"o":1},
      {"type":"roomObj","r":0,"o":2},
      {"type":"roomObj","r":3,"o":1},
    ],
    solution: {"room":[2,3,0,1],"time":[0,1,2,3],"obj":[3,1,2,0]},
  },
  {
    num: 23, quizId: "alibi-8-9-26", live: "2026-08-09", dateLabel: "August 9, 2026", sunday: true,
    suspects: ["Wilhelmina","Thaddeus","Clementine","Florian","Isadora"],
    rooms: ["Grand Foyer","Wine Vault","Music Conservatory","Orangery","Widow's Walk"],
    objects: ["ruby hatpin","gold cigarette case","ivory letter opener","silver hip flask","enamel locket"],
    times: ["6 pm","7 pm","8 pm","9 pm","10 pm"],
    stolen: "the Montrose sapphire diadem",
    venue: "Ravenswood Hall",
    clues: [
      {"type":"beforeRoom","s":1,"r":0},
      {"type":"roomTime","r":2,"t":0},
      {"type":"beforeRoom","s":2,"r":0},
      {"type":"beforeRoom","s":3,"r":1},
      {"type":"notObj","s":1,"o":3},
      {"type":"roomObj","r":0,"o":4},
      {"type":"notObj","s":2,"o":2},
      {"type":"roomObj","r":3,"o":2},
      {"type":"hasObj","s":4,"o":1},
      {"type":"notObj","s":1,"o":2},
      {"type":"before","s1":0,"s2":2},
    ],
    solution: {"room":[3,2,4,0,1],"time":[1,0,2,3,4],"obj":[2,0,3,4,1]},
  },
  {
    num: 24, quizId: "alibi-8-10-26", live: "2026-08-10", dateLabel: "August 10, 2026", sunday: false,
    suspects: ["Beatrice","Leopold","Vivienne","Crispin"],
    rooms: ["Parlour","Ice House","Long Gallery","Servants' Hall"],
    objects: ["pearl hairpin","brass telescope","velvet pouch","silver cigarette holder"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "the Carrington jade signet",
    venue: "Thistledown Manor",
    clues: [
      {"type":"roomObj","r":0,"o":3},
      {"type":"notRoom","s":3,"r":2},
      {"type":"beforeRoom","s":1,"r":3},
      {"type":"notObj","s":3,"o":2},
      {"type":"beforeRoom","s":0,"r":0},
      {"type":"roomTime","r":1,"t":2},
      {"type":"beforeRoom","s":3,"r":0},
      {"type":"notRoom","s":3,"r":1},
      {"type":"roomObj","r":2,"o":1},
    ],
    solution: {"room":[1,2,0,3],"time":[2,0,3,1],"obj":[2,1,3,0]},
  },
  {
    num: 25, quizId: "alibi-8-11-26", live: "2026-08-11", dateLabel: "August 11, 2026", sunday: false,
    suspects: ["Odile","Cassius","Jasper","Yolanda"],
    rooms: ["Dairy","Dovecote","Cellar Stair","Stable Yard"],
    objects: ["vesta case","opera glasses","crystal scent bottle","chatelaine keys"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "the Ravensmoor emerald clasp",
    venue: "Ravensmoor Hall",
    clues: [
      {"type":"before","s1":0,"s2":2},
      {"type":"beforeRoom","s":2,"r":2},
      {"type":"notObj","s":3,"o":2},
      {"type":"roomTime","r":1,"t":0},
      {"type":"notObj","s":3,"o":1},
      {"type":"notObj","s":0,"o":1},
      {"type":"notRoom","s":2,"r":3},
      {"type":"roomObj","r":0,"o":3},
      {"type":"before","s1":1,"s2":2},
      {"type":"notRoom","s":1,"r":3},
    ],
    solution: {"room":[3,1,0,2],"time":[1,0,2,3],"obj":[2,1,3,0]},
  },
  {
    num: 26, quizId: "alibi-8-12-26", live: "2026-08-12", dateLabel: "August 12, 2026", sunday: false,
    suspects: ["Valentina","Lucian","Nathaniel","Dashiell"],
    rooms: ["Turret Study","Portrait Hall","Wine Vault","Sun Room"],
    objects: ["brass card case","riding crop","pearl stickpin","opera glasses"],
    times: ["6 pm","7 pm","8 pm","9 pm"],
    stolen: "the Coldharbour miniature",
    venue: "Coldharbour House",
    clues: [
      {"type":"before","s1":3,"s2":0},
      {"type":"roomTime","r":0,"t":3},
      {"type":"notRoom","s":2,"r":3},
      {"type":"roomTime","r":3,"t":0},
      {"type":"roomTime","r":2,"t":1},
      {"type":"notRoom","s":0,"r":1},
      {"type":"notObj","s":3,"o":1},
      {"type":"roomObj","r":3,"o":3},
      {"type":"notRoom","s":2,"r":2},
      {"type":"notRoom","s":3,"r":3},
      {"type":"roomObj","r":0,"o":2},
    ],
    solution: {"room":[0,3,1,2],"time":[3,0,2,1],"obj":[2,3,1,0]},
  },
  {
    num: 27, quizId: "alibi-8-13-26", live: "2026-08-13", dateLabel: "August 13, 2026", sunday: false,
    suspects: ["Roderick","Delphinia","Kitty","Florentine"],
    rooms: ["Linen Room","Belvedere","Map Room","Old Kitchen"],
    objects: ["coral bracelet","embroidered handkerchief","brass card case","silver snuff tin"],
    times: ["8 pm","9 pm","10 pm","11 pm"],
    stolen: "the Ellerby wedding pearls",
    venue: "Ellerby Grange",
    clues: [
      {"type":"notObj","s":0,"o":2},
      {"type":"notRoom","s":2,"r":0},
      {"type":"roomObj","r":2,"o":3},
      {"type":"hasObj","s":1,"o":0},
      {"type":"roomTime","r":1,"t":1},
      {"type":"roomTime","r":2,"t":3},
      {"type":"notObj","s":0,"o":3},
      {"type":"beforeRoom","s":0,"r":3},
      {"type":"roomObj","r":3,"o":0},
      {"type":"roomObj","r":1,"o":1},
    ],
    solution: {"room":[1,3,2,0],"time":[1,2,3,0],"obj":[1,0,3,2]},
  },
  {
    num: 28, quizId: "alibi-8-14-26", live: "2026-08-14", dateLabel: "August 14, 2026", sunday: false,
    suspects: ["Winston","Marguerite","Evangeline","Delphinia"],
    rooms: ["Scullery","Butler's Pantry","Gate Lodge","Boot Room"],
    objects: ["coral bracelet","vesta case","jet mourning brooch","opera glasses"],
    times: ["5 pm","6 pm","7 pm","8 pm"],
    stolen: "the Pentacre gold repeater",
    venue: "Pentacre Lodge",
    clues: [
      {"type":"beforeRoom","s":0,"r":2},
      {"type":"hasObj","s":0,"o":0},
      {"type":"notObj","s":3,"o":3},
      {"type":"roomObj","r":0,"o":2},
      {"type":"before","s1":1,"s2":0},
      {"type":"notRoom","s":3,"r":1},
      {"type":"roomObj","r":3,"o":0},
      {"type":"roomTime","r":1,"t":2},
    ],
    solution: {"room":[3,0,1,2],"time":[1,0,2,3],"obj":[0,2,3,1]},
  },
  {
    num: 29, quizId: "alibi-8-15-26", live: "2026-08-15", dateLabel: "August 15, 2026", sunday: false,
    suspects: ["Alaric","Odile","Imogen","Kitty"],
    rooms: ["Boat House","Cellar Stair","Belvedere","Portrait Hall"],
    objects: ["vesta case","gilt pocket mirror","jet mourning brooch","sealing wax stamp"],
    times: ["9 pm","10 pm","11 pm","midnight"],
    stolen: "the Marchbank altar cross",
    venue: "Marchbank Priory",
    clues: [
      {"type":"roomObj","r":1,"o":2},
      {"type":"notRoom","s":1,"r":1},
      {"type":"roomTime","r":3,"t":0},
      {"type":"beforeRoom","s":0,"r":1},
      {"type":"hasObj","s":3,"o":0},
      {"type":"roomObj","r":2,"o":0},
      {"type":"roomObj","r":3,"o":1},
      {"type":"before","s1":3,"s2":0},
    ],
    solution: {"room":[0,3,1,2],"time":[2,0,3,1],"obj":[3,1,2,0]},
  },
  {
    num: 30, quizId: "alibi-8-16-26", live: "2026-08-16", dateLabel: "August 16, 2026", sunday: true,
    suspects: ["Odile","Winston","Bertram","Delphinia","Marguerite"],
    rooms: ["Nursery","Gate Lodge","Dovecote","Butler's Pantry","Portrait Hall"],
    objects: ["jet mourning brooch","silver snuff tin","kid gloves","enamel compact","gilt pocket mirror"],
    times: ["5 pm","6 pm","7 pm","8 pm","9 pm"],
    stolen: "the Wraysholme sapphire ring",
    venue: "Wraysholme Court",
    clues: [
      {"type":"notObj","s":4,"o":2},
      {"type":"before","s1":2,"s2":1},
      {"type":"beforeRoom","s":0,"r":4},
      {"type":"roomTime","r":4,"t":2},
      {"type":"notObj","s":1,"o":0},
      {"type":"roomObj","r":4,"o":2},
      {"type":"hasObj","s":3,"o":1},
      {"type":"beforeRoom","s":4,"r":3},
      {"type":"roomObj","r":1,"o":4},
      {"type":"beforeRoom","s":3,"r":2},
      {"type":"beforeRoom","s":0,"r":0},
      {"type":"before","s1":3,"s2":2},
    ],
    solution: {"room":[1,3,4,0,2],"time":[0,4,2,1,3],"obj":[4,3,2,1,0]},
  },
  {
    num: 31, quizId: "alibi-8-17-26", live: "2026-08-17", dateLabel: "August 17, 2026", sunday: false,
    suspects: ["Evangeline","Odile","Jasper","Imogen"],
    rooms: ["Music Room","Nursery","Card Room","Dovecote"],
    objects: ["ebony fan","brass card case","ivory letter opener","beaded reticule"],
    times: ["6 pm","7 pm","8 pm","9 pm"],
    stolen: "the Netherby diamond aigrette",
    venue: "Netherby Park",
    clues: [
      {"type":"roomObj","r":1,"o":2},
      {"type":"roomObj","r":2,"o":1},
      {"type":"beforeRoom","s":1,"r":2},
      {"type":"hasObj","s":0,"o":0},
      {"type":"roomTime","r":2,"t":2},
      {"type":"beforeRoom","s":3,"r":3},
      {"type":"beforeRoom","s":1,"r":0},
      {"type":"notObj","s":2,"o":1},
      {"type":"before","s1":3,"s2":0},
    ],
    solution: {"room":[3,1,0,2],"time":[3,0,1,2],"obj":[0,2,3,1]},
  },
  {
    num: 32, quizId: "alibi-8-18-26", live: "2026-08-18", dateLabel: "August 18, 2026", sunday: false,
    suspects: ["Quintina","Marguerite","Alaric","Cassius"],
    rooms: ["Smoking Room","Map Room","Stable Yard","Wine Vault"],
    objects: ["walnut pipe","jet mourning brooch","vesta case","embroidered handkerchief"],
    times: ["8 pm","9 pm","10 pm","11 pm"],
    stolen: "the Salterton ruby drop",
    venue: "Salterton Hall",
    clues: [
      {"type":"notRoom","s":0,"r":2},
      {"type":"notObj","s":2,"o":2},
      {"type":"notObj","s":1,"o":0},
      {"type":"roomObj","r":2,"o":2},
      {"type":"notObj","s":1,"o":3},
      {"type":"before","s1":1,"s2":2},
      {"type":"beforeRoom","s":1,"r":2},
      {"type":"roomTime","r":0,"t":1},
      {"type":"before","s1":2,"s2":0},
      {"type":"roomTime","r":1,"t":3},
      {"type":"notObj","s":0,"o":0},
    ],
    solution: {"room":[1,3,0,2],"time":[3,0,1,2],"obj":[3,1,0,2]},
  },
  {
    num: 33, quizId: "alibi-8-19-26", live: "2026-08-19", dateLabel: "August 19, 2026", sunday: false,
    suspects: ["Roderick","Lucian","Phineas","Edmund"],
    rooms: ["Scullery","Chapel","Old Kitchen","Boot Room"],
    objects: ["tin of pastilles","monocle on a ribbon","vesta case","gilt pocket mirror"],
    times: ["5 pm","6 pm","7 pm","8 pm"],
    stolen: "the Kingsmere ivory netsuke",
    venue: "Kingsmere House",
    clues: [
      {"type":"hasObj","s":0,"o":1},
      {"type":"before","s1":2,"s2":3},
      {"type":"notRoom","s":2,"r":1},
      {"type":"before","s1":0,"s2":2},
      {"type":"hasObj","s":3,"o":2},
      {"type":"roomTime","r":3,"t":3},
      {"type":"roomTime","r":0,"t":0},
      {"type":"notObj","s":2,"o":3},
      {"type":"notRoom","s":0,"r":0},
    ],
    solution: {"room":[1,0,2,3],"time":[1,0,2,3],"obj":[1,3,0,2]},
  },
  {
    num: 34, quizId: "alibi-8-20-26", live: "2026-08-20", dateLabel: "August 20, 2026", sunday: false,
    suspects: ["Imogen","Georgiana","Roderick","Hamish"],
    rooms: ["Cellar Stair","Laundry","Winter Garden","Boot Room"],
    objects: ["ivory letter opener","gilt pocket mirror","tortoiseshell comb","chatelaine keys"],
    times: ["9 pm","10 pm","11 pm","midnight"],
    stolen: "the Fallowfield reliquary",
    venue: "Fallowfield Abbey",
    clues: [
      {"type":"notRoom","s":1,"r":2},
      {"type":"roomObj","r":3,"o":0},
      {"type":"beforeRoom","s":2,"r":1},
      {"type":"notRoom","s":0,"r":2},
      {"type":"beforeRoom","s":2,"r":2},
      {"type":"notObj","s":1,"o":2},
      {"type":"beforeRoom","s":1,"r":3},
      {"type":"before","s1":0,"s2":3},
      {"type":"hasObj","s":0,"o":3},
    ],
    solution: {"room":[1,0,3,2],"time":[2,0,1,3],"obj":[3,1,0,2]},
  },
  {
    num: 35, quizId: "alibi-8-21-26", live: "2026-08-21", dateLabel: "August 21, 2026", sunday: false,
    suspects: ["Roderick","Hamish","Quintina","Odile"],
    rooms: ["Music Room","Stable Yard","Winter Garden","Linen Room"],
    objects: ["tortoiseshell comb","silk parasol","vesta case","kid gloves"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "the Duncroft silver salver",
    venue: "Duncroft Manor",
    clues: [
      {"type":"hasObj","s":0,"o":1},
      {"type":"before","s1":1,"s2":2},
      {"type":"hasObj","s":2,"o":2},
      {"type":"roomTime","r":0,"t":3},
      {"type":"hasObj","s":1,"o":3},
      {"type":"before","s1":3,"s2":0},
      {"type":"beforeRoom","s":2,"r":2},
      {"type":"roomTime","r":1,"t":0},
    ],
    solution: {"room":[0,1,3,2],"time":[3,0,1,2],"obj":[1,3,2,0]},
  },
  {
    num: 36, quizId: "alibi-8-22-26", live: "2026-08-22", dateLabel: "August 22, 2026", sunday: false,
    suspects: ["Araminta","Georgiana","Winston","Kitty"],
    rooms: ["Orangery","Sun Room","Portrait Hall","Card Room"],
    objects: ["garnet cufflinks","monocle on a ribbon","jet mourning brooch","lacquer cigarette case"],
    times: ["6 pm","7 pm","8 pm","9 pm"],
    stolen: "the Whitethorn cameo",
    venue: "Whitethorn Place",
    clues: [
      {"type":"before","s1":1,"s2":2},
      {"type":"beforeRoom","s":1,"r":2},
      {"type":"before","s1":3,"s2":1},
      {"type":"notRoom","s":3,"r":3},
      {"type":"roomObj","r":0,"o":0},
      {"type":"beforeRoom","s":3,"r":0},
      {"type":"before","s1":2,"s2":0},
      {"type":"hasObj","s":1,"o":2},
      {"type":"notRoom","s":2,"r":2},
      {"type":"notObj","s":0,"o":1},
    ],
    solution: {"room":[2,3,0,1],"time":[3,1,2,0],"obj":[3,2,0,1]},
  },
  {
    num: 37, quizId: "alibi-8-23-26", live: "2026-08-23", dateLabel: "August 23, 2026", sunday: true,
    suspects: ["Ursuline","Imogen","Araminta","Valentina","Odile"],
    rooms: ["Dovecote","Laundry","Card Room","Wine Vault","Still Room"],
    objects: ["monocle on a ribbon","walnut pipe","riding crop","lacquer cigarette case","tin of pastilles"],
    times: ["6 pm","7 pm","8 pm","9 pm","10 pm"],
    stolen: "the Barrowden opal pendant",
    venue: "Barrowden Hall",
    clues: [
      {"type":"roomTime","r":1,"t":1},
      {"type":"roomTime","r":2,"t":4},
      {"type":"before","s1":2,"s2":4},
      {"type":"beforeRoom","s":0,"r":3},
      {"type":"hasObj","s":1,"o":4},
      {"type":"roomObj","r":3,"o":2},
      {"type":"beforeRoom","s":4,"r":4},
      {"type":"notObj","s":3,"o":3},
      {"type":"hasObj","s":0,"o":1},
      {"type":"notRoom","s":2,"r":1},
      {"type":"roomObj","r":4,"o":4},
    ],
    solution: {"room":[1,4,0,2,3],"time":[1,3,0,4,2],"obj":[1,4,3,0,2]},
  },
  {
    num: 38, quizId: "alibi-8-24-26", live: "2026-08-24", dateLabel: "August 24, 2026", sunday: false,
    suspects: ["Cassius","Roderick","Dashiell","Tobias"],
    rooms: ["Stable Yard","Belvedere","Winter Garden","Chapel"],
    objects: ["silk parasol","tin of pastilles","embroidered handkerchief","ebony fan"],
    times: ["5 pm","6 pm","7 pm","8 pm"],
    stolen: "the Ilverton snuffbox",
    venue: "Ilverton Court",
    clues: [
      {"type":"hasObj","s":2,"o":1},
      {"type":"beforeRoom","s":0,"r":3},
      {"type":"notRoom","s":0,"r":1},
      {"type":"notObj","s":0,"o":2},
      {"type":"hasObj","s":1,"o":3},
      {"type":"beforeRoom","s":3,"r":0},
      {"type":"beforeRoom","s":2,"r":1},
      {"type":"before","s1":2,"s2":0},
    ],
    solution: {"room":[0,3,2,1],"time":[2,3,0,1],"obj":[0,3,1,2]},
  },
  {
    num: 39, quizId: "alibi-8-25-26", live: "2026-08-25", dateLabel: "August 25, 2026", sunday: false,
    suspects: ["Seraphina","Phineas","Hamish","Ursuline"],
    rooms: ["Map Room","Gun Room","Old Kitchen","Cloister"],
    objects: ["tortoiseshell comb","walnut pipe","enamel compact","vesta case"],
    times: ["9 pm","10 pm","11 pm","midnight"],
    stolen: "the Stonegate seal ring",
    venue: "Stonegate House",
    clues: [
      {"type":"notObj","s":2,"o":2},
      {"type":"notRoom","s":0,"r":1},
      {"type":"roomTime","r":3,"t":2},
      {"type":"roomTime","r":0,"t":0},
      {"type":"beforeRoom","s":0,"r":3},
      {"type":"notObj","s":1,"o":2},
      {"type":"notObj","s":2,"o":3},
      {"type":"before","s1":3,"s2":1},
      {"type":"roomTime","r":2,"t":3},
      {"type":"roomObj","r":0,"o":0},
      {"type":"before","s1":2,"s2":3},
    ],
    solution: {"room":[0,2,1,3],"time":[0,3,1,2],"obj":[0,3,1,2]},
  },
  {
    num: 40, quizId: "alibi-8-26-26", live: "2026-08-26", dateLabel: "August 26, 2026", sunday: false,
    suspects: ["Blanche","Evangeline","Edmund","Florentine"],
    rooms: ["Linen Room","Winter Garden","Boot Room","Billiard Room"],
    objects: ["pearl stickpin","beaded reticule","tin of pastilles","riding crop"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "the Hartsmere jade bangle",
    venue: "Hartsmere Lodge",
    clues: [
      {"type":"notObj","s":2,"o":3},
      {"type":"beforeRoom","s":2,"r":2},
      {"type":"before","s1":1,"s2":3},
      {"type":"hasObj","s":0,"o":2},
      {"type":"roomObj","r":3,"o":2},
      {"type":"notObj","s":3,"o":3},
      {"type":"notRoom","s":1,"r":2},
      {"type":"before","s1":2,"s2":0},
      {"type":"notObj","s":3,"o":1},
      {"type":"beforeRoom","s":0,"r":0},
    ],
    solution: {"room":[3,0,1,2],"time":[1,2,0,3],"obj":[2,3,1,0]},
  },
  {
    num: 41, quizId: "alibi-8-27-26", live: "2026-08-27", dateLabel: "August 27, 2026", sunday: false,
    suspects: ["Hamish","Valentina","Bertram","Winston"],
    rooms: ["Butler's Pantry","Smoking Room","Scullery","Gate Lodge"],
    objects: ["monocle on a ribbon","ebony fan","beaded reticule","coral bracelet"],
    times: ["6 pm","7 pm","8 pm","9 pm"],
    stolen: "the Crowmarsh amber rosary",
    venue: "Crowmarsh Hall",
    clues: [
      {"type":"notRoom","s":2,"r":0},
      {"type":"roomObj","r":1,"o":2},
      {"type":"hasObj","s":1,"o":0},
      {"type":"roomObj","r":3,"o":3},
      {"type":"roomTime","r":0,"t":0},
      {"type":"roomTime","r":1,"t":3},
      {"type":"beforeRoom","s":0,"r":2},
      {"type":"beforeRoom","s":2,"r":2},
    ],
    solution: {"room":[0,2,3,1],"time":[0,2,1,3],"obj":[1,0,3,2]},
  },
  {
    num: 42, quizId: "alibi-8-28-26", live: "2026-08-28", dateLabel: "August 28, 2026", sunday: false,
    suspects: ["Valentina","Hamish","Bertram","Kitty"],
    rooms: ["Portrait Hall","Old Kitchen","Music Room","Belvedere"],
    objects: ["sealing wax stamp","brass card case","silver snuff tin","lacquer cigarette case"],
    times: ["8 pm","9 pm","10 pm","11 pm"],
    stolen: "the Vaneby topaz stud",
    venue: "Vaneby Grange",
    clues: [
      {"type":"roomTime","r":1,"t":2},
      {"type":"beforeRoom","s":0,"r":1},
      {"type":"hasObj","s":2,"o":1},
      {"type":"notRoom","s":2,"r":3},
      {"type":"beforeRoom","s":0,"r":2},
      {"type":"roomObj","r":1,"o":3},
      {"type":"before","s1":3,"s2":1},
      {"type":"roomTime","r":0,"t":0},
      {"type":"roomObj","r":2,"o":2},
    ],
    solution: {"room":[3,2,0,1],"time":[1,3,0,2],"obj":[0,2,1,3]},
  },
  {
    num: 43, quizId: "alibi-8-29-26", live: "2026-08-29", dateLabel: "August 29, 2026", sunday: false,
    suspects: ["Ursuline","Dashiell","Nathaniel","Delphinia"],
    rooms: ["Wine Vault","Billiard Room","Music Room","Gun Room"],
    objects: ["sealing wax stamp","tortoiseshell comb","kid gloves","embroidered handkerchief"],
    times: ["5 pm","6 pm","7 pm","8 pm"],
    stolen: "the Ashenden garnet tiara",
    venue: "Ashenden Park",
    clues: [
      {"type":"hasObj","s":2,"o":1},
      {"type":"before","s1":2,"s2":1},
      {"type":"notObj","s":0,"o":3},
      {"type":"beforeRoom","s":0,"r":3},
      {"type":"before","s1":1,"s2":3},
      {"type":"notObj","s":3,"o":3},
      {"type":"roomObj","r":2,"o":2},
      {"type":"notObj","s":3,"o":2},
      {"type":"roomObj","r":0,"o":0},
      {"type":"notRoom","s":2,"r":1},
    ],
    solution: {"room":[2,1,3,0],"time":[0,2,1,3],"obj":[2,3,1,0]},
  },
  {
    num: 44, quizId: "alibi-8-30-26", live: "2026-08-30", dateLabel: "August 30, 2026", sunday: true,
    suspects: ["Phineas","Imogen","Quintina","Fitzwilliam","Lucian"],
    rooms: ["Gate Lodge","Boat House","Belvedere","Music Room","Laundry"],
    objects: ["jet mourning brooch","tin of pastilles","kid gloves","embroidered handkerchief","lacquer cigarette case"],
    times: ["7 pm","8 pm","9 pm","10 pm","11 pm"],
    stolen: "the Lowther pearl choker",
    venue: "Lowther Priory",
    clues: [
      {"type":"roomTime","r":4,"t":4},
      {"type":"hasObj","s":2,"o":0},
      {"type":"roomObj","r":2,"o":0},
      {"type":"roomTime","r":3,"t":1},
      {"type":"hasObj","s":1,"o":2},
      {"type":"hasObj","s":0,"o":3},
      {"type":"notObj","s":4,"o":4},
      {"type":"beforeRoom","s":3,"r":3},
      {"type":"beforeRoom","s":1,"r":2},
      {"type":"roomObj","r":0,"o":3},
      {"type":"before","s1":0,"s2":2},
    ],
    solution: {"room":[0,3,2,1,4],"time":[2,1,3,0,4],"obj":[3,2,0,4,1]},
  },
];
