// Puzzle data for Alibi, the daily logic deduction game. Imported
// ONLY by the server page (app/alibi/page.js), which filters live<=today AND
// strips the solution before passing puzzles to the client (the client derives
// the unique solution from the clues with its own 4!^3 brute-force solver, so
// the answer never ships over the wire).
//
// Every puzzle was generated (seeded constraint solver: random solution ->
// pool of true clues -> greedy add until unique -> prune redundant) and then
// INDEPENDENTLY re-verified to have exactly one solution, with 8-11 clues.
// Validate with scripts/verify-alibi.mjs after ANY edit.
//
// Clue schema (indices into suspects/rooms/objects/times):
//   notRoom {s,r}   suspect s was never in room r
//   notObj  {s,o}   suspect s was not carrying object o
//   roomObj {r,o}   whoever was in room r carried object o
//   roomTime{r,t}   the guest in room r left at time t
//   before  {s1,s2} s1 left earlier than s2
//   beforeRoom {s,r} s left before the guest in room r (s not in r)
//   hasObj  {s,o}   suspect s carried object o
export const PUZZLES = [
  {
    num: 1, quizId: "alibi-7-18-26", live: "2026-07-18", dateLabel: "July 18, 2026", sunday: false,
    suspects: ["Hugo","Ambrose","Beatrix","Ingrid"],
    rooms: ["Greenhouse","Gallery","Kitchen","Library"],
    objects: ["ivory comb","empty vial","torn letter","brass key"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "the Marlowe Emerald",
    venue: "Thornfield Manor",
    clues: [
      {"type":"roomObj","r":2,"o":3},
      {"type":"beforeRoom","s":1,"r":0},
      {"type":"roomTime","r":3,"t":1},
      {"type":"notObj","s":3,"o":2},
      {"type":"notRoom","s":2,"r":0},
      {"type":"notObj","s":0,"o":2},
      {"type":"roomTime","r":2,"t":3},
      {"type":"notRoom","s":1,"r":3},
      {"type":"before","s1":0,"s2":3},
      {"type":"roomObj","r":1,"o":0},
    ],
    solution: {"room":[0,1,3,2],"time":[2,0,1,3],"obj":[1,0,2,3]},
  },
  {
    num: 2, quizId: "alibi-7-19-26", live: "2026-07-19", dateLabel: "July 19, 2026", sunday: false,
    suspects: ["Ingrid","Otto","Silas","Ambrose"],
    rooms: ["Gallery","Ballroom","Conservatory","Billiard Room"],
    objects: ["wax-sealed envelope","black umbrella","brass key","silver flask"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "a Stradivarius violin",
    venue: "Blackwood Hall",
    clues: [
      {"type":"before","s1":3,"s2":2},
      {"type":"roomTime","r":0,"t":3},
      {"type":"beforeRoom","s":0,"r":1},
      {"type":"notRoom","s":0,"r":2},
      {"type":"before","s1":1,"s2":0},
      {"type":"roomObj","r":3,"o":2},
      {"type":"roomObj","r":1,"o":0},
      {"type":"roomObj","r":0,"o":1},
    ],
    solution: {"room":[3,2,0,1],"time":[1,0,3,2],"obj":[2,3,1,0]},
  },
  {
    num: 3, quizId: "alibi-7-20-26", live: "2026-07-20", dateLabel: "July 20, 2026", sunday: false,
    suspects: ["Hugo","Ingrid","Minerva","Casper"],
    rooms: ["Observatory","Gallery","Billiard Room","Conservatory"],
    objects: ["torn letter","opera glasses","empty vial","ivory comb"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "the Duchess's will",
    venue: "the Grand Hotel Meridian",
    clues: [
      {"type":"roomTime","r":1,"t":1},
      {"type":"beforeRoom","s":2,"r":3},
      {"type":"roomTime","r":3,"t":3},
      {"type":"before","s1":1,"s2":2},
      {"type":"roomObj","r":3,"o":1},
      {"type":"notRoom","s":0,"r":2},
      {"type":"before","s1":0,"s2":3},
      {"type":"notRoom","s":0,"r":0},
      {"type":"notObj","s":2,"o":0},
      {"type":"roomObj","r":0,"o":0},
      {"type":"roomObj","r":1,"o":2},
    ],
    solution: {"room":[1,0,2,3],"time":[1,0,2,3],"obj":[2,0,3,1]},
  },
  {
    num: 4, quizId: "alibi-7-21-26", live: "2026-07-21", dateLabel: "July 21, 2026", sunday: false,
    suspects: ["Edmund","Leopold","Opal","Hugo"],
    rooms: ["Ballroom","Greenhouse","Gallery","Wine Cellar"],
    objects: ["ivory comb","brass key","black umbrella","wax-sealed envelope"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "a jeweled dagger",
    venue: "Ashcombe House",
    clues: [
      {"type":"notObj","s":3,"o":3},
      {"type":"beforeRoom","s":2,"r":2},
      {"type":"notObj","s":3,"o":0},
      {"type":"notObj","s":3,"o":1},
      {"type":"roomTime","r":3,"t":2},
      {"type":"notRoom","s":0,"r":2},
      {"type":"notObj","s":0,"o":3},
      {"type":"roomObj","r":2,"o":1},
      {"type":"roomObj","r":0,"o":2},
      {"type":"before","s1":1,"s2":3},
    ],
    solution: {"room":[3,2,1,0],"time":[2,1,0,3],"obj":[0,1,3,2]},
  },
  {
    num: 5, quizId: "alibi-7-22-26", live: "2026-07-22", dateLabel: "July 22, 2026", sunday: false,
    suspects: ["Hugo","Vera","Rufus","Leopold"],
    rooms: ["Kitchen","Study","Conservatory","Wine Cellar"],
    objects: ["wax-sealed envelope","pocket watch","black umbrella","muddy gloves"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "the deed to the estate",
    venue: "the Yacht Aurora",
    clues: [
      {"type":"roomObj","r":1,"o":3},
      {"type":"roomTime","r":2,"t":3},
      {"type":"roomObj","r":3,"o":2},
      {"type":"beforeRoom","s":3,"r":2},
      {"type":"beforeRoom","s":2,"r":0},
      {"type":"notRoom","s":2,"r":1},
      {"type":"before","s1":0,"s2":2},
      {"type":"roomObj","r":2,"o":1},
    ],
    solution: {"room":[1,2,3,0],"time":[0,3,1,2],"obj":[3,1,2,0]},
  },
  {
    num: 6, quizId: "alibi-7-23-26", live: "2026-07-23", dateLabel: "July 23, 2026", sunday: false,
    suspects: ["Vera","Cleo","Otto","Ambrose"],
    rooms: ["Gallery","Kitchen","Observatory","Billiard Room"],
    objects: ["ivory comb","muddy gloves","empty vial","pocket watch"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "the Admiral's ruby ring",
    venue: "Wexley Court",
    clues: [
      {"type":"notRoom","s":0,"r":3},
      {"type":"beforeRoom","s":2,"r":1},
      {"type":"notObj","s":0,"o":1},
      {"type":"roomObj","r":1,"o":2},
      {"type":"notObj","s":0,"o":0},
      {"type":"notRoom","s":2,"r":2},
      {"type":"notObj","s":2,"o":0},
      {"type":"beforeRoom","s":1,"r":0},
      {"type":"before","s1":0,"s2":2},
      {"type":"notRoom","s":0,"r":2},
    ],
    solution: {"room":[0,2,3,1],"time":[1,0,2,3],"obj":[3,0,1,2]},
  },
  {
    num: 7, quizId: "alibi-7-24-26", live: "2026-07-24", dateLabel: "July 24, 2026", sunday: false,
    suspects: ["Edmund","Ingrid","Cleo","Ambrose"],
    rooms: ["Study","Kitchen","Library","Conservatory"],
    objects: ["silver flask","ivory comb","empty vial","black umbrella"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "a case of rare stamps",
    venue: "the Pemberton Club",
    clues: [
      {"type":"beforeRoom","s":2,"r":2},
      {"type":"notRoom","s":0,"r":1},
      {"type":"notObj","s":2,"o":0},
      {"type":"before","s1":2,"s2":3},
      {"type":"notRoom","s":0,"r":3},
      {"type":"roomObj","r":1,"o":0},
      {"type":"roomObj","r":3,"o":2},
      {"type":"before","s1":0,"s2":2},
      {"type":"roomTime","r":1,"t":1},
      {"type":"roomObj","r":2,"o":3},
    ],
    solution: {"room":[0,1,3,2],"time":[0,1,2,3],"obj":[1,0,2,3]},
  },
  {
    num: 8, quizId: "alibi-7-25-26", live: "2026-07-25", dateLabel: "July 25, 2026", sunday: false,
    suspects: ["Casper","Vera","Freya","Otto"],
    rooms: ["Conservatory","Billiard Room","Wine Cellar","Greenhouse"],
    objects: ["torn letter","black umbrella","silver flask","ivory comb"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "the Countess's pearl choker",
    venue: "Larkspur Lodge",
    clues: [
      {"type":"beforeRoom","s":0,"r":1},
      {"type":"roomTime","r":2,"t":0},
      {"type":"roomObj","r":2,"o":0},
      {"type":"notRoom","s":3,"r":3},
      {"type":"notObj","s":2,"o":0},
      {"type":"roomTime","r":3,"t":3},
      {"type":"notRoom","s":2,"r":0},
      {"type":"notObj","s":2,"o":3},
      {"type":"before","s1":2,"s2":3},
      {"type":"roomObj","r":3,"o":1},
    ],
    solution: {"room":[2,3,1,0],"time":[0,3,1,2],"obj":[0,1,2,3]},
  },
  {
    num: 9, quizId: "alibi-7-26-26", live: "2026-07-26", dateLabel: "July 26, 2026", sunday: false,
    suspects: ["Beatrix","Casper","Leopold","Opal"],
    rooms: ["Billiard Room","Library","Gallery","Ballroom"],
    objects: ["pocket watch","wax-sealed envelope","torn letter","silver flask"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "an original Vermeer sketch",
    venue: "the Observatory at Dunmore",
    clues: [
      {"type":"beforeRoom","s":0,"r":0},
      {"type":"notRoom","s":3,"r":2},
      {"type":"before","s1":3,"s2":0},
      {"type":"roomObj","r":1,"o":2},
      {"type":"beforeRoom","s":1,"r":0},
      {"type":"roomObj","r":2,"o":0},
      {"type":"roomObj","r":3,"o":1},
      {"type":"beforeRoom","s":3,"r":1},
      {"type":"beforeRoom","s":1,"r":2},
    ],
    solution: {"room":[2,1,0,3],"time":[2,1,3,0],"obj":[0,2,3,1]},
  },
  {
    num: 10, quizId: "alibi-7-27-26", live: "2026-07-27", dateLabel: "July 27, 2026", sunday: false,
    suspects: ["Beatrix","Rufus","Hugo","Freya"],
    rooms: ["Wine Cellar","Billiard Room","Greenhouse","Observatory"],
    objects: ["pocket watch","silver flask","empty vial","muddy gloves"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "the key to the vault",
    venue: "Hollybrook Abbey",
    clues: [
      {"type":"beforeRoom","s":0,"r":2},
      {"type":"roomObj","r":1,"o":2},
      {"type":"notRoom","s":1,"r":0},
      {"type":"beforeRoom","s":1,"r":1},
      {"type":"notObj","s":1,"o":3},
      {"type":"roomObj","r":2,"o":3},
      {"type":"before","s1":0,"s2":1},
      {"type":"roomObj","r":0,"o":0},
      {"type":"before","s1":3,"s2":1},
    ],
    solution: {"room":[0,3,1,2],"time":[0,2,3,1],"obj":[0,1,2,3]},
  },
  {
    num: 11, quizId: "alibi-7-28-26", live: "2026-07-28", dateLabel: "July 28, 2026", sunday: false,
    suspects: ["Silas","Leopold","Hugo","Vera"],
    rooms: ["Ballroom","Study","Gallery","Wine Cellar"],
    objects: ["torn letter","black umbrella","pocket watch","brass key"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "a first-edition folio",
    venue: "the Midnight Express",
    clues: [
      {"type":"roomObj","r":3,"o":3},
      {"type":"beforeRoom","s":0,"r":2},
      {"type":"notObj","s":2,"o":0},
      {"type":"beforeRoom","s":0,"r":3},
      {"type":"beforeRoom","s":1,"r":0},
      {"type":"notObj","s":1,"o":1},
      {"type":"beforeRoom","s":0,"r":0},
      {"type":"before","s1":2,"s2":3},
      {"type":"before","s1":1,"s2":2},
      {"type":"roomObj","r":0,"o":0},
      {"type":"roomObj","r":1,"o":2},
    ],
    solution: {"room":[1,3,2,0],"time":[0,1,2,3],"obj":[2,3,1,0]},
  },
  {
    num: 12, quizId: "alibi-7-29-26", live: "2026-07-29", dateLabel: "July 29, 2026", sunday: false,
    suspects: ["Minerva","Vera","Leopold","Cleo"],
    rooms: ["Gallery","Kitchen","Library","Greenhouse"],
    objects: ["empty vial","torn letter","silver flask","muddy gloves"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "the Baron's gold snuffbox",
    venue: "Ravenswood Estate",
    clues: [
      {"type":"roomObj","r":1,"o":0},
      {"type":"notRoom","s":2,"r":1},
      {"type":"beforeRoom","s":2,"r":3},
      {"type":"notObj","s":1,"o":2},
      {"type":"notObj","s":1,"o":3},
      {"type":"beforeRoom","s":1,"r":1},
      {"type":"roomObj","r":2,"o":2},
      {"type":"beforeRoom","s":3,"r":3},
      {"type":"roomTime","r":2,"t":1},
      {"type":"roomTime","r":3,"t":3},
    ],
    solution: {"room":[3,0,2,1],"time":[3,0,1,2],"obj":[3,1,2,0]},
  },
  {
    num: 13, quizId: "alibi-7-30-26", live: "2026-07-30", dateLabel: "July 30, 2026", sunday: false,
    suspects: ["Freya","Cleo","Silas","Casper"],
    rooms: ["Study","Wine Cellar","Kitchen","Gallery"],
    objects: ["black umbrella","torn letter","empty vial","wax-sealed envelope"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "a map to the family crypt",
    venue: "the Gilded Peacock Theatre",
    clues: [
      {"type":"notRoom","s":3,"r":0},
      {"type":"notRoom","s":3,"r":3},
      {"type":"roomObj","r":0,"o":1},
      {"type":"beforeRoom","s":0,"r":0},
      {"type":"roomObj","r":1,"o":3},
      {"type":"beforeRoom","s":0,"r":3},
      {"type":"notRoom","s":1,"r":0},
      {"type":"beforeRoom","s":3,"r":2},
      {"type":"before","s1":2,"s2":1},
      {"type":"notObj","s":1,"o":2},
    ],
    solution: {"room":[2,3,0,1],"time":[1,3,2,0],"obj":[2,0,1,3]},
  },
  {
    num: 14, quizId: "alibi-7-31-26", live: "2026-07-31", dateLabel: "July 31, 2026", sunday: false,
    suspects: ["Beatrix","Otto","Dorothea","Cleo"],
    rooms: ["Ballroom","Study","Observatory","Billiard Room"],
    objects: ["brass key","silver flask","torn letter","pocket watch"],
    times: ["7 pm","8 pm","9 pm","10 pm"],
    stolen: "the opera house ledger",
    venue: "Foxglove Priory",
    clues: [
      {"type":"before","s1":3,"s2":1},
      {"type":"roomObj","r":2,"o":1},
      {"type":"beforeRoom","s":3,"r":3},
      {"type":"beforeRoom","s":2,"r":2},
      {"type":"before","s1":1,"s2":0},
      {"type":"roomTime","r":0,"t":1},
      {"type":"notObj","s":0,"o":2},
      {"type":"beforeRoom","s":2,"r":0},
      {"type":"notObj","s":2,"o":3},
      {"type":"notObj","s":3,"o":2},
      {"type":"notObj","s":2,"o":2},
    ],
    solution: {"room":[2,3,1,0],"time":[3,2,0,1],"obj":[1,2,0,3]},
  },
];
