// Strata theme pools. Each pool is BOTH the source of a day's answers and the
// vocabulary the decoy check runs against: any pool word that is not an answer
// but can still be traced somewhere on the board fails the bank, because that is
// the cruel case (a real member of the category, sitting right there, refused).
// Keep pools tight for that reason. Words are A-Z only, 3 to 8 letters.

export const THEMES = [
  ['Weather', 'RAIN SNOW HAIL SLEET FROST THAW GUST STORM THUNDER DRIZZLE BREEZE MIST GALE SQUALL'],
  ['Big cats', 'LION TIGER LEOPARD JAGUAR CHEETAH COUGAR PUMA LYNX OCELOT PANTHER CARACAL SERVAL BOBCAT'],
  ['Kitchen tools', 'WHISK LADLE SPATULA GRATER PEELER SIEVE TONGS MASHER SKILLET KETTLE CLEAVER MORTAR'],
  ['Trees', 'OAK ELM ASH BIRCH CEDAR MAPLE WILLOW ASPEN ALDER POPLAR SPRUCE LARCH BEECH HAZEL'],
  ['Musical instruments', 'VIOLA CELLO ORGAN FLUTE OBOE HARP TUBA PIANO BANJO FIDDLE TRUMPET DRUM'],
  ['Gemstones', 'RUBY OPAL JADE TOPAZ PEARL AMBER GARNET ZIRCON BERYL ONYX AGATE JASPER EMERALD'],
  ['Birds of prey', 'EAGLE HAWK FALCON KESTREL OSPREY HARRIER BUZZARD CONDOR VULTURE MERLIN GOSHAWK'],
  ['Card games', 'HEARTS BRIDGE POKER RUMMY CANASTA EUCHRE SPADES WHIST CRIBBAGE FARO'],
  ['Dances', 'TANGO SALSA WALTZ RUMBA SAMBA MAMBO POLKA JIVE BOLERO FLAMENCO FOXTROT'],
  ['Fabrics', 'LINEN SILK DENIM VELVET SATIN TWEED COTTON CANVAS CHIFFON FLANNEL MUSLIN SUEDE WOOL'],
  ['Herbs and spices', 'BASIL THYME SAGE CUMIN ANISE CLOVE NUTMEG PAPRIKA OREGANO PARSLEY GINGER SAFFRON MINT'],
  ['Boats', 'KAYAK CANOE FERRY YACHT SKIFF BARGE SLOOP KETCH TRAWLER GALLEON DINGHY CUTTER PUNT'],
  ['Hand tools', 'HAMMER WRENCH PLIERS CHISEL DRILL SANDER MALLET CLAMP RASP PLANE LEVEL GOUGE'],
  ['Fish', 'TROUT SALMON TUNA PERCH BASS PIKE CARP MULLET HERRING MACKEREL SARDINE HALIBUT TURBOT'],
  ['Shades of red', 'CRIMSON SCARLET RUBY CORAL CARMINE MAROON CERISE GARNET BRICK ROSE BLUSH'],
  ['Body parts', 'SPLEEN TEMPLE KIDNEY LIVER ANKLE WRIST SHIN ELBOW THIGH PELVIS STERNUM TENDON RETINA'],
  ['Breads', 'BAGEL BRIOCHE CIABATTA PITA NAAN RYE BAGUETTE CHALLAH MUFFIN SCONE BANNOCK'],
  ['Currencies', 'EURO YEN PESO RUPEE DINAR FRANC KRONA RAND POUND DOLLAR SHEKEL FORINT DIRHAM'],
  ['Reptiles', 'GECKO IGUANA COBRA VIPER PYTHON ADDER TURTLE SKINK MONITOR CAIMAN MAMBA KRAIT'],
  ['Constellations', 'ORION LYRA DRACO CYGNUS PERSEUS PEGASUS HYDRA ARIES TAURUS VIRGO LIBRA CORVUS'],
  ['Pasta shapes', 'PENNE FUSILLI RIGATONI ORZO FARFALLE LINGUINE ROTINI ZITI LASAGNE RAVIOLI GNOCCHI'],
  ['Golf terms', 'BIRDIE EAGLE BOGEY PUTT DRIVER WEDGE FAIRWAY BUNKER CADDIE IRON SLICE ALBATROS'],
  ['Sea creatures', 'OCTOPUS SQUID CORAL URCHIN MANTA WHALE ORCA WALRUS LOBSTER PRAWN MUSSEL OYSTER'],
  ['Ancient Rome', 'TOGA FORUM LEGION SENATE COLUMN CHARIOT VILLA ARENA CAESAR MOSAIC TUNIC AUGUR'],
  ['Fruits', 'MANGO GUAVA PAPAYA LYCHEE APRICOT DAMSON QUINCE PLUM PEACH CHERRY MELON BANANA LEMON'],
  ['Flowers', 'TULIP DAHLIA PEONY ORCHID LILAC IRIS ASTER POPPY DAISY AZALEA FREESIA ZINNIA VIOLET'],
  ['Dog breeds', 'BEAGLE BOXER COLLIE POODLE TERRIER SPANIEL HUSKY SETTER MASTIFF WHIPPET BORZOI'],
  // US spelling: the house British-spelling scan reads reader-facing copy, and a
  // theme name is reader-facing.
  ['Theater', 'STAGE CURTAIN SCRIPT ACTOR WINGS PROPS USHER BALCONY ENCORE MATINEE CHORUS PROMPT'],
  ['Cheeses', 'BRIE GOUDA EDAM FETA STILTON CHEDDAR GRUYERE MANCHEGO RICOTTA HALLOUMI ASIAGO'],
  ['Knots', 'BOWLINE CLOVE HITCH REEF GRANNY TIMBER PRUSIK BEND LOOP SPLICE LANYARD'],
  ['Mountains', 'ANDES ALPS ROCKIES URALS ATLAS TAURUS ZAGROS PYRENEES CASCADES OZARKS SIERRA'],
  ['Bones', 'FEMUR TIBIA FIBULA RADIUS ULNA SCAPULA PATELLA SACRUM CARPAL RIB SKULL STAPES'],
  ['Winds', 'MISTRAL SIROCCO CHINOOK MONSOON TRADE ZEPHYR BORA HABOOB SANTAANA LEVANTER'],
  ['Castle parts', 'KEEP MOAT TOWER TURRET RAMPART BAILEY DRAWBRIDGE PORTCULLIS GATEHOUSE MERLON'],
  ['Printing', 'SERIF KERNING GALLEY PLATEN QUOIN FOLIO QUARTO LIGATURE INKWELL PRESS TYPE'],
  ['Cocktails', 'MARTINI NEGRONI DAIQUIRI MOJITO SIDECAR GIMLET SAZERAC PALOMA BELLINI JULEP'],
  ['Sewing', 'THIMBLE BOBBIN SEAM HEM PLEAT DART BASTE SERGE GUSSET SELVAGE NOTCH'],
  ['Volcanoes', 'ETNA FUJI HEKLA KRAKATOA VESUVIUS RAINIER SHASTA PELEE PARICUTIN COTOPAXI'],
  ['Chess', 'ROOK BISHOP KNIGHT PAWN QUEEN GAMBIT ZUGZWANG FORK PIN SKEWER CASTLE ENDGAME'],
  ['Rivers', 'DANUBE VOLGA RHINE SEINE THAMES TIBER EBRO LOIRE ODER ELBE SHANNON TAGUS'],
];

export function loadThemes() {
  return THEMES.map(([name, list]) => ({
    name,
    pool: [...new Set(list.split(/\s+/))].filter((w) => /^[A-Z]{3,8}$/.test(w)),
  })).filter((t) => t.pool.length >= 8);
}
