// Puzzle bank for Listed. Imported ONLY by the server page component, which
// filters to live<=today before passing puzzles to the client, so a future
// board (and its answer order) never ships to the browser bundle.
//
// Each puzzle ranks 8 real things by ONE measurable quantity. `items` is stored
// in TRUE ORDER: index 0 is rank 1, the top of the board. Authoring rules:
//   - the answer key must be a NUMBER from a citable source, never an opinion,
//     a critics' consensus, or an editorial "best of" ranking;
//   - no two items may tie or round to the same display string;
//   - reject any pair that reputable sources order differently (the classic
//     Nile-vs-Amazon trap), and prefer figures that do not move week to week;
//   - every item should be recognizable, while the ORDER is not, which is the
//     whole game. Aim for at least two genuine surprises per board.
// Sunday Editions carry a ninth item.
export const PUZZLES = [
  {
    num: 1,
    quizId: "listed-7-27-26",
    live: "2026-07-27",
    dateLabel: "July 27, 2026",
    title: "Highest-grossing films worldwide, not adjusted for inflation",
    metric: "Gross",
    hi: "Biggest",
    lo: "Smallest",
    source: "Box Office Mojo",
    items: [
      { t: "Avatar (2009)", v: "$2.92B", d: "Re-releases in 2021 and 2022 pushed it back past Endgame for the all-time crown." },
      { t: "Avengers: Endgame (2019)", v: "$2.80B", d: "It held the all-time record for two years before Avatar reclaimed it in China." },
      { t: "Titanic (1997)", v: "$2.26B", d: "Four separate theatrical runs, in 1997, 2012, 2017 and 2023, built this total." },
      { t: "The Force Awakens (2015)", v: "$2.07B", d: "Still the highest-grossing film ever in the United States, ahead of Avatar." },
      { t: "Spider-Man: No Way Home (2021)", v: "$1.92B", d: "The pandemic-era blockbuster that proved audiences would still fill theaters." },
      { t: "Inside Out 2 (2024)", v: "$1.70B", d: "Pixar's biggest hit ever, roughly doubling the 2015 original's worldwide take." },
      { t: "Top Gun: Maverick (2022)", v: "$1.50B", d: "Tom Cruise waited 36 years for the sequel, then took his first billion-dollar hit." },
      { t: "Barbie (2023)", v: "$1.45B", d: "The highest-grossing film ever directed by a woman." },
    ],
  },
  {
    num: 2,
    quizId: "listed-7-28-26",
    live: "2026-07-28",
    dateLabel: "July 28, 2026",
    title: "Deepest lakes in the world, by maximum depth",
    metric: "Depth",
    hi: "Deepest",
    lo: "Shallowest",
    source: "Published bathymetric surveys",
    items: [
      { t: "Lake Baikal (Russia)", v: "1,642 m", d: "Holds about one fifth of all the unfrozen fresh water on Earth." },
      { t: "Lake Tanganyika (Africa)", v: "1,470 m", d: "The world's longest freshwater lake, running some 400 miles north to south." },
      { t: "Caspian Sea", v: "1,025 m", d: "Big enough to be called a sea, but geographers still count it as a lake." },
      { t: "Lake Malawi", v: "706 m", d: "Home to more fish species than any other lake on the planet." },
      { t: "Great Slave Lake (Canada)", v: "614 m", d: "Ice roads are cut across its frozen surface each winter to reach remote mines." },
      { t: "Crater Lake (Oregon)", v: "594 m", d: "Filled the collapsed caldera of Mount Mazama with nothing but rain and snow." },
      { t: "Lake Tahoe", v: "501 m", d: "Too deep to lose its heat, so the main lake has never been recorded frozen over." },
      { t: "Lake Superior", v: "406 m", d: "The largest freshwater lake on Earth by surface area, yet the shallowest here." },
    ],
  },
  {
    num: 3,
    quizId: "listed-7-29-26",
    live: "2026-07-29",
    dateLabel: "July 29, 2026",
    title: "Most career points in NBA regular-season history",
    metric: "Points",
    hi: "Most",
    lo: "Fewest",
    source: "Basketball-Reference, through the 2025-26 season",
    items: [
      { t: "LeBron James", v: "43,440", d: "Passed Kareem in February 2023 and has extended the record every season since." },
      { t: "Kareem Abdul-Jabbar", v: "38,387", d: "Held the record for 39 years, built almost entirely on the unblockable skyhook." },
      { t: "Karl Malone", v: "36,928", d: "Eighteen seasons in Utah and not one championship to show for it." },
      { t: "Kobe Bryant", v: "33,643", d: "Scored 60 points in his farewell game in 2016, a fitting way out." },
      { t: "Michael Jordan", v: "32,292", d: "Two separate retirements cost him seasons in the middle of his prime." },
      { t: "Dirk Nowitzki", v: "31,560", d: "Played all 21 of his seasons for Dallas, the longest run with one franchise." },
      { t: "Wilt Chamberlain", v: "31,419", d: "Averaged 50.4 points a game in 1961-62, a number nobody has approached since." },
      { t: "Shaquille O'Neal", v: "28,596", d: "Also missed more free throws than any player in league history." },
    ],
  },
  {
    num: 4,
    quizId: "listed-7-30-26",
    live: "2026-07-30",
    dateLabel: "July 30, 2026",
    title: "Planets of the solar system, by diameter",
    metric: "Diameter",
    hi: "Widest",
    lo: "Narrowest",
    source: "NASA planetary fact sheets",
    items: [
      { t: "Jupiter", v: "142,984 km", d: "Wide enough to hold every other planet in the solar system inside it." },
      { t: "Saturn", v: "120,536 km", d: "Less dense than water, so a big enough ocean would let it float." },
      { t: "Uranus", v: "51,118 km", d: "Wider than Neptune but lighter, and it orbits tipped almost onto its side." },
      { t: "Neptune", v: "49,528 km", d: "Heavier than Uranus despite being narrower, and the windiest place known." },
      { t: "Earth", v: "12,756 km", d: "The densest planet here, and the only one not named after a god." },
      { t: "Venus", v: "12,104 km", d: "Nearly a twin of Earth in width, but hot enough at the surface to melt lead." },
      { t: "Mars", v: "6,792 km", d: "Half the width of Earth, yet home to the tallest volcano in the solar system." },
      { t: "Mercury", v: "4,879 km", d: "Smaller than two moons in this same solar system, Ganymede and Titan." },
    ],
  },
  {
    num: 5,
    quizId: "listed-7-31-26",
    live: "2026-07-31",
    dateLabel: "July 31, 2026",
    title: "Best-selling book series of all time",
    metric: "Copies",
    hi: "Most",
    lo: "Fewest",
    source: "Publisher sales estimates",
    items: [
      { t: "Harry Potter", v: "600M copies", d: "Seven novels, plus companion books and scripts, in more than 80 languages." },
      { t: "Goosebumps", v: "400M copies", d: "R. L. Stine wrote the original 62 books in roughly six years." },
      { t: "Perry Mason", v: "300M copies", d: "Erle Stanley Gardner published 82 Mason novels between 1933 and his death." },
      { t: "Choose Your Own Adventure", v: "250M copies", d: "Second-person narration and branching endings made it a 1980s phenomenon." },
      { t: "Jack Reacher", v: "200M copies", d: "Lee Child has published a Reacher novel almost every year since 1997." },
      { t: "Twilight", v: "160M copies", d: "Four novels moved 160 million copies in barely five years." },
      { t: "The Chronicles of Narnia", v: "120M copies", d: "C. S. Lewis finished all seven books in under seven years." },
      { t: "The Hunger Games", v: "100M copies", d: "Suzanne Collins has added two prequels to the original trilogy." },
    ],
  },
  {
    num: 6,
    quizId: "listed-8-1-26",
    live: "2026-08-01",
    dateLabel: "August 1, 2026",
    title: "Largest islands in the world, by area",
    metric: "Area",
    hi: "Largest",
    lo: "Smallest",
    source: "Satellite-derived area measurements",
    items: [
      { t: "Greenland", v: "2,108,000 km2", d: "Roughly three times the size of Texas, and about 80 percent covered by ice." },
      { t: "New Guinea", v: "773,800 km2", d: "Split between two countries and home to more than 800 living languages." },
      { t: "Borneo", v: "723,200 km2", d: "The only island in the world shared by three nations." },
      { t: "Madagascar", v: "592,500 km2", d: "Broke off from Africa so long ago that most of its wildlife lives nowhere else." },
      { t: "Sumatra", v: "428,100 km2", d: "Sits on the Ring of Fire and holds the Toba supervolcano crater." },
      { t: "Honshu (Japan)", v: "228,300 km2", d: "Carries Tokyo, Osaka and roughly 80 percent of Japan's population." },
      { t: "Cuba", v: "105,500 km2", d: "The largest island in the Caribbean, by a very wide margin." },
      { t: "Ireland", v: "83,700 km2", d: "Nicknamed the Emerald Isle for pasture that stays green year round." },
    ],
  },
  {
    num: 7,
    quizId: "listed-8-2-26",
    live: "2026-08-02",
    dateLabel: "August 2, 2026",
    sunday: true,
    title: "Highest mountains outside Asia, by elevation",
    metric: "Elevation",
    hi: "Highest",
    lo: "Lowest",
    source: "National survey data (USGS, IGN, swisstopo)",
    items: [
      { t: "Aconcagua (Argentina)", v: "6,967 m", d: "The highest peak anywhere outside Asia, and climbable without ropes." },
      { t: "Denali (Alaska)", v: "6,190 m", d: "Its rise from base to summit is greater than that of Everest." },
      { t: "Kilimanjaro (Tanzania)", v: "5,895 m", d: "A dormant volcano whose summit glaciers have shrunk by more than 80 percent." },
      { t: "Mount Elbrus (Russia)", v: "5,642 m", d: "A twin-coned volcano, and the highest point in Europe." },
      { t: "Mont Blanc (France, Italy)", v: "4,806 m", d: "Its official height is remeasured every two years as the snow cap shifts." },
      { t: "Matterhorn (Switzerland)", v: "4,478 m", d: "Glaciers carved its four faces at once, leaving the famous pyramid." },
      { t: "Mount Whitney (California)", v: "4,421 m", d: "The highest point in the lower 48, about 80 miles from Death Valley." },
      { t: "Mount Kosciuszko (Australia)", v: "2,228 m", d: "A continental high point gentle enough to reach on a walking track." },
      { t: "Ben Nevis (Scotland)", v: "1,345 m", d: "Britain's highest peak, with the remains of a collapsed volcano at its core." },
    ],
  },
  {
    num: 8,
    quizId: "listed-8-3-26",
    live: "2026-08-03",
    dateLabel: "August 3, 2026",
    title: "Most Formula One race wins by a driver",
    metric: "Wins",
    hi: "Most",
    lo: "Fewest",
    source: "Formula 1 official driver records, July 2026",
    items: [
      { t: "Lewis Hamilton", v: "106", d: "Win number 106 came at Barcelona in 2026, his first in Ferrari red." },
      { t: "Michael Schumacher", v: "91", d: "Won 13 of the 18 races in 2004, the best strike rate of any full season." },
      { t: "Max Verstappen", v: "71", d: "Took 19 wins in 2023 alone, the most anyone has managed in one year." },
      { t: "Sebastian Vettel", v: "53", d: "Became the sport's youngest champion at 23, then won four titles in a row." },
      { t: "Alain Prost", v: "51", d: "Nicknamed The Professor for winning on strategy rather than raw pace." },
      { t: "Ayrton Senna", v: "41", d: "His 65 pole positions stood as the record until Schumacher passed it in 2006." },
      { t: "Fernando Alonso", v: "32", d: "Still on the grid in his forties, though his last win came back in 2013." },
      { t: "Nigel Mansell", v: "31", d: "Won the 1992 title, left for IndyCar, and took that championship as a rookie." },
    ],
  },
  {
    num: 9,
    quizId: "listed-8-4-26",
    live: "2026-08-04",
    dateLabel: "August 4, 2026",
    title: "Founding years of famous technology companies",
    metric: "Founded",
    hi: "Oldest",
    lo: "Newest",
    source: "Company corporate histories",
    items: [
      { t: "Nokia", v: "1865", d: "Started as a riverside wood pulp mill in Finland, making paper, not phones." },
      { t: "Nintendo", v: "1889", d: "Spent its first 70 years making hanafuda playing cards by hand in Kyoto." },
      { t: "IBM", v: "1911", d: "A merger of firms making time clocks, weighing scales and card tabulators." },
      { t: "Samsung", v: "1938", d: "Opened in Daegu as a trading store selling dried fish, groceries and noodles." },
      { t: "Hewlett-Packard", v: "1939", d: "Built its first audio oscillator in a Palo Alto garage. Disney bought eight." },
      { t: "Sony", v: "1946", d: "Launched as a radio repair shop in a bombed out Tokyo department store." },
      { t: "Intel", v: "1968", d: "Founded to build memory chips. Its first microprocessor was three years off." },
      { t: "Microsoft", v: "1975", d: "Its first product was a BASIC interpreter for a mail order hobby computer." },
    ],
  },
  {
    num: 10,
    quizId: "listed-8-5-26",
    live: "2026-08-05",
    dateLabel: "August 5, 2026",
    title: "Best-selling video games of all time, by copies sold",
    metric: "Copies",
    hi: "Most",
    lo: "Fewest",
    source: "Publisher sales reports",
    items: [
      { t: "Minecraft", v: "350M copies", d: "Mojang has sold it on nearly every platform made since 2011, including phones." },
      { t: "Grand Theft Auto V", v: "225M copies", d: "Rockstar has shipped it across three console generations since 2013." },
      { t: "Wii Sports", v: "82.9M copies", d: "Bundled with the Wii almost everywhere, which is how it reached that number." },
      { t: "PUBG: Battlegrounds", v: "75M copies", d: "Its paid count froze in 2022 when the game went free to play." },
      { t: "Super Mario Bros. (1985)", v: "58M copies", d: "Packed in with the NES, it sold for a decade on a single cartridge." },
      { t: "Animal Crossing: New Horizons", v: "49.3M copies", d: "It launched in March 2020, the exact week much of the world locked down." },
      { t: "Super Smash Bros. Ultimate", v: "37.4M copies", d: "It brought back every playable fighter from every previous Smash Bros. game." },
      { t: "Zelda: Breath of the Wild", v: "35.3M copies", d: "A launch title for the Switch that also shipped on the dying Wii U." },
    ],
  },
  {
    num: 11,
    quizId: "listed-8-6-26",
    live: "2026-08-06",
    dateLabel: "August 6, 2026",
    title: "Largest deserts in the world, by area",
    metric: "Area",
    hi: "Largest",
    lo: "Smallest",
    source: "Encyclopaedia Britannica",
    items: [
      { t: "Antarctic Desert", v: "13,960,000 km2", d: "A desert of ice: the interior sees less precipitation than the Sahara." },
      { t: "Arctic Desert", v: "13,700,000 km2", d: "Polar and parched, spanning Greenland, northern Canada and Russia." },
      { t: "Sahara", v: "8,600,000 km2", d: "Nearly the size of the United States, and slowly expanding southward." },
      { t: "Arabian Desert", v: "2,300,000 km2", d: "Contains the Rub al Khali, the largest continuous sand sea on Earth." },
      { t: "Gobi Desert", v: "1,300,000 km2", d: "A cold desert where winter nights fall far below freezing." },
      { t: "Kalahari Desert", v: "930,000 km2", d: "Sandy but not truly barren: enough rain falls to support grass and big game." },
      { t: "Patagonian Desert", v: "673,000 km2", d: "South America's largest desert, kept dry by the rain shadow of the Andes." },
      { t: "Sonoran Desert", v: "310,800 km2", d: "The only place on Earth where the giant saguaro cactus grows wild." },
    ],
  },
  {
    num: 12,
    quizId: "listed-8-7-26",
    live: "2026-08-07",
    dateLabel: "August 7, 2026",
    title: "Most career home runs in Major League Baseball",
    metric: "Home runs",
    hi: "Most",
    lo: "Fewest",
    source: "Baseball-Reference career batting leaders",
    items: [
      { t: "Barry Bonds", v: "762", d: "Drew 2,558 walks because pitchers so often refused to give him a chance." },
      { t: "Hank Aaron", v: "755", d: "Never once hit 50 in a season, he simply hit about 40 for twenty years." },
      { t: "Babe Ruth", v: "714", d: "Started out as an ace pitcher with a record scoreless World Series streak." },
      { t: "Albert Pujols", v: "703", d: "Reached 700 in 2022, his final season, at the age of 42." },
      { t: "Alex Rodriguez", v: "696", d: "The youngest player ever to reach 500 home runs, getting there at 32." },
      { t: "Willie Mays", v: "660", d: "Lost most of two seasons to Army service right in the middle of his prime." },
      { t: "Ken Griffey Jr.", v: "630", d: "Injuries in Cincinnati ended a chase that once looked like a certainty." },
      { t: "Jim Thome", v: "612", d: "Hit 13 walk-off home runs, more than anyone else in the game." },
    ],
  },
  {
    num: 13,
    quizId: "listed-8-8-26",
    live: "2026-08-08",
    dateLabel: "August 8, 2026",
    title: "Calories in McDonald's US menu items",
    metric: "Calories",
    hi: "Most",
    lo: "Fewest",
    source: "McDonald's USA published nutrition information",
    items: [
      { t: "Double Quarter Pounder w/ Cheese", v: "740 cal", d: "Two quarter pound patties push it past every other standard burger." },
      { t: "Big Mac", v: "580 cal", d: "The club layer, that middle slice of bun, is bread a Quarter Pounder skips." },
      { t: "Quarter Pounder with Cheese", v: "520 cal", d: "Named for the raw weight of its patty, not the cooked weight served." },
      { t: "Large French Fries", v: "480 cal", d: "Nearly matches a Quarter Pounder, and it is usually ordered alongside one." },
      { t: "McFlurry with OREO Cookies", v: "410 cal", d: "The dessert outweighs the chicken sandwich two slots below it." },
      { t: "McChicken", v: "390 cal", d: "The lightest of the core sandwiches, despite being fried." },
      { t: "Hot Fudge Sundae", v: "330 cal", d: "More than a plain cheeseburger, from soft serve and hot sauce alone." },
      { t: "Cheeseburger", v: "300 cal", d: "One slice of cheese separates it from the hamburger, worth 50 calories." },
    ],
  },
  {
    num: 14,
    quizId: "listed-8-9-26",
    live: "2026-08-09",
    dateLabel: "August 9, 2026",
    sunday: true,
    title: "Longest-running Broadway shows, by total performances",
    metric: "Performances",
    hi: "Most",
    lo: "Fewest",
    source: "Internet Broadway Database",
    items: [
      { t: "The Phantom of the Opera", v: "13,981", d: "It played for 35 years before closing in 2023, the longest run Broadway has seen." },
      { t: "Chicago (1996 revival)", v: "11,704", d: "A revival that has now run more than twelve times longer than the 1975 original." },
      { t: "The Lion King", v: "11,329", d: "The highest-grossing production in Broadway history by total ticket revenue." },
      { t: "Wicked", v: "8,867", d: "It opened to mixed reviews and has been running for more than twenty years." },
      { t: "Cats", v: "7,485", d: "When it closed in 2000 it was the longest-running show Broadway had ever seen." },
      { t: "Les Miserables", v: "6,680", d: "Sixteen years on Broadway, and it has never really left the West End." },
      { t: "A Chorus Line", v: "6,137", d: "It closed in 1990 as the record holder, a title Cats took seven years later." },
      { t: "Mamma Mia!", v: "5,758", d: "Twenty-two ABBA songs, fourteen years, and no original music at all." },
      { t: "Rent", v: "5,123", d: "Its composer died the night before the first preview performance." },
    ],
  },
  {
    num: 15,
    quizId: "listed-8-10-26",
    live: "2026-08-10",
    dateLabel: "August 10, 2026",
    title: "American scripted TV series with the most episodes",
    metric: "Episodes",
    hi: "Most",
    lo: "Fewest",
    source: "Published series episode counts",
    items: [
      { t: "The Simpsons", v: "808 episodes", d: "It passed Gunsmoke for the all-time episode record back in 2018." },
      { t: "Gunsmoke", v: "635 episodes", d: "Twenty seasons on CBS, the first six of them broadcast in half-hour form." },
      { t: "Lassie", v: "591 episodes", d: "Seventeen seasons and several different owners for the same famous collie." },
      { t: "Bonanza", v: "431 episodes", d: "Fourteen seasons of the Cartwright family, and NBC ran it in color from day one." },
      { t: "Dallas", v: "357 episodes", d: "The Ewing saga ran thirteen seasons and reset the primetime soap opera." },
      { t: "CSI: Crime Scene Investigation", v: "337 episodes", d: "Fifteen seasons in Las Vegas, plus four spin-off series." },
      { t: "Cheers", v: "275 episodes", d: "Eleven seasons in a Boston bar, and it nearly got cancelled after year one." },
      { t: "M*A*S*H", v: "256 episodes", d: "Eleven seasons, well over three times the length of the war it depicted." },
    ],
  },
  {
    num: 16,
    quizId: "listed-8-11-26",
    live: "2026-08-11",
    dateLabel: "August 11, 2026",
    title: "Highest national capital cities, by elevation",
    metric: "Elevation",
    hi: "Highest",
    lo: "Lowest",
    source: "National geographic survey data",
    items: [
      { t: "La Paz (Bolivia)", v: "3,640 m", d: "The air is so thin that aircraft need an unusually long runway to lift off." },
      { t: "Quito (Ecuador)", v: "2,850 m", d: "Sits almost exactly on the Equator, yet the weather is cool all year." },
      { t: "Bogota (Colombia)", v: "2,625 m", d: "Locals joke there is no summer, only rainy season and drier season." },
      { t: "Addis Ababa (Ethiopia)", v: "2,355 m", d: "Founded beside hot springs, and now the diplomatic capital of Africa." },
      { t: "Mexico City", v: "2,240 m", d: "Built on a drained lake bed, and still sinking several inches a year." },
      { t: "Nairobi (Kenya)", v: "1,795 m", d: "The only capital with a national park, lions included, inside the city limits." },
      { t: "Kathmandu (Nepal)", v: "1,400 m", d: "Lower than most people expect, sitting in a bowl below the Himalaya." },
      { t: "Madrid (Spain)", v: "667 m", d: "The highest capital in the European Union, up on the Castilian plateau." },
    ],
  },
  {
    num: 17,
    quizId: "listed-8-12-26",
    live: "2026-08-12",
    dateLabel: "August 12, 2026",
    title: "Most career goals in NHL history",
    metric: "Goals",
    hi: "Most",
    lo: "Fewest",
    source: "Hockey-Reference, through the 2025-26 season",
    items: [
      { t: "Alex Ovechkin", v: "929", d: "Passed Gretzky in April 2025 from his familiar spot at the left circle." },
      { t: "Wayne Gretzky", v: "894", d: "His 1,963 assists alone would still top the all-time points list." },
      { t: "Gordie Howe", v: "801", d: "Played his final NHL season at 52, on the same Hartford line as his two sons." },
      { t: "Jaromir Jagr", v: "766", d: "Kept suiting up for professional games in Czechia into his fifties." },
      { t: "Brett Hull", v: "741", d: "Father Bobby scored 610, making them by far the top father and son pair." },
      { t: "Marcel Dionne", v: "731", d: "Scored almost all of it in Los Angeles and never reached a Cup final." },
      { t: "Phil Esposito", v: "717", d: "The first player to break 70 goals in a season, with 76 in 1970-71." },
      { t: "Mike Gartner", v: "708", d: "Scored 30 or more in 15 straight seasons without ever winning anything." },
    ],
  },
  {
    num: 18,
    quizId: "listed-8-13-26",
    live: "2026-08-13",
    dateLabel: "August 13, 2026",
    title: "Oldest universities still operating today",
    metric: "Founded",
    hi: "Oldest",
    lo: "Newest",
    source: "Official university founding dates",
    items: [
      { t: "University of Bologna", v: "1088", d: "Its founding year was fixed in 1888 by a committee led by the poet Carducci." },
      { t: "University of Oxford", v: "c. 1096", d: "No charter survives, but teaching was under way here in some form by then." },
      { t: "University of Cambridge", v: "1209", d: "Founded by scholars who fled Oxford after a violent town and gown dispute." },
      { t: "University of Salamanca", v: "1218", d: "Columbus argued his case for sailing west before its panel of scholars." },
      { t: "University of Padua", v: "1222", d: "Galileo taught here for 18 years and called them the best of his life." },
      { t: "University of Coimbra", v: "1290", d: "Chartered by King Dinis in Lisbon, it only settled in Coimbra in 1537." },
      { t: "Heidelberg University", v: "1386", d: "The oldest in Germany, opened while a schism split Europe between two popes." },
      { t: "Harvard University", v: "1636", d: "Created by a colonial vote, 140 years before the country around it existed." },
    ],
  },
  {
    num: 19,
    quizId: "listed-8-14-26",
    live: "2026-08-14",
    dateLabel: "August 14, 2026",
    title: "Films with the most competitive Academy Award wins",
    metric: "Oscars",
    hi: "Most",
    lo: "Fewest",
    source: "Academy of Motion Picture Arts and Sciences",
    items: [
      { t: "Ben-Hur (1959)", v: "11 wins", d: "The first film to win eleven, a record still unbroken after 67 years." },
      { t: "West Side Story (1961)", v: "10 wins", d: "Both of its directors, Robert Wise and Jerome Robbins, shared the Oscar." },
      { t: "The English Patient (1996)", v: "9 wins", d: "It beat Fargo and Shine in a year critics still argue about." },
      { t: "Amadeus (1984)", v: "8 wins", d: "F. Murray Abraham won Best Actor playing the man who envied Mozart." },
      { t: "Everything Everywhere All at Once", v: "7 wins", d: "It won three of the four acting awards, a feat only two other films managed." },
      { t: "La La Land (2016)", v: "6 wins", d: "It arrived with fourteen nominations, then lost Best Picture on live television." },
      { t: "One Flew Over the Cuckoo's Nest", v: "5 wins", d: "One of only three films ever to sweep the top five categories." },
      { t: "Parasite (2019)", v: "4 wins", d: "The first film not in English to win Best Picture." },
    ],
  },
  {
    num: 20,
    quizId: "listed-8-15-26",
    live: "2026-08-15",
    dateLabel: "August 15, 2026",
    title: "Largest US states, by total area",
    metric: "Area",
    hi: "Largest",
    lo: "Smallest",
    source: "U.S. Census Bureau state area measurements",
    items: [
      { t: "Alaska", v: "665,384 sq mi", d: "Larger than Texas, California and Montana put together." },
      { t: "Texas", v: "268,596 sq mi", d: "El Paso is closer to the California line than it is to Houston." },
      { t: "California", v: "163,695 sq mi", d: "Runs about 800 miles from the Oregon border down to Mexico." },
      { t: "Montana", v: "147,040 sq mi", d: "Fourth biggest state, with fewer residents than the city of Houston." },
      { t: "Nevada", v: "110,572 sq mi", d: "The federal government owns roughly 80 percent of the land." },
      { t: "Michigan", v: "96,714 sq mi", d: "Its total area counts a vast share of the Great Lakes as state water." },
      { t: "Florida", v: "65,758 sq mi", d: "Water covers more than a tenth of it, from the Everglades to the Keys." },
      { t: "New York", v: "54,555 sq mi", d: "Adirondack Park alone covers more ground than Yellowstone." },
    ],
  },
  {
    num: 21,
    quizId: "listed-8-16-26",
    live: "2026-08-16",
    dateLabel: "August 16, 2026",
    sunday: true,
    title: "Largest sports stadiums in the world, by capacity",
    metric: "Capacity",
    hi: "Biggest",
    lo: "Smallest",
    source: "Published stadium capacities, July 2026",
    items: [
      { t: "Narendra Modi Stadium", v: "132,000", d: "Ahmedabad rebuilt its cricket ground in 2020 as the largest venue on earth." },
      { t: "Rungrado May Day Stadium", v: "113,281", d: "The 16 arch bowl in Pyongyang stages mass gymnastics far more often than sport." },
      { t: "Michigan Stadium", v: "107,601", d: "The Big House sits mostly below ground level, which hides its scale outside." },
      { t: "Beaver Stadium", v: "106,572", d: "Penn State fills it eight times a year in the middle of rural Pennsylvania." },
      { t: "Ohio Stadium", v: "102,780", d: "Ohio State has sold out the Horseshoe in Columbus for every game since 1964." },
      { t: "Melbourne Cricket Ground", v: "100,024", d: "Home of the Boxing Day Test, Australian rules football, and the 1956 Olympics." },
      { t: "FNB Stadium", v: "94,736", d: "Johannesburg's calabash shaped ground hosted the 2010 World Cup final." },
      { t: "Wembley Stadium", v: "90,000", d: "Its 133 metre arch replaced the old twin towers when the ground reopened in 2007." },
      { t: "MetLife Stadium", v: "82,500", d: "The New Jersey home of the Giants and Jets staged the 2026 World Cup final." },
    ],
  },
  {
    num: 22,
    quizId: "listed-8-17-26",
    live: "2026-08-17",
    dateLabel: "August 17, 2026",
    title: "Most men's major golf championships won",
    metric: "Majors",
    hi: "Most",
    lo: "Fewest",
    source: "Major championship records, April 2026",
    items: [
      { t: "Jack Nicklaus", v: "18", d: "Also finished runner-up in a major 19 times, a record nobody envies." },
      { t: "Tiger Woods", v: "15", d: "Won the 2008 U.S. Open on a stress fracture and a torn knee ligament." },
      { t: "Walter Hagen", v: "11", d: "Took five PGA Championships back when it was still a match play event." },
      { t: "Gary Player", v: "9", d: "Flew more than 15 million miles chasing tournaments around the world." },
      { t: "Tom Watson", v: "8", d: "Five came at the Open, and he nearly added a sixth at the age of 59." },
      { t: "Arnold Palmer", v: "7", d: "Never won the PGA Championship, the one major that always got away." },
      { t: "Phil Mickelson", v: "6", d: "Became the oldest major winner in history at the 2021 PGA, aged 50." },
      { t: "Seve Ballesteros", v: "5", d: "Won the 1979 Open at 22 after driving into a car park and getting up and down." },
    ],
  },
  {
    num: 23,
    quizId: "listed-8-18-26",
    live: "2026-08-18",
    dateLabel: "August 18, 2026",
    title: "Largest companies by 2024 revenue",
    metric: "Revenue",
    hi: "Most",
    lo: "Least",
    source: "Fortune Global 500 2025, fiscal 2024 revenue",
    items: [
      { t: "Walmart", v: "$681.0B", d: "Has topped the Fortune Global 500 for most of the past two decades." },
      { t: "Amazon", v: "$638.0B", d: "Gaining on Walmart by tens of billions a year and closing the gap fast." },
      { t: "Saudi Aramco", v: "$480.2B", d: "State owned, and its 2019 flotation was the largest IPO ever held." },
      { t: "UnitedHealth Group", v: "$400.3B", d: "A health insurer that quietly out-earns Apple, which few people guess." },
      { t: "Apple", v: "$391.0B", d: "Takes in roughly one dollar for every two that Amazon does." },
      { t: "Toyota Motor", v: "$315.1B", d: "Sells over 10 million vehicles a year, more than any other carmaker." },
      { t: "Costco Wholesale", v: "$254.5B", d: "Membership fees are a sliver of this figure but most of the actual profit." },
      { t: "Microsoft", v: "$245.1B", d: "Sits below a warehouse chain, because software carries far higher margins." },
    ],
  },
  {
    num: 24,
    quizId: "listed-8-19-26",
    live: "2026-08-19",
    dateLabel: "August 19, 2026",
    title: "Longest suspension bridges, by main span",
    metric: "Main span",
    hi: "Longest",
    lo: "Shortest",
    source: "Published bridge engineering records",
    items: [
      { t: "Akashi Kaikyo (Japan)", v: "1,991 m", d: "The 1995 Kobe earthquake widened it by nearly a meter during construction." },
      { t: "Great Belt East (Denmark)", v: "1,624 m", d: "Its towers are the highest point in all of Denmark." },
      { t: "Humber Bridge (England)", v: "1,410 m", d: "Held the world record for 17 years after opening in 1981." },
      { t: "Verrazzano-Narrows (NYC)", v: "1,298 m", d: "The towers lean very slightly apart to allow for the curve of the Earth." },
      { t: "Golden Gate (San Francisco)", v: "1,280 m", d: "Painted international orange so it stays visible in Pacific fog." },
      { t: "Mackinac Bridge (Michigan)", v: "1,158 m", d: "You can walk across it just one day a year, on Labor Day morning." },
      { t: "George Washington (NYC)", v: "1,067 m", d: "The busiest motor vehicle bridge in the world." },
      { t: "Brooklyn Bridge", v: "486 m", d: "When it opened in 1883 it was half again longer than any span before it." },
    ],
  },
  {
    num: 25,
    quizId: "listed-8-20-26",
    live: "2026-08-20",
    dateLabel: "August 20, 2026",
    title: "Highest-grossing concert tours of all time",
    metric: "Gross",
    hi: "Biggest",
    lo: "Smallest",
    source: "Billboard Boxscore",
    items: [
      { t: "Taylor Swift, The Eras Tour", v: "$2,078M", d: "The first tour ever to gross more than a billion dollars, then it doubled that." },
      { t: "Elton John, Farewell Tour", v: "$939M", d: "Three hundred and thirty shows across five years before he retired from the road." },
      { t: "Ed Sheeran, Divide Tour", v: "$776M", d: "One man, a guitar and a loop pedal filling stadiums for 255 nights." },
      { t: "U2, 360 Tour", v: "$736M", d: "The claw stage cost so much that the tour needed a full year to break even." },
      { t: "Harry Styles, Love On Tour", v: "$617M", d: "He played fifteen straight nights at Madison Square Garden on this run." },
      { t: "Beyonce, Renaissance Tour", v: "$580M", d: "Fifty-six shows, and it still outgrossed tours three times its length." },
      { t: "The Rolling Stones, A Bigger Bang", v: "$558M", d: "They were already in their sixties when this two-year run began." },
      { t: "AC/DC, Black Ice Tour", v: "$442M", d: "Their first tour in eight years, and it sold out stadiums on four continents." },
    ],
  },
  {
    num: 26,
    quizId: "listed-8-21-26",
    live: "2026-08-21",
    dateLabel: "August 21, 2026",
    title: "Most career passing yards by a retired NFL quarterback",
    metric: "Pass yards",
    hi: "Most",
    lo: "Fewest",
    source: "Career passing leaders, through the 2025 NFL season",
    items: [
      { t: "Tom Brady", v: "89,214", d: "Drafted 199th overall, behind six other quarterbacks in the 2000 class." },
      { t: "Drew Brees", v: "80,358", d: "Miami passed on him over doubts that his shoulder would ever recover." },
      { t: "Peyton Manning", v: "71,940", d: "Missed an entire season after neck surgery and still edged out Favre." },
      { t: "Brett Favre", v: "71,838", d: "Started 297 consecutive games, the great durability record at the position." },
      { t: "Ben Roethlisberger", v: "64,088", d: "Won all 13 of his regular season starts as a rookie in 2004." },
      { t: "Matt Ryan", v: "62,792", d: "Built a 28 to 3 lead in a Super Bowl and somehow lost the game." },
      { t: "Dan Marino", v: "61,361", d: "Held this record for years and never won a Super Bowl ring." },
      { t: "Eli Manning", v: "57,023", d: "Beat an unbeaten New England in a Super Bowl, then beat them again four years on." },
    ],
  },
  {
    num: 27,
    quizId: "listed-8-22-26",
    live: "2026-08-22",
    dateLabel: "August 22, 2026",
    title: "Famous skyscrapers, by architectural height",
    metric: "Height",
    hi: "Tallest",
    lo: "Shortest",
    source: "CTBUH Skyscraper Center",
    items: [
      { t: "Burj Khalifa", v: "828 m", d: "So tall that people on upper floors break their Ramadan fast minutes later." },
      { t: "Shanghai Tower", v: "632 m", d: "Its glass skin twists 120 degrees to cut the wind load on the frame." },
      { t: "Makkah Royal Clock Tower", v: "601 m", d: "Carries a clock face 43 metres across, the largest anywhere in the world." },
      { t: "One World Trade Center", v: "541 m", d: "Its height in feet, 1,776, marks the year of American independence." },
      { t: "Taipei 101", v: "508 m", d: "A 660 tonne steel pendulum hangs inside to steady the tower in typhoons." },
      { t: "Petronas Twin Towers", v: "452 m", d: "Took the world title in 1998 on spire height, over a taller roofed rival." },
      { t: "Empire State Building", v: "381 m", d: "Its mast was built to moor airships, a plan dropped after one attempt." },
      { t: "The Shard", v: "306 m", d: "The tallest in western Europe, shaped to look like a splinter of glass." },
    ],
  },
  {
    num: 28,
    quizId: "listed-8-23-26",
    live: "2026-08-23",
    dateLabel: "August 23, 2026",
    sunday: true,
    title: "Melting points of everyday metals",
    metric: "Melts at",
    hi: "Highest",
    lo: "Lowest",
    source: "CRC Handbook values via the Royal Society of Chemistry",
    items: [
      { t: "Tungsten", v: "3,414 C", d: "The reason it was the filament inside every old incandescent light bulb." },
      { t: "Platinum", v: "1,768 C", d: "Rarer than gold, and it needs a far fiercer flame to work at the bench." },
      { t: "Iron", v: "1,538 C", d: "Blast furnaces run hotter than this, which is what makes cast iron possible." },
      { t: "Copper", v: "1,085 C", d: "Melts above gold, which catches out almost everyone who guesses." },
      { t: "Gold", v: "1,064 C", d: "Its low melting point is why goldsmithing is among the oldest crafts." },
      { t: "Silver", v: "962 C", d: "Used to fix a defining point on the international temperature scale." },
      { t: "Aluminium", v: "660 C", d: "Once cost more than gold, until cheap electricity made smelting easy." },
      { t: "Lead", v: "327 C", d: "Low enough for a camp fire to melt it, which is how bullets were cast." },
      { t: "Tin", v: "232 C", d: "The lowest here, which is why solder has always been built around it." },
    ],
  },
];
