// Puzzle data for Axiom, the daily rule-induction game. Imported ONLY by the
// server page (app/axiom/page.js), which filters live<=today before passing
// boards to the client, so future boards never ship to the browser bundle.
//
// A board is 24 word tiles (Sunday 28) and five candidate rules (Sunday seven).
// Exactly ONE candidate is consistent with every tile. Three tiles open green
// and two open red; the player spends a test budget flipping more, then names
// the rule.
//
// LEAK GUARD: no board stores which rule is the answer. Each tile carries its
// verdict (t) because the board has to answer a test locally, and the client
// derives the answer the same way the generator proved it unique: it evaluates
// every candidate spec against every tile and keeps the one that agrees
// everywhere. Rule specs are DATA ({ k: 'alpha' }, { k: 'len', n: 6 }); the
// evaluator and the human-readable labels both live in RULES in AxiomClient.
//
// Every board is machine-verified (scripts/verify-axiom.mjs) to satisfy:
//   C1 exactly one candidate is consistent with the whole board
//   C2 every candidate calls all three given greens true, so the gift greens
//      eliminate nothing and each rule starts alive
//   C3 the given reds kill one or two candidates, never the answer
//   C4 at least two live decoys remain after the reds, each exposed by >= 2
//      testable tiles
//   C5 at least six testable tiles where every live decoy agrees with the
//      truth (the traps: testing one teaches nothing)
//   C6 perfect is exactly 2, so no single tile can split the field on its own
// and, from board 7 on (the v2 generator, 2026-07-29):
//   C7 at most one "no letter X" candidate (two on Sunday) and one "exactly N
//      letters" candidate, so the field is not padded with rules that are never
//      the answer
//   C8 at least 8 informative tiles on a weekday, 10 on Sunday
//   C9 perfect-2 pairs are >= 12% of all tile pairs (9% Sunday), so the splitting
//      pair is findable rather than a needle
//   C10 across the bank: the answer is spread over the candidate slots, and no
//      common rule kind is a free cross-out. Candidate order is shuffled per
//      board, and the topic / hidden-word rules are decoys about as often as
//      they are the answer.
//   C11 no near-miss tiles: on a board carrying a set or hidden-word rule, no
//      tile may be a word a reasonable person would classify INTO that set when
//      the array leaves it out. The rules no longer print their array, so the
//      player supplies the knowledge, and it has to be the obvious kind. Boards
//      live before 2026-08-09 are exempt (already played): #2 GLASSES and #12
//      BASSES both hide ASS, the donkey, which HIDDEN.animal does not list.
// Boards 1-6 predate these and are frozen; the verifier exempts them.
// Validate with scripts/verify-axiom.mjs after ANY edit.
export const PUZZLES = [
  {
    num: 1, quizId: 'axiom-7-24-26', live: '2026-07-24', dateLabel: 'July 24, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'dbl' }, { k: 'len', n: 6 }, { k: 'startvowel' }, { k: 'vowels', n: 2 }, { k: 'alpha' }],
    tiles: [
      { w: 'BEER', t: 1 }, { w: 'VOLUMES', t: 0 }, { w: 'FACED', t: 0 }, { w: 'BANNED', t: 0 },
      { w: 'PREVIEW', t: 0, g: 1 }, { w: 'EFFORT', t: 1, g: 1 }, { w: 'TRASHCAN', t: 0 }, { w: 'BEGINS', t: 1 },
      { w: 'FILLS', t: 1 }, { w: 'PINCHES', t: 0 }, { w: 'IDIOM', t: 0 }, { w: 'ACCEPT', t: 1 },
      { w: 'FALSE', t: 0, g: 1 }, { w: 'LUNCH', t: 0 }, { w: 'QUARTER', t: 0 }, { w: 'FLOATING', t: 0 },
      { w: 'ACCENT', t: 1, g: 1 }, { w: 'ABORT', t: 1 }, { w: 'HATE', t: 0 }, { w: 'TRAIL', t: 0 },
      { w: 'LOSS', t: 1 }, { w: 'ACCESS', t: 1, g: 1 }, { w: 'RAISES', t: 0 }, { w: 'LOOP', t: 1 },
    ],
  },
  {
    num: 2, quizId: 'axiom-7-25-26', live: '2026-07-25', dateLabel: 'July 25, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'nolet', c: 'E' }, { k: 'onevowel' }, { k: 'nolet', c: 'A' }, { k: 'hides', set: 'animal' }, { k: 'norepeat' }],
    tiles: [
      { w: 'FANTASY', t: 1 }, { w: 'NULL', t: 0 }, { w: 'DREADING', t: 0, g: 1 }, { w: 'OPTIONAL', t: 0 },
      { w: 'IMAGINES', t: 0 }, { w: 'REPEATS', t: 0 }, { w: 'RELATED', t: 0 }, { w: 'RAPE', t: 1 },
      { w: 'STARTLED', t: 0 }, { w: 'RAMPANT', t: 1 }, { w: 'DREADED', t: 0 }, { w: 'GLASSES', t: 0 },
      { w: 'BOWL', t: 1, g: 1 }, { w: 'RATIOS', t: 1 }, { w: 'THEN', t: 1 }, { w: 'DISAGREE', t: 0 },
      { w: 'PIGS', t: 1, g: 1 }, { w: 'NETWORK', t: 0 }, { w: 'HEAVEN', t: 0 }, { w: 'COWS', t: 1, g: 1 },
      { w: 'CATS', t: 1 }, { w: 'TAPES', t: 1 }, { w: 'ATOM', t: 0 }, { w: 'CHANGING', t: 0, g: 1 },
    ],
  },
  {
    num: 3, quizId: 'axiom-7-26-26', live: '2026-07-26', dateLabel: 'July 26, 2026', sunday: true,
    budget: 7,
    rules: [{ k: 'vowels', n: 2 }, { k: 'alpha' }, { k: 'dbl' }, { k: 'nolet', c: 'S' }, { k: 'onevowel' }, { k: 'nolet', c: 'A' }, { k: 'nolet', c: 'E' }],
    tiles: [
      { w: 'PASSWORD', t: 1 }, { w: 'HEAR', t: 0, g: 1 }, { w: 'INERTIA', t: 0 }, { w: 'LOOP', t: 1, g: 1 },
      { w: 'WAIT', t: 0 }, { w: 'PROMPTED', t: 0 }, { w: 'REST', t: 0 }, { w: 'NEEDED', t: 1 },
      { w: 'CORRIDOR', t: 1 }, { w: 'SOONEST', t: 1 }, { w: 'WHEREAS', t: 0 }, { w: 'FLOOR', t: 1, g: 1 },
      { w: 'OFFICERS', t: 1 }, { w: 'WORRIED', t: 1 }, { w: 'AIMED', t: 0 }, { w: 'EGOS', t: 0 },
      { w: 'MALES', t: 0 }, { w: 'ATTRACTS', t: 1 }, { w: 'SPEED', t: 1 }, { w: 'FLOPPY', t: 1 },
      { w: 'READY', t: 0 }, { w: 'TAKEN', t: 0 }, { w: 'PLATE', t: 0 }, { w: 'CLAIMED', t: 0 },
      { w: 'SMASHED', t: 0 }, { w: 'DOOR', t: 1, g: 1 }, { w: 'MEANT', t: 0 }, { w: 'ARGUED', t: 0, g: 1 },
    ],
  },
  {
    num: 4, quizId: 'axiom-7-27-26', live: '2026-07-27', dateLabel: 'July 27, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'nolet', c: 'A' }, { k: 'onevowel' }, { k: 'len', n: 5 }, { k: 'vowels', n: 2 }, { k: 'alpha' }],
    tiles: [
      { w: 'STUCK', t: 1 }, { w: 'COLLATE', t: 0 }, { w: 'APPOINT', t: 0 }, { w: 'DOORS', t: 1, g: 1 },
      { w: 'FIRST', t: 1 }, { w: 'BEERS', t: 1, g: 1 }, { w: 'COPY', t: 1 }, { w: 'BELIEVES', t: 0 },
      { w: 'FLOOR', t: 1, g: 1 }, { w: 'FAIRLY', t: 0 }, { w: 'DIRTY', t: 1 }, { w: 'IMAGES', t: 0, g: 1 },
      { w: 'LORRY', t: 1 }, { w: 'DEEM', t: 1 }, { w: 'LOWERS', t: 0 }, { w: 'ALMOST', t: 0 },
      { w: 'TAKE', t: 0 }, { w: 'GUARD', t: 0 }, { w: 'WIVE', t: 0 }, { w: 'SWEARS', t: 0 },
      { w: 'INPUTS', t: 0 }, { w: 'QUOTED', t: 0 }, { w: 'BRICK', t: 1 }, { w: 'MINDLESS', t: 0, g: 1 },
    ],
  },
  {
    num: 5, quizId: 'axiom-7-28-26', live: '2026-07-28', dateLabel: 'July 28, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'vowels', n: 3 }, { k: 'endvowel' }, { k: 'nolet', c: 'A' }, { k: 'sameends' }, { k: 'len', n: 7 }],
    tiles: [
      { w: 'TRACING', t: 0 }, { w: 'EXPENSE', t: 1, g: 1 }, { w: 'EXPLODE', t: 1 }, { w: 'LENSES', t: 0 },
      { w: 'PERMITS', t: 0, g: 1 }, { w: 'CYCLIST', t: 0 }, { w: 'HASSLE', t: 0 }, { w: 'SPOILS', t: 0 },
      { w: 'DRAINED', t: 1 }, { w: 'ENFORCE', t: 1 }, { w: 'BECAME', t: 1 }, { w: 'IMMENSE', t: 1 },
      { w: 'JUST', t: 0 }, { w: 'ESSENCE', t: 1, g: 1 }, { w: 'NOTION', t: 1 }, { w: 'DUCKS', t: 0 },
      { w: 'PREDICT', t: 0 }, { w: 'GOLDEN', t: 0 }, { w: 'STOLEN', t: 0 }, { w: 'WORLDS', t: 0 },
      { w: 'AGENDA', t: 1 }, { w: 'EXCLUDE', t: 1, g: 1 }, { w: 'TRUCKS', t: 0, g: 1 }, { w: 'COPYING', t: 0 },
    ],
  },
  {
    num: 6, quizId: 'axiom-7-29-26', live: '2026-07-29', dateLabel: 'July 29, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'len', n: 5 }, { k: 'hides', set: 'body' }, { k: 'startvowel' }, { k: 'nolet', c: 'S' }, { k: 'vowels', n: 2 }],
    tiles: [
      { w: 'OBSERVES', t: 0 }, { w: 'COOKIES', t: 0 }, { w: 'MOMENT', t: 0 }, { w: 'RESTRICT', t: 0 },
      { w: 'HORRIFIC', t: 0, g: 1 }, { w: 'SWEAR', t: 1 }, { w: 'BREEZE', t: 0 }, { w: 'EARS', t: 1 },
      { w: 'EARLY', t: 1, g: 1 }, { w: 'PROFIT', t: 0 }, { w: 'EARNS', t: 1 }, { w: 'APPEARS', t: 1 },
      { w: 'GLOW', t: 0 }, { w: 'FIXED', t: 0 }, { w: 'EARTH', t: 1, g: 1 }, { w: 'CRAWLED', t: 0 },
      { w: 'PARSING', t: 0, g: 1 }, { w: 'ALARM', t: 1, g: 1 }, { w: 'LIVELY', t: 0 }, { w: 'MENTALLY', t: 0 },
      { w: 'WARMS', t: 1 }, { w: 'TACK', t: 0 }, { w: 'DEGRADE', t: 0 }, { w: 'ARMED', t: 1 },
    ],
  },
  {
    num: 7, quizId: 'axiom-7-30-26', live: '2026-07-30', dateLabel: 'July 30, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'nolet', c: 'C' }, { k: 'in', set: 'mammal' }, { k: 'norepeat' }, { k: 'vowels', n: 2 }, { k: 'endvowel' }],
    tiles: [
      { w: 'GUPPY', t: 0 }, { w: 'PANDA', t: 1 }, { w: 'EEL', t: 0 }, { w: 'PELICAN', t: 0 },
      { w: 'HAMSTER', t: 1 }, { w: 'MOLE', t: 1, g: 1 }, { w: 'TIGER', t: 1 }, { w: 'WREN', t: 0, g: 1 },
      { w: 'COD', t: 0 }, { w: 'WHALE', t: 1 }, { w: 'RABBIT', t: 1 }, { w: 'MINNOW', t: 0 },
      { w: 'WALRUS', t: 1 }, { w: 'CROW', t: 0 }, { w: 'CONDOR', t: 0 }, { w: 'HARE', t: 1, g: 1 },
      { w: 'DUCK', t: 0 }, { w: 'SPARROW', t: 0 }, { w: 'STORK', t: 0 }, { w: 'DEER', t: 1 },
      { w: 'TOUCAN', t: 0, g: 1 }, { w: 'GIRAFFE', t: 1 }, { w: 'RHINO', t: 1 }, { w: 'HORSE', t: 1, g: 1 },
    ],
  },
  {
    num: 8, quizId: 'axiom-7-31-26', live: '2026-07-31', dateLabel: 'July 31, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'norepeat' }, { k: 'vowels', n: 1 }, { k: 'hides', set: 'animal' }, { k: 'onevowel' }, { k: 'nolet', c: 'E' }],
    tiles: [
      { w: 'SNAIL', t: 1 }, { w: 'RATS', t: 1, g: 1 }, { w: 'GUILT', t: 1 }, { w: 'OFFENDERS', t: 0 },
      { w: 'ALIGNED', t: 0 }, { w: 'BLUE', t: 0 }, { w: 'WELFARE', t: 0 }, { w: 'SUBMIT', t: 1 },
      { w: 'CITIES', t: 0 }, { w: 'BALANCE', t: 0, g: 1 }, { w: 'PENNY', t: 0, g: 1 }, { w: 'DOING', t: 1 },
      { w: 'HOPELESS', t: 0 }, { w: 'PURPOSE', t: 0 }, { w: 'SQUAD', t: 1 }, { w: 'BACTERIUM', t: 0 },
      { w: 'UMBRELLA', t: 0 }, { w: 'RECYCLES', t: 0 }, { w: 'ADVERSELY', t: 0 }, { w: 'WANTS', t: 1, g: 1 },
      { w: 'GATES', t: 0 }, { w: 'QUIETLY', t: 0 }, { w: 'PANTS', t: 1, g: 1 }, { w: 'MATERIAL', t: 0 },
    ],
  },
  {
    num: 9, quizId: 'axiom-8-1-26', live: '2026-08-01', dateLabel: 'August 1, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'norepeat' }, { k: 'len', n: 7 }, { k: 'twinvowel' }, { k: 'vowels', n: 3 }, { k: 'nolet', c: 'S' }],
    tiles: [
      { w: 'OBEYS', t: 0 }, { w: 'KING', t: 0 }, { w: 'EQUIPS', t: 1 }, { w: 'FAINTER', t: 1 },
      { w: 'TELEPHONE', t: 0 }, { w: 'FORTH', t: 0 }, { w: 'EXPLAIN', t: 1, g: 1 }, { w: 'MERGING', t: 0 },
      { w: 'FORMERLY', t: 0 }, { w: 'HEARTS', t: 0 }, { w: 'MAKING', t: 0 }, { w: 'FREELY', t: 0 },
      { w: 'MATE', t: 0, g: 1 }, { w: 'GRADUATE', t: 0 }, { w: 'HEAR', t: 0 }, { w: 'PRODUCE', t: 1 },
      { w: 'BEATING', t: 1, g: 1 }, { w: 'THEREBY', t: 0 }, { w: 'FROGS', t: 0, g: 1 }, { w: 'CRUISING', t: 1 },
      { w: 'ECHOING', t: 1, g: 1 }, { w: 'SUMMED', t: 0 }, { w: 'JOURNAL', t: 1 }, { w: 'RETAIN', t: 1 },
    ],
  },
  {
    num: 10, quizId: 'axiom-8-2-26', live: '2026-08-02', dateLabel: 'August 2, 2026', sunday: true,
    budget: 7,
    rules: [{ k: 'dbl' }, { k: 'nolet', c: 'R' }, { k: 'vowels', n: 2 }, { k: 'len', n: 5 }, { k: 'nolet', c: 'G' }, { k: 'onevowel' }, { k: 'twinvowel' }],
    tiles: [
      { w: 'APART', t: 0 }, { w: 'INDUCING', t: 0 }, { w: 'QUEUING', t: 0 }, { w: 'DETECTOR', t: 0 },
      { w: 'ASCEND', t: 0 }, { w: 'OPEN', t: 0, g: 1 }, { w: 'INCHES', t: 0 }, { w: 'ENEMY', t: 0 },
      { w: 'UNDERTAKE', t: 0, g: 1 }, { w: 'STEEL', t: 1, g: 1 }, { w: 'VANISHED', t: 0 }, { w: 'INJURY', t: 0 },
      { w: 'CHEEK', t: 1, g: 1 }, { w: 'DIRECTOR', t: 0 }, { w: 'REQUESTS', t: 0 }, { w: 'RESPONDED', t: 0 },
      { w: 'MOTTO', t: 1 }, { w: 'SINKS', t: 0 }, { w: 'WORRY', t: 1 }, { w: 'SEEMS', t: 1, g: 1 },
      { w: 'WASHED', t: 0 }, { w: 'LOOSELY', t: 1 }, { w: 'INTEGRITY', t: 0 }, { w: 'SAID', t: 0 },
      { w: 'KEEPING', t: 1 }, { w: 'TRAVELING', t: 0 }, { w: 'KINDS', t: 0 }, { w: 'DRESS', t: 1 },
    ],
  },
  {
    num: 11, quizId: 'axiom-8-3-26', live: '2026-08-03', dateLabel: 'August 3, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'len', n: 6 }, { k: 'onevowel' }, { k: 'nolet', c: 'I' }, { k: 'endvowel' }, { k: 'in', set: 'fruit' }],
    tiles: [
      { w: 'GNOCCHI', t: 0 }, { w: 'PRESERVE', t: 1 }, { w: 'HONEY', t: 0, g: 1 }, { w: 'STEAK', t: 0 },
      { w: 'TURNIP', t: 0 }, { w: 'RADISH', t: 0 }, { w: 'THYME', t: 1 }, { w: 'LYCHEE', t: 1, g: 1 },
      { w: 'LEMON', t: 0 }, { w: 'NECTAR', t: 0 }, { w: 'SUSHI', t: 0 }, { w: 'BISCUIT', t: 0 },
      { w: 'PAPRIKA', t: 0 }, { w: 'PAPAYA', t: 1, g: 1 }, { w: 'PASTA', t: 1 }, { w: 'FIG', t: 1 },
      { w: 'APRICOT', t: 0 }, { w: 'DUMPLING', t: 0 }, { w: 'BANANA', t: 1, g: 1 }, { w: 'SOUP', t: 0 },
      { w: 'BREAD', t: 0 }, { w: 'MARZIPAN', t: 0 }, { w: 'RAVIOLI', t: 0 }, { w: 'SORBET', t: 0, g: 1 },
    ],
  },
  {
    num: 12, quizId: 'axiom-8-4-26', live: '2026-08-04', dateLabel: 'August 4, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'nolet', c: 'E' }, { k: 'onevowel' }, { k: 'hides', set: 'animal' }, { k: 'norepeat' }, { k: 'vowels', n: 1 }],
    tiles: [
      { w: 'DEGRADES', t: 0 }, { w: 'RAMPANT', t: 1 }, { w: 'WOOD', t: 0 }, { w: 'ETERNITY', t: 0 },
      { w: 'JUNIOR', t: 0, g: 1 }, { w: 'INJURED', t: 0, g: 1 }, { w: 'BATCH', t: 1, g: 1 }, { w: 'HELPLESS', t: 0 },
      { w: 'BASSES', t: 0 }, { w: 'MOTION', t: 0 }, { w: 'UNRELATED', t: 0 }, { w: 'PLANTS', t: 1, g: 1 },
      { w: 'DEPEND', t: 0 }, { w: 'AXIS', t: 0 }, { w: 'HENCE', t: 1 }, { w: 'STEER', t: 0 },
      { w: 'FEWER', t: 1 }, { w: 'FEVER', t: 0 }, { w: 'BATH', t: 1, g: 1 }, { w: 'CONGEST', t: 0 },
      { w: 'EMPTYING', t: 0 }, { w: 'BEER', t: 1 }, { w: 'BLATANT', t: 1 }, { w: 'ESTABLISH', t: 0 },
    ],
  },
  {
    num: 13, quizId: 'axiom-8-5-26', live: '2026-08-05', dateLabel: 'August 5, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'vowels', n: 1 }, { k: 'norepeat' }, { k: 'len', n: 5 }, { k: 'nolet', c: 'C' }, { k: 'onevowel' }],
    tiles: [
      { w: 'SEVEN', t: 1 }, { w: 'CLINIC', t: 0 }, { w: 'LISTING', t: 0 }, { w: 'RENDERED', t: 0 },
      { w: 'ATHEISM', t: 0 }, { w: 'REGIONAL', t: 0 }, { w: 'YOURSELF', t: 0 }, { w: 'ARRAY', t: 1 },
      { w: 'GRABS', t: 1 }, { w: 'DRIFT', t: 1, g: 1 }, { w: 'SITTING', t: 0 }, { w: 'PLANT', t: 1 },
      { w: 'INCURRING', t: 0 }, { w: 'TURNS', t: 1, g: 1 }, { w: 'DEEDS', t: 1 }, { w: 'SWING', t: 1, g: 1 },
      { w: 'LIBRARIAN', t: 0, g: 1 }, { w: 'WHERE', t: 1 }, { w: 'CASTING', t: 0, g: 1 }, { w: 'SINE', t: 0 },
      { w: 'NEVER', t: 1 }, { w: 'EVOLVED', t: 0 }, { w: 'SENTIMENT', t: 0 }, { w: 'ELEMENTS', t: 0 },
    ],
  },
  {
    num: 14, quizId: 'axiom-8-6-26', live: '2026-08-06', dateLabel: 'August 6, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'nolet', c: 'H' }, { k: 'norepeat' }, { k: 'vowels', n: 1 }, { k: 'len', n: 4 }, { k: 'onevowel' }],
    tiles: [
      { w: 'BATHROOM', t: 0 }, { w: 'CRYING', t: 1 }, { w: 'FIGHTER', t: 0 }, { w: 'DEAL', t: 1 },
      { w: 'REACHED', t: 0 }, { w: 'DRAW', t: 1, g: 1 }, { w: 'ADOPTS', t: 1 }, { w: 'DULL', t: 1 },
      { w: 'STAY', t: 1, g: 1 }, { w: 'VARIED', t: 1 }, { w: 'SOMEWHERE', t: 0, g: 1 }, { w: 'WORKINGS', t: 1 },
      { w: 'HOSTILE', t: 0 }, { w: 'SUIT', t: 1 }, { w: 'GRID', t: 1 }, { w: 'SAID', t: 1 },
      { w: 'SWITCHED', t: 0 }, { w: 'HOUSED', t: 0 }, { w: 'DARK', t: 1, g: 1 }, { w: 'DUMP', t: 1 },
      { w: 'LISP', t: 1 }, { w: 'TIME', t: 1 }, { w: 'CHECKS', t: 0, g: 1 }, { w: 'LIQUOR', t: 1 },
    ],
  },
  {
    num: 15, quizId: 'axiom-8-7-26', live: '2026-08-07', dateLabel: 'August 7, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'vowels', n: 2 }, { k: 'in', set: 'country' }, { k: 'norepeat' }, { k: 'nolet', c: 'M' }, { k: 'endvowel' }],
    tiles: [
      { w: 'HAMBURG', t: 1 }, { w: 'ROME', t: 1 }, { w: 'SEATTLE', t: 0, g: 1 }, { w: 'VERONA', t: 0 },
      { w: 'PERU', t: 1, g: 1 }, { w: 'CHILE', t: 1, g: 1 }, { w: 'FRESNO', t: 1 }, { w: 'SALZBURG', t: 1 },
      { w: 'HANOI', t: 0 }, { w: 'BOULDER', t: 0 }, { w: 'CHENNAI', t: 0 }, { w: 'OSAKA', t: 0 },
      { w: 'JAKARTA', t: 0 }, { w: 'OMAHA', t: 0 }, { w: 'BRISTOL', t: 1 }, { w: 'BORDEAUX', t: 0 },
      { w: 'COLOGNE', t: 0, g: 1 }, { w: 'HUNGARY', t: 1 }, { w: 'BRAZIL', t: 1 }, { w: 'PRAGUE', t: 0 },
      { w: 'HALIFAX', t: 0 }, { w: 'CUBA', t: 1, g: 1 }, { w: 'AUCKLAND', t: 0 }, { w: 'VALENCIA', t: 0 },
    ],
  },
  {
    num: 16, quizId: 'axiom-8-8-26', live: '2026-08-08', dateLabel: 'August 8, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'in', set: 'country' }, { k: 'nolet', c: 'L' }, { k: 'endvowel' }, { k: 'twinvowel' }, { k: 'vowels', n: 3 }],
    tiles: [
      { w: 'NEWARK', t: 0, g: 1 }, { w: 'CHENNAI', t: 1 }, { w: 'SAVANNAH', t: 0 }, { w: 'TUNIS', t: 0 },
      { w: 'GREECE', t: 1, g: 1 }, { w: 'DALLAS', t: 0 }, { w: 'ZURICH', t: 0 }, { w: 'BERLIN', t: 0 },
      { w: 'ITALY', t: 0, g: 1 }, { w: 'BUDAPEST', t: 0 }, { w: 'PERU', t: 0 }, { w: 'ACCRA', t: 0 },
      { w: 'RUSSIA', t: 1, g: 1 }, { w: 'POLAND', t: 0 }, { w: 'BRAZIL', t: 0 }, { w: 'CAIRO', t: 1 },
      { w: 'DETROIT', t: 1 }, { w: 'LIMA', t: 0 }, { w: 'EGYPT', t: 0 }, { w: 'ICELAND', t: 0 },
      { w: 'INDIA', t: 1, g: 1 }, { w: 'HALIFAX', t: 0 }, { w: 'CHINA', t: 0 }, { w: 'TOULOUSE', t: 1 },
    ],
  },
  {
    num: 17, quizId: 'axiom-8-9-26', live: '2026-08-09', dateLabel: 'August 9, 2026', sunday: true,
    budget: 7,
    rules: [{ k: 'nolet', c: 'P' }, { k: 'vowels', n: 2 }, { k: 'twinvowel' }, { k: 'dbl' }, { k: 'len', n: 4 }, { k: 'nolet', c: 'S' }, { k: 'onevowel' }],
    tiles: [
      { w: 'CIRCLES', t: 0 }, { w: 'UPGRADING', t: 0 }, { w: 'BEND', t: 1 }, { w: 'SPEEDS', t: 1 },
      { w: 'GAME', t: 0 }, { w: 'SPOOF', t: 1 }, { w: 'ORIGINALS', t: 0, g: 1 }, { w: 'PROOFS', t: 1 },
      { w: 'JACKET', t: 0 }, { w: 'TONES', t: 0 }, { w: 'GUYS', t: 1 }, { w: 'MAYOR', t: 0 },
      { w: 'KIDNAPS', t: 0 }, { w: 'NEEDLESS', t: 1 }, { w: 'POSTPONE', t: 0 }, { w: 'PARSE', t: 0 },
      { w: 'ITEMS', t: 0 }, { w: 'HABIT', t: 0, g: 1 }, { w: 'MUGS', t: 1 }, { w: 'VIRUSES', t: 0 },
      { w: 'WEDS', t: 1 }, { w: 'RUNS', t: 1 }, { w: 'MOOD', t: 1, g: 1 }, { w: 'COOL', t: 1, g: 1 },
      { w: 'DOOR', t: 1, g: 1 }, { w: 'EMULATE', t: 0 }, { w: 'MEETING', t: 0 }, { w: 'RAGE', t: 0 },
    ],
  },
  {
    num: 18, quizId: 'axiom-8-10-26', live: '2026-08-10', dateLabel: 'August 10, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'onevowel' }, { k: 'len', n: 4 }, { k: 'nolet', c: 'D' }, { k: 'norepeat' }, { k: 'hides', set: 'body' }],
    tiles: [
      { w: 'COMPETES', t: 0 }, { w: 'ARMY', t: 1, g: 1 }, { w: 'PITY', t: 1 }, { w: 'UNDERGONE', t: 0 },
      { w: 'BOBS', t: 0 }, { w: 'ENSURING', t: 0 }, { w: 'WIDE', t: 1 }, { w: 'KIDS', t: 1 },
      { w: 'BUSS', t: 0 }, { w: 'CONFLICTS', t: 0 }, { w: 'RESET', t: 0, g: 1 }, { w: 'AIDS', t: 1 },
      { w: 'SHIP', t: 1, g: 1 }, { w: 'SPOTTING', t: 0 }, { w: 'LIPS', t: 1 }, { w: 'SEES', t: 0 },
      { w: 'BOTHERED', t: 0 }, { w: 'BEER', t: 0 }, { w: 'LAKE', t: 1 }, { w: 'GENERATED', t: 0 },
      { w: 'MACHINERY', t: 1 }, { w: 'ARMS', t: 1, g: 1 }, { w: 'CLEVEREST', t: 0, g: 1 }, { w: 'FIXING', t: 0 },
    ],
  },
  {
    num: 19, quizId: 'axiom-8-11-26', live: '2026-08-11', dateLabel: 'August 11, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'len', n: 4 }, { k: 'onevowel' }, { k: 'norepeat' }, { k: 'nolet', c: 'C' }, { k: 'vowels', n: 1 }],
    tiles: [
      { w: 'ANCESTOR', t: 0, g: 1 }, { w: 'EXPLICIT', t: 0 }, { w: 'SARCASM', t: 0 }, { w: 'AGED', t: 1 },
      { w: 'RECORDED', t: 0 }, { w: 'PRODUCE', t: 0 }, { w: 'RIGHTLY', t: 1 }, { w: 'TIME', t: 1 },
      { w: 'COAL', t: 0 }, { w: 'COUNTING', t: 0 }, { w: 'TEND', t: 1, g: 1 }, { w: 'SYMPATHY', t: 1 },
      { w: 'CAGE', t: 0 }, { w: 'SORE', t: 1 }, { w: 'MUGS', t: 1, g: 1 }, { w: 'HACKS', t: 0 },
      { w: 'RECYCLE', t: 0 }, { w: 'POLITICS', t: 0 }, { w: 'CLEVER', t: 0, g: 1 }, { w: 'EXCEEDED', t: 0 },
      { w: 'HOLD', t: 1, g: 1 }, { w: 'LENDS', t: 1 }, { w: 'PATCH', t: 0 }, { w: 'SEARCH', t: 0 },
    ],
  },
  {
    num: 20, quizId: 'axiom-8-12-26', live: '2026-08-12', dateLabel: 'August 12, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'vowels', n: 3 }, { k: 'nolet', c: 'H' }, { k: 'in', set: 'ballsport' }, { k: 'twinvowel' }, { k: 'dbl' }],
    tiles: [
      { w: 'YACHTING', t: 0 }, { w: 'PETANQUE', t: 1 }, { w: 'FOOSBALL', t: 1, g: 1 }, { w: 'TUMBLING', t: 0 },
      { w: 'CANOEING', t: 0 }, { w: 'ROPING', t: 0 }, { w: 'ABSEILING', t: 0 }, { w: 'CROQUET', t: 1 },
      { w: 'JOGGING', t: 0 }, { w: 'SWIMMING', t: 0 }, { w: 'DISCUS', t: 0 }, { w: 'BOBSLEIGH', t: 0 },
      { w: 'DECATHLON', t: 0, g: 1 }, { w: 'KORFBALL', t: 1 }, { w: 'ROWING', t: 0 }, { w: 'SURFING', t: 0 },
      { w: 'CLIMBING', t: 0 }, { w: 'DIVING', t: 0 }, { w: 'BASEBALL', t: 1 }, { w: 'BOXING', t: 0, g: 1 },
      { w: 'ARCHERY', t: 0 }, { w: 'TREKKING', t: 0 }, { w: 'BILLIARDS', t: 1, g: 1 }, { w: 'SNOOKER', t: 1, g: 1 },
    ],
  },
  {
    num: 21, quizId: 'axiom-8-13-26', live: '2026-08-13', dateLabel: 'August 13, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'nolet', c: 'G' }, { k: 'vowels', n: 2 }, { k: 'altvc' }, { k: 'len', n: 5 }, { k: 'norepeat' }],
    tiles: [
      { w: 'PRESSURES', t: 0 }, { w: 'BONUS', t: 1, g: 1 }, { w: 'ARBITRARY', t: 0 }, { w: 'COMPILED', t: 0 },
      { w: 'BRANCH', t: 0 }, { w: 'METAPHOR', t: 0 }, { w: 'DONATION', t: 0 }, { w: 'DRAFTING', t: 1 },
      { w: 'ASSISTING', t: 0 }, { w: 'POSED', t: 1, g: 1 }, { w: 'CLOSER', t: 1 }, { w: 'SHONE', t: 1 },
      { w: 'INQUIRING', t: 0 }, { w: 'BLAST', t: 0 }, { w: 'PRACTICES', t: 0, g: 1 }, { w: 'LISTS', t: 0, g: 1 },
      { w: 'EXAMINED', t: 0 }, { w: 'MEASURED', t: 0 }, { w: 'DREADED', t: 0 }, { w: 'CELLS', t: 0 },
      { w: 'ORGAN', t: 1 }, { w: 'IGNORED', t: 0 }, { w: 'MALES', t: 1, g: 1 }, { w: 'NESTS', t: 0 },
    ],
  },
  {
    num: 22, quizId: 'axiom-8-14-26', live: '2026-08-14', dateLabel: 'August 14, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'onevowel' }, { k: 'alpha' }, { k: 'nolet', c: 'D' }, { k: 'vowels', n: 1 }, { k: 'len', n: 4 }],
    tiles: [
      { w: 'MOST', t: 1, g: 1 }, { w: 'DEEMS', t: 1 }, { w: 'DEPENDING', t: 0 }, { w: 'IRRITATE', t: 0, g: 1 },
      { w: 'STATES', t: 0 }, { w: 'STRANGE', t: 0 }, { w: 'BOOST', t: 1 }, { w: 'SHOUT', t: 0 },
      { w: 'HEEL', t: 0 }, { w: 'CREEP', t: 0 }, { w: 'IMPORTING', t: 0 }, { w: 'FEMALES', t: 0 },
      { w: 'RIDING', t: 0 }, { w: 'GLOW', t: 1, g: 1 }, { w: 'MANNING', t: 0 }, { w: 'DEEP', t: 1 },
      { w: 'BEER', t: 1 }, { w: 'COOKS', t: 0 }, { w: 'BILL', t: 1, g: 1 }, { w: 'BEATING', t: 0 },
      { w: 'LOOPS', t: 1 }, { w: 'FORTUNE', t: 0 }, { w: 'CONFRONT', t: 0 }, { w: 'CUBE', t: 0, g: 1 },
    ],
  },
  {
    num: 23, quizId: 'axiom-8-15-26', live: '2026-08-15', dateLabel: 'August 15, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'nolet', c: 'C' }, { k: 'vowels', n: 2 }, { k: 'len', n: 5 }, { k: 'in', set: 'mammal' }, { k: 'endvowel' }],
    tiles: [
      { w: 'HORSE', t: 1, g: 1 }, { w: 'PENGUIN', t: 0, g: 1 }, { w: 'PELICAN', t: 0 }, { w: 'CAMEL', t: 1 },
      { w: 'DOG', t: 0 }, { w: 'RAT', t: 0 }, { w: 'RHINO', t: 1, g: 1 }, { w: 'HERRING', t: 0 },
      { w: 'BADGER', t: 0 }, { w: 'ELK', t: 0, g: 1 }, { w: 'BASS', t: 0 }, { w: 'DONKEY', t: 0 },
      { w: 'EGRET', t: 1 }, { w: 'FALCON', t: 0 }, { w: 'WEASEL', t: 0 }, { w: 'TROUT', t: 1 },
      { w: 'MAGPIE', t: 0 }, { w: 'PANDA', t: 1, g: 1 }, { w: 'GIRAFFE', t: 0 }, { w: 'COD', t: 0 },
      { w: 'COW', t: 0 }, { w: 'MOOSE', t: 1 }, { w: 'WREN', t: 0 }, { w: 'LEOPARD', t: 0 },
    ],
  },
  {
    num: 24, quizId: 'axiom-8-16-26', live: '2026-08-16', dateLabel: 'August 16, 2026', sunday: true,
    budget: 7,
    rules: [{ k: 'len', n: 6 }, { k: 'vowels', n: 3 }, { k: 'twinvowel' }, { k: 'endvowel' }, { k: 'dbl' }, { k: 'nolet', c: 'H' }, { k: 'nolet', c: 'P' }],
    tiles: [
      { w: 'BLOB', t: 0 }, { w: 'VARIABLE', t: 1 }, { w: 'TWENTIETH', t: 1 }, { w: 'BAKED', t: 0 },
      { w: 'QUICKER', t: 1 }, { w: 'ACTOR', t: 0 }, { w: 'PREVAIL', t: 1 }, { w: 'RECEIVE', t: 1 },
      { w: 'PLANT', t: 0 }, { w: 'COFFEE', t: 1, g: 1 }, { w: 'CURRENT', t: 0 }, { w: 'COUPLES', t: 1 },
      { w: 'ACCORDS', t: 0 }, { w: 'UNITES', t: 0 }, { w: 'LESS', t: 0, g: 1 }, { w: 'SUITABLE', t: 1 },
      { w: 'TACKLING', t: 0 }, { w: 'HOLD', t: 0, g: 1 }, { w: 'BLACK', t: 0 }, { w: 'CUCKOO', t: 1, g: 1 },
      { w: 'BELL', t: 0 }, { w: 'TOLL', t: 0 }, { w: 'TEENAGE', t: 1 }, { w: 'BREEZE', t: 1, g: 1 },
      { w: 'DIAGRAMS', t: 1 }, { w: 'HEADLINE', t: 1 }, { w: 'CATTLE', t: 0 }, { w: 'MINDS', t: 0 },
    ],
  },
  {
    num: 25, quizId: 'axiom-8-17-26', live: '2026-08-17', dateLabel: 'August 17, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'nolet', c: 'O' }, { k: 'norepeat' }, { k: 'onevowel' }, { k: 'vowels', n: 1 }, { k: 'len', n: 4 }],
    tiles: [
      { w: 'UNSOUND', t: 0 }, { w: 'SCORING', t: 0, g: 1 }, { w: 'HOOKED', t: 0 }, { w: 'DOES', t: 0 },
      { w: 'SPIRIT', t: 1 }, { w: 'EXPECT', t: 1 }, { w: 'CAST', t: 1, g: 1 }, { w: 'PRODUCES', t: 0 },
      { w: 'GIFT', t: 1 }, { w: 'HALF', t: 1, g: 1 }, { w: 'JOKE', t: 0 }, { w: 'CRITIC', t: 1 },
      { w: 'BOARDS', t: 0 }, { w: 'EGOS', t: 0, g: 1 }, { w: 'PASS', t: 1 }, { w: 'LOGO', t: 0 },
      { w: 'FLOORS', t: 0 }, { w: 'ARCH', t: 1, g: 1 }, { w: 'DOORS', t: 0 }, { w: 'ROYALTIES', t: 0 },
      { w: 'DEEP', t: 1 }, { w: 'SHOOK', t: 0 }, { w: 'REPRESENT', t: 1 }, { w: 'POOL', t: 0 },
    ],
  },
  {
    num: 26, quizId: 'axiom-8-18-26', live: '2026-08-18', dateLabel: 'August 18, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'hides', set: 'number' }, { k: 'len', n: 6 }, { k: 'dbl' }, { k: 'nolet', c: 'L' }, { k: 'vowels', n: 2 }],
    tiles: [
      { w: 'DEDUCES', t: 0, g: 1 }, { w: 'CITE', t: 0 }, { w: 'LOGGED', t: 1 }, { w: 'TENNIS', t: 1, g: 1 },
      { w: 'SCHOOL', t: 1 }, { w: 'SELECTIVE', t: 0 }, { w: 'SHOWS', t: 0 }, { w: 'CEASES', t: 0 },
      { w: 'BLOCKS', t: 0 }, { w: 'LECTURES', t: 0 }, { w: 'WOODEN', t: 1 }, { w: 'ACCEPT', t: 1 },
      { w: 'BRAINS', t: 0 }, { w: 'CUTS', t: 0 }, { w: 'EATEN', t: 0 }, { w: 'EQUALITY', t: 0 },
      { w: 'FREQUENCY', t: 0 }, { w: 'DRAIN', t: 0, g: 1 }, { w: 'PROFIT', t: 0 }, { w: 'WETS', t: 0 },
      { w: 'ANGLES', t: 0 }, { w: 'ATTEND', t: 1, g: 1 }, { w: 'GOTTEN', t: 1, g: 1 }, { w: 'CHAPS', t: 0 },
    ],
  },
  {
    num: 27, quizId: 'axiom-8-19-26', live: '2026-08-19', dateLabel: 'August 19, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'nolet', c: 'I' }, { k: 'len', n: 4 }, { k: 'onevowel' }, { k: 'norepeat' }, { k: 'vowels', n: 1 }],
    tiles: [
      { w: 'STARTER', t: 0 }, { w: 'RAINING', t: 0 }, { w: 'RUMOR', t: 0 }, { w: 'LUXURY', t: 0 },
      { w: 'BANDS', t: 1 }, { w: 'TILE', t: 0 }, { w: 'NEXT', t: 1, g: 1 }, { w: 'PUNCH', t: 1 },
      { w: 'SUFFICE', t: 0 }, { w: 'POLLS', t: 1 }, { w: 'SHADOW', t: 0 }, { w: 'AGING', t: 0 },
      { w: 'CLINICAL', t: 0, g: 1 }, { w: 'TASK', t: 1, g: 1 }, { w: 'FREAK', t: 0, g: 1 }, { w: 'ATTENDING', t: 0 },
      { w: 'SHELTER', t: 0 }, { w: 'FREED', t: 0 }, { w: 'NUNS', t: 1 }, { w: 'PRINTING', t: 0 },
      { w: 'ANYWAY', t: 0 }, { w: 'PLUG', t: 1, g: 1 }, { w: 'JUDGMENTS', t: 0 }, { w: 'CLASH', t: 1 },
    ],
  },
  {
    num: 28, quizId: 'axiom-8-20-26', live: '2026-08-20', dateLabel: 'August 20, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'in', set: 'country' }, { k: 'norepeat' }, { k: 'endvowel' }, { k: 'vowels', n: 2 }, { k: 'nolet', c: 'T' }],
    tiles: [
      { w: 'JAPAN', t: 1 }, { w: 'BUFFALO', t: 0 }, { w: 'PERTH', t: 0 }, { w: 'AUCKLAND', t: 0, g: 1 },
      { w: 'EGYPT', t: 1 }, { w: 'DENVER', t: 0 }, { w: 'HALIFAX', t: 0 }, { w: 'BUDAPEST', t: 0 },
      { w: 'FRANCE', t: 1, g: 1 }, { w: 'ACCRA', t: 0 }, { w: 'SAVANNAH', t: 0 }, { w: 'SPAIN', t: 1 },
      { w: 'MARSEILLE', t: 0, g: 1 }, { w: 'GERMANY', t: 1 }, { w: 'ITALY', t: 1 }, { w: 'DENMARK', t: 1 },
      { w: 'KENYA', t: 1, g: 1 }, { w: 'SWEDEN', t: 1 }, { w: 'BRUSSELS', t: 0 }, { w: 'SEATTLE', t: 0 },
      { w: 'AUSTIN', t: 0 }, { w: 'MALMO', t: 0 }, { w: 'CHILE', t: 1, g: 1 }, { w: 'VALENCIA', t: 0 },
    ],
  },
  {
    num: 29, quizId: 'axiom-8-21-26', live: '2026-08-21', dateLabel: 'August 21, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'vowels', n: 2 }, { k: 'startvowel' }, { k: 'len', n: 4 }, { k: 'nolet', c: 'S' }, { k: 'norepeat' }],
    tiles: [
      { w: 'EDUCATING', t: 1 }, { w: 'INJURED', t: 1 }, { w: 'SCATTER', t: 0, g: 1 }, { w: 'SEPARATE', t: 0 },
      { w: 'DISAGREED', t: 0 }, { w: 'FUSION', t: 0 }, { w: 'AGENTS', t: 1 }, { w: 'FINDING', t: 0 },
      { w: 'COMPLAINT', t: 0 }, { w: 'CHOSEN', t: 0 }, { w: 'SPRINGING', t: 0 }, { w: 'ECHO', t: 1, g: 1 },
      { w: 'FOLLOW', t: 0 }, { w: 'OBJECT', t: 1 }, { w: 'GREATEST', t: 0 }, { w: 'DIALED', t: 0 },
      { w: 'GRAPHS', t: 0 }, { w: 'MILL', t: 0 }, { w: 'TACTICAL', t: 0 }, { w: 'UNDO', t: 1, g: 1 },
      { w: 'BLAMES', t: 0 }, { w: 'DISHONEST', t: 0 }, { w: 'DRIPPED', t: 0, g: 1 }, { w: 'EXAM', t: 1, g: 1 },
    ],
  },
  {
    num: 30, quizId: 'axiom-8-22-26', live: '2026-08-22', dateLabel: 'August 22, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'twinvowel' }, { k: 'vowels', n: 2 }, { k: 'nolet', c: 'S' }, { k: 'onevowel' }, { k: 'dbl' }],
    tiles: [
      { w: 'SCRAP', t: 0 }, { w: 'ARRIVAL', t: 1 }, { w: 'HORN', t: 1 }, { w: 'ERASED', t: 0, g: 1 },
      { w: 'GREEN', t: 1, g: 1 }, { w: 'STUPIDITY', t: 0 }, { w: 'OVERLOOKS', t: 0 }, { w: 'ABUSIVE', t: 0 },
      { w: 'SLIGHTLY', t: 0 }, { w: 'KEPT', t: 1 }, { w: 'ASSORTING', t: 0 }, { w: 'COBBLERS', t: 0 },
      { w: 'COURSES', t: 0 }, { w: 'BANS', t: 0 }, { w: 'SUES', t: 0 }, { w: 'ORIGINALS', t: 0 },
      { w: 'MONKEYS', t: 0 }, { w: 'STRAINS', t: 0, g: 1 }, { w: 'FOOT', t: 1, g: 1 }, { w: 'YOURS', t: 0 },
      { w: 'HOOK', t: 1, g: 1 }, { w: 'PRECISELY', t: 0 }, { w: 'ESTIMATE', t: 0 }, { w: 'COMMODITY', t: 1 },
    ],
  },
  {
    num: 31, quizId: 'axiom-8-23-26', live: '2026-08-23', dateLabel: 'August 23, 2026', sunday: true,
    budget: 7,
    rules: [{ k: 'nolet', c: 'C' }, { k: 'nolet', c: 'P' }, { k: 'vowels', n: 2 }, { k: 'altvc' }, { k: 'endvowel' }, { k: 'norepeat' }, { k: 'len', n: 4 }],
    tiles: [
      { w: 'MOVEMENT', t: 0 }, { w: 'TAIL', t: 1 }, { w: 'VACUUM', t: 0 }, { w: 'RECTIFIES', t: 0 },
      { w: 'BOOM', t: 0 }, { w: 'MOLECULE', t: 0 }, { w: 'MUSICAL', t: 1 }, { w: 'RESTRAINS', t: 0 },
      { w: 'GENERATED', t: 0 }, { w: 'DESPERATE', t: 0 }, { w: 'SIMULATES', t: 0 }, { w: 'MASSIVELY', t: 0 },
      { w: 'WEEK', t: 0 }, { w: 'MOON', t: 0 }, { w: 'COMMUNITY', t: 0 }, { w: 'BORE', t: 1, g: 1 },
      { w: 'MORE', t: 1, g: 1 }, { w: 'JOKE', t: 1, g: 1 }, { w: 'EDITOR', t: 1 }, { w: 'SMALL', t: 0 },
      { w: 'SEEKING', t: 0, g: 1 }, { w: 'STUPIDITY', t: 0 }, { w: 'LUNATIC', t: 1 }, { w: 'QUEUE', t: 0 },
      { w: 'CIVILIZES', t: 0 }, { w: 'AGREE', t: 0, g: 1 }, { w: 'DEFINES', t: 0 }, { w: 'SLASH', t: 0 },
    ],
  },
  {
    num: 32, quizId: 'axiom-8-24-26', live: '2026-08-24', dateLabel: 'August 24, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'nolet', c: 'I' }, { k: 'vowels', n: 1 }, { k: 'onevowel' }, { k: 'len', n: 4 }, { k: 'norepeat' }],
    tiles: [
      { w: 'SPRAY', t: 1 }, { w: 'PARTLY', t: 1 }, { w: 'WERE', t: 1 }, { w: 'BLACKMAIL', t: 0 },
      { w: 'ELIGIBLE', t: 0 }, { w: 'CLOG', t: 1, g: 1 }, { w: 'UNITE', t: 0 }, { w: 'VOTE', t: 0 },
      { w: 'SMALLISH', t: 0 }, { w: 'CLAUSE', t: 0 }, { w: 'HEAD', t: 0 }, { w: 'AMOUNT', t: 0, g: 1 },
      { w: 'HORDES', t: 0 }, { w: 'TACKLED', t: 0 }, { w: 'CONDENSE', t: 0, g: 1 }, { w: 'STATIONS', t: 0 },
      { w: 'POOL', t: 1 }, { w: 'STARVE', t: 0 }, { w: 'CRAP', t: 1, g: 1 }, { w: 'SEEN', t: 1 },
      { w: 'SUPPLY', t: 1 }, { w: 'FOOT', t: 1 }, { w: 'BEST', t: 1, g: 1 }, { w: 'FEES', t: 1 },
    ],
  },
  {
    num: 33, quizId: 'axiom-8-25-26', live: '2026-08-25', dateLabel: 'August 25, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'vowels', n: 2 }, { k: 'norepeat' }, { k: 'in', set: 'fruit' }, { k: 'len', n: 5 }, { k: 'nolet', c: 'S' }],
    tiles: [
      { w: 'MANGO', t: 1, g: 1 }, { w: 'JUICE', t: 1 }, { w: 'CHEESE', t: 0 }, { w: 'GINGER', t: 0 },
      { w: 'BUTTER', t: 0, g: 1 }, { w: 'PRESERVE', t: 0 }, { w: 'VENISON', t: 0 }, { w: 'OMELET', t: 0 },
      { w: 'CIDER', t: 1 }, { w: 'MUSTARD', t: 0 }, { w: 'MUFFIN', t: 0 }, { w: 'KETCHUP', t: 0 },
      { w: 'BROWNIE', t: 0 }, { w: 'GNOCCHI', t: 0 }, { w: 'RADISH', t: 0 }, { w: 'GRAPE', t: 1, g: 1 },
      { w: 'PORRIDGE', t: 0 }, { w: 'CABBAGE', t: 0, g: 1 }, { w: 'GRAVY', t: 1 }, { w: 'OMELETTE', t: 0 },
      { w: 'MOCHA', t: 1 }, { w: 'STEAK', t: 1 }, { w: 'LEMON', t: 1, g: 1 }, { w: 'BEAN', t: 0 },
    ],
  },
  {
    num: 34, quizId: 'axiom-8-26-26', live: '2026-08-26', dateLabel: 'August 26, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'vowels', n: 2 }, { k: 'len', n: 4 }, { k: 'endvowel' }, { k: 'nolet', c: 'B' }, { k: 'norepeat' }],
    tiles: [
      { w: 'DELIGHTED', t: 0 }, { w: 'COUNTRIES', t: 0 }, { w: 'HEARING', t: 0 }, { w: 'REQUIRED', t: 0, g: 1 },
      { w: 'OBJECTING', t: 0 }, { w: 'MOUNTAINS', t: 0 }, { w: 'PLAGUE', t: 1 }, { w: 'FORGIVE', t: 1 },
      { w: 'HIRE', t: 1, g: 1 }, { w: 'THOU', t: 1, g: 1 }, { w: 'SIMULATE', t: 1 }, { w: 'FROZE', t: 1 },
      { w: 'DRAINING', t: 0 }, { w: 'DRIFT', t: 0 }, { w: 'DECODING', t: 0 }, { w: 'PHONING', t: 0, g: 1 },
      { w: 'TIDIES', t: 0 }, { w: 'HARDSHIP', t: 0 }, { w: 'GLASS', t: 0 }, { w: 'CLEAR', t: 0 },
      { w: 'TYPESETS', t: 0 }, { w: 'TILE', t: 1, g: 1 }, { w: 'SCOPE', t: 1 }, { w: 'RESEMBLED', t: 0 },
    ],
  },
  {
    num: 35, quizId: 'axiom-8-27-26', live: '2026-08-27', dateLabel: 'August 27, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'len', n: 4 }, { k: 'nolet', c: 'P' }, { k: 'onevowel' }, { k: 'vowels', n: 1 }, { k: 'norepeat' }],
    tiles: [
      { w: 'SPONSOR', t: 0 }, { w: 'DISHONEST', t: 0 }, { w: 'THUS', t: 1, g: 1 }, { w: 'DISPLAYS', t: 0 },
      { w: 'CARRIED', t: 0, g: 1 }, { w: 'QUICK', t: 0 }, { w: 'FIBER', t: 0 }, { w: 'TOES', t: 0 },
      { w: 'SLIGHT', t: 1 }, { w: 'STICK', t: 1 }, { w: 'FLOW', t: 1, g: 1 }, { w: 'WINES', t: 0 },
      { w: 'RENEW', t: 0 }, { w: 'FRACTIONS', t: 0 }, { w: 'CLOTHED', t: 0 }, { w: 'STICKS', t: 1 },
      { w: 'TRUSTS', t: 1 }, { w: 'ANALYST', t: 0 }, { w: 'ISLANDS', t: 0 }, { w: 'COMPOSED', t: 0 },
      { w: 'FUDGE', t: 0, g: 1 }, { w: 'BURY', t: 1, g: 1 }, { w: 'EVENED', t: 0 }, { w: 'SERVED', t: 0 },
    ],
  },
  {
    num: 36, quizId: 'axiom-8-28-26', live: '2026-08-28', dateLabel: 'August 28, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'len', n: 8 }, { k: 'hides', set: 'animal' }, { k: 'nolet', c: 'N' }, { k: 'vowels', n: 4 }, { k: 'altvc' }],
    tiles: [
      { w: 'HUNDREDS', t: 0 }, { w: 'UNHEALTHY', t: 0 }, { w: 'CRAMPS', t: 1 }, { w: 'COUNTS', t: 0 },
      { w: 'BUYING', t: 0 }, { w: 'NOTES', t: 0 }, { w: 'OBEYED', t: 1 }, { w: 'NOMINATES', t: 0 },
      { w: 'EXECUTES', t: 1 }, { w: 'SCORING', t: 0 }, { w: 'EDUCATES', t: 1, g: 1 }, { w: 'BONES', t: 0 },
      { w: 'POINTED', t: 0 }, { w: 'JOKES', t: 1 }, { w: 'VISITING', t: 0, g: 1 }, { w: 'LITERATE', t: 1, g: 1 },
      { w: 'NODES', t: 0 }, { w: 'OPERATED', t: 1, g: 1 }, { w: 'MUNDANE', t: 0 }, { w: 'VISITED', t: 1 },
      { w: 'COPES', t: 1 }, { w: 'CHESTNUT', t: 0 }, { w: 'GUIDING', t: 0 }, { w: 'DETERMINE', t: 0, g: 1 },
    ],
  },
  {
    num: 37, quizId: 'axiom-8-29-26', live: '2026-08-29', dateLabel: 'August 29, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'altvc' }, { k: 'nolet', c: 'H' }, { k: 'norepeat' }, { k: 'len', n: 5 }, { k: 'vowels', n: 2 }],
    tiles: [
      { w: 'DATA', t: 1 }, { w: 'CHOSEN', t: 0 }, { w: 'PINT', t: 0 }, { w: 'THEREOF', t: 0 },
      { w: 'COMPOUND', t: 0 }, { w: 'FISHES', t: 0 }, { w: 'OPEN', t: 1 }, { w: 'DARES', t: 1 },
      { w: 'FAME', t: 1 }, { w: 'FILED', t: 1, g: 1 }, { w: 'PILOT', t: 1, g: 1 }, { w: 'CHEWED', t: 0 },
      { w: 'APPEARING', t: 0 }, { w: 'DIRECTLY', t: 0 }, { w: 'SATIRE', t: 1 }, { w: 'INHABITS', t: 0 },
      { w: 'MOVED', t: 1, g: 1 }, { w: 'HARM', t: 0 }, { w: 'ORTHODOX', t: 0 }, { w: 'SHORTEST', t: 0 },
      { w: 'MATCHES', t: 0, g: 1 }, { w: 'FUSE', t: 1 }, { w: 'SENTENCE', t: 0 }, { w: 'MONTHLY', t: 0, g: 1 },
    ],
  },
  {
    num: 38, quizId: 'axiom-8-30-26', live: '2026-08-30', dateLabel: 'August 30, 2026', sunday: true,
    budget: 7,
    rules: [{ k: 'nolet', c: 'D' }, { k: 'len', n: 4 }, { k: 'norepeat' }, { k: 'alpha' }, { k: 'onevowel' }, { k: 'nolet', c: 'C' }, { k: 'vowels', n: 1 }],
    tiles: [
      { w: 'CAUSES', t: 0 }, { w: 'ABORTED', t: 0 }, { w: 'BEERS', t: 1 }, { w: 'BAKES', t: 0 },
      { w: 'ENERGY', t: 0 }, { w: 'MOST', t: 1, g: 1 }, { w: 'CIVIL', t: 0 }, { w: 'FLOOR', t: 1 },
      { w: 'FLOORS', t: 1 }, { w: 'HOST', t: 1, g: 1 }, { w: 'EMERGE', t: 0 }, { w: 'CAUSAL', t: 0 },
      { w: 'DOORS', t: 1 }, { w: 'DOMINANT', t: 0 }, { w: 'ADHERES', t: 0 }, { w: 'POSTING', t: 0 },
      { w: 'GUARD', t: 0 }, { w: 'SEGMENTS', t: 0 }, { w: 'ENVY', t: 1, g: 1 }, { w: 'SELECT', t: 0 },
      { w: 'PHASED', t: 0, g: 1 }, { w: 'DEEMS', t: 1 }, { w: 'SUBTLETY', t: 0 }, { w: 'INTRINSIC', t: 0 },
      { w: 'COUGH', t: 0 }, { w: 'ACCORDED', t: 0 }, { w: 'BOOST', t: 1 }, { w: 'MAKERS', t: 0, g: 1 },
    ],
  },
  {
    num: 39, quizId: 'axiom-8-31-26', live: '2026-08-31', dateLabel: 'August 31, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'altvc' }, { k: 'in', set: 'fruit' }, { k: 'vowels', n: 2 }, { k: 'norepeat' }, { k: 'nolet', c: 'R' }],
    tiles: [
      { w: 'PRETZEL', t: 0, g: 1 }, { w: 'BURRITO', t: 0 }, { w: 'POTATO', t: 0 }, { w: 'SAUSAGE', t: 0 },
      { w: 'BUTTER', t: 0 }, { w: 'MELON', t: 1, g: 1 }, { w: 'RISOTTO', t: 0 }, { w: 'LEMON', t: 1, g: 1 },
      { w: 'OATMEAL', t: 0 }, { w: 'TOAST', t: 0 }, { w: 'WATER', t: 1 }, { w: 'BEET', t: 0 },
      { w: 'VINEGAR', t: 1 }, { w: 'CINNAMON', t: 0 }, { w: 'CUPCAKE', t: 0, g: 1 }, { w: 'BASIL', t: 1 },
      { w: 'CARAMEL', t: 0 }, { w: 'OMELET', t: 0 }, { w: 'SALAD', t: 0 }, { w: 'RICE', t: 1 },
      { w: 'PASTA', t: 0 }, { w: 'FALAFEL', t: 0 }, { w: 'DATE', t: 1, g: 1 }, { w: 'GELATO', t: 1 },
    ],
  },
  {
    num: 40, quizId: 'axiom-9-1-26', live: '2026-09-01', dateLabel: 'September 1, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'norepeat' }, { k: 'nolet', c: 'A' }, { k: 'len', n: 4 }, { k: 'vowels', n: 1 }, { k: 'hides', set: 'body' }],
    tiles: [
      { w: 'PATCH', t: 1 }, { w: 'NORMS', t: 1 }, { w: 'BROKERS', t: 0 }, { w: 'GENESIS', t: 0 },
      { w: 'FILTHY', t: 1 }, { w: 'HAST', t: 1 }, { w: 'STUMPS', t: 0 }, { w: 'WRIT', t: 1 },
      { w: 'KILO', t: 1 }, { w: 'SECT', t: 1 }, { w: 'SLAPS', t: 0 }, { w: 'EARNEST', t: 0, g: 1 },
      { w: 'DEED', t: 0 }, { w: 'FINISHED', t: 0, g: 1 }, { w: 'NAVY', t: 1 }, { w: 'UTTER', t: 0 },
      { w: 'GUMS', t: 1, g: 1 }, { w: 'SKIN', t: 1, g: 1 }, { w: 'BITE', t: 1 }, { w: 'WHIP', t: 1, g: 1 },
      { w: 'RATTLED', t: 0 }, { w: 'PRINTS', t: 1 }, { w: 'CONSERVE', t: 0 }, { w: 'BELLS', t: 0 },
    ],
  },
  {
    num: 41, quizId: 'axiom-9-2-26', live: '2026-09-02', dateLabel: 'September 2, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'altvc' }, { k: 'endvowel' }, { k: 'vowels', n: 4 }, { k: 'len', n: 8 }, { k: 'nolet', c: 'E' }],
    tiles: [
      { w: 'MOLECULE', t: 1 }, { w: 'HEROINE', t: 1 }, { w: 'MEDIOCRE', t: 1 }, { w: 'GRAFFITI', t: 1 },
      { w: 'PANIC', t: 0, g: 1 }, { w: 'PATS', t: 0 }, { w: 'QUERIES', t: 0 }, { w: 'HALFBACK', t: 0 },
      { w: 'CORVETTE', t: 1 }, { w: 'SPICER', t: 0 }, { w: 'REACTIVE', t: 1 }, { w: 'UTILITY', t: 0 },
      { w: 'SLAPS', t: 0, g: 1 }, { w: 'GULLIBLE', t: 1 }, { w: 'COLORADO', t: 1, g: 1 }, { w: 'GIRLY', t: 0 },
      { w: 'OVARIES', t: 0 }, { w: 'RELIANCE', t: 1 }, { w: 'CRUCIFIX', t: 0 }, { w: 'PANORAMA', t: 1, g: 1 },
      { w: 'VICINITY', t: 0 }, { w: 'SLUGGISH', t: 0 }, { w: 'MACARONI', t: 1, g: 1 }, { w: 'OVERALL', t: 0 },
    ],
  },
  {
    num: 42, quizId: 'axiom-9-3-26', live: '2026-09-03', dateLabel: 'September 3, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'norepeat' }, { k: 'endvowel' }, { k: 'hides', set: 'animal' }, { k: 'len', n: 4 }, { k: 'nolet', c: 'P' }],
    tiles: [
      { w: 'ANTE', t: 1, g: 1 }, { w: 'PIERCE', t: 0 }, { w: 'GARTH', t: 0 }, { w: 'CATE', t: 1, g: 1 },
      { w: 'ANTI', t: 1, g: 1 }, { w: 'SCRAMBLE', t: 1 }, { w: 'RATE', t: 1 }, { w: 'SENT', t: 0 },
      { w: 'TWITCH', t: 0 }, { w: 'CELLS', t: 0 }, { w: 'CURATE', t: 1 }, { w: 'MAGAZINE', t: 0 },
      { w: 'IMAM', t: 0, g: 1 }, { w: 'ANALOG', t: 0, g: 1 }, { w: 'INCREASE', t: 0 }, { w: 'INFECTED', t: 0 },
      { w: 'RELIEVE', t: 0 }, { w: 'COLOR', t: 0 }, { w: 'MAJOR', t: 0 }, { w: 'YOUR', t: 0 },
      { w: 'WORK', t: 0 }, { w: 'TORNADO', t: 0 }, { w: 'KINDRED', t: 0 }, { w: 'TAPE', t: 1 },
    ],
  },
  {
    num: 43, quizId: 'axiom-9-4-26', live: '2026-09-04', dateLabel: 'September 4, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'startvowel' }, { k: 'nolet', c: 'P' }, { k: 'endvowel' }, { k: 'altvc' }, { k: 'norepeat' }],
    tiles: [
      { w: 'SENATOR', t: 1 }, { w: 'TOTAL', t: 1 }, { w: 'ZETA', t: 1 }, { w: 'FEEDERS', t: 0 },
      { w: 'RUMP', t: 0 }, { w: 'LULU', t: 1 }, { w: 'SKETCHY', t: 0 }, { w: 'DISPOSE', t: 0, g: 1 },
      { w: 'SCENERY', t: 0 }, { w: 'DEANS', t: 0 }, { w: 'TYPE', t: 0 }, { w: 'PERIODIC', t: 0 },
      { w: 'OMEGA', t: 1, g: 1 }, { w: 'ADOBE', t: 1, g: 1 }, { w: 'HADES', t: 1 }, { w: 'ALUM', t: 1 },
      { w: 'JUMPER', t: 0, g: 1 }, { w: 'ELITE', t: 1 }, { w: 'WEEP', t: 0 }, { w: 'AROSE', t: 1, g: 1 },
      { w: 'SENIOR', t: 0 }, { w: 'SPOILED', t: 0 }, { w: 'IRON', t: 1 }, { w: 'AGITATED', t: 1 },
    ],
  },
  {
    num: 44, quizId: 'axiom-9-5-26', live: '2026-09-05', dateLabel: 'September 5, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'sameends' }, { k: 'onevowel' }, { k: 'dbl' }, { k: 'nolet', c: 'H' }, { k: 'vowels', n: 1 }],
    tiles: [
      { w: 'KINK', t: 1 }, { w: 'SPLITS', t: 1 }, { w: 'RISKING', t: 0 }, { w: 'SPELLS', t: 1, g: 1 },
      { w: 'ENABLE', t: 0 }, { w: 'STAFFS', t: 1, g: 1 }, { w: 'THENCE', t: 0 }, { w: 'TWISTING', t: 0 },
      { w: 'STUFFS', t: 1, g: 1 }, { w: 'HARSH', t: 1 }, { w: 'BIRDIE', t: 0 }, { w: 'ADDICT', t: 0, g: 1 },
      { w: 'DOMES', t: 0 }, { w: 'HELLS', t: 1 }, { w: 'KNITTING', t: 0 }, { w: 'PARABLE', t: 0, g: 1 },
      { w: 'THESE', t: 0 }, { w: 'ASKING', t: 0 }, { w: 'FANS', t: 1 }, { w: 'SPRINGS', t: 1 },
      { w: 'DEBATE', t: 0 }, { w: 'GOSH', t: 1 }, { w: 'OUTPOST', t: 0 }, { w: 'JOLLY', t: 1 },
    ],
  },
  {
    num: 45, quizId: 'axiom-9-6-26', live: '2026-09-06', dateLabel: 'September 6, 2026', sunday: true,
    budget: 7,
    rules: [{ k: 'in', set: 'mammal' }, { k: 'nolet', c: 'M' }, { k: 'onevowel' }, { k: 'nolet', c: 'G' }, { k: 'norepeat' }, { k: 'altvc' }, { k: 'vowels', n: 1 }],
    tiles: [
      { w: 'BOMB', t: 0 }, { w: 'STIMULUS', t: 0 }, { w: 'BAT', t: 1, g: 1 }, { w: 'RAT', t: 1 },
      { w: 'FOX', t: 1, g: 1 }, { w: 'MORAY', t: 0 }, { w: 'DOG', t: 1 }, { w: 'TIGER', t: 1 },
      { w: 'LOOMING', t: 0 }, { w: 'MOVE', t: 0 }, { w: 'MILL', t: 0, g: 1 }, { w: 'NATIVES', t: 1 },
      { w: 'TIMED', t: 0 }, { w: 'TREMOR', t: 0 }, { w: 'DEMANDED', t: 0 }, { w: 'TEAMED', t: 0 },
      { w: 'CAT', t: 1, g: 1 }, { w: 'SLAMMED', t: 0, g: 1 }, { w: 'SYSTEM', t: 0 }, { w: 'WAVED', t: 1 },
      { w: 'COW', t: 1 }, { w: 'CUTE', t: 1 }, { w: 'FOREMAN', t: 0 }, { w: 'PIG', t: 1 },
      { w: 'MEDUSA', t: 0 }, { w: 'KALE', t: 1 }, { w: 'APE', t: 1 }, { w: 'ARISE', t: 1 },
    ],
  },
  {
    num: 46, quizId: 'axiom-9-7-26', live: '2026-09-07', dateLabel: 'September 7, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'startvowel' }, { k: 'hides', set: 'body' }, { k: 'twinvowel' }, { k: 'norepeat' }, { k: 'vowels', n: 2 }],
    tiles: [
      { w: 'SPINACH', t: 0 }, { w: 'ARMORY', t: 1 }, { w: 'INSTEAD', t: 0 }, { w: 'ETERNAL', t: 0 },
      { w: 'STROLLER', t: 0 }, { w: 'SHOWTIME', t: 0 }, { w: 'BROTH', t: 0 }, { w: 'EARNS', t: 1, g: 1 },
      { w: 'SPARROW', t: 0 }, { w: 'AMASSED', t: 0 }, { w: 'DEFINING', t: 0 }, { w: 'FORMERLY', t: 0 },
      { w: 'JACKS', t: 0, g: 1 }, { w: 'EPISODE', t: 0 }, { w: 'EARTH', t: 1 }, { w: 'SOLOIST', t: 0, g: 1 },
      { w: 'INHABIT', t: 0 }, { w: 'ACHING', t: 1 }, { w: 'EARL', t: 1, g: 1 }, { w: 'JOKER', t: 0 },
      { w: 'ITCHING', t: 1 }, { w: 'SPICY', t: 0 }, { w: 'SPUR', t: 0 }, { w: 'EARTHLY', t: 1, g: 1 },
    ],
  },
  {
    num: 47, quizId: 'axiom-9-8-26', live: '2026-09-08', dateLabel: 'September 8, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'vowels', n: 2 }, { k: 'hides', set: 'number' }, { k: 'altvc' }, { k: 'nolet', c: 'G' }, { k: 'endvowel' }],
    tiles: [
      { w: 'LOATHE', t: 0 }, { w: 'HARASS', t: 0 }, { w: 'VARIABLE', t: 0 }, { w: 'THINKING', t: 0 },
      { w: 'CASHMERE', t: 0 }, { w: 'VIBE', t: 1 }, { w: 'CHERRY', t: 0 }, { w: 'RUDE', t: 1 },
      { w: 'PANTHERS', t: 0 }, { w: 'STARRY', t: 0 }, { w: 'PORE', t: 1 }, { w: 'OFFENSE', t: 0 },
      { w: 'NONE', t: 1, g: 1 }, { w: 'PEARCE', t: 0 }, { w: 'CONE', t: 1, g: 1 }, { w: 'FILE', t: 1 },
      { w: 'SEAHAWKS', t: 0 }, { w: 'TURTLES', t: 0 }, { w: 'STENCH', t: 0, g: 1 }, { w: 'THINK', t: 0, g: 1 },
      { w: 'GRID', t: 0 }, { w: 'NICEST', t: 0 }, { w: 'HONE', t: 1, g: 1 }, { w: 'BOOKLET', t: 0 },
    ],
  },
  {
    num: 48, quizId: 'axiom-9-9-26', live: '2026-09-09', dateLabel: 'September 9, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'in', set: 'mammal' }, { k: 'endvowel' }, { k: 'vowels', n: 3 }, { k: 'nolet', c: 'R' }, { k: 'twinvowel' }],
    tiles: [
      { w: 'DICTATED', t: 1 }, { w: 'RECOVER', t: 0 }, { w: 'DIALED', t: 1 }, { w: 'OVERTIME', t: 0, g: 1 },
      { w: 'RAGGED', t: 0 }, { w: 'REEFS', t: 0 }, { w: 'NORTHERN', t: 0 }, { w: 'AWARDED', t: 0 },
      { w: 'MOUSE', t: 1, g: 1 }, { w: 'KOALA', t: 1, g: 1 }, { w: 'LECTURED', t: 0 }, { w: 'CURT', t: 0 },
      { w: 'LOGISTIC', t: 1 }, { w: 'LEVIES', t: 1 }, { w: 'LOATHE', t: 1 }, { w: 'SERENE', t: 0 },
      { w: 'ABOUT', t: 1 }, { w: 'TRUTH', t: 0 }, { w: 'MOOSE', t: 1, g: 1 }, { w: 'RABBIT', t: 0, g: 1 },
      { w: 'ORGAN', t: 0 }, { w: 'ASTEROID', t: 0 }, { w: 'FUELS', t: 1 }, { w: 'CAPSULES', t: 1 },
    ],
  },
  {
    num: 49, quizId: 'axiom-9-10-26', live: '2026-09-10', dateLabel: 'September 10, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'vowels', n: 2 }, { k: 'len', n: 6 }, { k: 'hides', set: 'number' }, { k: 'nolet', c: 'H' }, { k: 'sameends' }],
    tiles: [
      { w: 'STARTS', t: 1 }, { w: 'MUSEUM', t: 1 }, { w: 'SUSHI', t: 0 }, { w: 'HEALING', t: 0 },
      { w: 'NOUN', t: 1 }, { w: 'TRACT', t: 1 }, { w: 'DISABLED', t: 1 }, { w: 'MEDICAID', t: 0 },
      { w: 'RUBBER', t: 1 }, { w: 'HUMBLING', t: 0, g: 1 }, { w: 'INITIAL', t: 0 }, { w: 'UPDATES', t: 0 },
      { w: 'SIXERS', t: 1, g: 1 }, { w: 'HONESTLY', t: 0 }, { w: 'HAVING', t: 0 }, { w: 'TENANT', t: 1, g: 1 },
      { w: 'NEWTON', t: 1 }, { w: 'STONES', t: 1, g: 1 }, { w: 'INHUMANE', t: 0 }, { w: 'HADES', t: 0 },
      { w: 'PHONE', t: 0, g: 1 }, { w: 'SISTERS', t: 1 }, { w: 'FRANTIC', t: 0 }, { w: 'TAUGHT', t: 1 },
    ],
  },
  {
    num: 50, quizId: 'axiom-9-11-26', live: '2026-09-11', dateLabel: 'September 11, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'norepeat' }, { k: 'altvc' }, { k: 'vowels', n: 3 }, { k: 'hides', set: 'animal' }, { k: 'nolet', c: 'M' }],
    tiles: [
      { w: 'HEALTHY', t: 0 }, { w: 'IDEAS', t: 1 }, { w: 'BUILDERS', t: 1 }, { w: 'PAPERS', t: 0 },
      { w: 'HOLISTIC', t: 0 }, { w: 'TERRIER', t: 0 }, { w: 'STINT', t: 0 }, { w: 'CURATE', t: 1, g: 1 },
      { w: 'NATAL', t: 0, g: 1 }, { w: 'CATHODE', t: 1 }, { w: 'LOCATING', t: 1 }, { w: 'BABES', t: 0, g: 1 },
      { w: 'LOUDEST', t: 1 }, { w: 'UPSTAIRS', t: 0 }, { w: 'EMBLEM', t: 0 }, { w: 'LOCATED', t: 1, g: 1 },
      { w: 'HIGHEST', t: 0 }, { w: 'SERVANTS', t: 0 }, { w: 'PIRATE', t: 1, g: 1 }, { w: 'LOCATE', t: 1 },
      { w: 'ENACTED', t: 0 }, { w: 'MAXIMISE', t: 0 }, { w: 'SEMANTIC', t: 1 }, { w: 'STATURE', t: 0 },
    ],
  },
  {
    num: 51, quizId: 'axiom-9-12-26', live: '2026-09-12', dateLabel: 'September 12, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'in', set: 'mammal' }, { k: 'vowels', n: 3 }, { k: 'len', n: 7 }, { k: 'dbl' }, { k: 'nolet', c: 'B' }],
    tiles: [
      { w: 'TACO', t: 0 }, { w: 'HAPPENED', t: 1 }, { w: 'IDEOLOGY', t: 0 }, { w: 'ANALYZES', t: 1 },
      { w: 'BROKERS', t: 0 }, { w: 'GIRAFFE', t: 1, g: 1 }, { w: 'LAUNCHER', t: 1 }, { w: 'ACCOUNT', t: 1 },
      { w: 'ELEVATOR', t: 0 }, { w: 'COUNCIL', t: 1 }, { w: 'OBVIOUS', t: 0 }, { w: 'BEING', t: 0 },
      { w: 'POLISHED', t: 1 }, { w: 'RACCOON', t: 1, g: 1 }, { w: 'FEDEX', t: 0 }, { w: 'PROCEED', t: 1 },
      { w: 'BODILY', t: 0 }, { w: 'GORILLA', t: 1, g: 1 }, { w: 'SIGHT', t: 0 }, { w: 'CRUMBLE', t: 0, g: 1 },
      { w: 'NEEDLE', t: 1 }, { w: 'BAT', t: 0, g: 1 }, { w: 'CASINO', t: 1 }, { w: 'ROBIN', t: 0 },
    ],
  },
  {
    num: 52, quizId: 'axiom-9-13-26', live: '2026-09-13', dateLabel: 'September 13, 2026', sunday: true,
    budget: 7,
    rules: [{ k: 'twinvowel' }, { k: 'len', n: 6 }, { k: 'startvowel' }, { k: 'nolet', c: 'N' }, { k: 'sameends' }, { k: 'endvowel' }, { k: 'nolet', c: 'D' }],
    tiles: [
      { w: 'ISLANDS', t: 0 }, { w: 'MORALS', t: 1 }, { w: 'CLOTHED', t: 0 }, { w: 'THREAT', t: 1 },
      { w: 'PELVIS', t: 1 }, { w: 'SERIES', t: 1 }, { w: 'UPGRADE', t: 0, g: 1 }, { w: 'ACACIA', t: 1, g: 1 },
      { w: 'NIFTY', t: 0 }, { w: 'BANISHED', t: 0 }, { w: 'PUZZLE', t: 1 }, { w: 'DISLIKES', t: 0, g: 1 },
      { w: 'TAUGHT', t: 1 }, { w: 'SCREW', t: 0 }, { w: 'PACIFIST', t: 0 }, { w: 'LAUREL', t: 1 },
      { w: 'SNAILS', t: 1 }, { w: 'BASALT', t: 1 }, { w: 'PLACES', t: 1 }, { w: 'WASHING', t: 0 },
      { w: 'FRONTED', t: 0 }, { w: 'AZALEA', t: 1, g: 1 }, { w: 'SAUCES', t: 1 }, { w: 'BESTOWED', t: 0 },
      { w: 'FINLAND', t: 0 }, { w: 'AURORA', t: 1, g: 1 }, { w: 'WIDOWED', t: 0 }, { w: 'SALSA', t: 0 },
    ],
  },
  {
    num: 53, quizId: 'axiom-9-14-26', live: '2026-09-14', dateLabel: 'September 14, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'startvowel' }, { k: 'nolet', c: 'B' }, { k: 'norepeat' }, { k: 'vowels', n: 2 }, { k: 'alpha' }],
    tiles: [
      { w: 'EGOS', t: 1, g: 1 }, { w: 'UPSET', t: 1 }, { w: 'LOSING', t: 1 }, { w: 'MICE', t: 1 },
      { w: 'BUBBLY', t: 0 }, { w: 'WILDFIRE', t: 0 }, { w: 'RUBS', t: 0, g: 1 }, { w: 'ORDERLY', t: 1 },
      { w: 'SHACK', t: 0 }, { w: 'LIBERATE', t: 0 }, { w: 'TREY', t: 0 }, { w: 'DEFEATED', t: 0 },
      { w: 'DISGRACE', t: 0 }, { w: 'BURY', t: 0 }, { w: 'BELL', t: 0, g: 1 }, { w: 'ULCER', t: 1 },
      { w: 'EXTRACTS', t: 1 }, { w: 'DOORBELL', t: 0 }, { w: 'GALLOP', t: 1 }, { w: 'AIRY', t: 1, g: 1 },
      { w: 'BANS', t: 0 }, { w: 'RISEN', t: 1 }, { w: 'MUPPETS', t: 1 }, { w: 'ALMOST', t: 1, g: 1 },
    ],
  },
  {
    num: 54, quizId: 'axiom-9-15-26', live: '2026-09-15', dateLabel: 'September 15, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'endvowel' }, { k: 'hides', set: 'animal' }, { k: 'norepeat' }, { k: 'vowels', n: 2 }, { k: 'nolet', c: 'G' }],
    tiles: [
      { w: 'DROWNING', t: 0 }, { w: 'STRONGLY', t: 0 }, { w: 'SPED', t: 1 }, { w: 'CAPE', t: 1, g: 1 },
      { w: 'COWARDLY', t: 1 }, { w: 'SWINGS', t: 0 }, { w: 'UNDERDOG', t: 0 }, { w: 'CATE', t: 1, g: 1 },
      { w: 'OCTAVE', t: 1 }, { w: 'BELONGED', t: 0 }, { w: 'HYDRATE', t: 1, g: 1 }, { w: 'HONED', t: 1 },
      { w: 'WRITING', t: 0, g: 1 }, { w: 'TYPED', t: 1 }, { w: 'NITRO', t: 1 }, { w: 'TRAUMA', t: 1 },
      { w: 'ANGLES', t: 0 }, { w: 'ABRASIVE', t: 1 }, { w: 'GRAIL', t: 0 }, { w: 'ASHORE', t: 1 },
      { w: 'NOVELS', t: 1 }, { w: 'TEMPTING', t: 0 }, { w: 'PIGGY', t: 0, g: 1 }, { w: 'FUMBLE', t: 1 },
    ],
  },
  {
    num: 55, quizId: 'axiom-9-16-26', live: '2026-09-16', dateLabel: 'September 16, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'sameends' }, { k: 'endvowel' }, { k: 'len', n: 7 }, { k: 'nolet', c: 'H' }, { k: 'onevowel' }],
    tiles: [
      { w: 'UNHEARD', t: 0, g: 1 }, { w: 'SEVENTH', t: 0 }, { w: 'STALLS', t: 1 }, { w: 'EXHAUST', t: 0 },
      { w: 'AMATEUR', t: 0 }, { w: 'COMPOSE', t: 0 }, { w: 'EXTREME', t: 1, g: 1 }, { w: 'EXPENSE', t: 1, g: 1 },
      { w: 'GELATIN', t: 0 }, { w: 'SHINTY', t: 0 }, { w: 'FAITH', t: 0 }, { w: 'TURRET', t: 1 },
      { w: 'ENGLISH', t: 0 }, { w: 'INVOLVE', t: 0 }, { w: 'STARTERS', t: 1 }, { w: 'MATURED', t: 0 },
      { w: 'BACHELOR', t: 0 }, { w: 'BULB', t: 1 }, { w: 'WHISTLE', t: 0, g: 1 }, { w: 'LEVEL', t: 1 },
      { w: 'HUGGING', t: 0 }, { w: 'ESSENCE', t: 1, g: 1 }, { w: 'SETTLES', t: 1 }, { w: 'DEVOURED', t: 1 },
    ],
  },
  {
    num: 56, quizId: 'axiom-9-17-26', live: '2026-09-17', dateLabel: 'September 17, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'vowels', n: 3 }, { k: 'nolet', c: 'F' }, { k: 'sameends' }, { k: 'len', n: 6 }, { k: 'endvowel' }],
    tiles: [
      { w: 'RHETORIC', t: 1 }, { w: 'EXCISE', t: 1, g: 1 }, { w: 'CAKE', t: 1 }, { w: 'QUICKER', t: 1 },
      { w: 'ABNORMAL', t: 1 }, { w: 'THEFT', t: 0, g: 1 }, { w: 'GRANDPA', t: 1 }, { w: 'TANGLE', t: 1 },
      { w: 'EJECTED', t: 1 }, { w: 'ALTITUDE', t: 1 }, { w: 'VIRTUE', t: 1 }, { w: 'FIFTHS', t: 0 },
      { w: 'LEFTISTS', t: 0 }, { w: 'ENCORE', t: 1, g: 1 }, { w: 'FOURTH', t: 0 }, { w: 'EXPOSES', t: 1 },
      { w: 'SHANGHAI', t: 1 }, { w: 'FETISH', t: 0, g: 1 }, { w: 'ESTATE', t: 1, g: 1 }, { w: 'FIST', t: 0 },
      { w: 'LITTLE', t: 1 }, { w: 'DOSAGE', t: 1 }, { w: 'MUNDANE', t: 1 }, { w: 'FEVER', t: 0 },
    ],
  },
  {
    num: 57, quizId: 'axiom-9-18-26', live: '2026-09-18', dateLabel: 'September 18, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'norepeat' }, { k: 'len', n: 6 }, { k: 'nolet', c: 'L' }, { k: 'twinvowel' }, { k: 'vowels', n: 2 }],
    tiles: [
      { w: 'PREACH', t: 1, g: 1 }, { w: 'IONIC', t: 1 }, { w: 'VIGILANT', t: 0 }, { w: 'HEARTS', t: 1, g: 1 },
      { w: 'BACKED', t: 1 }, { w: 'TOUTED', t: 1 }, { w: 'HINGED', t: 1 }, { w: 'NOTION', t: 1 },
      { w: 'TOUCAN', t: 1 }, { w: 'ALTER', t: 0, g: 1 }, { w: 'FLING', t: 0, g: 1 }, { w: 'CALM', t: 0 },
      { w: 'AVOIDING', t: 1 }, { w: 'CAUCUS', t: 1 }, { w: 'SLIGHTLY', t: 0 }, { w: 'TERRAIN', t: 1 },
      { w: 'NELLY', t: 0 }, { w: 'SOUGHT', t: 1, g: 1 }, { w: 'SHEEP', t: 1 }, { w: 'RAMBLING', t: 0 },
      { w: 'ARGUABLY', t: 0 }, { w: 'CADETS', t: 1 }, { w: 'GLOSSY', t: 0 }, { w: 'BAKING', t: 1 },
    ],
  },
  {
    num: 58, quizId: 'axiom-9-19-26', live: '2026-09-19', dateLabel: 'September 19, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'len', n: 8 }, { k: 'nolet', c: 'C' }, { k: 'norepeat' }, { k: 'vowels', n: 3 }, { k: 'startvowel' }],
    tiles: [
      { w: 'COMPUTER', t: 1 }, { w: 'YIELDED', t: 1 }, { w: 'SWOLLEN', t: 0 }, { w: 'DECEIVE', t: 0 },
      { w: 'ABIDING', t: 1 }, { w: 'USABLE', t: 1 }, { w: 'EXCEEDED', t: 0, g: 1 }, { w: 'ARGUMENT', t: 1, g: 1 },
      { w: 'EXTERIOR', t: 0 }, { w: 'PENNIES', t: 1 }, { w: 'YUCK', t: 0 }, { w: 'RASCAL', t: 0 },
      { w: 'ETHANOL', t: 1 }, { w: 'SECULAR', t: 1 }, { w: 'ACCORDS', t: 0, g: 1 }, { w: 'NASCENT', t: 0 },
      { w: 'ACADEMIC', t: 0 }, { w: 'AMBUSHED', t: 1, g: 1 }, { w: 'SLICE', t: 0 }, { w: 'UPGRADES', t: 1, g: 1 },
      { w: 'SPEAKING', t: 1 }, { w: 'CROOK', t: 0 }, { w: 'REMOVING', t: 1 }, { w: 'SMOOTH', t: 0 },
    ],
  },
  {
    num: 59, quizId: 'axiom-9-20-26', live: '2026-09-20', dateLabel: 'September 20, 2026', sunday: true,
    budget: 7,
    rules: [{ k: 'len', n: 4 }, { k: 'nolet', c: 'W' }, { k: 'sameends' }, { k: 'startvowel' }, { k: 'twinvowel' }, { k: 'vowels', n: 3 }, { k: 'nolet', c: 'M' }],
    tiles: [
      { w: 'URGED', t: 1 }, { w: 'WILDER', t: 0 }, { w: 'AIMS', t: 1 }, { w: 'GOWNS', t: 0 },
      { w: 'HOOD', t: 1 }, { w: 'AIRY', t: 1 }, { w: 'AIDS', t: 1 }, { w: 'AURA', t: 1, g: 1 },
      { w: 'DROWNING', t: 0 }, { w: 'KNEE', t: 1 }, { w: 'EASE', t: 1, g: 1 }, { w: 'INCENSE', t: 1 },
      { w: 'WITCHES', t: 0 }, { w: 'WASTEFUL', t: 0 }, { w: 'INTREPID', t: 1 }, { w: 'AREA', t: 1, g: 1 },
      { w: 'FREE', t: 1 }, { w: 'UNDERCUT', t: 1 }, { w: 'EMERALD', t: 1 }, { w: 'AERO', t: 1 },
      { w: 'WAGES', t: 0 }, { w: 'AWARDS', t: 0 }, { w: 'GLOWING', t: 0, g: 1 }, { w: 'WELCOMED', t: 0 },
      { w: 'OARS', t: 1 }, { w: 'ONWARDS', t: 0 }, { w: 'WELCOME', t: 0, g: 1 }, { w: 'EARL', t: 1 },
    ],
  },
  {
    num: 60, quizId: 'axiom-9-21-26', live: '2026-09-21', dateLabel: 'September 21, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'startvowel' }, { k: 'hides', set: 'body' }, { k: 'vowels', n: 3 }, { k: 'nolet', c: 'S' }, { k: 'twinvowel' }],
    tiles: [
      { w: 'RIBS', t: 0 }, { w: 'ARMOUR', t: 1, g: 1 }, { w: 'SILENCED', t: 0 }, { w: 'PATRON', t: 0 },
      { w: 'LIABLE', t: 0 }, { w: 'ACCUSE', t: 1 }, { w: 'DUBIOUS', t: 0, g: 1 }, { w: 'LIFEBOAT', t: 0 },
      { w: 'MAINLAND', t: 0 }, { w: 'OVERLAND', t: 1 }, { w: 'LIGHT', t: 0, g: 1 }, { w: 'TYPE', t: 0 },
      { w: 'EARNINGS', t: 1 }, { w: 'ARGUMENT', t: 1 }, { w: 'UNHEARD', t: 1, g: 1 }, { w: 'EYEBALL', t: 1 },
      { w: 'EARNING', t: 1, g: 1 }, { w: 'CLEMENT', t: 0 }, { w: 'ORDINARY', t: 1 }, { w: 'OLIVE', t: 1 },
      { w: 'HOLD', t: 0 }, { w: 'JUNKIE', t: 0 }, { w: 'RAILWAY', t: 0 }, { w: 'APPEAR', t: 1 },
    ],
  },
  {
    num: 61, quizId: 'axiom-9-22-26', live: '2026-09-22', dateLabel: 'September 22, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'norepeat' }, { k: 'vowels', n: 4 }, { k: 'twinvowel' }, { k: 'nolet', c: 'D' }, { k: 'len', n: 8 }],
    tiles: [
      { w: 'MACARONI', t: 1 }, { w: 'RELICS', t: 0 }, { w: 'INNOVATE', t: 1 }, { w: 'SUITABLE', t: 1, g: 1 },
      { w: 'REVAMP', t: 0 }, { w: 'NUMEROUS', t: 1 }, { w: 'REAPPEAR', t: 1 }, { w: 'LAVENDER', t: 0 },
      { w: 'UNWANTED', t: 0 }, { w: 'BREAKOUT', t: 1, g: 1 }, { w: 'WAYWARD', t: 0 }, { w: 'LENGTH', t: 0 },
      { w: 'SPRAINED', t: 0 }, { w: 'HOARD', t: 0 }, { w: 'HYDRATED', t: 0 }, { w: 'GRANTED', t: 0, g: 1 },
      { w: 'TRAVELED', t: 0, g: 1 }, { w: 'PLANT', t: 0 }, { w: 'DRUNK', t: 0 }, { w: 'FAILURES', t: 1, g: 1 },
      { w: 'OYSTERS', t: 0 }, { w: 'EERIE', t: 1 }, { w: 'NEEDLE', t: 0 }, { w: 'OVARIES', t: 1 },
    ],
  },
  {
    num: 62, quizId: 'axiom-9-23-26', live: '2026-09-23', dateLabel: 'September 23, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'vowels', n: 4 }, { k: 'norepeat' }, { k: 'len', n: 6 }, { k: 'nolet', c: 'W' }, { k: 'twinvowel' }],
    tiles: [
      { w: 'ROWS', t: 0 }, { w: 'AUNTIE', t: 1, g: 1 }, { w: 'ROBINS', t: 1 }, { w: 'CODEX', t: 0 },
      { w: 'WATCH', t: 0, g: 1 }, { w: 'REWARDS', t: 0 }, { w: 'RITUAL', t: 1 }, { w: 'OUTAGE', t: 1, g: 1 },
      { w: 'AWAKENED', t: 0, g: 1 }, { w: 'OFFICERS', t: 0 }, { w: 'SCRAPPED', t: 0 }, { w: 'SENSOR', t: 1 },
      { w: 'CLAWS', t: 0 }, { w: 'SLEW', t: 0 }, { w: 'CUBES', t: 0 }, { w: 'WALKWAY', t: 0 },
      { w: 'SHERRY', t: 1 }, { w: 'GOALIE', t: 1, g: 1 }, { w: 'REFERS', t: 1 }, { w: 'FOULED', t: 1 },
      { w: 'CEREAL', t: 1 }, { w: 'SILICONE', t: 0 }, { w: 'APACHE', t: 1 }, { w: 'ROUTED', t: 1 },
    ],
  },
  {
    num: 63, quizId: 'axiom-9-24-26', live: '2026-09-24', dateLabel: 'September 24, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'twinvowel' }, { k: 'norepeat' }, { k: 'startvowel' }, { k: 'len', n: 7 }, { k: 'nolet', c: 'H' }],
    tiles: [
      { w: 'INQUEST', t: 1, g: 1 }, { w: 'FLUENCY', t: 1 }, { w: 'GOODBYE', t: 1 }, { w: 'MANTLE', t: 0 },
      { w: 'ALDERMAN', t: 0 }, { w: 'SMEAR', t: 0 }, { w: 'INDOORS', t: 1 }, { w: 'AIRFLOW', t: 1 },
      { w: 'FETAL', t: 0 }, { w: 'SOLD', t: 0, g: 1 }, { w: 'REDEFINE', t: 0 }, { w: 'TREATS', t: 0 },
      { w: 'WEIGHED', t: 1 }, { w: 'DIOCESE', t: 1 }, { w: 'ENQUIRY', t: 1, g: 1 }, { w: 'OPINION', t: 1 },
      { w: 'CURES', t: 0 }, { w: 'SMOOTHER', t: 0 }, { w: 'DROOLING', t: 0 }, { w: 'FREEZING', t: 0 },
      { w: 'AMBIENT', t: 1, g: 1 }, { w: 'VISCERAL', t: 0, g: 1 }, { w: 'DOWNTIME', t: 0 }, { w: 'OPIOIDS', t: 1 },
    ],
  },
  {
    num: 64, quizId: 'axiom-9-25-26', live: '2026-09-25', dateLabel: 'September 25, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'len', n: 4 }, { k: 'startvowel' }, { k: 'nolet', c: 'E' }, { k: 'twinvowel' }, { k: 'norepeat' }],
    tiles: [
      { w: 'STAIR', t: 1 }, { w: 'LEFTIST', t: 0 }, { w: 'OUCH', t: 1, g: 1 }, { w: 'ENTICING', t: 0, g: 1 },
      { w: 'EMBODIES', t: 0 }, { w: 'DUEL', t: 1 }, { w: 'WELCOME', t: 0 }, { w: 'VAULTS', t: 1 },
      { w: 'BLOUSE', t: 1 }, { w: 'OVERCAME', t: 0 }, { w: 'ARTWORKS', t: 0, g: 1 }, { w: 'LADY', t: 1 },
      { w: 'AIMS', t: 1, g: 1 }, { w: 'SUIT', t: 1 }, { w: 'STARSHIP', t: 0 }, { w: 'IMPOSING', t: 0 },
      { w: 'ROUX', t: 1 }, { w: 'WAVE', t: 1 }, { w: 'MINIONS', t: 0 }, { w: 'OURS', t: 1, g: 1 },
      { w: 'SOARED', t: 1 }, { w: 'SOYBEAN', t: 1 }, { w: 'HEAT', t: 1 }, { w: 'CREATES', t: 0 },
    ],
  },
  {
    num: 65, quizId: 'axiom-9-26-26', live: '2026-09-26', dateLabel: 'September 26, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'vowels', n: 2 }, { k: 'len', n: 5 }, { k: 'endvowel' }, { k: 'hides', set: 'body' }, { k: 'nolet', c: 'F' }],
    tiles: [
      { w: 'UNDERAGE', t: 0 }, { w: 'FEMININE', t: 0 }, { w: 'YEARS', t: 1 }, { w: 'FATTY', t: 0, g: 1 },
      { w: 'PROVIDER', t: 0 }, { w: 'CHINO', t: 1, g: 1 }, { w: 'REVOLVER', t: 0 }, { w: 'FOOLISH', t: 0 },
      { w: 'EARTHLY', t: 1 }, { w: 'SPOILT', t: 1 }, { w: 'SHINE', t: 1, g: 1 }, { w: 'FLAG', t: 0 },
      { w: 'WHALING', t: 1 }, { w: 'MANGO', t: 1 }, { w: 'CHINA', t: 1, g: 1 }, { w: 'GRAFFITI', t: 0, g: 1 },
      { w: 'TEARS', t: 1 }, { w: 'FEELING', t: 0 }, { w: 'REALISES', t: 0 }, { w: 'BRIEFING', t: 0 },
      { w: 'SACKED', t: 1 }, { w: 'MISTAKES', t: 0 }, { w: 'WATCHING', t: 1 }, { w: 'ALERTS', t: 1 },
    ],
  },
  {
    num: 66, quizId: 'axiom-9-27-26', live: '2026-09-27', dateLabel: 'September 27, 2026', sunday: true,
    budget: 7,
    rules: [{ k: 'onevowel' }, { k: 'nolet', c: 'A' }, { k: 'sameends' }, { k: 'len', n: 4 }, { k: 'dbl' }, { k: 'twinvowel' }, { k: 'nolet', c: 'I' }],
    tiles: [
      { w: 'NOON', t: 1, g: 1 }, { w: 'DOMINANT', t: 0 }, { w: 'DESERVES', t: 1 }, { w: 'MAXIMUM', t: 0 },
      { w: 'STALKS', t: 0 }, { w: 'GLEAMING', t: 0, g: 1 }, { w: 'PEAKS', t: 0 }, { w: 'FILTHY', t: 1 },
      { w: 'GOON', t: 1 }, { w: 'MEEK', t: 1 }, { w: 'YACHT', t: 0 }, { w: 'MOANING', t: 0 },
      { w: 'REALIZED', t: 0 }, { w: 'BULL', t: 1 }, { w: 'SINGULAR', t: 0 }, { w: 'MILL', t: 1 },
      { w: 'LIANG', t: 0 }, { w: 'TOLL', t: 1 }, { w: 'SCRIPT', t: 1 }, { w: 'FACTS', t: 0 },
      { w: 'ROOT', t: 1 }, { w: 'ENZYME', t: 1 }, { w: 'PEEP', t: 1, g: 1 }, { w: 'PAVED', t: 0, g: 1 },
      { w: 'FLANKS', t: 0 }, { w: 'BROWS', t: 1 }, { w: 'SEES', t: 1, g: 1 }, { w: 'WARMLY', t: 0 },
    ],
  },
  {
    num: 67, quizId: 'axiom-9-28-26', live: '2026-09-28', dateLabel: 'September 28, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'len', n: 4 }, { k: 'nolet', c: 'W' }, { k: 'vowels', n: 1 }, { k: 'hides', set: 'number' }, { k: 'onevowel' }],
    tiles: [
      { w: 'WANDERER', t: 0 }, { w: 'AWKWARD', t: 0 }, { w: 'SHOWROOM', t: 0 }, { w: 'TEND', t: 1, g: 1 },
      { w: 'DOUBLY', t: 0 }, { w: 'RAMPS', t: 1 }, { w: 'TRIMMED', t: 0 }, { w: 'WIRE', t: 0 },
      { w: 'WORKLOAD', t: 0 }, { w: 'WEEK', t: 0 }, { w: 'MORGUE', t: 0 }, { w: 'LAWSUITS', t: 0 },
      { w: 'BOWLERS', t: 0 }, { w: 'BELLY', t: 1 }, { w: 'SENTINEL', t: 0 }, { w: 'WIRING', t: 0 },
      { w: 'WRETCHED', t: 0 }, { w: 'IMMUNITY', t: 0 }, { w: 'TENS', t: 1, g: 1 }, { w: 'WOES', t: 0, g: 1 },
      { w: 'CALL', t: 1 }, { w: 'CHILLS', t: 1 }, { w: 'TENT', t: 1, g: 1 }, { w: 'WRITTEN', t: 0, g: 1 },
    ],
  },
  {
    num: 68, quizId: 'axiom-9-29-26', live: '2026-09-29', dateLabel: 'September 29, 2026', sunday: false,
    budget: 6,
    rules: [{ k: 'endvowel' }, { k: 'nolet', c: 'N' }, { k: 'len', n: 7 }, { k: 'onevowel' }, { k: 'vowels', n: 2 }],
    tiles: [
      { w: 'SEPARATE', t: 0 }, { w: 'SPECTRE', t: 1, g: 1 }, { w: 'MOROCCO', t: 1 }, { w: 'ANGUISH', t: 0 },
      { w: 'GRANDPA', t: 1 }, { w: 'SHAVE', t: 0 }, { w: 'PURCHASE', t: 0 }, { w: 'WROTE', t: 0 },
      { w: 'DEFENSE', t: 1 }, { w: 'SORORITY', t: 0, g: 1 }, { w: 'PASSWORD', t: 0 }, { w: 'KETCHUP', t: 0 },
      { w: 'GERMAIN', t: 0 }, { w: 'MOLDING', t: 0 }, { w: 'TREMBLE', t: 1, g: 1 }, { w: 'BATHED', t: 0 },
      { w: 'HIKERS', t: 0, g: 1 }, { w: 'LASAGNA', t: 1 }, { w: 'OBSCURED', t: 0 }, { w: 'WRESTLE', t: 1, g: 1 },
      { w: 'MINDLESS', t: 0 }, { w: 'VICIOUS', t: 0 }, { w: 'BURROW', t: 0 }, { w: 'STAKE', t: 0 },
    ],
  },
];
