// Puzzle data for the daily game. Imported ONLY by the server page
// component, which filters to live<=today before passing puzzles to
// the client — so future puzzles (and their orders/years) never ship to
// the browser bundle.
//
// events MUST be authored in true chronological order (earliest first):
// the client treats array index as the answer key and seed-shuffles the
// display. `y` is the display year revealed on lock/reveal; `when` is a
// numeric year (negative = BC) used only by the validator to prove the
// authored order is really chronological. `theme` is a spoiler-free label
// shown above the board; `note` is a fun fact revealed at game end.
// `d` is each event's one-line story, shown ONLY on the end-of-game
// timeline (never during play — it could date the event). Every event
// must have one; keep it to a single short factual sentence.
export const PUZZLES = [
  {
    num: 1,
    quizId: 'dating-7-14-26',
    live: '2026-07-14',
    dateLabel: 'July 14, 2026',
    theme: 'The greatest hits',
    events: [
      { t: 'The Great Pyramid of Giza is completed', y: 'c. 2560 BC', when: -2560, d: 'It stayed the tallest building on Earth for more than 3,800 years.' },
      { t: 'The Colosseum opens in Rome', y: 'AD 80', when: 80, d: 'The emperor Titus opened it with a hundred days of games.' },
      { t: 'Magna Carta is sealed at Runnymede', y: '1215', when: 1215, d: 'King John never meant to keep it; the pope annulled it within ten weeks.' },
      { t: 'The Eiffel Tower is completed in Paris', y: '1889', when: 1889, d: 'Built as a temporary exhibit for a fair, with a 20-year permit.' },
      { t: 'Apollo 11 lands on the Moon', y: '1969', when: 1969, d: 'Armstrong and Aldrin walked for about two and a half hours; Collins stayed in orbit.' },
    ],
    note: 'Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.',
  },
  {
    num: 2,
    quizId: 'dating-7-15-26',
    live: '2026-07-15',
    dateLabel: 'July 15, 2026',
    theme: 'Older than you think',
    events: [
      { t: 'Teaching begins at Oxford University', y: 'c. 1096', when: 1096, d: 'No one founded it on purpose; there is no founding date on record at all.' },
      { t: 'The Aztecs found Tenochtitlan', y: '1325', when: 1325, d: 'Built on an island in a lake; Mexico City sits on the drained lakebed today.' },
      { t: 'Gutenberg prints his Bible', y: 'c. 1455', when: 1455, d: 'About 180 copies were printed; roughly 49 survive.' },
      { t: 'Harvard College is founded', y: '1636', when: 1636, d: 'It is 140 years older than the United States, and older than calculus.' },
      { t: 'The French Revolution begins', y: '1789', when: 1789, d: 'The Bastille held just seven prisoners on the day it fell.' },
    ],
    note: 'Oxford was already two centuries old when the Aztecs founded their capital.',
  },
  {
    num: 3,
    quizId: 'dating-7-16-26',
    live: '2026-07-16',
    dateLabel: 'July 16, 2026',
    theme: 'Inventions',
    events: [
      { t: 'Bell patents the telephone', y: '1876', when: 1876, d: 'A rival filed a similar claim at the same patent office on the very same day.' },
      { t: 'The Wright brothers fly at Kitty Hawk', y: '1903', when: 1903, d: 'The first flight lasted 12 seconds and covered 120 feet.' },
      { t: 'Fleming discovers penicillin', y: '1928', when: 1928, d: 'He found it growing on a petri dish he had left out over vacation.' },
      { t: 'The transistor is invented at Bell Labs', y: '1947', when: 1947, d: 'The first one stood half an inch tall; billions now fit on a fingernail-sized chip.' },
      { t: 'Tim Berners-Lee proposes the World Wide Web', y: '1989', when: 1989, d: "His boss stamped the proposal 'vague but exciting'; CERN later gave it away for free." },
    ],
    note: 'The telephone and the web are both Bell-shaped: Bell Labs, born from the telephone patent, built the transistor every web server runs on.',
  },
  {
    num: 4,
    quizId: 'dating-7-17-26',
    live: '2026-07-17',
    dateLabel: 'July 17, 2026',
    theme: 'The ancient world',
    events: [
      { t: 'The great sarsen circle of Stonehenge is raised', y: 'c. 2500 BC', when: -2500, d: 'The biggest stones weigh about 25 tons and were hauled some 15 miles.' },
      { t: 'Hammurabi issues his code of laws', y: 'c. 1754 BC', when: -1754, d: "282 laws carved in stone, including the original 'an eye for an eye'." },
      { t: 'The first recorded Olympic Games are held', y: '776 BC', when: -776, d: 'One event only: a sprint of about 200 yards, won by a cook named Coroebus.' },
      { t: 'Alexander the Great dies in Babylon', y: '323 BC', when: -323, d: 'Dead at 32, undefeated in battle from Greece to India.' },
      { t: 'Julius Caesar is assassinated', y: '44 BC', when: -44, d: 'Stabbed 23 times; his physician judged only one wound was fatal.' },
    ],
    note: 'BC years count backwards — the biggest number is the oldest. Stonehenge predates Hammurabi by seven centuries.',
  },
  {
    num: 5,
    quizId: 'dating-7-18-26',
    live: '2026-07-18',
    dateLabel: 'July 18, 2026',
    theme: 'American landmarks',
    events: [
      { t: 'The Mayflower lands at Plymouth', y: '1620', when: 1620, d: 'The 66-day crossing was aimed at Virginia; storms pushed it to Cape Cod.' },
      { t: 'The Declaration of Independence is signed', y: '1776', when: 1776, d: 'Most delegates actually signed on August 2, not July 4.' },
      { t: 'The Louisiana Purchase doubles the nation', y: '1803', when: 1803, d: 'Some 830,000 square miles from France, at under three cents an acre.' },
      { t: 'The Statue of Liberty is dedicated', y: '1886', when: 1886, d: 'A gift from France, shipped across the Atlantic in 350 pieces.' },
      { t: 'The Golden Gate Bridge opens', y: '1937', when: 1937, d: "Its 'International Orange' was a primer coat the architect fought to keep." },
    ],
    note: 'More time separates the Mayflower from the Declaration than separates the Declaration from the Statue of Liberty.',
  },
  {
    num: 6,
    quizId: 'dating-7-19-26',
    live: '2026-07-19',
    dateLabel: 'July 19, 2026',
    theme: 'Explorers',
    events: [
      { t: 'Marco Polo reaches China', y: 'c. 1275', when: 1275, d: 'He later dictated his famous travel book to a cellmate in a Genoese prison.' },
      { t: 'Columbus reaches the Americas', y: '1492', when: 1492, d: 'He believed he had reached the edge of Asia, and died still believing it.' },
      { t: "Magellan's expedition completes the first circumnavigation", y: '1522', when: 1522, d: "Of five ships and some 270 men, one ship and 18 men made it home. Magellan didn't." },
      { t: "Cook charts Australia's east coast", y: '1770', when: 1770, d: 'He claimed the coast for Britain and named it New South Wales.' },
      { t: 'Amundsen reaches the South Pole', y: '1911', when: 1911, d: 'He beat Scott by 34 days, thanks largely to sled dogs.' },
    ],
    note: 'Only 30 years separate Columbus crossing the Atlantic and a ship circling the entire globe.',
  },
  {
    num: 7,
    quizId: 'dating-7-20-26',
    live: '2026-07-20',
    dateLabel: 'July 20, 2026',
    theme: 'Masterpieces',
    events: [
      { t: 'Irish monks complete the Book of Kells', y: 'c. 800', when: 800, d: 'Twelve centuries on, it is still shown every day at Trinity College Dublin.' },
      { t: 'Leonardo begins the Mona Lisa', y: 'c. 1503', when: 1503, d: 'He carried her around for years and never delivered the commission.' },
      { t: 'Hamlet is first performed', y: 'c. 1600', when: 1600, d: "At roughly 30,000 words it is Shakespeare's longest play." },
      { t: "Beethoven's Ninth Symphony premieres", y: '1824', when: 1824, d: 'Nearly deaf, Beethoven had to be turned around to see the applause.' },
      { t: 'Picasso paints Guernica', y: '1937', when: 1937, d: "Painted in about five weeks for a world's fair, after the bombing that spring." },
    ],
    note: 'Leonardo and Shakespeare never overlapped — the Mona Lisa was begun 61 years before Shakespeare was born.',
  },
  {
    num: 8,
    quizId: 'dating-7-21-26',
    live: '2026-07-21',
    dateLabel: 'July 21, 2026',
    theme: 'Big ideas',
    events: [
      { t: 'Copernicus publishes his sun-centered model', y: '1543', when: 1543, d: 'The story goes that he saw the first printed copy on his deathbed.' },
      { t: 'Newton publishes the Principia', y: '1687', when: 1687, d: 'Edmond Halley, of comet fame, paid the printing costs out of pocket.' },
      { t: 'Darwin publishes On the Origin of Species', y: '1859', when: 1859, d: 'The first print run of 1,250 copies sold out to booksellers on day one.' },
      { t: 'Einstein completes general relativity', y: '1915', when: 1915, d: 'Confirmed four years later, when an eclipse showed starlight bending.' },
      { t: 'The DNA double helix is discovered', y: '1953', when: 1953, d: "Rosalind Franklin's X-ray image, Photo 51, was the crucial clue." },
    ],
    note: 'Each leap came faster than the last: 144 years from Copernicus to Newton, but only 38 from relativity to the double helix.',
  },
  {
    num: 9,
    quizId: 'dating-7-22-26',
    live: '2026-07-22',
    dateLabel: 'July 22, 2026',
    theme: 'Built to last',
    events: [
      { t: 'The Parthenon is completed in Athens', y: '438 BC', when: -438, d: 'It served as temple, church, and mosque before a 1687 powder blast wrecked it.' },
      { t: 'The Hagia Sophia is completed in Constantinople', y: 'AD 537', when: 537, d: "Justinian's engineers raised the great dome in under six years." },
      { t: 'Construction begins on the Leaning Tower of Pisa', y: '1173', when: 1173, d: 'It was already leaning before the builders reached the third story.' },
      { t: 'The Taj Mahal mausoleum is completed', y: '1648', when: 1648, d: 'A tomb for the empress Mumtaz Mahal, built by some 20,000 workers.' },
      { t: 'The Empire State Building opens', y: '1931', when: 1931, d: "So empty through the Depression that New Yorkers called it the Empty State Building." },
    ],
    note: 'The Empire State Building went up in 410 days. The Leaning Tower of Pisa took 199 years.',
  },
  {
    num: 10,
    quizId: 'dating-7-23-26',
    live: '2026-07-23',
    dateLabel: 'July 23, 2026',
    theme: 'Empires fall',
    events: [
      { t: 'Babylon falls to Cyrus the Great', y: '539 BC', when: -539, d: 'Herodotus says the Persians slipped in along the riverbed during a feast.' },
      { t: 'The Western Roman Empire falls', y: 'AD 476', when: 476, d: 'The last emperor, a teenager, was pensioned off rather than executed.' },
      { t: 'Constantinople falls to the Ottomans', y: '1453', when: 1453, d: 'Ottoman cannon breached walls that had held for a thousand years.' },
      { t: 'The Inca capital Cusco falls to Pizarro', y: '1533', when: 1533, d: 'An empire of millions, taken with under 200 Spaniards and local allies.' },
      { t: 'The Soviet Union is dissolved', y: '1991', when: 1991, d: 'The hammer and sickle came down over the Kremlin on Christmas Day.' },
    ],
    note: 'Constantinople outlived Rome by almost a thousand years — and fell just 80 years before the Inca capital.',
  },
  {
    num: 11,
    quizId: 'dating-7-24-26',
    live: '2026-07-24',
    dateLabel: 'July 24, 2026',
    theme: 'Getting around',
    events: [
      { t: 'The first passenger steam railway opens', y: '1825', when: 1825, d: 'Locomotion No. 1 pulled its passengers at about 15 miles per hour.' },
      { t: 'The London Underground opens', y: '1863', when: 1863, d: 'The first trains were steam-powered; the tunnels filled with smoke.' },
      { t: 'Benz patents the first gasoline automobile', y: '1886', when: 1886, d: 'Bertha Benz took the first road trip, 66 miles, without telling her husband.' },
      { t: 'Lindbergh flies solo across the Atlantic', y: '1927', when: 1927, d: 'Thirty-three and a half hours, New York to Paris, with no radio on board.' },
      { t: 'Gagarin becomes the first human in space', y: '1961', when: 1961, d: 'One orbit in 108 minutes, then a parachute jump from his own capsule.' },
    ],
    note: 'London had a subway 23 years before anyone had a car.',
  },
  {
    num: 12,
    quizId: 'dating-7-25-26',
    live: '2026-07-25',
    dateLabel: 'July 25, 2026',
    theme: 'Signals',
    events: [
      { t: 'Morse taps out the first telegraph message', y: '1844', when: 1844, d: "From Washington to Baltimore: 'What hath God wrought'." },
      { t: 'The first transatlantic cable is laid', y: '1858', when: 1858, d: 'Queen Victoria and President Buchanan traded messages; it died within a month.' },
      { t: 'Marconi sends radio across the Atlantic', y: '1901', when: 1901, d: 'The letter S, three dots, crossed from Cornwall to Newfoundland.' },
      { t: 'The first email is sent', y: '1971', when: 1971, d: 'Ray Tomlinson sent it to himself, and picked the @ sign that stuck.' },
      { t: 'The first iPhone goes on sale', y: '2007', when: 2007, d: 'People camped overnight for a phone with no app store and no copy-paste.' },
    ],
    note: 'The gap between the first email and the first iPhone is shorter than the gap between the telegraph and radio.',
  },
  {
    num: 13,
    quizId: 'dating-7-26-26',
    live: '2026-07-26',
    dateLabel: 'July 26, 2026',
    sunday: true,
    theme: 'Trailblazers',
    // SUNDAY EDITION: six events instead of five. Nellie Bly (1890) sits just
    // 13 years before Curie, so the extra slot is also the tightest call.
    events: [
      { t: 'Joan of Arc lifts the siege of Orleans', y: '1429', when: 1429, d: 'She was about seventeen at Orleans, and dead before she turned twenty.' },
      { t: 'Elizabeth I is crowned Queen of England', y: '1559', when: 1559, d: 'Her 44-year reign gave the whole era its name.' },
      { t: 'Nellie Bly circles the globe in 72 days', y: '1890', when: 1890, d: 'She set out to beat a fictional record and came home in 72 days, 6 hours, 11 minutes.' },
      { t: 'Marie Curie wins her first Nobel Prize', y: '1903', when: 1903, d: 'Still the only person with Nobel Prizes in two different sciences.' },
      { t: 'Amelia Earhart flies solo across the Atlantic', y: '1932', when: 1932, d: 'Only the second person to do it solo, five years after Lindbergh.' },
      { t: 'Valentina Tereshkova becomes the first woman in space', y: '1963', when: 1963, d: 'Her 48 orbits beat the flight time of every American astronaut to date, combined.' },
    ],
    note: 'Just 31 years separate the first solo Atlantic flight by a woman and the first woman in orbit.',
  },
  {
    num: 14,
    quizId: 'dating-7-27-26',
    live: '2026-07-27',
    dateLabel: 'July 27, 2026',
    theme: 'Game on',
    events: [
      { t: 'The first modern Olympics open in Athens', y: '1896', when: 1896, d: '14 nations, 241 athletes, all men; winners received silver medals.' },
      { t: 'The first World Series is played', y: '1903', when: 1903, d: 'Boston beat Pittsburgh five games to three in a best-of-nine.' },
      { t: 'The first FIFA World Cup kicks off', y: '1930', when: 1930, d: 'Hosts Uruguay won it; only 13 teams entered, four of them from Europe.' },
      { t: 'Bannister breaks the four-minute mile', y: '1954', when: 1954, d: '3:59.4 at a small meet in Oxford; the record stood for just 46 days.' },
      { t: 'The first Super Bowl is played', y: '1967', when: 1967, d: "Packers 35, Chiefs 10; tickets averaged about $12 and it didn't sell out." },
    ],
    note: 'The World Series is older than the World Cup by 27 years — and the Super Bowl is younger than both.',
  },
  {
    num: 15,
    quizId: 'dating-7-28-26',
    live: '2026-07-28',
    dateLabel: 'July 28, 2026',
    theme: 'When disaster struck',
    events: [
      { t: 'Vesuvius buries Pompeii', y: 'AD 79', when: 79, d: 'The eruption sealed the Roman town under ash in a matter of hours, preserving it for centuries.' },
      { t: 'The Lisbon earthquake', y: '1755', when: 1755, d: 'A quake, fire, and tsunami struck on All Saints\' Day and helped give rise to the science of seismology.' },
      { t: 'Krakatoa erupts', y: '1883', when: 1883, d: 'The blast was heard some 3,000 miles away and dimmed skies around the world for months.' },
      { t: 'The San Francisco earthquake', y: '1906', when: 1906, d: 'The shaking and the fires that followed leveled much of the city within three days.' },
      { t: 'The Titanic sinks', y: '1912', when: 1912, d: 'The liner billed as unsinkable went down on its maiden voyage after striking an iceberg.' },
    ],
    note: 'The Lisbon quake so shook Enlightenment Europe that Voltaire wrote it straight into Candide.',
  },
  {
    num: 16,
    quizId: 'dating-7-29-26',
    live: '2026-07-29',
    dateLabel: 'July 29, 2026',
    theme: 'Lost and found',
    events: [
      { t: 'The Rosetta Stone is unearthed', y: '1799', when: 1799, d: 'French soldiers in Egypt turned up the slab whose three scripts finally unlocked hieroglyphics.' },
      { t: 'Machu Picchu is revealed to the world', y: '1911', when: 1911, d: 'Hiram Bingham was led to the Inca ridge-top city by local farmers who had never lost track of it.' },
      { t: "Tutankhamun's tomb is opened", y: '1922', when: 1922, d: 'Asked if he could see anything, Howard Carter answered, "Yes, wonderful things."' },
      { t: 'The Dead Sea Scrolls are found', y: '1947', when: 1947, d: 'A Bedouin shepherd threw a stone into a cave, heard pottery break, and found the oldest biblical manuscripts.' },
      { t: 'The Terracotta Army is uncovered', y: '1974', when: 1974, d: 'Farmers digging a well struck an 8,000-strong clay army guarding China\'s first emperor.' },
    ],
    note: 'Nearly every one was an accident — soldiers, shepherds, and well-diggers made the first find, not archaeologists.',
  },
  {
    num: 17,
    quizId: 'dating-7-30-26',
    live: '2026-07-30',
    dateLabel: 'July 30, 2026',
    theme: 'At the movies',
    events: [
      { t: 'The Lumiere brothers hold the first paid film screening', y: '1895', when: 1895, d: 'Paris audiences paid to watch short films projected on a screen for the very first time.' },
      { t: 'The Jazz Singer brings sound to features', y: '1927', when: 1927, d: 'The first feature-length "talkie" let audiences hear a star speak and sing, ending the silent era.' },
      { t: 'Disney releases Snow White', y: '1937', when: 1937, d: 'The first full-length animated feature was mocked as "Disney\'s Folly" until it became a smash.' },
      { t: 'Star Wars opens', y: '1977', when: 1977, d: 'George Lucas\'s space epic reinvented the summer blockbuster and the movie special effect.' },
      { t: 'Pixar releases Toy Story', y: '1995', when: 1995, d: 'The tale of toys was the first feature film animated entirely on computers.' },
    ],
    note: 'A century of moviegoing in five steps: silent shorts, then sound, then color animation, then fully computer-made worlds.',
  },
  {
    num: 18,
    quizId: 'dating-7-31-26',
    live: '2026-07-31',
    dateLabel: 'July 31, 2026',
    theme: 'Household names',
    events: [
      { t: 'The first Coca-Cola is served in Atlanta', y: '1886', when: 1886, d: 'Pharmacist John Pemberton sold the first glass for five cents at a downtown soda fountain.' },
      { t: 'Ford introduces the Model T', y: '1908', when: 1908, d: 'At $850 it put a car within reach of ordinary families and went on to sell over 15 million.' },
      { t: 'The McDonald brothers open their first restaurant', y: '1940', when: 1940, d: 'It began as a barbecue drive-in in San Bernardino, years before the golden arches and the burger empire.' },
      { t: 'The Barbie doll goes on sale', y: '1959', when: 1959, d: 'She debuted at the New York Toy Fair as the first mass-produced doll with adult features.' },
      { t: 'Apple is founded', y: '1976', when: 1976, d: 'Jobs and Wozniak started it in a garage to sell the hand-built Apple I circuit board.' },
    ],
    note: 'Every one of these started small — a soda fountain, a drive-in, a garage — before the name went global.',
  },
  {
    num: 19,
    quizId: 'dating-8-1-26',
    live: '2026-08-01',
    dateLabel: 'August 1, 2026',
    theme: 'Eyes on the sky',
    events: [
      { t: 'Galileo spots four moons orbiting Jupiter', y: '1610', when: 1610, d: 'Worlds circling another planet helped topple the idea that everything orbits the Earth.' },
      { t: 'Herschel discovers Uranus', y: '1781', when: 1781, d: 'The first planet ever found with a telescope; at first he took it for a comet.' },
      { t: 'Neptune is found where math predicted', y: '1846', when: 1846, d: 'Calculated from wobbles in the orbit of Uranus, then spotted the very same night.' },
      { t: 'Clyde Tombaugh discovers Pluto', y: '1930', when: 1930, d: 'A 24-year-old caught it by comparing photographs of the same star field taken days apart.' },
      { t: 'Astronomers capture the first image of a black hole', y: '2019', when: 2019, d: 'A planet-spanning array of radio telescopes imaged the glowing ring around the black hole in galaxy M87.' },
    ],
    note: "Four centuries of one quest: from Jupiter's moons in a homemade spyglass to a black hole imaged across the galaxy.",
  },
  {
    num: 20,
    quizId: 'dating-8-2-26',
    live: '2026-08-02',
    dateLabel: 'August 2, 2026',
    sunday: true,
    theme: 'Into the unknown',
    events: [
      { t: 'Columbus reaches the Americas', y: '1492', when: 1492, d: 'Looking for a westward sea route to Asia, he made landfall in the Bahamas and believed he had found the Indies.' },
      { t: "Magellan's expedition completes the first voyage around the world", y: '1522', when: 1522, d: 'Magellan died along the way; just 18 of about 270 men brought the last ship home.' },
      { t: 'Captain Cook charts the east coast of Australia', y: '1770', when: 1770, d: 'He came ashore at the inlet he named Botany Bay and claimed the coast for Britain.' },
      { t: 'Amundsen reaches the South Pole', y: '1911', when: 1911, d: 'His Norwegian team beat Robert Scott to the pole by about five weeks.' },
      { t: 'Hillary and Tenzing reach the summit of Everest', y: '1953', when: 1953, d: 'They spent roughly fifteen minutes on the top of the world before starting the descent.' },
      { t: 'Yuri Gagarin becomes the first human in space', y: '1961', when: 1961, d: 'A single orbit of the Earth lasted 108 minutes and made him famous overnight.' },
    ],
    note: 'The first voyage around the world took nearly three years by sea; Gagarin circled the whole planet in under two hours.',
  },
  {
    num: 21,
    quizId: 'dating-8-3-26',
    live: '2026-08-03',
    dateLabel: 'August 3, 2026',
    theme: 'Getting the message across',
    events: [
      { t: 'Gutenberg prints his Bible with movable type', y: 'c. 1455', when: 1455, d: 'Mechanical printing dropped the price of books and let ideas spread across Europe.' },
      { t: 'The first message crosses the transatlantic telegraph cable', y: '1858', when: 1858, d: 'A greeting between Queen Victoria and the US president took about sixteen hours to send.' },
      { t: 'Bell patents the telephone', y: '1876', when: 1876, d: 'His first words down the wire asked his assistant to come into the room.' },
      { t: 'Baird gives the first public demonstration of television', y: '1926', when: 1926, d: 'He showed a moving, recognizable human face to a room of London scientists.' },
      { t: 'The first text message is sent', y: '1992', when: 1992, d: 'An engineer typed the words "Merry Christmas" from a computer to a mobile phone.' },
    ],
    note: 'Five centuries separate the printing press and the text message, yet both were built to carry a few words further and faster.',
  },
  {
    num: 22,
    quizId: 'dating-8-4-26',
    live: '2026-08-04',
    dateLabel: 'August 4, 2026',
    theme: 'Feats of engineering',
    events: [
      { t: 'The Eiffel Tower is completed in Paris', y: '1889', when: 1889, d: 'Built for the World\'s Fair, it was the tallest structure on Earth for over forty years.' },
      { t: 'The Panama Canal opens', y: '1914', when: 1914, d: 'The shortcut between the Atlantic and Pacific cut thousands of miles off the sea voyage.' },
      { t: 'The Empire State Building is finished', y: '1931', when: 1931, d: 'It rose in just over a year and stood as the world\'s tallest building for nearly four decades.' },
      { t: 'The Golden Gate Bridge opens', y: '1937', when: 1937, d: 'Its record-setting main span linked San Francisco to Marin County in burnt-orange steel.' },
      { t: 'The Burj Khalifa opens in Dubai', y: '2010', when: 2010, d: 'At over 828 meters it became, and remains, the tallest building in the world.' },
    ],
    note: 'From wrought iron in Paris to a half-mile tower in the desert, each project briefly claimed a record of its own.',
  },
  {
    num: 23,
    quizId: 'dating-8-5-26',
    live: '2026-08-05',
    dateLabel: 'August 5, 2026',
    theme: 'Breaking free',
    events: [
      { t: 'The United States declares independence', y: '1776', when: 1776, d: 'Thirteen colonies announced their separation from Britain with the Declaration of Independence.' },
      { t: 'Haiti wins its independence', y: '1804', when: 1804, d: 'A successful revolt by enslaved people created the first free Black republic in the world.' },
      { t: 'Mexico secures independence from Spain', y: '1821', when: 1821, d: 'A struggle that began in 1810 finally ended three centuries of Spanish colonial rule.' },
      { t: 'Brazil declares independence from Portugal', y: '1822', when: 1822, d: 'Prince Pedro broke with Lisbon and was crowned emperor of a newly independent Brazil.' },
      { t: 'India gains independence from Britain', y: '1947', when: 1947, d: 'After decades of nonviolent struggle, British rule ended and the subcontinent was partitioned.' },
    ],
    note: 'Nearly two centuries of independence movements, each ending the rule of a distant European crown.',
  },
  {
    num: 24,
    quizId: 'dating-8-6-26',
    live: '2026-08-06',
    dateLabel: 'August 6, 2026',
    theme: 'Milestones of medicine',
    events: [
      { t: 'Edward Jenner develops the smallpox vaccine', y: '1796', when: 1796, d: 'He showed that exposure to cowpox could protect against deadly smallpox, founding vaccination.' },
      { t: 'Alexander Fleming discovers penicillin', y: '1928', when: 1928, d: 'A stray mold on a petri dish revealed the first true antibiotic and transformed medicine.' },
      { t: 'The polio vaccine is proven effective', y: '1955', when: 1955, d: 'Trials confirmed that Jonas Salk\'s vaccine worked, easing a disease that had paralyzed children.' },
      { t: 'The first human heart transplant is performed', y: '1967', when: 1967, d: 'Surgeon Christiaan Barnard replaced a dying patient\'s heart in a landmark operation in South Africa.' },
      { t: 'The Human Genome Project is completed', y: '2003', when: 2003, d: 'Scientists finished mapping the roughly three billion letters of human DNA.' },
    ],
    note: 'Two centuries of medical firsts, from a country doctor\'s experiment to the reading of the entire human genome.',
  },
  {
    num: 25,
    quizId: 'dating-8-7-26',
    live: '2026-08-07',
    dateLabel: 'August 7, 2026',
    theme: 'Sporting firsts',
    events: [
      { t: 'The first modern Olympic Games are held in Athens', y: '1896', when: 1896, d: 'Athletes from fourteen nations revived the ancient games in a marble stadium.' },
      { t: 'The first Tour de France is run', y: '1903', when: 1903, d: 'A newspaper staged the grueling bicycle race to boost its circulation.' },
      { t: 'The first FIFA World Cup kicks off in Uruguay', y: '1930', when: 1930, d: 'The host nation won the inaugural football tournament before its home crowd.' },
      { t: 'The first Super Bowl is played', y: '1967', when: 1967, d: 'Green Bay beat Kansas City in a title game that would grow into an American institution.' },
      { t: 'The first Cricket World Cup is held', y: '1975', when: 1975, d: 'West Indies won the inaugural tournament, played in England over just two weeks.' },
    ],
    note: 'Eight decades of inaugural tournaments, each the humble start of an event that now draws billions.',
  },
  {
    num: 26,
    quizId: 'dating-8-8-26',
    live: '2026-08-08',
    dateLabel: 'August 8, 2026',
    theme: 'Sounds that moved millions',
    events: [
      { t: 'Beethoven\'s Ninth Symphony premieres in Vienna', y: '1824', when: 1824, d: 'Its choral finale, the Ode to Joy, broke every rule about what a symphony could be.' },
      { t: 'The first jazz record is released', y: '1917', when: 1917, d: 'The Original Dixieland Jass Band put the new American sound onto a commercial disc.' },
      { t: 'Elvis Presley releases Heartbreak Hotel', y: '1956', when: 1956, d: 'His first million-selling single helped push rock and roll into the mainstream.' },
      { t: 'The Beatles appear on The Ed Sullivan Show', y: '1964', when: 1964, d: 'An estimated 73 million Americans watched, igniting Beatlemania across the country.' },
      { t: 'MTV launches', y: '1981', when: 1981, d: 'The channel began with the pointed clip Video Killed the Radio Star and made music visual.' },
    ],
    note: 'A century and a half of sound, from a Vienna concert hall to music beamed straight into living rooms.',
  },
  {
    num: 27,
    quizId: 'dating-8-9-26',
    live: '2026-08-09',
    dateLabel: 'August 9, 2026',
    sunday: true,
    theme: 'The century that reshaped the world',
    events: [
      { t: 'The Titanic sinks on its maiden voyage', y: '1912', when: 1912, d: 'The ship believed unsinkable went down in the North Atlantic after striking an iceberg.' },
      { t: 'World War I begins', y: '1914', when: 1914, d: 'The assassination of an archduke pulled Europe\'s great powers into four years of war.' },
      { t: 'The Wall Street crash triggers the Great Depression', y: '1929', when: 1929, d: 'A collapse in stock prices wiped out fortunes and ushered in a decade of hardship.' },
      { t: 'World War II ends', y: '1945', when: 1945, d: 'The deadliest conflict in history closed with surrenders in Europe and the Pacific.' },
      { t: 'The Berlin Wall falls', y: '1989', when: 1989, d: 'Crowds tore down the barrier that had split the city, hastening the end of the Cold War.' },
      { t: 'The World Wide Web opens to the public', y: '1991', when: 1991, d: 'Tim Berners-Lee released the web to everyone, quietly beginning the internet age.' },
    ],
    note: 'Six turning points across eighty years, from a lost ocean liner to the network that now connects the planet.',
  },
  {
    num: 28,
    quizId: 'dating-8-10-26',
    live: '2026-08-10',
    dateLabel: 'August 10, 2026',
    theme: 'The world gets faster',
    events: [
      { t: 'The Stockton and Darlington Railway opens', y: '1825', when: 1825, d: 'The first public railway to run steam locomotives began carrying passengers and coal in England.' },
      { t: 'The first transcontinental railroad is completed', y: '1869', when: 1869, d: 'A golden spike in Utah joined the coasts and cut a cross-country trip from months to days.' },
      { t: 'Louis Bleriot flies across the English Channel', y: '1909', when: 1909, d: 'His fragile monoplane made the first heavier-than-air flight between Britain and France.' },
      { t: 'Charles Lindbergh flies solo across the Atlantic', y: '1927', when: 1927, d: 'His 33-hour flight from New York to Paris made him an overnight worldwide celebrity.' },
      { t: 'The first commercial jet airliner enters service', y: '1952', when: 1952, d: 'The de Havilland Comet began carrying passengers, opening the age of jet travel.' },
    ],
    note: 'From a coal railway to the passenger jet, each leap shrank the distance between distant places.',
  },
  {
    num: 29,
    quizId: 'dating-8-11-26',
    live: '2026-08-11',
    dateLabel: 'August 11, 2026',
    theme: "The space age, in order",
    events: [
      { t: "Sputnik 1 becomes the first satellite in orbit", y: "1957", when: 1957, d: "A polished metal sphere the size of a beach ball began the space age and alarmed Washington." },
      { t: "Yuri Gagarin becomes the first person in space", y: "1961", when: 1961, d: "One orbit of the Earth in 108 minutes made a 27-year-old pilot the most famous man alive." },
      { t: "Valentina Tereshkova becomes the first woman in space", y: "1963", when: 1963, d: "She flew 48 orbits solo, more time in space than every American astronaut to that date combined." },
      { t: "Apollo 8 carries the first people around the Moon", y: "1968", when: 1968, d: "Three men read from Genesis on Christmas Eve and photographed the Earth rising over the limb." },
      { t: "Viking 1 sends the first pictures from the surface of Mars", y: "1976", when: 1976, d: "The lander touched down on Chryse Planitia and returned a photograph of its own footpad." },
    ],
    note: "Five moments spanning 1957 to 1976, and the order is the whole puzzle.",
  },
  {
    num: 30,
    quizId: 'dating-8-12-26',
    live: '2026-08-12',
    dateLabel: 'August 12, 2026',
    theme: "Wars and the peace that followed",
    events: [
      { t: "The Battle of Waterloo ends Napoleon's return", y: "1815", when: 1815, d: "Wellington and Blucher closed two decades of European war in a single muddy afternoon." },
      { t: "The American Civil War ends at Appomattox", y: "1865", when: 1865, d: "Lee surrendered the Army of Northern Virginia and four years of fighting stopped within weeks." },
      { t: "The First World War begins", y: "1914", when: 1914, d: "The assassination of an archduke pulled Europe's alliances into four years of trench warfare." },
      { t: "An atomic bomb destroys Hiroshima", y: "1945", when: 1945, d: "One weapon flattened the city centre and Japan surrendered within nine days." },
      { t: "The Cuban Missile Crisis brings the superpowers to the brink", y: "1962", when: 1962, d: "Thirteen days of blockade and back-channel talks ended with the missiles withdrawn." },
    ],
    note: "Five moments spanning 1815 to 1962, and the order is the whole puzzle.",
  },
  {
    num: 31,
    quizId: 'dating-8-13-26',
    live: '2026-08-13',
    dateLabel: 'August 13, 2026',
    theme: "Science, one discovery at a time",
    events: [
      { t: "Galileo publishes what he saw through the telescope", y: "1610", when: 1610, d: "Galileo published what he had seen through the telescope, including four moons circling Jupiter." },
      { t: "Newton publishes the Principia", y: "1687", when: 1687, d: "Three laws of motion and one of gravitation explained both the tides and the planets." },
      { t: "Marie Curie isolates radium", y: "1898", when: 1898, d: "Years of processing pitchblende in a shed yielded a tenth of a gram of a new element." },
      { t: "Einstein publishes the theory of general relativity", y: "1915", when: 1915, d: "Gravity became the curvature of spacetime, and starlight was found to bend as predicted." },
      { t: "The Human Genome Project begins", y: "1990", when: 1990, d: "An international effort set out to read all three billion letters of human DNA." },
    ],
    note: "Five moments spanning 1610 to 1990, and the order is the whole puzzle.",
  },
  {
    num: 32,
    quizId: 'dating-8-14-26',
    live: '2026-08-14',
    dateLabel: 'August 14, 2026',
    theme: "Machines that changed the day",
    events: [
      { t: "The first passenger railway opens", y: "1825", when: 1825, d: "Locomotion No. 1 hauled wagons of coal and passengers, and the railway age began." },
      { t: "The first adhesive postage stamp is issued", y: "1840", when: 1840, d: "The first adhesive postage stamp made a letter cost the same to anywhere in the country." },
      { t: "The first mobile phone call is made", y: "1973", when: 1973, d: "An engineer stood on a New York pavement and rang his rival at the competing lab." },
      { t: "Berners-Lee proposes the World Wide Web", y: "1989", when: 1989, d: "A memo at CERN described hypertext over the internet, and his boss called it vague but exciting." },
      { t: "The first iPhone is unveiled", y: "2007", when: 2007, d: "A phone that was all screen, and the pocket computer arrived." },
    ],
    note: "Five moments spanning 1825 to 2007, and the order is the whole puzzle.",
  },
  {
    num: 33,
    quizId: 'dating-8-15-26',
    live: '2026-08-15',
    dateLabel: 'August 15, 2026',
    theme: "Moments that changed who decides",
    events: [
      { t: "The American colonies declare independence", y: "1776", when: 1776, d: "Thirteen colonies adopted Jefferson's text and announced a separation from the British crown." },
      { t: "Britain abolishes the slave trade", y: "1807", when: 1807, d: "Twenty years of campaigning ended the trade in British ships, though slavery itself lasted longer." },
      { t: "The Emancipation Proclamation takes effect", y: "1863", when: 1863, d: "Lincoln declared enslaved people in the rebelling states free, and the war changed purpose." },
      { t: "India becomes independent", y: "1947", when: 1947, d: "Freedom came at midnight, and partition displaced perhaps fifteen million people." },
      { t: "Hong Kong is handed back to China", y: "1997", when: 1997, d: "A midnight ceremony ended 156 years of British administration." },
    ],
    note: "Five moments spanning 1776 to 1997, and the order is the whole puzzle.",
  },
  {
    num: 34,
    quizId: 'dating-8-16-26',
    live: '2026-08-16',
    dateLabel: 'August 16, 2026',
    sunday: true,
    theme: "Days the ground moved",
    events: [
      { t: "The Great Fire destroys much of London", y: "1666", when: 1666, d: "Four days of fire from Pudding Lane took thirteen thousand houses and old St Paul's." },
      { t: "Krakatoa erupts and is heard three thousand miles away", y: "1883", when: 1883, d: "The blast destroyed most of the island and lowered global temperatures for a year." },
      { t: "The Johnstown flood follows a dam failure", y: "1889", when: 1889, d: "A neglected earth dam gave way and a wall of water took more than two thousand lives." },
      { t: "The Titanic sinks on her maiden voyage", y: "1912", when: 1912, d: "The ship went down two hours and forty minutes after striking an iceberg." },
      { t: "Mount St Helens erupts", y: "1980", when: 1980, d: "The north face slid away in the largest landslide ever recorded and the summit lost 400 metres." },
      { t: "A tsunami crosses the Indian Ocean", y: "2004", when: 2004, d: "A magnitude 9.1 rupture off Sumatra killed some 230,000 people in a dozen countries." },
    ],
    note: "Six moments spanning 1666 to 2004, and the order is the whole puzzle.",
  },
  {
    num: 35,
    quizId: 'dating-8-17-26',
    live: '2026-08-17',
    dateLabel: 'August 17, 2026',
    theme: "Before the Middle Ages",
    events: [
      { t: "The first Olympic Games are held at Olympia", y: "776 BC", when: -776, d: "A single foot race down the stadium, run by men from a scatter of Greek cities." },
      { t: "The Battle of Marathon halts a Persian invasion", y: "490 BC", when: -490, d: "Athenian hoplites broke a much larger force on the plain and the news ran to the city." },
      { t: "Hadrian's Wall is begun", y: "122", when: 122, d: "Eighty miles of stone and turf marked the northern edge of the Roman province." },
      { t: "The Domesday Book is completed", y: "1086", when: 1086, d: "A survey of England so thorough that contemporaries compared it to the Last Judgement." },
      { t: "The core module of the Mir space station is launched", y: "1986", when: 1986, d: "The first module of the Soviet station went up, and people lived aboard for fifteen years." },
    ],
    note: "Five moments spanning 776 BC to 1986, and the order is the whole puzzle.",
  },
  {
    num: 36,
    quizId: 'dating-8-18-26',
    live: '2026-08-18',
    dateLabel: 'August 18, 2026',
    theme: "Nights people still talk about",
    events: [
      { t: "Handel's Messiah is first performed", y: "1742", when: 1742, d: "The premiere was in Dublin, for charity, and the hall asked ladies to come without hoops." },
      { t: "Beethoven's Ninth Symphony is premiered", y: "1824", when: 1824, d: "The composer was too deaf to hear the applause and had to be turned to see it." },
      { t: "The first feature film with synchronised speech opens", y: "1927", when: 1927, d: "Audiences heard an actor speak from the screen and silent cinema was finished within three years." },
      { t: "Four hundred thousand gather at Woodstock", y: "1969", when: 1969, d: "Four hundred thousand people came to a dairy farm for three days of music and mud." },
      { t: "Live Aid raises money on two continents at once", y: "1985", when: 1985, d: "Sixteen hours of music from London and Philadelphia reached an audience of nearly two billion." },
    ],
    note: "Five moments spanning 1742 to 1985, and the order is the whole puzzle.",
  },
  {
    num: 37,
    quizId: 'dating-8-19-26',
    live: '2026-08-19',
    dateLabel: 'August 19, 2026',
    theme: "Five turning points, oldest first",
    events: [
      { t: "Rosa Parks is arrested and the bus boycott begins", y: "1955", when: 1955, d: "Her arrest in Montgomery started a boycott that lasted more than a year." },
      { t: "The first message is sent over ARPANET", y: "1969", when: 1969, d: "The system crashed after two letters, but the network that became the internet had spoken." },
      { t: "The first Space Shuttle reaches orbit", y: "1981", when: 1981, d: "Columbia flew with two men aboard on its maiden flight, a first for any spacecraft." },
      { t: "The Challenger breaks apart after launch", y: "1986", when: 1986, d: "A failed booster seal in freezing weather destroyed the orbiter and its crew of seven." },
      { t: "Mandela is elected president of South Africa", y: "1994", when: 1994, d: "Queues stretched for miles in the country's first election with universal suffrage." },
    ],
    note: "Five moments spanning 1955 to 1994, and the order is the whole puzzle.",
  },
  {
    num: 38,
    quizId: 'dating-8-20-26',
    live: '2026-08-20',
    dateLabel: 'August 20, 2026',
    theme: "Setting out for the edge of the map",
    events: [
      { t: "A small Greek force holds the pass at Thermopylae", y: "480 BC", when: -480, d: "A Greek rearguard held the pass for three days before being outflanked by a mountain path." },
      { t: "Magellan's expedition sets out to circle the globe", y: "1519", when: 1519, d: "Five ships left Seville; one came home three years later with eighteen men aboard." },
      { t: "Cook sets out on his first Pacific voyage", y: "1768", when: 1768, d: "The Endeavour left Plymouth to observe a transit of Venus and kept going for three years." },
      { t: "Amundsen reaches the South Pole", y: "1911", when: 1911, d: "His party arrived five weeks ahead of Scott and came home without losing a man." },
      { t: "Hillary and Tenzing reach the summit of Everest", y: "1953", when: 1953, d: "They stood on the top for fifteen minutes and were back at the South Col by nightfall." },
    ],
    note: "Five moments spanning 480 BC to 1953, and the order is the whole puzzle.",
  },
  {
    num: 39,
    quizId: 'dating-8-21-26',
    live: '2026-08-21',
    dateLabel: 'August 21, 2026',
    theme: "A run through the centuries",
    events: [
      { t: "Alexander the Great dies at Babylon", y: "323 BC", when: -323, d: "He had conquered from Greece to the Indus and left no settled heir at thirty-two." },
      { t: "The Black Death reaches Europe", y: "1347", when: 1347, d: "Galleys put in at Messina carrying a plague that killed perhaps a third of the continent." },
      { t: "Gutenberg begins printing with movable type", y: "1450", when: 1450, d: "Movable metal type made books cheap enough to outrun any authority trying to chase them." },
      { t: "The Chernobyl reactor explodes", y: "1986", when: 1986, d: "A botched safety test blew the roof off reactor four and contaminated a swathe of Europe." },
      { t: "The Hubble Space Telescope is placed in orbit", y: "1990", when: 1990, d: "Its mirror was flawed, and a shuttle crew fitted corrective optics three years later." },
    ],
    note: "Five moments spanning 323 BC to 1990, and the order is the whole puzzle.",
  },
  {
    num: 40,
    quizId: 'dating-8-22-26',
    live: '2026-08-22',
    dateLabel: 'August 22, 2026',
    theme: "Out past the atmosphere",
    events: [
      { t: "Voyager 1 launches on a tour of the outer planets", y: "1977", when: 1977, d: "It is now the most distant human object, still returning data from interstellar space." },
      { t: "Cassini launches for Saturn", y: "1997", when: 1997, d: "It took seven years to arrive and spent thirteen more circling the planet and its moons." },
      { t: "The first module of the International Space Station is launched", y: "1998", when: 1998, d: "A Russian module went up alone and the station was assembled around it over a decade." },
      { t: "A rover finds evidence of ancient water on Mars", y: "2004", when: 2004, d: "Opportunity landed in a crater and found rocks that had formed in standing water." },
      { t: "New Horizons launches on a nine-year flight to Pluto", y: "2006", when: 2006, d: "The fastest spacecraft ever launched still needed nine years to reach the outer solar system." },
    ],
    note: "Five moments spanning 1977 to 2006, and the order is the whole puzzle.",
  },
  {
    num: 41,
    quizId: 'dating-8-23-26',
    live: '2026-08-23',
    dateLabel: 'August 23, 2026',
    sunday: true,
    theme: "Battles that redrew a map",
    events: [
      { t: "The Battle of Hastings decides the English crown", y: "1066", when: 1066, d: "Harold fell and William of Normandy took a kingdom that changed language, law and landholding." },
      { t: "Constantinople falls to Ottoman cannon", y: "1453", when: 1453, d: "The Theodosian walls were breached after fifty-three days and the Byzantine empire ended." },
      { t: "The Spanish Armada is scattered", y: "1588", when: 1588, d: "Fire ships broke the crescent off Calais and the weather finished what the guns began." },
      { t: "The Armistice silences the guns", y: "1918", when: 1918, d: "The fighting stopped at the eleventh hour, with an estimated seventeen million dead." },
      { t: "The Second World War begins in Europe", y: "1939", when: 1939, d: "Germany invaded Poland and Britain and France declared war two days later." },
      { t: "Allied troops land in Normandy", y: "1944", when: 1944, d: "Some 156,000 men crossed the Channel in the largest seaborne invasion ever attempted." },
    ],
    note: "Six moments spanning 1066 to 1944, and the order is the whole puzzle.",
  },
  {
    num: 42,
    quizId: 'dating-8-24-26',
    live: '2026-08-24',
    dateLabel: 'August 24, 2026',
    theme: "How we worked it out",
    events: [
      { t: "Copernicus places the Sun at the centre", y: "1543", when: 1543, d: "He received the printed book on his deathbed, and the Earth stopped being the centre of things." },
      { t: "Jenner publishes his work on vaccination", y: "1798", when: 1798, d: "His inquiry into cowpox laid out the method that would eventually eradicate smallpox." },
      { t: "Darwin publishes On the Origin of Species", y: "1859", when: 1859, d: "The first printing sold out in a day and recast biology around descent with modification." },
      { t: "Fleming notices a mould that kills bacteria", y: "1928", when: 1928, d: "A contaminated dish cleared itself of staphylococcus and the antibiotic age followed." },
      { t: "Gravitational waves are detected for the first time", y: "2015", when: 2015, d: "Two black holes merged a billion years ago and shook the detectors for a fifth of a second." },
    ],
    note: "Five moments spanning 1543 to 2015, and the order is the whole puzzle.",
  },
  {
    num: 43,
    quizId: 'dating-8-25-26',
    live: '2026-08-25',
    dateLabel: 'August 25, 2026',
    theme: "Inventions, oldest first",
    events: [
      { t: "Bell makes the first telephone call", y: "1876", when: 1876, d: "He called his assistant in the next room, and the human voice travelled by wire." },
      { t: "Edison demonstrates a practical electric light", y: "1879", when: 1879, d: "A carbon filament burned for more than thirteen hours and the working day stopped ending at dusk." },
      { t: "The Ford Model T goes on sale", y: "1908", when: 1908, d: "A car built for farmers and priced for them, and fifteen million were made." },
      { t: "The transistor is invented", y: "1947", when: 1947, d: "Three men at Bell Labs built a switch with no moving parts, and electronics shrank." },
      { t: "The first mobile phone call is made", y: "1973", when: 1973, d: "An engineer stood on a New York pavement and rang his rival at the competing lab." },
    ],
    note: "Five moments spanning 1876 to 1973, and the order is the whole puzzle.",
  },
  {
    num: 44,
    quizId: 'dating-8-26-26',
    live: '2026-08-26',
    dateLabel: 'August 26, 2026',
    theme: "Rights, charters and revolutions",
    events: [
      { t: "Luther posts the Ninety-five Theses", y: "1517", when: 1517, d: "Objections to indulgences split Western Christianity within a single generation." },
      { t: "The Bastille is stormed", y: "1789", when: 1789, d: "Parisians took the fortress and its gunpowder, and the day came to stand for the revolution." },
      { t: "The Universal Declaration of Human Rights is adopted", y: "1948", when: 1948, d: "Fifty-eight nations agreed a list of rights that belonged to everyone, everywhere." },
      { t: "Martin Luther King speaks of his dream", y: "1963", when: 1963, d: "He spoke from the Lincoln Memorial to a quarter of a million people." },
      { t: "The Berlin Wall comes down", y: "1989", when: 1989, d: "East Germany opened the border and Berliners attacked the concrete with hammers." },
    ],
    note: "Five moments spanning 1517 to 1989, and the order is the whole puzzle.",
  },
  {
    num: 45,
    quizId: 'dating-8-27-26',
    live: '2026-08-27',
    dateLabel: 'August 27, 2026',
    theme: "Disasters, in order",
    events: [
      { t: "Krakatoa erupts and is heard three thousand miles away", y: "1883", when: 1883, d: "The blast destroyed most of the island and lowered global temperatures for a year." },
      { t: "The Johnstown flood follows a dam failure", y: "1889", when: 1889, d: "A neglected earth dam gave way and a wall of water took more than two thousand lives." },
      { t: "An earthquake and fire level San Francisco", y: "1906", when: 1906, d: "A magnitude 7.9 shock and three days of fire destroyed most of the city." },
      { t: "The Hindenburg burns at Lakehurst", y: "1937", when: 1937, d: "The airship caught fire while mooring, and passenger airship travel ended with it." },
      { t: "Mount St Helens erupts", y: "1980", when: 1980, d: "The north face slid away in the largest landslide ever recorded and the summit lost 400 metres." },
    ],
    note: "Five moments spanning 1883 to 1980, and the order is the whole puzzle.",
  },
  {
    num: 46,
    quizId: 'dating-8-28-26',
    live: '2026-08-28',
    dateLabel: 'August 28, 2026',
    theme: "The ancient world, in sequence",
    events: [
      { t: "Rome is founded, by tradition", y: "753 BC", when: -753, d: "The traditional date for a settlement on the Palatine that grew into an empire." },
      { t: "Julius Caesar is assassinated", y: "44 BC", when: -44, d: "Senators struck him down in the portico of Pompey's theatre on the Ides of March." },
      { t: "Vesuvius buries Pompeii", y: "79", when: 79, d: "Ash and pyroclastic flow sealed two towns and preserved them for seventeen centuries." },
      { t: "Constantinople becomes the capital of the empire", y: "330", when: 330, d: "Constantine refounded a Greek town as a new Rome that lasted eleven centuries." },
      { t: "The core module of the Mir space station is launched", y: "1986", when: 1986, d: "The first module of the Soviet station went up, and people lived aboard for fifteen years." },
    ],
    note: "Five moments spanning 753 BC to 1986, and the order is the whole puzzle.",
  },
  {
    num: 47,
    quizId: 'dating-8-29-26',
    live: '2026-08-29',
    dateLabel: 'August 29, 2026',
    theme: "Culture and sport, in order",
    events: [
      { t: "Shakespeare's Globe Theatre opens", y: "1599", when: 1599, d: "A playhouse built from the timbers of an older theatre, carried across the river by night." },
      { t: "The first modern Olympic Games are held", y: "1896", when: 1896, d: "Fourteen nations competed in a marble stadium rebuilt for the occasion." },
      { t: "Picasso paints Les Demoiselles d'Avignon", y: "1907", when: 1907, d: "Five figures broken into planes, and the picture sat in his studio for years before it was shown." },
      { t: "The first feature film with synchronised speech opens", y: "1927", when: 1927, d: "Audiences heard an actor speak from the screen and silent cinema was finished within three years." },
      { t: "The first FIFA World Cup is won", y: "1930", when: 1930, d: "Uruguay beat Argentina four goals to two in a stadium built for the tournament." },
    ],
    note: "Five moments spanning 1599 to 1930, and the order is the whole puzzle.",
  },
  {
    num: 48,
    quizId: 'dating-8-30-26',
    live: '2026-08-30',
    dateLabel: 'August 30, 2026',
    sunday: true,
    theme: "A run through the centuries",
    events: [
      { t: "Magna Carta is sealed at Runnymede", y: "1215", when: 1215, d: "King John conceded that the crown was not above the law, and the idea outlived the peace." },
      { t: "Mendeleev arranges the periodic table", y: "1869", when: 1869, d: "He left gaps for elements nobody had found, and the gaps were filled within fifteen years." },
      { t: "Apollo 11 lands on the Moon", y: "1969", when: 1969, d: "Armstrong and Aldrin walked on the Sea of Tranquillity while 600 million people watched." },
      { t: "Apollo 13 limps home after an explosion", y: "1970", when: 1970, d: "An oxygen tank burst 200,000 miles out and the crew used the lunar module as a lifeboat." },
      { t: "The Vietnam War ends with the fall of Saigon", y: "1975", when: 1975, d: "Helicopters lifted the last evacuees from the embassy roof as tanks entered the city." },
      { t: "The Gulf War begins with an air campaign", y: "1991", when: 1991, d: "A coalition of thirty-five nations moved to reverse the occupation of Kuwait." },
    ],
    note: "Six moments spanning 1215 to 1991, and the order is the whole puzzle.",
  },
  {
    num: 49,
    quizId: 'dating-8-31-26',
    live: '2026-08-31',
    dateLabel: 'August 31, 2026',
    theme: "Voyages and first ascents",
    events: [
      { t: "Magellan's expedition sets out to circle the globe", y: "1519", when: 1519, d: "Five ships left Seville; one came home three years later with eighteen men aboard." },
      { t: "Cook sets out on his first Pacific voyage", y: "1768", when: 1768, d: "The Endeavour left Plymouth to observe a transit of Venus and kept going for three years." },
      { t: "Lewis and Clark reach the Pacific", y: "1805", when: 1805, d: "The Corps of Discovery crossed the continent and wintered by the mouth of the Columbia." },
      { t: "Amundsen reaches the South Pole", y: "1911", when: 1911, d: "His party arrived five weeks ahead of Scott and came home without losing a man." },
      { t: "Hillary and Tenzing reach the summit of Everest", y: "1953", when: 1953, d: "They stood on the top for fifteen minutes and were back at the South Col by nightfall." },
    ],
    note: "Five moments spanning 1519 to 1953, and the order is the whole puzzle.",
  },
  {
    num: 50,
    quizId: 'dating-9-1-26',
    live: '2026-09-01',
    dateLabel: 'September 1, 2026',
    theme: "Milestones across the record",
    events: [
      { t: "The Great Fire destroys much of London", y: "1666", when: 1666, d: "Four days of fire from Pudding Lane took thirteen thousand houses and old St Paul's." },
      { t: "The Vietnam War ends with the fall of Saigon", y: "1975", when: 1975, d: "Helicopters lifted the last evacuees from the embassy roof as tanks entered the city." },
      { t: "Berners-Lee proposes the World Wide Web", y: "1989", when: 1989, d: "A memo at CERN described hypertext over the internet, and his boss called it vague but exciting." },
      { t: "Curiosity is lowered onto Mars by a sky crane", y: "2011", when: 2011, d: "A car-sized rover was lowered onto Mars by a sky crane and found an old streambed." },
      { t: "The Higgs boson is discovered", y: "2012", when: 2012, d: "Two CERN experiments found the particle predicted almost fifty years earlier." },
    ],
    note: "Five moments spanning 1666 to 2012, and the order is the whole puzzle.",
  },
  {
    num: 51,
    quizId: 'dating-9-2-26',
    live: '2026-09-02',
    dateLabel: 'September 2, 2026',
    theme: "The space age, in order",
    events: [
      { t: "Apollo 8 carries the first people around the Moon", y: "1968", when: 1968, d: "Three men read from Genesis on Christmas Eve and photographed the Earth rising over the limb." },
      { t: "Apollo 11 lands on the Moon", y: "1969", when: 1969, d: "Armstrong and Aldrin walked on the Sea of Tranquillity while 600 million people watched." },
      { t: "Viking 1 sends the first pictures from the surface of Mars", y: "1976", when: 1976, d: "The lander touched down on Chryse Planitia and returned a photograph of its own footpad." },
      { t: "The first Space Shuttle reaches orbit", y: "1981", when: 1981, d: "Columbia flew with two men aboard on its maiden flight, a first for any spacecraft." },
      { t: "The first module of the International Space Station is launched", y: "1998", when: 1998, d: "A Russian module went up alone and the station was assembled around it over a decade." },
    ],
    note: "Five moments spanning 1968 to 1998, and the order is the whole puzzle.",
  },
  {
    num: 52,
    quizId: 'dating-9-3-26',
    live: '2026-09-03',
    dateLabel: 'September 3, 2026',
    theme: "Wars and the peace that followed",
    events: [
      { t: "The Battle of Hastings decides the English crown", y: "1066", when: 1066, d: "Harold fell and William of Normandy took a kingdom that changed language, law and landholding." },
      { t: "The Spanish Armada is scattered", y: "1588", when: 1588, d: "Fire ships broke the crescent off Calais and the weather finished what the guns began." },
      { t: "The Battle of Waterloo ends Napoleon's return", y: "1815", when: 1815, d: "Wellington and Blucher closed two decades of European war in a single muddy afternoon." },
      { t: "The American Civil War ends at Appomattox", y: "1865", when: 1865, d: "Lee surrendered the Army of Northern Virginia and four years of fighting stopped within weeks." },
      { t: "The Cuban Missile Crisis brings the superpowers to the brink", y: "1962", when: 1962, d: "Thirteen days of blockade and back-channel talks ended with the missiles withdrawn." },
    ],
    note: "Five moments spanning 1066 to 1962, and the order is the whole puzzle.",
  },
  {
    num: 53,
    quizId: 'dating-9-4-26',
    live: '2026-09-04',
    dateLabel: 'September 4, 2026',
    theme: "Science, one discovery at a time",
    events: [
      { t: "Galileo publishes what he saw through the telescope", y: "1610", when: 1610, d: "Galileo published what he had seen through the telescope, including four moons circling Jupiter." },
      { t: "Marie Curie isolates radium", y: "1898", when: 1898, d: "Years of processing pitchblende in a shed yielded a tenth of a gram of a new element." },
      { t: "Einstein publishes the theory of general relativity", y: "1915", when: 1915, d: "Gravity became the curvature of spacetime, and starlight was found to bend as predicted." },
      { t: "The Human Genome Project begins", y: "1990", when: 1990, d: "An international effort set out to read all three billion letters of human DNA." },
      { t: "The Higgs boson is discovered", y: "2012", when: 2012, d: "Two CERN experiments found the particle predicted almost fifty years earlier." },
    ],
    note: "Five moments spanning 1610 to 2012, and the order is the whole puzzle.",
  },
  {
    num: 54,
    quizId: 'dating-9-5-26',
    live: '2026-09-05',
    dateLabel: 'September 5, 2026',
    theme: "Machines that changed the day",
    events: [
      { t: "The first passenger railway opens", y: "1825", when: 1825, d: "Locomotion No. 1 hauled wagons of coal and passengers, and the railway age began." },
      { t: "The first adhesive postage stamp is issued", y: "1840", when: 1840, d: "The first adhesive postage stamp made a letter cost the same to anywhere in the country." },
      { t: "Bell makes the first telephone call", y: "1876", when: 1876, d: "He called his assistant in the next room, and the human voice travelled by wire." },
      { t: "The Ford Model T goes on sale", y: "1908", when: 1908, d: "A car built for farmers and priced for them, and fifteen million were made." },
      { t: "The first message is sent over ARPANET", y: "1969", when: 1969, d: "The system crashed after two letters, but the network that became the internet had spoken." },
    ],
    note: "Five moments spanning 1825 to 1969, and the order is the whole puzzle.",
  },
  {
    num: 55,
    quizId: 'dating-9-6-26',
    live: '2026-09-06',
    dateLabel: 'September 6, 2026',
    sunday: true,
    theme: "Moments that changed who decides",
    events: [
      { t: "Luther posts the Ninety-five Theses", y: "1517", when: 1517, d: "Objections to indulgences split Western Christianity within a single generation." },
      { t: "Britain abolishes the slave trade", y: "1807", when: 1807, d: "Twenty years of campaigning ended the trade in British ships, though slavery itself lasted longer." },
      { t: "India becomes independent", y: "1947", when: 1947, d: "Freedom came at midnight, and partition displaced perhaps fifteen million people." },
      { t: "Rosa Parks is arrested and the bus boycott begins", y: "1955", when: 1955, d: "Her arrest in Montgomery started a boycott that lasted more than a year." },
      { t: "The Berlin Wall comes down", y: "1989", when: 1989, d: "East Germany opened the border and Berliners attacked the concrete with hammers." },
      { t: "Hong Kong is handed back to China", y: "1997", when: 1997, d: "A midnight ceremony ended 156 years of British administration." },
    ],
    note: "Six moments spanning 1517 to 1997, and the order is the whole puzzle.",
  },
  {
    num: 56,
    quizId: 'dating-9-7-26',
    live: '2026-09-07',
    dateLabel: 'September 7, 2026',
    theme: "Days the ground moved",
    events: [
      { t: "An earthquake and fire level San Francisco", y: "1906", when: 1906, d: "A magnitude 7.9 shock and three days of fire destroyed most of the city." },
      { t: "The Titanic sinks on her maiden voyage", y: "1912", when: 1912, d: "The ship went down two hours and forty minutes after striking an iceberg." },
      { t: "The Hindenburg burns at Lakehurst", y: "1937", when: 1937, d: "The airship caught fire while mooring, and passenger airship travel ended with it." },
      { t: "The Chernobyl reactor explodes", y: "1986", when: 1986, d: "A botched safety test blew the roof off reactor four and contaminated a swathe of Europe." },
      { t: "A tsunami crosses the Indian Ocean", y: "2004", when: 2004, d: "A magnitude 9.1 rupture off Sumatra killed some 230,000 people in a dozen countries." },
    ],
    note: "Five moments spanning 1906 to 2004, and the order is the whole puzzle.",
  },
  {
    num: 57,
    quizId: 'dating-9-8-26',
    live: '2026-09-08',
    dateLabel: 'September 8, 2026',
    theme: "Before the Middle Ages",
    events: [
      { t: "Rome is founded, by tradition", y: "753 BC", when: -753, d: "The traditional date for a settlement on the Palatine that grew into an empire." },
      { t: "The Battle of Marathon halts a Persian invasion", y: "490 BC", when: -490, d: "Athenian hoplites broke a much larger force on the plain and the news ran to the city." },
      { t: "Alexander the Great dies at Babylon", y: "323 BC", when: -323, d: "He had conquered from Greece to the Indus and left no settled heir at thirty-two." },
      { t: "Vesuvius buries Pompeii", y: "79", when: 79, d: "Ash and pyroclastic flow sealed two towns and preserved them for seventeen centuries." },
      { t: "Constantinople becomes the capital of the empire", y: "330", when: 330, d: "Constantine refounded a Greek town as a new Rome that lasted eleven centuries." },
    ],
    note: "Five moments spanning 753 BC to 330, and the order is the whole puzzle.",
  },
  {
    num: 58,
    quizId: 'dating-9-9-26',
    live: '2026-09-09',
    dateLabel: 'September 9, 2026',
    theme: "Nights people still talk about",
    events: [
      { t: "Shakespeare's Globe Theatre opens", y: "1599", when: 1599, d: "A playhouse built from the timbers of an older theatre, carried across the river by night." },
      { t: "Handel's Messiah is first performed", y: "1742", when: 1742, d: "The premiere was in Dublin, for charity, and the hall asked ladies to come without hoops." },
      { t: "The first modern Olympic Games are held", y: "1896", when: 1896, d: "Fourteen nations competed in a marble stadium rebuilt for the occasion." },
      { t: "Picasso paints Les Demoiselles d'Avignon", y: "1907", when: 1907, d: "Five figures broken into planes, and the picture sat in his studio for years before it was shown." },
      { t: "Four hundred thousand gather at Woodstock", y: "1969", when: 1969, d: "Four hundred thousand people came to a dairy farm for three days of music and mud." },
    ],
    note: "Five moments spanning 1599 to 1969, and the order is the whole puzzle.",
  },
  {
    num: 59,
    quizId: 'dating-9-10-26',
    live: '2026-09-10',
    dateLabel: 'September 10, 2026',
    theme: "Milestones across the record",
    events: [
      { t: "The Black Death reaches Europe", y: "1347", when: 1347, d: "Galleys put in at Messina carrying a plague that killed perhaps a third of the continent." },
      { t: "Beethoven's Ninth Symphony is premiered", y: "1824", when: 1824, d: "The composer was too deaf to hear the applause and had to be turned to see it." },
      { t: "The First World War begins", y: "1914", when: 1914, d: "The assassination of an archduke pulled Europe's alliances into four years of trench warfare." },
      { t: "The first FIFA World Cup is won", y: "1930", when: 1930, d: "Uruguay beat Argentina four goals to two in a stadium built for the tournament." },
      { t: "Valentina Tereshkova becomes the first woman in space", y: "1963", when: 1963, d: "She flew 48 orbits solo, more time in space than every American astronaut to that date combined." },
    ],
    note: "Five moments spanning 1347 to 1963, and the order is the whole puzzle.",
  },
  {
    num: 60,
    quizId: 'dating-9-11-26',
    live: '2026-09-11',
    dateLabel: 'September 11, 2026',
    theme: "Setting out for the edge of the map",
    events: [
      { t: "A small Greek force holds the pass at Thermopylae", y: "480 BC", when: -480, d: "A Greek rearguard held the pass for three days before being outflanked by a mountain path." },
      { t: "Magellan's expedition sets out to circle the globe", y: "1519", when: 1519, d: "Five ships left Seville; one came home three years later with eighteen men aboard." },
      { t: "Lewis and Clark reach the Pacific", y: "1805", when: 1805, d: "The Corps of Discovery crossed the continent and wintered by the mouth of the Columbia." },
      { t: "Amundsen reaches the South Pole", y: "1911", when: 1911, d: "His party arrived five weeks ahead of Scott and came home without losing a man." },
      { t: "Hillary and Tenzing reach the summit of Everest", y: "1953", when: 1953, d: "They stood on the top for fifteen minutes and were back at the South Col by nightfall." },
    ],
    note: "Five moments spanning 480 BC to 1953, and the order is the whole puzzle.",
  },
  {
    num: 61,
    quizId: 'dating-9-12-26',
    live: '2026-09-12',
    dateLabel: 'September 12, 2026',
    theme: "Five turning points, oldest first",
    events: [
      { t: "The Domesday Book is completed", y: "1086", when: 1086, d: "A survey of England so thorough that contemporaries compared it to the Last Judgement." },
      { t: "An atomic bomb destroys Hiroshima", y: "1945", when: 1945, d: "One weapon flattened the city centre and Japan surrendered within nine days." },
      { t: "Yuri Gagarin becomes the first person in space", y: "1961", when: 1961, d: "One orbit of the Earth in 108 minutes made a 27-year-old pilot the most famous man alive." },
      { t: "The Hubble Space Telescope is placed in orbit", y: "1990", when: 1990, d: "Its mirror was flawed, and a shuttle crew fitted corrective optics three years later." },
      { t: "Gravitational waves are detected for the first time", y: "2015", when: 2015, d: "Two black holes merged a billion years ago and shook the detectors for a fifth of a second." },
    ],
    note: "Five moments spanning 1086 to 2015, and the order is the whole puzzle.",
  },
  {
    num: 62,
    quizId: 'dating-9-13-26',
    live: '2026-09-13',
    dateLabel: 'September 13, 2026',
    sunday: true,
    theme: "Out past the atmosphere",
    events: [
      { t: "Sputnik 1 becomes the first satellite in orbit", y: "1957", when: 1957, d: "A polished metal sphere the size of a beach ball began the space age and alarmed Washington." },
      { t: "Apollo 13 limps home after an explosion", y: "1970", when: 1970, d: "An oxygen tank burst 200,000 miles out and the crew used the lunar module as a lifeboat." },
      { t: "Voyager 1 launches on a tour of the outer planets", y: "1977", when: 1977, d: "It is now the most distant human object, still returning data from interstellar space." },
      { t: "The Challenger breaks apart after launch", y: "1986", when: 1986, d: "A failed booster seal in freezing weather destroyed the orbiter and its crew of seven." },
      { t: "Cassini launches for Saturn", y: "1997", when: 1997, d: "It took seven years to arrive and spent thirteen more circling the planet and its moons." },
      { t: "New Horizons launches on a nine-year flight to Pluto", y: "2006", when: 2006, d: "The fastest spacecraft ever launched still needed nine years to reach the outer solar system." },
    ],
    note: "Six moments spanning 1957 to 2006, and the order is the whole puzzle.",
  },
  {
    num: 63,
    quizId: 'dating-9-14-26',
    live: '2026-09-14',
    dateLabel: 'September 14, 2026',
    theme: "Battles that redrew a map",
    events: [
      { t: "Constantinople falls to Ottoman cannon", y: "1453", when: 1453, d: "The Theodosian walls were breached after fifty-three days and the Byzantine empire ended." },
      { t: "The Armistice silences the guns", y: "1918", when: 1918, d: "The fighting stopped at the eleventh hour, with an estimated seventeen million dead." },
      { t: "The Second World War begins in Europe", y: "1939", when: 1939, d: "Germany invaded Poland and Britain and France declared war two days later." },
      { t: "Allied troops land in Normandy", y: "1944", when: 1944, d: "Some 156,000 men crossed the Channel in the largest seaborne invasion ever attempted." },
      { t: "The Gulf War begins with an air campaign", y: "1991", when: 1991, d: "A coalition of thirty-five nations moved to reverse the occupation of Kuwait." },
    ],
    note: "Five moments spanning 1453 to 1991, and the order is the whole puzzle.",
  },
  {
    num: 64,
    quizId: 'dating-9-15-26',
    live: '2026-09-15',
    dateLabel: 'September 15, 2026',
    theme: "How we worked it out",
    events: [
      { t: "Copernicus places the Sun at the centre", y: "1543", when: 1543, d: "He received the printed book on his deathbed, and the Earth stopped being the centre of things." },
      { t: "Newton publishes the Principia", y: "1687", when: 1687, d: "Three laws of motion and one of gravitation explained both the tides and the planets." },
      { t: "Darwin publishes On the Origin of Species", y: "1859", when: 1859, d: "The first printing sold out in a day and recast biology around descent with modification." },
      { t: "Mendeleev arranges the periodic table", y: "1869", when: 1869, d: "He left gaps for elements nobody had found, and the gaps were filled within fifteen years." },
      { t: "Fleming notices a mould that kills bacteria", y: "1928", when: 1928, d: "A contaminated dish cleared itself of staphylococcus and the antibiotic age followed." },
    ],
    note: "Five moments spanning 1543 to 1928, and the order is the whole puzzle.",
  },
  {
    num: 65,
    quizId: 'dating-9-16-26',
    live: '2026-09-16',
    dateLabel: 'September 16, 2026',
    theme: "Inventions, oldest first",
    events: [
      { t: "Gutenberg begins printing with movable type", y: "1450", when: 1450, d: "Movable metal type made books cheap enough to outrun any authority trying to chase them." },
      { t: "The first adhesive postage stamp is issued", y: "1840", when: 1840, d: "The first adhesive postage stamp made a letter cost the same to anywhere in the country." },
      { t: "Edison demonstrates a practical electric light", y: "1879", when: 1879, d: "A carbon filament burned for more than thirteen hours and the working day stopped ending at dusk." },
      { t: "The transistor is invented", y: "1947", when: 1947, d: "Three men at Bell Labs built a switch with no moving parts, and electronics shrank." },
      { t: "The first iPhone is unveiled", y: "2007", when: 2007, d: "A phone that was all screen, and the pocket computer arrived." },
    ],
    note: "Five moments spanning 1450 to 2007, and the order is the whole puzzle.",
  },
  {
    num: 66,
    quizId: 'dating-9-17-26',
    live: '2026-09-17',
    dateLabel: 'September 17, 2026',
    theme: "Rights, charters and revolutions",
    events: [
      { t: "Magna Carta is sealed at Runnymede", y: "1215", when: 1215, d: "King John conceded that the crown was not above the law, and the idea outlived the peace." },
      { t: "The Bastille is stormed", y: "1789", when: 1789, d: "Parisians took the fortress and its gunpowder, and the day came to stand for the revolution." },
      { t: "The Universal Declaration of Human Rights is adopted", y: "1948", when: 1948, d: "Fifty-eight nations agreed a list of rights that belonged to everyone, everywhere." },
      { t: "Martin Luther King speaks of his dream", y: "1963", when: 1963, d: "He spoke from the Lincoln Memorial to a quarter of a million people." },
      { t: "Mandela is elected president of South Africa", y: "1994", when: 1994, d: "Queues stretched for miles in the country's first election with universal suffrage." },
    ],
    note: "Five moments spanning 1215 to 1994, and the order is the whole puzzle.",
  },
  {
    num: 67,
    quizId: 'dating-9-18-26',
    live: '2026-09-18',
    dateLabel: 'September 18, 2026',
    theme: "Disasters, in order",
    events: [
      { t: "The Johnstown flood follows a dam failure", y: "1889", when: 1889, d: "A neglected earth dam gave way and a wall of water took more than two thousand lives." },
      { t: "An earthquake and fire level San Francisco", y: "1906", when: 1906, d: "A magnitude 7.9 shock and three days of fire destroyed most of the city." },
      { t: "The Hindenburg burns at Lakehurst", y: "1937", when: 1937, d: "The airship caught fire while mooring, and passenger airship travel ended with it." },
      { t: "Mount St Helens erupts", y: "1980", when: 1980, d: "The north face slid away in the largest landslide ever recorded and the summit lost 400 metres." },
      { t: "A tsunami crosses the Indian Ocean", y: "2004", when: 2004, d: "A magnitude 9.1 rupture off Sumatra killed some 230,000 people in a dozen countries." },
    ],
    note: "Five moments spanning 1889 to 2004, and the order is the whole puzzle.",
  },
  {
    num: 68,
    quizId: 'dating-9-19-26',
    live: '2026-09-19',
    dateLabel: 'September 19, 2026',
    theme: "The ancient world, in sequence",
    events: [
      { t: "The first Olympic Games are held at Olympia", y: "776 BC", when: -776, d: "A single foot race down the stadium, run by men from a scatter of Greek cities." },
      { t: "Julius Caesar is assassinated", y: "44 BC", when: -44, d: "Senators struck him down in the portico of Pompey's theatre on the Ides of March." },
      { t: "Hadrian's Wall is begun", y: "122", when: 122, d: "Eighty miles of stone and turf marked the northern edge of the Roman province." },
      { t: "Constantinople becomes the capital of the empire", y: "330", when: 330, d: "Constantine refounded a Greek town as a new Rome that lasted eleven centuries." },
      { t: "The Domesday Book is completed", y: "1086", when: 1086, d: "A survey of England so thorough that contemporaries compared it to the Last Judgement." },
    ],
    note: "Five moments spanning 776 BC to 1086, and the order is the whole puzzle.",
  },
  {
    num: 69,
    quizId: 'dating-9-20-26',
    live: '2026-09-20',
    dateLabel: 'September 20, 2026',
    sunday: true,
    theme: "Culture and sport, in order",
    events: [
      { t: "Shakespeare's Globe Theatre opens", y: "1599", when: 1599, d: "A playhouse built from the timbers of an older theatre, carried across the river by night." },
      { t: "Handel's Messiah is first performed", y: "1742", when: 1742, d: "The premiere was in Dublin, for charity, and the hall asked ladies to come without hoops." },
      { t: "Beethoven's Ninth Symphony is premiered", y: "1824", when: 1824, d: "The composer was too deaf to hear the applause and had to be turned to see it." },
      { t: "The first FIFA World Cup is won", y: "1930", when: 1930, d: "Uruguay beat Argentina four goals to two in a stadium built for the tournament." },
      { t: "Four hundred thousand gather at Woodstock", y: "1969", when: 1969, d: "Four hundred thousand people came to a dairy farm for three days of music and mud." },
      { t: "Live Aid raises money on two continents at once", y: "1985", when: 1985, d: "Sixteen hours of music from London and Philadelphia reached an audience of nearly two billion." },
    ],
    note: "Six moments spanning 1599 to 1985, and the order is the whole puzzle.",
  },
  {
    num: 70,
    quizId: 'dating-9-21-26',
    live: '2026-09-21',
    dateLabel: 'September 21, 2026',
    theme: "Five turning points, oldest first",
    events: [
      { t: "The American colonies declare independence", y: "1776", when: 1776, d: "Thirteen colonies adopted Jefferson's text and announced a separation from the British crown." },
      { t: "Jenner publishes his work on vaccination", y: "1798", when: 1798, d: "His inquiry into cowpox laid out the method that would eventually eradicate smallpox." },
      { t: "The Emancipation Proclamation takes effect", y: "1863", when: 1863, d: "Lincoln declared enslaved people in the rebelling states free, and the war changed purpose." },
      { t: "A rover finds evidence of ancient water on Mars", y: "2004", when: 2004, d: "Opportunity landed in a crater and found rocks that had formed in standing water." },
      { t: "Curiosity is lowered onto Mars by a sky crane", y: "2011", when: 2011, d: "A car-sized rover was lowered onto Mars by a sky crane and found an old streambed." },
    ],
    note: "Five moments spanning 1776 to 2011, and the order is the whole puzzle.",
  },
  {
    num: 71,
    quizId: 'dating-9-22-26',
    live: '2026-09-22',
    dateLabel: 'September 22, 2026',
    theme: "Voyages and first ascents",
    events: [
      { t: "A small Greek force holds the pass at Thermopylae", y: "480 BC", when: -480, d: "A Greek rearguard held the pass for three days before being outflanked by a mountain path." },
      { t: "Magellan's expedition sets out to circle the globe", y: "1519", when: 1519, d: "Five ships left Seville; one came home three years later with eighteen men aboard." },
      { t: "Cook sets out on his first Pacific voyage", y: "1768", when: 1768, d: "The Endeavour left Plymouth to observe a transit of Venus and kept going for three years." },
      { t: "Lewis and Clark reach the Pacific", y: "1805", when: 1805, d: "The Corps of Discovery crossed the continent and wintered by the mouth of the Columbia." },
      { t: "Amundsen reaches the South Pole", y: "1911", when: 1911, d: "His party arrived five weeks ahead of Scott and came home without losing a man." },
    ],
    note: "Five moments spanning 480 BC to 1911, and the order is the whole puzzle.",
  },
  {
    num: 72,
    quizId: 'dating-9-23-26',
    live: '2026-09-23',
    dateLabel: 'September 23, 2026',
    theme: "A run through the centuries",
    events: [
      { t: "Magna Carta is sealed at Runnymede", y: "1215", when: 1215, d: "King John conceded that the crown was not above the law, and the idea outlived the peace." },
      { t: "The American colonies declare independence", y: "1776", when: 1776, d: "Thirteen colonies adopted Jefferson's text and announced a separation from the British crown." },
      { t: "Berners-Lee proposes the World Wide Web", y: "1989", when: 1989, d: "A memo at CERN described hypertext over the internet, and his boss called it vague but exciting." },
      { t: "The Hubble Space Telescope is placed in orbit", y: "1990", when: 1990, d: "Its mirror was flawed, and a shuttle crew fitted corrective optics three years later." },
      { t: "The Higgs boson is discovered", y: "2012", when: 2012, d: "Two CERN experiments found the particle predicted almost fifty years earlier." },
    ],
    note: "Five moments spanning 1215 to 2012, and the order is the whole puzzle.",
  },
  {
    num: 73,
    quizId: 'dating-9-24-26',
    live: '2026-09-24',
    dateLabel: 'September 24, 2026',
    theme: "The space age, in order",
    events: [
      { t: "Sputnik 1 becomes the first satellite in orbit", y: "1957", when: 1957, d: "A polished metal sphere the size of a beach ball began the space age and alarmed Washington." },
      { t: "Voyager 1 launches on a tour of the outer planets", y: "1977", when: 1977, d: "It is now the most distant human object, still returning data from interstellar space." },
      { t: "The first Space Shuttle reaches orbit", y: "1981", when: 1981, d: "Columbia flew with two men aboard on its maiden flight, a first for any spacecraft." },
      { t: "The Challenger breaks apart after launch", y: "1986", when: 1986, d: "A failed booster seal in freezing weather destroyed the orbiter and its crew of seven." },
      { t: "The first module of the International Space Station is launched", y: "1998", when: 1998, d: "A Russian module went up alone and the station was assembled around it over a decade." },
    ],
    note: "Five moments spanning 1957 to 1998, and the order is the whole puzzle.",
  },
  {
    num: 74,
    quizId: 'dating-9-25-26',
    live: '2026-09-25',
    dateLabel: 'September 25, 2026',
    theme: "Wars and the peace that followed",
    events: [
      { t: "Constantinople falls to Ottoman cannon", y: "1453", when: 1453, d: "The Theodosian walls were breached after fifty-three days and the Byzantine empire ended." },
      { t: "The American Civil War ends at Appomattox", y: "1865", when: 1865, d: "Lee surrendered the Army of Northern Virginia and four years of fighting stopped within weeks." },
      { t: "The Armistice silences the guns", y: "1918", when: 1918, d: "The fighting stopped at the eleventh hour, with an estimated seventeen million dead." },
      { t: "Allied troops land in Normandy", y: "1944", when: 1944, d: "Some 156,000 men crossed the Channel in the largest seaborne invasion ever attempted." },
      { t: "The Cuban Missile Crisis brings the superpowers to the brink", y: "1962", when: 1962, d: "Thirteen days of blockade and back-channel talks ended with the missiles withdrawn." },
    ],
    note: "Five moments spanning 1453 to 1962, and the order is the whole puzzle.",
  },
  {
    num: 75,
    quizId: 'dating-9-26-26',
    live: '2026-09-26',
    dateLabel: 'September 26, 2026',
    theme: "Science, one discovery at a time",
    events: [
      { t: "Copernicus places the Sun at the centre", y: "1543", when: 1543, d: "He received the printed book on his deathbed, and the Earth stopped being the centre of things." },
      { t: "Galileo publishes what he saw through the telescope", y: "1610", when: 1610, d: "Galileo published what he had seen through the telescope, including four moons circling Jupiter." },
      { t: "Jenner publishes his work on vaccination", y: "1798", when: 1798, d: "His inquiry into cowpox laid out the method that would eventually eradicate smallpox." },
      { t: "Marie Curie isolates radium", y: "1898", when: 1898, d: "Years of processing pitchblende in a shed yielded a tenth of a gram of a new element." },
      { t: "Fleming notices a mould that kills bacteria", y: "1928", when: 1928, d: "A contaminated dish cleared itself of staphylococcus and the antibiotic age followed." },
    ],
    note: "Five moments spanning 1543 to 1928, and the order is the whole puzzle.",
  },
  {
    num: 76,
    quizId: 'dating-9-27-26',
    live: '2026-09-27',
    dateLabel: 'September 27, 2026',
    sunday: true,
    theme: "Machines that changed the day",
    events: [
      { t: "The first passenger railway opens", y: "1825", when: 1825, d: "Locomotion No. 1 hauled wagons of coal and passengers, and the railway age began." },
      { t: "Edison demonstrates a practical electric light", y: "1879", when: 1879, d: "A carbon filament burned for more than thirteen hours and the working day stopped ending at dusk." },
      { t: "The Ford Model T goes on sale", y: "1908", when: 1908, d: "A car built for farmers and priced for them, and fifteen million were made." },
      { t: "The transistor is invented", y: "1947", when: 1947, d: "Three men at Bell Labs built a switch with no moving parts, and electronics shrank." },
      { t: "The first message is sent over ARPANET", y: "1969", when: 1969, d: "The system crashed after two letters, but the network that became the internet had spoken." },
      { t: "The first mobile phone call is made", y: "1973", when: 1973, d: "An engineer stood on a New York pavement and rang his rival at the competing lab." },
    ],
    note: "Six moments spanning 1825 to 1973, and the order is the whole puzzle.",
  },
  {
    num: 77,
    quizId: 'dating-9-28-26',
    live: '2026-09-28',
    dateLabel: 'September 28, 2026',
    theme: "Moments that changed who decides",
    events: [
      { t: "Luther posts the Ninety-five Theses", y: "1517", when: 1517, d: "Objections to indulgences split Western Christianity within a single generation." },
      { t: "Rosa Parks is arrested and the bus boycott begins", y: "1955", when: 1955, d: "Her arrest in Montgomery started a boycott that lasted more than a year." },
      { t: "Martin Luther King speaks of his dream", y: "1963", when: 1963, d: "He spoke from the Lincoln Memorial to a quarter of a million people." },
      { t: "Mandela is elected president of South Africa", y: "1994", when: 1994, d: "Queues stretched for miles in the country's first election with universal suffrage." },
      { t: "Hong Kong is handed back to China", y: "1997", when: 1997, d: "A midnight ceremony ended 156 years of British administration." },
    ],
    note: "Five moments spanning 1517 to 1997, and the order is the whole puzzle.",
  },
  {
    num: 78,
    quizId: 'dating-9-29-26',
    live: '2026-09-29',
    dateLabel: 'September 29, 2026',
    theme: "Days the ground moved",
    events: [
      { t: "The Black Death reaches Europe", y: "1347", when: 1347, d: "Galleys put in at Messina carrying a plague that killed perhaps a third of the continent." },
      { t: "The Great Fire destroys much of London", y: "1666", when: 1666, d: "Four days of fire from Pudding Lane took thirteen thousand houses and old St Paul's." },
      { t: "Krakatoa erupts and is heard three thousand miles away", y: "1883", when: 1883, d: "The blast destroyed most of the island and lowered global temperatures for a year." },
      { t: "The Titanic sinks on her maiden voyage", y: "1912", when: 1912, d: "The ship went down two hours and forty minutes after striking an iceberg." },
      { t: "The Chernobyl reactor explodes", y: "1986", when: 1986, d: "A botched safety test blew the roof off reactor four and contaminated a swathe of Europe." },
    ],
    note: "Five moments spanning 1347 to 1986, and the order is the whole puzzle.",
  },
];
