// Shoe — the playout proofs behind every banked par and ace.
//
// Par and ace are not formulas. Par is basic strategy played blind on the
// day's shoe, and ace is the best of 600 blind runs — and these are the actual
// decision lines, one string of H / S / D per hand in the order the decisions
// were made (a hand settled by a natural has the empty string).
//
// This file exists so scripts/verify-shoe.mjs can replay both claims through
// the real rules engine (app/shoe/rules.js) rather than trusting a number in
// the bank. It is deliberately SEPARATE from puzzles.js and imported by
// nothing the browser loads, because the ace line is an excellent round on a
// live shoe and shipping it would hand today's players a solution.
export const PROOFS = {
  'shoe-8-21-26': { par: ["S","S","","H","H"], ace: ["S","D","","D","HS"] },
  'shoe-8-22-26': { par: ["H","S","HS","HH","S"], ace: ["H","S","S","D","S"] },
  'shoe-8-23-26': { par: ["S","HHS","HS","HS","D","HH","S"], ace: ["S","D","D","S","HHHS","D","S"] },
  'shoe-8-24-26': { par: ["S","HS","HS","S","S"], ace: ["S","HS","HS","S","D"] },
  'shoe-8-25-26': { par: ["HHS","S","S","S","S"], ace: ["HHS","S","D","D","D"] },
  'shoe-8-26-26': { par: ["S","HHS","HH","H","HH"], ace: ["S","HHH","D","S","D"] },
  'shoe-8-27-26': { par: ["S","HHH","D","S","D"], ace: ["S","HS","D","","S"] },
  'shoe-8-28-26': { par: ["S","HS","S","","S"], ace: ["S","HHS","S","","S"] },
  'shoe-8-29-26': { par: ["S","S","","","HS"], ace: ["D","S","","","D"] },
  'shoe-8-30-26': { par: ["HH","HH","S","D","S","S","S"], ace: ["D","S","H","S","S","D","S"] },
  'shoe-8-31-26': { par: ["H","S","HS","HH","S"], ace: ["S","HH","HS","D","S"] },
  'shoe-9-1-26': { par: ["S","HHS","S","S",""], ace: ["D","HHS","S","D","HS"] },
  'shoe-9-2-26': { par: ["S","S","S","S","S"], ace: ["D","S","S","HS","S"] },
  'shoe-9-3-26': { par: ["HH","HS","S","S","S"], ace: ["S","S","D","D","HS"] },
  'shoe-9-4-26': { par: ["S","S","HHS","H","S"], ace: ["S","S","S","D","D"] },
  'shoe-9-5-26': { par: ["HS","D","H","HS","HS"], ace: ["D","S","H","HS","HS"] },
  'shoe-9-6-26': { par: ["HS","S","S","D","D","S","H"], ace: ["HS","S","S","D","S","HS","H"] },
  'shoe-9-7-26': { par: ["D","HHHHS","HHS","HS","HH"], ace: ["D","HHHHS","HHH","S","S"] },
  'shoe-9-8-26': { par: ["S","S","HH","S","HS"], ace: ["S","S","D","HS","S"] },
  'shoe-9-9-26': { par: ["H","HH","D","HHH","D"], ace: ["D","S","D","HHH","D"] },
  'shoe-9-10-26': { par: ["S","S","HS","HH",""], ace: ["D","","HH","S",""] },
  'shoe-9-11-26': { par: ["S","","H","H","S"], ace: ["S","","S","S","D"] },
  'shoe-9-12-26': { par: ["HH","S","HHS","HH","S"], ace: ["S","","S","H","S"] },
  'shoe-9-13-26': { par: ["S","","S","HH","S","S","S"], ace: ["S","","S","D","S","S","S"] },
  'shoe-9-14-26': { par: ["HHS","H","S","S","HH"], ace: ["S","","D","","S"] },
  'shoe-9-15-26': { par: ["HHS","HS","S","S","HHS"], ace: ["HHS","D","S","S","D"] },
  'shoe-9-16-26': { par: ["HS","HHH","S","HS","S"], ace: ["S","S","D","S","S"] },
  'shoe-9-17-26': { par: ["S","S","HH","S","S"], ace: ["D","HHS","S","HH","D"] },
  'shoe-9-18-26': { par: ["HS","S","HHS","S","S"], ace: ["HS","HS","D","H","D"] },
  'shoe-9-19-26': { par: ["S","S","S","S","HHS"], ace: ["S","S","S","HH","D"] },
  'shoe-9-20-26': { par: ["HS","D","HS","HS","S","S","S"], ace: ["D","D","HS","HS","S","H","S"] },
  'shoe-9-21-26': { par: ["","HS","","S","S"], ace: ["","HH","S","D","S"] },
  'shoe-9-22-26': { par: ["S","D","","H","HS"], ace: ["S","D","","S","S"] },
  'shoe-9-23-26': { par: ["S","S","S","S","HH"], ace: ["S","S","D","HHS","D"] },
  'shoe-9-24-26': { par: ["S","HHH","D","S","HS"], ace: ["S","D","HS","S","HS"] },
  'shoe-9-25-26': { par: ["S","S","S","HS","D"], ace: ["HS","S","D","D","H"] },
  'shoe-9-26-26': { par: ["HH","D","HS","HHS","H"], ace: ["HH","D","HS","D","S"] },
  'shoe-9-27-26': { par: ["HHH","S","HS","H","S","HH","S"], ace: ["S","","D","H","HS","HHS","D"] },
  'shoe-9-28-26': { par: ["HHS","S","S","S","HS"], ace: ["D","HS","HS","S",""] },
  'shoe-9-29-26': { par: ["HH","HH","S","HS","S"], ace: ["HH","HH","D","H","HS"] },
  'shoe-9-30-26': { par: ["","S","S","","S"], ace: ["","S","D","","HS"] },
  'shoe-10-1-26': { par: ["H","S","H","HH","S"], ace: ["H","S","S","D","S"] },
  'shoe-10-2-26': { par: ["S","","S","HS","H"], ace: ["S","","D","S","S"] },
  'shoe-10-3-26': { par: ["HS","S","HH","HH","H"], ace: ["D","D","","D","H"] },
  'shoe-10-4-26': { par: ["D","S","HH","S","S","S","S"], ace: ["D","S","HH","S","S","D","D"] },
  'shoe-10-5-26': { par: ["HS","S","HS","S","S"], ace: ["HS","S","HS","D","D"] },
  'shoe-10-6-26': { par: ["H","HS","S","S","S"], ace: ["S","HS","S","D","HH"] },
  'shoe-10-7-26': { par: ["D","S","HS","S","HHHHH"], ace: ["S","S","HS","S","HHHHH"] },
  'shoe-10-8-26': { par: ["S","","S","HS","HH"], ace: ["S","","D","S",""] },
  'shoe-10-9-26': { par: ["HS","D","S","HHS","S"], ace: ["D","D","D","S","S"] },
  'shoe-10-10-26': { par: ["HS","D","D","H","S"], ace: ["D","D","D","S","S"] },
  'shoe-10-11-26': { par: ["S","HHS","S","S","S","S","HS"], ace: ["S","HHS","S","S","S","D","HS"] },
  'shoe-10-12-26': { par: ["","HS","H","HS","S"], ace: ["","HS","S","HHS","D"] },
  'shoe-10-13-26': { par: ["S","S","H","S","H"], ace: ["D","D","","HS","H"] },
  'shoe-10-14-26': { par: ["H","S","S","HS","S"], ace: ["S","HS","HHS","S","H"] },
  'shoe-10-15-26': { par: ["H","D","HH","S","H"], ace: ["H","HH","HH","S","S"] },
  'shoe-10-16-26': { par: ["HS","S","HHH","S","S"], ace: ["HS","S","HHH","D","D"] },
  'shoe-10-17-26': { par: ["HS","S","HS","S","HS"], ace: ["HHS","S","HS","D","HS"] },
  'shoe-10-18-26': { par: ["S","S","D","D","D","HS",""], ace: ["S","D","HS","D","S","S",""] },
  'shoe-10-19-26': { par: ["S","HS","HHS","H","S"], ace: ["D","D","HH","D","S"] },
  'shoe-10-20-26': { par: ["HS","S","H","S",""], ace: ["S","HS","D","S",""] },
  'shoe-10-21-26': { par: ["HS","S","S","S","S"], ace: ["HS","H","HH","HS","HHS"] },
  'shoe-10-22-26': { par: ["H","S","HS","S","S"], ace: ["H","S","HS","D","D"] },
  'shoe-10-23-26': { par: ["HH","S","HHH","HH","D"], ace: ["HH","S","D","HS","D"] },
  'shoe-10-24-26': { par: ["H","HHHS","HS","S","HH"], ace: ["S","HHHS","HS","S","D"] },
  'shoe-10-25-26': { par: ["HH","S","HHS","HHS","","S","H"], ace: ["HH","S","HS","D","HS","","S"] },
  'shoe-10-26-26': { par: ["H","S","H","HH","HS"], ace: ["H","D","HHS","S","S"] },
  'shoe-10-27-26': { par: ["","S","S","H","HS"], ace: ["","D","S","D","H"] },
  'shoe-10-28-26': { par: ["S","H","S","HS","S"], ace: ["HHS","S","D","D","S"] },
  'shoe-10-29-26': { par: ["H","HHH","S","HH","H"], ace: ["S","S","S","S","D"] },
  'shoe-10-30-26': { par: ["S","D","S","H","HS"], ace: ["S","D","D","S","HH"] },
  'shoe-10-31-26': { par: ["S","S","HS","H","HS"], ace: ["S","S","HHS","HH",""] },
  'shoe-11-1-26': { par: ["S","S","S","D","","HS","S"], ace: ["S","D","HS","S","","S","D"] },
  'shoe-11-2-26': { par: ["","S","S","S","H"], ace: ["","S","D","D","HH"] },
  'shoe-11-3-26': { par: ["S","HS","HS","H","HH"], ace: ["D","S","S","D","S"] },
  'shoe-11-4-26': { par: ["S","S","HHH","S","S"], ace: ["D","HS","","H","D"] },
  'shoe-11-5-26': { par: ["S","S","HHS","HS","HHS"], ace: ["D","HS","HS","S","D"] },
  'shoe-11-6-26': { par: ["S","HH","S","S","S"], ace: ["S","HS","D","S","S"] },
  'shoe-11-7-26': { par: ["S","S","H","S","HS"], ace: ["HS","D","HHS","","D"] },
  'shoe-11-8-26': { par: ["S","S","H","D","H","","S"], ace: ["S","S","S","S","D","","S"] },
  'shoe-11-9-26': { par: ["S","S","D","HS","H"], ace: ["S","S","S","HS","S"] },
  'shoe-11-10-26': { par: ["S","S","S","HH","HHS"], ace: ["S","D","HS","HS","D"] },
  'shoe-11-11-26': { par: ["HS","HHS","HS","HS",""], ace: ["HHS","HH","S","HS","S"] },
  'shoe-11-12-26': { par: ["HS","H","HS","HS","H"], ace: ["HS","H","S","S","S"] },
  'shoe-11-13-26': { par: ["S","D","HS","HHHH","S"], ace: ["S","D","HH","S","S"] },
  'shoe-11-14-26': { par: ["S","H","S","D",""], ace: ["S","H","HS","D",""] },
  'shoe-11-15-26': { par: ["HHS","S","HHS","H","S","D","D"], ace: ["HHS","D","S","H","S","S","D"] },
  'shoe-11-16-26': { par: ["S","H","S","HH","S"], ace: ["S","S","HH","S","D"] },
  'shoe-11-17-26': { par: ["H","S","S","S","S"], ace: ["D","S","S","S","D"] },
  'shoe-11-18-26': { par: ["D","HS","H","","D"], ace: ["D","HS","S","D","D"] },
  'shoe-11-19-26': { par: ["H","H","HS","S","S"], ace: ["H","H","D","S","HS"] },
};
