// Puzzle data for Sworn, the daily liars puzzle. Imported ONLY by the
// server page (app/sworn/page.js), which filters live<=today AND strips the
// solution before passing cases to the client — the client re-derives the
// unique (thief, liar-set) world from the testimony with its own brute-force
// solver, so the answer never ships over the wire.
//
// Every case was generated (seeded world -> one true-to-world statement per
// suspect -> uniqueness + §7a deducibility filters: parity propagation per
// candidate thief with a human-small case fan-out, NO search) and then
// independently re-verified. Weekdays seat 5 suspects; Sundays seat 6 for
// the Grand Inquest. Validate with scripts/verify-sworn.mjs after ANY edit.
//
// Statement schema (x = suspect index; speaker is the array position):
//   accuse {x}      "X is the thief."
//   innocent {x}    "X is innocent."
//   selfInnocent    "I am not the thief."
//   liar {x}        "X is lying."
//   honest {x}      "X is telling the truth."
//   thiefLiar       "The thief is lying."
//   thiefHonest     "The thief is telling the truth."
export const PUZZLES = [
  {
    num: 1, quizId: "sworn-7-18-26", live: "2026-07-18", dateLabel: "July 18, 2026", sunday: false,
    k: 2,
    suspects: ["Simon","Monty","Flora","Gideon","Rufus"],
    venue: "the Gilded Rooster tavern",
    stolen: "a purse of guineas",
    statements: [
      {"type":"innocent","x":4},
      {"type":"honest","x":3},
      {"type":"innocent","x":3},
      {"type":"accuse","x":4},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":1,"liars":[1,3]},
  },
  {
    num: 2, quizId: "sworn-7-19-26", live: "2026-07-19", dateLabel: "July 19, 2026", sunday: true,
    k: 3,
    suspects: ["Winnie","Lottie","Vera","Hazel","Felix","Monty"],
    venue: "the Saltmarsh docks",
    stolen: "a crate of silk",
    statements: [
      {"type":"accuse","x":3},
      {"type":"liar","x":5},
      {"type":"innocent","x":0},
      {"type":"liar","x":5},
      {"type":"honest","x":2},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":1,"liars":[0,1,3]},
  },
  {
    num: 3, quizId: "sworn-7-20-26", live: "2026-07-20", dateLabel: "July 20, 2026", sunday: false,
    k: 2,
    suspects: ["Monty","Pearl","Bruno","Barnaby","Ezra"],
    venue: "Fenwick's bakery",
    stolen: "the prize sourdough starter",
    statements: [
      {"type":"innocent","x":3},
      {"type":"innocent","x":2},
      {"type":"honest","x":1},
      {"type":"honest","x":2},
      {"type":"liar","x":1},
    ],
    solution: {"thief":3,"liars":[0,4]},
  },
  {
    num: 4, quizId: "sworn-7-21-26", live: "2026-07-21", dateLabel: "July 21, 2026", sunday: false,
    k: 3,
    suspects: ["Flora","Nell","Edmund","Percy","Jasper"],
    venue: "the Old Mill counting-house",
    stolen: "the week's wages",
    statements: [
      {"type":"innocent","x":2},
      {"type":"thiefHonest"},
      {"type":"honest","x":3},
      {"type":"accuse","x":0},
      {"type":"liar","x":0},
    ],
    solution: {"thief":1,"liars":[2,3,4]},
  },
  {
    num: 5, quizId: "sworn-7-22-26", live: "2026-07-22", dateLabel: "July 22, 2026", sunday: false,
    k: 2,
    suspects: ["Flora","Gideon","Winnie","Nell","Simon"],
    venue: "the Harbor Light inn",
    stolen: "a captain's sextant",
    statements: [
      {"type":"liar","x":4},
      {"type":"honest","x":4},
      {"type":"thiefLiar"},
      {"type":"liar","x":1},
      {"type":"innocent","x":3},
    ],
    solution: {"thief":0,"liars":[0,3]},
  },
  {
    num: 6, quizId: "sworn-7-23-26", live: "2026-07-23", dateLabel: "July 23, 2026", sunday: false,
    k: 3,
    suspects: ["Gideon","Winnie","Ezra","Victor","Felix"],
    venue: "the Penny Farthing playhouse",
    stolen: "the leading lady's tiara",
    statements: [
      {"type":"honest","x":1},
      {"type":"thiefLiar"},
      {"type":"accuse","x":1},
      {"type":"accuse","x":1},
      {"type":"selfInnocent"},
    ],
    solution: {"thief":4,"liars":[2,3,4]},
  },
  {
    num: 7, quizId: "sworn-7-24-26", live: "2026-07-24", dateLabel: "July 24, 2026", sunday: false,
    k: 2,
    suspects: ["Opal","Mabel","Rufus","Hazel","Delia"],
    venue: "the Copperfield apothecary",
    stolen: "a jar of rare saffron",
    statements: [
      {"type":"accuse","x":2},
      {"type":"honest","x":3},
      {"type":"innocent","x":4},
      {"type":"innocent","x":0},
      {"type":"honest","x":1},
    ],
    solution: {"thief":4,"liars":[0,2]},
  },
  {
    num: 8, quizId: "sworn-7-25-26", live: "2026-07-25", dateLabel: "July 25, 2026", sunday: false,
    k: 3,
    suspects: ["Simon","Delia","Mabel","Hazel","Cyrus"],
    venue: "the Drover's Arms",
    stolen: "a champion racing pigeon",
    statements: [
      {"type":"thiefLiar"},
      {"type":"liar","x":2},
      {"type":"liar","x":4},
      {"type":"innocent","x":2},
      {"type":"liar","x":2},
    ],
    solution: {"thief":3,"liars":[0,1,4]},
  },
  {
    num: 9, quizId: "sworn-7-26-26", live: "2026-07-26", dateLabel: "July 26, 2026", sunday: true,
    k: 3,
    suspects: ["Ezra","Gideon","Opal","Jasper","Cyrus","Nell"],
    venue: "the Lantern Street pawnshop",
    stolen: "a silver pocket watch",
    statements: [
      {"type":"accuse","x":2},
      {"type":"innocent","x":0},
      {"type":"accuse","x":3},
      {"type":"honest","x":5},
      {"type":"thiefHonest"},
      {"type":"liar","x":2},
    ],
    solution: {"thief":4,"liars":[0,2,4]},
  },
  {
    num: 10, quizId: "sworn-7-27-26", live: "2026-07-27", dateLabel: "July 27, 2026", sunday: false,
    k: 3,
    suspects: ["Iris","Mabel","Rosa","Amos","Percy"],
    venue: "the Wheatsheaf granary",
    stolen: "the harvest ledger",
    statements: [
      {"type":"honest","x":4},
      {"type":"innocent","x":4},
      {"type":"innocent","x":4},
      {"type":"liar","x":0},
      {"type":"liar","x":1},
    ],
    solution: {"thief":4,"liars":[1,2,3]},
  },
  {
    num: 11, quizId: "sworn-7-28-26", live: "2026-07-28", dateLabel: "July 28, 2026", sunday: false,
    k: 2,
    suspects: ["Clara","Hazel","Otis","Rosa","Lottie"],
    venue: "the Bellfound foundry",
    stolen: "the chapel's hand bell",
    statements: [
      {"type":"honest","x":2},
      {"type":"innocent","x":0},
      {"type":"accuse","x":3},
      {"type":"innocent","x":1},
      {"type":"accuse","x":2},
    ],
    solution: {"thief":2,"liars":[0,2]},
  },
  {
    num: 12, quizId: "sworn-7-29-26", live: "2026-07-29", dateLabel: "July 29, 2026", sunday: false,
    k: 3,
    suspects: ["Sadie","Simon","Rufus","Bruno","Felix"],
    venue: "the Quayside fish market",
    stolen: "the day's takings",
    statements: [
      {"type":"honest","x":2},
      {"type":"liar","x":2},
      {"type":"innocent","x":1},
      {"type":"innocent","x":0},
      {"type":"liar","x":2},
    ],
    solution: {"thief":0,"liars":[1,3,4]},
  },
  {
    num: 13, quizId: "sworn-7-30-26", live: "2026-07-30", dateLabel: "July 30, 2026", sunday: false,
    k: 2,
    suspects: ["Nell","Vera","Winnie","Gideon","Mabel"],
    venue: "the Tinker's Row workshop",
    stolen: "a walnut music box",
    statements: [
      {"type":"accuse","x":2},
      {"type":"accuse","x":0},
      {"type":"innocent","x":4},
      {"type":"honest","x":4},
      {"type":"innocent","x":1},
    ],
    solution: {"thief":3,"liars":[0,1]},
  },
  {
    num: 14, quizId: "sworn-7-31-26", live: "2026-07-31", dateLabel: "July 31, 2026", sunday: false,
    k: 3,
    suspects: ["Tessa","Rosa","Lottie","Gideon","Nell"],
    venue: "the Hollybush coaching inn",
    stolen: "the mail satchel",
    statements: [
      {"type":"honest","x":3},
      {"type":"thiefHonest"},
      {"type":"honest","x":4},
      {"type":"accuse","x":0},
      {"type":"innocent","x":1},
    ],
    solution: {"thief":3,"liars":[0,1,3]},
  },
  {
    num: 15, quizId: "sworn-8-1-26", live: "2026-08-01", dateLabel: "August 1, 2026", sunday: false,
    k: 3,
    suspects: ["Mordecai","Prudence","Alastair","Cordelia","Thaddeus"],
    venue: "the Marigold coffee-house",
    stolen: "an ivory chess set",
    statements: [
      {"type":"selfInnocent"},
      {"type":"accuse","x":3},
      {"type":"honest","x":3},
      {"type":"liar","x":1},
      {"type":"innocent","x":3},
    ],
    solution: {"thief":3,"liars":[2,3,4]},
  },
  {
    num: 16, quizId: "sworn-8-2-26", live: "2026-08-02", dateLabel: "August 2, 2026", sunday: true,
    k: 4,
    suspects: ["Agatha","Barnaby","Cornelius","Delphine","Ephraim","Marguerite"],
    venue: "the Ashgrove printworks",
    stolen: "a jeweled snuffbox",
    statements: [
      {"type":"liar","x":1},
      {"type":"innocent","x":0},
      {"type":"selfInnocent"},
      {"type":"thiefHonest"},
      {"type":"innocent","x":3},
      {"type":"innocent","x":3},
    ],
    solution: {"thief":3,"liars":[0,3,4,5]},
  },
  {
    num: 17, quizId: "sworn-8-3-26", live: "2026-08-03", dateLabel: "August 3, 2026", sunday: false,
    k: 3,
    suspects: ["Ignatius","Bellamy","Constance","Percival","Ottoline"],
    venue: "the Candlewick chandlery",
    stolen: "the guild's brass seal",
    statements: [
      {"type":"liar","x":4},
      {"type":"accuse","x":3},
      {"type":"innocent","x":4},
      {"type":"innocent","x":2},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":2,"liars":[1,3,4]},
  },
  {
    num: 18, quizId: "sworn-8-4-26", live: "2026-08-04", dateLabel: "August 4, 2026", sunday: false,
    k: 2,
    suspects: ["Alaric","Cressida","Dorian","Isolde","Roland"],
    venue: "the Peppercorn spice-house",
    stolen: "a brass astrolabe",
    statements: [
      {"type":"honest","x":2},
      {"type":"honest","x":4},
      {"type":"liar","x":4},
      {"type":"honest","x":4},
      {"type":"accuse","x":2},
    ],
    solution: {"thief":2,"liars":[0,2]},
  },
  {
    num: 19, quizId: "sworn-8-5-26", live: "2026-08-05", dateLabel: "August 5, 2026", sunday: false,
    k: 3,
    suspects: ["Matilda","Osric","Perpetua","Quentin","Sybil"],
    venue: "the Blackthorn brewery",
    stolen: "the vintner's tasting cup",
    statements: [
      {"type":"innocent","x":4},
      {"type":"liar","x":0},
      {"type":"liar","x":4},
      {"type":"liar","x":1},
      {"type":"honest","x":0},
    ],
    solution: {"thief":4,"liars":[0,3,4]},
  },
  {
    num: 20, quizId: "sworn-8-6-26", live: "2026-08-06", dateLabel: "August 6, 2026", sunday: false,
    k: 2,
    suspects: ["Casimir","Edwina","Fitzgerald","Griselda","Humphrey"],
    venue: "the Willowmere boathouse",
    stolen: "a bundle of beaver pelts",
    statements: [
      {"type":"liar","x":3},
      {"type":"innocent","x":0},
      {"type":"honest","x":1},
      {"type":"selfInnocent"},
      {"type":"innocent","x":2},
    ],
    solution: {"thief":2,"liars":[0,4]},
  },
  {
    num: 21, quizId: "sworn-8-7-26", live: "2026-08-07", dateLabel: "August 7, 2026", sunday: false,
    k: 3,
    suspects: ["Jerome","Katharine","Lucius","Millicent","Nathaniel"],
    venue: "the Sable and Crane haberdashery",
    stolen: "the mayor's signet ring",
    statements: [
      {"type":"liar","x":1},
      {"type":"honest","x":4},
      {"type":"innocent","x":1},
      {"type":"honest","x":1},
      {"type":"selfInnocent"},
    ],
    solution: {"thief":4,"liars":[1,3,4]},
  },
  {
    num: 22, quizId: "sworn-8-8-26", live: "2026-08-08", dateLabel: "August 8, 2026", sunday: false,
    k: 2,
    suspects: ["Octavia","Peregrine","Rosalind","Sebastian","Theodora"],
    venue: "the Greenhollow orchard",
    stolen: "a basket of heirloom apples",
    statements: [
      {"type":"thiefHonest"},
      {"type":"honest","x":4},
      {"type":"innocent","x":1},
      {"type":"thiefLiar"},
      {"type":"accuse","x":1},
    ],
    solution: {"thief":1,"liars":[2,3]},
  },
  {
    num: 23, quizId: "sworn-8-9-26", live: "2026-08-09", dateLabel: "August 9, 2026", sunday: true,
    k: 4,
    suspects: ["Ambrose","Beatrix","Cuthbert","Drusilla","Eldon","Fenwick"],
    venue: "the Ironmonger's yard",
    stolen: "a set of surgeon's blades",
    statements: [
      {"type":"selfInnocent"},
      {"type":"accuse","x":4},
      {"type":"accuse","x":4},
      {"type":"innocent","x":2},
      {"type":"thiefHonest"},
      {"type":"innocent","x":0},
    ],
    solution: {"thief":2,"liars":[1,2,3,4]},
  },
  {
    num: 24, quizId: "sworn-8-10-26", live: "2026-08-10", dateLabel: "August 10, 2026", sunday: false,
    k: 3,
    suspects: ["Godfrey","Henrietta","Isambard","Jocasta","Kingsley"],
    venue: "the Cloverdale creamery",
    stolen: "the dairy's copper churn",
    statements: [
      {"type":"innocent","x":2},
      {"type":"innocent","x":3},
      {"type":"innocent","x":3},
      {"type":"selfInnocent"},
      {"type":"liar","x":3},
    ],
    solution: {"thief":3,"liars":[1,2,3]},
  },
  {
    num: 25, quizId: "sworn-8-11-26", live: "2026-08-11", dateLabel: "August 11, 2026", sunday: false,
    k: 3,
    suspects: ["Percival","Sylvester","Quenby","Gulliver","Ignatius"],
    venue: "the Mercer Lane glassworks",
    stolen: "a bolt of Flanders lace",
    statements: [
      {"type":"selfInnocent"},
      {"type":"innocent","x":4},
      {"type":"honest","x":3},
      {"type":"thiefLiar"},
      {"type":"innocent","x":3},
    ],
    solution: {"thief":4,"liars":[1,2,3]},
  },
  {
    num: 26, quizId: "sworn-8-12-26", live: "2026-08-12", dateLabel: "August 12, 2026", sunday: false,
    k: 2,
    suspects: ["Winifred","Albertine","Clementine","Valentine","Peregrine"],
    venue: "the Rookery bathhouse",
    stolen: "the master key to the strongroom",
    statements: [
      {"type":"thiefHonest"},
      {"type":"accuse","x":0},
      {"type":"selfInnocent"},
      {"type":"honest","x":4},
      {"type":"accuse","x":2},
    ],
    solution: {"thief":0,"liars":[3,4]},
  },
  {
    num: 27, quizId: "sworn-8-13-26", live: "2026-08-13", dateLabel: "August 13, 2026", sunday: false,
    k: 3,
    suspects: ["Beatrix","Theodora","Tabitha","Percival","Ophelia"],
    venue: "the Thistledown tea rooms",
    stolen: "a case of surgical mirrors",
    statements: [
      {"type":"thiefLiar"},
      {"type":"selfInnocent"},
      {"type":"innocent","x":0},
      {"type":"liar","x":1},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":2,"liars":[0,3,4]},
  },
  {
    num: 28, quizId: "sworn-8-14-26", live: "2026-08-14", dateLabel: "August 14, 2026", sunday: false,
    k: 3,
    suspects: ["Quintus","Xanthe","Zillah","Ulric","Griselda"],
    venue: "the Kettlewick smithy",
    stolen: "the founder's inkstand",
    statements: [
      {"type":"honest","x":3},
      {"type":"selfInnocent"},
      {"type":"honest","x":4},
      {"type":"accuse","x":2},
      {"type":"innocent","x":0},
    ],
    solution: {"thief":1,"liars":[0,1,3]},
  },
  {
    num: 29, quizId: "sworn-8-15-26", live: "2026-08-15", dateLabel: "August 15, 2026", sunday: false,
    k: 2,
    suspects: ["Idris","Ophelia","Ezra","Tabitha","Octavia"],
    venue: "the Pargeter almshouse",
    stolen: "a tray of uncut garnets",
    statements: [
      {"type":"liar","x":2},
      {"type":"honest","x":4},
      {"type":"honest","x":3},
      {"type":"selfInnocent"},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":3,"liars":[2,3]},
  },
  {
    num: 30, quizId: "sworn-8-16-26", live: "2026-08-16", dateLabel: "August 16, 2026", sunday: true,
    k: 2,
    suspects: ["Kester","Horatio","Griselda","Norbert","Yvette","Idris"],
    venue: "the Verity Street bindery",
    stolen: "the lifeboat's brass bell",
    statements: [
      {"type":"accuse","x":3},
      {"type":"liar","x":3},
      {"type":"honest","x":4},
      {"type":"thiefHonest"},
      {"type":"thiefLiar"},
      {"type":"liar","x":4},
    ],
    solution: {"thief":3,"liars":[3,5]},
  },
  {
    num: 31, quizId: "sworn-8-17-26", live: "2026-08-17", dateLabel: "August 17, 2026", sunday: false,
    k: 2,
    suspects: ["Ursula","Quenby","Xanthe","Kester","Zillah"],
    venue: "the Saffron Hill dyehouse",
    stolen: "a crate of seed potatoes",
    statements: [
      {"type":"thiefLiar"},
      {"type":"selfInnocent"},
      {"type":"thiefHonest"},
      {"type":"honest","x":0},
      {"type":"honest","x":0},
    ],
    solution: {"thief":1,"liars":[1,2]},
  },
  {
    num: 32, quizId: "sworn-8-18-26", live: "2026-08-18", dateLabel: "August 18, 2026", sunday: false,
    k: 3,
    suspects: ["Josiah","Rosamund","Quintus","Millicent","Xanthe"],
    venue: "the Longspur riding school",
    stolen: "the tollkeeper's cashbox",
    statements: [
      {"type":"selfInnocent"},
      {"type":"thiefLiar"},
      {"type":"thiefLiar"},
      {"type":"thiefHonest"},
      {"type":"liar","x":2},
    ],
    solution: {"thief":0,"liars":[0,3,4]},
  },
  {
    num: 33, quizId: "sworn-8-19-26", live: "2026-08-19", dateLabel: "August 19, 2026", sunday: false,
    k: 3,
    suspects: ["Kester","Rowena","Drusilla","Horatio","Mortimer"],
    venue: "the Crowder Alley clockmakers",
    stolen: "a folio of engraved maps",
    statements: [
      {"type":"thiefLiar"},
      {"type":"liar","x":0},
      {"type":"thiefHonest"},
      {"type":"honest","x":4},
      {"type":"innocent","x":1},
    ],
    solution: {"thief":1,"liars":[0,3,4]},
  },
  {
    num: 34, quizId: "sworn-8-20-26", live: "2026-08-20", dateLabel: "August 20, 2026", sunday: false,
    k: 2,
    suspects: ["Ezra","Lavinia","Beatrix","Peregrine","Ambrose"],
    venue: "the Barleycorn malthouse",
    stolen: "the parish christening cup",
    statements: [
      {"type":"selfInnocent"},
      {"type":"honest","x":3},
      {"type":"accuse","x":3},
      {"type":"accuse","x":2},
      {"type":"thiefHonest"},
    ],
    solution: {"thief":2,"liars":[2,4]},
  },
  {
    num: 35, quizId: "sworn-8-21-26", live: "2026-08-21", dateLabel: "August 21, 2026", sunday: false,
    k: 3,
    suspects: ["Xanthe","Albertine","Zebedee","Ferdinand","Yvette"],
    venue: "the Fossgate ropewalk",
    stolen: "a set of tuning forks",
    statements: [
      {"type":"liar","x":1},
      {"type":"thiefHonest"},
      {"type":"innocent","x":0},
      {"type":"selfInnocent"},
      {"type":"accuse","x":2},
    ],
    solution: {"thief":3,"liars":[1,3,4]},
  },
  {
    num: 36, quizId: "sworn-8-22-26", live: "2026-08-22", dateLabel: "August 22, 2026", sunday: false,
    k: 2,
    suspects: ["Ignatius","Millicent","Eulalia","Tabitha","Drusilla"],
    venue: "the Nettlebed toll house",
    stolen: "the auctioneer's gavel",
    statements: [
      {"type":"honest","x":3},
      {"type":"thiefHonest"},
      {"type":"liar","x":4},
      {"type":"honest","x":2},
      {"type":"innocent","x":1},
    ],
    solution: {"thief":1,"liars":[1,4]},
  },
  {
    num: 37, quizId: "sworn-8-23-26", live: "2026-08-23", dateLabel: "August 23, 2026", sunday: true,
    k: 3,
    suspects: ["Horatio","Zillah","Ambrose","Albertine","Cornelius","Desmond"],
    venue: "the Chandler Quay warehouse",
    stolen: "a tin of Ceylon tea",
    statements: [
      {"type":"thiefHonest"},
      {"type":"selfInnocent"},
      {"type":"thiefHonest"},
      {"type":"thiefHonest"},
      {"type":"selfInnocent"},
      {"type":"accuse","x":0},
    ],
    solution: {"thief":0,"liars":[0,2,3]},
  },
  {
    num: 38, quizId: "sworn-8-24-26", live: "2026-08-24", dateLabel: "August 24, 2026", sunday: false,
    k: 3,
    suspects: ["Peregrine","Mortimer","Rosamund","Theodora","Octavia"],
    venue: "the Havelock reading room",
    stolen: "the weighbridge ledger",
    statements: [
      {"type":"selfInnocent"},
      {"type":"innocent","x":4},
      {"type":"honest","x":0},
      {"type":"innocent","x":1},
      {"type":"honest","x":2},
    ],
    solution: {"thief":0,"liars":[0,2,4]},
  },
  {
    num: 39, quizId: "sworn-8-25-26", live: "2026-08-25", dateLabel: "August 25, 2026", sunday: false,
    k: 2,
    suspects: ["Kester","Octavia","Idris","Valentine","Percival"],
    venue: "the Sparrowgate mews",
    stolen: "a pair of duelling pistols",
    statements: [
      {"type":"selfInnocent"},
      {"type":"thiefLiar"},
      {"type":"liar","x":4},
      {"type":"thiefLiar"},
      {"type":"thiefHonest"},
    ],
    solution: {"thief":0,"liars":[0,4]},
  },
  {
    num: 40, quizId: "sworn-8-26-26", live: "2026-08-26", dateLabel: "August 26, 2026", sunday: false,
    k: 2,
    suspects: ["Katrina","Clementine","Idris","Millicent","Lavinia"],
    venue: "the Pipers Croft cider press",
    stolen: "the choirmaster's baton",
    statements: [
      {"type":"innocent","x":2},
      {"type":"accuse","x":0},
      {"type":"accuse","x":1},
      {"type":"thiefLiar"},
      {"type":"accuse","x":3},
    ],
    solution: {"thief":1,"liars":[1,4]},
  },
  {
    num: 41, quizId: "sworn-8-27-26", live: "2026-08-27", dateLabel: "August 27, 2026", sunday: false,
    k: 3,
    suspects: ["Ignatius","Mortimer","Eulalia","Quenby","Winifred"],
    venue: "the Dunwold assembly rooms",
    stolen: "a bundle of raw silk skeins",
    statements: [
      {"type":"selfInnocent"},
      {"type":"thiefHonest"},
      {"type":"thiefLiar"},
      {"type":"honest","x":4},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":1,"liars":[2,3,4]},
  },
  {
    num: 42, quizId: "sworn-8-28-26", live: "2026-08-28", dateLabel: "August 28, 2026", sunday: false,
    k: 3,
    suspects: ["Fenella","Beatrix","Percival","Rowena","Wilfred"],
    venue: "the Marlpit lime kiln",
    stolen: "the lighthouse logbook",
    statements: [
      {"type":"innocent","x":3},
      {"type":"innocent","x":3},
      {"type":"accuse","x":0},
      {"type":"accuse","x":4},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":1,"liars":[2,3,4]},
  },
  {
    num: 43, quizId: "sworn-8-29-26", live: "2026-08-29", dateLabel: "August 29, 2026", sunday: false,
    k: 3,
    suspects: ["Ulric","Zillah","Kester","Drusilla","Horatio"],
    venue: "the Ravensworth seed merchant",
    stolen: "a canister of indigo dye",
    statements: [
      {"type":"accuse","x":2},
      {"type":"liar","x":0},
      {"type":"innocent","x":1},
      {"type":"innocent","x":2},
      {"type":"liar","x":1},
    ],
    solution: {"thief":1,"liars":[0,2,4]},
  },
  {
    num: 44, quizId: "sworn-8-30-26", live: "2026-08-30", dateLabel: "August 30, 2026", sunday: true,
    k: 4,
    suspects: ["Nerissa","Cornelius","Verena","Wilfred","Quintus","Peregrine"],
    venue: "the Turnstile lending library",
    stolen: "the physician's pocket scales",
    statements: [
      {"type":"liar","x":3},
      {"type":"liar","x":0},
      {"type":"thiefLiar"},
      {"type":"liar","x":0},
      {"type":"selfInnocent"},
      {"type":"thiefLiar"},
    ],
    solution: {"thief":0,"liars":[1,2,3,5]},
  },
];
