// Puzzle data for Circa, the daily year hunt. Imported ONLY by the server
// page (app/circa/page.js), which filters live<=today before passing puzzles
// to the client — so future moments, and their years, never ship to the
// browser bundle.
//
// One historical moment per day. `title` is the event as shown on the board
// (present tense, no year clues in the wording); `year` is the exact answer,
// always between 1000 and the current year (no BC — the input stays a clean
// four digits). `d` is the end-screen story line (one short factual sentence,
// 15–110 chars), shown only after the game ends. Sundays (`sunday: true`) are
// the same mechanic with a trickier, more obscure moment to place. Never
// reuse a moment already banked here or in app/dating/puzzles.js.
export const PUZZLES = [
  {
    num: 1,
    quizId: 'circa-7-14-26',
    live: '2026-07-14',
    dateLabel: 'July 14, 2026',
    sunday: false,
    title: 'The Battle of Hastings is fought',
    year: 1066,
    d: 'William took England in a day; the Bayeux Tapestry tells the story in 230 feet of embroidery.',
  },
  {
    num: 2,
    quizId: 'circa-7-15-26',
    live: '2026-07-15',
    dateLabel: 'July 15, 2026',
    sunday: false,
    title: 'The Titanic sinks on its maiden voyage',
    year: 1912,
    d: 'The "unsinkable" liner went down in under three hours; the wreck was not found until 1985.',
  },
  {
    num: 3,
    quizId: 'circa-7-16-26',
    live: '2026-07-16',
    dateLabel: 'July 16, 2026',
    sunday: false,
    title: 'The Berlin Wall falls',
    year: 1989,
    d: 'A fumbled answer at a press conference opened the gates; crowds with hammers did the rest.',
  },
  {
    num: 4,
    quizId: 'circa-7-17-26',
    live: '2026-07-17',
    dateLabel: 'July 17, 2026',
    sunday: false,
    title: 'The Great Fire of London burns',
    year: 1666,
    d: 'It destroyed some 13,000 houses, yet the official death toll was just six.',
  },
  {
    num: 5,
    quizId: 'circa-7-18-26',
    live: '2026-07-18',
    dateLabel: 'July 18, 2026',
    sunday: false,
    title: 'The stock market crashes on Black Tuesday',
    year: 1929,
    d: 'The Dow needed 25 years to climb back to its 1929 peak.',
  },
  {
    num: 6,
    quizId: 'circa-7-19-26',
    live: '2026-07-19',
    dateLabel: 'July 19, 2026',
    sunday: true,
    title: 'The Black Death reaches England',
    year: 1348,
    d: 'Within two years the plague had killed at least a third of the country.',
  },
  {
    num: 7,
    quizId: 'circa-7-20-26',
    live: '2026-07-20',
    dateLabel: 'July 20, 2026',
    sunday: false,
    title: 'World War I begins',
    year: 1914,
    d: "A wrong turn put the archduke's car in front of his assassin; the war killed 17 million.",
  },
  {
    num: 8,
    quizId: 'circa-7-21-26',
    live: '2026-07-21',
    dateLabel: 'July 21, 2026',
    sunday: false,
    title: 'The Spanish Armada is defeated',
    year: 1588,
    d: 'English fireships and Atlantic storms wrecked the invasion; barely half the fleet limped home.',
  },
  {
    num: 9,
    quizId: 'circa-7-22-26',
    live: '2026-07-22',
    dateLabel: 'July 22, 2026',
    sunday: false,
    title: 'Pearl Harbor is attacked',
    year: 1941,
    d: 'The strike lasted about 90 minutes and pulled the United States into World War II.',
  },
  {
    num: 10,
    quizId: 'circa-7-23-26',
    live: '2026-07-23',
    dateLabel: 'July 23, 2026',
    sunday: false,
    title: "Gold is discovered at Sutter's Mill",
    year: 1848,
    d: 'The find was meant to stay secret; within two years San Francisco grew roughly 25-fold.',
  },
  {
    num: 11,
    quizId: 'circa-7-24-26',
    live: '2026-07-24',
    dateLabel: 'July 24, 2026',
    sunday: false,
    title: 'Napoleon is defeated at Waterloo',
    year: 1815,
    d: 'His hundred-day comeback ended in a Belgian field; he died in exile on Saint Helena.',
  },
  {
    num: 12,
    quizId: 'circa-7-25-26',
    live: '2026-07-25',
    dateLabel: 'July 25, 2026',
    sunday: false,
    title: 'Sputnik becomes the first satellite in orbit',
    year: 1957,
    d: 'It was the size of a beach ball and beeped for three weeks; the Space Race was on.',
  },
  {
    num: 13,
    quizId: 'circa-7-26-26',
    live: '2026-07-26',
    dateLabel: 'July 26, 2026',
    sunday: true,
    title: "The Defenestration of Prague starts the Thirty Years' War",
    year: 1618,
    d: 'Two imperial officials were thrown from a castle window and survived — into a dung heap, by one account.',
  },
  {
    num: 14,
    quizId: 'circa-7-27-26',
    live: '2026-07-27',
    dateLabel: 'July 27, 2026',
    sunday: false,
    title: 'The American Civil War begins at Fort Sumter',
    year: 1861,
    d: 'The 34-hour bombardment killed no one; the war that followed killed more than 600,000.',
  },
  {
    num: 15,
    quizId: 'circa-7-28-26',
    live: '2026-07-28',
    dateLabel: 'July 28, 2026',
    sunday: false,
    title: 'The Chernobyl reactor explodes',
    year: 1986,
    d: "A safety test gone wrong; the plant's last reactor kept producing power until 2000.",
  },
  {
    num: 16,
    quizId: 'circa-7-29-26',
    live: '2026-07-29',
    dateLabel: 'July 29, 2026',
    sunday: false,
    title: 'The United States Constitution is signed',
    year: 1787,
    d: 'Thirty-nine delegates signed; Rhode Island never even sent one.',
  },
  {
    num: 17,
    quizId: 'circa-7-30-26',
    live: '2026-07-30',
    dateLabel: 'July 30, 2026',
    sunday: false,
    title: 'The great San Francisco earthquake strikes',
    year: 1906,
    d: 'The fires that followed did most of the damage, burning for three days.',
  },
  {
    num: 18,
    quizId: 'circa-7-31-26',
    live: '2026-07-31',
    dateLabel: 'July 31, 2026',
    sunday: false,
    title: 'Mount Everest is climbed for the first time',
    year: 1953,
    d: 'Hillary and Norgay spent about 15 minutes on top; the news reached London on coronation day.',
  },
  {
    num: 19,
    quizId: 'circa-8-1-26',
    live: '2026-08-01',
    dateLabel: 'August 1, 2026',
    sunday: false,
    title: 'Prohibition begins in the United States',
    year: 1920,
    d: 'Thirteen dry years built the bootleg fortunes of gangsters like Al Capone.',
  },
  {
    num: 20,
    quizId: 'circa-8-2-26',
    live: '2026-08-02',
    dateLabel: 'August 2, 2026',
    sunday: true,
    title: 'The Mona Lisa is stolen from the Louvre',
    year: 1911,
    d: 'A museum handyman walked out with it under his smock; the theft made the painting world-famous.',
  },
  {
    num: 21,
    quizId: 'circa-8-3-26',
    live: '2026-08-03',
    dateLabel: 'August 3, 2026',
    sunday: false,
    title: 'Rosa Parks refuses to give up her bus seat',
    year: 1955,
    d: 'Her arrest launched the 381-day Montgomery bus boycott and a 26-year-old Dr. King.',
  },
];
