// Puzzle data for Feud, the daily crowd-survey game. SERVER-ONLY: imported by
// app/feud/page.js (which strips everything but the questions before the
// client sees it) and by app/api/feud/route.js (which buckets and scores
// against the house pool + real answers).
//
// Five prompts a day. Each prompt carries:
//   q       — the survey question shown to players.
//   answers — the canonical answer buckets: `c` is the display label, `k` the
//             alias keys (quiz keyHit matching: substring either way, or every
//             word of a multi-word key present). The label itself is also
//             matched, so `k` only needs variants. Free-text answers that
//             match no bucket form dynamic buckets by normalized string.
//   house   — ~40 pre-written house votes (indices into `answers`), shaped to
//             a plausible crowd. They seed the pool until more than ten real
//             players are in (lib/feud-score.js HOUSE_CUTOFF), then retire.
//
// When banking more days: fresh, universally-answerable prompts (no trivia,
// no regional bias), never reuse a prompt, house always sums to 40 with no
// zero-vote bucket, and run the alias self-collision audit before shipping
// (every label + alias must resolve to its own bucket through the matcher).
export const PUZZLES = [
  {
    num: 1,
    quizId: "feud-8-1-26",
    live: "2026-08-01",
    dateLabel: "August 1, 2026",
    sunday: false,
    prompts: [
      {
        q: "Name something people do when they can't fall asleep.",
        answers: [
          { c: "Scroll their phone", k: ["phone", "scroll", "tiktok", "instagram", "social media", "doomscroll"] },
          { c: "Watch TV", k: ["tv", "television", "netflix", "youtube", "watch a show", "movie"] },
          { c: "Read", k: ["read", "book"] },
          { c: "Count sheep", k: ["sheep"] },
          { c: "Toss and turn", k: ["toss", "turn over", "lie there", "stare at the ceiling"] },
          { c: "Drink something warm", k: ["tea", "warm milk", "chamomile", "hot milk"] },
          { c: "Take melatonin", k: ["melatonin", "sleeping pill", "nyquil"] },
          { c: "White noise", k: ["white noise", "fan", "rain sounds", "podcast", "music"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7],
      },
      {
        q: "Name a food that's better as a leftover.",
        answers: [
          { c: "Pizza", k: ["pizza", "cold pizza"] },
          { c: "Chinese food", k: ["chinese", "lo mein", "fried rice", "takeout"] },
          { c: "Lasagna", k: ["lasagna"] },
          { c: "Chili", k: ["chili"] },
          { c: "Spaghetti", k: ["spaghetti", "pasta", "bolognese"] },
          { c: "Soup or stew", k: ["soup", "stew", "beef stew"] },
          { c: "Curry", k: ["curry"] },
          { c: "Fried chicken", k: ["fried chicken", "chicken"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7],
      },
      {
        q: "Name something people are always losing.",
        answers: [
          { c: "Keys", k: ["key", "car keys", "house keys"] },
          { c: "Phone", k: ["phone", "cell"] },
          { c: "The remote", k: ["remote", "clicker"] },
          { c: "Wallet", k: ["wallet", "purse"] },
          { c: "Sunglasses", k: ["sunglasses", "glasses"] },
          { c: "Socks", k: ["sock"] },
          { c: "Chapstick", k: ["chapstick", "lip balm"] },
          { c: "Earbuds", k: ["earbud", "airpod"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7],
      },
      {
        q: "Name an excuse people give for being late.",
        answers: [
          { c: "Traffic", k: ["traffic", "traffic was bad", "accident on the road"] },
          { c: "Overslept", k: ["overslept", "slept in", "slept through"] },
          { c: "Alarm didn't go off", k: ["alarm", "alarm didnt go off"] },
          { c: "Lost track of time", k: ["lost track", "didnt notice the time"] },
          { c: "Couldn't find parking", k: ["parking"] },
          { c: "Kids", k: ["kid", "the kids", "getting the kids ready"] },
          { c: "Train or bus was late", k: ["train", "bus", "subway"] },
          { c: "Couldn't find my keys", k: ["find my keys", "looking for keys"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 6, 6, 7],
      },
      {
        q: "Name something you'd find in a car's glovebox.",
        answers: [
          { c: "Registration", k: ["registration", "car registration"] },
          { c: "Napkins", k: ["napkin"] },
          { c: "Owner's manual", k: ["manual", "owners manual"] },
          { c: "Insurance card", k: ["insurance"] },
          { c: "Sunglasses", k: ["sunglasses", "glasses"] },
          { c: "Tire gauge", k: ["tire gauge", "gauge"] },
          { c: "Gum or mints", k: ["gum", "mint"] },
          { c: "Ketchup packets", k: ["ketchup", "sauce packets"] },
          { c: "Flashlight", k: ["flashlight"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7, 8],
      },
    ],
  },
  {
    num: 2,
    quizId: "feud-8-2-26",
    live: "2026-08-02",
    dateLabel: "August 2, 2026",
    sunday: false,
    prompts: [
      {
        q: "Name a topping people put on a hot dog.",
        answers: [
          { c: "Mustard", k: ["mustard"] },
          { c: "Ketchup", k: ["ketchup"] },
          { c: "Relish", k: ["relish"] },
          { c: "Onions", k: ["onion"] },
          { c: "Chili", k: ["chili"] },
          { c: "Cheese", k: ["cheese"] },
          { c: "Sauerkraut", k: ["sauerkraut", "kraut"] },
          { c: "Mayo", k: ["mayo", "mayonnaise"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 5, 5, 6, 6, 7],
      },
      {
        q: "Name something people do in an elevator to avoid talking.",
        answers: [
          { c: "Stare at their phone", k: ["phone", "check phone", "pretend to text", "scroll"] },
          { c: "Watch the floor numbers", k: ["numbers", "floor numbers", "watch the numbers", "stare at the display"] },
          { c: "Stare at the door", k: ["door", "stare at the door", "stare straight ahead"] },
          { c: "Look at the floor", k: ["look down", "look at their shoes"] },
          { c: "Earbuds in", k: ["earbud", "airpod", "listen to music"] },
          { c: "Awkward smile", k: ["smile", "nod"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5],
      },
      {
        q: "Name a chore people put off the longest.",
        answers: [
          { c: "Laundry", k: ["laundry", "folding laundry", "folding clothes"] },
          { c: "Dishes", k: ["dish", "the dishes"] },
          { c: "Cleaning the bathroom", k: ["bathroom", "toilet", "scrubbing the shower"] },
          { c: "Ironing", k: ["ironing"] },
          { c: "Mowing the lawn", k: ["mow", "lawn", "yard work"] },
          { c: "Dusting", k: ["dusting"] },
          { c: "Cleaning windows", k: ["window"] },
          { c: "Organizing the closet", k: ["closet", "garage"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7],
      },
      {
        q: "Name the first food to disappear at a potluck.",
        answers: [
          { c: "Deviled eggs", k: ["deviled egg"] },
          { c: "Mac and cheese", k: ["mac and cheese", "mac n cheese", "macaroni"] },
          { c: "Fried chicken", k: ["fried chicken", "chicken"] },
          { c: "Desserts", k: ["dessert", "brownies", "cookies", "cake"] },
          { c: "Meatballs", k: ["meatball"] },
          { c: "Chips and dip", k: ["dip", "chips", "queso", "guac", "guacamole"] },
          { c: "Potato salad", k: ["potato salad"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6],
      },
      {
        q: "Name a sound that instantly annoys people.",
        answers: [
          { c: "Nails on a chalkboard", k: ["nails", "chalkboard"] },
          { c: "Alarm clock", k: ["alarm clock", "morning alarm"] },
          { c: "Loud chewing", k: ["chewing", "chewing with mouth open", "smacking"] },
          { c: "Snoring", k: ["snoring"] },
          { c: "Crying baby", k: ["baby", "crying"] },
          { c: "Car alarm", k: ["car alarm going off"] },
          { c: "A mosquito buzz", k: ["mosquito", "buzzing", "fly"] },
          { c: "Dripping faucet", k: ["dripping", "faucet", "leaky"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7],
      },
    ],
  },
  {
    num: 3,
    quizId: "feud-8-3-26",
    live: "2026-08-03",
    dateLabel: "August 3, 2026",
    sunday: false,
    prompts: [
      {
        q: "Name something people forget to pack for vacation.",
        answers: [
          { c: "Toothbrush", k: ["toothbrush", "tooth brush"] },
          { c: "Phone charger", k: ["charger", "cable"] },
          { c: "Sunscreen", k: ["sunscreen", "sunblock"] },
          { c: "Toothpaste", k: ["toothpaste"] },
          { c: "Deodorant", k: ["deodorant"] },
          { c: "Underwear", k: ["underwear", "socks"] },
          { c: "Medication", k: ["medication", "medicine", "pills"] },
          { c: "Passport", k: ["passport"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7],
      },
      {
        q: "Name a pizza topping.",
        answers: [
          { c: "Pepperoni", k: ["pepperoni"] },
          { c: "Mushrooms", k: ["mushroom"] },
          { c: "Green peppers", k: ["green pepper", "bell pepper"] },
          { c: "Sausage", k: ["sausage"] },
          { c: "Extra cheese", k: ["cheese"] },
          { c: "Pineapple", k: ["pineapple"] },
          { c: "Onions", k: ["onion"] },
          { c: "Olives", k: ["olive"] },
          { c: "Bacon", k: ["bacon", "ham"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 8, 8],
      },
      {
        q: "Name something in everyone's junk drawer.",
        answers: [
          { c: "Batteries", k: ["battery", "batteries"] },
          { c: "Pens", k: ["pen", "pencil", "marker"] },
          { c: "Rubber bands", k: ["rubber band"] },
          { c: "Tape", k: ["tape", "scotch tape"] },
          { c: "Scissors", k: ["scissor"] },
          { c: "Takeout menus", k: ["menu", "takeout"] },
          { c: "Old chargers", k: ["charger", "cords", "cables"] },
          { c: "Matches or lighters", k: ["match", "lighter"] },
          { c: "A screwdriver", k: ["screwdriver"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 8, 8],
      },
      {
        q: "Name a reason people honk their horn.",
        answers: [
          { c: "Got cut off", k: ["cut off", "cut me off"] },
          { c: "Light turned green", k: ["green", "light", "sitting at the light", "not moving"] },
          { c: "Slow driver", k: ["slow"] },
          { c: "Someone texting while driving", k: ["texting", "on their phone"] },
          { c: "Road rage", k: ["rage", "angry", "mad"] },
          { c: "Saying hi", k: ["hi", "hello", "wave", "friend"] },
          { c: "Jaywalker", k: ["jaywalker", "pedestrian"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6],
      },
      {
        q: "Name something people pretend to understand.",
        answers: [
          { c: "Wine", k: ["wine", "wine tasting"] },
          { c: "Crypto", k: ["crypto", "bitcoin", "nft"] },
          { c: "Taxes", k: ["tax"] },
          { c: "The stock market", k: ["stock", "investing"] },
          { c: "Insurance", k: ["insurance"] },
          { c: "Modern art", k: ["art", "modern art"] },
          { c: "Jazz", k: ["jazz"] },
          { c: "Sports rules", k: ["offsides", "football rules", "cricket"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7],
      },
    ],
  },
  {
    num: 4,
    quizId: "feud-8-4-26",
    live: "2026-08-04",
    dateLabel: "August 4, 2026",
    sunday: false,
    prompts: [
      {
        q: "Name a classic breakfast food.",
        answers: [
          { c: "Eggs", k: ["egg", "scrambled", "omelet"] },
          { c: "Pancakes", k: ["pancake"] },
          { c: "Bacon", k: ["bacon"] },
          { c: "Cereal", k: ["cereal"] },
          { c: "Toast", k: ["toast", "bagel"] },
          { c: "Waffles", k: ["waffle"] },
          { c: "Oatmeal", k: ["oatmeal"] },
          { c: "Yogurt", k: ["yogurt"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7],
      },
      {
        q: "Name something people do while on hold.",
        answers: [
          { c: "Put it on speaker", k: ["speaker", "speakerphone"] },
          { c: "Scroll their phone", k: ["scroll", "browse", "social media"] },
          { c: "Do chores", k: ["chore", "clean", "dishes", "laundry"] },
          { c: "Forget they're on hold", k: ["forget"] },
          { c: "Hum along to the music", k: ["humming", "sing along", "hold music"] },
          { c: "Yell at the robot", k: ["yell", "representative", "talk to a human"] },
          { c: "Make food", k: ["eat", "snack", "make lunch"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6],
      },
      {
        q: "Name an animal people are irrationally afraid of.",
        answers: [
          { c: "Spiders", k: ["spider"] },
          { c: "Snakes", k: ["snake"] },
          { c: "Sharks", k: ["shark"] },
          { c: "Mice or rats", k: ["mice", "mouse", "rat"] },
          { c: "Bees", k: ["bee", "wasp"] },
          { c: "Cockroaches", k: ["cockroach", "roach"] },
          { c: "Bats", k: ["bat"] },
          { c: "Birds", k: ["bird", "pigeon"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 6, 7],
      },
      {
        q: "Name something you'd find under a couch cushion.",
        answers: [
          { c: "Loose change", k: ["change", "coin", "money", "quarter"] },
          { c: "The remote", k: ["remote"] },
          { c: "Crumbs", k: ["crumb", "chips", "food"] },
          { c: "A pen", k: ["pen"] },
          { c: "Hair ties", k: ["hair tie", "scrunchie", "bobby pin"] },
          { c: "Kids' toys", k: ["toy", "lego"] },
          { c: "A phone", k: ["phone"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6],
      },
      {
        q: "Name a song everyone knows the words to.",
        answers: [
          { c: "Happy Birthday", k: ["happy birthday"] },
          { c: "Sweet Caroline", k: ["sweet caroline"] },
          { c: "Bohemian Rhapsody", k: ["bohemian"] },
          { c: "Don't Stop Believin'", k: ["dont stop believin", "journey"] },
          { c: "Twinkle Twinkle Little Star", k: ["twinkle"] },
          { c: "Hey Jude", k: ["hey jude"] },
          { c: "Wonderwall", k: ["wonderwall"] },
          { c: "The National Anthem", k: ["anthem", "star spangled"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7],
      },
    ],
  },
  {
    num: 5,
    quizId: "feud-8-5-26",
    live: "2026-08-05",
    dateLabel: "August 5, 2026",
    sunday: false,
    prompts: [
      {
        q: "Name something people do at a red light.",
        answers: [
          { c: "Check their phone", k: ["phone", "text", "scroll"] },
          { c: "Change the music", k: ["music", "radio", "song", "change the station"] },
          { c: "Sing", k: ["sing", "car karaoke"] },
          { c: "Look at other drivers", k: ["look at people", "stare at drivers", "people watch"] },
          { c: "Fix their hair or makeup", k: ["makeup", "mirror", "hair"] },
          { c: "Daydream", k: ["daydream", "zone out", "space out"] },
          { c: "Drink their coffee", k: ["coffee", "drink"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6],
      },
      {
        q: "Name a condiment in everyone's fridge.",
        answers: [
          { c: "Ketchup", k: ["ketchup"] },
          { c: "Mustard", k: ["mustard"] },
          { c: "Mayo", k: ["mayo", "mayonnaise"] },
          { c: "Ranch", k: ["ranch"] },
          { c: "Hot sauce", k: ["hot sauce", "sriracha", "tabasco"] },
          { c: "Soy sauce", k: ["soy"] },
          { c: "BBQ sauce", k: ["bbq", "barbecue"] },
          { c: "Salad dressing", k: ["dressing", "italian"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 5, 5, 6, 6, 7],
      },
      {
        q: "Name a store people wander to kill time.",
        answers: [
          { c: "Target", k: ["target"] },
          { c: "The mall", k: ["mall"] },
          { c: "A bookstore", k: ["bookstore", "barnes"] },
          { c: "Walmart", k: ["walmart"] },
          { c: "A thrift store", k: ["thrift", "goodwill"] },
          { c: "Home Depot", k: ["home depot", "lowes", "hardware"] },
          { c: "Costco", k: ["costco", "sams club"] },
          { c: "IKEA", k: ["ikea"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7],
      },
      {
        q: "Name something kids today will never understand.",
        answers: [
          { c: "Dial-up internet", k: ["dial up", "dialup", "aol", "modem"] },
          { c: "VHS tapes", k: ["vhs", "rewinding", "blockbuster", "renting movies"] },
          { c: "Landlines", k: ["landline", "house phone", "cord phone"] },
          { c: "Payphones", k: ["payphone", "pay phone"] },
          { c: "Burning CDs", k: ["burning cd", "mix cd", "cds", "walkman"] },
          { c: "No internet at all", k: ["no internet", "encyclopedia", "library research"] },
          { c: "TV Guide", k: ["tv guide", "waiting for a show", "saturday cartoons"] },
          { c: "Paper maps", k: ["paper map", "mapquest", "printing directions"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7],
      },
      {
        q: "Name something plane passengers do that annoys everyone.",
        answers: [
          { c: "Recline their seat", k: ["recline", "seat back"] },
          { c: "Kick the seat", k: ["kick"] },
          { c: "Take their shoes off", k: ["shoes", "bare feet", "feet"] },
          { c: "Stand up right at landing", k: ["stand up", "rush the aisle", "unbuckle early"] },
          { c: "Talk too loud", k: ["talk", "loud talker", "chatty"] },
          { c: "Hog the armrest", k: ["armrest"] },
          { c: "Bring smelly food", k: ["smelly", "tuna", "food"] },
          { c: "Play videos out loud", k: ["no headphones", "videos out loud", "speaker"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 7, 7],
      },
    ],
  },
  {
    num: 6,
    quizId: "feud-8-6-26",
    live: "2026-08-06",
    dateLabel: "August 6, 2026",
    sunday: false,
    prompts: [
      {
        q: "Name something in a woman's purse.",
        answers: [
          { c: "Wallet", k: ["wallet"] },
          { c: "Phone", k: ["phone"] },
          { c: "Keys", k: ["key"] },
          { c: "Lipstick", k: ["lipstick", "lip gloss", "chapstick", "makeup"] },
          { c: "Gum", k: ["gum", "mint"] },
          { c: "Hand sanitizer", k: ["sanitizer"] },
          { c: "Tissues", k: ["tissue", "kleenex"] },
          { c: "Hair ties", k: ["hair tie", "bobby pin", "brush"] },
          { c: "Sunglasses", k: ["sunglasses"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7, 8],
      },
      {
        q: "Name a food people eat straight from the container.",
        answers: [
          { c: "Ice cream", k: ["ice cream"] },
          { c: "Peanut butter", k: ["peanut butter"] },
          { c: "Cookie dough", k: ["cookie dough"] },
          { c: "Whipped cream", k: ["whipped cream", "cool whip"] },
          { c: "Chips", k: ["chip"] },
          { c: "Pickles", k: ["pickle", "pickle jar"] },
          { c: "Nutella", k: ["nutella"] },
          { c: "Cereal", k: ["cereal"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7],
      },
      {
        q: "Name something people swear they'll start tomorrow.",
        answers: [
          { c: "The gym", k: ["gym", "working out", "exercise"] },
          { c: "A diet", k: ["diet", "eating healthy", "eating better"] },
          { c: "Cleaning", k: ["clean", "laundry", "organizing"] },
          { c: "Homework", k: ["homework", "studying", "that assignment"] },
          { c: "Waking up early", k: ["waking up early", "early"] },
          { c: "Quitting smoking", k: ["smoking", "quit smoking", "vaping"] },
          { c: "Budgeting", k: ["budget", "saving money"] },
          { c: "Calling someone back", k: ["call back", "call mom"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 6, 6, 7],
      },
      {
        q: "Name a job kids say they want when they grow up.",
        answers: [
          { c: "Astronaut", k: ["astronaut"] },
          { c: "Doctor", k: ["doctor", "vet", "veterinarian"] },
          { c: "Firefighter", k: ["firefighter", "fireman"] },
          { c: "Pro athlete", k: ["athlete", "football player", "basketball player", "soccer player"] },
          { c: "Teacher", k: ["teacher"] },
          { c: "Police officer", k: ["police", "cop"] },
          { c: "YouTuber", k: ["youtuber", "influencer", "streamer"] },
          { c: "President", k: ["president"] },
          { c: "Princess", k: ["princess"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 7, 7, 8],
      },
      {
        q: "Name something that ruins a movie theater experience.",
        answers: [
          { c: "People talking", k: ["talking", "loud people"] },
          { c: "Phone screens", k: ["phone", "texting"] },
          { c: "A crying baby", k: ["baby", "crying", "kids"] },
          { c: "Seat kicking", k: ["kick"] },
          { c: "Loud chewing", k: ["chewing", "loud popcorn", "crinkling wrappers"] },
          { c: "A tall person in front", k: ["tall"] },
          { c: "Overpriced snacks", k: ["overpriced", "expensive", "prices"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6],
      },
    ],
  },
  {
    num: 7,
    quizId: "feud-8-7-26",
    live: "2026-08-07",
    dateLabel: "August 7, 2026",
    sunday: false,
    prompts: [
      {
        q: "Name something people do the night before a trip.",
        answers: [
          { c: "Pack", k: ["pack", "packing"] },
          { c: "Can't sleep", k: ["cant sleep", "barely sleep", "too excited"] },
          { c: "Set five alarms", k: ["alarm"] },
          { c: "Check in online", k: ["check in", "boarding pass"] },
          { c: "Charge everything", k: ["charge", "charger"] },
          { c: "Triple-check documents", k: ["passport", "documents", "tickets", "double check"] },
          { c: "Clean the house", k: ["clean", "take out the trash"] },
          { c: "Stay up too late", k: ["stay up", "up late"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 7],
      },
      {
        q: "Name a fruit people put in a smoothie.",
        answers: [
          { c: "Banana", k: ["banana"] },
          { c: "Strawberries", k: ["strawberry", "strawberries"] },
          { c: "Blueberries", k: ["blueberry", "blueberries"] },
          { c: "Mango", k: ["mango"] },
          { c: "Pineapple", k: ["pineapple"] },
          { c: "Peach", k: ["peach"] },
          { c: "Raspberries", k: ["raspberry", "raspberries"] },
          { c: "Avocado", k: ["avocado"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 5, 5, 6, 7],
      },
      {
        q: "Name something guests always ask for at your house.",
        answers: [
          { c: "The wifi password", k: ["wifi", "wi fi", "internet password"] },
          { c: "Water", k: ["water", "something to drink", "a drink"] },
          { c: "The bathroom", k: ["bathroom", "restroom", "toilet"] },
          { c: "A phone charger", k: ["charger"] },
          { c: "Coffee", k: ["coffee"] },
          { c: "Snacks", k: ["snack", "food"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 5, 5],
      },
      {
        q: "Name a white lie everyone tells.",
        answers: [
          { c: "I'm fine", k: ["im fine", "fine"] },
          { c: "I'm almost there", k: ["almost there", "5 minutes away", "on my way"] },
          { c: "I read the terms and conditions", k: ["terms", "terms and conditions"] },
          { c: "I love it (about a gift)", k: ["love the gift", "love it", "its perfect"] },
          { c: "Let's get lunch sometime", k: ["lets get lunch", "we should hang out", "lets catch up"] },
          { c: "I'm busy that day", k: ["busy", "have plans"] },
          { c: "Your baby is so cute", k: ["baby is cute", "cute baby"] },
          { c: "I've seen that movie", k: ["seen it", "seen that movie"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7],
      },
      {
        q: "Name something people hoard but never use.",
        answers: [
          { c: "Plastic bags", k: ["plastic bag", "grocery bag", "bag of bags"] },
          { c: "Tupperware", k: ["tupperware", "containers", "lids"] },
          { c: "Hotel toiletries", k: ["hotel shampoo", "hotel soap", "toiletries"] },
          { c: "Candles", k: ["candle"] },
          { c: "Cables and chargers", k: ["cable", "charger", "cords"] },
          { c: "Sauce packets", k: ["sauce packet", "ketchup packet", "soy sauce packet"] },
          { c: "Gift bags", k: ["gift bag", "wrapping paper", "boxes"] },
          { c: "Rubber bands", k: ["rubber band", "twist ties"] },
          { c: "Pens", k: ["pen"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 8],
      },
    ],
  },
  {
    num: 8,
    quizId: "feud-8-8-26",
    live: "2026-08-08",
    dateLabel: "August 8, 2026",
    sunday: false,
    prompts: [
      {
        q: "Name something at every kid's birthday party.",
        answers: [
          { c: "Cake", k: ["cake", "birthday cake"] },
          { c: "Balloons", k: ["balloon"] },
          { c: "Pizza", k: ["pizza"] },
          { c: "Presents", k: ["present", "gift"] },
          { c: "A pinata", k: ["pinata"] },
          { c: "Goodie bags", k: ["goodie bag", "party favors"] },
          { c: "A bounce house", k: ["bounce house", "bouncy castle"] },
          { c: "A crying kid", k: ["crying", "meltdown", "tantrum"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 5, 5, 6, 6, 7],
      },
      {
        q: "Name a vegetable kids refuse to eat.",
        answers: [
          { c: "Broccoli", k: ["broccoli"] },
          { c: "Brussels sprouts", k: ["brussels", "sprouts"] },
          { c: "Spinach", k: ["spinach"] },
          { c: "Peas", k: ["pea"] },
          { c: "Asparagus", k: ["asparagus"] },
          { c: "Cauliflower", k: ["cauliflower"] },
          { c: "Carrots", k: ["carrot"] },
          { c: "Beets", k: ["beet"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 6, 6, 7],
      },
      {
        q: "Name the first thing people check when they wake up.",
        answers: [
          { c: "Their phone", k: ["phone", "notifications", "messages", "texts"] },
          { c: "The time", k: ["time", "clock", "what time it is"] },
          { c: "Social media", k: ["instagram", "tiktok", "social"] },
          { c: "The weather", k: ["weather"] },
          { c: "Email", k: ["email"] },
          { c: "The news", k: ["news"] },
          { c: "The snooze button", k: ["snooze"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 6],
      },
      {
        q: "Name a board game that ends friendships.",
        answers: [
          { c: "Monopoly", k: ["monopoly"] },
          { c: "Uno", k: ["uno"] },
          { c: "Risk", k: ["risk"] },
          { c: "Catan", k: ["catan", "settlers"] },
          { c: "Sorry!", k: ["sorry"] },
          { c: "Scrabble", k: ["scrabble"] },
          { c: "Mario Kart", k: ["mario kart", "mario party"] },
          { c: "Chess", k: ["chess"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 5, 5, 6, 7],
      },
      {
        q: "Name something people take home from a hotel room.",
        answers: [
          { c: "Shampoo bottles", k: ["shampoo", "conditioner", "toiletries", "lotion"] },
          { c: "Soap", k: ["soap"] },
          { c: "Pens", k: ["pen"] },
          { c: "Notepads", k: ["notepad", "stationery"] },
          { c: "Slippers", k: ["slipper"] },
          { c: "Coffee pods", k: ["coffee", "tea bags"] },
          { c: "Towels", k: ["towel", "robe"] },
          { c: "The sewing kit", k: ["sewing"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7],
      },
    ],
  },
  {
    num: 9,
    quizId: "feud-8-9-26",
    live: "2026-08-09",
    dateLabel: "August 9, 2026",
    sunday: false,
    prompts: [
      {
        q: "Name a pet name couples call each other.",
        answers: [
          { c: "Babe", k: ["babe"] },
          { c: "Baby", k: ["baby"] },
          { c: "Honey", k: ["honey", "hun"] },
          { c: "Sweetheart", k: ["sweetheart", "sweetie"] },
          { c: "Love", k: ["love", "my love"] },
          { c: "Boo", k: ["boo"] },
          { c: "Dear", k: ["dear"] },
          { c: "Darling", k: ["darling"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 6, 6, 7],
      },
      {
        q: "Name something that breaks right after the warranty ends.",
        answers: [
          { c: "Phone", k: ["phone", "iphone", "screen"] },
          { c: "Washer or dryer", k: ["washing machine", "dryer", "laundry machine"] },
          { c: "The car", k: ["car", "transmission"] },
          { c: "Fridge", k: ["fridge", "refrigerator"] },
          { c: "TV", k: ["tv"] },
          { c: "Laptop", k: ["laptop", "computer"] },
          { c: "Dishwasher", k: ["dishwasher"] },
          { c: "Vacuum", k: ["vacuum"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7],
      },
      {
        q: "Name a smell that reminds people of childhood.",
        answers: [
          { c: "Fresh-cut grass", k: ["grass", "cut grass"] },
          { c: "Cookies baking", k: ["cookies", "baking", "fresh baked"] },
          { c: "Crayons", k: ["crayon"] },
          { c: "Grandma's house", k: ["grandma"] },
          { c: "Chlorine", k: ["chlorine", "pool"] },
          { c: "Play-Doh", k: ["play doh", "playdoh"] },
          { c: "Campfire", k: ["campfire", "bonfire"] },
          { c: "Rain", k: ["rain", "wet pavement"] },
          { c: "School glue", k: ["glue", "elmers"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 7, 7, 8],
      },
      {
        q: "Name something people do in the shower besides shower.",
        answers: [
          { c: "Sing", k: ["sing", "concert"] },
          { c: "Think about life", k: ["think", "contemplate", "reflect"] },
          { c: "Win imaginary arguments", k: ["argue", "argument", "rehearse arguments"] },
          { c: "Cry", k: ["cry"] },
          { c: "Plan their day", k: ["plan"] },
          { c: "Come up with ideas", k: ["idea", "shower thoughts"] },
          { c: "Just stand there", k: ["stand", "stand in the hot water"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 6, 6],
      },
      {
        q: "Name a food that's impossible to eat gracefully.",
        answers: [
          { c: "Ribs", k: ["rib"] },
          { c: "Spaghetti", k: ["spaghetti", "pasta"] },
          { c: "Wings", k: ["wing", "buffalo wings"] },
          { c: "Tacos", k: ["taco"] },
          { c: "Corn on the cob", k: ["corn"] },
          { c: "A big burger", k: ["burger"] },
          { c: "Crab legs", k: ["crab", "lobster"] },
          { c: "A powdered donut", k: ["powdered", "donut"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 7, 7],
      },
    ],
  },
  {
    num: 10,
    quizId: "feud-8-10-26",
    live: "2026-08-10",
    dateLabel: "August 10, 2026",
    sunday: false,
    prompts: [
      {
        q: "Name something that happens at every wedding.",
        answers: [
          { c: "Dancing", k: ["dancing", "dance floor"] },
          { c: "Someone cries", k: ["cry", "crying", "tears"] },
          { c: "Speeches", k: ["speech", "toast"] },
          { c: "The bouquet toss", k: ["bouquet"] },
          { c: "Cake cutting", k: ["cake"] },
          { c: "A drunk uncle", k: ["drunk uncle", "drunk relative", "someone gets too drunk"] },
          { c: "An open bar", k: ["open bar"] },
          { c: "The Electric Slide", k: ["electric slide", "cupid shuffle", "line dance"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 7, 7],
      },
      {
        q: "Name a snack people buy at the movies.",
        answers: [
          { c: "Popcorn", k: ["popcorn"] },
          { c: "Candy", k: ["candy", "m and m", "sour patch", "twizzlers", "milk duds"] },
          { c: "Soda", k: ["soda", "coke", "icee", "slushie"] },
          { c: "Nachos", k: ["nacho"] },
          { c: "A pretzel", k: ["pretzel"] },
          { c: "Hot dog", k: ["hot dog"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 5, 5],
      },
      {
        q: "Name something people stretch the truth about on a resume.",
        answers: [
          { c: "Their skills", k: ["skill", "excel", "proficient"] },
          { c: "Experience", k: ["experience", "years"] },
          { c: "Job titles", k: ["title"] },
          { c: "Employment dates", k: ["date", "gaps"] },
          { c: "References", k: ["reference"] },
          { c: "Languages", k: ["language", "fluent"] },
          { c: "GPA", k: ["gpa"] },
          { c: "Hobbies", k: ["hobby", "interests"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 7],
      },
      {
        q: "Name a sport that's boring to watch on TV.",
        answers: [
          { c: "Golf", k: ["golf"] },
          { c: "Baseball", k: ["baseball"] },
          { c: "NASCAR", k: ["nascar", "racing"] },
          { c: "Cricket", k: ["cricket"] },
          { c: "Bowling", k: ["bowling"] },
          { c: "Soccer", k: ["soccer"] },
          { c: "Fishing", k: ["fishing"] },
          { c: "Chess", k: ["chess"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 7],
      },
      {
        q: "Name something in every garage.",
        answers: [
          { c: "Tools", k: ["tool", "toolbox"] },
          { c: "The lawn mower", k: ["mower", "lawn mower"] },
          { c: "Boxes of junk", k: ["boxes", "junk", "old boxes", "clutter"] },
          { c: "Bikes", k: ["bike", "bicycle"] },
          { c: "A ladder", k: ["ladder"] },
          { c: "Old paint cans", k: ["paint"] },
          { c: "A car", k: ["car"] },
          { c: "Christmas decorations", k: ["christmas", "holiday decorations"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 7],
      },
    ],
  },
  {
    num: 11,
    quizId: "feud-8-11-26",
    live: "2026-08-11",
    dateLabel: "August 11, 2026",
    sunday: false,
    prompts: [
      {
        q: "Name a reason people yell at the TV.",
        answers: [
          { c: "A bad ref call", k: ["ref", "referee", "bad call"] },
          { c: "Their team is losing", k: ["team", "losing", "sports", "fumble", "missed shot"] },
          { c: "Shouting game show answers", k: ["game show", "jeopardy", "wheel of fortune", "answer"] },
          { c: "Horror movie decisions", k: ["horror", "dont go in there", "dont open the door"] },
          { c: "The news", k: ["news", "politics", "politician"] },
          { c: "A cliffhanger", k: ["cliffhanger", "season finale"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5],
      },
      {
        q: "Name a drink people order at a coffee shop.",
        answers: [
          { c: "A latte", k: ["latte"] },
          { c: "Iced coffee", k: ["iced coffee", "cold brew"] },
          { c: "Plain coffee", k: ["black coffee", "drip", "regular coffee", "americano"] },
          { c: "A cappuccino", k: ["cappuccino"] },
          { c: "A mocha", k: ["mocha"] },
          { c: "A frappuccino", k: ["frappuccino", "frappe", "frozen"] },
          { c: "Tea", k: ["tea", "chai"] },
          { c: "Hot chocolate", k: ["hot chocolate"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 7],
      },
      {
        q: "Name something that makes a road trip better.",
        answers: [
          { c: "Snacks", k: ["snack", "road trip snacks"] },
          { c: "Good music", k: ["music", "playlist", "radio"] },
          { c: "Good company", k: ["company", "friends", "passenger"] },
          { c: "No traffic", k: ["no traffic", "empty road"] },
          { c: "Gas station stops", k: ["gas station", "rest stop", "pit stop"] },
          { c: "Nice scenery", k: ["scenery", "views"] },
          { c: "Car games", k: ["game", "i spy", "license plate"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 6, 6],
      },
      {
        q: "Name something people are embarrassed to admit they like.",
        answers: [
          { c: "Reality TV", k: ["reality tv", "bachelor", "love island", "kardashians"] },
          { c: "Fast food", k: ["mcdonalds", "fast food", "taco bell"] },
          { c: "Pop music", k: ["pop", "boy band", "taylor"] },
          { c: "Country music", k: ["country"] },
          { c: "Romance novels", k: ["romance"] },
          { c: "Nickelback", k: ["nickelback"] },
          { c: "Karaoke", k: ["karaoke"] },
          { c: "Cartoons", k: ["cartoon", "anime", "disney"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7],
      },
      {
        q: "Name an item on every grocery list.",
        answers: [
          { c: "Milk", k: ["milk"] },
          { c: "Eggs", k: ["egg"] },
          { c: "Bread", k: ["bread"] },
          { c: "Bananas", k: ["banana"] },
          { c: "Cheese", k: ["cheese"] },
          { c: "Chicken", k: ["chicken"] },
          { c: "Coffee", k: ["coffee"] },
          { c: "Toilet paper", k: ["toilet paper", "paper towels"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 5, 5, 6, 6, 7],
      },
    ],
  },
  {
    num: 12,
    quizId: "feud-8-12-26",
    live: "2026-08-12",
    dateLabel: "August 12, 2026",
    sunday: false,
    prompts: [
      {
        q: "Name what people do when their battery hits 1%.",
        answers: [
          { c: "Hunt for a charger", k: ["charger", "find a charger", "scramble"] },
          { c: "Panic", k: ["panic", "freak out", "anxiety"] },
          { c: "Low power mode", k: ["low power", "battery saver"] },
          { c: "Stop using it", k: ["stop", "put it down", "dont touch it"] },
          { c: "Dim the screen", k: ["dim", "brightness"] },
          { c: "Turn it off", k: ["turn it off", "shut it down"] },
          { c: "Close every app", k: ["close apps"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 5, 5, 6],
      },
      {
        q: "Name a food people burn their mouth on.",
        answers: [
          { c: "Pizza", k: ["pizza", "pizza cheese"] },
          { c: "Soup", k: ["soup"] },
          { c: "Hot Pockets", k: ["hot pocket"] },
          { c: "Coffee", k: ["coffee"] },
          { c: "Mozzarella sticks", k: ["mozzarella"] },
          { c: "Lasagna", k: ["lasagna"] },
          { c: "Grilled cheese", k: ["grilled cheese"] },
          { c: "Tea", k: ["tea"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 5, 5, 6, 6, 7],
      },
      {
        q: "Name something at every yard sale.",
        answers: [
          { c: "Old clothes", k: ["clothes", "clothing"] },
          { c: "Books", k: ["book"] },
          { c: "Kids' toys", k: ["toy"] },
          { c: "Dishes and mugs", k: ["dish", "mug", "glassware", "kitchen stuff"] },
          { c: "Furniture", k: ["furniture", "chair", "table"] },
          { c: "VHS tapes and DVDs", k: ["vhs", "dvd", "cds"] },
          { c: "Exercise equipment", k: ["exercise", "treadmill", "weights"] },
          { c: "Picture frames", k: ["frame"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7],
      },
      {
        q: "Name a phrase teachers say every year.",
        answers: [
          { c: "This will be on the test", k: ["on the test"] },
          { c: "The bell doesn't dismiss you", k: ["bell", "i dismiss you"] },
          { c: "Eyes up front", k: ["eyes up", "pay attention", "listen up"] },
          { c: "No talking", k: ["no talking", "quiet", "silence"] },
          { c: "Did you do the reading?", k: ["reading", "homework"] },
          { c: "See me after class", k: ["after class"] },
          { c: "I'll wait", k: ["ill wait", "i can wait"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6],
      },
      {
        q: "Name something people wish they'd learned in school.",
        answers: [
          { c: "Doing taxes", k: ["tax"] },
          { c: "Budgeting money", k: ["budget", "personal finance", "money", "saving"] },
          { c: "Cooking", k: ["cook"] },
          { c: "Investing", k: ["invest", "stock"] },
          { c: "Car maintenance", k: ["car", "changing a tire", "oil change"] },
          { c: "Social skills", k: ["social", "communication", "people skills"] },
          { c: "First aid", k: ["first aid", "cpr"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 6, 6],
      },
    ],
  },
  {
    num: 13,
    quizId: "feud-8-13-26",
    live: "2026-08-13",
    dateLabel: "August 13, 2026",
    sunday: false,
    prompts: [
      {
        q: "Name something that makes people instantly happy.",
        answers: [
          { c: "Dogs", k: ["dog", "puppy", "puppies"] },
          { c: "Food", k: ["food", "pizza", "snacks", "free food"] },
          { c: "Payday", k: ["payday", "money", "paycheck"] },
          { c: "A nap", k: ["nap", "sleep"] },
          { c: "Music", k: ["music", "favorite song"] },
          { c: "Sunshine", k: ["sun", "sunshine", "nice weather"] },
          { c: "A hug", k: ["hug"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6],
      },
      {
        q: "Name a pizza chain.",
        answers: [
          { c: "Domino's", k: ["dominos"] },
          { c: "Pizza Hut", k: ["pizza hut"] },
          { c: "Papa John's", k: ["papa john"] },
          { c: "Little Caesars", k: ["little caesar", "caesars"] },
          { c: "Marco's", k: ["marco"] },
          { c: "Blaze", k: ["blaze"] },
          { c: "Sbarro", k: ["sbarro"] },
          { c: "Papa Murphy's", k: ["papa murphy"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 5, 6, 7],
      },
      {
        q: "Name something people do at the gym besides work out.",
        answers: [
          { c: "Stare at their phone", k: ["phone", "scroll", "text"] },
          { c: "Take selfies", k: ["selfie", "mirror pic", "photos"] },
          { c: "Chat", k: ["talk", "chat", "socialize"] },
          { c: "Walk around aimlessly", k: ["walk around", "wander"] },
          { c: "People watch", k: ["people watch", "stare at people", "check people out"] },
          { c: "Sit in the sauna", k: ["sauna", "steam room", "hot tub"] },
          { c: "Refill their water", k: ["water", "water fountain"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 6, 6],
      },
      {
        q: "Name something grandparents always have at their house.",
        answers: [
          { c: "A candy dish", k: ["candy", "candy dish", "werthers"] },
          { c: "Old photos", k: ["photo", "pictures of grandkids", "picture frames"] },
          { c: "Crocheted blankets", k: ["blanket", "afghan", "crochet", "quilt"] },
          { c: "A recliner", k: ["recliner", "lazyboy"] },
          { c: "Ticking clocks", k: ["clock", "grandfather clock", "cuckoo"] },
          { c: "A china cabinet", k: ["china"] },
          { c: "Doilies", k: ["doilies", "plastic on the furniture"] },
          { c: "Snacks just for you", k: ["cookies", "treats", "ice cream"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7],
      },
      {
        q: "Name an excuse for calling in 'sick' when you're not.",
        answers: [
          { c: "Just needed a day off", k: ["mental health", "needed a day", "personal day", "dont want to go"] },
          { c: "A hangover", k: ["hangover", "drank too much"] },
          { c: "Feeling 'under the weather'", k: ["under the weather", "not feeling well", "stomach bug", "migraine"] },
          { c: "A job interview", k: ["interview"] },
          { c: "Too tired", k: ["tired", "exhausted", "no sleep"] },
          { c: "An 'appointment'", k: ["appointment", "doctor"] },
          { c: "Nice weather outside", k: ["beach day", "too nice out", "sunny day"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 6, 6],
      },
    ],
  },
  {
    num: 14,
    quizId: "feud-8-14-26",
    live: "2026-08-14",
    dateLabel: "August 14, 2026",
    sunday: false,
    prompts: [
      {
        q: "Name a food people only eat around the holidays.",
        answers: [
          { c: "Turkey", k: ["turkey"] },
          { c: "Stuffing", k: ["stuffing", "dressing"] },
          { c: "Eggnog", k: ["eggnog"] },
          { c: "Cranberry sauce", k: ["cranberry"] },
          { c: "Pumpkin pie", k: ["pumpkin"] },
          { c: "Ham", k: ["ham"] },
          { c: "Green bean casserole", k: ["green bean"] },
          { c: "Fruitcake", k: ["fruitcake"] },
          { c: "Candy canes", k: ["candy cane"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7, 8],
      },
      {
        q: "Name something people do while brushing their teeth.",
        answers: [
          { c: "Scroll their phone", k: ["phone", "scroll"] },
          { c: "Wander the house", k: ["walk", "wander", "pace"] },
          { c: "Stare in the mirror", k: ["mirror", "stare at themselves"] },
          { c: "Think about their day", k: ["think", "plan the day", "zone out"] },
          { c: "Watch TV", k: ["tv", "watch"] },
          { c: "Pick out clothes", k: ["clothes", "outfit"] },
          { c: "Clean the sink", k: ["clean", "tidy"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 5, 5, 6, 6],
      },
      {
        q: "Name a car feature people can't live without.",
        answers: [
          { c: "Backup camera", k: ["backup camera", "rear camera"] },
          { c: "Air conditioning", k: ["air conditioning", "air", "cold air"] },
          { c: "Bluetooth", k: ["bluetooth", "carplay", "apple carplay", "aux"] },
          { c: "Heated seats", k: ["heated seat"] },
          { c: "Cruise control", k: ["cruise"] },
          { c: "Cup holders", k: ["cup holder"] },
          { c: "Power windows", k: ["power window", "windows"] },
          { c: "GPS", k: ["gps", "navigation", "maps"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7],
      },
      {
        q: "Name something that always happens at a barbecue.",
        answers: [
          { c: "Someone burns the food", k: ["burn", "burnt", "charred"] },
          { c: "One guy hogs the grill", k: ["grill hog", "dad grills", "uncle grills", "grill master"] },
          { c: "Too much food", k: ["too much food", "leftovers"] },
          { c: "Flies everywhere", k: ["flies", "bugs", "mosquito"] },
          { c: "Running out of propane", k: ["propane", "charcoal runs out"] },
          { c: "Lawn games", k: ["cornhole", "horseshoes", "lawn games"] },
          { c: "Someone shows up empty-handed", k: ["empty handed", "brings nothing"] },
          { c: "It rains", k: ["rain"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7],
      },
      {
        q: "Name a candy parents steal from their kids' Halloween haul.",
        answers: [
          { c: "Reese's", k: ["reese"] },
          { c: "Snickers", k: ["snickers"] },
          { c: "Kit Kats", k: ["kit kat"] },
          { c: "Twix", k: ["twix"] },
          { c: "M&M's", k: ["m and m", "mms"] },
          { c: "Butterfinger", k: ["butterfinger"] },
          { c: "Skittles", k: ["skittle"] },
          { c: "Starburst", k: ["starburst"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 6, 6, 7],
      },
    ],
  },
  {
    num: 15,
    quizId: "feud-8-15-26",
    live: "2026-08-15",
    dateLabel: "August 15, 2026",
    sunday: false,
    prompts: [
      {
        q: "Name the first thing people do when the wifi goes out.",
        answers: [
          { c: "Restart the router", k: ["restart", "unplug", "router", "reboot"] },
          { c: "Check their phone", k: ["check phone", "is it just me", "check other devices"] },
          { c: "Switch to data", k: ["data", "hotspot"] },
          { c: "Panic", k: ["panic", "freak out"] },
          { c: "Call the provider", k: ["call", "comcast", "xfinity", "provider"] },
          { c: "Wait it out", k: ["wait"] },
          { c: "Go outside", k: ["outside", "read a book", "talk to family"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 6, 6],
      },
      {
        q: "Name a sandwich everyone has an opinion on.",
        answers: [
          { c: "Grilled cheese", k: ["grilled cheese"] },
          { c: "PB&J", k: ["pb and j", "peanut butter and jelly", "pbj"] },
          { c: "BLT", k: ["blt"] },
          { c: "Philly cheesesteak", k: ["cheesesteak", "philly"] },
          { c: "Tuna salad", k: ["tuna"] },
          { c: "A club", k: ["club"] },
          { c: "Reuben", k: ["reuben"] },
          { c: "Egg salad", k: ["egg salad"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7],
      },
      {
        q: "Name something that makes waiting rooms miserable.",
        answers: [
          { c: "The endless wait", k: ["wait", "waiting", "how long it takes"] },
          { c: "People coughing", k: ["cough", "sick people", "germs"] },
          { c: "Uncomfortable chairs", k: ["chair", "seats"] },
          { c: "Loud TV", k: ["tv", "daytime tv"] },
          { c: "Old magazines", k: ["magazine"] },
          { c: "Screaming kids", k: ["kid", "screaming", "crying"] },
          { c: "The paperwork", k: ["paperwork", "forms", "clipboard"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6],
      },
      {
        q: "Name something people keep in the car 'just in case'.",
        answers: [
          { c: "An umbrella", k: ["umbrella"] },
          { c: "Jumper cables", k: ["jumper cable", "jump starter"] },
          { c: "A blanket", k: ["blanket"] },
          { c: "Water bottles", k: ["water"] },
          { c: "A phone charger", k: ["charger"] },
          { c: "First aid kit", k: ["first aid"] },
          { c: "Snacks", k: ["snack", "granola bar"] },
          { c: "A spare tire", k: ["spare", "tire"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7],
      },
      {
        q: "Name a dance move everyone knows.",
        answers: [
          { c: "The Macarena", k: ["macarena"] },
          { c: "The Cha Cha Slide", k: ["cha cha"] },
          { c: "The Electric Slide", k: ["electric slide"] },
          { c: "The YMCA", k: ["ymca"] },
          { c: "The Floss", k: ["floss"] },
          { c: "The Moonwalk", k: ["moonwalk"] },
          { c: "The Twist", k: ["twist"] },
          { c: "The Cupid Shuffle", k: ["cupid"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7],
      },
    ],
  },
  {
    num: 16,
    quizId: "feud-8-16-26",
    live: "2026-08-16",
    dateLabel: "August 16, 2026",
    sunday: false,
    prompts: [
      {
        q: "Name something people always burn when cooking.",
        answers: [
          { c: "Toast", k: ["toast"] },
          { c: "Garlic", k: ["garlic"] },
          { c: "Popcorn", k: ["popcorn"] },
          { c: "Rice", k: ["rice"] },
          { c: "Cookies", k: ["cookie"] },
          { c: "Bacon", k: ["bacon"] },
          { c: "Grilled cheese", k: ["grilled cheese"] },
          { c: "Themselves", k: ["myself", "my hand", "fingers"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7],
      },
      {
        q: "Name a reason people stay up way too late.",
        answers: [
          { c: "Scrolling their phone", k: ["phone", "scroll", "tiktok", "instagram", "doomscroll"] },
          { c: "One more episode", k: ["episode", "netflix", "binge", "show"] },
          { c: "Gaming", k: ["game", "gaming", "video games"] },
          { c: "Overthinking", k: ["overthink", "thinking", "cant shut my brain off", "anxiety"] },
          { c: "Reading", k: ["read", "book"] },
          { c: "Talking to someone", k: ["talk", "texting someone", "facetime"] },
          { c: "Revenge bedtime procrastination", k: ["me time", "finally have free time"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 5, 5, 6],
      },
      {
        q: "Name something free that people get way too excited about.",
        answers: [
          { c: "Free samples", k: ["sample"] },
          { c: "Free food", k: ["food", "pizza at work", "donuts"] },
          { c: "Free wifi", k: ["wifi"] },
          { c: "Free refills", k: ["refill"] },
          { c: "Free shipping", k: ["shipping"] },
          { c: "Hotel breakfast", k: ["hotel breakfast", "continental"] },
          { c: "Free t-shirts", k: ["shirt", "t shirt", "merch"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 6, 6],
      },
      {
        q: "Name an app on basically everyone's phone.",
        answers: [
          { c: "Instagram", k: ["instagram", "insta"] },
          { c: "YouTube", k: ["youtube"] },
          { c: "TikTok", k: ["tiktok"] },
          { c: "Maps", k: ["maps", "google maps"] },
          { c: "Spotify", k: ["spotify", "music"] },
          { c: "Facebook", k: ["facebook"] },
          { c: "A weather app", k: ["weather"] },
          { c: "WhatsApp", k: ["whatsapp"] },
          { c: "Candy Crush", k: ["candy crush"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 8],
      },
      {
        q: "Name something families argue about in the car.",
        answers: [
          { c: "Directions", k: ["direction", "which way", "missed the exit", "gps"] },
          { c: "The music", k: ["music", "radio", "song", "aux"] },
          { c: "Driving too fast", k: ["speed", "driving", "slow down", "backseat driver"] },
          { c: "The temperature", k: ["temperature", "ac", "too hot", "too cold", "windows"] },
          { c: "Where to eat", k: ["where to eat", "food", "restaurant"] },
          { c: "Are we there yet", k: ["are we there"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5],
      },
    ],
  },
  {
    num: 17,
    quizId: "feud-8-17-26",
    live: "2026-08-17",
    dateLabel: "August 17, 2026",
    sunday: false,
    prompts: [
      {
        q: "Name a food people pretend to like.",
        answers: [
          { c: "Caviar", k: ["caviar"] },
          { c: "Oysters", k: ["oyster"] },
          { c: "Kale", k: ["kale"] },
          { c: "Sushi", k: ["sushi"] },
          { c: "Blue cheese", k: ["blue cheese"] },
          { c: "Olives", k: ["olive"] },
          { c: "Kombucha", k: ["kombucha"] },
          { c: "Tofu", k: ["tofu"] },
          { c: "Truffle anything", k: ["truffle"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 7, 7, 8],
      },
      {
        q: "Name something at every county fair.",
        answers: [
          { c: "The Ferris wheel", k: ["ferris"] },
          { c: "Funnel cake", k: ["funnel"] },
          { c: "Corn dogs", k: ["corn dog"] },
          { c: "Farm animals", k: ["cow", "pig", "petting zoo", "livestock"] },
          { c: "Carnival games", k: ["game", "ring toss", "win a goldfish"] },
          { c: "Cotton candy", k: ["cotton candy"] },
          { c: "Rickety rides", k: ["ride", "tilt a whirl"] },
          { c: "Giant stuffed prizes", k: ["prize", "stuffed animal"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7],
      },
      {
        q: "Name what people do the second the plane lands.",
        answers: [
          { c: "Turn off airplane mode", k: ["airplane mode", "phone on", "check phone", "check messages"] },
          { c: "Stand up immediately", k: ["stand"] },
          { c: "Unbuckle early", k: ["unbuckle", "seatbelt"] },
          { c: "Grab their bag", k: ["bag", "overhead bin"] },
          { c: "Text 'just landed'", k: ["just landed", "text family"] },
          { c: "Clap", k: ["clap"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 5, 5],
      },
      {
        q: "Name a superpower people wish they had.",
        answers: [
          { c: "Flying", k: ["fly", "flight"] },
          { c: "Invisibility", k: ["invisib"] },
          { c: "Teleportation", k: ["teleport"] },
          { c: "Mind reading", k: ["mind", "read minds", "telepathy"] },
          { c: "Time travel", k: ["time"] },
          { c: "Super strength", k: ["strength", "strong"] },
          { c: "Healing", k: ["heal"] },
          { c: "Super speed", k: ["speed", "fast"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 6, 6, 7],
      },
      {
        q: "Name something in every office breakroom.",
        answers: [
          { c: "The coffee maker", k: ["coffee", "keurig", "coffee pot"] },
          { c: "A microwave", k: ["microwave"] },
          { c: "The fridge", k: ["fridge", "refrigerator"] },
          { c: "A water cooler", k: ["water cooler", "water"] },
          { c: "Vending machine", k: ["vending"] },
          { c: "Passive-aggressive notes", k: ["note", "sign", "please wash your dishes"] },
          { c: "Someone's leftover donuts", k: ["donut", "stale donuts", "leftover cake"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6],
      },
    ],
  },
  {
    num: 18,
    quizId: "feud-8-18-26",
    live: "2026-08-18",
    dateLabel: "August 18, 2026",
    sunday: false,
    prompts: [
      {
        q: "Name something people do to look busy at work.",
        answers: [
          { c: "Type furiously", k: ["type", "typing", "keyboard"] },
          { c: "Stare at a spreadsheet", k: ["spreadsheet", "excel", "stare at the screen"] },
          { c: "Walk around with papers", k: ["paper", "walk with a folder", "walk fast"] },
          { c: "Answer 'emails'", k: ["email"] },
          { c: "Sit in meetings", k: ["meeting"] },
          { c: "Wear headphones", k: ["headphones"] },
          { c: "Furrow their brow", k: ["serious face", "frown", "concentrate face"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6],
      },
      {
        q: "Name a topping on a loaded baked potato.",
        answers: [
          { c: "Cheese", k: ["cheese", "cheddar"] },
          { c: "Bacon", k: ["bacon", "bacon bits"] },
          { c: "Sour cream", k: ["sour cream"] },
          { c: "Butter", k: ["butter"] },
          { c: "Chives", k: ["chive", "green onion", "scallion"] },
          { c: "Ranch", k: ["ranch"] },
          { c: "Broccoli", k: ["broccoli"] },
          { c: "Salt and pepper", k: ["salt", "pepper"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 6, 7],
      },
      {
        q: "Name a noise from the neighbors that drives people crazy.",
        answers: [
          { c: "Barking dogs", k: ["dog", "bark"] },
          { c: "Loud music", k: ["music", "bass", "party"] },
          { c: "Stomping upstairs", k: ["stomp", "walking", "footsteps", "upstairs"] },
          { c: "Lawn mower at 7am", k: ["mower", "lawn", "leaf blower"] },
          { c: "Power tools", k: ["drill", "tools", "construction", "hammering"] },
          { c: "Screaming kids", k: ["kid", "screaming"] },
          { c: "Arguing", k: ["argue", "fighting", "yelling"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6],
      },
      {
        q: "Name a movie almost everyone has seen.",
        answers: [
          { c: "Titanic", k: ["titanic"] },
          { c: "The Wizard of Oz", k: ["wizard of oz"] },
          { c: "Star Wars", k: ["star wars"] },
          { c: "The Lion King", k: ["lion king"] },
          { c: "Home Alone", k: ["home alone"] },
          { c: "Jurassic Park", k: ["jurassic"] },
          { c: "Shrek", k: ["shrek"] },
          { c: "Frozen", k: ["frozen"] },
          { c: "Forrest Gump", k: ["forrest", "gump"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 7, 7, 8, 8],
      },
      {
        q: "Name something people save for a special occasion but never use.",
        answers: [
          { c: "The good china", k: ["china", "fancy dishes", "good plates"] },
          { c: "Candles", k: ["candle"] },
          { c: "Fancy clothes", k: ["dress", "suit", "outfit", "clothes"] },
          { c: "Nice perfume", k: ["perfume", "cologne"] },
          { c: "Expensive wine", k: ["wine", "champagne"] },
          { c: "Gift cards", k: ["gift card"] },
          { c: "The good towels", k: ["towel"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6],
      },
    ],
  },
  {
    num: 19,
    quizId: "feud-8-19-26",
    live: "2026-08-19",
    dateLabel: "August 19, 2026",
    sunday: false,
    prompts: [
      {
        q: "Name something people google instead of asking a doctor.",
        answers: [
          { c: "Their symptoms", k: ["symptom", "whats wrong with me", "diagnosis"] },
          { c: "What a rash is", k: ["rash", "skin"] },
          { c: "Headache causes", k: ["headache", "migraine"] },
          { c: "Home remedies", k: ["remedy", "home remedies", "natural cures"] },
          { c: "Medication side effects", k: ["side effect", "medication"] },
          { c: "Is my bone broken", k: ["broken", "sprained"] },
          { c: "How much sleep they need", k: ["sleep"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 6, 6],
      },
      {
        q: "Name a fast food chain with a cult following.",
        answers: [
          { c: "Chick-fil-A", k: ["chick fil a", "chickfila"] },
          { c: "In-N-Out", k: ["in n out", "innout"] },
          { c: "McDonald's", k: ["mcdonald"] },
          { c: "Whataburger", k: ["whataburger"] },
          { c: "Five Guys", k: ["five guys"] },
          { c: "Popeyes", k: ["popeye"] },
          { c: "Culver's", k: ["culver"] },
          { c: "Wendy's", k: ["wendy"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7],
      },
      {
        q: "Name what people do when their favorite song comes on.",
        answers: [
          { c: "Turn it up", k: ["turn it up", "volume", "crank"] },
          { c: "Sing along", k: ["sing", "belt", "scream the lyrics"] },
          { c: "Dance", k: ["dance", "car dance"] },
          { c: "Say 'this is my song!'", k: ["my song", "this is my jam"] },
          { c: "Air drum", k: ["air drum", "air guitar", "steering wheel drums"] },
          { c: "Roll the windows down", k: ["window"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 5, 5],
      },
      {
        q: "Name something people forget seconds after being told.",
        answers: [
          { c: "Names", k: ["name"] },
          { c: "Directions", k: ["direction"] },
          { c: "What to buy at the store", k: ["grocery", "what to get", "the one thing"] },
          { c: "Birthdays", k: ["birthday"] },
          { c: "Phone numbers", k: ["number"] },
          { c: "Passwords", k: ["password"] },
          { c: "Where they put their keys", k: ["keys"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 6, 6],
      },
      {
        q: "Name a dessert on every diner menu.",
        answers: [
          { c: "Pie", k: ["pie", "apple pie", "cherry pie"] },
          { c: "Milkshakes", k: ["milkshake", "shake"] },
          { c: "Cheesecake", k: ["cheesecake"] },
          { c: "Ice cream sundae", k: ["sundae", "ice cream"] },
          { c: "Rice pudding", k: ["rice pudding"] },
          { c: "A brownie", k: ["brownie"] },
          { c: "Jell-O", k: ["jello"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 5, 5, 6, 6],
      },
    ],
  },
  {
    num: 20,
    quizId: "feud-8-20-26",
    live: "2026-08-20",
    dateLabel: "August 20, 2026",
    sunday: false,
    prompts: [
      {
        q: "Name something people do during commercials.",
        answers: [
          { c: "Check their phone", k: ["phone", "scroll"] },
          { c: "Bathroom break", k: ["bathroom", "pee"] },
          { c: "Grab a snack", k: ["snack", "food", "fridge"] },
          { c: "Mute the TV", k: ["mute"] },
          { c: "Channel surf", k: ["flip", "channel"] },
          { c: "Fast forward", k: ["fast forward", "skip"] },
          { c: "Talk about the show", k: ["talk"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 6],
      },
      {
        q: "Name a food that instantly reminds people of summer.",
        answers: [
          { c: "Watermelon", k: ["watermelon"] },
          { c: "Ice cream", k: ["ice cream", "popsicle"] },
          { c: "BBQ", k: ["bbq", "barbecue", "burgers", "grilling"] },
          { c: "Corn on the cob", k: ["corn"] },
          { c: "Hot dogs", k: ["hot dog"] },
          { c: "S'mores", k: ["smore"] },
          { c: "Lemonade", k: ["lemonade"] },
          { c: "Snow cones", k: ["snow cone", "shaved ice"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 7],
      },
      {
        q: "Name something every parent said growing up.",
        answers: [
          { c: "Because I said so", k: ["because i said so"] },
          { c: "We have food at home", k: ["food at home"] },
          { c: "Money doesn't grow on trees", k: ["money", "grow on trees"] },
          { c: "Were you born in a barn?", k: ["barn", "close the door"] },
          { c: "When I was your age...", k: ["when i was your age"] },
          { c: "Ask your mother/father", k: ["ask your"] },
          { c: "Turn off the lights", k: ["lights"] },
          { c: "Don't make me pull over", k: ["pull this car over", "pull over"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7],
      },
      {
        q: "Name a place where time moves slowest.",
        answers: [
          { c: "The DMV", k: ["dmv"] },
          { c: "Waiting rooms", k: ["waiting room", "doctors office"] },
          { c: "Work meetings", k: ["meeting", "work"] },
          { c: "School", k: ["school", "class", "last period"] },
          { c: "The post office line", k: ["post office", "line"] },
          { c: "Church", k: ["church"] },
          { c: "Traffic", k: ["traffic"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 5, 5, 6, 6],
      },
      {
        q: "Name a store people can't leave without overspending.",
        answers: [
          { c: "Target", k: ["target"] },
          { c: "Costco", k: ["costco", "sams"] },
          { c: "Trader Joe's", k: ["trader joe"] },
          { c: "IKEA", k: ["ikea"] },
          { c: "HomeGoods", k: ["homegoods", "tj maxx", "marshalls"] },
          { c: "Sephora", k: ["sephora", "ulta"] },
          { c: "The dollar store", k: ["dollar"] },
          { c: "Whole Foods", k: ["whole foods"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 6, 6, 7],
      },
    ],
  },
  {
    num: 21,
    quizId: "feud-8-21-26",
    live: "2026-08-21",
    dateLabel: "August 21, 2026",
    sunday: false,
    prompts: [
      {
        q: "Name something people practice in the mirror.",
        answers: [
          { c: "Speeches", k: ["speech", "presentation", "toast"] },
          { c: "Arguments", k: ["argument", "comeback", "confrontation"] },
          { c: "Smiling", k: ["smile"] },
          { c: "Asking for a raise", k: ["raise", "quitting", "talk to my boss"] },
          { c: "Dance moves", k: ["dance"] },
          { c: "Pickup lines", k: ["pickup", "flirting"] },
          { c: "Job interview answers", k: ["interview"] },
          { c: "Poses", k: ["pose", "selfie face"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7],
      },
      {
        q: "Name a cereal adults still love.",
        answers: [
          { c: "Cinnamon Toast Crunch", k: ["cinnamon toast"] },
          { c: "Frosted Flakes", k: ["frosted flake"] },
          { c: "Lucky Charms", k: ["lucky charm"] },
          { c: "Cheerios", k: ["cheerio", "honey nut"] },
          { c: "Fruity Pebbles", k: ["fruity pebble"] },
          { c: "Cap'n Crunch", k: ["captain crunch", "capn crunch"] },
          { c: "Reese's Puffs", k: ["reese"] },
          { c: "Froot Loops", k: ["froot loop", "fruit loop"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7],
      },
      {
        q: "Name something that makes a hotel feel fancy.",
        answers: [
          { c: "Fluffy robes", k: ["robe", "bathrobe"] },
          { c: "Room service", k: ["room service"] },
          { c: "A nice pool", k: ["pool", "rooftop pool"] },
          { c: "The big white bed", k: ["bed", "pillows", "sheets"] },
          { c: "Free breakfast", k: ["breakfast"] },
          { c: "A fancy lobby", k: ["lobby", "chandelier", "marble"] },
          { c: "The minibar", k: ["minibar"] },
          { c: "Turndown service", k: ["turndown"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 7, 7],
      },
      {
        q: "Name what people do when they see a dog in public.",
        answers: [
          { c: "Ask to pet it", k: ["pet", "can i pet"] },
          { c: "Smile", k: ["smile"] },
          { c: "Baby talk to it", k: ["baby voice", "baby talk", "talk to it", "whos a good boy"] },
          { c: "Point it out", k: ["point", "look a dog", "tell whoever theyre with"] },
          { c: "Stare at it", k: ["stare", "watch it"] },
          { c: "Take a picture", k: ["picture", "photo"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5],
      },
      {
        q: "Name the bill people hate paying most.",
        answers: [
          { c: "Rent or mortgage", k: ["rent", "mortgage"] },
          { c: "Car insurance", k: ["insurance", "car insurance"] },
          { c: "Electric", k: ["electric", "utilities", "power"] },
          { c: "Internet", k: ["internet", "cable", "wifi"] },
          { c: "Medical bills", k: ["medical", "hospital", "doctor"] },
          { c: "Taxes", k: ["tax"] },
          { c: "Phone bill", k: ["phone"] },
          { c: "Subscriptions", k: ["subscription", "streaming", "netflix"] },
        ],
        house: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7],
      },
    ],
  },
];
